### ISSUE TITLE
[In-game UI] Main menu UI layout is corrupted

### ISSUE THREAD

**Issue by MasterMann** [Facepunch/sbox-issues#1]
(I'll repost here, since this is probably a better place for reports)

Screenshot:
![изображение](https://user-images.githubusercontent.com/15061140/115385601-fcbe2c80-a1e0-11eb-9e1c-4c8c4170d69b.png)

Log.log: [Pastebin (pass: s&box)](https://pastebin.com/hyXAbffY)

DxDiag: [Pastebin (pass: s&box)](https://pastebin.com/hKhTqLGf)

Attempted mitigations:
- Reinstall (including onto different partitions)
- Restart game/PC
- Launch with tools

**Comment by garrynewman** [comment]
Thanks - diagnosing now. I just pushed an update, can you upload the log when you try that new version please, it'll have a bit more useful information.

**Comment by MasterMann** [comment]
Uploaded new log: [https://pastebin.com/N3LqZ36E](pastebin)

Same password.

**Comment by MasterMann** [comment]
It might be related to comma vs dot parsing due to regional formats in Windows, I think.

**Comment by garrynewman** [comment]
Yeah that looks like what it is, I'll get a fix soon

**Comment by garrynewman** [comment]
Alright fix submitted, give it 5 mins and try again

**Comment by MasterMann** [comment]
Can confirm, issue fixed.
