### ISSUE TITLE
Can not use multi-dimensional arrays, constructor is null

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#100]
When trying to create a multi-dimensional array an error occurs saying it can't resolve the constructor.

![image](https://user-images.githubusercontent.com/1388267/117036442-59e7d100-acfd-11eb-9f49-4ebb6a77846b.png)
(Can't copy from console)

Simply doing the following will trigger the error:

```csharp
var array = new byte[1,3];
```

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
