### ISSUE TITLE
Minor spelling error in the Dev Login page

### ISSUE THREAD

**Issue by MrARM** [Facepunch/sbox-issues#1000]
**Describe the bug**
There's a very minor spelling error in a link

**To Reproduce**
![image](https://user-images.githubusercontent.com/8205849/135006766-a28b5436-e1e2-4e22-8524-7bfff22ad6fe.png)

1. Hover over or click "try to recover your account"
2. Steam is spelled "Stean" in the URL

**Expected behavior**
Should be spelled Steam

**Screenshots**
Posted one in the to reproduce as well
![image](https://user-images.githubusercontent.com/8205849/135006738-d56136bb-c697-4f31-a48d-b339b2b36ebf.png)

**Additional context**
Found on https://sbox.facepunch.com/dev/.login

**Comment by RegiSimkus** [comment]
Would it not make more sense to send you to
https://help.steampowered.com/wizard/HelpWithLoginInfo?accountsearch=1&issueid=406
