### ISSUE TITLE
Unable to upload .zip files to FP backend, causing ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by eagleonedevteam** [Facepunch/sbox-issues#1002]
**Describe the bug**

Unable to upload any map in a .zip package to the FP backend that is above 1.2 GB

**To Reproduce**

1. Go to https://sbox.facepunch.com/*dev/*map_name
2. Click on 'Downloads'
3. Make sure download type is set to 'Zip'
4. Try to upload new file, or override previously existing one

**Expected behavior**

What should happen: Previously anything that was submitted would upload as long as it was under the 1.1 GB threshold. Anything over this size limit would fail - but this was a known limit.

**Screenshots**

![image](https://user-images.githubusercontent.com/70182442/135029805-b0b1c48d-19f1-422f-87b1-5aa7eaa00521.png)

**Additional context**

This was a previous issue #818 that was resolved, and has popped up again with our larger maps being uploaded.

We want to upload our 2nd Gr& Prix map Neotokyo but have hit this limit since it is full of custom assets.

**Comment by garrynewman** [comment]
This isn't going to be solved any time soon, but I do intend to let you upload much bigger files.. My best advice would be to try to get the size down for now if you can.
