### ISSUE TITLE
WebGL Integration

### ISSUE THREAD

**Issue by L1lith** [Facepunch/sbox-issues#1005]
**What can't you do?**
Host Servers via WebGL

**How would you like it to work?**
Basically you could have a website act like a server. When people enter the website it could have players authenticate through steam online, then render the game via WebGL. This would mean people could log into servers instantly via a link on any machine, through the browser without having to install the game. 

**What have you tried?**
I have been trying to figure out the best WebGL based game engine. There's not very much out there in the web dev ecosphere, and especially not with an integrated editor. If something like this were implemented it would help games whose portability is cutting edge, and really help bring 3d into full force in the browser ecosystem. 
Giving browser support is great because it reduces the barrier to entry to play the game, and it can act as a security layer as browsers are heavily sandboxed. It also could allow developers to tap into the JS ecosystem and potentially the browser APIs as well (free basically universal video encoding anyone?)

**Additional context**
N/A

**Comment by Kaydax** [comment]
What?

**Comment by samdisk11** [comment]
This is not possible because s&box is using source 2, and there is no web builds of source 2, only windows/linux/mac native builds.

and even then it will be VERY LAGGY as you will need a powerful pc just to run the base game on a website (let alone any addons said server will have)

**Comment by MrARM** [comment]
Like @samdisk11 said, you'd have to rewrite everything, for s&box, it's just not practical.

**Comment by Rohansi** [comment]
Realistically not going to happen. There are others that do this already.

https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_web.html

https://docs.unity3d.com/Manual/webgl-building.html

**Comment by garrynewman** [comment]
Yep sorry this isn't gonna happen any time soon
