### ISSUE TITLE
ParticleEditor: Screen Space Effect Particles appear blurry 

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#1006]
When creating "Screen Space Effect"s they appear blurry in both the viewport and ingame, there is no option to change the filtering or appearence inside the particle editor. It would be nice if they appeared not blurry and low res (I assume this is due to VR settings)

When you enable "Screen Space Effect" it also enables a VR HMD template it would be nice if it was an option to turn this on and off. (if not possible off?)

What it looks like.
![image](https://user-images.githubusercontent.com/8184184/135172018-3d715503-7478-4c72-b398-1303ca0eb8ff.png)

What the sprite looks like.
![image](https://user-images.githubusercontent.com/8184184/135172043-746d6841-d0ed-40f3-8560-b2862a8cdbbe.png)

However setting "vr_translucent_screen_space_downres" to 1 removes the downres blur and makes them appear clear.
(not sure what else this effects changing this to 1)
![image](https://user-images.githubusercontent.com/8184184/135173011-9bb26f26-64a1-4fc1-8b9e-9229e24d934e.png)

[Change test using this effect](https://files.facepunch.com/louie/1b2811b1/screen_particle.vpcf)

**Comment by justynboi** [comment]
Go under "View" and uncheck "Show Screenspace Overlay"

![image](https://user-images.githubusercontent.com/17112771/135178301-0e332698-de4a-41ed-899d-8ee7788e18d8.png)
