### ISSUE TITLE
Give us Access to the Change Level Command

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#1010]
**What can't you do?**
Speed-Dial had a map vote system that relied on the use of the `ConsoleSystem` class and the `changelevel` command. Due to recent changes we no longer have access to this command.

**How would you like it to work?**
Ideally there'd be some sort of static function we could call to change the map given a provided string. Otherwise simply re-enabling use of the `changelevel` command in `ConsoleSystem` would work just as well.

**What have you tried?**
I've tried looking into the s&box API but have found nothing exposed that we can use to do something equivalent.

**Comment by DoctorGurke** [comment]
#999
