### ISSUE TITLE
Orthographic View and Camera Alignment in Model Doc

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#1013]
**What can't you do?**
Use an orthographic camera in model doc, and snap the to different axis 

**How would you like it to work?**
Orthographic View:
Probably a toggle where the viewmodel mode is.

Camera Alignment :
Similar to blender 2.8 where there's an axis gimble in the top right corner
![image](https://user-images.githubusercontent.com/55055481/135449036-0740da08-a516-4aee-8a18-69c31b5fa755.png)

It could be just as simple as a dropdown in the camera mode menu group

**What have you tried?**
Manually positioning yourself on to a certain axis is annoying

**Comment by aylaylay** [comment]
I've just added these modes, the picking will be slightly off so I need to fix that.

**Comment by Jake-NSW** [comment]
Great work so far its super handy, although I think there is a bug where if you compile the model while in one of the orthographic views, the model goes all funky

Compiled without being in the orthographic view
![image](https://user-images.githubusercontent.com/55055481/135747681-ac8de6a8-77be-4746-9f4f-1c362face3c7.png)

Compiled while being in the orthographic view
![image](https://user-images.githubusercontent.com/55055481/135747698-4a249f5c-535a-45ac-a436-681a42e64638.png)

Seems to be only a cosmetic thing in model doc though cause the funky model doesnt show up in game

**Comment by gabengaGamer** [comment]
Orthographic View would look great in a hammer editor

**Comment by Jake-NSW** [comment]
It already is in hammer?
![image](https://user-images.githubusercontent.com/55055481/135837244-773149e3-4fde-4c0c-bd4c-e46d7b04230d.png)

**Comment by gabengaGamer** [comment]
3D Orthographic

**Comment by aylaylay** [comment]
I have pushed some improvements and a possible fix, let me know if it fixes your issue when it hits steam.

**Comment by Jake-NSW** [comment]
Works perfectly now
