### ISSUE TITLE
Expose all keys to developers without the use of binds, or implement automatic bind loading per gamemode

### ISSUE THREAD

**Issue by Fires1** [Facepunch/sbox-issues#1016]
**What can't you do?**
Easily manage custom keybinds outside of the scope of the API's currently limited input enum in order for gamemodes to allow additional keys without forcing players to continously fuck around in the console to rebind their keys or create config files or specific gamemodes.

**How would you like it to work?**
The quick and dirty way would be for gamemodes to have a method to bind console commands to certain keys, then within the S&box settings menu, expose options for players to easily rebind these keys, then take those console binds and just automatically save them to a config file, that way when you load a gamemode, it can automatically run your saved config file and load all of your binds immediately.

Say:
`RegisterCommandKey("gm_fancyability", "Fancy Ability", Input.X)`
Then within the settings menu, once loaded into that game, you would see an entry for "Fancy Ability" that is *by default* set to X.
As I mentioned before, you could realistically just have this be an automatic binding system, you can keep the current console command implements of `+gm_fancyability` and `-gm_fancyability` for a quick and dirty solution. 
The primary 'feature' implementation would be having the API expose a method to add an option, then display the options, then to also automatically save and load a player's keybindings for a specific gamemode.

The ideal way, would allow for an extension of the current API's `Input` commands, that allow developers to pass any key and use the current existing API methods for input. Including an expansion of the Input enum by having much more keys to pick from outside of the default. I understand there are likely restrictions and complications to this, which I why the proposed idea of using the existing bind system may be a better solution.

I'm not educated enough on Input systems to fully propose a foolproof system, but at the end of the day, I think even just serializing every `bind` entry and loading that upon gamemode load may be useful in other contexts as well. Perhaps I want to move my `iv_use` to another key but only in that gamemode. Having S&box do the bulk of this work means its accessible and players don't have to fuck around with doing configs themselves. Win-win.

**What have you tried?**
Using `Console.Run` to bind keys before it was disabled in a custom key binding system.

**Additional context**

FiveM, the GTA5 modding platform, has a system similar to this in terms of adding custom keybinds, which looks like this in game:

![Image of FiveM's setting menu](https://i.imgur.com/yF1rCJ6.png)

They expose a `RegisterKeyMapping` native, which you can find [documentation on usage at this link](https://docs.fivem.net/natives/?_0xD7664FD1).

**Comment by DoctorGurke** [comment]
#196

**Comment by Fires1** [comment]
Ah, I know an okay workaround, nevermind.
