### ISSUE TITLE
Crash when setting EntityName

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#102]
**Describe the bug**

S&box crashes when setting an Entity's EntityName, no exception or logs.

```
partial class BugtestPlayer : BasePlayer
{
	public BugtestPlayer()
	{
		Log.Info("Bugtest Player");
	}

	public override void Respawn()
	{
		SetModel("models/citizen/citizen.vmdl"); // If you have your own model, you can place it here instead.
		Controller = new WalkController();
		Animator = new StandardPlayerAnimator();
		Camera = new FirstPersonCamera();
		EnableAllCollisions = true;
		EnableDrawing = true;
		EnableHideInFirstPerson = true;
		EnableShadowInFirstPerson = true;
		base.Respawn();
	}

	protected override void Tick()
	{
		base.Tick();

		if (IsClient)
		{
			return;
		}

		if (Input.Pressed(InputButton.Slot1))
		{
			var ent = new CustomEntity();
			ent.EntityName = "Hello";
		}
	}

}
```

```
public partial class CustomEntity : Entity
{
}
```

**To Reproduce**

1. Create a new class inheriting Entity
2. Create a new instance of that entity on server
3. Set the entity's EntityName to something random
4. Game will crash

**Expected behavior**

Game doesn't crash or tells me not to change entity name or similar

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by cr4yz** [comment]
Fixed!
