### ISSUE TITLE
Net: Lists of Assets & BaseNetworkables don't network to the client

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#1021]
Gonna move this from the Discord's #help channel otherwise it's gonna get lost in the void.

![image](https://user-images.githubusercontent.com/22372616/135639898-acedf635-512e-4ea3-96ac-40d4e7a575ee.png)

```csharp
[Library( "item" ), AutoGenerate]
public partial class Item : Asset
{
        [Property]
        public Color SomeColor { get; set; }
}

public partial class InventoryComponent : EntityComponent
{
	[Net]
	public List<Item> Items { get; protected set; }

        public void DebugPrint()
        {
	        var position = Host.IsServer ? new Vector2( 100, 100 ) : new Vector2( 500, 100 );
        
	        string build = Host.IsServer ? "Server:" : "Client:";
	        foreach ( var item in Items )
		        build += $"\nItem: {item}";
        
	        DebugOverlay.ScreenText( position, 0, Color.White, build, 0.05f );
        }
}
```
I tried this with a List of BaseNetworkables, didn't work with that either. list of ints is fine as per the net-lab.

**Comment by DevulTj** [comment]
Initial update is good. But any writes are still not being retrieved on the client.

![image](https://user-images.githubusercontent.com/22372616/135842905-821358c9-7128-4923-b07a-a729c350a9cb.png)

After removing 2 items from this List

![sbox_MXnpO2jOpy](https://user-images.githubusercontent.com/22372616/135842948-08854ce2-36a1-4dbe-97e8-a92889cb5e28.png)

**Comment by garrynewman** [comment]
Hmm this is working for me locally

**Comment by DevulTj** [comment]
Ok I've figured what the issue is (I think).

In my Player, I had a [Net] field that pointed to the Component that was created in the Player's constructor.

```csharp
[Net] public InventoryComponent Pocket { get; set; }
...
public Player( Client cl ) : this()
{
    Pocket = Components.GetOrCreate<InventoryComponent>();
}
...
public override void Simulate( Client cl )
{
    Pocket?.DebugPrint();
}
```
I was then outputting shit through Pocket?.DebugPrint() with the code shown above in my original post. Server's version was fine. Client's version stopped receiving any updates, so it's probably unlinked somehow.

I changed my debug print code to run `Components.Get<InventoryComponent>()` instead of using the cached property and shit's working again. I assume this isn't a solid solution though.

**Comment by garrynewman** [comment]
Hmm, maybe I should stop components being able to be networked outside of being a component?

**Comment by DevulTj** [comment]
Probably worth it, yeah.

> In your case I don't see why it's a component if you're accessing it like that. You'd make something a component if you don't know whether you're going to have it or not. If it's hard coded I'd just make it a regular BaseNetworkable.

It's only hard coded for the Player. I wanna be able to use it on other entities too in the future, for containers, etc

**Comment by DevulTj** [comment]
I'll follow up on the new issue. Call this one solved ^^

**Comment by Nowp** [comment]
I still have the issue
My List of BaseNetworkable is instantiated clientside but the content is not mirrored.
It seems to happen with every List of classes extending BaseNetworkable

**Comment by DevulTj** [comment]
Show code
