### ISSUE TITLE
Less annoying scrolling for the Asset Browser in Hammer

### ISSUE THREAD

**Issue by litevxx** [Facepunch/sbox-issues#1025]
Scrolling up in the Asset Browser in Hammer can be very confusing (especially in small view) as it jumps up several rows even when scrolling slightly, sometimes completely skipping past assets as the asset browser is often kept at a very small size in Hammer.

https://streamable.com/pt7fwi

Adding smooth scrolling would help (similar to Google Chrome), or at the very least decreassing the amount it scrolls.

**Comment by aylaylay** [comment]
I've added an option for "free scroll" which scrolls at a small interval instead of scrolling by each item.

I could do smooth scrolling at some point but this should remove most of the annoyance.

**Comment by litevxx** [comment]
Free scroll is way too slow at most sizes
https://streamable.com/g4qmem
