### ISSUE TITLE
Expose list of attachments for model

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#103]
**What can't you do?**

Trying to loop through all attachments via code to find the nearest one to snap to, to do this now I have to know the name of the attachments and call GetAttachment for each one separately.

**How would you like it to work?**

Model could have a list of attachments, each attachment shows name, relative origin/rotation, weight, and bone

**Comment by aylaylay** [comment]
I have added GetAttachmentName and AttachmentCount

**Comment by cr4yz** [comment]
Perfect, tested and working.  Thanks!
