### ISSUE TITLE
`Client.SetValue` network serialization bug

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1032]
**Describe the bug**
The `Client.SetValue` does not work with `bool`.
Regarding <https://github.com/Facepunch/sbox-issues/discussions/1026#discussioncomment-1420657>

**To Reproduce**

Call `Client.SetValue("test", true)` on the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/11843790/135752755-193ba138-6217-46a4-9da0-de5b5dbcefbd.png)
and
![image](https://user-images.githubusercontent.com/11843790/135752815-2fb03205-0533-4d8c-9155-b7f7764b591b.png)

**Additional context**
Issue does not appear if using `Client.SetInt/Client.GetInt` (and manually casting a bool)

**Comment by garrynewman** [comment]
Should be fixed in next build
