### ISSUE TITLE
Hammer Crash When Clicking Outliner Pane With Selected Vertex/Edge/Face

### ISSUE THREAD

**Issue by WYVERN2742** [Facepunch/sbox-issues#1033]
**Describe the bug**
Hammer crashes when clicking the outliner pane while a vertex, edge, or face, is selected.

**To Reproduce**

1. Create a mesh
2. Select a vertex with the vertex tool
3. Right-click the outliner pane
4. Hammer Crashes

**Expected behavior**
Outliner menu shows up as ususal

**Screenshots**

![crash](https://user-images.githubusercontent.com/35181365/135757473-2e4f9433-1916-4999-b4ee-4f47766e3987.gif)

---

**Windows:** Version 10.0.19043 Build 19043
**Build:** 7469882

**Comment by aylaylay** [comment]
Should be fixed when the game next updates.

**Comment by WYVERN2742** [comment]
Confirmed fixed in game 👍
