### ISSUE TITLE
Maximum Renderable Dynamic Spot/Point Lights Controllable Via Convar

### ISSUE THREAD

**Issue by bellum128** [Facepunch/sbox-issues#1035]
**What can't you do?**
It is currently not possible to render more than ~16 projected dynamic lights at a time, as referred to in #497, including player spawned lamps, map lights, and player flashlights combined. There is a similar limit on point based lights, which I have found to be ~128 (though there appears to be some interplay between the two).

**How would you like it to work?**
I propose a new r_ convar to control the maximum amount of renderable spot/point lights in view. I understand that there needs to be a ***default*** limit for this, however the user should be able to override this if they wish, considering their specific system, use case, and performance tradeoffs that they wish to give.

**What have you tried?**
I have tried searching through the convar list for a suitable solution, to no avail.

**Additional context**
I feel strongly about this issue on a fundamental/generic level. Users should be trusted to have control over render limits as visible and critical as this with respect to the performance tradeoffs they are willing to give. If I want to set a lamp render limit to 9001, spawn 9001 lamps, and get 1 frame per 10 seconds, I should have the choice to do so. *My* actual *realistic* use case is creating complex stage designs, synced to external lighting controllers, and explorable in real time, for which many dynamic lights are a necessity. I believe these types of limits are also noticeable in many other realistic use cases as well, and it would be highly ideal for them to be overridable.

I have created this issue separate from closed issue #497, as this is a proposal for a new set of convars, rather than a bug callout as that issue was. May also be distantly related to #537, though my proposal is more related to granular control over lower level settings such as renderable light count, rather than a full blown graphics menu with higher level settings.

**Comment by ischmal** [comment]
I couldn't agree more. The lack of control over this in particular is totally inconsistent with everything else. 

After all, the game doesn't try to stop you from running an infinite while loop -- something _guaranteed_ to crash the game. But projected textures, which are really not all that expensive on modern hardware, are somehow in need of a hard-coded limit? It just doesn't make sense.

**Comment by handsomematt** [comment]
this isn't how rendering works
