### ISSUE TITLE
A way to automatically assign a component to a property

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#1043]
Instead of doing `Components.Get` all the time, it'd be nice to have a property that gets set appropriately when the component  type is added or removed.

```csharp
[AutoComponent]
public MyComponentName MyComponent { get; }
```

We need to decide the name, comments below please

```
[AutoFill]
[Auto]
[AutoComponent]
[Component]
[FromComponent]
[Get]
[GetComponent]
[AutoGet]
```

**Comment by DevulTj** [comment]
I like this idea, only thing that screams in my head is that AutoComponent or Auto assumes this Component always exists, and I'm not sure that's what you want.

**Comment by TheBerkin** [comment]
I'd like to suggest `[BindComponent]` because it's a binding. It's an unambiguous name and makes the function clear.

**Comment by garrynewman** [comment]
```csharp
[BindComponent]
public InventoryComponent MyComponent { get; }
```

**Comment by DevulTj** [comment]
Works flawlessly, thank you ❤️
