### ISSUE TITLE
`Client.GetInt()` and `Client.GetValue<T>()` error if requesting in early state

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1044]
**Describe the bug**
Currently don't know which sbox build caused this, but it didn't happen yesterday.
`Client.GetInt()` and `Client.GetValue<T>()` returns an error if requesting vars in early state (HUD constructor).

It's not something important as it was dumb doing this that way, now I'm creating a "Connected" ClientRPC to populate the HUD / Scoreboard later on (which solves the problem).

Something I saw was that `Client.ToString()` prints `STEAMID64\` without the client's nickname appended. `IsValid()` returned true on `Client`.

Feel free to close if this is something intended. If so, the error message is a bit confusing.

**To Reproduce**
Call e.g. `Client.GetInt("test")` in the constructor of a HUD (or panel that is created through HUD constructor)

**Screenshots**
![image](https://user-images.githubusercontent.com/11843790/135911840-b6f10ea1-5571-498f-a0e1-2c0cc0b7b9a3.png)

**Comment by garrynewman** [comment]
Fixed
