### ISSUE TITLE
Whitelist `System.Private.CoreLib/System.ValueTuple*`

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#105]
**What can't you do?**
I can't use tuples in C#.

**How would you like it to work?**
I would like all forms of `System.ValueTuple` whitelisted.

**What have you tried?**
```cs
var (a, b) = ("foo", 123);
```

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by TheBerkin** [comment]
It works now, thanks!
