### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by Sl4vP0weR** [Facepunch/sbox-issues#1068]
I want request separation of server & client sides, with executable file, that will host server with selected gamemode.
I think you must allow developers to do these things on the server-side: 
1. Use custom .NET libraries. (This will let to: Create more complex/advanced gamemodes; etc.)
2. Access filesystem. (This will let to: Creating local database; Reading/writing of configuration/translation files; etc.)

I tried to create new AppDomain to load libraries in it, but it didn't compiled, cause is that AppDomain isn't whitelisted. 
Also System.IO.File and System.IO.Directory aren't whitelisted too.

**Comment by Sl4vP0weR** [comment]
> If you want to run random libraries serverside you can modify the access list: https://wiki.facepunch.com/sbox/AccessList There is restricted filesystem access so you can't just read users personal files, read about it here: https://wiki.facepunch.com/sbox/FileSystem
I don't need user's files, I need server files access only.

**Comment by SleepyMode** [comment]
The restriction on .NET libraries and filesystem access are security measures, I honestly don't see Facepunch removing them anytime soon.

**Comment by Sl4vP0weR** [comment]
> The restriction on .NET libraries and filesystem access are security measures, I honestly don't see Facepunch removing them anytime soon.

Not to remove, just let developers more access.
Separate server & client codes is better way for security measures.

**Comment by Sl4vP0weR** [comment]
> If you want to run random libraries serverside you can modify the access list: https://wiki.facepunch.com/sbox/AccessList

I modified access list, but other players when joining still getting error, that something isn't whitelisted

**Comment by Sl4vP0weR** [comment]
Facepunch can make only serverside code folder that will allow developers to use something that not whitelisted, but to use it - you need to start something like S&BoxServer.exe

**Comment by ogniK5377** [comment]
> Facepunch could add something, that will allow developers to ignore accesslist on the serverside(like "only serverside code" folder), but to use it - you need to start something like S&BoxServer.exe

sounds like a good way to get system32 deleted. Server-sided code will have separation at some point. You just need to be patient
