### ISSUE TITLE
Game's Map config not working

### ISSUE THREAD

**Issue by costin88boss** [Facepunch/sbox-issues#1084]
**Describe the bug**
Basically i want to set the map to facepunch.flatgrass but when i go in game and search for the game, the default map is the construct one.

**To Reproduce**

1. Go in game dev settings on the page 
2. Map config
3. put Default map as "facepunch.flatgrass"
4. Check the game in game (wtf)
5. The default map is construct

**Expected behavior**
Default map should be flatgrass

**Screenshots**
![image](https://user-images.githubusercontent.com/42942503/137150327-8b2c8558-0a8a-44c6-bf7e-1e0a8591ff64.png)
![image](https://user-images.githubusercontent.com/42942503/137150386-47b11765-a42f-40c4-a89b-dd5986be8840.png)

**Additional context**

That game is not the disc save icon from the top bar. It is searched. 
Weird is that it doesn't even show the description?

**Comment by garrynewman** [comment]
Try adding `"ident": "yourorgname.rollaball"` to your .addon so when using it locally it knows which gamemode it is

**Comment by costin88boss** [comment]
It already has it. Is it because I put _? Sent from Mail for Windows From: Garry NewmanSent: Wednesday, October 13, 2021 05:19 PMTo: Facepunch/sbox-issuesCc: costin88boss; AuthorSubject: Re: [Facepunch/sbox-issues] Game's Map config not working (#1084) Try adding "ident": "yourorgname.rollaball" to your .addon so when using it locally it knows which gamemode it is—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
