### ISSUE TITLE
Base shader does not work with skinned meshes

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#1087]
**Describe the bug**
Using the base shader or a variation of the base shader on a skinned mesh causes it to jump around between the origin and a projection of where it should be. It looks to be an instancing issue but unsure as of now.

**To Reproduce**
Attach the base shader to any skinned mesh(the citizen model for example)

**Expected behavior**
The mesh should continue to work as normal

**Screenshots**
https://user-images.githubusercontent.com/25727384/137358117-7e8f8b25-fe34-46be-893a-195afc73f571.mp4

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by NotGaylien** [comment]
oh wait is it an issue with the base shader?
i thought it was an issue with the compiler, since i didn't have issues before its optimisation?

**Comment by ogniK5377** [comment]
Really? It could be compiler issue but I doubt it?

**Comment by NotGaylien** [comment]
idk, maybe something changed in that update with the base shader, since thats what i been using for everything?
anyway just throw this here https://github.com/Facepunch/sbox-issues/issues/1075
same thing, i just called it rigged instead

**Comment by NotGaylien** [comment]
can confirm this works now
thanks sam <3
