### ISSUE TITLE
Inspector's resource finder not enabled when targeting custom asset types

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#1097]
**Describe the bug**

When creating asset configs, defining a (resource:target) does not enable the resource finder if the target type is custom.

**To Reproduce**

[custom-asset-search.zip](https://github.com/Facepunch/sbox-issues/files/7357927/custom-asset-search.zip)

1. Download and extract attached gamemode to sbox/addons folder
2. Launch S&box, launch the new gamemode
3. Restart sbox-dev to load custom assets in tools
4. Go to inspector, Type -> Example
5. Vmdl will have resource finder enabled, the custom type will not

**Expected behavior**

Resource finder works for all asset types

**Screenshots**

![sbox-dev_2021-10-16_11-58-43](https://user-images.githubusercontent.com/9637557/137596075-864412ff-bf2c-445f-8a9f-d787f14916ec.png)

**Comment by robotboy655** [comment]
For automatic FGD generation you will want to use `[ResourceType("findable")]` on the property you want to have the asset browser. Should just work when the game next updates.
