### ISSUE TITLE
Mouse wheel isn't a thing on most laptops!

### ISSUE THREAD

**Issue by costin88boss** [Facepunch/sbox-issues#1100]
**Describe the bug**
For future game features, as well as the main menu's scrolling games section, there isn't any mouse wheel on most laptops so it's impossible to scroll.

**To Reproduce**

1. use a laptop
2. find out you can't scroll cuz you have no "mouse wheel"

**Expected behavior**
scroll

**Screenshots**

**Additional context**

An idea is to use the arrows, dragging with mouse, or using PGdn and PGup.

**Comment by Adesii** [comment]
don't most laptops support 2 finger swipe up/down on the touchpad to scroll?

**Comment by DoctorGurke** [comment]
don't laptop track pads support scrolling with two fingers? lol

**Comment by walllable** [comment]
using a thinkpad t430 which is quite old (and as a result doesn't have windows precision drivers) so I dunno if it still works this way on modern laptops, but [two-finger scroll (as well as trackpoint scrolling for those it's relevant to) work here. ](https://files.catbox.moe/ta5588.mp4)
I figure older laptops that don't have this either can't run it, or can scroll by dragging your finger on the side of the touchpad like the old days. I do agree though, a scrollbar would be nice, like for example if your scrollwheel's broken or something.

**Comment by costin88boss** [comment]
No. that’s not how it works. Sent from Mail for Windows From: AdesiSent: Saturday, October 16, 2021 09:25 PMTo: Facepunch/sbox-issuesCc: costin88boss; AuthorSubject: Re: [Facepunch/sbox-issues] Mouse wheel isn't a thing on most laptops! (#1100) don't most laptops support 2 finger swipe up/down on the touchpad to scroll?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
