### ISSUE TITLE
Add Trace.SweepCapsule/SweepSphere

### ISSUE THREAD

**Issue by ontrigger** [Facepunch/sbox-issues#1109]
**What can't you do?**
As of right now, the default player controller uses an AABB for movement traces, however there is no way to change those traces to use a capsule or a sphere. The benefits of using a capsule collider for a character controller should be obvious.

**What have you tried?**
It is possible to create a new entity with a capsule collider using `SetupPhysicsFromCapsule` and pass that to `Trace.Sweep`, but that has a few issues:

- First of all, you'd have to keep track of a new entity that has a shitload of fields, and you have no idea how these fields will affect the trace results. Do I need to set the `CollisionGroup` to be something specific? What effect do `EnableAllCollisions`, `EnableHitboxes`, `MoveType`  have on the trace results?
- You would probably also want to ignore both the Pawn and the capsule collider during for the trace. What if I needed to ignore some other entity?
- I want to change the size of the capsule for a specific trace. Is there a performance impact of calling `SetupPhysicsFromCapsule` ?
- Internally, `Trace.Sweep.Run()` seems to be calling `Trace.SweepPhysicsBody`. What is the difference between that and a normal `Trace.Ray` ?

**How would you like it to work?**

The way I'd like to see it is to add additional static methods to Trace for common shapes:
```c#
public static Trace SweepCapsule(Capsule capsule, Vector3 from, Vector3 to);
public static Trace SweepCapsule(float height, float radius, Vector3 from, Vector3 to);

public static Trace SweepSphere(float radius, Vector3 from, Vector3 to);

public static Trace SweepBox(BBox box, Vector3 from, Vector3 to);
public static Trace SweepBox(Vector3 mins, Vector3 maxs, Vectro3 from, Vector3 to);

// rename Sweep to SweepBody for consistenct
public static Trace SweepBody(PhysicsBody body, Transform from, Transform to);
```

**Comment by kurozael** [comment]
This functionality is in now 👍
