### ISSUE TITLE
Whitelist System.Random

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/sbox-issues#111]
**What can't you do?**
Using System.Random

**Additional context**
Need a random number generator where I have control of the seed for deterministic things.

**Comment by Trojaner** [comment]
> Random

> Deterministic things

????

**Comment by ZehMatt** [comment]
> > Random
> 
> > Deterministic things
> 
> ????

```
var rnd = System.Random(1)
rnd.Next(); // Always same number, deterministic.
```

**Comment by Trojaner** [comment]
Nevermind, today I learned that you can actually do this

**Comment by ZehMatt** [comment]
👍
