### ISSUE TITLE
Crash in hammer RT baked lighting preview

### ISSUE THREAD

**Issue by Glitchvid** [Facepunch/sbox-issues#1116]
Hammer sometimes crashes when switching between RT lighting preview modes.

**To Reproduce**

1. Load a map (with multiple custom light cookies)
2. Switch to All Lighting
3. Switch to RT Baked Lighting
4. Switch through all RT preview modes
5. Repeat 2-4 until crash.

**Screenshots**
![crash](https://s.gvid.me/s/2021/10/18/KC7933.png)
**Additional context**

It seems this only happens when using multiple light cookies.
May be related to: https://github.com/Facepunch/sbox-issues/issues/834

**Comment by bakscratch** [comment]
This still happens on larger/ detailed maps.
