### ISSUE TITLE
Model's Glow color doesn't match it's set color

### ISSUE THREAD

**Issue by SharpMars** [Facepunch/sbox-issues#1118]
**Describe the bug**
When using Glow for model color set doesn't match color rendered around the model. It's much lighter that it should be.

**Expected behavior**
Rendered color should be the same color as GlowColor.

**Screenshots**
![image](https://user-images.githubusercontent.com/70289680/137802453-38bbdcdd-f7ca-46cc-858b-c63b691b7a55.png)

**Additional context**
Doesn't seem to be fault of Postprocessing and appears both in gamemodes tested: Sandbox and Smash.
In any case map used: [maps.zip](https://github.com/Facepunch/sbox-issues/files/7368320/maps.zip)

## Update:
Turns out color was just 1px border on the outside of glow.
![obraz](https://user-images.githubusercontent.com/70289680/150244565-ccde569b-c4c8-4a02-895d-892232f336ca.png)
Color tested was Color32( 255, 40, 0 ).ToColor()
Further from glowing object set color is more visible.
![obraz](https://user-images.githubusercontent.com/70289680/150244791-00bb9c98-9292-4bca-a898-9f503fe572aa.png)

**Comment by matekdev** [comment]
Probably can close this, should be fixed with the new glow.

**Comment by SharpMars** [comment]
Yea probably right
