### ISSUE TITLE
Modeldoc: Custom GenericGameData Nodes

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#1119]
**What can't you do?**
Create custom @ModelGameData FGD Entries for Modeldoc.

**How would you like it to work?**
Since the FGD is loaded in Modeldoc it should also detect custom GenericGameData Nodes.
This would allow for Custom Data to be linked to each model like for example the hand_pose_pair node.
which would allow for example in my VR gamemode to use custom models instead of just the alyx ones.
This would also give more use to the GetData<T>("keyname"); function since that is able to load those custom nodes.

**What have you tried?**
Tried Creating a new FGD file and copying the @ModelGameData of particle and changing the name of it so it would show up as a new node.
Also tried making a custom hand_pose_pair node which also didn't work.

my current workaround is to just use the hand_pose_pair for my VR mode which works fine currently but since we will change the hands in the future the hand_pose_pair won't fit for the new model.

**Comment by robotboy655** [comment]
I have added basic support for custom `GenericGameData` nodes on the main branch.

Currently it works something like this:

1) Define a struct/class, tag it with `ModelDoc.*` attributes, `ModelDoc.GameData` being mandatory.
```c#
	/// <summary>
	/// Spawn a particle when the model is used on an entity. Support for this depends on the entity.
	/// </summary>
	[ModelDoc.GameData( "particle", AllowMultiple = true )]
	public class ModelParticle
	{
		[DisplayName( "Particle" ), ResourceType( "vpcf") ]
		public string Name { get; set; }

		[JsonPropertyName( "attachment_point" ), FGDType( "model_attachment" )]
		public string AttachmentPoint { get; set; }

		[JsonPropertyName( "attachment_type" )]
		public ParticleAttachment AttachmentType { get; set; } = ParticleAttachment.AttachmentFollow;

		[JsonPropertyName( "attachment_offset" )]
		public Vector3 AttachmentOffset { get; set; }
	}
```
2) Run the associated gamemode, which will generate a `_modeldata.fgd` file for your gamemode.
3) Assign the nodes to models
4) Use the data in code as such:
```c#
if ( model.TryGetData( out ModelPropData propInfo ) )
{
	Health = propInfo.Health;
}
```

or 

```c#
var hasAny = self.HasData<ModelParticle[]>();
var particles = self.GetData<ModelParticle[]>();
```

You can see more examples in `ModelExtensions.cs` of the base addon.

Please note that currently there is no markup necessary to completely replace `hand_pose_pair` in c#, it will be working on that next.

**Comment by Adesii** [comment]
This is already a great start. I can already imagine lots of useful ways to use this. 
like replacing the attachment point way im doing it on my anim interactables so that a normal model can have interactibles predefined in modeldoc instead of having it hardcoded, but also predefine parameters like if it should start locked etc. lots of possibilities already.

**Comment by robotboy655** [comment]
Added the following attributes for these nodes:
* ModelDoc.Axis
* ModelDoc.Box
* ModelDoc.Sphere
* ModelDoc.Capsule
* ModelDoc.Cylinder

They should all be sufficiently documented with C# XML comments which your IDE can read.

**Comment by robotboy655** [comment]
Thinking about `hand_pose_pair` specifically, I think a better idea would be to just allow to switch the hand models with a property in the node itself rather than expecting every gamemode that wants to use custom hand models to duplicate their own node just to change the model.

**Comment by Adesii** [comment]
that would make sense. tho im also not really sure how the internal stuff works with custom models. i tried to copy the handpose pair. and it wouldn't really work on my custom model, even tho i have the same bone structure.
it would show up. but i couldn't pose the finger bones. it was wonky as hell
maybe there is more to it than just switching models

**Comment by robotboy655** [comment]
Ah, that's a fair point.

**Comment by robotboy655** [comment]
Added the following ModelDoc attributes:
* ModelDoc.Line
* ModelDoc.HandPose
* ModelDoc.EditorWidget

They are all documented with XML comments as per usual.

I also added support for ModelBreakCommand nodes, which work like so:
```c#
/// <summary>
/// Spawn a particle system when this model breaks.
/// </summary>
[Library( "break_create_particle" )]
public class ModelBreakParticle : IBreakCommand
{
	/// <summary>
	/// The particle to spawn when the model breaks.
	/// </summary>
	[JsonPropertyName( "name" ), ResourceType( "vpcf" )]
	public string Particle { get; set; }

	// ...

	public void OnBreak( Sandbox.Breakables.Result res )
	{
		if ( !(res.Source is ModelEntity ent) ) return;

		var part = Particles.Create( Particle, ent.Position );
		part.SetOrientation( 0, ent.Rotation );
			
		// ...
	}
}
```

With these additions I am considering this request fulfilled. You can now recreate any of the default GenericGameData nodes for ModelDoc and create custom ones.

One thing that remains is same treatment for Animation Events (`@ModelAnimEvent`), but I am not sure how I would hook those up to work on all entities yet, and its not part of this request anyway. Feel free to create a separate request for it.
