### ISSUE TITLE
Crash when creating AnimSceneObject with invalid model

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#112]
**Describe the bug**

Creating a new AnimSceneObject with an invalid model causes the game to crash without exception or log.

`var animObj = new AnimSceneObject(Model.Load(""), Transform.Zero);`

**To Reproduce**

Put the above code inside the RenderScene ui test, it should crash when it executes.

**Expected behavior**

Give exception instead of crash (or use error model or something)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by cr4yz** [comment]
Fixed!
