### ISSUE TITLE
TextEntry horizontal scrolling

### ISSUE THREAD

**Issue by Crayolas** [Facepunch/sbox-issues#1120]
**What can't you do?**

https://user-images.githubusercontent.com/92621225/137874892-89e735c7-8935-4520-b387-e1275c61f25a.mp4

**How would you like it to work?**

https://user-images.githubusercontent.com/92621225/137875452-76c8ea69-0d19-46f6-9690-bb4f2ad71f3b.mp4

**What have you tried?**

tried using the "right" property with min-width and width: fit content but overflow doesnt hide the text with that solution
**Additional context**

**Comment by DrakeFruit** [comment]
I think this has been added with shift + scroll
