### ISSUE TITLE
Avatar is broken.

### ISSUE THREAD

**Issue by GrenHubber** [Facepunch/sbox-issues#1123]
Updated s&box to latest version.
The avatar that I have is broken.
![image](https://user-images.githubusercontent.com/86384557/137963583-81a892ce-2a28-4c4c-8aa8-50ed581d794b.png)
Image for proof.
Avatar mesh seems to be not correct.

**Comment by Stadus** [comment]
Can confirm that it's an issue for AMD GPUs (RX 6900XT).

**Comment by SharpMars** [comment]
Just checked and it appears that this issue also exists on integrated Intel Graphics(if anyone is actually using it bruh)
![](https://cdn.discordapp.com/attachments/833983416390385685/900161648067739648/unknown.png)

**Comment by Vaycron** [comment]
happening to me aswell on my amd cpu even after fresh installing it.

**Comment by Vaycron** [comment]
> > happening to me aswell on my amd cpu even after fresh installing it.
> > ![47de5df0c6ef4d36a59e1722c6746ccf](https://user-images.githubusercontent.com/92842023/138031208-054f235b-b7bd-4c10-8339-7f5bbfb58f4a.png)
> 
> First of all it's GPU issue, not CPU one. Second of all confirming something that is already confirmed that happens on all of those GPU's doesn't help in any other way and just makes this issue dirty. If you have something more to add than "I have that issue" you could comment that.

i got amd gpu aswell but yeah i was just posting it cuz its a new issue it seems.
