### ISSUE TITLE
Fists have strange normals and broken looking UVs and the citizen ragdoll spidering

### ISSUE THREAD

**Issue by yourtoast4** [Facepunch/sbox-issues#1125]
Bug 1: The fists weapon in the sandbox mode seem to have a strange normal map and incorrect looking textures

1. Select Fists
2. Observe

Fists have strange lighting around the thumb area, buttons on cuffs have strange uvs

![Fist Lighting](https://user-images.githubusercontent.com/39923359/137987370-5c3b69d0-f2dc-4bb4-a91d-ad6c29c6803f.PNG)

Bug 2: Citizen Ragdoll is incredibly easy to spider

1. Spawn Citizen Ragdoll
2. Freeze part of the Ragdoll
3. Drag or scroll another part of the ragdoll
4. Observe as the ragdoll spiders/stretches without much effort

Alternatively
1. Spawn Citizen Ragdoll
2. Drag Ragdoll into Map Geometry
3. Observe as the ragdoll spiders/stretches without much effort

and
1. Spawn Citizen Ragdoll
2. Grab part of the Ragdoll
3. Throw the ragdoll around with the Physics Gun
4. Observe as the ragdoll spiders/stretches without much effort

A side note from the two bugs are that Damage to both props and the player seem too effective, and it's possible to die super quickly from props simply being moved towards the player, or if you bash them onto the ground.
Comparing this with Garry's mod, it was basically impossible to damage yourself with props you hold with your phys gun let alone die from them. This makes it harder to move props around without them breaking, exploding in your face or just doing damage to you because it was in proximity. (Also the double space noclip is a little inconsistent to perform)

**Comment by aylaylay** [comment]
Temp model
We need to work on Rubikon to improve ragdolls
