### ISSUE TITLE
Angles and Rotation not sending via Console Command

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#113]
**Describe the bug**

Angles fails to send the correct values and Rotation throws an exception.

**To Reproduce**

Create a ServerCmd that accepts an Angles parameter
Execute it from the client
The Angles will be Zero on server end

Create a ServerCmd that accepts a Rotation parameter
Execute it from the client
Exception will be thrown "Need to add the ability to change from String to Rotation"

**Expected behavior**

Angles and Rotation work in rpcs

```
[ServerCmd("RpcTest")]
public static void RpcTest(Vector3 vec, Angles angles, Rotation rot)
{
	Log.Info($"Result: ({vec}), ({angles}), ({rot})");
}
```

```
if (IsClient)
{
	if (Input.Pressed(InputButton.Slot1))
	{
		RpcTest(new Vector3(2, 2, 2), new Angles(2, 2, 2), Rotation.From(new Angles(2, 2, 2)));
	}
}
```

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by cr4yz** [comment]
Fixed!
