### ISSUE TITLE
String ToInt and ToDecimal ignore default value

### ISSUE THREAD

**Issue by nikita-strelok** [Facepunch/sbox-issues#1131]
**Describe the bug**
StringX.ToInt and ToDecimal return 0 instead of default

**To Reproduce**
```csharp
Log.Info( "someshit".ToInt(-1) );
Log.Info( "someshit".ToDecimal( -1 ) );
```
![image](https://user-images.githubusercontent.com/88283901/138174851-ad5e8d94-b85c-47a2-947f-4ac611e799e0.png)

**Expected behavior**
-1
-1

**Screenshots**

**Additional context**

**Comment by ogniK5377** [comment]
I just pushed a fix, it should be fixed in the next game update!

**Comment by nikita-strelok** [comment]
Thanks, now it works as expected
