### ISSUE TITLE
Unable to remove all decals from world

### ISSUE THREAD

**Issue by Fear837** [Facepunch/sbox-issues#1134]
**Describe the bug**

Maybe I am missing something but calling `RemoveAllDecals()` on the `WorldEntity` entity does not have any effect regardless of whether or not it is called on clientside or serverside.

**To Reproduce**

1. Get the worldEntity by calling `PhysicsWorld.WorldBody?.Entity as WorldEntity`
2. Place decals using `Decals.Place(...)` and use the worldEntity in the entity argument
3. Try calling `worldEntity.RemoveAllDecals()` on serverside or clientside
4. See that no decals disappeared

The following gist can be used to reproduce:

https://gist.github.com/Fear837/2b1c2f1df4d3021229e338c700ae97af

**Expected behavior**

Decals should disappear.

**Comment by Fear837** [comment]
As far as I can tell, this problem still persists.
I can place decals but not remove them.

**Comment by aylaylay** [comment]
I'll have another look now that decals are showing up

**Comment by aylaylay** [comment]
Should be working now

**Comment by Fear837** [comment]
Seems to be fixed.
