### ISSUE TITLE
Input caret no longer visible

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#116]
**Describe the bug**

The caret has disappeared since a recent update.

**To Reproduce**

Open console and select the input box, caret won't be visible.

**Expected behavior**

Caret visible

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by cr4yz** [comment]
Fixed!
