### ISSUE TITLE
`Hammer.Skip` ignores inherited classes

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1172]
**Describe the bug**
`Hammer.Skip` ignores inherited classes. If I wanna add a weapon, that is inherited from my base weapon (with `Hammer.Skip` because it's an abstract class) to Hammer, there is no way to do so currently. The only workaround is to remove `Hammer.Skip` from my base class (which gonna lead to errors if a mapper / FGD user gonna try to use the abstract class).

**Expected behavior**
Inherited classes should not be checked whether their parent's class has `Hammer.Skip`.
E.g. if you used `type.IsDefined(typeof(T), true)` internally, `type.IsDefined(typeof(T), false)` would fix it.

**Comment by robotboy655** [comment]
Hammer.Skip no longer inherits when testing for entity classes.

**Comment by Alf21** [comment]
Thanks, working perfectly now! 👍
