### ISSUE TITLE
Menu doesn't want to render

### ISSUE THREAD

**Issue by REALalphas** [Facepunch/sbox-issues#1177]
**Describe the bug**
Just blinking lines sometimes form boxes of UI elements

**To Reproduce**
1. Launch game

**Expected behavior**
Facepunch logo appears at startup, then a bug appears
(More info and videos in comments)

**Screenshots**
![image](https://user-images.githubusercontent.com/26285012/139106488-f78a14ec-3118-4a94-9186-c8a3e4b19b20.png)
![image](https://user-images.githubusercontent.com/26285012/139106520-13a46b4d-2b19-4379-8e35-091a74da6c17.png)

**Additional context**
CPU: AMD Ryzen 7 4800H /w Radeon Graphics
Chipset: AMD K17.6 FCH, AMD K17.6 IMC
GPU: NVIDIA RTX 2060
RAM: 8Gb x2 Samsung M471A1K43DB1-CWE
Disk: SKHynix_HFS512GD9TNI-L2A0B  (512 GB, PCI-E 3.0 x4)
DirectX: DirectX 12.0
OS: Microsoft Windows 10 Home Single Language (Windows 11)

**Comment by REALalphas** [comment]
> Does this happen if you reinstall the game? ( Verifying files might be enough )

I reinstall after this bug, and nothing is changed. : /
Before reinstalling I verified game files, and nothing is changed...

**Comment by REALalphas** [comment]
Now I noticed that I can use UI elements (hover and click definitely work)

Bug playback video with strange menu display and clickable elements
https://user-images.githubusercontent.com/26285012/139508169-39730d43-4da5-402c-80dd-e7dd79f18272.mp4

**Comment by ogniK5377** [comment]
Did you delete your addons? This is usually caused by creating duplicates of the UI shaders

**Comment by REALalphas** [comment]
I reinstalled s&box from steam and this is not working for me, then I removed game folder and installed s&box from steam and that helped. Thanks, @ogniK5377 for your contribution.
