### ISSUE TITLE
More css options for box-shadow

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#118]
**What can't you do?**

Can't inset the shadow.

**How would you like it to work?**

Inset the shadow
`box-shadow inset offsetX offsetY blur spread color;`

Provide less parameters (forced to use all 4)

`box-shadow blur spread color;`

**Comment by 8char** [comment]
Still very much needed. I've already built a significant portion of my UI in Figma, and it heavily relies on shadow insets.
