### ISSUE TITLE
WorldPanel input doesn't work with a visible cursor

### ISSUE THREAD

**Issue by Oppossome** [Facepunch/sbox-issues#1183]
**Describe the bug**
Input doesn't reach WorldPanels when the cursor is unlocked with `pointer-events: visible` on the HUD

**To Reproduce**

1. Download and install [this bug repro fork](https://github.com/Oppossome/sbox-minimal)
2. Attempt to hover on the red square
3. Now do the same in DevCam

**Expected behavior**

For the WorldPanel to receive the mouse input

**Screenshots**
![video of bug](https://user-images.githubusercontent.com/15877760/139170084-d2ae7266-cfb7-4614-b8f3-7f7f38b9363b.gif)

**Comment by handsomematt** [comment]
This should work as expected now https://github.com/Facepunch/sbox-issues/discussions/1273

Let me know if it's still causing issues, otherwise feel free to close. :)
