### ISSUE TITLE
Hammer: RT Baked Lighting function black-screen

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#1187]
**Describe the bug**

When using the `RT Baked Lighting` function in Hammer to preview your accurate map's lighting, it just shows a black-screen since the core shaders issues.

**To Reproduce**

1. Go on Hammer, open any map that has light entities
2. Click on the drop down menu on the viewport
3. Select `RT Baked Lighting`
4. Screen will be black, no preview will be rendered

**Expected behavior**

The viewport should show the `RT Baked Lighting` preview rendering.

**Screenshots**

Current:
![image](https://user-images.githubusercontent.com/67245359/139245037-997f6017-eee2-4165-9fb0-131aed45938e.png)
Expected:
![image](https://user-images.githubusercontent.com/67245359/139244522-ea831cc9-189b-45a2-a203-239eb78da126.png)

**Comment by aylaylay** [comment]
This should be fixed when the game next updates

**Comment by VeeSaus** [comment]
![image](https://user-images.githubusercontent.com/75756114/139584080-df3c7aa6-c01c-4796-a03b-86bf8e380659.png)

Seems to mostly work fine, but blend materials/mats using the blendable shader appear as black now

**Comment by aylaylay** [comment]
I'd open a new issue for black blendable so sam can look at it
