### ISSUE TITLE
Widescreen WorldPanel input is faulty

### ISSUE THREAD

**Issue by Oppossome** [Facepunch/sbox-issues#1188]
**Describe the bug**
Widescreen WorldPanels don't properly register input, and only seem to do so within a square of the height.

**To Reproduce**
1. Install and load [this bug repro fork](https://github.com/Oppossome/sbox-minimal)
2. Attempt to light the square by hovering within the red outline.

**Expected behavior**
For the input to correctly work

**Screenshots**
![bug gif](https://user-images.githubusercontent.com/15877760/139266332-bde06c99-9542-403b-ad9b-4a093a57b944.gif)

**Comment by Oppossome** [comment]
It's probably an issue with the IsInside function called from within RayToLocalPosition

**Comment by Oppossome** [comment]
The issue is caused by passing a Vector3 into the IsInside(Vector2 pos) which causes the X Axis to always be 0

It is fixed by making this change
![devenv_2021-11-04_15-25-36](https://user-images.githubusercontent.com/15877760/140407243-b6decbe0-bbd1-4095-9af8-7372514b2a20.png)

**Comment by handsomematt** [comment]
This should work as expected now https://github.com/Facepunch/sbox-issues/discussions/1273

Let me know if it's still causing issues, otherwise feel free to close. :)
