### ISSUE TITLE
Gamemodes and Maps Quit To Screen If Missing Packet Occurs During Download

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#1193]
**Describe the bug**
If you try and download a gamemode over wi-fi, and the download misses a packet, the download stops entirely and quits back to the main screen, producing an error in the process. 

**To Reproduce**

1. Connect to Wi-Fi and be in another room or using a standard adapter
2. Attempt to Download Any Gamemode > 300mb
3. See error occur.

**Expected behavior**
Downloads should be able to be resumed if it errors out like this, or the handling of missing packets should be handled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/15205856/139466051-2c0283a7-9a7b-4b89-afd9-392090e5b08c.png)

**Comment by handsomematt** [comment]
I don't think we can fix your wifi adapter not being able to do basic TCP.
