### ISSUE TITLE
WebSocket Origin Header

### ISSUE THREAD

**Issue by LMNYX** [Facepunch/sbox-issues#1194]
**What can't you do?**
Setting the origin of the websocket connection.

**How would you like it to work?**
```csharp
webSocket = new WebSocket();
webSocket.Origin = "https://localhost";
// or
webSocket.SetOrigin("https://localhost");
```

**What have you tried?**
No possible workaround found.

**Additional context**
Some websocket servers decline connection if you haven't set the correct origin, I couldn't find the implementation for this in s&box, would be great if it was possible.

**Comment by LMNYX** [comment]
This isn't the case most of the time, though. For example, [Discord RPC](https://discord.com/developers/docs/topics/rpc#connecting) uses Origin header to authenticate your application (where you need to set origin header yourself on their developers platform). This is just a good practice for identifying that this is indeed this app / protecting (sort of?), I guess?

**Comment by Rohansi** [comment]
That's odd but sure. We should specify some origin header but it should not be customizable by the addon. Does Discord RPC require http(s) origins or could it be something like `sbox://gamemode/facepunch/pool`? If it needs http then we can just set it to `https://sbox.facepunch.com/` or something.

**Comment by LMNYX** [comment]
It requires http/https origin, according to the docs, also accepts localhost. First variant seems more reasonable, but I don't think they support custom browser protocols as origin, would be awesome if second variant had the same format, like `https://sbox.facepunch.com/dev/facepunch/minigolf`.

**Comment by trundler-dev** [comment]
I can't see a reason some arbitrary s&box client would be connecting to a random WS server. All this really does in the context of s&box is prevent random WS scanning from messing with your server, and that case would be covered by the auth token described in #507 in my opinion.

**Comment by Rohansi** [comment]
The origin header is now set to `https://sbox.facepunch.com/` on all WebSocket requests. We'll likely add the org/addon name in there in the future.
