### ISSUE TITLE
`System.NullReferenceException: C_BaseEntity was null when calling GetLifeState`

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1197]
**Describe the bug**
If you checking a player's `LifeState` when the player disconnects, you'll get an error. It seems like the instance of another player `LifeState` is using internally is set to null before the C#-accessable player instance is set to null as seen in this check (called in Simulate method which leads to the following error):

```csharp
if (Player.Health == 0 && Player.LifeState == LifeState.Alive)
{
    // ...
}
```

```text
System.NullReferenceException: C_BaseEntity was null when calling GetLifeState
Sandbox.Entity.get_LifeState C:\buildbot\work\sbox\sbox\engine\Sandbox.Game\Entity\Entity.cs:847
TTTReborn.UI.Nameplate.UpdateHintPanel C:\Program Files (x86)\Steam\steamapps\common\sbox\Addons\ttt-reborn\code\ui\generalhud\nameplate\Nameplate.cs:76
TTTReborn.Player.TTTPlayer.TickEntityHints C:\Program Files (x86)\Steam\steamapps\common\sbox\Addons\ttt-reborn\code\player\TTTPlayer.Hints.cs:57
TTTReborn.Player.TTTPlayer.Simulate C:\Program Files (x86)\Steam\steamapps\common\sbox\Addons\ttt-reborn\code\player\TTTPlayer.cs:184
Sandbox.Game.Simulate C:\Program Files (x86)\Steam\steamapps\common\sbox\Addons\base\code\Game.cs:71
Sandbox.PlayerCommand.Run C:\buildbot\work\sbox\sbox\engine\Sandbox.Game\PlayerCommand.cs:100
Managed.SourceClient.Exports.Sandbo_PlyerC_RunClient C:\buildbot\work\sbox\sbox\engine\Sandbox.Game\Interop.Client.cs:3539
```

As we can see, `Player.Health` is not printing the error but `Player.LifeState`, which leads to the finding that `Player` is valid (on the C# / gamemode side)

**To Reproduce**

1. Call `Player.LifeState` in the `Simulate` method of another player while that player disconnects (clientside).

**Expected behavior**
No error

**Comment by Jake-NSW** [comment]
Just check if the entity is valid?
