### ISSUE TITLE
WorldPanels are not color accurate

### ISSUE THREAD

**Issue by Oppossome** [Facepunch/sbox-issues#1199]
**Describe the bug**
WorldPanels draw colors much more brightly than they actually are

**To Reproduce**

1. Install [this bug repro repo](https://github.com/Oppossome/worldpanel-color)
2. Compare the red outlined worldpanel to the blue outlined hud panel

**Expected behavior**
For the colors to be accurate

**Screenshots**
![ezgif com-gif-maker-1](https://user-images.githubusercontent.com/15877760/139540232-250b1421-8c3f-4b32-a73a-0be70e56b191.gif)

**Comment by anthonysharpy** [comment]
in my case the colours are darker than expected

![image](https://user-images.githubusercontent.com/55365296/212980795-0d227171-b317-4474-be51-0493938be5d4.png)

**Comment by xezno** [comment]
I think this is just caused by tonemapping

**Comment by anthonysharpy** [comment]
@xezno what would be the correct way to create a world panel that is not affected by tonemapping?

**Comment by xezno** [comment]
You can't, it's an object in the world

**Comment by anthonysharpy** [comment]
> You can't, it's an object in the world

okie dokie, thanks anyways
