### ISSUE TITLE
PhysicsGroup should be a collection (`IEnumerable`)

### ISSUE THREAD

**Issue by megabro** [Facepunch/sbox-issues#1210]
**What it is**
Right now to iterate through the `PhysicsBody`'s in a `PhysicsGroup`, I'd have to write it like this:
```cs
for ( int index = 0; index < PhysicsGroup.BodyCount; index++ )
{
    var body = PhysicsGroup.GetBody( index );
    
    // Do something with body
}
```

**What it should be**
I think it would be clearer if instead of that, I could just write:
```cs
foreach ( var body in PhysicsGroup )
{
    // Do something with body
}
```

**Comment by aylaylay** [comment]
I agree

**Comment by aylaylay** [comment]
You now have

- PhysicsGroup.Bodies
- PhysicsGroup.Joints
- PhysicsWorld.Bodies
- PhysicsBody.Shapes
