### ISSUE TITLE
Hair rendering not working correctly in appearance editor

### ISSUE THREAD

**Issue by P4sca1** [Facepunch/sbox-issues#1213]
**Main menu:**
![s box_2021 11 04-00 44](https://user-images.githubusercontent.com/10992664/140234120-ffdac507-182c-4939-8c67-7493f67710a3.png)

**Appearance editor:**

![s box_2021 11 04-00 44_1 (2)](https://user-images.githubusercontent.com/10992664/140234106-48817919-6230-4d99-b383-6a17c27a85af.png)

**Additional context**
* Both images show the brown hair color selected, but the problem exists for both hair colors.
* OS: Windows 11
* GPU: AMD Radeon RX 5600 XT
* Radeon Driver version: 21.10.2

**Comment by garrynewman** [comment]
I think @aylaylay found a solution to this by enabling post processing - but maybe @samzanemesis  and or @ogniK5377  could look into it so we can understand why it's happening?
