### ISSUE TITLE
Glow will get baked into map Cubemaps

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#1214]
**Describe the bug**
Title might be a bit confusing but let me explain, when you have a glow active on any entity and bake the cubemaps on a map the glow from that entity will be plasted onto the cubemap

**To Reproduce**
Turn on glow on an entity (such as a pawn), position it inside a cubemap, and bake then bake cubemaps

**Expected behavior**
To not have the glow

**Screenshots**
The yellow stuff was when I bake cubemaps while being in that position with a glow active
![image](https://user-images.githubusercontent.com/55055481/140237259-804b1cf1-e0ab-4644-95d5-ff9e0a0d16e8.png)

**Comment by samzanemesis** [comment]
That should be fixed on the new glow system
