### ISSUE TITLE
Allow Text To Be Centered On New Lines

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#1216]
**What can't you do?**
Right now, if you have the string literal `"Josh Wilson\nIs the Dot Com Guy"` and try to center the text, the text will be right justified and there is no way within the current scss to do it.

**How would you like it to work?**
Some kind of style that allows us to adjust how we justify newlines. Right now text-align aligns the entire text within its child panel, and also only works horizontally. 

**What have you tried?**
Usually I have to create a second label if I want to do something like this, which can be time consuming and tedious, not to mention non-ideal for longer lists such as credits.

Here is a screenshot example from the menu lab:
![image](https://user-images.githubusercontent.com/15205856/140403276-3127a51a-da73-4eb8-b7d0-6a7bc528c4a1.png)

**Comment by MoonlyDays** [comment]
Bump 🙏🏼

**Comment by Geeknerd1337** [comment]
@MoonlyDays If you haven't already, it's well worth converting your UIs to using templates where possible. That system makes adjusting items and adding new labels 100x faster than it was when I originally wrote this issue.

**Comment by cr4yz** [comment]
This should be fixed now.
