### ISSUE TITLE
Whitelist System.Reflection.MethodBase and System.Reflection.ParameterInfo

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#1219]
**What it is**
Currently System.Reflection.MethodBase and System.Reflection.ParameterInfo are not whitelisted.

**What it should be**
Whitelist System.Reflection.MethodBase and System.Reflection.ParameterInfo, allowing us to retrieve a list of parameters from a MethodInfo object. Key functions here are MethodBase.GetParameters, MethodBase.Invoke, and ParameterInfo.IsIn, IsOut

I'm working on a node editor, trying to get it to hook up to the C# side of things directly with MethodInfo, and I need type/name info on the parameters to correctly populate the node inputs.

**Comment by liquiad** [comment]
I made a new issue for this since we have TypeLibrary now.

https://github.com/Facepunch/sbox-issues/issues/2200

**Comment by liquiad** [comment]
Fixed with https://github.com/Facepunch/sbox-issues/issues/2012
