### ISSUE TITLE
Flickering Camera Frustum, rotate control, model moving arrows in Source Filmmaker tool.

### ISSUE THREAD

**Issue by Stormyscratch** [Facepunch/sbox-issues#1222]
**Describe the bug**
SFM got flickering behaviour to Camera Frustum, rotate control, model moving arrows.

**To Reproduce**

1. Go to 'SFM' tool
2. Create a new camera
3. Switch to Work Camera
4. Observing the flickering from Camera Frustum, rotate control, model moving arrows through Work Camera viewport

**Expected behavior**
Flickering behavior shouldn't be happened.

**Screenshots**

https://user-images.githubusercontent.com/44833723/140513111-076c85ed-8b13-4278-8a99-e87b9680f6d0.mp4

**Comment by aylaylay** [comment]
Should be fixed in next update

**Comment by Stormyscratch** [comment]
Thank you, it is fixed.
