### ISSUE TITLE
Base WalkController forwards/backwards movement affected by view pitch

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#1227]
**Describe the bug**
The forwards/backwards movement (W/S) appears to be affected by the player's view pitch if you attempt to walk to the side at the same time.

**To Reproduce**
1. Look straight down.
2. Hold W+D.
3. You are now walking straight to your right with no forward movement.

**Expected behavior**
Forwards/backwards movement should not be affected by view pitch while strafing.

**Video example**
I'm holding S+D during the full duration of the video, only changing my view pitch.
https://user-images.githubusercontent.com/16853532/140617136-91c43d86-f99f-47e7-80c7-f3ecb2139758.mp4

**Comment by DevulTj** [comment]
Copy paste the WalkController and do this

```csharp
var rot = Input.Rotation.Angles().WithPitch( 0 );
WishVelocity *= rot.ToRotation();
```
In Simulate

**Comment by aylaylay** [comment]
sorted
