### ISSUE TITLE
Ent_path_platform/path_generic issues

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#1228]
Ent_path_platform and path_generic have a variety of limitations and bugs right now, so in this issue I want to list all the problems, as well as offer a couple of ideas for improvement.

bug #1

In the Output - any trigger entity can be specified as well as patch number, in the description GoToPoint written that when the specified patch is reached - ent_path_platform will stop, but it's not. 

![image](https://user-images.githubusercontent.com/54669564/140621042-948500f5-5ead-4138-bfad-b8b510cda79a.png)

https://www.youtube.com/watch?v=-MgdJtlylw4

path_generic_node problem #2

path_generic_node cannot be linked to each other, obviously you can try to place the initial path and the final one in the same coordinated, but this is crap

![image](https://user-images.githubusercontent.com/54669564/140620936-07c0e7b8-0f2f-4f04-b548-dc1a2933cd56.png)

path_generic / path_generic_node problem #3

patch_generic / patch_generic_node has no outputs, i.e. I cannot change any entity settings when a certain patch is reached

![image](https://user-images.githubusercontent.com/54669564/140562003-132c90cd-a07c-4403-bd60-a6888fb5a5ff.png)

path_generic_node problem #4

In path_generic cannot be changed the name or id, you have to use the common values specified by hammer, which is not very convenient.

![image](https://user-images.githubusercontent.com/54669564/140562170-c42be74b-24c7-47f9-9c4d-c824ae058929.png)

Path_generic problem #5

You cannot change the Path Entity in real time to another one, using outputs and so on.

![image](https://user-images.githubusercontent.com/54669564/140620975-bcf4c6a9-26a1-40d0-8a5e-e64d8772bc94.png)

![image](https://user-images.githubusercontent.com/54669564/140562980-d0c05fcb-82d9-4652-8341-407abc2041b8.png)

**Comment by robotboy655** [comment]
Can you send me the map file from the video? I cannot reproduce the issue you are experiencing.

**Comment by gabengaGamer** [comment]
[RubatMaster.zip](https://github.com/Facepunch/sbox-issues/files/7499627/RubatMaster.zip)

**Comment by gabengaGamer** [comment]
https://user-images.githubusercontent.com/54669564/140806837-30259ac2-37de-4292-b514-f70965a76f8b.mp4

also ent_button entity broken

**Comment by QuackCocaine** [comment]
>  cbJHQJQ2z3.mp4 
> also ent_button entity broken

I have also gotten some strange ent_button behavior but that's when the door I targeted was in an instance. The door would attach and warp itself to the button for whatever reason.

**Comment by gabengaGamer** [comment]
Apparently most of the entities are broken XD

**Comment by robotboy655** [comment]
The ent_button was broken by a recent change relating to how entities loading data from the map and should now be fixed.

The "issue" you were experiencing in that video is expected behavior considering you have this in your ent_path_platform:
![image](https://user-images.githubusercontent.com/3299036/140945211-34963b58-2f73-4908-a7b3-ed6e8dca2a82.png)

So there is in fact no bug. The rest of the missing/requested features will be looked at.

**Comment by gabengaGamer** [comment]
I have no idea how this parameter got into outputs, I didn't even open this tab there
