### ISSUE TITLE
Allow events to call static methods on non-entities

### ISSUE THREAD

**Issue by Oppossome** [Facepunch/sbox-issues#123]
**What can't you do?**
Call events on non-entities, which is understandable. But, being able to do it on their static methods would allow us to decouple logic from entities.

**How would you like it to work?**
```cs
public class MyClass {
  [Event("frame")]
  public static void OnFrame()
  {
	  Log.Info( "Wow!" );
  }
}
```

**What have you tried?**
Currently we have to write had a dispatcher that calls the method on the class. 

**Additional context**
It'd mostly be nice to have especially as people start to use Event.Run for non-entity related things. 😄

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
