### ISSUE TITLE
Hammer- Tiling support in Fast Texture Tool

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1230]
**What can't you do?**
We can't seamlessly tile things like trim sheets.

**How would you like it to work?**
Probable a box in Fast Texturing Tool to enable tiling. Maybe a slider to adjust tile scale too.
![image](https://user-images.githubusercontent.com/39461072/140623645-be4f8214-8076-41b4-ad9c-822c01c25198.png)

**What have you tried?**
Currently we have to tile manually by changing the texture scale. This isn't ideal and creates noticeable seams
![image](https://user-images.githubusercontent.com/39461072/140623631-a9cb7de2-3cce-428e-8624-95e18e1a8b04.png)

Current Tiling Process: https://streamable.com/70sf31

**Comment by gvarados1** [comment]
This will save hours of work on trims & kerbs

**Comment by Xenthio** [comment]
please

**Comment by QuackCocaine** [comment]
Bump, a nice QOL change this would be to make things faster

**Comment by gvarados1** [comment]
Looks like the DOTA tools already have this. It's separated it into Tile U and Tile V with options for how many repeats or Maintain Aspect Ratio
![image](https://user-images.githubusercontent.com/39461072/165855037-88216911-cc14-4d23-8469-2234c97d94ba.png)

**Comment by gvarados1** [comment]
If Tile U is ticked, The U scale will match the V scale, assuming Maintain Aspect Ratio is ticked.
If Repeat is on, the U Scale will repeat x times.
![image](https://user-images.githubusercontent.com/39461072/165856515-4f1a245f-49d0-43d4-b861-66421f2c89d6.png)

**Comment by handsomematt** [comment]
I copied how it functions in dota hammer, it works okay for me. Let me know if it doesn't behave as expected though.

**Comment by bakscratch** [comment]
Working as intended thanks matt!

**Comment by aylaylay** [comment]
Thank you matt!

**Comment by gvarados1** [comment]
Maintain Aspect Ratio doesn't seem to work properly when the mesh isn't straight. I think it uses the width of the mesh when you'd expect it to use the width of the yellow box in the tool.
![image](https://user-images.githubusercontent.com/39461072/167224552-a248dbb8-e9cf-4848-a8f4-763eedf27fee.png)
