### ISSUE TITLE
Particle Editor is flickering

### ISSUE THREAD

**Issue by ImWill0w0** [Facepunch/sbox-issues#1231]
**Describe the bug**

Nothing on the particle is set other than movement, it keeps changing size a bunch

**To Reproduce**

Use the particle editor

**Expected behavior**

Not to bug out

**Screenshots**

https://user-images.githubusercontent.com/28235017/140625397-4e16d516-d238-4631-9d51-dfbcf94424ce.mp4

**Comment by ogniK5377** [comment]
Doesn't seem to be an issue anymore
