### ISSUE TITLE
Steam's "Verify integrity of game files" will always fail to validate after playing the game

### ISSUE THREAD

**Issue by megabro** [Facepunch/sbox-issues#1232]
**Describe the bug**
If you have a fresh copy, get into a gamemode in s&box and verify integrity of game files after that, you will see that 2 files failed to validate.

**To Reproduce**

1. Get a fresh install of s&box (Or just have one that passes verification)
2. Verify integrity of game files just to be sure
3. Start s&box and play any gamemode
4. Exit game
5. Verify integrity of game files
6. See that 2 files failed to validate and will be reacquired

**Expected behavior**
Should see "All files successfully validated."

**Screenshots**
![image](https://user-images.githubusercontent.com/35005210/140626154-157eadcf-df42-4681-8d2c-4abb4fe706cd.png)

**Additional context**
I checked which files fail validation, and it's `base.fgd` and `base_modeldata.fgd` in addons/base/config
Looking at the files in hex, you can see that an extra byte gets prepended to the file.

Before starting a gamemode:
![image](https://user-images.githubusercontent.com/35005210/140626194-aae12fed-6021-44e2-b444-6f48df250641.png)

After starting a gamemode:
![image](https://user-images.githubusercontent.com/35005210/140626202-d2007c52-191b-4c6b-b93d-4b3e71ee0db3.png)

I think there are a couple more changes that s&box makes to the files looking at their diff, but didn't list those here.

**Comment by robotboy655** [comment]
This should be fixed when the game next updates.

**Comment by megabro** [comment]
Seems to have fixed it! 👍
