### ISSUE TITLE
CollisionEventData.Body for ragdolls

### ISSUE THREAD

**Issue by nikita-strelok** [Facepunch/sbox-issues#1233]
**What can't you do?**
I can't get exactly what body of ragdoll is colliding.

**How would you like it to work?**
CollisionEventData will have field Body or BodyIndex for manually getting.

**What have you tried?**
I have really don't know how can i temporarily implement this

**Additional context**

**Comment by robotboy655** [comment]
https://asset.party/api/Sandbox.CollisionEntityData.PhysicsShape
