### ISSUE TITLE
Task error when exiting to main menu

### ISSUE THREAD

**Issue by CrazyBloo** [Facepunch/sbox-issues#1235]
**Describe the bug**
The error below happens when exiting to the main menu if the game mode has a async task in it.

Attempted to use an expired MainThreadContext in task method Sandbox.TaskSource.Delay
This is probably because a task was left running after ending a game session

I'm assuming the tasks aren't being disposed correctly?

**To Reproduce**

1. Start a game with an Async Task with a Delay on it
2. Exit game to main menu
3. See error

**Expected behavior**
Exit game without error

**Additional context**
I'm assuming this error is related as well, I got it when loading into a game after playing minigolf:

Attempted to use an expired MainThreadContext in task method Sandbox.PlatformEntity.DoMove
This is probably because a task was left running after ending a game session

**Comment by Alf21** [comment]
https://github.com/Facepunch/sbox-issues/issues/387

**Comment by Alf21** [comment]
Receiving the same error after some update now as well, even with error catching. The error is printed internally and not passed on, so error catching isn't possible.

`await GameTask.DelaySeconds(1);` is throwing the error internally, other GameTask or Game.Task functions does not work as well (as I guess it's using the same function internally).
