### ISSUE TITLE
CSS 4 value padding is in wrong order

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#124]
**Describe the bug**

Padding doesn't follow the CSS spec:

* `padding: <all>`
* `padding: <top/bottom> <left/right>`
* `padding: <top> <left/right> <bottom>`
* `padding: <top> <right> <bottom> <left>`

Sbox gets it right for all but the last one:

* `padding: <all>` - is correct
* `padding: <top/bottom> <left/right>` - is correct
* `padding: <top> <left/right> <bottom>` - is correct
* `padding: <left> <top> <right> <bottom>`

Final case parsing code in Styles.SetPadding should change from:

```csharp
      this.PaddingLeft = new Length?(outval1);
      this.PaddingTop = new Length?(outval2);
      this.PaddingRight = new Length?(outval3);
      this.PaddingBottom = new Length?(outval4);
```

to

```csharp
      this.PaddingTop = new Length?(outval1);
      this.PaddingRight = new Length?(outval2);
      this.PaddingBottom = new Length?(outval3);
      this.PaddingLeft = new Length?(outval4);
```

**Comment by handsomematt** [comment]
This also applies to margin

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
