### ISSUE TITLE
Animgraph: Grid sends comment nodes flying when trying to resize them

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#1245]
**Describe the bug**
Resizing a comment node from the top sends them flying when you have the grid turned on

**To Reproduce**

1. Create Comment Node
2. Resize from the top (top left, top middle, or top right)
3. ???
4. Profit

**Expected behavior**
Usually, you can resize comment nodes in any direction to group up different nodes, moving the comment node will move all of the nodes inside it, as if to group them.

**Screenshots**

https://user-images.githubusercontent.com/86626409/140824361-01f81d9a-fb0d-4f02-bf0a-eebf766538ff.mp4

**Additional context**

I have grid snapping set to 16.

**Comment by aylaylay** [comment]
should be fixed
