### ISSUE TITLE
Player movement not following its frame of reference

### ISSUE THREAD

**Issue by Lexa013** [Facepunch/sbox-issues#1246]
**Describe the bug**
The player movement does not follow the platforms movement

**To Reproduce**

1. Load the map `test/velocity`
2. Go on any platform

**Expected behavior**
The player will fall or "glitch (trembling)"

**Screenshots / Videos**
[2021 11 08 23 49 33](https://youtu.be/Veg6r6PCwpo)

**Additional context**
N/A

**Comment by aylaylay** [comment]
This should be fixed now when standing on a pusher, the pushing code needs to be reimplemented in C# as some point though.
