### ISSUE TITLE
ent_button causes auto close delay to be ignored on doors

### ISSUE THREAD

**Issue by FBIsMostUnwanted** [Facepunch/sbox-issues#1247]
**Describe the bug**

ent_button used to open or toggle a door causes auto close to happen after a few seconds even if set to -1 

**To Reproduce**
1. Make a button
2. Make an output targeted to a door and have it toggle or open the door
3. Set auto close delay to -1 on the target door
4. Compile the map and press the button
**Expected behavior**
The door should stay open since auto closed delay is set to -1

**Comment by handsomematt** [comment]
Should be fixed when the build hits steam (2-3 mins), you won't need to recompile your map. Please test and close if they work as expected again.
