### ISSUE TITLE
ent_door movement type always set to moving regardless of what's selected under "movement type"

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1248]
**Describe the bug**

ent_door entities refuse to rotate and only move side to side, even if I had set "movement type" to "rotating".

**To Reproduce**

1. create a mesh and turn it into an ent_door entity.
2. set movement type to "rotating".
3. distance to 90.
4. compile and observe.

**Expected behavior**

to rotate as it is configured to do so.

**Additional context**
vmap and vpk attached below
[ent_door_bug01.zip](https://github.com/Facepunch/sbox-issues/files/7501383/ent_door_bug01.zip)

**Comment by handsomematt** [comment]
Should be fixed when the build hits steam (2-3 mins), you won't need to recompile your map. Please test and close if they work as expected again.

**Comment by QuackCocaine** [comment]
Works as expected now thanks!
