### ISSUE TITLE
Make generated Solution and Project-Files cross-platform compatible

### ISSUE THREAD

**Issue by Nutcake** [Facepunch/sbox-issues#1249]
**What can't you do?**
At the moment the generated .sln and .csproj files contain absolute file-paths that contain casing that is inconsistent with the actual game-files. For example, the `addons`-folder on disk is all lowercase (at least on Linux), while the path in the generated solution file is spelled `Addons`. This is not a problem on file-systems that are case insensitive (Windows) but results in unusable files on case-sensitive file-systems (Linux). 

Additionally, when running under wine, the host root partition is mounted as `Z:\`, which is not a valid path outside of wine. The project files use absolute paths which contain this virtual disk and are thus not usable from the host system. This means that project-files generated when running sbox through wine are not openable by an IDE running on the native system.

**How would you like it to work?**
The first point should be relatively easy to implement, just change the generated path to have consistent lowercase casing. This should not have an impact on Windows users, since their system is case insensitive. Technically it's possible to enable case-sensitivity on Windows, so this would fix that usecase too.

The second point might be a bit more annoying. I don't know if .sln and .csproj files allow using relative paths and if switching to those might break other things somewhere, but that would be the preferred solution in my eyes. An alternative would be detecting if sbox is running under wine (this is easily doable by checking for the existence of certain registry entries) and having the project files generated without the `Z:` drive prefix in file-paths. This should always result in a resolvable path under Unix systems.

**What have you tried?**
Doing the changes I presented manually results in the solution and projects loading fine, but is annoying since the game regenerates these files automatically. 

**Additional context**
Here's an image describing what I mean:
![solution](https://user-images.githubusercontent.com/10452593/140985432-9f0f90cd-f702-4eb8-8c38-aef2ee1b7aa5.png)

**Comment by ogniK5377** [comment]
Okay I switched the solution generation to use the correct addon folder & the sln & csproj files should be relative for the most part, Should be out in the next update; let me know if you run into any issues with it 👍

**Comment by Nutcake** [comment]
Very cool, thanks! However the .dll includes in the base and menu .csproj files still seem to be absolute.
See lines 26-29 in both files after fresh generation. Any chance those could get changed too? Relative paths seem to work fine there too, when manually editing the paths.

**Comment by ogniK5377** [comment]
The analyzers and references should also be relative now 👍 Should be in the next update, lmk if it works or if you have any more issues

**Comment by Nutcake** [comment]
That works perfectly, thank you!
