### ISSUE TITLE
Base WalkController/MoveHelper gets stuck while sliding against walls at shallow angles

### ISSUE THREAD

**Issue by MuffinTastic** [Facepunch/sbox-issues#1250]
**Describe the bug**
Walking along or strafing into walls at shallow angles causes the player to get stuck.
To be super specific, by "shallow angles" I mean the player's Velocity is close to being parallel with the wall upon collision.

**To Reproduce**

1. Choose any gamemode that uses the base WalkController, for example facepunch.sandbox
2. Choose any map with nice flat walls to test with, for example facepunch.flatgrass
3. Get your velocity close to parallel to the wall by walking along the wall at an angle of <24 degrees and only holding W, or strafing into it
4. See your view jitter as you repeatedly get stuck and automatically unstuck

**Expected behavior**
Smooth movement

**Screenshots**

https://user-images.githubusercontent.com/10884425/141021069-59dd2b1b-35da-4311-b6f2-e093bccd0f31.mp4

**Additional context**

This is a lot more noticeable if you crouch, and also at high velocities.

**Comment by aylaylay** [comment]
I have pushed a small change that should help

**Comment by MuffinTastic** [comment]
It seems to have worked a treat, thanks!
