### ISSUE TITLE
Light Entities don't have Tags in Hammer

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#1251]
**Describe the bug**
Tags are just normal Entities in C# therefore they also have the Tags property. but the FGD doesn't include that.
Which makes it not show up in Hammer. These can be useful to toggle lights based on Tags instead of having to use Targetname using I/O.

this is likely caused by Light Entities having their own FGD, instead of getting generated

**To Reproduce**

1. Place any Light Entity
2. See they don't have Tags as a KeyValue

**Expected behavior**
They should have the Tags Property like any other Entity.

**Comment by handsomematt** [comment]
The light entities are now auto generated, so this should no longer be the case. Can you confirm @Adesii ?

**Comment by Adesii** [comment]
Yeah, they now have Tags
