### ISSUE TITLE
Props can't break on input [Inputs broken: break & kill]

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [Facepunch/sbox-issues#1253]
**Describe the bug**

When setting an input to break a prop_dynamic it doesn't do anything, regardless of predefined breakpieces within the model,
same with prop_physics.

**To Reproduce**

1. In Hammer, set a prop_dynamic / prop_dynamic_override or prop_physics to break or kill using an input
2. Make sure it has breakpieces defined within the model
3. Ingame, activate the input and see nothing happens

**Expected behavior**
"Break" should break the model into its breakpieces.
"kill" should remove the prop from the map.

*Screenshots*
https://i.imgur.com/W912bWJ.png

**Additional context**
Break won't work whether the model is defined to be a prop_physics or prop_override in modeldoc.

**Comment by robotboy655** [comment]
prop_physics should work with Break input, prop_dynamic is not in c# so it won't work with c# entities.

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
> prop_physics should work with Break input, prop_dynamic is not in c# so it won't work with c# entities.

It doesn't work unfortunately.

**Comment by robotboy655** [comment]
Break definitely works, added `Delete` to prop_physics to replace `Kill`
