### ISSUE TITLE
env_explosion doesn't work ingame

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [Facepunch/sbox-issues#1254]
**Describe the bug**
env_explosions don't do aynthing when triggered

**To Reproduce**

1. Place a env_explosion in Hammer
2. Set an input to make it explode
3. Nothing will happen ingame

**Expected behavior**
It should explode

**Additional context**
Only way to get explosions working right now are through models within modeldoc.

**Comment by robotboy655** [comment]
Added `ent_explosion`, use that one instead. It will also appear in the Hammer's Entity tool under "Effects" category now.
