### ISSUE TITLE
trigger_teleport & trigger_hurt don't work when standing within them

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [Facepunch/sbox-issues#1255]
**Describe the bug**
Trigger_hurt and trigger_teleport only work when you walk into them.
If you stand within them when they get activated, they won't do anything to you.

**To Reproduce**
1. Create a trigger_teleport or trigger_hurt
2. Set them to be disabled on start
3. Activate them on an input
4. Load ingame and stand within the trigger
5. Activate the input

**Expected behavior**
It should either teleport you to a destined position or hurt you when enabled.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates
