### ISSUE TITLE
snd_event_point "Start On Spawn" doesn't work

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1257]
"Start On Spawn" actually does work, but all sounds seem to get disabled about half a second after the map starts.

This means I hear my map's ambient sound for half a second, then it's silent.

https://user-images.githubusercontent.com/39461072/141223453-308cbb68-e2c5-4814-8983-01b62471f72f.mp4

**Comment by gvarados1** [comment]
To fix this I just delay the sound by a second.
![image](https://user-images.githubusercontent.com/39461072/141674013-3f29fbbc-572d-4f18-9252-95d95b35fe67.png)

**Comment by robotboy655** [comment]
The way sounds work for this need reworking, so that sounds that are started before a player joins still sync up.

**Comment by gvarados1** [comment]
This is still an issue. We can't have sounds that start on map spawn.

**Comment by aylaylay** [comment]
I've made the sounds start on the client, see if that fixes it

**Comment by gvarados1** [comment]
I think this was fixed with the new sound systems?
