### ISSUE TITLE
Cloth model is broken

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1258]
models/cloth/cloth.vmdl is broken
![image](https://user-images.githubusercontent.com/39461072/141233898-ce0ca309-7c69-49d0-b248-85b1dbc9ca08.png)

**Comment by robotboy655** [comment]
Having the broken cloth model in Hammer spams this assert:
![sbox-dev_3wnLV9wvyt](https://user-images.githubusercontent.com/3299036/151243093-e5c1a9dc-00e0-4232-90cb-582050bb52fd.png)

**Comment by gvarados1** [comment]
still broken 
![image](https://user-images.githubusercontent.com/39461072/158271391-801aba32-9d23-4bef-8bc8-0ab13ccab933.png)
