### ISSUE TITLE
Chat message event

### ISSUE THREAD

**Issue by Erlite** [Facepunch/sbox-issues#126]
**What can't you do?**
Catch all chat messages sent by users. Could be useful to act upon them for things like chat commands or minigames.
Allow us to override displaying the message to other users via a return value.
**How would you like it to work?**
```cs
[Event("server.playersay")]
private bool OnChatMessage(ChatMessageArgs args)
{
    var sender = args.Sender;
    var msg = args.Message;

    if (msg.StartsWith("!"))
    {
        return true; // Don't display the message to other users.
    }
    
    // Do stuff.
    return false;
}
```

**What have you tried?**
N/A, would require modifying the base gamemode (implemented the above solution myself, however was met with an issue with events #94 )

**Additional context**
None

**Comment by Trojaner** [comment]
There should be an option to cancel default behavior (e.g. in case you want to process it as command and dont want it to be displayed)

**Comment by Erlite** [comment]
Yeah, in that case, events would need to be able to return values (not the case currently).
