### ISSUE TITLE
Make Sounds Nullable

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#1260]
**What can't you do?**
Sounds right now are not a nullable struct. This would be extremely useful for playing looping sounds when they don't exist with a simple `sound ??= Sound.FromScreen()`, sounds could also be de-referenced for garbage collection.

**What have you tried?**
In the cases where this is needed, simply having a boolean called `playSound` works just fine, but isn't as ideal or clean as just allowing the sound to be nullable.

**Comment by ogniK5377** [comment]
Anything preventing you from just using nullable types?
```cs
Sound? mySound = null;

mySound ??= Sound.FromScreen()
```

**Comment by Geeknerd1337** [comment]
There is not, I thought it wasn't working for some reason. Closing the issue.
