### ISSUE TITLE
Allow us to get spectrum data on a sound.

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#1261]
**What can't you do?**
In Unity, there is the following function:
```csharp
float[] _samples = new float[512];
_audioSource.GetSpectrumData(_samples, 0, FFTWindow.Blackman);
```
This allows you to store the spectrum data of an audio file in a float array, with the ability to select specific audio spectrum windows.

You can use this to analyze sound data and do stuff like have level geometry or effects react to sound. Additionally this could be used to perform manual effects like high and low pass filters then re-write them to an audio stream.

**How would you like it to work?**
The same as it does in Unity, or as close as we can reasonably get to it. The following scripting reference from Unity provides more information as to the various FFTWIndows.

https://docs.unity3d.com/ScriptReference/AudioSource.GetSpectrumData.html

**Comment by xezno** [comment]
You can use [MusicPlayer.Spectrum](https://asset.party/api/Sandbox.MusicPlayer.Spectrum)
