### ISSUE TITLE
Ingame Console doesn't open on QWERTZ Keyboard layout.

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#127]
**Describe the bug**
Depending on the Keyboard layout it won't open the Ingame Console.

**To Reproduce**
1. Choose German or other QWERTZ keyboard layout.
2. Try to open the Console ingame. using the ` key. ( ^ on the QWERTZ layout)
3. See it not opening. unless switching to a QWERTY layout.

**Expected behavior**
Opening the ingame Console when pressing the same key independent of Keyboard layout.

**Additional Info**
Im using a German Keyboard and it has "Deadkeys" (keys that are used for accents above letters. so the first press is nothing)
but even if i use a custom QWERTZ layout without "Deadkeys" it still won't open.

**Comment by Trojaner** [comment]
I have a German keyboard too, it opens/closes the ingame console with F1 for me (didnt do any binds).

**Comment by Adesii** [comment]
> I have a German keyboard too, it opens/closes the ingame console with F1 for me (didnt do any binds).

OH wow... you are right. that is really odd to have 2 keys that do the same. Thanks for the Info

**Comment by SebbeJohansson** [comment]
F1 no longer opens console. I am using a swedish qwerty keyboard and I can not close console after opening it.

**Comment by SebbeJohansson** [comment]
F2 seems to have replaced it.
