### ISSUE TITLE
Missing NPC Collision Group

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1271]
There is no CollisionGroup.NPC

![image](https://user-images.githubusercontent.com/39461072/141408435-50bf94e0-d320-42d5-b981-c4f921d43ea9.png)

**Comment by garrynewman** [comment]
We're trying to move away from collision groups - what do you need it for?

**Comment by gvarados1** [comment]
I thought I needed this for NPC Clip, but I just needed to make a custom MoveHelper and WalkController.
This would still be used for NPC Clip on physics based NPCs though.

**Comment by garrynewman** [comment]
This is something I need to really go over and fuck up.. the collision system is very complicated right now so I'd love to go in and massively simplify it.

**Comment by gvarados1** [comment]
That'd be great!
