### ISSUE TITLE
Shadows rendered on linebreaks

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#1272]
Text with shadow styles applies will render unwanted shadows on linebreaks

https://files.facepunch.com/crayz/1b1211b1/sbox_2021-11-12_03-13-54.png

**Comment by AWildErin** [comment]
This is pretty much #1202 which was closed but seems to not actually be fixed. It seems like it was fixed in the pictured commit but `text-shadow` still doesn't work 

![image](https://user-images.githubusercontent.com/28122025/141524552-37776970-ca3e-4511-b9b1-89cc9fdb6405.png)
