### ISSUE TITLE
Parametered constructors do not get called on the client

### ISSUE THREAD

**Issue by kidfearless** [Facepunch/sbox-issues#1274]
**Describe the bug**
Model entities do not call parametered constructors on the client. They always call the empty constructor on the client, but will call the parametered constructor on the server.

**To Reproduce**

```
	public class DerrivedEntity : ModelEntity
	{
		public string Value { get; set; }
		private string Location => Host.IsClient ? "[Client]" : "[Server]";

		public DerrivedEntity()
		{
			Log.Info( Location + "(Default Contstructor)" + this.Value );
		}

		public DerrivedEntity(string value)
		{
			this.Value = value;
			Log.Info( Location + "(Parametered Contstructor)" + this.Value );
		}
	}

	partial class MinimalPlayer : Player
	{
		public override void Respawn()
		{
			var ent = new DerrivedEntity( "" );
			base.Respawn();
		}
	}
```
Create an instance of DerrivedEntity with any string passed in.
The game will log:
> [Server](Parametered Contstructor)
> [Client](Default Contstructor)

**Expected behavior**
> [Server](Parametered Contstructor)
> [Client](Parametered Contstructor)

**Screenshots**
![image](https://user-images.githubusercontent.com/13614349/141514297-50cc3296-39da-4fed-a15d-4815a7d1e1aa.png)

**Additional context**
I'm trying to load the defaults of weapons through a config file, so that new weapons can be added and removed without needing to create a class for each one. I'm wanting to be able to assign the viewmodel on the client, but it always calls the empty constructor on the client instead. Any help working around this would also be very much so appreciated, as I've been trying to wrap my head around this for the past 3 days.

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.
Nothing In particular, the code just uses the minimal gamemode example to create the model entity when the player respawns.

**Comment by handsomematt** [comment]
This isn't a bug, this is how networked entities work.

**Comment by kidfearless** [comment]
Is there any way I could set the view model on the client from the server?

**Comment by handsomematt** [comment]
Ask for help in Discord or on the forums.
