### ISSUE TITLE
Allow Us To Get The RealTimeInSeconds Position of A Sound Relative to When It Started

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#1275]
**What can't you do?**
Right now if you want to sync up audio with in-game events you need to play a sound at the same time as a RealTimeSince variable. The issue is there seem to be some cases (specifically alt+tabbing for long periods of time) and recompiling which can have the audio stream go out of sync with the real time since.

I'm not sure how practical this is, but a variable that gives us the sounds current "position" in real time would be absolutely wonderful for syncing things up.

**How would you like it to work?**
```csharp
Sound = Sound.FromScreen( "DotComGuy" );
Log.Info(Sound.RealTimeSincePlayed);
//Or alternatively
Log.Info(Sound.PlayheadRealTimePosition);
```
**What have you tried?**
Running a RealTimeSince set to 0 the moment the song is played. This is reliable enough to maybe make the above unnecessary or superfluous, but it still would be nice to have.

**Comment by ogniK5377** [comment]
Should be in the next update, I pushed out `Sound.Elapsed` which gets the playhead in seconds from the start of the sound. I also added `Sound.Finished` to let you know that the sound has finished or not too

**Comment by Geeknerd1337** [comment]
Sound.Elapsed and Sound.Finished both work wonderfully. Ideally we'd have a Sound.Looped event that we can subscribe to. I also notice that elapsed time and the actual position of the playhead become descynced if you're alt+tabbed for long periods of time, this is ultimately minor and would require testing on my part to validate, and might not be an issue with the DSP stuff Ognik exposed today, but it felt worth mentioning. Closing since the features here have been added.
