### ISSUE TITLE
Custom assets fail to compile when they should.

### ISSUE THREAD

**Issue by AyeTSG** [Facepunch/sbox-issues#1278]
Custom assets are failing to compile when they should.

**To Reproduce**

1. Create a custom asset type
2. Create an asset of said type
3. Save it into your addon
4. Re-compile your game

**Expected behavior**

The asset should compile into an ``_c`` version of itself, but it does not.

**Comment by zeo** [comment]
Is the name longer than 7 characters?

**Comment by AyeTSG** [comment]
nope, the name itself falls under 8 characters.

![image](https://user-images.githubusercontent.com/49595354/141602193-ad2cb68c-adcb-4f3c-9de6-5950fe4d763c.png)

**Comment by handsomematt** [comment]
if this is still a problem for you make a proper issue with reproducible code
