### ISSUE TITLE
Linked hammer properties of type Rotation do not work

### ISSUE THREAD

**Issue by Fear837** [Facepunch/sbox-issues#1279]
**Describe the bug**
This issue affects entities that are linked to hammer and have custom properties of type `Rotation`. When such an entity
is placed on a map and when the property is set to some value, the actual value ingame will always be `Rotation.Identity` instead of the value that was manually set in hammer.

**To Reproduce**

1. Write an entity class that is linked to Hammer and has a property with the type `Rotation`
  1.1. By declaring the `[Library]` and `[Hammer.EntityTool]` attributes
  1.2. and declaring a property like so: `[Property(Title = "abc")] public Rotation Abc { get; set; }`
2. Open any map with hammer
3. Place that entity somewhere and set the rotation property to some value that is not `Rotation.Identity`
4. Compile and load the map
5. See that the entity exists and that the value of the rotation property is `Rotation.Identity`

The following gist can be used to reproduce: https://gist.github.com/Fear837/36315dad123a51915b672934b4bdfe0a

**Expected behavior**

The value of the rotation property should be the one that was set in hammer

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by Fear837** [comment]
Seems to be fixed, thanks!
