### ISSUE TITLE
Clothing Resources don't get registered for clients other than the host

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#1280]
**Describe the bug**
Clients cannot locate Clothing items through `Resource.FromId<Clothing>()` due to them not being registered. It only works when ran on the client who is hosting the game and/or on the server. Because of this I am unable to give clothes to my AnimSceneObject on any client that isn't the host.

**To Reproduce**
```cs
public static void ClothingTest()
{
	Clothing item = Resource.FromId<Clothing>( 1918103397 );
	Log.Info( item != null ? item.Name : "null" );
}
```
When ran on host's client:
> hardhat.yellow

When ran on any other client:
> null

**Expected behavior**
Return the corresponding clothing item on any client.

**Comment by DevulTj** [comment]
This is intended as resource IDs are hashes - it doesn't exist on the client, because yes, the resource doesn't exist yet.
