### ISSUE TITLE
Hammer - Collision Group Override on prop_physics Doesn't Work Properly

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1284]
Collision Group Override is broken. Setting it to to COLLISION_GROUP_DEBRIS isn't debris, and COLLISION_GROUP_ALWAYS makes it act like a ladder.
![image](https://user-images.githubusercontent.com/39461072/141672817-2045a1c5-c6f3-4ac3-9abf-a7b8325b90bb.png)

**Comment by gvarados1** [comment]
We need to remove the Solid collision layer for debris to work as intended.
![image](https://user-images.githubusercontent.com/39461072/141673948-421a8c53-03a7-4eb4-ab26-99f6575215c3.png)

**Comment by robotboy655** [comment]
Should be all fixed up.

**Comment by gvarados1** [comment]
Looks good. Thanks :)
