### ISSUE TITLE
Cannot run an event with an argument.

### ISSUE THREAD

**Issue by Erlite** [Facepunch/sbox-issues#129]
**Describe the bug**
I get an exception when trying to run an event and pass an argument with it.

**To Reproduce**

```cs
var args = new SomeArgs(1337);
Event.Run("server.playersay", args);

// Game class.
[Event("server.playersay")]
public void MyEventHandler(SomeArgs args)
{
    _log.Info("Hey!");
}
```
**Expected behavior**

The event is ran without any issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/25248023/117718387-4dbbb200-b1dc-11eb-9b26-8ba8d1de0cc6.png)

**Comment by Trojaner** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/94 😁

**Comment by Erlite** [comment]
Indeed, didn't see thanks :D
