### ISSUE TITLE
Indicate support for nullable reference types in .addon

### ISSUE THREAD

**Issue by goaaats** [Facepunch/sbox-issues#1290]
**What can't you do?**
Effectively enable nullable reference types via the generated csproj.

Since C# 8, you can indicate global support for nullable reference types by specifying `<Nullable>enable</Nullable>` in the csproj. This enables useful hints in IDEs that prevent NREs if paid attention to, and if the codebase is being written with it in mind.
.NET 6 puts this in csproj's by default for new projects.

**How would you like it to work?**
Add a property to the .addon that sets this property to `enable` in the generated csproj.

```json
{
    "sharedassets": "*.*",
    "ident": "my.ident",
	"nullable": true
}
```

**What have you tried?**
Setting the property manually in the generated csproj.
This works, until the game is restarted, which will cause the csproj to be regenerated without the property set. This will cause IDEs to be confused, as they will expect code without nullable references and disable annotations.

**Additional context**
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/nullable-reference-types
https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

**Comment by peter-r-g** [comment]
@handsomematt Why was this marked as wontfix? We have the ability to set a csproj root namespace and it would be nice to have this option available for the people that find use in it.
