### ISSUE TITLE
Some value changes aren't being networked

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#1291]
**Describe the bug**

Networked properties seem to have some reliability issues - with some values not being networked at all

**To Reproduce**

1. Go into pool
2. Add a bot thru `bot_add`
3. Try and play the game - the UI won't update past the initial stages. 

It appears that the game state isn't being networked properly - which makes the game impossible to play.

![image](https://user-images.githubusercontent.com/12881812/142057247-8fea49d6-2649-4774-a806-a917c1976fca.png)

**Expected behavior**

The UI should look like this:

![image](https://user-images.githubusercontent.com/12881812/142056916-3350fe5c-0ee9-404c-bfb2-025a9abf4f2c.png)

**Additional context**

This issue is also present in Instagib - the UI just doesn't update:

![image](https://user-images.githubusercontent.com/12881812/142056972-b32def07-2398-4b34-9e41-616b2ca44ad8.png)

Neither Instagib nor Pool have had code changes recently, which leads me to believe this is an issue with s&box's networking - not either of these gamemodes

**Comment by handsomematt** [comment]
Should be sorted when the update hits Steam.

**Comment by xezno** [comment]
All seems to be working now, thanks!
