### ISSUE TITLE
Hammer - Lift Color From Blend

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1292]
We need to be able to lift colors that we've painted on vertices. If I switch colors, I can't get the color I was using previously.

In this example, I want to select the color I used for the wall trim so I can use it elsewhere. I can't select it though, so I need to choose a new similar looking color.
![image](https://user-images.githubusercontent.com/39461072/142090081-db9b0b6f-13f9-454c-8590-eaa5700691de.png)

**Comment by aylaylay** [comment]
Can't you use the color picker?

**Comment by gvarados1** [comment]
No. Color picker would only work on pure white textures.

**Comment by aylaylay** [comment]
Done
