### ISSUE TITLE
Whitelist Json

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#13]
System.Text.Json.JsonSerializer
System.Text.Json.JsonSerializerOptions
System.Text.Json.Serialization.JsonIgnore
System.Text.Json.Serialization.JsonInclude

It may be possible to whitelist the entire `System.Text.Json.*` namespace but not sure if there is anything dangerous there.

**Comment by garrynewman** [comment]
I need to check this over before moving forward, just want to make sure there's no way to create classes by name or something, without referencing the type in your code. I can't imagine there is but I want to give it a once over.

**Comment by LiamProwse** [comment]
I'd argue that Newtonsoft's JSON would be a far better implementation of JSON and could be provided in the Sandbox namespace, there's plenty that could be stripped down in there.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
