### ISSUE TITLE
New Logger should have overload with object parameter

### ISSUE THREAD

**Issue by nikita-strelok** [Facepunch/sbox-issues#1300]
**What it is**
 public void Info(string message)
 public void Warning(string message)
 public void Error(string message)
...
these methods accept only string

**What it should be**

there also should be
 public void Info(object obj)
 public void Warning(object obj)
 public void Error(object obj)
...
for printing numbers, vectors and etc

**Comment by garrynewman** [comment]
Done, thanks!
