### ISSUE TITLE
Implement Ctrl combos for TextEntry

### ISSUE THREAD

**Issue by MuffinTastic** [Facepunch/sbox-issues#1301]
**What can't you do?**
Currently you cannot use standard Ctrl combos for navigating and editing text.

- Ctrl+Left Arrow - Skip cursor to the previous word boundary
- Ctrl+Right Arrow - Skip cursor to the next word boundary
- Ctrl+Shift+Left Arrow - Skip cursor and select up to the previous word boundary
- Ctrl+Shift+Right Arrow - Skip cursor and select up to the next word boundary
- Ctrl+Home - Skip cursor to the beginning of the first line
- Ctrl+End - Skip cursor to the end of the last line
- Ctrl+Shift+Home - Skip cursor and select up to to the beginning of the first line
- Ctrl+Shift+End - Skip cursor to the end of the last line
- Ctrl+Backspace - Delete from cursor until previous word boundary
- Ctrl+Delete - Delete from cursor until next word boundary

Ctrl+Home/End and Shift variants would only noticeable if the TextEntry is multiline, otherwise they would behave the same as Home/End in practice.

**How would you like it to work?**
Just like everywhere else. Ctrl+Home/End not shown:

https://user-images.githubusercontent.com/10884425/142253166-f9ca12cb-a796-4153-8afd-3bdbe087b753.mp4

**What have you tried?**
Implementing a bunch of them myself. Works just fine, but they should be part of the base TextEntry.

**Additional context**
For reference:
![wordboundaries](https://user-images.githubusercontent.com/10884425/142487704-a237d49f-b2f4-49fc-ba63-1fe169821339.png)
With it skipping all the whitespace until the next word.

**Comment by Rohansi** [comment]
Would be good to list out all the possible combos in this issue since it's not only for moving the cursor around quicker

**Comment by MuffinTastic** [comment]
Good point, I've edited in all the strictly Ctrl related stuff. It should be noted that Ctrl+Home/Ctrl+End as described work the same as how unmodified Home/End currently behave, and that Home/End are actually incorrect right now for multiline TextEntrys. Also, Page Up/Page Down currently do nothing. Should I edit this issue again to make it all-encompassing, or make some new ones?

**Comment by MuffinTastic** [comment]
Added by ogniK in commits `a692b8`, `ce9ff7`
