### ISSUE TITLE
Garbage Entities in Hammer

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1304]
There's a TON of garbage entities in hammer. Here's the path tool:
![image](https://user-images.githubusercontent.com/39461072/142496167-afb2a43e-48a7-42e5-8d53-d07972ff2eea.png)

Half of these shouldn't be in hammer. FGD generation should be OPT-IN, not OPT-OUT. That would solve this issue.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
