### ISSUE TITLE
Whitelist `System.Linq.Expressions`

### ISSUE THREAD

**Issue by Erlite** [Facepunch/sbox-issues#131]
**What can't you do?**
Use `System.Linq.Expressions` to determine the type of a delegate from a `MethodInfo`.

**How would you like it to work?**
Being able to include it would allow me to parse chat messages into arguments in order to call a `Delegate` from an `object[]` of values. Doing so requires the delegate type:

```cs
if (commandArguments.Count > 0)
{
    // Dynamically generate the delegate for the command's method.
    var paramTypes = info.GetParameters()
        .Select(p => p.ParameterType)
        .Append(info.ReturnType)
        .ToArray();
    
    // Not as fast as a known delegate signature, and requires executing the command with DynamicInvoke().
    var delType = Expression.GetDelegateType(paramTypes);
    cmd.MethodDelegate = Delegate.CreateDelegate(delType, module, info);   
}
```

**What have you tried?**
Using it, compiler ~~refuses~~ does not find the namespace at all.

*Note: this would only really be useful alongside Reflection, so I suppose it's not a priority until we have access to it or a wrapped version. This would likely need to be wrapped for safety reasons.*

**Comment by garrynewman** [comment]
I don't know enough about this API to determine whether it's needed or whether it's safe to expose. If it's only really useful with Reflection, maybe it's useless to expose?

**Comment by Erlite** [comment]
Yeah I guess, I haven't extensively used it but from what I can see it's not the safest yea :/ I mostly used it to create a delegate from a `MethodInfo` to make running it dynamically a little cheaper, I suppose I can just get rid of it if we get Reflection wrapped.

**Comment by garrynewman** [comment]
We already have Sandbox.Reflection - if you want stuff added to that just request it and I'll look at it. Reflection is mostly fine as long as we can restrain the types people are allows to reflect.

**Comment by Erlite** [comment]
Will do, thanks.

**Comment by Manonox** [comment]
Can't use MoonSharp because of this, exact same System.Linq.Expression thing missing.
I wonder if the 'request' has been made, or this was looked into at all (@garrynewman )
