### ISSUE TITLE
func_shatterglass - Motion Disabled Property

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1311]
We need a "Motion Disabled" property for func_shatterglass. I also want to have glass on the ceiling that technically isn't in a frame, so it falls when broken.

https://user-images.githubusercontent.com/39461072/142579298-044f11d1-c5eb-4954-ba98-b8f990624f55.mp4

**Comment by gvarados1** [comment]
accidently tagged this as bug. whoops :)

**Comment by robotboy655** [comment]
Replaced "In a frame" property with a "constraint" property which now has an option to do this. 

I felt this is more logical than adding a "Motion Disabled" property which would do nothing if you have "In a frame" enabled.

**Comment by gvarados1** [comment]
looks good :)
