### ISSUE TITLE
Blend Materials aren't tagged as Blend Material

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1313]
Blend Materials aren't being tagged as Blend Material in the asset browser
![image](https://user-images.githubusercontent.com/39461072/142582220-a24137b6-36f8-46ab-b628-342f3d2b2ae0.png)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

Please take note that existing blendable materials will need to be recompiled in order to get the tag.

I have done this for the ones that ship with the game.

**Comment by gvarados1** [comment]
thanks :)
