### ISSUE TITLE
Hotload stops networked properties from being sent to the client

### ISSUE THREAD

**Issue by MoonlyDays** [Facepunch/sbox-issues#1315]
**Describe the bug**
The first hotload after the game start breaks networked properties and they stop being transmitted to the client. They only update a single time after addon hotloads again.

**To Reproduce**
1. Create any `[Net]` property and continously keep updating it on the server and see the same value being sent to the client just fine.
2. Hotload the addon and see that property on the server keeps being updated, but property on the client stays untouched.
3. Hotload the addon again to see that client synced its value with the server, but only once. 

**Expected behavior**
Properties should still be sent to the client after addon hotload.

**Screenshots**

https://user-images.githubusercontent.com/32462579/142670896-ea783235-e215-4063-832d-d5b115e6b43d.mp4

**Additional context**
This was also tested on mininal gamemode. The only way to fix this right now is to restart the whole server and then it'll be fixed until the next hotload.

**Code that I tested this with**
```csharp
partial class NetTest : Entity
{
	[Net] public int IntTest { get; set; }
	[Net] public IList<int> ListTest { get; set; }
	[Net] public IDictionary<int, int> DictionaryTest { get; set; }

	public NetTest()
	{
		Transmit = TransmitType.Always;

		IntTest = 0;
		for ( int i = 0; i < 5; i++ )
		{
			ListTest.Add( 0 );
			DictionaryTest[i] = 0;
		}
	}

	[Event.Tick]
	public void Tick()
	{
		if ( IsServer )
		{
			IntTest++;
			for ( int i = 0; i < 5; i++ )
			{
				ListTest[i]++;
				DictionaryTest[i]++;
			}
		}

		DebugOverlay.ScreenText( IsServer ? 0 : 1, $"[{(IsServer ? "SV" : "CL")}] IntTest = {IntTest}" );

		for ( int i = 0; i < 5; i++ )
		{
			DebugOverlay.ScreenText( (IsServer ? 0 : 1) + 3 + i * 2, $"[{(IsServer ? "SV" : "CL")}] ListTest[{i}] = {ListTest[i]}" );
			DebugOverlay.ScreenText( (IsServer ? 0 : 1) + 14 + i * 2, $"[{(IsServer ? "SV" : "CL")}] DictionaryTest[{i}] = {DictionaryTest[i]}" );
		}
	}
}
```

**Comment by handsomematt** [comment]
Should be fixed in a few when the update hits Steam, let us know if not.

**Comment by MoonlyDays** [comment]
Seems to be fixed now. Thanks for a quick response! I am closing this.
