### ISSUE TITLE
Hammer.Skip attribute should be obsolete and instead in a different class/namespace

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1316]
**What it is**
the Skip Attribute for autogen is inside the Sandbox.Hammer namespace right now, despite being used for asset type parsing as well.

**What it should be**
Some generic namespace like Sandbox.AutoGen or whatever

**Comment by gvarados1** [comment]
good idea

**Comment by robotboy655** [comment]
Yeah I agree, it should be something like Tools.Skip or smth.

**Comment by handsomematt** [comment]
Surely it makes way more sense to opt in to wanting to be in Hammer, people already writing Hammer.Skip on 90% of their entities cause they shouldn't be map placeable.

**Comment by DoctorGurke** [comment]
it only generates for hammer when using [Property] anyways, skip is for inheritance shenanigans and Asset types wiht [AutoGenerate]

**Comment by gvarados1** [comment]
> Surely it makes way more sense to opt in to wanting to be in Hammer, people already writing Hammer.Skip on 90% of their entities cause they shouldn't be map placeable.

Good idea matt! This make a lot more sense.

**Comment by handsomematt** [comment]
In the next update:
* Entities are opt in to Hammer with [HammerEntity]
* [Hammer.Skip] is renamed to [HideInEditor] for usage on properties
