### ISSUE TITLE
Inspector doesn't remember last save location

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1317]
**Describe the bug**
When saving asset files with the inspector it will default to the last mounted addon's data folder every time

**To Reproduce**
1. Make an asset using the inspector and note the addon it opened by default
2. Save it in a different addon than the default
3. make a new asset file in the inspector and save it
4. notice that the first save location it's in the default addon folder again

**Expected behavior**
it should remember the last save location so you don't need to navigate to your actual addon five times when making assets

**Comment by aylaylay** [comment]
It should remember now

**Comment by DoctorGurke** [comment]
Can confirm, thank you
