### ISSUE TITLE
Asset browser displays model's hitboxes incorrectly

### ISSUE THREAD

**Issue by MoonlyDays** [Facepunch/sbox-issues#1318]
**Describe the bug**
Asset browser shows the hitboxes of a model incorrectly. 

**To Reproduce**

1. Open the Asset Browser
2. Find the citizel model.
3. Click "Hit Boxes" checkbox.

**Expected behavior**
It should display hitboxes correctly.

**Screenshots**

Asset Browser:
![image](https://user-images.githubusercontent.com/32462579/142733630-6db0322f-4dcb-4062-8d17-a1818858eba1.png)

ModelDoc:
![image](https://user-images.githubusercontent.com/32462579/142733660-00497fbf-0c86-4764-afb5-6d5c31c8a751.png)

**Additional context**
Similar problem occurs to regular Hitboxes, it's not exclusive to just HitboxCapsules.

**Comment by DoctorGurke** [comment]
can confirm
![sbox-dev_Dyf7NCUezP](https://user-images.githubusercontent.com/12602100/142733792-0b9fe8e6-7554-4ffd-8cd5-15b47b5dd623.png)

**Comment by aylaylay** [comment]
Out of curiosity, does HLA also have this issue. This part of the code looks old and doesn't support rendering of capsules. I can fix it all up but I'm just curious.

**Comment by xezno** [comment]
Looks like HLA renders them fine
![image](https://user-images.githubusercontent.com/12881812/144293316-cb1bcf7a-bdbc-4f5e-9945-e4883739392d.png)

**Comment by aylaylay** [comment]
Is that model using boxes for hitboxes though?

**Comment by xezno** [comment]
Yeah, the initial issue said it didn't matter though

**Comment by aylaylay** [comment]
I wanted to know if HLA supported drawing of capsules in this situation just out of curiosity because it's something I'll need to add.

**Comment by justynboi** [comment]
HLA can draw capsules. 

![image](https://user-images.githubusercontent.com/17112771/144297023-dfa5aa18-27c6-4bcf-884b-9d492d473745.png)

**Comment by DoctorGurke** [comment]
lmfao layla is asking about the asset browser hitbox preview though

**Comment by justynboi** [comment]
oh lol, the asset browser hitbox preview only supports boxes. can't draw capsules.

**Comment by aylaylay** [comment]
<img width="285" alt="sbox_IxIa3bBfLl" src="https://user-images.githubusercontent.com/1667289/144299281-d5fe6724-2c2d-44e6-a30d-efe2eb3fdada.png">

Done
