### ISSUE TITLE
Add clothing randomization to Clothing.Container

### ISSUE THREAD

**Issue by goaaats** [Facepunch/sbox-issues#1319]
**What can't you do?**
Apply random clothes to NPCs, based on all of the available clothes.

**How would you like it to work?**
```cs
private Clothing.Container container = new();

public override void Spawn() {
	container.DressEntityRandom( this );
}
```

**What have you tried?**
```cs
var model = Rand.FromArray( new[]
{
	"models/citizen_clothes/trousers/trousers.jeans.vmdl",
	[...]
} );
[...]
```
This is prone to errors when clothing gets e.g. moved or removed, as it has in the past, or when new clothing is added.

**Comment by handsomematt** [comment]
This is definitely something you can do properly and very easily yourself with Clothing.All and some very quick Linq.
