### ISSUE TITLE
map command fails when sv_password isn't empty

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#132]
**Describe the bug**

If `sv_password` is set local client will fail to create a game using `map` command

**To Reproduce**

Go to main menu
Put `sv_password password` in console
Put `map testmap` in console
It will fail to main menu

**Expected behavior**

When connecting to self should apply the server's `sv_password`

**Comment by Erlite** [comment]
+1, can reproduce, happened to me as well earlier. Can't `restart` either.

**Comment by KingDavidW** [comment]
As a workaround, set your password locally. It is rejecting the map command because it's rejecting the connection to your own server

`sv_password sandy
password sandy
map testmap`

**Comment by robotboy655** [comment]
Should be fixed.
