### ISSUE TITLE
[IMPORTANT] Every game mode I launch shows an error saying "Couldn't find addon with gamemode named ..."

### ISSUE THREAD

**Issue by StupidRepo** [Facepunch/sbox-issues#1320]
**Describe the bug**
So, a couple minutes ago I was testing my gamemode and released it to the public as Hot Release. I played it and kept updating it for a bit to edit some code and then I edit some more code, go to hit Play and it said `"Couldn't find addon with gamemode named graveqmodified"`. I tried with other gamemodes and they didn't let me launch into them either!

**To Reproduce**
1. Open s&box
2. Go into a gamemode
3. Create Lobby
4. Press Play
5. Witness error

**Expected behavior**
Should be able to launch into my gamemode and other gamemodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/69256931/142755543-a71166ef-a8b2-4357-9a48-43e065fa39ac.png)
Look at the bottom-left corner for the error.

**Additional context**
Fix this ASAP! I think it's an issue with the API?

**Comment by StupidRepo** [comment]
AH! Turns out I got rate-limited by GitHub. That's why GitHub gamemodes aren't working.

**Comment by StupidRepo** [comment]
`{"message":"API rate limit exceeded for <MY IP>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`

Maybe try making s&box use an authenticated request that can bypass it.

**Comment by StupidRepo** [comment]
Ok so I've just uploaded it as a ZIP and the error is still there?

**Comment by handsomematt** [comment]
We won't be using GitHub directly like this in the future - you don't need to push code to GitHub to play your gamemode each time, just use the local menu.
