### ISSUE TITLE
Whitelist WeakReference API

### ISSUE THREAD

**Issue by SK83RJOSH** [Facepunch/sbox-issues#1322]
**What can't you do?**
I'd like to create a simple resource cache using WeakReferences.

**How would you like it to work?**
I'd like to have System.WeakReference whitelisted.

**What have you tried?**
N/A

**Additional context**
Trying to make a simple resource caching system using the classic Dict + WeakReference approach. Unfortunately discovered these aren't whitelisted despite being used in base a fair bit. Would be great to have these exposed if there aren't any obvious security issues with them.

**Comment by Rohansi** [comment]
Probably also worth looking at its buddy [`ConditionalWeakTable<TKey,TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2?view=net-6.0) too.

I'm not seeing any issues aside from that `WeakReference(SerializationInfo, StreamingContext)` constructor. But that shouldn't be possible to use without whitelisting `SerializationInfo`, which shouldn't happen anyway.
