### ISSUE TITLE
[Hammer] Sliders On All Value Inputs in Editor Windows

### ISSUE THREAD

**Issue by SethTooQuick** [Facepunch/sbox-issues#1323]
The only value inputs that have the slider capabillities are the ones in the transform dropdown it seems. It'd be great if this was everywhere, even if the quick fix would be to have a square next to it, how like the angles have their angle (X, Y, Z, the area where sliding actually works). Alternatively, maybe just have dragging over values act as the slider, like in Blender?

**Comment by robotboy655** [comment]
This is it for now.
![image](https://user-images.githubusercontent.com/3299036/199245340-4634673c-4f18-4f03-899c-0466f73a925f.png)
