### ISSUE TITLE
ClientRPC fails to send parameter at higher pings

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#1324]
**Describe the bug**

When attempting to send an entity over `ClientRpc`, there is a chance that at higher pings (tested at 200) it ends up null. Is this behaviour just a network failure? Should we instead just be constantly checking the player's inventory on tick instead of relying on `ClientRpc` plus `Events`?

**To Reproduce**

Hopefully, this isn't related to my game mode. To repro send over an `entity` using a `ClientRpc` at higher pings (tested with `net_fakelag 200`).

**Expected behavior**

The `entity` should not end up null, most of the time it isn't.

**Screenshots**

**Additional context**

Server sending it
```csharp
Log.Info($"{Owner.Name} sending RPC of {entity.Name}");
RPCs.ClientOnPlayerCarriableItemPickup(To.Multiple(Utils.GetClients((pl) => pl.CurrentPlayer == player)), entity);
```

Client getting it
```csharp
[ClientRpc]
public static void ClientOnPlayerCarriableItemPickup(Entity carriable)
{
    Log.Info($"carriable null: {carriable == null}");
    Event.Run(TTTEvent.Player.Inventory.PickUp, carriable as ICarriableItem);
}

// later on...

[Event(TTTEvent.Player.Inventory.PickUp)]
private void OnCarriableItemPickup(ICarriableItem carriable)
{
    if (carriable == null)
    {
        Log.Info($"{Local.Pawn.Name} given null carriable");
        return;
    }

	// ...
}
```

![1](https://user-images.githubusercontent.com/32153021/142816923-18c8c4a5-a6ea-492d-b4a9-bd4268f3bfb4.png)
![2](https://user-images.githubusercontent.com/32153021/142816925-55bc48b3-ae5d-4bf0-8732-9a5c5cf384e5.png)

Here are direct links to the files without comments

**Adding the entity**
https://github.com/TTTReborn/tttreborn/blob/master/code/rounds/PreRound.cs#L145

**Sending the ClientRPC of the non null entity**
https://github.com/TTTReborn/tttreborn/blob/master/code/player/Inventory.cs#L56

**Client getting the ClientRPC**
https://github.com/TTTReborn/tttreborn/blob/master/code/global/RPCs.cs#L164-L168

**Client event receiving the entity**
https://github.com/TTTReborn/tttreborn/blob/master/code/ui/generalhud/inventorywrapper/inventoryselection/InventorySelection.cs#L104-L110

**Comment by Alf21** [comment]
Can repro this. Seems like ClientRpcs are send and executed before the parameters (networkable entities) have been send.
As it's working with low ping, could it be that the params and the clientrpc call are networked through different pipes or the entity initialization causes an additional delay?

**Comment by mzegar** [comment]
Just as an update, still experiencing this after the networking changes/updates recently.

**Comment by kolexxx** [comment]
I'm also experiencing this issue even after the updates
