### ISSUE TITLE
Problems with compiling high-poly models

### ISSUE THREAD

**Issue by Sherlock2004** [Facepunch/sbox-issues#1325]
**Describe the bug**
When I compile high poly models I get broken stretched polygons. Here are screenshots. Any other stuidomdl will compile everything correctly.
![Strip 2](https://user-images.githubusercontent.com/88171363/142861569-403be86f-bb40-413d-a326-526dace49444.jpg)

**To Reproduce**
Try to compile this model.
[elka.zip](https://github.com/Facepunch/sbox-issues/files/7580941/elka.zip)

**Comment by robotboy655** [comment]
This is the S&box GitHub repository, not Garry's Mod one.

**Comment by Sherlock2004** [comment]
Oh, damn sorry, I messed up.
