### ISSUE TITLE
AnimGraph Nested Graphs / AnimGraph Groups

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#1327]
**What can't you do?**
Make AnimGraph groups  that can be applied to other AnimGraphs, so you don't have to reimplement that same bunch of nodes a million times.

**How would you like it to work?**
Maybe something similar to Blenders shader nodes? Where you can do a Ctrl G to make it a group, then it can be used on other graphs

**Comment by aylaylay** [comment]
Done
