### ISSUE TITLE
[Hammer] Voxel Surface Supports More than a Quad

### ISSUE THREAD

**Issue by PyroBot11** [Facepunch/sbox-issues#1328]
**My request:**
I am not a very good coder, and I saw that voxel surface now supports splitting. I was wondering if vox files or blocks could be supported for this mechanic. I personally believe that this would be an amazing feature for those who are not so smart with c#.

**How it would work:**
Import the vox file into model doc and be able to set it to the voxel surface entity in Hammer. Or make a block and tie it to the voxel surface entity. 

Thanks,
Pyro.

**Comment by aylaylay** [comment]
This is an entity for a panel of voxels, not a volume
