### ISSUE TITLE
Model.GetAllData()

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#1329]
**What can't you do?**
Get all the model doc "GameData" on an object

**How would you like it to work?**
Model.GetAllData() returns an array of all the data on that model

**What have you tried?**
Doesn't exist

**Comment by Jake-NSW** [comment]
Would be also nice to have a Model.GetAllData<T>(), Which gets all the game data inherited from that T

**Comment by robotboy655** [comment]
I don't see why you should be needing this. When you define new nodes and use them in models, you also already know the "class names" of the nodes to use in your entities.

**Comment by Jake-NSW** [comment]
I was thinking of using them sort of like components that can be attached to models. For example I don't want to hard code viewmodel effects / so I thought why not just make each viewmodel effect its own node in model doc? 

This is how I thought it could be used.

```csharp	
	//
	// Viewmodel Node / Model Doc node
	//

	public class ViewmodelNode
	{
		public virtual EntityComponent CreateComponent( in Entity entity ) { return null; }
	}

	public class ViewmodelNode<T> : ViewmodelNode where T : ViewmodelComponent, new()
	{
		public override EntityComponent CreateComponent( in Entity entity )
		{
			return entity.Components.Create<T>();
		}
	}

	//
	// The Component
	//

	[ModelDoc.GameData( "esp.viewmodel_crouch_offset" )]
	public class CrouchOffsetNode : ViewmodelNode<CrouchOffset>
	{
		public Vector3 Offset { get; set; }
		public Rotation Rotation { get; set; }
	}

	public class CrouchOffset : ViewmodelComponent<CrouchOffsetNode>
	{
		protected float crouchTransition = 0;

		public override void PostCameraSetup( ref CameraSetup cameraSetup )
		{
			if ( Local.Pawn is not Pawn pawn )
				return;

			if ( pawn.GetActiveController() is not Controller controller )
				return;

			var stance = controller.GetMechanic<Stance>();

			var enabled = stance.Current == State.Crouch && !IsAimming && pawn.GroundEntity is not null;
			crouchTransition = crouchTransition.LerpTo( enabled ? 1 : 0, 5 * Time.Delta );

			var crouchOffset = Vector3.Lerp( Vector3.Zero, Data.Offset, Easing.EaseIn( crouchTransition ) );
			var crouchOffsetRotation = Rotation.Slerp( Rotation.Identity, Data.Rotation, Easing.EaseOut( crouchTransition ) );

			Position += (Rotation.Forward * crouchOffset.x) + (Rotation.Left * crouchOffset.y) + (Rotation.Up * crouchOffset.z);
			Rotation *= crouchOffsetRotation;
		}
	}

	//
	// In the viewmodel class itself
	//

	public override void OnNewModel( Model model )
	{
		base.OnNewModel( model );

		if ( !model.TryGetData<ViewmodelData>( out var data ) )
		{
			Log.Error( $"espionage_viewmodel not present on {model.Name}" );

			// Use Defaults if not present
			Data = new ViewmodelData();
			return;
		}

		foreach ( var item in model.GetAllData<ViewmodelNode>() )
		{
			item.CreateComponent( this );
		}

		Data = data;
	}
```

Codes not clean but its meant to give an idea of how id want it to work.

**Comment by robotboy655** [comment]
Ah, so what you are actually asking for is a method that returns a list of nodes that are assigned to the model and derive from a given base type. Yeah I can see how that can be useful.

**Comment by Jake-NSW** [comment]
Sweet! Cant wait to use it when its implemented

**Comment by robotboy655** [comment]
Ok, added it as `GetAllData<T>();`, I couldn't think of a of better name. It will NOT work with AllowMultiple nodes and with break commands.

**Comment by Jake-NSW** [comment]
Works wonderfully, thanks for this !

**Comment by Jake-NSW** [comment]
Looks like if the GameData doesn't have any data / properties on it you cant get it from the C# side, and then if you add data you have to restart your game (s&box) for the model doc FDG to compile, then you compile on the model then restart your game (s&box) again to then be able get the data from c#? Atleast thats what I think whats happening.  Seems incredibly weird

**Comment by robotboy655** [comment]
Regarding the restarts, it works like this currently:
1) You start a map, that generates the .fgd
2) You need to restart the whole game if you already opened ModelDoc in that session - something that probably needs addressing
3) If you recompiled the model and you already tried to get the data, you need to restart the map as the data is cached per model - also something that needs addressing

As for empty nodes, I am assuming you just did not have any properties in the C# struct/class at all?

**Comment by robotboy655** [comment]
Alright, empty data nodes should now work as well, not sure why you need this though.

**Comment by Jake-NSW** [comment]
> Alright, empty data nodes should now work as well, not sure why you need this though.

Was just messing around with the new feature, trying to get all bugs. Maybe someone else will use it in the future

**Comment by robotboy655** [comment]
Alright, I have added "Reload .FGD files" to ModelDoc, it works just like it does in Hammer, and it will also automatically reload .FGDs when all ModelDoc windows are closed.

This should cut down on the confusion and not require full game restarts, and help when iterating.
