### ISSUE TITLE
Convars with Name set do not work

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#1334]
**Describe the bug**
Convars with Name set do not show up in console suggestions and do not show their value

**To Reproduce**
Doesn't work:
```
[ConVar.Replicated("swb_sv_showhud", Name = "Enable the HUD for all clients", Saved = true)]
public static int ShowHudSV { get; set; } = 1;
```

Works:
```
[ConVar.Replicated("swb_sv_showhud", Saved = true)]
public static int ShowHudSV { get; set; } = 1;
```

**Screenshots**
![convar_issue](https://user-images.githubusercontent.com/4988198/143508590-166839c4-a2e9-4a6a-b2a0-010a4bde0295.png)

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/143509746-57f2a4f5-9cdb-4b59-86c0-eed9ecf8fb34.png)

Name is the variable you set with the constructors first argument. I don't even know why its public.

![image](https://user-images.githubusercontent.com/3299036/143509785-d0325362-9db7-4894-b184-2eaa73172dbd.png)

If you want to give the command help text, use the Help property.

**Comment by timmybo5** [comment]
Oohhh dam, I completely misunderstood, thanks for clearing that up!
