### ISSUE TITLE
Enabling All Lighting on certain map in Hammer causes frequent crashes

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#1336]
Trying to enable All Lighting in my map causes the game to hard crash 99% of the time, the strange thing is that if I do this without saving the map at all upon first load, it will work fine most of the time. Below I've included 2 crash dumps and the map with a material override so theres no missing textures

**To Reproduce**
1. Load map in Hammer
2. Save map
3. Try to enable All Lighting mode

**Expected behavior**
Not to crash 4head

Link (Github wouldnt let me upload the zip here): https://drive.google.com/file/d/1Yvhib8EvLrD6LjFmW6VVE9V8yMCNXK4Q/view?usp=sharing

Hardware: GTX 1660Ti with latest drivers, Ryzen 7 2700x, 32gb ddr4

**Comment by DeltaDesigns** [comment]
Update: I've discovered going into All Lighting while in a part of the map with no light visible wont cause a crash and allows normal use but any enabling while theres any light source in view it seems, causes the crash

**Comment by KayaDLX** [comment]
Ah me and @justynboi also had this issue recently, not sure what's causing it, it just happens on some map and not others.

**Comment by DeltaDesigns** [comment]
> Ah me and @justynboi also had this issue recently, not sure what's causing it, it just happens on some map and not others.

Glad to know it's not just me with this problem, was starting think it was just me

**Comment by aylaylay** [comment]
I have pushed a possible fix, see if you can get it to happen again

**Comment by KayaDLX** [comment]
Still happening to me, tested twice

**Comment by DeltaDesigns** [comment]
Tested a few times as well, still happening

**Comment by DeltaDesigns** [comment]
Bump, as this is still happening

**Comment by DeltaDesigns** [comment]
[sbox_2022_0110_170740_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/7842176/sbox_2022_0110_170740_0_accessviolation.zip)
Here's a new crash log from today along with the map with a white mat override. having the 'map model' selected then going into all lighting is what causes the crash it seems like
[map flat shaded.zip](https://github.com/Facepunch/sbox-issues/files/7842199/map.flat.shaded.zip)

**Comment by handsomematt** [comment]
This was cbuffers, fixed ages ago
