### ISSUE TITLE
Modeldoc Bounds Hull note non-functional

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1337]
**Describe the bug**
The ModelDoc node `Bounds Hull` doesn't seem to actually do anything for the compiled model.

**To Reproduce**

1. Prepare some random model. It doesn't need collisions, the default bbox will be based on the render model.
2. Inspect the compiled model's bbox
3. Go back into ModelDoc and add a Bounds Hull node with different bounds and compile the model.
4. Inspect the compiled model's bbox again and notice it hasn't changed

**Expected behavior**
For the node to properly set the model's b box.

**Screenshots**
![sbox-dev_uOIhnImqcp](https://user-images.githubusercontent.com/12602100/143619227-4be448de-b75a-4449-accd-fef49af3d6a7.png)

![sbox-dev_3hHajBYHs1](https://user-images.githubusercontent.com/12602100/143619230-1276b4ce-68e5-4c8f-9b75-ceae7f169fd1.png)

![sbox-dev_ueAZvC0YEv](https://user-images.githubusercontent.com/12602100/143619319-d19bf403-9bd2-4056-83db-95af79d745fc.png)

**Additional context**
The reason I want to set the bbox explicitly is so that the entity model can be properly placed in hammer. The model will rotate and move up and down, so the default bbox will have it clip into the ground.
Moving the origin outside of the initial bbox does change it's size accordingly.

Edit: This node also doesn't seem functional in alyx. Can't say for the View Bounds view node since I don't know how I'd test that properly.

**Comment by aylaylay** [comment]
This seems to be working fine. If you select "Show Hull Bounds" it renders it correctly. Maybe hammer isn't using hull bounds for placement so that would be a different issue if that's the case.

**Comment by DoctorGurke** [comment]
Ah I see, if it's a problem with hammer not using the bounds, should I just edit this issue accordingly or make a new one?

**Comment by aylaylay** [comment]
From the looks of it, hammer has never placed models using bounding box, it always places it at the model origin. This is a feature I could add if you need it.

**Comment by DoctorGurke** [comment]
Damn I must be mixing something up, maybe it used to be that way in s1? But yes it would be lovely if you could add that

**Comment by aylaylay** [comment]
Should place how you're wanting without setting anything up in modeldoc now.
https://user-images.githubusercontent.com/1667289/144598818-3faeb398-c886-4cd6-875a-83a77a340c8b.mp4

**Comment by DoctorGurke** [comment]
While the placing seems to work fine, the node still doesn't affect the bbox in hammer. I would still like to explicitly set a bbox that's larger than the actual model for the reasons stated in the original post

**Comment by aylaylay** [comment]
Bounds from this node is now added on
