### ISSUE TITLE
Save & Load custom Nav Generation Parameters

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1339]
We should be able to save and load custom Nav Gen Parameters. It should work like the Asset Sprayer, where there are buttons to save & load.

Asset Sprayer: 
![image](https://user-images.githubusercontent.com/39461072/143674689-0cf8239f-e065-45ef-aa0f-22d1d32c3f87.png)

Proposed Solution: 
![image](https://user-images.githubusercontent.com/39461072/143675006-8d5c64f5-0add-4833-a32c-ad09ce0200b0.png)

**Comment by DevulTj** [comment]
Obsolete as we use navmesh in scene instead
