### ISSUE TITLE
Glowstate enum names are reduntant

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1342]
**What it is**
The Glowstate enums are reduntant, see below.
![Code_Op6oZeCV3w](https://user-images.githubusercontent.com/12602100/143723170-3aeff755-5330-4889-b8cb-30352ea8ffaf.png)

**What it should be**
These enums should probably just be Glowstate.(Off/Use/LookAt/On) instead

**Comment by ogniK5377** [comment]
Should be in the next update 👍
