### ISSUE TITLE
Duck is broken on controller

### ISSUE THREAD

**Issue by SharpMars** [Facepunch/sbox-issues#1344]
Duck bind on controller is missing "+" at beggining. Currently its "iv_duck", but it should be "+iv_duck".

![image](https://user-images.githubusercontent.com/70289680/143774329-52f1b5ba-cc21-4c67-85f8-e7d796d421de.png)

**Comment by ogniK5377** [comment]
Should be fixed in the next update 👍

**Comment by SharpMars** [comment]
Works now. Thanks
