### ISSUE TITLE
Touch, StartTouch, EndTouch are not triggered by the WorldEntity and its geometry.

### ISSUE THREAD

**Issue by Ephememory** [Facepunch/sbox-issues#1345]
**What it is**
Touch, StartTouch, EndTouch are not triggered by the WorldEntity and its geometry.

**What it should be**
I would like to know for certain entities if they touched ANYTHING including the world.

**Comment by robotboy655** [comment]
Cannot reproduce?

![image](https://user-images.githubusercontent.com/3299036/144268327-9db6df64-b078-4a83-ab31-40bf143984e2.png)
![image](https://user-images.githubusercontent.com/3299036/144268377-5211335b-3ba4-44b8-89b6-2609b726f53f.png)

**Comment by Ephememory** [comment]
> Cannot reproduce?

Huh, strange. I suppose to clarify, I'm trying to do this inside a class derived from Player. After I saw your reply I went into my local sandbox gamemode fork and overrode the function inside it's Player class and it started working? I'll just try to find the difference that causes it not to work in the other gamemode

**Comment by Ephememory** [comment]
Restarting the game seemed to fixed it in my other game mode. Which obviously makes no sense. This may be an actual bug, and seems like a difficult one to nail down.
