### ISSUE TITLE
Text Gradient Support

### ISSUE THREAD

**Issue by lewisainslie** [Facepunch/sbox-issues#1348]
It would be good to be able to support linear/radiant gradients on CSS.

[https://www.css-gradient.com/text-gradients](https://www.css-gradient.com/text-gradients)

**Comment by Rohansi** [comment]
🌈

**Comment by lewisainslie** [comment]
@cr4yz ❤

**Comment by ogniK5377** [comment]
This issue is a bit old but I went ahead and added support for gradients in `color` it can be done like so:

```css
color: linear-gradient( rgba(255,0,0,1), rgba(255,154,0,1), rgba(208,222,33,1), rgba(79,220,74,1), rgba(63,218,216,1), rgba(47,201,226,1), rgba(28,127,238,1), rgba(95,21,242,1), rgba(186,12,248,1), rgba(251,7,217,1), rgba(255,0,0,1) );
```
