### ISSUE TITLE
Post Processing Volumes does not work when you walk into them.

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#1349]
**Describe the bug**
When you walk into any post processing volume it would not do anything, but making the volume into a "Master Volume" would work.

**To Reproduce**

Download this ZIP. I already made a test map with example volumes.
[postprocessvolume.zip](https://github.com/Facepunch/sbox-issues/files/7636709/postprocessvolume.zip)

**Expected behavior**
Post Processing Volume would not do anything when you walk into it

https://youtu.be/lGmN31Rry9M

This works in Hammer, but not in-game

**Comment by bakscratch** [comment]
https://user-images.githubusercontent.com/8184184/190648431-67274b0d-9465-4e66-884d-d7163d6d1076.mp4

I believe this was fixed a while back now.
