### ISSUE TITLE
Input.VR.LeftHand.ButtonA.WasPressed Always returns false

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1350]
**Describe the bug**
Input.VR.x.x.WasPressed always returns false for both hands on both A and B buttons.

**Expected behavior**
I assume WasPressed is meant to return true once when the button is released.
I think it would make more sense if these buttons had .Down .Pressed and .Released like regular inputs

**Comment by handsomematt** [comment]
was invalid controller config in manifest, was fixed quite a while ago
