### ISSUE TITLE
Precache Attribute

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#1352]
**How would you like it to work?**
Precache attribute gets attached to getter only string property, and attempts to precache the path that's on that string property. This is meant act as a ease of use feature.

![image](https://user-images.githubusercontent.com/55055481/144349376-e73f6eb4-ecda-4ac1-8703-1b92af4db24a.png)

**Additional context**
The way I think it could is it could get the path from the source generator and add it as a constructor to the precache attribute, then on game start it'd just get every Precache attribute and read the string value from the constructor and add that to the precache

**Comment by handsomematt** [comment]
The way you're meant to precache models is like so:

```csharp
public partial class Ball : ModelEntity
{
	static readonly Model Model = Model.Load( "models/golf_ball.vmdl" );

	public override void Spawn()
	{
		SetModel( Model );
	}
}
```

**Comment by Jake-NSW** [comment]
Ah okay thanks for the insight
