### ISSUE TITLE
Ortho camera on ScenePanel

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#1353]
**What can't you do?**
Set a `ScenePanel` to use an orthographic camera projection.

**How would you like it to work?**
Access an `Ortho` property on a ScenePanel instance, similar to how a Camera currently functions.

**Comment by ogniK5377** [comment]
Should be in the next game update
`scene = Add.ScenePanel( SceneWorld.Current, CamPos, Rotation.From( CamAngles ), 45, true );`
Final parameter decides if it's orthographic or not
