### ISSUE TITLE
net_fakelag Doesn't Enable When Server Restarts With "restart" Console Command

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1356]
**Describe the bug**
net_fakelag doesn't turn on if you restart the server using the "restart" console command.

**To Reproduce**

1. Start a server with net_fakelag off
2. Turn on net_fakelag (net_fakelag requires server restart to work)
3. Restart the server using "restart" in console

**Expected behavior**
net_fakelag should turn on when "restart" is used.

**Comment by aylaylay** [comment]
It should now take effect after server restart

**Comment by gvarados1** [comment]
works :)
