### ISSUE TITLE
[Discord] Implement moderator bot

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#1361]
Garry's mod discord server have `Toolgun` which is great! But it would be cool to have something like it on s&box server too.

**Comment by garrynewman** [comment]
why?

**Comment by FlorianLeChat** [comment]
Toolgun is not an official Facepunch bot, it was created by Spar (one of the Discord moderators) and is maintained voluntarily for the Garry's Mod community.

**Comment by kevdaawsome** [comment]
I don't understand why is being asked of here but it doesn't seem very important
