### ISSUE TITLE
Allow more UVs to compile into vmdl_c

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#1362]
**What can't you do?**
---
Right now if i wanted to use more than 2 uvs on a model, i can't do so.
It only seems to compile UV0 and UV1 correctly

**How would you like it to work?**
---
Just allow you to compile multiple uvs than can easily be used from a shader

**What have you tried?**
---
Creating different models with uvs and compiling and pulling them open to see what they have.
all i can see is vertex buffers for these, skipping UV2, and anything above UV3 and UV3 being unorm?

Compiled Vertex Buffers

TEXCOORD 0 - float (UV0)
TEXCOORD 1 - float (UV1)
TEXCOORD 3 - unorm (UV3)

**Additional context**
---
What i want to do is have clothing in sbox, with a base UV0 for the normals and all that.

then using additional uvs for different logo/design layouts, like a full pattern, big square logo on the front, a small logo where a pocket would be, and so on.
but i want it to be easily useable for anyone just create a uv channel, scale and position it to what you want, then it works fine!
but it does not since it only compiles UV0,UV1 (and i think UV2, but i cant seem to get it to work)

(if it comes down to it i could just compile the model with like 4 or 5 of the same shirt model but with different UV1 layouts and use body groups, but i feel like thats a really inefficient way of going about stuff)

**Comment by aylaylay** [comment]
are the uvs in your fbx or whatever format you're using

**Comment by NotGaylien** [comment]
closing this, mix of trying to do something a really weird way (i wanted an excuse to mess with more shaders 0-0) and i think i just fucked something up on my end partly.
