### ISSUE TITLE
rect editor rendering is broken with a custom shader 

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1363]
**Describe the bug**
A material using a custom shader using the base shader as a template won't render in the rect editor preview.

**To Reproduce**

1. make a material using the base shader
2. specify a rect file in the attributes
3. try to view the material in the rect editor

**Expected behavior**
For the material to render like any other material

**Screenshots**
using the custom shader:
![image](https://user-images.githubusercontent.com/12602100/144765377-fe019ddb-a86e-4dec-90e6-8df436c5dd59.png)

using the complex shader:
![image](https://user-images.githubusercontent.com/12602100/144765392-f2a96998-3671-45e5-b2c8-4d2a80b10703.png)

**Comment by samzanemesis** [comment]
Should be fixed now I think? Can you try again

**Comment by DoctorGurke** [comment]
recompiled the shader, lightmapping works now but rect editor rendering still seems non functional
![sbox-dev_AH9bQuZNsl](https://user-images.githubusercontent.com/12602100/145719460-644ae589-3c81-4ac9-8f8c-63aab36196a1.png)

**Comment by ogniK5377** [comment]
Not entirely sure what you're doing wrong, seems to work fine with the base shader. You must of messed something up
![image](https://user-images.githubusercontent.com/25727384/147661182-9f395d00-86a4-4af1-9a81-09382961a3fa.png)

**Comment by DoctorGurke** [comment]
hm, I'll try it again when I'm back at my main pc

**Comment by DoctorGurke** [comment]
sorry for the delay, this was an error on my side. I wasn't using the default `TextureColor` input for my main color texture, so it was just displaying the default color for every material. Using that input instead fixes it and it shows properly in the rect editor now.
