### ISSUE TITLE
Base shader doesn't output albedo for lightmapping

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1364]
**Describe the bug**
Surfaces with a material using a custom shader with the base shader as a template don't seem to count as lightmap space and are therefore not considered during light baking.

**To Reproduce**

1. Make a material with the base shader
2. apply it to meshes on a map
3. full compile the map
4. notice the meshes with the custom material appearing black

**Expected behavior**
Baked lighting to function as usual

**Screenshots**
![sbox-dev_ygacPtZc7m](https://user-images.githubusercontent.com/12602100/144765832-682ae7bb-f1be-4560-bbdf-a2b55ad36ce0.png)

![sbox-dev_56ZTmiVeWm](https://user-images.githubusercontent.com/12602100/144765833-05e44bf8-9d56-415d-bd09-6cac1c0d3e6c.png)

**Comment by DoctorGurke** [comment]
seems to be related to vrad3 only. Editor baked preview lighting via vrad2 works fine

**Comment by ogniK5377** [comment]
Is your base shader out of date? They seem to bake fine.
![image](https://user-images.githubusercontent.com/25727384/145074977-36c2ac6f-66c5-4468-9616-2ea198275b8a.png)
![image](https://user-images.githubusercontent.com/25727384/145075034-d42e0652-c764-4a90-aeb3-afe74e6c0140.png)

**Comment by DoctorGurke** [comment]
deleted the shader + common folder and verified, still busted when baking lighting. It's either pitch black or in some weird edge cases fullbright.

**Comment by ogniK5377** [comment]
Oh, I see what's up, albedo output isn't being filled. I'll take a look in the morning 👍

**Comment by DoctorGurke** [comment]
Any update on this?

**Comment by samzanemesis** [comment]
also related to https://github.com/Facepunch/sbox-issues/issues/1363

**Comment by ogniK5377** [comment]
Should be fixed in the next update, make sure to recompile your shader!

**Comment by DoctorGurke** [comment]
Yep seems to work fine now, thank you

**Comment by gabengaGamer** [comment]
is a similar fix for the blend shader planned?
