### ISSUE TITLE
custom shaders don't support custom world mapping in the material attributes

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1366]
**Describe the bug**
Materials using a custom shader using the base shader as a template don't have an option to set custom world mapping

**To Reproduce**

1. make a material using the base shader
2. go to the attributes tab
3. notice the world mapping attribute section is missing

**Expected behavior**
being able to set custom world mapping for materials using custom shaders

**Screenshots**
base shader:
![sbox-dev_022piMXKll](https://user-images.githubusercontent.com/12602100/144766613-fbb073a5-7416-4823-a60a-8c320cc7b07f.png)

complex:
![sbox-dev_qMveJHDtiC](https://user-images.githubusercontent.com/12602100/144766615-e358d541-9bf5-4558-950e-884406f0d675.png)

**Comment by ogniK5377** [comment]
Should be in the next update 👍

**Comment by DoctorGurke** [comment]
This seems to work perfectly, thank you
