### ISSUE TITLE
base shader _rough and _ao defaults are float3 instead of float internally

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1367]
**Describe the bug**
The default values for the roughness and ao channels on the base shader when not using textures seem to be float3 instead of float internally, leading to the default representation to be color pickers instead of sliders like for metalness

**To Reproduce**

1. make a material using the base shader
2. switch to using non-texture inputs for the roughness and ao channel
3. notice the defaults are red, 0.5 and 1.0 on the red(first) channel respectively

**Expected behavior**
the defaults to be sliders like for metalness, blend mask, tint mask

**Screenshots**
![sbox-dev_yl2HiK7MPb](https://user-images.githubusercontent.com/12602100/144766805-58a07795-4a0e-493c-9da9-0c5a44e2ad88.png)

![Code_iQDa5jqrK8](https://user-images.githubusercontent.com/12602100/144766827-124afc14-1d62-480a-909c-0a7eb4f3df03.png)

**Comment by ogniK5377** [comment]
Should be fixed in the next update

**Comment by DoctorGurke** [comment]
Works perfectly, thank you very much
