### ISSUE TITLE
make the material editor shader select focus the search input on popup

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1368]
**What can't you do?**
When opening the shader select in the material editor the search input field will not be focused and therefore not immediately typed in

**How would you like it to work?**
I'd like the input field to be focused right away when the window opens for ease of use and a better workflow experience

![sbox-dev_vk8SMgyHiR](https://user-images.githubusercontent.com/12602100/144769124-2243e037-09e3-4e27-9bae-b03a17391735.png)

**Comment by aylaylay** [comment]
Done
