### ISSUE TITLE
render backfaces does not work on base shader in tools/editor and appears black in game

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1372]
**Describe the bug**
the option "Render Backfaces" in the base shader doesn't work in tools/editor and renders pitch black in game

**To Reproduce**

1. make a material using the base shader
2. observe that backfaces are culled
3. enable "Render backfaces"
4. observe no change to backfaces in editor/tools and that it's just pitch blackness in game

**Expected behavior**
for backfaces not to be culled properly when the option is enabled and to render properly in game

**Additional context**
not having `Depth( "vr_depth_only.vfx" );` on the shader also doesn't seem to render them in game at all. I don't know if that's just to be expected, but I'd think transparent materials can also have visible backfaces

**Comment by ogniK5377** [comment]
Works fine, verify your game file

https://user-images.githubusercontent.com/25727384/144855100-76008f16-6521-4fdf-8f95-dd5a43b13d7c.mp4

**Comment by DoctorGurke** [comment]
seems to work only in-game but not in any tools. Although testing in-game is also a hassle because of #1364

**Comment by DoctorGurke** [comment]
I guess that's just one more issue to pile onto the tools/editor related problems with custom shaders right now

**Comment by DoctorGurke** [comment]
for the record though, are backfaces supposed to just be pitch black? cause that's what I'm seeing

![sbox-dev_iyIJp7vvUU](https://user-images.githubusercontent.com/12602100/144859808-d201bfb5-02e2-42db-b23b-bdad9780d3e5.png)

![sbox-dev_Fxj3i94UNs](https://user-images.githubusercontent.com/12602100/144859830-3e92eab6-28f1-4a7b-adb4-f5b595df2e97.png)

**Comment by DoctorGurke** [comment]
can this issue please be reopened? I changed the title to reflect the proper issue

**Comment by DoctorGurke** [comment]
just found #68, I assume it's related

**Comment by DoctorGurke** [comment]
bump
