### ISSUE TITLE
Pressing the UP arrow key while having selected a text cause an error

### ISSUE THREAD

**Issue by suiramdev** [Facepunch/sbox-issues#1373]
**Describe the bug**
The developer console is returning an error once you press the UP arrow while the entered command is selected.

**To Reproduce**
1. Open up the console (using F1 ?)
2. Type anything in the command input
3. Select it (I personally double left clicked)
4. Press the UP arrow from your keyboard

**Expected behavior**
No errors should appear, nothing should happen.

**Screenshots**
Here is a video, instead.

https://user-images.githubusercontent.com/71449142/144916233-1e711d35-0967-45ac-805f-e4d8fd3c02d3.mp4

**Additional context**
It happened to me that sometimes it wasn't returning any errors.

_I hope this issue isn't a duplicate :)_

**Comment by aylaylay** [comment]
Should be fixed next update
