### ISSUE TITLE
Custom library attributes don't work correctly

### ISSUE THREAD

**Issue by nikita-strelok** [Facepunch/sbox-issues#1375]
**Describe the bug**
Entities with custom attributes cannot be created via ``` Library.Create() ```.

**To Reproduce**
Use any custom attribute like this on entity and try to spawn it.
```csharp

[AttributeUsage(AttributeTargets.Class,Inherited = false)]
	class WeaponAttribute : LibraryAttribute
	{
		public WeaponAttribute(string title )
		{
			Title = title;
			Spawnable = true;
		}
	}

[Weapon("Pistol")]
class Pistol: Weapon { 
... 
}
```

**Expected behavior**
The entity is just spawned normally 

**Screenshots**
![image](https://user-images.githubusercontent.com/88283901/145102254-c4abacbc-159a-42e5-9c42-fc3576ae3784.png)

**Additional context**
I know, this is duplicate of #376,  but that issue is inactive.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
