### ISSUE TITLE
Read(BinaryReader reader) Should be static

### ISSUE THREAD

**Issue by Oppossome** [Facepunch/sbox-issues#1377]
**What it is**
There's some weirdness with the Vector3 and Color `Read(BinaryReader reader)` in that they are not static. 
It's also inconsistent as it's static on the Angles struct.

It leads to needing to do
`new Color().Read(streamReader)`

**What it should be**
They should be static to prevent the need of creating the object just to create the object.

**Comment by robotboy655** [comment]
Made `Color`, `Color32`, `Rotation` and `Vector3.Read` static
Made `Angles.Write` not static

I think that should cover it.
