### ISSUE TITLE
Disable sound for ViewModel animations

### ISSUE THREAD

**Issue by kolexxx** [Facepunch/sbox-issues#1378]
**What can't you do?**
Disable sound for ViewModel animations.

**How would you like it to work?**
`ViewModelEntity.EnableSound( bool )`

**What have you tried?**
SetAnimFloat( "volume", 0f );

**Additional context**
When creating Firstperson spectator viewmodels, I used the implementation of having every active child of every player have it's viewmodel created on the client. When you switch players I just disable `EnableDrawing` , but the sounds of the animations still play. It would be nice to have an easy way of setting this property. I don't want to disable animations completely if it's not being drawn, since I want the animations to continue even after switching players.

**Comment by DevulTj** [comment]
Your issue is that you're drawing **every single player's viewmodel.**

**Comment by kolexxx** [comment]
> Your issue is that you're drawing **every single player's viewmodel.**

Not every, only the active children. If you have a better solution im all ears, or just a solution to lowering the volume, since there's gotta be some float

**Comment by yuberee** [comment]
Animation events are set in ModelDoc and are tied to the animation itself, so there isn't a way to play the animation without playing the sound as far as I know.
You could always precache the models with `Precache.Add` and load them in when switching to a new player if you're concerned about performance.

**Comment by kolexxx** [comment]
> Animation events are set in ModelDoc and are tied to the animation itself, so there isn't a way to play the animation without playing the sound as far as I know. You could always precache the models with `Precache.Add` and load them in when switching to a new player if you're concerned about performance.

Then there is the issue of an animation not playing when switching to a player even though it's playing on the owner. Don't worry, optimization has been taken care of and im 100% sure this is the cleanest and best way of creating FirstPerson spectating models. After all, this is a feature request
