### ISSUE TITLE
Entity binary ext is broken

### ISSUE THREAD

**Issue by nikita-strelok** [Facepunch/sbox-issues#1379]
**What it is**
```csharp
	public static Entity Read(this Entity self, BinaryReader read)
	{
		return Entity.FindByIndex(read.ReadInt32());
	}

	public static void Write(this BinaryWriter writer, Entity self)
	{
		writer.Write(self?.NetworkIdent ?? 0);
	}
```
**What it should be**
```csharp
        public static Entity ReadEntity(this BinaryReader read)
	{
		return Entity.FindByIndex(read.ReadInt32());
	}

	public static void Write(this BinaryWriter writer, Entity self)
	{
		writer.Write(self?.NetworkIdent ?? -1); //-1 instead of 0 because 0 is id of worldent
	}

**Comment by robotboy655** [comment]
I have done some changes around the BinaryReader/Writer extensions, covers this and some other stuff too, so it's all consistent between all classes.

Added Entity.Write(), Entity.Read()
Fixed BinaryWriter/BinaryReader entity extensions
Make all BinaryWriter/BinaryReader extensions use the class Read/Write methods
Added BinaryReader.ReadRotation
Added Rotation.Write
Added Vector2.Read/Vector2.Write

**Comment by nikita-strelok** [comment]
Cool
