### ISSUE TITLE
text-decoration

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#138]
**What can't you do?**
Use text-decoration in CSS (e.g. to add underlined text that is clickable)

**How would you like it to work?**
See below

**Additional context**
https://www.w3schools.com/cssref/pr_text_text-decoration.asp

**Comment by rtm516** [comment]
I would suggest following the template next time, its likely easier to just do that anyway.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
