### ISSUE TITLE
Expose more light properties

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1380]
**What can't you do?**
Change properties such as Pattern and LightStyle for c# spawned light entities.

**How would you like it to work?**
Just being able to set them from c# like any other properties for dynamically spawned lights.

**What have you tried?**
The Properties are currently marked as internal so I can't use them at all.

**Comment by robotboy655** [comment]
Pattern and LightStyle are legacy properties that probably should be deleted from the game. if you want to animate the brightness, just do so?

**Comment by DoctorGurke** [comment]
yeah I suppose a curve would work for it
