### ISSUE TITLE
model doc set default save path for vmdl that was opened via "Create model for X" from the asset browser

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1381]
**What can't you do?**
the default save path for vmdls seems to always be the addon that was mounted last. It would save a lot of hassle if it would set a default save path for vmdls in a similar fashion as materials, where using the "Create model/material for X" from the asset browser sets the default save path to the same location as said assets.

**How would you like it to work?**
Right-click an fbx/model file in the asset browser, click "Create model for X". Saving the file will now set the location and name of the original fbx/model file as the default save path for the save dialogue.

**Comment by aylaylay** [comment]
Done
