### ISSUE TITLE
animgraph default save path is set to root sbox/animgraphs folder

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1382]
**Describe the bug**
When making a new animgraph file from modeldoc, it sets the default save path to sbox/animgraphs, outside of any addon.

**To Reproduce**

1. Go into modeldoc, press the "New" button on the animgraph panel
2. notice the default path is set to sbox/animgraphs

**Expected behavior**
It should probably default to the addon the vmdl is in, if possible. Otherwise to the default addon save path, which seems to be the last mounted addon

**Screenshots**
![sbox-dev_9H2yYHGJQc](https://user-images.githubusercontent.com/12602100/145290999-a1785a45-37ea-48b8-8cf2-050047022995.png)

**Comment by aylaylay** [comment]
Should be fixed now. I've made it set to addons/addon_name/animgraphs

We might decide that it's better to just save the animgraph next to the model but saving to the animgraph dir is how it was meant to work originally

**Comment by DoctorGurke** [comment]
This seems to work great, thanks!
