### ISSUE TITLE
No map verification when joining to server

### ISSUE THREAD

**Issue by kote2345** [Facepunch/sbox-issues#1384]
**Describe the bug**

Player can connect to server if player has different map with name map's as on server

**To Reproduce**

1. Player start a server
2. Second player takes different map with same name as on server. Connects to server
3. See error. Each player sees his own map

**Expected behavior**

When connecting to server, there must be a map check so that player's map matches server's map

**Screenshots**

![unknown1](https://user-images.githubusercontent.com/62496056/145463901-d037fede-3016-49cc-ae1e-a188ab741a87.png)

![unknown](https://user-images.githubusercontent.com/62496056/145463956-7542bf0c-134c-41f7-8cc4-20cb23ee093d.png)

**Comment by handsomematt** [comment]
Dupe #221
