### ISSUE TITLE
Tool dialogs make the hang window appear

### ISSUE THREAD

**Issue by conneath** [Facepunch/sbox-issues#1394]
**Describe the bug**
when you open SFM, a welcome window should pop up, after some time the hang report window should open, you can still interact with the welcome window just fine, and when you close it the hang window is gone

**To Reproduce**

1. Cause a dialog to appear (opening SFM, Hammer Open dialog)
2. after a bit you should see the hang window

**Expected behavior**
the hang window not appearing

**Comment by garrynewman** [comment]
I can't reproduce this - is it still an issue?

**Comment by conneath** [comment]
yea i think its fixed by now, not having it anymore
