### ISSUE TITLE
Change material editor "legacy source1 inverted normal" to DirectX Normals

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#1395]
Currently the game uses OpenGL style normal map texture. (+Y)

I feel like alot of people get confused with this.
and looking in the options,
"legacy source1 inverted normal"
is just really confusing, unless you know source 1 used DirectX style normals. 
![image](https://user-images.githubusercontent.com/82092361/145643422-691eca96-0acb-4d0c-aade-39dec4fd9d23.png)

**How would you like it to work?**

Change the "legacy source1 inverted normal" in material editor texture options to say
"DirectX -Y Normals" or just "DirectX Normals"

**Comment by QuackCocaine** [comment]
bump, this sounds like a no brainer to me to change it to something more clear
