### ISSUE TITLE
Selection for physics simulation doesn't work on func_physbox.

### ISSUE THREAD

**Issue by popcan12** [Facepunch/sbox-issues#1396]
**What can't you do?**
Be able to use shift-click or ctrl-click within the physics simulation tool to select or deselect a group of func_physboxes.

**How would you like it to work?**
The same way as ctrl-clicking or shift-clicking a group of models to select them all for a physics simulation.

**What have you tried?**
Shift-clicking and ctrl-clicking a group of func-physboxes. It doesn't work and I have to manually select each piece of the func-physbox entities (I.E clipping a wall into 15-20 pieces means I have to select each piece one by one.

**Additional context**
Video for proof
https://user-images.githubusercontent.com/46109751/145648350-fe4459fa-c1c0-45d9-9d59-ee540981d4ab.mp4

**Comment by aylaylay** [comment]
Should be fixed now
