### ISSUE TITLE
Prop_Physics doesn't scale correctly

### ISSUE THREAD

**Issue by popcan12** [Facepunch/sbox-issues#1397]
**Describe the bug**
Prop_Physics don't scale right from the editor to the game.

**To Reproduce**

1. Place a prop_Physics prop such as crate into a map.
2. Scale it in the XYZ
3. Run the game.
4. Look at the prop.

**Expected behavior**
To scale properly like how prop_static does it.

**Screenshots**
![image](https://user-images.githubusercontent.com/46109751/145651501-db0b5dc1-4b18-423e-bdc0-23f81fbb9343.png)
(One on the left is a prop_physics not scaling correctly and the other is a prop_static scaling correctly).

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by aylaylay** [comment]
Scaling entities is scalar and always will be.

**Comment by robotboy655** [comment]
We probably should make it act that way in Hammer to avoid further confusion like this.
