### ISSUE TITLE
In Hammer, pressing hotkeys for Save or Save As with no map loaded will crash the engine

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#140]
**Describe the bug**
Using the hotkeys Ctrl+S or Ctrl+Shift+S while no map is loaded in Hammer will crash the entire engine almost immediately.

**To Reproduce**

1. Open Hammer without loading any file into it
2. Press the key combination of Ctrl+S or Ctrl+Shift+S
3. Observe the engine crashing very quickly

**Expected behavior**
Do nothing, or play the default Windows "Asterisk" sound

**Comment by robotboy655** [comment]
Oops, sorry @aylaylay I just fixed it.
