### ISSUE TITLE
func_voxelsurface is broken at the moment

### ISSUE THREAD

**Issue by heut42069** [Facepunch/sbox-issues#1400]
**Describe the bug**
func_voxelsurface entities are misplaced. Can you please investigate what's wrong with them? Thanks in advance!

**To Reproduce**

1. Open the Hammer Editor
2. Load the vox_house map linked below
3. Compile a map
4. Observe that some of func_voxelsurfaces are misplaced 

**Expected behavior**
Entity should be located as seen in the editor

**Screenshots**
before compiling (hammer editor view)
![image](https://user-images.githubusercontent.com/87721232/145682736-ebb95890-6058-42a0-aa4e-867fffabaacb.png)
after compiling (in game)
![image](https://user-images.githubusercontent.com/87721232/145682959-04303edf-4cac-4ac1-b124-4e7424ff0d90.png)

**Additional context**

https://github.com/heut42069/vox_house - map

**Comment by aylaylay** [comment]
If you ask nicely I'll fix it

**Comment by DoctorGurke** [comment]
pretty sure this is just related to the fact that mesh entities don't rebuild properly if you move them after tying them to an entity

**Comment by aylaylay** [comment]
probably just not transforming it properly like i do with the shatter glass

**Comment by aylaylay** [comment]
Working fine here. Not sure what's up

**Comment by DoctorGurke** [comment]
just for verification, try moving the mesh entities and recompile and see if they moved properly

**Comment by heut42069** [comment]
> Working fine here. Not sure what's up

That's weird, I've restarted the map and it looks almost perfect, except for two voxel planes.

![image](https://user-images.githubusercontent.com/87721232/145687876-778bcc41-b9a1-4e28-899a-8af9ad71ca4f.png)
![image](https://user-images.githubusercontent.com/87721232/145687887-9b21267d-b9f4-44f3-a4cc-40bfaa809e92.png)

**Comment by heut42069** [comment]
![image](https://user-images.githubusercontent.com/87721232/146756984-858ce456-4d69-4f2e-8439-c69db5be897e.png)
![image](https://user-images.githubusercontent.com/87721232/146756970-0e8609c7-5378-4545-aa8c-2574d86395ad.png)

**Comment by aylaylay** [comment]
Fixed

**Comment by aylaylay** [comment]
This map should be working properly now
