### ISSUE TITLE
Event callback for when an Entity is created

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#1405]
**What can't you do?**
Have an event callback for when an entity is created.

**How would you like it to work?**
In the spawn method id just run an event .
```
Event.Run<Entity>( "entity.spawned", this );
```

then to use it of course

```
[Event( "entity.spawned" )]
public void OnEntitySpawn( Entity entity )
{

}
```

**What have you tried?**
n\a

**Additional context**
I'm making a game feature where any entity created after a certain time will get cleaned up when a new round starts.

**Comment by kurozael** [comment]
You could have an interface called IAutoCleanup and have any entities you want this to happen for implement it. Then, when a round starts you can do this:

```csharp
foreach ( var entity in Entity.All.OfType<IAutoCleanup>() )
{
    entity.Delete();
}
```

There are plenty of ways to handle  this. I don't see a need for this event because you have full control over your game code.

**Comment by DevulTj** [comment]
Entities have a variable on them to say if they're map spawned too, so you don't need an event.

**Comment by Jake-NSW** [comment]
Oh cool
