### ISSUE TITLE
Z-Fighting shadows with baked lighting on base shader

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1407]
**Describe the bug**
baking lighting on materials using the base shader will introduce weird z-fighting shadows

**To Reproduce**

1. make a generic material using the base shader
2. make a map with walls and lighting to produce proper shadows
3. do a full compile with baked lighting
4. notice weird z-fighting shadows on the walls

**Expected behavior**
For baked lighting to work as with any of the core shaders

**Screenshots**
with baked lighting
![sbox-dev_D4RbHTTySO](https://user-images.githubusercontent.com/12602100/145720674-f0747d0d-e565-4cf2-993c-8452fbeea1d5.png)

fast compile without baked lighting
![sbox-dev_5hXwCeGhL1](https://user-images.githubusercontent.com/12602100/145720690-6845be4a-0e42-4697-aab1-d8d2f9e3aa46.png)

map used for testing:
![sbox-dev_dbXuKTOQTZ](https://user-images.githubusercontent.com/12602100/145720773-41d424a6-b643-4de7-a00c-781b74fe5609.png)

**Comment by ogniK5377** [comment]
Can you provide a vmap for this?

**Comment by ogniK5377** [comment]
I've done quite a bit of digging and have determined that this is not an issue with the base shader, it is in fact an issue with the map you provided yourself. It happens on all materials, it becomes extremely prominent with a more reflective material. As you can see this is the complex material:
![2021-12-03_01-00-c3794199-1e74-418f-b535-99ff3a62a158-XRb6C3Ge](https://user-images.githubusercontent.com/25727384/146647563-09ca4087-94f4-4a9d-b1fa-29b2fb420351.jpg)

**Comment by DoctorGurke** [comment]
I made that test map specifically for this issue request, doing nothing out of the ordinary

**Comment by ogniK5377** [comment]
The issue is with the map you provided. The light probe volume is interesting with the wall, the reflection generated are obviously going to z-fight then. Extending them solves this issue. This is an issue with the map itself
![image](https://user-images.githubusercontent.com/25727384/146648030-89bbaa7f-df7f-44f0-8050-18d55ebec1c6.png)

**Comment by DoctorGurke** [comment]
My life has been a lie, I've always used them like that 😩 
thank you very much for investigating, I will now go reconsider my life choices
