### ISSUE TITLE
Unavailable Buttons Aren't Grayed Out In Tools

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1409]
All buttons in tools are solid white, regardless of if we can actually press them.
![image](https://user-images.githubusercontent.com/39461072/145774727-612d3b4e-4ba9-43ea-9e12-6a2d7dacf500.png)

Here's what is should look like: 
![image](https://user-images.githubusercontent.com/39461072/145775720-952c112d-54dd-4480-b8a7-c58c60f68565.png)

**Comment by garrynewman** [comment]
Thanks, fixed, sorry it took so long
