### ISSUE TITLE
Display not functioning/flickering when loading into a map (AMD)

### ISSUE THREAD

**Issue by Dakarun** [Facepunch/sbox-issues#1414]
**Describe the bug**
When loading into a game/map the display will repeatedly flicker until the process is terminated. This behavior does not occur on the main menu. I was able to load into a game once, but after about 10 seconds the issue presented itself as well.

**To Reproduce**

1. Start a server (In this case Sandbox with Construct)
2. Wait for game to load in

**Expected behavior**
Display does not flicker during

**Screenshots**
Can record a video if needed

**Additional context**
I've reinstalled/updated GPU drivers to ensure that was not the issue. I haven't experienced this issue in other games. I'm running a AMD Vega 64 and 5900x. I've tested with exclusive full screen as well as borderless windowed.

**Comment by VCSoldier** [comment]
Issue i made sounds familiar to what your encountering
https://github.com/Facepunch/sbox-issues/issues/1415

**Comment by Dakarun** [comment]
> Issue i made sounds familiar to what your encountering #1415

Looks like the same issue to me

**Comment by uglycoal** [comment]
Please check current game build. Close the issue if it's fixed.

**Comment by Dakarun** [comment]
Can confirm it works now, thank you for fixing.
