### ISSUE TITLE
Construct Water Crashing AMD cards

### ISSUE THREAD

**Issue by VCSoldier** [Facepunch/sbox-issues#1415]
**Describe the bug**
Opening construct at all will crash amd cards, this is likely due to the water

**To Reproduce**
1. Run SBOX with an amd computer
2. Open construct

**Expected behavior**
Opens construct without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/50423227/146077388-d5fab1d5-16df-491e-9ffb-a3a752f621bf.png)

**Additional context**
GPU
AMD RX 580 8GB Sapphire Nitro+
24GB RAM
i7-4790k

Edit: session log if thats helpful
[Log.log](https://github.com/Facepunch/sbox-issues/files/7714719/Log.log)

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by handsomematt** [comment]
This should now be fixed, please give it a try and close the issue if it's working as expected.

**Comment by TehFlaminTaco** [comment]
I was having this problem previously, but this patch has fixed it.
