### ISSUE TITLE
ent_door Damage Opens Setting

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1418]
Currently we can only open ent_door with map logic or the Use key. I have a door that I need to open when it's shot.

ent_door should also have an OnDamaged output.

**Comment by robotboy655** [comment]
I have added `OnDamaged` output. I am still mulling over whether we want to have "Shoot to open" as a separate option. Can I inquire what are you needing this for?

**Comment by gvarados1** [comment]
Target Practice Targets

**Comment by robotboy655** [comment]
My concern is adding gamemode specific things like bullet damage to base entities is that may not be appropriate or even work in other gamemodes.

The map blueprints system, whatever(and whenever) that ends up looking like, could probably be better suited for things like these.

**Comment by DoctorGurke** [comment]
how is "TakeDamage" gamemode specific? doesn't have to be bullet damage specifically, just damage, which is a base part of entity

**Comment by robotboy655** [comment]
I have added "OnDamage" output that is fired for **any** damage. There is no way to react to specific damage types though like the request is asking for.

**Comment by gvarados1** [comment]
looks like there's no interest in adding this
