### ISSUE TITLE
Hammer: Making a brush with the block tool with another brush selected should retain selected brush's position

### ISSUE THREAD

**Issue by randomperson189** [Facepunch/sbox-issues#1419]
**What can't you do?**
So I have a brush selected and then make a brush on a 2d view with the block tool, the created brush doesn't retain the position of the selected one, Source 1 Hammer had this feature.

**How would you like it to work?**
Add it like it is in Source 1 Hammer.

**What have you tried?**
Duplicating the brush and moving/resizing it but that takes longer than simply using the block tool.

**Additional context**
The timestamp of this video demonstrates what I man by this feature: https://youtu.be/nfIW_2sDphc?t=668

**Comment by aylaylay** [comment]
https://user-images.githubusercontent.com/1667289/147600987-4c31de6d-dff5-411e-b580-9fd4ced27122.mp4

**Comment by DoctorGurke** [comment]
does this work on all axis including using 2d views?

**Comment by aylaylay** [comment]
yes

**Comment by SethTooQuick** [comment]
This is awesome, but it'd be neat if it also did it in the 2D views. Creating primitives in 2D views completely ignores this.
