### ISSUE TITLE
[Hammer] Clicking on the browse button in the Active Material window toolbar causes s&box to crash

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1420]
**Describe the bug**

s&box crashes when clicking on the "browse" button on the "Active Material window toolbar".

**To Reproduce**

1. open sbox-dev
2. open hammer
3. click on the browse button within the Active Material window.
4. observe

**Expected behavior**

Open up a material selection window of all available materials.

**Video**
  

https://user-images.githubusercontent.com/23345567/146431568-bf40e635-0e3c-4b39-81f6-c0c6675f4db7.mp4

**crash log & minidump**
[Log.log](https://github.com/Facepunch/sbox-issues/files/7729821/Log.log)
[sbox-dev_2021_1216_141344_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/7729850/sbox-dev_2021_1216_141344_0_accessviolation.zip)

**Comment by Adesii** [comment]
Same thing happens when you try to add a Child to a Particle system

**Comment by justynboi** [comment]
Same thing happens when you open the Texture Browser in the Material Editor

**Comment by OMGOMGplays** [comment]
Same thing happens on SFM when trying to add anything that needs a seperate "asset browser" window or anything

**Comment by QuackCocaine** [comment]
ah well something certainly is fucked in the asset browser department

**Comment by garrynewman** [comment]
I got it m8s

**Comment by QuackCocaine** [comment]
sweet now it's working as expected!
