### ISSUE TITLE
Unable to use classes in a networked dictionary

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#1421]
**Describe the bug**
Using any valid class as the TValue for a networked IDictionary will compile but upon adding any entries it will throw an exception due to failed networking of said class.

**To Reproduce**
1. Create a networked IDictionary with any valid type as the key and a value of any valid class definition.
2. Add an entry to the networked IDictionary.
3. See the error "Can not NetWrite type X as it is or contains reference types"

**Expected behavior**
To be networked without error as IList is able to do this.

**Additional context**
Created a shell of a game so you can reproduce it easily.
Game is bughunt.netdictionarybug
Crash code is [here](https://github.com/peter-r-g/SBox-NetDictionaryBug/blob/master/code/NetDictionaryBugGame.cs#L23)

**Comment by handsomematt** [comment]
This one should be fixed now, if you want to network a class of data you can use a BaseNetworkable.
