### ISSUE TITLE
Crash on an AMD card causing driver failure and screen flickering

### ISSUE THREAD

**Issue by uglycoal** [Facepunch/sbox-issues#1422]
**Describe the bug**
I'm using latest AMD Radeon drivers, up to date. AMD Radeon RX 570 as GPU, latest Windows 10 version. Game crashes almost immediately on map Construct, experienced delayed crash on Flatgrass. Game freezes, screen goes black (with possibly colorful artifacts) then game tabs itself out, or AMD crash handler tabs it out and focuses itself, and says that response time for driver was exceeded or something. Then you can only close the game.

**To Reproduce**

1. Most likely test it on RX series AMD GPUs?
2. Open up Construct map and try to move.

If it's consistent, it will almost immediately freeze the game, screen might flicker and then AMD error screen pops up.

If it's not consistent, I'm willing to provide more information that could help to resolve this.

Attached log files from the latest session that had a crash on Construct too:
[Log.log](https://github.com/Facepunch/sbox-issues/files/7730795/Log.log)

**Comment by DoctorGurke** [comment]
possibly related to #1415 and #1414

**Comment by uglycoal** [comment]
> possibly related to #1415 and #1414

Seems so to me! Overlooked other reports of this problem, hope dupe issue is not bad.

**Comment by handsomematt** [comment]
This should now be fixed, please give it a try and close the issue if it's working as expected.

**Comment by uglycoal** [comment]
Had no problems with the newest version! Closing this issue.
