### ISSUE TITLE
LibraryMethod should have info about input parameters

### ISSUE THREAD

**Issue by nikita-strelok** [Facepunch/sbox-issues#1423]
**What it is**
Unimplemented

**What it should be**
```Parameters``` property or ```GetParameters()``` method
which returns ```Type[]``` types of input parameters or ```ParameterInfo[]```(better)

also it would be nice to have information about return parameter

**Comment by robotboy655** [comment]
https://asset.party/api/Sandbox.MethodDescription.Parameters
