### ISSUE TITLE
ConVar.Replicated not synced with server on join

### ISSUE THREAD

**Issue by Kaydax** [Facepunch/sbox-issues#1424]
**Describe the bug**
When setting a replicated convar in a lobby you host, for example uf_devhud in unicycle frenzy, and then leaving said lobby and joining another lobby, the convar is still enabled even though on the server the convar is false

**To Reproduce (Using unicycle frenzy for example)**

1. Start up a unicycle frenzy lobby
2. Change the uf_devhud convar to true
3. Leave and join another lobby that you dont host
4. uf_devhud is still true despite the fact its not enabled on the server

**Expected behavior**
The convar should be synced with the server (it being false in this case) and not be what the client already has set

**Screenshots**
Trying to set the dev hud when connected to a lobby you are not owner of:
![image](https://user-images.githubusercontent.com/11893096/146631029-dd5c9d51-3aa6-40cc-b2a8-6b351867cd0a.png)

Doing it again, but on a local server allows you to change it:
![image](https://user-images.githubusercontent.com/11893096/146631039-02750ba2-6e57-40b6-8ced-0c6dc28b3b1a.png)

Going back onto another server you are not hosting shows its still enabled yet you cannot change the value itself:
![image](https://user-images.githubusercontent.com/11893096/146631049-3a4d091a-49f5-4e91-8606-1541355996a4.png)

**Comment by DoctorGurke** [comment]
#1112

**Comment by Kaydax** [comment]
> #1112

Ah ight. Closing now due to duplicate
