### ISSUE TITLE
ModelDoc ConfigRandomColor Node Not Fully Functional

### ISSUE THREAD

**Issue by atherlal** [Facepunch/sbox-issues#1425]
**Describe the bug**
When the modeldoc ConfigRandomColor node is utilized, it works as expected in the Hammer preview and models are given a random color from the gradient used in the model's creation. However, when compiling a map, the models do not keep their assigned colors in game.

**To Reproduce**

1. Create an asset in modeldoc, assign a ConfigRandomColor node with a gradient. 
2. In my situation, I sprayed the asset using the spray tool. The colors will be nice and random.
3. Build the map, load in game. Colors will not be maintained, and tint will be white.

**Expected behavior**
The colors of the models in game should match the colors in hammer.

**Screenshots**

![image](https://user-images.githubusercontent.com/63070549/146658324-b2f62ce1-0c76-44ea-8e36-ff50e72dc644.png)
Model doc asset created with the ConfigRandomColor node.

![image](https://user-images.githubusercontent.com/63070549/146658328-7e688453-6bde-4b8f-9435-dac88e796e71.png)
Assets utilize a random color when spawned in hammer.

![image](https://user-images.githubusercontent.com/63070549/146658336-0b6cc32c-e40c-47f7-bc22-94903663d4c8.png)
Assets lose their tint in game.

**Additional context**

Noted that while the objects show a nice color in the hammer preview, they show white in the color option of the object properties panel.
Thanks :)

Intel i9-9900k
Nvidia 2070

**Comment by atherlal** [comment]
Want to add that this applies to the ConfigSetRenderColor as well. 

![image](https://user-images.githubusercontent.com/63070549/146850593-146f7ce8-2c0e-423a-b411-33431f63ce6c.png)
Objects in hammer as sprayed.

![image](https://user-images.githubusercontent.com/63070549/146850885-0c995e0d-c565-4ce4-a038-67460ae3e867.png)
Assets in game. 

Thanks all : )

**Comment by robotboy655** [comment]
The `SpawnConfig` system is currently completely disabled for entities (seems to be it was made for HL games), and I am not sure what's the best approach to making this work is.

We can either simply reenable the existing system, potentially expose it to c# later.

Or we can just scrap this system and replace it with already existing model generic game data system, which already has c# bindings, but then Hammer & ModelDoc visualization would need to be remade.

There are also a bunch of nodes that seem to be non functional like `DynamicConfig`, `ConfigRandomPick`, `ConfigGroup`, `ConfigReference`, etc.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/165934269-e58cc83f-4afb-4715-8d12-7dd5bed307df.png)

I have now added a replacement for the feature that didn't work.

It works in-game and is previewed in the editor like before.

**Comment by bakscratch** [comment]
Yes this works 👍
