### ISSUE TITLE
Labels don't render terminating newlines right

### ISSUE THREAD

**Issue by MuffinTastic** [Facepunch/sbox-issues#1427]
**Describe the bug**
Newlines without any text afterwards will show up as some sort of strange "space", rather than a proper new line. This is most obvious when working with multiline TextEntries.

**To Reproduce**
1. Make a multiline TextEntry, or download [this test repo](https://github.com/MuffinTastic/sbox-multiline-test/archive/refs/heads/master.zip)
2. Type some junk
3. Hit enter for a newline
4. See weird behavior

**Comment by ogniK5377** [comment]
Should be fixed next update

**Comment by MuffinTastic** [comment]
Fixed

**Comment by MuffinTastic** [comment]
Was a bit premature in closing. Placing the caret right after a newline character, at the beginning of the next line, now causes the caret to appear one line below where it actually is.
![sbox-dev_uMgIt9VDDZ](https://user-images.githubusercontent.com/10884425/146679931-2f069642-dcf5-441d-9feb-4b2c8f68ef28.png)

**Comment by MuffinTastic** [comment]
Latest issue here is still relevant

**Comment by cr4yz** [comment]
This should be fixed in next update
