### ISSUE TITLE
Allow prop_static to have multiple surface properties

### ISSUE THREAD

**Issue by gusdleon** [Facepunch/sbox-issues#1433]
**What can't you do?**
Make a **prop_static** with different surface properties just like a **prop_physics**

**How would you like it to work?**
Just, like **prop_physics**...
If you make a **prop_physics** with multiple **physichull** files and assign different surface properties like metal and concrete to every hull, in game the prop will have different properties like sound or particles, in every section of his hull, the same should happen with **prop_static**

**What have you tried?**
[This](https://youtu.be/l3lXQyLsKzM)

**Additional context**

**Comment by aylaylay** [comment]
This is something we've been meaning to fix for a long time. The map builder didn't have access to surface property names, now they do. Should work now.

**Comment by gusdleon** [comment]
OMG [IT WORKS](https://youtu.be/oXYQMDW0URU)!! 

Thanks @aylaylay 💗,it works as intended, 
do you realize that was a limitation since Source1, probably since GoldSrc (or quake... idk),

**Comment by aylaylay** [comment]
That's kinda impossible because this is only a bug because C# loads surface properties, which aren't available in the map compile process.
