### ISSUE TITLE
Whitelist file and IO type exceptions

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#1434]
**What it is**
Been messing around with file systems and noticed there are no exceptions whitelisted in regards to files and IO.
The following is a list of exceptions that I could find that made sense:

`System.Private.CoreLib/System.IO.IOException`
`System.Private.CoreLib/System.IO.FileNotFoundException`
`System.Private.CoreLib/System.IO.DirectoryNotFoundException`
`System.Private.CoreLib/System.IO.FileLoadException`
`System.Private.CoreLib/System.IO.PathTooLongException` 
`System.Private.CoreLib/System.IO.EndOfStreamException`
`System.Private.CoreLib/System.UnauthorizedAccessException`

**Comment by handsomematt** [comment]
Whitelisted.
