### ISSUE TITLE
Add Render.UI.Line

### ISSUE THREAD

**Issue by nikita-strelok** [Facepunch/sbox-issues#1435]
**What can't you do?**
I can't draw lines in Panel rendering blocks

**How would you like it to work?**
The method Render.UI.Line(Vector2 from, Vector2 to, Color col, float thickness)

**What have you tried?**
I tried use Render.GetDynamicVB( ) and draw line via it but I couldn't set render color.

**Additional context**

**Comment by cr4yz** [comment]
`Render.Draw2D.Line` exists now
