### ISSUE TITLE
s&box ignores the organisation name in ident

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#1436]
**Describe the bug**

ATM for s&box idents such as `tesa.tsc` and `sharpmars.tsc` are identical, which is not the right behaviour.

**To Reproduce**

1. Download https://github.com/rndtrash/Terrys-Summer-Car to the addons folder
2. Join the Terry Saves Christmas gamemode

You may notice that the game has a first person camera instead of the top-down view it's supposed to be. If you take a look into the console, you can see that for some reason Terry's Summer Car's Game class was made instead of Terry Saves Christmas one.

**Expected behavior**

When playing Terry Saves Christmas, it should play Terry Saves Christmas, and not Terry's Summer Car.

**Screenshots**

![sbox_IhL8JETbFC](https://user-images.githubusercontent.com/6745157/147396187-4c333f14-dcd8-4a58-996e-947debd3f3c9.png)
![sbox_WaA9MuUS1c](https://user-images.githubusercontent.com/6745157/147396190-d0407c04-e2c2-4812-ba2e-a4452d94d8b6.png)

**Additional context**

Terry's Summer Car ident: `tesa.tsc`

Terry Saves Christmas ident: `sharpmars.tsc`

**Comment by robotboy655** [comment]
I am unable to reproduce this by making a local copy of Sandbox, changing its ident to a different org and then loading the non-local version of Sandbox, so I am assuming this is fixed.
