### ISSUE TITLE
Can't even launch sbox

### ISSUE THREAD

**Issue by dotCore-off** [Facepunch/sbox-issues#1438]
**Actual behavior**
When opening sbox, it just crashes before getting into the main menu.

**To Reproduce**
Not really any kind of reproduction steps.

**Expected behavior**
Game should be able to run properly I guess.

**Screenshots**
![image](https://user-images.githubusercontent.com/64563384/147431503-d09a3e26-a442-46b7-93ca-f73cf6cd6e40.png)

**Additional context**
It's happening on a fresh install with a decent computer's configuration.

**Comment by bakscratch** [comment]
I'd suggest trying deleting the base folder in addon/ and "Verify Integrity" on steam
