### ISSUE TITLE
False positive virus

### ISSUE THREAD

**Issue by pizzadox11** [Facepunch/sbox-issues#1439]
**Describe the bug**
When scanning for viruses in Malwarebytes it always mark these files as viruses
(Windows Defender doesnt flag them)
I mean it can be kinda confusing if you use real time protection of Malwarebytes

**To Reproduce**
Just scan SBOX folder for viruses in Malwarebytes

**Expected behavior**
Files get deleted and you unable to play the game

**Screenshots**
https://i.imgur.com/2ZZn2e0.png

**Additional context**
WIN 8.1 AMD R9 270X

**Comment by handsomematt** [comment]
Report the false positive to your anti virus vendor.

**Comment by ogniK5377** [comment]
The file looks fine:
https://www.virustotal.com/gui/file/526e50c6a01b627879b403661f62556987861bb9c064ea81b3e3411b0b3269b4?nocache=1
It's possible you're infected with something or have something else which modifies the files.
