### ISSUE TITLE
Create Child on Particle Killed function in Particle System Editor

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#1441]
**What can't you do?**
Create a child Particle effect when a parent particle has died.
Example:
Rain hitting the floor and creating Child Splash particle in the place of the dead Parent Particles.
or
Firework like in the Minigolf gamemode for a hole in one. without having a predetermined amount.

Currently it is only possible to Enable child particles which limits the amount to the amount set in the particle editor.

**How would you like it to work?**
A function similar to Enable children from parent particle count but rather Create child from parent particle.
with a option to create the child on particle death (possibly with a list so it can randomly select one, this is mostly a nice-to-have and not needed for this to function).

**What have you tried?**
Getting the position from the parent particle in the child particle. and using the emit particles for killed parent particles.
but getting the position only works as a operator therefore setting it every tick moving to a new particles which isn't ideal.
Setting child control to particle position. also doesn't work since it will just copy a single particle until that particle died.

**Additional context**
im currently trying to create a rain particle with splashes using trace hits which kills the particle and should create a splash effect on the hit position.

**Comment by bakscratch** [comment]
Is in Core "particles/example/on_kill_example/on_kill_example.vpcf" the type of thing you was looking for?

**Comment by Adesii** [comment]
> Is in Core "particles/example/on_kill_example/on_kill_example.vpcf" the type of thing you was looking for?

Not really. since this only works with a single particle. imagine that same particle but instead of Emit Constant set to 1 it set to 10 and working the same way.
because otherwise you would need to manually create this On_Kill_Example 1000 times for each time you want to have it which is just odd because you might not know how many you want in the end. i want it to work exact same way like in the example just with a procedural amount of parent particles. so its easily scalable.

**Comment by bakscratch** [comment]
"Init from killed parent particle" and "Position from parent particles" should help you now.

**Comment by Adesii** [comment]
Yeah, that seems about what i wanted. tho i noticed that sometimes it creates multiple particles per dead parent particle. if there are lots of parent particles. i assume its because they die at the same time so it can't choose which parent particle to create from.

should i open a new issue on that or keep this one open?
seems more like a minor issue in most situations. i haven't seen it fail yet with low amounts of particles. but still a thing to consider fixing later on.
