### ISSUE TITLE
Add preprocessor defines to csproj

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#1442]
**What can't you do?**
Use any of the preprocessor defines that S&box uses effectively. Currently, in the csproj they are all undefined so if I write:
```cs
#if (SANDBOX && DEBUG)
Log.Info( "Very cool" )
#endif
```
Will always be ignored in an IDE even though S&box will compile and run that code just fine.

**How would you like it to work?**
For each preprocessor define that S&boxs compiling process uses to be added to the csproj.

**What have you tried?**
Using define for each preprocessor definition manually will only work on a per-file basis and is a huge waste of time in large projects. I've also tested [this StackOverflow answer](https://stackoverflow.com/a/51782647) and it worked perfectly. However, the next time you run S&box it'll overwrite the csproj.

**Comment by ogniK5377** [comment]
Should be in the next update

**Comment by peter-r-g** [comment]
Works great, thank you!
