### ISSUE TITLE
Ability to add custom preprocessor definitions

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#1443]
**What can't you do?**
Add preprocessor definitions to test different functionality without hindering the structure of code.

**How would you like it to work?**
A menu in the S&box editor where you can add a semi-colon separated list of preprocessor definitions that'll be applied when creating a local game. If there is a non-default set of preprocessor definitions then the game should probably be locked to only containing that player to prevent weird behavior between multiple clients' games.

**What have you tried?**
Using define for each preprocessor definition manually will only work on a per-file basis and is a waste of time in large projects where functionality could spread to many files.

**Comment by ogniK5377** [comment]
This really seems like it would completely defeat the purpose of hot reloading as you would end up rebooting your game each time. If it's purely for debugging and testing as it sounds like here, why not use:
`#if true` and `#if false`.

**Comment by peter-r-g** [comment]
> This really seems like it would completely defeat the purpose of hot reloading as you would end up rebooting your game each time.

In my mind, you would have an option in the menu state where you can change the preprocessor definitions like how you can only change the net fake lag from the menu state. In-game hot reload would work as normal and would just hot reload with the preprocessor definitions provided.

> If it's purely for debugging and testing as it sounds like here, why not use:
> `#if true` and `#if false`.

I've somewhat already mentioned using that:
> **What have you tried?**
> Using define for each preprocessor definition manually will only work on a per-file basis and is a waste of time in large projects where functionality could spread to many files.

Limiting it to true/false only makes the problem worse.
