### ISSUE TITLE
Implement Collision Types for physics props in ModelDoc/collision_properties.txt

### ISSUE THREAD

**Issue by FireKeep-HLA** [Facepunch/sbox-issues#1449]
Currently **ModelDoc** lacks the ability to set proper collision types for props, requiring a work-around via addon scripts. Proper collision type implementation (debris, for example) would be useful, especially for making assets that can be used in maps unrestricted to any particular gamemode.

![image](https://user-images.githubusercontent.com/69137890/147843536-69fb9811-c3a8-46f9-b9a3-d1874dbaac93.png)

![image](https://user-images.githubusercontent.com/69137890/147843545-2ae08736-3ab6-4b20-8218-cecd6488e065.png)

Because of the current state, certain props will always collide with players when such a thing isn't desired. As an example, I can stand on top of this small physics bottle. Not something I'd want in the final product of the map.

![image](https://user-images.githubusercontent.com/69137890/147843540-8ced68b2-2987-4223-980b-cb92a1b3fe17.png)

**Comment by aylaylay** [comment]
Editing collision_properties.txt to add whatever you need should work as a temp workaround. I don't want to come up with anything better yet because I don't know what the plan is for the whole collision filtering system, it could all change.

**Comment by aylaylay** [comment]
<img width="250" alt="sbox_ly6X3R6I3b" src="https://user-images.githubusercontent.com/1667289/150674608-ba7a4f75-4676-4eb2-8ef0-8d9292ae1195.png">

You can now set these directly in modeldoc, let me know if it works

**Comment by FireKeep-HLA** [comment]
Sorry that this response is a bit late (I don't check GitHub very often), but I went in and was able to change the properties in ModelDoc, however the player kept colliding with the bottles even with the parameters.

![image](https://user-images.githubusercontent.com/69137890/151724442-95193b0f-c3bb-47b5-9151-6b475844a2fa.png)

**Comment by aylaylay** [comment]
I'll have a look

**Comment by aylaylay** [comment]
Okay so I figured out that these properties are only useful for prop_static, entities stomp these properties.

**Comment by FireKeep-HLA** [comment]
Interesting. I suppose it wasn't necessary to implement this for HL;A since the player doesn't move like a traditional WASD character, which may be why it was never properly implemented.

Is it possible to make this applicable to physics props? And if so, I'm in no rush to get these assets out, so take all the time you need with this.

**Comment by aylaylay** [comment]
Closing, system has changed so this is outdated
