### ISSUE TITLE
assetbrowser command crashes game if any tool is open

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1454]
**Describe the bug**
The game will crash if the `assetbrowser` command is used while any tool is open.

**To Reproduce**

1. start sbox in dev mode
2. open any of the main tools(hammer, modeldoc, material editor, etc)
3. close the asset browser
4. use the `assetbrowser` command from the editor console

**Expected behavior**
For it to open the asset browser like usual

**Comment by aylaylay** [comment]
Should be fixed now.
