### ISSUE TITLE
Move map materials from core into a separate addon

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#1457]
**What can't you do?**
I can't search for materials for a map, such as wall and floor materials, without needing to search through engine materials as well.

**How would you like it to work?**
Similar to how the citizen model works, with the map assets broken out into a separate addon.

**What have you tried?**
I can search for the map assets with vague terms such as "floor" or "hs", but it would be easier to be able to check a box and only see assets usable for maps. This would also make finding assets that don't fit those terms easier, since I wouldn't need to scroll through engine materials to find them.

**Additional context**
S&box's Map materials next to engine materials
![image](https://user-images.githubusercontent.com/65134886/148053078-0587d446-59f5-43bd-b27f-cd57cf5a6b69.png)

Half-Life Alyx's materials separated from the core addon
![image](https://user-images.githubusercontent.com/65134886/148055052-11ffda7e-7624-4288-8c54-f11dbaa01f28.png)

**Comment by gvarados1** [comment]
This has been bothering me for a while. Definitely needs to be changed.

**Comment by bakscratch** [comment]
Me and @ogniK5377 set up tags to work, so now all the core s&box materals, models and maps are tagged correctly, you will only see editor/tools content if you select that tag. https://files.facepunch.com/louie/1b0411b1/sbox_whobIOoHgX.png

If there is anything that needs moving let me know and feel free to close if works correctly. <3

**Comment by GunnarKafel** [comment]
Works great, thanks!
