### ISSUE TITLE
Reflections request

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#1458]
In this request, I want to offer ideas for improving reflections, I understand that much that I can enumerate is impossible to implement, or difficult, but it's still worth trying :D

Additional cubemap entity settings:

The current cubmaps of the sandbox, and the whole source 2 lacks the resolution setting, at the moment the engine bakes cubmaps only in 256x. This resolution is very small, I suggest giving the setting, as in unigine or other game engines.

Source 2 256x experience:

![image](https://user-images.githubusercontent.com/54669564/148103907-b4be39b4-08c0-492c-af17-0e1d05b0b69a.png)

Better 2048x quality:

![image](https://user-images.githubusercontent.com/54669564/148104002-84a45527-3f93-40e2-8861-ada1cded95bc.png)

SSR and planar reflections:

SSR, despite working only in screen space, is a great thing! especially when combined with cubmaps, SSR will create a beautiful and dynamic world full of reflections.

SSR + Cubemaps 2048x:

![image](https://user-images.githubusercontent.com/54669564/148105331-ad8f13ef-494f-44e0-bc4f-ff93b0eac260.png)

As you can see, we are getting great results.

Also, Planar Reflections are useful for creating reflective surfaces like water in hl2 or mirrors:

![image](https://user-images.githubusercontent.com/54669564/148106098-fceca185-725e-438a-a4e1-ac85007ac445.png)

![image](https://user-images.githubusercontent.com/54669564/148106222-4fe215e5-ee65-4189-b4e0-556ac66e5866.png)

I know about SDF reflections from Sam, but they are very buggy, and also apparently reflect only AO proxy parts. This is why I created this request. ( And also apparently SDF reflections have only black color. )

![env_cubemap_array](https://user-images.githubusercontent.com/54669564/148108323-27731f9e-d362-46d5-965e-404e541d2fa2.png)

**Comment by samzanemesis** [comment]
We have planar reflections, I will see to expand it to something artists can use

I am really against using screenspace effects due to their expensiveness and they don't look very good

**Comment by gabengaGamer** [comment]
Will cubmaps get a resolution setting?

**Comment by kote2345** [comment]
> I am really against using screenspace effects due to their expensiveness and they don't look very good

Yes, but it seems to me in some cases it is better to use SSR, for example, for surfaces that strongly reflect, since with SDF all objects in reflection are black and it looks bad, with SSR it seems to me it would be better despite the limitation in screen space, and for rough surfaces like concrete, SDF is very well suited, since it is not very striking that the objects are black.

![image](https://user-images.githubusercontent.com/62496056/148205241-a5d332d3-2dd4-4222-815f-ca8240031c58.png)
![image](https://user-images.githubusercontent.com/62496056/148205258-ac3a3d9e-268f-4ac1-adb0-1b41cba4f7f3.png)

**Comment by ogniK5377** [comment]
> > I am really against using screenspace effects due to their expensiveness and they don't look very good
> 
> Yes, but it seems to me in some cases it is better to use SSR, for example, for surfaces that strongly reflect, since with SDF all objects in reflection are black and it looks bad, with SSR it seems to me it would be better despite the limitation in screen space, and for rough surfaces like concrete, SDF is very well suited, since it is not very striking that the objects are black.
> 
> ![image](https://user-images.githubusercontent.com/62496056/148205241-a5d332d3-2dd4-4222-815f-ca8240031c58.png)
> ![image](https://user-images.githubusercontent.com/62496056/148205258-ac3a3d9e-268f-4ac1-adb0-1b41cba4f7f3.png)
> 

In both these cases, SSR wouldn't work as the reflections contain pixel information which are not visible to the screen.

**Comment by kote2345** [comment]
> In both these cases, SSR wouldn't work as the reflections contain pixel information which are not visible to the screen.

Yes, I did not give a very good example.
Here's a better example. There is a highly reflective floor that reflects object with the correct color and it looks better if there was an SDF where the object would be black.
![image](https://user-images.githubusercontent.com/62496056/148206266-99013ec1-ff5f-4820-af9b-d2cdf909d359.png)

**Comment by kote2345** [comment]
Or here's an example. With SSR, it would look better, with normal color
![image](https://user-images.githubusercontent.com/62496056/148206939-d16c96db-6a60-438c-87a3-7898274554cc.png)

**Comment by ogniK5377** [comment]
> Or here's an example. With SSR, it would look better, with normal color
> ![image](https://user-images.githubusercontent.com/62496056/148206939-d16c96db-6a60-438c-87a3-7898274554cc.png)
> 

SSR wouldn't look good here as the roof would not be properly reflected as it's not visible on the screen

**Comment by gabengaGamer** [comment]
ssr in combination with cubemaps will look much better

**Comment by ogniK5377** [comment]
I don't think we'll be shipping SSR with the game itself, however, there's shader support and we do have a post-processing pipeline. You are free to implement it on your own. SSR doesn't look good in most cases and only really works in a tiny subset of situation, something like s&box it would look poor in most of the situations

**Comment by gabengaGamer** [comment]
Well, I suggest just transferring the SSR valve shader, it is in hla, steam vr, destinations and dota 2

**Comment by gabengaGamer** [comment]
![image](https://user-images.githubusercontent.com/54669564/148219668-007038d6-cf7a-4e95-851a-0b21c1eb721c.png)
Please give us the SSR source code from valve

**Comment by DevulTj** [comment]
No

**Comment by aylaylay** [comment]
No

**Comment by M2VC** [comment]
No
