### ISSUE TITLE
Ability to fetch model data such as verticies, normals, triangles, uvs etc

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#146]
**What can't you do?**
For `Model`, it would be nice to be able to fetch raw buffer data such as vertex information, normal information, uv information etc. Other details such as `Texture` should be exposed as well.

**How would you like it to work?**
```cs
ModelEntity modelEntity = (MyEntity as ModelEntity);
Model vmdl = modelEntity.GetModel();
Vertex[] vertex = vmdl.GetModelData();
Texture[] textures = vmdl.GetTextures();
```

**What have you tried?**
Currently, I use `GetModelName()`, open the actual vmdl_c file, and parse out the model data by hand. Having this all done internally would keep would allow for faster execution and it should work out of the box for dynamically generated meshes in-game(those made with `Model.Create`)

**Additional context**
The main reason for this is to allow for dynamic mesh fracturing and slicing. Both require the mesh to be rebuilt as well as its collisions, an easy-to-use function call to fetch the needed information for further processing would help a lot rather than trying to parse everything out manually

**Comment by aylaylay** [comment]
I'll look into it soon

**Comment by aylaylay** [comment]
I've been looking into this. It might be better to have in the API a way to convert a static mesh into a procedural mesh
