### ISSUE TITLE
Can't Set Game Control Mode

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1460]
Control Mode setting is missing from both the dev website and the in-game editor. This means we can't tag out games as VR/Controller compatible.

![image](https://user-images.githubusercontent.com/39461072/148252037-78c5d4e0-2538-4636-b1c3-c1374a67daee.png)

**Comment by gvarados1** [comment]
This is still an issue. I can't tag my VR game as VR.

**Comment by handsomematt** [comment]
You can set it again from "Game Setup" as well as the singleplayer/multiplayer/coop tags.

**Comment by gvarados1** [comment]
> You can set it again from "Game Setup" as well as the singleplayer/multiplayer/coop tags.

Thanks matthew, but I can't scroll down to click it.

https://user-images.githubusercontent.com/39461072/158857301-a694985f-781c-4804-9b5b-53b525120a55.mp4

**Comment by gvarados1** [comment]
Can't scroll down because description is too long

**Comment by gvarados1** [comment]
thankhew!

**Comment by gvarados1** [comment]
This is missing again.

**Comment by gvarados1** [comment]
Tony fixed it
