### ISSUE TITLE
Get Player's Language 

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#1462]
**What can't you do?**
Get what language the client is using for localization purposes.

**How would you like it to work?**
Could be shared on the `Client`, or client only on `Local`

**Comment by DevulTj** [comment]
s&box should provide a localization system to begin with imo

**Comment by handsomematt** [comment]
we can expose Steam's GetCurrentGameLanguage as a global variable somewhere easily for this

I imagine we'll have some sort of localization system in place down the line too, but exposing this for now is a nice way for people to do their own

**Comment by garrynewman** [comment]
Doesn't C# have built in stuff to get the current language

**Comment by handsomematt** [comment]
> Doesn't C# have built in stuff to get the current language

There is CultureInfo.CurrentUICulture ( and specifically not CurrentCulture ) - but we're stomping these in s&box currently to en-US currently, presumably so int/float/date/etc. parsing is consistent across regions.

**Comment by handsomematt** [comment]
Not quite getting the user's language, but there's some basic localization now: https://wiki.facepunch.com/sbox/localization
