### ISSUE TITLE
Fix ZipArchive Whitelist

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#1463]
What it is
Currently the whitelist has `System.IO.Compression/System.IO.Compression.ZipArchive.*`, which prevents you from calling the ZipArchive constructor or using ZipArchives at all

What it should be
change it to `System.IO.Compression/System.IO.Compression.ZipArchive*`, allowing us to construct ZipArchive using a stream.
This functionality is needed for my current project, as I'm downloading Beat Saber maps via HTTP and the API I'm using sends back compressed files.
I don't think there are any security concerns to changing this, as all of the ZipArchive constructors use streams.

**Comment by handsomematt** [comment]
Done, no security concerns at all. I think maybe this was trying to avoid ZipFile.Open or something.
