### ISSUE TITLE
[off/svphys/clphys] menu doesn't update on map restart

### ISSUE THREAD

**Issue by rugg0064** [Facepunch/sbox-issues#1467]
**Describe the bug**
In the console, the buttons for [off/svphys/clphys] get highlighted when you select one, but after a map reset (restart in console) or some other actions, whatever you had selected will stay selected, even though when the map loads the actual behavior restarts to what off does.

**To Reproduce**

1. Open sbox
2. Go into a game
3. Open the console
4. Press "svphys" or "clphys"
5. Observe that things are highlighted with physics
6. Type restart into the console
7. Notice that "svphys" or "clphys" is still highlighted even though you can't see collision meshes anymore.

**Expected behavior**
The highlighted button should stay consistent with what the game is displaying.
Whether or not that means you set it to off and highlight off or you keep whatever was selected highlighted and display that mode accordingly.

**Videos**
https://user-images.githubusercontent.com/35048262/148657012-a36c26e0-7561-4fc9-83c8-00055101742f.mp4

**Comment by robotboy655** [comment]
The dropdown now gets reset to off on map load.
