### ISSUE TITLE
Bad UI in local game browser and map browser

### ISSUE THREAD

**Issue by rugg0064** [Facepunch/sbox-issues#1468]
**Describe the bug**
On the menus for browsing local games as well as when you are looking through maps, if you scroll to the bottom you can't see the names of the bottom-most games very easily.

**To Reproduce**

1. Have a high enough quantity of local addons
2. Open sbox
2. Go to local games
3. Scroll to the bottom
4. Observe the bottom-most games names are obstructed by the blur with games are on it (Also, the purpose of the blur with games is unclear, it seems like its just 2 random games)
5. Repeat this for selecting a map, it is also blurred at the bottom.

**Expected behavior**
There should either be no blur here, or the scroll menu should stop higher up so games don't get cut off.

**Screenshots**
Images of the error:
![image](https://user-images.githubusercontent.com/35048262/148657114-d5ebe676-8b6f-4396-bd62-85f9399ffc6c.png)
![image](https://user-images.githubusercontent.com/35048262/148657126-1bb1a484-9df0-4d7e-9242-aecb2bee1ec1.png)

An image of how it should look:
![image](https://user-images.githubusercontent.com/35048262/148657145-46c6f136-5059-41dc-8442-8e6a3bb2af07.png)

**Comment by ogniK5377** [comment]
Should be fixed in the next update 👍

**Comment by MKotras7** [comment]
Looks like its fixed.

**Comment by rugg0064** [comment]
Looks like it's fixed.
