### ISSUE TITLE
Unable to right click and bring up the context menu for any image in the Material Editor

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#147]
As the title says. When right-clicking the image preview it does not bring up the context menu in Sbox.

Is pretty annoying to dig through the files to find the right image.

Here's what it should look like. (Screenshot from Alyx)
![unknown](https://user-images.githubusercontent.com/17112771/118089056-f19c8d80-b395-11eb-80c4-1fa70fc9a8c1.png)

**Comment by garrynewman** [comment]
Probably one for @aylaylay to look at

**Comment by aylaylay** [comment]
This should be fixed now

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by justynboi** [comment]
I will let you know once the build goes out.

**Comment by justynboi** [comment]
It works! Thank you!
