### ISSUE TITLE
Weird backspace behavior in console

### ISSUE THREAD

**Issue by rugg0064** [Facepunch/sbox-issues#1470]
**Describe the bug**
When I type something, sometimes (I don't know if the steps to reproduce will work 100% of the time) it skips a letter when I hit backspace.

**To Reproduce**

1. Open the game
2. Go to console
3. Type something into console
4. Hit backspace as many times as you want
5. One letter will be left unbackspaced

**Expected behavior**
It should remove everything that was typed

https://user-images.githubusercontent.com/35048262/148660745-578a5750-c4c4-4dec-bef4-f1a14405a6fa.mp4

**Comment by DoctorGurke** [comment]
#1459

**Comment by rugg0064** [comment]
Yeah duplicate of #1459
