### ISSUE TITLE
Game crashes if you spawn some props and exit skybox

### ISSUE THREAD

**Issue by megabro** [Facepunch/sbox-issues#1472]
**Describe the bug**
The game crashes if I spawn some props and fly away with noclip. Independent of gamemode and or `-tools` flag.
Log ends with:
```
2022/01/09 15:27:00.384	Engine	CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.	
2022/01/09 15:27:00.423	Engine	Bailing out of OnBlockForQuery after 0.250 seconds	
2022/01/09 15:27:00.675	Engine	Bailing out of OnBlockForQuery after 0.250 seconds	
2022/01/09 15:27:05.372	RenderSystem	ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( D3D11Device()->CreateTexture2D( &desc, bImmutable ? pSubResource : NULL, ( ID3D11Texture2D ** ) &pDx11Texture ) )	
2022/01/09 15:27:05.372	RenderSystem	*** Run with -dx11debug to see native D3D errors!	
2022/01/09 15:27:05.372	RenderSystem	ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( D3D11Device()->CreateTexture2D( &desc, bImmutable ? pSubResource : NULL, ( ID3D11Texture2D ** ) &pDx11Texture ) )	
2022/01/09 15:27:05.375	RenderSystem	ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( pDevice->CreateBuffer( &desc, NULL, &pD3dBuf ) )	
2022/01/09 15:27:05.375	RenderSystem	ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( pDevice->CreateBuffer( &desc, NULL, &pD3dBuf ) )	
2022/01/09 15:27:05.375	RenderSystem	ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( pDevice->CreateBuffer( &desc, NULL, &pD3dBuf ) )	
2022/01/09 15:27:05.375	RenderSystem	ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( pDevice->CreateBuffer( &desc, NULL, &pD3dBuf ) )	
2022/01/09 15:27:05.375	RenderSystem	ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( pDevice->CreateBuffer( &desc, NULL, &pD3dBuf ) )	
2022/01/09 15:27:05.375	Developer	XboxDVRCheck: AllowGameDVR = 0x00000001 (e0x00000006)	
2022/01/09 15:27:05.375	Developer	XboxDVRCheck: AppCaptureEnabled = 0x00000000 (e0x00000000)	
2022/01/09 15:27:05.375	Developer	XboxDVRCheck: GameDVR_Enabled = 0x00000000 (e0x00000000)	
2022/01/09 15:27:06.008	Engine	Bailing out of OnBlockForQuery after 0.250 seconds	
```

**To Reproduce**

1. Select the Facepunch Sandbox gamemode
2. Go on Construct
3. Spawn props using toolgun
4. Attempt to fly up
5. If game doesn't crash, repeat steps 3. and 4.
6. Observe crash

**Expected behavior**
Game doesn't crash.

**Screenshots**

https://user-images.githubusercontent.com/35005210/148685055-14842087-973f-4a3c-87e3-6be2af6a8c1c.mp4

**Additional context**
Logs and MDMP are included in the zip. Tried updating drivers and disabling xbox DVR.

[bugreport.zip](https://github.com/Facepunch/sbox-issues/files/7835192/bugreport.zip)

**Comment by ogniK5377** [comment]
Does this happen on any other maps? (a simpler one)

**Comment by megabro** [comment]
> Does this happen on any other maps? (a simpler one)

I tried to get it to crash on a simple test map with and without a 3D skybox and couldn't get it to crash, but I also tried on flatgrass and it froze after spamming some boxes and then finally crashed. Didn't even noclip anywhere when it froze, so probably doesn't have anything to do with leaving the map bounds, just something to do with the boxes.

Here are the files:
[flatgrass_freeze.zip](https://github.com/Facepunch/sbox-issues/files/7835579/flatgrass_freeze.zip)

This time it didn't crash instantly, but finally crashed when I resized the frozen window.
Says something about `Failed to create D3D11 pixel shader!` as well now.

**Comment by megabro** [comment]
Can't get it to crash anymore. I suspect that the `Fix incorrect bounds check on m_nNumFixedPlanes in CWorldCollideContextData, causing crash in rain particles` commit also fixed this for me, as I was getting a similar crash on maps using rain.
