### ISSUE TITLE
Reset PathPlatformEntity (Hammer) through code

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#1475]
**What can't you do?**

Need a way to `reset()` a `PathPlatformEntity` to the start regardless of whatever node it's currently at.

**How would you like it to work?**

Write a `reset()` method on `PathPlatformEntity `

**What have you tried?**

Using `StartBackwards()` however that isn't instantaneous, attempted changing `OnEndAction` to `WarpToStart`, however I would need to force the `PathPlatformEntity` to reach the end.

**Additional context**

Unrelated, but, the method `StartBackwards()` has an incorrect summary
```
Start moving forward through our nodes until we reach end of the path.
```

**Comment by robotboy655** [comment]
I have added "WarpToPoint" input, which can be used to teleport the platform to the first (or any other) node. 

Seeing what you are asking this for, I am not going to add a "Reset" method, as I believe it's better to look into map cleanup system rather than keep adding hacks to every entity to reset them.

**Comment by mzegar** [comment]
Hey, yeah it seems to warp the entity to the proper node. However, the position / rotation of said entity is different than if you did a `GoToPoint(...)` call, is this the intended behavior? 

I guess my question is that the `position` & `rotation` doesn't seem to reflect the original `position` & `rotation` of the end when it is at node 0.

Thanks!

**Comment by robotboy655** [comment]
Oh sorry, rotation should be set correctly now.

**Comment by mzegar** [comment]
Thanks, appreciate the changes!
