### ISSUE TITLE
Resource.FromPath returns null on server.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#1478]
**Describe the bug**
I'm not sure when this started happening, but it's fairly recent. My weapon base loads a resource for the ammo type of a gun, for defining ballistic stuff, and it used to work fine. However its started returning a NRE on the server only. Clientside, the resource loads fine.

**To Reproduce**

1. Load a custom resource in the Spawn method of an entity and log the variable.
2. Load the custom resource in ClientSpawn and log the variable.
3. Server is null, client is valid.

**Expected behavior**
They both load normally.

**Comment by suiramdev** [comment]
I also have this issue and could fix it temporarly by retyping the Asset loading system myself.
![image](https://user-images.githubusercontent.com/71449142/150186074-6c2c2eb5-9a27-489c-b199-3e2d3dc9e749.png)
