### ISSUE TITLE
Get client language

### ISSUE THREAD

**Issue by Bobjes** [Facepunch/sbox-issues#148]
**What can't you do?**
At this moment s&box doesn't have any language localisation and when it implemented i would like to get player language. 

**How would you like it to work?**
`Player.Local.Language`

**What have you tried?**
Nothing. I dont have s&box key 😳

**Comment by Erlite** [comment]
Please refrain from making issues when you don't have access to the game, a good way to discuss these things is on the [forums](https://forum.facepunch.com/).

Other than that, could be nice.
