### ISSUE TITLE
Model attachments scaling offset

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#1480]
**Describe the bug**
When scaling an entity the attachment points remain in their old position.

**Example**
I have a model that has an attachment called "effect_origin", when scaling the object to 12 "effect_origin" will remain in the same position and effects will not show correctly.

**Desired behavior**
Would be neat if the attachment positions get updated automatically.

**Comment by aylaylay** [comment]
send a model where this happens please

**Comment by timmybo5** [comment]
[silencer_pistol.zip](https://github.com/Facepunch/sbox-issues/files/7855306/silencer_pistol.zip)

**Comment by timmybo5** [comment]
Without textures: [silencer_pistol.zip](https://github.com/Facepunch/sbox-issues/files/7855341/silencer_pistol.zip)
With textures: https://drive.google.com/file/d/17QwuXSvGbUYzjjuZQigs55mOFLBAIVGJ/view?usp=sharing

**Comment by timmybo5** [comment]
This turned out to be caused by a weird offset caused by ModelEntity on the viewmodel layer, using an AnimEntity fixed the issue.
