### ISSUE TITLE
Handles on Block Tool do not Vertex Snap until it is fully created.

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#1487]
**Describe the bug**
When creating a mesh with the block tool, you cannot grab the handles and vertex snap them. You must actually create the mesh in order to use the handles.

**To Reproduce**

1. Create a mesh with the Block tool.
2. Try to snap one of the handles onto a vertex.
3. The handles will not snap to the vertex.

**Expected behavior**
The handles in creation mode should behave the same as handles on a normal mesh and snap properly.

**Screenshots**

https://user-images.githubusercontent.com/65134886/149203654-4b3cdec1-9810-48a3-9edc-343680d1d368.mp4

**Comment by aylaylay** [comment]
Should be working now

**Comment by GunnarKafel** [comment]
Works great thanks 👍
