### ISSUE TITLE
Error and Crash on Loading Images from HTTP

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#1488]
**Describe the bug**
Loading too many images from HTTP at a time creates the error:
CRenderContextBase::SetAssociatedThreadIndex():
Too many threads accessing the render device, need to increase -r_max_device_threads

**To Reproduce**
Open up Beat Saber from the backend, then switch to the download tab and flip through the pages until you get the popup.

**Expected behavior**
No popup or crash, images load as expected without error.

**Comment by garrynewman** [comment]
Should be fixed (or deferred) in my push
