### ISSUE TITLE
Hammer - Unable to input decimal values in parameters with AZERTY keyboard

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#149]
**Describe the bug**

With an AZERTY disposition keyboard, you cannot input any decimals in any parameters using them.

I also tried to switch my keyboard to QWERTY but same result, I cannot input a "." and even if I use the one already in place by default, it does not change the entity at all.
The numpad "." also does not work for me either.

Worth noting that this totally works in Alyx's Hammer for me.

**To Reproduce**

1. Try to use the AZERTY keyboard disposition
2. Place any light or fog volume entity
3. Try to change its brightness or fog strenght to a decimal value

**Expected behavior**

The brightness or the fog strenght should change accordingly to the decimal value.

**Videos**

s&box Hammer - https://youtu.be/BcgTE1O6_dM
Alyx Hammer - https://youtu.be/wCRTfwwdzkA

**Additional context**

Using a French keyboard - AZERTY

**Comment by MoonlyDays** [comment]
This issue isn't specific to just Hammer. Can confirm that it is also happening in other tools like Anim Graph Editor.

**Comment by DoctorGurke** [comment]
I think this issue also extends to using the numpad in hammer to type in exact values for transform, rotate and scale. Germany uses commas for decimals, therefore having a comma on the numpad on QWERTZ keyboards instead of a period.

**Comment by KayaDLX** [comment]
**Workaround found for now:**

Go to your control pannel -> regional stuff -> regional format settings -> more settings -> change the decimal from `,` to `.`

Restart your tools and it will work. 👍

**Comment by MrBrax** [comment]
Would be nice to have decimal support without changing system settings 👍

**Comment by robotboy655** [comment]
I can't seem to reproduce the inability to place a dot ( `.` ) in the text fields when using the french AZERTY keyboard layout in Windows 10, and have that setting mentioned above set to `,` for decimal symbol.

**Comment by MrBrax** [comment]
swedish regional formatting (, separator) + swedish qwerty layout breaks it, at least for me. maybe it depends on keyboard hardware too?

**Comment by robotboy655** [comment]
Huh, setting regional format to Swedish does indeed break it, interesting.

**Comment by robotboy655** [comment]
So yeah, it is specifically the 2 options that affect this.
![image](https://user-images.githubusercontent.com/3299036/128902726-3348896c-2dbe-49c6-9bb9-4341a12966ea.png)

Seems Qt only allows those symbols to be inputted into those number fields (in addition to numbers themselves naturally)

**Comment by aylaylay** [comment]
I have pushed a potential fix. Check in modeldoc and see if you can now use "."
If it works, I can apply it in other places that use the QT validators.

**Comment by aylaylay** [comment]
Btw even if it fixes it, if germany does use "," instead of "." it probably wont be possible to allow that here because even though QT supports it, valve have their own string parsing that's used too which seems to force US locale. That's why 0,5 just resulted in 0

**Comment by MrBrax** [comment]
i don't think the problem is that people *want* to use `,` instead of `.`, it's just that they can't type in anything at all

**Comment by robotboy655** [comment]
The fix seems to work in my tests.

**Comment by KayaDLX** [comment]
Seems to be working for me! Cheers.

**Comment by MrBrax** [comment]
Has it been applied to every field now?
