### ISSUE TITLE
momentary_rot_button C# layer implementation

### ISSUE THREAD

**Issue by FireKeep-HLA** [Facepunch/sbox-issues#1491]
I've created a crankwheel asset that will function for flatscreen players virtually the same as the valve wheels in HL2, using the momentary_rot_button entity. Currently, this entity has not gotten the C# layer treatment, making it incompatible with many of the other C# entities and as of now is functionally useless. 

![image](https://user-images.githubusercontent.com/69137890/149383154-971c823b-5121-4cf1-bb05-d7af5643ccdf.png)

There isn't really a way "around" this - it just needs the C# implementation whenever possible.

For further context, I'm in the process of making lots of interactable assets (wheels, levers, switches, etc.) for the community to use at some point and some of these will require special entities to use. I would eventually like a lot of said stuff to also work in VR, but that's for a system I'll detail in another request.

**Comment by robotboy655** [comment]
I can't promise VR support as I don't own a VR headset, but yeah I agree that this is something that should be in the base game.

We will need to see what is the best way to output the data from it rotating though.

**Comment by xezno** [comment]
If you wanted a VR crank wheel you'd be better off using an anim interactable anyway, which has its own separate issue: #1264

**Comment by robotboy655** [comment]
I feel like since we are not a VR only game, it's best if we have as much stuff like this be the same entity and not have VR specific versions, so the levels can be played both with and without VR. That of course is not as easy as it sounds, but it should be doable.

**Comment by FireKeep-HLA** [comment]
> 

Agreed! This was the sort of system I was talking about that could be made later down the line - essentially a weird-ish mix of anim_interactable and regular flatscreen controls so players from both platforms could interact with the same item.

**Comment by FireKeep-HLA** [comment]
Also, for the data output - I'm not a programmer by any means but I'd imagine one potential solution could be something like this:

As a base, the entity Rotates a full 360 degrees. For output purposes, a full rotation of the wheel can be represented as "1" (and thus 0-1 designates a rotation amount between 0-360). This could then allow for the level designer to designate how many full rotations they want on the wheel (i.e. setting a maximum rotation value of 4 would allow for 4 full turns before the wheel hits "max"). When hooked up to something, like a door, it will take the value of the rotation amount and apply that to it's own movement.

Probably a confusing explanation (and might not even be the best way) but I'd imagine something like that could be how the system works.

**Comment by robotboy655** [comment]
`ent_button` now has `Momentary` property which allows it to replace functionality of `momentary_rot_button`.

It will fire `OnProgress` output as you move it with values in range of 0 to 1, for use in any custom entities. `ent_door` and `ent_platform` also got a `SetPosition` input so that they can work with these buttons.

**Comment by FireKeep-HLA** [comment]
Awesome! I'll give it a quick test and let you know if it works fine.
