### ISSUE TITLE
VRAD 3 : Embree and Open Image Denoiser update request

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#1492]
I think everyone knows that vrad 3 uses intel embree and open image denoiser. These are great libraries, but in all this long time they have become outdated. Vrad 3 uses Open Image Denoise v1.1.0 from 2019, during which time 9 updates have been released, in which both performance and quality have been improved. The same with intel embree, vrad 3 uses Embree v3.6.1 from 2019, over these 3 years 11 updates have been released, in which performance on Intel processors has been improved, and various bugs have been fixed. I suggest updating these libraries if possible.

**Comment by ogniK5377** [comment]
I did performance tests of both these already and there was no notable differences in the speed or quality

**Comment by gabengaGamer** [comment]
It all depends on the processor itself, I think it's worth laying it out and letting modders test it.
