### ISSUE TITLE
Getting bone information from AnimSceneObjects

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#1493]
**What can't you do?**
There are no methods that allow you to get the bone information of AnimSceneObjects which is preventing me from creating a ragdoll with bones that match the ones of an AnimSceneObject. 

**How would you like it to work?**
The same way it works with ModelEntity. BoneCount, GetBoneIndex(), GetBoneName(), GetBoneTransform(), etc.

**What have you tried?**
I tried replacing my AnimSceneObject with a ModelEntity but then it refuses to update the AnimGraph properly instead. 

**Additional context**
Inability to copy bones, visualized.
https://user-images.githubusercontent.com/16853532/149410552-78128fc4-46df-4a0e-a415-72f17e27137b.mp4

**Comment by aylaylay** [comment]
AnimSceneObject probably should have this but why are you not using AnimEntity in this situation?

**Comment by Leafdroid** [comment]
Cause the object only exists on the client so I'd have to copy-paste the default animgraph and change it so that the client can control it and then override the animgraph on the entity for that to work which feels a bit wacky to do, I'd prefer if I could just make it work with the default citizen animgraph and in this case using an AnimSceneObject seems to be the only way.

**Comment by aylaylay** [comment]
Wait what, AnimSceneObject already has GetBoneWorldTransform, you can get the skeleton info from Model
