### ISSUE TITLE
InputBuilder.Pressed behaves like InputBuilder.Down with gamepad/controller buttons

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#1494]
**Describe the bug**

InputBuilder.Pressed will return true every frame when using a controller, in a method hooked to Event.BuildInput

Input.Pressed still behaves normally inside a hooked method.

**To Reproduce**

1. Download and add issue-controllerpressed addon or log builder.Pressed in a method hooked to Event.BuildInput
2. Hold Score button
3. Watch console output

[issue-controllerpressed.zip](https://github.com/Facepunch/sbox-issues/files/7866677/issue-controllerpressed.zip)

**Comment by handsomematt** [comment]
Fixed thank you.
