### ISSUE TITLE
No Gamepad/Controller input when in sbox-dev

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#1495]
**Describe the bug**

Controller input is not detected in game when in sbox-dev.exe

**To Reproduce**

1. Open sbox-dev with a controller plugged in
2. Create a Sandbox game
3. Attempt to use the controller, input is not detected

**Additional context**

Win10
Xbone controller via usb
Attempted plugging in both during game and before launching game
Windows game bar overlay still works

**Comment by handsomematt** [comment]
Seems specific to the separate executable - sbox.exe -tools works fine.
