### ISSUE TITLE
SFM View Depth Buffer [Z-buffer]

### ISSUE THREAD

**Issue by PatrickJnr** [Facepunch/sbox-issues#1497]
**What can't you do?**
Not able to view the Depth Buffer in SFM

**How would you like it to work?**
Being able to type a command like r_depthoverlay 0|1 like in Source 1 SFM

**What have you tried?**
r_depthoverlay 0/1
sfm_vis_mode [1 through around 50]

**Additional context**
It'd be nice to be able to export a[n] Depth Buffer'd image to be able to use Photoshop/Gimp etc for better DOF

**Comment by ogniK5377** [comment]
What kind of depth buffer would it be? Would it be a linear depth buffer or non-linear?

**Comment by PatrickJnr** [comment]
linear depth buffer
