### ISSUE TITLE
base shader Color Tint does nothing

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#1498]
**What can't you do?**
In the base shader, there is the color tint option at the top.
using it, it does nothing.
![image](https://user-images.githubusercontent.com/82092361/149521604-cc818fa4-7a9e-4842-95a9-f868a92f024a.png)

**How would you like it to work?**
For some reason there is a Tint Color parameter below the textures?
but i think thats not really a good idea, i think its better to just have it use the Color Tint option that is at the top

**Comment by ogniK5377** [comment]
Should be fixed next update 👍

**Comment by NotGaylien** [comment]
lovely thanks ognik!
