### ISSUE TITLE
PhysicsJoint.Generic won't disable collisions

### ISSUE THREAD

**Issue by suiramdev** [Facepunch/sbox-issues#1499]
**Describe the bug**
To disable collisions between an object and another, we are supposed to use Generic constraints.
So, for my game mode, I created a model with collisions by default and a PhysicsJoint between my player's physic body and the object's physic body but it won't remove collisions.

**To Reproduce**
1. Create a Prop or a ModelEntity with Physics
2. Add a Generic PhysicsJoint between the player's physic body and the object's physic body.
3. Try it out

**Expected behavior**
It is supposed, as I said above, to remove collisions between objects A and B.

**Screenshots**
![My code](https://user-images.githubusercontent.com/71449142/149528213-262c93f4-0107-4c47-9119-d0e9c61d9748.png)

**Additional context**
I saw that `facepunch.sandbox` game mode is also using this method for the gravity gun but it also seems broken on it.

**Comment by aylaylay** [comment]
It's not broken, the physics objects aren't colliding. What's happening is that the player movement is still tracing against the object, you need to filter that out in the player movement code.

**Comment by suiramdev** [comment]
I had no clue that physics works like that, thank you, and sorry for disturbing you!
