### ISSUE TITLE
Mouse Reappearing on the wrong monitor when changing Pointer-Events

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#1500]
**Describe the bug**

When changing Pointer-Events ingame or generally making the mouse appear like opening the Menu with ESC.
The Mouse will appear on the wrong monitor.

this seems to be happening when moving the game to another monitor.

**To Reproduce**

1. Open any game that takes mouse focus.
2. Move the Game window to another monitor.
3. Hide the mouse by clicking into the game.
4. press Escape or anything that makes the mouse Reappear
5. See the mouse on the wrong Monitor

**Expected behavior**
It Should appear on the monitor the Game is on.

**Screenshots**

https://user-images.githubusercontent.com/37816311/149547067-1fa418f8-7ed3-42fc-9572-0011f58798ed.mp4

^Alex's video posted in #bugs. my original video is too big for github.

**Comment by handsomematt** [comment]
I can't seem to recreate this, is it still an issue?

**Comment by Adesii** [comment]
Probably not. i can't replicate it either. gonna close this issue for now until i manage to either replicate it or it appears again.
