### ISSUE TITLE
Addon FGD files not generating

### ISSUE THREAD

**Issue by dhog10** [Facepunch/sbox-issues#1503]
**The bug**
Ever since the update today (14/01/2022) the addon .fgd files are not generating. For example I created a class inheriting Entity, with a Library attribute, and this will not be generated inside the addon's fgd file. This is causing entities to not be available in hammer, and existing entities are not updating in hammer either.

**To Reproduce**
A screenshot of a very basic class which should generate fgd information and be available in hammer:

https://images-ext-2.discordapp.net/external/Vmn--YKFPV2lQYTz4mbBSd3sLauqx_oq1xdPTW8JeeA/https/i.gyazo.com/1cd08c85f2e5433a1c76347027b59e82.png

The above class does not generate in the addon.fgd file and is not available to create in hammer.

**Expected behavior**
The fgd file should be generated when the game is launched and should create information for this entity.

**Comment by MoonlyDays** [comment]
To supplement this, custom asset FGDs are also not being regenerated.
