### ISSUE TITLE
Addon system lets you add an addon twice, breaks things

### ISSUE THREAD

**Issue by rugg0064** [Facepunch/sbox-issues#1504]
**Describe the bug**

**To Reproduce**

1. Go to sboxdev
2. Add a .addon from disk twice
3. Go to addon manager and try to update schema
4. You wont be able to until you remove one of them

**Expected behavior**
Don't let users add 2 of the same addon

**Screenshots**

**Additional context**

![sboxbb22](https://user-images.githubusercontent.com/35048262/149607385-ca319f83-f3ce-418a-9709-be66e4044943.gif)

**Comment by handsomematt** [comment]
You shouldn't be able to do this anymore.
