### ISSUE TITLE
Missing tool icons

### ISSUE THREAD

**Issue by magnusm1908** [Facepunch/sbox-issues#1506]
**Describe the bug**
When opening the dev tools Hammer, Model, Particle, and Inspector tool icons are missing.
The buttons still work though.

**To Reproduce**
Open up s&box dev tools

**What have you tried?**
Reinstalling s&box

**Screenshots**
![iconsmissing](https://user-images.githubusercontent.com/25257251/149620465-04ee9aaa-83e5-400b-a824-cdcf7e2d4102.png)

**Additional context**
Specs: (Windows 10) (NVidia Card)

**Comment by garrynewman** [comment]
Have you tried validating content?

**Comment by magnusm1908** [comment]
Just tried but it didn't work either

**Comment by handsomematt** [comment]
Do you have an older version of the `Material Icons` font installed on your system?

**Comment by magnusm1908** [comment]
I have version 1.011 of Material Icons
I tried downloading all version of the font from github: https://github.com/google/material-design-icons/tree/master/font
and restarting after but to no avail.

![materialiconsfont](https://user-images.githubusercontent.com/25257251/149628088-30cc425f-2783-4a4a-bc71-659fe9771a60.png)

**Comment by NotGaylien** [comment]
actually im intrigued what does this one look like for you?
the icons window in the editor.
![image](https://user-images.githubusercontent.com/82092361/149635301-094af7c7-66df-4c4f-a28b-4b319782624b.png)
wanna get an idea of how many icons are actually missing for you (and the other guy/guys that have this issue)

**Comment by magnusm1908** [comment]
Oh no.
![iconswtf](https://user-images.githubusercontent.com/25257251/149635721-682d02bc-1c7d-4c93-8263-670ea0e8c70d.png)

**Comment by handsomematt** [comment]
What happens if you uninstall the font - I'm guessing Qt is just loading the one from your system instead of the one from the game.

**Comment by magnusm1908** [comment]
That fixed it thanks
