### ISSUE TITLE
Support CSS variables

### ISSUE THREAD

**Issue by Walrusking16** [Facepunch/sbox-issues#1507]
**What can't you do?**
Currently you can't use css variables in the style sheets. this would be very useful for repeat styles.

**How would you like it to work?**
It should function just like in css, the variables start with two dashes (`--`) and to get the value from the variable you wrap it in `var()`
```
.bg-gray {
  background-color: #fafafa;
  opacity: var(--bg-opacity);
}

.bg-opacity-50 {
    --bg-opacity: 0.5;
  }
```

**What have you tried?**
This causes a parsing error `Error parsing stylesheet: Input string was not in a correct format.`
```
.bg-gray {
  background-color: #fafafa;
  opacity: var(--bg-opacity);
}

.bg-opacity-50 {
    --bg-opacity: 0.5;
  }
```

**Additional context**

**Comment by cr4yz** [comment]
We have scss variable support:

```
$fontcolor: red;

.class {
  color: $fontcolor;
}
```

`@import "myvarfile.scss";` also works if you'd like to keep variables in a separate file.

**Comment by Walrusking16** [comment]
> We have scss variable support:
> 
> ```
> $fontcolor: red;
> 
> .class {
>   color: $fontcolor;
> }
> ```
> 
> `@import "myvarfile.scss";` also works if you'd like to keep variables in a separate file.

Hmm I see that but I am unable to change the value with a new css class which is what I am trying to do

This will compile fine but it does not change the value
```
$bg-opacity: 1;

.bg-gray {
  background-color: #fafafa;
  opacity: $bg-opacity;
}

.bg-opacity-50 {
    $bg-opacity: 0.5;
}
```

**Comment by garrynewman** [comment]
We're not going to have css variables. We have "template" scss variables which I feel should be enough for 99% of people.

**Comment by rndtrash** [comment]
> We're not going to have css variables. We have "template" scss variables which I feel should be enough for 99% of people.

I have a use-case for the CSS variables where I want to expose a single color that can be changed in the inline `style` attribute. Could you please reconsider adding them?
