### ISSUE TITLE
Joining Clients have to download files from the base addons.

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#1508]
**Describe the bug**
When I host a lobby of any gamemode, if a client joins they have to download files that are already installed from the base addons. If I join someone else's lobby, I have to download files unrelated to the gamemode. This only affects joining, if I'm hosting the gamemode I don't have to download the files.

**To Reproduce**
1. Join any gamemode
2. When you connect, you will have to download files from the base s&box addons.
OR

1. Host a gamemode.
2. When a client joins, they will have to download the unnecessary files.

**Expected behavior**
Joining clients should only download files required for the gamemode, since the base addons are already installed.

**Screenshots**
From hosting Unicycle Frenzy
![image](https://user-images.githubusercontent.com/65134886/149637381-3f2888ff-84e7-4262-8c85-6e722030d2f9.png)

From joining a Sandbox gamemode lobby
![image](https://user-images.githubusercontent.com/65134886/149637469-3af58fc2-f810-4475-b4bc-14650ee424e4.png)

**Comment by FireKeep-HLA** [comment]
New Update! Addon manager! New bug! Download citizen models!

**Comment by KayaDLX** [comment]
Can confirm.

**Comment by handsomematt** [comment]
Shouldn't be the case now.
