### ISSUE TITLE
ModelDoc - Add meshes via rightclick and get them into the selected folder directly.

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1517]
**What can't you do?**
Currently, I need to manually search for "Add Meshes..." or Use the star. 
**How would you like it to work?**
I could just right click on the folders inside the RenderMeshList, as it is done in the animations.

https://user-images.githubusercontent.com/40291120/149764253-aa92c500-360f-49e6-a8a1-d3d5706096fb.mp4

**Comment by aylaylay** [comment]
Done

**Comment by KaesarZZ** [comment]
<3
