### ISSUE TITLE
Unable to change SCSS variables inside classes

### ISSUE THREAD

**Issue by Walrusking16** [Facepunch/sbox-issues#1519]
**Describe the bug**
When you create an SCSS variable you can't update it inside any classes.

**To Reproduce**

1. Create new variable
2. Try updating the variable inside a class
3. See error in console

**Expected behavior**
The expected behavior is to update the variable with the new changes.

**Screenshots**
![rider64_9fXtBP1GRI](https://user-images.githubusercontent.com/20746458/149820754-f3d03bda-a76d-4aa5-94fe-e2b3b812dc34.png)
![sbox-dev_FOf3tB0LLA](https://user-images.githubusercontent.com/20746458/149820759-40e6725d-be3e-4aa8-abfa-0e9f9f452e20.png)

**Comment by garrynewman** [comment]
Yep, this isn't how this works, and not really how it's going to work.
