### ISSUE TITLE
Symbolic Links addons do not load content but can load their code

### ISSUE THREAD

**Issue by AWildErin** [Facepunch/sbox-issues#152]
**Describe the bug**
The tools do not recognise symbolic link addons. If I move it to the addons folder, it works fine, but it does not seem to work if I link them. The screenshots give an idea of what I mean. While it's not a game-breaking issue, it's still a pain as I like to hold my WIP addons in a different folder and link them to the addons folder.

The game recognises the code, however, both the tools and game do not recognise the content files, such as maps, models, etc.
This could be an issue with how I am setting up my symlinks, but I thought it could be best to report it anyway. It's worth noting that I use this method for working with Garry's Mod addons as to not clutter up my folder, and it'd be great if it worked well in Sandbox too

**To Reproduce**

1. Go to addons folder
2. open cmd in that folder
3. Create a symlink. My example `mklink /J "./testaddon" "E:\Repositories\sandbox\testaddon"`
4. Load up `sbox-dev.exe` and take note that the content option does not appear, but on the main menu your gamemode will.

**Expected behavior**
It should work as a normal folder, I don't know if this is down to how Sandbox loads files or how I've set it up but it's weird that it can locate the game mode but not the content.

**Screenshots**
Asset Browser not showing the addon:
![image](https://user-images.githubusercontent.com/28122025/118121168-f5a5cb00-b3e8-11eb-864f-f1366e2d644b.png)

Addons Folder:
![image](https://user-images.githubusercontent.com/28122025/118121188-ff2f3300-b3e8-11eb-9d16-8a4563789552.png)

The addon does have content:
![image](https://user-images.githubusercontent.com/28122025/118121222-0ce4b880-b3e9-11eb-9179-0ef129ede0e0.png)

**Comment by robotboy655** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.

If it is fixed feel free to close the issue yourself.

**Comment by AWildErin** [comment]
Yep, all working fine now. Thanks!
