### ISSUE TITLE
ModelBuilder physics crash "cannot create degenerate mesh"

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#1523]
**Describe the bug**
The game freezes up and crashes if you attempt to build a collision mesh where two or more indices of the same triangle reference a vertex in the same position.

**To Reproduce**
```cs
[ClientCmd]
public static void PhysicsCrash()
{
	Vector3[] vertices = new Vector3[3]
	{
		Vector3.Zero,
		Vector3.Zero,
		Vector3.Up
	};

	int[] indices = new int[3] { 0, 1, 2 };

	ModelBuilder modelBuilder = new ModelBuilder().AddCollisionMesh( vertices, indices );

	modelBuilder.Create(); // death
}
```

**Expected behavior**
Not crash, throw exception, possibly generate mesh anyway but without the degenerate tris?

**Comment by aylaylay** [comment]
Fixed
