### ISSUE TITLE
Access to directly drawing textures to UI

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#1527]
**What can't you do?**
Render a texture to the UI using an equivalent way to how `Image` does with `PanelRenderer.DrawBackgroundTexture`.

**How would you like it to work?**
The method would have similar parameters to `Render.UI.Box`, except it would also include `Texture` and `ImageRendering` arguments as well.

**What have you tried?**
A RenderEntity drawing quads could likely work, but that would be re-inventing the wheel.

**Additional context**
For what I'm trying to achieve, adding tons of Image panels to the UI is not efficient enough since each Panel probably has a certain amount of overhead attached.

**Comment by garrynewman** [comment]
There's a Render or Paint method on the panel you can override and draw manually

**Comment by Willco2** [comment]
There's `DrawContent` and `DrawBackground` to override (different from the identically named internal methods), but they don't seem provide a means of drawing a texture within them. `Render.UI` doesn't contain any methods for texture rendering either.

**Comment by Willco2** [comment]
The new `Render.Draw2D` feature resolves this.
