### ISSUE TITLE
Shader Texture Attribute "FrameBufferCopyTexture" not usable to get framebuffer

### ISSUE THREAD

**Issue by rob5300** [Facepunch/sbox-issues#1528]
Trying to get the frame buffer as a texture in a transparent/translucent shader in the same way as sbox glass results in an error.
Trying to use the same PS imports as sbox glass is not possible as some are missing, causing the compile to fail.

Using this attribute in a shader causes the following error to be printed:
`Attribute-based texture g_tFrameBufferCopyTexture not bound for material "materials/invisibility.vmat"! Missing render attribute "FrameBufferCopyTexture".  Context (null)`
This error continues to print until 50 (`^^^ Attribute-based texture warning is now disabled after outputting 50 warnings.`)

**To Reproduce**

1. Create a translucent shader
2. Add a new texture using the "FrameBufferCopyTexture" attribute:
```
    BoolAttribute( bWantsFBCopyTexture, true );
    CreateTexture2D( g_tFrameBufferCopyTexture ) < Attribute( "FrameBufferCopyTexture" ); SrgbRead( false ); Filter( MIN_MAG_MIP_LINEAR ); >;
```
3. Compile and observe working translucency but the frame buffer texture being the default error checkerboard (In Material Editor)

**Expected behavior**
The frame buffer texture grab correctly working for user created shaders, or an alternate solution being detailed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6060966/150220000-a237d058-9742-41d0-b0e3-0bb5ed56cbda.png)

**Additional context**
Windows 10 Pro 64 bit. 19042.

**Comment by samzanemesis** [comment]
That's in tools, is the same behaviour happening ingame?

@ogniK5377 could have a look

**Comment by rob5300** [comment]
Screenshot from in game, same behavior is displayed 
![image](https://user-images.githubusercontent.com/6060966/150407774-fa6bb8ac-8b02-487e-8064-cdee6afa2393.png)

**Comment by rob5300** [comment]
Shader source with slight modification to show the "blur" result always. Frame buffer blur code taken from sbox glass: https://gist.github.com/rob5300/c124cc8bd53d8bd8d530c69f69fb7d8d

**Comment by rob5300** [comment]
This problem seems to now be fixed.
