### ISSUE TITLE
Support instances in fbx file when importing into Hammer

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#1529]
Would it be possible to allow fbx files that include instanced objects to be automatically added into hammer as an instance instead of being converted to its own separate mesh? This would make importing instanced things such as map objects or whatever else (yes I know porting bad blah blah) a lot more efficient and be more resource friendly
[Instance Example.zip](https://github.com/Facepunch/sbox-issues/files/7901532/Instance.Example.zip)
The example when imported into blender has 45 objects instanced as 1, while importing into hammer makes 45 seperate objects

**Comment by aylaylay** [comment]
Not going to do this, doesn't make much sense as it all will get compiled to the same thing
