### ISSUE TITLE
Animgraph flashing upon opening second file, epilepsy triggering

### ISSUE THREAD

**Issue by MoonlyDays** [Facepunch/sbox-issues#153]
Opening second file in Anim Graph Editor while you already have one open causes a seizure effect and crash.

**To Reproduce**

1. Open Anim Graph Editor
2. Open any animgraph file
3. Open a different one

**Expected behavior**

Open the second file in a separate window.

**Video _(EPILEPSY WARNING!)_**

https://user-images.githubusercontent.com/32462579/118143386-f43dc800-b413-11eb-93e1-7635b3e68175.mp4

**Comment by aylaylay** [comment]
This should be fixed when the game next updates

**Comment by MoonlyDays** [comment]
Seems to be fixed. Thanks.
