### ISSUE TITLE
Client.IsUsingVr is inconsistent on bots

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#1530]
**Describe the bug**

When you add bots to a game, IsUsingVr returns true on some bot's Clients, and false on others.

**To Reproduce**
1. Launch s&box.
2. Load repro project (or any game that checks Client.IsUsingVr).
3. Check bot's Client.IsUsingVr value.

**Expected behavior**
IsUsingVr should default to false. Maybe there should be a virtual variable in Sandbox.Bot that lets you set IsUsingVr on the client instance.

**Screenshots**
![notvrmode](https://user-images.githubusercontent.com/43252311/150448816-0a9a6fe7-5aaa-4311-addd-a3048f3959ab.PNG)

**Additional context**
[I've attached a repro project,](https://github.com/Facepunch/sbox-issues/files/7909659/IsUsingVrRepro.zip) which simply logs IsBot and IsUsingVr in ClientJoined. Originally, I thought this was dependent on -vr mode/my Oculus Quest 2, however after further investigation, nothing seems to skew it one way or other.

**Comment by ogniK5377** [comment]
Should be fixed in the next update 👍
