### ISSUE TITLE
Cannot scale prop_statics on arbitrary axes 

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#1532]
**Describe the bug**
In Hammer you do not have the ability to scale prop_statics through the selection gizmo or with the Scale tool.

**To Reproduce**

1. Place a prop_static
2. Switch to the selection tool
3. You will not have the ability to scale it

**Expected behavior**
Non-uniform scale does not cause any issues with a prop_static, so it should be unlocked for this prop class.

**Screenshots**
Behavior currently in s&box
https://user-images.githubusercontent.com/65134886/150596249-022c0ed6-47dd-4ae3-8c4e-e4d56a1f480e.mp4

Expected behavior from previous s&box builds and HLA
https://user-images.githubusercontent.com/65134886/150596572-22fae3ef-a266-435a-96e5-146871d34bec.mp4

**Comment by robotboy655** [comment]
This should be fixed when the game next updates, sorry about this.
