### ISSUE TITLE
[Net] IDictionary with Entity keys are null

### ISSUE THREAD

**Issue by MoonlyDays** [Facepunch/sbox-issues#1533]
**Describe the bug**
If you make a [Net] dictionary that has some class that extends Entity as keys, then the dictionary property will always be null.

**To Reproduce**

1. Make a `[Net] IDictionary<Entity, int>` property
2. Try to access it
3. Observe it be null

**Expected behavior**
It should not be null.

**Screenshots**
```csharp
[Net] public IDictionary<int, int> Dict_Plain { get; set; }
[Net] public IDictionary<Entity, int> Dict_Entity { get; set; }

public override void Simulate( Client cl )
{
    base.Simulate( cl );

    DebugOverlay.ScreenText(
        $"IDictionary<int, int> = {(Dict_Plain == null ? "null" : Dict_Plain)}\n" +
        $"IDictionary<Entity, int> = {(Dict_Entity == null ? "null" : Dict_Entity)}\n" );
}
```
![image](https://user-images.githubusercontent.com/32462579/150609862-b9e60b95-eb9a-4f1a-ab4b-c593b8102da2.png)

**Additional context**

**Comment by handsomematt** [comment]
Should be fine now, I'd just made the generator a bit more stricter so had to figure out what people were even using.

**Comment by MoonlyDays** [comment]
Can confirm that it's fixed. Thanks!
