### ISSUE TITLE
Load models from other filesystems

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#1534]
**What can't you do?**

Can't load a model from a filesystem that isn't the default Mounted one, e.g. FileSystem.Data. 
This prevents me from streaming in models from a remote server and loading them as needed.

**How would you like it to work?**

Would be nice if we could pass a `BaseFileSystem` to `Model.Load` in the same way we can with `Texture.Load`.

**What have you tried?**

An alternative solution would be to use another file format, like OBJ/FBX, and write my own parser - but these formats are limited and writing a VMDL parser seems like a lot of work when something like this could just be exposed by the API.

**Comment by handsomematt** [comment]
Would you say s&works APIs satisfy your requirements @xezno ?

**Comment by xezno** [comment]
Yeah, I'd say it covers my use case :+1:
