### ISSUE TITLE
Particles in front of Viewmodel

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#1536]
**What can't you do?**
Draw a particle in front of a viewmodel or model parented to a viewmodel

**How would you like it to work?**
Could be a bool property on the `Particles` class to enable/disable this feature

**Screenshots**
Examples when the laser is drawn incorrectly:

![20220125200049_1](https://user-images.githubusercontent.com/4988198/151033533-c2c141f4-de55-415d-b999-6b5cbd438ef7.jpg)
![20220125200054_1](https://user-images.githubusercontent.com/4988198/151033541-21811f54-d6ff-4149-ab0c-6b3247cadc43.jpg)

**Comment by bakscratch** [comment]
I haven't tested this but in the base properties.

There is an option for Viewmodel Particle.
https://files.facepunch.com/louie/1b2511b1/sbox-dev_qWBAoOzoLt.png

It is hidden can unhide here.
https://files.facepunch.com/louie/1b2511b1/sbox-dev_NgPmeA7Aiv.png

**Comment by timmybo5** [comment]
Just tested, activating this made the laser invisible, maybe the feature is not done yet?
