### ISSUE TITLE
Boolean or Method if some Entity is currently being rendered to the player

### ISSUE THREAD

**Issue by Koshel4** [Facepunch/sbox-issues#1538]
**What can't you do?**

I cannot check if some gameobject (Entity) is being rendered to some player.

**How would you like it to work?**

There has to be some sort of boolean, method or something like that to check, if some Entity is being rendered at the moment

**What have you tried?**

First of all, I tried checking the camera angle, and using it to check whether the player sees the object, but firstly, it worked through the walls, and secondly, if the field of view became a little bigger or smaller, this technology broke down. Next, I tried to use the rays coming from the player, but they did not work when the player was just above or below the target. (and at a great distance of the player from the object, too many rays are needed, so this option is not suitable)

**Additional context**
I need such thing just to check if some Entity is visible to player, that's all. I've seen different built-in methods for checking if some gameobject is visible on the screen in different game engines, but not in Garry's mod or S&Box, that's why I am asking about it.

**Comment by ogniK5377** [comment]
You could easily do a sweep trace for the object you're looking for since you know the direction between the the two objects you're checking for

**Comment by kolexxx** [comment]
I think it would be way more convenient if this was just a boolean chech or method like in other engines

**Comment by ogniK5377** [comment]
In other engines, you use a dot product to check the viewing angle and a trace with a sweep of the direction of the object like I described above
