### ISSUE TITLE
Whitelist for TupleElementNamesAttribute

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#154]
**What can't you do?**
```cs
var bots = new List<(long id, string name)>
{
  (1, "Bot1"),
  (2, "Bot2"),
  ...
};
```

**How would you like it to work?**
I would like to be able to name fields inside tuples, currently it is not possible since the related compiler generated attribute is not whitelisted

**What have you tried?**
Using `var bots = new List<(long, string)>` instead, which works but requires e.g. `bot.Item1` instead of `bot.id`

**Additional context**
![image](https://user-images.githubusercontent.com/1809172/118176088-a20f9d80-b439-11eb-98d0-1e898801a9fc.png)

```
System.Private.CoreLib/System.Runtime.CompilerServices.TupleElementNamesAttribute`
```

**Comment by rtm516** [comment]
In your example is it not better to use a dictionary?

**Comment by Erlite** [comment]
Technically yes in this example, but in any case this is a very useful thing to have. Instead of unnamed tuples, you can give a name and basically make "temporary" types.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Trojaner** [comment]
Works now, thanks.
