### ISSUE TITLE
Overlays materials & particles no longer preview in tools

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#1540]
**Describe the bug**

Not sure why this started happening but since a few days overlays and particles no longer preview in Hammer & the asset browser.
![image](https://user-images.githubusercontent.com/67245359/151212214-cccec6a8-b52b-4ef1-8814-39233d2f2dfc.png)
![image](https://user-images.githubusercontent.com/67245359/151214321-63ca5b55-5b3a-4d82-b23a-e02139accbc1.png)

For particles, ideally the thumbnail screenshot should be taken after a few frames delay so it takes an accurate preview of the particle mid-life.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/151836530-320b83e7-707b-4ba6-b89b-152491cd72e6.png)

Particles seem to work, but the dark gray background probably causes some to be invisible. Still we can probably make it better.

I have noticed that Live particle preview does not seem to be functional anymore however:
![image](https://user-images.githubusercontent.com/3299036/151836904-505ea9dc-f64d-4385-a1e2-7b80d830a693.png)

**Comment by aylaylay** [comment]
iirc garry disabled live preview, probably cos it sucks

**Comment by KayaDLX** [comment]
I feel like some are also not showing up because their thumbnail is taken on the first frame and not mid-life, so you can't see anything. I might be wrong though.

**Comment by KayaDLX** [comment]
Still relevant, I can't tell which decals/overlays I'm using
![image](https://user-images.githubusercontent.com/67245359/153902401-9bd70a5a-3ec3-46bf-a7bf-84cd0d6bd38f.png)

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/158235429-a8b8758d-43ea-4043-a384-6968735c246f.png)

garry fixed this a few days back
