### ISSUE TITLE
sbox-dev not focusing game

### ISSUE THREAD

**Issue by AlexVeeBee** [Facepunch/sbox-issues#1543]
i think this will explain it self

https://user-images.githubusercontent.com/75509525/151456825-51671a6b-870c-4da8-936c-989a19110e72.mp4

i cant move nor got to the main menu

**Comment by yuberee** [comment]
I can confirm that it happens to me as well. This has started happening around 2 hours ago.

**Comment by timmybo5** [comment]
Same here, can only use mouse input.

https://user-images.githubusercontent.com/4988198/151459946-6caef1cf-88c0-440a-bc9a-3862fa36ad5e.mp4

**Comment by garrynewman** [comment]
Does this ALWAYS happen, or only sometimes? Are there ways to make it happen?

**Comment by AlexVeeBee** [comment]
Happen to be always

**Comment by Adesii** [comment]
Just tested it, and it seems to always happen. In any Gamemode.
non-tools mode works fine tho.

**Comment by trundler-dev** [comment]
+1, happening to me too. I tried reinstalling my game, erasing the config, etc.

https://cdn.discordapp.com/attachments/834329341189816350/936677689039941643/sbox_editor_2022-01-28_13-41-25.mp4
https://cdn.discordapp.com/attachments/834329341189816350/936677949355229214/sbox_editor_2022-01-28_13-43-29.mp4

**Comment by trundler-dev** [comment]
To anyone who missed the conversation, the workaround for this issue is to delete the core/cfg folder in sbox - should fix it!
