### ISSUE TITLE
AnimSceneObject AddChild in SceneWorld screws up bones

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#1547]
**Describe the bug**

While bonemerging models in an AnimSceneObject inside a SceneWorld via AddChild, the child bones will not merge correctly and get moved to 0 0 0.

**To Reproduce**

1. Create a SceneWorld
2. Use an AnimSceneObject to display your model
3. Bonemerge another model to it that contain bones
4. Bones will get screwed over

**Screenshots**

![image](https://user-images.githubusercontent.com/67245359/151600874-f13668ef-4da2-43ac-b09e-12eb6f17d788.png)
![image](https://user-images.githubusercontent.com/67245359/151600890-fd134d6c-d1ac-4109-b076-34be7cdcc585.png)

**Comment by KayaDLX** [comment]
```
public void PreviewClass( PlayerClass pclass )
        {
            var player = Local.Pawn as TFPlayer;
            if ( player == null ) return;

            SelectedClass = pclass;

            PlayerModel?.Delete();
            WeaponModel?.Delete();

            if ( SelectedClass == null ) return;

            //
            // PLAYER MODEL
            //

            var playerModel = pclass.Model;
            if ( string.IsNullOrEmpty( playerModel ) ) return;

            //
            // WEAPON MODEL
            //

            var slot = GetPreviewWeaponSlot();
            var entry = pclass.Weapons.Where( x => x.Slot == slot ).FirstOrDefault();
            if ( entry == null ) return;

            // Check if weapon data exists.
            var primaryWeapon = entry.WeaponData;
            if ( primaryWeapon == null ) return;

            var weaponModel = primaryWeapon.Model;
            if ( string.IsNullOrEmpty( weaponModel ) ) return;

            using ( SceneWorld.SetCurrent( World ) )
            {
                var rotation = Rotation.From( 0, 190, 0 );
                var transform = new Transform( Offset, rotation );

                PlayerModel = new AnimSceneObject( Model.Load( playerModel ), transform );
                WeaponModel = new AnimSceneObject( Model.Load( weaponModel ), PlayerModel.Transform );
                PlayerModel.AddChild( "weapon", WeaponModel );

                int skin = Math.Clamp( (int)player.Team - 2, 0, 1 );
                PlayerModel.SetMaterialGroup( $"{skin}" );
                WeaponModel.SetMaterialGroup( $"{skin}" );
            }
        }
```

**Comment by N-cognito** [comment]
This happens specifically to bones that don't have a matching bone on the parent

**Comment by aylaylay** [comment]
I'll sort it but this part of the API defo needs a rework, it was slapped together to support animated models in UI with not much thought put into it.

**Comment by aylaylay** [comment]
I might have fixed it, it's hard to tell because I don't have a weapon model I can merge that has extra bones.

**Comment by MoonlyDays** [comment]
Seems to be fixed, thanks for the quick response!

**Comment by KayaDLX** [comment]
This worked, thanks a lot 🥇 
![image](https://user-images.githubusercontent.com/67245359/151667186-bbc07ddc-049c-4b89-ab84-a3c8fda02313.png)
