### ISSUE TITLE
Expose post processing volume Hammer entity to C#

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#1548]
**What can't you do?**

I cannot dynamically toggle the post processing of a map when I'm inside some specific menus of my gamemode.
As I'm using a SceneWorld and a background model that is unlit, the map's post processing interferes with my scene and makes it look bad due to the additional bloom of some maps.

**What have you tried?**

All we can do for now is killing the map's post processing entity but we cannot re-enable it after that.

**Comment by robotboy655** [comment]
This was done a while ago.
