### ISSUE TITLE
Convar min/max range

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#1549]
**What it is**

Currently, there's no way to set a min/max for a ConVar.
The range attribute is ignored, and using a custom setter crashes the game(!!). The only way around this is to clamp the value where it's being used, but that feels a bit shit - it'd be better if it was just handled at the source.

Ranges exist in other Source games, like TF2:
![image](https://user-images.githubusercontent.com/12881812/151620804-44af274a-ca8a-47a6-bfef-0790152c4953.png)

**What it should be**

It'd be cool if we could just add a `Range` attribute to the property and have that get used by the ConVar attribute:
```cs
[ClientVar( "fw_viewmodel_fov", Help = "Specifies the client's viewmodel field of view" ), Range( 50, 90 )]
public static float ViewmodelFov { get; set; }
```

**Comment by ogniK5377** [comment]
![image](https://user-images.githubusercontent.com/25727384/151924571-257b73db-257c-4c7a-8278-877941bc4aa3.png)
```cs
	[ClientVar( "fw_viewmodel_fov_range", Help = "Specifies the client's viewmodel field of view" , Min = 50.0f, Max = 90.0f)]
	public static float ViewmodelFov { get; set; }

	[ClientVar( "fw_viewmodel_range_min", Help = "Specifies the client's viewmodel field of view", Min = 50.0f)]
	public static float ViewmodelFovMin { get; set; }

	[ClientVar( "fw_viewmodel_range_max", Help = "Specifies the client's viewmodel field of view", Min = 90.0f )]
	public static float ViewmodelFovMax { get; set; }

	[ClientVar( "fw_viewmodel_norange", Help = "Specifies the client's viewmodel field of view" )]
	public static float ViewmodelFovNoRange { get; set; }
```
Should be in the next update

**Comment by xezno** [comment]
Awesome, thanks ognik! 🎉
