### ISSUE TITLE
Tools broken on Linux

### ISSUE THREAD

**Issue by Kexogg** [Facepunch/sbox-issues#1557]
**Describe the bug**
Game tab in main window is broken and flashes. Resizing window or tab will cause the game to crash. If game is launched without `-tools` option it works as expected. 

Resizing some other tabs (2D/3D view in hammer, etc) in tools will also cause game to crash, but they don't have shifting issues, just flashing

**To Reproduce**

1. Launch game with `-tools` option

**Expected behavior**
Game tab is not shifted/flashing

**Screenshots**
![ksnip_20220131-012133](https://user-images.githubusercontent.com/65514050/151716334-35fa7854-963e-4c41-8460-92fab0ece476.png)

**Additional context**

I am on latest Arch Linux, using proton experimental, AMD Radeon RX 570 (8GB). Fresh S&Box install

Log files
[Log.log](https://github.com/Facepunch/sbox-issues/files/7966857/Log.log)
[sbox_d3d11.log](https://github.com/Facepunch/sbox-issues/files/7966858/sbox_d3d11.log)
[proton log tail.log](https://github.com/Facepunch/sbox-issues/files/7966865/proton.log.tail.log)

**Comment by DrakeFruit** [comment]
I'd say this isn't low priority

**Comment by DevulTj** [comment]
We're not looking to support this
