### ISSUE TITLE
Crash when using PhysicsJoint on player ragdolls

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#1559]
**Describe the bug**
Game crashes after some second if more than one player has the joint below attached to them, from my testing it seems to run completely fine with just one player, even when combined with a bunch of bots. I've tried using a bunch of different things for "OtherBody", including a static entity, unique entities for every player and even the world itself, all with the same result.

Crash log:
```
2022/01/30 22:35:36.484	Interop	Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')	System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Sandbox.HandleIndex.Delete(IntPtr ptr, Int32 handle) in C:\buildbot\work\sbox\sbox\engine\Sandbox.Engine\Interop\Handle.cs:line 80
   at Managed.SourceServer.Exports.Sandboserver_Physcs_f5(IntPtr ptr, Int32 idx) in C:\buildbot\work\sbox\sbox\engine\Sandbox.Game\Interop.Server.cs:line 6746
```
**To Reproduce**

Create this joint on more than one player (bots don't count) and wait, should result in a crash.
Player is using model "models/citizen/citizen.vmdl" and SetupPhysicsFromModel( PhysicsMotionType.Dynamic ).

```cs
var pelvis = PhysicsGroup.GetBody(0);

var pos = OtherBody.Transform.PointToLocal( pelvis.Position );
var rot = OtherBody.Transform.RotationToLocal( pelvis.Rotation );

var joint = PhysicsJoint.Generic
	.From( pelvis )
	.To( OtherBody, pos, rot )
	.WithAngularMotionX( JointMotion.Free )
	.WithAngularMotionY( JointMotion.Locked )
	.WithAngularMotionZ( JointMotion.Locked )
	.Create();
```

**Expected behavior**
Not crash.

**Comment by aylaylay** [comment]
Can't reproduce

**Comment by Leafdroid** [comment]
Seems like the crashing is occuring when the joint is being removed or created, very inconsistent. 
Try using https://github.com/Leafdroid/ragdolls (gamemode leaf.ragdolls).

Spam space a bunch with another player and it should crash within some minute. (Again, does not reproduce with bots)

**Comment by Leafdroid** [comment]
Just tried it in sbox-dev instead of the normal version and this time it threw exceptions with the same error listed above instead of crashing the first 4 times but crashed the game the 5th time.

**Comment by aylaylay** [comment]
Might be fixed now

**Comment by Leafdroid** [comment]
Seems to work!
