### ISSUE TITLE
Ability to get notified of network property changes.

### ISSUE THREAD

**Issue by Erlite** [Facepunch/sbox-issues#156]
**What can't you do?**
Get a callback for when a network property is changed/networked (only on the receiving end). Think UE4's `RepNotify`

**How would you like it to work?**

```cs
// Pass in the name of the method to execute. 
[Net, Notify("OnScoreChanged")]
public int Score { get; private set; }

// Callback is passed the old value of the property. It is executed after the value is set.
public void OnScoreChanged(int previousScore)
{
}
```

**What have you tried?**
This feature does not exist.

**Comment by geferon** [comment]
This would be a very nice feature to have, kinda annoying having to manually do RPCs or such which would be sending an extra message to the client when the client already knows when the variables and such are updated.
