### ISSUE TITLE
Cannot launch gamemode uploaded via game uploader

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1560]
**Describe the bug**
I've uploaded a gamemode using the new Game uploader and can't load into it. Upon connecting it disconnects you with a 403 forbidden error. The local version of the gamemode works fine.

**To Reproduce**

1. Try launching into Speed Dial from the main menu
2. See error

**Expected behavior**
Just being able to launch into the gamemode like normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/12602100/151667507-04e2b093-9f47-46a0-8b19-27107a756c9a.png)
![image](https://user-images.githubusercontent.com/12602100/151667519-6b04c0cb-1151-4722-8fb7-574306464a4d.png)

**Additional context**
I've confirmed this with a few other people as well, so it's not a problem on my side.

**Comment by garrynewman** [comment]
I believe this is fixed now
