### ISSUE TITLE
Add color picker for Color properties back to the entity inspector

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1564]
**What can't you do?**
Change a color property of an entity in the entity inspector

**How would you like it to work?**
Similar to other types like vec3 etc, just have a custom ui inspector element come up

**What have you tried?**
Clicking the color property in the inspector in different locations

**Additional context**
The old inspector had a color picker for Color types, the "new" editor inspector lacks this specific element
![sbox-dev_n3AQPe3LVK](https://user-images.githubusercontent.com/12602100/151724890-c819f41b-96fb-430b-b29b-c9677a987ef5.png)

**Comment by Matt9440** [comment]
Sorry to be that guy, but bump
