### ISSUE TITLE
Modifying properties of existing PhysicsJoints

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#1568]
**What can't you do?**
You can't modify an existing PhysicsJoint.

**How would you like it to work?**
Methods to modify the joint post-creation such as PhysicsJoint.SetFriction(), PhysicsJoint.LockAngularMotion() etc.

**What have you tried?**
In order to change the friction of the joint I create a duplicate of the joint with the same settings along with the new friction and remove the old one. This works well at first but causes the ragdoll to have increasingly large spasms the more I do it.

**Comment by aylaylay** [comment]
this already exists, the builder returns the joint with all the functions you need to change it after the fact

**Comment by Leafdroid** [comment]
Oh oops, missed those. There doesn't seem to be one for friction though?

**Comment by aylaylay** [comment]
which joint

**Comment by Leafdroid** [comment]
Just PhysicsJoint itself, it has no property for friction

**Comment by Leafdroid** [comment]
im using spherical joints

**Comment by aylaylay** [comment]
done
