### ISSUE TITLE
Impossible to compile/access models and materials if they are saved in a folder containing "obj" in its name.

### ISSUE THREAD

**Issue by leeroycas** [Facepunch/sbox-issues#1571]
**Describe the bug**

It is impossible to compile/open an asset (.vmat or .vmdl) if it is saved in a folder containing "obj" in its name. (ex : models/**obj**ects/testmodel.vmdl / materials/models/**obj**ects/testmaterial.vmat)

**To Reproduce**

1. Open **ModelDoc** or **Material Editor**.
2. Create a new Model/Material and save it in a folder containing the 3 letters **OBJ** in a row. (ex : "models/objects/test.vmdl")
3. Notice that it is not possible to compile the model (or material) after pressing the compile button.

**Expected behavior**

Being able to compile i guess!

**Additional context**

I have encountered this problem a few weeks ago. I used to have a lot of assets already compiled in "models/objects" and "materials/models/objects" and they all suddenly became impossible to open in modeldoc/material editor aswell as not being able to be found in the asset browser. They were still appearing in my map despite the fact that the model path in the prop_static showed no existing model. As for materials it was simply saying "You need to save "_whatevertexture.vmat' to a recognized content path_"

During my testing to try and find a solution i found out that the 3 letters "obj" set in a row are creating this problem. saving them in a folder simply called "OBJ" would create this error meanwhile, saving them in a folder called "bject" would work fine.

_Sorry if it is confusing i'm not native english :D_

**Comment by aylaylay** [comment]
this should be fixed now

**Comment by aylaylay** [comment]
Keep in mind that an "obj" dir is still ignored but something like "objects" isn't
