### ISSUE TITLE
World Mapping Reset on Blend Materials

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1572]
**Describe the bug**
It looks like world mapping got reset on all blend materials, including my own custom ones. Not sure how this happened.

**Expected behavior**
World mapping needs to be re-added to all blend materials.
![image](https://user-images.githubusercontent.com/39461072/152080412-fe7541cc-c6b5-48c1-a32a-910ecf5015ab.png)

**Comment by ogniK5377** [comment]
There's no way to recover your previous values after you have saved/changed them. You'll have to just set your values again

**Comment by gvarados1** [comment]
I think you misunderstood the issue. I wasn't asking for my values to magically be restored. I was asking for all of the default materials to be fixed. They were all broken.

They've been slowly getting fixed (whenever someone at FP used them?) so I think it's fine now :)

**Comment by gvarados1** [comment]
Actually there are still a ton of broken materials. Here are a couple:

materials/generic/wall_brick_blend_old_paint.vmat
materials/generic/wall_brick_blend_new_old.vmat
materials/generic/wall_brick_blend_old_moss.vmat
materials/generic/wall_brick_blend_older_dirt.vmat
materials/nature/floor_riverbed_dirt_blend_a.vmat
materials/generic/concrete_glossy_used_blend.vmat
