### ISSUE TITLE
Addons List is broken in the Hammer Asset Browser

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1573]
**Describe the bug**
The addons list has a ton of extra space below the addons, making it so I can't change my addon selection without moving the window to the bottom of my display.

![image](https://user-images.githubusercontent.com/39461072/152080709-98d976c8-10a3-4c69-941f-bd77eed62d62.png)

**To Reproduce**
1. Open Hammer
2. Go to Asset Browser
3. Click Addons

**Expected behavior**
Addons list shouldn't have all this extra space. Also, Addons/Tags lists still do not save on floating windows. #1306

**Comment by ogniK5377** [comment]
Should be fixed next update

**Comment by gvarados1** [comment]
Perfect! Thank you!
