### ISSUE TITLE
Better Map Selection For Map-Restricted Games

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1576]
Every map should be shown under every category when the maps list is so small for map-restricted games.
This current system is very confusing. I'm not going to sort maps when I only see one in the list. I'll just assume there's only one map.

https://user-images.githubusercontent.com/39461072/152266081-b2f3b5d7-cfd4-4fa1-be04-a6a2f152f828.mp4

**Comment by robotboy655** [comment]
This was fixed with the menu rework as far as I can tell.
