### ISSUE TITLE
Animgraph - Enable zoom while the node out arrow is selected. 

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1578]
**What can't you do?**

I'm currently managing a fairly large graph, when I have to connect something from the top to the bottom it's annoying that you can't zoom in or have the "camera" following your cursor while you're selecting the arrow.

https://user-images.githubusercontent.com/40291120/152398717-e6c8da58-81a3-4f01-9ead-bc74c4579be3.mp4

**Comment by aylaylay** [comment]
Should be able to zoom now
