### ISSUE TITLE
Modeldoc - Animevent doesn't recognize sounds from our addons anymore

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1579]
**Describe the bug**

Since the change to the addons, when you use AE_CL_PLAYSOUND and then search for custom sounds they no longer appear, we only have the ones from the "core addons". 

**To Reproduce**

Use AE_CL_PLAYSOUND.
Try to browse.

**Comment by DeltaDesigns** [comment]
bump, same problem

**Comment by byplt** [comment]
bump

**Comment by DeltaDesigns** [comment]
It's been working fine for me recently, I think you have to be in your game for the sounds to appear

**Comment by Grodbert** [comment]
> It's been working fine for me recently, I think you have to be in your game for the sounds to appear

It's a workaround that's been known, but being in that gamemode to be able to select the sound event is not the intended behavior, it also doesn't play in ModelDoc if you preview the animation
