### ISSUE TITLE
Hammer 2D Box Selection is in Screen Space, should be World Space

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1586]
**Describe the bug**
When I move my 2d view, the selection box stays relative to the view instead of staying in the world where I originally selected. This doesn't make any sense and makes the 2d view completely useless for large-scale precision selections, which is one of it's primary uses.

**To Reproduce**
In this video, I try selecting a group of pillars. Some are off-screen, so I zoom out to get it, but I end up selecting the entire map.
I then compare this to source 1, where selection is in world space as it should be.

https://user-images.githubusercontent.com/39461072/152674374-f16637c4-4164-49f8-85e0-80c86177e62a.mp4

**Expected behavior**
Box Selection should be world space, not screen space.

**Comment by aylaylay** [comment]
This may need to be an option, I think screenspace selection is still going to be what some people want

**Comment by gvarados1** [comment]
An option would work :)
I've been thinking about this, and I just can't think of a use case for screenspace selection. I'd love to know if anyone has one.

**Comment by aylaylay** [comment]
<img width="323" alt="sbox_oC6MhRldDQ" src="https://user-images.githubusercontent.com/1667289/153138897-0f4f7f05-edfd-4bd9-80a9-cbe7aca3450c.png">

**Comment by gvarados1** [comment]
Perfect! Thanks!

**Comment by aylaylay** [comment]
Done

**Comment by gvarados1** [comment]
Perfect! Thanks!
