### ISSUE TITLE
Can't Pan Hammer 2D View While Selecting

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1587]
**Describe the bug**
We can't pan the hammer 2d view while selecting. We can only zoom in/out.

**To Reproduce**

1. Drag out a selection in a hammer 2d view, don't release mouse button
2. Try to pan the view
3. See error

**Expected behavior**
We should be able to pan the 2d views while selecting.

**Comment by aylaylay** [comment]
It doesn't make sense to have two drag operations running at once so I wont be adding this.

**Comment by aylaylay** [comment]
That being said, it does make a little more sense with world space box select so I might revisit it.

**Comment by gvarados1** [comment]
I never use it personally. Just found out it was possible in source1 the other day.

**Comment by gvarados1** [comment]
After doing some heavy 2d view work recently, this is definitely needed.
