### ISSUE TITLE
Show Length/Width of 2D Box Selections in Hammer

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1588]
**What can't you do?**
We can't see the size of our 2d box selections in hammer. This is very useful for quickly determining scale & dimensions.

**How would you like it to work?**
When we drag out a box select, we should see the size of the selection.

Here's how it looks currently, no dimensions shown:
![image](https://user-images.githubusercontent.com/39461072/152674660-6f0f6ad9-4160-4781-aa86-32c43fdd652e.png)

Here's how it should look. I can see my selection is 184x188 units.
![image](https://user-images.githubusercontent.com/39461072/152674756-3096e40c-133e-4fcc-83f6-8b24f8ac7d7f.png)

**What have you tried?**
Currently we have to create a dummy mesh to see dimensions.

**Comment by aylaylay** [comment]
I've added this, it's screenspace size though because to show worldspace I need to do #1586

**Comment by gvarados1** [comment]
This doesn't work on the front/side views. Only the top.

**Comment by aylaylay** [comment]
Should be fixed

**Comment by gvarados1** [comment]
This doesn't work anymore. Must have broke in a recent update.
I don't have permission to re-open this issue. Probably because I didn't close it.
