### ISSUE TITLE
S&box doesn't unload assemblies after hotloading

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#159]
**Describe the bug**
S&box does not unload older assemblies after hotloading or disconnecting

**To Reproduce**
1. Hotload your gamemode a few times or disconnect
2. Attach dnSpy debugger
3. Debug -> Windows -> Modules
4. Check loaded assemblies, you will see that all are still fully loaded

**Expected behavior**
I guess older assemblies should unload since they are not used anymore. I don't know if this is intentional or not, so I decided to report this.

**Screenshots**
Here is a list of assemblies loaded from my test gamemode:
![image](https://user-images.githubusercontent.com/1809172/118186992-0e44ce00-b447-11eb-85b6-b1290206a789.png)

I have been developing my gamemode for 2 hours and there are now 70 assemblies for the same gamemode loaded

![image](https://user-images.githubusercontent.com/1809172/118187367-84493500-b447-11eb-812b-226afed95685.png)
^ I added the Lobby namespace in 251, this shows that the assemblies are different and not the same ones

**Comment by Erlite** [comment]
Can repro, had exceptions from a previous gamemode I played when I started another.
