### ISSUE TITLE
[AV detection] Bitdefender says that tools/InteropGen.exe file is infected with Trojan

### ISSUE THREAD

**Issue by GuardNexusGN** [Facepunch/sbox-issues#1595]
Pressed update button in Steam, got an AV notification.

Bitdedender Total Security does not allow to update s&box, says that file tools/InteropGen.exe is infected with Trojan. 
It can be false-positive, but, anyway, desided to move file in quarantine and report problem here.

Screenshots from Bitdefender notifications tab:

![image](https://user-images.githubusercontent.com/72446184/152795400-0ddea6fa-888b-4ada-943a-264eb203eb4f.png)

![image](https://user-images.githubusercontent.com/72446184/152796905-31b7d0a3-9bc0-467c-8c4f-0845f5a84191.png)

UPD: VirusTotal showed that 2 more avs flagged the file as malicious: https://www.virustotal.com/gui/file/146f99bd6e8083bfbffd860ab3eef4df308016c503a8d391b4ea48cce4bda7ad/detection

**Comment by GuardNexusGN** [comment]
VirusTotal showed that 2 more avs flagged the file as malicious: https://www.virustotal.com/gui/file/146f99bd6e8083bfbffd860ab3eef4df308016c503a8d391b4ea48cce4bda7ad/detection

**Comment by xezno** [comment]
Duplicate of #1439 and #626.

Report any false positives to your antivirus vendor [here](https://www.bitdefender.com/consumer/support/answer/29358/).
