### ISSUE TITLE
Cannot use nullables with [Net] 

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#160]
**Describe the bug**
Using nullable with [Net] results in compilation errors (applies to structs, primitives and enums)

**To Reproduce**
```cs
public enum Team
{
   ...
}

[Net]
public Team? Team { get; internal set; }
```

**Expected behavior**
Should not cause compilation errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1809172/118193498-7a77ff80-b450-11eb-8161-2f4f7a6c2c29.png)

**Comment by Jac0xb** [comment]
I'm pretty sure you can't use any networked type with Nullable.

**Comment by Trojaner** [comment]
Yes, I will update the title
