### ISSUE TITLE
using phys_hinge in tileset crashes s&box

### ISSUE THREAD

**Issue by TheBoxTrot** [Facepunch/sbox-issues#1600]
**Describe the bug**
if you have a phys_hinge in a tileset it will crash s&box when loading a map with that tileset

**To Reproduce**

1. create a tileset
2. create a phys_hinge
3. attach it to a prop_dynamic and prop_physics in the tile
4. load a map with that tile in the level

**Expected behavior**
the phys object hangs off the dynamic prop

**Screenshots**

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by aylaylay** [comment]
Please send a basic map showing this

**Comment by aylaylay** [comment]
works fine here

**Comment by TheBoxTrot** [comment]
its working now but now if there two of the same tile the prop physics hooks onto both the hinges at once

**Comment by aylaylay** [comment]
so does it crash or not? can you give me a map that crashes otherwise I can't fix it

**Comment by TheBoxTrot** [comment]
no crashing is no longer a issue
