### ISSUE TITLE
Shaders with S_ALPHA_TEST failing to compile

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#1607]
**Describe the bug**
Seems like any shader with `Feature( F_ALPHA_TEST, 0..1, "Rendering" );` and `StaticCombo( S_ALPHA_TEST, F_ALPHA_TEST, Sys( ALL ) );` will fail to compile with the standard includes.
It spits out the error  `error X3003: redefinition of 'g_flAlphaTestReference'`.
This happens when I try to compile the base foliage.vfx shader, as well as any custom shaders using alpha testing.

**To Reproduce**
Compile foliage.vfx shader, error is produced

**Expected behavior**
No error, alpha testing works as expected

**Comment by ogniK5377** [comment]
Can you provide the shader you're using?

**Comment by ogniK5377** [comment]
Should be fixed up next update
