### ISSUE TITLE
Hammer FGD "angle" type has misleading Field Labels

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#161]
Problem:
The FGD "angle" type works via Pitch Yaw and Roll fields, but displays it as "X Y Z", suggesting a vector representation.

Suggestion:
Make it Display as "Pitch Yaw Roll" instead.

**Comment by aylaylay** [comment]
Would P, Y, R be fine? It would mess up the alignment in the UI otherwise

**Comment by aylaylay** [comment]
Angles now use P,Y,R
