### ISSUE TITLE
func_monitor does not render the point_camera view

### ISSUE THREAD

**Issue by DepHedge** [Facepunch/sbox-issues#1610]
**Describe the bug**
The func_monitor entity/brush doesn't render the point_camera

**To Reproduce**
1. Place a func_monitor(brush or entity) 
2. Place a point_camera and name it `my_cool_camera`
3. Set the Camera Name in the func_monitor to be `my_cool_camera`

**Expected behavior**
Using either the entity or brush should render what the camera can see onto it.

**Screenshots**
![image](https://user-images.githubusercontent.com/25727384/153550808-a398b0ca-a200-46cc-b2f3-e34792f37bf2.png)

**Additional context**
Attached is an example vmap & vmf of the issue for reproduction.
[monitors.zip](https://github.com/Facepunch/sbox-issues/files/8046775/monitors.zip)

~~i grabbed a func_monitor and point camera and i selected it in the func monitor but it doesnt work in sbox~~

**Comment by ogniK5377** [comment]
I've gone ahead and completely rewrote this issue. For next time please stick to the issue format & provide a better explanation on what's going on

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
bump

**Comment by robotboy655** [comment]
It does work, it just needs a special material to do so. I have included relevant info in func_monitor's description, as well as added a sample material that works with it: `dev/func_monitor`.

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
> 

Got it to work! Ty

Any chance to add support for camera switching per monitor?
E.g. right now you have to make multiple monitors to display multiple cameras, but a button output to change a monitor to a different camera would be nice to save performance and space.

**Comment by robotboy655** [comment]
Done.

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
> Done.

Could be doing this wrong, but it does not seem to be working.
![image](https://user-images.githubusercontent.com/93285193/165138142-86331b19-4cea-4387-a635-c458bb0f828d.png)

I set a button output to target my monitor with a paremeter override of the cameras entity name.

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
> 

Works now 👌
