### ISSUE TITLE
Workshop Asset Packs

### ISSUE THREAD

**Issue by Noxmore** [Facepunch/sbox-issues#1613]
**How would you like it to work?**

I would like to have another addon type called something like "Asset Pack" that only contains models, materials, sounds, etc.

People can then download these Asset Packs and use them in their addons, probably giving credit, or marking the Asset Pack as a dependency in the uploaded addon.

Also to make the user's download times quicker, it could only download assets that are used in the addon.

**Comment by googleooer** [comment]
“Content” addons are already a thing.
