### ISSUE TITLE
sv_cheats bypass with -tools

### ISSUE THREAD

**Issue by JustPlayerDE** [Facepunch/sbox-issues#1616]
**Describe the bug**

You can bypass `sv_cheats 0` if you opened the dev tools

for example by changing the color of the hidden to make it visible to you

**To Reproduce**

1. Open dev tools (e.g. `-tools` as start parameter in steam)
2. Change stuff using the dev tools on any gamemode or server with `sv_cheats 0`
3. Profit?

**Expected behavior**

if sv_cheats is set to 0 it should prevent that from happening

maybe kicking people from servers with `sv_cheats 0` when dev tools enabled? (or don't let them join?)

**Screenshots**

[example video of enabling full-bright](https://files.justplayer.de/justin/006ca54c57e82330f3db4734ae4fe3817fab21fb.mp4)
[example video of making the hidden visible](https://files.justplayer.de/justin/72b81256e914f148dc3328d3a8333586ae6ba296.mp4)

**Comment by SupinePandora43** [comment]
Server setting `sv_devtools` or `sv_allowdevtools` or `sv_devtools_allow`/`sv_devtools_enable` will be better than simply kicking everyone with devtools on `sv_cheats 0` server.
What `sv_cheats 1` is used for by the way? 🥴

**Comment by JustPlayerDE** [comment]
It seems fixed now so i close it ¯\_(ツ)_/¯
