### ISSUE TITLE
Multiplayer Voice Volume Setting

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1630]
**What can't you do?**
We need a setting to adjust the volume of other players in-game or turn them off.

**How would you like it to work?**
Slider in the menu

**Additional context**
I've tried a couple console commands but I don't think any of them do this.

**Comment by aylaylay** [comment]
should be able to fuck w it now in settings menu or snd_voipvolume

**Comment by gvarados1** [comment]
lovely
