### ISSUE TITLE
Edit Particles object's color through method

### ISSUE THREAD

**Issue by AndyResu** [Facepunch/sbox-issues#1631]
**What can't you do?**
We cannot edit a `Particles` object's color through a C# method, however, we are able to edit a particle's color in the Particle Editor.
This would allow devs to recolor particles so that they may re-use a single particle instead of using many singly-colored particles for the same purpose.

An example in the Particle Editor:
![image](https://user-images.githubusercontent.com/8263217/154827811-ef1e2dd1-9949-4318-acc5-099c1b3038e4.png)
The Particles class of objects does not have a method for editing this. 

**How would you like it to work?**
Here is some pseudo-code for Particles.cs:
![image](https://user-images.githubusercontent.com/8263217/154828125-b8a0e57b-83f7-415f-93df-a85dfa5e1f24.png)
Please note that m_ConstantColor will not appear in the .vpcf file if the default, white, value is used.

**What have you tried?**
I considered modifying my code to fetch, modify, & save the .vpcf before I create a particle using:
`Particles.Create("particles/myParticle.vpcf");`
However, then whenever a new color is chosen, I would have to read/write to the disk again and this would smother performance.

If that does not work, I will need to make a series of singly-colored particles and use those instead.

**Additional context**
Thank you!

**Comment by ogniK5377** [comment]
Is there any reason you cannot use control points here? You can modify those from C# and mess with just about any attribute then

**Comment by AndyResu** [comment]
I am able to use a particle's .SetEntity() method to set the control points (like for a rope), however, I am unsure of how to to use control points to modify other attributes, like color. Intellisense does not detect a ControlPoint object for example.

**Comment by DoctorGurke** [comment]
This can be done entirely through control points, as long as the particle is made to support it.

**Comment by AndyResu** [comment]
I will investigate it and close this issue. Thank you ogniK and DoctorGurke.
If you have any code examples, I would really appreciate it.
