### ISSUE TITLE
Be able to find convars by their flags using the `find` console command

### ISSUE THREAD

**Issue by megabro** [Facepunch/sbox-issues#1632]
**What can't you do?**
Right now I can only search for convars by strings contained in their `name` or `help text` using the `find` command, but I'd like for the command to also search by their `flags`. For example I'd like to be able to search for convars that have the `managed` or `replicated` flags.

Notice the "no results" output when I search for `managed`:
![image](https://user-images.githubusercontent.com/35005210/154851882-75007575-f72b-4d7b-bd83-6eda9c3eba5a.png)

**How would you like it to work?**
If I search `managed` for example, I'd like the command to output all convars using said flag.

**What have you tried?**
To be able to find gamemode specific managed convars, I have to rely on naming conventions, like having a shortened name and underscore before the convar and searching for that, but that is limited.

**Comment by saul** [comment]
You can at least search for replicated cvars with:

```
findflags replicated
```

It doesn't work for `managed` though.

**Comment by megabro** [comment]
Didn't know about `findflags`, somehow slipped under my radar lol.
Yeah, in that case adding `managed` to the list of flags would suffice.

**Comment by megabro** [comment]
Works as expected now!
