### ISSUE TITLE
Can't connect to API on Linux

### ISSUE THREAD

**Issue by REALalphas** [Facepunch/sbox-issues#1633]
**Describe the bug**
No games and statistics, but steam works

**To Reproduce**

1. Run game
2. Press F1
3. See error
```
Exception when posting to API
There was a problem retrieving account information
FakePacketLag is now 0.000000
Api Error: "https://apix.facepunch.com/sandbox-asset?id=facepunch.sandbox"
No package found for facepunch.sandbox
Api Error: "https://apix.facepunch.com/sandbox-asset?id=eagleone.speed_dial"
No package found for eagleone.speed_dial
Api Error: "https://apix.facepunch.com/sandbox-asset?id=swb.demo"
No package found for swb.demo
Api Error: "https://apix.facepunch.com/sandbox-asset?id=piano.gr__piano"
No package found for piano.gr__piano
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The SSL connection could not be established, see inner exception.)
The SSL connection could not be established, see inner exception.
Api Error: "https://apix.facepunch.com/sandbox-asset-list?type=gamemode&order=newest&userid=76561199072617332"
Api Error: "https://apix.facepunch.com/sandbox-asset-categories"
Api Error: "https://apix.facepunch.com/sandbox-asset-categories"
Api Error: "https://apix.facepunch.com/sandbox-asset-list?type=gamemode&order=newest&userid=76561199072617332&tags="
```
```
ping apix.facepunch.com 
PING apix.facepunch.com (104.18.4.180) 56(84) bytes of data.
64 bytes from 104.18.4.180 (104.18.4.180): icmp_seq=1 ttl=57 time=6.82 ms
64 bytes from 104.18.4.180 (104.18.4.180): icmp_seq=2 ttl=57 time=8.20 ms
64 bytes from 104.18.4.180 (104.18.4.180): icmp_seq=3 ttl=57 time=7.98 ms
64 bytes from 104.18.4.180 (104.18.4.180): icmp_seq=4 ttl=57 time=6.51 ms
^X64 bytes from 104.18.4.180 (104.18.4.180): icmp_seq=5 ttl=57 time=6.90 ms
^C
--- apix.facepunch.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 6.508/7.281/8.197/0.676 ms

╭─ ~ ▓▒░                                         ░▒▓ ✔  took 5s  at 20:54:46 
╰─ 
```

**Expected behavior**
Connection to APIs

**Screenshots**
![Screenshot from 2022-02-20 20-47-15](https://user-images.githubusercontent.com/26285012/154856644-9699566d-b544-4538-8aee-94ba92d9cb77.png)
![Screenshot from 2022-02-20 20-47-37](https://user-images.githubusercontent.com/26285012/154856645-cee1f63f-2ed5-4275-bb1f-cc7cf2ced760.png)
![Screenshot from 2022-02-20 20-48-47](https://user-images.githubusercontent.com/26285012/154856647-f1883b96-61bd-46cb-84d6-af3173901d3e.png)

**Additional context**
Before today's update, I always getting problems with rendering. I don't know it is Nvidia proprietary + amdgpu drivers or what, but now I don't have Nvidia drivers and rendering is ok.

OS: Arch Linux x86_64 
Host: 82B1 Lenovo Legion 5 15ARH05H 
Kernel: 5.16.10-zen1-1-zen 
Resolution: 1920x1080 
DE: GNOME 41.4 
WM: Mutter 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz 
Chipset: AMD K17.6 FCH, AMD K17.6 IMC
GPU: AMD ATI 05:00.0 Renoir 
GPU: NVIDIA GeForce RTX 2060 Mobile 
Memory: 8Gb x2 Samsung M471A1K43DB1-CWE

**Comment by REALalphas** [comment]
Proton: Proton 7.0-1

**Comment by handsomematt** [comment]
#1526 dupe
