### ISSUE TITLE
Gib Models Aren't Tagged as "Gibs"

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1637]
**Describe the bug**
There are a lot of gib models that aren't tagged as "Gibs"
Just untag Gibs and search gib to find them.

![image](https://user-images.githubusercontent.com/39461072/155239600-216d2305-c43e-4209-8f3c-4f70a483d46a.png)

It would be nice if models were auto-tagged as "Gibs" if they have "_gib" in the filename

**Comment by bakscratch** [comment]
Should be up to date.

**Comment by gvarados1** [comment]
There are still a few :) 
![image](https://user-images.githubusercontent.com/39461072/156274490-0abf530c-0c21-4fff-bd6d-630a7ccb1f2d.png)
