### ISSUE TITLE
Background images are still repeated even with `background-repeat: no-repeat;`

### ISSUE THREAD

**Issue by MoonlyDays** [Facepunch/sbox-issues#1639]
**Describe the bug**
When creating a panel, and giving it a `background-image` and `background-repeat: no-repeat` the image should not be repeated. Right now, however, it is being repeated but only on the right side.

**To Reproduce**

1. Make a `<div>` panel
2. Stylize it like this:
```css
height: 100px;
width: 250px;
background-image: url(/path/to/image.png);
background-size: contain;
background-repeat: no-repeat;
background-position: center;
background-color: red;
```
3. Observe the bug

**Expected behavior**
The background-image should not be repeated.

**Screenshots**
![image](https://user-images.githubusercontent.com/32462579/155317712-7564bb76-f2ac-4857-ba66-c4242e570c35.png)

**Additional context**

**Comment by handsomematt** [comment]
Should be fixed now.
