### ISSUE TITLE
Whitelist IEquatable<T>, System.Reflection.DefaultMemberAttribute (for custom collections)

### ISSUE THREAD

**Issue by Erlite** [Facepunch/sbox-issues#164]
**What can't you do?**
[This class](https://github.com/Erlite/sbox-net-types/blob/master/Collections/NetworkedList.cs)

**How would you like it to work?**
`System.Private.CoreLib/System.IEquatable<T>` is used to override how Equals is used for objects.
`System.Reflection.DefaultMemberAttribute` is emitted by the compiler on any class that implements an indexer (like collections). 

These two aren't going to cause any issue, and are super important if we want to make our own collections.

**Comment by kurozael** [comment]
Done :)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Erlite** [comment]
Fixed
