### ISSUE TITLE
TestUI Colorpicker fails to render correctly 

### ISSUE THREAD

**Issue by Oppossome** [Facepunch/sbox-issues#1643]
**Describe the bug**
It appears to be an issue with mix-blend-mode as it's the multiplicative rendering layer that's showing up. The issue also presents itself in my personal color picker.

**To Reproduce**

https://user-images.githubusercontent.com/15877760/155768607-ed3bed43-1a7c-47a7-9ffa-1aa09c70043b.mp4

**Expected behavior**
For the multiplicative layer to properly apply itself to the layer below it.

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/158920274-89ead37a-bafb-4cb0-9378-51cfb071c087.png)

Should be working as expected again.
