### ISSUE TITLE
Main menu charachter t-pose bug

### ISSUE THREAD

**Issue by PalkerCode** [Facepunch/sbox-issues#1644]
**Describe the bug**
If you hover over the exit button, the character will stand in a t-pose

**To Reproduce**
Hover over the exit button

**Expected behavior**

**Screenshots**
![das](https://user-images.githubusercontent.com/54351305/155833966-ccc42ac1-7641-4c8f-a785-113c96cf22ed.png)

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by MaxLebled** [comment]
Thanks for the report! This is fixed now.
