### ISSUE TITLE
Entites that return false in the CleanUpFilter still get respawned.

### ISSUE THREAD

**Issue by kolexxx** [Facepunch/sbox-issues#1646]
**Describe the bug**
Entites that return false in the CleanUpFilter still get respawned.

**To Reproduce**

Download Minimal Example
[minimalexample.zip](https://github.com/Facepunch/sbox-issues/files/8147545/minimalexample.zip)

**Expected behavior**

Summary:
Called when deleting and then creating entities to decide which ones to keep
and which ones to delete.
Return false to preserve entity (don't delete and do not respawn). Entity argument
will be null when spawning entities.

**Comment by robotboy655** [comment]
You are hitting an edge case that is kinda unavoidable. When creating entities, the system can only work with classnames, not entity instances. It cannot possibly know that you are going to conditionally not remove certain map entities before respawning all of them.

You should only work with classnames in the filter for map entities. The Entity object is there to easily not delete entities spawned through code basically.

**Comment by kolexxx** [comment]
I'm using the default cleanup filter and it's still not getting deleted. I'm sorry if I didn't get what you are saying.

**Comment by robotboy655** [comment]
Yes because your entity code does `Parent = Game.Current;` which is effectively same as modifying the filter function to not remove a specific entity instance.

I will look into removing that part of the default filter, and maybe keeping track of non deleted map entities internally to then not respawn them.

**Comment by robotboy655** [comment]
Ok I applied both changes now to the game. Your example should now work as you expect it to.
