### ISSUE TITLE
net_fakelag is not protected by sv_cheats

### ISSUE THREAD

**Issue by Meowcat285** [Facepunch/sbox-issues#1647]
**Describe the bug**
The command `net_fakelag` is not protected by `sv_cheats` as in previous source games. Any client can run the command at any time regardless of server settings

**To Reproduce**

1. Join a game as a client
2. Open console and run `net_fakelag 100`

**Expected behavior**
The game should not allow the client to run `net_fakelag` with `sv_cheats` not set to `1`

**Comment by handsomematt** [comment]
fake lag is a serverside thing, not sure why it should be protected by sv_cheats

**Comment by Meowcat285** [comment]
> fake lag is a serverside thing, not sure why it should be protected by sv_cheats

It is not, when you run it as a client, it is applied to the client who runs it
