### ISSUE TITLE
World Mapping attribute doesn't exist on Blendable shader

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#1649]
**Describe the bug**
In the Material Editor, if you are using the Blendable shader there is no option to set World Mapping.

**To Reproduce**

1. Create a new material
2. Set the shader to 'Blendable'
3. Go to the Attributes tab
4. There is no World Mapping option.

**Expected behavior**
The world mapping panel should exist with Blendable selected.

**Screenshots**
Material with the Blendable shader selected:
![image](https://user-images.githubusercontent.com/65134886/155873600-f38ac435-caba-470c-8ed8-78b5aaf17e42.png)

Material with the Base shader selected: 
![image](https://user-images.githubusercontent.com/65134886/155873616-9b191e2c-d392-45d2-baf1-fa6e975c6b0d.png)

**Comment by gvarados1** [comment]
hammer has been so scuffed these past few months

**Comment by DoctorGurke** [comment]
this is a material editor thing though 😕

**Comment by gvarados1** [comment]
everything relating to hammer / mapping has been so scuffed these past few months

**Comment by xezno** [comment]
dev preview

**Comment by GunnarKafel** [comment]
Works perfectly, thanks!
