### ISSUE TITLE
IEnumerable & BaseNetworkable 

### ISSUE THREAD

**Issue by Sampleeeee** [Facepunch/sbox-issues#1654]
**Describe the bug**
When implementing `IEnumerable<T>` on a class that inherits from `BaseNetworkable`, it fails to network the network variables.

**To Reproduce**
[ienumerabletest.zip](https://github.com/Facepunch/sbox-issues/files/8180627/ienumerabletest.zip)
If you remove the `[Net]` from `[Net] protected IList<int> _values (...)` the error will go away.

**Expected behavior**
It should not error

**Comment by handsomematt** [comment]
#1448

**Comment by Sampleeeee** [comment]
Just tested this again, still seems to not be fixed, still using the same addon linked in the op.

**Comment by handsomematt** [comment]
Was closed as a duplicate issue

**Comment by Sampleeeee** [comment]
oh sorry i thought that meant it was fixed my b
