### ISSUE TITLE
ThirdPerson model of the player doesn't get rendered on Respawn()

### ISSUE THREAD

**Issue by kolexxx** [Facepunch/sbox-issues#1655]
**Describe the bug**
ThirdPerson model of the player doesn't get rendered on Respawn().

**To Reproduce**

1. Kill the player
2. Respawn

**Screenshots**
![Desktop Screenshot 2022 03 04 - 12 54 58 90](https://user-images.githubusercontent.com/48793595/156761281-efc6576b-7198-44e4-862f-7501f386a104.png)

![Desktop Screenshot 2022 03 04 - 12 55 10 27](https://user-images.githubusercontent.com/48793595/156761287-1d9ffa50-6f93-491d-9783-0139ddff16dc.png)

**Additional context**
Switching to ThirdPerson mode fixes this problem. Also if we set the camera to `ThirdPersonCamera` on `Respawn()` instead of `FirstPersonCamera`, the bug doesn't happen.

**Comment by aylaylay** [comment]
should be fixed
