### ISSUE TITLE
"Sequence contains no elements" error when toggling devcam

### ISSUE THREAD

**Issue by Retr0-01** [Facepunch/sbox-issues#1659]
**Describe the bug**
Activating/deactivating the devcam with custom ``MaterialPostProcess`` shaders added will create a "Sequence contains no elements" error and prevent the devcam from being toggled off

**To Reproduce**

1. Ensure you have a custom ``MaterialPostProcess`` effect enabled
2. Add the effect using ``PostProcess.Add()``
3. Toggle the devcam

**Expected behavior**
Devcam should be toggled on/off normally without any issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/61121754/156881191-5432a02a-da7b-4896-a00c-2245a9752508.png)
*First three errors when toggling the devcam on*<br>
![image](https://user-images.githubusercontent.com/61121754/156881201-5dfb6c63-5504-48b9-8bdd-a6aeaa5a0ca6.png)
*Errors each frame while trying to toggle the devcam off - Camera is frozen in place*<br>
![image](https://user-images.githubusercontent.com/61121754/156881244-dc419d9a-22a6-4e2e-b849-309ea88a16af.png)
*Stack trace*<br>
![devenv_T0Z7aSzAXX](https://user-images.githubusercontent.com/61121754/156881260-1fa75ba1-89c2-4d52-895e-a222a0a5aca6.png)
*Highlighted code that causes the errors*

**Additional context**
Note: not adding any custom post processing effects while not cause this error. This happens with ``MaterialPostProcess`` effects.

**Comment by handsomematt** [comment]
Should be good now.

**Comment by Retr0-01** [comment]
Yep, issue has been resolved. Thanks Matt!
