### ISSUE TITLE
Point_ViewControl

### ISSUE THREAD

**Issue by popcan12** [Facepunch/sbox-issues#1661]
**What can't you do?**
Use the entity "point_viewcontrol" to control a player's viewpoint on a map.

**How would you like it to work?**
https://developer.valvesoftware.com/wiki/Point_viewcontrol
I'd want to be able to set up the entity so it can point the player's view
into a different spot, similar to the wakeup sequence in portal where it can also
freeze the player and then after another input the point_viewcontrol can be disabled.

**What have you tried?**
Point_camera but it doesn't have any spawnflags or any functionality like it.

**Additional context**
Would be cool for abstract maps like in Portal 2 (Kazerlight for example).

**Comment by DoctorGurke** [comment]
This doesn't seem viable for maps themselves, this should be done by the gamemode. The gamemode could of course have a custom entity for this, but for generic purpose this doesn't seem right

**Comment by handsomematt** [comment]
This is definitely something for games to implement themselves.
