### ISSUE TITLE
`Assets` failing to initialize in time

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#1662]
**Describe the bug**

Our custom [asset](https://github.com/mzegar/sbox-TTT/blob/main/code/asset/Asset.cs) fails to load for joining players when running the game off of face punch servers. I've confirmed that the asset was successfully uploaded and was downloaded by the user, it also seems like sometimes the uploading system ignores the `asset` files when uploading as well.

This system completely works when I host a local server and join the game on a separate instance of my client. It does not work when I have another player join me off a face punch hosted server.

**To Reproduce**

1. Download a little game mode I wrote to repro this issue https://github.com/mzegar/bug-report
2. Launch the game mode (on Facepunch servers)
3. Notice that `Pawn.cs` `Line 33`  sometimes ends up being `null` as a result of the `Asset` failing to load

**Comment by mzegar** [comment]
Hey, I managed to write up a game mode to isolate the issue.
https://github.com/mzegar/bug-report
```

 06:07:10   [1]  Sending connect to [U:1:67999400]:1
 06:07:10   Received S2C_CHALLENGE [3671634887 auth 3] from [U:1:67999400]:1
 06:07:10   Sending C2S_CONNECT [1001 protocol 3671634887 auth 3] to [U:1:67999400]:1
 06:07:10   Received S2C_CHALLENGE [3671634887 auth 3] from [U:1:67999400]:1
 06:07:10   Sending C2S_CONNECT [1001 protocol 3671634887 auth 3] to [U:1:67999400]:1
 06:07:10   Received S2C_CONNECTION from [U:1:67999400]:1 [addons:'']
 06:07:10   CL:  Suppress INetchannel::Transmit() in loopmode( remoteconnect )
 06:07:10   CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  
 06:07:10   CL:  Permit INetchannel::Transmit()
 06:07:10   CL:  CNetworkGameClient already exists for connection to '76561198028265128'
 06:07:10   CL:  connection to '76561198028265128' already started
 06:07:12   SetConVar: sv_noclipspeed = "0.5"
 06:07:12   SetConVar: sv_lobby = "109775240979814934"
 06:07:12   SetConVar: viewmodel_offset_y = "0"
 06:07:12   SetConVar: gamemode = "code.bug_test"
 06:07:12   SetConVar: host_timescale = "1"
 06:07:12   SetConVar: viewmodel_offset_x = "0"
 06:07:12   SetConVar: maxplayers = "24"
 06:07:12   SetConVar: sv_noclipspeed_min = "0.1"
 06:07:12   SetConVar: viewmodel_offset_z = "0"
 06:07:12   Error loading resource file "sbox_procedural_model.vmdl_c" (Error: ERROR_FILEOPEN)
 06:07:12   Joined Server Lobby 109775240979814934
 06:07:12   Looks like the game lobby changed to 109775240979814934
 06:07:13   Error loading resource file "cubemaps/construct_sky_custom_cubemap.vtex_c" (Error: ERROR_FILEOPEN)
 06:07:13   Error loading resource file "materials/particle/beam_generic_2.vtex_c" (Error: ERROR_FILEOPEN)
 06:07:14   CL: CNetworkGameClient::ProcessTick server tick 321 went backward from previous of 343, resetting previous
 06:07:14   Reverb: Unable to load baked data file (maps\construct.sareverb).
 06:07:15   Couldn't find property [ActiveGame](arg:0).PlayerListCanvas
 06:07:20   [230]  Object reference not set to an instance of an object.
 06:07:20   CL:  disconnect
 06:07:20   CL:  Server disconnected: 2: NETWORK_DISCONNECT_DISCONNECT_BY_USER
 06:07:20   CL:  Disconnecting from server: NETWORK_DISCONNECT_DISCONNECT_BY_USER
 06:07:20   Looks like the game lobby changed to
```

Notice that line 33 in `Pawn.cs` `Simulate` ends up being null sometimes. This occurs for the player host and the connecting player. If it doesn't end up null, try restarting the game mode a few times.

**Comment by Alf21** [comment]
Yea got the same issue back in the days, workaround: Moving the asset folder into the code folder ^^

**Comment by mzegar** [comment]
so to summarize, seems like the general issues are...
1. Sometimes `assets` don't successfully get uploaded to FacePunch servers, I have for sure uploaded assets before by defining the resource path `/assets/*`, but, it's hit or miss. 
2. `Assets` do not get sent to users when downloading the game mode itself (again, sometimes)
3. More specific to my game mode, `Assets` fail to initialize in time. It seems like it is the case that `Simulate()` starts calling on the player before the `assets` are even fully loaded in.

**Comment by mzegar** [comment]
Going to rewrite this ticket with a bit more conciseness, potentially split up since I think this is a multiple issue problem.
