### ISSUE TITLE
Steam deck gyro is offset by 90 degrees

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#1668]
**Describe the bug**

Steam deck gyro is offset by 90 degrees.

**To Reproduce**

1. Open "Gr&prix" gamemode on Steam Deck
2. Try to use gyro steering in-game
3. Observe that you constantly run into the wall

**Expected behavior**

Gyro-powered steering that doesn't require portrait mode holding

**Screenshots**

https://user-images.githubusercontent.com/11138884/157142952-576c4c89-ca3c-4729-b0d0-d3483ac9bcbd.mp4

**Additional context**

This is likely a pretty deep-rooted issue in the Deck's firmware, though I'm not sure how deep this runs. Likely have to work out the problem with Valve.

**Comment by handsomematt** [comment]
Cross posted to the Steam Input forum: https://steamcommunity.com/groups/steamworks/discussions/22/5144805327262517453/ - if it's intended by Valve I'll probably add a specific check to offset this so it behaves the same across all controllers.

**Comment by handsomematt** [comment]
Valve replied with

> We shipped a bug fix related to the quaternion about two weeks ago and the github ticket is ~9 days old so possibly they were running a build from before the fix?

And after checking in with you on Discord looks like it handles fine in the lab game and matches a normal controller behavior 

![image](https://user-images.githubusercontent.com/1388267/158874710-8a761603-cbd7-417e-a844-5de227f514ed.png)
![PXL_20220317_181500238](https://user-images.githubusercontent.com/1388267/158874798-4c0eea38-6795-44ea-a40f-1457e29ab08b.jpg)
