### ISSUE TITLE
ClientRpc breaks stuff when called during prediction

### ISSUE THREAD

**Issue by TankNut** [Facepunch/sbox-issues#167]
**Describe the bug**

Calling any function with the ClientRpc attribute during prediction will break things on the client, most notably velocity

**To Reproduce**

1. Clone dm98
2. Insert the following code into DeathmatchPlayer.Tick right below `base.Tick()`: 
```cs
Player player = All.Count() > 1 ? All[1] : null;

if ( IsClient && player != null )
{
	var diff = player.Velocity.Length - Velocity.Length;

	if ( diff > 20.0f )
		Log.Info( $"{diff}" );
}
```
3. Go in-game, enable consoleoverlay and spawn a bot
4. Move together with the bot while firing (dryfiring works as well)
5. Watch your console spit out huge differences in velocity between you and the bot and (sometimes) watch them warp into a completely different spot

**Expected behavior**

ClientRpc calls shouldn't break stuff

**Screenshots**

![2021-05-14_22-01-30](https://user-images.githubusercontent.com/1381265/118322891-1e6cb400-b500-11eb-8b21-f47be4970fca.png)

https://user-images.githubusercontent.com/1381265/118322944-317f8400-b500-11eb-9971-9a105c05b88c.mp4

It's not entirely obvious due to BaseDMWeapon.DryFire not having any effects but the hitching is caused by me spamming attack and hitting the aforementioned ClientRpc

**Additional context**

It seems to happen every single time an rpc call is made as long as it (somehow) involves the player, happens with everything from ShootEffects in dm98 to DecalDefinition.Place and is pretty game breaking for anything involving multiplayer

**Comment by garrynewman** [comment]
This is interesting, this is a bug I've seen but not been able to nail down what causes it. I'll see if I can recreate it with your method.

I've seen it happen on physics props too, usually when shooting them. Maybe the RPC to add decals is doing it there?

**Comment by TankNut** [comment]
I've done some testing with physics props in sandbox and have been able to recreate the issue there no problem. It'd have to be the decal rpc yeah.

What's interesting though is that I've been able to get it to work with any object that's in motion and not just things I'm shooting at. The rate at which objects 'warp' seems to be influenced by their velocity (The faster the object moves, the easier it is to trigger, hence why it's significantly easier to trigger by shooting at a prop which gives it a nice big punt)

Shot in the dark here but is it possible that rpc's are somehow causing the client to process the same server snapshot multiple times?

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by TankNut** [comment]
Haven't been able to recreate it using any methods I know 👍
