### ISSUE TITLE
Custom clothing assets not showing up

### ISSUE THREAD

**Issue by Kabubu2** [Facepunch/sbox-issues#1672]
Creating a clothing asset in a custom addon does not display in the terry clothing selector

**To Reproduce**

Create a clothing asset in a custom addon and see terry clothing selector.

**Expected behavior**

New clothing assets show up as it did before

**Screenshots**

![image](https://user-images.githubusercontent.com/18005111/157317034-bb137986-2498-4ac9-a94e-832df1123c37.png)

![image](https://user-images.githubusercontent.com/18005111/157317118-8a0602e8-6db5-481e-a92d-8f8ffffbb0fb.png)

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/1565

(Same issue)
