### ISSUE TITLE
`Assets` fail to upload sometimes

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#1673]
**Describe the bug**

My `asset` files do not upload successfully sometimes. Here is an example video https://www.youtube.com/watch?v=1EeGahyqqNM

1. I have my asset files in my `assets` folder
2. I make a change to a random file, and then click upload
3. Notice that my freshly uploaded game mode doesn't have any of the compiled asset files anymore

I've double-checked other game modes that use asset files and I use a similar `.addon` file plus where the assets are stored.

What I've done to fix this, is I take out the `assets` folder, re-upload the game mode, bring back the `assets` folder inside, then upload it again in order for the assets to be properly sent.

**Expected behavior**

The asset files should upload.

**Comment by handsomematt** [comment]
I can't recreate this, can you make a reproducible for me?

**Comment by mzegar** [comment]
Yeah no luck myself as well, I tried making a small little sample project but was also unable to repro. If my project runs into it again I'll let you know (or if the Fortwars people do as well), might be able to use those as a starting point?

**Comment by mzegar** [comment]
Haven't had this happen in a while, but I also did end up removing a bunch of files from my repo. Closing since there is no repro available.
