### ISSUE TITLE
Can't Lasso Select While Hovering Over Selected Object

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#1674]
**Describe the bug**
You cannot Lasso Select while hovering over a selected object

**To Reproduce**

1. Select an object
2. Try and lasso select over the selection
3. Lasso select will not work in the selected region

**Expected behavior**
You should be able to lasso select over other selected objects

**Screenshots**
https://user-images.githubusercontent.com/65134886/157758405-3e6e0776-2b84-42c8-a6b2-26af8c521f80.mp4

**Comment by aylaylay** [comment]
This isn't a simple fix, this is just how the system works. I don't think it's a big issue because you can just cancel the selection and then do the lasso.
