### ISSUE TITLE
Incorrect Light_omni Preview In Hammer

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1678]
**Describe the bug**
Light_omni casts a weird shadow in hammer after loading into a map
![image](https://user-images.githubusercontent.com/39461072/158045792-9035439d-b0de-486d-8cde-0149829f227e.png)

**To Reproduce**
1. Load into a map
2. Place a light_omni in hammer
3. See error

**Expected behavior**
light_omni shouldn't have anomalous shadows

**Comment by KayaDLX** [comment]
Lightcookies issue

**Comment by gvarados1** [comment]
I think this and #1679 were unintentionally fixed
