### ISSUE TITLE
Lighting in Appearance Editor Menu Breaks after Loading a Map

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1679]
**Describe the bug**
The fog/lighting in the character editor breaks after loading into a map

Just launched s&box:
![image](https://user-images.githubusercontent.com/39461072/158047232-25be7e35-6088-4820-a26f-dd034f2b31b1.png)

After loading a map:
![image](https://user-images.githubusercontent.com/39461072/158047238-8abe8e48-ac8a-4b6a-b84b-faaf165566ca.png)

**To Reproduce**

1. Launch s&box
2. Load a map
3. Open Character Appearance Menu

**Comment by ogniK5377** [comment]
Unable to reproduce, what map are you loading? I've tried loading construct, office & a map which messes with fog

**Comment by NotGaylien** [comment]
This happens randomly when messing with flashlights or things with light cookies or whatever they are called.
Its happened to me a few times randomly.

**Comment by ogniK5377** [comment]
I tried with spamming lamps, lights, flashlights, compiling maps etc and can't seem to trigger it. Maybe it was accidently fixed?

**Comment by gvarados1** [comment]
Yeah I think this and #1678 were unintentionally fixed a couple days ago. I'll re-open if it turns out they weren't fixed.
