### ISSUE TITLE
ent_path_platform horizontal player movement is still broken

### ISSUE THREAD

**Issue by AfteraOfficiel** [Facepunch/sbox-issues#1686]
**Describe the bug**

Hello

There are already a closed ticket : https://github.com/Facepunch/sbox-issues/issues/904

But this bug are not corrected

**To Reproduce**

Same as old ticket

Create an ent_path_platform and set it to follow a path_generic that has horizontal movement.
Load the map in game and ride the platform around.
See error.

**Expected behavior**

**Screenshots**

**Additional context**.
[ent_path_platform_bug.zip](https://github.com/Facepunch/sbox-issues/files/8257872/ent_path_platform_bug.zip)

**Comment by handsomematt** [comment]
I'd only fixed this on PlatformEntity and not PathPlatformEntity, this should now be good.

https://user-images.githubusercontent.com/1388267/158606973-1195b1fd-c361-463b-86ea-e2e017ed4dd8.mp4

**Comment by AfteraOfficiel** [comment]
thank you for your quick response. If we put a prop on it yes, but if the player is on it we still go through

**Comment by AfteraOfficiel** [comment]
https://user-images.githubusercontent.com/99672629/158658240-0c1932a6-0aea-47e9-ab19-68e214ca0b8a.mp4

**Comment by handsomematt** [comment]
> thank you for your quick response. If we put a prop on it yes, but if the player is on it we still go through

If you were testing on Sandbox gamemode, try again - I forgot to upload since it uploads a copy of the base addon.

**Comment by AfteraOfficiel** [comment]
Great, Working thank you Matt !
