### ISSUE TITLE
Ctrl+S to Save doesn't work on Asset Inspector

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1688]
**Describe the bug**
Pressing Ctrl+S doesn't save on the asset inspector

**To Reproduce**
1. Open asset inspector
2. Press Ctrl+S
3. See error

**Expected behavior**
Ctrl+S should save the file

**Screenshots**
![image](https://user-images.githubusercontent.com/39461072/158893879-3a37a147-f93a-4254-b1b3-249b1c3a0153.png)

**Comment by Adesii** [comment]
This explains a lot. i thought i was just stupid and didn't focus the window... good to know that im not the only one having this issue lol

**Comment by handsomematt** [comment]
Should be good now.

**Comment by gvarados1** [comment]
Perfect. Thanks!
