### ISSUE TITLE
Resource types exceeding a specific length will not compile properly

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#1691]
If you're making an asset, and its file extension is too long, it won't ever compile.

**Repro:** 
1. Grab https://github.com/DevulTj/sbox-assetlab
2. Run the game
3. Open the Asset Browser and find myresource.e_resource, right click it, and try to Full Compile. Notice that it is not a compileable resource.

**Things to Note:**
- The resource generates a working FGD file.
- You can create assets in the Inspector with this new type.

**Images:**
![image](https://user-images.githubusercontent.com/22372616/159101714-1a29cca0-f38c-4d25-9ab9-ca3ac6c12c2d.png)
![image](https://user-images.githubusercontent.com/22372616/159101720-ec92fca2-cff0-40bd-a309-d5c06b3b5c7b.png)

**Comment by handsomematt** [comment]
I've made this chuck an obvious error and not generate asset types that exceed 8 character file extensions. As well as not load these existing invalid ones, so you shouldn't be able to get into this confusing state again.

I thought about letting it exceed but internally these are all turned into a uint64, so making them bigger is a pita and probably fucks a bunch of optimizations in the resource system.

**Comment by DevulTj** [comment]
Works a treat, ty
