### ISSUE TITLE
Allow assets as ClientRpc parameters

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#1695]
**What can't you do?**
I'd like to pass a custom asset as an argument in a client RPC. This currently causes an exception at runtime which says something like: 

```
[ClientRpc] OnClientPlayScreenEffect is not allowed to use ScreenEffect for the parameter 'effect'!
```

**How would you like it to work?**
I should be able to write RPC methods that accept parameter types that inherit from `Asset`. 

**What have you tried?**
```cs
[ClientRpc]
protected void OnClientPlayScreenEffect(ScreenEffect effect)
{
	Event.Run(GameEvent.ScreenEffect, effect);
}
```
where `ScreenEffect : Asset`

**Comment by kolexxx** [comment]
You can pass the Asset.Id to the client rpc and then call Asset.FromId<ScreenEffect( id ) on the client to get the asset.

**Comment by TheBerkin** [comment]
> You can pass the Asset.Id to the client rpc and then call Asset.FromId<ScreenEffect( id ) on the client to get the asset.

I use a very similar workaround at the moment, but being able to pass the asset directly into the method would remove the need for that extra step.
