### ISSUE TITLE
Model spawning concrete debris on break

### ISSUE THREAD

**Issue by Kabubu2** [Facepunch/sbox-issues#1696]
Whenever I break a custom model it spawns a block of concrete.

https://user-images.githubusercontent.com/18005111/159419962-aacf1982-6091-4735-8f84-09a7be074359.mp4
![image](https://user-images.githubusercontent.com/18005111/159419994-1152f0df-a163-4366-b8a1-44f67144f5ec.png)
![image](https://user-images.githubusercontent.com/18005111/159420027-7f4b7807-9e34-44b6-80ae-078d45f55cdc.png)

It should spawn the break_create_particle model but it doesn't.

**Comment by robotboy655** [comment]
I don't think that is what the `Model` field is in the particle for. Either way, it spawns the generic gib because your model has no gibs of its own. You could simply make your `chips_damaged.vmdl` a break piece on your base model.

**Comment by Kabubu2** [comment]
Awesome, sorted by adding the model as a break piece
