### ISSUE TITLE
Add the ability to generate sounds form Samples

### ISSUE THREAD

**Issue by TehFlaminTaco** [Facepunch/sbox-issues#1703]
**What can't you do?**
Generate Sounds at runtime

**How would you like it to work?**
Probably a factory class like Textures?
`Sound.Create().WithSamples(array).WithSampleRate(64f).Finish()`?

**What have you tried?**
The `Sound` and `SoundEvent` classes contain no method of sound construction.

**Additional context**
Would allow for implementation of downloaded sounds, and other sound generates like SPU's from Olde wiremod.

**Comment by m0uka** [comment]
You can create a sound stream, see sound.CreateStream. Then you just write the samples with Stream.WriteData(short[] data).

**Comment by TehFlaminTaco** [comment]
Sound.CreateStream seems to be an Instance Method rather than a Static Method, Is this intentional?

**Comment by m0uka** [comment]
Yes, sounds should be attached to something: use the static methods to create the Sound object (FromEntity, FromWorld, FromScreen), and then create the soundstream from that
