### ISSUE TITLE
Input.Pressed is unreliable in the Tick method of panels.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#1705]
**Describe the bug**
When checking for `Input.Pressed` in the Tick method of a Panel, it returns true multiple times across several ticks.

**To Reproduce**
```CS
    //override tick method on a Panel
    public override void Tick()
    {
        base.Tick();

        if (Input.Pressed(InputButton.Flashlight))
        {
            Log.Info("funny");
        }
    }
```
This will log 'funny' multiple times after a single press of the flashlight input.

**Expected behavior**
Only be logged once.

**Comment by DevulTj** [comment]
This has been a pain for me too, it can invalidate your input as well so it makes input feel shitty when opening/closing a menu this way.

**Comment by handsomematt** [comment]
I think Input.Pressed is reacting off of server ticks. Could probably change it's behaviour depending on the context it's being used in (not Simulate)

**Comment by handsomematt** [comment]
Give that a go lads

**Comment by Fortune117** [comment]
```CS    
public override void Tick()
    {
        if (Input.Pressed(InputButton.Flashlight))
        {
            Log.Info("funny");
            ToggleMenu();
        }
    }
```
Seems to always log twice when I try this.
