### ISSUE TITLE
ModelDoc option to disable keyframe interpolation to allow for constant keyframe animations

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1706]
**What can't you do?**
Have animations sampled with constant keyframes.

**How would you like it to work?**
An option on the simple animation file node or something similar.

**What have you tried?**
I don't doubt that I might be missing something, but I think I might currently be limited by the blender fbx exporter. Whatever I try, my constant keyframes always get either resampled or interpolated on export, so having an option built into the source 2 import pipeline would be great.

**Additional context**
It's possible that this isn't even feasible, but I don't currently see any other way to make constant key frame animations possible other than to write my own fbx exporter. This seems to be a general issue with common fbx exporters based on my research.

**Comment by aylaylay** [comment]
Added @DoctorGurke

![sbox-dev_QiDxwUi5pl](https://github.com/Facepunch/sbox-issues/assets/1667289/0b7bd708-b613-4eae-a227-501605223e9e)

**Comment by DoctorGurke** [comment]
awesome thanks
