### ISSUE TITLE
Cursor: none; doesn't hide the Cursor and keeps the Last Cursor Shape that was Active

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#1707]
**Describe the bug**
When setting the Style Cursor: none; on a Panel it doesn't hide the cursor and rather keeps the last active Shape.
so when hovering on a Button like the Leave Game button in the Menu and then closing the Menu it will keep the click shape until hovering over something else.

**To Reproduce**

1. Have a Fullscreen Panel with Cursor: none; and Pointer-Events: all;
2. Open the Main Menu
3. Hover over the Leave Game Button
4. Close the Main Menu While being over the Button
5. See the Cursor Shape being stuck on the Click Shape

or use the Example Addon Provided and skip Step 1:
[CursorNoneExample.zip](https://github.com/Facepunch/sbox-issues/files/8356425/CursorNoneExample.zip)

**Expected behavior**
It should Hide the Cursor just like it does when the Window is capturing the Mouse.

in my case for use in Custom Cursor's, but also similar scenario's where the mouse shouldn't be visible but still act as a free mouse.
Other Solutions to this would be fixing Pointer-Events: auto; to be limited to the Active Viewport or giving us a option atleast to capture it with our own Solution. since Mouse.Position will return values bigger than the screen which is absurd. Will likely make another issue on that tho

using Mouse Delta to move a Panel around isn't a solution because the Sensitivity is all wrong and doesn't represent the Real mouse Movement (not sure if this is a real issue or just me being dumb in using it)

**Screenshots**

https://user-images.githubusercontent.com/37816311/160257899-48d7bc02-5655-4ba0-9e40-39807b8a5eb9.mp4

**Comment by handsomematt** [comment]
should be good now

**Comment by Adesii** [comment]
Yeah, works great now.

**Comment by Adesii** [comment]
wait... nevermind. in tools mode atleast when clicking outside the game window the cursor won't dissapear until the menu is opened

**Comment by handsomematt** [comment]
I'd say that's expected behavior since your game view isn't focused?

**Comment by Adesii** [comment]
if i click into the game it doesn't dissapear. only when opening the menu.
it might not be visible in the video but im clicking into the game

**Comment by handsomematt** [comment]
Because you're so lovely there ya go. I think it was happening to any other cursor type too, so that's nice to have fixed as well.

**Comment by Adesii** [comment]
Lovely. Works Perfectly now <3
