### ISSUE TITLE
Traffic cone gibs are errors.

### ISSUE THREAD

**Issue by LeftoverAtoms** [Facepunch/sbox-issues#1708]
**Describe the bug**

When you destroy this model, it spawns errors.

**To Reproduce**

1. Cause a traffic cone to gib.
2. See error.

**Expected behavior**

Should spawn destroyed versions of the model and not errors?

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/66341882/160260981-2b801ca3-d24b-4bc1-aa95-baadfe64e8c3.png)

**Comment by bakscratch** [comment]
I did a full recompile of the gibs, hopefully it fixed this issue. Everything seems to be set up correctly in ModelDoc.
