### ISSUE TITLE
Map Mesh Entities Always Appear, Even When the Entity Doesn't Exist.

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1709]
**Describe the bug**
Map mesh entities from other games appear, even when the current game doesn't support that entity. I assume it turns into some dummy base mesh entity. It shouldn't be spawned in at all.

**To Reproduce**

1. Create a mesh entity for a game (ex. wall entity for Fortwars)
2. Load the map on a game that doesn't have that entity (ex. not Fortwars)
4. The mesh entity is still there, even though it doesn't exist on that game.

**Expected behavior**
If the game doesn't have the specified entity, the entity shouldn't exist. This is expected behavior and seems to be how it works for point entities & triggers.

**Screenshots**
In this screenshot you can see the wall entity from Fortwars (func_wall_toggle) in sandbox mode. This is just a huge wall that breaks every game other than Fortwars. This makes it so I would have to upload separate versions of the map for simple entity changes.
![image](https://user-images.githubusercontent.com/39461072/160265220-d4bca741-06c2-4c5b-a3a7-5d6d871c553c.png)

Here you can see Conquest is unplayable because of the Fortwars wall.
![image](https://user-images.githubusercontent.com/39461072/160265411-8bb63c14-14dd-4ba3-984e-12d4b1030cb3.png)

**Comment by handsomematt** [comment]
Makes sense for us to make these meshes not show if part of a non existent entity, I'll see what I can do.

**Comment by handsomematt** [comment]
Actually this already works like I said - the problem is `func_wall_toggle` is still implemented in C++ so it's falling back to it... I'll remove it.

**Comment by gvarados1** [comment]
thank you :)

**Comment by gvarados1** [comment]
func_breakable still exists in c++. needs to be removed. There are probably a few others too.
