### ISSUE TITLE
Allow mesh entities created in Hammer to retain static Mesh collision shapes

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#1714]
**What can't you do?**
Create a mesh entity in Hammer, and have that entity generate mesh colliders like a non-entity mesh does.

**How would you like it to work?**
Add `ModelEntity.SetupPhysicsFromMesh` or similar, depending on how mesh collision data is stored/generated from Hammer.

**What have you tried?**
Tried using `Model.GetVertices` to copy the mesh's model data and feed that into `PhysicsBody.AddMeshShape`, but the list of vertices returns null. Probably due to not being "compiled for CPU access" like models can be in ModelDoc.

**Comment by aylaylay** [comment]
Does it create a convex collision instead of mesh collision currently?

**Comment by bakscratch** [comment]
Have you tried setting the Physics Type to "Mesh" https://files.facepunch.com/louie/1b2411b1/sbox_fT7Q2bqT2y.png, you'll need to be a in mesh mode to do this https://files.facepunch.com/louie/1b2411b1/sbox_f3lBOLwDRJ.png
