### ISSUE TITLE
Inconsistent `Client.All` in `Game.ClientJoined`

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1715]
**Describe the bug**
`Client.All` is inconsistent, *probably* depending on the map (size?).

That leads to the issue that there are uninitialized data / events for the connected player if the code is relying on fetching the connected Client e.g. by NetworkIdent.

**To Reproduce**

1.
Add to your `Game` class code

```csharp
public override void ClientJoined(Client client)
{
    Log.Warning($"Ident: {client.NetworkIdent}");

    foreach (Client cl in Client.All)
    {
        if (cl.NetworkIdent == client.NetworkIdent)
            Log.Warning("Found");
        else Log.Warning("Not found");
    }

    Log.Warning($"{Client.All.Count}");
}
```

2. Connect e.g. to a `ice.terminal`
3. Spawn a bot via `bot_add` (Error should appear)
4. Disconnect
5. Connect to the default construct map
6. Spawn a bot via `bot_add` (Error should *not* appear)

**Expected behavior**
Consistent behavior, so Client.All is updated before `Game.ClientJoined` is called

**Comment by handsomematt** [comment]
This is probably fixed now.

**Comment by Alf21** [comment]
Yea, now, it works as intended. Thanks!
