### ISSUE TITLE
Cloth simulation pauses when the window IS selected

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#1717]
**Describe the bug**

The cloth simulation on an AnimModel is paused whenever the game's window is focused and starts playing back again when you tab out of it.

**To Reproduce**

I'll attach the seal model to reproduce the bug.
https://drive.google.com/file/d/1z7k5oOjVQeJEPlQAIuCFiyZrSh13iEGi/view?usp=sharing
The model may need to be compiled at first, I'm not sure why.

**Expected behavior**

Instead of pausing when the window is in focus it should be the opposite, or maybe never pause at all. 

**Screenshots**

https://user-images.githubusercontent.com/59583743/160884506-5a63e9f0-b214-498c-978c-2849b094627c.mp4

**Additional context**

Here's the code I used:
`using Sandbox;

public partial class Seal : AnimEntity
{

	public override void Spawn()
	{

		base.Spawn();

		SetModel( "models/seal/seal.vmdl" );
		SetupPhysicsFromModel( PhysicsMotionType.Static );

	}

	[Event.Tick.Client]
	public void Tick()
	{

		SetAnimParameter( "Honk", true );

	}

}
`
This also happens on PhysicsMotionType.Dynamic

**Comment by yuberee** [comment]
@samzanemesis Yes, it still happens.
When the video lags it's because I ALT-TAB out of the window.

https://user-images.githubusercontent.com/59583743/178293909-99311e02-e919-439f-965e-46efd668715c.mp4

**Comment by ShadowBrian** [comment]
Sam pls fix

**Comment by yuberee** [comment]
Seems like our model doesn't have cloth simulation anymore. Did you have to modify it yourself to get it working?
