### ISSUE TITLE
Glass doesn't break when trying to walk through it.

### ISSUE THREAD

**Issue by kolexxx** [Facepunch/sbox-issues#1718]
**To Reproduce**

1. Launch up `DM98`
2. Break some glass
3. Try to walk through it

**Additional context**
This seems to work just fine on gamemodes that haven't been updated in a while, like `Sandbox`.

**Comment by DoctorGurke** [comment]
Sandbox was last updated 3 days ago

**Comment by handsomematt** [comment]
The glass is colliding with bugged pickup triggers on weapons in Sandbox.

Player's physics shadow is never getting the chance to touch the glass because of the movement code, will have a think about what to do for this.
