### ISSUE TITLE
PET: Set Float (Per-Particle) Roll min and max values make no sense.

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#1721]
**Describe the bug**

When setting the Roll with Set Float. You would expect the min and max values would be -360 to 360, but no. It's actually -6.2831 to 6.2831 because 6.2831 = to 360 for whatever reason.

**To Reproduce**

Download the vpcf below and mess around with the set float function that has roll as its output field.
[untitled_particle_2.zip](https://github.com/Facepunch/sbox-issues/files/8401199/untitled_particle_2.zip)

**Expected behavior**

Whatever value you put in doesn't match the actual roll value that the particle has.

https://user-images.githubusercontent.com/17112771/161350955-d5e33ab5-fee5-495b-9db4-5983eed233c0.mp4

**Comment by DoctorGurke** [comment]
radians

**Comment by justynboi** [comment]
Yeah, but I think it would be better to not deal with radians and put the exact degree that the artist wants like in every source 1 and 2 game? Its annoying that if I want an exact degree I have to convert that to a radian everytime.

**Comment by DoctorGurke** [comment]
nah it should definitely be wrapped in degrees for the user, expecting users/artists to use radians in a ui is stupid

**Comment by aylaylay** [comment]
I'll sort it tomorrow. Let me know if there's any other instances of input taking radians

**Comment by justynboi** [comment]
as far I know, the other outputs in Set Float are fine, but using alpha as an output limits you to use 0 to 1 instead of 0 to 255. Not really a big deal, but would be nice if that got changed.

**Comment by DoctorGurke** [comment]
alpha being 0-1 should probably stay for the sake of default random range being 0-1 as well. Would also just break all particles using random alpha etc ever lol

**Comment by justynboi** [comment]
true

**Comment by aylaylay** [comment]
Angles for this particle function should now deal in degrees. There's other functions that will still use radians so just make a new issue when you see them and I'll apply the same fix.

**Comment by justynboi** [comment]
Appears to work great! Can you apply the same fix onto "Set Float (Per Particle)" also?

**Comment by justynboi** [comment]
bump

**Comment by aylaylay** [comment]
I have applied the fix for "Set Float (Per Particle)" please check if it works

**Comment by justynboi** [comment]
Appears to be working. Thanks!
