### ISSUE TITLE
Chat not working with bound key

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1724]
**Describe the bug**
Chat is not working if you've bound a key via menu to `+iv_chat` anymore. Tested on every gamemode.

My Chat key is bound to [ENTER]. Adding

```csharp
if (Input.Down(InputButton.Chat))
{
    Log.Warning("Pressed");
}
```

to the Simulate function produces corresponding prints on the Client and Server. If no key is bound to the chat, this log is not printed.

So it seems like `Sandbox.Hooks.Chat.OnOpenChat` is not called properly. I've checked that I did not modify any base file. I've reinstalled S&Box already.
The issue stays. It does not work in normal S&Box and S&Box with `-tools` argument / Editor view.
Resetting the keys to default enables the chat interaction but disables the InputButton detection.

**To Reproduce**

Bind a key to `Open Chat` / `+iv_chat`

**Expected behavior**

Chat opening if key is bound to another key.

**Screenshots**
![image](https://user-images.githubusercontent.com/11843790/161429381-ef90a2c7-41a8-4bec-8cfa-bb1979d20b90.png)

![image](https://user-images.githubusercontent.com/11843790/161429415-b58926e7-6344-4d8f-a18d-27f547f71a0d.png)

**Comment by handsomematt** [comment]
My bad I was trying to unify all this stuff but forgot this one.

**Comment by Alf21** [comment]
Yea not that I could think about a person binding it to a different key, but I found myself testing stuff and now debugging why my chat wasn't working anymore :D

**Comment by handsomematt** [comment]
Finally got around to this, sorry it took so long.

I've obsoleted `Sandbox.Hooks.Chat.OnOpenChat` so the way you'd do a chatbox is as simple as any other panel now:

```csharp
public partial class ChatBox : Panel
{
	public override void Tick()
	{
		base.Tick();

		if ( Sandbox.Input.Pressed( InputButton.Chat ) )
		{
			Open();
		}
	}
}
```
