### ISSUE TITLE
Bugged water

### ISSUE THREAD

**Issue by Bugtogs** [Facepunch/sbox-issues#1727]
**Describe the bug**
Recording with OBS causes the water ripples to freak out

**To Reproduce**

1. Go to construct
2. Record with OBS
3. Interact with the water

Video
https://user-images.githubusercontent.com/36604273/161462466-59a74d2c-c49a-4b72-af14-20e23f837c3b.mp4

**Comment by samzanemesis** [comment]
This should be fixed, can you confirm?
