### ISSUE TITLE
System.Runtime.Serialization.* whitelist

### ISSUE THREAD

**Issue by Sl4vP0weR** [Facepunch/sbox-issues#1728]
Especially System.Runtime.Serialization.Formatters.Binary.BinaryFormatter class for binary serialization.

**Comment by handsomematt** [comment]
https://docs.microsoft.com/en-gb/dotnet/standard/serialization/binaryformatter-security-guide

Not gonna happen.

**Comment by Sl4vP0weR** [comment]
@handsomematt Thanks, maybe exists some workaround for binary serialization?

**Comment by handsomematt** [comment]
There's alternative examples on the link, generally you would implement a BinaryReader / BinaryWriter to serialize stuff.
