### ISSUE TITLE
ent_path_platform horizontal player movement is still broken #2

### ISSUE THREAD

**Issue by AfteraOfficiel** [Facepunch/sbox-issues#1730]
**Describe the bug**

Hello

There are already a closed ticket : https://github.com/Facepunch/sbox-issues/issues/1686

There is still a small bug

**To Reproduce**

Same as old ticket with some new actions

Create an ent_path_platform and set it to follow a path_generic that has horizontal movement.
Set "Stop" in Automatic Movement in ent_path_platform entity
Load the map in game and ride the platform around.
Wait for the end of the action of the platform and see that we are projected at the speed of the entity even if it is stopped

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/99672629/161580118-b7a7516a-81a0-4157-a2af-ab57dfbfac68.png)

**Additional context**

https://user-images.githubusercontent.com/99672629/161580252-0a5e95fd-58f9-45a9-acd3-61e62a05222a.mp4

vmap in older ticket

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by AfteraOfficiel** [comment]
> Should be fixed when the game next updates.

After two restart + update same problem, i give a vmap so you can easy test

[map_for_rubat.zip](https://github.com/Facepunch/sbox-issues/files/8413233/map_for_rubat.zip)

**Comment by handsomematt** [comment]
I've reuploaded the Sandbox game, it should work now.

**Comment by AfteraOfficiel** [comment]
> I've reuploaded the Sandbox game, it should work now.

Thanks Matt, it work
