### ISSUE TITLE
Finish the sbox Editor mode and its functionality

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1731]
**What can't you do?**
Use all available -tools mode functions from the main editor window (F3)

**How would you like it to work?**
Move all the old stuff from the F1 editor menu to the new one.

**What have you tried?**
Need to use F1 to access some of the old functionality, which leads to some awful UI situations.

**Additional context**
![sbox-dev_pQM8JcpJwT](https://user-images.githubusercontent.com/12602100/161647674-c26cbeee-4faf-40d0-8669-ab6cf1157a21.png)

Functions that are still in the old (F1) menu:

- SV/CL phys preview
- Console overlay toggle
- Perf stats and perf chart widgets
- Entity IO debug toggle
- Fakelag options
- Prediction errors debug toggle
- Filter console by Error, Warning and Message categories

**Comment by trundler-dev** [comment]
Please also fix #1525 :)

**Comment by KayaDLX** [comment]
Related issue: #1775
