### ISSUE TITLE
Input Settings overflowing off screen

### ISSUE THREAD

**Issue by SharpMars** [Facepunch/sbox-issues#1732]
![obraz](https://user-images.githubusercontent.com/70289680/161861323-c05504ce-e7cb-4b3a-91fd-1a6dd19c813c.png)
Input Settings don't fit entirely within the screen, with Slot9 and Slot0 options getting cut off.

Resolution: 1366x768

**Comment by cr4yz** [comment]
Should be fixed in the next update!

**Comment by SharpMars** [comment]
Thanks :)
