### ISSUE TITLE
Asset properties don't get set if their internal_name is different from the autogenerated one.

### ISSUE THREAD

**Issue by kolexxx** [Facepunch/sbox-issues#1738]
**Describe the bug**
Asset properties don't get set if their `internal_name` is different from the autogenerated one.

**To Reproduce**

1. Download [minimalexample.zip](https://github.com/Facepunch/sbox-issues/files/8443248/minimalexample.zip)

**Additional context**
To confirm this, open `assets/untitled.test` and change `worldmodel = resource:"models/light_arrow.vmdl"` to `worldmodelpath = resource:"models/light_arrow.vmdl"`, after that reload the asset and restart the gamemode.

**Comment by robotboy655** [comment]
You need to use ```[JsonPropertyName]```, not ```[Property]``` if you wish to override the internal name.
