### ISSUE TITLE
[s&works] Can't enter https://sw.facepunch.com/~notices

### ISSUE THREAD

**Issue by BeatCrazey** [Facepunch/sbox-issues#1742]
I cannot access https://sw.facepunch.com/~notices to accept my organization's invitation. It keeps spewing the following error:

![image](https://user-images.githubusercontent.com/52133628/162628032-834f193e-007b-4bdb-8bd3-e7dc2fd911b9.png)

I don't know what kind of problem this is, as it isn't related to the s&box client. Maybe some of the s&works backend people could take a look at this? Having this problem since yesterday.

- **Browser:** Google Chrome

- **Location (roughly):** Center-West, Brazil

**Comment by gvarados1** [comment]
having same issue
