### ISSUE TITLE
func_shatterglass Reset Hammer Input

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1743]
**What can't you do?**
We can't reset func_shatterglass with hammer inputs

**How would you like it to work?**
I've looked at the code, and a Reset() function is already there. It just needs to be turned into a hammer Input
![image](https://user-images.githubusercontent.com/39461072/162641991-19fe5822-adc2-4bd0-9472-49128e762604.png)

**Comment by AfteraOfficiel** [comment]
On HLA it is possible, it would be a wonderful feature

**Comment by aylaylay** [comment]
Done
