### ISSUE TITLE
[Hammer] Allow editing compiler command line

### ISSUE THREAD

**Issue by FullStack0verfl0w** [Facepunch/sbox-issues#1747]
**What can't you do?**
I want to edit compiler command line to change some settings or execute commands after compiling a map.

**How would you like it to work?**
Just make the text box editable.

**Comment by ogniK5377** [comment]
What would need to be changed/added specifically?

**Comment by FullStack0verfl0w** [comment]
> 
This
![image](https://user-images.githubusercontent.com/36414434/162769628-b694ce98-8129-4a17-a0dd-6c991720b731.png)

**Comment by DoctorGurke** [comment]
right but what about it? the command line just mirrors what your settings above do with resourcecompiler

**Comment by ogniK5377** [comment]
> > 
> 
> This ![image](https://user-images.githubusercontent.com/36414434/162769628-b694ce98-8129-4a17-a0dd-6c991720b731.png)

I meant which command-line options would you need to change/add
