### ISSUE TITLE
Entities from S&works Show as Error, No Assets are Downloaded

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1748]
**Describe the165 bug**
When you mount entities from s&works, it only downloads the entities. No assets like models/materials are included.
This results in Errors & missing textures.

**To Reproduce**
1. Mount a s&works game on hammer with content that you don't have installed locally (ex. dm98)
2. Place a model entity in your map. (ex. dm_battery)
3. If you don't have the model installed locally, it will be an error

**Expected behavior**
If you mount entities it should also have all the assets.
This includes custom tool materials for custom triggers.

**Screenshots**
![image](https://user-images.githubusercontent.com/39461072/162876347-7f4d8ad5-f370-4d76-a407-b3d866dac0e9.png)

**Additional context**
Currently to fix this we have to:
1. Install the game locally, which defeats the point of this whole system.
or
2. Play the game on s&box to get all the assets loaded, then launch hammer.

**Comment by handsomematt** [comment]
This should now work.

**Comment by gvarados1** [comment]
Works! Thank you!
