### ISSUE TITLE
Hammer - S&works Entities Show as Obsolete Until Updated

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1750]
**Describe the bug**
All s&works entities will show as obsolete in hammer until updated after re-opening the map.

**To Reproduce**
1. Place an entity from s&works in your map, save & close s&box
2. Re-open s&box and your map, you will see the entities as obsolete
3. Update the entity (ex. move it), entity will show correctly

**Expected behavior**
Entities shouldn't be obsolete until updated

**Screenshots**

https://user-images.githubusercontent.com/39461072/163009228-7498bfb8-20d2-485e-a724-378c6308a207.mp4

**Comment by handsomematt** [comment]
Was loading the packages slightly too late, should work perfectly now.

**Comment by gvarados1** [comment]
doesn't work

**Comment by gvarados1** [comment]
Doesn't work

**Comment by KayaDLX** [comment]
works for me

**Comment by gvarados1** [comment]
Are you testing with a local game or game mounted from s&works?

**Comment by KayaDLX** [comment]
no local game at all, only assets & maps

**Comment by gvarados1** [comment]
> does this still happen @gvarados1

yes

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
Bump.
Got the same issue.

**Comment by gvarados1** [comment]
looks like restarting hammer also fixes this

**Comment by handsomematt** [comment]
entities should be loading on tools startup way before Hammer is even opened - I can't replicate this in any way

**Comment by robotboy655** [comment]
Sometimes I do get it when I launch Hammer too quick. It's the async jobs that don't finish in time.

**Comment by gvarados1** [comment]
Seems to be fixed. Thanks!
