### ISSUE TITLE
Map Trigger Volumes Don't Compile Properly - Shows Materials When it Should be Invisible

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1752]
**Describe the bug**
Some map trigger volumes in hammer don't compile properly. It shows the mesh & original material before it was turned into a trigger.
So if I was to make a block with a dev texture, then turn it into func_precipitation, it would show as a devtexture block in-game.

I've tested a few entities and so far I've only found func_precipitation and some TFS2 entities have this issue. For reference, trigger_multiple works correctly.

**To Reproduce**

1. Place an affected entity in a map, compile (ex. func_precipitation)
2. See error

**Expected behavior**
Triggers / Volumes should be invisible

**Screenshots**
The func_precipitation is visible as a devtexture but has no collisions
![image](https://user-images.githubusercontent.com/39461072/163082394-9a427ac6-2898-4f6c-bf6b-fe87e63a15a9.png)

Here is the func_precipitation in hammer:
![image](https://user-images.githubusercontent.com/39461072/163082990-f4de891c-2c60-4019-8d12-eaef0918965a.png)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by gvarados1** [comment]
I thought it wasn't working, but looks like there's a different bug with entities not updating properly after compiling.
I had to restart my game after compiling the map to see it fixed.
