### ISSUE TITLE
[Material Editor] Math expressions

### ISSUE THREAD

**Issue by FullStack0verfl0w** [Facepunch/sbox-issues#1754]
**What can't you do?**
I want to create a material that uses two self illum masks. The first one is for parts that always glow, and the second one is for parts that glow under certain conditions. The only way I could do that is by adding mask2 to mask1 and control brightness for mask2 through C#.

**How would you like it to work?**
A texture/vector list below the main texture/vector where we can add masks and select math expression for them.
Of course, it would be awesome if we get material editor like Unreal Engine has, but I'm pretty you have to fully rework the material system for this.

**What have you tried?**
Right now I have to apply a different material with the same texture to the dynamic part to make both parts work together.

**Comment by ogniK5377** [comment]
You need to be more specific on what you need as we already have "Dynamic Expressions" where you can tie attributes to dynamic values and expressions

**Comment by FullStack0verfl0w** [comment]
> You need to be more specific on what you need as we already have "Dynamic Expressions" where you can tie attributes to dynamic values and expressions

You need to read carefully. I know about dynamic expressions, and that I can control attributes through them. I need an ability to add, multiply, etc mask2 to mask1.

**Comment by FullStack0verfl0w** [comment]
Like this.
![image](https://user-images.githubusercontent.com/36414434/163326512-51e6eaae-ca33-4d5c-b15b-633eba846f65.png)

**Comment by ogniK5377** [comment]
Is there any reason you couldn't bake these into a single texture? There's nothing dynamic about this setup

**Comment by FullStack0verfl0w** [comment]
> it would be best to create a custom shader for it
Yeah. Creating a custom shader is so much fun.

**Comment by FullStack0verfl0w** [comment]
Why closing it? This feature must be in every modern engine.

**Comment by ogniK5377** [comment]
> 

Multiple reasons:
1. "Math Expressions" are just dynamic expressions that there's full support already. It allows for dynamically setting up inputs and is passed on a per-frame basis to the current shader.
2. The use-case which you specified with your use-case is that your final material should be baked as your result is always fixed.
3. If you want dynamic per pixel inputs, you can already do this with shaders which is what they're used for. Specifying a per-pixel operation without doing it on the GPU is very silly. Like all "modern engines," they create a shader permutation using a shader graph which we already support.
4. Being sarcastic and rude usually leads to your issue being ignored as well.
