### ISSUE TITLE
Hammer crashing when trying to open a big map

### ISSUE THREAD

**Issue by DaddyFrosty** [Facepunch/sbox-issues#1756]
**Describe the bug**
Title says it

**To Reproduce**

1. Import a mesh with around 800k vertices. ( You'll have to do 100k at a time to avoid crashing ).
2. Save the map
3. Open it, boom.

**Expected behavior**
Opening

**Screenshots**

**Additional context**
2022/04/14 19:40:05.369	Hammer	Begin loading file: A:\SteamLibrary\steamapps\common\sbox\addons\legacy\maps\rust_island_2013.vmap	
2022/04/14 19:40:05.480	Engine	CBaseFileSystem::ReadToBuffer: file too large	
2022/04/14 19:40:05.480	Engine	CDataModel: Unable to open file a:\steamlibrary\steamapps\common\sbox\addons\legacy\maps\rust_island_2013.vmap	

While there are a lot of veritces and the map file is 2.4GB, I compiled a small part of the map and the resulting file size is 1/7th of the vmap file. Which means this 2.4GB map will be around 343MB this is not unreasonable for the size of this map. Please increase/fix the CBaseFileSystem limit.

**Comment by handsomematt** [comment]
This is really silly, you shouldn't have enough map meshes to exceed 2.4GB.

Terrain will be something we solve.

If you need large amounts of vertices in your maps you should be using actual models with prop_static and LODs.

**Comment by bakscratch** [comment]
Best idea is also to just split the map into separate maps and then prefab them into one big map.
