### ISSUE TITLE
Grabbing/Holding/Pickup entities/objects APIs for the pawn

### ISSUE THREAD

**Issue by Ceiridge** [Facepunch/sbox-issues#1757]
**What it should be**
Provide a simple API for the pawn to hold entities, similar to https://wiki.facepunch.com/gmod/Player:PickupObject
This already exists in Sandbox with the gravity gun: https://github.com/Facepunch/sandbox/blob/master/code/tools/GravGun.cs#L210

I believe that this is a feature that many game modes would need, so implementing an API would be useful.

**Comment by DevulTj** [comment]
This should not exist in base

**Comment by aylaylay** [comment]
Copy paste it

**Comment by Ceiridge** [comment]
That's what I have done now. Is there a guideline on what belongs into the base?
