### ISSUE TITLE
Modeldoc orthographic views don't rotate the model if you rotate using the mouse

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#1758]
**Describe the bug**
If you view your model with one of the orthographic views (Front, Left, Top etc.) and try to rotate the model using the mouse shortcut of CTRL+RMB, the lighting and background will rotate, but if you rotate using the manual "Model Rotation" slider in the ground settings, the model itself will rotate.

**To Reproduce**

1. Open a model in ModelDoc
2. In View Settings, select "Front"
3. Hold CTRL+RMB and move around
4. Alternatively, go to ground settings and use the "Model Rotation Slider"

**Expected behavior**
I don't know which of the 2 should be the expected behavior, but I'm guessing the model is supposed to be the one rotating when changing the "Model Rotation" value, even if in orthographic view from the "Front".

**Screenshots**

https://user-images.githubusercontent.com/86626409/163656937-f59e7961-749c-44bd-87ef-f89573d00e3d.mp4

In the video, you can see the values of the "Model Rotation" changing when I rotate the model using CTRL+RMB, just like it would if I were to change it manually using the slider, but the results are different, and they only sync up when I go back to perspective view and then ortho again.

**Additional context**

This isn't really that important, just wanted to let people know, feel free to screenshot 😔

**Comment by aylaylay** [comment]
This is how it behaves in normal camera mode too tho?
