### ISSUE TITLE
[Material Editor] Suppress Compilation Toggle

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1759]
**What can't you do?**

Suppress compilation of textures/Materials in the Material Editor. 

**How would you like it to work?**

To Suppress and prevent material compilation while toggled. Like in Deskjob/Dota Tools

Not Suppressed
![deskjob_9WM9Uwxgqw](https://user-images.githubusercontent.com/23345567/163684933-2d153da1-6c08-4676-9683-ab1582bba27f.png)

Suppressed
![deskjob_CUNEWRJEn0](https://user-images.githubusercontent.com/23345567/163684998-e58e9dd4-eab3-4d7b-b338-1b586c4f6e15.png)

**Comment by ogniK5377** [comment]
Is there any purpose to pausing the compilation? The only thing I could think of would be to not lag due to adding textures but we sped that up quite a bit so it's not really much of a problem now

**Comment by QuackCocaine** [comment]
Good point... though I'm curious now why valve was even added in the first place. Probably because they don't have to deal with that bogus compilation speed that you pushed to s&box a while ago.
