### ISSUE TITLE
Whitelist new C# index syntax types

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#176]
**What can't you do?**

```csharp
int[] someArray = new int[5] { 1, 2, 3, 4, 5 };
int lastElement = someArray[^1]; // lastElement = 5
```

Need the following whitelisted:

```
System.Private.CoreLib/System.Index*
System.Private.CoreLib/System.Range*
System.Private.CoreLib/System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray*
```

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
