### ISSUE TITLE
Hammer - Allow key bindings for 2D View Shading modes

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#1760]
**What can't you do?**
Switch Between 2D View Shading modes easily through a key bind

**How would you like it to work?**
Be able to assign a key bind for the function

**Additional context**
![image](https://user-images.githubusercontent.com/50308149/163686215-98d567ba-b597-49a4-8762-9674273812f8.png)

**Comment by aylaylay** [comment]
Done - enjoy
