### ISSUE TITLE
Skyboxes don't scale correctly when viewed in Source Filmmaker

### ISSUE THREAD

**Issue by ImWill0w0** [Facepunch/sbox-issues#1762]
**Describe the bug**

When you set the map for a Source Filmmaker session, the skybox doesn't scale correctly.

**To Reproduce**

Load up any map that has a skybox in Source Filmmaker

**Expected behavior**

For a map's skybox to scale appropriately and to be positioned in the right location.

**Screenshots**

![sbox-dev_LNG3O9puva](https://user-images.githubusercontent.com/28235017/164339525-570db2f4-2851-45d7-bd07-6931c4420fb3.png)

**Comment by ogniK5377** [comment]
Can we get a reproduction vmap? I have a feeling I know what's going on
