### ISSUE TITLE
ent_path_platform horizontal player movement is broken #4

### ISSUE THREAD

**Issue by AfteraOfficiel** [Facepunch/sbox-issues#1764]
**Describe the bug**

Hello, the train no longer works as it should, we pass through it, moreover, the "onpassed" action no longer work as well and If a new speed is set on a movement_path_node, this one is not taken and the train continues at the same speed
And without understanding why, after a while the train slowed down to speed 1 or 2 for no reason..

My gamemode is broken now :( 

**To Reproduce**

Create an ent_path_platform and set it to follow a path_generic that has horizontal movement.
Load the map in game and ride the platform around.

https://user-images.githubusercontent.com/99672629/164748886-c3ab9479-44fc-4a15-9dbd-0fe7319a9347.mp4

[map_platform.zip](https://github.com/Facepunch/sbox-issues/files/8542327/map_platform.zip)

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
I got a similar issue, ent_path_platform seems to ignore the speed settings alltogether, seen here:
https://streamable.com/98vj1c

**Comment by AfteraOfficiel** [comment]
> I got a similar issue, ent_path_platform seems to ignore the speed settings alltogether, seen here: https://streamable.com/98vj1c

Yes, this is one of the problems I have :/

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
> 

Seems to only happen in sandbox, try another gamemode and it should work properly. Just found out

**Comment by robotboy655** [comment]
I think some of unintended changes got uploaded to Sandbox, it should be resolved now, let me know if that is not the case.

**Comment by AfteraOfficiel** [comment]
The speed seems fixed, but we can no longer change it with the "on passed" actions on a node and we continue to pass through the model as on the video

**Comment by robotboy655** [comment]
Update on the `OnPassed` output - it should be fixed when the game next updates, and requires map recompile.

**Comment by AfteraOfficiel** [comment]
OnPassed output is fixed

but one more problem : If we hit the model we pass inside

Uploading Nouveau projet.mp4…

:

**Comment by AfteraOfficiel** [comment]
Hello, you have news about this last bug ? :S
