### ISSUE TITLE
Whitelist System.Text.UTF8Encoding

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1768]
**What can't you do?**
Using `System.Text.UTF8Encoding` to convert bytes to a string and vice-versa.

**How would you like it to work?**
Whitelisted :)

**What have you tried?**
Encoding.Unicode works, but as it's similar to `UTF-16` and I wanna save networked volume, it's not the same as `UTF-8`

**Additional context**
Used in networking as `byte[]` isn't allowed in ServerCmd

**Comment by handsomematt** [comment]
`Encoding.UTF8.GetBytes( "wanker" );` would've worked but I've whitelisted it all now.
