### ISSUE TITLE
ent_path_platform speed settings are broken

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [Facepunch/sbox-issues#1769]
**Describe the bug**
When you set an ent_path_platforms speed, it seemingly ignores that speed settings, causing it to go really slow rather than fast.

**To Reproduce**
1. Create an ent_path_platform
2. Make it follow a path_generic
3. Set the speed higher than 800
4. It refuses to go fast

**Expected behavior**
It should go faster depending on higher speed settings.

**Videos**
https://streamable.com/98vj1c

**Screenshot**
![image](https://user-images.githubusercontent.com/93285193/164895817-2df4451e-eaaa-4b31-b3ce-999f65806644.png)

**Additional context**
It seems that it's only broken in the sandbox gamemode.

**Comment by robotboy655** [comment]
I think some of unintended changes got uploaded to Sandbox, it should be resolved now, let me know if that is not the case.

**Comment by robotboy655** [comment]
Related issue: https://github.com/Facepunch/sbox-issues/issues/1764

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
Something happened and now movement seems entirely broken, uploaded a video below.
https://streamable.com/p11wvp

The ents get stuck on place but still rotate the way they should.

**Comment by bakscratch** [comment]
similar issue happening here as well.

https://user-images.githubusercontent.com/8184184/165370396-1a8b19ee-d908-49eb-97d1-1da058f6b841.mp4

**Comment by robotboy655** [comment]
This should be fixed when the game next updates.
