### ISSUE TITLE
Ability to clone or create materials based of premade materials

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#177]
**What can't you do?**
Currently, when setting dynamic expressions on a material, it applies to all meshes that material is applied to. Being able to copy a copy of the material but keep it unique would prevent this from happening.

**How would you like it to work?**
```cs
Material mat = Material.Load("materials/my_material.vmat");
Material newMaterial = mat.Clone(); // This material is now separate from mat
// OR
Material mat = Material.CreateCopy("materials/my_material.vmat", "ANewUniqueName");
Material newMaterial = Material.CreateCopy("materials/my_material.vmat", "AnotherUniqueName");
```

**What have you tried?**
Creating a separate material for every unique texture I'd like to apply.

**Additional context**
Using only a single material with different dynamic expressions:
https://user-images.githubusercontent.com/25727384/118370692-3a4d8400-b5ec-11eb-86a4-4710d6f63e5d.mp4

Using multiple materials with different dynamic expressions:
https://user-images.githubusercontent.com/25727384/118370739-6f59d680-b5ec-11eb-91cd-981ad5d2629f.mp4

**Comment by aylaylay** [comment]
`			var mat = Material.Load( "materials/blank.vmat" );
			var matCopy = mat.CreateCopy();
			matCopy.OverrideTexture( "Color", tex );`

The param names are usually things like "g_tColor", "g_tNormal" it seems to be a standard naming so you can just use "Color" and it will prepend the bullshit for you.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
