### ISSUE TITLE
ModelDoc crashes after closing a file

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [Facepunch/sbox-issues#1770]
**Describe the bug**
After you close a file in ModelDoc, the entire game crashes

**To Reproduce**

1. Edit and compile a model in ModelDoc
2. Close it
3. Watch it crash sbox
4. Error attached below

**Expected behavior**
It should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/93285193/164910900-1d62af0d-74c5-4328-a2d1-93ae38b0b727.png)

**Additional context**
This happens while having hammer open in the background, 3D view

**Comment by ogniK5377** [comment]
Cannot reproduce, please provide the model & resources you're using

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
> 

Like my entire addon folder in a zip or just the model?
