### ISSUE TITLE
Implement console command to debug lightprobe volume density

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1773]
**What can't you do?**

Debug light probe volume density with `r_light_probe_volume_debug_grid` as demonstrated in the video below in DeskJob.

**How would you like it to work?**

https://streamable.com/lhit5e

**Comment by aylaylay** [comment]
You now have all the r_light_probe_volume_debug_grid* convars that deskjob has - enjoy

**Comment by QuackCocaine** [comment]
Works as expected, Thanks for the addition.
