### ISSUE TITLE
Unable to click anything after Toggling console in Fullscreen mode in Dev-Tools

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#1774]
**Describe the bug**
if you're in fullscreen and press ` when in dev tools and click anywhere it puts you back into full screen

**To Reproduce**

1. Load up sbox-dev
2. go fullscreen 
3. press `
4. try to click on something 

**Expected behavior**
Should allow you to click on the item but instead it puts you back into fullscreen

**Comment by KayaDLX** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/1611
