### ISSUE TITLE
Assets (vmat, vtex, vmdl) do not compile outside sbox-dev / -tools

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1777]
**Describe the bug**
Assets (vmat, vtex, vmdl) do not compile if you're not using sbox-dev / -tools option on sbox startup.

If this is intended to avoid compiling assets for the default user, would be cool to know. Then, I'd avoid fetching the repo directly from GitHub and instead offering a compiled version.

**To Reproduce**
1. Remove compiled assets
2. Start sbox without -tools option
3. Try to use an asset which you removed the compiled version before

**Expected behavior**
Same as in -tools mode

**Comment by aylaylay** [comment]
This is how it's meant to work
