### ISSUE TITLE
Editor will crash when clicking on a vsnd sound file within the Assets Browser

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1778]
**Describe the bug**

Upon clicking on a `vsnd` sound file within the `Assets Browser`  the editor will freeze and an error (shown below) will pop up then crash upon clicking ok.

![ApplicationFrameHost_6fWGBBvR1Q](https://user-images.githubusercontent.com/23345567/165665563-88c1fba3-dbb3-43ab-b0ae-709ca320a53d.png)

**To Reproduce**

1. Go to the `Assets Browser`.
2. Click on a `vsnd` sound file within your addon folder structure and not in `@recents`.
3. Game will crash along with an error.

**Expected behavior**

To preview the sound file.

**Video**

https://user-images.githubusercontent.com/23345567/165665428-32775d17-d134-49e0-9a3b-3490e15e36f3.mp4

**Comment by QuackCocaine** [comment]
Clicking on the vsnd file plays the sound as it should now without a crash. however, if you rapidly click between the .sound and .vsnd the editor will eventually crash. Leaving behind some qt related lines in the log below

**Log :**
[qt errors.txt](https://github.com/Facepunch/sbox-issues/files/8590951/qt.errors.txt)

**Comment by garrynewman** [comment]
Thanks, I have fix for this on my branch, will be fixed when I merge
