### ISSUE TITLE
Ability to use resourcecompiler.exe to compile maps without a gpu or integrated graphics

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#178]
**What can't you do?**
Compile maps on a dedicated server vm without a gpu or integrated graphics, it just crashes immediately, even when run via commandline/powershell.

**How would you like it to work?**
Being able to compile maps via commandline on a dedicated machine, similar to source 1 compilers.

**What have you tried?**
Launching tools or running resourcecompiler.exe via commandline.

**Comment by Moonded** [comment]
**Addition:** Apparently resourcecompile.exe itself ain't using a gpu but vrad3 for work flow offload as seen by running resourcecompile.exe via cmd line and then following vrad3s activity.

**Comment by Jake-Rich** [comment]
Using the -dx9 switch will crash with or without a gpu present. The -dx11 switch will work with a gpu present but will crash without a gpu present.

I have tried all switches I could find: -novid, -nowindow, -textmode, -novr, etc etc. Have tried on linux under wine & on a cloud windows server and same result either way.
