### ISSUE TITLE
Sbox-Dev Taskbar Tray Icon Overrides Other Existing Tray Icon

### ISSUE THREAD

**Issue by Ceiridge** [Facepunch/sbox-issues#1780]
**Describe the bug**
When starting sbox-dev, a tray icon is created in the taskbar. It hides another tray icon (in my case Everything search), which can be annoying.

**To Reproduce**
Start sbox-dev

**Expected behavior**
A tray icon that does not hide others or an option to disable the tray icon (it has no purpose at the moment anyway).

**Screenshots**
_Before_
![before](https://user-images.githubusercontent.com/40047520/166113159-5a8cbd4b-bc68-4000-99d1-eb30c958fe26.png)
_After_
![after](https://user-images.githubusercontent.com/40047520/166113161-bcf69ab0-a70c-444e-b6d8-945c9686362c.png)
(The Everything search icon completely disappears and reappears once sbox-dev is closed. It is not pushed to the second row of icons.)

**Comment by VCSoldier** [comment]
This feels more like a windows issue than an sbox issue, but i could be wrong

**Comment by Ceiridge** [comment]
I have 23 tray icons (without the arrow, so I can see them all at once) and there sometimes are slightly broken, for example when an application exits without removing the tray icon first, it stays there until I move the mouse over it or if I restart explorer, some icons do not appear anymore.
But this issue has not occurred before and always and only happens with the s&box tray icon.
Until it is fixed (or maybe completely removed?), I can manually disable the tray icon of s&box in the Windows settings. It's useless at the moment anyway.

**Comment by xezno** [comment]
I believe the tray icon is used for Windows toast notifications (used for tools compile errors etc), so removal isn't really an option. If it's causing an issue you can just force drag it into your expanded tray and it should stay there:

https://user-images.githubusercontent.com/12881812/166167004-30810eef-4663-4b0e-8079-b3fb9bd8e725.mp4

You can also hide it in "Notification Area Icons", which you can access by right clicking the downwards arrow and clicking "Customize notification icons":
![image](https://user-images.githubusercontent.com/12881812/166166993-e6d71583-eace-42dd-940c-44814e2d67a9.png)

**Comment by Ceiridge** [comment]
I have disabled the tray icon expander (I have *Always show all icons* enabled), as I want to see all tray icons all the time, so I can't disable it specifically.
It's still a strange bug that a tray icon replaces another one. I'm not sure if this happens to everyone.
At the moment it doesn't annoy me that much for me to come up with a solution (for example it could probably still be hidden with a registry key or something)

**Comment by handsomematt** [comment]
there's nothing being done specifically for this, it's just a standard tray icon
