### ISSUE TITLE
Generic Game Data Particle does not render on entities using Hammer.EditorModel

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#1783]
**Describe the bug**
As the title suggets, you create a model with the GenericGameData: particle node as such:
![image](https://user-images.githubusercontent.com/7847372/166268320-bfade4bf-90d9-413f-9968-62959fac4a76.png)

You can see the particle effect in model doc and in game, however, it does not appear in hammer when you create an instance of the entity which is set to this model.

**To Reproduce**

1. Add particle node to model.
2. Use the model as the argument for the Hammer.EditorModel attribute
3. Particle is not visible in hammer.

**Expected behavior**
Particle is visible.

**Additional context**
It's possible this isn't really a bug but it would be a nice feature either way 👍

**Comment by robotboy655** [comment]
Added.

![image](https://user-images.githubusercontent.com/3299036/166718425-96c21c4b-2c84-4f20-8709-4f638a096862.png)

**Comment by Fortune117** [comment]
Works perfectly 👌
