### ISSUE TITLE
Material editor crashing sbox on saving new material

### ISSUE THREAD

**Issue by TheGetHuber** [Facepunch/sbox-issues#1785]
**Describe the bug**
Material editor is crashing sbox on saving new material to whatever addon folder.

**To Reproduce**

1. Go to 'Material Editor'
2. Click on 'New'
3. Change nothing
4. Click on "Save"
5. Give it random name
6. Save the material in whatever folder
7. Crash

**Expected behavior**
To save new material without any crash.

**Screenshots**
.vmat file that was created
![изображение](https://user-images.githubusercontent.com/69822538/166439975-4d96346a-b7a4-4df4-bb75-af6884c09cc7.png)
video of me doing all of this
https://user-images.githubusercontent.com/69822538/166440675-446895f7-8cf9-4ffd-8cdf-d389a4194a37.mp4

**Additional context**
When i tried to compile the .vmat file using "rebuild_all.bat" this what it gave to me:
```
//---------------------------------------------------


---------
// Valve Content Builder ( Build : May  3 2022 )
// Copyright (c) Valve Corporation, All rights reserved.
//------------------------------------------------------------

Command Line:
  ..\..\bin\win64\contentbuilder.exe -b -o -nop4 -v -f

Working Directory: G:\Steam\steamapps\common\sbox\addons\koth_sawmill
Mod:               core @ "G:\Steam\steamapps\common\sbox\core"
Operation:         Force-building content and deleting orphans
Verbosity: high
Building:          All
Excluding:         None

Initializing app systems...
Done in 0.10 seconds.
Finalizing build list...
1 assets need to be built


Error: Failed to compile materials/test_mat.vmat
--------------------------- OUTPUT ---------------------------
- addons\koth_sawmill\materials\test_mat.vmat
  +- addons\koth_sawmill\materials\default\default_normal_tga_7be61377.generated.vtex


Exited with code -1073741795.
Command Line: resourcecompiler.exe -f -dxwarp -testmode -ignorecontentasserts -unbufferedio -useforcedirtyfile -i G:/Steam/steamapps/common/sbox/addons/koth_sawmill/materials/test_mat.vmat -outroot G:\Steam\steamapps\common\sbox\.source2\contentbuild_0\1ABC5132_0\game -threads 1
Run time: 0m:3s
--------------------------------------------------------------


No files found to merge from "G:\Steam\steamapps\common\sbox\.source2\contentbuild_0\1ABC5132_0\game"!
Merging compile results: 1/1 (100.0%) in 0m:0s
Deleting temp files...

The following assets failed to compile:
  materials/test_mat.vmat


Finished - 0 OK - 1 FAIL - 0m:4s
```

**Comment by bakscratch** [comment]
Where are you getting VR Simple from? It doesn't seem to appear in the shader list.
<img width="525" alt="sbox_MnZS4mB2o8" src="https://user-images.githubusercontent.com/8184184/166441367-7c117d99-c6e3-48ee-8de6-035f6e42e23a.png">

**Comment by TheGetHuber** [comment]
material editor giving it by default to any material that i made
no mater what shader u use tho

**Comment by robotboy655** [comment]
I cannot reproduce this issue either, not on my build, not on the Steam build.

**Comment by TheGetHuber** [comment]
i can upload my sbox on google drive. so maybe you could reproduce all of this

**Comment by handsomematt** [comment]
is koth_sawmill an addon you've added via the addon manager with a .addon file?

**Comment by TheGetHuber** [comment]
yes i do

**Comment by TheGetHuber** [comment]
i got completely disappointed by this freaking error. god damn sbox trying to use default textures (like color, normal and ect.) from a folder named "default" thats not exists in the addon matterial folder. it doesnt trying to use them from "base" folder. f*** it, ill just delete it and wait couple of monthes till this bug will disappear
