### ISSUE TITLE
Hammer - Crashing when reloading a vmap from disk with unsaved changes

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1788]
**Describe the bug**

Crashing when attempting to reload a map with unsaved changes from disk after selecting `Yes - Disregard and reload from disk`

**To Reproduce**

1. Open a map place an object and save then change something in the map.
2. Click on `File` then `Reload From Disk`.
3. Click on `Yes - Disregard and reload from disk`.
4. Game will pause for a few seconds then crash producing a minidump.

**Expected behavior**

Reload map from disk without crashing.

**Video**

https://user-images.githubusercontent.com/23345567/166490053-db10bd4f-d732-412f-a9e5-1b5cd05dd41a.mp4

**Additional context**

_Mini-Dump_

[sbox-dev_2022_0503_115221_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/8611824/sbox-dev_2022_0503_115221_0_accessviolation.zip)

**Comment by aylaylay** [comment]
Should be fixed now - enjoy

**Comment by QuackCocaine** [comment]
Works as it should now, Thanks!
