### ISSUE TITLE
[VR] Resolution/Supersampling can't be changed while game is running

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#1789]
**Describe the bug**
The supersampling/resolution value of the game can't be changed while the game is running. If you change the supersampling value while in game, it must be restarted fully for the new resolution to take effect.

**To Reproduce**

1. Open sbox in VR and enter a VR gamemode (I tested with Terry/Squid Game
2. Go to SteamVR's settings, go to the "Video" section, and change the supersampling percentage there (I set it to 20%)
3. Observe lack of change in resolution
4. Close and re-open game, open a gamemode, and see the new resolution

**Expected behavior**
The resolution should be able to be changed at runtime.

**Comment by handsomematt** [comment]
I can't see a simple way to do this with OpenVR (the call is expensive and there seem to be no events for it), are there any other games / engines that actually behave properly with setting at runtime?

**Comment by walllable** [comment]
Unity games running through OpenVR seem to be able to do so, but I haven't seen other engines (UE4, Serious Engine 4, whatever engine Euro Truck Sim 2 runs on) able to do it. I noticed that there's a way to disable Alyx's auto-resolution system (blog post about it [here](https://petrakeas.medium.com/half-life-alyx-performance-analysis-or-why-low-graphic-settings-produce-a-sharper-image-4d17fb8c19bb)) so I'll see if it's able to adjust resolution on the fly to see if it's an sbox-specific problem.
It could potentially be a good idea to implement this auto-resolution system though, so that the user doesn't have to worry about adjusting the resolution themselves if they're getting GPU limited.

**Comment by walllable** [comment]
Seems that Alyx only checks SteamVR's resolution when it's started up as well, then uses that as its reference for the auto-fidelity stuff as mentioned in the blog post. I'll close this issue and make a new one for the auto-resolution system.
