### ISSUE TITLE
Calling a ClientRpc in Spawn doesn't work on an Entity, but does on a ModelEntity

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#179]
**Describe the bug**
When calling a ClientRpc from the Spawn method of an Entity, it will not execute on the client. However, if the entity inherits from ModelEntity instead, the ClientRpc will execute as expected.

**To Reproduce**
Create the following entity on the server. The RPC will **not** execute upon spawning the entity. Then set the entity to inherit from ```ModelEntity```, spawn it again, and "RPC Success" should be logged as intended.
```
partial class RpcTest : Entity
{
	public override void Spawn()
	{
		base.Spawn();
		Log.Info("Sending RPC from server");
		doSomething();
	}

	[ClientRpc]
	private void doSomething()
	{
		Log.Info("RPC Success");
	}
}
```

**Expected behavior**
The ClientRpc should execute in both cases, no matter the specific type of entity that is used.

**Comment by DaddyFrosty** [comment]
+1 Please fix this
