### ISSUE TITLE
[VR] - Menu overlay steals input focus from other overlay applications

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#1792]
**Describe the bug**
When s&box's menu overlay is displayed in SteamVR, other overlay applications such at OVR Toolkit and OVR Advanced Settings cannot be interacted with. Specifically in OVR Toolkit's case, pulling the trigger can't activate any buttons or interact with the desktop, and squeezing the grips doesn't hide/unhide unpinned windows. In OVR Advanced Settings case, the custom bind I set for offsetting my playspace also can't be activated This doesn't seem to happen after some time during loading - potentially because it isn't polling for input or something once it reaches a particular stage?
Once I'm loaded into a game, this issue doesn't apply.

**To Reproduce**

1. Open an overlay application such as OVR Toolkit (Or OVR advanced settings if you don't wanna pay for something)
2. Open s&box in VR mode
3. Attempt to use an overlay's functions while s&box's menu overlay is displayed

**Expected behavior**
s&box shouldn't conflict with other overlays' inputs.

**Screenshots**
SteamVR crashed during the recording, but it should get the point across. A [separate bug](https://github.com/Facepunch/sbox-issues/issues/1793) involving the VR display mirror is also shown.
https://files.catbox.moe/z6se5r.mp4

**Additional context**
If you want to test with OVR Advanced Settings, open the SteamVR overlay, access OVRAS by clicking its button on the toolbar at the bottom, go to Motion on the sidebar to the left, and select "Left Hand" under "Space Drag" - Then apply the binding I've shown in the video. To reset the offset, open OVRAS, go to Motion on the sidebar, then click on "Reset" You can also bind "Reset Offets" to another button, I think this is shown in the video as well. I am running an older version of OVRAS, so the Steam version may have some changes I'm not aware about.

**Comment by xezno** [comment]
We use a steamvr overlay to render and let you interact with our menu in VR - to my knowledge we unfortunately have zero control over how SteamVR handles inputs and focus when that overlay is visible.

We will eventually move over to just rendering it all with our own solution with our own input stuff to prevent this, we'll most likely do it when we move the VR menu over to a nice custom 3D scene.
