### ISSUE TITLE
[VR] - Desktop mirror is displayed incorrectly, based on SteamVR's supersampling resolution

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#1793]
**Describe the bug**
s&box's desktop mirror for the VR view is not centered on the player's left eye. The amount it's screwed up seems to be linked to SteamVR's resolution.

**To Reproduce**

1. Open s&box in VR mode
2. Enter a gamemode
3. Observe the incorrect desktop mirror
4. Change SteamVR's resolution in its options (SteamVR settings > Video > Render Resolution,) restart the game, re-enter the gamemode, and observe the different incorrect-ness

**Expected behavior**
The mirror should be centered on the player's left eye, independently of SteamVR's resolution. It would also be nice to be able to change which eye is mirrored, but that's unrelated...

**Screenshots**
Supersampling set to 20%:
![image](https://user-images.githubusercontent.com/10066958/166572088-321a6323-1cfe-416f-801d-a05982359e74.png)
Supersampling set to 60%:
![image](https://user-images.githubusercontent.com/10066958/166571593-06200097-c901-4e3a-97b7-c8f4057bd7f1.png)
Supersampling set to 100%:
![image](https://user-images.githubusercontent.com/10066958/166571743-cecf9903-b344-41ec-88cf-a205b3eae802.png)
Supersampling set to 150%:
![image](https://user-images.githubusercontent.com/10066958/166571925-610d22d1-e5ff-4c9b-9e3e-d7ba10c61335.png)

**Comment by handsomematt** [comment]
This should be fixed. There's some convars that control the behavior:

* vr_companion_window_zoom 0/1 - default 1, when turned off simply blits each eye to the screen
* vr_companion_window_zoom_level - default 1.25, controls how much the displayed eye is zoomed in
* vr_spectator_show_left_eye 0/1 - default 0 (right eye)

**Comment by walllable** [comment]
Awesome, I appreciate the convars. I'll test this out later.

**Comment by walllable** [comment]
Tested at 20% and 36% render resolutions, can confirm it's fixed on my end.
