### ISSUE TITLE
Hammer - Allow Physics Tool to work on prop_physics

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#1794]
**What can't you do?**
I am unable to use the Physics Tool in hammer to position prop_physics entities.

**How would you like it to work?**
Same way it works with prop_static.

**What have you tried?**
I tried converting my entity from prop_static to prop_physics after positioning it, but it reset all the bone positions of the ragdoll.

**Comment by bakscratch** [comment]
https://files.facepunch.com/louie/1b0411b1/Hammer%202022-05-04%2009-07-00.mp4

Seems to work fine, what model are you trying to simulate? I assume it is an model that isn't using a hull for its collision.

**Comment by Fortune117** [comment]
I'm using "models/sbox_props/office_chair/office_chair.vmdl" and a custom model I've got. Neither of them seem to work for me, I'll check if other models do.

**Comment by aylaylay** [comment]
physics tool doesn't allow you to simulate prop_physics that have multiple bodies, this is probably because when the game starts, the ragdoll is going to simulate from the bindpose and not where you simulated it to in editor. So I think this is all working as it should.

**Comment by aylaylay** [comment]
You're in luck, I added support for this on prop_physics - let me know if there's any issue

**Comment by Fortune117** [comment]
Works as expected, thanks 👍
