### ISSUE TITLE
Unable to use different render target sizes for ScenePortals

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#1796]
**Describe the bug**
setting a ScenePortal's rtSize to something that isn't 512 in the constructor causes the game to spam this error:
`Error allocating render target binding! Different render target dimensions/MSAA assigned from the depth target! Main: 1024x1024, Depth: 512x512`

**To Reproduce**
Create a ScenePortal with an rtSize that is not 512x512.

**Expected behavior**
ScenePortal renders correctly with different render target sizes.

**Comment by ogniK5377** [comment]
Should be fixed next update 👍
