### ISSUE TITLE
modular fences aren't modular

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#18]
fences, kerbs, and walls are on unity cm grid, not source grid.
They're 3 meters long instead of 128 units, so they don't snap to the grid and are not modular.
![image](https://user-images.githubusercontent.com/39461072/115943242-5be79f80-a474-11eb-9890-87e06333c742.png)

They should be resized to 128 long and probably renamed to reflect source grid (ex. wall_64_128 instead of wall_125_300)

If resize per axis is added to modeldoc, that can just be applied to all of these and fix it instantly.

**Comment by garrynewman** [comment]
I think if this is going to be an issue we're better off removing them and re-doing them properly.
