### ISSUE TITLE
Animgraph - Crashing when you revert connections using groups

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1801]
**Describe the bug**

https://user-images.githubusercontent.com/40291120/167140505-024f6b25-cd9d-45c5-a713-c66db5f86aee.mp4

**To Reproduce**

Just ctrl+z when many nodes are connected inside the group

**Comment by aylaylay** [comment]
Can you replicate this with as less nodes as possible so I can recreate the same crash

**Comment by aylaylay** [comment]
Nevermind, I got one

**Comment by aylaylay** [comment]
should be fixed, try and break it pls
