### ISSUE TITLE
Assorted Missing Hammer entities to be remade in C#

### ISSUE THREAD

**Issue by Tones3D** [Facepunch/sbox-issues#1805]
I know gvarados has already covered a few of the big ones,
but my current map really relies on trigger_push to move the player on a conveyor belt

Here's a few entities I'm really missing:

- [ ] env_fire
- [ ] trigger_push
- [ ] func_dustmotes
- [ ] move_rope
- [ ] point_message
- [ ] env_laser
- [ ] env_smokestack

I guess env_fire isn't entirely necessary with info_particle_system existing, but it is nice that it adds damage automatically, and is just a simple place-and-forget fire.

Also, huge props for adding point_camera and func_monitor already. placing camera systems in maps is one of my favorite things to do.
Thank you!

**Comment by ogniK5377** [comment]
What makes smokestack and dustmotes different from a particle system

**Comment by robotboy655** [comment]
Same goes for move_rope

**Comment by DoctorGurke** [comment]
Fire and laser just have a damage component to them that could be replicated manually but are otherwise also just particles

**Comment by QuackCocaine** [comment]
Func_dustmotes can just be replaced with func_precip pretty much

**Comment by Tones3D** [comment]
How would move_rope be made with a particle system?
It kinda needs two points.

I didn't consider that most of these were solved by particle systems, mainly just env_fire
for real though, I gotta have that trigger_push

**Comment by DoctorGurke** [comment]
You use control points for the rope ends

**Comment by robotboy655** [comment]
You can use the Path Tool:
![image](https://user-images.githubusercontent.com/3299036/167293274-6f3ea9d6-c6a4-458d-a566-673e9c689358.png)

**Comment by handsomematt** [comment]
Not gonna remake source 1 things just because. All of this stuff can already be done better.
