### ISSUE TITLE
Animgraph - You don't get errors/warnings inside the groups

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1806]
**Describe the bug**

https://user-images.githubusercontent.com/40291120/167269416-9a65be0d-297a-4302-8f2f-427cc72bc1bc.mp4

**Comment by aylaylay** [comment]
what warning/error should be happening?

**Comment by KaesarZZ** [comment]
Basically the same as if I take the nodes out of the group.

**Comment by aylaylay** [comment]
Which are what? I don't know what nodes you're using and how they're set up

**Comment by KaesarZZ** [comment]
It's not something specific, any wrong node inside the group ignores it even if the graph is totally broken. 

https://user-images.githubusercontent.com/40291120/167270094-7d461ecb-ecd9-4586-94e0-63166b54b815.mp4

**Comment by aylaylay** [comment]
should work now

**Comment by KaesarZZ** [comment]
Re-opening this, when an animation is missing in the model, normally you click on the warning and the camera focuses on the specific node, if the "missing animation node" is inside the group you click on the warning and nothing happens.

**Comment by KaesarZZ** [comment]
And it's not specific of "Missing animation" warning, it's happening with every warning.

**Comment by aylaylay** [comment]
should work now

**Comment by KaesarZZ** [comment]
Perfect
