### ISSUE TITLE
Closing in-game console as the game loading screen fades will stop the animation

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#1809]
**Describe the bug**
Opening/restarting a game with the in-game (F1) console open and then closing it as the menu fades away will "burn it" in your screen. I have to restart again to remove the overlay.

**To Reproduce**

1. Open the in-game console
2. Start a gamemode
3. As the loading screen fades, close the console
3a. You can spam the console if you have trouble timing it

**Screenshots**

https://user-images.githubusercontent.com/59583743/167312463-bfc9e23f-4382-4f35-bc38-7bacefdf5360.mp4

Sometimes it completely blocks the screen

![image](https://user-images.githubusercontent.com/59583743/167312548-eee355b5-56ab-4071-81a2-119abbf2e06e.png)

This is a problem whenever I restart a gamemode via the console, happens almost everytime so I had to set a keybind to do it without opening it.

**Comment by yuberee** [comment]
![image](https://user-images.githubusercontent.com/59583743/167670386-60a2bd0b-d281-4b8c-98ca-185bbb63d661.png)

This seems to happen on any panel with a fading animation.

**Comment by cr4yz** [comment]
This should be fixed in the next build, please lemme know if it gives you anymore trouble

**Comment by yuberee** [comment]
Doesn't happen anymore in any of the examples I've showed indeed. :+1:
