### ISSUE TITLE
Way to disable in-game preview lighting warning

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#181]
**What can't you do?**

Baking lightmaps prevents a map from becoming totally dark when the light_environment is rotated for night time, could be ambient lighting or something but it's baked in when lightmaps are enabled.

But it's required to get rid of the message on screen saying to bake lighting.

**How would you like it to work?**

Few options:
Property in map to mark dynamic lighting, don't show the warning
Check if light_environment is set to per-pixel & indirect lighting None, don't show warning
Figure out what baked data is causing map to stay lit, do something about it

**What have you tried?**

In Hammer I set Direct Lighting to Per-Pixel and Indirect Lighting to None.
Tried setting Ambient & Sky Ambient Bounce colors to black
Disabled my env_cubemap

Haven't found a way to bake lighting to disable the message _and_ have totally dark nights.

https://i.imgur.com/D4ft3gc.jpg

**Comment by aylaylay** [comment]
I have changed it to not require baked lighting if lightmap building is disabled. This is usually set per s2 game but here I don't see why we'd ever require baked lighting. If the user doesn't want fully dynamic lighting, that's up to them.

Let me know if there's any issues doing this or any other warnings that pop up.

**Comment by cr4yz** [comment]
The warning is gone, haven't noticed any side effects yet.  Thanks!
