### ISSUE TITLE
Expose more Post Processing Effects

### ISSUE THREAD

**Issue by PatrickJnr** [Facepunch/sbox-issues#1810]
**What can't you do?**
Add things like Chromatic Aberration, Motion Blur and Film Grain to a Post Processer.

**How would you like it to work?**
The same way, we usually add Post Processing.

**What have you tried?**
Nothing.

**Additional context**
Just want extra Post Processing stuffs.

**Comment by Fortune117** [comment]
The standard post processor already includes film grain and motion blur, unless I'm misunderstanding what you mean.

**Comment by ogniK5377** [comment]
https://sbox.facepunch.com/news/november2021#PostProcessing

**Comment by Fortune117** [comment]
There's an entity in hammer that allows you to add post processing to a volume. I don't know much more about it other than that it exists though.
