### ISSUE TITLE
Input broken in tools mode

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#1811]
Tools mode doesn't take any inputs into the game window other than mouse clicks.
core/cfg wipe has been tried to no avail. They keys are bound and the game works fine in non tools mode

the bug isn't reproducible as far as I know

**Comment by Xenthio** [comment]
I've only noticed the issue today so I assume it became a thing around today (9/5/2022)

**Comment by DoctorGurke** [comment]
It should be core/cfg

**Comment by Xenthio** [comment]
> It should be core/cfg

woops typo, I meant core/cfg

**Comment by walllable** [comment]
Here's a video demonstration of the issue:
https://files.catbox.moe/a70lv2.mp4

**Comment by handsomematt** [comment]
Looks like it was caused from borderless window, thanks Rifter for finding that out.
Should be fixed now, let me know if it's still fucked in some way though.
