### ISSUE TITLE
WorldPanels CSS rotations do not work

### ISSUE THREAD

**Issue by suiramdev** [Facepunch/sbox-issues#1812]
**Describe the bug**
The CSS attribute `rotate()` or `translate()` does not work on world panels.

**To Reproduce**
1. Create a world panel with a template and a stylesheet
2. Design it, and try to add a `transform: rotate()` to it

**Expected behavior**
The panel should be rotated or translated.

**Screenshots**
I personally have a world panel, with its template and stylesheet.
In it, you'll find:
![image](https://user-images.githubusercontent.com/71449142/167422169-a6bc9b9b-e822-4a62-83af-bf4b20aa8910.png)
![image](https://user-images.githubusercontent.com/71449142/167422132-3e8065ed-5576-4490-8309-bf178254cca0.png)
And that gives:
![image](https://user-images.githubusercontent.com/71449142/167422263-f9155959-4669-4048-bb5c-2b198c0dd673.png)

**Comment by Gmod4phun** [comment]
Can confirm, this is still an issue.

**Comment by notmatical** [comment]
Still an issue, would love to have the ability to apply transforms to world panels.

**Comment by ogniK5377** [comment]
Should be fixed next update
