### ISSUE TITLE
AssetSystem hangs for 80~ seconds on first launch of game since PC start

### ISSUE THREAD

**Issue by Ephememory** [Facepunch/sbox-issues#1815]
**EDIT: This may be actually upon the first launch of the game since system start instead? I'm almost sure of that since, there's always a steam update for s&box when I first start my PC.**

### Describe the bug

``` 
03:23:39   AssetSystem pruned 7662 stale assets
03:24:53   AssetSystem initialized in 74.98 seconds. [0.03 load, 0.07 scan, 74.84 dependencies, 0.01 save]
```

Is this the normal/expected behaviour? I assumed it was just a side effect of some changes to the asset system, in case it isn't, here's the bug report.

### To Reproduce
1. Start s&box for the first time since booting your system.
2. Launch s&box editor (-tools)
3. Editor hangs for an unusually long time, around 60 seconds minimum. (Maybe this scales with number of assets in each addon?)

### Expected behavior

I have no idea if this is intentional, I would assume not. I would *like* the editor to not hang for 1-2 minutes on a launch but this could easily be an early access issue and thus, not a bug.

### Additional context

Running on Windows 10 with s&box installed on an SSD.

**Comment by Ephememory** [comment]
I have no idea why, I even checked the commits page to check if a change was relevant to this but, today the asset system loaded in 3 seconds upon being launched for the first time since machine start AND after a receiving a game update. I don't recall this happening until today, but again, I didn't see a commit that mentioned startup times or asset system loading times.

**Comment by Adesii** [comment]
the commit that fixed the long loading times was on the 11/05/2022.
the .source2 folder isn't uploaded with game updates anymore, therefore should fix the long startup times.

**Comment by Ephememory** [comment]
> the commit that fixed the long loading times was on the 11/05/2022. the .source2 folder isn't uploaded with game updates anymore, therefore should fix the long startup times.

I did see that one a couple days ago, and tested startup times that day and it was still slow.

**Comment by Adesii** [comment]
it would have been slow the first time. since it would still invalidate the cache once. any subsequent ones are faster. And it shouldn't overwrite stuff inside it anymore. so it shouldn't happen anymore, to the same extend.

**Comment by Ephememory** [comment]
> it would have been slow the first time. since it would still invalidate the cache once. any subsequent ones are faster. And it shouldn't overwrite stuff inside it anymore. so it shouldn't happen anymore, to the same extend.

Duh, you're right. 🤦 I think I ran it the day of that commit, but not yesterday, so I guess "almost without fail" was just vague enough. I think its safe to say this is fixed then.
