### ISSUE TITLE
ent_path_platform werido movement

### ISSUE THREAD

**Issue by KETALss** [Facepunch/sbox-issues#1817]
### Describe the bug

ent_path_platforms spins 2x 180 degrees when end action is set on "reverse direction" and "rotate alongside path is set" 
![image](https://user-images.githubusercontent.com/81901907/167646339-9b41e312-331d-4d48-b353-9d4d9b603f1b.png)

### To Reproduce

ent_path_platform with paramentrs described above; not looped movement_path 

### Expected behavior

reverse direction with no rotation

### Media/Files

https://user-images.githubusercontent.com/81901907/167649053-9af51051-efe6-46ae-8e72-7fe932eb9c7c.mp4

**Comment by robotboy655** [comment]
This should be fixed.
