### ISSUE TITLE
SFM Render Corrupts on Output

### ISSUE THREAD

**Issue by Pacific939** [Facepunch/sbox-issues#1819]
### Describe the bug

When I try to render a video in the SFM using the Movie/MP4 option, it always ends up like this in the output, the video size is zero and it failed to open the file

### To Reproduce

1. I tried reproducing this error by going to an existing project and creating a new project
2. going to export > movie
3. clicking export movie
4. and waiting until both projects finished rendering, both renders still failed, and created the file with zero bytes

### Expected behavior

what should be happening is when the video file is rendered, it should open normally, and should not look corrupted

### Media/Files

![Screenshot 2022-05-10 160830](https://user-images.githubusercontent.com/93893876/167717979-e594c41b-68c8-4fb0-8b0b-8cce1db8c99e.png)
![Screenshot 2022-05-10 160912](https://user-images.githubusercontent.com/93893876/167718005-c0c9bcd2-af7b-4c64-a073-2c814ed67919.png)

### Additional context

I'm running on Windows 11 btw, PC Specs are

NVIDIA GeForce GTX 1660 Ti GPU
Intel Core i7-10700F CPU @ 2.90GHz
16 GB Of Ram

I am using VLC Media Encoder to view my clips

And also if your wondering why the filepath in that error says Aperture Desk Job and not S&Box, it’s because I made the folder path go to there for my renders not inside S&Box

**Comment by aylaylay** [comment]
to be expected, SFM wont be worked on any time soon

**Comment by Pacific939** [comment]
darn
