### ISSUE TITLE
Animgraph - Crashing previewing Blend2D if you disable/remove ExtractMotion

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1822]
### Describe the bug

I just found it randomly adding the treadmill in the playermodel, quite specific but yeah. 

If you disable "ExtractMotion" in some animation while you're previewing the Blend2D and you compile the model it crashes. 

### To Reproduce

Explained in the video. 

### Expected behavior

Fix the crash.

### Media/Files

https://user-images.githubusercontent.com/40291120/167870006-e9921bc2-69b5-4078-8e96-bf18bbd0934b.mp4

**Comment by aylaylay** [comment]
Should be fixed now
