### ISSUE TITLE
Make CheckJumpButton protected virtual in WalkController

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#183]
**What can't you do?**
Disable jumping in WalkController

**How would you like it to work?**
I want to derive my controller from WalkController but disable jumping

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
