### ISSUE TITLE
Implement CSS currentColor for UI

### ISSUE THREAD

**Issue by jep-a** [Facepunch/sbox-issues#1832]
### For?

S&Box

### What can't you do?

I'm unable to reference the current color in other css properties like border or background like with CSS's currentColor value

### How would you like it to work?

I want it to work by being able to set a color's value to currentColor and it should reference our element's current color.

### Additional context

**[CSS Tricks - currentColor Summary](https://css-tricks.com/currentcolor/)**
**[W3 Spec](https://www.w3.org/TR/css-color-3/#currentcolor)**

**Comment by xezno** [comment]
How useful is this, it seems pretty niche, what's the benefit to this over just using a SCSS variable?

**Comment by jep-a** [comment]
@xezno 
> How useful is this, it seems pretty niche, what's the benefit to this over just using a SCSS variable?

It lets us get whatever the current 'color' property is set as, usually from the parent

```html
<div style="color: red;">
  <div style="border-right: 1px solid currentColor"/>
</div>
```

SCSS variables are static and don't let you grab what the actual current 'color' is

**Comment by xezno** [comment]
Not seeing a solid use-case for this outside of svg fills, which we don't support as we don't have inline svg support. If you really want to do that anyway you already can through a mask.
