### ISSUE TITLE
Changing resolution scale different to Native causes image glitches

### ISSUE THREAD

**Issue by gusdleon** [Facepunch/sbox-issues#1833]
### Describe the bug

Changing the Resolution Scale to anything different to the (Native) setting, will result in weird reflections and some other unexpected behavior in different view modes like `vis_debug_show`

### To Reproduce

1. Go to settings > video 
2. Change the Resolution Scale setting to anything different to the (Native) one
3. Open Construct (or any map with reflective surfaces or water)

### Expected behavior

that... (idk.. "overlay") should not interfere with the rendering of the image

### Example 1
Native
![image](https://user-images.githubusercontent.com/3170940/168452393-402a0dda-720b-48f2-927f-08832ca963b7.png)
Ultra Quality
![image](https://user-images.githubusercontent.com/3170940/168452402-e9bace2d-92fe-468d-afc8-08e3fa75d85c.png)

### Example 2
Native
![image](https://user-images.githubusercontent.com/3170940/168452424-442d9cd0-b931-4dc6-8392-7fe4bae144b8.png)
Ultra Quality
![image](https://user-images.githubusercontent.com/3170940/168452436-a7573c79-7777-4c18-bcac-6218358b35f5.png)
Performance
![image](https://user-images.githubusercontent.com/3170940/168452444-bd4859ac-543a-4e41-a55c-2424e52b28ce.png)

### Example 4
Native
![image](https://user-images.githubusercontent.com/3170940/168452517-2704c850-0d10-4538-8790-0117de41370b.png)
Performance
![image](https://user-images.githubusercontent.com/3170940/168452511-8ae65964-db00-4a90-9c9a-366afb5abcc5.png)

### Example 5
Native
![image](https://user-images.githubusercontent.com/3170940/168452575-e0ab24c8-d363-44e9-8274-680bb293bdbb.png)
Performance
![image](https://user-images.githubusercontent.com/3170940/168452584-f4d667eb-7a28-4701-a041-25e137657a89.png)

**Comment by ogniK5377** [comment]
Water should be fixed, i'll take a look at some tool modes, is vis_debug_show the only one which is affected?

**Comment by ogniK5377** [comment]
Next steam update will have this fixed now 👍
