### ISSUE TITLE
Crash when interacting with the buttons

### ISSUE THREAD

**Issue by fixinit75** [Facepunch/sbox-issues#1835]
### Describe the bug

When I interact with some game elements like the buttons, the game crashes, though I can still play if I never hover a cursor on them.

### To Reproduce

1. Start up the game
2. Hover your cursor over any of the buttons

### Expected behavior

The expected result for me should be no crashes and regular interaction events.

### Media/Files

[sbox_2022_0516_182636_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/8701431/sbox_2022_0516_182636_0_accessviolation.zip)

https://user-images.githubusercontent.com/78933401/168630900-9eadfd4c-f225-45b2-b5f1-de5d395170bd.mp4

### Additional context

I'm on windows 11 25115. My specs are:
AMD Ryzen 7 5800X
16GB of come Crucial ram
ASUS GTX 1050Ti 4GB
The system is installed on a 500GB Samsung 970 EVO Plus and the game itself is on WD20EFAX 2TB HDD.

**Comment by fixinit75** [comment]
Yep, my headphones are disconnected rn.

**Comment by fixinit75** [comment]
Oh, yeah, seems that everything crashes only w/o audio output devices

**Comment by handsomematt** [comment]
Pretty sure I fixed all the crashes with null audio devices, please reopen the issue if not though.
