### ISSUE TITLE
Unable to set game resolution to 3840 × 2160

### ISSUE THREAD

**Issue by Cameron-Bush** [Facepunch/sbox-issues#1845]
### Describe the bug

When setting the game resolution if wont display the option for 4K (3840 × 2160) unless you go to your GPU's settings and enable 'GPU Scaling' as opposed to 'Monitor Scaling'. For owners of AMD cards, this is in the Radeon Software under Settings>Display>GPU Scaling. The default option for both AMD and Nvidia is 'Monitor Scaling'

### To Reproduce

1. Own a 4K monitor
2. Don't enable GPU Scaling
3. Maximum game resolution will either be 1440p or 3200x1800

### Expected behavior

Game should detect the system resolution and offer option for 3840 × 2160

### Media/Files

![image](https://user-images.githubusercontent.com/83086877/169101165-3ac33cbf-cc03-4624-8ba7-fd80921cc452.png)

### Additional context

Running Windows 11, 4th Gen i5, RX480, 16GB RAM, Iiyama G-Master GB2888UHSU (yes I know my hardware is crap for 4K)

"Lily (Pixel³)#0001" in the s&box Discord also had the same issue with their Nvidia Card

**Comment by handsomematt** [comment]
There was 1 weird thing that I fixed that might've been interfering but I do doubt it.

- Do other DX11 games show this resolution properly for you? ( Try Dota 2? )
- Are you using a proper HDMI 2.0+ cable in your monitor's HDMI 1 slot? Or DisplayPort?

**Comment by Cameron-Bush** [comment]
Good news Matt. I think you've fixed it. I will quickly confirm with the other people who also said they were having the issue but for my device, I've now got the correct resolution options coming up.
