### ISSUE TITLE
I want to see an Asset's type in the object

### ISSUE THREAD

**Issue by Nickishero** [Facepunch/sbox-issues#1850]
### What it is?

Currently you can query to the API for multiple types.
These are currently only two, according to the wiki, being 'gamemode' and 'map'.
However the objects which are returned have no definition of this.

Ex. http://sap.facepunch.com/asset/list?type=map

### What should it be?

I would like that assets which are being returned, to include a 'type' property. 

Currently it is not present, so when you have multiple assets in your frontend, which consist of maps and gamemodes (you can get both when querying without the type= filter), you don't know which is a map or which is a gamemode. I've looked at the categories but these don't seem to define the type of the asset.

In the future when more types would be added I'd think this would be even more handy.

edit: I saw there was a 'packagetype' but I am not sure if this is what I mean. There is no reference to it in the wiki, at least not a clear one. I've seen packagetypes of 1, 2 and 5. And since there's only 'gamemode' and 'map' I assumed these would not be it. Correct me if I'm wrong.

**Comment by cr4yz** [comment]
PackageType is what you're after.  Here are the types:

```
Map = 1
Gamemode = 2
Tool = 3
Content = 4
Model = 5
```

I'll toss these up on the wiki too

**Comment by Nickishero** [comment]
> PackageType is what you're after. Here are the types:
> 
> ```
> Map = 1
> Gamemode = 2
> Tool = 3
> Content = 4
> Model = 5
> ```
> 
> I'll toss these up on the wiki too

Thanks!
