### ISSUE TITLE
Hammer crashes constantly

### ISSUE THREAD

**Issue by eagleonedevteam** [Facepunch/sbox-issues#1851]
### Describe the bug

Lately Hammer has been crashing every few minutes on a number of various commands. The most common is going into ALL LIGHTING mode which crashes 90% of the time now. It will also crash when saving the map, or pressing SHIFT O to hide entities.

It does NOT happen when doing edits to hammer meshes or editing faces. It mostly happens when lighting is involved.

### To Reproduce

I have attached the vmap that I was making. It is only dev textures and hammer meshes so that you don't have to have anything else to open it 

Download vmap at the following address (it was too big zipped to attach)

https://cdn.discordapp.com/attachments/822614200294834236/977651159458250792/devhammer_bare.zip

1. Open the vmap
2. Go around and do random things such as going into ALL LIGHTING
3. Crash will happen

### Expected behavior

Editor will crash after a few changes have been made. If you go into and out of instances it will crash randomly as well.

### Media/Files

[sbox-dev_2022_0514_093941_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/8748215/sbox-dev_2022_0514_093941_0_accessviolation.zip)
[sbox-dev_2022_0521_120512_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/8748216/sbox-dev_2022_0521_120512_0_accessviolation.zip)

Here are some minidumps that have occurred

### Additional context

Started to happen in the last 2 weeks - was not an issue at all before then.

**Comment by handsomematt** [comment]
Same crash as always, transform cbuffer is getting full. @samzanemesis do you want me to switch this over to structured buffers or are you already in progress?

**Comment by ogniK5377** [comment]
Should be fixed next steam update
