### ISSUE TITLE
[ModelDoc] Ability to create single frame face poses from existing shape keys within Modeldoc

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#1852]
### For?

S&Box, ModelDoc

### What can't you do?

Currently, making faces or using flexes is very unpractical, as it requires many formats and plugins, it is convoluted and unintuitive.
It would be nice if there was a way to create shape key animations inside the tools.

### How would you like it to work?

A simple "Create Animation from Morph..." wizard option would suffice, it could create a real animation file, or be internal to the model, what matters is that it can be used like any other animation, in the Animgraph for example.
![1](https://user-images.githubusercontent.com/86626409/169689223-6e671118-cb62-4aea-9930-1828dbde3b58.png)

Weight List already has some semblance of what it could look like, sliders for each morph, here is a mockup:
![2](https://user-images.githubusercontent.com/86626409/169690419-31a4962c-d2a4-4f61-a807-5d9b1536af21.png)

But some functionality that would be nice to have would also be:

1. To see the changes in real-time, for a faster workflow
2. To pack various faces in the same animation, just in different frames, like the attack faces the citizen uses

For the last function, as seen in the mockup, it could be a simple slider to select the frames, and you can add or remove frames from it, this is useful because you can have a single animation for every face you could need, and use "single-frame animation" in animgraph to use them individually.

EDIT: I just realized we could use the Morph Explorer's option to enable "manual slider control", which allows for real-time viewing of the flexes, maybe the function could be a feature of the morph explorer? Maybe a "Create animation from current Sliders", it would be up to the developer
![image](https://user-images.githubusercontent.com/86626409/169693716-ae699424-94ee-4b5d-bbd2-c5a0721860e6.png)

### What have you tried?

I've tried working with the current system and it is painful, as many can attest.

### Additional context

I know that the devs have considered a more streamlined way to do this for some time, a discussion with ShadowBrain, who has the same strifes as I am, confirmed this was not an isolated case.

Bonus compilation of Max spitting straight facts

![image](https://user-images.githubusercontent.com/86626409/169690029-7ad98afa-c261-4345-9434-9ac9148ef529.png)

And the main inspiration for this feature request:
![image](https://user-images.githubusercontent.com/86626409/169690047-dcacd528-1348-414d-972b-52e5fe44e2ff.png)
As Max said, a way to offload some of the work to the tools would be fantastic, not sure if this is leaking private discussions, but it was all from the ModelDoc channel.

**Comment by ShadowBrian** [comment]
🙏 this would be great

**Comment by MaxLebled** [comment]
I'll add that in the meantime, you can use the SFM to create DMX animation files containing the poses that you want.

One trick you need to use is that channels can't be "on the same value" for the entire duration. I have to fill frame -1 with noise (using the Jitter slider) for channels to properly export.

**Comment by aylaylay** [comment]
Added MorphFrame node
