### ISSUE TITLE
Using Game Resource `ResourceType("png")` throws exception

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#1853]
### Describe the bug

Using `ResourceType("png")` on a `GameResource` throws an exception.
```
Unknown asset type (png) from  ResourceType( AssetBrowse(png) )
[3]  Object reference not set to an instance of an object.
```

### To Reproduce

1. Create a `GameResource` with a property attribute `[Title( "Icon" ), Category( "UI" ), ResourceType( "png" )]`
2. Try to change the property
3. Notice that an exception is thrown

### Expected behavior

It should work as it previously did, allowing us to select any `.png` files 
https://github.com/Facepunch/sbox-issues/issues/1580

### Media/Files

![image](https://user-images.githubusercontent.com/32153021/169713413-5db1afd2-262e-490c-bf21-173cf5613eab.png)
![image](https://user-images.githubusercontent.com/32153021/169713417-fb56370e-9f8c-4ca4-a976-5902cc311da1.png)

**Comment by aylaylay** [comment]
all images use jgp asset name, we should probably fix the exception and have "image" for images

**Comment by garrynewman** [comment]
I did a hack around this, should be fixed now

**Comment by mzegar** [comment]
Still getting the same errors on my end
```csharp
[JsonPropertyName( "icon" )]
[Title( "Icon" ), Category( "UI" ), ResourceType( "png" )]
public string IconPath { get; set; } = "";
```
![image](https://user-images.githubusercontent.com/32153021/170531918-9df94904-ab3a-47cd-b371-62f209d9c310.png)
![image](https://user-images.githubusercontent.com/32153021/170531937-7067ee4e-c32f-4fc7-adc7-a80504cfa644.png)


Unless the `ResourceType` should be changed to something else?

**Comment by mzegar** [comment]
After the latest update you pushed, I'm getting no exceptions (the file selection pops up correctly, and allows me to select a `.png`). However, it fails to load the photo ingame "Image.Load: ui/weapons/knife.jpg not found (Could not find file `/ui/weapons/knife.jpg`.)"

The original file is a `knife.png` in this case, while using the `"png"` resource type.

**Comment by Fortune117** [comment]
I think I'm having a related issue:
```CS
[GameResource("Bingus", "bingus", "Bingus time")]
public class TestResource : GameResource
{
    [ResourceType("png"), Category("Item Info")]
    public string Icon { get; set; }
}
```
Creating a reasource like this and assigning an image to the Icon in the inspector gives an error in console and the resource fails to compile.

![image](https://user-images.githubusercontent.com/7847372/171624442-a6d4c0c8-d6e5-4425-803d-9a15ac907c24.png)

This was working fine before the last pain day.

**Comment by garrynewman** [comment]
Looks like this is fixed now

**Comment by mzegar** [comment]
@garrynewman Is there something I'm missing? I'm getting errors when trying to load the pngs. This repo will produce that error when the game mode starts. 
```
Image.Load: ui/none.jpg not found (Could not find file `/ui/none.jpg`.)
```
[repo.zip](https://github.com/Facepunch/sbox-issues/files/8953699/repo.zip)

**Comment by garrynewman** [comment]
Did you add the ui folder to the resource paths in your add-on config?

This is a list of files that are sent to the client.. so if the folder isn't on the list it won't find them.

**Comment by mzegar** [comment]
Yeah, those images are properly set in the resource paths, but, this is happening on a local copy so the files are there anyways. I'm assuming the issue is that I'm trying to precache the image in the `PostLoad()` (since the file path is correct). I'll play around with some test cases and post an issue if so. 

Thanks

**Comment by mzegar** [comment]
So the issue occurs due to the fact that when you select a `png` from the asset browser, the path tags on a `.jpg` which ends up not finding the image. Here's an example snippet

```csharp
	[ResourceType( "png" )]
	public string IconPath { get; set; } = "";

	protected override void PostLoad()
	{
		base.PostLoad();

		if ( Host.IsClient )
		{
			Log.Info( $"PNG - ui/none.png" );
			Texture.Load( FileSystem.Mounted, "ui/none.png" );

			Log.Info( $"JPG - {IconPath}" );
			Texture.Load( FileSystem.Mounted, IconPath );
		}
	}
```
```
 09:27:09   PNG - ui/none.png // <- using `.png` fetches the file fine
 09:27:09   JPG - ui/none.jpg // <- notice that the path is `.jpg`
 09:27:09   Image.Load: ui/none.jpg not found (Could not find file `/ui/none.jpg`.)
```

**Comment by robotboy655** [comment]
I have made the asset picker use real extensions, let me know if that breaks something.
