### ISSUE TITLE
Editor: inspector filter line edit does nothing

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#1854]
### Describe the bug

Using the line edit in the editor doesn't do anything

### To Reproduce

1. Open the editor
2. Type something into the "Filter.." box in the inspector header

### Expected behavior

When there's something in the filter box, it should only show properties that match the filter

### Media/Files

https://user-images.githubusercontent.com/12881812/169714261-73e8db31-a90f-433c-8f52-2861cc1b5e62.mp4

### Additional context

By the looks of it, there's no actions or events hooked up to the line edit in code - looks like it was never implemented to begin with:
![image](https://user-images.githubusercontent.com/12881812/169714273-a463a111-8fbe-4453-9577-55a5a161c895.png)

**Comment by DevulTj** [comment]
Had a look into this, but it's probably not worth it for now. We could add a filtering method that gets passed to InspectorWidget later if we want it.

I got rid of the filter so it's not confusing.
