### ISSUE TITLE
Engine: run-length encoded grayscale TGAs cause a complete engine crash

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#1855]
### Describe the bug

TGA textures that use run-length encoded grayscale data will cause the entire engine to crash (see [here](https://en.wikipedia.org/wiki/Truevision_TGA#:~:text=11%20run%2Dlength%20encoded%20black%2Dand%2Dwhite%20(grayscale)%20image) for more info). While these aren't going to be used extensively, I did export an AO map like this, and having it crash the engine did throw me off for a little while 🙂

To my knowledge, this only happens with grayscale RLE textures.

### To Reproduce

1. Download this texture: https://files.gu3.me/2022/May/22/crash_texture.tga or https://files.catbox.moe/jh90pg.tga
2. Rename it to "crash_texture" or something
3. Put it in a s&box addon
4. Open s&box
5. If s&box hasn't crashed at this point, try to find it in the asset browser

### Expected behavior

The engine shouldn't crash.

### Media/Files

https://user-images.githubusercontent.com/12881812/169714853-641a119a-2771-4254-9ae6-66df3745bd12.mp4

(There should be a couple of mdmps uploaded to sentry related to this, but if you need one specifically from me, give me a shout and I'll send you one I backed up)

**Comment by aylaylay** [comment]
Should be fixed now.
![sbox-dev_KJXru28VBM](https://user-images.githubusercontent.com/1667289/170857108-41919e3c-c8fd-4043-9858-c4219f588ff6.png)

**Comment by xezno** [comment]
All working now, thanks Layla 🙂
