### ISSUE TITLE
Allow `ResourceTypeAttribute` to take in a `params string[] types`

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#1858]
### What it is?

The attribute `ResouceType` only allows us to pass in a single type. For example...
```csharp
[ResourceType( "carri" )]
public List<string> ExclusiveItems { get; set; }
```
This means that when we go into the editor and click on the icon to select a file, only files of type `.carri` will appear
![image](https://user-images.githubusercontent.com/32153021/169870062-5bcc6055-f5d3-4bab-8357-87f2229239c4.png)

### What should it be?

What if someone wants to grab the path of multiple different file types? In my use case, it would be something like...
```csharp
[ResourceType( "carri", "perk" )]
public List<string> ExclusiveItems { get; set; }
```
People may have use cases where they want to get references to multiple different image types for example
```csharp
[ResourceType( "png", "jpg" )]
public List<string> Images { get; set; }
```
(technically `png` is broken right now but this worked before the pain day https://github.com/Facepunch/sbox-issues/issues/1853)

**Comment by DevulTj** [comment]
I don't think it's good design to have different resource extensions that do the same thing, not sure why you'd want multiple file types with the same data structure

**Comment by mzegar** [comment]
Sure let me explain my use case...

- Base `GameResource` class that contains information that every single `item` should have (i.e Name, Icon, etc.)
- Sub `GameResource` classes that contain information only specific to that use case.
	- Ex. `Carri` which is a generic carriable for the player
		- Ex. `Weapon` which has information pertaining to fire rate, reload time, etc. 

When I view these `GameResources` in the inspector they only show relevant information related to that `GameResource`. My inspector view isn't a million different irrelevant properties basically.

Laylad suggested that maybe a generic `image` `ResourceType` should be used in https://github.com/Facepunch/sbox-issues/issues/1853#issuecomment-1135086484. If so, I feel like a generic `GameResource` type would solve my use case as well.

**Comment by matekdev** [comment]
Closing this since https://github.com/Facepunch/sbox-issues/issues/2416 will take care of this functionality.

**Comment by MrBrax** [comment]
Did that issue actually make it possible to choose any file or from a few choices?

**Comment by LeQuackers** [comment]
> Did that issue actually make it possible to choose any file or from a few choices?

You can make some base `GameResource` class and derive other classes from it; if you specify the base `GameResource` as the property's type, the inspector will allow you to select the base class (if it's instantiatable) as well as the derived classes.

If you have several unrelated `GameResource` classes that should be able to be selected (e.g. items/abilities/effects in a shop), then not really; you'll end up in inheritance hell if you try to make it work, which sucks (see #3829).

**Comment by MrBrax** [comment]
> > Did that issue actually make it possible to choose any file or from a few choices?
> 
> You can make some base `GameResource` class and derive other classes from it; if you specify the base `GameResource` as the property's type, the inspector will allow you to select the base class (if it's instantiatable) as well as the derived classes.
> 
> If you have several unrelated `GameResource` classes that should be able to be selected (e.g. weapons/ammo/abilities/effects in a shop), then not really; you'll end up in inheritance hell if you try to make it work, which sucks (see #3829).

Oh ok, thanks. Would not really work for me then i think, and since there's seemingly no way of only returning ResourceName it doesn't seem to be that useful to me anyway.

**Comment by MrBrax** [comment]
Doesn't seem to be working for me anyway when trying it, would be really nice with a true multi select option as I'm kinda stuck programming an item list right now.
