### ISSUE TITLE
Inspector doesn't show property sheets for classes

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#1865]
### Describe the bug

When I use a class as a property on a `GameResource` and expose it, the Inspector will not display the properties of the class; instead it displays a text block containing the .NET type name of the class. When using a struct, the properties of the type are displayed as expected.

### To Reproduce

1. Create a `GameResource` with at least one property that uses a custom class as a type, like the following, and add it to any gamemode:

```cs
[GameResource("String Table", EXTENSION, "Contains UI strings localized in a specific display language.", Icon = "text_fields")]
public sealed class StringTable : GameResource
{
    public const string EXTENSION = "strtbl";

    [Property(Title = "Entries")]
    public Entry[] Entries { get; set; }

    public sealed class Entry
    {
        [Property(Title = "Key")]
        public string Key { get; set; }

        [Property(Title = "Content")]
        public string Content { get; set; }
    }
}
```
2. Create a new resource of this type in the Inspector.
3. Attempt to add and edit entries.

### Expected behavior

`GameResource` properties that are classes should display their inner properties in the Inspector in the same way as structs.

### Media/Files

![image](https://user-images.githubusercontent.com/1622492/170329586-5d098980-e3f9-409b-aecb-c075fbbba992.png)

### Additional context

This issue did not occur in the old Inspector.

**Comment by DevulTj** [comment]
Shouldn't be a problem with controls
