### ISSUE TITLE
Broken blur on WorldPanel

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#1866]
### Describe the bug

Using; `backdrop-filter: blur( 10px );` works fine on normal panels but not on WorldPanels, the blur stops when the text stops for some reason, it can also flicker on and off from time to time.

![image](https://user-images.githubusercontent.com/4988198/170359032-1bbaea80-ed6f-41ff-b9a2-b70ded737d71.png)

**Comment by cr4yz** [comment]
I've pushed a fix for this, it should be included in the next update.  Please let me know if you're still having issues

**Comment by timmybo5** [comment]
Issue is fixed!
