### ISSUE TITLE
Light Probe Volume debug command doesn't work on the env_light_probe_volume entity

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1867]
### Describe the bug

When attempting to debug light probe volumes with the command `r_light_probe_volume_debug_grid` in a map that uses the  `env_light_probe_volume` entity, the debug command doesn't enable the debug grid on that entity.

### To Reproduce

1. Compile or load provided map. 
2. set `r_light_probe_volume_debug_grid` to `1`.
3. observe the issue when moving between the two sides.

Map Files :
[probe_setup.zip](https://github.com/Facepunch/sbox-issues/files/8777546/probe_setup.zip)
 

### Expected behavior

For the light probe debug grid to show up just like if you were using the `env_combined_light_probe_volume` entity.

**Comment by aylaylay** [comment]
Done but can you please test if it works - i couldn't be arsed to make a map

**Comment by QuackCocaine** [comment]
Works as expected, Thanks!
