### ISSUE TITLE
Add the ability to override entity physics simulation

### ISSUE THREAD

**Issue by TomDotBat** [Facepunch/sbox-issues#187]
**What can't you do?**
Override the engine defined behaviour of a physics object.

**How would you like it to work?**
A method you can implement that works like GMod's [ENT:PhysicsSimulate](https://wiki.facepunch.com/gmod/ENTITY:PhysicsSimulate).

**What have you tried?**
Implementing an OnPostPhysicsStep method from IPhysicsUpdate, but it only allows you to make changes after the physics engine.

**Additional context**
Useful for changing gravity behaviour per entity and etc.

**Comment by rtm516** [comment]
Can't you do that with Entity:Simulate?

**Comment by TomDotBat** [comment]
Not quite
