### ISSUE TITLE
Multiple custom Hammer entities creates multiple tabs 

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#1873]
### Describe the bug

In a game project, you can create multiple custom entities.
For some reason when you get in hammer and use the Entity Tool, you will see a multiple tabs for said game.
The amount of tabs that appear correspond to the amount of custom entities you have.
(for example... in mine, Lobby has 4 custom entities, Dine N Dash has 2 custom entities)

Note, only the bottom tab works, the rest above the bottom of for said games do nothing.

### To Reproduce

1. Have a game addon
2. Go in and create multiple new custom entities in the code using [HammerEntity] on each one ofc
3. Let it compile and look at the entity tool in hammer and see said issue

### Expected behavior

It shouldn't have extra tabs appearing

### Media/Files

![image](https://user-images.githubusercontent.com/82092361/170784082-d5c00205-621f-4e4c-b161-567c0c97fb29.png)

**Comment by handsomematt** [comment]
Can't recreate, need to see your .addon and some code really

**Comment by NotGaylien** [comment]
Oh sugar,
sorry for the late response.

yeah i figured out what causes this issue to happen, on my end at least.

In my addon, if the Organisation Ident is set to local, then it causes this to happen.

**Comment by handsomematt** [comment]
Perfect, I can sort it now.

**Comment by handsomematt** [comment]
There we go, sorry that took so long and thanks for the bug report ❤️

**Comment by NotGaylien** [comment]
Lovely! thank you matt, works perfectly!
thanks for your time. ❤️
