### ISSUE TITLE
Animgraph - Early subgraph feedback 

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1875]
### Describe the bug

Let's use github instead of so much discord because it seems that I can find stuff like this (I hope not too many)

How to fuck up the subgraph node v2, add a subgraph inside another subgraph copy/paste your nodes, ctrl +z.

### To Reproduce

Explained in the video.

### Expected behavior

Layla fixing stuff <3

### Media/Files

https://user-images.githubusercontent.com/40291120/170871726-c18c1504-6c0a-4128-9b32-ebd21776c77c.mp4

**Comment by KaesarZZ** [comment]
Fuck, I think adding subgraphs inside other subgraphs opens another world.

Got two crashes.

1.
**Inside** a subgraph, if you copy/paste a subgraph into it, it appears called "Subgraph", a null node since it's already in use, all fine. 

If you cop/paste a subgraph inside another subgraph, you can keep both when you shouldn't (or maybe yes, it's a bit complex to think it has a utility for now). 

if I edit the connections in one of them and do ctrl + z, I have a crash. 

https://user-images.githubusercontent.com/40291120/170875580-58cf72f7-c893-4dda-b8a1-4bcfba7a4209.mp4

2. Make two subgraphs, copy/paste one of them inside the other one, if you remove everything, you still have it in use (bug), try to add it and play animgraph and it crashes. 

https://user-images.githubusercontent.com/40291120/170875182-7ec7081f-56d0-4fce-867a-629a1c949801.mp4

**Comment by aylaylay** [comment]
Please make an issue for each specific bug
