### ISSUE TITLE
Hammer - Prop_physics wont show up in the hammer entity list

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1876]
### Describe the bug

The `prop_physics` entity won't show up hammer entity list.

### To Reproduce

1. Setup a clean install.
2. Open the editor.
3. Open hammer. 
4. Navigate to the entity tool and search for `prop_physics`.
5. Observe that it won't show up.

### Expected behavior

To show up.

### Additional context

This issue was tested on a clean install with no addons.

**Comment by QuackCocaine** [comment]
I have further figured out that it will show up on a clean install, sometime (no configs or previous cache). And you restart the tools it will go away no longer show up

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/170974412-3bc2110d-3b95-400b-ba57-c2fbde209846.png)

It's showing up just fine on a clean Steam build for me. Can you post a log and some screenshots,

**Comment by QuackCocaine** [comment]
Another fresh install with video of booting the fresh install https://streamable.com/u07edz .  the log shows nothing of use but here it is anyway.
[Log.log](https://github.com/Facepunch/sbox-issues/files/8797743/Log.log)

**Comment by Adesii** [comment]
i too don't have Prop or prop_physics.
no error's in the console on startup or hammer opening.

The only error i get is when searching something:
![image](https://user-images.githubusercontent.com/37816311/170979125-606b9fdf-baa0-4dd1-964d-be2775cabf65.png)

**Comment by QuackCocaine** [comment]
Yup

**Comment by QuackCocaine** [comment]
Works like a charm now matt.
