### ISSUE TITLE
Animgraph - Crashing if you remove the subgraph and try undo

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1878]
### Describe the bug

Add a subgraph inside another one, delete one and try to undo, you find the crash.

If you save in the process your animgraph is completely corrupted. 

### To Reproduce

Explained in the video. 

### Expected behavior

Fix it.

### Media/Files

https://user-images.githubusercontent.com/40291120/170893611-decf08c2-1e49-4f55-b4c0-9475b07a094e.mp4

**Comment by aylaylay** [comment]
Undoing should hopefully be more stable now

**Comment by KaesarZZ** [comment]
That's fixed yeah. Thanks

**Comment by KaesarZZ** [comment]
Reopening this, there is a complex one but the same crash; add a subgraph inside a subgraph, add a random node into it, remove the node and the file, go back to home it crashes recovering it.

https://user-images.githubusercontent.com/40291120/171162723-8746a48c-394c-490c-a8a8-030e0e686ba9.mp4
