### ISSUE TITLE
Animgraph - Bonemerge browser is broken

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1879]
### Describe the bug

The browser layout when you try to open the bonemerge model is broken.
![bug](https://user-images.githubusercontent.com/40291120/171020773-c89acb44-c984-4f24-82ca-1b5e107dba0c.png)

### To Reproduce

Just open the browser.

### Expected behavior

Get the same as we have in ModelDoc e.g.
![good](https://user-images.githubusercontent.com/40291120/171020714-3915abdf-1ff2-4ea9-a9cc-552002b00709.png)

### Additional context

Deleting .source2/settings/animgraph_editor doesn't fix it.

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by KaesarZZ** [comment]
Fixed, ty <3
