### ISSUE TITLE
Modeldoc crashing when pressing specific buttons when opening read-only model

### ISSUE THREAD

**Issue by AdamSai** [Facepunch/sbox-issues#188]
**Describe the bug**

Pressing these Animation Controls in modeldoc after having opened a read only model crashes s&box.

I doubt very many will run into this issue, as there's no reason to press the buttons when no model is showing, but I found in nonetheless.

**To Reproduce**

1. Open a read-only model by double clicking a read-only .vmdl file in the asset browser
2. Click on one of the following buttons  
2a. Jump to start  
2b. Step back  
2c. Jump to End  
3. s&box crashes  

**Expected behavior**
Nothing should happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/11211186/118408212-dc20af80-b684-11eb-9064-b5c995444aff.png)  
**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.  
Depending on the model, one of the buttons might not make s&box crash.  
On the citizen.vmdl model, all 3 highlighted makes s&box crash  

Looking at the Mini-Dump which is generated you see it's an access violation.
![image](https://user-images.githubusercontent.com/11211186/118408304-4fc2bc80-b685-11eb-8d0c-554d4910f23b.png)

**Comment by aylaylay** [comment]
The controls you highlighted shouldn't crash now. I need to take a second look at this at some point because I don't see the point in opening a compiled model if you can't even see it.

**Comment by AdamSai** [comment]
> The controls you highlighted shouldn't crash now. I need to take a second look at this at some point because I don't see the point in opening a compiled model if you can't even see it.

Yeah it's fixed. And I agree, there's no point in being able to open up ModelDoc or any of the other editor for read-only assets. It's still nice to see them in the asset browser, so we can see all the assets available to us
