### ISSUE TITLE
Animgraph - Crash if you copy/paste the same subgraph inside it

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1880]
### Describe the bug

There is a easy crash after the last changes if you copy/paste the same subgraph inside it.

### To Reproduce

Explained in the video. 

### Expected behavior

Fix it. 

### Media/Files

https://user-images.githubusercontent.com/40291120/171022364-8e8cc2ff-45f5-4954-85ac-1ffa31793571.mp4

**Comment by KaesarZZ** [comment]
Your last commit fixes it, but here is the v2. Pasting itself in a subgraph.

https://user-images.githubusercontent.com/40291120/171161661-1fe34499-d664-4308-a1a1-973b29d4ab3f.mp4

**Comment by aylaylay** [comment]
Should be more stable now

**Comment by KaesarZZ** [comment]
Fixed, ty <3
