### ISSUE TITLE
ConVar not working on generic classes.

### ISSUE THREAD

**Issue by FoxTTT** [Facepunch/sbox-issues#1883]
### Describe the bug

You can't create convar's on generic classes

### To Reproduce

Works:
```csharp
	public class TestW
	{
		[ConVar.Replicated( "test" )] public static bool ok { get; set; } = false;
	}
```

Doesn't work:
```csharp
	public class Test<T> where T: Enum
	{
		[ConVar.Replicated("test")] public static bool ok { get; set; } = false;
	}
```

### Expected behavior

To work, if I missed a core element of generic's mb.

**Comment by saul** [comment]
How would you expect this to work? It's not possible to do `Test.ok` on a generic class - you need to supply a generic type argument, like `Test<int>.ok`

See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1000

**Comment by FoxTTT** [comment]
That is true, didn't give any consideration to that. I can just make it inherit a non-generic if needed.
