### ISSUE TITLE
Automatically hide outdated addons when breaking changes happen and allow for players to show hidden outdated addons

### ISSUE THREAD

**Issue by SebbeJohansson** [Facepunch/sbox-issues#1885]
### For?

S&Box

### What can't you do?

I am unable to show outdated addons that are hidden because of a pain day update.

### How would you like it to work?

I dont know if this makes sense, but I think it would be cool if addons that use API things that have a breaking change are automatically hidden (similarly to what happens after pain day updates) and allow players to show these hidden updates.

The point of this would be to keep broken addons from showing up in searches, while still allowing players who are looking for something specific to still find it. A use case for this would be older addons that might still be playable, even if they have errors.

### What have you tried?

Does not apply.

### Additional context

The extreme of this idea would be to hide **all** addons that are outdated as is the procedure currently after pain days. But I think this has the potential of being too destructive.

If an automatic system based on API updates cant be created, an alternative could be for a community driven report system where a manual check and "hide" has to be done, but this would obviously need administration work from either Facepunch or the community. Which is obviously not great.

**Comment by garrynewman** [comment]
This should already be the case?

**Comment by SebbeJohansson** [comment]
> This should already be the case?

@garrynewman I wasn't aware that the plan was to do this in the future (even after release etc). Maybe I missed something in the dev blog?
