### ISSUE TITLE
ModelDoc - Bonemerged model disappears after compiling

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1887]
### Describe the bug

I don't know if this is something new or has always happened but if you add a model with the "Bone Merge tool" and you do any edit on the "mainly" model and recompile it, the merged model disappears even if it comes "Added" on the list. You need to re-add it. 

### To Reproduce

1. Add a bonemerged model in ModelDoc.
2. Edit and recompile the main model.
3. It disappears.

### Expected behavior

Keep the merged model after compilation.

**Comment by aylaylay** [comment]
what bone merge tool???

**Comment by NotGaylien** [comment]
![image](https://user-images.githubusercontent.com/82092361/171483349-24528430-004a-47a8-9481-4a50e8966d89.png)
This one!

**Comment by aylaylay** [comment]
aight

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by KaesarZZ** [comment]
Fixed, ty Rubat,
