### ISSUE TITLE
Expose dmx/keyvalue2 functions to c#

### ISSUE THREAD

**Issue by Kaydax** [Facepunch/sbox-issues#1889]
### For?

S&Box, Other

### What can't you do?

Currently the only way to parse any kind of dmx / keyvalue2 files, for instance a vmap file, is to implement a custom parsing system for the entire format as a whole. This takes a lot of time as the dmx format is very under documented, even on the developer forums, and the only good way of doing it is to convert it to keyvalues2, which itself is time consuming and some things it contains is undocumented

### How would you like it to work?

Have the dmxloader and keyvalues parsing functions exposed to the c# api for use in addons. Basically allowing addons to be able to take dmx files and unserialize them / parse them, the same with keyvalues

### What have you tried?

Writing my own keyvalues2 parser that works in s&box. It works well but the issue is supporting everything on top of the fact its only limited to keyvalues, and not the dmx format itself

### Additional context

A good use case for this is direct vmap parsing, allowing for dynamic map generation based on prefabs without the need to export to different model formats

**Comment by xezno** [comment]
Would be super nice to have this, I could do with having it for a tool that serializes & deserializes .vtex files.. writing a DMX/KV2 parser is doable but a bit of a pain in the arse

**Comment by robotboy655** [comment]
What do you need to parse vtex files for?

For vmap parsing and having dynamic map generation, @aylaylay had made something that would allow you to spawn in compiled maps at runtime, I don't know what it's status is though besides that its not in the game. (Yet?)

**Comment by handsomematt** [comment]
It does seem anything this would be good for would be something we should be exposing an API for like model imports. I don't think vtex files should even need to be created we could do it similar to the sound metadata and tools would just point to the .png / .jpg

**Comment by aylaylay** [comment]
I think having a dmx api can be avoided altogether, we should just have api's that can build whatever asset and the engine can then serialize it to dmx

**Comment by garrynewman** [comment]
We kind of already expose a keyvalues parser, but indirectly. We generally expose keyvalues as json to c#, since there already exists a world of tools to mess with json and there are already conversion functions in the engine. I'd always favour this over directly exposing KeyValues classes to addons.

**Comment by xezno** [comment]
Yeah, that's fair - I don't think vtex files shouldn't be something people need to worry about, the whole process should be transparent. I can't think of anything else that uses DMX aside from vtex/vmap, so having an api for it seems pretty pointless
