### ISSUE TITLE
Entity.EnableDrawing = false doesn't stop attached particles from rendering

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#1894]
### What it is?

Spawned particle systems are technically not part of the entity, so on paper it makes sense. But it's a little unintuitive. Say you have some GameData for a particle on a model for a weapon, and you switch from that weapon to something else, it'll still draw its particles. See below:

https://user-images.githubusercontent.com/22372616/171690910-643c45b9-137b-4f2e-a855-9401b28ff2b9.mp4

### What should it be?

I think it's worth discussing whether or not it's a warranted change before anything is set in stone.

**Comment by DoctorGurke** [comment]
I remember it being an intended feature that child entities stop drawing when their parent has drawing dissabled, I think the same should apply in this instance as well. Especially since in this case it's literally part of the model.

**Comment by robotboy655** [comment]
Should be working as expected when the gam next updates.

**Comment by DevulTj** [comment]
Your implementation works
