### ISSUE TITLE
Fix Duplicate Keybinds

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1895]
### For?

Hammer

### What can't you do?

Ctrl+Up (& Ctrl+Down) hotkeys should nudge your current selection by 1 unit, the same as Ctrl+Left/Right. However, there's a duplicate binding for Vertex/Edge/Face mode to Add/Remove from Selection. This is not the case in Mesh/Object/Group mode, Nudge by 1 unit works there.

Add/RemoveFromSelection is completely useless in my experience. I actually think it doesn't work.

Here you can see the bindings in question. You'll notice Nudge By 1 Unit isn't listed because it's implicit. The Ctrl key is a modifier that disables the grid.
![image](https://user-images.githubusercontent.com/39461072/171790698-45048380-6409-4fa5-ba87-84ef3f36ed70.png)

### How would you like it to work?

The AddToSelection & RemoveFromSelection bindings should be unbound by default, or bound to different keys. I don't think the hotkey does anything so it's OK being unbound.

### What have you tried?

Currently we have to manually edit the bindings txt file. This isn't ideal and it seems to occasionally gets reset.

![image](https://user-images.githubusercontent.com/39461072/171789217-f6f5b266-ff88-4e1d-aa99-16de4b0235fd.png)

### Additional context

If anyone knows what Add/RemoveFromSelection does please let me know. I'm pretty sure it's completely useless and/or bugged.

**Comment by aylaylay** [comment]
I couldn't tell if the feature it working as intended or just doesn't have much use (you need to have 2 or more things selected for it to work, if you wanted to test it again) So I've just made them bound to keys that aren't in use (ctrl+shift+up/down)

**Comment by gvarados1** [comment]
ty ty. I asked a few other mappers and they all agreed it was useless.
