### ISSUE TITLE
Any base shaders with self-illum crashing game.

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#1896]
### Describe the bug

When creating or having an existing material using Any base shader with self illum options on it,
and enabling self illum it will just crash your game.
trying to open or preview a material with that existing option enabled will also crash your game.

### To Reproduce

1. Create a new material and save it anywhere.
2. Set its shader to any base shader with self illum
3. try enable Self Illum on it

![image](https://user-images.githubusercontent.com/82092361/171874217-59e73fb5-0bb4-4e33-8afe-e48539d9e67a.png)

### Expected behavior

No crashing and to be able to use said self illum

### Media/Files

[sbox-dev_2022_0603_152525_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/8833015/sbox-dev_2022_0603_152525_0_accessviolation.zip)
here is the mini-dump file that gets spit out when i try this.

### Additional context

This crashing only happens on any of the base shaders with self illum

**Comment by NotGaylien** [comment]
Ok also another pain in the ass thing to mention.

I created a new addon and copied everything i had before into it and force compiled everything, this issue stopped happening, but still happened in the old one even if i force compiled everything in that one.

it does not make much sense as to why...

**Comment by ogniK5377** [comment]
There was an issue that caused the material editor to crash which I ended up fixing it so it's possible that caused it. If not do you happen to have the file which causes the crash?

**Comment by NotGaylien** [comment]
Gonna be honest I think it must have been related to that since it happened to every file, new or old.
I can't get it to happen anymore so you probably got it sorted. I have tried this morning but it's all working as normal again.

**Comment by NotGaylien** [comment]
Oh yeah btw, thanks ognik!
