### ISSUE TITLE
[Hammer] - Entity Tool searches by class names even when friendly names are turned on

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#1899]
### Describe the bug

Searching for friendly names in the entity tool doesn't return results, but searching by class name does, even when class names are off/friendly names are on.

### To Reproduce

1. Open Hammer
2. Turn class names off
3. Try to search for an entity by its friendly name (e.g. Sound Event, or just Sound,) then try searching by its class name (e.g. snd_event or just snd_)
4. voila

### Expected behavior

When class names are turned off, you should just be able to search by friendly name.

### Media/Files

https://user-images.githubusercontent.com/10066958/171971467-3903e88b-8bf8-4651-b23a-411152773e15.mp4

**Comment by aylaylay** [comment]
Should be working now. It searches for both no matter what, this was the intended behavior but the search was case sensitive.

**Comment by walllable** [comment]
Fixed
