### ISSUE TITLE
Sound references are invalid after Hotloads.

### ISSUE THREAD

**Issue by VladUndying** [Facepunch/sbox-issues#1901]
### Describe the bug

Trying to maintain a reference of the Sound results in it getting destroyed after Hotloads.

### To Reproduce

```
using Sandbox;

public static class Sounds
{
	public static Sound MySound = new();

	[ConCmd.Client( "playmysound" )]
	public static void PlaySound()
	{
		MySound = Sound.FromScreen( "counting_120" );
	}

	[Event.Hotload]
	private static void OnHotload()
	{
		Log.Info( $"MySound finished: {MySound.Finished}" );
		Log.Info( $"MySound time: {MySound.ElapsedTime}" );
	}
}
```

### Expected behavior

The reference of the sound should be valid or should keep previous reference data.

### Media/Files

Demonstration - https://www.youtube.com/watch?v=30oPCqHvhPE

### Additional context

-

**Comment by VladUndying** [comment]
The sound I used:
```
<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->
{
	data = 
	{
		UI = true
		Volume = 1
		VolumeRandom = 0
		Pitch = 1
		PitchRandom = 0
		DistanceMax = 360
		Sounds = 
		[
			"sounds/diagnostics/counting_120.vsnd",
		]
		SelectionMode = 3
	}
}
```
It should be available for anyone (Built-in file)

**Comment by VladUndying** [comment]
#1918 is related.

**Comment by garrynewman** [comment]
With reference to that - does this work okay if the field isn't static?

**Comment by VladUndying** [comment]
> With reference to that - does this work okay if the field isn't static?

Yes, it does work without static.

**Comment by VladUndying** [comment]
Demonstration without static and with networking - https://www.youtube.com/watch?v=3DZu0Ufdql8

**Comment by VladUndying** [comment]
Fixed now!
