### ISSUE TITLE
Postprocessing Editor - Right Click to Add Layer, Delete Layer, or Copy/Paste

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1903]
### For?

Other

### What can't you do?

We can't right click to add a layer in the pp editor. We have to click the little button to add a new layer

![image](https://user-images.githubusercontent.com/39461072/172020726-3913a1d5-1f85-428a-a632-ba88ecb9117e.png)

### How would you like it to work?

We should be able to right click in the layers panel to add layers
There should also be buttons for Delete Layer, Copy & Paste

### What have you tried?

currently we have to click the Add Layer button to add a new layer or delete/add layers

**Comment by ogniK5377** [comment]
![image](https://user-images.githubusercontent.com/25727384/172049255-7101e2b9-209b-4eca-bc0b-c5ecabd3455a.png)
Should be out next steam build 👍

**Comment by gvarados1** [comment]
Perfect! Thanks!
