### ISSUE TITLE
Postprocessing Editor - Input Box to Enter Values Manually

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1905]
### For?

Other

### What can't you do?

We can't type values manually into the Layer Settings in the pp editor.

### How would you like it to work?

These display numbers should be converted to input boxes that we can type values into 
![image](https://user-images.githubusercontent.com/39461072/172020997-91b6c2dc-aee8-4413-8b82-708a6f397896.png)

### What have you tried?

Currently we have to use the slider bar to input any values

**Comment by ogniK5377** [comment]
Should be available next build 👍

**Comment by gvarados1** [comment]
Perfect! Thanks!
