### ISSUE TITLE
Animgraph Crash when opening a Blend2D

### ISSUE THREAD

**Issue by OMGOMGplays** [Facepunch/sbox-issues#1907]
### Describe the bug

Whenever I try and open a Blend2D node the tools crash and I have to restart them.

### To Reproduce

1. Open animgraph
2. Create a Blend2D node
3. Double click the Blend2D node to open it
4. Crash!!

### Expected behavior

I'd expect the Blend2D node to open normally instead of the crash that occurs.

### Media/Files

https://user-images.githubusercontent.com/87585550/172049373-c28ea2b5-d516-48d0-9b68-4a113917ddbc.mp4

**Comment by aylaylay** [comment]
Fixed
