### ISSUE TITLE
Material Editor - Apply Max Output Resolution to Every Texture

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1910]
### For?

Material Editor

### What can't you do?

There is no easy way to apply a Max Output Resolution to every texture in a material

### How would you like it to work?

I'm not sure where the best spot for this would be, but there should be an option somewhere to apply a Max Output Resolution to every texture in a material. This would not be a global limit. It would apply the change to the setting on each texture.

![image](https://user-images.githubusercontent.com/39461072/172113860-bb52a1a1-e0fa-4c3a-aa45-dace00718f77.png)

### What have you tried?

Currently we have to apply it to one texture, wait about 4 seconds for it to load, then repeat 4-5 times for each texture in the material. This adds up to about a minute of wasted time for each texture. It's very annoying and personally I've just stopped lowering texture res because it takes so long. This is further exaggerated by the inability to scroll through lists, #1583

**Comment by QuackCocaine** [comment]
probably could have it be in a context menu when you right-click the material like this 
![sbox-dev_QzEsh7ET2D](https://user-images.githubusercontent.com/23345567/172144460-c4b915fc-494f-42bf-8453-21b9dc2dd88e.png)
