### ISSUE TITLE
`TypeLibrary.GetDescription` exception in Attribute's constructor

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1912]
### Describe the bug

Just "fixed" the compatibility with one of my gamemodes regarding PainDay III. 
Everything works fine except that after changing `Library.GetAttribute` into `TypeLibrary.GetDescription` I'm getting the following error:
![image](https://user-images.githubusercontent.com/11843790/172180513-41757bdc-1663-466a-be86-04010ae11b99.png)

I tried `TypeLibrary.Has<T>()`, `GetAttribute<Sandbox.LibraryAttribute>()` etc. as well, but everytime receiving the same error.

After trying to compile / start the gamemode multiple times, I get different amounts of the same error:
![image](https://user-images.githubusercontent.com/11843790/172180957-540dbaa7-c22d-4d7a-ade6-07d998fb4d7f.png)

The error line is the following:
```csharp
if (PrimaryAmmoType != null && TypeLibrary.GetDescription(PrimaryAmmoType) != null)
```

The code I'm using:

```csharp
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
public class WeaponAttribute : CarriableAttribute
{
	public string PrimaryAmmoName { get; private set; }
	public string SecondaryAmmoName { get; private set; }

	public Type PrimaryAmmoType { get; set; }
	public Type SecondaryAmmoType { get; set; }

	public WeaponAttribute(CarriableCategories category, bool defaultAmmoType = true) : base(category)
	{
		if (defaultAmmoType)
		{
			PrimaryAmmoType = GetAmmoType(Category);
		}

		if (PrimaryAmmoType != null && TypeLibrary.GetDescription(PrimaryAmmoType) != null)
		{
			PrimaryAmmoName = Utils.GetLibraryName(PrimaryAmmoType); // TypeLibrary.GetDescription(...).Name
		}

		if (SecondaryAmmoType != null && TypeLibrary.GetDescription(SecondaryAmmoType) != null)
		{
			SecondaryAmmoName = Utils.GetLibraryName(SecondaryAmmoType); // TypeLibrary.GetDescription(...).Name
		}
	}
}
```
where `CarriableAttribute` is derived from `ItemAttribute`, which is derived from `Attribute`. (but that's irrelevant as it happens with normal Attributes as well) 

As you can see, `Object reference not set to an instance of an object.)` can't be caused by this line as there is nothing that could be `null`.
I've checked the Classes that are using that attribute and every one of it has a `LibraryAttribute` (even that if not it shouldn't error).

### To Reproduce

```csharp
using System;

namespace Sandbox
{
	public partial class MyGame : Game
	{
		public MyGame()
		{
			foreach (Type type in TypeLibrary.GetTypes<Weapon>())
			{
				Log.Warning(TypeLibrary.GetAttribute<WeaponAttribute>(type).TmpName);
			}
		}
	}

	public abstract partial class Ammo : Prop { }
	[Library("TestAmmo")] public partial class TestAmmo : Ammo { }

	public abstract partial class Weapon { }
	[Library("TestWeapon"), Weapon(typeof(TestAmmo))] public partial class TestWeapon : Weapon { }

	[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
	public class WeaponAttribute : Attribute
	{
		public string TmpName { get; private set; }

		public WeaponAttribute(Type tmpType) : base()
		{
			if (tmpType != null)
			{
				TmpName = TypeLibrary.GetDescription(tmpType).Name;
			}
		}
	}
}
```

### Expected behavior

No error / working behavior inside Attribute's constructor

### Additional context

Doing `TypeLibrary.GetDescription` outside of Attribute's constructor is working like

```csharp
using System;

namespace Sandbox
{
	public partial class MyGame : Game
	{
		public MyGame()
		{
			foreach (Type type in TypeLibrary.GetTypes<Weapon>())
			{
				var vr = TypeLibrary.GetAttribute<WeaponAttribute>(type);

				if (vr?.TmpType != null)
				{
					Log.Warning(TypeLibrary.GetDescription(vr.TmpType).Name);
				}
			}
		}
	}

	public abstract partial class Ammo : Prop { }
	[Library("TestAmmo")] public partial class TestAmmo : Ammo { }

	public abstract partial class Weapon { }
	[Library("TestWeapon"), Weapon(typeof(TestAmmo))] public partial class TestWeapon : Weapon { }

	[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
	public class WeaponAttribute : Attribute
	{
		public Type TmpType { get; private set; }

		public WeaponAttribute(Type tmpType) : base()
		{
			TmpType = tmpType;
		}
	}
}

```

**Comment by garrynewman** [comment]
I think you're causing a bit of a race condition by using TypeLibrary inside the constructor of an attribute.. you're accessing it as it's filling it. The contents aren't going to be reliable because it's going to be determined by the order in which types are being added. Plus even worse than that, we add all this using threads - so you're accessing from multiple threads, while adding too.

I would recommend changing `PrimaryAmmoType ` to a dynamic property, and filling in the get to do all that logic you have in the constructor. If performance is a consideration you could cache the result.

Failing that, you should be able to implement `Sandbox.ITypeAttribute`, which will call `TypeRegister()` on the main thread, after everything has been processed.

**Comment by Alf21** [comment]
Ah yea, assumed the same, just wanted to mention that it broke after the PainDay III.
Thanks for the quick answer. I'm gonna use caching of the result in another place instead of the attribute's constructor :)
