### ISSUE TITLE
Hex Input in Color Picker

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#1913]
### For?

Hammer

### What can't you do?

I can't use hex codes with the color picker
![image](https://user-images.githubusercontent.com/65134886/172252675-b29e2818-4661-49c8-8953-d53be56355c4.png)

### How would you like it to work?

I would like for there to be an additional field where I can input hex codes, which then updates the RGB values

### What have you tried?

Inputting HSV or RGB individually instead of using a hex code

**Comment by bakscratch** [comment]
This was added a while back 
![image](https://user-images.githubusercontent.com/8184184/190645525-4929b2ed-76d8-452a-8ded-dc1e6b796bee.png)
