### ISSUE TITLE
GameResource:  [ResourceType]'d properties are being prefixed with "resource:"

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#1914]
### Describe the bug

I've got an asset, with some pretty basic properties - when I'm picking a vmdl from the assets browser, it's being prefixed with `resource:` which is causing problems. See below:

```csharp
[Category( "Setup" ), ResourceType( "vmdl" )]
public string Model { get; set; }
```

Example code in a GameResource. This is a problem because when doing stuff such as referencing sounds in code via their path, or precaching a model from a GameResource, it'll fail to find what we're looking for.
```
 11:39:54   ERROR: Could not calculate CRC for dependency: 'e:\sbox\sbox-contact\weapons\rust_smg\rust_smg.vmdl'
 11:39:54   ERROR: Could not calculate CRC for dependency: 'e:\sbox\sbox-contact\weapons\rust_smg\v_rust_smg.vmdl'
```
Shown in a GameResource's source file:
```
Model = resource:"weapons/rust_smg/rust_smg.vmdl"
```
When I remove that prefix, everything works fine.
```
Model = "weapons/rust_smg/rust_smg.vmdl"
```

### To Reproduce

I've got a repro project here: https://github.com/DevulTj/sbox-contact/tree/sbox_asset_resource_issue

All you have to do is enable the addon, load in, and try to compile `rifle.cwpn` in the Assets Browser. It'll fail because it's trying to point to something that doesn't exist, but in reality, it does.

### Expected behavior

Should pick up resources correctly.

**Comment by garrynewman** [comment]
The `resource:` in keyvalues is normal, it's allowing the asset/resource system to track dependencies. Not being able to fine the model isn't normal though, I'll look at why that is.

**Comment by DevulTj** [comment]
Latest commit seems to have fixed the issue.
