### ISSUE TITLE
Network property state change detection

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#192]
**What can't you do?**
Having a nicer system in place to detect when `[Net]` properties have changed. This could be an extra event that gets fired or an override in the NetworkClass we can play with. Currently, the only way to play with this is to override NetWrite & NetRead directly.

**How would you like it to work?**
```cs
[Net] public int MyProperty { get; set; }

[OnPropertyChanged("MyProperty")]
public void OnMyPropertyChanged(int LastValue, int NewValue) {
	Log.Info( $"MyProperty changed from { LastValue } to { NewValue }" );
}
```

**What have you tried?**
Currently, we can do something similar in regards to messing with the `NetRead` and `NetWrite` properties. However, this doesn't detect all known state changes(eg on the server-side). However, for client-sided state changes, this is no issue:
```cs
[Net] public int MyProperty { get; set; }

public void OnMyPropertyChanged(int LastValue, int NewValue) {
	Log.Info( $"MyProperty changed from { LastValue } to { NewValue }" );
}

public override bool NetRead( NetRead read )
{
	int lastPropertyValue = MyProperty;
	bool returnValue = base.NetRead( read );
	if( MyProperty != lastPropertyValue )
	{
		OnMyPropertyChanged( lastPropertyValue, MyProperty );
	}
	return returnValue;
}
```

**Additional context**

**Comment by Erlite** [comment]
I also made a request for this, except it'd be an attribute on the property and not a method (#156).

For now you can just use [the class conna made](https://github.com/Erlite/sbox-net-types/blob/master/NetworkVar.cs), it allows for state change detection on both server and client.

**Comment by garrynewman** [comment]
Would it only trigger when it changes as a result of the network changing it, or any set?

**Comment by Erlite** [comment]
Network changing it would be more useful since we can already just implement a setter to get notified of normal sets.
