### ISSUE TITLE
AnyGame.Current turns into Game class after hotload.

### ISSUE THREAD

**Issue by ArgoniumCode** [Facepunch/sbox-issues#1921]
### Describe the bug

After hotloading `AnyGame.Current` turns into `Game` class, instead of returning `AnyGame` class.
In my video AnyGame is basically SandboxGame.

### To Reproduce

1. Hotload.
2. Gratz, you now game `Game`, instead of `AnyGame`.

### Expected behavior

1. `Current` returns `AnyGame` class instead of `Game` class.

### Media/Files

https://youtu.be/uo4Wn1tpBIY

**Comment by Metapyziks** [comment]
Fixed by Facepunch/sbox@61fef2306086c7b02283d548fd202b87b93a9b75

Thanks for the report!
