### ISSUE TITLE
Add (SetSkin) to the IO of (prop_physics)

### ISSUE THREAD

**Issue by PixelQubed** [Facepunch/sbox-issues#1922]
### For?

S&Box, Hammer

### What can't you do?

I am unable to set the skin property via entity IO of the prop_physics entity.

### How would you like it to work?

I would like it to be simple so I can just set the skin of a prop_physics in the entity IO. I want to be able to a light emission on and off via the skin value through entity IO so when the lights do turn off the props emission skin isn't still set.

### What have you tried?

You can't currently target entity properties that haven't been exposed in the entity IO manager so there is nothing to try.

**Comment by robotboy655** [comment]
This was added a while ago as `SetMaterialGroup( "name" )` input.
