### ISSUE TITLE
Per pixel lighting is unreliable on light_spot.

### ISSUE THREAD

**Issue by PixelQubed** [Facepunch/sbox-issues#1923]
### Describe the bug

So when you have a light_spot set to "per pixel" lighting instead of baked, and you have a custom resolution set over 8k they become unreliable. There is no alternative to get the sharp shadows of CSM but have the cone effect of light_spot with more than one light. Even then the range is poor. They tend to flicker on and off for some reason if there is more than one set at resolution 8k. My use case uses three in three separate spaces. I require sharp shadows but can not use a light_ortho due to it being orthographic.

### To Reproduce

1. Create a light_spot.
2. Set the direct lighting type to "per pixel".
3. Change the resolution value from 0 to 8192 for both width and height.
4. Duplicate the light 3 times.
5. Spread the lights out from each other.
6. Witness the issue at hand.

### Expected behavior

You should be able to create the lights with no issue and have a high res for sharper shadows. When trying to emulate a light source from the ceiling that's about 1024 units away from the player but projected onto the environment, it should not flicker on and off with more than one light.

### Additional context

May not be necessary but here are my specs.

OS: Windows 11
CPU: AMD Ryzen 3900X
RAM: 2x 8GB 3200mhz Dual Channel
GPU: Gigabyte 1080TI 11GB VRAM

If you need any more info, just ask.

**Comment by xezno** [comment]
I don't think that 8192x shadow maps will ever be supported. Even if it did work (more about that in a second), you're trying to render the scene out multiple times at a pretty insane resolution.
It also looks like all shadow maps get put into an atlas which can be at most 16384x16384 in size (dx11 limit) so it'd require a lot of reworking and refactoring to get this to work in the first place.

**Comment by PixelQubed** [comment]
> I don't think that 8192x shadow maps will ever be supported. Even if it did work (more about that in a second), you're trying to render the scene out multiple times at a pretty insane resolution. It also looks like all shadow maps get put into an atlas which can be at most 16384x16384 in size (dx11 limit) so it'd require a lot of reworking and refactoring to get this to work in the first place.

Well, that makes sense. I never knew there was a limit on the DirectX end of things. I'll close this issue now, then. Thanks for explaining it.
