### ISSUE TITLE
Animgraph - "Auto-add" reference models is bugged

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1927]
### Describe the bug

There is an option that automatically adds all the models that are using that animgraph from modeldoc (I guess) but it never identifies that those models are already added so it adds all models repeatedly. 

Plus using this option and getting repeated models, causes a crash by changing the models using Blend2D, if I add the models manually it doesn't happen (I hope I'm right now).

### To Reproduce

Explainded in the video. 

### Expected behavior

Fix it.

### Media/Files

https://user-images.githubusercontent.com/40291120/173064767-72b21fd3-d5b6-454b-a8ab-0317a030df3b.mp4

**Comment by aylaylay** [comment]
try now
