### ISSUE TITLE
Sound Inspector - Dropdown menu for Decibel Strings

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1928]
### For?

Other

### What can't you do?

We can't see a full list of all the decibel levels in the inspector for sounds

### How would you like it to work?

There should be a dropdown menu for decibels in addition to the slider
![image](https://user-images.githubusercontent.com/39461072/173166218-7d1f585a-7fc9-4a53-8be4-5d9ff9e4da02.png)
It should show a list of all the levels and their reference names which we can click on
![image](https://user-images.githubusercontent.com/39461072/173166235-67dd3fb7-7a7e-449c-916e-85c186df2901.png)

### What have you tried?

Currently we have to mess around with the slider to find the right string. This works well with raw numbers but can be confusing with strings. If we want to look through the list of all strings we have to open up the screenshot.

**Comment by garrynewman** [comment]
Done
