### ISSUE TITLE
Drop arguments variableName & group from NetworkDirty

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#193]
**What can't you do?**
These currently are not being used at all and can lead to some confusion on marking a class as dirty as everything just gets networked either way.

**How would you like it to work?**
Either omitting the arguments or at least passing only the `variableName` to allow for partial dirtying of properties instead of the entire class.

```cs
NetworkDirty();

// Or if partial dirtying becomes a thing
public int MyProperty;

void Foo()
{
	NetworkDirty("MyProperty");
}
```

**What have you tried?**
N/A

**Additional context**

**Comment by garrynewman** [comment]
This isn't something people should have to worry about eventually, so this is a bit redundant
