### ISSUE TITLE
Animgraph - Full screen preview

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#1930]
### For?

Other

### What can't you do?

I would like to have the option to convert the preview to fullscreen.

Surely there are people like me who don't program and don't have the facility to bring everything to ingame, so creating quick recreations/videos in animgraph is something that would be nice to have.

### How would you like it to work?

Simply an icon that automatically gets the preview to full screen

![2dbcbf992463c2db05b47588d596b061](https://user-images.githubusercontent.com/40291120/173185227-ccffb6f7-6298-458d-89d6-28072cbd7137.png)

### What have you tried?

Change the scene by increasing the preview manually or edit the video, but it's a pain to do it every time you want to record something.

**Comment by bakscratch** [comment]
This was added to hammer as well, could also be nice for the Particle Editor.

**Comment by DoctorGurke** [comment]
I can see a use case for material editor and modeldoc as well 😅

**Comment by bakscratch** [comment]
> I can see a use case for material editor and modeldoc as well 😅

ModelDoc Already has it :)

**Comment by KaesarZZ** [comment]
> > I can see a use case for material editor and modeldoc as well 😅
> 
> ModelDoc Already has it :)

Where? I've never used it

**Comment by bakscratch** [comment]
Shift alt z

**Comment by KaesarZZ** [comment]
Oh I didn't know

**Comment by aylaylay** [comment]
Shift + Alt + Z

**Comment by KaesarZZ** [comment]
If you could make a reset of the layout when we close animgraph with fullscreen ON it would be perfect, I think "preserving" it is pointless. 

Thanks <3
