### ISSUE TITLE
Hammer - Add grid snapping to Interpolated Bridge helpers

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#1932]
### For?

Hammer

### What can't you do?

Snap Interpolated Bridge helpers to the grid.

### How would you like it to work?

To be able to snap the Interpolated Bridge helpers to the grid to make precise adjustments.

### What have you tried?

Nothing, unable to have them snap to the grid currently.

###  Additional Context 

what they do currently with no snapping

https://user-images.githubusercontent.com/23345567/173204432-d83b743f-0b83-482c-b6a2-4af744c077ef.mp4

**Comment by gvarados1** [comment]
this would be lovely!
