### ISSUE TITLE
Tabbing in and out of the dev client too many times makes explorer.exe unresponsive

### ISSUE THREAD

**Issue by ImWill0w0** [Facepunch/sbox-issues#1944]
### Describe the bug

I use references a lot when I work on maps, so I'm tabbing in and out constantly as I don't have a second monitor. If I tab in and tab out too much my taskbar will freeze up and I won't be able to use alt tab anymore. This hasn't happened with any other software or program I've used, it only happens when the dev client is opened and you are specifically tabbing in and out of it.

It especially gets annoying when I'll just be working on a map and I won't be able to tab back in or use the taskbar to select the dev client to save before restarting, losing progress and having to revert to an autosave.

### To Reproduce

1. Open s&box dev
2. Begin tabbing in and out of s&box dev, could be to your desktop or whatever, make sure you're tabbing in and out of the dev client specifically
3. You should notice that your taskbar will cease to function and alt tabbing will become useless, forcing you to restart or log out.

If no progress is made, spam alt tab repeatedly as much as you can to get the bug

### Expected behavior

The expected behavior should be that it doesn't make explorer.exe unresponsive, I should be able to tab in and out to check references without the expectation that I will be restarting my computer in about 10 minutes

### Additional context

I'm running Windows 10

**Comment by JamDoggie** [comment]
Can't reproduce on Windows 11 as far as I can tell. Running on the beta branch (Windows 11 build 22621.160)

**Comment by MaxLebled** [comment]
Couldn't reproduce on Windows 10. Please share more details for your repro. e.g. show how your window is laid out, if you have any third-party programs running that may hook into games (RTSS, GeForce Experience, etc.)

**Comment by ImWill0w0** [comment]
![Ry4v2bIKkt](https://user-images.githubusercontent.com/28235017/174220957-81239ccd-6c73-4a17-94cd-4d42d394fae2.png)
![KiGyVJkiSo](https://user-images.githubusercontent.com/28235017/174220960-9269b33c-a58f-407f-aabe-d102da1580c5.png)
![Speccy64_COw8LiImPZ](https://user-images.githubusercontent.com/28235017/174220991-dd1b86b7-aecd-47fb-b263-7492302916de.png)

I don't believe I have anything running that hooks into the game opened

**Comment by KingOfTheFBI** [comment]
I was not able to reproduce this exact situation. But there is and has been a lot of issues with the editor when you have multiple windows open in it. For ex if I'm running hamming and have a level open hammer stutters a lot. But it will randomly stop lagging and go back to full speed so its not a hardware issue as far as I can tell. Having modeldoc and material editor open does something similar.
