### ISSUE TITLE
Images are blurry

### ISSUE THREAD

**Issue by DaddyFrosty** [Facepunch/sbox-issues#195]
**Describe the bug**
Images are blurry. The only way to have them not be blurry is if you override UpdateScale and don't call base (leaving scale = 1), and resize the window to different resolutions.

**To Reproduce**
Override UpdateScale function to not do anything aka leave Scale to 1.
Resize window randomly until UI Icons are not blurry.

**Expected behavior**
Images to not be blurry.

**Screenshots**
http://share.willswebsite.net/sbox-dev_9pDdhwNBvb.png
http://share.willswebsite.net/sbox-dev_CmbIIr5Sbk.png

**Additional context**
Console prints out Width/Height Scale ( this is the scale that the UI uses )
This problem persists even with a proper vanilla UpdateScale function, but instead, any resolution produces blurry images.

**Comment by DaddyFrosty** [comment]
The issue was due to my lack of IQ.

**Comment by rtm516** [comment]
Care to share for future people?

**Comment by DaddyFrosty** [comment]
Don't position anything unevenly eg 2.5px from the left, anywhere leading up to the image.

**Comment by rtm516** [comment]
Ah yea, you shouldn't be using decimal pixel amounts.
