### ISSUE TITLE
ResourceLibrary.Get isn't retrieving assets 

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#1950]
### Describe the bug

I'm using ResourceLibrary.Get from a string path defined by a Hammer Entity - in my case, to load dynamic light configurations for my time of day system. As of right now, it's not finding those assets.

The GameResources seem to be loading correctly, their PostLoad method runs just fine - but ResourceLibrary.Get is not retrieving the same resources. 

### To Reproduce

1. Use ResourceLibrary.Get on an asset path
2. Observe that it's retrieving null

### Expected behavior

It should be retrieving the correct Resource

### Media/Files

https://github.com/DevulTj/sbox-spire/blob/master/code/Environment/Entities/DayNightController.cs#L147

I've got a game that is experiencing this problem. The link above shows the usage of ResourceLibrary.Get - the GameResource it's trying to load is in the same file.

**Comment by gvarados1** [comment]
I'm having the same issue

**Comment by S4TURN21** [comment]
Same issue.
But as @yuberee mentioned before in Discord, you can store your resource in static dictionary during PostLoad, using resource name as key. And then use ResourceType.Dictionary["name"] to retrieve it.
For example:
```
[GameResource( "Curve Float", "curvef", "Curve Float." )]
public partial class CurveFloat : GameResource
{
  [Property]
  public Curve Curve { get; set; }
  
  public static IDictionary<string, CurveFloat> All => _all;
  internal static Dictionary<string, CurveFloat> _all = new();
  
  protected override void PostLoad()
  {
    base.PostLoad();
    
    if ( !_all.ContainsKey( this.Name ) )
    {
       _all.Add( this.Name, this );
    }
  }
}
```
And then:
`CurveFloat.All["normalmovement"]`
