### ISSUE TITLE
Animgraph - Resize Note Text Box

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1953]
### For?

Other

### What can't you do?

We can leave notes at the top of animgraph nodes, but we can't resize the note text box. It's hard to read if there's a lot of text because the box is so small and you have to scroll.

### How would you like it to work?

There should be a line that we can click and drag to resize the text box
![image](https://user-images.githubusercontent.com/39461072/174459396-874f892d-e420-466b-9b5a-3f192b88a8bd.png)

### What have you tried?

Currently we can't resize the text box. We have to scroll.

**Comment by aylaylay** [comment]
Added

**Comment by gvarados1** [comment]
Epic! Thanks :)
