### ISSUE TITLE
Animgraph - Right Click -> Create node -> Search Box

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1954]
### For?

Other

### What can't you do?

We can't search when creating nodes in the animgraph. There's a huge list with a ton of options but no search box. This box is so big that is almost takes up the entirety of a 1080p display. It's really hard to find anything on it.

### How would you like it to work?

When you right click -> Create node, there should be a search box
![image](https://user-images.githubusercontent.com/39461072/174459560-e371c75c-bf0d-46b9-8760-9eab8cd46fbb.png)

This search box should be active immediately and we should be able to type without having to specifically click on it
similarly to the search/filter box in the F1 menu
![image](https://user-images.githubusercontent.com/39461072/174459542-19aa289c-42fa-4aba-9b16-d9b214148193.png)

### What have you tried?

currently we have to spend 30 seconds looking through the huge list to find the correct node type

**Comment by gvarados1** [comment]
Here's how it looks in unity 
![image](https://user-images.githubusercontent.com/39461072/174459682-9da3783e-06bd-4435-8456-ada7f12af9ad.png)

**Comment by aylaylay** [comment]
I've added a search box, I'm not sure about adding categories for it, wouldn't even know what categories to sort them into

**Comment by gvarados1** [comment]
perfect! thanks!

**Comment by aylaylay** [comment]
Max came up with some categories so now they're in 
![sbox-dev_nEiyubXrVw](https://user-images.githubusercontent.com/1667289/176810834-f9d5497b-541d-4dbe-b9e8-c242ad8b880e.png)
