### ISSUE TITLE
Animgraph - Autosave

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1955]
### For?

Other

### What can't you do?

There is no auto-save for the animgraph editor. The autosave folder is generated but nothing is ever saved there.

### How would you like it to work?

There should be an auto-save feature similar to hammer
![image](https://user-images.githubusercontent.com/39461072/174466443-adddca0b-a28d-4a5b-9812-706aaac2301e.png)

### What have you tried?

currently if we want auto-save we have to setup auto-hotkey or another tool

**Comment by aylaylay** [comment]
It should now autosave - no ui for it yet, I'll do it later

**Comment by gvarados1** [comment]
Perfect! Thanks!
