### ISSUE TITLE
animgraph_preview command doesn't work anymore

### ISSUE THREAD

**Issue by S4TURN21** [Facepunch/sbox-issues#1957]
### Describe the bug

Previously using animgraph_preview "X" (where X is the entity you wish to preview) and loading graph in the tool allowed to preview graph in real-time. But now using animgraph_preview command doesn't do anything anymore.

### To Reproduce

1. Run your game.
2. Type and run **animgraph_preview "X"** command (where X is the entity you wish to preview, example: "Player 83"). Entity has to have your animgraph.
3. Load the graph yourself in the tool.
4. Press play.
5. Observe nothing.

### Expected behavior

All animgraph parameters, states and animations in tool should be synchronized with entity's.

**Comment by aylaylay** [comment]
There will be a better system for this in the future built into the game tool ui
