### ISSUE TITLE
Substance material .sbsar support

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1959]
### For?

S&Box, Other

### What can't you do?

Unable to tweak & exposed parameters of a Substance Material `.sbsar` and view the changes within the S&box Editor.

### How would you like it to work?

1. Click on the `.sbsar` file within the `assets browser`

2. Inspector will open up with the following

- preview window of the material. 
- shader dropdown box ( simple, complex, etc ) 
- ¹output checkboxes ( color, normal, rough, etc ) 
- ²All Exposed parameters such as Output Size, Random Seed, etc. 

3. A button somewhere to save a `.vmat`  when done tweaking the material. The final generated vtex files will be saved as well.

¹You would be able to toggle what texture maps you want to export.

²You would be able to tweak these parameters and see the material update in real-time in a preview window. Performance would be dependent on how complex the material happens to be.

### What have you tried?

Load the `.sbsar` with [Substance Player](https://substance3d.adobe.com/documentation/sp31/substance-player-2294742.html), tweak settings, export the textures to S&box, then finally create a material with the textures. 

### Additional context

While using substances player does the job well enough, I'd rather prefer an integrated, in-engine solution to tweak substance materials and view them with the appropriate shaders to see how my material will look "exactly" in-engine without having to first export and manually create a vmat.

**Comment by DoctorGurke** [comment]
This seems excessive for the editor when it's a proprietary format that has editors/tools already

**Comment by QuackCocaine** [comment]
Yea..fair enough 😅 I guess, I don't know why I tend to sometimes suggest stuff like this. Even then integration would be dope though.
