### ISSUE TITLE
Selecting "Empty Map" in addon config does not apply retroactively to games you've already loaded into

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#1966]
### Describe the bug

If you create & start a lobby in a game with, for example, `facepunch.construct` as the map, and then change the game's config to use "Empty map" - you'll be unable to change it and it'll always use `facepunch.construct`.

### To Reproduce

1. Start a lobby on a game you own, make sure the game is set up to allow for any map, use any map.
2. After loading into that game, leave the lobby.
3. Change the addon config so that it uses "empty map" as its map selection, save it
4. Restart the engine
5. Try and start a lobby... rather than loading into an empty map, you'll load into whatever map you chose for step 1

### Expected behavior

Having a game set up to use "empty map" should always load into an empty map regardless of what you did before.

### Additional context

Getting around this is as simple as deleting the cookie entry for it in `sbox/config/menu.cookies.json`, but this isn't very user friendly.

**Comment by cr4yz** [comment]
This should be fixed in the next update, please let me know if it gives you any more trouble

**Comment by xezno** [comment]
This is fixed now, thanks Crayz 🙂
