### ISSUE TITLE
Partial classes breaking codegen.

### ISSUE THREAD

**Issue by FoxTTT** [Facepunch/sbox-issues#1968]
### Describe the bug

When you try to split a class into seperate you will arrive to the issue:

Error SB5000  Code Generator Crashed at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add( String hintName, SourceText source )   at Sandbox.Generator.Processor.Run( CSharpCompilation c ) - The hintName **'CarriableItem_CarriableItem.cs'** of the added source file must be unique within a generator.

### To Reproduce

Repro attached.

### Expected behavior

To be able to work and have partial classes not crash the codegen.

### Media/Files

[bug_report_test.zip](https://github.com/Facepunch/sbox-issues/files/8967131/bug_report_test.zip)

**Comment by handsomematt** [comment]
just to confirm, the error is that you're doing this in the same file and not separate files?

```csharp
public partial class CarriableItem
{
...
}

public partial class CarriableItem
{
...
}
```

**Comment by FoxTTT** [comment]
Yeahh.

> just to confirm, the error is that you're doing this in the same file and not separate files?
> 
> ```cs
> public partial class CarriableItem
> {
> ...
> }
> 
> public partial class CarriableItem
> {
> ...
> }
> ```

Yeah

**Comment by Adesii** [comment]
Isn't the point of partial classes that you can put them into seperate files? why use Partial classes in the same file.

**Comment by handsomematt** [comment]
it is a confusing usage, but I'll fix this anyway
