### ISSUE TITLE
Introduce ReadAllBytes to BaseFileSystem

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#197]
**What can't you do?**
There's a ReadAllText method already, might as well expand it to allow for ReadAllBytes to allow for throwing entire byte streams into memory

**How would you like it to work?**
```cs
byte[] myFileBytes = FileSystem.Mounted.ReadAllBytes( "my_file.bin" );
```

**What have you tried?**
```cs
BinaryReader reader = new( FileSystem.Mounted.OpenRead( "my_file" ) );
byte[] myFileBytes = reader.ReadBytes( (int)reader.BaseStream.Length );
```

**Additional context**

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
