### ISSUE TITLE
trigger_push

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1970]
### For?

Hammer

### What can't you do?

There should be a default trigger_push entity. It's a pretty generic feature that I've found myself wanting to use on maps for multiple games.

### How would you like it to work?

Same as Source1, but using the new tag system

### What have you tried?

Currently each game needs to implement this individually

**Comment by robotboy655** [comment]
Added as `push_volume` entity. Let us know if it lacks some functionality you actually need.

**Comment by bakscratch** [comment]
Seems like its all there and working 👍
