### ISSUE TITLE
Increase brightness in the clothing menu

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1972]
### For?

S&Box

### What can't you do?

The lighting in clothing menu is very dark. It doesn't seem that dark when you're actually using it in-game but it's noticeably dark in videos. There's also a lot of fog that can wash out the colors.

### How would you like it to work?

The lights in the clothing menu should be brighter

### What have you tried?

Any time I show the clothing menu in my videos I have to brighten it.

Default:
![image](https://user-images.githubusercontent.com/39461072/175715209-312b35e3-eaa9-45cd-a4ea-ea955ae86a5a.png)

Brightened for the video:
![image](https://user-images.githubusercontent.com/39461072/175718220-925d296c-e5c9-4c82-9706-ccdd236b282b.png)

**Comment by DevulTj** [comment]
Edited this a bit.. Though it'll probably get scrapped and redone in the future so don't worry about it being imperfect.
