### ISSUE TITLE
Hammer - Hotkey to align workplane to selected object 

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#1974]
### For?

Hammer

### What can't you do?

Quickly Align the workplane to a selected Hammer mesh or object with a hotkey.

### How would you like it to work?

in Dota 2 tools, this is bound to `Alt`+`Q`  but I think that conflicts with the select tool so any other key combo should work really.

 **Video of quickly using the hotkey to align the workplane to a hammer mesh**

https://user-images.githubusercontent.com/23345567/175752741-c8b270c4-7213-4310-ad1a-d67a2ffad4f4.mp4

 
### What have you tried?

Using the eyedropper manually to do so, but I find the hotkey to be a tad bit quicker.

**Comment by handsomematt** [comment]
Thanks for the request, this is really useful - I've implemented it and put it on Alt + Q let me know how it works out for you.

**Comment by QuackCocaine** [comment]
Works like a charm, Thanks Matt!
