### ISSUE TITLE
Per-Material Color Tints

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1975]
### For?

S&Box

### What can't you do?

We can set per-material material overrides on a model using `SetMaterialOverride( SkinMaterial, "skin" );` but as far as I can tell we can't set per-material color tints.

### How would you like it to work?

We should be able to add additional  parameters to specify which material we're tinting similarly to `SetMaterialOverride`

### What have you tried?

A recent update added flesh to the clothing items themselves. Here I'm applying a slightly random color tint to the zombies. This doesn't work anymore because I can not tint the flesh that is attached to the clothes.
![image](https://user-images.githubusercontent.com/39461072/175795927-eecaf7bd-5827-4493-b38d-b801141d12dc.png)

As a workaround, I'd have to make a bunch of slightly different zombie skins instead of using a random tint. I want to do this anyways but currently can't because we don't have the source files for the citizen's skins..

**Comment by garrynewman** [comment]
This seems like a bad idea. The skin should be updated (noted in your other issue) rather than being able to set specific material parameters.

**Comment by gvarados1** [comment]
I thought this was something that wouldn't get added but figured I'd ask anyway 👍
