### ISSUE TITLE
Recording while starting a game will cause a hang

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#1978]
### Describe the bug

Whenever I am recording and I either start a new game or restart the current one, the frames will drop to 1fps.
The performance graph shows that Rendering takes up more than 1000ms.

### To Reproduce

1. While in the menu, start a recording
2. Create and launch a new lobby on any game

Alternatively

1. While in a game, start a recording
2. Restart the game

### Expected behavior

To not decimate fps

### Media/Files

![image](https://user-images.githubusercontent.com/59583743/175815483-d7872797-e523-48a8-8704-053cc99b78c8.png)

### Additional context

I remember it happening while I was hosting a serve oncer, the players reported not being able to move.
No other context

**Comment by aylaylay** [comment]
Try it now, it should handle it better

**Comment by yuberee** [comment]
FPS are normal after the game loads while recording. :+1:
![image](https://user-images.githubusercontent.com/59583743/176267631-4d9d769f-da21-46ea-8ea4-d7c8dcef7fb9.png)
