### ISSUE TITLE
Map.Physics.IsPointWater does not work

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#1980]
### Describe the bug

Map.Physics.IsPointWater seems to always return false, I tested this by checking the player, weapon, and bullet traces while swimming on construct.

Picture for reference.

![20220627023025_1](https://user-images.githubusercontent.com/4988198/175838046-99342ef7-6e23-4bf1-a046-246787b1d484.jpg)

**Comment by garrynewman** [comment]
This shouldn't really be exposed, in engine it just returns false.

**Comment by timmybo5** [comment]
Is there an alternative or should I just do a trace that only hits water to check a position?

**Comment by timmybo5** [comment]
I see, thanks for the suggestion! :)
