### ISSUE TITLE
Add Navmesh to DM98 maps (Datacore, Crossfire)

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1981]
### For?

S&Box

### What can't you do?

The dm98 maps don't have a navmesh.

### How would you like it to work?

The DM98 maps (Datacore, Crossfire) should have a navmesh.

### What have you tried?

There is nothing to try. The maps don't have a navmesh.

**Comment by ogniK5377** [comment]
This issue is not related to s&box. Please file the issue in the correct repos,
https://github.com/Facepunch/sbox-dm98-datacore
https://github.com/Facepunch/sbox-dm98-crossfire
