### ISSUE TITLE
Expanded Glow Component

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1984]
### For?

S&Box

### What can't you do?

We can't do advanced things with the Glow component. Currently we can only set the Range, Color, and Active.

### How would you like it to work?

We should be able to set glow through walls and glow border thickness. The glow behind walls should have it's own color separate from the main glow.

### What have you tried?

Currently we'd have to make our own glow to do anything advanced

### Additional context

I think we used to have a lot more features but they were removed when Glow was turned into a component

**Comment by ArgoniumCode** [comment]
Praying for this 🥺

**Comment by gvarados1** [comment]
The glow was updated but the new glow is actually more broken than the old one. Would be lovely if it worked 👍

**Comment by DevulTj** [comment]
We've got an issue internally for this https://github.com/Facepunch/sbox/issues/450, so closing this as dupe
