### ISSUE TITLE
RenderAttributes.Set for Vector2/float2

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#1985]
### For?

S&Box

### What can't you do?

Pass a Vector2 from C# to a shader's float2 attribute with `Render.Attributes.Set` or `SceneObject.Attributes.Set`

### How would you like it to work?

Exactly how the current float/Vector3/Vector4 attribute setters are.

### What have you tried?

Set two separate float attributes, or pass a Vector3 and ignore the Z component.

**Comment by ogniK5377** [comment]
Should be on the next update
