### ISSUE TITLE
Implement font-style style property.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#199]
**What can't you do?**

Italicize text elements.

**How would you like it to work?**

Implement `font-style`.

**What have you tried?**

Checking if `font-style` had been implemented.

**Additional context**

I see italic fonts in the base fonts folder. Am I missing something?

https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#propdef-font-style

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
