### ISSUE TITLE
Specifying a relative path to stylesheets from HTML files fails causes the scss to fail to hotload

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#1991]
### Describe the bug

My directory structure is a bit different from most s&box developers. Instead of placing my template, cs, and stylesheet files all together, I have a subdirectory in my UI dedicated to Stylesheets.

`UI/Stylesheets/MyStylesheet.scss`
`UI/Example/MyPanel.cs`
`UI/Example/MyPanel.html`

When specifying a **relative path** in your html file, the scss files fail to hotload (saving changes simply causes nothing to happen). Using the absolute path works fine, though.

`<link rel="stylesheet" href="/UI/Stylesheets/ExperienceDrops.scss" />` <-- This works
`<link rel="stylesheet" href="../Stylesheets/ExperienceDrops.scss" />` <-- This doesn't

This only seems to occur when the relative path is to a parent folder:
`<link rel="stylesheet" href="./ExperienceDrops.scss" />` <-- This works
`<link rel="stylesheet" href="../Stylesheets/ExperienceDrops.scss" />` <-- This doesn't

### To Reproduce

1. Download the reproducible
[relative-path-repro.zip](https://github.com/Facepunch/sbox-issues/files/9028977/relative-path-repro.zip)
2. Navigate to `/UI/Stylesheets/MyPanel.scss`
3. Try changing something
4. Notice the file does not trigger a hot reload

### Expected behavior

The SCSS files declared with a relative path should hotload correctly.

**Comment by cr4yz** [comment]
This should be fixed in the next build.  Lemme know if you have anymore issues with it

**Comment by trundler-dev** [comment]
Works great! Thanks Crayz!
