### ISSUE TITLE
Adding conditions to state machine connectors while animgraph simulation is running causes crashes

### ISSUE THREAD

**Issue by mewtek** [Facepunch/sbox-issues#1992]
### Describe the bug

When attempting to add a parameter to a state machine node while running the simulation of the animation graph, the s&box dev tools crash.

### To Reproduce

1. Open a state machine
2. Select a node connector
3. Add any form of condition
4. Watch in horror as your dev tools crash and burn in front of your eyes, the flames ungulfing your tools as all life in your animation graph fades in a flash... and a prompt to close the window.

### Expected behavior

The expected result is to be blocked off from adding a condition to a node line,

**Comment by aylaylay** [comment]
Conditions and tags UI should now be disabled when preview mode is active
