### ISSUE TITLE
Creating a string property initialized to string.Empty throws CS0182

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#1993]
### Describe the bug

When I try to create a string property with it initialized to string.Empty S&box fails to compile the game. It throws a CS0182 error and cites a section of code that does not contain any problems.

### To Reproduce

1. Add a string property.
2. Initialize the property to string.Empty.
3. S&box fails to compile.

### Expected behavior

For the code to compile without errors.

### Media/Files

Code:
![image](https://user-images.githubusercontent.com/11802285/177005751-274a6b34-aa22-439e-8019-f41155537a38.png)

Error:
![image](https://user-images.githubusercontent.com/11802285/177005712-3d7a532f-d62f-4619-ae75-7bb86e7dc43c.png)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by peter-r-g** [comment]
Fixed, thank you!
