### ISSUE TITLE
Prevent the Asset Browser from focusing everytime you launch the editor

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#1995]
### For?

S&Box

### What can't you do?

Everytime we launch the editor, the asset browser will always pop in front of the actual editor, sometimes even with a slight delay which is inconvenient.

### How would you like it to work?

I'd like it to work so it doesn't focus in everytime you launch the editor but stays in the background and let the s&box editor be the main window.

### What have you tried?

When I'm on my regular setup I usually just move it on my second monitor which is slightly less annoying, but on a one monitor setup it can get pretty awkward.

**Comment by yuberee** [comment]
Instead of not focusing I'd be fine with having an option to not open it at all.
