### ISSUE TITLE
SetVolume and SetPitch aren't working on UI sounds anymore.

### ISSUE THREAD

**Issue by Bumpy226** [Facepunch/sbox-issues#1997]
### Describe the bug

`SetVolume()` and `SetPitch()` don't work anymore on UI sounds. I've used these to control music, but a recent update seems to have broken it. `SetRandomPitch()` does still work on UI sounds however.

### To Reproduce

Create a sound definition with the UI checkbox checked. Then try to play the sound like so and alter it's volume/pitch:

```cs
Sound mySound = Sound.FromScreen( "SoundName" );
mySound.SetVolume( 0.5f );
mySound.SetPitch( 0.5f );
```

Also notice how unchecking the UI checkbox and re-saving causes the volume and pitch to start working again.

### Expected behavior

The expected result should be for the volume and pitch to change when the representing functions are being called.

**Comment by Fortune117** [comment]
I'm having this issue on sounds played from an entity as well. Setting the volume doesn't change it it all.

**Comment by Geeknerd1337** [comment]
Currently still experiencing this for screen sounds. Blocking some of my gamemodes which use dynamic music.

**Comment by garrynewman** [comment]
Sorry this took so long to fix :(
