### ISSUE TITLE
Editor Panel Inspector does not respect dpi scaling

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2003]
### Describe the bug

When using the panel inspector, the outlines for the panels do not respect dpi scaling.

![image](https://user-images.githubusercontent.com/57276947/177166408-ed195889-d190-441a-b1af-9437cbafc094.png)

This can make it very difficult to debug panels.

### To Reproduce

1. Increase or decrease your [dpi scaling](https://www.digitaltrends.com/computing/how-to-adjust-high-dpi-scaling-in-windows-10/).
2. Open the editor, and the panel inspector
3. Hover over elements. Notice the outlines are in the incorrect position.

### Expected behavior

The panel outlines should properly outline the panels.

### Additional context

Windows 10

**Comment by garrynewman** [comment]
I fixed this on my tier2addons branch

**Comment by trundler-dev** [comment]
I can verify this is now fixed. Thanks Garry!
