### ISSUE TITLE
Add PreVelocity, PostVelocity, PreAngularVelocity of the other entity to CollisionEventData

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#2006]
### What it is?

Assuming the summary is correct, CollisionEventData currently gives you the PreVelocity, PostVelocity, and PreAngularVelocity of your entity.

### What should it be?

Assuming OnPhysicsCollision gets called twice, once for each entity involved in the collision, it would be useful to have the pre and post velocity for the other entity as well as our own. Would the engine support this?
It's worth noting that the pre/post velocity data for the other entity was present in source 1's gamevcollisionevent_t, so it seems like this would be useful for replicating s1 style impact logic etc

**Comment by handsomematt** [comment]
I've changed the API so you now have the full collision data of both entities involved. I've also added the Surfaces of each entity that has collided. Let me know if there's anything up with it.

```csharp
public struct CollisionEntityData
{
	public Entity Entity;
	public PhysicsShape PhysicsShape;
	public Surface Surface;
	public Vector3 PreVelocity;
	public Vector3 PostVelocity;
	public Vector3 PreAngularVelocity;
	public Vector3 PostAngularVelocity;
}

public struct CollisionEventData
{
	public CollisionEntityData This;
	public CollisionEntityData Other;

	public Vector3 Position;
	public Vector3 Velocity;
	public Vector3 Normal;
	public float Speed;
}
```
