### ISSUE TITLE
Right Click .fbx-> Create Model

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2009]
### For?

Other

### What can't you do?

We can't Right Click a mesh file (.dmx, .smd, .fbx, .obj, .vox) -> Create Model in the new asset browser. We can do this in the legacy asset browser but not the new one.
![image](https://user-images.githubusercontent.com/39461072/177230209-fb953de6-5d22-4819-8ad7-774a452b445c.png)

### How would you like it to work?

When I Right Click an mesh I should have the option to create a vmdl, similarly to the legacy asset browser:
![image](https://user-images.githubusercontent.com/39461072/177230462-654e83c3-8a91-441c-9063-54e1a1378f7d.png)

### What have you tried?

Currently we have to either use the legacy asset browser or create a vmdl separately and manually add the rendermesh

**Comment by handsomematt** [comment]
Done, thanks for the issue
