### ISSUE TITLE
Expansion to MethodDescription

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#2012]
### What it is?

Currently, the `Sandbox.MethodDescription` you get from `TypeLibrary.FindStaticMethods` is very limited. It only exposes the invoke method that you can't get a return value from.

Right now the workaround is to abuse attributes to attach data about parameters and a methods return type. In the case of the return value, you can't actually return the value. Because of that, you have to set a publically accessible static member and make the invoking side handle that.

### What should it be?

The following items should be added/changed on `Sandbox.MethodDescription`
* ReturnType property > Returns [MethodInfo.ReturnType](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.returntype?view=net-6.0).
* GetParameters method > Returns the result of [MethodBase.GetParameters](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase.getparameters?view=net-6.0#system-reflection-methodbase-getparameters).
* Invoke method > The same as it is currently but returns an object as it is defined in [MethodBase.Invoke](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase.invoke?view=net-6.0#system-reflection-methodbase-invoke(system-object-system-object())).

If exposing ParameterInfo in the GetParameters method is a concern. Creating a `ParameterDescription` would work and could include the following items:
* Attributes > Returns the attributes on the parameter like how `Sandbox.MemberDescription` already does.
* Name property > Returns [ParameterInfo.Name](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.name?view=net-6.0).
* ParameterType property > Returns [ParameterInfo.ParameterType](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.parametertype?view=net-6.0).
* IsIn property > Returns [ParameterInfo.IsIn](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.isin?view=net-6.0).
* IsOptional property > Returns [ParameterInfo.IsOptional](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.isoptional?view=net-6.0).
* IsOut property > Returns [ParameterInfo.IsOut](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.isout?view=net-6.0).

**Comment by garrynewman** [comment]
Thanks, this should all be mostly covered now. Sorry it took so long.

If there's any other functionality you think we're missing please make a new issue 👍
