### ISSUE TITLE
Creating a generic multi-dimensional array creates an NRE in the whitelist

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#2014]
### Describe the bug

Create a multi-dimensional array of a templated type and it will fail to load the game mode with something not allowed in the whitelist. When it shows the error, instead of giving the not allowed type and where it comes from. It will just show the NRE text.

### To Reproduce

1. Create a method/class/etc that uses templates.
2. Create a multi-dimensional array of type T.
3. Load game mode.
4. S&box complains that something is not in the whitelist. 

### Expected behavior

For the code to compile and not hit any un-whitelisted items

### Media/Files

Code:
![image](https://user-images.githubusercontent.com/11802285/177443967-3eb6e1e5-a8cd-47e4-8161-68f5f0a5d7a3.png)

Error:
![image](https://user-images.githubusercontent.com/11802285/177443744-a44324a3-d4ff-4702-8e7c-d6bcedaaf6da.png)

**Comment by drongood12** [comment]
Bump
