### ISSUE TITLE
Ability to play scenes (vcd files) on entities in C#

### ISSUE THREAD

**Issue by randomperson189** [Facepunch/sbox-issues#2017]
### For?

S&Box

### What can't you do?

I can't play vcd files on entities through C# which allows you to add lipsync, expressions, gestures, etc. They can be created with the Faceposer tool

### How would you like it to work?

Make a function like Entity.PlayScene(path) or Entity.PlayVCD(path)

### What have you tried?

I haven't found any possible alternatives so far

### Additional context

GMod has a lua function called Entity:PlayScene(path) so you can basically call that on anything such as NPCs and Players

**Comment by garrynewman** [comment]
This is something we need to evaluate. We need to weigh up using the old tool vs creating our own tools etc, I'd expect to get to this within the next couple of months.

**Comment by garrynewman** [comment]
Closing this.. after evaluation I think we're going to be best off in the long run making our own system for this. It shouldn't take long to get the basics done.

I imagine lip sync and the choreography to be different issues, so I'd prefer to split them up so we don't have to use faceposer for it.
