### ISSUE TITLE
Sounds of "Content" Addon Type have to be recompile each game launch

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#2022]
### Describe the bug

Hello,

When I try to use Sounds provided by a "Content" Addon Type :
![image](https://user-images.githubusercontent.com/5229571/178117213-341a0c88-f0f9-47d7-8c82-28180c57e880.png)

I have to constantly recompile each sound of this Addon for being able to work in another Addon Type like Game.

### To Reproduce

1. Create an Addon Type "Content"
2. Adds sounds to this Addon and "Create Sound Definition" for each
3. On your Addon Type "Game", use the new fresh created Sound Definition
4. Restart your game
5. Try to play your sound on your Addon Type "Game" : this doesn't work. You have to recompile the "Sound Definition"

### Expected behavior

I think sounds in an Addon Type "Content" have to recompile automatically as same as you put sounds in an Addon Type "Game".

### Media/Files

https://user-images.githubusercontent.com/5229571/178117560-f197ba73-6744-4b07-9cb7-be084ef3993a.mp4

**Comment by DrakeFruit** [comment]
content projects don't exist anymore, is this still relevant?
