### ISSUE TITLE
Cubemaps fail to compile fully

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#2027]
### Describe the bug

When attempting to build Cubemaps in preview lighting or during a full compile the `.vtex_c` files for the cubemaps don't get built. A `.mdmp` file from resourcecompiler is produced when the compile "finishes" either in the map `.vpk` itself or in the maps _bakeresourcecache folder/`.vpk`.

### To Reproduce

1. compile preview lighting in hammer with the provided map.
3. observe that the probe shows full black and that there's `.mdmp` files in the _bakeresourcecache folder where the `.vtex_c` for the cubemaps should be.

### Expected behavior

for cubemaps to be compiled & to show up in-game and or in hammer.

### Media/Files

mini-dump files : 
[minidumps.zip](https://github.com/Facepunch/sbox-issues/files/9095306/minidumps.zip)

map :
[issue.zip](https://github.com/Facepunch/sbox-issues/files/9095343/issue.zip)

### Additional context

the cubemap `.exr` & raw `.vtex` files generate fine but the step where resourcecompiler generates the `.vtex_c` files is shitting the bucket somehow.

**Comment by KingOfTheFBI** [comment]
To me it seems like only metallic textures are messing up

**Comment by samzanemesis** [comment]
Does this still happen

**Comment by QuackCocaine** [comment]
Yes

**Comment by QuackCocaine** [comment]
https://user-images.githubusercontent.com/23345567/184702819-ba0af92d-9e78-43c3-bb3d-dfa7f5e04471.mp4

**Comment by Xenthio** [comment]
Confirming, still cannot build on my end.

**Comment by urnotnick** [comment]
Still happens, if you try to manually compile a cube map it'll crash your game.

**Comment by garrynewman** [comment]
Fixed one bug with vrad2 not running. We're definitely seeing some kind of errors when creating cubemaps here though.. 

```
PS C:\git\sbox-sandbox\maps\_bakeresourcecache\untitled_1_baked> C:\git\sbox\game\bin\win64\resourcecompiler -i env_cubemap_3.vtex -verbose -f
C:\git\sbox-sandbox\maps\_bakeresourcecache\untitled_1_baked\env_cubemap_3.vtex:
Bad texture dimension type 4 for texture "ggxcubemapblur_sourcecubemap.vtex".. wanted 1 - returning error texture in CTextureManagerDx11::GetResourceView
Bad texture dimension type 4 for texture "ggxcubemapblur_sourcecubemap.vtex".. wanted 1 - returning error texture in CTextureManagerDx11::GetResourceView
Bad texture dimension type 4 for texture "ggxcubemapblur_sourcecubemap.vtex".. wanted 1 - returning error texture in CTextureManagerDx11::GetResourceView
Bad texture dimension type 4 for texture "ggxcubemapblur_sourcecubemap.vtex".. wanted 1 - returning error texture in CTextureManagerDx11::GetResourceView
Bad texture dimension type 4 for texture "ggxcubemapblur_sourcecubemap.vtex".. wanted 1 - returning error texture in CTextureManagerDx11::GetResourceView
Bad texture dimension type 4 for texture "ggxcubemapblur_sourcecubemap.vtex".. wanted 1 - returning error texture in CTextureManagerDx11::GetResourceView
```

@samzanemesis is going to look at it today

**Comment by garrynewman** [comment]
As a shortcut repro:

[env_cubemap_3.zip](https://github.com/Facepunch/sbox-issues/files/9445357/env_cubemap_3.zip)

- Extract somewhere
- Open command prompt in its folder
- run `C:\git\sbox\game\bin\win64\resourcecompiler -i env_cubemap_3.vtex`

**Comment by QuackCocaine** [comment]
They are now behaving normally now thanks! 

![sbox-dev_ip0KhLomzO](https://user-images.githubusercontent.com/23345567/187247624-fa4aecc9-da47-4b9b-902a-92edc35d5a33.png)
