### ISSUE TITLE
Launcher toolbar and Tools toolbar do not appear in "View" dropdown

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#2028]
### Describe the bug

When you click on the "View" dropdown in the editor, the new Launcher toolbar as well as the Tools toolbar do not appear. Subsequently, if you right-click blank space on either of the toolbars, there are two extra unnamed tools at the bottom, which are supposed to be the launcher and tools toolbars. I'm putting these in the same issue because I believe they're related.

### To Reproduce

1. Open s&box tools.
2. Click the "View"/right-click blank space on either of the two toolbars.

### Expected behavior

Both toolbars should appear in both menus, and be easily toggleable.

### Media/Files

![image](https://user-images.githubusercontent.com/43252311/178554135-192f0681-7ad0-4b06-a173-b37577d494d5.png)
![image](https://user-images.githubusercontent.com/43252311/178554295-c2a0e579-5ffc-4253-9a44-5f0eb48aaf40.png)

### Additional context

All of the widgets that appear in both the "View" dropdown and right-click dropdown are marked with the [Dock] attribute, however when applying this to the Launcher to try to find a fix, the styling of the toolbar broke. It appears DockAttribute.Register() adds the marked widget to the dropdown, so maybe moving this initialization elsewhere is the fix?

**Comment by cr4yz** [comment]
Probably not needed anymore, the launcher has been embedded into the game window
