### ISSUE TITLE
editorconfig template has invalid indent settings

### ISSUE THREAD

**Issue by nywek** [Facepunch/sbox-issues#2029]
### Describe the bug

The `.editorconfig` file that is automatically generated whenever you create a gamemode using sbox-dev contains invalid settings for indendation.

This generated file contains the following settings:

```
[*.cs]
indent_style = tab
indent_size = tab
tab_size = 4
```

`tab_size` does not exist according to the [official website](https://editorconfig.org/#file-format-details) and instead should be called `indent_size`.
I imagine the correct settings would be:

```
[*.cs]
indent_style = tab
indent_size = 4
```

### To Reproduce

1. Launch `sbox-dev.exe`
2. Create a new `game` addon using the Addon Manager
3. Open the newly generated `.editorconfig` for this game addon
4. See that it contains invalid settings for indendation

### Expected behavior

The `tab_size` setting should not exist and `indent_size` should be set to `4` instead of `tab`

**Comment by handsomematt** [comment]
thank you
