### ISSUE TITLE
ERROR_FILEOPEN when trying to SetModel(string) a dynamically created model

### ISSUE THREAD

**Issue by TankNut** [Facepunch/sbox-issues#203]
**Describe the bug**

Trying to SetModel a model made through VertexBuffer.CreateModel (Or Model.Create) using it's path results in a ERROR_FILEOPEN error and sets the entity to error.mdl instead

**To Reproduce**

1. Clone sandbox
2. Insert this anywhere:
```cs
using Sandbox;

[Library( "ent_vbotest", Title = "Vbo Test", Spawnable = true )]
public partial class VboTest : Prop
{
	public static float Size => 10.0f;

	public VboTest() : base()
	{
		CreateModel();
	}

	public virtual void CreateModel()
	{
		VertexBuffer buffer = new();

		buffer.Init( true );
		buffer.AddCube( Vector3.Zero, Vector3.One * Size, Rotation.Identity );

		Model.Create( "cube", Material.Load( "materials/shiny_white.vmat" ), buffer, true );

		SetModel( "cube.vmdl" );
		SetupPhysicsFromOBB( PhysicsMotionType.Dynamic, new Vector3( -0.5f ) * Size, new Vector3( 0.5f ) * Size );
	}
}
```
3. Try to spawn the entity
4. Check console

**Expected behavior**

The model is set as expected

**Screenshots**

![2021-05-17_23-31-39](https://user-images.githubusercontent.com/1381265/118559332-0e570d80-b768-11eb-9e0a-ee3a15e8a5d3.png)
![2021-05-16_19-24-55](https://user-images.githubusercontent.com/1381265/118559340-1151fe00-b768-11eb-8510-a6220fc32fa7.png)

**Comment by aylaylay** [comment]
Procedural models are anonymous for now, which means they're not referenced by name.
