### ISSUE TITLE
Incorrect files extension in the asset selector for a custom game resource

### ISSUE THREAD

**Issue by tjones4701** [Facepunch/sbox-issues#2035]
### Describe the bug

When selecting a png through the

### To Reproduce

**Step 1**
Create a game resource with a png as the type
For example:

[GameResource( "Upgrade Definition", "upgrade", "Describes an upgrade" )]
	public partial class UpgradeResource : GameResource 
	{
		public string ParentUpgradeClassName { get; set; }
		public string UpgradeName { get; set; }
		public string Description { get; set; }
		[ResourceType( "png" )]
		public string Image { get; set; }
	}

**Step 2**
Create a custom asset of this type

**Step 3**
Select a png for that asset

**Step 4**
Load that asset in your game through the Resource.Get function

**Step 5**
Log out the Image name and see that it resolves to an incorrect file extension.

### Expected behavior

The variable on the resource object should be using the correct extension type.

### Media/Files

![image](https://user-images.githubusercontent.com/49579085/179211263-b94cb24c-cd13-40d4-9ba5-85a344dbe259.png)

**Comment by robotboy655** [comment]
Should be fixed, there was a discrepancy when setting the image asset on an empty property vs an already populated one.
