### ISSUE TITLE
ModelEntity.SetMaterialOverride() isn't always applied on the client

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2036]
### Describe the bug

ModelEntity.SetMaterialOverride() isn't always applied on the client.

This is causing zombies in NPC Zombie Horde to sometimes spawn with the default skin. All other clothing parts are loaded in.
![image](https://user-images.githubusercontent.com/39461072/179374989-166e7d93-90a7-4ce3-ad59-448df6970b41.png)

This also causes player skins to sometimes appear as the default
(both characters should have brown skin)
![image](https://user-images.githubusercontent.com/39461072/179375643-9d5e7732-1da0-45b4-b137-4525fff0447f.png)

![image](https://user-images.githubusercontent.com/39461072/179375653-b03747f1-7ef8-4d3e-9a8c-95cb8be3bae3.png)

### To Reproduce

1. Join a server with players in it
2. Sometimes player's won't have their MaterialOverride set, they'll all have the default skin

Or:
1. Play NPC Zombie Horde.
2. Sometimes Zombies will have the default skin
Note: This seems to happen more often on maps with lower fps like eagleone.thorinium

### Expected behavior

SetMaterialOverride should always work.

### Additional context

A good example of this is in the default ClothingContainer.DressEntity()

**Comment by garrynewman** [comment]
I should have fixed all of the ways this could have fucked up now - please let me know

**Comment by gvarados1** [comment]
Seems to be fixed. Thanks!

**Comment by yuberee** [comment]
It seems that after the update, SetMaterialOverride doesn't work on Client only ModelEntity.

I'm making a ModelEntity on the client with the same model of the parent, doing SetMaterialOverride to make it bright white, and animating the scale.

Before: (Sorry for bad quality, screenshot from twitter)
![image](https://user-images.githubusercontent.com/59583743/187080602-a826c93f-fabc-4092-8e92-8d7cbbfb1a74.png)

After:
https://user-images.githubusercontent.com/59583743/187080552-2780ca35-28b4-4d95-af13-817c87fb8e9e.mp4

![image](https://user-images.githubusercontent.com/59583743/187080402-d8fa9e72-5297-44cf-a653-cb1cab4bab99.png)

**Comment by garrynewman** [comment]
Which SetMaterialOverride?

**Comment by yuberee** [comment]
Shortened the code
```
Material whiteMaterial = Material.Load( "materials/dev/primary_white_emissive.vmat" );
animationModel.SetMaterialOverride( whiteMaterial );
```

**Comment by garrynewman** [comment]
That should be fixed now

**Comment by yuberee** [comment]
Works correctly now 👍
