### ISSUE TITLE
VS 2022 17.2.6 CS0518 Errors

### ISSUE THREAD

**Issue by MyDimeIsUp** [Facepunch/sbox-issues#2037]
### Describe the bug

Updated from 17.2.5 to 17.2.6 and getting CS0518 for every type.

### To Reproduce

Update to 17.2.6 on VS 2022

### Expected behavior

No errors

### Media/Files

![image](https://user-images.githubusercontent.com/8619739/179386946-3e7da40f-cac8-4d7d-9a99-3323996f3d61.png)

**Comment by DoctorGurke** [comment]
Make sure you have dotnet core 6 installed

**Comment by MyDimeIsUp** [comment]
It is. To double check I downloaded 6.0.32 from the website and still nothing.

**Comment by MyDimeIsUp** [comment]
Fixed with a fresh install of Win 11. Not sure what lead to this but seems to have been a problem with my OS. This still happened when updating from 17.2.5 to 17.2.6 so I'll leave this open since it happened with a VS update.
