### ISSUE TITLE
Texture.Update crashes with an access exception on differing texture types

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#204]
**Describe the bug**
Calling `Texture.Update` for any texture type which is not the default `ImageFormat.RGBA8888` type ends up crashing the game(specifically throws an exception in the GPU driver which ends up terminating the game).

**To Reproduce**
```cs
Texture tex = Texture.Create( 64, 64, ImageFormat.RGB888 ).WithName( "MyTexture" ).WithDynamicUsage().WithData( internalScreenFramebuffer ).Finish();

tex.Update( /* ... */, 0, 0, 64, 64 );
```

**Expected behavior**
This should update the texture(my suspicion is that the incorrect texture format is passed when updating).

**Screenshots**

**Additional context**
I haven't tested with sub buffers, only been messing with entire texture copies thus far.

**Comment by aylaylay** [comment]
Are you sure the data you're giving it is the right size for the format

**Comment by garrynewman** [comment]
Either way it should never be possible to crash it. If it's the wrong data size etc we should be throwing an exception.

**Comment by aylaylay** [comment]
This should be fixed now. I also throw exceptions when there's less image data than what is required when creating/updating texture.

I haven't thoroughly tested it so let me know if you can break it.

**Comment by aylaylay** [comment]
Is this fixed?

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
