### ISSUE TITLE
Friction property missing on HingeJoint and SliderJoint

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#2041]
### For?

S&Box

### What can't you do?

Currently it's not possible to change the friction of HingeJoints and SliderJoints, even though there's an option for that in ModelDoc.

### How would you like it to work?

Have a Friction property in HingeJoint and SliderJoint.

### What have you tried?

Finding the friction property.

### Additional context

Enable Limit is also missing, not sure how useful exposing that would be though.

**Comment by robotboy655** [comment]
Added.

**Comment by krotter0** [comment]
Seems to work fine. Thanks.
