### ISSUE TITLE
ent_path_platform and ent_platform does not work anymore

### ISSUE THREAD

**Issue by AfteraOfficiel** [Facepunch/sbox-issues#2043]
### Describe the bug

This entity does not work correctly, 

The platform moves, but no longer moves the associated props (hierarchy)

### To Reproduce

Just try enth_path_platform or ent_platform

### Expected behavior

Model should move with the platform

### Media/Files

https://user-images.githubusercontent.com/99672629/180058054-aaef3d88-6e50-4f1c-a10d-a3d116472f9c.mp4
[ent_path_platform_bug.zip](https://github.com/Facepunch/sbox-issues/files/9153647/ent_path_platform_bug.zip)

**Comment by robotboy655** [comment]
Should be fixed when the game/Sandbox gamemode next updates.

**Comment by AfteraOfficiel** [comment]
Fix thanks
