### ISSUE TITLE
`EnableTouch()`/`EnableTouchPersists()` doesn't seem to stop `StartTouch(...)` calls

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#2046]
### Describe the bug

![image](https://user-images.githubusercontent.com/32153021/180324475-63fff1c6-b31d-421b-b02e-7850d59efe0f.png)
There are two bools to achieve the same thing? They don't seem to stop `StartTouch(...)` from being called either.

### To Reproduce

1. Disable `EnableTouch`, notice that `StartTouch(...)` still gets called

### Expected behavior

It should disable `StartTouch(...)`

**Comment by Weldify** [comment]
I've also experienced this
