### ISSUE TITLE
S&box tool addons have no dependency to base tools

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#2047]
### Describe the bug

When you try to use any code within the base tools addon you will be unable to use them as the generated csproj does not reference it.

### To Reproduce

1. Create a tool addon.
2. Try using something in the base tools addon (like ICodeEditor).
3. Get the "Cannot resolve symbol" error.

### Expected behavior

For everything in the base tools addon to be accessible to all tool addons.

### Additional context

If you try to add the dependency yourself it will work fine in your IDE but it seems to get stomped in S&box and throws a build error.

**Comment by handsomematt** [comment]
Sorted, cheers.
