### ISSUE TITLE
Add Rider as an officially supported code editor

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#2048]
### For?

S&Box

### What can't you do?

Use Rider as a code editor through S&box.

### How would you like it to work?

Rider to be a selection in the drop-down menu. Once selected it uses Rider like how it uses Visual Studio (Code).

### What have you tried?

Made my own file for it, everything functions like the Visual Studio (Code) editors do. Would just need to copy paste it 😄 https://github.com/peter-r-g/Sbox.RiderEditorTool/blob/master/CodeEditor.Rider.cs

**Comment by handsomematt** [comment]
Thanks, I grabbed most of what you did and tidied it up a bit. I didn't bother testing because I cba installing JetBrains bullshit so let me know if I fucked it.

**Comment by peter-r-g** [comment]
Works, thank you!
