### ISSUE TITLE
LibraryAttribute Name/FullName not being set to attached Type anymore

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2051]
### Describe the bug

The Name/FullName Properties of LibraryAttributes are supposed to be set to their attached Type name, but aren't being set at all.

### To Reproduce

Launch any gamemode and retrieve any LibraryAttribute instance and print their values.

```csharp
foreach ( var attr in TypeLibrary.GetAttributes<LibraryAttribute>() )
{
	Log.Info( $"Attribute: {attr}" );
}
```
Attribute as seen in the Inspector:
![sbox-dev_7pnZNKUyNJ](https://user-images.githubusercontent.com/12602100/180460033-a14c7db4-681c-44d9-8dd2-62ec6684e960.png)

### Expected behavior

The Name/FullName properties are supposed to be set to the Type name, unless specifically changed via the first attribute argument.
ent_door FullName is therefore supposed to be DoorEntity

![devenv_uMNUxPxQeN](https://user-images.githubusercontent.com/12602100/180460376-2a20ef02-16e2-4a33-8492-d55f7a503d64.png)

**Comment by garrynewman** [comment]
`[Library]` is kind of obsolete

**Comment by DoctorGurke** [comment]
How is this supposed to work now?

**Comment by handsomematt** [comment]
Well what do you want to do

**Comment by DoctorGurke** [comment]
create types based on a custom attribute's property
previously this would've just been via TypeLibrary.Create with getting the type name from the custom attribute which inherits from LibraryAttribute, filtered by the custom attributes property via TypeLibrary.GetAttributes

**Comment by peter-r-g** [comment]
`LibraryAttribute` is just unused now with the type library system as far as I can tell. You can create your own attribute, insert the type/class name you want to be attached to it in a property then use `TypeLibrary.GetAttributes<YourAttributeType>()` to fetch it. From there you can do `TypeLibrary.Create<YourReturnType>( YourAttribute.YourProperty )`

I think this is an example of what you're looking for:
```cs
class YourAttribute : Attribute
{
    public Type TypeToCreate;
    public YourAttribute( Type typeToCreate )
    {
        TypeToCreate = typeToCreate;
    }
}

[YourAttribute( typeof(YourType) )]
class YourType : YourBaseType
{
}

// Somewhere else
var attributes = TypeLibrary.GetAttributes<YourAttribute>();
foreach ( var attribute in attributes )
    TypeLibrary.Create<YourBaseType>( attribute.TypeToCreate )
```

**Comment by DoctorGurke** [comment]
considering this used to be nice and inexplicit, having to explicitly pass the type to the attribute for this is not a great alternative at all

**Comment by handsomematt** [comment]
You can just write your own attribute that implements ITypeAttribute, makes much much more sense to me then having this big LibraryAttribute that encompasses everything.

**Comment by garrynewman** [comment]
You could use `ITypeAttribute` for it, but I really would avoid that if possible. I only really added `ITypeAttribute` as a backwared compatibility thing for the current LibraryAtttribute. 

Looking at alternatives, it does seem like we're missing some things that would be nice. Like the ideal situation I feel is this..

```
var descs = TypeLibrary.GetTypeDescriptionsWithAttribute<MyAttribute>();

foreach( var desc in descs )
{
	desc.Create( constructor params );
}```

But we're missing the ability to GetTypeDescriptionsWithAttribute, and a Create function on TypeDescription. There's a bunch of Create methods on TypeLibrary, and you could fgeed TypeDescription.TargetType in - but I feel it'd be more logical on the class itself.
