### ISSUE TITLE
Addon Creation: sub-folder should automatically be created

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#2052]
### For?

S&Box

### What can't you do?

The "Create New Addon" window doesn't make a sub-folder automatically, but it probably should - especially considering the default value is now "%UserProfile%/Documents/S&box Projects"

### How would you like it to work?

![image](https://user-images.githubusercontent.com/12881812/180475258-8c8f0fec-38ff-4aac-86fe-8587f3342366.png)

If I make a new addon with ident "balls", and my location is "D:\Alex\Documents\S&box Projects", then it should make a subfolder "D:\Alex\Documents\S&box Projects\balls" and stick my addon in there. This makes it so that I only have to change one text entry (the title) and my addon gets put in the right place, with a friendly ident.

### What have you tried?

Right now I'd have to append "\balls" manually (or whatever my ident is) and it'll make a folder, but that's a bit shit.. if it's filling the textbox to begin with, then it might as well go all the way

**Comment by handsomematt** [comment]
That should feel better, let me know if there's any weird edge cases I guess.

**Comment by xezno** [comment]
This works great, thank you Matt ❤️
