### ISSUE TITLE
[Proton] Can't launch sbox on Mint

### ISSUE THREAD

**Issue by 5FB5** [Facepunch/sbox-issues#2056]
### Describe the bug

My current problem with Proton:
- It can launch the game on Proton ver 5, but window doesn't shown, but earlier it draws the window at least;
- If the game works, I can't enter to any gamemode. It just crash.
I've tried on different Proton version and check game files.

### To Reproduce

-

### Expected behavior

Normal work of the game on Mint

### Additional context

OS: Linux Mint 20.3 Cinnamon
Linux kernel: 5.13.0-44-generic

**Comment by handsomematt** [comment]
https://github.com/ValveSoftware/Proton/issues/4940

Use Proton 7 / Experimental - if something isn't working post your logs there.
