### ISSUE TITLE
"Open Solution" Opens the Wrong Version of Visual Studio

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2058]
### Describe the bug

When I click the new "Open Solution" button it opens VS 2019 which doesn't even work with s&box. The button should open VS 2022. The old "Open Visual Studio" button did this.
![image](https://user-images.githubusercontent.com/39461072/180702022-2dca9062-8cad-4b81-8ddb-896038984b6d.png)

I can't change this in the Editor Preferences. I only have the option to select Visual Studio, not the specific version.
![image](https://user-images.githubusercontent.com/39461072/180701188-91af6017-ff46-4d37-80df-7cbd37ccbcc9.png)

### To Reproduce

1. Have multiple versions of Visual Studio installed
2. Click "Open Solution"
3. The wrong version loads.

### Expected behavior

"Open Solution" should open VS 2022.

### Additional context

This isn't an issue with my default programs because VS 2022 loads if I open the solution from file explorer
![image](https://user-images.githubusercontent.com/39461072/180701430-9c710a68-1e51-43a1-8a32-8e86efacf70b.png)

**Comment by handsomematt** [comment]
Hmmm does your VS2022 install not have the .NET workload?

I'm using vswhere to find the latest installed VS with .NET by using `vswhere -latest -requires Microsoft.NetCore.Component.SDK` - maybe it's pointless to require that component and it works fine with only the .NET SDK installed separately.
