### ISSUE TITLE
Physgun beam direction incorrect

### ISSUE THREAD

**Issue by Numerix76** [Facepunch/sbox-issues#2059]
### Describe the bug

When you are fireing with the physgun for more like 6 seconds without moving, the direction of the beam is weird. It's due to the idle animation being played.

### To Reproduce

1. Fire with the phygun
2. Don't move during 6 seconds

### Expected behavior

The idle animation shouldn't been played when fireing with the phygun.

### Media/Files

https://user-images.githubusercontent.com/42088870/180749395-8878d431-952b-432e-99b5-ec50ed907aed.mp4

**Comment by aylaylay** [comment]
Not an engine or API bug, just how the particle is used in the sandbox gamemode. We don't really care about bugs in sandbox gamemode atm unless it's due to a problem with the engine or API.
