### ISSUE TITLE
Modeldoc - Ragdoll physics are fucked up

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#2062]
### Describe the bug

It seems that something recent broke the physics testing of a model (ragdoll) in modeldoc, they work as usual ingame. 

Tested with the citizen and the same thing happens.

### To Reproduce

Explained in the video.

### Expected behavior

Fix it.

### Media/Files

https://user-images.githubusercontent.com/40291120/180980845-b68c351a-d574-4967-bcf3-3fb6823b9686.mp4

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by KaesarZZ** [comment]
Ty <3
