### ISSUE TITLE
Dynamic speed changing of PlatformEntity (ent_platform) is broken

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#2065]
### Describe the bug

When trying to change the speed of a PlatformEntity in a function that should run automatically every tick, the PlatformEntity does not spin. Even if you call StartMoving on it, it visually does not move. The platform itself seems to think that it is moving, since IsMoving returns true and when getting the Speed property, it also returns the proper speed, as is show by the console output, but the Platform just refuses to move.

When changing the speed manually, for example by a test tool, the PlatformEntity seems to behave correctly. But if its done as in the example above, it does not seem to work at the moment. This worked fine a year ago, and I have no idea why it doesn't work anymore unless something got screwed either about the PlatformEntity itself, or the Event system.

This video showcases the issue at hand: https://www.youtube.com/watch?v=3bOgesMliPM

### To Reproduce

Spawn a TestPlatformEntity (it's speed should be changing from 0 to 50), select the tester tool and press Reload while aiming on said PlatformEntity to toggle moving, and watch nothing happen.

### Expected behavior

Expected behaviour is to gradually speed up/slow down, like it used to.

### Media/Files

[TestPlatformEntityTool.zip](https://github.com/Facepunch/sbox-issues/files/9200706/TestPlatformEntityTool.zip)

ZIP Archive containing the Entity and the Tool.

**Comment by Gmod4phun** [comment]
After further testing it turns out the issue is infact that the platform does not update its speed mid-move, instead it uses the speed that was set when the platform initially started moving. Fixed it for my needs by using an edited version of the entity, nevertheless I still believe this should get fixed in the default PlatformEntity as well, as it used to work before.

**Comment by robotboy655** [comment]
I doubt it has ever worked like you want it to, and you really shouldn't be using it for stargates, it would be much cheaper to have a proper custom entity for the moving ring, or even simply rotating a bone on the model.

That being said, it should work as expected after the game next updates.

**Comment by Gmod4phun** [comment]
Thank you
