### ISSUE TITLE
asset.party home page bug

### ISSUE THREAD

**Issue by JohnyBro** [Facepunch/sbox-issues#2067]
### Describe the bug

When you leave the versions page of a gamemode that hasn't finished to load and come back to the home page it will still show the sidebar of the gamemode when the loading finish.
![image](https://user-images.githubusercontent.com/10268766/181481335-1f1b1068-5e98-444d-b0c0-8e2a4e793425.png)

### To Reproduce

1. Go to a version page of a gamemode that take times to load, Aftera for example
2. Come back to the home page before the versions finish to load
3. Wait to see the sidebar appear

### Expected behavior

Have the same layout for the homepage as when you land on it for the first time.

**Comment by harbour0** [comment]
Most likely because a GET request is sent when retrieving version history and the response is finally recieved resulting in the content being shown within the incorrect page.
