### ISSUE TITLE
Can't Launch S&Box

### ISSUE THREAD

**Issue by ChrsitopherSteele** [Facepunch/sbox-issues#2069]
### Describe the bug

When I try to launch the game I get this error:

![image](https://user-images.githubusercontent.com/59217529/181567766-595868a0-9ee7-492b-b7c5-d4f8bb9d82b5.png)

I have verified game integrity and it didn't work.

The dll file in the directory and the file path matches exactly.

### To Reproduce

Download game from steam

Try to launch it

Error

### Expected behavior

The game should launch.

**Comment by roblox34** [comment]
Reinstall should work

**Comment by ChrsitopherSteele** [comment]
> Reinstall should work

I'll try this after I get out of work tonight. It's a fresh copy just downloaded so I don't know what would change.

**Comment by Pozaza** [comment]
> ### Describe the bug
> When I try to launch the game I get this error:
> 
> ![image](https://user-images.githubusercontent.com/59217529/181567766-595868a0-9ee7-492b-b7c5-d4f8bb9d82b5.png)
> 
> I have verified game integrity and it didn't work.
> 
> The dll file in the directory and the file path matches exactly.
> 
> ### To Reproduce
> Download game from steam
> 
> Try to launch it
> 
> Error
> 
> ### Expected behavior
> The game should launch.
> 
> ### Media/Files
> _No response_
> 
> ### Additional context
> _No response_

Install visual basic c++ redistributable 2005-2022, this should help

**Comment by handsomematt** [comment]
Fixed this a while back by marking Steam to install the 2022 redist
