### ISSUE TITLE
Load and whitelist System.IO.Compression.dll or provide similar functionality

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#207]
**What can't you do?**

More of an obscure request from me fucking around with file format loaders, but I can see some potential usage in actual games:
* Send compressed streams over network to clients using DeflateStream.
* Read zip files and get streams to the contents.
* Use DeflateStream to load PNG in C# (Although this could also be handled by exporting Sandbox.TextureLoader)

**How would you like it to work?**

You can safely whitelist the following with no File IO exposed:

```
System.IO.Compression/System.IO.Compression.CompressionLevel
System.IO.Compression/System.IO.Compression.CompressionMode
System.IO.Compression/System.IO.Compression.DeflateStream.*
System.IO.Compression/System.IO.Compression.GZipStream.*
System.IO.Compression/System.IO.Compression.ZipArchive.*
System.IO.Compression/System.IO.Compression.ZipArchiveEntry.*
System.IO.Compression/System.IO.Compression.ZipArchiveMode
```

Anything File IO is exposed in `System.IO.Compression.ZipFile.dll`, DeflateStream, GZipSteram and ZipArchive all use Stream's with no filename accessors.

I've not looked at Brotil but it seems to be the new gzip, so could be included too.

**Comment by Tripperful** [comment]
This would probably need to be safely wrapped though to fail if you try to unzip malware into files

**Comment by handsomematt** [comment]
> This would probably need to be safely wrapped though to fail if you try to unzip malware into files

You can't unzip anything to files using this, it's purely just streams.

**Comment by handsomematt** [comment]
Thank you rohan :)
