### ISSUE TITLE
Changing various compiler settings throw a NullReferenceException

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2071]
### Describe the bug

Changing the Root Namespace, Symbols, or No Warn options in the project settings throws a NullReferenceException.

![image](https://user-images.githubusercontent.com/57276947/181659050-b84ec116-ad99-4199-8934-2ee97142df91.png)

### To Reproduce

1. Open a project's settings
2. Go to compiler section
3. Change the root namespace, symbols, or no warn options
4. Observe error

### Expected behavior

No error

**Comment by robotboy655** [comment]
Cannot reproduce, assuming fixed since report?

**Comment by trundler-dev** [comment]
This appears to be fixed now. Closing :)
