### ISSUE TITLE
Pressing 'save' in the project settings hides window oddly

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2072]
### Describe the bug

When pressing the save button in project settings, the window is hidden behind the main editor window. This is unusual behaviour, since you naturally might think the project settings window has been closed. I had 10 project settings windows open before I noticed the save button does not close them.

![image](https://user-images.githubusercontent.com/57276947/181659437-dc5066b9-1ff0-4fdf-ac7d-982b6499826a.png)

### To Reproduce

1. Open project settings
2. Press save
3. The window is hidden behind the main editor window

### Expected behavior

Either the window should close, or the window should not hide behind the editor.

**Comment by robotboy655** [comment]
I think you were hitting a bug which made the editor window move to front. It was fixed since then.

**Comment by trundler-dev** [comment]
Yes, this appears to be fixed. Closing :)
