### ISSUE TITLE
Playing sounds through their full paths doesn't always under some conditions.

### ISSUE THREAD

**Issue by R4K0** [Facepunch/sbox-issues#2074]
### Describe the bug

When playing sounds using the full path, you need to play the sound in the asset browser first for it to work.
`PlaySound( "sounds/switch_sound/switch.sound" );` - Bad, will only work if during the current boot you've played that specific sound in the asset browser.

This isn't true for playing sounds through their name, without specifying the full path - In this scenario, the sound will always play.

`PlaySound( "switch" );` Good, will always work - Even without playing the sound first via the asset browser.

### To Reproduce

Failing Scenario:
1. Freshly boot S&Box
2. Have your code run PlaySound with the full path.
3. Watch it be silent.

Passing Scenario:
1. Freshly Boot S&Box
2. Navigate to asset browser, to the desired .sound asset/.wav file.
3. Prompt the asset browser to play the sound through any means (blue speaker icon in the Sounds array drawer, "Preview" button, clicking on the .wav directly)
4. Next time you run PlaySound using the full path, it'll work as expected.

### Expected behavior

Full-path sounds should play without having to manually play it in the asset browser first.

### Additional context

Might be a duplicate of #2022

**Comment by DoctorGurke** [comment]
I didn't even realize full paths work with sounds under any circumstances. The latter method is the intended way and has been since the beginning.

**Comment by R4K0** [comment]
Looks like by design you should do both, but the only documented way is by the shorter name.
![image](https://user-images.githubusercontent.com/17243415/181780424-cb7a6c25-85e1-40da-99b6-00069c890ba3.png)

**Comment by handsomematt** [comment]
So I can only get this to happen if the sound is in a different project to the game.. Which is what you'd really expect because how would you ship the sound with your game otherwise?

**Comment by DoctorGurke** [comment]
Resource paths

**Comment by handsomematt** [comment]
?

**Comment by DoctorGurke** [comment]
If you has assets in an external Project like an asset collection, you could include said assets via resource paths to be uploaded with the game, no?
