### ISSUE TITLE
asset browser: allow deleting assets and asset cleanup

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2076]
### For?

S&Box, Other

### What can't you do?

The new asset browser lacks an option to delete assets and their children etc.

### How would you like it to work?

Probably just similarly to how the legacy asset browser did it, via an extra right-click option
![sbox-dev_lbPBJB9LyB](https://user-images.githubusercontent.com/12602100/181741653-034fe2a7-b8b4-42c2-8559-5fc609ed7adb.png)
![sbox-dev_i4gINEGrkU](https://user-images.githubusercontent.com/12602100/181741719-c146a3b0-a9b7-4729-af5a-81fc72bb2ac8.png)

### What have you tried?

Pressing delete or something on a selected asset, but there seems to be no way as of now to directly delete assets from the browser.

### Additional context

#1402 could maybe also be looked into regarding asset cleanup etc

**Comment by tjones4701** [comment]
After looking into this it seems like even if we make our own tool addon and delete the asset the flag isDeleted isn't being set.

Additionally the AssetBrowser.cs file doesn't check to see if the asset has been deleted when filtering the assets.

Even if it didn't remove the pointers from assets or references in games marking them as deleted and not showing in the asset browser would be awesome.

Another cool idea would be renaming, cloning, moving etc. Basic file operation stuff.

**Comment by garrynewman** [comment]
Yeah all of this stuff is definitely a pain point - definitely something we could handle better.

**Comment by DevulTj** [comment]
I've added Delete to the Asset Browser, which will delete the source + compiled file if it's found.

![2C4lP0lDqV](https://user-images.githubusercontent.com/22372616/191081796-5bc15dcb-ef25-4d00-9e7a-31180793e6c2.png)

Let me know if there are any issues with it.
