### ISSUE TITLE
asset browser: easy way to refresh the asset browser

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2077]
### For?

S&Box, Other

### What can't you do?

I cannot "refresh" the asset browser view to update it for file changes. Example: manually deleting an asset file from an addon directory will not update its presence in the asset browser

### How would you like it to work?

The legacy asset browser refreshes its view when you refresh the search, so a quick add and delete to the file search would usually update its view completely, but there would surely be a more intuitive way to do this like an explicit refresh button

### What have you tried?

old legacy browser way as mentioned above doesn't work and there doesn't seem to be an option for reloading the browser without having to restart the game (or maybe the widget?)

**Comment by garrynewman** [comment]
Does right click refresh not work for this?

**Comment by DoctorGurke** [comment]
I'm unsure, is that supposed to be in this menu?
![sbox-dev_OXFOMK7eDv](https://user-images.githubusercontent.com/12602100/181797316-5a6de552-8fd6-486c-963a-a5e6c0039751.png)

**Comment by cr4yz** [comment]
> I'm unsure, is that supposed to be in this menu? ![sbox-dev_OXFOMK7eDv](https://user-images.githubusercontent.com/12602100/181797316-5a6de552-8fd6-486c-963a-a5e6c0039751.png)

It'll be under your addons in the sidebar

![](https://files.facepunch.com/crayz/1b1011b1/sbox-dev_OF24lMSbcL.png)

**Comment by liquiad** [comment]
> Does right click refresh not work for this?

I've been having this issue too, right click refreshing the addon folder or the folder the files are in doesn't update it.

**Comment by DoctorGurke** [comment]
Maybe something like a refresh button next to the addon folder in the left side bar would work better, so it's immediately obvious that you refresh your view there. But I suppose it's not too big of a deal once you know what you need to target, thanks!

**Comment by DevulTj** [comment]
Just to note, I've also added Refresh to the folder context menu as well. 
![image](https://user-images.githubusercontent.com/22372616/187812477-67f4c837-d3e9-4471-aaa1-560c9a92ba07.png)

Also, some instances where making a new folder, or refreshing did nothing, are now fixed too.
