### ISSUE TITLE
Models do not render in Hammer's 2D viewports

### ISSUE THREAD

**Issue by wouterpleizier** [Facepunch/sbox-issues#208]
**Describe the bug**

Entities with model representations (not just prop_static, but also stuff like info_player_start and light_spot) are invisible in Hammer's 2D viewports in wireframe mode. The entity names and bounding boxes do render, but their models don't.

**To Reproduce**

1. Launch Hammer and create/open a map
2. Create one of the entities mentioned above
3. Switch to any of the 2D viewports (F2, F3 or F4) and make sure it's in wireframe mode (viewport dropdown -> 2D View Shading -> Wireframe)

**Expected behavior**

Models should be shown as wireframes.

**Screenshots**

s&box Hammer:
![image](https://user-images.githubusercontent.com/8166218/118712666-56863680-b821-11eb-8a3a-60cca3d181f1.png)

HL:A Hammer (expected behavior):
![image](https://user-images.githubusercontent.com/8166218/118712731-6a319d00-b821-11eb-8af3-246057d78df6.png)

**Additional context**

The 'Show editor only objects' option does not affect this issue. Models do render properly in the 3D viewport. They also render in the 2D viewports when the view shading mode is set to fullbright instead of wireframe.

**Comment by aylaylay** [comment]
This should now be fixed, please close issue if it's fixed for you x

**Comment by TheGoret** [comment]
Can confirm it fixed it for me

**Comment by wouterpleizier** [comment]
Same here, thanks!
