### ISSUE TITLE
Addon manager: title validation

### ISSUE THREAD

**Issue by BeirlaenAaron** [Facepunch/sbox-issues#2080]
### Describe the bug

When uploading a new addon with the addon manager there is no validation on the title of the addon while there is on the web. The web does not allow special characters in the addon title. So if an addon is uploaded with special characters, it results in it not being editable on the web (e.g. editing the summary/description or adding a thumbnail).

### To Reproduce

1. Add a new addon with the addon manager that contains special characters in the title (e.g. s&box). 
2. Once it's added go to the addon on https://asset.party/
3. Try to add a thumbnail. The save button will always be disabled until you remove the special characters from the title.

### Expected behavior

The same validation as on the web should also be done in the addon manager. (or just get rid of the validation on the web if it doesn't matter.)

### Media/Files

![image](https://user-images.githubusercontent.com/55881661/181850331-5cd2feb9-2361-4743-a460-1fccbf936c7f.png)
![image](https://user-images.githubusercontent.com/55881661/181852243-054709b4-1927-428e-a0e5-6a1484a8efc7.png)

**Comment by cr4yz** [comment]
Should be fixed, lemme know if you have any more issues with it
