### ISSUE TITLE
GameResources disappear from the asset browser on restart

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#2085]
### Describe the bug

Custom GameResource files disappear from the asset browser after a restart. New files can still be created in the asset browser and they show up fine until sbox is restarted. Addons can still load them when this occurs.

### To Reproduce

1. Create a GameResource class
2. Create a GameResource file in the asset browser from that class
3. Restart sbox
4. GameResource file created in step 2 can no longer be seen in the asset browser

### Expected behavior

GameResources should show up in the asset browser even after a restart.

**Comment by mzegar** [comment]
Experiencing the same, resources also failed to upload since I'm assuming they don't get detected anymore.
![image](https://user-images.githubusercontent.com/32153021/181937668-f6434eb0-2fca-4b73-9ac9-4b628a20b4e2.png)
