### ISSUE TITLE
"Error creating gamemode" with local addon after changing to "local" org

### ISSUE THREAD

**Issue by Ephememory** [Facepunch/sbox-issues#2088]
### Describe the bug

When I try to run/edit my local gamemode, s&box fails and throws a generic 'Coding Error' and an exception: "Couldn't find a gamemode!" when the gamemode compiles and runs fine after a game restart (which is annoying to do every time).

### To Reproduce

1. Start s&box with your addon's org set to your s&works org (NOT LOCAL). (As in, the addons org was set to your s&works org before you launched the game or when you last saved the addon and closed the game.)
2. Change your addon's org to "local".
3. Attempt to launch gamemode, throws error.
4. Restart s&box, addon now launches.

### Expected behavior

Being able to launch a gamemode addon after changing its org to local without a game restart.

### Media/Files

![image](https://user-images.githubusercontent.com/66768086/182012916-e51d1fde-2ab9-4856-bb7e-d413142af4f4.png)
```
 01:16:31   Loading map "null.breakfloor_tsar"
 01:16:31   Found local game: local.breakfloor
 01:16:31   SV:  maxplayers set to 16
 01:16:31   Building 2 compilers
 01:16:33   Error creating gamemode
 01:16:34   CL:  disconnect
 01:16:34   CL:  Server disconnected: 2: NETWORK_DISCONNECT_DISCONNECT_BY_USER
 01:16:34   SV:  Server shutting down: NETWORK_DISCONNECT_DISCONNECT_BY_USER (2)
 01:16:34   [5]  Shader attribute "LightSim_MaterialTint" has inconsistent value or type across multiple shaders of a feature combo!
 01:16:34   Discarding pending request 'Loading (null.breakfloor_tsar), 6'
```

When clicking on the `Error creating gamemode` line of the output to inspect the error:
![image](https://user-images.githubusercontent.com/66768086/182012967-d38072bf-005e-4284-b7c5-5cfa15367a1e.png)

**Comment by Ephememory** [comment]
It seems that you no longer (or never needed to) switch a gamemode's org to local to live code/edit it. So, not that annoying but still an issue?

**Comment by handsomematt** [comment]
Works okay for me, still an issue?

**Comment by Ephememory** [comment]
> Works okay for me, still an issue?

All fixed, thanks.
