### ISSUE TITLE
Custom Resources Don't Appear in the Asset Browser

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2089]
### Describe the bug

When I create a custom resource, I can see it in the asset browser fine. However, once I restart my game, the asset can no longer be seen.

### To Reproduce

1. Create the custom asset (the Ammo asset I've included should work)
2. Save it and restart sandbox
3. Asset will not be visible. 

### Expected behavior

Assets should be visible.

### Media/Files

[Resources.zip](https://github.com/Facepunch/sbox-issues/files/9228485/Resources.zip)
Contains two resource files, in case this is caused because of how I've set up the resource.

### Additional context

Ubre also seemed to be running into issues with this, he might be able to offer more details.

**Comment by DoctorGurke** [comment]
#2085

**Comment by Fortune117** [comment]
> #2085

Woops, closed as duplicate.
