### ISSUE TITLE
NetList<NetworkClass> crashes to desktop

### ISSUE THREAD

**Issue by TankNut** [Facepunch/sbox-issues#209]
**Describe the bug**

Trying to use a NetList with any class derived from NetworkClass causes the game to crash to desktop

**To Reproduce**

1. Clone sandbox
2. Insert this anywhere:
```cs
using Sandbox;

public partial class NetElement : NetworkClass
{
	[Net]
	public int Index { get; set; }
}

[Library( "ent_net", Title = "NetList Test", Spawnable = true )]
public partial class NetListTest : Prop
{
	[Net]
	NetList<NetElement> NetList { get; set; }

	public override void Spawn()
	{
		base.Spawn();

		NetList = new();
		NetList.Set( 1, new NetElement() { Index = 1 } );

		SetModel( "models/thruster/thrusterprojector.vmdl" );
		SetupPhysicsFromModel( PhysicsMotionType.Dynamic, false );
	}

	[Event( "tick" )]
	public void Tick()
	{
		DebugOverlay.ScreenText( IsClient ? 0 : 1, $"{NetList.Get( 1 )}" );
	}
}
```
3. Try to spawn the entity
4. Crash

**Expected behavior**

It probably shouldn't crash to desktop

**Additional context**

It doesn't seem to happen when the thing being networked is an entity.

**Comment by Erlite** [comment]
IIRC that happens because `NetList<T>` uses `NetRead.Read<T>()`. It seems that method attempts to read memory out of bounds if the type you try to network doesn't have a fixed size.

**Comment by garrynewman** [comment]
I fixed the crash, but the fix is to not allow you to send NetworkClass. I would suggest instead making NetElement a struct.

**Comment by Erlite** [comment]
Is there no better way to do this than an unmanaged constraint on `Read<T>`? That works, but for things like generic collections/wrappers this means we need to make two versions per generic that'll be used in a Read method (i.e. `NetworkVar<T> where T : class` and `NetworkValueVar<T> where T : unmanaged`. Even worse with multiple generics like dictionaries where you have `NetworkDictionary<TKey, TValue>` and suddenly you have to make 4 versions of it to support class and unmanaged keys/values.)

**Comment by garrynewman** [comment]
The end goal here is to make things like Entity, Dictionary and List network automatically

**Comment by Erlite** [comment]
Good to know, thanks.
