### ISSUE TITLE
UI Number Input field scaling issue

### ISSUE THREAD

**Issue by ghoeffner** [Facepunch/sbox-issues#2094]
### Describe the bug

Change the settings "Framerate cap" and "Default FoV" on a notebook with high resolution

### To Reproduce

Go to Settings
See fields as described above

Windows scaling set to 250%
Resolution is set to 3840x2400

### Expected behavior

Numbers should scale so they can be properly read

### Media/Files

![image](https://user-images.githubusercontent.com/1123412/182035414-65a3b27b-f147-4bd2-ab3f-e44a9b575415.png)

**Comment by DevulTj** [comment]
This'll be fixed in the next steam build. Thank you for reporting!
