### ISSUE TITLE
If a map build fails game & dev tools require a restart

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#21]
In my case I built the map while it was already loaded in s&box causing the final copy step to fail (access error maybe)

When this happens anymore map build attempts show this dialog and fails to build: https://i.imgur.com/aScAOnF.png

Requires a restart of the game and tools to fix.

**Comment by cr4yz** [comment]
seems like there's another issue causing the dialog, trying to replicate now

**Comment by cr4yz** [comment]
It's related to overriding the default gamemode with `gamemode` command.

I can build/run/build many times without problems if I don't override the default gamemode.

If I override the default gamemode I get the fail to copy error on build (if the map is loaded in-game), and the dialog pops up if I try building again.

The dialog can also be replicated this way:
Launch sbox-dev
Put `gamemode somecustomgamemode` in console
Launch Hammer
Build a map in `somecustomgamemode`'s content_src/maps
Press the Run/skip build button to load map
Disconnect
Build the map, the dialog should appear and game needs restart

**Comment by garrynewman** [comment]
Please let me know if this is still an issue

**Comment by cr4yz** [comment]
> Please let me know if this is still an issue

Seems to be fixed now, thank you.
