### ISSUE TITLE
Block S&box main menu from opening when pressing escape

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#210]
**What can't you do?**

Pressing escape habitually to close out of something, it will open the S&box main menu instead.  I'd like to implement behaviour into my menus to close them on pressing escape, then decide when to open the S&box menu.

**How would you like it to work?**

A way to tell s&box not to open the main menu on escape then I can handle what happens when pressing it

Alternatively an "escape stack", when something opens I can add it to the stack.  Next time I press escape it will grab the last added item to the stack and close it.  If the stack is empty then open the S&box main menu.

**Comment by TomDotBat** [comment]
This would be nice for UX, I hope custom escape menus don't come from this though 👀
