### ISSUE TITLE
Asset Browser: Recompile all assets in selected directory and its subdirectories

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#2100]
### For?

S&Box

### What can't you do?

Can't recompile all assets in a folder automatically, Currently has to be done one by one manually.

### How would you like it to work?

After selecting a folder in the asset browser, it would be nice to have an option to recompile all assets which are in that dir and subdirs.

Probably something like this:
![image](https://user-images.githubusercontent.com/5991682/182118130-ff3a0533-70b5-4e69-8d0c-bb25b17dac3f.png)

### What have you tried?

Just manually recompiling stuff. Its tedious.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/188506675-74a5c210-9ff3-4f6b-881b-5f072b2197ff.png)

**Comment by Gmod4phun** [comment]
Thank you so much, works like a charm.
