### ISSUE TITLE
Templates gone?

### ISSUE THREAD

**Issue by DissolveDZN** [Facepunch/sbox-issues#2101]
### Describe the bug

When i try to make a new addon and select a template the only template that shows is "minimal", the other templates seem be gone.

![image](https://user-images.githubusercontent.com/66252754/182142208-1159b9f1-5719-46f5-ad1e-4587b0b61120.png)

### To Reproduce

1. in the Addon manager click the plus sign
2.  click on "create new"
3.  select game as addon type and such templates as "shooter" will not appear

### Expected behavior

other addons like "shooter" should appear
![image](https://user-images.githubusercontent.com/66252754/182142697-5dca26a8-e40d-4ca7-adc4-b4274383af05.png)

### Additional context

I'm using the newest version of s&box on windows

**Comment by DissolveDZN** [comment]
i'm not sure whether this is a bug or it just got removed

**Comment by DevulTj** [comment]
We don't have other templates available yet. They will be added in the future.
