### ISSUE TITLE
Gamemode thumbnails and backgrounds are not loading

### ISSUE THREAD

**Issue by AdamSai** [Facepunch/sbox-issues#211]
**Describe the bug**
Thumbnails and backgrounds for gamemodes are no longer loading and an exception is thrown.
Loading screen is also completely white.

**To Reproduce**

1. Open sbox.exe or sbox-dev.exe
2. See images not loading and the exception

**Expected behavior**
Gamemode images should load

**Screenshots**
![image](https://user-images.githubusercontent.com/11211186/118726776-15e2e900-b832-11eb-873e-50fc5ec709f8.png)  
![image](https://user-images.githubusercontent.com/11211186/118726801-1e3b2400-b832-11eb-8dbd-9c255227da33.png)

**Additional context**
This happens after the update "Make TextureLoader.Image public as well".

EDIT: You can still play the gamemodes, it's just the images that aren't loading. 

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by Erlite** [comment]
Same here.

**Comment by AdamSai** [comment]
It is now working as intended again, cheers 👍
