### ISSUE TITLE
Updates to a sub-animgraph aren't hotloaded until the parent is modified

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2110]
### Describe the bug

When you update a subgraph in the animgraph editor, it won't hotload the animations in game. You need to modify the animgraph the subgraph is located in before it hotloads as expected.

### To Reproduce

1. Create an animgraph and a subgraph.
2. Update the subgraph and save. In game wont hotload the changes.
3. Update the main animgraph, changes should now hotload.

### Expected behavior

Hotload on subgraph updates.

**Comment by aylaylay** [comment]
Finally got around to this, it should be working now! Let me know if it isn't

**Comment by Fortune117** [comment]
Just gave this a go, it did work, but only after I updated the parent animgraph for the first time. I started off by just modifying the subgraph and that didn't seem to register until after I updated the parent once.

**Comment by aylaylay** [comment]
Yep that's to be expected, it needs to add the dependencies first so a first compile is needed, after that it should work as expected.

**Comment by Fortune117** [comment]
Alright, cool 👍
