### ISSUE TITLE
Using weld tool can cause 2 cars fall underground

### ISSUE THREAD

**Issue by GrayWolf64** [Facepunch/sbox-issues#2114]
### Describe the bug

When I try to weld 2 cars together and drive them, they fall underground after I drive them.

### To Reproduce

Use weld tool on 2 cars, and then drive one of the cars. First, drive straight and then turn a little. Then get off, the first car you drive will fall underground first and the second car will fall later.

### Expected behavior

They won't drop underground.

### Media/Files

https://user-images.githubusercontent.com/88234821/182377378-3fda87d0-7854-43fa-be66-f385007de58c.mp4

### Additional context

Weld tool should be improved in some ways.

**Comment by aylaylay** [comment]
Please stop making issues for the sandbox mode, we don't care about bugs in this mode yet unless it's an engine bug.
