### ISSUE TITLE
Addon Manager - Incorrect `create organization link`

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#2115]
### Describe the bug

When attempting to click create organization within the `Addon Manager` it takes you to the following page in your browser `https://asset.party/.create` which leads to 404 Not Found error.

### To Reproduce

1. Click on `organization Ident` setting and then click on `Create New Organization... `
2. Observe that your browser will open to `https://asset.party/.create` which doesn't exist.

### Expected behavior

For it to take you to `https://asset.party/~create` and not `https://asset.party/.create`

**Comment by DevulTj** [comment]
Sorted, thank you!
