### ISSUE TITLE
Addon Manger - Upload button text out-of-date

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#2116]
### Describe the bug

When hovering over the button to upload your addon it says `Upload to S&works`. 

### To Reproduce

1. Goto any addon with an assigned org.
2. hover over the upload button to see the out-of-date text.

### Expected behavior

The text should say `Upload to asset.party` instead.

**Comment by DevulTj** [comment]
Sorted, thank you!
