### ISSUE TITLE
Water Flickering

### ISSUE THREAD

**Issue by MikeShaughnessy** [Facepunch/sbox-issues#2117]
### Describe the bug

Water flickersv

### To Reproduce

1. add water
2. compile map

### Expected behavior

Water shouldnt flicker

### Media/Files

[https://gyazo.com/70131632d84a52b60f8be01f9d9f99a5](url)

**Comment by samzanemesis** [comment]
Could you attach the vmap?

**Comment by MikeShaughnessy** [comment]
> https://drive.google.com/file/d/1rM_328LdoStEnkjX2h6QFt-v5_w3kxNz/view?usp=sharing

**Comment by MikeShaughnessy** [comment]
It seems to have started working, idk what caused it but it might of been adding a 3dskybox?
