### ISSUE TITLE
FindActiveCamera returns Camera instead of ICamera

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#212]
**Describe the bug**
FindActiveCamera returns Camera instead of ICamera

Requires casting like this for now:
![image](https://user-images.githubusercontent.com/1809172/118733564-2cdf0680-b845-11eb-9db2-c3287477fb79.png)

**To Reproduce**
Override FindActiveCamera and return some entity's camera

**Expected behavior**
FindActiveCamera should return ICamera since entities use it too.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Trojaner** [comment]
Issue is fixed
