### ISSUE TITLE
Can't See Underscores in Model Doc Text Entries

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2122]
### Describe the bug

When editing text entries in model doc I noticed you can't see the underscores:
![image](https://user-images.githubusercontent.com/7847372/182537008-10f3e18f-f388-44c8-bfe4-009968fcbd57.png)

This says "shoot_aim_empty" but just looks like it has spaces in it.

### To Reproduce

1. Open model doc
2. Add something with a text entry (like generic anim events)
3. type in some text

### Expected behavior

You can see the underscores

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
