### ISSUE TITLE
Style `animation-play-state` and `Style.AnimationPlayState` doesn't work

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#2123]
### Describe the bug

Hello,

Simply the style attribute `animation-play-state` and `Style.AnimationPlayState` seems to be implemented in S&box but it doesn't work.
Even if i use `Dirty()`

### To Reproduce

Use the example files below or try yourself on your custom keyframes animation :

In .scss :
`animation-play-state: paused;` 
Or
In .CS :
```
Style.AnimationPlayState = "paused";
Style.Dirty();
```

### Expected behavior

https://developer.mozilla.org/fr/docs/Web/CSS/animation-play-state

### Media/Files

TestPanel.cs :
```
using Sandbox.UI;

namespace Sandbox
{
	[UseTemplate]
	public class TestPanel : Panel
	{

		public void StopTest()
		{
			Log.Info( "Pressed" );

			Style.AnimationPlayState = "paused";
			Style.Dirty();
		}

	}
}
```

TestPanel.html :
```
<link rel="stylesheet" href="TestPanel.scss" />

<panel>
    <button onclick="StopTest()">hello</button>
</panel>
```

TestPanel.scss :
```
TestPanel {
    position: absolute;
    width: 100px;
    height: 100px;
    background-color: red;
    animation-name: spin;
    animation-duration: 2s;
    animation-timing-function: linear;

    animation-play-state: paused;

    pointer-events: all;
}

@keyframes spin {
    0% {
        transform: rotate(0deg);
    }

    100% {
        transform: rotate(360deg);
    }
}
```

**Comment by cr4yz** [comment]
This should be in the next update, please let me know if you have any issues with it.  You won't have to dirty the style, just set `Style.AnimationPlayState` to `paused` or `running`

**Comment by PolSpock** [comment]
Thx 👍 🎉!
