### ISSUE TITLE
God-like bug with knights helmet / bucket hat

### ISSUE THREAD

**Issue by harbour0** [Facepunch/sbox-issues#2124]
### Describe the bug

When a user is wearing the knights helmet / bucket helmet it creates a "god" like glitch making the user invincible within multiple gamemodes. (identified by Velocks and his hacks) 

User is able to be killed with crowbar.
User is not able to be killed with a gun weapon. 

### To Reproduce

1. Launch game.
2. Ensure user is wearing knights helmet / bucket helmet. 
3. Launch a gamemode (Commando Terry / Alex's Instagib).
4. Try to kill with non-melee weapon (does not work).
5. Try to kill with melee weapon (works and player is killed). 

### Expected behavior

Player should be able to be killed no matter the model / accessories. 

### Media/Files

![image](https://user-images.githubusercontent.com/110195246/182654508-ffd6ac5a-475f-4b71-b2f1-be424dbda28d.png)

**Comment by handsomematt** [comment]
The games need to ignore clothing in their traces.
