### ISSUE TITLE
UI: Allow post processing to be overridden for ScenePanels

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#2125]
### For?

S&Box

### What can't you do?

UI ScenePanels seem to use the default vpcf with no ability to swap this out or remove postprocessing completely. This leads to some ugly looking renders in some situations:
![image](https://user-images.githubusercontent.com/12881812/182698603-38178fca-57d5-4d9b-9332-d97df29c8942.png)

### How would you like it to work?

It would be nice if the post processing could be swapped out:
```cs
myScenePanel.PostProcessingFile = "/postprocess/no_bloom.vpost";
```

Or removed completely by blanking out the path:
```cs
myScenePanel.PostProcessingFile = "";
```

### What have you tried?

I don't think there's any way to get around this right now.

**Comment by DevulTj** [comment]
I've added ScenePanel.DisablePostProcessing, this should provide what you need - if it turns out you need something different, please make another issue.

**Comment by xezno** [comment]
Yep this works nicely, thank you!
