### ISSUE TITLE
Validation issue when cloning gamemode from asset.party

### ISSUE THREAD

**Issue by harbour0** [Facepunch/sbox-issues#2126]
### Describe the bug

When cloning a gamemode from asset.party - if the folder already exists it prevents overwrite (fine, this is expected).

However if you switch to a new folder - the previous validation prevents you from creating the gamemode, even if in a new folder / different location. 

### To Reproduce

1. launch sbox-dev.exe
2. (have previous cloned addon / gamemode from asset.party) - example sake; dm98
3. add addon -> from asset.party
4. clone existing gamemode from asset.party -> not allowed as exists.
5. change checkout location.
6. cannot clone from asset.party

### Expected behavior

You should be able to clone the gamemode once location is changed and the folder you've changed to doesn't include the gamemode you wish to clone.

### Media/Files

(Unable to clone as gamemode exists within files)
![image](https://user-images.githubusercontent.com/110195246/182729110-8d1fda8f-c124-497f-8719-b14f213ccd91.png)

(Switch to new location -> still unable to clone)
![image](https://user-images.githubusercontent.com/110195246/182729226-98520adb-7fc3-43e9-9c8e-82e1731e8429.png)

(empty check out location)
![image](https://user-images.githubusercontent.com/110195246/182729201-eed5dd6d-515f-4a5f-aecb-b395031ea25a.png)

**Comment by cr4yz** [comment]
This is intentional.  The button is disabled because your addon manager already has a DM98 and it doesn't want two addons with the same ident.  If you remove it first, you can clone it again.

**Comment by harbour0** [comment]
I'd of thought you would be able to clone as much as you like but just change the identity on clone i.e DM98 -> clone again -> DM98-2?

Just an idea!

Thanks for the response and clarification though; I appreciate it
