### ISSUE TITLE
Trigger_Teleport doesnt teleport physics

### ISSUE THREAD

**Issue by MikeShaughnessy** [Facepunch/sbox-issues#2127]
### Describe the bug

When I try to have a teleporter with props in the area of the teleporter, it doesnt teleport them.

### To Reproduce

1. create teleporter
2. have physics prop go into teleporter
3. physics prop doesnt get teleported

### Expected behavior

the physics prop should get teleported

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/182848267-40f73b30-e73b-40cd-9ac8-7e4b3a811a44.png)

You need to let the trigger know what entities you want it to teleport.

So, you want props to teleport, you need to have `prop` tag set in Hammer.
