### ISSUE TITLE
EyePos returns wrong value

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#213]
**Describe the bug**
After the recent pawn changes EyePos does not return correctly anymore for me. Does not matter if using Activated or Update, result is always the same

```cs
// Local.Client.Camera (*not* pawn camera)
public override void Activated()
{
    var diff = TargetEntity.EyePos - TargetEntity.Position; // 0, 0, 0
    var type = TargetEntity.GetType(); // BaseKillerPawn
    var model = (TargetEntity as ModelEntity)?.GetModelName(); // "models/citizen/citizen.vmdl"
    _cameraHeight = (TargetEntity.EyePos - TargetEntity.Position).z; // 0 instead of 64
    base.Activated();
}
```

**To Reproduce**

1. Create pawn as in the screenshots below
2. Create a LookAtCamera with the Activated method above, set TargetEntity to the players pawn
3. Assign Client.Camera to it
4. Observe issue in Activated()

**Expected behavior**
Should return 0, 0, 64 instead

**Screenshots**
![Code_-_Insiders_2021-05-19_04-46-38](https://user-images.githubusercontent.com/1809172/118744632-599f1800-b85d-11eb-87ee-7a18ace8b70a.png)
![image](https://user-images.githubusercontent.com/1809172/118744682-6de31500-b85d-11eb-90da-8e94eb1e5ce0.png)

**Comment by garrynewman** [comment]
Why do you expect it to be 0, 0, 64?

**Comment by Trojaner** [comment]
If I remember correctly, that's what it returned before the change. It was definitely not 0.

**Comment by garrynewman** [comment]
Things have changed, make sure EyePos is being set.

**Comment by Trojaner** [comment]
The TargetEntity is a pawn that has a controller set which is derived from WalkController. However the pawn is not assigned to a client at that point so I guess it doesnt update EyePos.
