### ISSUE TITLE
Map isn't getting tagged properly 

### ISSUE THREAD

**Issue by MikeShaughnessy** [Facepunch/sbox-issues#2130]
### Describe the bug

I have matt.ttt marked for supported games yet it doesnt show up as a tag on the website and neither does it show up in the map pool which is based off tagged maps.

### To Reproduce

I don't have any idea why this is happening other people have the same setup and it works.

### Expected behavior

It should get the tag matt.ttt and show up in the map pool.

### Media/Files

https://i.imgur.com/z7z2vJw.png
https://i.imgur.com/Ve38CmO.png

**Comment by cr4yz** [comment]
Game support gets set per version, so you will need to update the addon config with the supported game then upload a new version of the map, then the tag should be set.  

Could you give that a try and let me know if it's still not working?

**Comment by MikeShaughnessy** [comment]
> Game support gets set per version, so you will need to update the addon config with the supported game, then upload a new version of the map, then the tag should be set.
> 
> Could you give that a try and let me know if it's still not working?
so are you saying update the supported games becasue Ive already done that.
Or are you saying I need to upload a new map or both?

**Comment by cr4yz** [comment]
Update the supported games _and_ upload the map again.

**Comment by MikeShaughnessy** [comment]
> Update the supported games _and_ upload the map again.


I get the omg success screen but it doesnt get updated on asset.party and the new version doesnt show up either
