### ISSUE TITLE
[ModelDoc] FBX animations are set to 1 frame over the maximum when imported

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2132]
### Describe the bug

Whenever I import animations using FBX files they appear as expected but have 1 frame over the maximum of the animation:
![image](https://user-images.githubusercontent.com/7847372/183015661-2a8dff3a-7178-4dc2-8472-4c7333b22e9d.png)

### To Reproduce

1. Open model doc and import an animation from an FBX file
2. It should have 1 extra frame

### Expected behavior

Frames should be set to the maximum in the animation.

**Comment by ogniK5377** [comment]
Can you provide the FBX file?

**Comment by Fortune117** [comment]
[snork_animations.zip](https://github.com/Facepunch/sbox-issues/files/9269143/snork_animations.zip)
Mesh + animations

Add the animations fbx and then change the 'take' to any of the animations. 
![image](https://user-images.githubusercontent.com/7847372/183089970-9349aec6-e3af-41fc-ae5d-bfbfc73b397a.png)

**Comment by PolSpock** [comment]
Same probleme here 👍
![image](https://user-images.githubusercontent.com/5229571/192475614-b35b8e21-ef13-4b6d-9619-7c1df9c93dab.png)

**Comment by aylaylay** [comment]
Fixed
