### ISSUE TITLE
[ModelDoc] Rotating Physics Joint Conical has Unexpected Behaviour

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2135]
### Describe the bug

I'm not sure when this happened, but rotating physics joint conical is very broken - I've recorded a short video of what I mean:

https://user-images.githubusercontent.com/7847372/183250502-2740af85-789f-4eef-a1cf-ee03188be13d.mp4

### To Reproduce

1. Open the provided model doc files
2. Try and rotate any of the physics joints

### Expected behavior

Rotates as per the displayed axis.

### Media/Files

[bloodsucker.zip](https://github.com/Facepunch/sbox-issues/files/9275090/bloodsucker.zip)

### Additional context

Side note, the widgets are also really tiny, would it be possible to enlarge them or add a slider for them somewhere?

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
