### ISSUE TITLE
Allow us to change voice chat to be 2D

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#2137]
### What it is?

https://discord.com/channels/833983068468936704/835035328779518023/1002756700039811192

Just making an issue so this isn't forgotten, I need this for my game.

### What should it be?

Give us an API so we can change the voice chat into `2D` instead of `3D`

**Comment by DevulTj** [comment]
This is planned. It's set up natively but we don't have anything in C# for it just yet.

**Comment by aylaylay** [comment]
Easy to do, just an api design issue

**Comment by aylaylay** [comment]
@mzegar You can now change the voice to be 3D or 2D (2D is on by default)

You do this by changing VoiceStero on the Client, a good place to do this is OnVoicePlayed

**Comment by mzegar** [comment]
Thank you, works well.
