### ISSUE TITLE
S&box Wiki additions

### ISSUE THREAD

**Issue by HichGog** [Facepunch/sbox-issues#2139]
### For?

S&Box

### What can't you do?

There is no full control in the Wiki and the page with console commands was deleted, yes, I know that you can use console commands from HL:Alyx, but many of them don't work. I would check all console commands myself , but I 'm afraid my game will break

### How would you like it to work?

I want this to be added, because you don't know which team is responding to what, you can also ask in #general-dev, but no one knows the answer there 

### What have you tried?

I do not know how all console commands work , at most how to add a bot to the server

**Comment by handsomematt** [comment]
If you want to know how bots work, look at the bots page.

The wiki is available to edit for all, if there's something specific you need to know you can ask in Discord and add to wiki. There's no point in adding every concommand to a page for the sake of it.
