### ISSUE TITLE
Error List Addon Filter doesn't update according to enabled/disabled addons

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2146]
### Describe the bug

When disabling/enabling addons via the addon manager, the filter tab in the Error List doesn't update accordingly.

### To Reproduce

1. Launch sbox, note which addons are present in the Error List filter dropdown
2. Enable/disable some local addons via the addon manager
3. note the Error List filter dropdown didn't update

### Expected behavior

I should be able to set the filter to my addon before launching/recompiling after enabling it

### Additional context

Launching/Recompiling updates the error list like expected

**Comment by DevulTj** [comment]
Done! Check it out on steam in ~10 minutes. Thank you for reporting ❤️

**Comment by DevulTj** [comment]
Sorry, this isn't the thing I fixed. I fixed https://github.com/Facepunch/sbox-issues/issues/2148 - looking into this one shortly.
