### ISSUE TITLE
Compiling an addon resets the error list filter

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2147]
### Describe the bug

After compiling an addon, the error list filter resets.

### To Reproduce

1. set the error list filter to an addon (eg. base)
2. compile an addon
3. note that the filter dropdown reset to All Addons

### Expected behavior

The filter should be saved between compiles, only resetting if the addon gets disabled 

### Additional context

#2146 relevant for resetting the filter when filtered addon is disabled

**Comment by cr4yz** [comment]
This should be fixed in the next update
