### ISSUE TITLE
Error list "type" buttons don't account for filtered addon

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2148]
### Describe the bug

When changing the filter inside the error list to a specific addon, the amount of warnings or errors isn't updated according to the filtered addon.

### To Reproduce

1. Have two or more addons enabled and displayed in the error list
2. filter for one
3. note how the amount of warnings/errors on the type toggles doesn't update

### Expected behavior

The amount of errors and warnings should only represent the currently filtered addon

### Media/Files

![sbox-dev_0drRN5BJ4g](https://user-images.githubusercontent.com/12602100/183683383-3787f3bc-de8c-4241-aeee-b4eb4e8d4156.png)
![sbox-dev_GwlH6hFg5U](https://user-images.githubusercontent.com/12602100/183683396-51a64e95-ec70-4730-a130-e7c8382fd619.png)
The lower picture still includes the warnings from the base addon

**Comment by DevulTj** [comment]
This should be live on steam now.
