### ISSUE TITLE
Allow custom checks if an entity should collide

### ISSUE THREAD

**Issue by qualitycont** [Facepunch/sbox-issues#215]
**What can't you do?**
Check if an entity can collide with an object on a case by case basis

**How would you like it to work?**
```cs
public partial class SomeEntity : ModelEntity
{
    public override bool ShouldCollide(Entity ent)
    {
        if(ent is SomeOtherEntity)
            return true; // collides
        return false; // doesnt collide
    }
}
```
(and use ShouldCollide when CollisionGroup is set to ConditionallySolid)

**What have you tried?**
Using CollisionGroup.ConditionallySolid with CollisionLayers

**Additional context**
N/A

**Comment by Gmod4phun** [comment]
Bump. This is needed to disable collisions at runtime between two specific entities, like the GMod ShouldCollide hook.
