### ISSUE TITLE
Game Resources with names equal to or smaller than the description don't load and throw an exception

### ISSUE THREAD

**Issue by Redhacker1** [Facepunch/sbox-issues#2153]
### Describe the bug

```csharp
using Sandbox;

[GameResource("Tile", "tile", "Describes a tile to be used with a generator")]
public partial class Tile : GameResource
{
	public string Title { get; set; }

	[ResourceType( "vmdl" )]
	public string Model { get; set; }


}
```
I was trying to create a resource along the lines of this, and it kept failing with "startIndex cannot be larger than length of string. (Parameter 'startIndex')" and refusing to load the GameResource,  with advice on discord here to make the "Friendly name" longer than the file extension, a change and a restart of Sandbox later, it worked. 

### To Reproduce

Create a GameResource with a friendly name of "Tile", with an extension of "tile" and whatever you want as far as description and properties, and then try and edit it.  After than call it "Something Tile", restart the game and open the gamemode addon in question and try editing it again, it should work.

### Expected behavior

The expected behavior is it should just work with Tile as a friendly name. 

### Media/Files

I apologize this is in image form. The Error list refused to spit out the actual stacktrace or even acknowledge the error.
![My stacktrace.](https://user-images.githubusercontent.com/66490743/184022829-ef183d5f-8fc5-49e3-a526-97c85c489cc4.png)

### Additional context

Discord message link: https://discord.com/channels/833983068468936704/833983416390385685/1007033102016729208
I positioned the asset in my own addon, inside a resources folder, which was marked as being a  resource path with `/resources/*`

**Comment by cr4yz** [comment]
This should be fixed in the next build, lemme know if you have anymore issues with it
