### ISSUE TITLE
Lightmap playerspace tool brush blocks nav generation in Hammer

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#2159]
### Describe the bug

When I tried previewing my nav mesh in Hammer, it got blocked by my lightmap playerspace brushes.
To work around this, I had to select those brushes and set their `Physics Type` to `None` instead of `Default`.

### To Reproduce

1. Make an empty box map
2. Place lightmap playerspaces brushes on your map
3. Create a walkable seed in the navigation tab
4. Click on "Nav Preview"
5. See issue

### Expected behavior

Should not be considered as something solid as it's an editor brush.

### Media/Files

![image](https://user-images.githubusercontent.com/67245359/184137187-a61a401b-9775-4786-b04c-ec4781e03f43.png)

**Comment by Fortune117** [comment]
This also happens with blocklights.

**Comment by KayaDLX** [comment]
This happens for physics simulations as well. Just got an issue where my func_precipitation was blocking the physics simulation in Hammer.

**Comment by bakscratch** [comment]
Seems like the material attributes is being ignored for no collision.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by KayaDLX** [comment]
Fixed, thanks!
