### ISSUE TITLE
ConditionalVisibilityAttribute not working on properties inside of categories

### ISSUE THREAD

**Issue by liquiad** [Facepunch/sbox-issues#2162]
### Describe the bug

If you have an asset property with some kind of `ConditionalVisibilityAttribute` and `CategoryAttribute`, no properties will show in that category, even when the condition is met.

### To Reproduce

Create a custom asset type with some properties that use a `ConditionalVisibilityAttribute` and `[Category]`

### Expected behavior

The properties should show up in their category when their conditions are met.

### Media/Files

Without `[Category]`

```cs
public ItemType Type { get; set; }

[ShowIf( nameof( Type ), ItemType.Clothing )]
public Clothing Clothing { get; set; }

[ShowIf( nameof( Type ), ItemType.Clothing )]
public ClothingSlot ClothingSlot { get; set; }
```

https://user-images.githubusercontent.com/13039986/184253371-dc3935c4-1da9-46ef-a9d6-011b2ffb0cf5.mp4

With `[Category]`

```cs
public ItemType Type { get; set; }

[Category("Clothing"), ShowIf( nameof( Type ), ItemType.Clothing )]
public Clothing Clothing { get; set; }

[Category("Clothing"), ShowIf( nameof( Type ), ItemType.Clothing )]
public ClothingSlot ClothingSlot { get; set; }
```

https://user-images.githubusercontent.com/13039986/184253374-db6de706-9eb8-4652-b9e3-c1a9dcb070c8.mp4

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
