### ISSUE TITLE
Entity.IsFromMap is always false on Spawn

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#2167]
### Describe the bug

IsFromMap property on entities will always return false when it's accessed inside the Spawn method.

### To Reproduce

1. Write an entity that logs the IsFromMap property on Spawn
2. Place entity on a map in Hammer
3. Load into level
4. IsFromMap is false

### Expected behavior

IsFromMap should always return true if it's loaded by the map.

**Comment by aylaylay** [comment]
I don't think this can currently be done with how the flag is set, It's done post spawn. Thoughts, @robotboy655 ?

**Comment by robotboy655** [comment]
Found a way to do it, let us know if it causes any issues or doesn't fix it completely.

**Comment by krotter0** [comment]
Seems to be working fine, thanks.
