### ISSUE TITLE
Stuck in Golf Corse 7 (Minigolf Game)

### ISSUE THREAD

**Issue by DevOMan-Source** [Facepunch/sbox-issues#2168]
### Describe the bug

I got stuck in the water pit on stage 7 in mini golf

### To Reproduce

You hit ball into pit and then you are stuck

### Expected behavior

Stuck in Pit

**Comment by liquiad** [comment]
Have you thought about posting this issue on the minigolf repo?

https://github.com/Facepunch/sbox-minigolf/
