### ISSUE TITLE
Allow numeric input for mesh operations in Hammer

### ISSUE THREAD

**Issue by wouterpleizier** [Facepunch/sbox-issues#217]
**What can't you do?**

Certain mesh operations in Hammer use the current grid size as a parameter. E.g. when the grid size is 64, selecting an edge and using Bevel will cause the bevel to have a size of 64x64 units. This is a useful time saver, but it limits you to using powers of two up to 512.

**How would you like it to work?**

It would be nice to also have an option that lets you enter a specific number that should be used as the parameter. Maybe a numeric input popup if Ctrl or Shift is held when clicking the button? This way it wouldn't clutter up the user interface or conflict with existing hotkeys. Alternatively, allow the user to override the parameter afterwards by typing in a number with the numpad, similar to how it works with the translate, rotate and scale tools.

**What have you tried?**

From what I can tell, there are currently no hotkeys or other ways to affect this behaviour.

**Additional context**

The following mesh operations use the grid size as a parameter:
Vertex - Bevel
Edge - Bevel
Edge - Extrude
Edge - Extend
Face - Thicken Faces

**Comment by robotboy655** [comment]
Related https://github.com/Facepunch/sbox-issues/issues/892
