### ISSUE TITLE
Toolbox like Roblox

### ISSUE THREAD

**Issue by DissolveDZN** [Facepunch/sbox-issues#2170]
### For?

Hammer

### What can't you do?

download community-made maps, scripts, sounds, music, images, skyboxes, meshes (with scripts) or custom properties etc...

### How would you like it to work?

Roblox has a toolbox which is very handy in most situations since you can easily add placeholders and even final props/see above. It's very good to learn the basics of hammer since you could examine the downloaded content. I know that it is already possible to download maps, full addons and entities but it would be useful to be able to import them directly into your current project which as far as I know isn't easy to do right now. And you currently can't search for something like mentioned above besides in s&works (only props without custom scripts) which could be expanded upon into a kind of roblox toolbox

![image](https://user-images.githubusercontent.com/66252754/184501045-e59feb2c-3adb-4371-bbb0-2c0f827bd9db.png)

### What have you tried?

nothing, this is just a quality of life/workflow request

**Comment by DoctorGurke** [comment]
this is basically what asset.party (sworks) content is supposed to be down the line I believe. You can currently upload models to it and use those any way you want dynamically from games, but there's also official hammer integration on the way and I don't see why this can't be expanded to other asset types as well

**Comment by DissolveDZN** [comment]
yea i didn't know they were already working on it, i also said that they can expand s&works into a kind of roblox toolbox thing because as far as i know you currently can't add custom scripts/ properties to your models
