### ISSUE TITLE
S&box isn't in my library anymore

### ISSUE THREAD

**Issue by Tom21200** [Facepunch/sbox-issues#2174]
I don't know where to post this but it isn't in my library anymore (it's been a while but I didn't said anything) , and I used it pretty often.. so.. I don't know

**Comment by lyricsdev** [comment]
@DevulTj open it again.

**Comment by Tom21200** [comment]
I knew it would be closed instantly.. well if there is a support, someone tell me

**Comment by bakscratch** [comment]
Try steam support as it sounds like a steam issue.

**Comment by ogniK5377** [comment]
What's your steam id

**Comment by ogniK5377** [comment]
Found it, your key was not revoked in error. Your key was revoked due to a lack of activity in the game. You have not launched the game for 10 months & 30 days. Nearly an entire year, therefore your key was revoked

**Comment by Tom21200** [comment]
The problem is that I haven't waited 10 months :|
