### ISSUE TITLE
Error List NullReferenceException upon refresh when Error List is closed

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#2175]
### Describe the bug

When loading a gamemode and any warnings happen while doing so, the loading fails because the Error List triggers an exception when refreshing the UI. Only happens if you don't have the Error List tab open.

![image](https://user-images.githubusercontent.com/5991682/184530299-81e5afd0-ec0f-4176-b5aa-1c39d6d147ca.png)

### To Reproduce

Start game in dev mode, make sure Error List tab is closed, start a gamemode, and if there are warnings the Error List errors out.

### Expected behavior

Load as normal even while not having the Error List open.

**Comment by cr4yz** [comment]
This should be fixed in the next build

**Comment by Gmod4phun** [comment]
Works like a charm now, thank you
