### ISSUE TITLE
I lost access to sbox

### ISSUE THREAD

**Issue by GGerlach904** [Facepunch/sbox-issues#2176]
### Describe the bug

while i was working on my game in sbox, i recieved this message (german):
![grafik](https://user-images.githubusercontent.com/111230669/184536826-40d9d983-d6b2-4f8b-893b-12ce6e6b7072.png)
and then i couldnt start

### To Reproduce

i was using sbox while i got this message, so it couldnt have been the 10 month timeout
i was also using it yersterday just fine

### Expected behavior

can someone please help me with this, i dont want to lose access..

**Comment by DevulTj** [comment]
Don't use GitHub issues for this. Refer to https://asset.party/~get to retrieve access. Further issues will be closed.

**Comment by GGerlach904** [comment]
i had acces, the blue bar saying i don't isnt even there
i own the game since 2nd august, why is it gone?
please.. i am really sad

**Comment by aylaylay** [comment]
Alt of https://github.com/CrezyDud - Abusive towards developers.

**Comment by GGerlach904** [comment]
i am sorry
