### ISSUE TITLE
Base Shader Tanks Performance

### ISSUE THREAD

**Issue by magnusm1908** [Facepunch/sbox-issues#2177]
### Describe the bug

When using the unmodified base shader for a material, the material severely drops performance.
Same as when I use a copy of the base shader with or without modifications.

Using 'Base Shader' on a material inside a test map, the performance widget shows 'Rendering Present' goes up by a lot compared to the 'Simple Shader' as shown in the pics I've attached.

### What I've tried
'Verifying Files' fixed it temporarily but it got back to low fps by unknown cause. Only worked once.

Tried deleting the shaders folder within the addons/base and verifying again with no luck.

Turning off 'Tiled Rendering' didn't work, it made it worse. (r_tiled_rendering 0)

### To Reproduce

Create new material using the base shader.

When looking at the material in hammer or in-game, frames drop by roughly 40%

### Expected behavior

'Base Shader' should not use that many resources.

### Media/Files

When I use the base shader, the 'Rendering Present' metric goes up alot, compared to the simple shader.
![Simple Shader](https://user-images.githubusercontent.com/25257251/184535792-d44af6b6-4d91-4ff6-af45-eecd74c79c9c.png)
![Base Shader](https://user-images.githubusercontent.com/25257251/184535793-fba2b672-5ef2-4722-8d5b-fd08cff38769.png)

### Additional context

Specs:
Windows 10

GPU:
gtx 1060 6gb

CPU:
Intel i5-7300HQ 2.5Ghz

**Comment by samzanemesis** [comment]
I am to finish the shader API & standard shading model and with that also do a full optimization pass on it, right now it's missing some culling attributes present on Valve's shading model

**Comment by magnusm1908** [comment]
It seems to be fixed with your latest commit! Thank you

**Comment by samzanemesis** [comment]
There are still optimizations to do on base shader tho
