### ISSUE TITLE
Animgraph - Copy/Paste Parameters

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#2179]
### For?

Other

### What can't you do?

Currently when you want to make parameters you have to make them from scratch, when you could copy/paste a similar one and then rename it.

### How would you like it to work?

Right click on a parameter to display the copy and paste option.

### What have you tried?

Thinking about this feature.

**Comment by robotboy655** [comment]
@aylaylay Added this.

![image](https://user-images.githubusercontent.com/3299036/184649244-737b6259-71b2-4499-bab2-dd398fa3d31d.png)

**Comment by KaesarZZ** [comment]
I don't get a complete duplicate, it only transfers the Network tick, the other properties are ignored. If you have animations that are practically the same the idea is to optimize your time.

**Comment by aylaylay** [comment]
I'll see what other properties can be copied over - unless @robotboy655 gets to it.

**Comment by aylaylay** [comment]
@KaesarZZ All properties of the parameter should now be copied. Let me know if I've missed any.

**Comment by KaesarZZ** [comment]
Nope

https://user-images.githubusercontent.com/40291120/184675188-91f39eba-65e2-4e40-a0c6-45adc1d99527.mp4

**Comment by aylaylay** [comment]
Have you got the latest build from steam?

**Comment by KaesarZZ** [comment]
Yeah tested rn, I'll wait next build, maybe steam trolling or idk.

**Comment by KaesarZZ** [comment]
Correct, after 30 minutes I got the right build lol. All seems perfect, thanks for your quick interest.
