### ISSUE TITLE
animgraph direct playback

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#2182]
### For?

S&Box

### What can't you do?

right now you can't control the animation in animgraph through code, meaning it's hard to implement scripted events, the animgraph direct playback node allowed the ability for the code to control a sequence at a point in the animgraph

### How would you like it to work?

Allow us to reference Direct playback nodes via code and set their sequence name, similar to setting AnimEntity.CurrentSequence.Name i guess.

### What have you tried?

You can disable anim graph and play sequences manually, but doing this means you'll have to make up for what the animgraph previously did through code making layering animations and blending them etc harder.

**Comment by aylaylay** [comment]
Nevermind, I got the jist of it

**Comment by aylaylay** [comment]
Direct playback support has been added. AnimatedEntity.DirectPlayback

**Comment by Xenthio** [comment]
> Direct playback support has been added. AnimatedEntity.DirectPlayback

everything seems to work nicely! would it be possible to get things like the elapsed time of the sequence and/or the total duration of the sequence like you could with AnimEntity.CurrentSequence?
I would also see it being useful to people to reference multiple direct playback nodes seperately that might have different spots in the anim graph aswell.

**Comment by aylaylay** [comment]
All code in HLA used 1 direct playback node, it's the ways it's designed, I'd have to come up with a way to support this. If I can find a sane way to do it, i'll do it.

**Comment by aylaylay** [comment]
@Xenthio I have added Time and Duration getters, let me know if they work for you
