### ISSUE TITLE
Material Browser Crash

### ISSUE THREAD

**Issue by Maxamalamute123** [Facepunch/sbox-issues#2183]
### Describe the bug

Pressing "show hidden assets" on the settings wheel in the material editor will crash the material editor and s&box dev entirely.

### To Reproduce

1. Open s&box dev
2. Go to the material editor
3. Go to the material browser
4. Press the cog in the top right and select "show hidden assets"
5. Your client will crash

### Expected behavior

It should show hidden assets

### Additional context

Running Windows 10 on version 21H2. My PC specs are Ryzen 9 5950X with 2060.

**Comment by Radeoxx** [comment]
Can confirm, here is a video reproducing the bug

https://user-images.githubusercontent.com/12381901/184921612-23ea424b-7a67-4d74-826d-4698d9a8745e.mp4

**Comment by aylaylay** [comment]
Should be fixed now.

**Comment by KayaDLX** [comment]
Tested, this is fixed
