### ISSUE TITLE
Resources can't have float values with magnitude less than 0.01

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2185]
### Describe the bug

Whenever you edit a resource to have a float value of less than 0.01, it rounds up to 0.01. 

I'm trying to implement data for bullets, including their weight and cross sectional area, which often have values much smaller than 0.01.

### To Reproduce

1. Create a resource with a float
2. Edit the float with a value of less than 0.01 or -0.01
3. It will save the value as 0.01 or -0.01

### Expected behavior

Should save the value as provided to the float

**Comment by robotboy655** [comment]
This is done on purpose, the numbers are stored correctly, but are displayed truncated like that in the inspector. This will affect the resources on re-save through the inspector, even if the value was untouched.

@garrynewman Any opinions? Should we just get rid of this limitation?

**Comment by garrynewman** [comment]
We should really have a smarter display of the values I think, actually rounding never but displaying a rounded value.

**Comment by robotboy655** [comment]
https://files.facepunch.com/rubat/1b1311b1/sbox-dev_2A2G1luuKQ.mp4

That should do it.

**Comment by Fortune117** [comment]
Works like a charm :^)
