### ISSUE TITLE
Metric/Customizable Grid

### ISSUE THREAD

**Issue by iiboharz** [Facepunch/sbox-issues#2187]
### For?

Hammer

### What can't you do?

I can't set the grid to use "metric" values (1, 5, 10, 50, 100, etc.) or otherwise arbitrary values.

### How would you like it to work?

Ideally the user should be given the option of using either powers of two, metric, or maybe, if possible, to be able to set their own grid intervals, with the default selected option being powers of two. This would be a dropdown in the options menu.

![image](https://user-images.githubusercontent.com/5212525/185218688-683d21a3-8769-4c72-afb2-ad5b568aad5b.png)

Selecting the "custom" option would open up otherwise greyed-out fields for the user to enter their own grid intervals, either a fixed number of them (maybe 10-20 fields, and whatever the user leaves empty gets ignored) or with the user being able to add more as they see fit. Obviously I don't know how easily this would be done so this is more of a "nice to have".

The metric grid sizes would be something like:
0.125
0.25
0.5
1
5
10
50
100
500
1000

It would also be useful for the user to be able to set a temporary arbitrary grid size on the fly without entering the options menu (ie: the user should be able to type an arbitrary number in the grid dropdown at the bottom of the Hammer window.)

### What have you tried?

Obviously setting the grid size to 1 allows me to, for example, drag out a cube to about any size I want, but this is imprecise and therefore not practical for use in production.

**Comment by NotGaylien** [comment]
Can i get this looked into
since i have encountered an annoying ass issue where.
1 hammer grid = 0.75 inches.
1 unit also = 1 inch.

and i made something exactly with inches and its off the grid by 1.333333
and scaling 1 inch to 1 hammer grid unit makes everything painfully small.

would be nice to switch between 
0.75 inches (current grid unit size)
1 inch
1 cm or meter

and so on.


Im not asking for the standards to be changed, just the grid snapping size to be able to be adjusted to different sizes.

**Comment by handsomematt** [comment]
what do you mean 1 hammer grid is 0.75 inches

**Comment by MackenzieShirk** [comment]
Would really appreciate this addition, will give more flexibility too when porting content to and from other engines that use metric

**Comment by NotGaylien** [comment]
> what do you mean 1 hammer grid is 0.75 inches

Its a thing with mapping, and art. the code is 1 unit = 1 inch, but if you use realistic scale and treat 1 unit as 1 inch, the map or models will be fucked and look shrunk, so you got to treat the scale as 1 hammer unit = 0.75 inches instead. or just scale realistic scaled models up by 1.33333 to look right.
(this is why most non-vr models look so big in vr)

i think if its a vr map and you treat 1 unit and 1 inch it ends up looking right, but in non-vr it feels cramped and hard to navigate.

idk if its a camera issue, or player issue or something that makes everything feel smaller and cramped / hard to move though, if its in non-vr, but its just always been an issue with maps in source.
