### ISSUE TITLE
0 mbps when downloading missing files

### ISSUE THREAD

**Issue by ottersmans** [Facepunch/sbox-issues#2189]
### Describe the bug

I tried to play Construct for the first time, when I was downloading the missing files, the speed was constantly at 3 mbps then it dropped down to 2 or 1 then eventually to 0 but it will download for a bit but at very slow rate. I tried checking Discord or YouTube, my internet was fine

then I tried playing Cat Harvest and still happened. It's at 0 mbps but it will download the kilobytes for like every 5 or 10 seconds

https://imgur.com/a/XBEDs6R

### To Reproduce

1. Play any game for the first time
2. Downloading missing files
3. It will drop to 0 mbps eventually

### Expected behavior

The download speed should be constant at 3 mbps (my max speed)

### Media/Files

https://imgur.com/a/XBEDs6R

### Additional context

Windows 10 Pro 64 Bit, pretty sure it's not related to hardware

My internet still works fine I can watch and browse the internet even s&box downloads at 0 mbps

**Comment by robotboy655** [comment]
This is simply either an issue on your end, or Amazon's servers had a temporary issue. Nothing we can be do here.
