### ISSUE TITLE
Assertion failed in SetupModel

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#219]
**Describe the bug**

SetModel causes an assert to fail, this happens since a recent update (today maybe?):

`SetModel($"models/modular/ceiling.vmdl");`

[ceiling model.zip](https://github.com/Facepunch/sbox-issues/files/6509649/ceiling.model.zip)

**To Reproduce**

1. Add the above model to a gamemode
2. Spawn a model entity and call SetModel with the above model
3. Exception should pop up

**Screenshots**

![sbox-dev_2021-05-19_09-35-28](https://user-images.githubusercontent.com/9637557/118832661-6d12a900-b886-11eb-8c85-38a7de4548f5.jpg)

**Additional context**

The model was made by exporting from hammer to fbx
The first time this exception occurs there's a 3-4 second hang
Other than the exception everything seems fine
I'm calling SetModel in the constructor

**Comment by cr4yz** [comment]
Caused by calling SetModel in the constructor

**Comment by ZenBre4ker** [comment]
Still a problem. Just had this now. But yeah in the constructor seems to be the problem. Why though?
