### ISSUE TITLE
Type of Problem That Spams Errors In Console

### ISSUE THREAD

**Issue by LocationError** [Facepunch/sbox-issues#2191]
### Describe the bug

Only so far tried on the maps Flat Grass and Construct but when you kill a bot specifically on Construct and quickly switch maps the console spams out an error message and the overhead light shows no texture

### To Reproduce

1. start s&box
2. go to sandbox gamemode 
3. pick the map construct
4. spawn a bot using the console
5. stand face to face with the bot with a pistol
6. press esc and preselect Flat Grass 
7. kill the bot and very quickly start the other map

### Expected behavior

 If you get the (attempted to) message as the map is loading usually it indicates that it will happen
The video should be the end result

https://user-images.githubusercontent.com/111539280/185532243-f550b3c4-07da-4c03-abe8-d425272afbce.mp4

### Media/Files

![2022-08-18 20-23-37_Trim_Moment](https://user-images.githubusercontent.com/111539280/185525285-20e2568c-d975-4d8c-aade-ffcd1391d7e0.jpg)

**Comment by liquiad** [comment]
I don't know where you got all of these complicated steps from. This just happens if you load Construct and then Flat Grass without doing anything else.

**Comment by yuberee** [comment]
> I don't know where you got all of these complicated steps from. This just happens if you load Construct and then Flat Grass without doing anything else. Slaughtering a bot is unnecessary.

It's part of the ritual to summon the error.

**Comment by LocationError** [comment]
> I don't know where you got all of these complicated steps from. This just happens if you load Construct and then Flat Grass without doing anything else. Slaughtering a bot is unnecessary.

Well hey I didn't know it was already know plus I couldn't find it anywhere else
