### ISSUE TITLE
Asset Browser: Allow contextmenu on multi selection

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2192]
### For?

S&Box, Other

### What can't you do?

Select multiple assets, right-click and recompile, open in editor, etc.

### How would you like it to work?

Open the context menu for multi-selections and apply its actions to all selected items

### What have you tried?

The context menu will not open via rightclick if you have more than one item selected

**Comment by Gmod4phun** [comment]
This would be a very welcome addition

**Comment by KayaDLX** [comment]
Yes please!

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/188469863-16414379-d778-496e-ad2b-e6545ddfc7c1.png)

**Comment by Gmod4phun** [comment]
This is wonderful, it saves alot of clicking. Would it be possible to also implement such option for selected directories? #2100
