### ISSUE TITLE
Addon uploader: more control over addon upload checkout

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2196]
### For?

S&Box, Other

### What can't you do?

I'm unable to only upload/update specific files when updating an addon, for example for a quick patch of a material while there has already been more changes

### How would you like it to work?

Something similar to the github desktop checkout would be awesome, where we can just tick which files to upload
![GitHubDesktop_VO8dDCxSo2](https://user-images.githubusercontent.com/12602100/185639167-3b024aba-4d1e-4cf7-af05-86d9d8f20ffc.png)

### What have you tried?

Currently it seems to just upload all changed/added files.
Alternatively it'd be possible to make a patch branch and upload from there, assuming the addon is setup with git and your branch situation allows this. ie. tagging a commit for a release version etc

**Comment by DevulTj** [comment]
I don't think this is necessary. Ideally, we'd omit files that don't hold any references instead of allowing to opt out of specific files from being uploaded. That's most probably our target.
