### ISSUE TITLE
Exception when spawning in a map with no spawn points

### ISSUE THREAD

**Issue by TomDotBat** [Facepunch/sbox-issues#220]
**Describe the bug**
When a map has no spawn points the following exception occurs when someone spawns:
![image](https://user-images.githubusercontent.com/11298466/118865737-2bf7b480-b8d9-11eb-9ad9-181484f7bc8c.png)

**To Reproduce**
Make/join a map with no spawn points.

**Expected behavior**
A warning is logged and it returns instead of causing an exception.

**Additional context**
This can be fixed easily by placing a return after line 26 in `base/Game.Pawn.cs`.

**Comment by robotboy655** [comment]
Should be fixed whenever the game updates next. Please reply to this post or feel free to close the issue yourself to let us know if it's fixed

**Comment by TomDotBat** [comment]
Yep that sorted it, cheers rubat.
