### ISSUE TITLE
Resizable player bug

### ISSUE THREAD

**Issue by Maxamalamute123** [Facepunch/sbox-issues#2201]
### Describe the bug

Resizing a car to be really big or really small then getting in and out of it will cause the playermodel to also be affected by the resizer. Meaning the player can be really big or really small.

### To Reproduce

1. Spawn car
2. Use resize tool to make the car massive
3. Enter the car
4. Exit the car
5. You are now big!

### Expected behavior

Either the car should not be resizable (not preferred) or the player should not become the same size as the car (preferred)

**Comment by DoctorGurke** [comment]
This has previously been reported and closed as being an intended feature rather than a bug. This also isn't the right github for a sandbox gamemode specific issue, that should go onto the actual gamemode's issue page.

**Comment by DevulTj** [comment]
This is a Sandbox gamemode specific issue - and everything in that gamemode is in flux - it will either be addressed or removed in the future.
