### ISSUE TITLE
Car does not drive

### ISSUE THREAD

**Issue by Maxamalamute123** [Facepunch/sbox-issues#2202]
### Describe the bug

When entering the car, the body seems to fluctuate up and down and does not drive

### To Reproduce

1. Spawn in a car
2. Enter it
3. Attempt to drive.
4. Fail.
5. Car will despawn on vehicle exit.

### Expected behavior

Car should drive

**Comment by liquiad** [comment]
These issues should probably be submitted to the [sandbox gamemode repo](https://github.com/Facepunch/sandbox) itself rather than here. That car is not part of the base game, it's part of Facepunch's sandbox gamemode.

**Comment by DevulTj** [comment]
This is a Sandbox gamemode specific issue - and everything in that gamemode is in flux - it will either be addressed or removed in the future.
