### ISSUE TITLE
Collision Matrix rules do not seem to use 'least colliding' pair

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#2205]
### Describe the bug

The Collision Matrix logic says that if there are multiple collission pairs found, it choses the least colliding one. Based on my attempts, it seems to not be working correctly. 

Test done using the following Collission Matrix setup:
![image](https://user-images.githubusercontent.com/5991682/185804027-8b2ae8c5-2329-4c6f-b40f-01c0da891427.png)

From the explanation, anything that has the 'ingate' tag should not collide with anything else, and especially with anything that has the 'world' tag. However, adding the 'ingate' tag to a prop does not affect it, it still collides, contrary to what the behaviour should be. Here is a video demonstrating the issue:

https://user-images.githubusercontent.com/5991682/185804218-ac365892-4f07-4870-8a3b-0d3fb04eaeed.mp4

Either I am not understanding the explanation, or there is a problem with deciding which pair of collisions rule to use.

### To Reproduce

Add a collision ruleset that should disable collisions when entity has the appropriate tag, and add that tag to an entity.

### Expected behavior

Expected result is for the entities to not collide.

**Comment by garrynewman** [comment]
The defaults in the left column only apply if there are no matches on the right. If you have other matches on the right it'll use those before it uses the default column. 

I haven't totally parsed your matrix but could that explain what's happening?

**Comment by Gmod4phun** [comment]
You are correct thats what *should* be happening, but it is not. The rule I added for 'world' vs 'ingate' = 'ignore' should disable collisions for world any any entity that has the 'ingate' tag, however it does not. (I am applying the 'ingate' tag to anything that touches the big blue circle of the Stargate) I noticed that the WorldEntity has both the 'solid' and 'world' tag, so I am not sure if that is causing a problem or not, but based on the Matrix, it should be behaving differently than it currently is.

**Comment by garrynewman** [comment]
I think I found out what's happening here.. the "world" tag isn't actually applied to the world. It just has the "solid" tag. I would guess that having "solid" and "ingate" ignore would fix your problems..

**Comment by Gmod4phun** [comment]
I will check this and see if I can get it to work. However I remember checking if the worldentity had the world tag, and it did.

**Comment by garrynewman** [comment]
Yep that's a bug - the world entity has the tag, but the underlying physics don't.

**Comment by Gmod4phun** [comment]
Alright, just checked this, and if I add the 'world' tag on another entity, then it seems to behave as it should, so its indeed an issue with the world tag not affecting the world entity.

As for what I was trying to do, I would need to only disable collissions with the world, and retain collissions with other solid objects, so the world tag not working on the world entity makes what I was doing pretty much not possible/viable at the moment. Should I make a new issue regarding the world tag?

**Comment by garrynewman** [comment]
We already have an issue for the world tag thing on our main repo, but if you want to make one too we can link it.

**Comment by aylaylay** [comment]
I have added a world tag to all physics shapes in the level, see if that fixes this issue.

**Comment by Gmod4phun** [comment]
Seems to work now, thank you very much :)
