### ISSUE TITLE
Setting entity positions makes them slide quickly to the specified point.

### ISSUE THREAD

**Issue by urnotnick** [Facepunch/sbox-issues#2206]
### Describe the bug

I have an entity that over time will scare the player by teleporting behind them to startle them. However, when setting the position (Entity.Position) I have found that I can see them sliding behind me. Typically over larger distances it is easier to see.

### To Reproduce

Set the position of an entity and observe this.

### Expected behavior

When setting the position, the Entity should just be at the position specified, instead of sliding to the point.

### Media/Files

![image](https://user-images.githubusercontent.com/66189083/185805095-d5730e39-4e14-4d42-918b-ae73cb2a9eb4.png)
[Video](https://cdn.discordapp.com/attachments/942744557534212148/1010974833061929160/sbox_0019.mp4)

### Additional context

If you want my code I can send it privately, I'd rather not share it publicly.

**Comment by DoctorGurke** [comment]
call ResetInterpolation after setting the position

**Comment by urnotnick** [comment]
Thanks, this worked.
