### ISSUE TITLE
asset.party gamemode visual bug

### ISSUE THREAD

**Issue by gmeyer2** [Facepunch/sbox-issues#2207]
### Describe the bug

When viewing profiles of creators and gamemodes on the website, clicking on your profile will cause the game or creator to stay on your page. I was able to do this in chrome, brave and also edge. Note: Chrome and Brave had extensions installed but edge was a clean install. Refreshing fixes the visual bug

### To Reproduce

1. Click on any gamemode
2. Click on your name to go to your profile

### Expected behavior

Clicking on your profile should not show other creators and gamemodes.

### Media/Files

https://user-images.githubusercontent.com/111548602/185806532-6e35eccb-3591-4a9e-80ac-d635f1739ccd.mp4

### Additional context

_No response

_

**Comment by robotboy655** [comment]
Cannot reproduce, assuming fixed?
