### ISSUE TITLE
Make an option to edit your addon's visuals locally

### ISSUE THREAD

**Issue by PiMoNFeeD** [Facepunch/sbox-issues#2208]
### For?

S&Box

### What can't you do?

I don't want to create an addon on s&box backend just to change stuff like like it's thumbnail or description when this addon is still being worked on locally and not ready to be published, I know I can keep it hidden but I might not even intend an addon to ever be public ever and that doesn't mean I shouldn't be able to distinguish my local addons by big images rather than small names

### How would you like it to work?

Possibly add a separate configuration menu for that or implement it within project settings

### What have you tried?

I could just hardcode it in the source code for the menu but it's incredibly stupid

**Comment by yuberee** [comment]
If you have enough local addons that it's becoming a problem to distinguish the ones you're working on, why not disable all the others so they don't show up?

**Comment by PiMoNFeeD** [comment]
> If you have enough local addons that it's becoming a problem to distinguish the ones you're working on, why not disable all the others so they don't show up?

that was just an example, that's not the point of my issue
