### ISSUE TITLE
Cannot compile models on ModelDoc

### ISSUE THREAD

**Issue by Maxamalamute123** [Facepunch/sbox-issues#2213]
### Describe the bug

When pressing the "Needs compiling" button on ModelDoc, it will switch to "Compiling..." for a split second before returning to "Needs compiling", despite having not made any changes in that timeframe.

### To Reproduce

1. Open model doc
2. Add a render mesh file
3. Add a default material group
4. Attempt to compile

### Expected behavior

Model should compile successfully

### Additional context

I am using only a rendermeshfile and defaultmaterialgroup and add a file to both of them. Not sure if compiling works for setups that aren't the same as that.

**Comment by aylaylay** [comment]
Can you give me the vmdl and fbx (or whatever mesh file) please

**Comment by Maxamalamute123** [comment]
Here you go.
[layla.zip](https://github.com/Facepunch/sbox-issues/files/9396756/layla.zip)

**Comment by aylaylay** [comment]
I've used your obj and material and added both nodes and it compiled fine for me, is there anything else you can think of that you're doing differently? Like where are you saving the model for example, where are your mesh and material located?

**Comment by Maxamalamute123** [comment]
vmat - "S:\SteamLibrary\steamapps\common\sbox\addons\csgo_weapons\materials\vmat\ak47\vulcan\vulcan_mat.vmat"
Mesh - "S:\SteamLibrary\steamapps\common\sbox\addons\csgo_weapons\models\OBJ\ak-47.obj"
vmodel - "S:\SteamLibrary\steamapps\common\sbox\addons\csgo_weapons\models\VMDL\AK47\ak47_vulcan.vmdl"

**Comment by aylaylay** [comment]
Modeldoc doesn't like folder names like "OBJ" rename that folder while I look into why we can't save with a folder with that name, I think I fixed this elsewhere.

If it's still not compiling then also change the "vmat" and "vmdl" folders.

**Comment by aylaylay** [comment]
"meshes" is a good folder name replacement
