### ISSUE TITLE
Asset Browser/ModelDoc - Game crashes when you try to compile a model

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#2214]
### Describe the bug

I have some outdated models which I didn't compile for a while because I prefer to make changes in a single model, I removed some animations that I used before, which makes that outdated models not compile.

Today, I tried to open a model but I got this message and s&box crashes.

https://i.gyazo.com/e916b768c0a2511abd87114d519d8ae2.png

Tested with Asset Browser Legacy and the same happens.

### To Reproduce

I guess forcing a model not to compile with errors (the citizen I guess) since I am talking about playermodels, try to open it from the assetbrowser being an error.

### Expected behavior

Fix it.

**Comment by trende2001** [comment]
Happened to me too. I was porting a playermodel that was able to be compiled perfectly before, but now it just doesn't.

**Comment by aylaylay** [comment]
Update game

**Comment by KaesarZZ** [comment]
Oopsie fixed
