### ISSUE TITLE
Whitelist System.Activator.CreateInstance(Type, args[])

### ISSUE THREAD

**Issue by TomDotBat** [Facepunch/sbox-issues#222]
**What can't you do?**
Use the overloads of `System.Private.CoreLib/System.Activator.CreateInstance`, useful for inversion of control.

**How would you like it to work?**
```csharp
Activator.CreateInstance(typeof(T), args)
```

**What have you tried?**
No *known* workaround.

**Comment by Erlite** [comment]
You can use `Library.Create<T>(type)` for now, works as long as the provided type has the `[Library]` attribute.

**Comment by Trojaner** [comment]
Should be wrapped instead of whitelisted. It's a dangerous method after all.

**Comment by TomDotBat** [comment]
iirc I saw an overload of this method in the whitelist already, but it's the version that doesn't take any parameters.

**Comment by Erlite** [comment]
Yeah I think that one's fine anyway since you need a `Type`
