### ISSUE TITLE
Ability to set Pitch and Volume on snd_event_point

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2221]
### For?

Hammer

### What can't you do?

We can't set pitch and volume of snd_event_point in hammer

### How would you like it to work?

Volume and Pitch should be properties on snd_event_point in hammer.

There should also be hammer Inputs for SetPitch and SetVolume
![image](https://user-images.githubusercontent.com/39461072/186597034-44cbdbfe-5ae9-4373-b143-5ba2c7eb88d1.png)

### What have you tried?

currently we have to make separate sound resources if we want the same sound at different volumes/pitches in a map

**Comment by bakscratch** [comment]
Added this option.
![image](https://user-images.githubusercontent.com/8184184/190644815-ab86d5b4-249d-4c7c-b10a-bf050fe5858b.png)

**Comment by gvarados1** [comment]
Omg this is epic! Thank you so much bakky!! 😍😍😍😍😍😍😍
Do we need the extra "Override Default" bool though? Seems redundant.
