### ISSUE TITLE
`PhysicsBody.BodyType` isn't networked to client

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#2225]
### Describe the bug

Not sure what category this goes under, asked in the discord about this as well. I'm looking for a way to determine if a prop is movable (i.e `BodyType == PhysicsBodyType.Dynamic`) on client. Currently, `PhysicsBody.BodyType` does not get networked to client, however, other things on the `PhysicsBody` do. Can I get this networked to client? or is this a unreasonable request.

Thanks.

### To Reproduce

Try and access `PhysicsBody.BodyType` on client and notice it defaults to `keyframed`.

### Expected behavior

`PhysicsBody.BodyType` gets networked to the client.

**Comment by aylaylay** [comment]
A networked body on the client actually is keyframed, if you want a way to see if an entity is moveable, we'd add a better way to check for that if there isn't already

**Comment by mzegar** [comment]
Yeah, that would be great. I cannot seem to find a way to do that on client.

**Comment by mzegar** [comment]
What I was looking for was `ModelEntity.PhysicsEnabled`, it solves my issue. It might be reasonable to have this under `PhysicsBody`? Not sure, closing since that would be unrelated to this issue.
