### ISSUE TITLE
Ability to copy text from the in-game console

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#223]
I can't copy text from the in-game console. I have to use the external console in the tools. This is very inconvenient for simple things like getpos.
![image](https://user-images.githubusercontent.com/39461072/118887118-8421bd00-b8bf-11eb-94e1-3206a963519c.png)

**Comment by robotboy655** [comment]
You can left click on a line to copy it, but yeah, a better solution is needed.
