### ISSUE TITLE
Console history/autocomplete stopped working after some latest updates

### ISSUE THREAD

**Issue by Phyksar** [Facepunch/sbox-issues#2230]
### Describe the bug

The list of last entered commands or autocompletes doesn't appear while typing in the console

### To Reproduce

Open sbox-dev.exe, go to console
Start typing any command and enter it
Try navigating through history with arrow keys

### Expected behavior

The list of last entered commands or autocompletes should appear

### Media/Files

![console-history](https://user-images.githubusercontent.com/13320416/187025362-20e4859c-006b-4ff8-9cf6-b2c44496a811.jpg)

**Comment by garrynewman** [comment]
Thanks
