### ISSUE TITLE
Possibility to flood maps with water

### ISSUE THREAD

**Issue by BOGDAN-GRISHIN** [Facepunch/sbox-issues#2232]
### For?

S&Box

### What can't you do?

In old gmod i always wanted to flood maps with water but that was actually really hard to realise.

### How would you like it to work?

Add some tool for example "Flood" and make the options like, depth (in meters), maybe waves control, and possibility to make water poisonous (like swamps in hl2). I think this will be really cool and i think that's not so hard to realise) (just make water and change her level)

### What have you tried?

Nothing, i want you to make it!

**Comment by handsomematt** [comment]
Parent a func_water to an ent_platform?

**Comment by miw1234** [comment]
maybe you could make that addon by yourself?
