### ISSUE TITLE
General TypeLibrary and related regressions as of commit sbox/master#15c885

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2234]
### What it is?

As of commit `sbox/master#15c885` numerous TypeLibrary related Properties and Methods fail the compile Whitelist. This has caused a regression in features and caused games and systems to break without any apparent reason given for the Lockdown.

Affected members (provided by actual existing projects) are:
```
System.Private.CoreLib/System.Type.get_Name()
System.Private.CoreLib/System.Type.get_FullName()
System.Private.CoreLib/System.Reflection.MemberInfo.IsDefined( System.Type, System.Boolean )
System.Private.CoreLib/System.Type.get_IsAbstract()
System.Private.CoreLib/System.Type.get_ContainsGenericParameters()
System.Private.CoreLib/System.Type.get_IsGenericType()
System.Private.CoreLib/System.Type.MakeGenericType( System.Type[] )
System.Private.CoreLib/System.Type.IsAssignableTo( System.Type )
System.Private.CoreLib/System.Type.GetGenericArguments()
System.Private.CoreLib/System.Type.GetProperties()
System.Private.CoreLib/System.Reflection.PropertyInfo.SetValue( System.Object, System.Object )
System.Private.CoreLib/System.Reflection.PropertyInfo.GetValue( System.Object )
System.Private.CoreLib/System.Reflection.PropertyInfo.get_PropertyType()
System.Private.CoreLib/System.Type.get_IsClass()
System.Private.CoreLib/System.Type.GetProperties( System.Reflection.BindingFlags )
System.Private.CoreLib/System.Reflection.PropertyInfo.get_CanRead()
System.Private.CoreLib/System.Reflection.PropertyInfo.get_CanWrite()
System.Private.CoreLib/System.Reflection.MemberInfo.GetCustomAttributes( System.Type, System.Boolean )
System.Private.CoreLib/System.Type.op_Inequality( System.Type, System.Type )
```

### What should it be?

Ways to circumvent these lockdowns should either be provided or the lockdown should be reverted/re-evaluated and considered more carefully.

**Comment by garrynewman** [comment]
I whitelisted some of these, but not all.

Getting a list of properties, Setting and Getting their values should be done via TypeLibrary rather than c#'s built in reflection

**Comment by peter-r-g** [comment]
Still have some things missing:

`System.Private.CoreLib/System.Type.MakeGenericType( System.Type[] )` doesn't exist in TypeLibrary. I use it for networking generic types in custom networking.
`System.Private.CoreLib/System.Type.GetGenericArguments()` doesn't exist in TypeLibrary. I use it for the same reason as above.
`System.Private.CoreLib/System.Type.get_IsClass()` doesn't exist in TypeDescription. I use it to verify that the type provided is a class for entity replication in custom networking.

**Comment by garrynewman** [comment]
With `System.Type.MakeGenericType` is your reason to create the generic type? Or do you want to keep it around for some reason?

**Comment by peter-r-g** [comment]
It is to create a generic type. I use it in my custom networking library [here](https://github.com/peter-r-g/SBox-CustomNetworking/blob/master/Server/Shared/Utility/NetworkReader.cs#L60). Currently it's used by two builtin networkables; those being [NetworkedList<T>](https://github.com/peter-r-g/SBox-CustomNetworking/blob/master/Server/Shared/Networkables/Builtin/NetworkedList.cs) and [NetworkedHashSet<T>](https://github.com/peter-r-g/SBox-CustomNetworking/blob/master/Server/Shared/Networkables/Builtin/NetworkedHashSet.cs). The functionality is also there for anyone who wants to create their own generic networkables.

**Comment by garrynewman** [comment]
Got it

**Comment by liquiad** [comment]
If I try to access the new MethodDescription.Parameters I get a whitelist error:

```cs
foreach ( var parameter in method.Parameters )
```

```
Not in whitelist: System.Private.CoreLib/System.Reflection.ParameterInfo 
```

**Comment by garrynewman** [comment]
That should be in now :)

**Comment by DoctorGurke** [comment]
gonna close this as most of it has been addressed, anything specific should probably have new issues made as this was mostly made following a specific update
