### ISSUE TITLE
There is currently no way to get the local client's voice level

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2236]
### What it is?

VoiceLevel is always 0 for the local client.

### What should it be?

VoiceLevel should be populated for the local client via Voice.Level

**Comment by aylaylay** [comment]
You find out if you're using the mic with Voice.IsRecording

**Comment by trundler-dev** [comment]
oh lol... ok thanks

**Comment by aylaylay** [comment]
If you want Voice.Level or something, I could add that. Base addon has VoiceSpeaker UI btw which shows a little speaker icon when you're speaking.

**Comment by trundler-dev** [comment]
Voice.Level would be great!

**Comment by aylaylay** [comment]
You now have Voice.Level

**Comment by trundler-dev** [comment]
Looks good! Thanks Laylad
