### ISSUE TITLE
Input.GetAnalog returns outdated values on server for gamepad controller

### ISSUE THREAD

**Issue by Phyksar** [Facepunch/sbox-issues#2238]
### Describe the bug

1. The values returned by `Input.GetAnalog` never come to zero serverside, staying the same as they were before releasing the input axis.
2. `Input.Forward` and `Input.Left` are multiplied by some "magic constant" `1.5`, I'm lost in thoughts what it can be. This results in clipping, some input positions are lost. (shown on 2nd screenshot)
    > Input.Forward: `0.767922 / 0.512 = 1.499847`
    > Input.Left: `0.17825861 / (-0.119) = -1.497971` (I suppose X-axis is inverted because it represents the right direction of move)

### To Reproduce

Here is the code I'm using to debug the problem:
```csharp
private void DumpInputStateToScreen(Vector2 screenPosition)
{
    DebugOverlay.ScreenText($"IsServer: {IsServer}", screenPosition, 0, Color.White);
    DebugOverlay.ScreenText($"Input.Forward:                             {Input.Forward}", screenPosition, 1, Color.White);
    DebugOverlay.ScreenText($"Input.Left:                                {Input.Left}", screenPosition, 2, Color.White);
    DebugOverlay.ScreenText($"Input.GetAnalog(InputAnalog.Move):         [{Input.GetAnalog(InputAnalog.Move)}]", screenPosition, 3, Color.White);
    DebugOverlay.ScreenText($"Input.GetAnalog(InputAnalog.Look):         [{Input.GetAnalog(InputAnalog.Look)}]", screenPosition, 4, Color.White);
    DebugOverlay.ScreenText($"Input.GetAnalog(InputAnalog.LeftTrigger):  [{Input.GetAnalog(InputAnalog.LeftTrigger)}]", screenPosition, 5, Color.White);
    DebugOverlay.ScreenText($"Input.GetAnalog(InputAnalog.RightTrigger): [{Input.GetAnalog(InputAnalog.RightTrigger)}]", screenPosition, 6, Color.White);
}
```
I am calling it in Pawn's `Simulate`, `FrameSimulate` of default game template.
```csharp
public override void Simulate( Client cl )
{
    base.Simulate( cl );

    if (IsServer) {
        DumpInputStateToScreen(new Vector2(128.0f, 32.0f));
    }
```
```csharp
public override void FrameSimulate( Client cl )
{
    base.FrameSimulate( cl );

    DumpInputStateToScreen(new Vector2(128.0f, 180.0f));
```

### Expected behavior

The input values should be the same on both client and server. The `Input.Forward` and `Input.Left` should return the same values as `Input.GetAnalog(InputAnalog.Move)`.

### Media/Files

![ezgif-3-44fc06e822](https://user-images.githubusercontent.com/13320416/187069033-51ddfa9c-80ea-413d-a3ac-b5e4ca678433.gif)
![ezgif-3-44fc06e822](https://user-images.githubusercontent.com/13320416/187069034-9b952d77-3f87-48f9-8786-c5455f54a195.png)

### Additional context

I am using Dualshock 4 gamepad controller with Steam Input emulation enabled by default.

**Comment by handsomematt** [comment]
I'll fix 1, I don't think 2 is a bug as you can control that by overriding BuildInput and adjusting the MoveDirection iirc, the default BuildInput mimicks Source which multiplies controller analogs by 1.5 for movement.

**Comment by handsomematt** [comment]
I've zeroed these out now when the controller is not being used, I'd recommend if you're accessing anything analog based like this from the controller you can wrap it with `if ( Input.UsingController ) { }`

And some more on the analog mismatch, if you want to change the behavior you can do it all within your game:

```csharp
// AnalogMove / AnalogLook taking controller input
InputBuilder.AnalogMove += new Vector3( Instance.AnalogInputs[(int)InputAnalog.Move].y * 1.5f, -Instance.AnalogInputs[(int)InputAnalog.Move].x * 1.5f, 0 );
InputBuilder.AnalogLook += new Angles( -Instance.AnalogInputs[(int)InputAnalog.Look].y * 1.5f, -Instance.AnalogInputs[(int)InputAnalog.Look].x * 1.5f, 0 );

// Game.BuildInput using that input
inputBuilder.ViewAngles += inputBuilder.AnalogLook;
inputBuilder.InputDirection = inputBuilder.AnalogMove;
```

**Comment by Phyksar** [comment]
Thanks, 2nd was more like a question, it wasn't obvious for me why inputs get multiplied.
