### ISSUE TITLE
Server info API

### ISSUE THREAD

**Issue by MatStef132** [Facepunch/sbox-issues#2242]
### For?

S&Box, Other

### What can't you do?

Can't get detailed information about a server (player list, player count, current map etc.)

### How would you like it to work?

An api probably on asset.party which would return info about servers in a specific gamemode or just a specific server with all the info you would need which I listed above. It could be useful if in the future if someone wanted to create something like gametracker or just use it for displaying info about your own server on your discord/website.

### What have you tried?

I have tried asking a couple of people that played the game and searching in the API. I also looked at the networking tab in asset.party and it wasn't returned anywhere, because it probably wasn't needed. There wasn't an endpoint for this.

**Comment by yuberee** [comment]
Something like this? https://sap.facepunch.com/asset/fish.stud_jump/
You can access it in game with `Package.Fetch( "fish.stud_jump" )`

**Comment by MatStef132** [comment]
> 

I was talking about the web API (an endpoint to access that information), not a in-game function or something. Sorry I wasn't specific D;

**Comment by DevulTj** [comment]
I don't think we have any plans for this currently.
