### ISSUE TITLE
Soundscape cannot be edited

### ISSUE THREAD

**Issue by Redesaile** [Facepunch/sbox-issues#2244]
### Describe the bug

When I try to create my own soundscape, there are no problems before editing, after the first attempt to edit the file it becomes clear that I cannot do this, the settings are not saved.

### To Reproduce

1. Create a `.sndscape` file
2. Open it
3. Add some looped or sting sounds
4. Save changes
5. Reopen it
6. See error

### Expected behavior

All added sounds should disappear completely. Even editing the file through a code editor does not work, s&box replaces everything with null.

### Media/Files

**Before saving and reopening:**
![](https://user-images.githubusercontent.com/90133781/187090282-f026279a-beda-437a-9851-c6889f137af8.png)

**After saving and reopening:**
![image](https://user-images.githubusercontent.com/90133781/187090309-aca2ef8e-d825-42d3-9a9b-66751d14b1d8.png)

### Additional context

**Device:** Laptop
**OS:** Windows 10 21H1
**Processor:** Intel(R) Core(TM) i7-3537U CPU @2.00GHz
**Memory:** 4 GB RAM
**Graphics:** Nvidia GeForce GT 720M

**Comment by Adesii** [comment]
This issue isn't exclusive to Soundscapes.

![image](https://user-images.githubusercontent.com/37816311/187766514-72dcf2b0-d8ab-4bd7-b1fb-ff5008466065.png)

Custom Game Resources also encounter this issue.
I also get an error when selecting the iron resource after the asset selector closes.

![image](https://user-images.githubusercontent.com/37816311/187766732-a797d0f7-ed04-4dbd-8573-590b18c4d875.png)

**Comment by garrynewman** [comment]
I think I fixed this - can you let me know please <3

**Comment by Redesaile** [comment]
This works for me!

I can't check the Custom Game Resources, but the official soundscape just works now.

https://user-images.githubusercontent.com/90133781/187909856-85aa23bd-086b-4105-a89d-01aa07898b29.mp4

**Comment by Redesaile** [comment]
Custom Game Resources also work properly.

https://user-images.githubusercontent.com/90133781/187920441-7a899147-7599-4c3d-a0cf-26da71d1c44d.mp4

**Comment by Adesii** [comment]
yeah, my custom resources work now too
