### ISSUE TITLE
Allow keybind for "Replace Objects With Instances"

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#2247]
### For?

Hammer

### What can't you do?

Currently no keybind for "Replace Objects With Instances"

### How would you like it to work?

Allow a keybind instead of having to right click and go to the tab where the option is located

### What have you tried?

...

**Comment by bakscratch** [comment]
Useful to have a quick bind for.
![image](https://user-images.githubusercontent.com/8184184/190633103-ac488eb1-67bc-41d3-9a4d-b13e970c4b14.png)
