### ISSUE TITLE
text-transform

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#225]
What can't you do?
Use text-transform in CSS (e.g. to capitalize text)

How would you like it to work?
See below

Additional context
https://www.w3schools.com/cssref/pr_text_text-transform.asp

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
