### ISSUE TITLE
NPC Clip Doesn't Affect Navmesh Generation Anymore

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2250]
### Describe the bug

Some tool materials don't affect navmesh generation when they should (and used to)
This is breaking my maps because I can't properly adjust nav

Here are the affected tool materials. They don't affect navmesh generation but they should.
- Invisible
- Clip
- NPC Clip
- Nav Clip
- Ladder

### To Reproduce

1. Create a map with an affected material
2. Try to generate navmesh
3. Nav Generates incorrectly

### Expected behavior

Specific tool materials should affect navmesh generation

### Media/Files

There is an npc clip connecting these two areas but the navmesh doesn't care and doesn't generate on it anymore. It used to before the collision update.
![image](https://user-images.githubusercontent.com/39461072/187526662-c7511370-f72c-4c7b-988f-bac471913e52.png)

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/195656168-9cf2798d-a93f-4cd3-82b5-cacd2dbb3e61.png)

Should be fixed when the game next updates. I am not sure player clip should affect the navmesh, but I made it affect it for time being.
