### ISSUE TITLE
SceneModel lacks GetAttachment and SetAnimParameter for Rotations

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#2256]
### What it is?

The SceneModel class lacks a GetAttachment function entirely and SetAnimParameter is missing for Rotation types

### What should it be?

SceneModel's API should be nearly identical to AnimatedEntity I would think?

My current use for it is to set a hand IK position and rotation based on a weapon's attachment.
Can't do it currently.

**Comment by aylaylay** [comment]
SceneModel now has GetAttachment, same API as ModelEntity, let me know if it works for you.

**Comment by aylaylay** [comment]
Missing SetAnimParameter for rotation has also been added (but I think anim params API is going to change slightly soon?)

**Comment by ShadowBrian** [comment]
Works perfectly- thanks!

I used it here for the front grip on the RPG and SMG models. :)

https://user-images.githubusercontent.com/11138884/190893717-d63d1375-0931-49dc-8488-701cfa471fdf.mp4
