### ISSUE TITLE
FGD parameter for editor-only rendercolor

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#226]
**What can't you do?**
set an editor-only rendercolor via the fgd for something like the new tintable info_player_start model

**How would you like it to work?**
@PointClass base(Targetname) editormodel( "models/dev/playerstart_tint.vmdl" ) color(255 50 50) = my_entity : 
    "tinted info_player_start entity"
[
]

Note the "color(rrr ggg bbb)", this supposedly (according to vdc) tinted the editor bounding box in source 1 but doesn't seem to do anything anymore.

**What have you tried?**
@PointClass base(Targetname) editormodel( "models/dev/playerstart_tint.vmdl" ) = my_entity : 
    "tinted info_player_start entity"
[
    rendercolor(color255) : "" : "50 50 255" : 
        "Only used for editor colour, has no impact on the game"
]

**Additional context**
using the rendercolor parameter works, but isn't technically editor-only and can be changed via the entity properties, I'd like this to be only set via the fgd

**Comment by gvarados1** [comment]
It would be great if we could also link colors to the choices parameter
![image](https://user-images.githubusercontent.com/39461072/119014377-889cb300-b95d-11eb-9c0c-81c388be8611.png)
That way we'd be able to set different colors for different team spawns

Or different colors for different rarity or tier of loot.
