### ISSUE TITLE
scss width And left Properties Have Weird Behaviour

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#2261]
### Describe the bug

width: 50% and left: 25% (or any other percentage) are giving surprising results. Namely:

1) width: 50% does not make the element half the width of the screen (image A).
2) left: 50% does not put the element one half of the width of the screen from the left (image B).
3) if width is less than left then it causes the element to shrink (image C - in this image left is set to 50% and width is set to 25% - I guess I would expect this to make a box of size 25%, 50% away from the left, but instead it seems to glitch out).

This codepen shows the sort of thing I guess I would be expecting to see: https://codepen.io/anthonysharpy/pen/gOzObqO

### To Reproduce

This code should be able to reproduce it.

I also tried with position: absolute. Initially I actually tried position: fixed but it kept telling me that was invalid.

#####################

PlayerHealth.cs
```
using Sandbox;
using Sandbox.UI;
using Sandbox.UI.Construct;

namespace LameRP;

public class PlayerHealth : Panel
{
	private Panel Background;

	public PlayerHealth()
	{
		Background = Add.Panel("health-background");
	}
}
```
GUI.scss

```
.health-background {
    background-color: rgba(0, 0, 0, 0.5);
    width: 50%; // Adjust as desired
    height: 50%;
    top: 25%;
    left: 50%; // Adjust as desired
}
```
PlayerHud.cs

```
using Sandbox.UI;

namespace LameRP;

public class PlayerHUD : RootPanel
{
	public Label Label;

	public PlayerHUD()
	{
		StyleSheet.Load( "/GUI/GUI.scss" );
		SetTemplate( "/GUI/HUDTemplate.html" );
	}
}
```
HUDTemplate.html (I could also reproduce this not using a template).

```
<root>

    <PlayerHealth></PlayerHealth>

</root>
```

### Expected behavior

1, 2 and 3 above should work as described.

### Media/Files

Image A

![image](https://user-images.githubusercontent.com/55365296/188014619-8e73b3a6-8488-4586-bf99-97628e4b6409.png)

Image B

![image](https://user-images.githubusercontent.com/55365296/188017256-66325e1e-6d23-4e91-b3b8-dff34e1bf361.png)

Image C

![image](https://user-images.githubusercontent.com/55365296/188015629-73f60b8b-1311-46e6-be48-39a4da9250f0.png)

### Additional context

Only tested in the editor.

Thanks 😄

**Comment by handsomematt** [comment]
your PlayerHealth is also an element that needs to be styled, your % width on .health-background is based on it's parent PlayerHealth and not the root panel.

Check out the panel inspector to see what's going on

**Comment by anthonysharpy** [comment]
@handsomematt Yup, that's perfect now. I just had to add position: absolute to my .health-background and add:

```
PlayerHealth {
    width: 100%;
    height: 100%;
}
```

I didn't know the Panel Inspector was a thing so I've mentioned it in the wiki: https://wiki.facepunch.com/sbox/UI. Feel free to yeet it if it's no good.

Thanks!
