### ISSUE TITLE
func_precipitation volumes have collisions in hammer editor physics simulation

### ISSUE THREAD

**Issue by FireKeep-HLA** [Facepunch/sbox-issues#2262]
### Describe the bug

When attempting to physics simulate a chair in hammer editor, I came to realize for some reason the func_precipitation volume collided with it. So I can have a chair resting on top of a volume now. In editor.

The effect of course immediately dissapears in-game after a compile. This appears to be a hammer thing only.

### To Reproduce

1. Make a func_precipitation volume (can be any size!).
2. Get a prop that is able to be physics simulated in hammer.
3. Simulate, hopefully attempting to get the two to collide in the process.
4. Huzzah! It appears the volume causes physics props to collide with it in the editor.

### Expected behavior

This should behave like a normal trigger volume - no collisions between the two!

### Media/Files

![sbox_wtf](https://user-images.githubusercontent.com/69137890/188052408-b6f177d9-d67c-4690-91f5-41c45e481328.gif)

**Comment by KayaDLX** [comment]
Related issue: #2159

**Comment by robotboy655** [comment]
I had a brief look, from what I can tell it's probably the tag stuff in `mapdoclib/physicsmodel.cpp`. Interestingly in my tests the trigger tool texture works correctly while others do not.

**Comment by garrynewman** [comment]
It's in the material attributes rather than hardcoded in code now

**Comment by robotboy655** [comment]
Oh shit it is the tags, they just aren't updating live in Hammer.

The issue should be fixed when the game next updates.

**Comment by FireKeep-HLA** [comment]
Tested it with the same setup, there are now no collisions between the two. Cannot say the same with other tools textures but given the scope of this issue it's now closed.
