### ISSUE TITLE
Panel.GetAttribute ignores specified default value

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#2263]
### Describe the bug

Panel.GetAttribute will return null if the panel has no attributes at all, but works fine otherwise.

The implementation looks like this right now:
```cs
        //
        // Summary:
        //     Used in templates, try to get the attribute that was set in creation
        public string GetAttribute(string k, string defaultIfNotFound = null)
        {
            if (Attributes == null)
            {
                return null;
            }

            if (Attributes.TryGetValue(k, out var value))
            {
                return value;
            }

            return defaultIfNotFound;
        }
```

### To Reproduce

Use Panel.GetAttribute on a panel which has no attributes, with a custom defaultIfNotFound value.

### Expected behavior

It should be consistent with any number of attributes.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by krotter0** [comment]
Works fine now, thanks.
