### ISSUE TITLE
Soundscape can't loop sound

### ISSUE THREAD

**Issue by Redesaile** [Facepunch/sbox-issues#2265]
### Describe the bug

When I tested my soundscape, looped sound didn't work.

I enabled looping via **.meta** in the audio file settings, but the sound didn't stop after exiting the soundscape. Re-entering the soundscape creates another sound.

### To Reproduce

1. Run a map with a soundscape that loops the sound
2. Enter the soundscape

### Expected behavior

The soundscape should loop sounds.

Looped via **.meta** sound should stop if not used.

### Media/Files
**Looping in Soundscape:**
**Note:** Sound quality is poor due to fps, sorry about that.

https://user-images.githubusercontent.com/90133781/188195697-9ec3227f-07d9-4d61-a4ef-15bb40ea1912.mp4

**Looping created by .meta file:**
**Note:** "outdoors" in the inspector means nothing, I just forgot to maximize the game window :/

https://user-images.githubusercontent.com/90133781/188195772-26a7f613-c85d-403e-a7e9-f1df4680318e.mp4

### Additional context

Steam Audio baked

**Device:** Laptop
**OS:** Windows 10 21H1
**Processor:** Intel(R) Core(TM) i7-3537U CPU @2.00GHz
**Memory:** 4 GB RAM
**Graphics:** Nvidia GeForce GT 720M

There is something similar in another report under ID https://github.com/Facepunch/sbox-issues/issues/2128.

**Comment by robotboy655** [comment]
I cannot reproduce the sounds not looping, I am going to assume this was fixed since this report.

**Comment by Redesaile** [comment]
On some maps from Asset.Party everything works fine, but I have some problems 😥

https://user-images.githubusercontent.com/90133781/198828077-32f8b1f2-8294-477e-a958-cdb24855e2b7.mp4

**Comment by Redesaile** [comment]
On some maps from Asset.Party everything works fine, but I have problems 😥

https://user-images.githubusercontent.com/90133781/198828132-0c823a4f-92ba-4d15-842a-669afe7c8ae4.mp4

**Comment by robotboy655** [comment]
Press this:
![image](https://user-images.githubusercontent.com/3299036/198830678-85141e5e-e106-4c8d-b4c7-f087a4dde929.png)

And recompile the asset

**Comment by Redesaile** [comment]
Somehow I didn't think about it 🤯

Well, everything is fine 🙂

https://user-images.githubusercontent.com/90133781/198834485-71ad0a0d-2515-4015-b449-a400d6c3681e.mp4
