### ISSUE TITLE
Asset Browser - Drop shadow for the filter dropdown isn't set at the right position

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#2269]
### Describe the bug

Whenever I open the asset browser filters, I get to see its drop shadow being placed at the corner of my game viewport instead of being below it.

### To Reproduce

1. Click on the filter dropdown
2. Notice where the drop shadow is placed

### Expected behavior

Should be below the filter dropdown.

### Media/Files

![image](https://user-images.githubusercontent.com/67245359/188266780-048cddec-2a9a-4c4b-9c70-93f685d6844f.png)

**Comment by garrynewman** [comment]
Fixed
