### ISSUE TITLE
linear-gradient rotation is incorrect

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#2271]
### Describe the bug

Specifying an angle for linear-gradient will result in incorrect rotation of the gradient. 14deg or 0.25rad appears to be 90°.

### To Reproduce

Use linear-gradient with a rotation.

### Expected behavior

Properly rotated gradient.

### Media/Files

![image](https://user-images.githubusercontent.com/65136069/188269336-24f46808-11c3-46fd-9811-ae92dfea4894.png)

### Additional context

`to left`, `to bottom`, etc. works correctly.

This does not appear to be an issue with other properties, `transform: rotate(90deg);` works as expected for example.

**Comment by cr4yz** [comment]
This should be fixed in the next update

**Comment by krotter0** [comment]
Yep, it's working. Thanks.
