### ISSUE TITLE
Entity velocity never gets set to zero when making their physics bodytype static after being dynamic

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#2273]
### Describe the bug

I found this bug from playtesting Fortwars though at the time I wasn't sure what caused it, now I know!

The walk controller sets "BaseVelocity" based on the item it's standing on, so in the Sandbox gamemode if you move your prop and freeze it mid-move it retains its velocity and will launch you if you try standing on it.

### To Reproduce

1. Go to the Sandbox gamemode on any map
2. Spawn a prop
3. Move it and hit right click while still moving so it freezes mid-move
4. Stand on the prop. It will propel you in the direction you moved it.

### Expected behavior

Velocity is automatically set to zero when a prop's bodytype changes from dynamic to static.

### Media/Files

Little video demonstrating the bug:

https://user-images.githubusercontent.com/11138884/188273124-480c39ca-e8fa-4b9c-af69-a55ad48f211b.mp4

### Additional context

When looking at the Sandbox source code all freeze does is set the heldBody.BodyType to PhysicsBodyType.Static, which should be all that's needed but seems to not be.
This is a pretty recent bug, likely popped up during the collision refactor.

I've also tried manually setting their velocity to zero after or before freezing and it doesn't actually work or change anything.

**Comment by aylaylay** [comment]
Haha, i feel like we would have always had this bug, just never noticed it until now, should be an easy fix

**Comment by ShadowBrian** [comment]
Maybe! I don't think it was a thing in fortwars until I fixed it up after the collision refactor though so I'm not sure.

**Comment by ShadowBrian** [comment]
https://user-images.githubusercontent.com/11138884/188273717-50f11a38-1857-45be-980e-63f82f7fa72d.mp4

Here's me messing with it in fortwars :)
Physgun is largely the same just has a cool custom skin and freezes on release.

**Comment by aylaylay** [comment]
its kinda a cool mechanic

**Comment by aylaylay** [comment]
Yep you're right this happened after the collision refactor stuff, entity velocity is different to body velocity

**Comment by ShadowBrian** [comment]
Yeah honestly if it was a little less obscure and more well conveyed it might be a neat thing heh.
Functionally though a proper conveyor block would make more sense as people would just instantly grasp how that works

**Comment by aylaylay** [comment]
Should be fixed when the update hits steam

**Comment by aylaylay** [comment]
btw you would have been able to fix it before by setting entity velocity to zero after setting body to static. Entity velocity gets set from body velocity but once a body isn't active, it no longer got set.

**Comment by ShadowBrian** [comment]
I tried that, didn't work somehow, really weird...

**Comment by Gmod4phun** [comment]
Can confirm, it's fixed now

**Comment by ShadowBrian** [comment]
Looks like it's fixed if you use BodyType = PhysicsBodyType.Static; but not if you use PhysicsEnabled = false;
PhysicsEnabled might still be using an older method?

**Comment by ShadowBrian** [comment]
Specifically, PhysicsEnabled = false has the old undesired behavior of launching you off the prop.
I switched to using BodyType again, the PhysicsEnabled thing was me trying to fix the old bug but now it looks like it's the only thing causing it still.

**Comment by ShadowBrian** [comment]
Both should exist btw, I think PhysicsEnabled is for making an entire entity static rather than a single physics body of an entity, but it should probably also be fixed for that

**Comment by aylaylay** [comment]
I'll sort it but all you have to do is reset the velocity on the entity after you freeze it

**Comment by ShadowBrian** [comment]
Yeah like I said, I tried that before: 
![devenv_GKvlhTvFdR](https://user-images.githubusercontent.com/11138884/188282259-6af6fbe1-6307-4923-8511-89a6992ff84e.png)
this setup, where I tried to zero out all velocity stuff, still had the glitch happen.

**Comment by ShadowBrian** [comment]
Looking back it would've probably worked if I reversed it but I feel like I also tried that...

**Comment by ShadowBrian** [comment]
Though you'd think setting it to zero before freezing would have the same effect right since it just made the same velocity stick?

**Comment by aylaylay** [comment]
It works sometimes so yeah that's not an ideal way to do it

**Comment by aylaylay** [comment]
Should be sorted now

**Comment by ShadowBrian** [comment]
Will check and close 👍

**Comment by ShadowBrian** [comment]
Yup! 100% fixed.
