### ISSUE TITLE
[Web] Time played stat in the Players tab isn't correctly calculated

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#2275]
### Describe the bug

In the Players tab on my game's asset.party page, the player "theossiraptor" has a total recorded playtime of almost 160 hours, despite them admitting to not even having 100 hours recorded on steam. The user guesses their total playtime to be around 55 hours.

### To Reproduce

1. View playtime of https://steamcommunity.com/id/theossiraptor/ (76561198122657134)
2. View their playtime in https://asset.party/fish/stud_jump/players

### Expected behavior

Record playtime correctly

### Media/Files

![image](https://user-images.githubusercontent.com/59583743/188304764-13c2a845-4825-4a0e-870c-f8c5bf503914.png)
![image](https://user-images.githubusercontent.com/59583743/188304767-6c2ee0cc-600c-4caa-961d-f6a1de27969f.png)
![image](https://user-images.githubusercontent.com/59583743/188304784-d5f42374-43aa-47f7-b9d5-4f1e792f8316.png)

### Additional context

1. Reportedly they have never opened multiple sessions of S&box at once.
2. They have never played the game in LAN and joined their own lobby.
3. Bots were spawned at the start of each gaming session.

**Comment by garrynewman** [comment]
Thanks, I need to audit all of this code
