### ISSUE TITLE
Skybox toolmat isn't contributing to VIS, leading to all newly compiled maps having terrible optimisation

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#2277]
### Describe the bug

Not sure when or why this started happening but the skybox toolmat isn't contributing to VIS anymore, which means that the maps don't get proper visibility calculations as of recent, like Construct.

### To Reproduce

1. Make a small test map
2. Seal it with skybox toolmat
3. Build VIS, compile your map
4. Notice how it fails to properly seal the map

### Expected behavior

It should contribute to VIS calculation like it used to before.

### Media/Files

Neo Tokyo in Hammer, showing the skybox toolmat sealing the map
![sbox-dev_8BhXi](https://user-images.githubusercontent.com/67245359/188330881-f6e41a57-f26e-41e7-86b2-d8f891ed4e53.png)

With VIS contributors view enabled in Hammer, skybox toolmat isn't considered as a contributor
![sbox-dev_dveZi](https://user-images.githubusercontent.com/67245359/188330892-df047d7a-84c9-42cd-a48a-a8aaf2888780.png)

Built VIS as a result, notice how clusters are only being built around the nodraw toolmat
![sbox-dev_eYIjF](https://user-images.githubusercontent.com/67245359/188330910-2c130550-be35-42e3-9d43-92a28cfce75c.png)

**Comment by googleooer** [comment]
Can confirm, last week i made a simple map and when i turned on "only show vis contributors" the skybox mat didnt show but i thought it only was a visual thing

**Comment by KayaDLX** [comment]
Fixed, thanks!
