### ISSUE TITLE
Translucent materials don't have collision in game

### ISSUE THREAD

**Issue by genericicon** [Facepunch/sbox-issues#228]
**Describe the bug**
If you check the translucent tick box in the material editor, meshes with that material in-game do not have collisions. 
**To Reproduce**

1. Go to the material editor.
2. Check the translucent tick box for any shader that supports it.
3. Save the material and then apply it to a mesh in hammer.
4. Compile the map, the player and physics props will not have collision in sandbox and dm98.

**Expected behavior**
Meshes with this material should have a collision. 

**Screenshots**
![sbox-dev_kjjLimgvps](https://user-images.githubusercontent.com/75807239/118913294-2a3ce980-b8f7-11eb-8b65-0c03e1a454f4.png)
![sbox-dev_YlSq2NiE5W](https://user-images.githubusercontent.com/75807239/118913314-33c65180-b8f7-11eb-8942-6f894dd0241b.png)

https://user-images.githubusercontent.com/75807239/118913552-ae8f6c80-b8f7-11eb-94c6-79ee5f88c172.mp4

**Additional context**
Might have something to do with collision layers

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by genericicon** [comment]
It seems like this issue is back now.
https://cdn.discordapp.com/attachments/841536617847586836/877000721285910578/kSe2F0SaRP.gif

**Comment by justynboi** [comment]
I can confirm that it's back.


https://user-images.githubusercontent.com/17112771/129650194-ca271bfb-e8b0-424d-ac1b-ce8dfa71a987.mp4

**Comment by MD485** [comment]
Can confirm, occurs on wine_glass also.
