### ISSUE TITLE
OnPhysicsCollision is not called on entities created on the client

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#2280]
### Describe the bug

Fully client-side entities with physics will not call OnPhysicsCollision when they collide.

### To Reproduce

See [repro code](https://github.com/Facepunch/sbox-issues/files/9491592/collision.repro.zip), or:
1. Create a custom entity with physics enabled, which does stuff on OnPhysicsCollision
2. Spawn it on the client
3. OnPhysicsCollision is never called

### Expected behavior

OnPhysicsCollision should be called on the client, if the entity was created on the client.

### Media/Files

https://user-images.githubusercontent.com/65136069/188500362-28fca01f-8e51-43b2-a57f-f895131e9136.mp4

### Additional context

Client-side entities don't have impact sounds either, which can be seen (or not heard, to be more precise) in the attached video, it' probably related to this issue.

**Comment by aylaylay** [comment]
This should be working now

**Comment by krotter0** [comment]
Thanks, it is working.
