### ISSUE TITLE
Replicated convars are not updating properly between sessions on the client

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2281]
### Describe the bug

When changing game settings for my game, the replicated convars associated with the game settings are not being updated properly.

Example:
- Start a game with `terrain_border` as false. This is properly replicated the first time a game is started.
- Quit your lobby and start a new game with `terrain_border` as true. The terrain_border is true serverside, but is still false clientside.
- Restart your gamemode (I just use the `restart` concommand) and the convar is now correct.

### To Reproduce

1. Start a game with certain game settings
2. Change the game setting
3. The settings are not changed clientside until another restart occurs

### Expected behavior

The convars should update properly.

### Media/Files

https://user-images.githubusercontent.com/57276947/188503003-375b28ff-1709-420b-a235-66f0d301f7e3.mp4

### Additional context

If for some reason you need a repo to test it on: https://github.com/apetavern/sbox-grubs

**Comment by kurozael** [comment]
A Steam build with this fix is in progress @trundler-dev, if you can confirm it works for you that'd be great but in my test it was fixed 👍

**Comment by trundler-dev** [comment]
Works like a charm, thanks!
