### ISSUE TITLE
Struct collection types in property editor are broken

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#2283]
### Describe the bug

Assets with collections which contain struct values will only show a text input in the property editor, which makes certain asset types (such as decal defintions, soundscapes, etc.) only editable by modifying them in a text editor. A regular struct property will show up fine though.

### To Reproduce

Try to create a decal definition.

### Expected behavior

Struct collections should work just like before.

### Media/Files

![image](https://user-images.githubusercontent.com/65136069/188622111-5f31bd83-5faa-4eff-8623-1a525e4e2e9e.png)

**Comment by garrynewman** [comment]
Hey - this is fixed here for me locally - is it still broken for you?

**Comment by krotter0** [comment]
Seems to be fixed now. I think it has been fixed on the same day I've created the issue, but I didn't have time to test it.
