### ISSUE TITLE
`SceneObject` `ViewModelLayer` does not draw on viewmodel layer

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#2285]
### Describe the bug

Enabling `SceneObject.Flags.ViewModelLayer = true;` on a world panel does not make the panels draw on the view model layer. They are still rendered behind the world.

### To Reproduce

1. Create any world panel
2. Set `SceneObject.Flags.ViewModelLayer = true;`
3. Notice that they do not draw on the view model layer

### Expected behavior

World panels should draw on the view model layer.

**Comment by Shinyshark1** [comment]
You can use this as a workaround:
myWorldPanel.SceneObject.RenderLayer = SceneRenderLayer.OverlayWithoutDepth;

Credit to ducc#5773 for telling me.
