### ISSUE TITLE
S&Box's Steam api doesn't detect when the game closes.

### ISSUE THREAD

**Issue by ItzRock** [Facepunch/sbox-issues#2287]
### Describe the bug

Whenever you boot up s&box and close the game steam will still say you've got s&box open.

### To Reproduce

Open sandbox 
Close sandbox

### Expected behavior

For it to say I'm not playing s&box when its closed.

### Media/Files

https://user-images.githubusercontent.com/18369504/188796376-86c096f0-5202-45be-b3f1-133a736c58ed.mp4

### Additional context

Windows 11, It still persists in the dev tools.

**Comment by garrynewman** [comment]
Steam is kind of viral in that if you launch a game, and then that game launches another process - it'll act like that's the game too.

That said, we're only launching the crash handler and I would have expected that to quit when the game does. If that isn't the case I'll have to investigate why..

**Comment by Adesii** [comment]
Vscode also counts for somereason. Its quite annoying when the game crashes that you have to close vscode to be able to start s&box again through steam.

**Comment by garrynewman** [comment]
VScode should only really count if you launched it via the game. It is annoying but I'm not sure there is any way around it.

**Comment by ItzRock** [comment]
> Steam is kind of viral in that if you launch a game, and then that game launches another process - it'll act like that's the game too.
> 
> That said, we're only launching the crash handler and I would have expected that to quit when the game does. If that isn't the case I'll have to investigate why..

Seems to have been fixed for me. Not sure if you fixed anything but if you did you can close the issue.
