### ISSUE TITLE
[Editor] Allow us to adjust the order of game settings

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2288]
### For?

S&Box

### What can't you do?

You can add and remove game settings, but you cannot change the order.

### How would you like it to work?

Click and drag, or buttons to move position up or down. I have a long list in Grubs now, and I would like to be able to adjust which order the settings are seen in-game without removing and re-adding the game settings. These could even be options in the right click menu, when right clicking a game setting entry from the list.

### What have you tried?

I believe you can move the entries around manually by opening your .addon and copy-pasting around, however I believe the intent of the .addon is to be something you never have to edit manually.

**Comment by kurozael** [comment]
I've added it as an option in the right-click menu for the time being.

**Comment by trundler-dev** [comment]
That is great! Thanks conna :)
