### ISSUE TITLE
Whitelist Task.Run

### ISSUE THREAD

**Issue by Erlite** [Facepunch/sbox-issues#229]
**What can't you do?**
Use `System.Threading.Tasks.Task.Run()` to run code in a background task.

**How would you like it to work?**
```cs
var someBackgroundTask = Task.Run(async () => await SomeExpensiveLongMethod());
```
**What have you tried?**
This, but it isn't whitelisted.

**Comment by FlorianLeChat** [comment]
If I'm not mistaken, there is `GameTask.Run` which uses `Task.Run` internally so this request can be closed.
