### ISSUE TITLE
Allow game settings to have additional information (tooltips)

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2290]
### For?

S&Box

### What can't you do?

I want to describe in further detail what each setting does in my games. For example, in Grubs, terrain resolution, scale, width, and height all mean different things, but it's hard to convey the differences in such a short title.

### How would you like it to work?

Allow a tooltip / description field for a game setting. The UI and UX choices do not really matter to me, as long as it's available in some capacity. Hovering over the setting, or a description below the setting, etc.

### What have you tried?

N/A

**Comment by kurozael** [comment]
Hey @trundler-dev I'm gonna add the description below the setting title in the lobby for now as we don't have a tooltip system right now so this will work for now, we may see a menu re-design in the future.

**Comment by trundler-dev** [comment]
Yeah that works just fine, thanks again :)
