### ISSUE TITLE
font-smooth property in css

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#2291]
### For?

S&Box

### What can't you do?

Right now there's no way to have a pixellated font or any kind of bitmap font at all 

### How would you like it to work?

font-smooth is a css property that is only available in webkit based browsers, I think it'll still make a good addition to being able to use pixellated unsmoothed fonts for art style purposes.

### What have you tried?

I don't see any work arounds for this, (edit: well kinda, i did try using actual bitmap font types but s&box doesn't support .fon files, but that's another issue)

**Comment by garrynewman** [comment]
What are you trying to achieve?

**Comment by Xenthio** [comment]
> What are you trying to achieve?

a pixellated unsmoothed font

**Comment by Xenthio** [comment]
![image](https://user-images.githubusercontent.com/28588188/189097596-519ac739-4daf-4739-9c36-a30be7617df5.png)

**Comment by trende2001** [comment]
aliased fonts you mean?
