### ISSUE TITLE
Hammer - Crash when attempting to load a map

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#2293]
### Describe the bug

When attempting to load the provided `.vmap` in this bug report, into hammer, it will appear that it is going to load just fine but at the last moment the editor crashes with this error 
![sbox-dev_IqJQNe1781](https://user-images.githubusercontent.com/23345567/189033562-9672085d-18ac-4991-81fe-06ec4c8ec43e.png)

### To Reproduce

1. load provided map file.
2. Observe it will start to load and shortly after the editor will crash with an error dialog popup.

### Expected behavior

Open the map and not shit the bed.

### Media/Files

Bug in action : 

 

https://user-images.githubusercontent.com/23345567/189618353-a5316fc6-2dbe-4036-b737-e1f7310c92bc.mp4

affected map :
[outdoor_scene_test_branch2.zip](https://github.com/Facepunch/sbox-issues/files/9523496/outdoor_scene_test_branch2.zip)

### Additional context

Steam ID : 76561198066682455
Crash time reported by sentry: 2022-09-12T08:16:38.704Z

seems to be the same exact error I got a few days ago: https://discord.com/channels/833983068468936704/833983416390385685/1016417435852754985

**Comment by garrynewman** [comment]
@aylaylay @DevulTj @handsomematt anyone want to look into this?

**Comment by handsomematt** [comment]
Can't get it to crash, could I get the prefab maps/prefabs/environments/environment_workshop_night.vmap @QuackCocaine

**Comment by aylaylay** [comment]
This might be a case of an asset having to recompile while loading the map, I had the same thing happen in boomer yesterday

**Comment by QuackCocaine** [comment]
> Can't get it to crash, could I get the prefab maps/prefabs/environments/environment_workshop_night.vmap @QuackCocaine

here ya go [maps.zip](https://github.com/Facepunch/sbox-issues/files/9566434/maps.zip)

**Comment by handsomematt** [comment]
Looks like two things causing it independently:

First @aylaylay was right with the asset recompiles, this one affects in-games and Hammer:

```
2022/09/14 19:39:25.571	AssetSystem	On-demand recompile of asset pp/flatgrass.vpost	
2022/09/14 19:39:25.571	AssetSystem	 -> reason: At least one out-of-date dependency: pp/flatgrass.vpost (file CRC changed)
2022/09/14 19:39:25.590	Engine	ERROR: Reentrant call to CResourceSystem::BlockUntilManifestLoaded() while already in a frame update!	
```

Second seems to be Hammer specific with a change we did to lightcookies and loading them just-in-time in the middle of a frame.

**Comment by handsomematt** [comment]
Fixed them both, give it a go and try to get it to crash now @QuackCocaine - I ended up disabling the UI refreshing when an asset recompiles on demand because that was fucking everything, we'll have to see about doing it in a better way.

**Comment by QuackCocaine** [comment]
It works! @handsomematt  closing now.
