### ISSUE TITLE
Editor Frame Rate Quirks

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#2295]
### Describe the bug

**Issue 1**

Sometimes when launching the editor, the frame rate is capped at 60 FPS (even with vsync turned off [although the option is disabled anyway]).

![image](https://user-images.githubusercontent.com/55365296/189220158-e202ae8e-5249-4f38-a950-6a8d5acea447.png)

This somehow causes the frame rate in Hammer to be capped at 30 FPS (pls ignore my ugly ass map I just use it for testing code).

![image](https://user-images.githubusercontent.com/55365296/189220265-89c7a722-797b-4c82-b7c7-25fd9113cfd6.png)

It's completely random when this happens - some days it will work just fine and it will be uncapped (getting 200+ FPS in editor). Other days it will be capped. Sometimes restarting the editor will fix the issue (maybe - not sure). Sometimes I can restart it 3 times and it doesn't fix it.

**Issue 2**

When the main editor window is minimised, this causes other editor windows to run at like 3 FPS. For example, for Hammer:

![image](https://user-images.githubusercontent.com/55365296/189220717-5340a4dd-51f0-4948-be88-73e50242b75e.png)

I'm guessing this might be because Hammer etc are child windows and minimising the parent editor window causes the operating system to call window events less often.

Not sure if 1 and 2 are related somehow.

This doesn't just happen with Hammer - the other tools are affected too. E.g. model editor also gets capped at 30 FPS:

![image](https://user-images.githubusercontent.com/55365296/189222508-172d0ece-bc72-4b1c-90b1-a37ddecfab2c.png)

### To Reproduce

As above.

### Expected behavior

Always uncapped FPS.

### Additional context

Now here's where it gets interesting (not really). I'm running on a double monitor setup. One of my monitors is 240Hz (my primary monitor). My secondary monitor is just 60Hz.

When the frame capping is happening, on my primary monitor, my frame rate is capped at 60 (and Hammer at 30 etc).

![image](https://user-images.githubusercontent.com/55365296/189221635-8fb127e9-6b02-4bb0-a112-1b3412239a2e.png)

But, if I move the editor or Hammer etc over to my 60Hz screen, I get uncapped FPS somehow (obviously my screen can only show up to 60 FPS though - I just mean that it runs at uncapped FPS) 

![image](https://user-images.githubusercontent.com/55365296/189221907-59e3109d-b21c-43ff-8e2b-f99879505cba.png)

![image](https://user-images.githubusercontent.com/55365296/189222023-cd65b63b-a8a0-4fda-8894-440da7e69f67.png)

(sorry Fraps is now refusing to show the FPS counter on Hammer so I used the in-editor one).

Now, if I unplug my 60Hz monitor, the issue disappears:

![image](https://user-images.githubusercontent.com/55365296/189222708-abee981c-31e3-4e24-b6f2-1956b144dbd6.png)

So my theory is that the editor incorrectly thinks my 60Hz monitor is my 240Hz monitor and vice-versa.

My main monitor is connected via display port and the 60Hz monitor is connected via HDMI. Both are connected to the graphics card - I have a NVIDIA GeForce GTX 1660 SUPER. Also on Windows 10.

Another thing possibly worth looking into is why the editor tools run at half of the frame rate of the main editor. Even if there is no capping, my editor runs at ~240 whilst Hammer runs at ~120.

Even more interesting is: why can I get 200+ FPS in Hammer and ~800 FPS in the editor when I put the windows on my 60HZ SCREEN, whereas when I put them on my 240Hz screen I can get only 120 FPS in Hammer and 240 FPS in the editor (it's capping it at my screen refresh rate). Both monitors are 1080p.

Not too fussed about this really but just thought I'd mention it since no one seems to have made an issue for it yet.

😎👍

**Comment by garrynewman** [comment]
Hey thanks for the analysis.. one quick question to test a theory..

If you start up and move the window, and it gets uncapped frame rate.. does it stay uncapped when you move it back?

**Comment by anthonysharpy** [comment]
@garrynewman Can't reproduce it today sadly... but 95% sure that it doesn't stay uncapped when it gets moved back. It seems to know what screen it's on and it caps/uncaps depending on that 😁
