### ISSUE TITLE
Asset Packs

### ISSUE THREAD

**Issue by ItzRock** [Facepunch/sbox-issues#2296]
### For?

Hammer

### What can't you do?

Currently if you want to make a map and use custom textures somebody else had created, you'll need to go peaking into their github repository (if public) and copy and paste them to get the textures.

### How would you like it to work?

For when you have a map addon selected, right under "Supported Games" there should also be "Asset Pack" where for example you could type "shishkabob27.hls2_content" and then once you load the map up in hammer, you'll have the included materials (and possibly models too) from half life source 2. 

### What have you tried?

If I wanted to make a map using hl s2 assets I'd need to have the hl s2 content downloaded as an addon and then once I wanted to publish the map I'd need to include it in the actual map addon.

**Comment by DrewBritt** [comment]
This is already being worked on by Matt on the sbox/hammer-transient-packages branch 
![image](https://user-images.githubusercontent.com/43252311/189243018-c4be126c-9959-4058-bde7-40930c22ab53.png)

**Comment by ItzRock** [comment]
> This is already being worked on by Matt on the sbox/hammer-transient-packages branch ![image](https://user-images.githubusercontent.com/43252311/189243018-c4be126c-9959-4058-bde7-40930c22ab53.png)

👍 Alright thanks for letting me know
