### ISSUE TITLE
Editor - Open Solution doesn't function when previously selected code editor is no longer installed 

### ISSUE THREAD

**Issue by QuackCocaine** [Facepunch/sbox-issues#2298]
### Describe the bug

When I attempt to open up the S&box solution from the editor it fails to open, complaining that there is `No code editor found `.  When in fact I have VS Code installed and have it set as the code editor to use in editor preferences. 

### To Reproduce

Make sure you have at least two Compatible code editors installed. VS Code & Visual Studio 2022 will do. You can also try this in reverse with VS Code being the one you uninstall leaving VS 2022 Installed, though I have not tested that.

1. Make sure your code editor is set to VS 2022 then quit the editor.
2. Uninstall  VS 2022.
3. Open up the S&box Editor again. VS Code should now be selected in Editor Preferences.
4. Attempt  `File` ---> `Open Solution`.
5. Observe that it will complain that `No code editor found` even though VS Code is installed and set as the Code Editor.

### Expected behavior

To Open the solution in the selected code editor. 

### Additional context

It seems like in `config/tools.cookies.json` ,  The `Value` is not set to `VSCode` but instead stuck to `VisualStudio`. unable to be changed in editor preferences as there is nothing else to select from aside from VSCode. Only way to get Open Solution to work again is to delete tools.cookies.json and have it just generate a new one.

```
"CodeEditor": {
    "Value": "VisualStudio",
    "Timeout": 1663924497
  },
```

**Comment by handsomematt** [comment]
I added a couple of checks for if the CodeEditor class exists still or if it's installed - if not it'll fall back. Let me know if something doesn't work as expected though.

**Comment by QuackCocaine** [comment]
seems to function properly this time around from my testing. Thanks, matt!
