### ISSUE TITLE
Triggers defined in fgd not appearing in-game

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#23]
Here's my fgd:
```
@SolidClass base(Trigger) = trigger_timer_start :
	"A trigger that starts the timer on exit."
[
]

@SolidClass base(Trigger) = trigger_timer_end :
	"A trigger that ends the timer on enter."
[
]
```

It shows up in Hammer but when compiling the map and doing `showtriggers` command the custom triggers do not show.  Other triggers, like trigger_teleport, do show, but triggers defined in sbox.fgd like `trigger_traversal_invalid_spot` also do not show.

The entity does appear in the console but is unlike other triggers:
https://i.imgur.com/up6F9SR.png

Trigger code (have also tried deriving from `Entity`
```
using Sandbox;

namespace Strafe.Entities
{

	[Library("trigger_timer_start", Title = "Timer Start")]
	public class TriggerTimerStart : ModelEntity
	{

		public override void StartTouch( Entity other )
		{
			base.StartTouch( other );


		}

		public override void EndTouch( Entity other )
		{
			base.EndTouch( other );

			Log.Info( "Exited start zone!!!" );
		}

	}

}
```

**Comment by aylaylay** [comment]
My initial thought is that it's because it's spawning as a model entity and not the trigger entities that are in engine, the trigger entities on the native side probably handle the rendering of showtriggers

**Comment by aylaylay** [comment]
I'll see what can be done about it

**Comment by cr4yz** [comment]
Thanks.  I should also note the EndTouch method does not trigger, not sure if I implemented something wrong or it's related to the trigger rendering.

**Comment by aylaylay** [comment]
I recently implemented trigger_hurt and EndTouch was firing, have a look at that and see if there's anything different

**Comment by cr4yz** [comment]
> I recently implemented trigger_hurt and EndTouch was firing, have a look at that and see if there's anything different

Okay we're good there, I copied the spawn override from trigger_hurt and trigger events are firing.

**Comment by aylaylay** [comment]
If you implement the triggers you need in C# deriving from BaseTrigger, these can be drawn with drawtriggers_toggle
