### ISSUE TITLE
sbox-dev crashing when messing with decals

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#230]
**Messing with Decals in the Inspector will randomly crash sbox-dev**

**To Reproduce**

1. On sbox-dev search for .decal files and or open the inspector and begin making a decal.
2. Once in the inspector, try adding or opening the dropdown of one of the decals in the decal list.
3. If it does not crash yet just keep closing the inspector and re-opening it, or opening decal files and then doing the dropdown in the decal list, and it should eventually crash.

**Here is a video example**

https://www.youtube.com/watch?v=1Uca5dXmkes

**Also here is the mini-dump file it produces when it crashes**

![image](https://user-images.githubusercontent.com/82092361/119043857-6765b200-b9b1-11eb-8011-5f6c01f6ddb7.png)

[sbox-dev_2021_0520_212931_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/6518620/sbox-dev_2021_0520_212931_0_accessviolation.zip)

**This can happen right after you have opened sbox-dev 1st time or the 10th time opening the dropdown, its completely random and not specific to any decal file, or even if its an existing decal file, could be a new one you are trying to make. Also seems to not matter if there are multiple inspector windows open, it could be 1 window or 5.**

Note - With the .sound and .surface files you can also make from the inspector, the dropdowns they have area always stuck open and can not be collapsed for me, where the ones for the .decals can be collapsed and opened again? maybe that might have a part to play with the issue?

**Comment by robotboy655** [comment]
Should be fixed whenever the game updates next. Please reply to this post to let me know if it's fixed.

If it is fixed feel free to close the issue yourself.

**Comment by NotGaylien** [comment]
ye all sorted, thanks!
