### ISSUE TITLE
Omni Lights not casting shadows on props

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#2300]
### Describe the bug

Omni lights will not give shadows on props while other lights like environmental lights do, even physics props.
![a7f6d4c1661660e7890991fe7bc4dbee](https://user-images.githubusercontent.com/105941502/189498547-c7181bbc-710e-47ff-a1aa-410ea27d7fcb.jpg)
![unknown](https://user-images.githubusercontent.com/105941502/189498548-f31e55d0-b3ac-4e6e-af79-44810abcbb4d.png)

### To Reproduce

1. Put omni light in map
2. Put a prop near it
3. Compile

### Expected behavior

Light should cast shadows on the prop

**Comment by magnusm1908** [comment]
Doesn't seem to cast on the player either, maybe it's all entities

**Comment by KingOfTheFBI** [comment]
Works if they are dynamic but not baked. I know it used to work when baked a while ago, not sure when it stopped working.

**Comment by magnusm1908** [comment]
Should probably mention that the problem only occurs with baked lights

**Comment by magnusm1908** [comment]
Also only a problem with omni_light

**Comment by KingOfTheFBI** [comment]
Looks like it happens where there are more than one omni lights in the map

**Comment by garrynewman** [comment]
Am I right in thinking this is a lightmap problem? They're not casting shadows in the lightmap?

**Comment by Adesii** [comment]
understanding it correctly i think its baked omni lights not casting dynamic shadows. Like the other light types do.
![image](https://user-images.githubusercontent.com/37816311/189516096-1c2304e3-efb8-4b1e-89f0-2863756a355a.png)

**Comment by samzanemesis** [comment]
That's an indexed light, rather than a fully dynamic one, correct? 

I think we have a special case to not cast mixed shadows on them, but they do on dynamic, I can see what we can do to not allocate 6 faces for every one of them

**Comment by Adesii** [comment]
yeah i think it is. Its the default settings for the light. the only thing i changed was intensity
