### ISSUE TITLE
Hammer - Ctrl+Shift+Z Hides Floating Windows

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2301]
### Describe the bug

In hammer when you press Ctrl+Shift+Z, it hides any floating windows you have on a second monitor

### To Reproduce

1. Open Hammer
2. Create a floating window (ex. floating asset browser on another monitor)
3. Press Ctrl+Shift+Z
4. See Error

### Expected behavior

Floating windows should not be hidden

**Comment by handsomematt** [comment]
I can see the use of this not happening, I'll sort it.
