### ISSUE TITLE
Soundscapes Don't Turn Off When You Enter A New Soundscape Radius

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2303]
### Describe the bug

When you enter a new soundscape radius, the old soundscape doesn't turn off.
This results in sounds constantly stacking on top of each other until s&box eventually crashes

### To Reproduce

1. Walk around a map that has soundscapes (ex. Crossfire)
2. When you enter a new soundscape the old one doesn't turn off
3. Eventually s&box will crash if you walk around long enough

### Expected behavior

Only one soundscape should be played at a time.

If you leave the radius of a soundscape it should keep playing until you enter the volume of a new soundscape
The old soundscape should fade out and the new one will start playing.

**Comment by garrynewman** [comment]
Can you confirm this @bakscratch?

**Comment by bakscratch** [comment]
Yeah, it ends up playing both at the same time.

https://user-images.githubusercontent.com/8184184/190104500-784ef2e4-24f3-4a34-99ca-eafed30edf2e.mp4

**Comment by garrynewman** [comment]
Should be good now 👍

**Comment by bakscratch** [comment]
Confirming this is now fixed (noticing that gamemodes need to be updated)
