### ISSUE TITLE
Parallax Occlusion Shader Invisible

### ISSUE THREAD

**Issue by Meowcat285** [Facepunch/sbox-issues#2309]
### Describe the bug

The Parallax Occlusion shader is now invisible, it can not be selected in the shader list, but still works on existing materials. It can also be added via editing the vmat file in a text editor.

### To Reproduce

1. Open Material Editor
2. Open Shader list
3. Unable to select the Parallax Occlusion shader as its not in the list

### Expected behavior

The Parallax Occlusion shader should be a option in the shader list in the material editor

### Media/Files

![image](https://user-images.githubusercontent.com/13440415/189550632-8a8a323d-0b4c-4cd5-9ca7-4462b6722f5c.png)

**Comment by gvarados1** [comment]
I was wrong, the parallax occlusion shader isn't hidden, it's just gone. The core materials that have it are actually using Projected Decal (didn't know projected decal also had parallax). It would be lovely to have parallax occlusion, the cool liquid shader, and the tarp shader back.

**Comment by samzanemesis** [comment]
Parallax will come back as a feature in an upcoming ubershader rather than as a separate shader
