### ISSUE TITLE
ScenePanel DisablePostProcessing & RenderOnce obsoleted - but I need them

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#2310]
### What it is?

[Sandbox.UI.ScenePanel.DisablePostProcessing](https://asset.party/api/Sandbox.UI.ScenePanel.DisablePostProcessing) and [Sandbox.UI.ScenePanel.RenderOnce](https://asset.party/api/Sandbox.UI.ScenePanel.RenderOnce) have been obsoleted (and do not seem to work anymore) but I need them for my game - I show the avatars at the side on the UI like this:
![image](https://user-images.githubusercontent.com/12881812/189551044-e72870fc-336d-4792-8767-b385b18727bd.png)

RenderOnce being removed means that these are all rendering.. when they don't need to be.. and tanks my (already poor) framerate massively - from 144fps to like 40fps.
In addition to that, the bloom on these looks incredibly ugly. I could disable this before and everything would look perfect.

### What should it be?

While the new SceneCamera changes are good, it would be nice if I could use these avatars again. My only alternative right now is to remove them outright.

**Comment by garrynewman** [comment]
RenderOnce is back, working on a way to disable post process

**Comment by garrynewman** [comment]
Added SceneCamera.EnablePostProcessing - I think that should fix your issue, you can access the SceneCamera on the ScenePanel

**Comment by xezno** [comment]
Yep, all works now, thanks Garry!
