### ISSUE TITLE
Asset Part support for tool addons

### ISSUE THREAD

**Issue by tjones4701** [Facepunch/sbox-issues#2311]
### For?

S&Box, Other

### What can't you do?

I am unable to currently place my tool addon/addon into Asset party and have other developers use these tool addons.

### How would you like it to work?

I would love to be able to start producing tool addons and have them hosted in Asset Party so other developers can start using them.

### What have you tried?

At the moment it is just sharing and manually adding tool addons which can be annoying.

### Additional context

I have created tool addons to speed up things like png -> Material creation and i see other users creating their own tool addons.

Once we can start sharing tools then the doors open up for some amazing things. I already have some tools i created that i find useful and i would love to start sharing them and get feedback from other developers.

**Comment by garrynewman** [comment]
Planned, probably next month

**Comment by xezno** [comment]
@garrynewman is this still planned? I can think of some concerns / issues with this, mainly security-related
