### ISSUE TITLE
Creating new static Player instance breaks the editor

### ISSUE THREAD

**Issue by lotuspar** [Facepunch/sbox-issues#2313]
### Describe the bug

Creating a static Sandbox.Player and calling its constructor breaks most of the editor and spams the console (sometimes)

The editor then needs to be restarted to be used again

### To Reproduce

1. Try to create static Sandbox.Player 
```
public partial class MyGame : Sandbox.Game
{
    static Sandbox.Player player = new();
    ...
```
2. Click on editor

### Expected behavior

Shouldn't break the editor

### Media/Files

![image](https://user-images.githubusercontent.com/91263142/189560989-1a0c2510-f538-4b40-8d78-6cbdfb3e003b.png)

**Comment by garrynewman** [comment]
Assigned @Metapyziks because it looks like a hotload issue.. let me know if it's something else please @Metapyziks

**Comment by lotuspar** [comment]
Seems to happen with any exception caused during init of a static member
```
// where abc/def doesn't exist...
static BaseFileSystem abc = FileSystem.Data.CreateSubSystem( "abc/def" );
```

**Comment by Metapyziks** [comment]
> Seems to happen with any exception caused during init of a static member
> 
> ```
> // where abc/def doesn't exist...
> static BaseFileSystem abc = FileSystem.Data.CreateSubSystem( "abc/def" );
> ```

Thanks, this seems to be the main issue. I can repro by just doing `throw new Exception()` in a type initializer.

We should completely abort swapping assemblies if a type initializer throws.

**Comment by Metapyziks** [comment]
I've added a check to protect against this now, could you give it a quick test too @lotuspar ?

**Comment by lotuspar** [comment]
Seems to work!
Throws the error but the editor works fine after
![image](https://user-images.githubusercontent.com/91263142/190505481-e337eabd-ad29-466f-b958-cf1f8b88ab90.png)

**Comment by Metapyziks** [comment]
Perfect, thanks for your help!
