### ISSUE TITLE
Hammer – S&box crashes after opening a map

### ISSUE THREAD

**Issue by ItsAshi** [Facepunch/sbox-issues#2314]
### Describe the bug

When opening some maps, (such as in this case the official Construct map, downloaded using Git Bash from here), this message pops up and after closing the message the game auto exits. 
![image](https://user-images.githubusercontent.com/97547084/189588783-f773f6d3-c2a0-4420-be05-0288440565da.png) 
Now the first time I loaded it, it loaded with no problem, but after I restarted my pc all hell broke loose and it didn't.

### To Reproduce

1. Load the map provided
2. See the result

### Expected behavior

Flawlessly open the map, even if there are errors and missing parts of the map.

### Media/Files

[ICouldNotSubmit2FilesSoIPackedThemIntoZip.zip](https://github.com/Facepunch/sbox-issues/files/9546536/ICouldNotSubmit2FilesSoIPackedThemIntoZip.zip)

**Comment by QuackCocaine** [comment]
#2293

**Comment by yuberee** [comment]
Do you mind providing the last Log.log file generated and your steamid so they can look up the crash?
Also I've seen people having a similar problem, was related to the 4 way blend material shader which Construct probably uses.

**Comment by Sosniesienudzi** [comment]
My apologies, I didn't know there was a report about this already. My steamid is 76561198283374079 ,and the log I unfortunately cannot provide as I do not know where it is

**Comment by QuackCocaine** [comment]
I believe the logs are sent to them already via sentry

**Comment by ItsAshi** [comment]
Thanks, I found it. It reads as follows: 
"
2022/09/12 11:21:04.761	AssetSystem	AssetSystem initialized in 3.50 seconds. [0.11 load, 0.11 scan, 3.24 dependencies, 0.01 save]	
2022/09/12 11:21:27.831	Hammer	Begin loading file: C:\Users\light\OneDrive\Dokumenty\S&box Projects\containment\maps\construct.vmap	
2022/09/12 11:21:42.358	ResourceSystem	Error loading resource file "materials/particle/beam_generic_2.vtex_c" (Error: ERROR_FILEOPEN)	
2022/09/12 11:21:44.094	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.094	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.094	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.118	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.118	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.118	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.179	AssetSystem	Error:  loading C:\Program Files (x86)\Steam\steamapps\common\sbox\_toolsettings\asset_settings\containment\maps/construct.vmap_user.txt	
2022/09/12 11:21:44.179	Hammer	Completed loading file: C:\Users\light\OneDrive\Dokumenty\S&box Projects\containment\maps\construct.vmap (16.3s)	
2022/09/12 11:21:44.815	AssetSystem	On-demand recompile of asset postprocess/construct.vpost	
2022/09/12 11:21:44.815	AssetSystem	 -> reason: At least one out-of-date dependency: postprocess/construct.vpost (file mod changed)	
2022/09/12 11:21:44.835	Qt	QWidget::repaint: Recursive repaint detected	
2022/09/12 11:21:44.837	Engine	ERROR: Reentrant call to CResourceSystem::BlockUntilManifestLoaded() while already in a frame update!	
"

**Comment by ItsAshi** [comment]
It seems that my message with the log didn't send itself. My apologies, I send it and immediately went to school in a rush. Here is the log:
2022/09/12 11:21:04.761	AssetSystem	AssetSystem initialized in 3.50 seconds. [0.11 load, 0.11 scan, 3.24 dependencies, 0.01 save]	
2022/09/12 11:21:27.831	Hammer	Begin loading file: C:\Users\light\OneDrive\Dokumenty\S&box Projects\containment\maps\construct.vmap	
2022/09/12 11:21:42.358	ResourceSystem	Error loading resource file "materials/particle/beam_generic_2.vtex_c" (Error: ERROR_FILEOPEN)	
2022/09/12 11:21:44.094	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.094	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.094	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.118	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.118	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.118	Qt	QLayout: Attempting to add QLayout "" to CQStylizedGroupBoxControllable "", which already has a layout	
2022/09/12 11:21:44.179	AssetSystem	Error:  loading C:\Program Files (x86)\Steam\steamapps\common\sbox\_toolsettings\asset_settings\containment\maps/construct.vmap_user.txt	
2022/09/12 11:21:44.179	Hammer	Completed loading file: C:\Users\light\OneDrive\Dokumenty\S&box Projects\containment\maps\construct.vmap (16.3s)	
2022/09/12 11:21:44.815	AssetSystem	On-demand recompile of asset postprocess/construct.vpost	
2022/09/12 11:21:44.815	AssetSystem	 -> reason: At least one out-of-date dependency: postprocess/construct.vpost (file mod changed)	
2022/09/12 11:21:44.835	Qt	QWidget::repaint: Recursive repaint detected	
2022/09/12 11:21:44.837	Engine	ERROR: Reentrant call to CResourceSystem::BlockUntilManifestLoaded() while already in a frame update!

**Comment by handsomematt** [comment]
Should be fixed now
