### ISSUE TITLE
Intel Iris XE fails to render many things.

### ISSUE THREAD

**Issue by sophfee** [Facepunch/sbox-issues#2316]
### Describe the bug

When I'm working on my laptop (All specs will be listed in additional context) I cannot do any of the following (they just won't work properly)

- Render dynamic lights.
- Preview baked or dynamic lights (Sometimes it will generate what looks like indirect light when I preview lighting in Hammer)
- Render reflections
- Compile cubemaps

### To Reproduce

Have a laptop (possibly desktop too?) with Intel Iris XE Integrated graphics and run s&box.

### Expected behavior

Properly render

### Media/Files

Visual bugs on main menu
![image](https://user-images.githubusercontent.com/66189083/189992009-cd2a6a5f-1d25-4097-be20-d4cc49a12d43.png)

Preview lightmap in hammer doesn't render correctly (Was generated on desktop, specs listed in additional context.)
![image](https://user-images.githubusercontent.com/66189083/189992253-0e6325ba-746f-4ee9-9c3e-1343c83ec436.png)

Preview lightmap generated on Intel Iris XE
![image](https://user-images.githubusercontent.com/66189083/189993120-46ea2cad-cfb8-4d7e-9031-9d00adbbc8ea.png)

### Additional context

Laptop Specs:
CPU: Intel i5-1135G7
GPU: Intel Iris Xe Graphics
RAM: 16 GB

Desktop Specs; (This machine works fine with s&box)
CPU: Ryzen 7 3700X
GPU: RTX 3070 Ti
RAM: 24 GB

**Comment by samzanemesis** [comment]
Most of this is also the case on Adreno Snapdragon, while I don't have an Intel UHD GPU I can validate it on a Surface Duo

I know why some of these happens while others need a more in depth look

**Comment by samzanemesis** [comment]
This is fixed on Snapdragon

**Comment by urnotnick** [comment]
> Hey, I don't have a Intel Xe graphics card at hand but these should be fixed

Sorry for the delay, I'll boot up s&box on my laptop and test it out.

**Comment by PolSpock** [comment]
![image](https://user-images.githubusercontent.com/5229571/217503498-a77fcb6b-33e7-46ab-9b17-b4487f90d6a2.png)
Same problem on SceneModel with custom playermodel
