### ISSUE TITLE
soundscape editor not functioning properly

### ISSUE THREAD

**Issue by beaumancer** [Facepunch/sbox-issues#2318]
### Describe the bug

in asset browser, im inspecting a soundscape file to edit and make changes.
I cant add sounds properly, theres no drop down menu or text that I'm used to seeing.

I cant click drag files in either.

### To Reproduce

in asset browser, im inspecting a soundscape file to edit and make changes.
click buttons to add sound
no UI for actually adding a sound, cant be populate properly

![image](https://user-images.githubusercontent.com/39849783/190115250-30a8b621-48b0-4b62-9363-8872ad08ed79.png)

### Expected behavior

I expect to see something like "add new sound event" "add new sound file" and a drop down menu

### Media/Files

![image](https://user-images.githubusercontent.com/39849783/190115389-361deff2-cdf2-4646-b0ef-f8c5b63b806e.png)

### Additional context

I think this issue might be less than a day old, I havent heard of this from anyone else and it was functioning properly earlier this week.

**Comment by garrynewman** [comment]
Thank you - missed this! This should be fixed in the next build

**Comment by bakscratch** [comment]
Confirming this is working correctly now.
