### ISSUE TITLE
Input.MouseDelta steps are too high which result as Shaky/Laggy behaviour.

### ISSUE THREAD

**Issue by AlexBoost** [Facepunch/sbox-issues#232]
**Describe the bug**
When i'm using this : 
``Input.Forward`` or ``Input.Left``, the player movement is really smooth.
So I wonder if this is normal that using ``Input.MouseDelta``, make it shaking / lagging.
If I move the mouse really slowly and from 1milimeter
Sometime, my player will move 10m apart.
Sometime, he will just move in the wrong direction.

**To Reproduce**
Using ``Input.MouseDelta`` in a Controller made the movement lagging/shaking
Ex: Move player using the Mouse in a 2D plan. (X is static)

Here a code exemple : 

```csharp
[Library]
public class DesignerController : BasePlayerController
{
	public override void Simulate()
	{
		Rotation = Rotation.FromYaw( 180 );

		Vector3 vel = new Vector3( 0, -Input.MouseDelta.x, -Input.MouseDelta.y );

		vel = vel.Normal * 20000;

		Velocity += vel * Time.Delta;

		if ( Velocity.LengthSquared > 0.01f )
		{
			Move( Velocity * Time.Delta );
		}

		Velocity = Velocity.Approach( 0, Velocity.Length * Time.Delta * 5.0f );
	}

	public void Move( Vector3 delta, int a = 0 )
	{
		if ( a > 1 )
			return;

		var targetPos = Position + delta;

		Position = targetPos;
	}
}
```

**Expected behavior**
The movement should be smooth and MouseDelta "step" shouldn't be that high.
If that's not possible for some reason, then provide something which allows us knows where the mouse is relative to the screen.
Like Input.MouseScreenPosition which will return a ratio of the current mouse position from the screen.
I know it's possible to get coordonates from the UI side, the problem is that we can't interact in game if we are activating the mouse from the UI side and move it, click, etc.

**Screenshots**
Here what's happens :
Using ``Input.Forward`` and ``Input.Left`` : https://gyazo.com/4ba2882fa27bcd82995e95845327d4c2
Using ``Input.MouseDelta`` : https://gyazo.com/644f763457f941c4df4d8ff823ed1bcf (I'm moving slowly the mouse but the Input.MouseDelta step is way more important than reality.
Sometime, the MouseDelta's step can be more high than 10, which is really high and product that shaking effect.

**Additional context**
It looks like Input.MouseWheel and Input.CursorAim are updated good.
I tried to move my player using Input.MouseWheel and it was smooth.
That's why I'm wondering if it's normal that Input.MouseDelta is not.

**Question**
Is there something relative to Mouse DPI ? 
Like => The more high the DPI is, the more high the MouseDelta.Step is.

**Comment by garrynewman** [comment]
Simulate is called every tick (60 frames per second). The reason movement feels smooth is because it lerps using the Velocity.

You can use FrameSimulate() on the client to fill in the frames between the ticks.. but you should be aware that anything you do in FrameSimulate isn't authoritive.

**Comment by AlexBoost** [comment]
Ok so I tried with someone else to see if it was relative to me or not.

First of all, here's the controller code :
```csharp
[Library]
public class DesignerController : BasePlayerController
{
	public override void Simulate()
	{
		Vector3 vel = new Vector3( 0, -Input.MouseDelta.x, -Input.MouseDelta.y );

		Move( vel );
	}

	public void Move( Vector3 delta, int a = 0 )
	{
		if ( a > 1 )
			return;

		var targetPos = Position + delta;

		Position = targetPos;
	}

	public override void FrameSimulate()
	{
		base.FrameSimulate();

		Rotation = Rotation.FromYaw( 180 );

		Vector3 vel = new Vector3( 0, -Mouse.Delta.x, -Mouse.Delta.y );

		Move( vel );
	}
}
```` 

Here's his point of view when he's drawing : https://files.amperpowered.com/kaya/32glc9/Desktop_2021.05.27_-_16.48.37.03.mp4

Here's mine : https://gyazo.com/b4f71e377241253dd90cb1da6d728c3a

As you can see, it's smooth on his side, but not on mine.
We can even see him drawing on my side video and it looks more smooth than me who is local xD

Any idea about what's happening? or how to fix that?

**Comment by garrynewman** [comment]
Well, you need to think about what it's doing.

TICK: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
TICK: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
FRAME: move based on mouse movement
TICK: move based on mouse movement

When you're getting the positions from your friend, you're only getting positions generated by Tick, the positions in between are being lerped.

What I would try is getting rid of FrameSimulate because it's not doing anything for you, In Move try setting Velocity to delta too.
