### ISSUE TITLE
scss: animations with hsl not affecting color property on worldpanel labels

### ISSUE THREAD

**Issue by notmatical** [Facepunch/sbox-issues#2323]
### Describe the bug

setting the color property for a label using hsl isn't working as intended.

```
name {
  font-family: Poppins, sans-serif;
  font-size: 42px;
  
  &.rainbow {
    animation-name: rainbow;
    animation-duration: 2s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
  }
}

@keyframes rainbow {
  0% {
    color: hsl(0turn, 90%, 65%);
  }

  25% {
    color: hsl(0.25turn, 90%, 65%);
  }

  50% {
    color: hsl(0.5turn, 90%, 65%);
  }

  75% {
    color: hsl(0.75turn, 90%, 65%);
  }

  100% {
    color: hsl(1turn, 90%, 65%);
  }
}
```

### To Reproduce

create a instance of a world panel and create a label and apply your `Client.Name` to it.
set `rainbow` class to the NameLabel
text will remain white and not be applied the intended color.

### Expected behavior

It should apply a rainbow effect to the text that is infinite, as it is behaving in the exact same code on a JSFiddle.
https://jsfiddle.net/v0f9jk8m/18/

### Media/Files

Current Behaviour:
![image](https://user-images.githubusercontent.com/30790036/190497565-7b2f5b8f-2213-4e36-b660-2ee9529771a5.png)

Expected Behaviour:
https://jsfiddle.net/v0f9jk8m/18/

**Comment by cr4yz** [comment]
I'm unable to reproduce, I've tried on world panels and screen panels: https://files.facepunch.com/crayz/1b1511b1/sbox-dev_F3cdufk0L1.mp4

Could you put together a small project showcasing the issue?

**Comment by notmatical** [comment]
While looking at my code preparing to bootstrap a test project, I noticed I didn't put the keyframes in the proper code block...

Apologizes for raising the issue, it is solved.

**Comment by cr4yz** [comment]
> While looking at my code preparing to bootstrap a test project, I noticed I didn't put the keyframes in the proper code block...
> 
> Apologizes for raising the issue, it is solved.

No worries, glad you got it solved
