### ISSUE TITLE
Creating any networked property using => silently breaks codegen

### ISSUE THREAD

**Issue by qualitycont** [Facepunch/sbox-issues#233]
**Describe the bug**
Creating any networked property using => silently breaks codegen

**To Reproduce**
Put
```cs
[Net]
public bool Test => true;
```
anywhere in your gamemode
codegen should now be broken

**Expected behavior**
It gives you an error (or just doesnt network)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by TheBerkin** [comment]
That's just a different way to write a get-only property:

```cs
// This...
public bool Test => true;

// ... is the same as this
public bool Test
{
    get
    {
        return true;
    }
}
```

Unless I'm mistaken, you can't network a property without a setter.

**Comment by qualitycont** [comment]
yes i know
it just shouldnt let the entire project break with no error message

**Comment by garrynewman** [comment]
Yep definitely shouldn't be silently dying, will fix

**Comment by garrynewman** [comment]
This'll be fixed when I merge the network update in next week
