### ISSUE TITLE
New control points don’t show up in particle editor until reopening asset

### ISSUE THREAD

**Issue by mahalis** [Facepunch/sbox-issues#2333]
### Describe the bug

Control points are supposed to show up in the right-hand “Control Points” pane as soon as you reference them (i.e. set something to have a control point number other than 0), but if the asset was newly created, this doesn’t work.

### To Reproduce

1. open particle editor
2. File > New
3. next to Emitters, click the + and double-click Continuous Emitter
4. next to Initializers, click the + and double-click Position In Box
5. in the properties panel, set “control point number” to 1
6. look in the right-hand panel under Control Points

### Expected behavior

you should see a control point XYZ listed; instead, the panel stays blank

### Additional context

if you save the file, close it (Ctrl-F4 or closing the particle editor entirely), and reopen it, the control point appears as expected

**Comment by aylaylay** [comment]
This is working fine for me? I save it and it shows up.

**Comment by mahalis** [comment]
Right—the issue is that it doesn’t work *until* you save, which is really confusing. There’s nothing in the UI suggesting that that’s a requirement.

**Comment by aylaylay** [comment]
Control points is part of the preview, you can't preview if you haven't saved the asset.

![sbox-dev_IXkzcp6GTZ](https://user-images.githubusercontent.com/1667289/191133803-bcc15efc-e723-4d30-9762-70be85787263.png)

**Comment by aylaylay** [comment]
I have now added a warning on the control point preview

**Comment by mahalis** [comment]
That’d work. Thank you!
