### ISSUE TITLE
Particle Editor : CP-Value field doesn't accept decimal numbers for Scale

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#2334]
### Describe the bug

when trying to change the Scale from Control Point Value on for example color blend on Render Rope. It doesn't actually save the value and just reverts it to what was previously in it.
Example:

https://user-images.githubusercontent.com/37816311/191095941-47119be2-9068-4908-a1d1-bbfeb902274d.mp4

### To Reproduce

1. create or open a Particle that has any field set to Control Point Value 
2. change it to anything decimal
3. select something else
4. select it again and see the value reverted

### Expected behavior

it should keep the value you typed in.

the only way to force it is by changine the file itself using a text editor like notepad++

### Media/Files

[portal_laser_beam_colored.zip](https://github.com/Facepunch/sbox-issues/files/9601725/portal_laser_beam_colored.zip)
^here is the particle i used in the video

**Comment by aylaylay** [comment]
Works fine here, not sure what's going wrong.

**Comment by bakscratch** [comment]
Tested on yours and own particle and seems fine as well.

https://user-images.githubusercontent.com/8184184/191126337-349cf392-eeae-4be0-8ab5-4cbf6276bfd0.mp4

**Comment by Adesii** [comment]
wtf. I'll be honest i got no clue why it doesn't work for me. I think i remember having this issue for quite a while already but since i don't do particles fairly often i rarely come across this.

i got no clue why it isn't repeatable for you two. but even on a new particle i have this issue

**Comment by Adesii** [comment]
it does seem to work if any of the 3 inputs are whole numbers and above 0. then it will also save the others

https://user-images.githubusercontent.com/37816311/191128505-5dc55397-48db-4b76-9965-ea20704fd8bf.mp4

**Comment by aylaylay** [comment]
There's nothing I can do to get this to happen

**Comment by Adesii** [comment]
This has been fixed in the latest commit.
