### ISSUE TITLE
Creating RenderEntity in constructor breaks rendering

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#234]
**Describe the bug**
Creating a new RenderEntity (or an entity derived from it) in a constructor breaks rendering for the entity (and in some cases other entities) until the entity exits and re-enters the client's view.

**To Reproduce**

1. 
```
public SomeEntity()
{
    new RenderEntity();
}
```
2. Rendering for entity is now broken

**Expected behavior**
Expecting the entity to render normally

**Screenshots**
![image](https://user-images.githubusercontent.com/16853532/119170028-faaaf000-ba62-11eb-823a-496a4532fcd5.png)
![image](https://user-images.githubusercontent.com/16853532/119168691-77d56580-ba61-11eb-887a-45467056d022.png)

**Comment by garrynewman** [comment]
I should probably forbid you from doing anything in the constructor, since you could potentially create an infinite loop.

Why are you creating it in the constructor?

**Comment by Leafdroid** [comment]
I was creating it in the constructor because it wouldn't create when I tried to do it in the spawn method. Used to work perfectly fine until a recent update.

**Comment by garrynewman** [comment]
Are you trying to create it on the client or the server?

**Comment by Leafdroid** [comment]
Must have been on the server, just tried it again in ClientSpawn and it worked without issue.
