### ISSUE TITLE
ModelDoc - Crashes opening/closing models via AssetBroswer

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#2345]
### Describe the bug

Some update is causing me crashes opening/closing modeldoc via AssetBrowser, it doesn't happen on all models only on my playermodels for some motive, you can see there are no errors/warnings.

If you open the playermodels directly from modeldoc (Tools>ModelEditor>File>Open) it's not crashing.

This was working perfectly yesterday.

### To Reproduce

install sboxmp.hazmatsuit

https://user-images.githubusercontent.com/40291120/191482668-28c8a566-f34e-472a-854f-e4009cdbbf4d.mp4

### Expected behavior

Get it fixed.

**Comment by aylaylay** [comment]
I'm gonna have to have a model that this happens with

**Comment by aylaylay** [comment]
Nevermind got it to crash, will fix

**Comment by aylaylay** [comment]
Should be fixed when update next hits steam

**Comment by KaesarZZ** [comment]
Thank you for all support, as per usual <3
