### ISSUE TITLE
Catch special characters causing uploads to asset.party to fail

### ISSUE THREAD

**Issue by kin37ik** [Facepunch/sbox-issues#2352]
### For?

S&Box

### What can't you do?

When attempting to upload assets, maps and various other things, any files such as TGA's or texture files, map files and anything else in between will not upload to asset.party if they contain any special characters, despite this even if S&Box fails to upload these files it will continue to say "Success" even after failing, making things not immediately apparent if this happens.

### How would you like it to work?

I think it would be a good idea to catch any files that have a special character within the file name before allowing S&Box to attempt an upload and inform the user to remove the special characters, and if an upload fails having some more detailed information about what was not uploaded rather than jumping to "success"

### What have you tried?

apart from all the trial and error to find out why the uploads wouldn't work, i dont feel there is anything else for me to try.

**Comment by garrynewman** [comment]
Can you give me an example of a special character? Which files have failed to upload?

**Comment by kin37ik** [comment]
> 

yes, for example, one of my TGA's had a # in the file name (#teleport.tga) which caused it to fail on upload which prevented all the files from being uploaded to asset.party, these characters !@$%^&*() i assume would also cause files to fail uploading.
I would hazard a guess that any odd characters outside of these such as Alt code characters would also cause this issue.

**Comment by kin37ik** [comment]
As additional information, i have also learned along with G Kaf that there is a 16 character limit for any materials being uploaded to asset.party, anything longer than 16 fails to upload even though it says success rather than catching it and reporting it as a problem.
