### ISSUE TITLE
Compiling Material Error

### ISSUE THREAD

**Issue by Kabubu2** [Facepunch/sbox-issues#2354]
Not sure why but my material is a purple checkerboard and spits out this error unless I force compile to disk. When I reopen the game it's the purple checkerboard and spitting this error again.
![image](https://user-images.githubusercontent.com/18005111/192118043-fb5fbb35-ed63-41a8-99fe-433e3d2fc92f.png)

**Comment by handsomematt** [comment]
Have you used the `install` con command to install a cloud asset? Whats your sbox/.source2/cloud folder look like
