### ISSUE TITLE
Abstract ClientRpc functions don't compile without specifying `Sandbox.ClientRpc`

### ISSUE THREAD

**Issue by lotuspar** [Facepunch/sbox-issues#2359]
### Describe the bug

The ClientRpc attribute needs to be specified as `Sandbox.ClientRpc` even if you have `using Sandbox;`

### To Reproduce

1. Try:
```
using Sandbox;
public abstract partial class Activity : Entity
{
    [ClientRpc] public abstract void Test();
}
```
2. See "Error when generating code"
3. Try: 
```
using Sandbox; // this can still stay here
public abstract partial class Activity : Entity
{
    [Sandbox.ClientRpc] public abstract void Test();
}
```
4. See no error!

### Expected behavior

No error

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
