### ISSUE TITLE
Implement entity IO delay

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#236]
**What can't you do?**

I can't output to entities on a delay within the hammer editor's defined delay parameter.

**How would you like it to work?**

Either have the ability to get the delay time and handle it or automatically delay the output given the parameter set in hammer.

**What have you tried?**

Set the delay of two outputs, both outputs fired at the same time.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
