### ISSUE TITLE
[base] BasePathEntity<T>'s generic type should extend IBasePathNode rather than BasePathNode 

### ISSUE THREAD

**Issue by IceAge2OnDVD** [Facepunch/sbox-issues#2366]
### Describe the bug

As far as I'm aware, it is currently not possible (or at least not very easy) to have a custom path with a custom entity node in sbox.

### To Reproduce

```cs
public class CustomEntityNode : BasePathNodeEntity
{
    ...
}

public class CustomPath : BasePathEntity<CustomEntityNode>
{
    ...
}
```
Will error since `BasePathEntity` has a generic type of `BasePathNode`. 
`The type 'CustomEntityNode' cannot be used as type parameter 'T' in the generic type or method 'BasePathEntity<T>'. There is no implicit reference conversion from 'CustomEntityNode' to 'Sandbox.BasePathNode'.`

### Expected behavior

If BasePathEntity used IBasePathNode for its generic type instead.

```cs
	public partial class BasePathEntity<T> : Entity
		where T : IBasePathNode
	{
            ...
```

Either this, or another solution which would allow sub classes of BasePathNodeEntity to be compatible with sub classes of BasePathEntity.

**Comment by robotboy655** [comment]
You can do that easily by giving the path node class to `PathAttribute`. You can see how it is done for `MovementPathEntity` and its node entity, it's open source @ `addons\base\code\Entity\Hammer\MovementPathEntity.cs`

`BasePathEntity<T>` is meant to allow you to override the type of `BasePathEntity`'s `PathNodes` property, point being, you can still have custom per-node data, but without the need to have node entities spawn in-game, making it a cheaper option.
