### ISSUE TITLE
"Make Local" organization button in addon manager doesn't prompt save

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#2367]
### Describe the bug

When clicking the "Make Local" button in the organization dropdown it does not allow you to save the .addon file like switching it to a different organization does.

### To Reproduce

1. Create an addon with an organization.
2. Make the addon a local one.
3. See the save button still greyed out.

### Expected behavior

For the save button to be usable and save the change you made.

**Comment by Xenthio** [comment]
i remember finding this annoying when i was working on a project that i wasn't in the organisation yet for, i kept having change the addon settings file and exclude it from all my commits. sounds nice
