### ISSUE TITLE
Modeldoc Jigglebones don't scale with the model scale being set

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#2368]
### Describe the bug

My game has a shrunken down player, if I have clothing items on with jiggle bones they'll be enlarged on my rescaled player.

### To Reproduce

1. Put on the jiggleboned pony tail.
2. go into any gamemode and that has a rescaled player.
3. Observe:

https://user-images.githubusercontent.com/11138884/193028156-0c9be0cf-ec5b-48a6-aec1-2f66392fb53a.mp4

### Expected behavior

I would have expected the jigglebones to rescale properly.

### Additional context

Alternately if you add jigglebones to an object after its already been rescaled in-game they'll be properly scaled down when hitting compile so I think it's just an oversight, that it doesn't re-check the parent model scale or something.

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by ShadowBrian** [comment]
Yup, fixed! Thanks.
