### ISSUE TITLE
Severe framerate drop / high GPU usage in avatar editor after post processing merge

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#2369]
### Describe the bug

Whenever I open the avatar editor, my framerate drops a ton and my GPU usage rises to 100% (up from like 10%)
This happens in both tools and non-tools mode.

https://user-images.githubusercontent.com/12881812/193066918-2ad5838b-016f-4b10-b65f-24639037cdf3.mp4

### To Reproduce

1. Open s&box
2. Click on the avatar editor button
3. See fps drop

### Expected behavior

Avatar menu should run at more than 10 frames per second

### Additional context

Since this might be hardware-specific, here are some specs that could be relevant
GPU - Nvidia Geforce GTX 1070
Processor - Ryzen 5 3600

**Comment by trundler-dev** [comment]
Also happening to me!

GTX 3070 Ti (latest driver)
Ryzen 7 5800X

**Comment by xezno** [comment]
Matt asked for a log with the `-dx11debug` launch flag, here's what I got
[Log.log](https://github.com/Facepunch/sbox-issues/files/9675911/Log.log)

**Comment by NotGaylien** [comment]
[Log.log](https://github.com/Facepunch/sbox-issues/files/9675934/Log.log)

Ryzen 5 3600
GTX 3060

**Comment by DoctorGurke** [comment]
Curiously enough, I don't have the issue. Also running on 2070s with latest drivers

**Comment by PixelQubed** [comment]
I'm on the latest drivers for everything currently. I'll post my log here too.

Specs: 
Ryzen 3900x 
16 GB RAM 3200mhz Dual Channel
GTX 1080 ti

<img width="750" alt="sbox-dev_D9C9xzpXvY" src="https://user-images.githubusercontent.com/32498714/193070260-ef6912b0-9112-445a-bc2c-6e71fd87833f.png">

[Log.log](https://github.com/Facepunch/sbox-issues/files/9676008/Log.log)

**Comment by garrynewman** [comment]
Fixed?

**Comment by peter-r-g** [comment]
Fixed for me

**Comment by PixelQubed** [comment]
> Fixed? I believe this happened if you had a AA setting less than 8

Weird because I always have 2x msaa and 16x antristropic filtering

It's fixed now though, thanks.

**Comment by xezno** [comment]
Yep fixed now, sorry
