### ISSUE TITLE
TypeLibrary: Expose Type.IsValueType

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#2370]
### What it is?

Currently there is no whitelisted way to access [Type.IsValueType](https://learn.microsoft.com/en-us/dotnet/api/system.type.isvaluetype?view=net-6.0).

### What should it be?

It should be a whitelisted item in the type class or stubbed into `TypeDescription`. My use-case for it is to use it in conjunction with [Type.IsEnum](https://learn.microsoft.com/en-us/dotnet/api/system.type.isenum?view=net-6.0) to know if I am working with a structure type for custom networking.

**Comment by ogniK5377** [comment]
Should be added next update :+1:

**Comment by peter-r-g** [comment]
Sorted, thank you!
