### ISSUE TITLE
Glow component will never work again after enabled = false;

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#2372]
### Describe the bug

if you create a new glow component on a model, it will work fine setting the colour and enabling it to true,

but as soon as glow.enabled = false;
you will never be able to get it to glow again even if you glow.enabled = true; and set colour.

### To Reproduce

its just generally an issue, sandbox gamemode is a really good example of it happening with the physgun.

doing this

```
var glow = modelEnt.Components.GetOrCreate<Glow>();
glow.Enabled = true;
glow.RangeMin = 0;'
glow.RangeMax = 1000;
glow.Color = new Color( 4f, 50.0f, 70.0f, 1.0f );
```

then later on getting the glow component and setting

```glow.Enabled = false;```

it will cause 
```glow.Enabled = true;```
to not be able to turn it back on

### Expected behavior

enabling and disabling the glow shouldn't kill it forever

**Comment by Unreal852** [comment]
I can confirm this. See the attached video.

https://user-images.githubusercontent.com/5130243/193134274-b30f09c6-d454-4ff8-964d-ea50445a5c75.mp4

**Comment by DrewBritt** [comment]
I was also experiencing this issue last night, however now everything appears to work fine for me. I'm not sure which commit fixed this.

**Comment by robotboy655** [comment]
A fix for this was issued.

**Comment by NotGaylien** [comment]
oh yeah it works fine on my end now <3
thanks guys, love you
