### ISSUE TITLE
ToolVis options broken for main game viewport

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#2375]
### Describe the bug

IN TOOL MODE.
on the game window there is a dropdown to switch between the different toolvis modes.
they dont do anything now.

### To Reproduce

1. go into and sbox game and load up a map
2. try go through to toolvis options
3. they dont change anything now

### Expected behavior

it should switch all materials to the repective toolvis mode.

### Media/Files

https://youtu.be/IkWgq4xJ7Gg

(video showing said issue)

### Additional context

(this has been happening for a while tbh i think it was a little while after the shading model stuff was added at some point it broke.)

**Comment by garrynewman** [comment]
I think @aylaylay fixed thisone
