### ISSUE TITLE
TypeLibrary.SetProperty fails silently on structs

### ISSUE THREAD

**Issue by lotuspar** [Facepunch/sbox-issues#2378]
### Describe the bug

Using TypeLibrary.SetProperty on a struct doesn't do anything. Changing the struct to a class instantly makes it work.

(this also applies to PropertyDescription.SetValue)

This might just be undocumented intended behaviour but I'm not sure.

### To Reproduce

1. Make a struct and call SetProperty on it
```
public struct Test {
	public int Value { get; set; }
}

// in a function...
Test test = new();
TypeLibrary.SetProperty( test, "Value", 123 );
Sandbox.Assert.AreEqual( test.Value, 123 );
```
2. Try above with a class instead and it works

### Expected behavior

It should work (or if it's intended it should be documented)

**Comment by peter-r-g** [comment]
This is expected behavior. You're passing a struct by value which creates a copy that gets edited. That edited version is never returned to you. I believe doing something like this will work for your use case:

```cs
Test test = new();
object testObj = (object)test;
TypeLibrary.SetProperty( testObj, "Value", 123 );
test = (Test)testObj;
```
