### ISSUE TITLE
Code gen forge game data based on attributes attached to entities for use in hammer.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#238]
**What can't you do?**

An easy way to setup a Sandbox entity in hammer and setup all their properties, IO outputs, and IO inputs.

**How would you like it to work?**

1) Some kind of class attribute like:

`[HammerEntity("func_brush")]`

2) Some way to define the Outputs.

3) Code gen for entity class, output events, inputs methods, and hammer properties.

```csharp
using Sandbox;

[HammerEntity]
[Library( "func_brush" )]
public partial class FuncBrush : KeyframeEntity
{
	public enum SolidityType
	{
		Toggle = 0,
		NeverSolid = 1,
		AlwaysSolid = 2
	}

	private SolidityType solidity;

	[HammerProp( "Solidity")]
	public SolidityType Solidity
	{
		get { return solidity; }
		set
		{
			solidity = value;

			if ( this.PhysicsBody == null ) return;

                        FireOutput( "OnSolidityChange", null, this );

			this.PhysicsBody.CollisionEnabled = value == SolidityType.AlwaysSolid;
			this.PhysicsBody.Enabled = value == SolidityType.AlwaysSolid;
		}
	}

	[Input]
	public void SetNonsolid()
	{
		this.Solidity = SolidityType.NeverSolid;
	}

	[Input]
	public void SetSolid()
	{
		this.Solidity = SolidityType.AlwaysSolid;
	}
}

```

**What have you tried?**

Manually creating FGDs.

**Additional context**

I think there would be a huge benefit to codegen'd fgds based on sbox entities. It would make the work of transitioning to C# based entities much easier.

**Comment by garrynewman** [comment]
This is part of the plan <3
