### ISSUE TITLE
Crashes on Linux as i enter a game

### ISSUE THREAD

**Issue by Foresteam** [Facepunch/sbox-issues#2385]
### Describe the bug

Menu works, but the game crashes as i try to join a game / start my own.

### To Reproduce

Install the game on Linux
Proton experimental or 7 - crashes
Earlier versions - the game doesn't start at all

### Expected behavior

I should be successfully logging in, i guess

### Media/Files

[Log.7.log](https://github.com/Facepunch/sbox-issues/files/9718861/Log.7.log)
[Log.log](https://github.com/Facepunch/sbox-issues/files/9718862/Log.log)

### Additional context

5.19.7-1-MANJARO
KDE X11
NVIDIA 515.65.01

**Comment by ogniK5377** [comment]
Proton is out of our control, refer to this issue for any problems you might be facing on Linux specifically & proton:
https://github.com/ValveSoftware/Proton/issues/4940
