### ISSUE TITLE
"Index was outside the bounds of the array" error when previewing .ogg files for the first time

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#2388]
### Describe the bug

When I click on a .ogg file in the asset browser (After I made a new sound event with nine blank audio slots, in case that helps) I get an "Index was outside the bounds of the array" error, and the sound doesn't preview. Clicking on the sound again previews the sound like it should. I'm not sure if this affects other audio formats.

### To Reproduce

1. Add a .ogg file to an addon/project
2. Make a sound event maybe? Not sure if this is related...
3. Click on the sound in the asset browser

### Expected behavior

The file should preview instantly.

### Media/Files

Video of the issue: https://files.catbox.moe/x79b0o.mp4

**Comment by walllable** [comment]
Hm, I can't reproduce it either, now. I think I'll just close it until I can get a consistent repro.

**Comment by walllable** [comment]
Oh, got a stack trace this time. https://i.imgur.com/MigyYVe.png

Here are the sound files that cause the issue. I think most of them should cause it, at least.
[walllSounds.zip](https://github.com/Facepunch/sbox-issues/files/9780787/walllSounds.zip)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates. OGG files were getting invalid sound duration, which caused very short sounds have 0 duration - which caused the sound wave preview fail for your files.

You will need to recompile all your OGG files to fix this.
