### ISSUE TITLE
Add multiple sounds to a sound event at once

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#2389]
### For?

S&Box, Other

### What can't you do?

I can't add multiple sounds to a sound event at once, so I have to drag them in one at a time. Clicking on a sound slot and selecting multiple files doesn't add those sounds to each slot individually either, it just adds the first sound to the selected slot.

### How would you like it to work?

I'm not fully sure of the best way to implement this, but one potential way would be to select the multiple sounds I want, then drag them over the .sound asset in the browser? [Sorta like this.](https://files.catbox.moe/kpf9f0.mp4)

### What have you tried?

I tried selecting all the sounds with shift+click to drag into the sound event's inspector, but that just deselects the sound event. I also tried selecting a sound slot and selecting multiple files in the pop-up browser window, but that just adds the first-selected sound to the slot.

### Additional context

Unity has a similar-ish problem and it bugs me there too.

**Comment by robotboy655** [comment]
You can do it like so:
![image](https://user-images.githubusercontent.com/3299036/195087698-27ef758a-7684-494d-8bc2-1acbb62d1ca4.png)

**Comment by robotboy655** [comment]
I have also added ability to do it via drag'n'drop like so:
https://files.facepunch.com/rubat/1b1111b1/sbox-dev_tH20o2aafW.mp4

(Asset browser dragging also works)
