### ISSUE TITLE
[Net] Entity does not get set on client

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#239]
**Describe the bug**
```cs
[Net] 
public Entity TargetEntity { get; set; } 
```
will not be set on client since latest Net update

**To Reproduce**
```cs
if (!IsServer)
{
    return;
}

var pawn = team == Team.Killers
    ? (DbmPawn)new BaseKillerPawn()
    : new SurvivorPawn();

// Note: client.Pawn is not set on purpose as this will be done later
pawn.Owner = client as Entity;
pawn.Respawn();

var cameraAnimator = Library.Create<GameStartCameraAnimator>();
cameraAnimator.Owner = client as Entity;
cameraAnimator.TargetEntity = pawn; // def. not null and only set by server
cameraEntity.Spawn();
```

```cs
public partial class GameStartCameraAnimator : Entity
{
    [Net]
    public Entity TargetEntity { get; set; }
    
    public override void Spawn()
    {
        Transmit = TransmitType.Owner;
        base.Spawn();
    }

    [Event("tick")]
    protected void OnTick()
    {
        if (TargetEntity == null)
        {
            throw new Exception("TargetEntity was null");
        }
    }        
}
```

**Expected behavior**
TargetEntity should never be null

**Screenshots**
![image](https://user-images.githubusercontent.com/1809172/119259391-d07a3f00-bbd6-11eb-90a7-dc81630b0e1a.png)

![image](https://user-images.githubusercontent.com/1809172/119259259-0cf96b00-bbd6-11eb-96f4-2a1f71d0d3a6.png)

**Comment by Trojaner** [comment]
Could be related to creating the entity right before assigning it

**Comment by garrynewman** [comment]
Well, you shouldn't really be calling Spawn manually - but I'll look into it

**Comment by Trojaner** [comment]
Good to know. Removed all manual Spawn() calls, but Issue still happens so its likely not related to that.

**Comment by Trojaner** [comment]
Fixed by #bad65b
