### ISSUE TITLE
Cannot Upload Assets To Asset.Party

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#2394]
### Describe the bug

When I try to publish a material, it throws an object reference not set error for all the files and doesn't upload.

I've tried renaming the files, making a new addon, and reinstalling s&box but nothing fixes it.

### To Reproduce

[Reproduction Addon](https://github.com/Facepunch/sbox-issues/files/9761687/my_asset_party_stuff.zip)

1. Create the material, either through the auto-generator or from scratch
2. Try and upload the material
3. All of the files will say Object Reference not set
4. None of the files will have been uploaded to asset.party

### Expected behavior

The assets should upload to the cloud without issue

### Media/Files

https://user-images.githubusercontent.com/65134886/195254451-a596a3b7-a5c4-4b38-b53b-541ef263fc8f.mp4

![image](https://user-images.githubusercontent.com/65134886/195254969-2ae950c7-f1b6-4680-b0cb-bfea58901905.png)

**Comment by robotboy655** [comment]
File name of your material is too long. I will update the publisher to better handle errors.
