### ISSUE TITLE
inspector category collapse header bounce breaks if category above is expanded

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2399]
### Describe the bug

When toggling a category head collapse in the inspector, the bounce animation breaks if there's an opened category above it

### To Reproduce

1. Open any game resource with categories in the inspector
2. open a category and toggle the category below it a few times
3. notice weird bounce

### Expected behavior

n/a

### Media/Files

![sbox-dev_AWUjBavNKC](https://user-images.githubusercontent.com/12602100/195702259-87d11a4a-c786-4b26-80aa-2a312f9fd24e.gif)

**Comment by DoctorGurke** [comment]
This now also affects the project manager.

**Comment by DevulTj** [comment]
we don't use this anymore
