### ISSUE TITLE
Introduce Fract to MathX

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#240]
**What can't you do?**
Return the fractional part of a float or double. Useful helper function which should be included for everyone

**How would you like it to work?**
```cs
public static float Fract(this float f) => f - MathF.Floor(f);
public static double Fract(this double f) => f - Math.Floor(f);
```

**What have you tried?**
See above

**Additional context**

**Comment by chelog** [comment]
For doubles there's `Math.Truncate()`

**Comment by garrynewman** [comment]
Isn't it just `val = f % 1`

**Comment by ogniK5377** [comment]
> Isn't it just `val = f % 1`

Yeah, can be implemented like that as well, however, it's faster to go for the floor variant I posted above:

https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcDMACR2DC2A3utmbjgGYA2A9mMNgGIBOYAxkgBQ32MAeASmKlyY3AHZs/bAFJsSANzlRZAL6rsmrNl4Nmbdgh519QkWnFi4UmQFpsAWQYALJgDomdWiy5DlZJoaliohZDp6jKwcmCZ80sIkYVY20tgOzsBu7gAqLACuAHbsDACmfoIBWsnBYtpUplGGACxxZoma4qn22FwAloXAghVVQehqQA=

**Comment by garrynewman** [comment]
Are you having performance issues with `% 1`

**Comment by ogniK5377** [comment]
Not at all, just seems like a nice useful extension to have and it seems would be more clear as property or function call instead of just suddenly through `% 1`
