### ISSUE TITLE
ColorHsv.ToColor() erronously interprets the Hue field as a value between 0 and 255

### ISSUE THREAD

**Issue by sndrec** [Facepunch/sbox-issues#2400]
### Describe the bug

When converting a ColorHsv to a Color using the ToColor() method, it interprets the Hue field as a value between 0 and 255, rather than as a value between 0 and 1.

### To Reproduce

Create a ColorHsv with a hue between 0 and 1
Convert it to a Color with the ToColor() method
Log the new Color to console, and observe that its value will always be either fully red or almost fully red

### Expected behavior

The ToColor() method should expect the hue to be between 0 and 1.

**Comment by ogniK5377** [comment]
Do you have some test code? Our test cases seem to be passing here:
```cs
		[TestMethod]
		public void HsvTest()
		{
			var color = new Color(.5f, .5f, .5f, 1.0f);
			ColorHsv hsv = color.ToHsv();

			Assert.AreEqual( color, hsv.ToColor() );
			Assert.AreEqual( color.ToHsv(), hsv );
		}
```

**Comment by Phyksar** [comment]
Hue is ranged between 0 and 360, so the only bug I see is in the description of ColorHsv.cs
```csharp
	//
	// Summary:
	//     Hue component of this color in range 0 to 1.
	public float Hue { readonly get; set; }
```
![2022-10-14 16_28_49-sbox-dev](https://user-images.githubusercontent.com/13320416/195858859-8c531138-289a-4aed-8f60-02ecacc2070d.png)

@ogniK5377 this is a very tricky test, it tests only the equality of reverse functions but doesn't show what results each of them produces. And also you can't test the correctness of hue conversion as this color is gray and literaly have no hue. It should look at least like this:
```csharp
[TestMethod]
public void ColorToHsvTest()
{
    var color = new Color(0.36f, 1.0f, 0.2f, 1.0f);
    Assert.AreEqual(new ColorHsv(108.0f, 0.8f, 1.0f, 1.0f), color.ToHsv());
}

[TestMethod]
public void HsvToColorTest()
{
    var hsv = new ColorHsv(108.0f, 0.8f, 1.0f, 1.0f);
    Assert.AreEqual(new Color(0.36f, 1.0f, 0.2f, 1.0f), hsv.ToColor());
}

**Comment by ogniK5377** [comment]
Just checked, and it was documented wrong. This test case as well does pass.
Hue should be 0->360
