### ISSUE TITLE
modeldoc engine crash when duplicating node and "category" or head node selected

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2402]
### Describe the bug

duplicating nodes via the rightclick menu in modledoc crashes if there is a head node in the current selection, which usually cannot be duplicated

### To Reproduce

1. create a new template model from the asset browser
2. select both entries in the node list
3. rightclick -> duplicate, crashes immediately

### Expected behavior

I assume it's trying to duplicate the head node as well, which shouldn't be possible

### Media/Files

No Duplicate option on head node:
![sbox-dev_KGuXL0ssSo](https://user-images.githubusercontent.com/12602100/195955493-787892b5-8a99-417b-a97b-7d2a8474926c.png)

This does NOT crash:
![sbox-dev_PshoYhPkc1](https://user-images.githubusercontent.com/12602100/195955474-2e395313-2d6b-42c8-aef5-df1fe98451f3.png)

This DOES crash:
![sbox-dev_UlydFzXohs](https://user-images.githubusercontent.com/12602100/195955483-77f0eb1a-8118-4d80-8ce3-e73a0fcb15d2.png)

**Comment by aylaylay** [comment]
Duplicate context action will no longer show up when you have a singleton node selected
