### ISSUE TITLE
Add Angles.Vector

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#2403]
### For?

S&Box

### What can't you do?

Right now taking an angle and converting it to a vector3 sucks even though they are the same. There should be a Angles.Vector3 to be the opposite of Vector3.EulerAngles

### How would you like it to work?

Angles a = new Angles(20,90,45);
a.Vector - ( Vector3(20,90,45) )

### What have you tried?

You can go new Vector3(a.pitch, a.yaw, a.roll) but that sucks and looks bad to have so having an inbuilt func to do that would be nice

**Comment by robotboy655** [comment]
https://asset.party/api/Angles.Direction is what you are looking for.

**Comment by garrynewman** [comment]
We should probably obsolete this to Angles.Forward to match Rotation?

**Comment by robotboy655** [comment]
Added Angles.Forward, obsoleted Angles.Direction.

@Xenthio I am not quite sure what exactly you are looking for, `Vector3(a.pitch, a.yaw, a.roll)` is not the opposite of `Vector3.EulerAngles`, why would you want this anyway?

**Comment by Xenthio** [comment]
> Added `Angles.Forward`, obsoleted `Angles.Direction`.
> 
> @Xenthio I am not quite sure what exactly you are looking for, `Vector3(a.pitch, a.yaw, a.roll)` is not the opposite of `Vector3.EulerAngles`, why would you want this anyway?

there is no fucking way i have been using this function wrong the entire fucking time and just magically having shit work whatthe fuck come on oh my god.

**Comment by Xenthio** [comment]
> > Added `Angles.Forward`, obsoleted `Angles.Direction`.
> 
> > 
> 
> > @Xenthio I am not quite sure what exactly you are looking for, `Vector3(a.pitch, a.yaw, a.roll)` is not the opposite of `Vector3.EulerAngles`, why would you want this anyway?
> 
> 
> 
> there is no fucking way i have been using this function wrong the entire fucking time and just magically having shit work whatthe fuck come on oh my god.

I'm so sorry lmfao, that's a bit embarrassing.
