### ISSUE TITLE
Ability to get parameters of PhysicsShape

### ISSUE THREAD

**Issue by aled93** [Facepunch/sbox-issues#2405]
### For?

S&Box

### What can't you do?

Currently there is no way to get radius of Spherical PhysicalShape, radius and height of capsule, vertices of mesh shape, etc.

### How would you like it to work?

Additional method for PhysicsShape like
```csharp
float GetRadius();
float GetHeight();
Vector3 GetExtent();
uint GetVertices( List<Vector3> outVertices, List<int> outIndices );
```
or better make subclasses of PhysicsShape for each shape variant with relevant methods.

### What have you tried?

There is no workaround except exotic like photogrammetry-like reconstruction of geometry

**Comment by aylaylay** [comment]
Added Add PhysicsShape.Sphere and PhysicsShape.Capsule
