### ISSUE TITLE
Whitelist: Allow System.Diagnostics.Debug.Assert methods

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/sbox-issues#2408]
### For?

S&Box

### What can't you do?

I'm unable to add debug assertions to my project that should be removed in release mode (related to #2320).

### How would you like it to work?

The following methods from the ```System.Diagnostics.Debug``` static class would be nice to have:
```cs
public static void Assert(bool condition);
public static void Assert(bool condition, string? message);
public static void Assert(bool condition, string? message, string? detailMessage);
```

### What have you tried?

I've tried ```System.Diagnostics.ConditionalAttribute```, but it isn't whitelisted.
I've also tried the ```Sandbox.Assert``` static class, but they aren't removed in release mode.

**Comment by robotboy655** [comment]
We have https://asset.party/api/Sandbox.Assert

**Comment by LeQuackers** [comment]
As stated, it persists in release mode; it isn't removed during compilation.

**Comment by garrynewman** [comment]
I'd lean towards whitelisting `System.Diagnostics.ConditionalAttribute` rather than `System.Diagnostics.Debug.Assert`

**Comment by LeQuackers** [comment]
> I'd lean towards whitelisting `System.Diagnostics.ConditionalAttribute` rather than `System.Diagnostics.Debug.Assert`

Fair enough. Would it still be in the cards to whitelist ```System.Diagnostics.Debugger.IsAttached``` and ```System.Diagnostics.Debugger.Break```? What about adding a method that only calls ```Debugger.Break``` if it's running in debug mode and/or ```Debugger.IsAttached``` is true?

**Comment by garrynewman** [comment]
I can't see any harm in whitelisting those

**Comment by LeQuackers** [comment]
Alright, I'll go ahead and close this and open a more specific request for `Debugger.Break` and `Debugger.IsAttached`.
