### ISSUE TITLE
S2FM crashes when attaching IK rig if bones have certain names.

### ISSUE THREAD

**Issue by LambdaHidden** [Facepunch/sbox-issues#2409]
### Describe the bug

S2FM crashes if you try to add an IK rig to your model if its wrist helper bones are named "wrist.R" or "wrist.L".

### To Reproduce

1. Create a humanoid in ModelDoc and make the arms with this bone tree: upper_arm.R > lower_arm.R > wrist.R and hand.R.
2. Open Source 2 Filmmaker and import the model you made.
3. Bend the elbows in.
4. Select it's animation set, right-click, go to Rig -> Auto Attach Rigs.

### Expected behavior

IK handles and poles being added to the hands, elbows, ankles and knees.

**Comment by DrakeFruit** [comment]
can probably close consider s2fm is gone
