### ISSUE TITLE
Network Classes Can't Be Networked as a Part of Arrays Or Lists

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#241]
**What can't you do?**

Right now I can't create a class deriving from `NetworkClass` and add it to a list or array in another class and have it be networked properly. The specific example I'm referring to is that our players have a list of 'abilities' which derive from a networked base class called `BaseAbility` at present, there is no way to keep a list or array of networked classes and have that list be networked.

**How would you like it to work?**
 Just like entity, lists and arrays of networked classes should be networked.

I should be able to write something similar to 

```csharp
public class TestClass : NetworkClass{

[Net]
public int boppo{ get; set; } = 1;

[Net]
public string bippo{get; set; } = 1;

[Net]
public TimeSince bappo{get; set;}

public string GetBoppoBippo(){
    return bippo + " " + boppo.ToString();
}


}

public class SomeOtherClass{

[Net]
public List<TestClass> { get; set; }

[Net]
public TestClass[] {get; set; }

}


```

**What have you tried?**

Right now basically our only option is to convert any class we want to network and have be apart of a list or array into an entity. The problem with this is that for something as simple as abilities (or really anything that doesn't require something to have a physical presence in the world), converting it to an entity adds a lot of unnecessary overhead that could potentially cause issues later down the line.

**Comment by garrynewman** [comment]
I've been having a think about this overnight, I think there's enough positives to making this possible to put effort into it, and I think I can make it possible for you.

**Comment by R4K0** [comment]
Just leaving a comment behind to show interest, I've been waiting for this a bit as well - Having to network an entity is non-optimal for majority of use cases where you'd network a custom data structure that doesn't necessarily have a physical representation, without having to turn it into a struct.

**Comment by DreamplaySE** [comment]
Piggybacking onto this, I think that Dictionaries when they are added should have support for networked classes to be values as well.
