### ISSUE TITLE
unable to bind crouch/duck to side mouse buttons

### ISSUE THREAD

**Issue by zedioo** [Facepunch/sbox-issues#2410]
### Describe the bug

Trying to bind crouch/duck to the back sidemouse button and it goes to the previous page instead

### To Reproduce

1. go to input settings
2. try to bind crouch to side mouse button
3. be sad

### Expected behavior

I should be able to just bind it to the side mouse button 

### Media/Files

https://user-images.githubusercontent.com/113804058/196023856-8ad500d0-9023-4c3f-bdbe-4314809fcedc.mp4

### Additional context

I doubt its a problem with just my mouse but just incase I'm using a Logitech G Pro X Superlight Wireless
also make it possible to rebind previous page button so you can still use a button to go back if you do decide to bind crouch to a side mouse button

**Comment by gvarados1** [comment]
I think you can bind them manually through console. `bind mouse4 +iv_duck`

**Comment by zedioo** [comment]
> 

that works ty
