### ISSUE TITLE
Players can see the entire map through Hammer's 'Game View'.

### ISSUE THREAD

**Issue by Aspect12** [Facepunch/sbox-issues#242]
**Describe the bug**
Players can see the entire map that they are loaded into in the game, including all players, entities, effects, and everything in between, except themselves. This is possible regardless of whether the player is the host of the game or just joining another player's game. This can possibly be used to cheat on gamemodes such as prophunt, dm98, hidden, and others that rely on the player's view remaining static to their body.

**To Reproduce**
1. Open the Developer Tools and create or join a game.
2. Open up hammer.
3. Open or create a new map.
4. Make sure the Game View window is visible.
5. Hold right click on the Game View window and use the W/A/S/D keys to fly around the map.

**Expected behavior**
A possible fix for this problem without completely removing the feature would be to make the window only render if the player is the host of the game and in fact not a client.

**Media**
https://user-images.githubusercontent.com/41125780/119274815-7ef3a380-bc1a-11eb-854e-c6c9f284731e.mp4

**Comment by garrynewman** [comment]
I don't think we should be too worried about this stuff right now. Obviously as we move forward it's something that we need to address (ie, not letting people play live gamemodes with tools enabled).
