### ISSUE TITLE
Rotation: Add implicit conversion to System.Numerics.Quaternion

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#2420]
### What it is?

Right now, `Rotation` cannot implicitly convert to a `System.Numerics.Quaternion` like how the `Vector3` can to `System.Numerics.Vector3`.

### What should it be?

Just needs a quick implicit operator in the Rotation struct:
```cs
public static implicit operator Quaternion( Rotation value )
{
    return value._quat;
}
```

**Comment by robotboy655** [comment]
Done.

**Comment by peter-r-g** [comment]
Perfect, thank you!
