### ISSUE TITLE
Allow hair to be equipped with hats

### ISSUE THREAD

**Issue by objectionist** [Facepunch/sbox-issues#2425]
### For?

S&Box

### What can't you do?

I'm unable to wear hear with hats on Terry. When you equip an item from the hats category, hair gets automatically unequipped. This is annoying!

### How would you like it to work?

There's a couple different ways this could be pulled off. The most involved and long-term way of doing this is creating variants of existing hair styles that are flattened and work well enough with most hats in the hats category of clothing. The lazier way is to just cull all the parts of the hair that clip with the hat you're wearing. As long as you can't see what's under it, everything should work fine, right? I imagine this would still be an issue with hairstyles like the ponytail, which seems to be the only scenario I can see where there'd _have_ to be a different variant.

Oh shit, skin groups exist! You could do that as well.

### What have you tried?

It's easier to make a feature request. I haven't tried anything, no.

### Additional context

Hair is cool. I don't want to be bald wearing every single hat. Terry doesn't want to be bald wearing every single hat. Do it for Terry! Terry rights!

**Comment by objectionist** [comment]
Okay, so I completely forgot about this issue! I've decided to provide a little mock-up of what it might look like, given that my explanation is probably ass.

![image](https://user-images.githubusercontent.com/86072496/198158603-a03524d8-2e49-4e72-8f5c-f461fdea9518.png)

**Comment by DevulTj** [comment]
We've planned to support this with conditional meshes, and some of the work has already been done to support this - it'll just be something we do over time
