### ISSUE TITLE
Hammer - Additional Path tool context menu features

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#2429]
### For?

Hammer

### What can't you do?

* Select any path with more than 1 segment and quickly split them into two or more individual path entities.
* Merge two a more paths together 

### How would you like it to work?

Additional Right-click context menu options as demonstrated below in Desk Job

**Split into Path Per-Segment**

Split each segment into its own individual path entity.

https://user-images.githubusercontent.com/23345567/197418144-2d9215e4-1c8d-4867-a633-2c8e247aabf7.mp4

**Merge Paths**

Merges two or more of the same type of path entities together at either end.

https://user-images.githubusercontent.com/23345567/197418155-12f9e655-ad42-4688-9713-06e6b93b2dc8.mp4

### What have you tried?

Nothing as both features do not exist in s&box's version of hammer.

**Comment by handsomematt** [comment]
This should be an easy one with the additions to the Hammer C# API, I'll expose Path map nodes and it'll let us do a lot of cool shit.

**Comment by QuackCocaine** [comment]
sweet! I look forward to that!

**Comment by gvarados1** [comment]
It would also be nice to be able to continue placing nodes after we already made the path. Currently we have to shift drag nodes which really sucks
