### ISSUE TITLE
Can't select hammer gizmo if it's too high in the viewport

### ISSUE THREAD

**Issue by AWildErin** [Facepunch/sbox-issues#243]
**Describe the bug**
You are unable to select a gizmo if it's too high in the viewport. I've attached a video that fully describes more since I'm struggling to actually describe what I mean.

**To Reproduce**

1. Open a hammer map
2. Select a edge, mesh or anything.
3. Move your gizmo to the top of the viewport
4. Try to move the top and see that it can't be moved unless you go more near the root of the gizmo

**Expected behavior**
You should be able to select it with no issues.

**Media**
https://streamable.com/f49wfe

**Comment by aylaylay** [comment]
Works fine for me, I can't repoduce it

**Comment by AWildErin** [comment]
Yeah, another fp dev said that as well. It's strange, it's not exactly a problem just an annoyance that it's only happened with sbox and not HL:A's hammer. I'll look into seeing if there are any causes possibly, as well as seeing if anybody else has the same issue as me

**Comment by AWildErin** [comment]
Unsure of what happened, but it seems to work just fine now so I'm going to close this.
