### ISSUE TITLE
Crash on Gamemode Startup

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2431]
### Describe the bug

When I try to launch my gamemode in tools mode, it compiles fine and runs up until the map is done loading and then crashes.

The gamemode is Ghosts of the Zone if you want to replicate the issue.

I checked the log files and I couldn't see anything that might be causing a crash, other than possibly some obsoleted HitboxIndexes.

### To Reproduce

1. Start Ghosts of the Zone on any map
2. Crash on load in

### Expected behavior

Doesn't crash

**Comment by handsomematt** [comment]
Crash has been worked around for now and we have an issue internally for a proper fix.
