### ISSUE TITLE
Expose Hammer instances to tools API

### ISSUE THREAD

**Issue by Rylius** [Facepunch/sbox-issues#2433]
### For?

Hammer

### What can't you do?

I'm currently generating PolygonMesh/MapMesh instances in a tool addon and a fair amount of these meshes are identical.

According to [Valve](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Level_Design/Prefabs_and_Instances#Instances) instances can be used in this case, which provides both usability and performance benefits.

### How would you like it to work?

I'd like to use the instancing feature already available in Hammer from C#.

### What have you tried?

Currently I'm creating separate MapMeshes, which obviously isn't great.

Reusing PolygonMesh objects does not make a difference (they're treated as entirely separate meshes).

**Comment by handsomematt** [comment]
Added MapInstance class, usage is super simple with it just having a Target property, let me know how that works out for you.

```csharp
new MapInstance()
{
	Position = Vector3.Up * 128.0f,
	Target = Selection.All.First(),
};
```

**Comment by Rylius** [comment]
Works great, thanks a lot!
