### ISSUE TITLE
Hammer I/O does not respect Fire Once Only

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#2434]
### Describe the bug

When you set an output to fire once only, it will still output when it is fired again.

### To Reproduce

1. Make an ent_button
2. Add an OnPressed output and set it to Fire Once Only
3. Press the button twice
4. The output will fire the second time even though it is set to Fire Once Only.

### Expected behavior

When an output is set to Fire Once Only it should only output once.

### Media/Files

Reproduction level, the citizen should only flicker the first time you press the button.
[Fire Once Bug.zip](https://github.com/Facepunch/sbox-issues/files/9867144/Fire.Once.Bug.zip)

https://user-images.githubusercontent.com/65134886/197962174-f497bb1f-a32a-4afb-8555-31edb6f45478.mp4
![image](https://user-images.githubusercontent.com/65134886/197962235-45dc77eb-d827-4943-a92f-e6b7c7559448.png)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by GunnarKafel** [comment]
Works great now, thanks!
