### ISSUE TITLE
SceneModel.SetAnimGraph crashes game with mismatched anim graph

### ISSUE THREAD

**Issue by lotuspar** [Facepunch/sbox-issues#2435]
### Describe the bug

Using SceneModel.SetAnimGraph with an anim graph not intended for the model crashes the game completely

### To Reproduce

1. Create watermelon SceneModel and use the citizen anim graph
```
var model = new SceneModel( Map.Scene, "models/sbox_props/watermelon/watermelon.vmdl", Transform.Zero );
model.SetAnimGraph( "models/citizen/citizen.vanmgrph" ); // crash!
```
2. See crash!

### Expected behavior

Throw an exception or something instead of crashing completely

**Comment by aylaylay** [comment]
Good catch. Do you know if this happens with entities too?

**Comment by lotuspar** [comment]
Yeah seems to crash entities too!

**Comment by aylaylay** [comment]
The crashes should be fixed now.

**Comment by lotuspar** [comment]
Crash seems to be fixed, closing
