### ISSUE TITLE
Unable to add materials to decal definition

### ISSUE THREAD

**Issue by nywek** [Facepunch/sbox-issues#2437]
### Describe the bug

When I try to add a material to the decal list inside a decal definition by clicking on the `Empty Material` area, the following exception occurs: `Unknown asset type '' for type 'Sandbox.Material'!`

The stacktrace:

```
2022/10/26 20:22:00.805	Interop	Unknown asset type '' for type 'Sandbox.Material'!	System.Exception: Unknown asset type '' for type 'Sandbox.Material'!
   at Tools.ResourceProperty`1.OnMouseClick(MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\PropertyEditors\ResourceProperty.cs:line 126
   at Tools.Widget.OnMouseReleased(MouseEvent e)
   at Tools.Widget.InternalMouseReleaseEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Tools_Widget_InternalMouseReleaseEvent(UInt32 self, IntPtr e)
```

If I instead try to drag an existing material onto the `Empty Material` area, the area lights up blue but nothing happens when I "drop" the material onto the area.

### To Reproduce

1. Open up the Assets Browser
2. Rightclick any folder
3. Click on `New Decal Definition..`
4. Click on the plus icon next to the Decal List
5. Click on the `Empty Material` area/button
6. See that the exception occurs
7. Navigate to a folder containing a material
8. Drag and drop the material onto the `Empty Material` area
9. See that nothing happens

### Expected behavior

Clicking on the `Empty Material` area should open up an asset browser popup that allows me to select a material.
Dragging and dropping an existing material onto the `Empty Material` area should cause the material to be selected as the material to use for that individual decal entry.

### Additional context

This problem seems to happen specifically for decal definitions.
I can add materials to clothing definitions just fine.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by nywek** [comment]
Seems to be fixed thanks!
