### ISSUE TITLE
Spring joint crashes physics engine

### ISSUE THREAD

**Issue by chelog** [Facepunch/sbox-issues#244]
**Describe the bug**
Physics engine goes boom while creating spring joint

**To Reproduce**
Just create spring joint, tried different parameters, all give the same results
```cs
PhysicsJoint.Spring
    .From(ent1.PhysicsGroup.GetBody(0))
    .To(ent2.PhysicsGroup.GetBody(0))
    .Create();
```

**Expected behavior**
Not crashing 🤷‍♂️ 

**Video**
https://youtu.be/SJAvREZQugI

**Comment by aylaylay** [comment]
This should be fixed now. It was caused by frequency being zero. I've set sensible defaults but also fixed it blowing up when frequency is zero.

**Comment by chelog** [comment]
I've set frequency to higher than that when testing giving the same results. Will test now anyway
