### ISSUE TITLE
Failed tool compiles will block other tools from compiling correctly

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#2441]
### Describe the bug

Whenever I open the game with a broken tool, the editor doesn't load properly.

### To Reproduce

1. Download this repro, add it as a tools project: [broken_tool.zip](https://github.com/Facepunch/sbox-issues/files/9879935/broken_tool.zip)
2. Restart your game
3. Entity list, project manager, inspector, etc. will all be blank.

The tools API changes regularly & tools are often not updated until a short while later, which is why this has been an issue for some people in the past.
Fixing any compile errors with the tool in question & hotloading it in will fix this.

### Expected behavior

Failed tool compiles shouldn't stop other tools (or the editor itself) from the compiling properly.

### Media/Files

![image](https://user-images.githubusercontent.com/12881812/198300062-1e385fd5-a562-4406-8a64-3dae2b4a8727.png)

**Comment by handsomematt** [comment]
Garry sorted this now.
