### ISSUE TITLE
Error List filtering recessions

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2442]
### Describe the bug

The Error list can no longer be filtered by addon or message type (Message, Warning, Error)

### To Reproduce

1. Use the error list with a project enabled with nullable ( lol )
2. see a billion warnings from the base addon because it is not written for nullable
3. notice you can no longer filter by addon
4. try and click the "346 Warnings" button to disable the category/type of message entirely
5. notice it doesn't work

### Expected behavior

Category filtering not working seems to just be a bug, but the addon filter was removed entirely

### Media/Files

![sbox-dev_6CCf1XsMtP](https://user-images.githubusercontent.com/12602100/198361057-214b7b18-74a2-418a-b530-f0e3e0dfd6d7.png)

### Additional context

Error list should also probably clear right when a new compile starts, not when it's finished

**Comment by handsomematt** [comment]
garry beat me to it

**Comment by DoctorGurke** [comment]
still can't seem to filter by addon? my error list is still being spammed by 340+ warnings from the base addon due to having nullable enabled in my project.

**Comment by DoctorGurke** [comment]
Could you elaborate further? I feel like it would be useful to be able to filter our warnings, bugs, and console prints on a per addon basis. especially considering the 300+ warnings I'm getting from the base addon
