### ISSUE TITLE
Menu Compile Errors

### ISSUE THREAD

**Issue by alexavil** [Facepunch/sbox-issues#2446]
### Describe the bug

When I try to start s&box in the normal mode, it comes up with the "Menu Compile Errors" box, and I have to kill the process to exit.

### To Reproduce

1. Start s&box from the Steam Library or anywhere else.
2. Wait a bit on the Facepunch logo screen.
3. Observe.

### Expected behavior

The menu should compile and load properly.

### Media/Files

![image](https://user-images.githubusercontent.com/32246131/198557293-f4418b63-9491-476b-bc83-cb08e4239904.png)

Log File:
[Log.log](https://github.com/Facepunch/sbox-issues/files/9887256/Log.log)

### Additional context

My PC is running Windows 10, and my specs are the following:

Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  VivoBook_ASUSLaptop X509JB_R521JB
    Form Factor: Laptop
    Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
    CPU Family:  0x6
    CPU Model:  0x7e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  1190 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Supported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Supported
    AVX512VNNI:  Supported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce MX110
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  31.0.15.1694
    DirectX Driver Version:  31.0.15.1694
    Driver Date: 7 21 2022
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce MX110
    VendorID:  0x10de
    DeviceID:  0x174e
    Revision:  0xa2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.64" (15.51" diag)
                                            34.4cm x 19.4cm (39.4cm diag)
    Primary Bus: PCI Express 4x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Наушники (JBL T460BT Stereo)

Memory:
    RAM:  5949 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  1197411 MB
    Largest Free Hard Disk Block:  123340 MB
    OS Install Date: ??? 25 2022
    Game Controller: None detected
    MAC Address hash: a2c881d9ae2f5760a47fcda1f943424da29e518f

Storage:
    Disk serial number hash: 2c45246c
    Number of SSDs: 0
    Number of HDDs: 0

**Comment by garrynewman** [comment]
I found it, it's happening when your computer takes over 20 seconds to start the game up. The compiler assumes we have hit some kind of infinite loop and abandons. I increased the timeout for now, but will look at a better solution down the road.
