### ISSUE TITLE
SFM Refused to open after this patch 6746925

### ISSUE THREAD

**Issue by PatrickJnr** [Facepunch/sbox-issues#245]
**Describe the bug**
SFM Crashed after this patch was released a few hours ago
_Modified file – bin/win64/tools/sfm.dll (+17.74 MiB)_

**To Reproduce**
Open up sbox-dev click SFM in Asset Browser, wait a few seconds, crashes

**Expected behavior**
SFM to launch

**Additional context**

Seems to have broken after Garry pushed out this update https://steamdb.info/patchnotes/6746925/

**Comment by garrynewman** [comment]
what kind of crash?

**Comment by cmg-divined** [comment]
It simply instantly closes it's self, no crash dump.

**Comment by PatrickJnr** [comment]
After build 6759945 was pushed SFM launches instantly now!

**Comment by PatrickJnr** [comment]
![image](https://user-images.githubusercontent.com/3267523/119630282-b4f57b00-be06-11eb-8d90-addfdaba3151.png)
Sadly lights no longer work.

**Comment by PatrickJnr** [comment]
It was fixed, thank you Garry ♥
