### ISSUE TITLE
Cant run a compiled map

### ISSUE THREAD

**Issue by scienceiseverything** [Facepunch/sbox-issues#2456]
### Describe the bug

whenever I try to run my map after I compiled it the map just doesnt play it and stays in the hammer editor. 
is this a known issue? is there a way to fix it by any chance? the only thing that shows up in my console is this:
![image](https://user-images.githubusercontent.com/77688052/198835274-aab7af58-9840-44fe-bffa-0ad43d046652.png)
thanks, and have a nice day :)

### To Reproduce

I have no idea

### Expected behavior

it SHOULD just run the map with no problems

### Additional context

I'm running this on windows 11 and my specs are an AMD Ryzen™ 5 5500U with 8GB of ram

**Comment by handsomematt** [comment]
I've made the map launch from Hammer wrap the path in quotes so this doesn't happen.
