### ISSUE TITLE
Model import

### ISSUE THREAD

**Issue by veydart** [Facepunch/sbox-issues#2457]
### Describe the bug

when i trying to import models, window closing

### To Reproduce

Model Editor, Import Model

### Expected behavior

Model must be imported

**Comment by veydart** [comment]
Error loading resource file "models/untitled_4.vmdl_c" (Error: ERROR_FILEOPEN)

**Comment by aylaylay** [comment]
more info needed

**Comment by veydart** [comment]
I downloaded this model (https://www.turbosquid.com/3d-models/3d-genesis-car-modified-1676017) and trying to import

**Comment by veydart** [comment]
https://www.youtube.com/watch?v=5uMnWaVq_58 sorry for sound on background )))

**Comment by aylaylay** [comment]
Model is too complex, loader is hitting limits

**Comment by aylaylay** [comment]
![sbox-dev_BFCtCERqc8](https://user-images.githubusercontent.com/1667289/198849318-77422c5b-6af1-4d62-902f-8eec521db379.png)

**Comment by aylaylay** [comment]
We should add some protection against trying to load a model like this but you really don't want to be using this model in a game.

**Comment by veydart** [comment]
ok thanks
