### ISSUE TITLE
GetMaterialGroup() always returns 0

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#246]
**Describe the bug**
ModelEntity.GetMaterialGroup() will always return 0 regardless of what material group is currently active on both server and client. I have double checked that the model has more than one material group as setting it to 0 and 1 makes a visual difference. 

**To Reproduce**
1. 
```
SetMaterialGroup( 1 );
Log.Info( GetMaterialGroup().ToString() );
```
2. Get "0"

**Expected behavior**
Expected to return the index of the active material group

**Additional context**
I have only tried this on the Sandbox.Prop class

**Comment by aylaylay** [comment]
Should be fixed.

**Comment by Leafdroid** [comment]
Is fixed!
