### ISSUE TITLE
#faq in the discord

### ISSUE THREAD

**Issue by F0gboy** [Facepunch/sbox-issues#2464]
### For?

Other

### What can't you do?

I wasnt sure where to request this, but alot of new people arrive to the server daily, asking for the exact same things. 
How does the new key system work? how do i get a key? i want s&box?
if there was a facts and questions channel in the discord, we could simply direct them to that channel.

### How would you like it to work?

.

### What have you tried?

.

### Additional context

just filling these out as blanks, because the first box tells it all.

**Comment by bakscratch** [comment]
https://wiki.facepunch.com/sbox/General_FAQ

Has all the info.

**Comment by F0gboy** [comment]
ah great, thanks!
