### ISSUE TITLE
A websocket implementation.

### ISSUE THREAD

**Issue by NoSharp** [Facepunch/sbox-issues#247]
**What can't you do?**
Use any form of networking to communicate with a web server in real time. Web Sockets would be ideal for communication with a Web Server, although potentially possible currently with the use of the HTTP library, it'd be nice to have a nice wrapper around this. 

**How would you like it to work?**
To be able to communicate with a web server from a game server.

**What have you tried?**
No current workaround.

**Additional context**
None

**Comment by Rohansi** [comment]
There's now a `Sandbox.WebSocket` class for this
