### ISSUE TITLE
Markdown support for Gamemode descriptions.

### ISSUE THREAD

**Issue by PixelQubed** [Facepunch/sbox-issues#2483]
### For?

S&Box

### What can't you do?

We can't properly format the descriptions of game modes currently with like bold lettering or underlining, which makes descriptions look ugly.

### How would you like it to work?

Just like how GitHub's markdown works. Have buttons on the site but also allow the syntax in the editor online. Also, a preview of the final result would be nice too.

### What have you tried?

Nothing I can try other than adding huge spaces between paragraphs.

**Comment by ogniK5377** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/1113
