### ISSUE TITLE
Steam overlay bug in editor

### ISSUE THREAD

**Issue by JohnyBro** [Facepunch/sbox-issues#2488]
### Describe the bug

When I want to invite a steam friend to my party it open the overlay but I can't interact with it.

### To Reproduce

1. Open S&Box editor
2. Clic on the + in the right menu
3. Clic on "Invite someone else..."
4. Try to interact with the overlay

### Expected behavior

I should be able to interact with the overlay ui, pressing buttons etc.

**Comment by DevulTj** [comment]
Ideally we'd disable steam overlay in Editor Mode, but the Steam API doesn't have anything like this exposed for us to do that right now.
