### ISSUE TITLE
Camera methods to check if point is in frustum / entity is visible

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#249]
**What can't you do?**
I can't easily check if the player can see a given entity or that a given point is inside a camera's view frustum.

**How would you like it to work?**

A couple of new methods:
* `bool Camera.IsEntityVisible(Entity ent)`: indicates whether `ent` is visible from the camera.
* `bool Camera.IsPointInFrustum(Vector3 point)`: indicates whether `point` is inside the camera's view frustum.

**What have you tried?**
I'm currently using a terrible solution involving multiple raycasts and some view angle math to check if the player can see a specific entity, but it's not very accurate.

**Additional context**
N/A

**Comment by garrynewman** [comment]
By putting it in a Camera it'd only really be usable clientside. What do you want to do in particular?

**Comment by TheBerkin** [comment]
I'm looking for ways to make entities react to players seeing them. In particular I have a use case where I have an NPC that adversely affects the player as soon as it enters their field of vision-- but if they're looking away (even if it's just out of frame) it does nothing.

I'm sure there are better ways to solve this, but some sort of camera interaction was the best solution I could think of at the time of writing this.

**Comment by garrynewman** [comment]
I think for this thing you basically want to use dot product. Get the eye director of the player's eye and dot product it to the direction from the player's eye to the enemy to find out of they're parallel or facing the opposite way.
