### ISSUE TITLE
ModelDoc's RenderPrimitiveSphere node generates a bugged model in-game

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#250]
**Describe the bug**
The sphere's geometry is normal on the outside. However there is a flat disk shape on the interior of the sphere. Additionally, the sphere's shadow is cast by this disk shape instead of the actual sphere geometry on the outside. Oddly, this bug can't be observed in ModelDoc or the Asset Browser preview.

**To Reproduce**
1. Create a new model in ModelDoc
2. Add a `RenderPrimitiveSphere` node to the model, and leave the default settings
3. Spawn a ModelEntity with this model set to it by SetModel()
4. Fly inside the sphere with devcam to observe

**Expected behavior**
There shouldn't be an anomalous shape within the sphere, and shadows should be cast from the sphere's expected geometry.

**Screenshots**
Exterior of the sphere appears normal aside from the shadow:
![Screenshot (151)](https://user-images.githubusercontent.com/33941498/119570352-9bf0b980-bd75-11eb-9f23-75f90102f193.png)

Peeking into the sphere:
![Screenshot (152)](https://user-images.githubusercontent.com/33941498/119570288-84b1cc00-bd75-11eb-8e3b-1eccac41a9bb.png)

**Comment by aylaylay** [comment]
Yep we're aware of this one. It's a strange one. I'll take another look.

**Comment by aylaylay** [comment]
This was a really bizarre one, lucky I managed to fix it. Let me know if it's alright now.

**Comment by Willco2** [comment]
Yep, all fixed now, thanks.
