### ISSUE TITLE
Entities derived from Player class no longer activate hammer triggers when Client spawnflag is enabled.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#252]
**Describe the bug**

Entities derived from Player class no longer activate hammer triggers when Client spawnflag is enabled. This was working before pawn system.

**To Reproduce**

- Create a trigger_once that does something to another hammer entity. Select 'Client' spawn flag.

- Walk through it. Notice the trigger is no longer activated.

- Must select 'Everything' spawnflag.

**Expected behavior**

- Selecting Client should trigger spawn flag as a Player pawn.

**Comment by handsomematt** [comment]
I fixed this a while ago, basically I fucked off the spawnflag and made the triggers work with our entity tags ( https://wiki.facepunch.com/sbox/Entity_Tags ), by default all triggers start with a "player" tag which is also on the default player pawn.
