### ISSUE TITLE
Using custom tag names in templating no longer render their corresponding panel.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#253]
**Describe the bug**

Before we were able to render the chatbox by doing `<chatbox></chatbox>`. This no longer seems to be the case.

**To Reproduce**

- Embed `<chatbox></chatbox>` into an html template.

- The child that you'd expect to be a Chatbox is instead just a Panel.

**Expected behavior**

Embedded custom panels in html template should render.

**Additional context**

I think its really important to HTML templating that you can recursively render custom panels. Without this functionality we can only use html templating for leaf node panels.

**Comment by Trojaner** [comment]
Would be great if we can somehow pass values too, e.g. `<chatbox SomeProperty="123" />` or `<chatbox @SomeProperty="SomeOtherProprerty" />` to bind to a property of the current panel. This could be also used to subscribe to events (e.g. `<chatbox @OnEntry="OnNewChatEntry" />`

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Jac0xb** [comment]
It's working great!
