### ISSUE TITLE
New console NRE

### ISSUE THREAD

**Issue by TankNut** [Facepunch/sbox-issues#254]
**Describe the bug**

Clicking on any command that's been input into the console causes an NRE

**To Reproduce**

1. Load game
2. `status` in console
3. Click the line that says `> status`

**Expected behavior**

Either a stack trace or nothing at all

**Screenshots**

![2021-05-26_17-58-31](https://user-images.githubusercontent.com/1381265/119694394-7931d400-be4d-11eb-83b4-683b9cbb57dc.png)
![2021-05-26_18-04-05](https://user-images.githubusercontent.com/1381265/119694312-6b7c4e80-be4d-11eb-9668-6d5407bdbed4.png)

**Additional context**

The time displayed next to the command always reads 12:00:00 as well

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by TankNut** [comment]
No more errors and the time issue is fixed 👍
