### ISSUE TITLE
Make WalkMove Virtual

### ISSUE THREAD

**Issue by Redhacker1** [Facepunch/sbox-issues#255]
**What can't you do?**
Currently, Walkmove in the WalkController is not overridable. I do it on my client though it means other people cannot play.

**How would you like it to work?**
I would prefer to override it using the override keyword.

**What have you tried?**
For now, I can just add "virtual" to the Walkmove Controller and override it, however, it causes issues with other people.

**Additional context**
By default WaterMove, LadderMove, and Airmove are all virtual. I can override them.

**Comment by garrynewman** [comment]
I'm kind of on the fence with this. I feel like it'd be better if I make it sealed and expect people to copy and paste it into their project.

Either way this should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Trojaner** [comment]
Can you please look into https://github.com/Facepunch/sbox-issues/issues/183 as well while at it?

**Comment by Redhacker1** [comment]
Thank you, it looks to have been fixed.
