### ISSUE TITLE
A way to tell if a object is being seen

### ISSUE THREAD

**Issue by TheBoxTrot** [Facepunch/sbox-issues#2555]
### For?

S&Box

### What can't you do?

have an entity have a response if it is seen by a player like how trigger_look works on source 1

### How would you like it to work?

same way onTouch works for triggers. just have OnSeen and OnUnSeen

### What have you tried?

nthing

**Comment by kythre** [comment]
you could cast a ray to the player from the object to see if there is line of sight then just do some math to calculate if the object is in the direction the player is facing and if its within the players fov

**Comment by kythre** [comment]
actually you could use [this method](https://asset.party/api/Sandbox.Vector3Extensions.ToScreen(Vector3,Vector2)), input the position of the entity and if it returns non null then it's visible on screen

**Comment by TheBoxTrot** [comment]
> actually you could use [this method](https://asset.party/api/Sandbox.Vector3Extensions.ToScreen(Vector3,Vector2)), input the position of the entity and if it returns non null then it's visible on screen
> 

This seems promising I'll see if this works
