### ISSUE TITLE
Translate tool doesn't work properly with static cable nodes

### ISSUE THREAD

**Issue by wouterpleizier** [Facepunch/sbox-issues#256]
**Describe the bug**

In Hammer, the translate tool gizmo's centre (the purple dot) can be dragged in order to quickly move the selection to whatever is behind the mouse cursor in 3D space. When moving a static cable's nodes this way, the nodes will move erratically when the grid is enabled, or fly towards the camera when the grid is disabled or set to a low size. It looks like Hammer is attempting to snap the cable's nodes to the cable's own geometry.

**To Reproduce**

1. Launch Hammer and open/create a map
2. Switch to the Path Tool and create a static cable
3. Select one of path's nodes, switch to the translate tool and attempt to move the node with the centre gizmo

**Expected behavior**

When moving static cable nodes, their own geometry should be ignored and they should snap to the geometry behind them instead.

**Video**

Video showing the expected behaviour with a regular entity, then the bug when moving cable nodes with and without grid snapping:

https://user-images.githubusercontent.com/8166218/119713862-7b525d80-be62-11eb-9979-cbfa101c8404.mp4

**Comment by aylaylay** [comment]
This should be fixed when the game next updates. Let me know if it is.

**Comment by wouterpleizier** [comment]
Working as expected now. Thanks!
