### ISSUE TITLE
Scroll wheel doesn't scroll Inspector

### ISSUE THREAD

**Issue by Weldify** [Facepunch/sbox-issues#2560]
### Describe the bug

Scroll wheel doesn't work in the Inspector

### To Reproduce

1. Scroll your mouse inside the inspector

### Expected behavior

Scroll wheel should work inside the inspector

**Comment by trundler-dev** [comment]
I'll just add that it does work while mousing over the scroll bar.

**Comment by Weldify** [comment]
Bumping this, Inspector still isn't scrollable unless youre hovering directly over the scroll bar. One thing to note is the animgraph inspector scrolls properly.

**Comment by DevulTj** [comment]
Doesn't happen for me anymore
