### ISSUE TITLE
Default `pointer-events` behavior is not `none`

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#2570]
### Describe the bug

Creating a UI panel that enables pointer events and tries to listen to pointer events will not work if the game hud has not explicitly set `pointer-events: none`.

Setting `pointer-events: none` on the hud panel will then allow a UI panel to receive the pointer events.

### To Reproduce

Video demonstration: https://drive.google.com/uc?id=1zdE2thzIrCTK-wgqM2nu9aHlDInZpFx7

Alternative:

1. Use the DM98 code
2. Create a UI panel that sets `pointer-events: all` and has mouse callbacks
3. Display the UI panel and try to select/hover/click
4. The events will not be received by the UI panel, the hud is receiving the events instead.

### Expected behavior

If `pointer-events` is not set on a ui panel, it should default and behave as if it were set to `none` as defined in the sbox wiki: https://wiki.facepunch.com/sbox/pointer-events#pointereventsnone

### Media/Files

https://drive.google.com/uc?id=1zdE2thzIrCTK-wgqM2nu9aHlDInZpFx7

**Comment by xezno** [comment]
Fixed this a while ago when I added auto-generated defaults - it's definitely PointerEvents.None now
