### ISSUE TITLE
Entity IO issues with func_button, func_door_rotating, and triggers

### ISSUE THREAD

**Issue by genericicon** [Facepunch/sbox-issues#258]
**Describe the bug**
When pressing a func_button not all outputs fire. Outputs fire to a func_door_rotating but not anything else

Outputs from a func_door_rotating work on itself, however, they do not go out to other entities.

Triggers in the sandbox game mode don't work properly with the player, you have to check "everyone" spawnflags in order for players to trigger the trigger.

Vmap with some world text explanations is attached.
[io_test.zip](https://github.com/Facepunch/sbox-issues/files/6553509/io_test.zip)

**Comment by garrynewman** [comment]
This is awesome, thank you

**Comment by garrynewman** [comment]
I think I solved all of these except for the door one. I didn't really see any way it could trigger the second door?

**Comment by garrynewman** [comment]
Did you forget to save

![image](https://user-images.githubusercontent.com/928843/119838256-2adb0e80-befb-11eb-9ff9-a8e23c5c091f.png)

**Comment by genericicon** [comment]
Seems like it, I'll add upload a new vmap.
[io_test.zip](https://github.com/Facepunch/sbox-issues/files/6554622/io_test.zip)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by genericicon** [comment]
Everything works, thanks!
