### ISSUE TITLE
border-color, border-width styles not parsed

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#259]
**Describe the bug**

Styles.Set is missing parsing for `border-color` and `border-width`.

```csharp
    case "border-color":
        BorderColor = Color.Parse(value);
        return true;
    case "border-width":
        BorderWidth = Length.Parse(value);
        return true;
```

**Comment by kurozael** [comment]
Thanks @handsomematt. This should be fixed in the next Steam build which usually takes 5 minutes. Please can you confirm whether it has resolved the issue, and then close this issue if it has.
