### ISSUE TITLE
Antialiasing Issues

### ISSUE THREAD

**Issue by VanderAGSN** [Facepunch/sbox-issues#26]
It may not be the best idea to report this issues for the current stage of game, but it is there, i need game with no aa for own purposes

**In Game:** 

With 8x MSAA

![image](https://user-images.githubusercontent.com/14910562/116038124-b437c080-a671-11eb-9dfa-4a37adf04e8d.png)

With 0/1 (no MSAA)

![image](https://user-images.githubusercontent.com/14910562/116039351-4d1b0b80-a673-11eb-9c18-c12fdb91c6ac.png)

Steps to reproduce: open **gameinfo.gi** and change "MSAADefaultNonVR"	"4" to 0/1. When value is more than 1 - game looks fine, when is 0/1 the game becomes brighter and feels like an oversaturated bloom

**In Dev Tools:**

In Asset Browser -> Tools -> Options you can change AA for your purposes, and there is 16x MSAA, it crashes Hammer, and broke ModelDoc viewport

With 8x MSAA

![image](https://user-images.githubusercontent.com/14910562/116039274-370d4b00-a673-11eb-82e6-30ddcebfcbd1.png)

With 16x MSAA

![image](https://user-images.githubusercontent.com/14910562/116039286-3a083b80-a673-11eb-9d7a-12435b397543.png)

**Comment by VanderAGSN** [comment]
I found out that problems with overbrighten bloom are not only in the game

With no MSAA in Asset Browser Settings

![image](https://user-images.githubusercontent.com/14910562/116042335-f3b4db80-a676-11eb-8d4d-eac819827b40.png)


With 8x MSAA

![image](https://user-images.githubusercontent.com/14910562/116042340-f6afcc00-a676-11eb-8709-94d8e5be65fd.png)

**Comment by celebeimre67** [comment]
also this is happening in HL:A same behavior.

**Comment by VanderAGSN** [comment]
On construct you can still see intense bloom without antialiasing, here are comparisons with AA and without AA
![msaa](https://user-images.githubusercontent.com/14910562/136096785-2f1cda12-4d5f-45c9-b9f9-7b34a689604b.png)
![no msaa](https://user-images.githubusercontent.com/14910562/136096793-81ff68ee-dfa1-4d19-94c4-96e0341ae4ef.png)
Most likely it still affects the tools as well
