### ISSUE TITLE
Fix casing of the CollisionLayer enums

### ISSUE THREAD

**Issue by TomDotBat** [Facepunch/sbox-issues#261]
The CollisionLayer enums currently swap between UPPER_SNAKE_CASE and PascalCase, it would be nicer just to use one to make things more clean and consistent.

**How would you like it to work?**
Use PascalCase for all of the enums to keep consistency.

**Screenshot**
![https://img.tomdotbat.dev/yy6Gf](https://img.tomdotbat.dev/yy6Gf)

**Comment by garrynewman** [comment]
The collision system needs a big review on how it works. I'm waiting until we're further down the road for that, so I've got better knowledge of what's what.
