### ISSUE TITLE
Disabling a project doesn't refresh the asset browser view properly

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2637]
### Describe the bug

When I have a project selected in the asset browser, it doesn't refresh and remove those assets from the view when I disable the project.

### To Reproduce

1. Have some project with assets enabled and select it in the asset browser
2. Disable the project
3. Notice how it's still showing the selected project directory plus all the assets, despite them being unmounted

### Expected behavior

The asset browser should refresh when project states are changed

### Media/Files

Enabled Speed-Dial Project:
![sbox-dev_cd0dPORbDK](https://user-images.githubusercontent.com/12602100/205454328-5d10b8b9-e1f7-4a8c-b1cd-f16c3ca82277.png)

Disabled Speed-Dial Project:
![sbox-dev_FRbR5mNrb3](https://user-images.githubusercontent.com/12602100/205454338-7cb545b8-4a87-440a-a8dc-31ba5f4674c5.png)

### Additional context

Attempting to open any of the left-behind files will just bring up an empty modeldoc or material editor view etc, very confusing

**Comment by DevulTj** [comment]
Shouldn't be a thing anymore since we load singular projects
