### ISSUE TITLE
Level Streaming

### ISSUE THREAD

**Issue by sophfee** [Facepunch/sbox-issues#2649]
### For?

Hammer

### What can't you do?

I’d like to make more procedural type levels, but a big inhibitor is that you can only use dynamic lights, which aren’t the best.

### How would you like it to work?

I’d like to see the ability to place a prefab type object via code that has the ability to use a precompiled lightmap but can be used anywhere in the map. Aka Level streaming

### What have you tried?

Using dynamic lights

**Comment by geferon** [comment]
Any way we could get something similar to this in any way? Would be nice to be able to dynamically import light maps
