### ISSUE TITLE
Easy ViewModel rendering accessor on Sandbox.Camera

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2659]
### For?

S&Box

### What can't you do?

Previously, CameraSetup had an accessor for ViewModel specific camera settings, such as viewmodel fov, nearz, farz. This is no longer the case and we have to go via the SceneCamera reference directly and set the values there.

### How would you like it to work?

Would be nice to have an accessor directly on Camera again, to simply affect the main viewmodel. Something like... `Camera.ViewModel.FieldOfView = fov` etc...

### What have you tried?

Currently we have to use `Camera.Main.SetViewModelCamera( fov, nearz, farz )`, Not at nice api wise I think

**Comment by timmybo5** [comment]
Before the refactor the viewmodel cam would always follow the main camera, so applying a shake to the main camera meant the viewmodel camera followed it automatically, now we need to apply the same camera shake to all the active viewmodels. It would be nice if there was a property on the viewmodel to automatically follow the main cam.
