### ISSUE TITLE
New particle system entity ignores start active flag in hammer.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#266]
**Describe the bug**

There is no `Spawn` logic in `ParticleSystemEntity.cs` that listens to the start_active hammer prop and spawns the entity.

**To Reproduce**

- Create a `info_particle_system`
- set it to Start Active.
- Particle system will not start on map spawn and you must call Start() on the entity or have a trigger start the system with IO.

**Expected behavior**

Start Active is not ignored and starts the system like expected.

**Comment by aylaylay** [comment]
I looked into this. There's problems creating the particle in Spawn. Something @garrynewman will have to look into.

**Comment by Jac0xb** [comment]
I think this was fixed.
