### ISSUE TITLE
Change `UpdateBBox` in `Duck.cs` to be `virtual` modifier

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#267]
**What can't you do?**

When attempting to override the `UpdateBBox()` method in `WalkController.cs`, there is a call made to `Duck.UpdateBBox(...)` which is an `internal` method. This means that I'm unable to override this method (and even call it) unless I create my own `Duck.cs` class and change the implementation.

**How would you like it to work?**

Change `UpdateBBox()` in `Duck.cs` to be `virtual`, or allow other assemblies to call the method.

```csharp
// WalkController.cs
public virtual void UpdateBBox()
{
	var girth = BodyGirth * 0.5f;

	var mins = new Vector3( -girth, -girth, 0 ) * Pawn.Scale;
	var maxs = new Vector3( +girth, +girth, BodyHeight ) * Pawn.Scale;

	Duck.UpdateBBox( ref mins, ref maxs );

	SetBBox( mins, maxs );
}

// Duck.cs
internal void UpdateBBox( ref Vector3 mins, ref Vector3 maxs ) { .. }
```

**What have you tried?**

Trying to override `UpdateBBox()` in `WalkController.cs` throws an error `Duck.UpdateBBox(...)` `Cannot access internal method 'UpdateBBox' here`

**Additional context**

`UpdateBBox()` in `WalkController.cs` is already a public virtual, so probably makes sense to give access to `Duck.cs` as well.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
