### ISSUE TITLE
Whitelisting of some basic functions

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/sbox-issues#268]
**What can't you do?**
Not allowed to use: System.Private.CoreLib/System.ArgumentException
Not allowed to use: System.Private.CoreLib/System.ArgumentNullException
Not allowed to use: System.Private.CoreLib/System.ArgumentOutOfRangeException
Not allowed to use: System.Private.CoreLib/System.InvalidCastException
Not allowed to use: System.Private.CoreLib/System.InvalidOperationException
Not allowed to use: System.Private.CoreLib/System.PlatformNotSupportedException

Not allowed to use: System.Private.CoreLib/System.BitConverter
Not allowed to use: System.Private.CoreLib/System.Convert

Not allowed to use: System.Private.CoreLib/System.Diagnostics.Stopwatch

Not allowed to use: System.Private.CoreLib/System.IComparable

**How would you like it to work?**
Hopefully should be simple to whitelist. I might be able to simplify the exceptions, but would be a bit tedious.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by thegrb93** [comment]
Looks good. Just a heads-up there's a `System.Private.CoreLib/System.Convert.ToInt32*` on line 76 that can be deleted now.
