### ISSUE TITLE
Outputs with delay parameter set trigger at the same time as Outputs with no delay parameter.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#269]
**Describe the bug**

Outputs fire instantly regardless of delay time set in IO parameters. 

This is an extension of #236 since it was thought to have been fixed.

This map demonstrates that two outputs fire at the same time (opening and closing a door) even though the door should close 10 seconds after the button press is fired.
[io_delay.zip](https://github.com/Facepunch/sbox-issues/files/6559460/io_delay.zip)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by garrynewman** [comment]
re
