### ISSUE TITLE
Don't attempt to join servers with passwords via the menu

### ISSUE THREAD

**Issue by bludotbat** [Facepunch/sbox-issues#273]
**What can't you do?**
Join other servers if one person in the gamemode has a password on

**How would you like it to work?**
Any instance of a game with a password to just be ignored by the menu find server button

**What have you tried?**
n/a

**Additional context**
n/a

**Comment by DoctorGurke** [comment]
use the password con command

**Comment by bludotbat** [comment]
what that's not a solution to the problem

**Comment by DoctorGurke** [comment]
Didn't say it was but it works for now, especially if you don't want random people join your dev game once an hour

**Comment by DoctorGurke** [comment]
I also seem to have misread the issue a bit, nvm
