### ISSUE TITLE
Custom Compile Saves

### ISSUE THREAD

**Issue by Mike466-0** [Facepunch/sbox-issues#2737]
### For?

Hammer

### What can't you do?

If you have a sort of preset to compile you have to enter it in every time which adds up and you sometimes forget tu check or uncheck things

### How would you like it to work?

I want to be able to save custom compile presets 

### What have you tried?

Ive tried entering it in every time but often leads to mistakes and wastes time

**Comment by MikeShaughnessy** [comment]
bump
