### ISSUE TITLE
Client stuck on "Ready To Play", can still hear sounds/ do interactions

### ISSUE THREAD

**Issue by m4rkey** [Facepunch/sbox-issues#274]
**Describe the bug**
Gvarados has created a map called Spooky Forest ( gvar.slendy_forest ) when a player attempts to join on this map the player will never actually finish loading into the game and will be stuck on the "Ready To Play" screen or they will load into the game with around 0-1 fps, They will still be able to hear sounds and click buttons while being stuck on this screen, meanwhile the Host is spammed with sending full update messages. I have attempted and recreated this with 2 gamemodes ( Sandbox, and my own gamemode ) and 2 different individuals

**To Reproduce**

1. Click on Sandbox and create a game, and select the map Spooky Forest
2. Wait for yourself to load in and then have another player join the game ( not a bot )
3. Wait for the console to start spamming sending full update messages to the client

**Expected behavior**
I expect that anyone that anyone that attempts to load this map should be able to and play normally.

**Screenshots**

![](https://i.imgur.com/M9qlUMD.png)

**Additional context**

We have tried removing things from the map, reuploading the map, recompiling the map, and making small changes to the map but are unfamiliar on what is actually causing this issue. It seemed to have started happening after the last few updates.

**Comment by garrynewman** [comment]
This was caused by the sea trigger interacting with the static world 🤕 

This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by m4rkey** [comment]
It works now. Thank you very much! :)
