### ISSUE TITLE
[ModelDoc] Multiple-meshed FBX files will discard almost every bone if you include a Morph

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#2752]
### Describe the bug

Importing an FBX file that contains morphs and multiple meshes, all sharing one armature, will only keep **the first mesh's vertex groups**, which causes every other bone to be automatically discarded.

Here is a full video of the issue in action:
https://www.youtube.com/watch?v=hlRqxGc0Yw0

The file contains every mesh's vertex groups, is skinned correctly, and the morphs work as they should, so I am left to assume ModelDoc is the culprit here.

Some troubleshooting I did:
- Creating a ragdoll that uses every bone will show that the meshes are not even skinned, as they will not follow their parent bones.
- Breaks even if only one mesh has a morph, still will use the first mesh instead of the one with the morph.
- Blender's horrible FBX exporter is seemingly not at fault, as no option changes the outcome, and the file works correctly if imported back into blender.

If it is intentional, then feel free to change the tag to "Feature Request", because I feel it shouldn't be.
I had this problem multiple times in the past, and to fix it I had to export every mesh as its own file containing the armature, this is not ideal.

### To Reproduce

1. Create multiple meshes
2. Rig them to a common armature
3. Add morphs
4. Export all of them in FBX
5. Import FBX in modeldoc
6. Add a morph-supported material
7. ???
8. Profit

You can also use the blend file I attached to repro this, it has the morphs by default, it is very minimal and I didn't do any trickery.

### Expected behavior

All meshes should contain their vertex groups and morphs too,
it is possible that this is the intended behaviour, as Max uses a separate dmx file for the citizen's head that contains the facial morphs, instead of including it all in the same FBX file like the rest of the body, that has its bodygroups separated in multiple meshes.

Possibly this is the reason? I feel as if it's worth bringing up.

### Media/Files

Here is a full video of the issue in action:
https://www.youtube.com/watch?v=hlRqxGc0Yw0

Here are quick repro I did, they are minimal (I replaced the eye material so you don't have to download that too):
- The VMDL file **without morphs**
[spheres_vmdl.zip](https://github.com/sboxgame/issues/files/10368702/spheres_vmdl.zip)

- The spheres.fbx file **with morphs** (replace with original spheres.fbx)
[spheres_morphs.zip](https://github.com/sboxgame/issues/files/10368703/spheres_morphs.zip)

- The Blender file, morphs included, delete or re-add at will
[spheres_blend.zip](https://github.com/sboxgame/issues/files/10368704/spheres_blend.zip)

### Additional context

I am using Blender's default horrible FBX importer/exporter, so maybe the results are different if you use Maya or 3dsMax.

Although I hope that's not the case as I asked 2 other modellers to try it on their machines, and they had the same result.

**Comment by Grodbert** [comment]
Welfare check on this issue after https://github.com/sboxgame/issues/issues/3213 , as it seemed they could be related,
it is still happening, as I've just ran into it again.

**Comment by aylaylay** [comment]
did you say this is fixed now?

**Comment by Grodbert** [comment]
> did you say this is fixed now?

Seems it works now!
before:
![Image](https://github.com/user-attachments/assets/8886e841-b1e7-4323-a077-c516e92b7e80)
after:
![Image](https://github.com/user-attachments/assets/49547dd6-3063-4d62-aa53-12c7513887e4)

You can see both the bones and the morphs are kept!
