### ISSUE TITLE
Trouble setting a predicted value from the server.

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#276]
**Describe the bug**
Trying to modify the BaseWeapon's AmmoClip value from the Game's OnKilled(Client, Pawn) has lead to some confusion regarding predicted values. This might very well be my/our misunderstanding of how prediction is supposed to work, but we can't get it to replicate an updated value from the server to the client or persist when setting it on both manually. This isn't just an issue of timing and getting a single prediction error, the value just *never* updates on the client in most attempts and will persist to give prediction errors until the value gets reset via death or similar.

We tried changing it in a supposedly predicted context via the Player's and Weapon's simulate, using a boolean field to check when we want it changed. Tried just setting it from the Game, thinking it'd be server side and authoritative. Also tried a clientrpc to update it on the client manually and some other attempts that build upon these ideas.

**Expected behavior**
Have value replicated to clients or an easy way to set values from an authoritative end.

**Additional context**
To reiterate, this could very well just be a matter of misunderstanding from our side, but anybody that was nice enough to spend some time talking to us in the help channel either seemed equally as clueless or found the behaviour to be weird as well.
We're literally just trying to add to the current AmmoClip from OnKilled 😢

**Comment by garrynewman** [comment]
Did you solve this?

I tried setting a predicted value from server only, and while I got the prediction error (which is expected), it did update the value on the client.

Is this behaviour you're not seeing?

**Comment by garrynewman** [comment]
Actually I got it, don't worry

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
