### ISSUE TITLE
Incorrect resolution options

### ISSUE THREAD

**Issue by LunaFolf** [Facepunch/sbox-issues#2769]
### Describe the bug

I'm playing on a 2560x1440 monitor and for the past several months, 4+ months minimum, my currently set resolution option does not show and I only have two options available.

![image](https://user-images.githubusercontent.com/5392255/211874056-3e6cfd41-26e9-4d2c-9575-dec6ecd4b61b.png)

### To Reproduce

Not really reproduceable on other systems as far as I can tell so far...

### Expected behavior

Multiple resolutions should be shown, including the correct resolution for my monitor.
In addition to this, the current resolution should be shown - my current theory is that my resolution _is_ set to 2560x1440, but because it's not an option it doesn't display as the selected value.

### Media/Files

![image](https://user-images.githubusercontent.com/5392255/211874653-25e3573d-146c-4e53-90eb-518f90726bce.png)

### Additional context

I first noticed this issue on windows 10, and I am currently using windows 11.
AMD CPU, 2080s, latest gpu drivers always.

I've included a DxDiag report, which should have all the necessary hardware info you should need.
[DxDiag.txt](https://github.com/sboxgame/issues/files/10394618/DxDiag.txt)

**Comment by sheeperz** [comment]
Heya, throwing my experience in here as well.  I seem to be having the same issue.

I'm expecting to be able to select 1920x1080, but can only select from the following.

![image](https://user-images.githubusercontent.com/10039167/215219384-79381bb1-647d-4611-80d0-0f431717fc6d.png)

As OP said, I also suspect that the app is rendering at my desired native resolution already, and perhaps is a display bug of some sort.  However, if I select any other resolution and try to switch back, I'm unable to.  

If anyone else experiences this, my workaround is to completely uninstall/delete all s&box files and then reinstall in hopes that the app defaults to my desired native resolution.  Hope I was able to help.  I will also throw my DxDiag in the ring.

[DxDiag-sheep.txt](https://github.com/sboxgame/issues/files/10523639/DxDiag-sheep.txt)

**Comment by ogniK5377** [comment]
The resolution is reported by the driver. Since you're both running on nvidia cards, check the Nvidia control pannel in the Change resolution section. You should see a list of resolutions your drive will report, if your resolution isn't there try adding it and see if it works

**Comment by WhiskeeDev** [comment]
> The resolution is reported by the driver. Since you're both running on nvidia cards, check the Nvidia control pannel in the Change resolution section. You should see a list of resolutions your drive will report, if your resolution isn't there try adding it and see if it works

![image](https://user-images.githubusercontent.com/5392255/218588782-07c7288f-fd19-44b5-b3d5-86deb8ec1651.png)
![image](https://user-images.githubusercontent.com/5392255/218588896-f2217265-b357-431e-bdb0-3640f6905faf.png)

**Comment by Moofers** [comment]
Same, can go borderless at 2560x1440 but the option isn't there in game.

**Comment by dictateurfou** [comment]
i have the same issue
