### ISSUE TITLE
func_button entities don't toggle properly

### ISSUE THREAD

**Issue by waffles187** [Facepunch/sbox-issues#277]
**Describe the bug**
Pressing a func_button with "OnIn" and "OnOut" outputs do not seem to do anything.
Pressing a button with "OnPressed" outputs work as expected.

vmap + vpk:
[maps.zip](https://github.com/Facepunch/sbox-issues/files/6566015/maps.zip)

**Comment by robotboy655** [comment]
Should be fixed whenever the game updates next on Steam.

Please confirm so from your end and close this issue.

**Comment by waffles187** [comment]
It's still affected by "Delay Before Reset" on my end.

**Comment by robotboy655** [comment]
That is intentional, no? I have looked how it works in Source 1 and that is it. You can always set "Delay before reset" to 0 or 0.1.

**Comment by waffles187** [comment]
There is no way to stop it from resetting except for putting "-1" as the delay. Except then you can't press the button anymore.

**Comment by robotboy655** [comment]
Use 0, that should work with yesterdays changes.

**Comment by waffles187** [comment]
Yeah setting it to 0 works. I just remember it being 3 by default and not having to worry about it.
