### ISSUE TITLE
Change WorldPanel Render Time

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#2770]
### For?

S&Box

### What can't you do?

For background:
I am trying to make a "world panel" hud that uses world panels as hud elements, however I want to draw my world panels after the `PostTransparent` render stage, and have them ignore the depth buffer so they draw on-top of the world.

### How would you like it to work?

I would like to have an additional flag on world panels; the ability to say "render in the world like everything else" and "render after the world, ignoring depth"

### What have you tried?

I have no way of doing apart from creating a new scene world, rendering the panels there, and then drawing them ontop of the game scene with a render hook.

This sorta works, but also has other issues such as no backdrop filter effects, and strange antialiasing.

![image](https://user-images.githubusercontent.com/3459787/211955519-101d2bbc-6a40-4fe1-91d0-6f2b27c6aeb9.png)
Look at those gross lines on the border of the box, and the weird text rendering!

### Additional context

I have tried using css `transform` but it just doesn't look as good, also then post processing effects don't effect the UI.

**Comment by Remscar** [comment]
I've actually played more around with my method of rendering in another scene. It seems like the strange text rendering can be improved (but not fixed) with increasing the scale of the world panel. But it still needs some antialiasing.

![image](https://user-images.githubusercontent.com/3459787/211956654-50c679db-0bfd-4b76-9528-742f5f384405.png)

**Comment by xezno** [comment]
I think this was addressed when we added the rendering properties to world panels
![Image](https://github.com/user-attachments/assets/93e4a26f-ff6d-44eb-8209-7d442d9a8171)
