### ISSUE TITLE
Multiple classes in Add.Label(text, class)

### ISSUE THREAD

**Issue by MenschlichTv** [Facepunch/sbox-issues#278]
**What can't you do?**
Using multiple classes within the string argument 'class'.

**How would you like it to work?**
```
// cs
var deaths = Add.Label( "Deaths", "content__death column" );

// scss
.content__death {
   font-size: 14px;
}
  
.column {
   flex-direction: column;
}
```

**What have you tried?**
Setting the flex-direction of 'column' to `!important`

**Comment by PatrickRatzow** [comment]
You can already do this.
```cs
_body.Add.Label( "Testing", "text-white text-lg" );
```
Looking at it in an inspector reveals it has both the expected classes
![:/](https://i.imgur.com/GkwdXhT.png)
