### ISSUE TITLE
ViewOffset of internal class ModelEntity Does not actually change the offset

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#279]
**Describe the bug**
ViewOffset in internal class ModelEntity does not actually change the Offset of the model, but keeps the values?

**To Reproduce**
Set the ViewOffset property in the constructor or anywhere on client and it wont update, It will store its values though.

**Expected behavior**
Changes the offset of the Model

**Screenshots**

(In the context of a Viewmodel)
Top left shows what the offset is meant to be (Did using `Log.Info(ViewOffset.ToString();`)
![image](https://user-images.githubusercontent.com/55055481/120108970-cfcf4300-c1aa-11eb-94bf-e940e8b56065.png)

How the offset is meant to look
![image](https://user-images.githubusercontent.com/55055481/120108847-3e5fd100-c1aa-11eb-98ad-4160ebd1e96d.png)

The hacky fix I did to get it to work somewhat as intended. By doing this though I got a lot of micro stutter / random lag.
` Position = camSetup.Position + (ViewOffset.x * Rotation.Left) + (ViewOffset.y * Rotation.Up) + (ViewOffset.z * Rotation.Backward);`

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Jake-NSW** [comment]
Got removed
