### ISSUE TITLE
Editor tool to generate .vtex for an image

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#2794]
### For?

S&Box

### What can't you do?

I can't directly import and use images (png/tga/etc) as particle sprites.

### How would you like it to work?

Right click a `png` file in the editor, click a "generate vtex" button, and a vtex file is created, allowing me to use it in the particle editor.

### What have you tried?

The guide on the wiki which is manual and time consuming; https://wiki.facepunch.com/sbox/Using_custom_sprites

### Additional context

Having native png support in the particle editor would also be rad.

**Comment by DoctorGurke** [comment]
It should be noted that manual vtex for particles are also used to make sprite sheets and animated textures
