### ISSUE TITLE
Whitelist System.Globalization.NumberStyles

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#280]
**What can't you do?**
```cs
int.Parse("12ef", System.Globalization.NumberStyles.HexNumber);
```
![sbox_fQOqP6uxRM](https://user-images.githubusercontent.com/6745157/120111948-810ab480-c17c-11eb-9e9b-b242d58a9e3d.png)

**Additional context**
(Yeah, I know that number parsing can be done with `Convert.ToInt32(i, base)`)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by rndtrash** [comment]
Nice, thanks!
