### ISSUE TITLE
Source Filmmaker Off-Screen 

### ISSUE THREAD

**Issue by Ghaqq** [Facepunch/sbox-issues#2818]
### Describe the bug

Basically, I was testing some features inside the tool but after it crashed (for the first time) the program opens but won't show on my screen. The only thing that I can see from it is just the setting option (to create a new section, open a recent one, increase fps etc). Even in the windows tab, it shows the program open and ready to be used, but even interacting with the window seems useless.
I've checked the Widget Debugger only to find these properties:
![Issue](https://user-images.githubusercontent.com/123336006/213946377-d373e938-f7cf-4290-bd15-fcc3ecc9cd78.jpg)

### To Reproduce

1. Make sure to fix the offscreen values after a crash

### Expected behavior

It should open without the program opening off-screen.

**Comment by DevulTj** [comment]
Filmmaker is gone
