### ISSUE TITLE
Default Rotation value for .decal type breaks random rotation

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#283]
**Describe the bug**
The default rotation value for decal types in the inspector, (0 - 360) seems to break the entry getting a random rotation. This is fixed by setting it to (0 - 359)

**To Reproduce**
Make a .decal using one of the default decals and leave the Rotation at default. Place decal in the world using a trace or something. Decal will always be rotated at the same angle.

**Expected behavior**
Random rotation to work with the default values.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
