### ISSUE TITLE
UI file hotloading

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#286]
**Describe the bug**
When hotloading UI it wont be refreshed until the next hotload it seems, in the video below I change the label to "Test" and save, it hotloads in game but is not updated however if I save the file again it hotloads again and it is now refreshed.

**To Reproduce**

1. Make a change to a UI file and save the file.
2. It will not update until another hotload occurs.

**Expected behavior**
Should update after the first hotload.

**Screenshots**
https://user-images.githubusercontent.com/16431607/120125293-196e5c80-c1b0-11eb-965d-446a3e083a00.mp4

**Additional context**
Using visual studio. This worked fine a few days ago.

**Comment by nodgear** [comment]
Anything changed today? Because my ui hotloading is working just fine.
I tried updating just a label value like you did and it still worked.

**Comment by louiefox** [comment]
Yeah thats the thing, it worked fine for me a week ago. Didn't change anything just came back after being away for 3 days and it was like this.

**Comment by louiefox** [comment]
Seems to just be my gamemode specifically.
