### ISSUE TITLE
Quaternion values in editor go wild

### ISSUE THREAD

**Issue by TheBoxTrot** [Facepunch/sbox-issues#2863]
### Describe the bug

the Rotation properties in the editor in both the entity inspector and in .assets seem to randomly change their value when inputting in others

### To Reproduce

create a game resource
have a Rotation  property
try and type in a value

### Expected behavior

it doesn't go funky

### Media/Files

https://user-images.githubusercontent.com/29888245/216776470-c1ed194f-8f2c-40a6-81fe-c766eade05f7.mp4

**Comment by yuberee** [comment]
Just a hunch, but I assume it's translating the Euler Angles you input to Quaternion Rotations, which is what S&box uses, and then showing you the resulting Euler Angle back. At the end of the day it's still going to be the same angle you input, kinda like how an angle with 90 Roll and and angle with 270 yaw point to the same direction.

**Comment by TheBoxTrot** [comment]
no the value it sets it to does not end up being the the right rotation

**Comment by TheBoxTrot** [comment]
https://user-images.githubusercontent.com/29888245/216805869-13891a9b-3d3f-4c19-9f96-52c88f4e5eb8.mp4

also the entities tab values do this if you view them
