### ISSUE TITLE
[Menu] Extreme FPS drop when selecting games/maps/addons

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#2866]
### Describe the bug

When selecting maps, games or addons in the menu, the framerate drops significantly. I believe this started hapenning only very recently.

Video showing the problem (take note of the FPS counter):

https://user-images.githubusercontent.com/5991682/216787409-985478f8-2a37-4336-809d-9fa34008feb3.mp4

### To Reproduce

Go to menu, select stuff, see fps drops, cry.

### Expected behavior

There should not be any FPS drops.

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by garrynewman** [comment]
What CPU do you have? how many cores?

**Comment by Gmod4phun** [comment]
Ryzen 7 5700X

**Comment by garrynewman** [comment]
The drops aren't unexpected, because by hovering and unhovering it is having to do some work.. but I'll see if I can make it less work..

**Comment by Gmod4phun** [comment]
Yeah it seems like there is something weird going on. You can even try scrolling the map list, then move your mouse in and out of it and it will just get really choppy.

**Comment by Gmod4phun** [comment]
Don't believe this is happening anymore as the whole UI has been reworked since this issue has been made. If it reoccurs I will open another one.
