### ISSUE TITLE
Model Doc breaking Client Input when a controller is plugged in

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2870]
### Describe the bug

Recently I've been getting a very strange issue where opening model doc seems to be interfering with my client input:
[Video of the Bug](https://giant.gfycat.com/MedicalColorlessArmedcrab.mp4)

Even when I close model doc the issue remains until I restart s&box.

### To Reproduce

1. Open Ghosts of the Zone
2. Open Model Doc

### Expected behavior

Model doc should have no impact on the game.

**Comment by Fortune117** [comment]
Ok, upon investigating I've discovered this only happens when I have a controller plugged when I open model doc.

**Comment by DevulTj** [comment]
I'm gonna close this, I don't see this happening anymore with all the shit we've changed in the last 6 months.
