### ISSUE TITLE
Whitelist Quaternion and Matrix4x4

### ISSUE THREAD

**Issue by rtm516** [Facepunch/sbox-issues#288]
**What can't you do?**
Load a 3x3 matrix as a 4x4 then create a quaternion based on that

**How would you like it to work?**
Be able to use them 

**What have you tried?**
```csharp
Rotation brickRot = Quaternion.CreateFromRotationMatrix( new Matrix4x4(
	transformParts[0].ToFloat(), transformParts[1].ToFloat(), transformParts[2].ToFloat(), 1f,
	transformParts[3].ToFloat(), transformParts[4].ToFloat(), transformParts[5].ToFloat(), 1f,
	transformParts[6].ToFloat(), transformParts[7].ToFloat(), transformParts[8].ToFloat(), 1f,
	0f, 0f, 0f, 1f
) );
```
```
-1,0,0,0,1,0,0,0,-1
```

**Additional context**
You could just port the CreateFromRotationMatrix into the Rotation class and allow the Matrix4x4 class

```
System.Private.CoreLib/System.Numerics.Quaternion
System.Private.CoreLib/System.Numerics.Quaternion.*
System.Private.CoreLib/System.Numerics.Matrix4x4
System.Private.CoreLib/System.Numerics.Matrix4x4.*
```

**Comment by thegrb93** [comment]
@rtm516 quaternions are generally more expensive and I don't know anything they can do that matrices can't. I have matrix slerp code you can have if that's what you're using them for.
