### ISSUE TITLE
Clothing Tags

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#2896]
### For?

S&Box

### What can't you do?

We can't filter clothing pieces by what kind of clothes they are

### How would you like it to work?

Clothes should have tags that roughly describe what they are. For example, the police vest could be tagged as "armor", "police", "clean", "uniform"
![image](https://user-images.githubusercontent.com/39461072/218156847-38fc6957-2812-4c6f-a34c-eaba9a858dd6.png)

### What have you tried?

Currently we have to manually exclude exact file names or just not use player's custom clothes at all

### Additional context

For example, a PvP game where players can equip in-game armor would be very confusing if some players had their own cosmetic armor pieces. It would still be confusing if the game used it's own custom armor models

Another example is a roleplay game that allows citizens to use their own outfits, If a citizen is using a police outfit they'll be confused for an actual in-game police officer.

Third example: Fallout style apocalypses game. This system would let us filter to only use clothes tagged as "dirty"

**Comment by DevulTj** [comment]
I think I added this a few months ago
