### ISSUE TITLE
Whitelist more exceptions

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#29]
Missing exceptions like `IndexOutOfRangeException`, `FormatException`, etc

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Jake-Rich** [comment]
Yup fixed thanks
