### ISSUE TITLE
A way to get an animation's Root motion delta's in C#

### ISSUE THREAD

**Issue by Brassx** [Facepunch/sbox-issues#291]
**What can't you do?**
Currently, if my animation has root motion, such as an attack that lunges the model forwards, the root motion displays fine in model doc and anim graph, but if I use it in-game the model stays in one spot. There's no way that I know of right now to get this info from animgraph.  

![image](https://user-images.githubusercontent.com/6100996/120225936-c254a000-c220-11eb-9e45-93453aac6555.png)
My animation graph, showing the root motion:

https://user-images.githubusercontent.com/6100996/120226146-31ca8f80-c221-11eb-9bc7-99a9c201bc04.mp4

What it looks like in game without being able to use the root motion delta's with my move helper. Please note, I'm not actually trying to make this a player, but I used it as a quick example. I'm making an AI enemy with this model:

https://user-images.githubusercontent.com/6100996/120226153-34c58000-c221-11eb-8884-2b1b82d1aead.mp4

I need this so I can add those delta's to my move helper so it moves with the animation (and has collisions intact).
**How would you like it to work?**
Pretty much just like gmod's GetSequenceMovement.  Returns a delta position and rotation that we can translate to world coordinates to add to our movement code so motion can sync up with animations, and have collisions intact. 

**What have you tried?**
I've tried to find any info on where to get this data, but haven't been able to. I checked to see if animgraph had support to encode it into a parameter, that I could get on the C# side, but no luck.

**Additional context**
If there's a way to do this already and I missed it, I apologize. I asked around and no one else knew anything. Still getting the hang of everything.

**Comment by nytemart** [comment]
I am a long time S&Box master god creator and I too have been having this issue for several decades now. I am tremendously sad as my frogs just won't fucking move. If only some strong masculine developer such as Garry could implement some functionality which would allow my adorable froggies to move. 
Best Regards, Billy

**Comment by aylaylay** [comment]
I've added AnimEntity.RootMotion, see if you can make use of that value
