### ISSUE TITLE
GameResource Inspector "Reset to Default" option for properties

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2915]
### For?

S&Box

### What can't you do?

I can't reset a game resource property to its code-defined default via editing it from the inspector.

### How would you like it to work?

Like in most other tools, rightclick the property and click "Reset to Default".

### What have you tried?

Even deleting the entry from the text file manually and re-opening it doesn't seem to default properties.

### Additional context

![sbox-dev_ShL9ZCQTNA](https://user-images.githubusercontent.com/12602100/219159692-fbc110e7-19c9-4ea8-b322-ac2869511599.png)
![sbox-dev_Exbof41JkM](https://user-images.githubusercontent.com/12602100/219159711-31a8235d-723b-47c1-8b60-35e39224c926.png)

**Comment by badandbest** [comment]
This issue is still relevant after the switch to ControlWidget.

**Comment by DevulTj** [comment]
this has been added
