### ISSUE TITLE
Browse more than 30 maps

### ISSUE THREAD

**Issue by ImWill0w0** [Facepunch/sbox-issues#292]
**What can't you do?**
Browse everyone's released maps.

**How would you like it to work?**
idk just a longer list or infinite scroll pls

**What have you tried?**
using map in the console but it gets a bit annoying and i don't think that's optimal

**Additional context**
when you start up a game it only shows a set amount of maps, any new maps won't show up

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
