### ISSUE TITLE
OnVoicePlayed is not being triggered with voice_loopback 0

### ISSUE THREAD

**Issue by kaiaverkvist** [Facepunch/sbox-issues#293]
OnVoicePlayed is not being triggered with voice_loopback 0

**To Reproduce**

1. voice_loopback 1
2. +iv_voice
3. Voice list entry shows up
4. -iv_voice
5. voice_loopback 0
6. +iv_voice
7. No voice list entry shows up

**Comment by rtm516** [comment]
Likely that `OnVoicePlayed` isn't called on the client that sends it and probably only gets called on clients.

**Comment by aylaylay** [comment]
This is the point of the convar
