### ISSUE TITLE
File Corruption 

### ISSUE THREAD

**Issue by Mike466-0** [Facepunch/sbox-issues#2933]
### Describe the bug

Files seem to be going completly blank and or corrupted. Started a month ago when I tried to upload a map and the files wouldnt appear. Then 3 weeks later on anohter addon I cant load it up, I then try to load into that old addon and it wont load, I fixxed those by deleting the vpks and recompiling and it worked.  Then today when I tried to load up s&box it gave me some sort of bootstrap error, so then I verifed files, some were missing and then it worked. but when I loaded in I only had 3 addons, and when I try to add others it would give me the same error. I checked the files and it seemed by client cookies went blank and all the broken addon files have nothing in it.

### To Reproduce

sbox/addons/basalt/.addon

### Expected behavior

FIles shouldn t be breaking

### Media/Files

error ive gotten every time
('0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.)

### Additional context

Windows 11, s&box is on a western digital hdd. I ran chkdsk on the drive and nothing came up and Its onyl sbox having the issues.

**Comment by Moofers** [comment]
I would do an SFC file scan and a scan for viruses too.

**Comment by MikeShaughnessy** [comment]
> 

Not the issue
