### ISSUE TITLE
Implement locking support on func_door C# entity

### ISSUE THREAD

**Issue by m4rkey** [Facepunch/sbox-issues#294]
**What can't you do?**
I am attempting to manipulate doors inside my game mode by setting them to locked and unlocking them when a player attempts to open them with a key.  However, I went and looked into the C# entity FuncDoor and it does not seem to have locking support besides the "Start Locked" spawn flag.

**How would you like it to work?**
I expect the func_door entity to have this functionality and be able to override whether or not a door is locked, and If it is locked It should prevent itself from opening. 

**What have you tried?**
I have created my own door entity, But I believe this is unnecessary.

**Comment by robotboy655** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.

If it is fixed feel free to close the issue yourself.

**Comment by m4rkey** [comment]
Hi there, Thank you for the quick response on the request.

Testing the Hammer inputs, It seems to work fine and as intended. I can Unlock/Lock them.

However, when attempting to lock the door via C# you can not access the Locked boolean as its not public. Unless there is way of calling the Input methods Lock/Unlock that you added from C# that I am currently unaware of.

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by m4rkey** [comment]
Works great now thanks.
