### ISSUE TITLE
VPK Resource packing for maps

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#296]
**What can't you do?**
If a map has a large amount of assets there is no easy way to filter through assets and put them into the map. I have a map with about 40 custom models and materials but also other assets currently not being used, I would have to look up the "References or Dependencies on other assets" which shows a list of assets being used in the map. (It doesn't show the materials used on models or vtex either)

**How would you like it to work?**
It would be nice having a .bat or program of some sort that packs/ moves the assets being used into the map into a folder or the vpk it self.

**What have you tried?**
Doing it manually, locating each file and copying them into a new folder structure. This does not work.

**Additional context**
VRF has the ability to show which files are being used inside the map. https://github.com/SteamDatabase/ValveResourceFormat/

**Comment by garrynewman** [comment]
Yeah this would be nice, maybe as part of the map build.

**Comment by DoctorGurke** [comment]
Yea maybe as an extra tickbox next to Vis/Nav that's just "Pack used assets" or something

**Comment by Geeknerd1337** [comment]
@garrynewman Over the weekend I decided to try my hand at creating an asset packer for our maps as we plan on releasing a gamemode in about a week. 

![image](https://user-images.githubusercontent.com/15205856/123655738-e0e49180-d7f4-11eb-9f9f-51cdfba28af6.png)

This s&box asset packer requires that you have all the compiled files present in your map in a folder, and that the compiled VPK is in the same location as your vmap. This program will perform various operations to extract the vmdl_c, vmat_c, and vtex_c files and paths from the vmap file, then copy all the corresponding asset files to a temporary folder in the directory. The program then uses vpk.exe to unpack the currently compiled vpk into the folder containing all the compiled assets. It then uses vpk.exe to re-pack that folder into a complete VPK containing all the assets.

This effectively solves our above issue and we'll likely be releasing the program for everyone here in a few days. An option within hammer would still be nice though.

**Comment by Geeknerd1337** [comment]
Also want to note @DoctorGurke helped me get this up and running as well.
