### ISSUE TITLE
RPCs not being called even when they are from the Server.

### ISSUE THREAD

**Issue by AncientEntity** [Facepunch/sbox-issues#297]
**Describe the bug**
An RPC is not being called while indeed being the server.
https://sbox.facepunch.com/dev/ryan/minigameparty/
https://github.com/AncientEntity/minigameparty-sbox
**To Reproduce**
In the minigame party gamemode, type "forceround 4" in the console and the minigame Hardcore Parkour will start. Noclip over to the opposite red boxes, it should end the gamemode, it is suppose to run an RPC in OnKilled as it kills the player when they win and makes them noclip. Also added a Test(); RPC to where it is suppose to occur (HarcoreParkourEventEntity.WhileEvent) it also doesn't run.
The public version on the S&Box selection menu should have this bug, the gamemode needs the ryan.dsminimalmap to run, which that'll load into.

**Expected behavior**
The Test(); RPC runs and says "TEST" in console, and in OnKilled an RPC called AnnouncePlacement is suppose to run, which it doesn't. It works for any other minigame.

**Additional context**
Honestly might not be a bug with S&Box, could just be me, but I've tested a bunch of stuff and can't figure it out, so I thought I would may as well make an issue just in case it is a bug with S&Box and not me being stupid.

**Comment by rtm516** [comment]
Can you link the lines with those calls? (If you don't know how just find the line on GitHub and then click the number and copy paste the URL in your URL bar)

**Comment by AncientEntity** [comment]
Alright,
Here is where Test() gets called: 
https://github.com/AncientEntity/minigameparty-sbox/blob/master/code/Minigames/HardcoreParkourEventEntity.cs#L111
Test is defined here:
https://github.com/AncientEntity/minigameparty-sbox/blob/master/code/Minigames/HardcoreParkourEventEntity.cs#L122
The RPC AnnouncePlacement which should get called here:
https://github.com/AncientEntity/minigameparty-sbox/blob/master/code/MinigamePlayer.cs#L267
Announce Placement defined here:
https://github.com/AncientEntity/minigameparty-sbox/blob/master/code/MinigamePlayer.cs#L271

The method that executes or at least should execute AnnouncePlacement is GrantPoints and gets ran in OnKilled only for the server.
https://github.com/AncientEntity/minigameparty-sbox/blob/master/code/MinigamePlayer.cs#L247
https://github.com/AncientEntity/minigameparty-sbox/blob/master/code/MinigamePlayer.cs#L202

hope this helps.
