### ISSUE TITLE
[Hammer] Ambient Color and Sky Color are black with shadows disabled

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#2972]
### Describe the bug

Working on a game that uses dynamic ambient light, because of the style we're going for, we won't be needing shadows being cast.
But disabling shadows will turn any dark area into pitch black, regardless of Sky Color or Ambient Color.

This is the settings I'll use:
![image](https://user-images.githubusercontent.com/59583743/222002702-8087cd0e-eff9-4125-b7a7-d5464f1ffeed.png)
And this is what it looks like with
![image](https://user-images.githubusercontent.com/59583743/222002773-c72a68f5-44a3-44b2-bfcf-3640127e8861.png)
![image](https://user-images.githubusercontent.com/59583743/222002808-555ff1f2-7fd0-4a54-af12-7ea57b6f15b5.png)

While this is what it looks like with 
![image](https://user-images.githubusercontent.com/59583743/222002840-4df8536f-7e29-4d83-8d48-eea69907c7cb.png)
![image](https://user-images.githubusercontent.com/59583743/222002859-6c008980-5dda-4cbb-8da5-31cd8b67d3e8.png)

Don't mind the red, as I've used it to make it easier to see the difference.
Ignoring the shadows being cast for obvious reasons, setting "Cast Shadows" to "No" is only going to use the sun's color, which looks ugly unless that's the style you're going for, which should still be an option.

### To Reproduce

1. Open any Hammer Map
2. Set the light_environment to not use baked light
3. Set "Cast Shadows" to "No"
4. Mess around with Sky Color, Sky Intensity, and Ambient Color
5. Set "Cast Shadows" to "Yes" to see differences

### Expected behavior

Instead of dark areas being pitch black, it should use the Ambient Color like it normally would.

### Additional context

We're going with a retro style in a forest, so not only does disabling shadows boost FPS, it also makes sense for a PSX-style game.
Unfortunately right now it's either pitch black or full bright.

**Comment by WheatleyMF** [comment]
Can confirm this is still happening at the current moment. All dark spots and shadowed areas appear pitch black regardless of any option as long as you have shadow casting disabled, which is quite inconvenient

**Comment by yuberee** [comment]
This does not happen in scene
