### ISSUE TITLE
PhysicsBody is not net-synced

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#301]
**Describe the bug**
PhysicsBody values differ on client and server.

**To Reproduce**

1. Set `PhysicsBody.Mass` to any float
2. Set up Tick event listener which logs separately value on the client and on the server
3. See that mass value is different

Project: 
[desynced-physics-test.zip](https://github.com/Facepunch/sbox-issues/files/6592816/desynced-physics-test.zip)

**Expected behavior**
I expected PhysicsBody's properties to be the same on both sides so that prediction won't be broken

**Screenshots**
![sbox_mdBkJnL5Ju](https://user-images.githubusercontent.com/6745157/120665372-61350280-c494-11eb-8661-12e24f3216a3.png)
![devenv_WZWKuVVvoj](https://user-images.githubusercontent.com/6745157/120665395-672ae380-c494-11eb-869c-7103b529b931.png)

**Additional context**
Temporary solution: use ClientRPC to synchronize PB manually (ewww...)
```cs
		public override void Respawn()
		{
			base.Respawn(); // Player constructor rewrites MoveType, so that's why it's called first

			Controller = null;
			Animator = null;

			...

			MoveType = MoveType.Physics;
			CollisionGroup = CollisionGroup.Interactive;
			PhysicsEnabled = true;
			UsePhysicsCollision = true;

			...

			Log.Info( $"{IsServer}" );
			PhysicsBody.Mass = 1.0f;
			Log.Info( $"Server Mass: {PhysicsBody.Mass}" );
			SyncPhysics( PhysicsBody.Mass );
		}

		[ClientRpc]
		private void SyncPhysics(float mass)
		{
			PhysicsBody.Mass = mass;
			Log.Error( $"Client Mass: {PhysicsBody.Mass}" );
		}

		[Event.Tick]
		public void Tick()
		{
			if ( PhysicsBody == null )
				return;

			DebugOverlay.ScreenText( new Vector2( 0.0f, 200.0f ), IsServer ? 0 : 1, new Color( 255, 255, 0 ), $"{IsServer} | {PhysicsBody.Mass}" );
		}
```

**Comment by aylaylay** [comment]
Rubikon doesn't replicate things like this. You either have to have your own mass variable (you can probably just set it on the server because I don't think setting mass client side will have any effect) Or we'll have to handle it, which we probably will because things like sandbox mode are gonna want to know the mass clientside
