### ISSUE TITLE
Add support for filters in Physics.GetEntities* methods

### ISSUE THREAD

**Issue by yoranmandema** [Facepunch/sbox-issues#302]
**What can't you do?**

Get entities using the `Physics.GetEntities*` where results are already prefiltered on entity types. 

**How would you like it to work?**

Add `Physics.GetEntitiesInSphere<T>(Vector3 position, float radius)` where `T` specifies the class of the Entity we want to get as a result (subclasses can be included/excluded using an optional parameter perhaps?)

The same filter should be applicable to similar methods such as `Physics.GetEntitiesInBox` etc.

Maybe similar syntax as `Trace` using the builder pattern could be used as well for finer filtering control (e.g by including/excluding certain classes etc)?

By applying the filters within the API, it can hopefully utilise the engine's more optimised way of looking up entities.

**What have you tried?**

Get the result of `Physics.GetEntitiesInSphere` and manually loop through and filter results.

**Additional context**

Doing `Physics.GetEntitiesInSphere` on a prop heavy map can give you a lot of props in return that you might not be looking for. If you're only looking for player entities for example, it's a lot of wasted data.

**Comment by Jac0xb** [comment]
```
using System.Collections.Generic;
using System.Linq;
public static class PhysicsExtensions
{
	public static IEnumerable<T> GetEntitiesInsideSphere<T>( Vector3 pos, float radius ) where T : Entity
	{
		var ents = Physics.GetEntitiesInSphere( pos, radius );
		return ents.OfType<T>();
	}
}
```

**Comment by yoranmandema** [comment]
This would still return all ents in the sphere from the engine which have to be looped over. Question is whether this type of filtering could be applied down in a lower level and whether this would also speed things up.

**Comment by Jac0xb** [comment]
You're probably right.

**Comment by aylaylay** [comment]
I need to add filters but the physics query can't filter specific entity types. The function is already pretty fast so it shouldn't be an issue.

**Comment by garrynewman** [comment]
It makes sense to be able to query by collision group, but I don't think specific entity types etc make sense.
