### ISSUE TITLE
Mapping - Add func_movelinear & point_teleport

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#303]
**What can't you do?**

`func_movelinear` and `point_teleport` are both not working for now.
I wanted to use these to make a moving 3D skybox around my level.

I'm attaching two testmaps to this issue showcasing the two different entities for you to test, and some text explanations:
-> [func_movelinear & point_teleport.zip](https://github.com/Facepunch/sbox-issues/files/6592980/func_movelinear.point_teleport.zip)

func_movelinear
![image](https://user-images.githubusercontent.com/67245359/120680100-377eda00-c49a-11eb-8c51-c0002ef868f8.png)

point_teleport
![image](https://user-images.githubusercontent.com/67245359/120680191-52514e80-c49a-11eb-9ec2-a4afc1d9a005.png)

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/55

**Comment by Jac0xb** [comment]
If you want a basic working func move linear, I've made one

```
[Library( "func_movelinear" )]
public partial class FuncMoveLinear : KeyframeEntity
{

	[HammerProp( "speed" )]
	public float Speed { get; set; }

	[HammerProp("movedistance")]
	public float MoveDistance { get; set; }

	private Transform _transformOn;
	private Transform _transformOff;
	private float _keyFrameDuration;

	public override void Spawn()
	{
		base.Spawn();

		SetupPhysicsFromModel( PhysicsMotionType.Keyframed );
		this.PhysicsBody.MotionEnabled = false;


		var delta = -WorldAng.Direction * MoveDistance;
		_keyFrameDuration = delta.Length / Speed;
		_transformOff = Transform;
		_transformOn = _transformOff.Add( delta, false );

		Transmit = TransmitType.Always;
	}


	[Input]
	public void Open()
	{
		_ = KeyframeTo( _transformOn, _keyFrameDuration );
	}

	[Input]
	public void Close()
	{
		_ = KeyframeTo( _transformOff, _keyFrameDuration );
	}
}
``

**Comment by robotboy655** [comment]
Added `ent_platform` entity as a replacement for `func_movelinear`.

**Comment by KayaDLX** [comment]
Thank you for this new entity!
Closing this one as there's another main open issue for that.
