### ISSUE TITLE
Make built-in bullet impact sounds louder. It's near inaudable.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#3035]
### For?

S&Box

### What can't you do?

S&box's built-in surfaces bullet impact sounds are too quiet to hear.

https://user-images.githubusercontent.com/91832803/225875057-0358695c-f281-4927-ad79-78ac9e259f7f.mp4

### How would you like it to work?

Ideally the sounds should be louder so that it isn't completely drowned out by the weapon firing.

### What have you tried?

You can always make your own surfaces.

### Additional context

Version without firing sounds.

https://user-images.githubusercontent.com/91832803/225875228-a90b033a-6fdc-4a82-9131-d1a8266167d3.mp4

**Comment by DevulTj** [comment]
This is probably a little better now, but also shouldn't this be the case? A weapon firing is a lot louder than sounds of impact.
