### ISSUE TITLE
[ModelDoc] Import scale doesn't support decimal numbers 

### ISSUE THREAD

**Issue by TheGoret** [Facepunch/sbox-issues#304]
When adding meshes in ModelDoc, you cannot change the import scale using a decimal separator ( , or . )

**To Reproduce**

1. Create a model in ModelDoc
2. Add a new mesh
3. Try to modify the Import scale to a decimal number such as 0.5 or 0,9
4. The number goes back to normal and trying to put down a decimal point won't even work

**Expected behavior**
The import scale should accept decimal numbers as it does in Half-Life: Alyx's ModelDoc.

**Comment by bakscratch** [comment]
Are you sure? It seems to be fine for me; https://files.facepunch.com/louie/1b0311b1/ModelDoc%20__%20untitled_1%20_%202021-06-03%2023-21-27.mp4

Can you maybe show a video or something?

**Comment by TheGoret** [comment]
I'm sure, yeah. Could it be because I'm using a different keyboard layout? (AZERTY in my case)
It straight up refuse to let me place a point and acknowledge the number I write just after. 

https://i.imgur.com/k18yTzf.gif

**Comment by bakscratch** [comment]
Can you do like 1,2,3,4,5 ect? Yeah I think it has to be "." that is probably your problem.

**Comment by TheGoret** [comment]
I booted up Half-Life Alyx to try it out and yeah, it doesn't accept decimals comas, my bad.
Although, the "." works in HL:A's ModelDoc but not in S&Box's.
https://i.imgur.com/RwfRCqP.gif

**Comment by KayaDLX** [comment]
I had the same issue, found a workaround for now in #149 (last comment).
This will work across all tools 👍

**Comment by TheGoret** [comment]
I can confirm the workaround works, thanks! 
https://i.imgur.com/9rDT1YN.gif

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/149
