### ISSUE TITLE
Add support for prop_dynamic

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#305]
**What can't you do?**

Use prop_dynamic in my maps and hook it up to IO or parent it to C# entities.

**How would you like it to work?**

The ability to spawn prop_dynamic (which is always static) and run animations on them.

**What have you tried?**

I get really weird behavior when I made my own. Sometimes the entity never appears for the client, sometimes it has the wrong rotations. The animations always restart when out of POV too.

```csharp
	[Library( "prop_dynamic" )]
	public partial class PropDynamic : AnimEntity, IUse
	{

		private string _model;

		[HammerProp("model")]
		public string Model { get; set; }

		[HammerProp( "DefaultAnim" )]
		public string defaultAnim { get; set; }


		private int _renderamt;
		[HammerProp( "renderamt" )]
		public int RenderAmount
		{
			get
			{
				return _renderamt;
			}
			set
			{
				_renderamt = value;
				this.RenderAlpha = ((float)value) / 255f;
				this.RenderDirty();
			}
		}

		public override void Spawn()
		{
			this.SetModel( Model );
			this.SetupPhysicsFromModel( PhysicsMotionType.Static );

			base.Spawn();
		}

		[Input]
		public void SetAnimation(string sequence)
		{
			this.Sequence = sequence;
		}

		[Input]
		public async void Alpha(int alpha)
		{
			this.RenderAmount = (int)alpha;
		}

		public bool OnUse( Entity user )
		{
			FireOutput( "OnUse", user, this );
			return false;
		}

		public bool IsUsable( Entity user )
		{
			return true;
		}
	}
```

**Additional context**

This is the second most important prop entity for mappers IMO, it should be supported or something like it.

**Comment by Jac0xb** [comment]
The biggest problem is that animations, and rotation break when a model has a physics shape parented to a bone.

**Comment by robotboy655** [comment]
> The biggest problem is that animations, and rotation break when a model has a physics shape parented to a bone.

Do we have a model in the base game that does this? If not, can you provide one?

**Comment by Jac0xb** [comment]
[physics_joint_with_sequences_model.zip](https://github.com/Facepunch/sbox-issues/files/6865943/physics_joint_with_sequences_model.zip)

**Comment by KayaDLX** [comment]
This entity should really be fully implemented, it's been over a year now

**Comment by gvarados1** [comment]
Any updates on this? It's a pretty simile entity that is _extremely_ useful for maps and would only take a few minutes to make.

**Comment by robotboy655** [comment]
Useful how? Just playing animations?

**Comment by gvarados1** [comment]
Yes. we can't have basic animated models in maps.
I would love to be able to just have a simple AnimatedEntity that I can put in maps and send a SetAnimParameter input.

It would also be lovely to be able to set raw animations, bypassing the laggy animgraph like you can with the default source1/2 entity as well as a default animation.

Prop_dynamic doesn't even have to be it's own entity. The only major difference between prop_dynamic and prop_physics is dynamic doesn't have physics enabled. It would be totally fine if they were merged into a generic "prop" with a simple bool to toggle physics

**Comment by Redhacker1** [comment]
That is the main draw/purpose of it for people last I checked. I don't think there is any inbuilt solution for setting a model that can play animations through IO independently. The end user or gamemode probably should not have to effectively recreate it to play animations in such a manner IMHO. I also understand why you guys are on the fence, but, ideally a decision should at the very least be made as to whether it makes the cut, and if not removed, that way no one gets confused as to why prop_dynamic does not work. There should not be an entity sitting around in engine using the incompatible C++ IO system.

**Comment by bakscratch** [comment]
It's not just for playing animations, It also allows for models skins to be changed at run time and materials as well as changing the scale of props at run time.

**Comment by KayaDLX** [comment]
Yeah, skins, bodygroups, animations, toggle drawing the model, scaling, all of that.

**Comment by robotboy655** [comment]
prop_physics already has `Static` property that disables physics simulation. 

I have added a few new inputs to prop_physics that should fill your aforementioned needs (save for animations, that will have to be a separate entity), let me know of any feedback.

**Comment by gvarados1** [comment]
Thank you! This should just replace the old prop_dynamic so it doesn't break every map & all the default prefabs.

**Comment by robotboy655** [comment]
Renaming it was done on purpose. For one, the new name better represents what the entity meant to be used for, secondly, it further distances people from expecting same entities doing same thing as Source 1.

**Comment by gvarados1** [comment]
This is missing "Disable Collisions"

**Comment by gvarados1** [comment]
Thank you! The hammer physics preview doesn't actually update though.

In this pic the models have their collisions turned off but hammer thinks they're still on. This messes up preview and phys sim
![image](https://user-images.githubusercontent.com/39461072/191330115-673a8269-7067-4f81-8c5c-f424e4bedbcc.png)

**Comment by gvarados1** [comment]
Also I noticed an inconsistency between this and func_brush.
func_brush's option says "Solid" and prop_animated says "Collisions"
"Solid" on func_brush doesn't update the hammer physics either.

**Comment by robotboy655** [comment]
I have fixed the Collisions property not having an effect on Hammer, as for the inconsistency, you are right, I will rename it for the time being in Hammer.
