### ISSUE TITLE
ShowIf/HideIf Attributes do not work on Struct Properties in Game Resources

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#3052]
### Describe the bug

I have two properties on a game resource:
```CS
	public bool ApplyStatModifier { get; set; }

	[HideIf(nameof(ApplyStatModifier), false)]
	public StatModifier StatModifier { get; set; }
```
`StatModifier` is a struct, and is not hidden regardless of the value of `ApplyStatModifier`. 

`[ShowIf]` has the same problem.

### To Reproduce

1. Create a game resource
2. Mark a struct with HideIf/ShowIf
3. It does not hide the property.

### Expected behavior

Structs are hidden the same as other properties

**Comment by DevulTj** [comment]
I believe this is linked to https://github.com/sboxgame/issues/issues/3013#issuecomment-1469443626 and when we tackle this, we'll fix everything in one fell swoop.
