### ISSUE TITLE
Camera can be jittery when moving around

### ISSUE THREAD

**Issue by brecert** [Facepunch/sbox-issues#3058]
### Describe the bug

When playing on some gamemodes the camera becomes rather jittery.
The problem is worse when on certain maps than others.
Setting `fps_max` to a value other than 0 can make the problem worse.

### To Reproduce

Set `fps_max` to `60`
Try Terry's Alright Skater on the map Skate Park, or Minigolf on the map Minigolf Green.
Move around and notice the jitter.

### Expected behavior

The camera movements should be smooth and without jitter or stutter.

### Media/Files

https://youtu.be/ghlENRPkU94
https://youtu.be/BGfslFj_Lxk

**Comment by sugmagaming** [comment]
can confirm i had the same issue in alright skater and gr&prix

**Comment by chrisspieler** [comment]
I've noticed this too in the editor when working on my own projects. When the stutter happens, it makes me doubt whether my movement and camera code are accurate. Right now, I have to choose between heat + coil whine or seeing problems that don't actually exist.
