### ISSUE TITLE
Events not firing for LibraryClass

### ISSUE THREAD

**Issue by Ceveos** [Facepunch/sbox-issues#307]
**Describe the bug**
I have a simple GameMode that does 2 things:
1. Uses `Library.GetAll<Foo>` to find libraries that I want to load
2. On each library that I find, I perform a `Library.Create<Foo>(obj)` and add it to a list

Each library derives from `LibraryClass` and has a Library annotation at the top. Additionally, there are `[Event]` methods within the library. Now when I fire an event from the main GameMode, none of my library classes can see it.

**To Reproduce**
Using my repo to help explain the problem: https://github.com/Ceveos/minimal-extended 

1. [Game.cs](https://github.com/Ceveos/minimal-extended/blob/main/code/Game.cs) will fire some desired events using the `AddonEvent` helper class
2. My [AddonEvent.cs](https://github.com/Ceveos/minimal-extended/blob/main/code/AddonEvent.cs) file will load all addons using `Library.GetAll<Foo>`, then fire all events using the standard `Event.Run()`
3. The events from the [Save.cs](https://github.com/Ceveos/minimal-extended/blob/main/code/addons/save/Save.cs) file does not trigger as expected

**Expected behavior**
When firing an event, all the library classes that are listening for the event should trigger

**Screenshots**
![image](https://user-images.githubusercontent.com/292875/120883046-dfc29a80-c58f-11eb-8e0a-1e445fa116dd.png)

**Additional context**

I've tried defining my library classes in many different ways with no success. It seems that if I have to search for my classes in runtime, Events do not get triggered on them. However, functions work fine on them.

**Comment by Ceveos** [comment]
The intent with this code is to have a simple gamemode that bears no logic. Then I can have an "addons" folder that will add functionality to my game. This will make it easy to reuse code between projects.

**Comment by garrynewman** [comment]
You need to register and deregister your class for events manually in this case. With entities and panels we manage the lifetime so this is done for you.

Event.Register I think the method is.

**Comment by Ceveos** [comment]
Wow that was an insanely easy fix for this solution. Thanks Garry, I'll close this bug
