### ISSUE TITLE
Clientside traces not hitting clientside entities

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#308]
**Describe the bug**
Clientside traces do not hit client only entities, is there a way to make this possible?

**To Reproduce**

1. Create a clientside model
2. Run a trace at the model and it wont hit

**Expected behavior**
The trace should hit the clientside entitiy

**Screenshots**
![image](https://user-images.githubusercontent.com/16431607/120892047-19cd8400-c604-11eb-958d-262f6a1a6ce1.png)

**Comment by garrynewman** [comment]
Can you show your code for creating a clientside model and code for tracing?

**Comment by louiefox** [comment]
`	[ClientRpc]
	public void CreateClientModel()
	{
		LootItem item = LootItem.Items[ItemID];

		ClientModel = new ModelEntity();
		ClientModel.Parent = this;
		ClientModel.Position = Position;
		ClientModel.SetModel( item.Model );

		ClientModel.GlowState = GlowStates.GlowStateOn;
		ClientModel.GlowDistanceStart = 0;
		ClientModel.GlowDistanceEnd = 1000;
		ClientModel.GlowColor = new Color( 1.0f, 1.0f, 1.0f );
		ClientModel.GlowActive = true;
	}

    [ClientCmd( "test_loottrace" )]
    public static void TestLootTrace()
    {
        if ( Local.Pawn.Camera is not BRThirdPersonCamera cam ) return;

        var tr = Trace.Ray( cam.Pos, cam.Pos + cam.Rot.Forward * 2500 )
            .Ignore( Local.Pawn )
            .Run();

        DebugOverlay.Line( tr.StartPos, tr.EndPos, 10, true );
    }`

**Comment by ZenBre4ker** [comment]
Maybe I can help. Got a similar problem and wgile debugging I saw, that the server still handles the physics collider even if transmittype.never is used.
Heres a short video demonstrating it with clphys debugging turned on:
https://gyazo.com/7a48d53cf618569bf3c7e26c37b68b98

And here's my issue for the rts gamemode where I posted my ugly fix by sertings the physicsbody position directly.
https://github.com/Facepunch/sbox-rts/issues/107

**Comment by louiefox** [comment]
How long are we talking?

**Comment by ZenBre4ker** [comment]
I guess it depends on the map size. In my gyazo video you can see, that it's under 2 seconds. And the the thread shows you, that the collider lags when moving.

**Comment by ZenBre4ker** [comment]
Did you try the clphys debug view? You can activate it via F1.

**Comment by ZenBre4ker** [comment]
So my bug is something else, but I think I found your issue.
Assign your model a physicscollider and it should work.
So either:
`ClientModel.SetupPhysicsFromModel( PhysicsMotionType.Keyframed );`
or
`ClientModel.UsePhysicsCollision = true);`

**Comment by ZenBre4ker** [comment]
Here if you want to fiddle with the code yourself:
https://github.com/ZenBre4ker/sandbox/commit/0edc8f31b8bcf6c5e49b9650cd18353c45044aa9

**Comment by ZenBre4ker** [comment]
@louiefox is that still relevant or did you fix it and can be closed?

**Comment by louiefox** [comment]
Sorry, I haven't been doing much in s&box lately, if it works for you then its probably fine. I don't remember running setting up physics/collisions for the clientside model so thats probably it. Thanks btw.
