### ISSUE TITLE
info_overlay can't be clicked in hammer

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#309]
**Describe the bug**
Can't click info_overlay entities, have to use the lasso on them.

**To Reproduce**

1. Place info_overlay entity on surface
2. Try to click it with mouse
3. It selects the object behind it

**Expected behavior**
To select the info_overlay entity

**Screenshots**
![1622978333389](https://user-images.githubusercontent.com/1517911/120922499-c32a7d80-c6c9-11eb-9613-01343a86f31c.png)

**Comment by DoctorGurke** [comment]
Are you in object or mesh selection mode

**Comment by MrBrax** [comment]
Object selection mode. Pretty sure either doesn't work?

**Comment by justynboi** [comment]
The selection hitbox for the info_overlay is VERY tiny. You have to use box select or lasso to select the info_overlay.

**Comment by aylaylay** [comment]
You could be able to click the box of info_overlay now. Let me know if that causes any issues though because I'm not sure why they initially made it not have any bounds.

**Comment by aylaylay** [comment]
Ah shit I know why, when you place the overlay, it will be offset by the bounds. I'll try and fix that but keep the selection bounds

**Comment by aylaylay** [comment]
Should be all good now, also changed the default material it uses so it's not and error

**Comment by MrBrax** [comment]
Yep, works!
