### ISSUE TITLE
GPU Baking

### ISSUE THREAD

**Issue by PatrickJnr** [Facepunch/sbox-issues#31]
It'd be nice to have GPU Baking for Hammer like Layla teased on twitter.

![image](https://user-images.githubusercontent.com/3267523/116137425-71a2d200-a6cb-11eb-83fb-3207209be7e5.png)

**Comment by QuackCocaine** [comment]
Oh god yes so I can see how well my 3060ti compiles compared to my cpu

**Comment by pBinarySoul** [comment]
This function should also be used to compile visibility.

**Comment by PixelQubed** [comment]
Yeah this is important imo. Large maps compile too slowley on the CPU. I would like to see what performance is like on the GPU.

**Comment by Redhacker1** [comment]
Why was this closed?
