### ISSUE TITLE
Add an option to maintain player velocity under trigger_teleport

### ISSUE THREAD

**Issue by NSGOmega** [Facepunch/sbox-issues#311]
**What can't you do?**
Maintain a player's velocity when entering trigger_teleports. Would be useful for surf/bhop or other map creators who don't want players to lose their speed when teleporting. 

**How would you like it to work?**
Possibly add a tick-box under the trigger_teleport for the option.
![image](https://user-images.githubusercontent.com/70560728/120934207-616b1300-c6cb-11eb-8be4-10c8709fb672.png)

**What have you tried?**
N/A

**Additional context**

**Comment by robotboy655** [comment]
This should be added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.

If it is fixed feel free to close the issue yourself.

**Comment by NSGOmega** [comment]
Working nicely, thanks!
