### ISSUE TITLE
Publisher UX should be improved to not overwrite data saved on website, but not in addon

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#3113]
### Describe the bug

During the package publish/upload flow, the Package Meta screen has options to fill out title, summary, description, tags, and visibility. The page also says _you can also edit these on the website afterwards_.

If you leave any of the fields empty, your addon is not updated, as expected. When you edit on the website afterwards, there is now a discrepancy between these fields the next time you try to upload. If you fail to copy your information from the website into the uploader for the next publish, the existing meta on the backend gets overwritten with the empty fields.

I propose that:
1) there should be input fields available for this meta information in the project settings, so you can save this information for your project outside of the publisher
2) the uploader description box is made into a textarea into of a textinput field (multi-line) - a preview for markdown would be nice too
3) there should be a better UX flow when uploading empty information when there is populated meta information on the backend - whether the .addon or the backend should be the authority depends on how 1 and 2 are handled

### To Reproduce

1. Upload a project to the backend with no description or tags
2. Edit the information on the backend
3. Upload the project again
4. See the package meta fields get overwritten on the backend

### Expected behavior

The meta fields are not overwritten, or a more logical and user-friendly experience is presented.

**Comment by NotGaylien** [comment]
To add onto this.
i have a bunch of models uploaded.
i lost the .meta file for them models at some point idk how.

i have to find out what the model was uploaded as, then refill in the correct ident, and details for that model.
is it possible to have a way to "relink" your model to existing assets idents and their metadata. along with this sync.

if its not possible to do automatically then is it possible to do something like this?

currently like this
![image](https://github.com/sboxgame/issues/assets/82092361/a7a1eea6-8d02-4f8e-b706-f3ea566c424e)

this is a bit overkill.
but having a nice way to select force fetch metadata of uploaded assets along with also fetching them, incase you ever do lose your models .meta file
![image](https://github.com/sboxgame/issues/assets/82092361/1c15b556-86cf-428b-a8b9-ab50aa74a17e)

ofc it its possible to just do it automatically and not have to do this then that would be all good, just having a nice way to re-link that asset up is super useful.
