### ISSUE TITLE
NetworkComponent properties don't work right with constructors

### ISSUE THREAD

**Issue by m0uka** [Facepunch/sbox-issues#312]
**Describe the bug**

If you create a constructor that sets any property with a Net attribute on a NetworkComponent class, a NRE occurs.
Errors vary for every type.

This works:
```c#
NetworkingTest = new NetworkingTest();
NetworkingTest.Test = "Test";
```

This doesn't:
```c#
NetworkingTest = new NetworkingTest("Test");
```

**To Reproduce**

1. Create a class deriving from NetworkComponent with a networked property and a constructor that assigns it
```c#
public partial class NetworkingTest : NetworkComponent
{
	[Net]
	public string Test { get; set; }
		
	public NetworkingTest( string test )
	{
		Test = test;
	}
}
```

2. Add the class to an entity
3. Create a new instance of the class using the constructor with the string serverside
4. An error occurs

**Expected behavior**

No errors should occur

**Screenshots**

![image](https://user-images.githubusercontent.com/31182042/120936367-b298f800-c707-11eb-9bb7-1d31956a64f7.png)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by m0uka** [comment]
![image](https://user-images.githubusercontent.com/31182042/121771966-dc707580-cb72-11eb-8b8f-1e1272434cc6.png)

Still occurs, even tested it on a clean gamemode

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by m0uka** [comment]
Now no errors get thrown when trying to do this, but the properties are just null (or default).

Also when there isn't a parameterless constructor defined, this gets thrown (not sure if this is intentional):
![image](https://user-images.githubusercontent.com/31182042/123659744-4d7e8100-d833-11eb-8233-6c78583dc6ea.png)
