### ISSUE TITLE
Client RPCs not being ran on class based of BaseWeapon

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#313]
**Describe the bug**
Client RPCs not being ran on class based off BaseWeapon. 

**To Reproduce**
1. Create a client RPC
2. Attempt to run it anywhere in class based off BaseWeapon
3. It wont work

**Expected behavior**
It should run the client RPC

**Screenshots**

Client RPC and server cmd test code
![image](https://user-images.githubusercontent.com/16431607/120945435-dc1a4980-c730-11eb-99f8-ed4e2302458d.png)

Weapon reload code (also tried in other methods and got the same results)
![image](https://user-images.githubusercontent.com/16431607/120945439-df153a00-c730-11eb-9ee1-3ff2522027a4.png)

Testing code:
![image](https://user-images.githubusercontent.com/16431607/120945387-c573f280-c730-11eb-9b21-bab3b4a51764.png)

**Additional Information**
I also tried printing the result of GetClientOwner and ply in both the weapon and server cmd and all results were the same.
Weapon code: https://github.com/louiefox/sbox-bots/blob/main/code/Weapons/BRWeapon.cs

**Comment by louiefox** [comment]
![image](https://user-images.githubusercontent.com/16431607/120946227-acb90c00-c733-11eb-964a-b71ac68a8b40.png)
Can't seem to get it to be ran in player code either, seems as if it cant be ran in entity code?

**Comment by louiefox** [comment]
Turning off prediction beforehand seems to solve the issues.

**Comment by garrynewman** [comment]
If you remove the IsServer it'll work.

**Comment by louiefox** [comment]
That would just be in the examples above, in my actual code I need to be able to call the client RPC from the server.

**Comment by garrynewman** [comment]
It doesn't replay received RPCs on the client like this because it assumes the client already ran it during prediction. If it didn't do this you'd end up hearing a gunshot from your prediction and a gun shot from the server run etc.

If you're only running something on the server you need to turn prediction off, that's what it's for.

**Comment by louiefox** [comment]
Ah that makes sense my bad, thanks for the quick reply.
