### ISSUE TITLE
`Graphics.RenderToTexture` does not respect camera first person viewer

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#3147]
### Describe the bug

When using `Graphics.RenderToTexture` with a scene camera, the `FirstPersonViewer` property on the camera is not used, instead the `FirstPersonViewer` from the main game camera is used.

### To Reproduce

```
var camera = new SceneCamera();
camera.World = Game.SceneWorld;
camera.Position = Position + Vector3.Up * 60 + Rotation.Forward * 20;
camera.Rotation = Rotation.From(new Angles(0, 0, 0));
camera.FieldOfView = 120;
camera.ZFar = 10000;
camera.FirstPersonViewer = null;

Graphics.RenderToTexture(camera, someTexture);
```

### Expected behavior

The first person entity from the scene camera is used. Thus allowing you to render the first person viewer.

### Media/Files

In this video you can see when the third person camera is being used, the player can see themselves. When the first person camera is used, it cannot be used.

https://drive.google.com/uc?id=1CCfN43qacgfED9Ezj5bQXhj2dYul0Zg8

**Comment by anthonysharpy** [comment]
i don't suppose you happened to find a good workaround for this?

**Comment by handsomematt** [comment]
You should be able to do what you want with Camera.ExcludeTags. Camera.FirstPersonViewer is kinda hacky

**Comment by anthonysharpy** [comment]
@handsomematt thing is that when Camera.FirstPersonViewer is set it stops the player from showing up in every camera, and it seems there's no way to turn it off (without affecting the main camera), so to workaround that i'm kind of having to:

-> add a tag to every player containing their steam id (to make it more difficult tags can't have numbers in so i have to convert their steam id to be letters instead). 
-> rip out all usage of Camera.FirstPersonViewer and set the steam id tag on Camera.Main.ExcludeTags instead
-> set the steam id tag on the player and all their clothing

which also feels quite hacky. unless there's a better way?
