### ISSUE TITLE
SCSS :not pseudo class

### ISSUE THREAD

**Issue by zeo** [Facepunch/sbox-issues#315]
**What can't you do?**
Use the common pseudo class `:not` 

**How would you like it to work?**
When used with a CSS selector it would target the elements that **don't** match the selector inside :not

_Example:_
```scss
.discussion:not(.locked) {
    color: white;
}
```
Will select elements containing the discussion class but do not contain the locked class.

**What have you tried?**
N/A

**Additional context**
[Mozilla Docs :not](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)

**Comment by Westsaid** [comment]
I think pseudo classes are a pretty neat thing in general. For example the [:nth-child](https://developer.mozilla.org/de/docs/Web/CSS/:nth-child) can be in pretty helpful if you want to give a specific child (like the 3. child) or even better, each second element a special property.  We used this in the web mockup of our scoreboard to color the background:

![image](https://user-images.githubusercontent.com/58175915/121380638-53c0c200-c945-11eb-82aa-fc2c44580160.png)

Of course there are ways to achieve this like using css classes like .even & .odd and some c# logic which rerenders the scoreboard everytime there is a change in the order of the players but with this pseudo selector this would be much easier.

**Comment by garrynewman** [comment]
This should work now. 

I think it's revealing some issues with the selection ordering of the style blocks though.. since I imagine :not always gets a priority in .css, regardless of the order it's declared in the file. I'll need to look at that since I think there's some other fundamental issues there.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by zeo** [comment]
Yep looks like it's added and working as expected. Thanks!
