### ISSUE TITLE
[Hammer] Entity IO parameters

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#317]
**What can't you do?**

Use parameter overrides in entity IO.

<img src="https://user-images.githubusercontent.com/5273873/121084429-3f928e80-c7a6-11eb-9fef-2c409703391e.png" width="512">

```csharp
[Input]
public void SetAnimation(string sequence)
{
	this.Sequence = sequence;
}
```

![image](https://user-images.githubusercontent.com/5273873/121084268-1114b380-c7a6-11eb-907f-661704632ada.png)

**How would you like it to work?**

Being able to set parameters for IO output triggers so we can pass values to Input methods. It should try to cast it to the specified parameter type in the method or throw a detailed exception on what Input method failed and what the value was.

**What have you tried?**

Have to make my own input methods that are non-generic like SetAnimationDown.

**Comment by robotboy655** [comment]
This should be working as of July 9th.
