### ISSUE TITLE
polygon tool broken

### ISSUE THREAD

**Issue by ImWill0w0** [Facepunch/sbox-issues#318]
**Describe the bug**
upon selecting the polygon tool and using it, crashes the tools and steam along with it

**To Reproduce**

use the polygon tool, slowly

**Expected behavior**
to draw without crashing

https://user-images.githubusercontent.com/28235017/121110327-fb14ec00-c7c1-11eb-99c9-d2d1d0387445.mp4

**Comment by aylaylay** [comment]
Unable to reproduce

**Comment by ImWill0w0** [comment]
> Unable to reproduce

odd, I verified the integrity and nothing was missing, any thoughts on what could be causing this on my end?
