### ISSUE TITLE
Pie menu for Hammer selection modes

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#3211]
### For?

Hammer

### What can't you do?

Currently in Hammer the only way to change selection modes is to either click on the dedicated buttons or use 1 2 3 4 5 8 (which doesn't fully work on non-qwerty keyboards due to regional accents).

### How would you like it to work?

I'd like it to work like in Maya/Blender, Maya does it by continously right clicking on the object/viewport to switch between selection modes as shown in this video:

https://user-images.githubusercontent.com/67245359/235145676-a800d29c-b48a-42b5-b721-1b50a580f8f3.mp4

I think this would be really handy for people that are used to this workflow.

**Comment by Jake-NSW** [comment]
This would be super cool! and I definitely see it potentially being nice to have with the new gizmos stuff 😄

**Comment by QuackCocaine** [comment]
oh this would be dope for the debug render modes in hammer too

**Comment by Andiq** [comment]
Id love this

**Comment by handsomematt** [comment]
I think I'd rather just expose what you'd need to make this an addon
