### ISSUE TITLE
[Animgraph] Aim Matrix increments incorrectly.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#3249]
### Describe the bug

The Aim Matrix is a 3x4 matrix, S&box divides the poses to fit within `-45°` and `45°`.

I have recreated how the Aim Matrix divides these poses.
![image](https://github.com/sboxgame/issues/assets/91832803/3d3a7e1d-7d9c-48bd-8801-638640817ea5)

The most glaring issues  are that:
* ![image](https://github.com/sboxgame/issues/assets/91832803/c45972ae-7f17-4bba-aed3-8bc60578b95c) is not at 0° pitch.
* ![Straight Up](https://github.com/sboxgame/issues/assets/91832803/6bde649a-25c0-4e97-b16b-0ac3e400fb0e) is at a pitch of 45°, instead of 90°.

### To Reproduce

1. Set up an Aim Matrix node.
![image](https://github.com/sboxgame/issues/assets/91832803/cda1b682-8f20-4283-893e-fe77876b0e99)
2. Aim 45° up.

It will now play the Straight Up pose, instead of the Up Center pose. 

### Expected behavior

Aim Matrix is a 3x4 matrix. Straight Up should require a second increment like this 2DBlend example, taken from Team Fortress 2.
![image](https://github.com/sboxgame/issues/assets/91832803/71204f96-77c9-493d-8f64-c022d7a6ed7d)

### Additional context

This is a S&box specific issue. In Half Life: Alyx it works as you'd expect.

**Comment by badandbest** [comment]
Please it's been over 100 days

**Comment by badandbest** [comment]
Please it's been over 200 days

**Comment by garrynewman** [comment]
Can you explain this to me like I'm a 5 year old please. Is this in animgraph?

**Comment by badandbest** [comment]
Yes! Sorry, should have specified that more clearly.

Something about the node's math is wrong.

https://github.com/sboxgame/issues/assets/91832803/9535dc7f-733a-40a1-b9ee-8b84a62a97ce

[animgraph file.zip](https://github.com/sboxgame/issues/files/13448534/animgraph.file.zip)

I should also make clear that this is _not_ a problem with the citizen animations.

**Comment by badandbest** [comment]
1 year anniversary 🎉

A lot of the systems in s&box are being remade for scenes. Will the animgraph get the same treatment? And if so, would it even be worth keeping this issue up?

**Comment by aylaylay** [comment]
This should be working correctly now, for both 3x4 and 3x5 (Can look straight down is 3x5) @badandbest

**Comment by badandbest** [comment]
Holy shit it works

https://github.com/Facepunch/sbox-issues/assets/91832803/8c6a75ce-e5e0-4494-b26f-ae8a53a4c371
