### ISSUE TITLE
The rings around Lights bug out

### ISSUE THREAD

**Issue by Andiq** [Facepunch/sbox-issues#3250]
### Describe the bug

When you instance a light the ring around it bugs out when you move it and when you open the instance and close it it will set itself to 0 0 0. it will also stay there no matter if you restart hammer or sandbox.

### To Reproduce

1. Create a Light
2. Create an Instance with it
3. enjoy.

### Expected behavior

The ring should either not show while in an instance or move with it.

### Media/Files

https://i.imgur.com/eSiJY3m.png

**Comment by bakscratch** [comment]
This seems to be a broader issue with our gizmos not working well with instances and prefabs
