### ISSUE TITLE
Water shader is slightly busted in VR

### ISSUE THREAD

**Issue by MuffinTastic** [Facepunch/sbox-issues#3252]
### Describe the bug

The player's view seems to be 'overlaid' onto the water's surface in VR, and then there's whatever that is 11 seconds into the clip

### To Reproduce

Load into construct in VR, gamemode doesn't matter. Look at the water!

### Expected behavior

Should just look normal

### Media/Files

Please ignore the plant spaz in the background, that's [another issue](https://github.com/sboxgame/issues/issues/3251).

https://user-images.githubusercontent.com/10884425/236653758-9e2db47e-1130-4cd8-8310-18d602060ecb.mp4

### Additional context

RTX 4080
Driver 531.41

**Comment by samzanemesis** [comment]
should be fine now
