### ISSUE TITLE
[Hammer] Grid Causes Major Performance Issues

### ISSUE THREAD

**Issue by PixelQubed** [Facepunch/sbox-issues#3257]
### Describe the bug

When you put the hammer grid to low values on a high-resolution monitor such as a 4K screen, it reduces the FPS of Hammer pretty substantially.

### To Reproduce

1. Open Hammer
2. Make sure you are using a high-resolution screen
3. Reduse hammer grid size below 16
4. Watch performance drop like hell the lower you set the grid size to a low value

### Expected behavior

It shouldn't have performance issues due to something as simple as a grid.

### Media/Files

<img width="138" alt="sbox-dev_5LCbeQovmA" src="https://user-images.githubusercontent.com/32498714/236874577-99d7b529-7574-4ef2-a994-3cd729c1d5a2.png">
<img width="141" alt="sbox-dev_WBQ2K4niTz" src="https://user-images.githubusercontent.com/32498714/236874596-fe7a4e36-6ff0-4ba4-be18-1379258f64a6.png">

**Comment by KayaDLX** [comment]
2D or 3D grid?

**Comment by trende2001** [comment]
This happened to me while doing some regular old mapping. Just use 1 grid sparingly, ex. detailing something on your map
I mostly use 16 grid for map layout.

**Comment by PixelQubed** [comment]
> This happened to me while doing some regular old mapping. Just use 1 grid sparingly, ex. detailing something on your map I mostly use 16 grid for map layout.

I just used extremes. It happens at 8 on maps that have some geo. This is still an issue.
