### ISSUE TITLE
Add play button to asset.party

### ISSUE THREAD

**Issue by kristiker** [Facepunch/sbox-issues#3268]
### For?

Other

### What can't you do?

Add a play button to asset.party maps and games.

### How would you like it to work?

Steam protocol lets you open any game with launch args and the engine supports launch args to be passed to console.

### What have you tried?

I'm mostly opening maps I found on asset party through the ident via console

**Comment by Retroeer** [comment]
I agree with this, when testing a game you don't have access to the lobby system unless you post on Asset.Party, meaning you have to guess what the map names are, aswell as the indents. 

Having a "Play" button, or shrimply providing a copy-paste console command would be wonderful.

**Comment by TheBoxTrot** [comment]
Would also be cool in that case to have a default map or default gamemode setting for a user to launch defaults gamemode when selecting a map or vice versa

**Comment by kristiker** [comment]
I usually select the HL:S2 game mode when I can 😆. Light and smooth movement.
