### ISSUE TITLE
"Simple Liquid" shader isn't working as intended

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#327]
**Describe the bug**
The shaders fill level does not seem to properly orient itself to the worlds up axis. Alternatively the jitter and wobble seems to be constant and the liquid never seems to settle.

**To Reproduce**
[materials.zip](https://github.com/Facepunch/sbox-issues/files/6623100/materials.zip)

**Expected behavior**
The water line should always orient itself towards the world up axis(alternative the gravity direction so the fluid can be played with for directional gravity)

**Screenshots**
https://user-images.githubusercontent.com/25727384/121340345-dad06300-c962-11eb-8b20-c6def7779df6.mp4
![image](https://user-images.githubusercontent.com/25727384/121340811-5b8f5f00-c963-11eb-93d2-20d5218116eb.png)

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by samzanemesis** [comment]
Should work now
