### ISSUE TITLE
CSS text-shadow weird background

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#329]
**Describe the bug**
When using the css property text-shadow there is background overlay on the element.

**To Reproduce**

1. Use text-shadow property in css

**Expected behavior**
Shouldn't have a background

**Screenshots**
![image](https://user-images.githubusercontent.com/16431607/121456542-26ecc900-c99e-11eb-8fe5-913734d56977.png)
![image](https://user-images.githubusercontent.com/16431607/121456573-33712180-c99e-11eb-9115-26b13ea71465.png)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by louiefox** [comment]
Fixed as well, thanks.
