### ISSUE TITLE
io on func_button doesn't work

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#33]
my button has "Use Activates" enabled. The button moves, but the OnPressed output doesn't work.

![image](https://user-images.githubusercontent.com/39461072/116160282-5928bc80-a6b7-11eb-8b8b-f497dcf6a45b.png)

![image](https://user-images.githubusercontent.com/39461072/116160257-5332db80-a6b7-11eb-8baa-d36ebeb3f9ac.png)

**Comment by garrynewman** [comment]
Is this right @bakscratch? I thought our tests were testing for this?

**Comment by walllable** [comment]
I recompiled `test/buttons.vmap` to check, and they seem to work there. What're you trying to do?

**Comment by bakscratch** [comment]
I thought we had something for this? There could be an issue sending events from a button to certain entities? There are a lot of use cases so deepest apologies for missing things.

**Comment by gvarados1** [comment]
I've done some more testing and it looks like the button does work, but the io only interacts with other C# entities. It opens the C# doors, but it doesn't trigger my logic_relay because that's not in C#.

**Comment by gvarados1** [comment]
Also the FGD is messed up. Each output is listed twice

![image](https://user-images.githubusercontent.com/39461072/116431672-9c953f00-a80d-11eb-8230-c8d2b374c00e.png)

**Comment by garrynewman** [comment]
> I've done some more testing and it looks like the button does work, but the io only interacts with other C# entities. It opens the C# doors, but it doesn't trigger my logic_relay because that's not in C#.

Yep, this is how it's going to work. We're going to remake any entity that needs io in c#. Just make a feature request for each entity that you want to use, explain why you want to use it and we'll get to it.

(I'm not asking you to make a post for every entity that used to exist, just entities that you want to use right now)

**Comment by bakscratch** [comment]
logic_relay would probably be the only one needed, As that can be used to communicate with other non c# ents.

**Comment by garrynewman** [comment]
If we remake it in c# it won't be able to communicate with non c# ents though 🙄

**Comment by gvarados1** [comment]
https://github.com/Facepunch/sbox-issues/issues/55

**Comment by bakscratch** [comment]
I'd probably avoid remaking logic_relay in c# as lots of entities rely on it, Unless there are 2 versions one for c# entities and one for current ones.

**Comment by garrynewman** [comment]
Those entities don't work though, because they're in c++? Do you understand what I'm saying here?

We're not using the input system in c++. That's in the bin. We're using the new input system that is made in c#. Anything that is using the input system in c++ isn't going to work for us, so why have a logic_relay system that doesn't work just because it can communicate with a bunch of entities that we can't use?

**Comment by Jac0xb** [comment]
So essentially we can't hook any of the map entities converted to C# to source 2 native map logic entities? That seems like a huge loss in functionality.

**Comment by qualitycont** [comment]
> > 
> > 
> > So essentially we can't hook any of the map entities converted to C# to source 2 native map logic entities? That seems like a huge loss in functionality.
> 
> https://developer.valvesoftware.com/wiki/List_of_entities
> Yeah that's a lot.

Arent those the source 1 entities?

**Comment by Nickishero** [comment]
> 
> 
> > > So essentially we can't hook any of the map entities converted to C# to source 2 native map logic entities? That seems like a huge loss in functionality.
> > 
> > 
> > https://developer.valvesoftware.com/wiki/List_of_entities
> > Yeah that's a lot.
> 
> Arent those the source 1 entities?

I think it's a mix of both. Entities which were named [here](https://github.com/Facepunch/sbox-issues/issues/55) are also on this list. It doesn't say whether it is a list of source 1 or source 2 entities however.

**Comment by garrynewman** [comment]
The point is that we can remake that loss of functionality, and we can make it better than it was.

We're at a point where we don't have to support a ton of legacy maps, we should embrace and take full advantage of that. You've been creating 7 entities to play logic tennis for way too long, we should be looking at what we can do to make things easier - not hanging onto the past ways of doing things.
