### ISSUE TITLE
Graphical glitch on text

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#330]
**Describe the bug**
Text is malformed on text occasionally. Seems very specific as I haven't ran into it before, but might be worth looking in to.

**To Reproduce**
Text: "SPECTATING"
CSS:
`			text-align: center;
			font-family: Roboto;
			font-weight: 500;
			text-shadow: 0 0 3px black;
			font-size: 20px;
			color: #4ecca3;`

**Screenshots**
![image](https://user-images.githubusercontent.com/16431607/121456748-70d5af00-c99e-11eb-8ff3-ec5eb95293ca.png)
![image](https://user-images.githubusercontent.com/16431607/121456712-64515680-c99e-11eb-8c5b-f3be9b0b60d2.png)

**Additional context**
Resolution: 2560x1440

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by louiefox** [comment]
Fixed, thanks!
