### ISSUE TITLE
Panels sometimes stick in UI Inspector after closing game

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#3305]
### Describe the bug

Sometimes, when closing or restarting games in the editor, the RootPanel and its children, plus any world panels, stick around instead of being culled.

I know this issue is not very easy to debug given this information. I will be on the lookout for patterns or reproduction steps.

### To Reproduce

This doesn't happen consistently for me.

1. Create a game with UI
2. Close the game
3. If your editor is in some arbitrary unknown bugged state, the panels will not be culled

### Expected behavior

The panels get culled properly.

**Comment by trundlr** [comment]
Seems to be relatively easy to reproduce, I found it happens quite consistently when just sitting around working on UI:
![image](https://github.com/sboxgame/issues/assets/57276947/874589a3-c4c6-47ce-a410-912a69a9bb69)

**Comment by garrynewman** [comment]
Yep I get this too, does seem to be hotload related

**Comment by trundlr** [comment]
This seems to be resolved now, will re-open if I experience it again.
