### ISSUE TITLE
A way to get what key is binded to InputButton

### ISSUE THREAD

**Issue by brett-taylor** [Facepunch/sbox-issues#331]
**What can't you do?**
Get what key is binded to a `InputButton`. For example if I had an action binded to `InputButton.Flashlight` and I wanted the HUD to say "Press F to use flashlight"

**How would you like it to work?**
An example api could be `player.Input.GetKeyBindedTo(InputButton.Flashlight)` which would return `Key.F`. 
Or if an input action could be binded to multiple buttons e.g. on a keyboard and a xbox controller then it would return an array like `[Key.F, Key.XBOX_A]`

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
