### ISSUE TITLE
Baked Volumetric Fog is not showing up in-game.

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#332]
Volumetric Fog shows up in Hammer, but not in-game.

To reproduce the bug. Just add any volumetric lights into your map and compile the map. It will not show up after compile.

In Hammer: 
![sbox-dev_v64wwxm8VB](https://user-images.githubusercontent.com/17112771/121608121-4e37aa80-ca1f-11eb-88ef-e59417677f6b.png)

In-game: 
![sbox-dev_fqhy8mJWqW](https://user-images.githubusercontent.com/17112771/121608144-5abc0300-ca1f-11eb-9ff5-d902977813c5.png)

**Comment by KayaDLX** [comment]
Can confirm not working.

**Comment by samzanemesis** [comment]
Could you attach your vmap file?

**Comment by justynboi** [comment]
[volumetricfogbug.zip](https://github.com/Facepunch/sbox-issues/files/6638960/volumetricfogbug.zip)

**Comment by 5FB5** [comment]
I don't know if this an actual issue, but it works for me if I set fogging to dynamic 🤷‍♂️

**Comment by QuackCocaine** [comment]
The issue pertains to baked volumetric fog . Dynamic works fine but is limited

**Comment by KayaDLX** [comment]
Yeah we figured out afterwards that it was related to baked only

**Comment by Fortune117** [comment]
Bump. Just ran into this issue myself

**Comment by gvarados1** [comment]
This doesn't work
