### ISSUE TITLE
Jetbrains Rider debugging integration would be lovely

### ISSUE THREAD

**Issue by tavichh** [Facepunch/sbox-issues#334]
**What can't you do?**
Explore the stack trace from the console and breakpoints mainly.

**How would you like it to work?**
If there is an error in the console for s&box; you are given the option to click it and open up visual studio which I would assume brings you to the stack trace or places breakpoint at the very least.

**What have you tried?**
Well, the only way to remedy this is to download Visual Studio and I would much rather use Rider.

**Additional context**
I'm sure it's being considered. The addition of this would make debugging so much easier.'

**Comment by AtlasTheProto** [comment]
More rider support in general would be majorly appreciated.
