### ISSUE TITLE
[Editor] FPS cap is incorrect

### ISSUE THREAD

**Issue by Weldify** [Facepunch/sbox-issues#3361]
### Describe the bug

![image](https://github.com/sboxgame/issues/assets/66477673/ce68a486-839c-42fd-969f-a1c989e0c19b)
Seems like the FPS cap isn't being calculated correctly, for me the actual FPS is always roughly double my `fps_max` 

### To Reproduce

1. Set `fps_max` convar to anything
2. Observe your fps being higher (unless your computer is shit. in that case it probably doesnt matter. my condolences)

### Expected behavior

The FPS should never go above `fps_max`

**Comment by Mr-VIT** [comment]
same bug in not editor, just in geme
