### ISSUE TITLE
Material Editor compiling textures to wrong directories

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#34]
I have a material `sbox\addons\fortwars\materials\fortwars\2x3_blue.vmat` with a source `2x3_blue_color.png`.

Initially the texture appears fine in preview, until saved and I get the following:

![image](https://user-images.githubusercontent.com/1388267/116162618-1504de80-a6ee-11eb-9c94-bfa3a028087d.png)

With the following error spammed:

```
Texture manager doesn't know about texture "materials/fortwars/2x3_blue_color_png_62858750.vtex" - returning error texture in CTextureManagerDx11::GetResourceView
```

The texture is getting compiled to `sbox\fortwars\materials\fortwars\2x3_blue_color_png_62858750.vtex_c` when it should be `sbox\addons\fortwars\materials\fortwars\2x3_blue_color_png_62858750.vtex_c`.

You can workaround this for now by moving the compiled textures to where they should be.

**Comment by Jake-Rich** [comment]
Yea `.vtex_c` are ending up in `sbox/addon/` instead of `sbox/addons/addon/`

**Comment by garrynewman** [comment]
This should be fixed now, let me know if it isn't

**Comment by handsomematt** [comment]
works, cheers 👍
