### ISSUE TITLE
Codegen fails on nested classes with net attributes

### ISSUE THREAD

**Issue by FinIsOro** [Facepunch/sbox-issues#340]
**Describe the bug**
Codegen throws an error when trying to add Net attribute to nested class.

**To Reproduce**

```cs
public partial class Base
{
	public partial class Nested : NetworkComponent
	{
		[Net] public int Variable { get; set; }
	}
}
```

**Expected behavior**
Code should compile successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/35429720/121703034-13934800-cadb-11eb-9cba-d46fd5c7279e.png)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by FinIsOro** [comment]
It works fine, thank you
