### ISSUE TITLE
IconSprite for FGD auto gen

### ISSUE THREAD

**Issue by AWildErin** [Facepunch/sbox-issues#341]
**What can't you do?**
I can't use `iconsprite` in the FGD as there is no attribute for it, if this could be added it would be great as some of my gamemode's entities work better with sprites as opposed to a model or the blank white cube when we don't specify either.

**How would you like it to work?**
It'd be nice to have something like how we have `Hammer.EditorModel` we could possibly have `Hammer.EditorSprite` or `Hammer.IconSprite`

**What have you tried?**
I've tried doing it manually, but as the FGD is auto-generated at each compile, it's impractical to do it this way.

**Additional context**
I've looked through the `Hammer` namespace and I can't see anything about this, if it already exists then this request is useless.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by AWildErin** [comment]
Yep, thanks for adding it!
