### ISSUE TITLE
[Website] Bug - Broken link in the FAQ

### ISSUE THREAD

**Issue by Squadz** [Facepunch/sbox-issues#3437]
### Describe the bug

**URL :** [S&Box FAQ](https://sbox.facepunch.com/faq/)

Broken link that redirect the users to a 404 page.

### To Reproduce

1. Go to the section "**_How can I get access to the developer preview?_**"
2. Click on "[Developer Preview Torture Service](https://asset.party/get/developer/preview)"

### Expected behavior

- Seeing the page "Developer Preview Torture Service" page

**Comment by KayaDLX** [comment]
game breaking bug, i cant do anything anymore, please fix asap!

**Comment by yuberee** [comment]
game breaking bug, i cant do anything anymore, please fix asap!
