### ISSUE TITLE
Whitelist error with C# 11 static abstract/virtual interface methods

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#3441]
### Describe the bug

C# 11 introduced static abstract methods in interfaces:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/static-abstracts-in-interfaces

However it seems like trying to compile the following valid code produces access control errors:
```
public interface TestLogBase
{
    public static abstract void CoolLog();
}

public interface TestLogDerived : TestLogBase
{
    static void TestLogBase.CoolLog()
    {
        Log.Info( "derived log!" );
    }
}

public class TestClass : TestLogDerived
{
    private static void InternalRunTestLog<T>() where T : TestLogDerived
    {
        T.CoolLog();
    }
    public static void RunTestLog()
    {
        InternalRunTestLog<TestClass>();
    }
}
```

### To Reproduce

Compile the above code in a s&box project and have it call RunTestLog() in MyGame() or something

See the following errors when attempting to start the gamemode:
Whitelist Error: Sandbox.TestClass.InternalRunTestLog(..) - [CallAbstract]   Call not allowed on abstract methods.
Whitelist Error: Sandbox.TestClass.InternalRunTestLog(..) - [Constrained]   Missing callvirt following constrained prefix.

Alongside that, I'm also seeing a similar error related to abstract interface methods in another addon I'm working on:
Whitelist Error: [LdftnNonFinalVirtual]   Cannot LDFTN a non-final virtual method for delegate creation if target object is potentially not the same type as the method class.

### Expected behavior

S&box should start the addon without problems - or if there are security issues here, potentially add some intellisense warnings to warn devs about using the feature?

**Comment by DaddyFrosty** [comment]
as far as I could understand, the issue seemed to be quite a deep one down to the parser. Good luck to whoever needs to update it!

**Comment by handsomematt** [comment]
We're moving away from ILVerify as we switch to non dll distribution, so this should be fixed then.
