### ISSUE TITLE
Hotload doesn't work with classes that contain actions

### ISSUE THREAD

**Issue by FinIsOro** [Facepunch/sbox-issues#345]
**Describe the bug**

Hotload can't recreate an instance of the class because the class contains Action with one or more parameters, the type of which is the class itself.

**To Reproduce**

1. Run the following code

```cs
public static class GlobalClass
{
	public static ActionClass ActionClass { get; set; } = new();
}

public class ActionClass
{
	public Action<ActionClass> action = instance => Log.Info("Initializing action");
	
	public ActionClass()
	{
		action += Action;
	}

	private static void Action(ActionClass instance)
	{
		Log.Info("Empty function");
	}
}
```

2. Try to edite the code (just add comment somewhere)
3. See console output, there should be something like `Type is not supported. (.ActionClass)`

**Expected behavior**

All code recompiles fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/35429720/121786176-dad09d00-cbc6-11eb-8c80-57a502717452.png)
![image](https://user-images.githubusercontent.com/35429720/121786183-e328d800-cbc6-11eb-8692-d7790a44b5fc.png)

**Additional context**

This problem only appears when the `action` field is set with the `=` operator and then subscribed with the `+=` operator.

**Comment by Metapyziks** [comment]
Thanks for the report!

This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.

If it is fixed feel free to close the issue yourself <3

**Comment by FinIsOro** [comment]
It works fine, thank you
