### ISSUE TITLE
Ability to upload all assets in a Content Project

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#3454]
### For?

S&Box

### What can't you do?

I have a bunch of models and materials in a art repo.
Some of those models are used in a map, some aren't.

I would like to be able to upload all the models/art in that repo to asset party in one click, or as few clicks as possible.

### How would you like it to work?

Inside the content project settings, there is a way to "Publish to Asset Party"

This will detect all assets and try to upload to asset party.

### What have you tried?

I can make a blank map, throw all the content in there, and then upload that to asset party.

### Additional context

It would be nice to be able to set the idents for each asset from the same place.

**Comment by handsomematt** [comment]
> I have a bunch of models and materials in a art repo.
> Some of those models are used in a map, some aren't.

Just checking that you know assets referenced by your map will be automatically uploaded right?

**Comment by Remscar** [comment]
> > I have a bunch of models and materials in a art repo.
> > Some of those models are used in a map, some aren't.
> 
> Just checking that you know assets referenced by your map will be automatically uploaded right?

Yes, but not all of our assets need to be used in the map.

**Comment by trende2001** [comment]
Garry is working on this now
