### ISSUE TITLE
Prefab Editor doesn't show unsaved edits

### ISSUE THREAD

**Issue by Weldify** [Facepunch/sbox-issues#3474]
### Describe the bug

![image](https://github.com/sboxgame/issues/assets/66477673/ba321991-7a7a-430b-a979-3f6cb8f922eb)
I made changes to the prefab, but the traditional "unsaved asterisk" is not there. It makes me forget to save a lot.

### To Reproduce

1. Make changes to a prefab
2. It won't show the asterisk - but it should

### Expected behavior

When you have unsaved edits, it should show an asterisk. Could also warn you when youre trying to close without saving

**Comment by nickclickmyads** [comment]
Garry mentioned that he would rewrite the whole editor, so I expect all issues with it are irrelevant. 
[https://github.com/sboxgame/issues/issues/3013#issuecomment-1469443626](https://github.com/sboxgame/issues/issues/3013#issuecomment-1469443626)

**Comment by Phyksar** [comment]
Garry mentioned that he would rewrite the whole editor, so I expect all issues with it are irrelevant. 
[https://github.com/sboxgame/issues/issues/3013#issuecomment-1469443626](https://github.com/sboxgame/issues/issues/3013#issuecomment-1469443626)
