### ISSUE TITLE
Overrides for Game Menu open and close

### ISSUE THREAD

**Issue by SharpMars** [Facepunch/sbox-issues#3486]
### For?

S&Box

### What can't you do?

I am currently unable to write code that runs when menu is closed and open.
For example:
I want to set TimeScale for my game when its open and closed, pausing the game when menu is open and and unpausing when its closed.

### How would you like it to work?

Have one override for Game Menu when it gets open and one for when it gets closed.

### What have you tried?

I tried:
- Tick function
- GameEvent.Tick (doesnt work on Game Menus)
- Different UI overrides

Anything I tried so far didnt work

**Comment by cr4yz** [comment]
There's `Game.IsMainMenuVisible`, that might work for you.

**Comment by SharpMars** [comment]
Tried it, but couldn't have code run after its closed
