### ISSUE TITLE
Broken hammer entities - Elevator(func_tracktrain and related entities)

### ISSUE THREAD

**Issue by Lakatos76** [Facepunch/sbox-issues#349]
**Describe the bug**

There's a lot, so the best course of fixing this is just looking at the linked .vmap and fix what doesn't work. The elevator is functional in Half Life Alyx.

Some of outputs/inputs that are broken: 
* [x] Missing input for change color of a func_brush
* [ ] Missing input for disabling/enabling a relay
* [ ] Missing many inputs and outputs of logic_compare
* [x] Missing input for func_door to open/close
* [x] Missing input for func_button to lock/unlock
* [ ] The state of path_track entities or func_tracktrain could be completely broken

[elevator_example.zip](https://github.com/Facepunch/sbox-issues/files/6643737/elevator_example.zip)

**Comment by Jac0xb** [comment]
#55
