### ISSUE TITLE
launchSettings.json gets generated in the wrong location

### ISSUE THREAD

**Issue by rtm516** [Facepunch/sbox-issues#35]
After the changes with where addon files are, the `ProjectGen.exe` now generates the `launchSettings.json` in the wrong location. This causes the project to not be launchable from visual studio.

Generates in: `sbox\addons\addon\Properties\launchSettings.json`
Should be in: `sbox\addons\addon\Code\Properties\launchSettings.json`

**Comment by garrynewman** [comment]
Thanks, fixed
