### ISSUE TITLE
Whitelist System.Collections.Generic.List<T, T>

### ISSUE THREAD

**Issue by VladUndying** [Facepunch/sbox-issues#350]
**Describe the bug**
Unable to create lists with multiple arguments

**To Reproduce**

List<Entity, float> = new List<Entity, float>();

**Expected behavior**
Multiargument List

**Comment by Alf21** [comment]
`using System.Collections.Generic`

**Comment by VladUndying** [comment]
You're right. I for some reason thought multiarg lists existed? Perhaps not, thanks.
