### ISSUE TITLE
Wiki Cleanup

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#3503]
Making a checklist of wrong/bad information here. Feel free to go to the wiki and fix this, failing that I'll do it myself.

- [ ] Rely on the sidebar less. Have Contents pages that link to pages instead. Less pages in the sidebar.
- [x] Define a learning path. Page up front with 1. The Project System, 2. Creating a map etc
- [x] Getting Started with Hammer explains how to create a content addon, but not how to create a map
- [x] Should have a "how to import a model" page for ModelDoc. Shortest, easiest path.
- [ ] Way too much text in Animgraph breakdown page. Show don't tell.
- [ ] UI System overview page - explain that we're panels and stylesheets, not a webkit renderer
- [ ] Texture Settings - who is this for? delete?
- [ ] Audio should probably have its own section
- [ ] Coding Overview page layout is confusing and weird
- [x] Re-evaluate what belongs in the coding "getting started" section
- [ ] Re-evaluate what belongs in the coding "making games" section
- [x] Traces section has a todo
- [ ] Should playing guides be a different wiki?

**Comment by yuberee** [comment]
Would be nice if we could embed YouTube/Streamable videos, sometimes a wiki page can just be a single YouTube video.

**Comment by robotboy655** [comment]
Embedding external resources on the wiki would just lead to the external resource dying at some point. So your single YouTube video wiki page just becomes useless.

**Comment by peter-r-g** [comment]
> Re-evaluate what belongs in the coding "making games" section

I'll leave it for a member of FP to check off but I've made the following changes in this regard:
* Moved [Running Multiple Instances of the Game](https://wiki.facepunch.com/sbox/multi-run) to Playing > Playing Guides
* Moved [Traces](https://wiki.facepunch.com/sbox/Traces) to Coding > Physics
* Moved [The Game Loop](https://wiki.facepunch.com/sbox/GameLoop) to Coding > Getting Started

I haven't touched [Making a Simple AI](https://wiki.facepunch.com/sbox/MakingASimpleAI) but following the style of the wiki, it should probably just get deleted
