### ISSUE TITLE
Water bug

### ISSUE THREAD

**Issue by Kuhleron** [Facepunch/sbox-issues#3505]
### Describe the bug

When I somehow interact with water, which causes waves to appear, my waves begin to increase indefinitely until I turn away. Maybe it's because of my laptop. My CPU is i3-8145U 2.2GHz, Nvidia Geforce MX250 GPU. 8 GB RAM

### To Reproduce

Spawn on any map with water, try to interact with water, and you'll see a bug

### Expected behavior

Waves should not increase indefinitely

### Media/Files

https://github.com/sboxgame/issues/assets/122085856/7abd7511-6801-4ce3-a620-0e76b5c1dbcd

**Comment by samzanemesis** [comment]
should be fine now
