### ISSUE TITLE
`Sandbox.MenuSystem.PartyLobby` not working anymore

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#3515]
### Describe the bug

Hello,

I tried to use the static class [PartyLobby](https://asset.party/api/Sandbox.MenuSystem.PartyLobby) but it currently doesn't work in GameMenu state.

For beginning,
S&box lobby is currently broken, if you try to invite your friend to your lobby, he will receive the steam invitation but nothing occurs on accepts.

So i start to navigate through `FriendPopup.razor` from `menu` and i discover the static [PartyLobby](https://asset.party/api/Sandbox.MenuSystem.PartyLobby) class

This class seems to handle the S&box lobby but all of their properties return empty value in GameMenu state :
- [Members](https://asset.party/api/Sandbox.MenuSystem.PartyLobby.Members) return empty
- [Owner](https://asset.party/api/Sandbox.MenuSystem.PartyLobby.Members) returns an empty Friend

_But in S&box main Menu state is working :_
![image](https://github.com/sboxgame/issues/assets/5229571/ba019636-fc24-4d0a-adf0-d88779b74c1c)

It's sad cause i'm looking to retrieve the current S&box Lobby for my Game.Menu in order to create a "crew" who join together a server when Lobby.Owner joins the server.

I also try to use [Sandbox.MenuSystem.GameLobby.TryJoinLobby(ulong)](https://asset.party/api/Sandbox.MenuSystem.GameLobby.TryJoinLobby(ulong)) but is only usable in Menu, not Game.Menu (and it's for another usage)

### To Reproduce

To reproduce the lobby s&box bug :
1) Try to invite your friend to a Lobby :
![image](https://github.com/sboxgame/issues/assets/5229571/670b3816-ffb2-4603-97c7-f604542329be)
2) When he accepts, nothing occurs. You just will get the crown for beiing the `PartyLobby.Owner.IsMe`

To reproduce the [PartyLobby](https://asset.party/api/Sandbox.MenuSystem.PartyLobby) bug :
1) Try to use PartyLobby class anywhere (except s&box main menu, which works) : this always acts like an Empty Lobby

### Expected behavior

1) S&box lobby must work like before
2) The static class PartyLobby must be correctly return informations from the current lobby

**Comment by Retroeer** [comment]
bump, with the recent key surges, being able to easily connect to each other's is probably needed more than ever
