### ISSUE TITLE
UI CSS mismatch

### ISSUE THREAD

**Issue by SebastianMaj** [Facepunch/sbox-issues#352]
![image](https://user-images.githubusercontent.com/6146752/121822602-f3e05900-cc6d-11eb-95e7-d202f747d51f.png)

Using the css transform element shifted the render of the UI properly but it didn't seem to shift the elements properly. This resulted into the positions of the boxes to be offset from the render and the on hover class wouldn't register unless I hovered my mouse over the shifted position. So if I put my mouse in the bottom right of my screen the boxes in the center would darken as they were being "hovered over"

transform: translateX(-50%) translateY(-50%);

After removing the line above I got the proper results
![image](https://user-images.githubusercontent.com/6146752/121822670-50dc0f00-cc6e-11eb-804c-732fad1d8cbb.png)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by SebastianMaj** [comment]
It's been fixed. Thank you!!! :)
