### ISSUE TITLE
backdrop-filters cause visual issues in WorldPanels

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#3520]
### Describe the bug

When using `backdrop-filter` in a WorldPanel, it will cause you to see cursed visuals that seem to be based on your camera view

https://github.com/sboxgame/issues/assets/5159369/1af33c4a-cb47-46b2-9244-e11d1a7164c4

### To Reproduce

Do `backdrop-filters: blur(2px);` in a Panel within a WorldPanel to reproduce the video above.

### Expected behavior

It should blur the background (or do whatever filter effect should be applied)

**Comment by chrisspieler** [comment]
I forgor to make an issue when it happened to me, so enjoy this additional repro footage
https://github.com/sboxgame/issues/assets/8889285/40fe149b-d642-4a63-aa94-365fa26c23f4

**Comment by trundlr** [comment]
Curious if this could get added to the tracker? Issue still persists in scene, and is very easy to reproduce.

**Comment by xezno** [comment]
These should work now, here's an example:

![image](https://github.com/Facepunch/sbox-issues/assets/12881812/6984cbdc-0b43-4f28-964a-8e58bfc7269b)

Let me know if there's any problems
