### ISSUE TITLE
CSS blur features

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#353]
**What can't you do?**
Apply any type of blur filter in css.

**How would you like it to work?**
Have css properties implemented:
filter: blur();
backdrop-filter: blur();

**Additional context**
I saw that there were some tests for it in the effects tab for the UI tests however they were commented out, I assume this means they were being worked on at some point or planned?

UI test code
`AddTest( "Background Blur 2px", "backdrop-filter: blur(2px);" );`
`AddTest( "Background Blur 10px", "backdrop-filter: blur( 10px );" );`
`AddTest( "Background Blur 10px And Unsaturated", "backdrop-filter: blur( 10px ) saturate(0);" );`
`AddTest( "Very Saturated", "backdrop-filter: saturate(200%);" );`

**Comment by TimGoll** [comment]
I noticed this as well. It is even listed as supported feature [in the wiki](https://wiki.facepunch.com/sbox/supported-style-properties). I tried it a few different ways but it most certainly doesn't work. So I can confirm that your testing is valid, this is a bug in the game.

**Comment by louiefox** [comment]
Am I okay to close this now that its been added?

**Comment by garrynewman** [comment]
Yep! Tahnk you!
