### ISSUE TITLE
Some maps download twice, game fails to extract due to files being locked.

### ISSUE THREAD

**Issue by thirteen-io** [Facepunch/sbox-issues#354]
**Describe the bug**
Creating a game on Office (https://sbox.facepunch.com/dev/baks/office) more than once causes the game to re-download map and fail due to the file being locked.

I have been unable to repeat this on any other map.

**To Reproduce**
1. Start a game on Office (any gamemode).
2. Return to menu and repeat step 1.
3. See error (Additional information in console).

**Expected behaviour**
Map should download once (and cache).
Map should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/1660830/121826472-b3a1ca80-ccaf-11eb-90fe-6e47db04baf6.png)

**Additional context**
N/A

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by thirteen-io** [comment]
Confirmed fixed!

Thank you!
