### ISSUE TITLE
Allow Batch Publishing on Game Addons

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#3547]
### For?

S&Box

### What can't you do?

Currently if you have a game with a bunch of assets that you would like to upload you have to temporarily edit the .addon file and change the Type from "game" to "content" to batch upload the assets.

### How would you like it to work?

Ideally game addons would allow for batch asset uploading as well, the wording may need to be clarified to avoid confusion, from "Batch Upload to asset.party" to "Batch Upload Assets to asset.party". so that it's not confused with "Upload to asset.party".

### What have you tried?

Temporarily editing the .addon file and changing the Type from "game" to "content", which does work.

**Comment by DevulTj** [comment]
this seems like bad design to me - seems like it should be a content project, in which the game project refers to those assets

**Comment by CarsonKompon** [comment]
This should be revisited now that content mode is being phased out :)

**Comment by Jammie3d** [comment]
Now that the Projects window has been removed could bulk upload be moved to the content browser? Maybe when you right click the project folder or something.
![image](https://github.com/Facepunch/sbox-issues/assets/60801006/8031a4cd-5557-4325-be5d-114b9b41977e)

**Comment by garrynewman** [comment]
Yep

**Comment by Jammie3d** [comment]
Looks like this has been added now, thanks!
