### ISSUE TITLE
`ServerVar` with `Replicated = true` not updating on clients

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#355]
**Describe the bug**
A `[ServerVar]`-decorated property with `Replicated = true` does not replicate to clients when its value is changed.

**To Reproduce**
1. Create a static property annotated with `[ServerVar("foo", Replicated = true)]`
2. Change its value in the console
3. Read the property on any connected client-- it will still be set to the default value

**Expected behavior**
ServerVars with replication enabled should update on clients when the server changes them.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
