### ISSUE TITLE
Whitelist System.Net stuff

### ISSUE THREAD

**Issue by Yomanz** [Facepunch/sbox-issues#356]
As far as I know these are the only things that need to be whitelisted to be able to use System.Net for HTTP requests.
- `System.Net.Http/System.Net.Http.HttpClient`
- `System.Net.Http/System.Net.Http.Headers.*`
- `System.Net.Http/System.Net.Http.HttpMethod`
- `System.Net.Http/System.Net.Http.HttpRequestMessage`
- `System.Net.Http/System.Net.Http.HttpResponseMessage`
- `System.Net.Http/System.Net.Http.HttpClientHandler`
- `System.Net.Http/System.Net.Http.DelegatingHandler`
- `System.Net.Http/System.Net.Http.HttpMessageHandler`
- `System.Net.Http/System.Net.Http.WebRequestHandler`
- `System.Net.Http/System.Net.Http.ByteArrayContent`
- `System.Net.Http/System.Net.Http.FormUrlEncodedContent`
- `System.Net.Http/System.Net.Http.MultipartFormDataContent`
- `System.Net.Http/System.Net.Http.StreamContent`
- `System.Net.Http/System.Net.Http.StringContent`

**Comment by garrynewman** [comment]
We're not going to whitelist all this

**Comment by handsomematt** [comment]
System.Net.Http isn't going to get whitelisted for security reasons afaik.

I believe you can use `Sandbox.Internal.Http` though.

**Comment by Yomanz** [comment]
> 
> 
> System.Net.Http isn't going to get whitelisted for security reasons afaik.
> 
> I believe you can use `Sandbox.Internal.Http` though.

Ah cool didn't know about that.
Thanks,

**Comment by Yomanz** [comment]
Just had a look at `Sandbox.Internal.Http` and it's rather minimalist and doesn't allow for headers, different methods or bodies. I assume it'll be fleshed out as time goes on.

**Comment by handsomematt** [comment]
> Just had a look at `Sandbox.Internal.Http` and it's rather minimalist and doesn't allow for headers, different methods or bodies. I assume it'll be fleshed out as time goes on.

It's marked as Internal as the API will be changing a lot, so don't depend on it too heavily working the way it is now.
