### ISSUE TITLE
Translucent materials don't work as expected

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#3578]
### Describe the bug

The goal was to have a translucent object that casts a shadow. Material has an "Alpha Test" checked and Translucency set to 0.5. My friend who made it has some kind of dithering pattern on his PC, which is fine, and in ModelDoc the material looks perfect.

It looks excellent in ModelDoc for me as well, but in game it's solid gray.

### To Reproduce

1. Download the attached model
2. Open ModelDoc
3. Click the "Launch Game Preview" button
4. Focus on the main dev tools window

### Expected behavior

I'd like to have a consistent behavior of such materials. The only clue I have is that he uses an AMD card, while I use an Nvidia one.

### Media/Files

My PC (GTX 3060, driver version 536.40, Windows):
![G8bxb26OEi](https://github.com/sboxgame/issues/assets/6745157/5c63609a-c37f-467b-9ac1-bfbbc10c2491)
His PC (AMD videocard, Windows):
![Discord_vfXYVs2zPr](https://github.com/sboxgame/issues/assets/6745157/3886c5a5-b446-4738-8c73-a53aab202e45)
![Discord_yMD4RdNiG6](https://github.com/sboxgame/issues/assets/6745157/1a827b4f-76ae-4739-a4bc-dfb9731cb622)
My other friend's PC (AMD Ryzen 5700G built-in GPU, Mesa 23.1.3, Linux)
![Discord_eTUKo3LGDE](https://github.com/sboxgame/issues/assets/6745157/38ef3669-afe5-4261-aa15-f55857025bce)

The model: [hamsterball.zip](https://github.com/sboxgame/issues/files/11992480/hamsterball.zip) [(tesa.hamsterball)](https://asset.party/tesa/hamsterball)

### Additional context

@Zuerg
```[tasklist]
### Tasks
```

**Comment by ceitine** [comment]
Same happens on a NVIDIA 2070S
![mspaint_DmnIzxIUi6](https://github.com/sboxgame/issues/assets/19620198/97063299-1a23-4133-8943-e0cb3bf93a2d)
