### ISSUE TITLE
SCSS :nth-child pseudo

### ISSUE THREAD

**Issue by Westsaid** [Facepunch/sbox-issues#358]
**What can't you do?**
Use the [:nth-child pseudo](https://developer.mozilla.org/de/docs/Web/CSS/:nth-child): Select a particular child based on a number, e.g. second child `.parent .child:nth-child(2)`. 
Also and even better, select **every** second element, e.g. `.parent .child:nth-child(2n)` . This is especially usefull if you want to color every second background in another color, we used this on our scoreboard draft we made in the web:
![image](https://user-images.githubusercontent.com/58175915/121898176-68290400-cd23-11eb-9049-7d869819dd5f.png)
(See red box)

**How would you like it to work?**
Preferably like in the web. SCSS nesting supported like: 
```
.parent {
    ...
    .child {
        &:nth-child(1n) {
            ...
        }

        &:nth-child(2n) {
            ...
        }
    }
}
```

**What have you tried?**
Add classes like `.even` & `.odd` to the children. This makes life hard especially when the order of the elements is changing regularly. You could use C# then to reset the classes when the scoreboard is updating, but this is not as best as possible. 
 

**Additional context**
Usage of :nth-child in the scoreboard of our web draft: http://www.ttt-sbox.com/

**Comment by zeo** [comment]
If we're already adding the :nth-child, would be nice to have nth-last-child aswell

**Comment by garrynewman** [comment]
I added support for 

`:nth-child( 4 )`
`:nth-child( odd )`
`:nth-child( even )`

No 2n, 3n, 3n+4 etc support right now. Let me know if you can't cope without them

**Comment by Westsaid** [comment]
Great it works! We were able to use this for our scoreboard as intended:
![image](https://user-images.githubusercontent.com/58175915/123479637-8505e700-d601-11eb-990c-5c03c7675938.png)

Ty for implementing it! This issue is closed therefore. :)
