### ISSUE TITLE
GameMenu always uses cloud version of panels when in-game.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#3582]
### What it is?

So, while I was working on a custom game menu I was experiencing what I thought was an error with stylesheets, maybe that s&box was confusing my FrontPage.razor.scss with the base library's FrontPage.razor.scss, and the style was different but only in the in-game version of the menu. That ended up not being the case. Here's what I mean by "main menu" version and "pause menu/in-game" version.

Main menu version: ![image](https://github.com/sboxgame/issues/assets/66768086/123aa623-fce0-40a8-95de-183f68c0daa2)
Pause menu/in-game: ![image](https://github.com/sboxgame/issues/assets/66768086/a6a3f718-73fb-4260-96ed-d1f496af9caf)

What I found is that it seems like the game *always* downloads the current asset.party version of the game menu for use in the pause menu/in-game version of the menu, even when developing locally. 

### What should it be?

I would prefer that, at least when developing the game, that the menu is always the local version regardless of if we are in the main menu or in-game. Makes it easier to verify that any InGame specific stuff is working correctly. Bit annoying that I have to upload to asset.party to see changes reflected on the in-game version at the moment.

**Comment by CarsonKompon** [comment]
I personally think that the Pause Menu should be it's own Panel that is NOT the Main Menu.

The Main Menu obviously doesn't have any way to interface with clients/entities, because they do not exist on a Main Menu. But these things will always exist when in-game, and your Pause Menu should have access to this. Attempting to maintain a Main Menu that doubles as a Pause Menu (or even has a separate one altogether) is also more effort than it should be as a result.

**Comment by dch-GH** [comment]
> Attempting to maintain a Main Menu that doubles as a Pause Menu (or even has a separate one altogether) is also more effort than it should be as a result.

Yeah that's probably true, but I'm just forking off the default menu for simplicity. I assume you can do this split of entirely distinct UIs if you do it all yourself right? Or does sbox currently force you to usen your main menu has a pause menu?

**Comment by CarsonKompon** [comment]
They force you to use your Main Menu as your Pause Menu. My comment wasn't really pertaining to your issue specifically but it would definitely solve your problem by proxy.

**Comment by dch-GH** [comment]
> They force you to use your Main Menu as your Pause Menu. My comment wasn't really pertaining to your issue specifically but it would definitely solve your problem by proxy. I was commenting because I think it's a larger issue that should be considered first by facepunch instead of these smaller ones that could even be caused by the fact that they are both the same menu.

Gotchya. In that case I totally agree that we should be allowed to have separate a GameMenu/PauseMenu for our games. There are plenty of cases where using the same one for both is just non-sensical and would be so much overhead and unneeded complexity. A lot of games need at most 3 buttons for a pause menu instead of the whole thing. 👍
