### ISSUE TITLE
Add the ability to get the current collision rules of the physics world

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#3588]
### For?

S&Box

### What can't you do?

Currently it is not possible to get the current active collision rules of a game. We can do `SetCollisionRules` to apply new rules at runime, but we cant access the ones that are already active, for the purpose of adding new rules to already existing ones (expand a game's collision rules via an addon). 

### How would you like it to work?

A `GetCollisionRules` method would be the way to go.

### What have you tried?

Nothing :(

**Comment by Gmod4phun** [comment]
Bumping this, as I still have a need for it

**Comment by garrynewman** [comment]
- [ ] Add PhysicsWorld.CollisionRules { get; set; } accessor
- [ ] Before PhysicsWorld step, generate and compare hash of CollisionRules
- [ ] If hash has changed, update collisionrules json
- [ ] Initialize CollisionRules from project config!
- [ ] Update CollisionRules when project config changes during game!
- [ ] Delete ServerConfig class, everything should be much simpler now
