### ISSUE TITLE
CSS clip/clip-path property

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#359]
**What can't you do?**
https://www.w3schools.com/cssref/pr_pos_clip.asp
https://www.w3schools.com/cssref/css3_pr_clip-path.asp

**What have you tried?**
Using it.

**Additional context**
The clip-path property is a replacement for it and someone else opened an issue for that but closed it, might want to implement clip-path instead.

**Comment by SleepyMode** [comment]
I'm fairly sure this is still needed?
