### ISSUE TITLE
[asset.party] Leaderboards are showing the bottom 10 results instead of top 10

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#3590]
### Describe the bug

Others have said they do not see this, while I see it on all games on both firefox and chrome whether I am logged in or not.

![image](https://github.com/sboxgame/issues/assets/5159369/b8ca1ee9-d1ef-4630-852e-84b6bd710862)
https://asset.party/carsonk/tetros/leaderboards/v/tetros_highscore/

![image](https://github.com/sboxgame/issues/assets/5159369/ff9bb629-87a2-4c06-ba9a-24f9cd45985e)
https://asset.party/facepunch/sausagesurvivors/leaderboards/v/kills/

Here is a screenshot from someone else where they see the top 10 instead of bottom 10:
![image](https://github.com/sboxgame/issues/assets/5159369/92840c91-f003-457b-a326-0affe0c5b645)

### To Reproduce

See above links.

### Expected behavior

It should show the top 10 results instead of the bottom 10.

**Comment by garrynewman** [comment]
This is kind of by design. If you don't have an entry your entry is 0, so it shows the bottom entries.

I don't know whether we should ever show the top 10, because it's likely going to be people cheating.

**Comment by DrewBritt** [comment]
I understand what you're getting at regarding cheating, but wouldn't it be kind of pointless to show the bottom entries since they're sure to be riddled with low-score entries? Like in this image Carson posted:
![image](https://github.com/sboxgame/issues/assets/43252311/7aff25b8-098d-4bf1-ae95-9f2d4fce2591)

**Comment by CarsonKompon** [comment]
I was going to argue the same thing, if they were the bottom 10 then they are equally as pointless. Would be nice to have the option when editing the leaderboard maybe.

**Comment by garrynewman** [comment]
We'll generally you're only looking at the leaderboard to see where you are, but I get the point, will make it an option..
