### ISSUE TITLE
Implement <slot></slot> for HTML templating.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#360]
**What can't you do?**

You can't put contents into a custom HTML panel. Which limits what you can do with templating.

**How would you like it to work?**

```html
<ParagraphTitle>This is the Title</ParagraphTitle>
```

PargraphTitle html template would look like:
```html
<div>
    <text class="title">
          <slot></slot>
    <text>
</div>
```

or 

```html
<MemberInfo>
    <text slot="name">Llamalords</text>
    <text slot="role">Coder</text>
</MemberInfo>
```

MemberInfo html template would look like:
```html
<div>
    <div class="member">
          <slot name="name"></slot>
          <div class="divider"></div>
          <div class="role-container">
                <slot name="role"></slot>
          </div>
    <div>
</div>
```

**What have you tried?**

You have to do programatic panel creation.

**Comment by garrynewman** [comment]
This might happen, I just need to find a good use case for it myself and I'll implement it.
