### ISSUE TITLE
Black screen when launching for the first time

### ISSUE THREAD

**Issue by Weldify** [Facepunch/sbox-issues#3603]
### Describe the bug

Launching the s&box player for the first time on a machine sometimes causes an infinite black screen, it doesn't even show the FP logo. It will hang forever, and the only way to get rid of it is to keep restarting s&box until it shows up the FP logo and starts properly. After loading properly once the black screen never happens again. This happened to my friend a couple weeks ago and to me just now since I hopped on from a different laptop.

### To Reproduce

1. Open the S&box player for the first time (the bug can happen even if you opened tools before)
2. If the FP logo doesn't show - you got the bug

### Expected behavior

Shouldnt hang infinitely

**Comment by dm4uz3** [comment]
I got on for the first time right now and this happens so at least im happy knowing im not the only one. tldr can reproduce
