### ISSUE TITLE
Implement logic system in HTML templating.

### ISSUE THREAD

**Issue by Jac0xb** [Facepunch/sbox-issues#361]
**What can't you do?**

Without some kind of ability to use conditional statements, field value rendering, or for loops in templating--templating is pretty useless currently.

**How would you like it to work?**

Some kind of logical system like this:

```html
<div>
    {if (ClassField == true)}
           <div>Only rendered when field is true!</div>
    {end}
</div>

```

Some kind of iterable like this:

```html
<div>
    {for (var value in EmunerableFieldValue)}
           <div>{value.Field}</div>
    {end}
</div>

```

Some kind of in-line value rendering:

```html
<div>
    {ClassField}
</div>

```

**What have you tried?**

This must be done completely programatically without any templating (or it gets really messy).

**Comment by garrynewman** [comment]
Honestly, this probably won't happen, but I'll leave this ticket open just in case it does.
