### ISSUE TITLE
Allow us to specify Leaderboard Timeframe (Daily/Weekly/Monthly Leaderboards)

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#3611]
### For?

S&Box

### What can't you do?

You should be able to specify the timeframe that the leaderboard displays results from. This way you could have daily/weekly/monthly leaderboards.

### How would you like it to work?

![image](https://github.com/sboxgame/issues/assets/5159369/f8327a0d-13b3-4a6e-85b8-b14252c26bcc)

### What have you tried?

Looking for an option similar to what I proposed but could not find one (because the leaderboard api is so early)

**Comment by ShadowBrian** [comment]
A year later, any news on this? 
Would love to make weekly seeded game runs.

**Comment by Dimmies** [comment]
A year and a few days later, I think being able to sort leaderboards by time could be nice. Something like the attached (using your Dude Jump leaderboards) 
![nfZjXxT](https://github.com/user-attachments/assets/9bbcfa66-7c8c-4c12-ba3a-5c420e8764e3)
