### ISSUE TITLE
Add a bind for Mouse3

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#362]
I want to add a third ability to my guns, bound to Mouse3.

I can't because Mouse3 is unbound by default.

**Comment by VladUndying** [comment]
You can add a console command and bind it later, not a perfect solution but atleast something.

**Comment by garrynewman** [comment]
What do you want it bound to? Attack3?

We have to consider how these keys would translate to a controller.

**Comment by VladUndying** [comment]
> What do you want it bound to? Attack3?
> 
> We have to consider how these keys would translate to a controller.

Can't we have something in Settings (I know they're not ready yet) to bind C# added Bindings, so both controllers and keyboards can bind and use any keys they want. The variety on keyboards is much bigger tho.

**Comment by garrynewman** [comment]
Of course we're going to have the ability to change binds in the settings. I'm asking what the default should be. We could bind it to +forward by default but that's not going to help anyone.

**Comment by VladUndying** [comment]
> Of course we're going to have the ability to change binds in the settings. I'm asking what the default should be. We could bind it to +forward by default but that's not going to help anyone.

I guess no bind by default? Devs can send some message/warning to users who don't have bind set.

**Comment by garrynewman** [comment]
Would it not be more useful to have it bound to something by default?

**Comment by VladUndying** [comment]
Only for keyboard I guess? Controllers don't have a lot of keys available.

**Comment by NotGaylien** [comment]
I never use controllers, but they have the ability to press down the joystick as its own input right?
I think that could work well, unless that's already used.

**Comment by gvarados1** [comment]
For reference, Portal 2 and Left 4 Dead 2 have +zoom bound to MOUSE3 & STICK2 (right stick pressed)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by gvarados1** [comment]
> This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.
> 
> If it is fixed feel free to close the issue yourself <3

Thanks. Works!
