### ISSUE TITLE
S&box performance gets worse as you open and close more tools

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#3631]
### Describe the bug

Through the performance graph (And my fps) I can see that the Tools section is taking up more and more time after opening and closing tools such as hammer or modeldoc.
It's understandable when you have them open, but the performance remains the same even after closing them, leading to awful performance in the middle of a full development session, requiring me to restart S&box to "reset" the performance.
 

### To Reproduce

1. Open the Performance graph
2. Take note of the time Tools take
3. Open a tool such as hammer, modeldoc, animgraph etc...
4. Close the tool
5. Notice how the Tools time has increased and will do so the more tools you opened in the past

### Expected behavior

For tools to properly stop using any resource after they've been closed.

### Media/Files

Before opening any tools:
![image](https://github.com/sboxgame/issues/assets/59583743/e72a8d2e-d868-4853-96ab-9ca860be6351)

After opening and closing Hammer:
![image](https://github.com/sboxgame/issues/assets/59583743/67191995-acc8-4d5d-aacc-59be99841a99)

After opening and closing Modeldoc:
![image](https://github.com/sboxgame/issues/assets/59583743/6c8dd198-18b1-45b8-8287-a4602e54618c)

After opening and closing Particle Editor:
![image](https://github.com/sboxgame/issues/assets/59583743/16c8f92d-e1b4-424e-a85b-70c222452fc3)

Now I'm left with a third of the FPS with no tools open.

**Comment by handsomematt** [comment]
![image](https://github.com/sboxgame/issues/assets/1388267/3025606f-d14b-4ed1-9a89-5eaaf903bae4)

Doesn't seem to happen for me, is there anything specific to make it happen

**Comment by yuberee** [comment]
Not sure to be honest, I'll give out my specs just in case it's got something to do with those:

CPU: AMD Ryzen 7 5800X
GPU: GTX 1060 3GB
RAM: 16GB 2144Mhz
OS: Windows 10 64bit

Might give redownloading S&box a try since I have never done since the first time 2+ years ago.
I'll find a way to check the performance better when I'm home.

**Comment by yuberee** [comment]
Doesn't happen anymore. Not sure if it has to do with my new GPU GTX 1060 6GB
