### ISSUE TITLE
Convert model to the editable mesh bug (hammer)

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#364]
**Convert model to the editable mesh bug**

When converting a model to mesh, the engine for some reason instead of taking materials from already maded vmdl file tries to use them from source mesh like fbx / dmx and so on, this leads to an error - missing materials

![image](https://user-images.githubusercontent.com/54669564/122029401-851e0f80-cdd5-11eb-8e1b-d90ec42a6683.png)
![image](https://user-images.githubusercontent.com/54669564/122029462-92d39500-cdd5-11eb-84c6-35e5c44e11af.png)

**To Reproduce**

1. Сonvert your custom model to an editable mesh.
![image](https://user-images.githubusercontent.com/54669564/122029855-eba32d80-cdd5-11eb-8ac9-f81320ea3205.png)

2. See error 

**Workaround for this bug**
Remove your source mesh file & vmdl, you should only have vmdl_c left. Convert it to mesh and see that it worked
![image](https://user-images.githubusercontent.com/54669564/122030527-86037100-cdd6-11eb-8e17-fdf4d7efbdff.png)
( precisely because of this, the facepunch and valve models do not cause an error when converting, they do not have a source of files that the engine could refer to ) Although there is a workaround, I still insist on fixing this bug.

**Comment by aylaylay** [comment]
Just pushed a fix for this, please close the issue if it works for you and you're happy with it

**Comment by gabengaGamer** [comment]
Thank you :3
