### ISSUE TITLE
Add support for Shadow Inset

### ISSUE THREAD

**Issue by 8char** [Facepunch/sbox-issues#3649]
### For?

S&Box

### What can't you do?

I'm trying to do a very simple inset box-shadow using css `box-shadow: 0 0 128px 48px rgba(0,0,0,1) inset;`, however it seems like s&box currently doesn't support it.

### How would you like it to work?

Expect it to work, just like how all of the major browsers supports shadow insets.

### What have you tried?

I've tried using four empty elements, placing them around what I would want to have the shadow inset on, and game them the same properties, however this yields a slightly different result with the corners overlapping creating for some extra dark areas.

**Comment by xezno** [comment]
Added, let me know if there's any problems.

![image](https://github.com/Facepunch/sbox-issues/assets/12881812/0d13fe53-f0dc-4cb7-9f22-2da7b97fbf62)
