### ISSUE TITLE
vmdl compiling errors if same filepath exists in different gamemode folder

### ISSUE THREAD

**Issue by Nebual** [Facepunch/sbox-issues#365]
**Describe the bug**

Compiling assets in-game, such as vmdl -> vmdl_c, fails and spams errors at the main menu indefinitely, dropping fps to 10, if the same model path is found in a different addons/ folder.

**To Reproduce**

1. Duplicate a gamemode folder in addons/ (eg. a testing branch)
2. Delete a `.vmdl_c` (or probably any asset's _c) so it needs to be recompiled
3. Launch `sbox-dev.exe`

Sometimes it happens to pick a consistent modelpath and works, its probably easier to reproduce with additional copies, or maybe the gamemode naming order matters.

**Expected behavior**

Asset compiling either only uses assets within a given gamemode folder, or at least prioritizes the version within the same folder if there's multiple.

**log output**

```
2021/06/15 19:04:06.337	AssetSystem	Reloading Resource [1/1]: models/weapons/toolgun.vmdl	
2021/06/15 19:04:06.337	AssetSystem	On-demand recompile of asset models/weapons/toolgun.vmdl	
2021/06/15 19:04:06.337	AssetSystem	 -> reason: Resource Compile Failed	
2021/06/15 19:04:06.337	AssetSystem	Recompiling resource asset: 'models/weapons/toolgun.vmdl'	
2021/06/15 19:04:06.337	ResourceCompilerSystem	- addons\nebtown-wirebox\models\weapons\toolgun.vmdl	
2021/06/15 19:04:06.337	ResourceCompilerSystem	Error during compile: Invalid full path 'm:/steamlibrary/steamapps/common/sbox/addons/nebtown-wirebox/models/weapons/toolgun.vmdl' registered during compile - the relative path 'models\weapons\toolgun.vmdl' resolves to a different file: 'm:/steamlibrary/steamapps/common/sbox/addons/wirebox/models/weapons/toolgun.vmdl'	
2021/06/15 19:04:06.397	AssetSystem	ERROR recompiling: 'models/weapons/toolgun.vmdl'	
2021/06/15 19:04:06.397	AssetSystem	WARNING: Failed on-demand recompile for asset models/weapons/toolgun.vmdl
```

**Comment by MrBrax** [comment]
yeah i think this is what happened to me a few days ago, but with materials, it started confusing the tga's between addon folders

**Comment by Nebual** [comment]
I believe this is still an issue.
