### ISSUE TITLE
Overload for Panel.Add.Icon to specify class

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#367]
**What can't you do?**
Set class of icon in constructor.

**How would you like it to work?**
Be able to set class of icon panel on creation similar to how labels and normal panels work rather than having to assign it and then add the class.

**What have you tried?**
Panel.Add.Icon only takes on argument

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by louiefox** [comment]
This has been fixed, thanks.
