### ISSUE TITLE
Baking reverb in hammer causes the game to crash.

### ISSUE THREAD

**Issue by waffles187** [Facepunch/sbox-issues#368]
**Describe the bug**
When baking reverb on a map in hammer, the game will crash. I've tried setting the parameters to different values but it always closes with no error messages.

**To Reproduce**

1. Open a map in hammer
2. Click on 'Steam Audio'
3. Click on 'Bake Reverb...'
4. Click on 'Ok'

**Expected behavior**
Reverb is baked and the map can be played with sounds echoing in rooms.

**Comment by PixelQubed** [comment]
This is important imo. Having reverb changes the sound dynamic in an important way. I have no idea why this is broken.

**Comment by aylaylay** [comment]
I have stopped it from crashing but you'll have to test it to see if the data is actually used because I have no idea.

You can try adding more entries to scripts/surfaceproperties_steamaudio.txt, if alyx has that file, it's possible you could use that.

**Comment by aylaylay** [comment]
I've enabled everything I can see to allow reverb but I'm unable to hear any difference, let me know if you can make a map with it working.

**Comment by PixelQubed** [comment]
Ill have a go, thanks layla.

> 
> 
> I've enabled everything I can see to allow reverb but I'm unable to hear any difference, let me know if you can make a map with it working.

**Comment by aylaylay** [comment]
I managed to get it to work, reverb node needs to be in the vmix, I'm not sure yet how to do this properly though because it needs to be disabled when the map has no baked reverb otherwise there will be silence.

**Comment by walllable** [comment]
Interesting, I didn't know vmix was actually used for anything currently.

**Comment by PixelQubed** [comment]
> 
> 
> I managed to get it to work, reverb node needs to be in the vmix, I'm not sure yet how to do this properly though because it needs to be disabled when the map has no baked reverb otherwise there will be silence.

Well I tried the reverb calc in my map and it works nicely, only problem is that surfaces havent been set up to reverb correctly so everything is kind of muffled.

**Comment by aylaylay** [comment]
Yeah I don't know if I'm just using it incorrectly in the vmix or you just have to tweak the surfaces. 

You can do snd_steamaudio_reverb_simtype 0 to enable dynamic reverb and change surfaceproperties_steamaudio.txt and reload the map to try out different values

**Comment by aylaylay** [comment]
So this is fixed but it will be decided if we even keep steam audio reverb, I think it's shit

**Comment by walllable** [comment]
I think it's worth keeping and seeing if there's any way to improve its implementation here. This video does a pretty good job of showing how good it can sound if it's got a decent implementation, particularly the HRTF/3D audio and occlusion behind walls.
https://youtu.be/t63n7khEwOo?t=13

**Comment by waffles187** [comment]
I remember in HL:A you need to do "Generate Probes" before baking reverb. Maybe that's why it sounds somewhat muffled?

**Comment by aylaylay** [comment]
This is something that will have to be discussed. Might be worth closing this issue as it doesn't crash anymore and start a discussion instead.

**Comment by waffles187** [comment]
It's started crashing again for some reason. I could still close it though if more audio work needs to be done first.
