### ISSUE TITLE
The First Cubemap Entity That is Placed in a Map Will Always Show Up When Transitioning into a Different Cubemap.

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#369]
**Describe the bug**
The first combined light probe or env_cubemap you placed in a map will show up when you or an object is transitioning into a different cubemap.

**To Reproduce**
This bug affects every single map, but I made a map to showcase this bug.
[maps.zip](https://github.com/Facepunch/sbox-issues/files/6671407/maps.zip)

**Videos**
The first combined light probe I placed is in this red room. In the video, It shows the cubemap from the red room always shows up when transitioning into different light probes. 

https://youtu.be/IjfXkNA3FTo

**Additional context**

I think this bug was introduced into the game around the time when the new player pawn was added. Also, I think the engine is forgetting the last cubemap you or an object was in. This currently effects non-static entities Players, physics props, dynamic props, decals, etc.

**Comment by piqey** [comment]
I have been unable to get any cubemaps to cast upon specular surfaces at all. I also noticed that lighting previews for cubemaps baked in-editor are saved to the maps directory of the last alphabetically sorted addon folder instead of the addon that contains the map I'm baking. Hesitant to open a new issue as cubemaps do seem to have a good number of problems at the moment.

**Comment by justynboi** [comment]
Another bug that is worth mentioning. Is also broken for me.
![image](https://user-images.githubusercontent.com/17112771/122598392-c400cf00-d03a-11eb-8662-76c00d46bc5b.png)

**Comment by justynboi** [comment]
Looks like this bug also affects world geometry. For Example, A mesh is not touching any combined light probes, so the mesh will use the first placed combined light probe's cubemap.

**Comment by justynboi** [comment]
If you have your combined light probe perfectly fit with your room dimensions. The parallax would not work for the floor, walls, and ceiling.

![sbox-dev_EYyJNRcem6](https://user-images.githubusercontent.com/17112771/128645541-9a0d47a3-61e5-4923-9b6b-feddbff22fcd.png)

https://user-images.githubusercontent.com/17112771/128645848-9bca6582-745d-4606-91fe-82d8139a53f6.mp4

To get around this problem. You have to extend the light probe box way out.

![sbox-dev_V0NGSzkLE2](https://user-images.githubusercontent.com/17112771/128645857-df1e37d7-57f6-4fc2-a76b-299da4cca028.png)

https://user-images.githubusercontent.com/17112771/128645860-b88b1688-6358-4971-86a6-9343ebb7da17.mp4

This is not really efficient since it mess up the parallax and could assign other meshes with the wrong light probe since this box is big.

[cubemapbug2.zip](https://github.com/Facepunch/sbox-issues/files/6951484/cubemapbug2.zip)

**Comment by justynboi** [comment]
This bug also messes up baked specular from light probes as seen in these screenshots.

s&box
![image](https://user-images.githubusercontent.com/17112771/134727895-4e0807d9-4c57-416e-b2c3-4fbf160dba22.png)

Alyx
![image](https://user-images.githubusercontent.com/17112771/134727964-c88d55ad-2ed6-4f43-a948-cb6f75502149.png)

**Comment by QuackCocaine** [comment]
I'm getting some very strange flickering artifacts on textures with the probes which wasn't an issue the day before the shader recompile.

https://streamable.com/s1u8cb



Compiled map and source
[cubemapbug2.zip](https://github.com/Facepunch/sbox-issues/files/7377178/cubemapbug2.zip)

**Comment by justynboi** [comment]
Technically this specific bug has been fixed so I'm closing this, but there many other cubemap bugs.

https://github.com/Facepunch/sbox-issues/issues/1484
https://github.com/Facepunch/sbox-issues/issues/1482
https://github.com/Facepunch/sbox-issues/issues/489
https://github.com/Facepunch/sbox-issues/issues/1476
