### ISSUE TITLE
Package Selection should be streamlined and support version selecting

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#3693]
### For?

S&Box

### What can't you do?

The current UI for referencing packages is very confusing, as it simply takes a string and doesn't communicate that you can or can't do certain things.
![image](https://github.com/sboxgame/issues/assets/5159369/6219da52-7fa7-48e4-b13c-8c55f75c4481)

### My Main Problems:
- You can ([according to garry](https://github.com/sboxgame/issues/assets/5159369/b4a733c7-6424-492f-9319-cd09658c5bde)) specify a specific version of an asset using the format `facepunch.code#version`. However, these version numbers are seemingly random so you have to go out of your way to find the version id through the url of the version on asset.party website.
![image](https://github.com/sboxgame/issues/assets/5159369/5f088794-40c3-47a8-bac9-a3fa9360ad5b)
- You cannot use collections. However, if you enter the ident of a collection, it will download the entire collection (causing s&box to hang) and upon the downloads completion, it will give you an error (as it is disallowed)
- You have to enter strings. This is obviously very error prone and is just not very good UX.

### How would you like it to work?

The current textbox selectors:
![image](https://github.com/sboxgame/issues/assets/5159369/b0643927-18e2-46c9-8ba4-6bf147ed86ed)
should be replaced with the selector used for the "Parent Game" option (since it works well and already exists):
![image](https://github.com/sboxgame/issues/assets/5159369/b9660b4a-ccdc-4727-bb6a-b1d1579e7618)

However, the game select menu should instead be the full-on asset browser:
![image](https://github.com/sboxgame/issues/assets/5159369/62f2d0dd-40c6-473d-8925-8a074fb9ed74)

If the asset you click on is not a collection, another menu opens asking which version of the asset you would like to use (this is ***especially*** helpful for libraries):
![image](https://github.com/sboxgame/issues/assets/5159369/3da64175-c125-45f4-b261-79c1c64c62eb)

If the asset you clicked on is a collection, it could open a list with all items checked by default asking which assets you want to reference from the collection.

![image](https://github.com/sboxgame/issues/assets/5159369/fc88bdaa-4c74-4235-b693-0cb682b921a3)

If branches were to ever be introduced for games/addons/libraries then it would also be nice if this menu would let you select a branch as well.

### What have you tried?

I have tried the various methods mentioned throughout (manually searching for asset idents on asset party, finding version numbers on asset party, and trial-and-error to learn that you can't use things such as collections)

**Comment by trundlr** [comment]
I'd like to see a more cohesive workflow for versioning in general.

Currently when you upload something to asset.party, it is instantly public and what new users download.
I would prefer a scenario where you can upload, give it a [semantic version](https://semver.org/), and then choose set the live/default version at your own leisure. Furthermore, it would be nice to allow a "staging" branch that members of your org can access.

For example:
- I have Grubs uploaded and public. I want to upload a new update 2.0, but before it is made liveI want to playtest this version with the dev team to make sure there are no obvious issues.
- I upload 2.0, but the existing version 1.9 is still selected as the live version until I change it.
- I can create a private game on the staging version and play it with my team.
- After playtesting, I decide it is good to go live. A nice bonus feature would be able to schedule when the live version changes.

For the purpose of libraries, semantic versioning would make it very easy to track and share with consumers of the library. Furthermore, you could tie it to GitHub releases in the case of an open source library.

**Comment by CarsonKompon** [comment]
The new Library Manager is basically what i requested 1:1 😄
