### ISSUE TITLE
Trace.WithinWorld

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#3720]
### For?

S&Box

### What can't you do?

Perform a fully featured and optimized Trace within a custom `PhysicsWorld` by default.

### How would you like it to work?

Add it to a Trace struct so that you can trace within a custom `PhysicsWorld`.
```csharp
var pw = new PhysicsWorld();

var tr = Trace.Ray(AimRay, 1024f)
    .Ignore(this)
    .WithinWorld(pw)
    .Run();
```

### What have you tried?

There doesn't seem to be any built-in solution for this.

### Additional context

This would be extremely useful if you are introducing physics to a `SceneWorld` (even as simple as 2D) as you wouldn't have to rewrite features that already exist for the primary `PhysicsWorld`, or design your own collision tree to try and optimize tracing manually.

**Comment by Diddykonga** [comment]
The Editor version of `Trace` already allows passing in a specific `MapWorld` into the `.run(MapWorld world)` method.
Just need an Game version equivalent.
