### ISSUE TITLE
Iterating needlessly in Sandbox.UI.NavigatorTargetAttribute

### ISSUE THREAD

**Issue by PatrickRatzow** [Facepunch/sbox-issues#375]
Not really a bug, but it's not a feature request either, no idea where to post this.

**Describe the bug**
Sandbox.UI.NavigatorTargetAttribute.FindValidTarget does not make use of the delegate in FirstOrDefault, instead using Where. I imagine there might be cases where a specific attribute can end up having hundreds of usages in larger games, so might as well do as little work as possible.

```cs
public static NavigatorTargetAttribute FindValidTarget( string url )
{
	return Library.GetAttributes<NavigatorTargetAttribute>()
		.Where( x => x.CanServeUrl( url ) )
		.FirstOrDefault(); 
}
```

**Solution**
Make use of FirstOrDefaults delegate parameter overload.
```cs
public static NavigatorTargetAttribute FindValidTarget( string url )
{
	return Library.GetAttributes<NavigatorTargetAttribute>()
		.FirstOrDefault( x => x.CanServeUrl( url ) );
}
```

**Comment by Rohansi** [comment]
LINQ is lazy so they actually iterate the same number of times. This pretty much just saves an enumerator allocation.
