### ISSUE TITLE
SCSS hotload fail shows success notification

### ISSUE THREAD

**Issue by zeo** [Facepunch/sbox-issues#379]
**Describe the bug**
Whenever you make a syntax in a hotloaded scss file, it gives you a success notification, even tho it silently failed in the background. It still shows the parse error in the console.

**To Reproduce**

1. Make a syntax error in a scss file
2. Wait for it to hotreloaded
3. It will show a hotreload success notification but give the parse error in the console

**Expected behavior**
Give an error notification instead of a success notification but keep the parse error in console.

**Additional context**
Example syntax error
```scss
$font = 'Montserrat'
```

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
