### ISSUE TITLE
Top-Down Template 2nd Player Movement

### ISSUE THREAD

**Issue by Andrei15193** [Facepunch/sbox-issues#3795]
### Describe the bug

The top-down template is bugged in the sense that when creating a server where someone else joins, the player that joined moves extremely weird. At the root of the problem it may be the camera rotation that is being ignored for the player that is not the host.

### To Reproduce

1. Open the editor and create a new project using the Top-Down template
2. Open the console type `sv_lan 1` to allow local connections
3. Open a 2nd instance of sbox and in the console type `sv_lan 1` for the same reason
4. Host a game from the 1st instance (editor instance)
5. Join the game from the 2nd instance (client instance) by typing `connect localhost` in the console
6. Move around once joined

### Expected behavior

The player that joined the server is able to move around the same way the player hosting the server is.

**Comment by DevulTj** [comment]
This template does not exist any more.
