### ISSUE TITLE
Stuttery/Glitchy audio

### ISSUE THREAD

**Issue by TmanGamer** [Facepunch/sbox-issues#3797]
### Describe the bug

The audio has stuttering nonstop.

### To Reproduce

Play any game with audio

### Expected behavior

The audio should be crisp and clear without any stuttering.

### Media/Files

Specs:
![image](https://github.com/sboxgame/issues/assets/34608057/51cb7996-ab1f-4b67-bfdb-4fd349e8f40a)
![image](https://github.com/sboxgame/issues/assets/34608057/1bd3559d-7acc-4e52-ba1f-33b649ee9ad3)

### Additional context

I am running on Windows 11. 
Specs will be in **Media/Files**

**Comment by DoctorGurke** [comment]
Are you able to capture this on a video recording? Sound works fine for me

**Comment by TmanGamer** [comment]
> Are you able to capture this on a video recording? Sound works fine for me

Uploading it to gofile now

**Comment by TmanGamer** [comment]
[Here is the video](https://gofile.io/d/T6ASjX)

**Comment by TmanGamer** [comment]
Any updates?

**Comment by TmanGamer** [comment]
I also found that its becoming hard to play games like GarryWare because the audio lags behind.

**Comment by paradoxuum** [comment]
I have the same issue. The audio stuttering/crackling seems to be much worse when the audio device's sample rate is 48 kHz, so I'd recommend setting it to 44.1 kHz if it's not set to that already.

As far as I can tell, it's not a hardware (i.e. CPU/GPU) issue either, as this happens on my system which has a 7800x3D and a 4070 Ti, which (I assume?) are far above the requirements for the game.

I'm also using an audio interface (MOTU M2), so it could also be a hardware issue related to the audio device.

I've recorded two videos showing the comparison between the two sample rates. I'm also running the game on the lowest video settings to try and minimise any impact that may have on the audio.

44.1 kHz:
https://streamable.com/qc4vk7

48 kHz:
https://streamable.com/ja7hws

**Comment by TmanGamer** [comment]
It must have been a syncing issue, the issue hasn't presented itself for a while now. I will close this issue now.
