### ISSUE TITLE
Source 1 legacy entities broken or mismatched by fgd autogen

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#380]
Source 1 legacy entities were removed from the core fgd I guess under the assumption that the auto generated fgds were okay, but it's broken a few things in Hammer for me and others.

I don't think FP should be bothering with supporting legacy entities from 1999 (there are 4 ways to make a door and so many different trigger types), sbox has the opportunity to ditch them all and make simple easy to use entities - anyway if they are supported then they should behave as expected.

Couple of things that have caused issue for me and others that I've noticed, there's probably more:
* func_brush is missing render properties that are used internally by the map builder to control lighting (these should almost always exist on all static brush based entities):
  * base(RenderFields)
  * vrad_brush_cast_shadows
* prop_door_rotating is incorrectly marked as SolidClass now making it impossible to use correctly in Hammer.

Also various descriptions, help texts and default values weren't carried over.

I threw up some Hammer attributes on the [API donation](https://github.com/Facepunch/sbox-issues/discussions/348#discussioncomment-873281) thread that handle RenderProperties and some other things.

**Comment by justynboi** [comment]
info_particle_system is broken. 
![image](https://user-images.githubusercontent.com/17112771/122851554-2547cd00-d2dd-11eb-8038-ee4fc6e353c3.png)

**Comment by robotboy655** [comment]
Fixed up prop_door_rotating  and info_particle_system. I couldn't get any of the render properties to work besides render color, so I am considering those to not be affected by the FGD autogen at this moment. If you can make a map that proves me wrong - feel free to.

**Comment by handsomematt** [comment]
I was mainly using the fields to control how Hammer builds lighting, it was a hacky solution and better solved by purely using the world mesh alongside an entity creating significantly better results, so `vrad_brush_cast_shadows`, `rendertocubemaps` and `lightmapstatic` shouldn't be added.

Some things from RenderFields would still be useful for brush entities func_brush / func_door, etc.. like:
* fgd: `rendercolor` -> C# Entity.RenderColor
* fgd: `disableshadows` -> C# Entity.EnableShadowCasting
* fgd: `disablereceiveshadows` -> C# Entity.EnableShadowReceive

There are various inputs on these too.

**Comment by robotboy655** [comment]
`EnableShadowReceive` is not currently functional, `disableshadows` and `rendercolor` are added. Most of the keyvalues got their descriptions and titles fixed. If there's anything I missed or something that needs doing/is missing, let us know.
