### ISSUE TITLE
font-family doesn't support font fallbacks

### ISSUE THREAD

**Issue by Ryhon0** [Facepunch/sbox-issues#381]
**Describe the bug**
The `font-family` CSS property doesn't work when you specify multiple fonts, likely trying to use a font with the value of this property

**To Reproduce**

Add `font-family: Font1, Font2;` to a CSS file.

**Expected behavior**

CSS uses `Font1`, when this font doesn't have a glyph, it falls back to `Font2`

**Screenshots**
![fallback](https://user-images.githubusercontent.com/21126698/122827079-37793980-d2e4-11eb-870c-d477dd502008.png)

**Comment by Jac0xb** [comment]
Won’t the font always be downloaded before the game is loaded?

**Comment by garrynewman** [comment]
Why do you need a fallback?

**Comment by Ryhon0** [comment]
In this example I'd like the emojis to be in the Twemoji font, while the rest of the text of the text would be in the Poppins font as Twemoji only has glyphs for emojis. You could also use some fancy font that only has a-z A-Z 0-9 glyphs to display something like usernames which can have any characters in them and a similar looking one for missing characters

**Comment by garrynewman** [comment]
I'm not sure if our backend library would support that, but I'll check it out

**Comment by Ryhon0** [comment]
bump

**Comment by handsomematt** [comment]
I don't see why you would need fallbacks when you package the fonts files directly in your game?
