### ISSUE TITLE
Hammer prefabs (and tilesets) on asset.party

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#3814]
### For?

Hammer

### What can't you do?

I want to be able to share geometry made in hammer on asset party easily, keeping whatever textures are applied as well. this could be useful for things like roof tiles, pillars, and other common building architecture

### How would you like it to work?

1)create a hammer prefab
2)right click the prefab and save it as a file somewhere locally
3)upload the prefab to asset party
4)others can drag the prefab into hammer without needing to convert it to hammer geometry and deal with the issues that causes

### What have you tried?

importing into modeldoc and uploading the geometry as a model

**Comment by GunnarKafel** [comment]
This would also be super useful for sharing prefabs with properties, so the user has more control instead of having to reconstruct everything by hand

**Comment by Jammie3d** [comment]
Tile meshes would be very nice to have too.

**Comment by FireKeep-HLA** [comment]
This would make it super easy to upload complex custom asset configurations for anyone to use!

**Comment by Niconami** [comment]
This would be good for certain logic as well

**Comment by DrakeFruit** [comment]
Probably no longer needed
