### ISSUE TITLE
Add complex blend shader

### ISSUE THREAD

**Issue by 9yz** [Facepunch/sbox-issues#382]
### What can't you do?
The current blend shader is not very feature-rich. It just has support for 2 basic materials (color, normal, and roughness) and a blend mask. This is pretty limiting, especially for people who want to make more complex environments, such as terrain or complex blended surfaces. Adding a complex blend shader (or improving the current one) would be extremely useful.

### How would you like it to work?
Ideally, a complex blend shader would support *at least* 4 materials with their own color, normal, roughness, and height (for blending and parallax) textures. Additionally, support for more than 4 materials, tint masks (the basic blend shader doesn't support this), detail textures & normals for each material, and AO/metallic textures would be great.

### What have you tried?
The only way to blend multiple materials right now is to split a face and have a different blend material on each one. This isn't great, as you have to create a new material for every combination and even then you can't have more than 2 materials blending in the same place. You also can't use tint masks or metallic textures with a blend.

### Additional context
This shader may seem excessive or needlessly complex, but the more different options and flexibility that can be included, the more useful it will be (even if only a few people use it).

**Comment by samzanemesis** [comment]
I have added a Blendable shader with the same PBR feature set as Complex, it'll also be used as a guideline for the future user shader workflow
