### ISSUE TITLE
Fonts sometimes fail to load for clients

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#3826]
### Describe the bug

Could be related to https://github.com/sboxgame/issues/issues/3427

I have never experienced this issue personally, but whenever people play Grubs I notice their fonts are often missing. The same font is used in the menu and the game. Usually it seems that the menu font loads perfectly fine but the font stops working in-game. I have confirmed that the font is being included for both menu files and resource files.

This started happening around the time the menu stuff changed

### To Reproduce

1. Open Grubs
2. Look at text
3. If it's default font, something is wrong! It should be Londrina Solid

### Expected behavior

The font should work

### Media/Files

How it should look
![image](https://github.com/sboxgame/issues/assets/57276947/74b7cbd9-931c-4abf-850c-f359f73864bb)

How it looks sometimes
https://cdn.discordapp.com/attachments/825835778474770442/1139328872282861578/Desktop_2023.08.10_-_15.44.47.02.DVR_Trim.mp4

**Comment by matekdev** [comment]
This is still happening to users, it seems like it is most prevalent to occur if you are launching the game for the first time.

**Comment by trundlr** [comment]
This is _probably_ fixed, but I will re-open or create a new issue if I observe it happening again.
