### ISSUE TITLE
Weird empty window appears with the Welcome window

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#3828]
### Describe the bug

Some weird empty window emerges on the Welcome screen of s&box dev tools, which can be seen only when choosing the active window with a shortcut like alt tab or win tab.

### To Reproduce

1. Open s&box dev tools
2. Press Alt+Tab or Win+Tab.

### Expected behavior

It shouldn't exist.

### Media/Files

![sbox-dev_6a6zDrWdxw](https://github.com/sboxgame/issues/assets/6745157/cf0e4630-ef5f-4016-b58a-25e31167c1c8)

### Additional context

I can't say it's an important issue, but it's still annoying to stumble upon this window when alt-tabbing.

I'm using Windows 10 with .NET 7.0.9.

**Comment by xezno** [comment]
This was fixed a while ago when Matt made the welcome window its own standalone thing
