### ISSUE TITLE
Crash: Map is crashing with specific gamemode

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#383]
**Describe the bug**
After one or two hours of debugging, I came to result that my game didn't broke because of the gamemode's code, but the map keeps crashing the game. ("Office" map by bakscratch)
Hard to find the reason. If I try to start my gamemode (https://github.com/TTTReborn/ttt-reborn/tree/544a0758e63d28436107da8e1a82315f5fce6d3d) with the Office map two times in a row, it crashes to the desktop. It doesn't happen with another map, but it doesn't happen with another gamemode as well :smile:
It compiles, last hint "Client Startup". Last log entries:

```txt
[...]
2021/06/22 18:47:00.701    Engine    Failed to transfer KV3 data for resource 'particles/entity/env_explosion/explosion_emp.vpcf' - Failed to allocate an instance of class 'C_INIT_AgeNoise'
[...]    
2021/06/22 18:47:00.825    Generic    Skipping path mount, already mounted: C:\Program Files (x86)\Steam\steamapps\common\sbox\download\http\files.facepunch.com\sbox_org_baks_office_964b8ea2 GAME    
2021/06/22 18:47:01.688    Engine    No conversion from utlstringtoken to string at the moment!    
2021/06/22 18:47:01.688    Engine    No conversion from ehandle to string at the moment!    
2021/06/22 18:47:01.688    Engine    No conversion from utlstringtoken to string at the moment!    
2021/06/22 18:47:01.688    Engine    No conversion from ehandle to string at the moment!    
[...]
2021/06/22 18:47:01.723    HostStateManager    Loading (baks.office)    
2021/06/22 18:47:01.747    Generic    "Alf21" has joined the game    
2021/06/22 18:47:01.874    Server    SV:  Sending full update to client Alf21 (reason:  initial update)    
2021/06/22 18:47:01.964    Generic    /ui/weapons/ttt_knife.png: Could not find file `/ui/weapons/ttt_knife.png`.    
2021/06/22 18:47:02.041    Client    CL:  Signon traffic "client":  incoming 495.999 KB [24 pkts], outgoing 545 bytes [19 pkts]    
```

**To Reproduce**

1. Get TTTReborn from GitHub (https://github.com/TTTReborn/ttt-reborn/tree/544a0758e63d28436107da8e1a82315f5fce6d3d)
2. Start a game with the "Office" map by bakscratch
3. Disconnect and quick connect (with the same settings)
4. It should crash to the desktop

**Expected behavior**
Obviously, no crash :D

**Additional context**
If you need more information, please don't hesitate to ask. Thanks :)

**Comment by garrynewman** [comment]
Does this still happen for you? I followed your instructions and didn't get any crashes

**Comment by Alf21** [comment]
Yea I saw you assigned that PR yesterday, so I tried replicating this issue, but currently I'm still trying to get map downloads to work as sbox seems to not download any new map :D Gonna give you an update asap as I get it working :) Thank you for your concern

**Comment by Alf21** [comment]
Okay tested with the branch <https://github.com/TTTReborn/ttt-reborn/tree/544a0758e63d28436107da8e1a82315f5fce6d3d> again and it still crashed (maybe you used the master branch instead of the branch at commit-state of merged # 44 PR).

The newest branch does not crash the game, so I did a lot of tests getting back to the change that had fixed that crash and I came to the following result:
The crash was fixed with this commit <https://github.com/TTTReborn/tttreborn/tree/4ad9ff5c2776efc46991fcbfd9683457d82fdd71> / this PR <https://github.com/TTTReborn/tttreborn/pull/86>.

As you can see, we just modified the HUD to support Hotloading. Pretty weird and lucky that it was fixed by "just programming", but I can't explain what is causing this as I do not do any hotloading at all nor added any destroy method to the Hud.

**Comment by garrynewman** [comment]
I found it, was crashing in shatter glass. Since we don't use this I disabled it.

**Comment by Alf21** [comment]
Okay tested, it's fixed, thanks!
