### ISSUE TITLE
Fetching the gamemode from GitHub when name is not "master"

### ISSUE THREAD

**Issue by TimGoll** [Facepunch/sbox-issues#385]
**Describe the bug**

Recently GitHub switched their default branch name from "master" to "main". However s&box tries to fetch from the master branch. While it is solvable on our side by renaming the branch, it would be better to support the standard GitHub naming convention:

**To Reproduce**

1. Create a GitHub repositiory with a new gamemode
2. Link it to the s&box gamemode system
3. Try to launch ist

**Expected behavior**

s&box should support the default branch of GitHub since master is no longer used.

**Screenshots**

![image](https://user-images.githubusercontent.com/13639408/122973683-c7c18800-d391-11eb-830d-7a543d93b07e.png)

**Comment by TimGoll** [comment]
For those of you disagreeing with me. This is not a discussion if "master" or "main" is the better name. But since this game is built with GitHub in mind, it should also use the GitHub naming convention. It is kind of strange to expect every developer to rename their branch and not just support both.

**Comment by Rohansi** [comment]
This is a good spot. However it's not a case of just replacing "master" with "main". People could use any name as a branch.

**Comment by xezno** [comment]
Does setting the backend URL to `https://github.com/TTTReborn/ttt-reborn/tree/main` not work?

**Comment by TimGoll** [comment]
> Does setting the backend URL to `https://github.com/TTTReborn/ttt-reborn/tree/main` not work?

![image](https://user-images.githubusercontent.com/13639408/123048692-f7f34000-d3fe-11eb-84d2-0ef995d93fc9.png)

Seems like it is working. I did not change the branch name, but the error implies that it should work.

**Comment by TimGoll** [comment]
> This is a good spot. However it's not a case of just replacing "master" with "main". People could use any name as a branch.

I'd suggest just using whatever default branch the repository is using

**Comment by rtm516** [comment]
GitHub and git allow the default branch to be either, but yes it should 100% pick it up from the repo.
As for your repo you are using `master` and the below works fine so there should be no issues with the request, maybe it was down to a bad internet connection or the GitHub API being down?
https://api.github.com/repos/TTTReborn/ttt-reborn/branches/master

**Comment by TimGoll** [comment]
We switched to "master" to make it usable. We previously had the branch namen "main".

**Comment by Rohansi** [comment]
This should be fixed now - give it a few minutes to push to Steam. It will now use the default branch unless you set it to use a branch-specific URL (ex: https://api.github.com/repos/TTTReborn/ttt-reborn/branches/master).

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
