### ISSUE TITLE
[Shadergraph] Ability to set the ranges for float2 & float3 variables

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#3851]
## For?

Other

## What can't you do?

Currently you are unable to specify a range ( Min Max )  from within shadergraph for both float2 & float3 nodes . The only _Constant node_ that lets you set this is Float. So it would be nice to be able to specify a Range for these two nodes.

## How would you like it to work?

A _Range Property_ right under the _Value Property_  which allows you to set a Range for the Float2 or Float3 and thus sets the corresponding Range2 or Range3 for the variable in the generated shader.

## What have you tried?

Nothing as from within shadergraph you cannot specify a range for a Float2 or Float3 Variables.

**Comment by aylaylay** [comment]
Done
