### ISSUE TITLE
Automatic prop population on meshes (detail props)

### ISSUE THREAD

**Issue by 9yz** [Facepunch/sbox-issues#386]
### What can't you do?
Source 1 had a nice but underused feature called [detail props](https://developer.valvesoftware.com/wiki/Detail_props). It let you automatically populate sprites and models onto displacements. This was commonly used for grass but could be used for many things, like rocks, trees, and trash. Source 2/S&box doesn't have this. 

### How would you like it to work?
Ideally, you would be able to create a file (possibly through a separate tool) that let you define which models to place, and for each model:
- Rotation, scale, and offset (and the ability to randomize these)
- % chance of being placed
- What surface slope to place it on
- What vertex alpha to place it on (for painting the same way you paint blend materials
- How far away to fade out
- Placement mask (could be defined inside the material)

You would then be able to select this file in your material's properties (similar to how you select a subrect file for hotspots)

### What have you tried?
Hammer already has a pretty good sprinkle tool built in, but it requires you to manually paint it on all surfaces you want the props on. It also gets laggy pretty quickly when painting and doesn't automatically update if you change the surface it's painted on.

**Comment by garrynewman** [comment]
It feels like this could be done easily in addon code, I'm not sure if there's a great benefit to us making it?

**Comment by 9yz** [comment]
Having proper, modeled grass (as opposed to just a grass texture on a surface) seems like something that a lot of people would use. This is a pretty common feature in other engines, so it's actually a bit surprising that s2 doesn't already have it.

**Comment by gvarados1** [comment]
This should be a default feature. Anyone who's made terrain in source 2 knows the sprinkle tool is awful for this.
