### ISSUE TITLE
Add a way to get the audio level from a MusicPlayer instance

### ISSUE THREAD

**Issue by wgaylord** [Facepunch/sbox-issues#3867]
### For?

S&Box

### What can't you do?

Access the "Level" of a sound being played with a MusicPlayer instance.

### How would you like it to work?

This would work similar to https://wiki.facepunch.com/gmod/IGModAudioChannel:GetLevel to get the audio level of from the sound file being played at that moment in time. 

This could be used to change on screen indicators for how loud a sound is (equalizer bars?), or for my use case implement a form of Automatic Level Control to prevent player provided sounds from being extremely loud or extremely quiet. 

### What have you tried?

I looked thru the api docs on asset.party and couldn't find any way to work around this. 

### Additional context

The level value should ideally not be affected by the volume control.

**Comment by aylaylay** [comment]
I'll probably add fft to this

**Comment by aylaylay** [comment]
Added
https://asset.party/api/Sandbox.MusicPlayer.Amplitude
and
https://asset.party/api/Sandbox.MusicPlayer.Spectrum

**Comment by krotter0** [comment]
MusicPlayer.Spectrum has a length of 1024, but above index 512 all values are exactly 0 on my end.

**Comment by aylaylay** [comment]
Spectrum returns 512 now and should work better
