### ISSUE TITLE
System.Threading.Task: Issue with `Sandbox.GameTask`, `Game.Shutdown()` and `TaskCanceledException`

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#387]
**Describe the bug**
Currently, it's hard canceling a Task properly. Most of all, the same error is printed when disconnecting from a game regarding not canceled task.

I came around with the following "ugly" fix:

```cs
private bool _isShuttingdown = false;

private async void StartGameTimer()
{
    while (!_isShuttingdown)
    {
        try
        {
            OnGameSecond();

            await GameTask.DelaySeconds(1);
        }
        catch(Exception e)
        {
            if (e.Message.Trim() != "A task was canceled.")
            {
                Log.Error($"{e.Message}: {e.StackTrace}");
            }
            else
            {
                _isShuttingdown = true;
            }
        }
    }
}

// seems not working
public override void Shutdown()
{
    _isShuttingdown = true;

    base.Shutdown();
}
```

Sadly, I can't access `System.Threading.Tasks.TaskCanceledException`, that's why I've to check the `Exception.Message` instead of doing `e is not System.Threading.Tasks.TaskCanceledException`.

Additionally, `Game.Shutdown()` seems not working properly, as the `Task` isn't killed on gamemode's shutdown (keep printing error without setting `_isShuttingdown` to `true` in the `catch`-phrase of `StartGameTimer` fn).

Error ingame without that catch-phrase workaround:
![unknown (2)](https://user-images.githubusercontent.com/11843790/123108071-61dd0b00-d43a-11eb-973f-5466d07d2665.png)

Last but not least, it's unclear why we have the lib `Sandbox.GameTask`, as we can still access `System.Threading.Task`, but not e.g. `System.Threading.Tasks.TaskCanceledException`.

**To Reproduce**

1. Create a Task like
```cs
private async void StartGameTimer()
{
	while (true)
	{
		OnGameSecond();

		await GameTask.DelaySeconds(1);
	}
}
```

2. Start a game and call the funtion `StartGameTimer` starting the `Task`
3. Disconnect from the game

**Expected behavior**
No error or proper error handling, like being able accessing `System.Threading.Tasks.TaskCanceledException` OR getting a working `Game.Shutdown()`.

**Additional context**

As always, don't hesitate to ask for further details if something is unclear.

**Comment by garrynewman** [comment]
Am I parsing this right, is your problem that TaskCanceledException shows?

**Comment by Alf21** [comment]
> Am I parsing this right, is your problem that TaskCanceledException shows?

Cutting it down: yes.

But as you can see in the example, this error shouldn't show endless, because I theoretically "closed" the task on shutdown, that's why I came around with the additional workaround (error checking).

Every GameTask timer has this problem afaik, regarding the feedback of Discord and tests.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Alf21** [comment]
Thanks for taking concern :)

It partially fixed but sadly, it is not working if game is closed (in my situation) on gametimer's tick:
![image](https://user-images.githubusercontent.com/11843790/123675795-6abb4b80-d843-11eb-9c80-8cdb5f482304.png)

The code I used (which is such a way better now anyways):
```cs
private async void StartGameTimer()
{
	ForceRoundChange(new WaitingRound());

	while (!Global.IsClosing)
	{
		try
		{
			OnGameSecond();

			await GameTask.DelaySeconds(1);
		}
		catch (Exception e)
		{
			Log.Error($"{e.Message}: {e.StackTrace}");
		}
	}
}
```

**Comment by garrynewman** [comment]
You're printing that error out. By default it should exit silently if you don't catch it.

**Comment by Alf21** [comment]
> You're printing that error out. By default it should exit silently if you don't catch it.

Oh okay haha, yea that makes sense. So it's still called, but silently... Hmm.. Then I need to add the `TaskCanceledException` check, because error in the tick aren't printed but just break the timer.

If that's nothing you wanna rework too (as it's not as essentially, but being able to access `TaskCanceledException` for a proper check would be cool), feel free closing this issue as well :)
