### ISSUE TITLE
Unable to find an entry point named 'SteamAPI_SteamApps_v008'

### ISSUE THREAD

**Issue by C1AST3Q** [Facepunch/sbox-issues#3873]
### Describe the bug

hello,

i've been trying to acces the game since yesterday and can't seem to even launch it since im getting prelnit error at the launch of the game
error in media below

### To Reproduce

1. go to steam
2. open game
3. get error on launch

### Expected behavior

i would expect for the game to launch normaly

### Media/Files

![image](https://github.com/sboxgame/issues/assets/142639880/5136042b-3670-4a32-8fb1-28dc6ac445c1)

### Additional context

I'm using windows 10 

gpu: GIGABYTE rtx 3060
cpu: AMD Ryzen 5 3500X 
ram: 16GB

**Comment by handsomematt** [comment]
probably pirate steam_api.dll somewhere, probably fixed now we explictly load ours
