### ISSUE TITLE
Incorrect debugging/single stepping

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/sbox-issues#389]
**Describe the bug**
Debugging code with VS seems to be stepping into the wrong locations.

**To Reproduce**

1. Download [invasion.zip](https://github.com/Facepunch/sbox-issues/files/6703206/invasion.zip) and pack it into your addons
2. Start the game with the addon on any map.
3. Attach VS and place a breakpoint on GoapTests.cs:53, this is a place where the breakpoint actually works.
4. Run ```goap_test``` in the console and begin to step in the code.

**Expected behavior**
Correct single stepping behavior.

**Screenshots**
![2021-06-23_18-15-14](https://user-images.githubusercontent.com/5415177/123127060-9a88de80-d452-11eb-9109-099ee0ec6d2a.gif)

**Additional context**
I tried this with VS 2019 16.10.2 and VS 2022 (Preview 17.0.0 1.0)

**Comment by thegrb93** [comment]
I'm also getting source line number differences causing this issue.
