### ISSUE TITLE
[AnimGraph][Mover Node] Selecting "Parameter" for Face Direction doesn't allow for Parameter selection

### ISSUE THREAD

**Issue by SilverDash** [Facepunch/sbox-issues#3898]
### Describe the bug

The Mover Node in the animation graph editor allows for Face Direction selections. 

The parameter option in the drop down doesn't allow you to select a parameter to use.

UI is missing?

### To Reproduce

Go to the animation graph of any model

Add a "mover node"

Select the "paramater" option for the Face Direction drop down.

### Expected behavior

Mover node should show a UI dropdown for parameter selection.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/5953198/83f91a13-11fc-4673-9735-a4e78ff7db70)

**Comment by aylaylay** [comment]
Fixed - you can use parameters now
