### ISSUE TITLE
info_offscreen_movie_texture,point_clientui_world_movie_panel not working

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#391]
Info_offscreen_movie_texture and point_clientui_world_movie_panel entities no longer display video as they did in hl alyx

![image](https://user-images.githubusercontent.com/54669564/123170060-bc9a5500-d482-11eb-9f04-8543fb9cfe43.png)
![image](https://user-images.githubusercontent.com/54669564/123171576-ad1c0b80-d484-11eb-936f-56608f0b4efe.png)

hl alyx example: https://www.youtube.com/watch?v=t2Eiu8oL3b8

**To Reproduce**

1. Create point_clientui_world_movie_panel

![image](https://user-images.githubusercontent.com/54669564/123170954-cc666900-d483-11eb-820b-80fcc8341b64.png)

2. Configure entity as in the screenshot
3. Compile map

The video textures were very useful in hl alyx, I really hope that you can fix it or make a replacement for this entity

**Comment by aylaylay** [comment]
This is something that we wont fix but rather, reimplement.

**Comment by gabengaGamer** [comment]
oh cool
