### ISSUE TITLE
Input.Pressed & Input.Released are broken when using gamepad controller inputs

### ISSUE THREAD

**Issue by Phyksar** [Facepunch/sbox-issues#3914]
### Describe the bug

`Input.Pressed(string action)` returns true each tick when the action is down, in other words it behaves the same way as `Input.Down(string action)`.
`Input.Released(string action)` always stays false and never returns true.

### To Reproduce

```csharp
public override void BuildInput()
{
	if (Input.Pressed("SlotPrev")) Log.Info("SlotPrev pressed");
	if (Input.Pressed("SlotNext")) Log.Info("SlotNext pressed");
	if (Input.Released("SlotPrev")) Log.Info("SlotPrev released");
	if (Input.Released("SlotNext")) Log.Info("SlotNext released");
}
```
These actions are bound to the bumper buttons of the controller.
```
 08:38:20   Client  [185] SlotNext pressed
 08:38:21   Client  [143] SlotPrev pressed
 08:38:21   Client  [17] SlotNext pressed
 08:38:22   Client  [21] SlotPrev pressed
 08:38:22   Client  [27] SlotNext pressed
 08:38:23   Client  [85] SlotPrev pressed
 08:38:23   Client SlotNext pressed
 08:38:23   Client SlotPrev pressed
 08:38:23   Client SlotNext pressed
 08:38:23   Client SlotPrev pressed
 08:38:24   Client  [68] SlotNext pressed
 08:38:25   Client SlotPrev pressed
 08:38:25   Client SlotPrev released
```

### Expected behavior

`Input.Pressed` should only return true when its input state is changed from up to down.
`Input.Released` should return true when its input state is changed from down to up.

### Additional context

I'm using Dualshock 4 via Steam Input emulation and the default input profile for S&box.

**Comment by DevulTj** [comment]
This should be fixed now
