### ISSUE TITLE
[AnimGraph][Turn Helper Node] Selecting "Parameter" for "Turn to Face" doesn't allow for Parameter selection

### ISSUE THREAD

**Issue by SilverDash** [Facepunch/sbox-issues#3917]
### Describe the bug

Identical issue to MoverNode #3898 The paramater drop down doesn't allow for a parameter selection.

### To Reproduce

Go to the animation graph of any model

Add a "Turn Helper node"

Select the "paramater" option for the "Turn to Face" drop down.

### Expected behavior

Mover node should show a UI dropdown for parameter selection.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/5953198/c41c7662-1a30-4a2b-9bbc-74b3b41cb1e2)

**Comment by aylaylay** [comment]
Fixed - you can use parameters now
