### ISSUE TITLE
Post Processing looks more intense with Tonemap Scale and Bloom.

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#392]
I think last week. A update mess up something with the Tonemap Scale and Bloom. Now if you have a post processing volume in your map. The tonemap and bloom looks too bright and intense in your map.

Example. This screenshot is from June 10.
![sbox_0016](https://user-images.githubusercontent.com/17112771/123172433-272f9e80-d44b-11eb-88f8-58123754efba.png)

Same map, but the screenshot is from today. (June 23)
![sbox_0020](https://user-images.githubusercontent.com/17112771/123172530-45959a00-d44b-11eb-8fa0-0e97cfe56c3b.png)

I didn't change any of the settings for the post processing volume and I didn't recompile the lighting for this map. I didn't touch this map during the time of those 2 screenshots.

Also, the camera adjust the tonemap scale way too fast and it looks really bad.

https://user-images.githubusercontent.com/17112771/123173686-f6e8ff80-d44c-11eb-9958-e30049366c7d.mp4

**Comment by garrynewman** [comment]
Is it possible that the post processing just started working again?

**Comment by justynboi** [comment]
Post processing always have been working, but recently every map I made is now strangely brighter. I couldn't pin point what's wrong with it. All I know is just related to the post processing. Maybe standard.vpost_c is different? idk.

I revisited the June 10 build of s&box and you can see there a big difference.
https://user-images.githubusercontent.com/17112771/123288409-8b9b3e00-d4dd-11eb-87fb-4726f148565f.mp4

**Comment by justynboi** [comment]
Looks like today's update fixes the strong tonemap, but now the bloom is weirdly strong. 

Again, Left is from June 10, Right is from Today (June 28)
![image](https://user-images.githubusercontent.com/17112771/123683835-b0afe980-d81a-11eb-8261-5dae61ae8fbd.png)

Closer screenshot of the grate.
![image](https://user-images.githubusercontent.com/17112771/123684340-55322b80-d81b-11eb-93e8-0977b5d0ec2e.png)

**Comment by garrynewman** [comment]
Do you know you can make your own post processing settings?

**Comment by justynboi** [comment]
Nevermind my last comment because I just compared the standard.vpost and basepostprocess.vpost in s&box and Alyx, and it looks like the post processing is working fine now.
