### ISSUE TITLE
Write string of more than 1024 characters

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#393]
**What can't you do?**
Write a string of more than 1024 characters.
![image](https://user-images.githubusercontent.com/16431607/123279708-05dcba00-d500-11eb-82dd-23e5355bda3d.png)

**How would you like it to work?**
Be able to write longer strings, this is useful for sending json over the network etc.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by louiefox** [comment]
Yep its fixed, thanks!
