### ISSUE TITLE
broken snd_event_point entity

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#395]
The snd_event_point sound object, which was recently rewritten in C#, does not work, unlike its direct counterpart snd_event_alignedbox, which was written in C++

![image](https://user-images.githubusercontent.com/54669564/123312555-2ec97300-d531-11eb-839a-9045b7745f5d.png)

Video demonstration: https://www.youtube.com/watch?v=P4jEO3oieNE

**To Reproduce**

1. Create snd_event_point
2. Select audio file 
3. Compile map

**Comment by robotboy655** [comment]
Start on spawn doesn't appear to work, because the sound is played before the player joins the server.

**Comment by gabengaGamer** [comment]
via logic_auto and trigger does not work either

**Comment by robotboy655** [comment]
Non C# entities (Logic entities and many more) cannot interact with C# entities. Buttons and triggers will work, but all the entities are subject to change at this point.

**Comment by gabengaGamer** [comment]
indeed, it will work through a button, but through trigger_multiple or once it will not. Check this: https://www.youtube.com/watch?v=KrL6aPK2XkQ

**Comment by robotboy655** [comment]
Start on/start on spawn should now appear functional.
