### ISSUE TITLE
CSwapChainBase::QueuePresentAndWait() and various other console spam when restarting a game

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#3957]
### Describe the bug

During a long development session, about 3 hours, I restarted my game through the Launch Config and instead of restarting my game it started dropping to single-digit fps and my console started spamming about what I presume is rendering since I could hear the game restarting in the background but it was frozen.
It would restart itself a couple of times from what I could hear/see being printer in the console until eventually the game crashed.

### To Reproduce

Not reliable, sorry.

### Expected behavior

N/A

### Media/Files

https://github.com/sboxgame/issues/assets/59583743/16775362-f647-4af5-8654-0d56a00f9fe9

I click through the error stack trace a bunch, it's random but I can't really target a single one because of the low fps

Here is the log:
[Log.log](https://github.com/sboxgame/issues/files/12500933/Log.log)
(Skip towards the end, it was a long development session)

### Additional context

Windows 10
Latest drivers on everything
GTX 1060 3GB Version
16GB Ram
Ryzen 7 3800X

The development session was 3 hours long, in the middle of a game I used the button on the game window to pause since I was in the middle of fixing a bug in the behaviour of my bot, then unpaused around an hour later after dinner. Don't think it has anything to do since I restarted without problem a bunch of times after but it's worth noting. During that hour long pause I did put my PC to sleep.

During the whole time, I was on the latest version of S&box.

If I encounter it again I'll update.

**Comment by andy013** [comment]
I've had this several times as well. It tends to happen when I've had the game open for long time but that might just be because it's rare and so it's more likely to happen the longer you have the game running.

**Comment by PolSpock** [comment]
Hello,

I'm currently working on my laptop with an Intel Iris Xe graphics card. And on the day of Friday 15 December, my s&box cannot be used anymore since i had a few spammy console errors. Resulting in a s&box crash after each tried to load s&box scene.

This is not the first time i'm having graphics trouble with this laptop and S&box, but it's the first time i cannot use S&box anymore, and that is embarrassing since i use it for multiplayer debugging.

Here is spammy s&box console error (below the stack):
```
[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.	
[engine/Engine] Bailing out of OnBlockForQuery after 0.250 seconds	
```

It was working well on 12 December, so i think it's a recent s&box update who causing this.
I have already tried to update my drivers to the latest version & also reinstall from scratch s&box (through Steam + deleting all keeping files)

PC details:
Processor: 12th Gen Intel(R) Core(TM) i5-1235U
Processor Speed: 1300  MHz
GFX Driver Name: Intel® Iris® Xe Graphics
Shader Version: 5.1
OpenCL* Version: 3.0

Microsoft DirectX:
Runtime Version: 12
Hardware-Supported Version: 12
Vendor ID: 8086
Device ID: 46A8
Device Revision: 0C
GFX Driver Version: 31.0.101.5081
Dedicated RAM: 128 Mo
Shared RAM: 8 Go
Max Supported Displays: 4
GFX Vulcan: 1.3.267
GFX GOP: 21.0.1046

https://github.com/Facepunch/sbox-issues/assets/5229571/a8e89834-c328-4265-9f09-9b603154723b


Detailed stack errors :
```
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message)
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message)
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.SourceEngineApp.RunFrame() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 48
   at Sandbox.SourceEngineApp.RunLoop() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 39
   at Sandbox.Program.LaunchGame() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 93
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 58
```

```
Bailing out of OnBlockForQuery after 0.250 seconds
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message)
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message)
```

**Comment by PolSpock** [comment]
> Hello,
> 
> I'm currently working on my laptop with an Intel Iris Xe graphics card. On the day of 15 December, my `s&box [staging]` cannot be used anymore since the scene system can't be able to load. Resulting in a s&box crash after trying to play a s&box scene.
> 
> This is not the first time i'm having graphics trouble with this laptop and S&box, but it's the first time i cannot use S&box anymore, and that is embarrassing since i use it for multiplayer debugging.
> 
> The weird thing is that all working well on 12 december. Also, it's working well on the no-beta branch. So i definitively think it's a recent s&box update between 13 - 15 december who causing this.
> 
> Also here are interesting full-stack errors at my s&box startup :
> 
> ```
> ERROR! D3D call failed! hr = DXGI_ERROR_DEVICE_REMOVED ( pDevice->CreateBuffer( &desc, NULL, &pD3dBuf ) )
>    at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message)
>    at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message)
>    at Sandbox.SceneCamera.Render()
>    at Sandbox.SceneCamera.AddToRenderList()
>    at Sandbox.ToolsDll.OnRender()
>    at Sandbox.EngineLoop.OnClientOutput()
>    at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_OnClientOutput()
>    at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
>    at Sandbox.SourceEngineApp.RunFrame() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 48
>    at Sandbox.SourceEngineApp.RunLoop() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 39
>    at Sandbox.Program.LaunchGame() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 93
>    at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 58
> ```
> 
> These errors conclude to spammy errors in my s&box console (so similar to the main topic of the issue):
> 
> ```
> [engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.	
> [engine/Engine] Bailing out of OnBlockForQuery after 0.250 seconds	
> ```
> 
> I have already tried to update my drivers to the latest version & also reinstall from scratch s&box (through Steam + deleting all keeping files)
> 
> Reproduce steps:
> 
> * Get an idiot HP laptop  15-eg2 with Intel Iris Xe Graphics
> * Install s&box [staging]
> 
> Click me to see my full `Log.log` :
> Click me to see PC details
> Video of what i get when i launch s&box [staging] :
> 
>  out.mp4

Hello, i decided to retry S&box on my laptop with an Intel Iris Xe graphics card since the S&box Vulkan update has been released.
I was surprised that now everything works like before.

But i don't know if it's really from the Vulkan change or another fix 🤷

**Comment by handsomematt** [comment]
It looks like there was a DX11 CreateBuffer call that was crashing the GPU device for all of you - and I suppose Pol says it's resolved on Vulkan now.
