### ISSUE TITLE
Restarting the sandblox gamemode crashes the game.

### ISSUE THREAD

**Issue by birdbrainswagtrain** [Facepunch/sbox-issues#396]
Restarting the sandblox gamemode crashes the game. I ran into it on my fork but it turns out it affects FP's version as well. I can only assume this has something to do with meshes.

**To Reproduce**

1. Install the [Sandblox](https://github.com/Facepunch/sandblox) gamemode.
2. Start a Sandblox game.
3. Disconnect
4. Start another Sandblox game.
5. The game should crash.

**Expected behavior**
The game doesn't crash.

**Additional context**
[Crash Dump](http://tmp.bz/sbox_2021_0624_162634_0_accessviolation.mdmp)

**Comment by Alf21** [comment]
Sounds like https://github.com/Facepunch/sbox-issues/issues/383

**Comment by aylaylay** [comment]
This should be fixed now

**Comment by birdbrainswagtrain** [comment]
Yep, looks good. Thanks!
