### ISSUE TITLE
CSS border size on corners is off

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#398]
**Describe the bug**
When creating a border with rounded corners the width of the border on the corners is not the same as on the sides.

**To Reproduce**

1. Create a border in css with a border-radius of 8px etc
2. Border on the corners will be thicker

**Expected behavior**
Border thickness on the corners should be the same.

**Screenshots**
In game border
![image](https://user-images.githubusercontent.com/16431607/123344546-fbe0a880-d54b-11eb-8f07-00f634b0013b.png)

Normal border in css/html
![image](https://user-images.githubusercontent.com/16431607/123344552-000cc600-d54c-11eb-90c8-10f91bc4ecc2.png)

**Comment by garrynewman** [comment]
I noticed this myself, seems more evident on thinner borders maybe

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by louiefox** [comment]
Looks good, thanks :)
