### ISSUE TITLE
[Shadergraph] Distance node

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#3994]
### For?

Other

### What can't you do?

At the moment there isn't really a way to measure the distance between two inputs Without having to implement the node to use Distance yourself.

### How would you like it to work?

A Node with with two inputs to calculate the distance and then output the result. 

### What have you tried?

My own node that lets me use the Distance Function

```csharp
[Title( "Distance" ), Category( "Unary" )]
public class Distance : ShaderNode
{
	[Input]
	[HideInEditor]
	public NodeInput InputA { get; set; }

	[Input]
	[HideInEditor]
	public NodeInput InputB { get; set; }

	[Output]
	[HideInEditor]
	public NodeResult.Func Result => ( Compiler compiler ) =>
	{
		var resultA = compiler.ResultOrDefault( InputA, 0.0f );
		var resultB = compiler.ResultOrDefault( InputB, 0.0f ).Cast( resultA.Components );

		return new NodeResult( 1, $"distance( {resultA}, {resultB} )" );
	};
}
```

### Additional context

A Distance node should really be included out of the box.

**Comment by aylaylay** [comment]
Added - thanks
