### ISSUE TITLE
Base WalkController does not apply AirAcceleration

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#4]
Could do something like this:
https://i.imgur.com/vIQLwYO.png

Some gamemodes utilize the variation in ground & air accel.

**Comment by garrynewman** [comment]
Are you sure? I think it'd feel really obvious if it didn't.

**Comment by cr4yz** [comment]
> Are you sure? I think it'd feel really obvious if it didn't.

Yeah, just double checked it:

https://streamable.com/pn2w42

**Comment by aylaylay** [comment]
Yeah it just wasn't using that value. That whole player movement code needs to be remade properly at some point
