### ISSUE TITLE
prop_door_rotating doesn't work

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#40]
prop_door_rotating doesn't work. I have to convert the door model into a mesh and use func_door_rotating

![image](https://user-images.githubusercontent.com/39461072/116172040-99943480-a6cf-11eb-9493-24d04cb494c7.png)

**Comment by robotboy655** [comment]
Reimplemented a basic version of this in C#, it now opens with +use (and doesn't crash the game)
