### ISSUE TITLE
Setting gravity to zero in Project Settings resets it to default 

### ISSUE THREAD

**Issue by Phyksar** [Facepunch/sbox-issues#4017]
### Describe the bug

Zero gravity doesn't get saved in the Game's Project Settings. Seems like when you type it, the `Gravity` field is getting removed from the `.sbproj` file.

### To Reproduce

1. Go to the Game's `Project Settings` in the S&box editor.
2. Open the `Physics` section and type in `Gravity` - `x:0 y:0 z:0`
3. Click the `Save` button.
4. Reopen the `Project Settings` and observe that the gravity value became the default one `x:0 y:0 z:-800`.

### Expected behavior

The zero gravity should be saved correctly since it's a completely valid value.

**Comment by aylaylay** [comment]
Json serialize actually makes this tricky. If I can't find a way around it, I'd be tempted to just add a ignore gravity bool

**Comment by aylaylay** [comment]
Redundant now?
