### ISSUE TITLE
[ResourceType] doesn't work on Lists in Prefab Editor

### ISSUE THREAD

**Issue by trende2001** [Facepunch/sbox-issues#4057]
### Describe the bug

I try to put the [ResourceType("weapon")] attribute onto a list of strings, and it doesn't turn into what I tell it to be.

![image](https://github.com/sboxgame/issues/assets/68961063/011744be-ab66-44bb-ae4d-a1a09684d5e1)

### To Reproduce

1. Create a list of strings and expose to Prefab Editor with [Prefab]
2. Put [ResourceType("clothing"] just to test
3. It remains a list of strings with no resource cards.

### Expected behavior

Should function like it does in GameResources.
![image](https://github.com/sboxgame/issues/assets/68961063/8703f970-4294-410a-8ace-a7e712538e70)

### Media/Files

N/A

**Comment by LeQuackers** [comment]
Probably related: #3013

**Comment by Fortune117** [comment]
You can just use a list of the actual type of the game resource. 

i.e. `public List<WeaponResource> WeaponResourceList {get; set;}`

**Comment by trende2001** [comment]
> You can just use a list of the actual type of the game resource.
> 
> i.e. `public List<WeaponResource> WeaponResourceList {get; set;}`

I could, but it would be nice for it to work the other way around too
