### ISSUE TITLE
Change `Player.LifeState` to be just synced to the local player instead of broadcasted

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#407]
**What can't you do?**
I can't restrict the networking of `Player.LifeState` as it's synced to every client. This is, especially regarding anti-cheating, quite important, as currently every client can check whether another player is alive (In TTT, some players shouldn't be aware that other players died as long as they were not confirmed).

I know that this would be a breaking change for some add-ons, but I thought I should mention this in early state already.

**How would you like it to work?**
I'd like to have it just synced to the client.Pawn's client and syncing other states manually.

**What have you tried?**
I thought about disconnecting the Pawn from the client on death (LifeState is bound to the `Player` entity), but in that way a cheater could just check for `client`s that do not have a `Pawn` bound.

**Additional context**
![image](https://user-images.githubusercontent.com/11843790/123519569-6c9ed680-d6ac-11eb-8e44-bb37f17c3114.png)

You can check this e.g. via

```cs
[ClientCmd(Name = "alives")]
public static void AlivePlayers()
{
    List<Client> playerList = Client.All.ToList();

    for (int i = 0; i < playerList.Count; i++)
    {
        Log.Info($"Player (ID: '{i}'): {playerList[i].Name} - Alive: {playerList[i].Pawn?.LifeState == LifeState.Alive}");
    }
}
```

**Comment by garrynewman** [comment]
Can't you just not use LifeState?

**Comment by Alf21** [comment]
> Can't you just not use LifeState?

As `Player.LifeState` is set automatically after `Player.OnKilled`, I can't restrict that. And I'm not using `Player.LifeState` as I'm syncing player states like `IsConfirmed` and other stuff manually. But that's not the topic in question: If the client can access automatically set and synced `Player.LifeState` in the topic of anti-cheating, the client could use that to get a not really detectable game advandage if cheating.

If you do not wanna change this, I'm totally okay with this. Just wanted to make sure, you are aware of this in early stage, so it wouldn't break tons of things if recognized in a later state.
