### ISSUE TITLE
Simplify adding input actions

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4074]
### For?

S&Box

### What can't you do?

Adding input actions is a little slow right now, I thought it would be neat to do it the way Godot does.

### How would you like it to work?

Type the name of the input action in a text box and press enter to add it to the list of input actions
Double click a field to edit it, clicking input action spaces opens a menu to look through the list of available inputs / press the associated key.

Here's a demonstration of how I would like it to work (how godot does it):

https://github.com/sboxgame/issues/assets/94070205/2f97f9bf-acf3-46cf-a044-e01ea54036ed

### What have you tried?

No workarounds I can think of.

**Comment by DevulTj** [comment]
I actually messed with Godot last week, and it's pretty nice in the input system. It was one of our references when drafting the Input Actions feature, but we went in a different direction.

I did just push something to make grabbing inputs easier - instead of manually inserting the name of the keyboard code, you just hit the key and it'll find it.

**Comment by DrakeFruit** [comment]
the main thing I'm wanting is just typing the name of the action and pressing enter, I really hate the way it's currently done, especially since I need to press the edit button instead of just double clicking the text field.

**Comment by DrakeFruit** [comment]
@DevulTj thanks for adding the inline editing, could you add this while you're at it or is it not planned. You just type the name of the action and press enter so adding a ton of actions is really fast.
https://github.com/sboxgame/issues/assets/94070205/4a14d5ab-50d1-4464-b83c-7a941cb02572

**Comment by DevulTj** [comment]
Yeah

**Comment by DevulTj** [comment]
I've added a couple more things that I think will be good for now. New actions will be placed in the last group, so you won't have to go searching your list to find that new action.

I also added a input field for you to name your action and hit enter, as requested.

![sbox-dev_duZ3bhoZdb](https://github.com/Facepunch/sbox-issues/assets/22372616/91a32ce6-df29-42ef-bbe0-95d6cedf9b76)
