### ISSUE TITLE
Whitelist System.Net.WebUtility

### ISSUE THREAD

**Issue by m0uka** [Facepunch/sbox-issues#408]
Would be useful to have the HtmlDecode and UrlDecode methods, so we can replace the HTML special characters (&quot; &#039;, etc...)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by m0uka** [comment]
Thanks 👍
