### ISSUE TITLE
Inherited triggers have no spawnflags making all implemented triggers unusable.

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#410]
All trigger classes are inherited from BaseTrigger and don't autogen fgd inherited spawnflags property - without this you can not set trigger filters and default behavior is to ignore everything.

**Comment by kurozael** [comment]
Thanks @handsomematt. This should be fixed in the next Steam build which usually takes 5 minutes. Please can you confirm whether it has resolved the issue, and then close this issue if it has.
