### ISSUE TITLE
Game.Server.MaxPlayers in GameMenu is always 1 for those who join the server

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#4108]
### Describe the bug

This is the player count on my side:

![image](https://github.com/sboxgame/issues/assets/6745157/3a6ea7d4-eb5d-4921-aa59-76965982e89b)

And this is the player count on my friend's side:

![image](https://github.com/sboxgame/issues/assets/6745157/4b3fe62a-8b35-42a9-bb04-378a8b802afd)

### To Reproduce

```razor
<root>@Game.Server.MaxPlayers</root>
```

### Expected behavior

It should be the same for each client.

**Comment by DevulTj** [comment]
Not a thing anymore
