### ISSUE TITLE
StringX.GetSha256 returns an int.

### ISSUE THREAD

**Issue by birdbrainswagtrain** [Facepunch/sbox-issues#411]
`StringX.GetSha256` returns an int. Seems odd that a hash with a 256 bit digest only returns 32 bits.

Ideally it should probably return either a string, byte array, or some kind of hash struct. In it's current state I don't understand what advantage this is supposed to offer over `String.GetHashCode`. It should be fairly easy to find collisions with the current implementation.

Alternatively, it would be cool if some functions from `System.Security.Cryptography` were whitelisted, but the assembly doesn't even seem available.

**Screenshots**
![](https://tmp.bz/2y4auvanfMC.png)

**Comment by garrynewman** [comment]
Thanks, I've removed this function for now. If you want a replacement or want something specific whitelisted, can you make a new issue please.
