### ISSUE TITLE
[Shadergraph] Lighting broken on shaders

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#4115]
### Describe the bug

Models/meshes using shadergraph shaders cause incorrect lighting in Hammer and in-game. 
The lighting does look correct once lighting is baked though
Left cube in screenshots is complex shader, right is shadergraph. Both using just the testgrid texture 

### To Reproduce

1. Make a basic shader in shadergraph
2. Apply it to something in Hammer
3. Mess with the lighting in Hammer, it wont look correct on the object with the material on it

### Expected behavior

Should look the same as the complex shader

### Media/Files

![image](https://github.com/sboxgame/issues/assets/50308149/ba757e46-f8f1-493e-a1a4-704aca6cc25c)
![image](https://github.com/sboxgame/issues/assets/50308149/2ec65cd8-1486-4a4c-8ec7-4c69c98d28c2)
![image](https://github.com/sboxgame/issues/assets/50308149/7cc4d0ca-a2e7-4111-b2d1-a44ae8486a36)

**Comment by handsomematt** [comment]
Will be fixed when the new lightbinner is merged.
