### ISSUE TITLE
Physics behaviour seems to have changed after recent Izabu physics update

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4121]
### Describe the bug

After the new physics changes, physics objects seem to behave differently, and not in a good way. I notice very strange behaviour with my stuff, as will be shown in the video. There are several issues I noticed which did not happen before (there may be more, it's hard to tell with these things):

1. The concrete barrier prop seems to make an impact sound when it 'collides' with the blue watery surface (called event horizon, which has disabled collisions, so no idea how it can even try to collide)
2. Freezing a prop (in this case the box) while inside the event horizon makes it trigger the teleport behaviour (seems to only happen if its more than halfway through, so I guess it somehow makes the game think the box passed all the way through, stopped touching the event horizon and thus should be teleported)
3. When placing a big metal shield over the event horizon (called an iris), things should not be allowed to pass through. However, the props seem to ignore collisions with the iris entirely.

I don't know if this is intentional and 'basically its going to be like this', and the logic for handling the physics will need to be changed on my end, or if these are just bugs introduced during the physics changes which cause this. I guess that games/addons that relied on physics working in a certain way were fucked during the update.

### To Reproduce

1. Probably try out https://asset.party/katka/stargateaddon inside of the https://asset.party/wiremod/sandboxplus game
2. Try for yourself, possibly compare the behaviour with earlier versions of sbox with the old physics

### Expected behavior

Hard to say, but the behaviour should be as it was before the physics changes.

### Media/Files

https://github.com/sboxgame/issues/assets/5991682/5b2ebc62-0126-4e4f-84a9-5109fe56ad91

**Comment by andy013** [comment]
I have noticed 1 as well. When my player drops an object or throws a grenade then it will make an impact sound with the player who threw it, despite it not colliding with them.

I have also noticed that `ApplyLocalAngularImpulse` is orders of magnitude more powerful. Now my thrown objects are spinning much more than before. 

Also, I was previously setting the rotation of an object and then an angular impulse directly after but this no longer works. `ApplyLocalAngularImpulse` applies in the same direction regardless of the objects rotation.

**Comment by PolSpock** [comment]
Yes, some Physics APIs have stopped working with the Izabu change. For example, https://asset.party/api/Sandbox.ModelEntity.EnableTouch, when set to False, will still continue to toggle StartTouch / EndTouch. However, this function is related to an Entity, so i don't think it has been fixed

**Comment by aylaylay** [comment]
Going to close this, if there's still issues can you make 1 issue per physics issue please
