### ISSUE TITLE
Speech Recognition doesn't work (Possibly only in Game Menu space?)

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4127]
### Describe the bug

Trying to use Sandbox.Speech.Recognition, it appears to do nothing.

### To Reproduce

![devenv_96ajGqRixL](https://github.com/sboxgame/issues/assets/11138884/cafdedcd-af27-46bf-bd74-216b32110410)

Try to run that code in a Scene game and observe nothing actually gets logged.

### Expected behavior

I would expect the results to get output and logged properly.

**Comment by kurozael** [comment]
This is working for me with the Scene System when using this code in a component's `OnUpdate` method - could you try again @ShadowBrian?

**Comment by ShadowBrian** [comment]
I'm not getting any results still, really weird.

**Comment by kurozael** [comment]
Would you be able to send me the whole project @ShadowBrian - just in-case it's something very specific to how you're using it? I wonder if it just isn't registering your microphone...

**Comment by ShadowBrian** [comment]
I invited you to the repo, it's in my house generator game so it'll be a bit tricky to properly test I think given all the extra files it needs to run :p

**Comment by ShadowBrian** [comment]
Alright so I gave this another look and I still can't get it working- I know it's picking up my mic because I put a voice transmitter on loopback in my scene and it was outputting my mic fine- it's not logging anything despite that...
Are there any windows prerequisites to using microsoft's voice recognition maybe?

**Comment by kurozael** [comment]
Thanks, I'll take another look this week ☺️

**Comment by kurozael** [comment]
@ShadowBrian this repro still works for me - but you might wanna remove the `Recognition.Stop` block. For me, after pressing Jump and saying something, it can take up to 2-3 seconds for the callback to be called. Maybe this is why it isn't working for you? You're not giving it long enough and you're releasing the Jump key - thereby stopping the recognition, perhaps?

**Comment by kurozael** [comment]
I'm gonna assume the above comment was the reason why - if I'm wrong and you haven't got this to work, please re-open :)
