### ISSUE TITLE
Make `Editor` folder available for addons and libraries.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4134]
### For?

S&Box

### What can't you do?

I'm unable to make an Editor folder for my addons or libaries.
More importantly, it is preventing me from making widgets in my addon and library.

For game projects, a .editor gets added. ( Shown below )
Doing the same thing in an addon or library project, no such .editor appears. ( Shown below )

![image](https://github.com/sboxgame/issues/assets/91832803/93d637c5-ea88-432e-9819-e5f135715ee8)

### How would you like it to work?

An Editor folder in addon and library projects should work similarly to that of ones inside a game project.
![image](https://github.com/sboxgame/issues/assets/91832803/0a4b46e2-1213-4446-87a2-28756b0a863c)

### What have you tried?

I have tried creating an Editor folder in my addon with no success.

### Additional context

Opened by request of ubre the handsome

**Comment by yuberee** [comment]
I agree, especially for Libraries.
Personally I have many libraries in the works that require editor tools to function, especially with the new scene system.

**Comment by garrynewman** [comment]
We might want to keep things simple for a couple of months, but I'll put this on the backburner.

**Comment by badandbest** [comment]
Libraries are cool now
