### ISSUE TITLE
Hammer.DrawAnglesAttribute has no parameterless constructor for drawangles()

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#414]
The attribute supports writing `drawangles( angleKV )` or `drawangles( angleKV, isLocalKV )` but not `drawangles()` which is commonly used for drawing the rotation of the entity.

I can workaround with `[Hammer.DrawAngles( "" )]` which will generate `drawangles(  )` but it's not explicitly clear of it's usage.

You should be able to simply do `[Hammer.DrawAngles]` for Hammer to draw the entities rotation.

**Comment by robotboy655** [comment]
Done.
