### ISSUE TITLE
[Scene Editor] Grid Snapping

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#4149]
### For?

S&Box

### What can't you do?

I'd love to be able to snap things to a global grid, even if it's just being able to snap the position to whole numbers for now.

Eventually being able to customize grid size would also be very helpful, especially if you can choose power of two sized increments as well as 1, 5, 10, 50, 100 etc.

### How would you like it to work?

I think ideally it should be a ui button toggle to enable/disable snapping and then a shortcut to override that, like Ctrl + transform to temporarily enable snapping.

Eventually being able to customize grid size would also be very helpful, especially if you can choose power of two sized increments as well as 1, 5, 10, 50, 100 etc.

### What have you tried?

Manually typing in round numbers each time I want to move an object.

### Additional context

Moving issue from scenestaging to here https://github.com/Facepunch/sbox-scenestaging/issues/22

**Comment by CarsonKompon** [comment]
Vertex snapping would also be really nice (not sure if that should be it's own feature request)

**Comment by garrynewman** [comment]
Basics of this are in now

**Comment by Jammie3d** [comment]
Works really well, cheers!

Would it be possible to get angle snapping on rotations too? Happy to make a new issue for that if needs be.

**Comment by garrynewman** [comment]
Yeah make a new issue please so I don't forget
