### ISSUE TITLE
Create @EntityGroup for custom categories in [Hammer.EntityTool]

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#415]
**What can't you do?**

Specify a custom category in [Hammer.EntityTool( "title", "category" )] - it does not show in the entity tool due to missing @EntityGroup

**How would you like it to work?**

Fgd generator should detect unique categories in [Hammer.EntityTool] and output corresponding `@EntityGroup`.

`[Hammer.EntityTool( "title", "category" )]` would prepend `@EntityGroup "category"`

**Comment by handsomematt** [comment]
Alternatively another way this could work is if the category is specified as the assembly so all entities in a single addon end up in the same category making it easy for mappers to see all addons specific to each addon.

**Comment by robotboy655** [comment]
Automatic addon category might be an interesting idea, but I think we need to look into removing the necessity for `@EntityGroup` if possible.

**Comment by robotboy655** [comment]
Removed the need for `@EntityGroup` for custom categories. Any missing categories will be created collapsed by default.

From what I understand `@EntityGroup` is meant for Source 2 mods to have better control over the UI in Hammer, which doesn't really apply to Sbox, it being a standalone game.

**Comment by handsomematt** [comment]
Nice one mate
