### ISSUE TITLE
Use scenes as prefabs

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4150]
### For?

S&Box

### What can't you do?

Make scenes children of the current scene as you would a prefab

### How would you like it to work?

Scenes and prefabs have essentially the same functionality aside from being children of other gameobjects (including scenes), I find the seperation kind of useless. If I wanted to have multiple levels managed by one server, you could let a server run multiple scenes at once but I can't imagine how the api for that would work. It would make intuitive sense to just put each level as a child scene of the main one and assign players to a certain scene if its used as a level, or don't if I'm using it as a collection of objects like a prefab is now.

### What have you tried?

I've tried using prefabs but they're often buggy and don't make sense as parts of or an entire level themselves. If I want multiple levels in one scene I don't have many options.

**Comment by CarsonKompon** [comment]
This makes me wonder, what is the reason that Unity has a distinction between the two? In s&box I already appreciate that the language is slightly different so I know if im editing a scene vs a prefab and it not letting me go into a prefab in play mode. I think it is good to draw a line between the two so instead the feature request should be more broad as to allowing multiple scenes to be loaded at once (which unity also allows you to do)

**Comment by handsomematt** [comment]
#5388
