### ISSUE TITLE
Add a way to only render a models shadows

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4156]
### Describe the bug

I wish to see the player's shadow but hide the model itself from drawing.

https://github.com/sboxgame/issues/assets/5159369/cbda54af-5912-43ce-8657-1020be3970cc

### To Reproduce

See the video above

### Expected behavior

The shadow should be visible or there should be a way for us to achieve the desired result of hiding a model but not its shadow.

**Comment by garrynewman** [comment]
This is easy enough to add, but I don't see how still rendering shadows of excluded objects would be the ideal functionality for 99% of situations. It's more likely to be a setting on the renderer itself (you can already kind of do this via the SceneObject)

**Comment by handsomematt** [comment]
We can add this to ModelRenderer to either render with/without or only shadows.

**Comment by badandbest** [comment]
That would be much more intuitive than what I'm doing now.
```c#
var modelRenderer = GameObject.Components.Get<ModelRenderer>();
modelRenderer.SceneObject.Flags.IsOpaque = false; // Show only shadows.
```

**Comment by DevulTj** [comment]
Added.

https://github.com/Facepunch/sbox-issues/assets/22372616/82fed125-159e-4c38-a260-34eb796bedba
