### ISSUE TITLE
Need Trace.Ray.Ignore equivalent 

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4158]
### For?

S&Box

### What can't you do?

I'm unable to ignore a specific gameobject in a ray trace, this use to be possible with entities but no gameobject equivalent exists

### How would you like it to work?

just like the way it used to work, but gameobjects

### What have you tried?

can use a tag that only that object has but making a tag for one object feels silly

**Comment by Fortune117** [comment]
Just ran into a need for this myself, would be very nice to have.

**Comment by garrynewman** [comment]
I have planned how I'm gonna implement it, just need to fit it in.

**Comment by garrynewman** [comment]
Added SceneTrace.IgnoreGameObject, SceneTrace.IgnoreGameObjectHierarchy

**Comment by yuberee** [comment]
May we have these for PhysicsTraceBuilder as well?

**Comment by garrynewman** [comment]
Not really, that have no concept of gameobjects
