### ISSUE TITLE
CFlattenedSerializer:Decode Error

### ISSUE THREAD

**Issue by 5FB5** [Facepunch/sbox-issues#416]
**Describe the bug**
If you try to connect to existing sandbox game, you'll get an error like in screenshot I shot.

**To Reproduce**

1. Go to 'Sandox' gamemode
2. Click on 'Find game'
3. See error

**Expected behavior**
Normal connecting to sandbox server

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/15859698/123668453-cb4a8880-d843-11eb-80c2-01442c0088a4.png)

**Additional context**
None

**Comment by 5FB5** [comment]
It can be fixed by verify game files via Steam.
Thanks to xrayhunter for hint.

**Comment by Geeknerd1337** [comment]
This should be re-opened because it happens randomly while playing on a server of about 6 people. We were playtesting speed-dial and would get this crash 3-4 times over the course of an hour.

**Comment by Geeknerd1337** [comment]
![image](https://user-images.githubusercontent.com/15205856/123676091-1d21ed00-d809-11eb-9a0e-6bf615165830.png)

This is one of our screenshots of the error that happened in the middle of a playtesting session, just to show off.

**Comment by 5FB5** [comment]
![image](https://user-images.githubusercontent.com/15859698/124003412-96733880-d9df-11eb-9ea0-03ac0ec8c9d3.png)
New variant of this error

**Comment by aylaylay** [comment]
I've made a change that could stop this error from happening, try and break it. Let me know here if it pops up again.

**Comment by 5FB5** [comment]
So, for me any of this error doesn't happened. I think, that I can close this issue. If someone will see this again, I reopen it

**Comment by 5FB5** [comment]
I've got this error again
![Screenshot_2](https://user-images.githubusercontent.com/15859698/130254490-c8b17c97-2801-46a1-8832-bb9a9bbb7ed1.png)

**Comment by KayaDLX** [comment]
very old! its been fixed for a while now
