### ISSUE TITLE
Multithreaded DXT Compression Crash

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4165]
### Describe the bug

Creating material crashes to desktop

### To Reproduce

Right click on this image in s&box asset browser
Create new material
Double-click material to open
Crash to desktop

[image_file.zip](https://github.com/sboxgame/issues/files/13639790/image_file.zip)

After creating the material, s&box won't boot until the material's .vmat file is deleted

### Expected behavior

Works

### Additional context

Donno if it's related but I'm getting these errors in the logs

2023/12/11 18:44:16.1887	[engine/Engine] CDmSerializerBinary: Attribute 'snaprotationangle' of element '' read as 'int' but expected 'float'	
2023/12/11 18:44:30.7443	[engine/Engine] CDmSerializerBinary: Attribute 'snaprotationangle' of element '' read as 'int' but expected 'float'	
2023/12/11 18:44:31.0559	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'g_flDetailTexCoordRotation' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'g_vDetailTexCoordOffset' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'g_vDetailTexCoordScale' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'TextureDetail' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'TextureDetailMask' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'TextureNormalDetail' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'g_flDetailBlendFactor' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'g_flDetailBlendToFull' has (80).	
2023/12/11 18:44:31.0572	[engine/Engine] Shader 'shaders/complex' - Group Sort Key Mismatch! First trumps. 'g_bUseSecondaryUvForDetailTexture' has (170), 'g_flDetailNormalStrength' has (80).	
2023/12/11 18:44:31.2259	[engine/Engine] CDmSerializerBinary: Attribute 'snaprotationangle' of element '' read as 'int' but expected 'float'	

Steam ID: 76561197997412036

**Comment by handsomematt** [comment]
Looks like a crash with [multithreaded DXT compression](https://github.com/Facepunch/sbox/blame/master/src/bitmap/floatbitmap.cpp#L1063-L1063C5).

**Comment by anthonysharpy** [comment]
Seems to happen when the image dimensions is not a power of 2

**Comment by xezno** [comment]
We can move DXT compression over to the GPU - I'll look at making sure this is fixed when we do that
