### ISSUE TITLE
Command parameter conversion is unreliable

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/sbox-issues#417]
**Describe the bug**
You cannot rely on a command parameter being converted properly. 

**To Reproduce**
```csharp
[ServerCmd( "Test" )]
private static void Test( int num )
	 => Log.Info( num );
```
`test NotAnInt` returns 0

**Expected behavior**
The caller should be notified the argument is invalid.

**Comment by thegrb93** [comment]
I don't see any problem with the current behavior. Maybe would be cool if help-text was printed to the user if arguments were missing or mismatched but seems more like a feature than a bug.

**Comment by thegrb93** [comment]
It's not unexpected if you know that 0 is the default :v

**Comment by thegrb93** [comment]
Alternatively, if you really need to verify it, you could make the arg a string and parse it yourself.

**Comment by aStonedPenguin** [comment]
You could and on second thought this probably isn't a bug but it is suboptimal.

**Comment by ZehMatt** [comment]
I think this should properly check if the input is convertible to the type. If you already provide a way to specify the input type it should be checked, there is no reason not to.
