### ISSUE TITLE
`SceneTraceResult` has inconsistent results when hitting a hitbox

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4176]
### Describe the bug

Right now when a SceneTrace is run and hits a hitbox, some of the values in the trace result are either not set or are set to the incorrect thing.

I have some code that looks like this:

Also SceneTraceResult.Body.GameObject is still of type `object` and can probably be updated now.

```CS
var tr = hurtBox.PerformTrace();

if ( !tr.Hit )
    continue;

// tr.Body.GameObject is returning the hitbox object that was hit instead of the game object
// tr.GameObject returns null when the trace hits a hitbox (works when hitting a physics shape though)
// tr.Hitbox.GameObject works and returns the hitboxes game object.
```

### To Reproduce

1. Run a SceneTrace
2. Hit a hitbox
3. See incomplete results for the trace.

### Expected behavior

All properties should be defined as expected.

**Comment by garrynewman** [comment]
This should all be fixed now

**Comment by Fortune117** [comment]
Seems to be all good now 👍
