### ISSUE TITLE
When becoming ragdoll, the bone positions don't match the animation bones

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4179]
### What it is?

I have NPCs set up in my game to ragdoll upon dying. It doesn't create a new object but instead enables a `ModelPhysics` component on them.

However, right now it essentially causes the ragdoll to snap back to the bind pose when it's enabled. I was able to get around this before on the scenestaging branch by adding my own method to the `ModelPhysics` component.

```CS
public void SetBonesToRenderer()
{
	if ( PhysicsGroup is null ) return;
	if ( Renderer is null ) return;
		
	foreach( var body in PhysicsGroup.Bodies )
	{
		var bone = Renderer.Model.Bones.AllBones.FirstOrDefault( x => x.Name == body.GroupName );
		if ( bone is null ) continue;

		var rendererBone = Renderer.GetBoneTransform( bone, true );
		body.Transform = rendererBone;
	}
}
```

This method would allow me to manually force the model physics bones to match the NPC models bone positions upon death.

### What should it be?

Either the model physics should assume the position of the renderers bones upon being enabled or allow me to manually set them as I was doing before, with something akin to this:

```CS
	private void OnDeath(DamageEventData damageEventData)
	{
		if ( !Components.TryGet<ModelPhysics>( out var modelPhysics, FindMode.EverythingInSelfAndDescendants ) )
			return;

		modelPhysics.GameObject.Tags.Add( "corpse" );
		modelPhysics.Enabled = true;
		modelPhysics.SetBonesToRenderer(); //this bit!
	}
```

**Comment by aylaylay** [comment]
I've made it copy the renderer bones to the model physics on enable

**Comment by Fortune117** [comment]
Works great 👍
