### ISSUE TITLE
Trying to write "sv_gravity" in the main menu crashing the game

### ISSUE THREAD

**Issue by 5FB5** [Facepunch/sbox-issues#418]
**Describe the bug**
If you write server command (for me, "sv_gravity") game is crashed! I think the game must check this.
This can repeats with not only this command. It must be checked too, I think

**To Reproduce**

1. Go to main menu
2. Write "sv_gravity  (number)"
3. See error

**Expected behavior**
I think that the game must write in console like "You can't use this" or something like that and continue his work

**Screenshots**
None

**Additional context**
None

**Comment by garrynewman** [comment]
![image](https://user-images.githubusercontent.com/928843/123825448-d3173500-d8f6-11eb-9461-d0845d86ddee.png)

**Comment by 5FB5** [comment]
Very strange. Maybe it happened before I update the game. I test it now

**Comment by 5FB5** [comment]
Game is crashed when I entered to my gamemode, then I've disconnected and after that I tried to change value in main menu

**Comment by 5FB5** [comment]
![image](https://user-images.githubusercontent.com/15859698/123826869-d2879a00-d908-11eb-877b-cf7ea36b268e.png)
Log is clear

**Comment by robotboy655** [comment]
I can confirm after starting the Sandbox gamemode, disconnecting and then changing gravity.

**Comment by aylaylay** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.

If it is fixed feel free to close the issue yourself <3

**Comment by 5FB5** [comment]
Yes, it works! Thanks!
