### ISSUE TITLE
Scene: Ability to make component properties read only in the inspector

### ISSUE THREAD

**Issue by yikegaming** [Facepunch/sbox-issues#4181]
### For?

S&Box

### What can't you do?

Limit what can be done with component properties in game

### How would you like it to work?

On properties we should be able to control what can be changed in game, for example adding a [ViewOnly] to set that the property is only able to be viewed, not changed, for properties that are strictly set in the game code and shouldn’t be changed or might only exist for computational reasons.

Another example would be [Min(INT)] or [Max(INT)] to control the minimum and maximum values for an integer property, these could be put in place to prevent potential erroring in a devs code.

### What have you tried?

This doesn’t exist in anyway yet!

**Comment by GavrilovNI** [comment]
> Worth noting that `RangeAttribute` exists already - but being able to make a property readonly in the inspector would be nice 👍🏻

That would be awesome if we could make custom attributes like Range

**Comment by garrynewman** [comment]
I think we might have `[ReadOnly]` already - if not, should be easy enough to accomodate.
