### ISSUE TITLE
Text-to-Speech synth doesn't work anymore, no audio output.

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4182]
### Describe the bug

Text-to-Speech synth doesn't work anymore, no audio output.

### To Reproduce

1. try to get text to speech to say anything
2. fail to

### Expected behavior

1. try to get text to speech to say anything
2. it works!

**Comment by DevulTj** [comment]
Pushed a fix now - I tested locally and it was working with this code:

```csharp
[Property] public string StringProperty { get; set; }

protected override void OnStart()
{
	var handle = new Sandbox.Speech.Synthesizer()
		.WithText( StringProperty )	
		.Play();
}
```

**Comment by ShadowBrian** [comment]
Yup synth works. I have a different issue to make now relating to soundHandle though :D
