### ISSUE TITLE
Local Offset for Box and Sphere Collider Components

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4185]
### For?

S&Box

### What can't you do?

I can't move a box or sphere collider so it isn't centered on the origin of a GameObject.

### How would you like it to work?

A Vector3 property that offsets the collider in the GameObject's local space.

### What have you tried?

Child GameObject with a collider component, so that the child's local position is the offset for the collider.

**Comment by garrynewman** [comment]
What if you need to rotate the collider? Or add different tags? Shall we add those too?

**Comment by handsomematt** [comment]
I think this is in now.
