### ISSUE TITLE
Cant join local dev game (not uploaded yet) with a new instance

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#4186]
### Describe the bug

You can not join your own local dev game with a new local sbox instance (and i imagine anyone else).

It displays Package [local.game] wasn't found!

_note_
this is specific to games you have not uploaded

### To Reproduce

Have a local in development game with networking.
and then try to join via a new instance
![image](https://github.com/Facepunch/sbox-issues/assets/82092361/333605b9-6529-4d91-95d7-74318f87c658)

then on the new game window it wont load and show this.
![image](https://github.com/Facepunch/sbox-issues/assets/82092361/c798fa59-179b-452b-a248-7aa4fb4897b7)

### Expected behavior

It should send the local game to the connecting player like it did before

### Additional context

(we can still upload the game and test that way, but this can be a pain over time)

**Comment by garrynewman** [comment]
This should now be fully possible There are some specifics that don't work, which we should have separate issues for:

- Prefabs aren't sent to clients
- scss isn't sent to clients

**Comment by NotGaylien** [comment]
Yep works now, thanks!

shall i make them both separate issues.
or 1 issue with both of them included.
