### ISSUE TITLE
Asset Party isn't tracking player count or playtime for scene games

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4187]
### Describe the bug

Games show as unplayed even if you have played them multiple times and player count remains at zero.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/2dfd35ac-2268-4f1d-a01c-5c553934503f)

Looking at asset party backend I can also see zero trends in users.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/3105af35-f007-4474-a305-e1b61151f819)

But there have been at least 9 players who have submitted scores (presumably more who launched the game and closed it before a score could be submitted)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/7e684a60-83b6-487c-bb4c-4288bc5b6f74)

### To Reproduce

Upload a scene game
Play it in s&box (not the s&box editor)
See no change in stats.

### Expected behavior

It should track this 👍

**Comment by CarsonKompon** [comment]
I seem to have players tracked now but I believe its only from people who played the game who *arent* on the staging branch of steam.

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/6b345fb0-e303-4fb3-8c03-c119a8a6faf3)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/9cfa25a9-8af8-412d-9ab5-ba46fee5ae13)

After playing the game a few more times today I'm still not showing on the players list in asset party and the game still shows "unplayed" 
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/cfd8b065-d1ed-4a74-a30d-aaf9f7ff5ea4)

**Comment by garrynewman** [comment]
I think you're right - I looked into this too. Will give it another go.

**Comment by garrynewman** [comment]
defo working now!
