### ISSUE TITLE
Localization isn't working in scene games

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4188]
### Describe the bug

Using localization tags in ui with a .localization/en/gamename.json file does not load properly in scene games.

### To Reproduce

Create a `.localization/en/gamename.json` file like so:
```json
{
    "mymenu.quit": "Exit the fucking game"
}
```
and try to display it in a razor panel:
```razor
<p>#mymenu.quit</p>
```
and you'll see it is not localized:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/c7e2aa12-341a-4f38-8e5c-6173f175fd9b)

### Expected behavior

I would expect it to work as it did before.

Interestingly, you can still localize to base s&box tags, so the localization system is still working, it's just not picking up game-specific loc:
```razor
<p>#menu.quit</p>
```
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/b7e12e9a-a89b-4973-ad75-d2d80c1403ae)

**Comment by garrynewman** [comment]
I think I remember @handsomematt fixing this, is it fixed?

**Comment by handsomematt** [comment]
I hadn't, but now I have.

**Comment by CarsonKompon** [comment]
Yep, can confirm it works now :)
