### ISSUE TITLE
Decals Don't Work When Created At Runtime

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4189]
### Describe the bug

I'm using this code to create a decal but it doesn't seem to work atm

```
private void DoImpactEffects(Vector3 location, Rotation rotation)
{
	var decalObject = new GameObject();
	var decal = decalObject.Components.Create<DecalRenderer>();

	decalObject.Transform.Rotation = rotation;
	decalObject.Transform.Position = location + rotation.Backward * 4f;
	decalObject.Name = "Decal";

	decal.Material = Material.Load( "materials/decals/bullethole.vmat" );
	decal.Size = new Vector3( 5, 5, 5 );
	decal.Reset(); // I tried with and without this	
}
```

A decal with the exact same settings in the editor works fine. The decal on the right was created manually, the decal on the left was created at runtime.

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/0e8122fe-fb97-4e64-8ab6-22d04d02653c)

They have basically the same settings in the inspector

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/6a532880-abab-4509-a45f-0700c75f40cc)

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/391b0298-bf14-4f8d-89a3-f5152c69c4f1)

Also, some other problems I'm sort of running into:

- There's no way I can find to get the normal of a face from a SceneTraceResult. This makes it hard to know how to rotate the decal.
- There's no more DestroyAsync, so it's hard to delete the decal
- None of the async stuff seems to be working for some reason as the await is ignored and the object is destroyed immediately. For example, I tried:

```
private void DoImpactEffects(Vector3 location, Rotation rotation)
{
	// ... blah blah blah

	DestroyAsync( decalObject, 600000 );
}

private async Task DestroyAsync( GameObject obj, int milliseconds)
{
	await GameTask.Delay( milliseconds );
	Log.Info( "destroying" );
	obj.Destroy();
}
```

I also tried stuff like

```
private void DestroyAsync( GameObject obj, int milliseconds)
{
	GameTask.RunInThreadAsync( async () =>
	{
		await GameTask.Delay( milliseconds );
		Log.Info( "destroying" );
		obj.Destroy();
	} );
}
```

IMO the async stuff in s&box has never really worked 100%, or maybe I'm just having a long-term skill issue here?

### To Reproduce

see above

### Expected behavior

epic decals

**Comment by DevulTj** [comment]
I've made some changes to how DecalRenderer works - please let me know if this solves your issue! You shouldn't need Component.Reset or anything like that. It should just listen for changes.

**Comment by anthonysharpy** [comment]
@DevulTj works great, thanks so much 😄 


https://github.com/Facepunch/sbox-issues/assets/55365296/565bf404-e26a-4202-bfc7-b2202a4438eb


BTW, with the async thing, I noticed that Task.DelayRealtime works but Task.Delay does not (not even sure what the difference is between them tbh). also, i'm gonna see if i can try find the normal of the face but looking at its triangle vertices and calculate it from there. so happy for this to be closed, i can make a new issue if i get stuck

**Comment by anthonysharpy** [comment]
oh so turns out there is .Normal on the trace result... not sure if that was just added or if i was being blind before 😄 not sure why i have to add 90 degrees to it but this code works perfect for me in case anyone else comes across this

var hit = Scene.Trace.Sphere( ... blah blah ... ).Run();

var angle = hit.Normal.EulerAngles;
angle = angle.WithPitch( angle.pitch + 90f );
DoImpactEffects( hit.HitPosition, angle );

anyways, closing this now
