### ISSUE TITLE
Dragging Camera Component's viewport size causes hard crash

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4190]
1. Play scene
2. Select Camera
3. Drag viewport W to the left so it goes negative
4. Result

Obviously this is the wrong thing to do, but we should never be letting the developer kill their game like this. These things should be sanitized before being used.

**Comment by DevulTj** [comment]
I added a few things to prevent against this. It's now clamped in SceneCamera to prevent crashing. I also made the control widget respect RangeAttribute.

![sbox_g6X5TNg4fQ](https://github.com/Facepunch/sbox-issues/assets/22372616/627f99b7-3eff-4e86-91e0-fb2cbe84e23c)

**Comment by garrynewman** [comment]
These tiny sliders are a terrible idea

**Comment by DevulTj** [comment]
The sliders are gone but the ranges are there. Should be all good now
