### ISSUE TITLE
Gizmo.Draw.ScreenText tabs show as boxes

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4192]
![Image](https://github.com/Facepunch/sbox-issues/assets/928843/eca1dfd5-05a5-4cd8-b8ac-d4e96eb4ca6d)

```
Gizmo.Draw.ScreenText( $"AnalogMove:	{Input.AnalogMove}", new Vector2( 100, 100 ), flags: TextFlag.LeftTop );
```

Do we translate these in the UI system or something?

**Comment by cr4yz** [comment]
It'll be something we do in RichTextKit when dealing with whitespace, tabs weren't supported before.  I'll see what we need here
