### ISSUE TITLE
VRAM fills up after playing and stopping a scene a bunch

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4193]
### Describe the bug

It seems that whenever a scene is played in the scene editor, some fog_lighting_clipmap textures are made that take up space on the GPU forever. 

### To Reproduce

1. Open up a scene in the scene editor
2. Wildly mash the F5 button to start and stop the scene
3. Observe that the game textures are now muddy and the console is being spammed

### Expected behavior

The 10th run of a scene should not take up significantly more resources than the 1st.

### Media/Files

Message that gets spammed in console:
![image](https://github.com/Facepunch/sbox-issues/assets/8889285/25e9d85e-6a7e-44c7-8543-b122002f5efa)
From the GPU Resident Textures window:
![image](https://github.com/Facepunch/sbox-issues/assets/8889285/09642a1a-92d6-4f69-8418-b0376179c950)

### Additional context

I first noticed the issue today, so maybe it was caused by a change today.

**Comment by handsomematt** [comment]
I've made cameras dispose of these now as well as not create them in the first place if there's no volumetric fog volumes in the scene.
