### ISSUE TITLE
Massively long stall when trying to upload scene game

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4194]
### Describe the bug

The whole editor stalls for upwards of 500 seconds while trying to upload a scene game if it's big enough:
![image](https://github.com/Facepunch/sbox-issues/assets/11138884/9dd591ab-7464-4a03-b7f2-005c751c87c9)

### To Reproduce

Literally just try uploading any scene game and you'll probably see it stall

### Expected behavior

just compile and don't stall for 500 seconds, maybe like 20-30 seconds at most I would expect, if that?

**Comment by garrynewman** [comment]
How many files is it uploading?

**Comment by ShadowBrian** [comment]
Not too many I don't think, this project is barely off the ground, just uploading so I can test multiplayer in some scenes

**Comment by handsomematt** [comment]
Can you upload your Log.txt too

**Comment by ShadowBrian** [comment]
Looks like it got overridden by the test client, give me like 10 minutes to upload again

**Comment by ShadowBrian** [comment]
took _exactly_ 500 seconds but uhhh, the log is unhelpful.
![image](https://github.com/Facepunch/sbox-issues/assets/11138884/41672463-45a3-4d23-b7cc-bc3e9bdfaf78)

**Comment by DevulTj** [comment]
Stuck a couple of logs in to see what's taking so long..

```
2023/12/24 16:09:05.2516	[GameMenu] Assets count: 337	
2023/12/24 16:09:05.2516	[GameMenu] Asset assets/particles/laserdot.vpcf has 1 references	
2023/12/24 16:09:05.2635	[GameMenu] Asset assets/particles/laserline.vpcf has 1 references	
2023/12/24 16:09:05.2759	[GameMenu] Asset assets/scenes/gunfight_fps_testing.scene has 187 references	
2023/12/24 16:09:10.2488	[engine/ToolsStallMonitor] Stall detected(5.007s): '(Unknown Cause)'	
2023/12/24 16:09:34.4866	[GameMenu] Asset assets/scenes/gunfight_fps_testing.scene_c has 187 references	
2023/12/24 16:11:01.8104	[GameMenu] Asset assets/scenes/gunfight_main_menu.scene has 188 references	
2023/12/24 16:13:26.9288	[GameMenu] Asset assets/scenes/gunfight_main_menu.scene_c has 188 references	
```

Did some benchmarking...

![image](https://github.com/Facepunch/sbox-issues/assets/22372616/6041445d-c99b-4050-9cda-ca6362bfceb7)

It's taking a long time in `WildcardMatch` - but it's also worth noting how many references we have on each scene.

![parsecd_vekYArI5aU](https://github.com/Facepunch/sbox-issues/assets/22372616/630b5b41-f3bc-4e91-b7a5-974fff57e890)

Very easy repro on trying to publish a new version of https://github.com/Facepunch/sbox-gunfight.

**Comment by garrynewman** [comment]
This should be fixed now. Was re-querying a linq enumerable in a loop instead of resolving it to an array first.
