### ISSUE TITLE
Add a "TintColor" node to shadergraph

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4195]
### For?

S&Box

### What can't you do?

In the old system if you used a Vertex Color node in a shader made in shadergraph it'd get filled out by setting the tint of an object, in the new Scene system it seems like tinting is done slightly differently.

### How would you like it to work?

 I would like some obvious way to get the model's tint set in the scene editor, probably a node or perhaps just a button in the color node that makes it get the tint value instead.

### What have you tried?

You can manually code a shader that gets the tint properly I think, since it's likely just setting the tint value of the complex shader, but matching the name of that is a bit tricky at the moment I believe.

**Comment by aylaylay** [comment]
I've added a Tint node that will grab the tint color of the scene object, I'll add something shortly to change the tint of the preview

**Comment by aylaylay** [comment]
![sbox-dev_ELn53pVfKS](https://github.com/Facepunch/sbox-issues/assets/1667289/e6dcc092-e3ae-4b70-a28f-9dc1380e1feb)

**Comment by ShadowBrian** [comment]
Perfect! Its been so long I don't even remember what I needed this for but I will mark it as completed.
