### ISSUE TITLE
Gizmo selection bounds do not properly reflect scaled gameobject

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4198]
### Describe the bug

In a scene, a non-uniformly scaled GameObject has the selection bounds of a uniformly scaled GameObject. That is to say, it appears like I am hovering over the GameObject when I am not. 

### To Reproduce

1. Create a scene
2. Add a GameObject
3. Scale x by 5, while leaving y and z at 1
4. Notice clicking on the outside of the GameObject will click the GameObject

### Expected behavior

The selection only occurs within the bounds of the object

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/57276947/76fcc22a-37d8-49ec-b515-8e4b0000c668

**Comment by garrynewman** [comment]
I noticed this too

**Comment by garrynewman** [comment]
Should be fixed - let me know

**Comment by trundlr** [comment]
It is fixed 👍 Thanks!
