### ISSUE TITLE
PlayerController component should support controller

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4199]
### For?

S&Box

### What can't you do?

- Navigate menus using a controller
- Exit a game or open the menu with a controller
- Most games don't support controller in any way

### How would you like it to work?

- Menus should be navigable with joysticks and bumpers
- The start button should function identically to escape, not sure why you would want it bound to anything else
- Game templates should have controller support by default (the player controller component uses mouse specific actions instead of analogmove / analoglook )

### What have you tried?

pressing all the buttons on multiple different controllers with no results.

**Comment by DrakeFruit** [comment]
Not sure why w a s and d are set up as individual actions in projects by default anyways, AnalogMove takes controller and keyboard into account and could be bound to different keys universally

**Comment by handsomematt** [comment]
Gamepad UI duplicate #954 

Input.AnalogMove could probably be retired and the character controller responsible for checking both, I don't like that it uses hard coded input actions.

**Comment by DrakeFruit** [comment]
> Gamepad UI duplicate #954
> 
> Input.AnalogMove could probably be retired and the character controller responsible for checking both, I don't like that it uses hard coded input actions to create it. We have Input.GetAnalog for controllers.

If analogmove was removed would you not have to manually implement something similar? I really like how simple it is right now and just wish it was compatible with custom key bindings

**Comment by handsomematt** [comment]
Doesn't seem like such a huge deal to do this or similar:

```cs
if ( Input.Down( "Forward" ) ) WishVelocity += rot.Forward;
if ( Input.Down( "Backward" ) ) WishVelocity += rot.Backward;
if ( Input.Down( "Left" ) ) WishVelocity += rot.Left;
if ( Input.Down( "Right" ) ) WishVelocity += rot.Right;
// Add controller move
WishVelocity += new Vector3( Input.GetAnalog( InputAnalog.Move ), 0 );
```

AnalogMove would have the engine making assumptions about input actions and what your game is doing.

**Comment by garrynewman** [comment]
I think it's safe to make assumptions that a gamepad will have an analog joystick though, we don't have to make things purposefully hard for people.

**Comment by handsomematt** [comment]
We do make that assumption, I'm against assuming in engine we have Forward Backward input actions to construct Input.AnalogMove from the keyboard.

I think we should be removing Input.AnalogMove and Input.AnalogLook and be using Input.Down and Input.MouseDelta like we already do in PlayerController. And then add controller support on with the already existing Input.GetAnalog( InputAnalog.Move/Look ) API.

```cs
public class PlayerController : Component, INetworkSerializable
{
	public void BuildWishVelocity()
	{
		WishVelocity = 0;

		// How it's done now (minus the controller input)
		if ( Input.Down( "Forward" ) ) WishVelocity += rot.Forward;
		if ( Input.Down( "Backward" ) ) WishVelocity += rot.Backward;
		if ( Input.Down( "Left" ) ) WishVelocity += rot.Left;
		if ( Input.Down( "Right" ) ) WishVelocity += rot.Right;
		WishVelocity += new Vector3( Input.GetAnalog( InputAnalog.Move ), 0 );

		// How OP wants it
		WishVelocity  += Input.AnalogMove * rot;
	}
}
```

**Comment by garrynewman** [comment]
I'm not so sure making them check button and analog inputs is better. I can totally see justification for just wanting to use AnalogMove. I can totally see why people would want to do `Input.AnalogMove` versus `Input.GetAnalog( InputAnalog.Move )`, I'd rather use a property too, I don't see any particular need to have GetAnalog versus exposing them as properties.

The sticking point here seems to be how AnalogMove gets built internally. IIRC it tests whether those inputs exist first, before trying to use them. I suspect in the future we can bind the digital buttons to analog inputs - and that will avoid this completely.
