### ISSUE TITLE
Disabled components can't be dragged into slots in the Inspector

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4200]
### Describe the bug

Dragging a disabled component into a slot in the Inspector makes that slot empty.

### To Reproduce

Drag and drop a disabled component onto any slot that would normally accept it.

### Expected behavior

Disabled components should behave the same as enabled when dragging and dropping in the editor UI.

**Comment by cr4yz** [comment]
Fixed in next build, please let me know if you have any more trouble with it.
