### ISSUE TITLE
[Shadergraph] Transform Normal Shading Errors

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#4201]
### Describe the bug

When using a transform normal node in the shadergraph the shading seems to be incorrect.

Left is complex, right is the attached shader.
![image](https://github.com/Facepunch/sbox-issues/assets/60801006/86afe19a-63a4-4783-9477-defe905505a6)

If you untick "Decode Normal" on the transform normal node then the shading will be more accurate but it will not use the full range of the normal texture.

### To Reproduce

Copy the shadergraph clipboard code into a new shadergraph shader.
Apply shader to a material and model.
Choose a normal map texture to use.
Compare to a duplicate mesh using the complex shader and the same normal map texture.
```
shadergraph:H4sIAAAAAAAACn1TYWvCMBD9L/lcp61Stn6TuQ1hU3FuX8aQWM8ukCYluYBO+t93qW1pFUYppO/eXd69u56Z0nuwLPk6s20quaUje5aa44QF7JNLBwSEQfUQsuC5B+g0t1NEI3YOCThwaSFgH3OWnNnmVHjOo5baEHFlRM7N6cVoV/hwU6IsqcgeFIqDAEPIyJO1FSi0os/BeDQJBuNxzMqgI25juLIHbfIFvVx6Japw+F7w1JfdcJVRTYJnkFJrNStB4+DqvvDqviii+x7ipqLX2uNHFFk6rEJsDdZJ9E10tcERnYF3nheSUqhQzjOvCrWWdkg+ZGCHOeDliGRUjW79easqsXeFyii3qZKcy8bZ2rq28xkcuFfRndDTEUHZS0stcWV0CtbSPBpQ/NbWWApXo2ocfBUK+L+DowQDHKG2qftVOxDNPOvGva7bkzCu3O4ZWLvadrYkTQJPLAlbaK1d9qOomS74BsjlBRy14DTfCRKwTFPpLoZQQk/TuK/pfhQMwtiv4VTuYK9vNsCHbjaAfop6x67Yfhq3+/Jd/gES+JlKdAMAAA==
```

### Expected behavior

Shading should match the complex shader.

**Comment by handsomematt** [comment]
You can choose which normal space this uses now, it defaults to tangent which is what you'd want. Let me know if it works.

**Comment by Jammie3d** [comment]
Seems to be good now, thanks!
