### ISSUE TITLE
Scene: Can't assign GameResource that inherits type in property

### ISSUE THREAD

**Issue by yikegaming** [Facepunch/sbox-issues#4204]
### Describe the bug

If you have these two game resources `public class ResourceA : GameResource` & `public class ResourceB : ResourceA` and you have a component with `[Property] public ResourceA resource {get; set;}` You cant assign a resource of type ResourceB to that property through the asset browser

### To Reproduce

1. Create two GameResources, one type inheriting the other
2. Create a property on a component of the type of your first GameResource
3. Try to assign a resource of the type of the second GameResource

### Expected behavior

I expect all resources of types that inherit the type I have set on the property to appear in the browser.

### Additional context

I have found that you can copy and paste the path of the resource into the property in the inspector and it can be assigned through code with no errors. But dragging and dropping from the asset browser doesn't work and it straight up doesn't show up as an option if you select the property to assign the resource. the

**Comment by aylaylay** [comment]
Fixed
