### ISSUE TITLE
Terrain data makes .scene files 1000x larger

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4205]
### Describe the bug

After saving a scene that contains terrain, the file size of the .scene will be over 10 megabytes. This makes the file very annoying to read, as I often do in GitHub Desktop before making a commit. I feel that the .scene file should always be human-readable for sanity checking and troubleshooting purposes.

### To Reproduce

1. Create a scene with a few objects.
2. Save the scene.
3. Observe that the scene file is of modest size.
4. Create terrain in the scene.
5. Save the scene again.
6. Observe that the scene file is now a thousand times larger.

### Expected behavior

Very large data such as what gets saved for terrain should probably be saved outside of the .scene file.

### Media/Files

<img width="391" alt="image" src="https://github.com/Facepunch/sbox-issues/assets/8889285/514d63b0-a0ac-4c00-acd9-619ef5395a60">

https://github.com/Facepunch/sbox-issues/assets/8889285/2e3c3b63-d289-4ca5-9caa-926241dd0ee4

**Comment by aylaylay** [comment]
I think this was just a limitation at the time when terrain wasn't in engine. We for sure shouldn't be saving it as json @handsomematt

**Comment by garrynewman** [comment]
I can see that storing it in the scene is a lot simpler, cleaner and easier, but yeah shouldn't really be the only option - and in this instance would maybe be better off as compressed base64'd binary data in the json to save space/serializing.

Something we need to think about when changing this stuff is versioning. Components should probably save a schema version number, and have functions to upgrade from one to the next. We shouldn't be breaking people's scenes when we change this stuff.

**Comment by handsomematt** [comment]
Terrain data is a versioned gameresource now
