### ISSUE TITLE
ModelDoc - Add PhysicsShapeCylinder

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#421]
There's no cylinder physics shape in modeldoc. This spool's collisions should be 3 cylinders, but that doesn't exist. I'd have to create a custom physics mesh.

![image](https://user-images.githubusercontent.com/39461072/123715828-c1725680-d83e-11eb-9166-a69a7145dddb.png)

**Comment by aylaylay** [comment]
I've just added this, the rendering of it could be better but it's good enough for now. Let me know how you get on with it.
