### ISSUE TITLE
No lighting at all for non-clearing camera view

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#4213]
![parsecd_7EhMVmYOz8](https://github.com/Facepunch/sbox/assets/22372616/1d1ab518-aefb-441c-901e-f366ef935135)

Tried directional and point lights. You can test this out using https://github.com/Facepunch/sbox-gunfight/tree/camera-lighting-bug.

**Comment by samzanemesis** [comment]
Needs a bit of rethought, lights will be from static view if you're taking out tags
![image](https://github.com/Facepunch/sbox-issues/assets/6563447/af723c25-8ddf-497e-b9d2-e865e63fefae)

**Comment by DevulTj** [comment]
https://github.com/Facepunch/sbox-issues/assets/22372616/0d96f93b-000a-4077-bafe-5f11b1f28460

I had another look and found the problem. We just weren't passing the GameObject tags to the light.

This does pose another question - should we even have to? if there's no tags to pass, it should be included instead of being explicitly defined.
