### ISSUE TITLE
Custom Fonts not working in scene games

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4220]
### Describe the bug

Can't use custom included ttf fonts in scene games the same way we could with entity games.

### To Reproduce

1. Create a /fonts/ folder and add your ttf (with -Regular, -Bold, ect variants)
2. Refer to the font by the file name (before the -Regular) in css
3. If you have the font installed on your computer (c:/windows/fonts) you *will* see the change reflected, however if you do not (or upload the game to asset party with the font resources included, others will not see the font)

### Expected behavior

Custom fonts should be recognized in scene games

**Comment by Gmod4phun** [comment]
Agree, personally, I had issues with custom fonts sometimes not loading even in regular games, see #3427

**Comment by handsomematt** [comment]
Fixed, not sure about the related issue but I added some logs when a font can't be found that may help debug.
