### ISSUE TITLE
Add an offset to all types of colliders

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4222]
### For?

S&Box

### What can't you do?

I'm unable to offset colliders of any type, this is a recurring problem when working with the flat plane model.

### How would you like it to work?

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/c742461e-2245-4931-bfa4-277ebbba4e4a)
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/eb2ad883-d752-43b2-93f0-cbb6ed3f6ef7)

### What have you tried?

For the plane I can just have the collider be really thin but it looks bad and is bad practice in my opinion

**Comment by Willco2** [comment]
Duplicate of #4185

**Comment by yuberee** [comment]
I had concept arts and all
