### ISSUE TITLE
Property of type List<enum> don't get populated because of casting issue

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4224]
### Describe the bug

Components with properties that take List of enums will have the enums not show up and spit the following error in console:
```
Unable to cast object of type 'UnitType' to type 'System.Int64'.
System.InvalidCastException: Unable to cast object of type 'UnitType' to type 'System.Int64'.
   at Sandbox.SerializedListProperty.GetValue[T](T defaultValue)
   at Editor.EnumControlWidget.PaintControl()
   at Editor.ControlWidget.OnPaint()
   at Editor.Widget.InternalPaintEvent(QPainter e, Int32 flags)
   at Managed.SourceTools.Exports.Editor_Widget_InternalPaintEvent(UInt32 self, IntPtr e, Int32 flags)
```
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/d15090d8-f4a9-41c0-815e-b333a6332ee0)

### To Reproduce

1. Define a new enum
2. Have a component with a property being List of that enum
3. Check inspector

### Expected behavior

To cast correctly into an Int64 and fill the dropdown menu

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/21df38f1-a266-4ffa-9bf1-9abbbbc31647)
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/6e5b1649-7ca4-4b1a-98c4-716851d96c94)

### Additional context

Having your enum derive from Int64 fixes the error since it has no problem casting.
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/2b19be70-deb2-42b3-97e4-0f878b7ae6a1)
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/fa8e9351-91c8-45ec-9ac3-1b5902ed2959)

**Comment by DevulTj** [comment]
This is working for me, can you please try again?

**Comment by yuberee** [comment]
Not having it derive from Int64 now makes the options show up but I am unable to select them.
This is the code: https://github.com/Small-Fish-Dev/Snop-Farm/blob/main/code/Unit/UnitType.cs

Without deriving from Int64: 
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/b51abbaf-6f95-4608-adf2-19876450c44c)

Deriving from Int64:
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/490af31f-e575-4caf-ae68-7683a773a865)

**Comment by DevulTj** [comment]
Ty I'll have a look

**Comment by DevulTj** [comment]
This has been fixed in the last few months or so.
