### ISSUE TITLE
Graphics.RenderToTexture Crashes To Desktop

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4226]
### Describe the bug

I am doing something like this in a Panel class

```
public partial class GUIProfileMenu
{
	public Image CharacterImage { get; set; } // Links to <image></image> in .razor file using @ref=
	private SceneCamera CharacterCamera;
	private Texture CameraTexture;

	protected override void OnAfterTreeRender( bool firstTime )
	{
		if (firstTime)
		{
			CharacterCamera = new SceneCamera();
			CharacterCamera.ZFar = 1000;
			CharacterCamera.World = Camera.Main.World;
		}
	}

	public override void Tick()
	{
		if ( !IsVisible || CharacterImage == null )
			return;

		CameraTexture = Texture.CreateRenderTarget().WithSize(new Vector2(100, 100)).Create();
		Graphics.RenderToTexture( CharacterCamera, CameraTexture );
		CharacterImage.Texture = CameraTexture;
	}
}
```

When I start the scene this usually produces a crash

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/5aceaeb0-3c36-45d7-b4f9-cfb32c4e82b5)

I was hoping I could do all this with CameraComponent instead of SceneCamera but I couldn't find the same functionality for that

### To Reproduce

see above

### Expected behavior

Doesn't crash

### Additional context

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/d9703399-6289-4d98-a111-223e1035d0c7)
![image](https://github.com/Facepunch/sbox-issues/assets/55365296/c8861ab3-30d7-4449-ba93-ef00d2b17f70)

SteamID 76561197997412036

Nothing useful in the logs

**Comment by anthonysharpy** [comment]
The more I think about this the more I think my approach is wrong anyway since I was trying to spawn an entity... but what's the new way of doing it? 🤔

**Comment by PolSpock** [comment]
i already sent you a DM but it can be useful for another reader:

For me, the issue is similar to https://github.com/Facepunch/sbox-issues/issues/3452
[Sandbox.UI.Panel.DrawBackground(RenderState)](https://asset.party/api/Sandbox.UI.Panel.DrawBackground(RenderState)) must be used with `Graphics` API call

**Comment by anthonysharpy** [comment]
Yup this is a duplicate of #3452 😄 oops! Gonna keep it open though as this one is in triage whereas the other one is not 😆

**Comment by handsomematt** [comment]
Does this still happen? We were simulating UI in the middle of rendering accidentally before.

**Comment by anthonysharpy** [comment]
> Does this still happen? We were simulating UI in the middle of rendering accidentally before.

Yeah seems to be fixed, thanks
