### ISSUE TITLE
Terrain.RayIntersects performance

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4229]
Seem to be some kind of performance issue when editing terrain, and looking at the sky..

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/bf3e498d-18b2-4ee7-a563-44703ddb2caa)

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/4011156d-c960-4cdc-b053-c4d1428d710e)

**Comment by aylaylay** [comment]
The original RayIntersects function was just temp, I've added a faster way to do it now
