### ISSUE TITLE
Local dev games do not send razors .scss file to connecting players

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#4231]
### Describe the bug

.scss files do not get sent to connecting players, only the .razor file.

### To Reproduce

1. load the given project
2. hit play, you will see what it should look like
3. connect with new instance, new instance it will look bad and show there is no .scss

### Expected behavior

it should send .scss files along with all normal code!

### Media/Files

[test_1.zip](https://github.com/Facepunch/sbox-issues/files/13696027/test_1.zip)

**Comment by handsomematt** [comment]
@kurozael and this?

**Comment by kurozael** [comment]
All good 👍
