### ISSUE TITLE
Add ModelDoc `AnimEvent` `PlaySound`

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#4238]
### For?

S&Box

### What can't you do?

Hello,

Currently the old way of playing sound with ModelDoc AnimEvent by `AE_CL_PLAYSOUND` or `AE_SV_PLAYSOUND` is not working anymore.

### How would you like it to work?

I want it to work like the previous system: take a sound name and place it in a specific Frame.
It also be cool to be able to play the sound only for the player or for everyone like a `[Broadcast]` function call. So maybe with an optional checkbox?

![image](https://github.com/Facepunch/sbox-issues/assets/5229571/8bee8494-4bc2-4651-bb08-fe6c575aee71)

### What have you tried?

I have tried the previous system but it doesn't work anymore in-game: no sounds are played.
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/d7add10f-1575-46e8-a18b-ab7ef9664841)

**Comment by garrynewman** [comment]
I added functionality for this - but untested, please let me know if it worked.

**Comment by PolSpock** [comment]
For the host, sounds seem to be played at Vector3.Zero (both for `AE_SV_PLAYSOUND` and `AE_CL_PLAYSOUND`)

https://github.com/Facepunch/sbox-issues/assets/5229571/d3ae71db-a6ab-4884-b57b-daaee3fbd387

And for the connected instances, no sound are played / heard

https://github.com/Facepunch/sbox-issues/assets/5229571/c86e57bd-be48-442c-9ac1-1c8a5ee5846e

**Comment by garrynewman** [comment]
No sounds are played for connected clients because they're not playing the animation. There's no networking here - if you want to play a sound on the clients, it can't come from the viewmodel.

Do the sound events have an attachment point? Is it valid? If you don't specify one, does the sound still come from 0,0,0?

**Comment by PolSpock** [comment]
> No sounds are played for connected clients because they're not playing the animation.

Ok, but in this case :
There is a utility to keeping `AE_SV_PLAYSOUND`?
Why the sound are not playing even if my secondary user has the ViewModel and playing the Firing animation correctly? (video 2 of my previous comment) It must be played locally

> Do the sound events have an attachment point? Is it valid? If you don't specify one, does the sound still come from 0,0,0?

How can i specify any sound attachment point in modeldoc ? There are only a few options currently.
In the Entity System, it was directly played on Entity that loaded the VMDL

![image](https://github.com/Facepunch/sbox-issues/assets/5229571/105fc4f9-8d43-4d82-a04b-176eafe3433d)

**Comment by PolSpock** [comment]
Have you changed something? Today it looks good for both users (host & connected)

https://github.com/Facepunch/sbox-issues/assets/5229571/a87013ee-02d2-4e6f-a12f-65437952c3e5

However, there is still this interrogation pending :
- There is a utility to keeping `AE_SV_PLAYSOUND`? Since you said :
> No sounds are played for connected clients because they're not playing the animation. There's no networking here - if you want to play a sound on the clients, it can't come from the viewmodel.

**Comment by garrynewman** [comment]
no, SV_PLAYSOUND and CL_PLAYSOUND are identical. I only kept them both so people don't have to reconfigure all of their models.
