### ISSUE TITLE
Turning SceneObject.Flags.CastShadows off doesn't disable AO

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-issues#4240]
### Describe the bug

When you disable `SceneObject.Flags.CastShadows` such as a model rendered with `Gizmo.Draw.Model`, indrect shadows are still visible for that object.

### To Reproduce

1. Render a model with `Gizmo.Draw.Model`
2. Observe indirect shadows still visible even though it sets `SceneObject.Flags.CastShadows` to false

### Expected behavior

I'd expect there to be no shadows at all from this SceneObject

### Media/Files

![Image](https://files.facepunch.com/conna/1b1811b1/sbox-dev_9zZcb0zPz8.png)

**Comment by DevulTj** [comment]
This should be fixed now
