### ISSUE TITLE
Pressing F1 to open the console stalls the game

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4242]
### Describe the bug

Ingame, pressing the F1 key to open the console stalls the game. In editor mode, it does not seem to recover and constantly keeps stalling. When playing the regular game, it seems to stall for a bit, then recover, but the console isn't opened. Checked in menu to see that console is enabled.

### To Reproduce

1. Launch game
2. Press F1

### Expected behavior

No stalling, open console.

**Comment by handsomematt** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/1388267/7d96e491-ccb2-440b-909b-c3a28cd7d19e)

**Comment by Gmod4phun** [comment]
Looks fixed :) thank you
