### ISSUE TITLE
Disabled components can't be dragged into slots in the inspector

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4244]
### Describe the bug

Previous issue: https://github.com/Facepunch/sbox-issues/issues/4200

I still am not able to drag and drop a disabled component into a slot in the scene hierarchy.

https://github.com/Facepunch/sbox-issues/assets/57276947/38ca5d85-b483-4acf-b48d-51fe7af1053b

### To Reproduce

1. Create a component on a gameobject that accepts a specific component type
2. Create an object with the matching component, but disable the component
3. Drag the disabled component into the slot
4. Observe the slot not populating

### Expected behavior

The slot should populate so I can reference the component and enable it when I choose

**Comment by cr4yz** [comment]
Woops, should be fixed in the next build.

**Comment by trundlr** [comment]
Works now, thanks Crayz!
