### ISSUE TITLE
Cursor is a hand in the Game view of the editor even when it shouldn't be

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-issues#4246]
### Describe the bug

Using this stylesheet to show the cursor in-game:

```html
<style>
    CursorController {
        position: absolute;
        left: 0px;
        top: 0px;
        width: 0px;
        height: 0px;
        pointer-events: all;
        cursor: default;
    }
</style>
```

The cursor should be an arrow (it is when not using the editor) but it's showing what I would expect if it was set to `pointer`.

### To Reproduce

1. Create a PanelComponent and use the stylesheet provided above
2. Observe that in the Game view the cursor appears to be a hand as if you were hovering a link

### Expected behavior

The cursor should be the system default arrow.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/486972/cefc093b-e93e-4315-8c29-9f50a3ba674d

**Comment by garrynewman** [comment]
Could this have been the stylesheets not loading like in your other issue?

**Comment by kurozael** [comment]
Unable to reproduce this again as shown in the video at the moment, potentially somehow linked to #4245 - will first look into that one and keep an eye on this for now.
