### ISSUE TITLE
Grid Z Fighting when flying near it in Scene Edit Mode

### ISSUE THREAD

**Issue by mariovata** [Facepunch/sbox-issues#4248]
### Describe the bug

When approaching the grid in any scene, the grid starts to show green pixels (See video). 

### To Reproduce

1. Open Any Scene
2. Fly towards the grid
3. Observe the effect

### Expected behavior

1. Fly towards the grid
2. Observe the grid without the green artifacts

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/33606897/7c2c6754-d6b4-44b0-830c-c017f39d9ed1

### Additional context

Windows 10 Pro 64-Bit (10.0, Build 19045)
13th Gen Intel i9-13900K
32GB RAM
RTX 3090

**Comment by DrakeFruit** [comment]
I wouldn't say this is z fighting

**Comment by handsomematt** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/1388267/2e5c9f6f-3673-4f19-aceb-b5589fd9a4df)

Can't get it to happen myself anymore.

**Comment by DrakeFruit** [comment]
yep, fixed for me too

**Comment by mariovata** [comment]
Yes it is fixed, thanks!

**Comment by aylaylay** [comment]
nice grid
