### ISSUE TITLE
info_particle_system and snd_event_point broken

### ISSUE THREAD

**Issue by ImWill0w0** [Facepunch/sbox-issues#425]
**Describe the bug**

start active is ticked but they don't run

**To Reproduce**

try to use either entities

**Expected behavior**
 
play the particles, play the sounds

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/395

**Comment by robotboy655** [comment]
Start on/start on spawn should now appear functional.
