### ISSUE TITLE
Visualize Animgraph Parameters while playing + "Direct Playback" input (animation picker)

### ISSUE THREAD

**Issue by MaxLebled** [Facepunch/sbox-issues#4251]
![image](https://github.com/Facepunch/sbox-scenestaging/assets/3624123/29b3d7bd-369e-4f78-92d5-64d463e6fec6)

(Sorry for the low quality screenshot, I grabbed the first one I could find from my 2 years of various captures)

We had this in the old system — it would be great to have this functionality again

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/0da29c65-98b5-430d-ab38-30c3890b43a5
