### ISSUE TITLE
CitizenAnimationHelper "IsSitting" bool is actually supposed to be an enum

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4252]
### Describe the bug

The citizen sit state is determined by an enum called "sit" which has 3 states:
-Not sitting
-Sitting
-Sitting on the ground

### To Reproduce

Right now CitizenAnimationHelper has it as a bool on "b_sitting" which doesn't actually exist.

### Expected behavior

I'd love for an enum to be made for it and for that to be exposed as a property on the citizen animation helper too so we can make sitting terries without having to make a separate script to set the sit state.

**Comment by bakscratch** [comment]
Should be good, I also added the special move state (ledge grabbing, rolling)
