### ISSUE TITLE
Change Component order by clicking and dragging on header in the Inspector

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4254]
### For?

S&Box

### What can't you do?

The only way I know of to change the order of a GameObject's Components in the Inspector is to open the right-click menu on the header and select "move up" or "move down". If want to change a Component's position by several places, I have to perform that action multiple times.

### How would you like it to work?

The behavior for dragging a Component between two other Components should work the same as dragging a GameObject in the Hierarchy tree view between two other GameObjects.

### What have you tried?

Using the right-click menu to repeatedly move the Component up or down one place at a time.

### Additional context

This issue is more annoying if you tend to work with many small components or have code that works differently depending on component order.

**Comment by NotGaylien** [comment]
please! i have done this way too many times already, 

it just feels like the most intuitive way to move them.

**Comment by cr4yz** [comment]
Please note I've found a new bug when adding feature this that may seem like components don't get ordered correctly as you drag them around.  It's a separate bug of QT duplicating drag events.  I'm going to poke at that tomorrow.
