### ISSUE TITLE
Crash when recompiling a model used in active scene. 

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4256]
### Describe the bug

The game crashes if you attempt to recompile a model that is used in your active scene.

### To Reproduce

1. Apply model to a ModelRenderer in your active scene.
2. Recompile your model while the active scene is open.

### Expected behavior

The game should not crash.

**Comment by DevulTj** [comment]
this is due to a change I made to AO proxies - looking into it now

**Comment by DevulTj** [comment]
next build on steam should have resolved this problem - please let me know if this has solved your issue

**Comment by badandbest** [comment]
Looks like it's fixed now.
