### ISSUE TITLE
Add SceneUtility.Instantiate overloads that accept prefab file path

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4257]
### For?

S&Box

### What can't you do?

Currently, instantiating a prefab from code is very indirect unless a GameObject-type property of a GameObject has been set to the prefab file. But there are times when you might want to instantiate a prefab but don't have easy access to these properties, like if you're writing code in a GameObjectSystem. 

It seems that unless I create a GameObject that uses prefabs and properties, the the only way that I can instantiate a prefab is:
1. Load the PrefabFile using ResourceLibrary
2. Get create a PrefabScene, and get its Scene - or use SceneUtility.GetPrefabScene
3. Instantiate that Scene as I would any other GameObject

My intent is simply "instantiate this prefab file in the current scene", but I need to touch ResourceLibrary, PrefabFile, and maybe PrefabScene all along the way.

### How would you like it to work?

For every overload of SceneUtility.Instantiate that accepts a GameObject, I would like for there to be a similar overload that accepts a string instead. This string would be the path to a prefab file, which would be instantiated the same as any GameObject property would be instantiated.

### What have you tried?

The most headache-free and hard to forget way I have of working around this is to create a "prefab zoo" component which has GameObject properties that I use to refer to prefabs. Instead of using ResourceLibrary and PrefabFile, I just find that component in the scene.

**Comment by garrynewman** [comment]
Can you show me the code you have to write vs the code you want to write please

**Comment by chrisspieler** [comment]
> Can you show me the code you have to write vs the code you want to write please

What I write:
```csharp
var prefabFile = ResourceLibrary.Get<PrefabFile>( "prefabs/my_prefab.prefab" );
var go = SceneUtility.Instantiate( SceneUtility.GetPrefabScene( prefabFile ) );
```

What I'd rather write:
```csharp
var go = SceneUtility.Instantiate( "prefabs/my_prefab.prefab" );
```

**Comment by garrynewman** [comment]
I don't really want to encourage people to spawn things by path, so I'm not going to add this a requested, but we can clean up and make SceneUtility.GetPrefabScene (or something) take a string path to make things easier.

**Comment by Xenthio** [comment]
You could compare it to things like Sound.Play and previously things like Particles.Create and Decals.Place.
because doing something like 
`Prefab.Spawn("filename")`
is a lot nicer than 
`GameObject = SceneUtility.Instantiate( SceneUtility.GetPrefabScene( ResourceLibrary.Get<PrefabFile>( "filepath" ) ), Transform.Zero );`

**Comment by garrynewman** [comment]
But the idea is that you do

```
GameObject = SceneUtility.Instantiate( BulletPrefab, Transform.Zero );
```

then you don't have to hardcode paths at all.
