### ISSUE TITLE
SkinnedModelRenderer stops rendering if model origin is too far out of view

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4258]
### Describe the bug

I am almost perfectly sure the SkinnedModelRenderer stops rendering the model if the model's origin goes too far out of screen bounds. With the standard `ModelRenderer`, the model keeps rendering correctly until the model's view bounds are no longer visible, but not with `SkinnedModelRenderer`, needed for animated models.

The model itself is not rendered, but the shadows are.

https://github.com/Facepunch/sbox-issues/assets/5991682/9580af80-e792-41d9-bafa-c47cf36e3f79

I suspect it is the model's origin causing it, since in my case the model's origin is not close to the mesh itself and I remember something like this happening from my modding shenanigans back in the day: 
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/73d9430b-50e0-44f8-b61e-3a412965f7bc)

### To Reproduce

1. Have a model that has its origin outside of the model's view bounds 
2. Use SkinnedModelRenderer with such model
3. Slowly pan the camera/view until the origin of the model isnt on screen and it should stop rendering

### Expected behavior

The model should render correctly, just like with the standard `ModelRenderer`.

**Comment by garrynewman** [comment]
There's no code that stops this, could it be a LOD issue?

**Comment by Gmod4phun** [comment]
I would say no, as the model has no LODs yet.

**Comment by aylaylay** [comment]
Could I get a model this happens with please?

**Comment by Gmod4phun** [comment]
Sure, here are two models that I noticed have the problem

[some_models_for_layla.zip](https://github.com/Facepunch/sbox-issues/files/14627130/some_models_for_layla.zip)


https://github.com/Facepunch/sbox-issues/assets/5991682/2c29410e-fdf3-4e7c-b146-7003a5196116

**Comment by aylaylay** [comment]
Thanks

**Comment by aylaylay** [comment]
Just pushed a fix, bounds calculation for animated objects should be improved to cover this situation.

**Comment by Gmod4phun** [comment]
Yep, working nicely now, thanks so much.

**Comment by Gmod4phun** [comment]
Alright, so something might have gotten screwed up, as I believe it was working fine until now. Its another model that Im using which has morphs. Now it just randomly stops rendering depending on where you look at it from.

Works fine with standard model renderer, but with skinned (which it needs to morphs) started doing this:

https://github.com/Facepunch/sbox-issues/assets/5991682/a257cfcc-0c24-49dd-b706-a6148c3504ac

Here are the files (should have everything necessary): 
[kawoosh_model.zip](https://github.com/Facepunch/sbox-issues/files/14628214/kawoosh_model.zip)

**Comment by aylaylay** [comment]
Pushed a fix

**Comment by Gmod4phun** [comment]
Works again, thank you :)
