### ISSUE TITLE
Multi-Line Text For Text Renderer Component

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4261]
### For?

S&Box

### What can't you do?

It seems you can't have multi-line text in a Text Renderer component, at least not via the editor

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/f30703e0-b0d1-4129-aab9-abbd7c8446b5)

### How would you like it to work?

Multi-line input text box
So you can just
type it
like this

### What have you tried?

 < br>
\n
Pressing enter 💅

**Comment by badandbest** [comment]
We have a [TextArea] property now. I'd add that (And maybe some format options).

**Comment by DevulTj** [comment]
Just pushed that now, let me know if you encounter any problems.

**Comment by anthonysharpy** [comment]
Looks good! If I'm being really picky the only issue remaining is that you can't left-align the text. But I'm sure it will happen eventually 🤓
