### ISSUE TITLE
Connection.IsHost Seems Wrong

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4262]
### Describe the bug

When pressing play in the editor, this code prints 

False
True

When I would have expected it to print

True
True

```
public class MyGameBase : Component, Component.INetworkListener
{
	public void OnActive( Connection connection )
	{
		Log.Info( connection.IsHost );
		Log.Info( GameNetworkSystem.IsHost );
	}
}
```

Surely with the way the new scene system works the only connection/player on the server must be the host?

### To Reproduce

see above

### Expected behavior

see above

### Additional context

https://docs.facepunch.com/s/sbox-dev/doc/network-events-te4Wq9RLvs

**Comment by garrynewman** [comment]
This does all need tightening up

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by anthonysharpy** [comment]
this works for the host but on a connecting client it says that they're the host too:

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/23bfd93c-2b37-453b-b0c4-160561538095)

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/c76d5ae6-5f1a-495d-87e4-992f6958cdf5)

**Comment by garrynewman** [comment]
I can't reproduce that. OnActive gets called on the server only, during the client handshake. I've added this assert..

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/773a2c0c-9fca-49df-af1b-f22ae3c9fcda)

And nothing is being triggered.

**Comment by anthonysharpy** [comment]
Maybe the remaining bug in this case then is that the server logs are getting output to the connecting client's console? Guess that would be a separate issue, so feel free to close this
