### ISSUE TITLE
Eliminate frame gameobject iteration

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4264]
In a few different places right now we're iterating every child, every frame. This results in 30+ms frame times with tens of thousands of models in a scene.

* FixedUpdate
* Update
* PreRender

We should change this to be a targeted list. So for example when a component becomes enabled, and has overridden OnUpdate, it gets added to the scene's OnUpdate list. This needs to be done carefully, because we need to be able to add/remove components to this list while iterating.

PreRender is currently called for every model in the scene and updates the position/transform. We should have a dirty renderer system here instead, because these model updates can be done in parallel and only when changed.. which would be a lot nicer.

**Comment by kurozael** [comment]
Just for future reference I did some tests on `updaters-test` branch where I have CodeGen add an `IUpdateListener` interface to each component class that overrides `OnUpdate` or `OnFixedUpdate`. I then have it add those to a list when enabled to only iterate those, as well as adding GameObjects with dirty tags to an update list and iterate networked objects separately for transform interpolation.

Initial results from just doing that seemed positive (~47 FPS in-game with 30,000 cubes with just ModelRenderer) compared to (~28 FPS with the current way of doing things.)

I imagine a combination of this and what you mention about `PreRender` it could be pretty good.

**Comment by kurozael** [comment]
This is solved with @handsomematt's recent optimizations. Closing.
