### ISSUE TITLE
ModelRenderer does not update its model after clearing it unless the component is re-enabled

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4266]
### Describe the bug

After clearing the Model option of ModelRenderer, the displayed mesh does not reset to the default cube unless the component is re-enabled.

 

https://github.com/Facepunch/sbox-issues/assets/5991682/ef07f61d-a24d-47b7-89ba-a4428dc40308

### To Reproduce

1. Spawn GameObject with ModelRenderer
2. Add a model
3. Clear model
4. See that it does not change until the component is re-enabled

### Expected behavior

The model should update to the default one.

**Comment by aylaylay** [comment]
It should reset back to default cube now

**Comment by Gmod4phun** [comment]
Seems to work now, thank you
