### ISSUE TITLE
Scene files don't show up under "Recent" in the Assets Browser

### ISSUE THREAD

**Issue by MaxLebled** [Facepunch/sbox-issues#4267]
![image](https://github.com/Facepunch/sbox-issues/assets/3624123/5a6d9dee-318b-499e-9145-f8ec8bc6bf1f)

Been opening plenty of scene files, but they don't show up here

**Comment by DevulTj** [comment]
![parsecd_dQvBYTUb1B](https://github.com/Facepunch/sbox-issues/assets/22372616/5ae264ad-c0c0-4d31-9079-d6ef94a25e87)

This seems to be working for me
