### ISSUE TITLE
Startup Scene never loads on the first project load

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4268]
### Describe the bug

When I open a project in the S&box Editor, the scene loaded is the default nearly empty scene with a light and a camera. I have to close the project and reopen it before the startup scene actually loads.

### To Reproduce

1. Ensure that you have a project with a valid Startup Scene specified in the project file
2. Ensure that the S&box editor is completely closed
3. Start the S&box editor
4. Open your project
5. Observe that the Startup Scene has not loaded
6. Go to File -> Close Game Project
7. Reopen the same project
8. Observe that your Startup Scene has now been loaded

### Expected behavior

If specified, the Startup Scene should be the scene that is loaded when opening a project.

### Media/Files

[Log.170.log](https://github.com/Facepunch/sbox-issues/files/13728414/Log.170.log)

https://github.com/Facepunch/sbox-issues/assets/8889285/0d868717-d6b3-4215-b0a5-f5a19ca7f635

**Comment by DevulTj** [comment]
This should work now
