### ISSUE TITLE
Generated asset videos flucuate in brightness

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4270]
### Describe the bug

The generated asset video get noticably brighter over its duration.

I believe it might be auto-adjusting brightness mid-generation?

### To Reproduce

1. Publish a model to asset.party.
2. The generated video gets noticably brighter over its duration.

### Expected behavior

It should remain the same brightness troughout for it to be a perfect loop.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/91832803/fe7d44b5-4534-4412-a601-bd4e725ff995

https://github.com/Facepunch/sbox-issues/assets/91832803/e766268a-e244-4b19-a620-b58fa62cad86

Old models don't have this problem.

https://github.com/Facepunch/sbox-issues/assets/91832803/a9e4588d-97e1-48e9-a529-de0d728928fb

Here I'm publishing a model to asset.party. It gets increasingly brighter throughout the video generation.

https://github.com/Facepunch/sbox-issues/assets/91832803/b4c626e0-fffc-4a57-8118-0de1afdd45a5

https://github.com/Facepunch/sbox-issues/assets/91832803/c2e4d155-7f07-4571-a5d8-963823ce2372

### Additional context

A similar thing happens in the preview. Probably related.

https://github.com/Facepunch/sbox-issues/assets/91832803/67fc89d1-c024-4f32-ae94-46d9281704ac

**Comment by garrynewman** [comment]
I get this in the scene view too, but it reverts to normal when I switch to the game view and back. Might be something @samzanemesis knows more about.
