### ISSUE TITLE
Add virtual OnPanelLoaded method to PanelComponent

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4271]
### For?

S&Box

### What can't you do?

In PanelComponent, properties that are `@ref` references do not get set until _after_ the first call to OnUpdate. It seems that there's no method I can override with the assumption that all the code I run in it will have access to the `@ref` Panels.

### How would you like it to work?

Add a virtual OnPanelLoaded method to PanelComponent that is called after the `@ref` references of PanelComponent have been set.

```csharp
// This panel is set by a @ref reference.
private Panel MyPanel { get; set; }

protected override void OnPanelLoaded()
{
    // No NRE will be raised, assuming I've set the @ref correctly in razor.
    MyPanel.DoSomething();
}
```

### What have you tried?

To work around this, I can just check whether the Panel is null, but I have to reset the flag every time the PanelComponent disabled and then reenabled.

```csharp
// This panel is set by a @ref reference.
private Panel MyPanel { get; set; }

private bool _panelLoaded = false;

protected override void OnEnabled()
{
    base.OnEnabled();

    _panelLoaded = false;
}

protected override void OnUpdate()
{
    if ( !_panelLoaded && MyPanel is not null)
    {
        MyPanel.DoSomething();
        _panelLoaded = true;
    }
}
 ```

**Comment by garrynewman** [comment]
Note: needs OnAfterTreeRender to loop back, the same way BuildRenderTree is. We could probably split it into OnFirstRendered, OnRendered.
