### ISSUE TITLE
Position and Scale is broken on Transforms parented to an object with non uniform scale

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4274]
### Describe the bug

It seems that doing any kind of transform fuckery with something parented to a non uniformly scaled object in code is all kinds of broke 

### To Reproduce

Parent an object to something with non uniform scale and mess with its position and scale

### Expected behavior

Setting scale should respect the parent non uniform when it converts to a localscale (will currently become uniform)
Setting Position will localise the position as if the scale is uniform, even if the localscale is untouched.

**Comment by garrynewman** [comment]
I think fixed this now
