### ISSUE TITLE
[ActionGraph] GameObject Components ForEach node breaks the tool window completely.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4275]
### Describe the bug

.

### To Reproduce

1. Create an Action of type `Action<GameObject>`
2. Try to create a ForEach iteration node for the GameObject's Components.
3. ActionGraph editor tool breaks completely.

### Expected behavior

.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/66768086/f2451d87-73b5-45d2-899f-16349f91a39d

**Comment by Metapyziks** [comment]
I've stopped similar unsupported methods from being listed, and now you can use a new `Components -> Get All` node, then `Control Flow -> For Each` on its result.
