### ISSUE TITLE
Async general unexpected behaviour

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4276]
### Describe the bug

I'm trying to make the model grow, wait half a second, then shrink it back.
Initially I tried using GameTask.Delay, but it doesn't actually work and instead runs it all at the same time, but it doesn't seem to actually match with what's printed in my console.
I then switched to GameTask.DelayRealTime and initially it seemed to work, but I then noticed that it wouldn't scale the model up before shrinking it.
Leading to overall shrinkage.

Doing some debugging revealed that despite succesfully setting the scale the first time, it would get ignored after the Delay and it would shrink the original unshrunken size.
Logging Time.Now reveals that after using Delay it would return RealTime.Now instead.

### To Reproduce

Here's the code I'm using:
```
public async Task HurtAnimation()
{
	if ( Renderer == null ) return;

	Log.Info( $"Current Time.Now: {Time.Now}" );
	Log.Info( $"Current RealTime.Now: {RealTime.Now}" );

	Log.Info( $"Initial scale is: {Transform.Scale}" );

	Log.Info( $"Current Time.Now is: {Time.Now}, Scale is {Transform.Scale} multiplying scale by 1.05" );
	Transform.Scale *= 1.05f;
	Log.Info( $"Scale is now {Transform.Scale}" );

	await GameTask.DelayRealtime( 500 );

	Log.Info( $"Current Time.Now is: {Time.Now}, Scale is {Transform.Scale} dividing scale by 1.05" );
	Transform.Scale /= 1.05f;

	Log.Info( $"Final scale is: {Transform.Scale}" );

	return;
}
```

Just switch GameTask.DelayRealtime with GameTask.Delay to test the other happenstance.

### Expected behavior

Correctly keep track of Time.Now I guess is the issue, but I'm not sure it explains why the model doesn't get scaled up initially.

### Media/Files

In the video shown I first try it with GameTask.Delay, you can see in the console it logs it instantly. After the reload I try with GameTask.DelayRealtime and you can see it works but not initially. Both times Time.Now gets switched.

https://github.com/Facepunch/sbox-issues/assets/59583743/b5c71878-6e41-4ca1-96d4-0f9199833901

**Comment by yuberee** [comment]
Just as a sidenote, this code works as I wanted it to:

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/6942a209-1eae-4a91-80fe-703ff90640e8)

**Comment by Gmod4phun** [comment]
Can confirm that Task/GameTask.Delay or DelaySeconds is behaving weirdly and seems to not work. Realtime variants seems to work, but that's not feasible with variable game timescale.

**Comment by garrynewman** [comment]
Should be fixed now. On a side note, you don't have to manually use GameTask when calling from a component, it has a member called Task - which is a GameTask.

**Comment by yuberee** [comment]
Gotcha, works now as well. Thank's
