### ISSUE TITLE
A few gizmos are missing a way to rotate

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4278]
### For?

S&Box

### What can't you do?

Some gizmos have the ability to be rotated such as LineCircle and others do not need a rotation because of how they're set up like LineCylinder.
The gizmos that have no way to rotate the direction they're facing are the following:

SolidCircle
SolidRing
SolidBox

### How would you like it to work?

Similar to LineCircle, they should have a Vector3 Axis or Vector3 Normal parameter

### What have you tried?

I'm currently using two LineCircles instead of a SolidRing but it doesn't convey exactly what I'm envisioning.

**Comment by garrynewman** [comment]
using ( Gizmo.Scope( "circle", new_transform_with_rotation ) )
{
 // draw circle
}
