### ISSUE TITLE
VR in-headset view warps exponentially based on distance to zero on the VR anchor

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4280]
### Describe the bug

VR in-headset view warps exponentially based on distance to zero on the VR anchor.
This is specifically on my Valve Index.
I also tried it on the Vive XR Elite and got part of the same issues, rotating the anchor rotates the visuals to the side of my view (which also happens on Index), but the positional warping doesn't happen.

### To Reproduce

This one is a little tricky because the effect only happens in-headset, the VR mirror views all look correct but in the actual headset the view warps like crazy, so I can't record the effect to show you what I'm seeing.

### Expected behavior

no warping on the VR view based on distance to world zero

**Comment by xezno** [comment]
Should be fixed on next build
