### ISSUE TITLE
Can't create custom Component Widgets in Libraries (Can't access Editor namespace)

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4282]
### Describe the bug

You cannot access the `Editor` namespace in Libraries. This means you cannot make custom widgets for your library's components in the inspector (which may be necessary for something like a terrain component in a terrain library)

### To Reproduce

Try to use the `Editor` namespace in order to use `ComponentEditorWidget`, `Widget`, `ControlWidget`, `[CustomEditor(typeof(whatever))]`, ect. and you will not be able to. Even if it is placed in an "Editor" folder or a "code/Editor" folder.

### Expected behavior

You should be able to access the classes and attributes necessary to create Custom Editors for your Components.

There's probably a good reason for why the `Editor` namespace is disallowed in libraries (that I can't think of) but there's a good case to allow some of the stuff.

**Comment by DevulTj** [comment]
this'll be related to https://github.com/Facepunch/sbox-issues/issues/4134 I believe

**Comment by badandbest** [comment]
Yes
