### ISSUE TITLE
Opening Content Mode solutions in Visual Studio

### ISSUE THREAD

**Issue by AlexChecker** [Facepunch/sbox-issues#4283]
### Describe the bug

Projects can be opened (and properly genereated) only when you open game project. If you open editor in content mode, projects won't generate solutions and projects that were created with solutions won't open in visual studio, throwing  "Object reference not set to an instance of an object" error

### To Reproduce

1. Start s&box in editor mode
2. Select "Content mode"
3. Create addon
4. Try to open addon in Visual Studio
5. Nothing will open.

### Expected behavior

Visual Studio should open with selected solution

### Additional context

I've tried to create addon, using instructions from [this](https://wiki.facepunch.com/sbox/Addons/GettingStarted) wiki page. Also, sometimes it tries to use WSL paths (/mnt/c/...), even when I fully disabled it

**Comment by garrynewman** [comment]
If you don't have a game, what would you expect to open in the solution? Where would you expect the solution to be?

**Comment by AlexChecker** [comment]
addon itself, I thought. On wiki page that it says to open in content mode, not the game project

**Comment by garrynewman** [comment]
We need to rethink content mode itself to work out what we're going to do here.
