### ISSUE TITLE
Model morphs don't seem to update correctly at all times

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4284]
### Describe the bug

Morphs dont seem to update properly at all times. I can get it to update after changing the model to another one (and that one has to have morphs, too), then changing back to my model (probably triggers some sort of update). The morph value does change but the model's appearance does not.

Use this code to test the morphs if needed:

```cs
public class MorphController : Component, Component.ExecuteInEditor
{
	[Property]
	public SkinnedModelRenderer Target {get; set;}

	[Property]
	public string MorphName {get; set;}

	[Property]
	public float MorphValue {get; set;}

	[Property, System.ComponentModel.ReadOnly(true)]
	public float CurrentMorphValue {get; set;}

	protected override void OnUpdate()
	{
		base.OnUpdate();

		if (Target.IsValid() && Target.SceneModel.IsValid()) {
			Target.SceneObject.Flags.IsOpaque = false;
			Target.SceneObject.Flags.IsDecal = true;

			Target.SceneModel.Morphs.Set(MorphName, MorphValue);
			CurrentMorphValue = Target.SceneModel.Morphs.Get(MorphName);
		}
	}
}
```

https://github.com/Facepunch/sbox-issues/assets/5991682/6c9a42bf-fa4a-4947-b674-86608ca7fd73

### To Reproduce

1. Create a GameObject with a SkinnedModelRenderer and Morph Controller
2. Select a model with morphs
3. Try changing the morph values

### Expected behavior

Morphs should update the model properly.

**Comment by garrynewman** [comment]
I don't know anything about how the morph system works and updates, so this might need a system to update it.

**Comment by Gmod4phun** [comment]
If I set the model to the model I want to use, then to citizen.vmdl, then back to the model I use, then the morphs seem to work correctly, but only until the model renderer component is disabled, then it fucks again and needs the whole model1->model2->model1 shenanigan. I have no clue why it happens tho.

**Comment by aylaylay** [comment]
Morphs are only applied when scene object update runs

**Comment by aylaylay** [comment]
They now get updated straight away

**Comment by Gmod4phun** [comment]
Yeah, the morphs work flawlessly now. Thank you very much
