### ISSUE TITLE
Scale breaks on children of children

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4287]
### Describe the bug

When I make one object a child of another child, the scale is set to a really low value on several axis

### To Reproduce

1. Create an empty gameobject
2. create a cube, scale it, and make it a child of the empty
3. create another identical cube and make it a child of the other cube

### Expected behavior

the scale should stay the same when parented

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/94070205/bbb575b7-93af-4a09-9362-29dfde661dd6

**Comment by DrakeFruit** [comment]
okay looks like the scale is just set relative to it's parent, because setting the scale to 1 1 1 returns it to the scale it was before. Maybe this is intentional but it feels wrong and I shouldn't have to manually set the scale back to 1 1 1 when I parent it.

**Comment by garrynewman** [comment]
I think I fixed this now
