### ISSUE TITLE
Multiple cameras don't work

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4289]
When creating multiple cameras using different rects on the screen, the views are stretched and wrong.

**Comment by handsomematt** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/1388267/61712df2-caa1-4725-95d9-950e6a458a28)

Multi cameras were okay, issue was the post processing in your scene - Valve's postprocessing worked fine, but our C# stuff was a little fucked.

The scene looks mostly fine now, but the shadow mapping does look ridiculous.

**Comment by garrynewman** [comment]
I would have never found that, good job
