### ISSUE TITLE
Accessing EnvironmentLight.Color causes a crash to desktop

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-issues#429]
**Steps to Reproduce**

1. Get the `light_environment` entity from the map and try to read or write the `Color` property.
2. Experience the crash to desktop.

**Expected Behavior**

It doesn't crash to desktop.

**Comment by aylaylay** [comment]
does this happen for any other property or just color

**Comment by robotboy655** [comment]
From what I gather it's any `Color` property that tries to access `lightComponent` on `EnvironmentLightEntity`

**Comment by kurozael** [comment]
@aylaylay I've tried setting `Brightness` which doesn't seem to crash.

**Comment by aylaylay** [comment]
Should be sorted now
