### ISSUE TITLE
Terrain Editor gives errors when rotating/scaling the Terrain GameObject

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4291]
### Describe the bug

If you create a new Terrain object and try to rotate/scale it you will see the console spit the following errors:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/70d7b4f1-dc6e-48b8-8c5b-7279363145d5)

### To Reproduce

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/7bc8d63a-739d-4383-ac11-65638cbd65a6)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/e0453ac5-6544-47e5-a0b3-36058a2c5b1e)
Change these values (or rotate/scale with the gizmo)

### Expected behavior

There should be no errors

**Comment by handsomematt** [comment]
#4209
