### ISSUE TITLE
All audio is 10-20x louder with the new Audio Changes

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4294]
### Describe the bug

All sounds are played at insane volumes by default. Seems as though everything is amplified by an amount it shouldn't be.

### To Reproduce

Try to play a sound and compare it to the volume it was before the audio changes (not easily replicate-able I know but it's very easy to tell the difference if you knew how it was beforehand)

### Expected behavior

Sounds should be played at a normal volume

**Comment by garrynewman** [comment]
My latest changes may have fixed this
