### ISSUE TITLE
Visual Misalignment of ModelPhysics after Instantiation

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4299]
### Describe the bug

Whenever a game object with a ModelPhysics component is instantiated and it's transformation is changed, the model will appear to be located at a different transformation, but still respect all collisions as if it was located at it's actual transformation.

### To Reproduce

1. Create a prefab with a SkinnedModelRenderer and ModelPhysics
2. Instantiate prefab and adjust it's transform in code

### Expected behavior

The ragdoll should visually respect the new transform.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/99102549/a264484b-f600-478d-976b-b9fc0fe9ec2c

The ragdoll's transform is located at the cube, however it visually appears far away yet still respects the collision of the plane under the cube.

**Comment by garrynewman** [comment]
Can you turn the physics debug view on and see if it actually moved?

**Comment by aylaylay** [comment]
Could you upload a small repro please, it isn't exactly clear to me what's happening in the video

**Comment by aylaylay** [comment]
Actually, this might be fixed now, can you test for me please?

**Comment by ScoutWozniak** [comment]
The position of the model seems to update, but now the bones appear to have the incorrect rotation.  I'm able to still create that repro if need be.
![Screenshot 2023-12-26 095330](https://github.com/Facepunch/sbox-issues/assets/99102549/711a6fe5-aa24-472b-8394-9fe35d15eb55)

**Comment by aylaylay** [comment]
Should be good now

**Comment by ScoutWozniak** [comment]
Works perfectly now, thanks!
