### ISSUE TITLE
Hammer excludes first five characters from "map" console command used to run the map after build if the map is outside `myaddon\maps`

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#43]
**Describe the bug**
When building a map, no matter whether it is a directory or filename, the first five letters are truncated. For example, when the .vmap file is in `sbox\addons\addon\mapname.vmap`, the command Hammer uses becomes `map me`. When nested in directories, like for example `sbox\addons\addon\source\map\mapname.vmap`, the command becomes `map e\map\mapname`

**To Reproduce**

1. Create an addon folder in `addons` (# of characters in this folder doesn't matter)
2. Open Hammer
3. Create a new .vmap
4. Save the .vmap in the addon folder
5. Open the build window. The `Console Commands` section should show the incorrectly formatted command. Upon building, the game will say it can't find the map, due to the omitted characters.

**Expected behavior**
Hammer should be doing `map mapname` if the .vmap is not stored in any directories, and `map source\map\mapname` if it is (Using the previous file structure example)

**Comment by garrynewman** [comment]
Is the map name wrong here?

![image](https://user-images.githubusercontent.com/928843/116225319-9a69ac80-a749-11eb-9a2c-18f43b9f7d37.png)

I just tried it locally and it ran fine. Maybe your issue is that you're creating the map outside of a maps folder?

**Comment by walllable** [comment]
I don't think it's that, doing it in a maps folder (In my case, `addons\testmap_extended\source\maps\testmap1.vmap`) still results in this.
![image](https://user-images.githubusercontent.com/10066958/116226334-d6d4e280-a720-11eb-91c5-90479fe99c9c.png)

Unless you mean I should format the directory like `addons\testmap_extended\maps\testmap1.vmap`?

**Comment by walllable** [comment]
After trying out `addons\testmap_extended\source\maps\testmap1.vmap`, it seems that was indeed the problem. I still think it should let you know about that, instead of cutting off the first five characters.

**Comment by garrynewman** [comment]
Yeah `addons/myaddon/maps/blahblah.vmap` is what you should be doing - but I'll also make it not shit the bed if someone doesn't put it in a maps folder too.

**Comment by garrynewman** [comment]
Okay I pushed a fix for this, will only remove `maps/` in the command line if there's `maps/`

**Comment by walllable** [comment]
The update seems to have broken Hammer. These two errors pop up when launching from the asset browser window, and the game crashes shortly afterwards.
![sbox-dev_2021-04-27_06-53-42](https://user-images.githubusercontent.com/10066958/116230344-890ea900-a725-11eb-8a9b-fe05a3103566.png)
![sbox-dev_2021-04-27_06-53-56](https://user-images.githubusercontent.com/10066958/116230353-8a3fd600-a725-11eb-89c3-469650fb55db.png)

I'm validating the game's files in Steam as a sanity check, but I figured I should let you know instead of waiting for that to finish.

**Comment by walllable** [comment]
Hammer seems to be fixed now
