### ISSUE TITLE
[Shadergraph] Not all applicable nodes are available to create when dragging out a new connection

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#4300]
## Describe the bug

In shadergraph when you go ahead and drag out a connection to create a new node the list you get to create a node is heavily reduced . For example when i drag out the **_xy_** output of a _**Float 2 Node**_ under binary only option i get is lerp which is pretty much the same for all node outputs.

## To Reproduce

1. Open Shadergraph.
2. Place down any node , The _**Float 2 Node**_ for example.
3. Drag out a connection from the Output/Result of the node. 
4. Notice that the amount of applicable nodes to create is not what you'd expect by just right clicking on an empty spot in the graph.

## Expected behavior

When dragging out a connection from the Output/Result of the node all avalible outputs for that vector type should be made available in the list.

### Issue Example
![Screenshot 2023-12-23 105458](https://github.com/Facepunch/sbox-issues/assets/23345567/638551bd-65df-4b58-bb18-0aafb0bb4f6c)

## Additional context

I suspect this popped up back with one of the ActionGraph related commits?

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by QuackCola** [comment]
Lovely its working as intended now. Thanks laylad

**Comment by QuackCola** [comment]
This seems to be fucked again 
![Screenshot 2024-07-21 191425](https://github.com/user-attachments/assets/b8b4e5bd-9965-42d5-9061-94092819fc52)

**Comment by aylaylay** [comment]
Fixed
