### ISSUE TITLE
Relative path conflict when consecutively adding two projects containing same-named file

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4301]
### Describe the bug

On the Welcome window, adding two projects with a file with the same relative path cause errors to be logged infinitely:
```
2023/12/23 09:40:10.7640	[engine/ResourceCompilerSystem] Error during compile: Invalid full path 'c:/users/chris/documents/s&box projects/type_bleed_repro_a/scenes/minimal.scene' registered during compile - the relative path 'scenes\minimal.scene' resolves to a different file: 'C:/Users/Chris/Documents/s&box projects/type_bleed_repro_b/scenes/minimal.scene'	
2023/12/23 09:40:10.7640	[engine/AssetSystem] ERROR recompiling: 'scenes/minimal.scene'	
```

### To Reproduce

1. Open the S&box editor Welcome screen
2. Import both of the projects in the attached ZIP file, one after the other.
3. Observe that the Welcome screen is hanging and the most recent log is filling up

### Expected behavior

Multiple different projects can coexist with the same relative path names. Pretty much all of my projects have a scenes/main.scene file.

### Media/Files

[type_bleed_repro.zip](https://github.com/Facepunch/sbox-issues/files/13759670/type_bleed_repro.zip)

**Comment by garrynewman** [comment]
This might be quite tricky for us to fix. The asset system doesn't really support removing or swapping assets. I guess we should make it support it though.

I wouldn't be totally surprised if we end up rewriting the asset system to be managed in c#.

**Comment by handsomematt** [comment]
These projects shouldn't be mounted at the same time anymore as you can only open and mount 1
