### ISSUE TITLE
strange issue with rotating a gameObject using angles greater than 90 degrees

### ISSUE THREAD

**Issue by dictateurfou** [Facepunch/sbox-issues#4305]
### Describe the bug

I don't know how to better explain the problem, I made a short video, the bug happens around 30 seconds when I pass the values ​​above 90 degrees.
I use the following code

```csharp
public class BikeShowRotBug : Component
{
	protected override void OnFixedUpdate()
	{
		var angleRot = GameObject.Transform.Rotation.Angles().WithPitch( 180f);
		GameObject.Transform.Rotation = angleRot.ToRotation();
		
	}
}

```

https://github.com/Facepunch/sbox-issues/assets/12927420/be989cf8-341e-4b67-bdb8-aeaf91f6a4eb

We can see on the video that when we pass 90 degrees the roll and the yaw we tend to go to -180 or 180 it depends.
With another version which works in the additional context I also have this bug of the yaw and the roll which goes to -180 while the pitch remains stuck between 90 and -90 which creates a kind of flick during the transition

### To Reproduce

just add this component
public class BikeShowRotBug : Component
{
	public Angles BaseAngles;
	protected override void OnFixedUpdate()
	{
		var angleRot = GameObject.Transform.Rotation.Angles().WithPitch( 180f);
		GameObject.Transform.Rotation = angleRot.ToRotation();
	}
}

### Expected behavior

don't know what to answer

### Additional context

with this code the bug disappears but it requires creating an angle property to use that of the gameObject. But it still has a little flickering effect because the roll and the yaw go to -180 or 180

```csharp
public class BikeShowRotBug : Component
{
	public Angles BaseAngles;
	protected override void OnFixedUpdate()
	{
	
		//WORK
		BaseAngles.pitch += 5f;
		GameObject.Transform.Rotation = BaseAngles.ToRotation();
		

		
		
	}
}
```

**Comment by garrynewman** [comment]
Is this gimbal lock?

**Comment by dictateurfou** [comment]
I don't know, the only thing I can say is that the rotation is blocked with 90° when you want to modify the angle of the gameObject by retrieving it with GameObject.Transform.Rotation.Angles();

but creating an empty angles variable and modifying it from here solves the problem but suddenly we can no longer modify the rotation of the object without modifying this variable.

The little piece of code above is the only one that controls the gameObject, that's why I called the strange issue because I don't understand why one works but not the other

**Comment by garrynewman** [comment]
Generally you want to create a Rotation and then apply that to the rotation, instead of converting to Angles and then back to Rotation. That way you won't lose accuracy.

For example:

```
Rotation delta = new Angles( 5, 0, 0 );
Transform.Rotation *= delta;
```
