### ISSUE TITLE
Auto genereated FGD will add entity names that already exist in another fgd/internally, causing parsing to fail

### ISSUE THREAD

**Issue by rob5300** [Facepunch/sbox-issues#431]
The automatically generated FGD for an add-on will include all entities marked with the Library attribute, however if an add-on implements an entity that exists already in Source 2, such as `func_movelinear` or `point_teleport`, it will also add this to the file. This will cause parsing of the fgd to fail when it reaches this entry, due to a "duplicate entry".

**To Reproduce**

1. Use pre existing entity name such as `func_movelinear` in a Library attribute
2. Let FGD generate
3. Load hammer, see that entities listed after this do not have working definitions, and act as there are no definitions for them.

**Expected behavior**

Pre existing entities would be skipped, or parsing would continue and ignore duplicate entity definitions.

**Additional context**

This may be a unique issue for the current state of the game, as many entities do not operate, its more common now for developers to re implement them in their add-on. Its desirable to use existing entity names for re implemented versions due to certain enhancements that some entities get in hammer.

**Comment by robotboy655** [comment]
This is technically not a bug. The plan is to eventually have all the entities in c# under different names, removing the old stuff from the base fgd.
