### ISSUE TITLE
Clicking on errors repeatedly opens new instances of IDE when using Visual Studio Code

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4310]
### Describe the bug

Using VSCode as my IDE, clicking on an error opens up the IDE, clicking on another error opens up another instance of VSCode instead of using the already running instance. Sometimes it stalls the game before opening the second instance, which only opens when I close the first VSCode instance and the game then recovers. I think the only time it does not stall is if I opened the first instance of VSCode using the 'Open Solution' shortcut.

I am not sure if this has been a problem for some time or its new, as I only just switched to VSCode and I am on a different machine than usual. Also this did not happen when using Visual Studio.

### To Reproduce

1. Set VSCode as your s&box IDE
2. Have errors
3. Click on one
4. Then click on another

### Expected behavior

Should not open more than 1 instance of the IDE

**Comment by dch-GH** [comment]
Also happens to me when using VS 2022, for what its worth.

**Comment by DevulTj** [comment]
I've made a change that should address your problem - let me know if this fixes it for you!

**Comment by Gmod4phun** [comment]
Seems good now, thanks
