### ISSUE TITLE
Camera.Main's properties are default when both Game and Scene view are open.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4313]
### Describe the bug

When you have both Game view and Scene view open at the same time, such as a split in docked, or one as a floating window on another monitor, Camera.Main's properties are defaulted and unusable.

```cs
protected override void OnUpdate()
{
     Log.Info( Camera.Main ); // logs correctly, and the properties in the Inspector are actually correct. (Position, Rotation, etc).
     Log.Info( Camera.Main.Position ); // logs 0,0,0
     Log.Info( Camera.Main.Rotation ); // logs 0,0,0,1
}
```

### To Reproduce

Have both Game and Scene view open, try to use Camera.Main for game code.

### Expected behavior

Camera.Main should refer to the Game view camera if both views are visible.

**Comment by garrynewman** [comment]
I don't love Camera.Main - we should probably try to eradicate it in favour of referencing the "main" cameracomponent somehow.

**Comment by dch-GH** [comment]
> I don't love Camera.Main - we should probably try to eradicate it in favour of referencing the "main" cameracomponent somehow.

Yeah, understandable. That is actually what I ended up doing as a workaround in my code. In my case I just needed the camera's position and rotation, and got those from the CameraComponent's gameobject itself.
