### ISSUE TITLE
Grid snap doesn't work with dragging assets into scene

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4316]
### Describe the bug

Grid snap doesn't work with dragging assets (e.g models, prefabs) into scene.

### To Reproduce

1. Enable grid snap.
2. Drag an asset (e.g model) into the scene.
3. The GameObject doesn't snap to the grid when placing.

### Expected behavior

Dragging an asset into the scene should use grid snap, as well as toggle while holding ctrl.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/91832803/66cb95b2-7835-401b-a8fd-3fc504bbc28d

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/e2519f5e-a97f-41a6-b528-1c91b7e90fba

**Comment by badandbest** [comment]
That looks awesome
