### ISSUE TITLE
Scene Editor: Fullbright doesn't work

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4317]
### For?

S&Box

### What can't you do?

Currently the only way we can enable full bright in a scene is by typing in the command in the console or using selecting it in the game view.  These methods work, but we cannot change it from the editor itself.

### How would you like it to work?

Add a button in the toolbar to toggle Fulbright on and off.

### What have you tried?

Typing "mat_fullbright 1" in the console works in the editor, same with using the View Debug button in the game view, but it would be better to have it integrated into the editor.

### Additional context

The editor currently has a button to disable lighting but it feels like it has no proper use due to it just drenching the environment in black.  Switching it to use Fulbright would make this a lot more useful.

**Comment by garrynewman** [comment]
This is what the sun icon at the top is meant to do, are you saying it's stopped working?

**Comment by ScoutWozniak** [comment]
> This is what the sun icon at the top is meant to do, are you saying it's stopped working?

Yeah it just makes the scene completely dark now.  I wasn’t too sure if that was supposed to happen but it makes sense now.

**Comment by NotGaylien** [comment]
tbf i would argue 
This scene view should have the tool vis modes 
![sbox-dev_YrjSZ9BWPs](https://github.com/Facepunch/sbox-issues/assets/82092361/690127fc-117a-492c-bc7c-91e2bb089cd4)

the game window has them at the bottom right, they are more useful for dev stuff.
![sbox-dev_u0DUVuSYb0](https://github.com/Facepunch/sbox-issues/assets/82092361/10c8eefd-dc0e-4f17-9b00-ef78e053c05d)

**Comment by yuberee** [comment]
Oh I swear it never worked for me, it's always been black. Never noticed the sun icon on the top

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/afb7b480-f685-4ad4-b6e6-9f16c73b8e56)

**Comment by badandbest** [comment]
Never worked for me.

**Comment by garrynewman** [comment]
This works now
