### ISSUE TITLE
Time.Now returns RealTime.Now after using await in the same function

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4319]
### Describe the bug

It seems that `Time.Now` does not always return the correct value. It seems to always return the wrong values in certain places and work fine in other places (as in it doesn't magically start giving bad values where it gave good ones and vice versa). 

I noticed this when using a 'Timed Task' system for scheduling actions. I use this across many components and in one of them it just does not work right. In this example, I add a new task to a list with `Time.Now` as the time of execution for the task. Then I process the tasks, and debug print the current time using `Time.Now` and the Task's execution time.

As can be seen from the image, when creating the new task, Time.Now in that context returns a bad value. Immediately on the next tick, the debug prints the correct Time.Now.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/c67761a6-f457-4df2-b44d-9d2064292363)

The next image shows the same thing, but taken about 9 minutes (536 seconds) later, and surprise surprise, the Time.Now seems to be offset by that exact much. And that is in a newly run Scene.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/f8ba7ac3-2242-4399-a521-136d282e1577)

So it seems like that sometimes Time.Now doesn't use the time since starting the scene, but just keeps counting up. I can't reproduce it as it seems to happen in random places.

Could be related to issue #4276 

### To Reproduce

1. Try to call `Time.Now` in various places
2. Check and compare if the values make sense or not

### Expected behavior

Values returned by `Time.Now` should be in sync, irrelevant of where in code where they are called.

**Comment by Gmod4phun** [comment]
After trying to find the reason why this happens, it seems that using an `await` is the thing which causes the issue.

A function like this
```cs
public async void Test()
{
	Log.Info( Time.Now );
	Log.Info( RealTime.Now );
}
```
produces the following output:

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/0e5bfcb4-d802-4e0c-9881-412fcae27766)

Same function, with an await call
```cs
public async void Test()
{
	await GameTask.DelayRealtime( 1 );

	Log.Info( Time.Now );
	Log.Info( RealTime.Now );
}
```
produces this:

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/3457ff68-a16c-4f75-8e99-bc4031ddd4fc)

**Comment by garrynewman** [comment]
This one should be fixed now, please take a look and close if fixed

**Comment by Gmod4phun** [comment]
Yep, its fixed. Thank you very much
