### ISSUE TITLE
PhysicsBody.GravityVector

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/sbox-issues#432]
Outerspace demands control over gravity, but it seems we only get 'GravityScale'. 'GravityVector' would be better.

**Comment by aylaylay** [comment]
I want to check if you need per object gravity vec and not a global gravity vec, cos you can already do the latter

**Comment by thegrb93** [comment]
Yeah per obj

**Comment by aylaylay** [comment]
I understand why you want it and it's not a hard thing to add, it's just not a change I'm willing to make to rubikon currently unless there's a huge demand for it.

**Comment by aylaylay** [comment]
Currently you can disable gravity and apply your own gravity force in physics post step, see how you get on doing it that way first

**Comment by thegrb93** [comment]
> 
> 
> Currently you can disable gravity and apply your own gravity force in physics post step, see how you get on doing it that way first

Won't that be extremely slow if every entity in the game is running a physics simulate hook?

**Comment by thegrb93** [comment]
If source 2 physics is lacking that feature then I understand, but it seems like a crumby work-around

**Comment by aylaylay** [comment]
it shouldn't be that bad and if it is, then that would be a good reason to have it implemented natively, I'm just not going to do it just yet until it's proven that it's a real need.

**Comment by aylaylay** [comment]
I know that may be a frustrating answer but we'll have a better game if we implement things based on proven needs rather than things that could be cool.

**Comment by thegrb93** [comment]
ok, I'll try 100 entities without a physics hook, then again with physics hook and let you know how much it costs.

**Comment by thegrb93** [comment]
Will come back to this if I run into it again
