### ISSUE TITLE
Multiple cameras break dynamic reflections

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4321]
Try the multicamera scene in testbed. Disable cameras, move camera viewports around..

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/d737c924-1357-4c99-91d3-8d66093b2c97)

**Comment by handsomematt** [comment]
Is this fixed now @samzanemesis ?

**Comment by samzanemesis** [comment]
Ya
