### ISSUE TITLE
Add a coroutine system

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#4325]
### For?

S&Box

### What can't you do?

There is no built-in method to run staggered code on the main thread during the game loop.

### How would you like it to work?

TL;DR: Unity-like coroutines, Look at the proposed API at the bottom.

It would be great to have it work like [Unity's coroutine system](https://docs.unity3d.com/Manual/Coroutines.html). I have already made my own library that is used by the community but a built-in solution would fit better. In explaining the API request I will reference my library.

## Basic example
```cs
using Coroutines;
// Optional: You can alias the type so that it is more readable.
using CoroutineEnumerator = System.Collections.Generic.IEnumerator<Coroutines.ICoroutineStaller>

CoroutineEnumerator DoBehavior()
{
    Log.Info( "Hello!" );
    yield return new WaitForSeconds( 10 );
    Log.Info( "I waited 10 seconds" );
}

// Two options to start:
// Option A (Pass method to Start):
Coroutine.Start( DoBehavior );
// Option B (Invoke coroutine then pass off enumerator to Start):
var coroutine = DoBehavior()
Coroutine.Start( coroutine );
```

## Coroutine stalling
Coroutines work by stalling the enumerator till a condition is met. These stallers allow you to delay logic in your game loop. This could be till the next frame, a few seconds, till another coroutine is complete, etc. This section of the API should be left open to developers so they can make specialized use of it when needed. Within my library, I do this with a [ICoroutineStaller](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/ICoroutineStaller.cs) interface.

In my library, I provide the following built-in stallers that would be good to have in the built-in system:
[WaitForNextFrame](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitForNextFrame.cs) - Pauses a coroutine until the next frame.
[WaitForFrames](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitForFrames.cs) - Pauses a coroutine for a specified amount of frames.
[WaitForSeconds](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitForSeconds.cs) - Pauses a coroutine until a specified amount of seconds have passed (Affected by time scale.)
[WaitForRealSeconds](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitForRealSeconds.cs) - Pauses a coroutine until a specified amount of seconds have passed (Not affected by time scale.)
[WaitForNextStage](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitForNextStage.cs) - Pauses a coroutine until the next execution of a [GameObjectSystem.Stage](https://asset.party/api/Sandbox.GameObjectSystem.Stage).
[WaitForCoroutine](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitForCoroutine.cs) - Pauses a coroutine until another coroutine is finished (regardless of success or failure.)
[WaitForTask](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitForTask.cs) - Pauses a coroutine until an asynchronous task is completed.
[WaitUntil](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/Stallers/WaitUntil.cs) - Pauses a coroutine until a method returns true.

## Coroutine buckets
Grouping coroutines into a bucket of sorts would be very useful. For example when you have a bunch of coroutines owned by a game object; If that game object is destroyed, all of the coroutines it had running need to be destroyed alongside it. Within my library, I expose a type simply named [CoroutineBucket](https://github.com/peter-r-g/Sbox-Coroutines/blob/master/CoroutineBucket.cs) which mimics all of the functionality of the regular coroutine calls so it can be used transparently. If the plan is to make coroutines built into game objects you can just abstract the bucket away and put methods directly into the `GameObject` implementation.

## Proposed API
```cs
/*
    Pseudo-code.
*/

// Optional, could just have coroutines all run through buckets in GameObjects and components.
static class Coroutine
{
    // Pass already started coroutine.
    public static void Start( CoroutineEnumerator coroutine );
    // Pass coroutine method, get back the created enumerator
    public static CoroutineEnumerator Start( Func coroutineMethod );
    // Pass coroutine method and its parameters, get back the created enumerator
    public static CoroutineEnumerator Start( Func<T1, T2, ...> coroutineMethod, T1 firstParam, T2 secondParam, ... );
    // Stops an existing coroutine.
    public static void Stop( CoroutineEnumerator coroutine );
    // Stops all coroutines currently running.
    public static void StopAll();
    // Returns whether or not said enumerator has finished.
    public static bool IsComplete( CoroutineEnumerator coroutine );
}

class CoroutineBucket
{
    // Same API as Coroutine.
}

class GameObject
{
    // Same API as Coroutine, invoked through an internal CoroutineBucket.
}

class Component
{
    // Same API as Coroutine, invoked through the GameObjects internal CoroutineBucket.
}

interface ICoroutineStaller
{
    // Returns whether or not this stallers condition has been met and that the coroutine can continue.
    bool IsComplete { get; }
    // Returns at what stage Update should be called and for the execution of the coroutine to continue.
    // There is probably a better way to go about this, my use case was to enable WaitForNextStage and for
    // generic stalls to execute at the end of a frame (Stage.UpdateBones.)
    GameObjectSystem.Stage PollingStage { get; }

    // Updates the state of the staller.
    void Update();
}

// Would be nice to have a simple return type like CoroutineEnumerator
// but last I checked C# shits the bed if it isn't just an explicit IEnumerator<ICoroutineStaller>.
// Because of that, I suggest people do something like the following:
global using CoroutineEnumerator = System.Collections.Generic.IEnumerator<Coroutines.ICoroutineStaller>
// Perhaps the using statement could be inserted through the code generator?
CoroutineEnumerator MyCoroutine()
{
    // Stallers should follow a "WaitFor*" naming scheme. Things like "WaitUntil" would be an exception.
    // Please do not copy Unity's "yield return null" for the next frame.
    yield return new WaitForNextFrame();
}

// Built-in stallers
WaitForNextFrame // Pauses a coroutine until the next frame.
WaitForFrames // Pauses a coroutine for a specified amount of frames.
WaitForSeconds // Pauses a coroutine until a specified amount of seconds have passed (Affected by time scale.)
WaitForRealSeconds // Pauses a coroutine until a specified amount of seconds have passed (Not affected by time scale.)
WaitForNextStage // Pauses a coroutine until the next execution of a GameObjectSystem.Stage.
WaitForCoroutine // Pauses a coroutine until another coroutine is finished (regardless of success or failure.)
WaitForTask // Pauses a coroutine until an asynchronous task is completed.
WaitUntil // Pauses a coroutine until a method returns true.
```

### What have you tried?

I have made a library that some members of the community already make use of. Its identifier is `gooman.coroutines` and its related sites can be found on [asset.party](https://asset.party/gooman/coroutines) and [GitHub](https://github.com/peter-r-g/Sbox-Coroutines).

**Comment by ShadowBrian** [comment]
I've been using his library for a long time now and built the entirety of my AI House Generator on it, would be amazing if it was made a native feature.

**Comment by anthonysharpy** [comment]
> There is no built-in method to run staggered code on the main thread during the game loop.

Could you do this with async?

```
private PointLight _testLight;

protected override void OnStart()
{
	_testLight = GameObject.Components.Create<PointLight>();
	FlickTheLightAsync(); // Non-blocking.
}

private async void FlickTheLightAsync()
{
	for (int i = 0; i < 1000; i++)
	{
		await Task.MainThread();
		_testLight.Enabled = !_testLight.Enabled;
		await Task.Delay( 100 );
	}
}
```

Although I can see how something like Task.WaitForFrames might be useful.

**Comment by garrynewman** [comment]
Why aren't async functions this?

**Comment by ShadowBrian** [comment]
I think they're both really close but async has a tendency to go off-thread and act weird when used incorrectly?
And coroutines can't really be used incorrectly, so it's like an idiot proof async.
But I'd rather not be the one to explain coroutines vs async because I know fuck-all about async beyond having been told my use of them was causing weird behavior on a project in the past...

**Comment by Metapyziks** [comment]
My feeling is that async / await is exactly the language-level way to do coroutines.

I can understand that if you're coming from Unity it would be easiest if our API worked exactly the same way, but then we'd be forced to make the same concessions they have, and do the same ugly hacks.

If async / await is jumping between contexts in unexpected ways then it's on us to document that better / fix it.

**Comment by garrynewman** [comment]
Have to agree with @Metapyziks. Our async system is single threaded, it runs in the scene's context (so time etc should be right), and Components have a Task object, which automatically cancels when the object is destroyed.

Coroutines have positives over async, but they have a lot more negatives imo. Once you start to use async and see how integrated into the language it is, how you can return values, use try/catch, coroutines start to look a lot less appealing.

**Comment by ShadowBrian** [comment]
Yeah so coroutines are easier to work with but async is more powerful, after reading up on it.
Unity does allow for either one and generally recommends coroutines because there's a lot less manual error handling required, which is probably why I like it more than async, but I guess it'll stay a library if you guys don't see a point in having both natively.

**Comment by garrynewman** [comment]
We're using async correctly, we're just forcing it to run on one thread instead of any thread.

What do you find difficult about async vs coroutines that makes it less appealing?

**Comment by ShadowBrian** [comment]
If they do indeed have the same feature set (with async just having more) the syntax just feels nicer on coroutines I guess?
More deliberate on a way, but part of that might be my 10 years of unity usage so I'm not sure I'm the best person to give rational reasoning for it here, kind of biased through habit..
