### ISSUE TITLE
Models And Textures From Map Instances Aren't Sent To A (Non-Host) Joining Client

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4329]
### Describe the bug

Maybe similar to #4230 and #4231

When a player (who isn't the host) joins a game with a map instance, most of the textures and models from the map are missing

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/128ac91e-ac12-4ceb-8a9d-a8f0b096025c)
![image](https://github.com/Facepunch/sbox-issues/assets/55365296/7c5a762f-2148-4d97-a4ad-c7abdea52a78)
![image](https://github.com/Facepunch/sbox-issues/assets/55365296/a630392b-c1cc-4125-a5d7-465bdd750e1f)
![image](https://github.com/Facepunch/sbox-issues/assets/55365296/18e1cc14-1278-40b7-aa33-239015c50c06)

### To Reproduce

See above

### Expected behavior

Works

### Additional context

This happened when I was joining via the create new instance button

On joining, client is spammed with stuff like

```
Error loading resource file "models/props/pizza/pizza.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "models/sbox_props/lamp_post/lamp_post_opaque.vmat_c" (Error: E
Error loading resource file "materials/generic/floor_tile_basalt.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "models/sbox_props/street_lamp/street_lamp_opacity.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/stone/brick/wall_stone_brick_a1.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/chainlink.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/generic/wall_panel_b.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "models/sbox_props/wall_letter_box/wall_letter_box.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/models/city_props/cafe/cafe_furniture.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/models/props/mattress.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/generic/concrete_simple.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "models/caged_lights02/caged_light02_glass.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "models/sbox_props/iron_fence/iron_fence.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "metal_shelf.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
```

**Comment by garrynewman** [comment]
This is an odd one, how are they getting the map?

**Comment by anthonysharpy** [comment]
Magic

ATM just using a networked map instance component. Tried turning the networking of it off to see if that made a difference but it's the same thing either way

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/ca96a59f-238b-4a17-a05b-363e57f5d248)

**Comment by garrynewman** [comment]
So the local client does have access to that map somehow, or it wouldn't be loading the geometry I guess? Where are all the missing textures hosted? Are they in an addon or in the game or something?

**Comment by anthonysharpy** [comment]
> So the local client does have access to that map somehow, or it wouldn't be loading the geometry I guess

Yeah it always seems to get the latest geometry so it must be getting it somehow

> Where are all the missing textures hosted? Are they in an addon or in the game or something?

The textures that are included with the gamemode seem to work fine

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/1d6e3804-db31-45f9-a06f-a7bddab1198c)

Most of the textures are from asset.party and none of those seem to work

Most of the models are from asset.party too. Some of those have missing models, some of them just have missing textures but not models

**Comment by anthonysharpy** [comment]
Could use the map from #4233 to test possibly

**Comment by garrynewman** [comment]
Yeah that's pretty interesting. I suspect it'll clean itself up once we have file network tables..

**Comment by anthonysharpy** [comment]
Think this was fixed ages ago
