### ISSUE TITLE
Editor color should change slightly while the current scene is Playing

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4333]
I keep editing objects in the scene without realizing it's playing, then losing all those changes.

Unity slightly dims the editor when playing. Could stand to be a bit more obvious imo. Maybe there could be a "Editor Play Mode Tint" setting.

**Comment by garrynewman** [comment]
We could do something basic, like this

![image](https://github.com/Facepunch/sbox-issues/assets/928843/e0f1ee71-bd3f-42d2-a442-d0228ddce1df)

![image](https://github.com/Facepunch/sbox-issues/assets/928843/fd8a83ca-263a-4702-b9dc-928f6e47d0b3)

but tinting all of the controls might be a bit more involved..

**Comment by cr4yz** [comment]
I did the simplest thing I could think of for this, lemme know if that'll do


https://github.com/Facepunch/sbox-issues/assets/9637557/6f393d1d-23e3-473b-b3d5-10c37fdc2aed

**Comment by andy013** [comment]
A bit too subtle in my opinion. It's hard to notice much difference on my monitor.

**Comment by anthonysharpy** [comment]
Maybe the whole header background colour could change to blue or something

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/a065beb3-aee7-4bba-8fef-1ec5497852cd)

**Comment by andy013** [comment]
I think it would make more sense to have a red border around the scene when the game is active. Similar to the border in hammer that tells you when the main viewport is the active selection.

![image](https://github.com/Facepunch/sbox-issues/assets/10728824/9f913f2e-aa44-489e-8fbc-866f1f12bfa4)

**Comment by Retroeer** [comment]
I actually agree with the red border idea, the black really just looks awful with the editor's color scheme
