### ISSUE TITLE
RangedFloat not implemented in components properties

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4334]
### Describe the bug

RangedFloat is pretty useful, without it I have to use two separate floats or a Vector2 for the same function. It was implemented in the old system.

### To Reproduce

Create a RangedFloat property and inspect it in the editor.

### Expected behavior

To display like it used to and be editable

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/554163df-8738-4e9a-bcb0-917d47264234)

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/42245235-db5f-42e7-ac25-0068c7f2652e)

**Comment by yuberee** [comment]
This has been implemented, but while I'm at it I'll post here that it's not a slider anymore. Not sure if intentional because other uses like in a SoundEvent it doesn't make sense not to.

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/0ba565e0-9347-4fcf-95d7-4227ad1d2db8)

**Comment by garrynewman** [comment]
I think this is done now right?
