### ISSUE TITLE
add OnTriggerStay to ITriggerListener

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4335]
sbox has Start/Update/Stop for collisions, but only Enter/Exit for triggers. 
Unity has OnTriggerStay 🧐

**Comment by garrynewman** [comment]
Why?

**Comment by ryleigh** [comment]
- I've got a Unit and a Door (Door has a trigger hitbox and an IsOpen bool)
- When a Unit touches a Door that has IsOpen=true, Unit travels through Door
The problem: if a Unit touches a non-open Door, which is then opened, the Unit won't travel through the Door like I want (until it leaves and re-enters the trigger)

First I tried keeping the Door boxcollider disabled until IsOpen=true, but it was still calling Unit's OnTriggerEnter even when disabled.

Now I have Door manage a list of touching Units via OnTriggerEnter/OnTriggerExit, and when IsOpen->true, it selects a touching Unit (if one exists) and they enter. But would be simpler to use OnTriggerStay to check.

And it would be more consistent with the Collision callbacks, and with Unity.

**Comment by garrynewman** [comment]
I still don't totally see the point of OnTriggerStay here. I would prefer to avoid these methods that call all the time for no real reason if possible.

Triggers/Colliders have a `Touching` list of other colliders that they're touching - would that be useful?

**Comment by ryleigh** [comment]
Oh nice, `Touching` makes my usecase a lot simpler. I don't care about OnTriggerStay anymore.
