### ISSUE TITLE
Maps incorrectly cull game objects

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4337]
### Describe the bug

Whenever a map is in a scene, it will stop models in one section from rendering except for their shadows.  The map does not have vis and all map geometry is still there, it's just any Game Objects added to the scene that are affected. 

### To Reproduce

Unsure what exactly will reproduce this as it seems random to each map, but making a map with a few hallways and loading it in a scene should show the bug.

### Expected behavior

The models should still be rendered normally when they are visible.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/99102549/ed205ca7-1a60-44c1-bacc-77e35e5fef20
This is the main example I'm running into now.

**Comment by handsomematt** [comment]
> The map does not have vis

Are you sure? Can you upload the map to make it easier to reproduce

**Comment by ScoutWozniak** [comment]
Map is on asset party under katewoz.e1m1 but the project itself is at https://github.com/ScoutWozniak/RetroFPS
Fairly certain the map doesn't have vis as I compiled without it and deleted the .los file and such.  I had other issues with vis on that stopped after that recompile.

**Comment by DoctorGurke** [comment]
Compiling without vis is different to actually disabling vis. Additionally the .los file only contains editor data, deleting it doesn't affect runtime vis at all.
If your baked visibility isn't disabled via map properties, you still have to have at least one version of vis compiled, which it will force on the first compile. 

Your issues stopping after a recompile sounds like you simply haven't been recompiling vis, which you should do at least whenever you meaningfully change vis contributing geometry (main world meshes)

**Comment by ScoutWozniak** [comment]
Yeah so I apologise, that was me being really stupid then.  Thanks for the heads up on that
