### ISSUE TITLE
SkinnedModelRenderer screws up bone hierarchy when changing model

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4338]
### Describe the bug

I am not 100% sure this is what is happening, but it seems plausible and would explain everything that is going on.

When using a SkinnedModelRenderer, setting a model with a skeleton and then selecting models without one (or with just one root bone) causes the models to not behave correctly, either following the previous model's bones or not rendering at all (which I suspect is due to the bones being positioned at the (0,0,0) position).

Here are a few examples:

In this first video, you can see the new model following the movements of the old model's skeleton. I am unsure why, as it does not seem to happen with all models.

https://github.com/Facepunch/sbox-issues/assets/5991682/6fa70256-944e-4f19-833c-5e5c4fa03065

The next video shows that after setting the model to the Citizen, then to a sphere, the sphere renders incorrectly.

https://github.com/Facepunch/sbox-issues/assets/5991682/306fb740-d4f8-418d-be2b-ca137527e990

The last video shows the thing I suspect is causing the model from not being rendered - as long as the map origin (0,0,0) can be seen, the model renders, but if not, the model stops rendering. I think the bones from the old model are stuck at that position for some reason.

https://github.com/Facepunch/sbox-issues/assets/5991682/2ff8552b-bf41-4b1e-a784-b86a28ba5ca6

### To Reproduce

1. Create a GameObject with a SkinnedModelRenderer
2. Set the model to the Citizen
3. Play the scene so the Citizen's animgraph kicks in and plays the idle animation
4. Set the model to another model and observe the weird behaviour

### Expected behavior

The models should render correctly, the old bone hierarchy from the previous model should be cleared.

**Comment by aylaylay** [comment]
Just pushed a fix for this, happy new year

**Comment by Gmod4phun** [comment]
I will check it tomorrow morning and let you know :) happy new year to you, too

**Comment by Gmod4phun** [comment]
Does not seem to be fixed sadly. The new model still keeps following the movement of a would be citizen's skeleton.

https://github.com/Facepunch/sbox-issues/assets/5991682/fcdc4897-b1ce-4e45-b9a6-c99acf59d533

Here's the model I'm using, might be easier to diagnose what's going on.

[iris_atlantis_for_layla.zip](https://github.com/Facepunch/sbox-issues/files/14623021/iris_atlantis_for_layla.zip)

**Comment by aylaylay** [comment]
Thanks for the model. Just to confirm, it's fixed though for the second video you sent? Changing citizen to sphere?

**Comment by Gmod4phun** [comment]
Yea that one seems fine

**Comment by aylaylay** [comment]
Pushed a fix

**Comment by Gmod4phun** [comment]
Will check as soon as it goes live. Also, seems to not happen if I remove the animation from the model, but if it has an animation, even if its just a static idle one, it does the wonky shit.

**Comment by Gmod4phun** [comment]
Seems to be fixed now :)
