### ISSUE TITLE
Maps in scenes require a restart of the editor to update

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4339]
### Describe the bug

When compiling a map, changes will not be reflected in a scene.  The only way to fix this is to restart the editor.

### To Reproduce

1. Compile a map
2. Run a scene (map hasn't changed)
3. Restart editor
4. Run the scene again (map has changed)

### Expected behavior

The map loaded in the scene should be the newly compiled version.

### Additional context

Haven't tested asset party maps but this is the case for local maps.

**Comment by badandbest** [comment]
Tested it with asset.party maps. You don't have to restart the whole editor. You only have to close and reopen the scene for it to update.

**Comment by handsomematt** [comment]
I thought @kurozael made this work already

**Comment by kurozael** [comment]
> I thought @kurozael made this work already

I fixed a bug where the map wouldn't copy over the compiled vpk if the scene map was in use, but don't "hotload" the map in the scene yet as wasn't sure about entities etc. But that doesn't really matter now so should be able to get it to just reload 👍

**Comment by kurozael** [comment]
Should be sorted now 👍
