### ISSUE TITLE
CSS mask Feature request

### ISSUE THREAD

**Issue by Aiko-Suzuki** [Facepunch/sbox-issues#434]
CSS mask

```css
mask-image: url("/materials/ui/sao_hud.png");
mask-mode: alpha;
mask-size: 100% 100%;
mask-repeat: no-repeat;
mask-position: center;
```
![image](https://user-images.githubusercontent.com/42787030/124361025-cfd3c000-dbfa-11eb-8f6e-fa074d84e59c.png)

**Comment by Gmod4phun** [comment]
Just encountered this problem, this would be really useful to have.
