### ISSUE TITLE
Editor loads maps when it shouldn't

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4341]
### Describe the bug

The editor seems to load a map into the scene when the scene is first opened or after pressing undo after having run a scene.  Disabling the component and then re-enabling it unloads the map.

### To Reproduce

Reproduction mentioned above, just make sure there is a map component present in the scene

### Expected behavior

The map should only be loaded at run time.

### Additional context

Currently the way maps are handled makes this a surprisingly useful feature to place game objects in the scene so they line up with the map.  This bug is annoying but if we could have a dedicated way to load and unload the map in the editor then that would be good as a temporary fix before proper hammer integration.

**Comment by kurozael** [comment]
To clarify - I think maps should always be shown in the scene view, but you want a way to hide them?

**Comment by ScoutWozniak** [comment]
Yeah, but this seemed to have been added after I made this issue so I'll go ahead and close this.

**Comment by MrBrax** [comment]
Disabling the map component seems to unload the map in the scene view but is still present in the game view.
