### ISSUE TITLE
Add the ability to offset the position/rotation/scale of ModelRenderer

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4344]
### For?

S&Box

### What can't you do?

I am unable to offset a rendered model if I want to adjust its position/rotation/scale without the need of creating additional GameObjects for each ModelRenderer.

### How would you like it to work?

I would like to have the option to offset the individual parts of the model's transform, like this:

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/3f076c55-2bb0-4405-ba2a-332c79ad8c36)

### What have you tried?

In the meantime I tried adding new GameObject for every new ModelRenderer component, which I don't really like as I have a feeling you don't want to have unnecessary GameObjects (unless it's not that big of a problem).

I also made a custom component, which works fine, but I would prefer this was implemented directly into the default ModelRenderer component.

**Comment by garrynewman** [comment]
Nope

**Comment by Gmod4phun** [comment]
Understandable, have a great day :)
