### ISSUE TITLE
Add support for white-space: pre

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#4345]
### For?

S&Box

### What can't you do?

Right now every supported `white-space` value collapses the whitespace, so it's not possible to do the following that can be done in browser just fine:
![image](https://github.com/Facepunch/sbox-issues/assets/19620198/9720369d-04f2-4790-9f47-ebfa1926b828)
![image](https://github.com/Facepunch/sbox-issues/assets/19620198/ae358a5e-8c90-4ed3-a57f-c1ca3c110e4f)

### How would you like it to work?

I would like to have `white-space: pre` supported the same way it works on browser.

### What have you tried?

I've tried using all the s&box supported settings for `white-space` which are `pre-line`, `normal` and `nowrap`. 
None of them work for what I want to do.

**Comment by xezno** [comment]
Added, should be up on next build
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/3b824bad-36e1-40f0-842f-7fe62506c161)

**Comment by ceitine** [comment]
Works as expected.
Thanks!
