### ISSUE TITLE
Scene Editor viewport camera resumes movement if it was not finished before moving cursor away from the window

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4346]
### Describe the bug

In the Scene Editor, when moving around with Right Click + WASD, the camera keeps moving even after letting go of the controls. It however stops moving if the mouse leaves the scene editor window. The issue is that it resumes moving once you hover the mouse over the window, which can be distracting, as it often happens that I return to the scene and it suddenly moves a bit (the camera finishing its movement).

https://github.com/Facepunch/sbox-issues/assets/5991682/2040d034-0ce0-421e-865d-f31a3d4dda7d

### To Reproduce

1. Have Scene Editor open
2. Move around the scene with Right Click + WASD
3. Before the camera stops moving, move cursor away from the viewport
4. Return cursor to the viewport and see that the camera updates only when hovered over the viewport.

### Expected behavior

The camera should either stop moving and stay where it last was even when hovering over the viewport again, or let it finish the movement in the first place.

**Comment by cr4yz** [comment]
I'm unable to repro, are you still having this issue?

https://github.com/Facepunch/sbox-issues/assets/9637557/ae6585fa-5fdf-4be0-a4d3-d6b278639f51

**Comment by Gmod4phun** [comment]
Looks like it no longer is an issue. Probably got fixed a while back I guess.
