### ISSUE TITLE
SceneTraceRay `IgnoreGameObjectHierarchy` doesn't ignore hitboxes

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4347]
### Describe the bug

I have some code that looks like this:
```CS
        var tr = Scene.Trace.Ray( Transform.World.PointToWorld( Center1 ), Transform.World.PointToWorld( Center2 ) )
            .WithoutTags( "nohit" )
            .UseHitboxes()
            .IgnoreGameObjectHierarchy( ignoreTarget )
            .Radius( Radius )
            .Run();
        
        Log.Info( ignoreTarget );
        Log.Info( $"HIT: {tr.GameObject}" );
```

this should make the players sword ignore their own body, but as you can see it still detects a hit on it:

https://github.com/Facepunch/sbox-issues/assets/7847372/b72ca529-7417-424f-a9e4-f0a4cc7eece3

### To Reproduce

1. Run a trace through some hitboxes set up on an ignored game object
2. See that it still detects the hitboxes on that object.

### Expected behavior

hitboxes should be ignored as well

**Comment by garrynewman** [comment]
Should work next build

**Comment by Fortune117** [comment]
Seems to still have the same issue on the latest build

**Comment by dch-GH** [comment]
Also just confirmed myself it still not working on latest build

**Comment by garrynewman** [comment]
Fixed - probably

**Comment by Fortune117** [comment]
Same problem still

**Comment by garrynewman** [comment]
God damn it, I'm actually gonna test it this time

**Comment by garrynewman** [comment]
![Image](https://github.com/Facepunch/sbox-issues/assets/928843/528880b6-edb2-47c9-bd92-956d481a1e26)

**Comment by garrynewman** [comment]
I just realised that's the wrong thing! BRB!
