### ISSUE TITLE
Add SceneTrace.IgnoreTriggers

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4350]
Often you'll want a trace to only hit solid colliders and ignore all trigger colliders, but there's no handy way to do it.

**Comment by Fortune117** [comment]
Wouldn't you just use `WithoutTag("trigger")`? or does that tag not get auto applied on triggers

**Comment by ryleigh** [comment]
There's no auto "trigger" tags, as far as I can tell

**Comment by garrynewman** [comment]
The implementation of this, by default traces shouldn't hit triggers. We should add .WithTriggers(), WithTriggersOnly().

**Comment by garrynewman** [comment]
Done
