### ISSUE TITLE
Content Mode needs a rethink

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4355]
We shouldn't let people launch without a game. At some point the menu system won't be visible in the editor and there'll be no way to load games other than the one you're running.

People creating maps, and models, need a way to create those without downloading the source of a game. They should probably be able to have a packaged game as their active game.. with the ability to use all the components and gameresource's within.

This brings up a bigger picture thing. If someone is launching in content mode - which is their project. If they're saving scenes, where are they saving them? 

Should we always have a "main" project? Like if someone is creating a map, their main project is that map. If someone is creating models, their main project is the one containing those models?

**Comment by CarsonKompon** [comment]
This is the workflow I picture when you say this:
1. Click "Content Mode" (or whatever it will become)
2. Select a project from asset.party to pull the components and gameresources from
3. You're making content for that project

This sounds super simple and streamlined, I like it a lot. Definitely worth thinking about having addons/libraries thrown in the mix as well though.

Someone may want to create a prefab that uses components from a certain addon or library (or may even want to create prefabs that can work across multiple games so those games all use certain interfacing components through a library). Not sure how that could be added to the mix but worth considering

**Comment by MrBrax** [comment]
Shouldn't content mode be for purely standalone models/materials/maps etc? You'd open it and no scene would open, only the "app" list.

**Comment by handsomematt** [comment]
You will always have a project now, this makes sense because you need a project to store your stuff anyway.
