### ISSUE TITLE
Map Selection / Loading

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4356]
Games need to be able to let users select and load a map. We should provide an easy, unified way for that to happen.

## Addon side

Addons should be able to get and set a global variable for the name of the map. This would either be a package or a local map.

Our map loader could have an option to use that variable instead of the provided map name. In editor runs it will always use the passed in variable name.

We should probably cater for other configuration data in the future, so this should probably be called "LaunchConfig", "LaunchParameters", "GameLaunch" or something, and have a kind of "bag" type ability to store any data we might need. 

It might be worth simplifying this to a startup launch parameters type thing, where everything is a string key and a string value, and gets parsed down from there by the game.

## Map Selection

Games could provide their own menu system to select the map, which would set this global variable.

We could provide a menu side popup when launching a game, to select the map. This will make it so experimental games don't have to bother with the bullshit of making a whole menu system just to prototype. Game Project Config will specify that when starting a new game, the user should select a map - and could define filters and defaults.

## Future

We should keep in mind about the distant future possibility of the traditional map format going away and maps being some other format (maybe scenes, maybe some compiled_scene or something). I think this system works the same with that, and we don't really have to worry.

**Comment by CarsonKompon** [comment]
To play devils advocate, what are the main reasons Map Loading/Selection should be baked into a game's configuration data instead of just being another Component that allows maps to be placed into a scene just like any other model/object? Not every game requires a map for their workflow (and like you say they will probably end up being replaced with scenes anyway) so imo would be weirder transition (especially if/when we end up getting a solution for multiple scenes loaded at once/a DontDestroyOnLoad scene)

**Comment by garrynewman** [comment]
I see it as working like this. You configure your game for the launch type, which would be multiple options like..

* Just start the game (StartupScene)
* Try to join any server, or start a game (Fast Start)
* Try to join a server, fail if none
* Etc Etc

These change how the menu launches your game.

If you're prototyping a quick game idea, it would make sense that you don't want to make a game menu, you just want it to launch into the game, in which case you'll enable the game launch configuration.. which will let you configure things like the active map, servername and the maxplayers. Maybe in the future, even saved games etc.

Whether you launch the built in game launch config or name your own in game is irrelevant, but the idea is to make it so you can sidestep all that bullshit if you want to. We'll probably have a control config option too..

Something to note on this stuff is that they're going to be modals that your game can launch. So if you do make a menu, you have the option of making all your own UI, or just having a button that opens the modal.

It makes a lot of sense for the menu to be able to tell a game that it wants to launch with a specific map. There are a lot of benefits to that.
