### ISSUE TITLE
Add CylinderCollider component

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4357]
### For?

S&Box

### What can't you do?

We have Box, Sphere, and Capsule colliders, but we're missing Cylinder.
As #421 suggests we do have the collisions implemented but I have never noticed myself, might be too old.

### What have you tried?

Some of the time we can use capsules instead of cylinders, but it doesn't cover all cases.

**Comment by garrynewman** [comment]
The cylinder is just a hull, but I don't totally see a reason why we can't add this.

**Comment by aylaylay** [comment]
I've added HullCollider which lets you choose a cylinder or cone

**Comment by yuberee** [comment]
Works great in game, other than a UI issue.
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/abde29ca-c540-4b4b-a4b8-f095e4596d0b)

The artists on the team are asking if the cone shape could also be added in modeldoc, should I made a different feature request?
![image](https://github.com/Facepunch/sbox-issues/assets/59583743/1b7b9ca0-6a40-4c25-a4f5-2f0e680a6ecc)

**Comment by aylaylay** [comment]
I don't get that UI bug

**Comment by aylaylay** [comment]
Also, I'm trying not to add shit to native tools currently so I probably wont add cone to modeldoc

**Comment by yuberee** [comment]
> I don't get that UI bug

It seems to be a different unrelated bug. #4803 
I'll close this feature request since it's been completed, thanks!

**Comment by aylaylay** [comment]
Possible? Probably. Is it worth doing yet? Not really.

**Comment by MrBrax** [comment]
My car is shaking like crazy, but it might also be that the joints are not up to the task for car physics.
