### ISSUE TITLE
Option to run game tasks off the main thread and let players know if any are still going when they disconnect

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-issues#436]
- `GameTask.Run` should accept a method that will execute off the main thread (internally `Task.Run`)
- `GameTask` will keep track of any tasks that haven't completed yet
- When disconnecting from a game, if any threads are still active, throw up an error
- The player cannot join any new games until these threads close
- Potentially warn developers through the backend that they are not completing tasks properly
- Hotload cannot run while the background task is actively running

**Comment by Willco2** [comment]
It would still be great to have this, as well as the `Parallel` class (or a functional equivalent), enabled for use.
