### ISSUE TITLE
There is no Sound.Stop

### ISSUE THREAD

**Issue by trende2001** [Facepunch/sbox-issues#4361]
### For?

S&Box

### What can't you do?

Currently I'm able to only stop all sounds, but I'm making a multiplayer game and I have a looping sound that I want to specifically stop.

### How would you like it to work?

N/A

### What have you tried?

The only workaround is ugly, like making a SoundHandle

**Comment by Gmod4phun** [comment]
Isn't making a SoundHandle the correct way of doing it tho?

**Comment by DoctorGurke** [comment]
var sound = Sound.Play("Sound");
sound.Stop();

**Comment by garrynewman** [comment]
How do you want to do it?

**Comment by garrynewman** [comment]
(accidental close)

**Comment by brannanz** [comment]
@DoctorGurke Please stop being a menace to a society

**Comment by MrBrax** [comment]
What about parenting (longer) sounds to entities/game objects? Do we have that still?

**Comment by Gmod4phun** [comment]
You have to manually update the `SoundHandle`'s Position but yeah, its possible. Gunfight uses that, too https://github.com/Facepunch/sbox-gunfight/blob/23a483d34e8fce2e61249a075eea211aa104944b/code/Utils/SoundEmitter.cs

**Comment by trende2001** [comment]
Sorry I'm just an entity chad trying to migrate over so I got confused easily
