### ISSUE TITLE
Adding a filter to the scss of a world panel causes it to render in screen space

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4362]
### Describe the bug

You can see in this video that the damage numbers appear in the world, but when i uncomment the filter in their scss they appear in the top left corner of the screen.

https://cdn.discordapp.com/attachments/1159407633497870347/1191956767484166264/2024-01-03_15-04-34.mp4?ex=65a7533e&is=6594de3e&hm=a0f519dbda51271f6d207c4990f4de83080e740f9fb13add6e6624a69f7968b1&

### To Reproduce

1. Make a world panel with some text
2. apply the filter property in scss
3. should render on screen

### Expected behavior

This used to work fine. It broke at some point after the scene staging branch got merged in.

**Comment by xezno** [comment]
Fixed this a while back but we have depth issues with worldpanels that become more apparent here, will track in #6165
