### ISSUE TITLE
Parenting seems inconsistent during OnUpdate

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4363]
### Describe the bug

I have the ability for the player to pick up weapons on the ground. The way this works is that it sets the parent of the object they're picking up to the players hold bone and then zeros its local position and rotation:

```CS
	public void EquipItem( ItemComponent itemComponent )
	{
		if ( itemComponent.Handedness is not Handedness.Left )
		{
			RightHandItem = itemComponent;
			itemComponent.GameObject.SetParent( HoldRight, false );
		}
		else
		{
			LeftHandItem = itemComponent;
			itemComponent.GameObject.SetParent( HoldLeft, false );
		}
		
		itemComponent.GameObject.Transform.LocalPosition = 0;
		itemComponent.GameObject.Transform.LocalRotation = Rotation.Identity;

		itemComponent.PlayerController = this;
		//carriedItemComponent.AnimatedModelComponent.BoneMergeTarget = Body;
		itemComponent.OnEquipped();
	}
```

This works *sometimes* and seems to randomly fail:

https://github.com/Facepunch/sbox-issues/assets/7847372/9a8058f2-6606-4918-83ae-bf2aab5631ab

You can see here it fails for the right hand but works for the left. It can happen to either hand and there's no way to seemingly predict when it will work.

### To Reproduce

Not super sure how to easily reproduce this. Seems a bit random.

### Expected behavior

Behavior should work consistently.

**Comment by FancyApricot** [comment]
GameTransform.ClearLerp ?

**Comment by Fortune117** [comment]
> GameTransform.ClearLerp ?

This fixed my issue! thanks
