### ISSUE TITLE
A clean ModelRenderer shows all bodygroup choices at the same time.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4369]
### Describe the bug

A clean modelrenderer will show all bodygroup choices at the same time until you override it.

### To Reproduce

1. Add a new model renderer.
2. Select a model that has body groups.

It will show all body group choices at the same time.

### Expected behavior

A clean model renderer should always use the default (first) choice of every body group.

### Media/Files

Each cube is in its own bodygroup choice.

https://github.com/Facepunch/sbox-issues/assets/91832803/ef49c455-e5aa-472d-9f98-5f275f408a90

[Model used in the video.zip](https://github.com/Facepunch/sbox-issues/files/13820895/Model.used.in.the.video.zip)

**Comment by aylaylay** [comment]
Body group now gets set to the model default on model change
