### ISSUE TITLE
ActionGraph Usability

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4370]
Something occurs to me with ActionGraph. We should be capturing the Scene, GameObject and Component implicitly.

We shouldn't need to define actions like this.

```
public delegate Task UpdateFunc( GameObject self, float dt );

[Property]
public UpdateFunc Update { get; set; }
```

That's messy and yucky. We should be able to define actions like this.

```
	[Property] public Action OnMapLoaded { get; set; }
```

Because this is defined on a Component, I would think we should be able to inject that into the graph as a kind of global when it's deserialized or created in the editor. This would make things a lot simpler and straight forward to use.

**Comment by Metapyziks** [comment]
That's a nice idea, I'll need to think about how to do it cleanly.

**Comment by dch-GH** [comment]
I definitely agree. As, at first with no prior knowledge about how ActionGraph worked, I went into it assuming the GameObject at the very least was implicitly passed to the action graph and was confused that it wasn't.

**Comment by Metapyziks** [comment]
How's this?

```csharp
[Property]
public Action ExampleAction1 { get; set; }
```
![image](https://github.com/Facepunch/sbox-issues/assets/1110904/acc1fa3e-ba2f-47de-ab99-ff8e18e51acb)

```csharp
[Property]
public Action<string, int> ExampleAction2 { get; set; }
```
![image](https://github.com/Facepunch/sbox-issues/assets/1110904/8c9ae17b-5e82-40cf-a6d2-c0491acc9a04)

And then you can customize it like:
```csharp
[Property, ActionContextCapture( Scene = true, GameObject = true, Component = false )]
public Action Action { get; set; }
```

**Comment by garrynewman** [comment]
That looks great! I would name Object to GameObject though?

I feel like it'd be better if they were standalone nodes that you dropped in, like global variables, rather than on the source node.

**Comment by Metapyziks** [comment]
Sure, I can play around with doing it that way.

**Comment by MrBrax** [comment]
Are the colors for arguments consistent? Or should there be a label for what the data types are?

**Comment by Metapyziks** [comment]
> Are the colors for arguments consistent? Or should there be a label for what the data types are?

The colours are based on types, like GameObjects are blue and components are green. I pretty much just picked random colours for all the other basic types so I'd expect them to change.

**Comment by MrBrax** [comment]
> > Are the colors for arguments consistent? Or should there be a label for what the data types are?
> 
> The colours are based on types, like GameObjects are blue and components are green. I pretty much just picked random colours for all the other basic types so I'd expect them to change.

Alright, sounds good. What about naming arguments?

**Comment by Metapyziks** [comment]
> Alright, sounds good. What about naming arguments?

You can define the delegate type like Garry's example above, or rename them in the ActionGraph editor.

**Comment by MrBrax** [comment]
Ok, I'll probably understand this more when there's documentation.

**Comment by Metapyziks** [comment]
> I feel like it'd be better if they were standalone nodes that you dropped in, like global variables, rather than on the source node.

Done:

![image](https://github.com/Facepunch/sbox-issues/assets/1110904/a13f4167-c837-423f-899c-7a3bd99c2695)

Also made it aware of which components are actually on the object containing the action, so you can easily add nodes to get them:

https://github.com/Facepunch/sbox-issues/assets/1110904/56dd1ac0-7740-4b67-8dca-488ccad145ed

**Comment by Metapyziks** [comment]
> Ok, I'll probably understand this more when there's documentation.

Here's a start: https://docs.facepunch.com/s/sbox-dev/doc/actiongraph-CUMGi4q3sS

**Comment by MrBrax** [comment]
> > Ok, I'll probably understand this more when there's documentation.
> 
> Here's a start: https://docs.facepunch.com/s/sbox-dev/doc/actiongraph-CUMGi4q3sS

Nice. Knowing whether it's useful for certain tasks is the next thinker.

Image URLs on the action components page are broken.

**Comment by Metapyziks** [comment]
> I also noticed Destroy() is missing on GameObject in the editor.

Well spotted, added them now.

**Comment by MrBrax** [comment]
Nice. Maybe this is out of scope and not the intended vision, but what i thought it was going to look like was this:

![1704802686726](https://github.com/Facepunch/sbox-issues/assets/1517911/4f81b0cc-6bdd-4ae5-9ba4-d9268fec154f)

Where all the fields/properties/methods was on the GameObject/Component node, without adding an extra "Get" node for every operation. Maybe this would be too restrictive.

**Comment by Metapyziks** [comment]
I'll see what I can do

**Comment by MrBrax** [comment]
It's your vision though, I don't want to change it for the worse if it is. I don't have any education in UX/UI design, I just enjoy trying to create self-explanatory and intuitive interfaces for my hobby projects.

**Comment by MrBrax** [comment]
Do we have a way to create an IEnumerable or List on the fly in the editor, or is that planned?
I might be bloating this issue too much with unrelated questions, if so, I will take notes for later.

**Comment by Metapyziks** [comment]
Feel free to open new issues with any feature requests like this, it's exactly the sort of stuff I'm looking for 👍
