### ISSUE TITLE
Inspector / ActionGraphs: Allow the `[Property]` Attribute to Be Used on `event` Fields

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/sbox-issues#4372]
### For?

S&Box

### What can't you do?

I'm unable to use the `[Property]` attribute on `event` fields.

### How would you like it to work?

I'd like the `[Property]` attribute to be usable on `event` fields; it should behave like an action graph.

### What have you tried?

This is the current workaround:
```csharp
public class ThingComponent : Component
{
    [Property]
    private Action<int> _onThing { get; set; }

    public event Action<int> OnThing;

    protected override void OnAwake()
    {
        if (_onThing != null)
        {
            OnThing += _onThing;
        }
    }

    public void DoThing(int foo)
    {
        OnThing?.Invoke(foo);
    }
}
```

**Comment by garrynewman** [comment]
Why are you using `event`?

**Comment by LeQuackers** [comment]
> Why are you using `event`?

Because I have a use case where the delegate shouldn't be set or raised directly; subscribers should only be added or removed from it.

**Comment by garrynewman** [comment]
Makes sense - added
