### ISSUE TITLE
Scene Trace IgnoreGameObjectHierarchy throws an NRE.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4373]
### Describe the bug

IgnoreGameObjectHierarchy( GameObject ).Run(); seems to always throw a null reference error:

`08:27:40   Generic Error in trace filter: Object reference not set to an instance of an object.`
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/2d35f2c7-3e8c-48f1-bb62-8fcc94c21367)

> 

### To Reproduce

```cs
		var tr = Scene.Trace.Ray( Vector3.Zero, Vector3.One * 100 ).IgnoreGameObjectHierarchy( GameObject ).Run();
```

### Expected behavior

Not throwing an error.

**Comment by garrynewman** [comment]
What colliders do you have in your scene? Are you on a map?

**Comment by dch-GH** [comment]
> What colliders do you have in your scene? Are you on a map?

Did it in 2 projects, both were using a map from asset.party. 1 project had no colliders, the other was just a Hitbox collider on the player GameObject.

**Comment by garrynewman** [comment]
Perfect, should be fixed now

**Comment by dch-GH** [comment]
Fixed 🥰
