### ISSUE TITLE
Rearranging gameobjects in the hierachy doesn't force a refresh of the labels

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4374]
When you rearrange objects in the hierarchy by dragging a label, it won't update them until you click or scroll.

https://github.com/Facepunch/sbox-issues/assets/1173137/7a961c1d-a66d-41f5-ad2d-117f4959ef6e

**Comment by garrynewman** [comment]
This is working fine for me

**Comment by ryleigh** [comment]
Here's me doing it on the physics lock testbed scene right now. Some objects in the hierarchy never have the behaviour, and others have it 100% of the time. Not sure why it only happens to certain ones.
https://github.com/Facepunch/sbox-issues/assets/1173137/867cde6f-dcc4-47df-abfe-e00f6ff5cc09
