### ISSUE TITLE
Created Bone Objects on a skinned model component do not update when model is recompiled

### ISSUE THREAD

**Issue by TheNameIsMatt** [Facepunch/sbox-issues#4376]
### Describe the bug

I want the bone objects in the scene to update and recompile when the model is updated in modeldoc.

I recognise this could be intentional design so feel free to close if it is.

### To Reproduce

1. Add a model into the scene that has Model Renderer (skinned) component
2. Tick Create Bone Objects in the component
3. Go to that VMDL and add or remove some bones and recompile the model
4. See that in scene view the created bone objects are not updated

### Expected behavior

Bones should automatically update in the live scene if this is possible, and references to the bones by other components should hopefully be kept in place if the bone still has the same name.

### Additional context

Current solution for this issue is to untick and retick the "create bone objects" box.

**Comment by garrynewman** [comment]
I'm not sure what the best thing to do here is. It would be unfortunate if you updated a model and it deleted a GameObject that had children you were using.. but it would probably make more sense to automatically update.

**Comment by aylaylay** [comment]
Okay I've made this update the bone hierarchy on model change and model reload, it's non destructive so it'll keep the objects but wont flag them as bones if they no longer exist (the same as if you retick the "create bone objects" box)
