### ISSUE TITLE
Services.Auth.GetToken returns quotation wrapped token

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4381]
### Describe the bug

When creating a token, the resulting token is wrapped in quotes.

Expected:
`87fb014a-cac4-437f-9b74-31c5afd6eedf`
Actual:
`"87fb014a-cac4-437f-9b74-31c5afd6eedf"`

### To Reproduce

1. Call `var token = await Sandbox.Services.GetToken( "ServiceName" );`
2. Log the value of token
3. Notice quotation marks surrounding the token

### Expected behavior

The token should not have quotation marks around it

**Comment by xezno** [comment]
Should be fixed now 😁

**Comment by trundlr** [comment]
Looks good! Thanks Alex!
