### ISSUE TITLE
No warning in console when using [Property] tag on a field.

### ISSUE THREAD

**Issue by TheNameIsMatt** [Facepunch/sbox-issues#4382]
### Describe the bug

Ran into an issue where I forgot to add {get; set;} to a field that had [Property]
![image](https://github.com/Facepunch/sbox-issues/assets/77700466/1be7d044-086b-4148-ac78-835209fb2795)

However the field still shows up in the component UI for me to add references to.
![image](https://github.com/Facepunch/sbox-issues/assets/77700466/b59f7b10-7696-41a7-86e8-d2ab91e66951)

I was confused as to why my reference kept going null upon pressing play and it was because I forgot to add getters and setters.

### To Reproduce

1. Create a field with the property tag but do not add {get; set;}
2. See that you can add reference to it in the component system
3. See that any reference in there returns null.

### Expected behavior

It should show an error of some sort for people like me.

**Comment by DevulTj** [comment]
This should work now, please let me know!

**Comment by TheNameIsMatt** [comment]
Yep doesn't let me add any values to it now in the scene without the {get; set;} thank you Devul 👍

**Comment by TheNameIsMatt** [comment]
Okay yes thats working now. Thank you <3
