### ISSUE TITLE
`WrappedPropertyGet/Set` Should Have an `Attributes` Property Like `WrappedMethod`

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/sbox-issues#4383]
### What it is?

`WrappedPropertyGet/Set` has a `MemberIdent` property which you can use to get the `MemberDescription` and then the actual attributes, but it'd be more concise to just have an `Attributes` property, especially if the [CodeGenerator](https://docs.facepunch.com/s/sbox-dev/doc/codegen-zhqowLeADO) attributes you're using have data associated with them.

It's also odd that `WrappedMethod` has an `Attributes` property, but `WrappedPropertyGet/Set` doesn't.

### What should it be?

`WrappedPropertyGet/Set` should have an `Attributes` property like `WrappedMethod`.

**Comment by kurozael** [comment]
Sorted! Lemme know if you have any other problems 👍
