### ISSUE TITLE
ModelRenderer stops rendering when not looking at Scene origin unless its re-enabled

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4384]
### Describe the bug

ModelRenderer stopped rendering unless the Scene origin is visible. This fixes itself if the component is disabled and enabled again. I assume a recent break since it worked fine yesterday.

https://github.com/Facepunch/sbox-issues/assets/5991682/f1b1a9b2-6716-4339-aba3-45a526758d86

### To Reproduce

1. Create a GameObject
2. Add ModelRenderer and set model
3. Observe the behaviour

### Expected behavior

Model should render properly

**Comment by aylaylay** [comment]
I can't see other models doing this so could you provide the model you're using or a repro I can download?

**Comment by garrynewman** [comment]
Does it fix itself when moving the GameObject slightly?

**Comment by Gmod4phun** [comment]
I am on a different computer at the moment, but the issue doesn't seem to happen. I will test it on the main computer again later today and see if it was just some random thing or if it still happens.
