### ISSUE TITLE
[Proton] Error loading package.base.dll

### ISSUE THREAD

**Issue by DarkReaper231** [Facepunch/sbox-issues#4385]
### Describe the bug

When I try to play any game, it's just a black screen, after few seconds, a red notification bubble appears at the bottom saying `Error loading package.base.dll`. Also I'm not on the `staging` branch. Should I be? Also when I'm in this state, I can't go back to main menu, the game probably isn't frozen since I do get the error notification, but the mouse is not visible and I can't exit. Killing is the only option. 

### To Reproduce

Run s&box under GE-Proton 8.25 maybe? 

### Expected behavior

All games should work. 

### Additional context

System: Arch Linux (latest rolling)
Proton version: GE-Proton 8.25
GPU: Nvidia GTX 1060 6GB

**Comment by handsomematt** [comment]
You're trying to play a game designed for scene not on the staging branch, we've frozen the main branch.
