### ISSUE TITLE
Video backgrounds set through scss don't loop

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4387]
### Describe the bug

If you set a background image to a video url then it will only play the video through once and not loop.

### To Reproduce

Try the following scss and see that the video doesn't loop:
```css
background-image: url("https://files.facepunch.com/garry/8aa83cc1-bcd6-4b11-80ce-ef2776c1b420.mp4");
```
Same thing happens with webms.

### Expected behavior

The video should loop or there should be a css style to set a background video to loop (?)

**Comment by handsomematt** [comment]
#4379 dupe
