### ISSUE TITLE
Body Group on Citizen Model Do Not Save On Playing Scene

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4388]
### Describe the bug

Disabling body groups on Terry does not save.

### To Reproduce

1. Create a Terry model with a player and citizen controller.
2. Changes the body groups on or off
3. Observe them not saving

### Expected behavior

The body groups should be save.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/76a49ec6-f95b-4631-81d9-601ad2a13513

**Comment by aylaylay** [comment]
Should be fixed now
