### ISSUE TITLE
[UseTemplate] not sending files to connecting clients

### ISSUE THREAD

**Issue by scottd564** [Facepunch/sbox-issues#439]
**Describe the bug**

Using `UseTemplate` on a Panel class will cause the html file to not be sent/loaded to connecting clients and will instead throw a FileNotFoundException. They will however be sent/used when using SetTemplate() instead.

**To Reproduce**

1. Create a Panel class with the `UseTemplate` attribute
2. Place the html file with the same name as the class and cs file along side the cs file.
3. Create the panel. In my case this is created in a HudEntity<RootPanel> class.
4. Have someone connect to you and the error will be thrown for them and no panel will be created/visible.

**Expected behavior**

The same as SetTemplate.

**Screenshots**

![error](https://dg1y66dctnlv0.cloudfront.net/ShareX/2021/07-04/4rUIURbI3V.png)

**Additional context**

Its possible Im messing something up but here is the codebase I tested it with and the change I did to make it work again.

https://github.com/scottd564/sbox-party/commit/67b61bd98e2db180c45742bcc963b5b769a7bc96

**Comment by Oppossome** [comment]
This issue is shared with imports in scss
