### ISSUE TITLE
SoundHandle.Volume isn't consistently applied immediately, sometimes it fades?

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4393]
### Describe the bug

SoundHandle.Volume isn't consistently applied immediately, sometimes it fades

### To Reproduce

Make a text to speech synth and set the volume right after playing a line, repeat this for a while with different sentences, you'll notice differences in volume.

### Expected behavior

Rather have volume be applied immediately

**Comment by garrynewman** [comment]
Have you tried calling SoundHandle.Update() after changing the volume? Does that fix it?

**Comment by ShadowBrian** [comment]
Yeah it does!
