### ISSUE TITLE
Terry's Irregular Skin Color

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4396]
### Describe the bug

Terry's skin looks all old and pale.

### To Reproduce

1. Use the terry model in a scene.

### Expected behavior

Terry should look normal

### Media/Files

![Screenshot 2024-01-05 141921](https://github.com/Facepunch/sbox-issues/assets/95300917/0d0513c2-9bc4-477f-ac3b-15233d4c8844)

**Comment by trundlr** [comment]
you ok honey?
