### ISSUE TITLE
Prefab fails to open if component throws exception in constructor

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#4397]
### Describe the bug

If the component constructor runs into a null exception you are unable to open the prefab.

For example, a Player component on a prefab with the following constructor...

```csharp
public Player()
{
       Object obj = null;
       Log.Info( obj.ToString() );
}
```

will run when you open said prefab. This will not allow you to open the prefab.

### To Reproduce

1. Create a component and put it on a prefab
2. Make sure that the component has a constructor
3. Try and open the prefab

### Expected behavior

It should allow you to open the prefab at least.

**Comment by garrynewman** [comment]
When you open a prefab it creates the component, why would you expect the constructor not to run?

**Comment by matekdev** [comment]
I don't think I care that much that it runs the constructor, but, it does seem a bit weird that if the constructor throws any exception you are unable to open the prefab.

**Comment by garrynewman** [comment]
I can fix that

**Comment by matekdev** [comment]
Thanks, I'll edit the issue details to be more explicit.
