### ISSUE TITLE
Scene loading screen stuck forever when playing scene for the first time

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4398]
### Describe the bug

When I click 'Play' to play the scene, the loading screen never disappears unless I stop the game and play again. I also tested it on a newly created project, too, just to check if my existing one isn't at fault.

### To Reproduce

1. Run the editor
2. Open any scene project
3. Click 'Play'
4. See loading screen stuck unless you stop and play again

### Expected behavior

Loading screen should work on the first time playing the scene in a session

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/d927ac3c-76ab-4ef3-ac9d-adbce04fe25d

**Comment by garrynewman** [comment]
I'm getting this too, I don't think the loading screen is even open - it just isn't rendering anything so it's showing what was drawn last.

**Comment by garrynewman** [comment]
I found out how to fix this. Resizing the screen slightly makes it render again..

**Comment by garrynewman** [comment]
I haven't had this happen for a while

**Comment by Gmod4phun** [comment]
I am still getting this from time to time.

**Comment by badandbest** [comment]
Happens to me a lot

**Comment by canoom** [comment]
This isn't exactly what i am having, but i'm guessing its related

**Comment by canoom** [comment]
This was fixed for me in the latest update, thanks
