### ISSUE TITLE
Show scene-related save/reload windows when the scene has changes and you try to close s&box or you've pulled in scene changes from git

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4399]
### For?

S&Box

### What can't you do?

Whenever the scene has changes you can just close the game without saving, and if you're working on a project with others it doesn't detect external changes in the scene file so you have to close and re-open it.

### How would you like it to work?

 It should probably ask you if you're sure you want to close the game and lose your changes.
And it should probably also detect external changes were made and offer to reload the scene, like visual studio does with pulled in changes.

### What have you tried?

You can just close the game without saving if you have changes in your scene, and reloading is kind of annoying if the scene has been changed by others in your dev group.

**Comment by DevulTj** [comment]
Yeah but something broke it last week (https://github.com/Facepunch/sbox-issues/issues/4694#issuecomment-1936763269)
