### ISSUE TITLE
Getting Crash very often While Placing asset.party object

### ISSUE THREAD

**Issue by Barakamonnn** [Facepunch/sbox-issues#4402]
### Describe the bug

while downloading, and placing the asset.party object, i always getting this weird crashes

### To Reproduce

1. Install the object
2. Place the object onto the scene
3. Play The Scene for 1 minutes or less
4. Then the game will be freeze and crash automatically

### Expected behavior

Placing the asset.party object shouldnt crash the game easily, maybe a little stall 

### Additional context

My Laptop Spec is Ryzen 5 5600H with GTX 1650ti and running on Window 11 

im using VS 2022 as my main IDE

its should be good enough

**Comment by Gmod4phun** [comment]
Possibly related to #4403

**Comment by garrynewman** [comment]
Has it just started happening today?

**Comment by Barakamonnn** [comment]
Yes, yesterday its just seems ok when i try to drag n drop the asset onto the scene (just a little laggier as far as i remember) 
but this time, it got more laggier and crashed very often or when i play the scene and move around with that asset store, my editor would freeze and crashed again. It kinda make me annoyed ngl.

**Comment by garrynewman** [comment]
Might be fixed in the next build
