### ISSUE TITLE
Asset thumbnails are rendering weirdly and crash the game

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4403]
### Describe the bug

I noticed that recompiling/editing assets crashes the game, for some reason the thumbnail becomes all pixelated and then crashes after a while.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/fc5db95c-47b5-4e47-b07a-bbc0e60db78b)

Here's also a video of it in action

https://github.com/Facepunch/sbox-issues/assets/5991682/137472b2-202e-4c7f-971d-449ac89ce576

### To Reproduce

1. Open up a model
2. Change it and recompile
3. Try to see if it screws up and crashes after a while

### Expected behavior

No crash

**Comment by garrynewman** [comment]
Should be fixed in the next build
