### ISSUE TITLE
Make CameraComponent RenderTags and RenderExcludeTags use ITagSet

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4407]
### What it is?

The CameraComponent's RenderTags and RenderExcludeTags properties are of the `TagSet` type, not of `ITagSet` like the regular gameobject Tags, so it's not possible to use methods like `Set` or `SetFrom` directly on those tag sets.

In the meantime, manually casting the tags as ITagSet works.

### What should it be?

Should probably be `ITagSet` so that the various tag methods are available on those camera tag sets.

**Comment by garrynewman** [comment]
Added the missing methods to those classes.
