### ISSUE TITLE
List properties start shrinking the more populated your GameObject becomes

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4408]
### Describe the bug

When a List (Or any other collection like Arrays) gets displayed in the Inspector, it starts off looking as intended.
But the moment the GameObject gets more populated by Components it will slowly shrink to the point of being unusable.
Simply collapsing the components being viewed will return the List to the original way it was.

### To Reproduce

1. Create a component with a List property
2. Add the component to a game object
3. Add other components
4. Observe the List shrink

### Expected behavior

For the List property not to shrink

**Comment by trende2001** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/68961063/0e50e82f-8b5a-4dd8-a64e-bb868283a9c9)
All of the other components uncollapsed

![image](https://github.com/Facepunch/sbox-issues/assets/68961063/5e377a71-c0cb-4f5d-b407-0ae18cdacbbe)
Collapsed

**Comment by garrynewman** [comment]
Thsi should be fixed now
