### ISSUE TITLE
Need better way to use TagSet to test against a GameObject's Tags

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4409]
### What it is?

I have a component that looks like this:
```
public sealed class FilteredTrigger : Component, Component.ITriggerListener
{

	[Property] public TagSet TriggerInclude { get; set; }
	[Property] public TagSet TriggerExclude { get; set; }

	public void OnTriggerEnter( Collider other )
	{
		GameTags otherTags = other.GameObject.Tags;
		if ( otherTags.HasAny( TriggerInclude ) && !otherTags.HasAny( TriggerExclude ) )
		{
			// Do stuff
		}
	}

	public void OnTriggerExit( Collider other ) { }

}
```

However, I can't use the `TagSet` properties to test the GameObject directly, as `HasAny(...)` takes a `HashSet<string>` instead. It would be easy to convert the `TagSet`, but it feels like this scenario could be improved.

### What should it be?

`GameTags.HasAny(...)` should have an overload that accepts `TagSet`.

**Comment by LeQuackers** [comment]
Would be great if `TagSet`/`ITagSet` implemented `IReadOnlySet<string>`.

Related:
#3759
#4037

**Comment by garrynewman** [comment]
Added
