### ISSUE TITLE
Make scissoring shader based

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#441]
Switch to a shader attribute based scissor so:

- Scissoring works on panels with transforms
- Scissoring could apply border-radius
- Scissoring works on layers (for filter:)
- Could also support #434  while we're at it

**Comment by trundler-dev** [comment]
Ran into a scissoring issue whilst transforming a panel today so I felt the need to bump this. Hopefully it can be re-opened 🚂 😸
