### ISSUE TITLE
Editor Camera Can be NaN'd

### ISSUE THREAD

**Issue by TehFlaminTaco** [Facepunch/sbox-issues#4411]
### Describe the bug

When focusing on a GameObject who's transform contains a NaN, the Editor's Camera Position and Rotation will immediately inherit this, and be permanently broken.

### To Reproduce

Give a GameObject an Invalid Transform
```csharp
GameObject.Transform.Position = Vector3(1f/0f, 1f/0f, 1f/0f);
```
Double click it in the heirarchy

### Expected behavior

NaN Camera Positions / Rotations should be reset to default.

**Comment by garrynewman** [comment]
Should be fixed in the next update
