### ISSUE TITLE
Adding a tag from the inspector crashes the game

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4412]
### Describe the bug

When I try to add an existing tag to a component or gameobject from the inspector the game crashes.

### To Reproduce

1. Make a gameobject
2. Give it an existing tag through the inspector

### Expected behavior

Shouldn't crash 😭

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/91832803/9dd7bfbd-d595-474b-9907-e7e55f09bf3e

[Log.log](https://github.com/Facepunch/sbox-issues/files/13853019/Log.log)

**Comment by Gmod4phun** [comment]
Also seems to only be caused by clicking an existing tag button in the inspector menu. Adding a tag by manually typing in the name or setting them through code does not cause a crash.

**Comment by badandbest** [comment]
> Also seems to only be caused by clicking an existing tag button in the inspector menu. Adding a tag by manually typing in the name or setting them through code does not cause a crash.

Alright. I've update the issue. 👍

**Comment by garrynewman** [comment]
Did I cause an infinite loop 🙈
