### ISSUE TITLE
Model.Load fails to load the model if .vmdl_c is provided instead of .vmdl

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4414]
### Describe the bug

When using `Model.Load` to load models, the Model fails to load with an error if the provided filename ends with the compiled variant vmdl_c instead of vmdl. This is annoying because the default string when copying the asset path includes the compiled variant.

`ERROR: Resource name "models/any_model.vmdl_c" has the incorrect extension "vmdl_c" for the specified resource type (expected "vmdl")!`

### To Reproduce

1. Go to inspector, find a model, right click and copy path
2. Use that in a Model.Load
3. See the error

### Expected behavior

Model.Load should work with the vmdl_c, too.

**Comment by garrynewman** [comment]
Should be fixed in the next build

**Comment by Gmod4phun** [comment]
Looks like its fixed
