### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by hassantheking123321** [Facepunch/sbox-issues#4415]
### Describe the bug

Whenever I join a game it will only shows a black screen and shows no sign of loading the menu of the game any fix? The only game that works without a black screen is sandbox gamemode before that bug it was working there wasn't any black screen

### To Reproduce

1. Open s&box
2. Click on any gamemode

### Expected behavior

It will show a black screen instead of menu

### Additional context

I'm running on windows 11 my computer is 64 bits

**Comment by garrynewman** [comment]
You're not on the staging branch. The games you're trying to play are on the staging branch.
