### ISSUE TITLE
Gizmos don't show up in render modes

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4417]
### Describe the bug

Gizmos don't show up in render modes. This is quite annoying because you need fullbright to see in prefabs.

### To Reproduce

1. Look at a gizmo.
2. Select a render mode.
3. Gizmos stop rendering.

### Expected behavior

Gizmos should still render.

### Media/Files

I'm using fullbright as an example but this happens in every other render mode too.
| Normal | Fullbright |
|--------|--------|
| ![image](https://github.com/Facepunch/sbox-issues/assets/91832803/04b19ef9-f623-454b-91ce-d7611634f0aa) | ![image](https://github.com/Facepunch/sbox-issues/assets/91832803/1f17117c-2581-40ef-a379-c18de97f9b2c) |
|  ![image](https://github.com/Facepunch/sbox-issues/assets/91832803/1daa7b64-8de8-4947-8a64-f4aa032ea7ff) | ![image](https://github.com/Facepunch/sbox-issues/assets/91832803/26845cec-3a34-475f-b369-40b292ea871e) |

**Comment by handsomematt** [comment]
Let me know if that's working for you next build.

**Comment by badandbest** [comment]
That was incredibly fast. Thank you!
