### ISSUE TITLE
Add support for multiline label control widget

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4418]
### For?

S&Box

### What can't you do?

I'm unable to enter multiple lines of text in a string property field. It would be nice to have a property to allow that.

### How would you like it to work?

Similar to `[Property, FGDType( "text_block" )]`
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/6a08fdfc-3016-4e7b-85d3-dfe9a4afdedf)

### What have you tried?

`[FGDType( "text_block" )]` doesn't work.
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/34d76264-bdd3-43df-9f1d-b130f8c1a68d)

Putting `\n` in the field doesn't work.
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/d7253478-ed8f-4e91-8d31-4843185371d7)

### Additional context

A recent bug made me realize how much I want this.
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/41a73982-430a-4c12-bfb9-572a540b76e0)

**Comment by garrynewman** [comment]
This should be easy enough to implement. Should be something like `[TextArea]` on a string property.

**Comment by DevulTj** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/b4b0353e-63c0-4793-bdcd-686ce1b147d2)
Added this now, use [TextArea] on a string property

**Comment by badandbest** [comment]
Wow it even has a scrollbar. I'm super happy with this thank you.
