### ISSUE TITLE
Model Physics renders some models at scene origin

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4420]
### Describe the bug

Not sure why or the specific reason some models are affected, but models like the trolley or the toilet don't render where they should if used in a Model Physics component. They seem to be stuck at the scene origin. Other models, like the Citizen or the human model work fine.

### To Reproduce

1. Create a object with Model Physics and use any of the affected models, like the toilet or trolley
2. See that it does not render where it should

### Expected behavior

Model should render in the correct place.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/16691355-b2ff-4587-8301-11a3711231ec

**Comment by aylaylay** [comment]
This should be fixed when the game next updates

**Comment by Gmod4phun** [comment]
Seems good, thanks :)
