### ISSUE TITLE
PhysicsBody.AddShape Doesn't Produce A Valid PhysicsBody

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4421]
### Describe the bug

I'm trying to do a hull trace with `Scene.Trace.Body`, but `PhysicsBody.AddShape` doesn't produce a valid `PhysicsBody` (e.g. the bounds are incorrect).

This code:

```
var standingModel = Model.Load( "models/player_collider_standing.vmdl" );
var hull = standingModel.Physics.Parts.First().Hulls.First();

Log.Info( "bounds of hull are " + hull.Bounds ); 

PhysicsBody playerCollider = new( Scene.PhysicsWorld );

if ( playerCollider.AddShape( hull, new Transform() ) == null )
    Log.Error( "failed to create player collision shape" );

Log.Info( "bounds of player collider are " + playerCollider.GetBounds() ); 
```

Outputs:

```
bounds of hull are mins -10,-10,-0, maxs 10,10,71
bounds of player collider are mins -0.0625,-0.0625,-0.0625, maxs 0.0625,0.0625,0.0625
```

When it should output:

```
bounds of hull are mins -10,-10,-0, maxs 10,10,71
bounds of player collider are mins -10,-10,-0, maxs 10,10,71
```

Here are the model files used above:

[model_files.zip](https://github.com/Facepunch/sbox-issues/files/13861064/model_files.zip)

### To Reproduce

See above

### Expected behavior

`PhysicsBody.AddShape` works, or it throws/logs an error/warning explaining why it doesn't work

### Additional context

Doing something simpler like adding a box shape seems to work fine

**Comment by aylaylay** [comment]
Thanks for providing the model files, I'll look into it

**Comment by aylaylay** [comment]
@anthonysharpy Are you sure this isn't because you were doing ``new Transform()`` and that used to do zero scale?

**Comment by aylaylay** [comment]
I have made it warn you when creating hull or mesh is invalid, that should help a little bit with any confusion

**Comment by anthonysharpy** [comment]
> Are you sure this isn't because you were doing new Transform() and that used to do zero scale?

@aylaylay Yeah I think this must have been something that was messing it up, the bounds show correctly now

I still can't get this to produce a valid raycast though, no matter what I try it seems to be defaulting to the tiny sphere... I'm trying to do something along these lines

```
var standingModel = Model.Load( "models/player_collider_standing.vmdl" );
var standingHull = standingModel.Physics.Parts.First().Hulls.First();

StandingPlayerCollider = new( Scene.PhysicsWorld );
StandingPlayerCollider.AddShape( standingHull, new() );

// ... later ...

var collider = StandingPlayerCollider;

collider.Position = Transform.Position; // Set it to our player's position

var trace = Scene.Trace
	.Body( collider, Transform.Position + (Velocity * 0.01f) ); // Velocity is a Vector3

// Think this line is unnecessary but better safe than sorry
trace.FromTo( Transform.Position, Transform.Position + (Velocity * 0.01f) );

// Set some tags and stuff
// trace = SetCollisionTags( trace, 1 );

var result = trace.Run(); 
```

Are there any code examples of something like this working? There might just be a small mistake in my code somewhere but nothing obvious is popping out at me.

**Comment by aylaylay** [comment]
Looks like sweeping a body hasn't been supported yet in scene, I'll add support for that

**Comment by aylaylay** [comment]
I've now added support for Scene.Trace.Body, here's the repro component I'm using.

```cs
public sealed class TestSweep : Component, Component.ExecuteInEditor
{
	PhysicsBody StandingPlayerCollider;

	protected override void OnEnabled()
	{
		base.OnEnabled();

		var standingModel = Model.Load( "models/player_collider_standing.vmdl" );
		var standingHull = standingModel.Physics.Parts[0].Hulls[0];

		StandingPlayerCollider = new( Scene.PhysicsWorld );
		StandingPlayerCollider.AddShape( standingHull, new() );
	}

	protected override void DrawGizmos()
	{
		base.DrawGizmos();

		var collider = StandingPlayerCollider;
		collider.Position = Transform.Position;

		var trace = Scene.Trace
			.Body( collider, Transform.Position + Transform.Rotation.Forward * 1000 );

		var result = trace.Run();

		Gizmo.Draw.Color = result.Hit ? Color.Red : Color.Green;
		Gizmo.Draw.Line( Transform.World.PointToLocal( result.StartPosition ), Transform.World.PointToLocal( result.EndPosition ) );
		Gizmo.Draw.Model( "models/player_collider_standing.vmdl", global::Transform.Zero.WithPosition( Transform.World.PointToLocal( result.EndPosition ) ) );
	}
}
```

**Comment by anthonysharpy** [comment]
@aylaylay Thanks so much, this was driving me nuts 😃 Works great
