### ISSUE TITLE
Skinned Models lack a Root Motion Property

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4422]
### For?

S&Box

### What can't you do?

Can't access the root motion of my animated objects in the scene system.

### How would you like it to work?

Probably just SkinnedModelComponent.RootMotion, or maybe have it on the animgraph?

### What have you tried?

Can't find a work around :(

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/b24dac2b-5195-4498-9c3f-f5d3390f7d52
