### ISSUE TITLE
ModelCollider is bugged when object is scaled by z or x axices

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4424]
### Describe the bug

ModelCollider is not working proprly when being scaled
looks like z and x axices were mixed up

https://github.com/Facepunch/sbox-issues/assets/9992453/80238bea-2780-49a6-b65e-68741cb32c9b

### To Reproduce

scale x or z axis of object with model collider and try to collide it with something
or use this pastebin as scene https://pastebin.com/Ndn1dbdm

### Expected behavior

collides how it supposed to

**Comment by aylaylay** [comment]
This should be fixed when the game next updates
https://github.com/Facepunch/sbox-issues/assets/1667289/ae918b95-89ef-4375-a1cc-3314dcc1b1b3

**Comment by GavrilovNI** [comment]
yeah, that works with vmdl models, but it does not work for generated models
here is a setup that doesn't work:
try to scale "crate" object
"crate" should has TestCube component on it with set collider property

generation code: https://pastebin.com/rr6MSMRE
scene: https://pastebin.com/nQaiWnWX

https://github.com/Facepunch/sbox-issues/assets/9992453/bb29878b-9ae6-4dd1-bb45-055754aa0a0a

**Comment by aylaylay** [comment]
Should work now when the game next updates
