### ISSUE TITLE
Cameras seem to jitter when parented to something.  

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4426]
### Describe the bug

Cameras seem to jitter when parented to something.
 

### To Reproduce

Parent a camera to something moving (like a player)
look at jitter

### Expected behavior

should correctly follow the object its parented to

### Media/Files

https://cdn.discordapp.com/attachments/1159407633497870347/1193732624452161596/Desktop_2024.01.08_-_12.46.32.03.mp4

**Comment by garrynewman** [comment]
That's odd, I haven't experienced that, will look into it

**Comment by Xenthio** [comment]
heres another video showing it only happens when parented, 
https://cdn.discordapp.com/attachments/715503242280304660/1194180661569933384/Desktop_2024.01.09_-_18.26.01.05.mp4

**Comment by Xenthio** [comment]
Okay well uhm interestingly it seems to be fixed, it mightve been somehow related to the rigidbody NRE? but I had that NRE way before this issue started happening
