### ISSUE TITLE
Time.Tick Broken or need replacement

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4428]
### Describe the bug

It seems that Time.Tick is either broken or is now unavailable after the scene system stuff,

### To Reproduce

Log.Info(Time.Tick)

### Expected behavior

a time number that is synced between the server and the client of the game showing the current count of total fixed updates (new equivalent of a tick), (handy for syncing random numbers across client and server)

**Comment by Xenthio** [comment]
Idk if this is fully solved? Is there a valid replacement that already exists that I'm not aware of?

**Comment by garrynewman** [comment]
No it's solved, it wasn't used for anything
