### ISSUE TITLE
Editor crashes on start up due to Action Graph

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4430]
### Describe the bug

Whenever I try to start up the editor, an error is thrown after the compiling all base projects stage.  The error is present in the logs provided.  Seems to be related to the action graph.

### To Reproduce

Not too sure how to reproduce, but this started happening after an editor crash due to a compile.

### Expected behavior

The editor should load as normal.

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/13873609/Log.log)

### Additional context

Repo is at https://github.com/ScoutWozniak/RetroFPS , might provide more answers.

**Comment by Metapyziks** [comment]
Just pushed a potential fix of what I think the problem was, it'll take a few minutes to show up.

**Comment by ScoutWozniak** [comment]
Yep works now thanks!
