### ISSUE TITLE
Add SkinnedModelRender.GetBoneObject( Bone bone )

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4431]
### What it is?

I'm able to parent things to the different bones of a skinned model render in the hierarchy, but they seem to be inaccessible on the code level.

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/83a2b8d9-1ffd-4431-b5a6-c366d083a2bc)

There's an internal dictionary for converting bone indexes to game objects but no way to access it or retrieve anything from it.
`private Dictionary<int, GameObject> boneToGameObject = new Dictionary<int, GameObject>();`

### What should it be?

In my use case, I'm hitting a hitbox and I want to parent the object that hit the hitbox to the bone used for that hitbox. I can access the bone and its index, but can't turn that into the game object I need to set the parent to.

**Comment by DevulTj** [comment]
Hey I've added this, let me know if it's all good for you. I tested this in Gunfight with the following code:

```csharp

if ( tr.GameObject?.Components.Get<SkinnedModelRenderer>( FindMode.EnabledInSelfAndDescendants ) is var s )
{
	var go = s.GetBoneObject( tr.Hitbox.Bone );
}
```

**Comment by Fortune117** [comment]
Works great, thanks!
