### ISSUE TITLE
Lots of dynamic, shadow mapped lights cause performance issues

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4432]
### Frame Rate

I have a big-ish map with lots of lights etc. I used to get 50-120 FPS on this map with no VIS and the MapInstance component used to work fine, until a couple of days ago when it looks like some changes were made and now the framerate has taken a nosedive, such that it's quite painful to use now...

https://github.com/Facepunch/sbox-issues/assets/55365296/9856e36f-32cd-4ca3-a7f0-b3f3c32b0809

I suspect the issue is something to do with the lights, since if I manually disable them in the scene, I get a decent framerate again. This is not a workaround though since as soon as I press play, the lights automatically get re-enabled.

### Light Brightness

The lights in-game have become a lot brighter suddenly. This is sort of good as it now more accurately matches what's in Hammer:

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/e340c42d-baf4-44e1-b2c0-77d2b4f6d94e)

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/11147b3a-427b-414e-9e93-625ed7fd74e1)

It does mean that I have to re-adjust some of my lights now though. Is this something that's expected to stay? I don't want to manually adjust hundreds of lights only to find it's going to change again or something.

### Light Colours

The lights spawned in by the map component seem to have the wrong colours. This leads to some awkward places where the colour of the baked lighting disagrees with the colour of the scene lighting:

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/f800d845-c038-4623-b6a6-c4b6971f3ad6)

The same thing in Hammer:

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/a97c4752-640c-4ba3-8b79-64c535151928)

Another example:

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/a400ded2-6cab-4417-a7da-22aa4fc29a55)

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/b514f47f-be2c-4111-9d48-d350bce49269)

### To Reproduce

See above

### Expected behavior

See above

**Comment by MrBrax** [comment]
My suspicion is that the SceneLight does not take into consideration if the hammer light is baked only, therefore applying dynamic lighting to every created SceneLight in the map. Also having this issue.

**Comment by handsomematt** [comment]
Frame rate will be fixed with #4759 

Please make individual issues for the light colour & light brightness
