### ISSUE TITLE
LODs aren't calculated correctly in VR

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4434]
### Describe the bug

LODs aren't calculated correctly in VR.
It appears they are calculated based on distance from world zero, but it's hard to verify.

### To Reproduce

Look at terry in VR, the further from world zero you get the higher the LOD rendered is.

### Expected behavior

LOD based on VR view position/direction/screen.

**Comment by xezno** [comment]
Should be fixed on next build

**Comment by ShadowBrian** [comment]
Yup, all good. Thanks Alex!
