### ISSUE TITLE
Right eye in VR gets a lot of shadow artifacts if you look around/backwards from the world forward direction

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4435]
### Describe the bug

Right eye in VR gets a lot of shadow artifacts if you look around/backwards from the world forward direction

### To Reproduce

Start VR, look behind you.

### Expected behavior

No weird artifacting in either eye.

### Media/Files

https://cdn.discordapp.com/attachments/834357840646504478/1194306740037095425/chrome_WApo6OjyRM.mp4?ex=65afdfd3&is=659d6ad3&hm=9a814dd15010332942adecd58e7c18f33befc11f5cf502567484696d9cb92031&

### Additional context

Video shows the issue in the right eye.

**Comment by garrynewman** [comment]
Looks like the same stuff as in regular multi-camera

**Comment by ShadowBrian** [comment]
Seems to be fixed?

**Comment by samzanemesis** [comment]
Root cause of this still persists, I'm working on it now

**Comment by samzanemesis** [comment]
Should be good

**Comment by ShadowBrian** [comment]
lgtm ty sam
