### ISSUE TITLE
Hitting ESC/Enter should unfocus a selected Inspector field

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4438]
A minor (but common) occurance I have:
- select an inspector field and type in a value, hit enter
- attempt to switch to Move/Position widget mode by hitting W key
- since the inspector field is still selected, it types there instead

![sbox-dev_2024-01-09_21-13-17](https://github.com/Facepunch/sbox-issues/assets/1173137/60309ef5-68cb-4962-9600-0c2724b237ac)

Currently the only way I can find to unfocus the field is by using the mouse and clicking somewhere else.
I'd suggest making Enter "submit" a currently focused inspector field (and/or making ESC unfocus one), so you can continue using keyboard shortcuts without needing to use the mouse first.

**Comment by xezno** [comment]
Should be fixed on next build

**Comment by Retroeer** [comment]
While fixed, I do wish we got the proposed "Enter" = "Submit".  Hitting enter doesn't really do anything to those fields right now and feels kinda bad (personally).

**Comment by xezno** [comment]
Can do

**Comment by xezno** [comment]
Never mind, looks like @handsomematt got there before me 😄
