### ISSUE TITLE
Input rebinding doesn't work

### ISSUE THREAD

**Issue by MaxLebled** [Facepunch/sbox-issues#4443]
### Describe the bug

I've reproduced this with both the model viewer project and sbox-walker

![image](https://github.com/Facepunch/sbox-issues/assets/3624123/11695b7a-13d7-47f2-88b5-12141373cfcb)

Binds are in place (WASD to ZQSD because French keyboard), **but inputs aren't getting replaced accordingly**. WASD is still answering

### To Reproduce

Go to Edit > Project Settings > Input, and change the movement keys to other keys

### Expected behavior

New binds should work

### Additional context

![image](https://github.com/Facepunch/sbox-issues/assets/3624123/fdf2a0ef-358b-4eaf-a63e-3021f992620e)

.sbproj is getting updated correctly

**Comment by DevulTj** [comment]
Worth noting that this isn't the right way to be rebinding common inputs. All common inputs such as left, forward, right, etc.. are common inputs and are loaded from your **local** binding options in the game settings. 

If you're making your own, new inputs, that don't clash with the naming of common inputs - they should be getting updated properly unless you've saved your own preferences locally too.

**Comment by MaxLebled** [comment]
Yup, nothing under sbox\game\config\input

**Comment by MaxLebled** [comment]
Okay, I see what happened. I was under the impression that the menu-side input was completely discarded since you can't access the menu (or get back to it) from a project. Loading the tools in "content mode" has let me access the menu, and from there, through settings, I was able to rebind these "common inputs".

So the problem at play here is that the distinction between common & game-specific inputs is very much not clear (let alone the fact that you can't rebind these so-called "common inputs")

**Comment by MaxLebled** [comment]
(which is to say, I'll let you write up an issue for that if you'd like, as that's out of my realm)
