### ISSUE TITLE
ModelDoc viewport models are completely black

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4444]
### Describe the bug

In the viewport of ModelDoc, both the plane and subject are completely black with no texture. It's as if viewing a scene with no lighting whatsoever.

### To Reproduce

1. Open a model in ModelDoc
2. Look at the viewport

### Expected behavior

You should be able to see models in ModelDoc.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/8889285/d84f14de-7310-4168-9f5b-aa652ec7ab63

**Comment by MaxLebled** [comment]
Can confirm

**Comment by MaxLebled** [comment]
Looks like it's been fixed, can you confirm?

**Comment by handsomematt** [comment]
yeah fixed this morning
