### ISSUE TITLE
Creating a new component does not properly open the solution in vscode

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4445]
### Describe the bug

When you create a new component and it opens vscode for you, there's no project open. It just opens the .cs file so I get no intellisense and have to close visual studio and open it from the component again, which opens the solution fine.

### To Reproduce

make sure vscode is closed
create a component, it will automatically open in vscode
try to type something in it
no intellisense because there's no solution loaded

### Expected behavior

it should open the solution and the file so intellisense works properly and you can navigate through the project

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/94070205/32659fe1-1dfe-426a-9987-eea5eab90869

### Additional context

if you put spaces in the name of a component, it should probably remove them in the file explorer popup because it'll try to put spaces in the class name too.

**Comment by DevulTj** [comment]
I've made a change that should address your problem - let me know if this fixes it for you!
