### ISSUE TITLE
Allow accessing SceneCamera from CameraComponent

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4446]
### What it is?

I want to make a screenshot from camera view using Graphics.RenderToTexture but i cant because can't get SceneCamera from CameraComponent

### What should it be?

SceneCamera property in CameraComponent should be public
or
make another way to make a screenshot without using SceneCamera

**Comment by DevulTj** [comment]
I'm trying not to expose SceneCamera until absolutely necessary. I've added CameraComponent.RenderToTexture that'll do what you need.
