### ISSUE TITLE
Prop static doesn't work in Hammer

### ISSUE THREAD

**Issue by Ethrenduil** [Facepunch/sbox-issues#4448]
### Describe the bug

When i start Hammer, all my props are obsolete.

### To Reproduce

1. Open Hammer
2. Click on entity
3. A lot of them dissapeard

### Expected behavior

Have a lot of entity types to add to your map

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/72016152/66f6dafc-8295-48f6-80da-091aa07b15db)

**Comment by handsomematt** [comment]
They'll be there again next build
