### ISSUE TITLE
Wireframe debug view

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#4450]
It would be nice to have option to show a wireframe view, The console command mat_wireframe 1 does function but it would be nice to have a quick button for it as well. There are 2 functions as well with mat_wireframe, 1 is with depth, 2 is without nice to be able to select which one to use.
![image](https://github.com/Facepunch/sbox-issues/assets/8184184/7db480bf-90f9-4cee-a4aa-911b05118ec0)

**Comment by handsomematt** [comment]
I did also hookup the "Wireframe" render attribute, so this should be done without changing mat_wireframe globally, the same way we set ToolsVis
