### ISSUE TITLE
Add aspect ratio to CameraComponent

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4451]
### For?

S&Box

### What can't you do?

Now its impossible to change aspect ratio of camera
I'm trying to make texture by Camera.RenderToTexture() and want it to be square, but i can't

### How would you like it to work?

I'd like to have AspectRatio property on CameraComponent
when modified it will use that value instead of screen aspect ratio
and have something like ResetAspect method to reset and use screen aspect ratio

### What have you tried?

no there is no way to change it
probably for Camera.RenderToTexture() i can just make full screen image and cut part of it, but it's too complicated

**Comment by handsomematt** [comment]
This seems backwards

We should be creating a render target the camera can render to and use the size of that.

**Comment by GavrilovNI** [comment]
> This seems backwards
> 
> We should be creating a render target the camera can render to and use the size of that.

any way that will allow making texture of required aspect ratio would be awesome!
