### ISSUE TITLE
Allow expanding the entire hierarchy of a game object

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4454]
### For?

S&Box

### What can't you do?

I have items parented to specific bones on the players skeleton and it's a bit of a pain to dig through the game object hierarchy each time to get to them.

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/7bb6ef1f-83c5-457d-984f-71b70c3d4d9d)

### How would you like it to work?

Having the ability to right click the players game object and click 'expand all' would be very convenient.

### What have you tried?

Manually digging through the tree.

**Comment by DevulTj** [comment]
@solwllms implemented this a while ago, from what I remember

**Comment by Fortune117** [comment]
> [@solwllms](https://github.com/solwllms) implemented this a while ago, from what I remember

There's no option when you right click a hierarchy, but shift clicking on the arrow works.
