### ISSUE TITLE
inspector numeric properties acceps letters as inputs

### ISSUE THREAD

**Issue by RickGreeve** [Facepunch/sbox-issues#4456]
### Describe the bug

changing the rotation value and pressing 'w' afterwards resets the value

### To Reproduce

1. select an object
2. change the rotation and press w
3. hit enter and the value resets to 0

### Expected behavior

those properties shouldn't accept letters as inputs

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/125879070/91fd5d51-1b82-4883-805f-38c4e91d362e

**Comment by DevulTj** [comment]
I've added probably the world's chunkiest regex validator to float control widgets so it disallows use of letters outside of e (for exponential notation), and outside of that only accepts whole and decimal numbers. Should be all good now!
