### ISSUE TITLE
console spammed with: [engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event

### ISSUE THREAD

**Issue by tommydaz** [Facepunch/sbox-issues#4457]
> 2024/01/11 14:16:02.3770	[engine/Engine] SteamAPI_Init succeeded.  SteamID is [U:1:401701] (76561197960667429), AppID is 590830	
2024/01/11 14:16:07.8622	[Generic] Waiting for Web Auth Ticket..	
2024/01/11 14:16:08.8516	[GameMenu] Was unable to determine package for /models/sbox_props/cardboard_box/cardboard_box_open.vmdl_c	
2024/01/11 14:16:08.8516	[GameMenu] Was unable to determine package for /facepunch.floor_asphalt_blend/thumb.png	
2024/01/11 14:16:13.8097	[engine/ToolsStallMonitor] Stall detected.	
2024/01/11 14:16:18.3625	[engine/AssetSystem] AssetSystem initialized in 9.96 seconds. [0.16 load, 0.17 scan, 9.58 dependencies, 0.03 save]	
2024/01/11 14:16:19.0291	[Generic] Took 11.1952738s to get steam auth ticket	
2024/01/11 14:16:26.9949	[engine/ToolsStallMonitor] Stall detected.	
2024/01/11 14:16:48.3776	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:48.6514	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:48.9405	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:49.2384	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:49.5441	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:49.8551	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:50.1686	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:50.4562	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:50.7583	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:51.0658	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:51.3678	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:51.6714	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:51.9754	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:52.2766	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:52.5988	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:52.8826	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:53.1862	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:53.5135	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:53.7963	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:54.0908	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:54.3984	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:59.6346	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:16:59.9592	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:00.2573	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:00.5607	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:00.8593	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:01.1669	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:01.4793	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:01.7715	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:02.0735	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:02.3855	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:02.6824	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:02.9871	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:03.2892	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:03.5922	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:03.8958	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:04.1974	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:04.5372	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:04.8109	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:05.1121	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:05.4086	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:05.7340	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:06.0147	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:06.3248	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:06.6269	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:06.9265	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:07.2275	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:07.5310	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:07.8341	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:08.1327	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:08.4442	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:08.7422	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:09.0468	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:09.3742	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:09.6722	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:09.9703	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:10.2580	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:10.5606	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:10.8636	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:11.1671	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:11.4749	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:11.7941	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:12.0953	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:12.3878	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:12.6859	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:12.9815	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:13.2895	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:13.6075	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:13.8942	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:14.2013	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:14.5013	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:14.8048	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:15.1263	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:15.4130	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:15.7140	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:16.0161	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:16.3156	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:16.6227	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:16.9268	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:17.2303	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:17.5344	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:17.8374	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:18.1404	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:18.4460	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:18.7466	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:19.0541	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:19.3551	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:19.6567	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:17:19.9607	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:18.4789	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:18.7765	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:19.0581	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:19.3845	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:19.6751	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:19.9727	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:20.2796	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/01/11 14:18:20.6607	[Generic] EngineLoop::Exiting	
2024/01/11 14:18:20.6903	[engine/ToolFramework2] Shutting down Qt windows.............	
2024/01/11 14:18:20.6903	[engine/Engine] Source2Shutdown	
2024/01/11 14:18:20.6903	[engine/Engine] ShutdownSource2Logging

**Comment by handsomematt** [comment]
solved with driver update
