### ISSUE TITLE
DecalRenderer Component doesn't update material and size

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#4458]
Changing the material or size of the DecalRenderer component doesn't update unless you disable and enable.

https://github.com/Facepunch/sbox-issues/assets/8184184/0fd50694-7618-4946-8402-72eb58ac1fff

**Comment by DevulTj** [comment]
This should be working as intended now

**Comment by bakscratch** [comment]
Yes thank you tony!
