### ISSUE TITLE
Creating new Component via Inspector could be smoother

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4459]
1) "New Component" is at the very bottom and isn't discoverable without noticing the scrollbar.

https://github.com/Facepunch/sbox-issues/assets/1173137/3653510b-aab3-4f6c-94f8-48ff2f2cd886

Since making a component is pretty common it feels like it should be near the top, perhaps as an icon.
This "Component" header looks like a button but isn't clickable, and seems quite redundant, maybe that space could be reclaimed for "New Component"
![sbox-dev_2024-01-11_11-31-36](https://github.com/Facepunch/sbox-issues/assets/1173137/db53e551-07ee-4ee9-bb86-d79a18b237c7)

2) Typing the name of a new component and hitting enter will add a newline to the name.

https://github.com/Facepunch/sbox-issues/assets/1173137/5947a266-e48b-497f-a11b-3fdad855d7a8

It shouldn't allow newlines in the name box, and should just create a new Simple Component when you hit enter (unless you manually add .razor in the filename, then Enter would make a new razor panel component)

**Comment by DevulTj** [comment]
Not sure if I agree with some of the stuff here.

> It shouldn't allow newlines in the name box, and should just create a new Simple Component when you hit enter (unless you manually add .razor in the filename, then Enter would make a new razor panel component)

I think this adds too much complexity to the code, where you can just click the button or use your arrow keys to select the component type you want.

> Since making a component is pretty common it feels like it should be near the top, perhaps as an icon.
This "Component" header looks like a button but isn't clickable, and seems quite redundant, maybe that space could be reclaimed for "New Component"

This is the category name.. I don't think putting the new component button there makes much sense. When you're in a subcategory, that button serves as the 'return to last selection' function.

> Typing the name of a new component and hitting enter will add a newline to the name.

This is fair, I've fixed this now.

**Comment by ryleigh** [comment]
Fair enough about  the unneeded code complexity, and I didn't realize the "Component" header turns into a subcategory/back button.

Though I still think "New Component" would feel nicer at the top, instead of hidden at the bottom.

**Comment by DevulTj** [comment]
> Though I still think "New Component" would feel nicer at the top, instead of hidden at the bottom.

I gave it a go last night and it didn't work well. It's the lesser used option than finding a component to plug in, so it makes sense to be lower down. I thought about docking it outside of the scroll area, but that will add too much code to the type selector.

![Image](https://github.com/Facepunch/sbox-issues/assets/22372616/6e8d1372-e554-4d2e-bde2-e81675d7559f)

**Comment by MrBrax** [comment]
I forget that option even exists, i just make a new cs file and write boilerplate myself. Not even sure what that one does?
