### ISSUE TITLE
[Hammer] info_particle_system doesn't have preview of particle system in 3D viewport

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#446]
**Describe the bug**
Back when it was a native entity, `info_particle_system` showed an in-editor preview of its assigned particle system. Although I'm sure its planned to return at some point, this feature isn't present at the moment.

**To Reproduce**
1. In Hammer, create an `info_particle_system`
2. Assign a particle system to it
3. Ensure that the "Toggle Particle Visibility" option is enabled under the View Settings

**Expected behavior**
Should have an active preview of the particle system in Hammer.

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by Willco2** [comment]
Issue is fixed now, thanks. But now there is no editor model, and not even the default cube, so it's impossible to see the entity in Hammer.

**Comment by robotboy655** [comment]
That should also be fixed now.
