### ISSUE TITLE
Glass shader materials cause a crash when recompiled

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4461]
### Describe the bug

Materials that use the glass shader crash upon recompile, even materials that worked fine until now. Also the glass materials show up broken again (pink/black checkerboard). There is nothing in the Logs that would say whats going on.

### To Reproduce

1. Have a material with the glass shader
2. Try recompiling it

### Expected behavior

No crashing

**Comment by xezno** [comment]
Shouldn't crash now. Glass also seems to be working fine on my end both on DX11 and Vulkan - where are you seeing it black/pink?

**Comment by Gmod4phun** [comment]
Any translucent model will do, for example the wineglass02 model.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/fdf4449e-db74-46ff-8ee6-eb1cdb882165)

Looks like the SceneObject WantsFrameBufferTexture flag isn't being set for some reason.

**Comment by xezno** [comment]
I see it now

**Comment by handsomematt** [comment]
Specific to the component not using the right flags for the model, a normal sceneobject still works

**Comment by xezno** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/2679dbf2-077b-432c-8c2e-1c367f945443)
Should be fixed next build

**Comment by Gmod4phun** [comment]
Yep, working fine again, thank you
