### ISSUE TITLE
Hammer Build Failed on Vtex Texture

### ISSUE THREAD

**Issue by KaanSacma** [Facepunch/sbox-issues#4462]
### Describe the bug

Cannot build any Hammer map

### To Reproduce

Go to Hammer
Open any map
Press 'F9'
Click any Compile Method (Full, Fast, Final)

### Expected behavior

Build the map

### Media/Files

<img width="791" alt="Screenshot 2024-01-12 at 14 33 58" src="https://github.com/Facepunch/sbox-issues/assets/91870254/f3ebb8ec-650c-4d03-a21d-8bb837294eb2">

### Additional context

I'm running on Windows 11.

**Comment by handsomematt** [comment]
All good now
