### ISSUE TITLE
Model Physics props don't gib correctly

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#4465]
Video showing what happens; object doesn't gib correctly only creates one of the gibs and doesn't kill the main model.

https://github.com/Facepunch/sbox-issues/assets/8184184/cd8b731c-0b18-492a-9e8a-d02a6ba64927

![image](https://github.com/Facepunch/sbox-issues/assets/8184184/55366c1e-3ee1-4665-b4e4-7ca8457c0fd9)

**Comment by aylaylay** [comment]
Looks like this got fixed but it spawns gibs at the wrong location
