### ISSUE TITLE
Having to have your game uploaded for local networking to function.

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4466]
### Describe the bug

If you have a project with a network helper, you have to upload your project to asset.party to be able to join from a new instance.

### To Reproduce

1. Create a project with a player and network helper
2. Try to join an instance.

### Expected behavior

Your game should not have to be uploaded.

**Comment by badandbest** [comment]
Yeah this is really annoying. Prefabs and maps have the same problem. They won't load on local instances unless you've upload them to asset.party first.

**Comment by garrynewman** [comment]
What makes it so you have to upload it? What errors do you get? What happens?

**Comment by badandbest** [comment]
> What makes it so you have to upload it? What errors do you get? What happens?

If the gamemode isn't uploaded, it will send the instance to the main menu.

https://github.com/Facepunch/sbox-issues/assets/91832803/35d0f65a-b73e-4b67-a113-1d081cf46545

If a map isn't uploaded, the instance can't load the map. Prefabs are a similar story.

https://github.com/Facepunch/sbox-issues/assets/91832803/f2478737-a0ba-429c-8fdd-9aaed4608c4b

Here's my log.
[Log.log](https://github.com/Facepunch/sbox-issues/files/13931285/Log.log)

Hope this helps you. 👍

**Comment by Ethrenduil** [comment]
I have the same issue

**Comment by DrakeFruit** [comment]
this also seems to happen to any models or materials, even if they're already on asset party.

**Comment by kurozael** [comment]
For `local` games:

- [ ] We need to download and install cloud package references
- [ ] We need to download and install cloud maps with MapInstance (what about local VPKs?)

**Comment by kurozael** [comment]
I believe this is stale.
