### ISSUE TITLE
Model Colliders don't set the surface property correctly.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4467]
### Describe the bug

I'm not sure if this is an issue with Model Colliders or traces, but my traces are not returning the correct surface when they hit a model collider:

https://github.com/Facepunch/sbox-issues/assets/7847372/8b5de85d-9b0c-40f9-92a4-0b4f94531511

In this video you can see it print the correct surface property, 'hay', when using a box collider. However, when using a model collider with the same surface property it returns 'default'.

The trace code I'm using looks like this:
```CS
		var traces = Scene.Trace.Ray( AimRay, 80f )
			.IgnoreGameObjectHierarchy( GameObject )
			.UseHitboxes()
			.Radius( 3 )
			.RunAll();
			
//for each trace result
			Log.Info( traceResult.Surface.ResourceName );
```

However, the surface is being set correctly on some level, as the physics sounds on the rigid body are playing correctly, as if each physics shape has the correct surface.

### To Reproduce

1. Fire a trace at a model collider and log the surface property
2. See that changes to the model doesn't seem to affect this.

### Expected behavior

Should return the correct surface.

**Comment by aylaylay** [comment]
Is this just an issue with RunAll?

**Comment by aylaylay** [comment]
It's possible that I fixed this by fixing something else, can you test for me please?

**Comment by Fortune117** [comment]
Yep, seems fixed now.
