### ISSUE TITLE
Small physics shapes pass through the floor very easily

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4468]
### Describe the bug

Here you can see several physics shapes going through the floor:

https://github.com/Facepunch/sbox-issues/assets/7847372/5079e81c-f4f5-42a9-b6d3-0a9851850c70

This is with a fixed update rate of 120.

You can see the physics shape is a pretty small rectangular prism, so I wouldn't be surprised if this is simply too small for the engine to handle reliably, but it doesn't seem that unreasonable.
![image](https://github.com/Facepunch/sbox-issues/assets/7847372/3ec79673-2a5c-4ab2-bb9d-57a7c5054e3a)

### To Reproduce

1. Make a small physics shape
2. Move it with a decent velocity
3. Goes through floors

### Expected behavior

Shouldn't go through floors so easily.

**Comment by Gmod4phun** [comment]
You could try setting the ground plane's collider as static. Don't quote me on this as this is just from my own observation, but I think static colliders use continuous collision detection and prevent small shit from passing through it.

It would be nice if the physics engine handled this stuff better for non-static colliders but I am not sure it is that trivial to make that work.

**Comment by Fortune117** [comment]
Oh wow, this immediately fixed it. Thanks! :D

**Comment by Gmod4phun** [comment]
It will still be a problem with non static colliders, so if you have a moving target, it might miss and go through it. I was doing some experiments with traces that trace from the previous to current position of an object, and if it hits what I need, I do some magic.
