### ISSUE TITLE
Collidision with a map does not work with ICollisionListener

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4469]
### Describe the bug

None of the functions in ICollisionListener are triggered when a gameobject collides with a map.  This also effects the rigid body's collision sounds as they also don't play.

### To Reproduce

1. Create a component with ICollisionListener in a scene with a map.  
2. Watch it not work
3. Bonus points if you listen to the rigid bodies not making any noises on collision!

### Expected behavior

OnCollisionStart, OnCollisionEnd and OnCollisionUpdate should be called for map colliders.

**Comment by quntherdev** [comment]
Same issue here

**Comment by aylaylay** [comment]
This should work now (note: you'll hear the wrong impact sound on meshes but that's a seperate issue i'll fix)

**Comment by ScoutWozniak** [comment]
Seems to work now!  Thanks!
