### ISSUE TITLE
Event EntityCreated and JointCreated

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/sbox-issues#447]
**What can't you do?**
Watch for entities or joints being created

**How would you like it to work?**
The event is called and passed the entity/joint once spawned

**What have you tried?**
Searched the object browser for an existing event

**Additional context**
Idk if joints count as entities or not, but if they are then EntityCreated alone would be fine.

**Comment by garrynewman** [comment]
Why?

**Comment by thegrb93** [comment]
I need to store the relative transform of two entities when a joint is connected to them via a tool or other mod so that the constraint can be accurately applied again in the future. (i.e. duplicator tool)

**Comment by garrynewman** [comment]
Hmm, I can see that being useful anyway - maybe it should be built into joints. This way you know you're getting the 100% correct data rather than hoping it's accurate based on the read values.

**Comment by thegrb93** [comment]
> 
> 
> Hmm, I can see that being useful anyway - maybe it should be built into joints. This way you know you're getting the 100% correct data rather than hoping it's accurate based on the read values.

I do see PhysicsJoint has some anchor values. I'll see if those will work.
