### ISSUE TITLE
Allow any PNG to be clicked and dragged from the Asset Browser to the scene

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4470]
### For?

S&Box

### What can't you do?

I cannot click and drag PNGs from the Asset Browser to the scene view to make a sprite.

### How would you like it to work?

When I click and drag a PNG from the Asset Browser to the scene, a new GameObject should be created that uses the PNG as the texture of a SpriteRenderer. 

### What have you tried?

Resizing my PNG to a power of two, creating a VTEX, creating a GameObject and SpriteRenderer myself, setting the Texture property of the SpriteRenderer to the VTEX.

### Additional context

I should not have to create a VTEX myself, and this should work for PNG files of arbitrary dimensions.

**Comment by garrynewman** [comment]
I agree with this, we should really find a nicer path.
