### ISSUE TITLE
Network.OwnerId returns 000000-00000-0000-0000 for network objects that were created before the client joined

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4473]
### Describe the bug

I'm trying to see if the `Rpc.CallerId` matches the `Network.OwnerId` of a component like so:
```cs
[Broadcast]
public void TryTalkingTo()
{
	if ( IsProxy ) return;

	IsAvailable = false;

	var other = NetworkManager.Instance.People.Where( x => x.Network.OwnerId == Rpc.CallerId ).FirstOrDefault();
	if ( other is null ) return;
	TalkingTo = other;

	TimeSinceLastRefresh = 0f;
}
```

The Linq search would never yield any results, but it wasn't until I printed info to the screen that I understood why.

Here is the `NetworkManager.Instance.People` list on the host:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/f479e8fb-96af-45ed-9af4-8a92b9f374cb)

Here is the same list on the client that connected first:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/461d83d6-fb99-4e4d-aa96-c97b0ed4db1f)

And here is the same list on the client that connected last:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/5d661c67-a716-4aef-a693-efd257811288)

It seems as though `Network.OwnerId` of existing components is not propagated to clients who join after their creation.

### To Reproduce

Get all your player components in the scene and then try logging their OwnerIds and see how they act on the host and connecting clients:
```cs
List<Player> people = Scene.Components.GetAll<Player>( FindMode.EnabledInSelfAndDescendants );
foreach(var person in people)
{
    Log.Info(person.Network.OwnerId);
}
```

### Expected behavior

You should always be able to see who owns a networked object.

**Comment by PolSpock** [comment]
Similar to https://github.com/Facepunch/sbox-issues/issues/4391 i guess

**Comment by dch-GH** [comment]
And maybe related to https://github.com/Facepunch/sbox-issues/issues/4304 ? Maybe my issue was wrong and it was just a symptom of this root problem instead.

**Comment by garrynewman** [comment]
Should be fixed now
