### ISSUE TITLE
Cloud assets are not downloaded when inside a Prefab

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#4476]
### Describe the bug

When you open a scene for the first time it will download all cloud assets that you are missing.
However, if those cloud assets are within a prefab they will not be automatically downloaded.

### To Reproduce

- Add a cloud model to a scene
- Convert the gameobject to a prefab
- Delete the cloud model in the asset browser
- Restart the editor and re-open the scene

### Expected behavior

The cloud model inside the prefab gets downloaded with other "loose" cloud assets in the scene.

**Comment by handsomematt** [comment]
I think this would've been fixed today, can you check?

**Comment by Jammie3d** [comment]
Just tested, seems good now thanks!
