### ISSUE TITLE
RenderToTexture stretches the image

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4479]
### Describe the bug

RenderToTexture stretches the output texture (looks like 8x horizontally)

used code:
`var itemTexture = Texture.CreateRenderTarget().WithWidth(256).WithHeight(256).Create();
Camera.RenderToTexture(itemTexture);`

Image the cam see: 
![image](https://github.com/Facepunch/sbox-issues/assets/9992453/fb94ec57-035c-4d66-8ca6-b2c10a1c5064)
And the image i get:
![image](https://github.com/Facepunch/sbox-issues/assets/9992453/6b663656-b1ea-450a-8d54-ed96db389204)

### To Reproduce

use this code:

var itemTexture = Texture.CreateRenderTarget().WithWidth(256).WithHeight(256).Create();
Camera.RenderToTexture(itemTexture);

the image you get will be stretched

### Expected behavior

the image you get by using Camera.RenderToTexture doesn't stretch

### Additional context

I output final image to the cube's ModelRenderer using `ModelRenderer.SceneObject.Attributes.Set("color",` itemTexture);`
with a dynamic expression set to 'color'

**Comment by aylaylay** [comment]
I've tried this and it's looking completely fine to me. If you're still getting this can you upload a complete repro showing it not working please. @GavrilovNI

**Comment by GavrilovNI** [comment]
@aylaylay yeah, im still getting this
here you are:
https://github.com/GavrilovNI/RenderToTexture/tree/main

https://github.com/Facepunch/sbox-issues/assets/9992453/fd9ed56f-64cf-4bf5-85da-2b865112e00c

**Comment by aylaylay** [comment]
Thanks for the repro, I'll check it out

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by GavrilovNI** [comment]
It is, Thanks!!
