### ISSUE TITLE
Get the current amplitude from Voice component

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4480]
### For?

S&Box

### What can't you do?

Animate a UI element based on the amplitude of the person talking. I can only get `voice.IsRecording` to see if their mic is being picked up.

### How would you like it to work?

`voice.Amplitude` returns a float

### What have you tried?

I tried using `voice.IsRecording` but that isn't exactly what I'm looking for

**Comment by aylaylay** [comment]
The plan is for this is to allow any sound to query the amplitude and spectrum

**Comment by aylaylay** [comment]
Added Voice.Amplitude

**Comment by garrynewman** [comment]
Are there any performance worries on having this enabled on every sound?

**Comment by aylaylay** [comment]
I don't see it being that big of a deal but considering it's not going to be used often, it probably should be opt in.
