### ISSUE TITLE
`Scene.FixedUpdateFrequency` and `Scene.NetworkFrequency` not synced between players

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#4483]
### Describe the bug

Hi,

I'm looking to get an overboosted game where all is running at 128 ticks.
So i decide to set my `Scene.FixedUpdateFrequency` and `Scene.NetworkFrequency`to 128f.
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/37b3a36e-c73d-4cbf-86ae-67afc3caaae3)

However, once the Network lobby started and the secondary user connected, i was surprised to see that properties were not synced between clients.

This causes several issues, like `Time.Delta` is different between clients: so every player has his own Time behaviors.

### To Reproduce

1) Change your `FixedUpdateFrequency` and `NetworkFrequency` Scene settings
2) Prints `Scene.FixedUpdateFrequency` and `Scene.NetworkFrequency`
3) Create a network lobby and join with a secondary user
4) Look at the result: the values are different from each other.

Host console :
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/4b4c4788-48d2-499b-a31f-b107102dca98)

Secondary user (keeping default scene settings value) :
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/d28845fb-7e50-4246-b3e5-3e01ffb115cc)

### Expected behavior

Scene settings must be synced between players

**Comment by garrynewman** [comment]
That's odd I would have thought they'd have got synced with the scene, will investigate

**Comment by PolSpock** [comment]
Your answer has created some doubt for me. So i have tried on the `network.scene` and see that there are no unsync Scene params between clients.

However, i forgot to mention something, i have loaded the scene through `GameManager.Active.Load( mySceneFile)` before doing my manipulation.

So i bring you another Steps to Reproduce to be sure to get the issue :
1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `NetworkSession.cs` with my shitty code :
```
using Sandbox.Network;

public static class Reload
{
	public static bool Reloaded;
}

public sealed class NetworkSession : Component
{
	protected override void OnAwake()
	{
		Reload.Reloaded = false;
	}

	protected override void OnStart()
	{

		//
		// Create a lobby if we're not connected
		//
		if ( !GameNetworkSystem.IsActive )
		{

			if ( !Reload.Reloaded )
			{
				SceneFile sceneGamemode = ResourceLibrary.GetAll<SceneFile>().FirstOrDefault( x => x.Id.Equals( Guid.Parse( "796dfacd-f635-42fe-ae65-41904e6b5f90" ) ) );
				GameManager.ActiveScene.Load( sceneGamemode );

				Reload.Reloaded = true;
			}

			GameNetworkSystem.CreateLobby();
		}

		if ( Scene is not null )
		{
			Log.Info( Scene.NetworkFrequency );
			Log.Info( Scene.FixedUpdateFrequency );
			Log.Info( Scene.Id );
		}


	}

}
```

3) Run `networking.scene`
4) Connect the secondary user
5) Look at the result on both consoles
