### ISSUE TITLE
Cloud.Model always returning an error.

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4485]
### Describe the bug

Cloud.Model is always returning an error model even if you manually mount the package.

### To Reproduce

What should work:
```cs
var model = Cloud.Model("facepunch.wooden_crate");
modelRenderer.Model = model;
```
This yield the following error:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/ff5545e8-2a50-41e2-8899-a07ce3b06f2d)

I also tried this weird hack which I expected to work but it did not:
```cs
var ident = "facepunch.wooden_crate"
var package = await Package.FetchAsync(ident, false);
await package.MountAsync();
var model = Model.Load(Cloud.Asset(package.FullIdent));
modelRenderer.Model = model;
```

### Expected behavior

Cloud models should load as intended

**Comment by CarsonKompon** [comment]
I just landed on this which seems to work. Would be nice if we could use Cloud.Model instead of having to do this :)
```cs
var ident = "facepunch.wooden_crate"
var package = await Package.FetchAsync(ident, false);
await package.MountAsync();
var model = Model.Load(package.GetMeta("PrimaryAsset", ""));
modelRenderer.Model = model;
```

**Comment by garrynewman** [comment]
This seems like it's working now?

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/faa55ae3-5079-4b70-a8d5-3df58ee8a922)

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/47cc9d55-f81d-47e0-90b3-1a59796b452d)
