### ISSUE TITLE
GameObject.BreakFromPrefab() takes to much time to run

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4486]
### Describe the bug

GameObject.BreakFromPrefab() sometimes takes to much time to run(up to 30ms and probably more)
looks like the more prefab is cloned the more time it takes
even with an empty prefab

### To Reproduce

clone prefabs few times as shown in video - it will take more time to run

used prefab:
just an empty object converted to prefab

used code:
```
using Sandbox;
using System.Diagnostics;

public class Test : Component
{
    [Property] public GameObject Prefab { get; set; }
    [Property] public int Count { get; set; } = 100;
    [Property] public bool Spawn { get; set; } = false;
    [Property] public int TotalSpawned => GameObject.Children.Count;

    protected override void OnUpdate()
    {
        if(Spawn)
        {
            Spawn = false;
            SpawnPrefab();
        }
    }

    public void SpawnPrefab()
    {
        for(int i = 0; i < Count; ++i)
        {
            Stopwatch stopwatch = new();
            stopwatch.Start();
            var pos = Vector3.Random * 69;

            Transform cloneTransform = new(Transform.Position + Vector3.One * 69, Transform.Rotation);
            var spawnedPrefab = Prefab.Clone(cloneTransform, GameObject, false, $"Test {pos}");
            Log.Info($"Time taken to clone prefab without breaking: {stopwatch.ElapsedMilliseconds}ms");
            spawnedPrefab.BreakFromPrefab();
            Log.Info($"Time taken to fully clone prefab: {stopwatch.ElapsedMilliseconds}ms");

            stopwatch.Stop();
        }
    }
}
```

### Expected behavior

GameObject.BreakFromPrefab() takes less time to run (like 0ms as first calls)

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/9992453/4b63c651-966d-4dab-8cb5-e96e7fb153f7

**Comment by handsomematt** [comment]
Undo/redo history gets filled each time you break, and it's filling up #4477

**Comment by GavrilovNI** [comment]
> Undo/redo history gets filled each time you break, and it's filling up #4477

I don't think it should be added to Undo/redo history as it's breaking via code.
It is the same as changing object's position via code and we dont put it into undo/redo history, don't we?

And hopefully it's not hapenning in a build
