### ISSUE TITLE
Ragdolls created with ModelPhysics (that arent citizen) exhibit weird morphing

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4487]
### Describe the bug

Non-citizen ragdolls looking rather fucked
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/687c387e-b7a1-4679-b8af-33b4ce7afdaa)

Citizen ragdolls looking quite sexy
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/fffb0983-b96b-407c-9378-4e1b97691079)

### To Reproduce

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/47eebce0-d3d2-47cf-b6bf-92f184e35aa6)

### Expected behavior

The ModelPhysics component itself is a bit jank, would love to have a solution like one mentioned a few days ago:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/76af76f4-9be1-45e7-889d-0453ee8bc6ff)

**Comment by aylaylay** [comment]
Provide a model/repro that does this please

**Comment by CarsonKompon** [comment]
I will make one but am currently blocked by https://github.com/Facepunch/sbox-issues/issues/4603

**Comment by aylaylay** [comment]
Can I get that model?

**Comment by CarsonKompon** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/8661768c-d18a-4aab-88f5-b20f560d4557)

Model: `azumangafans.shrek-ragdoll` (but it happening with about any model when you search "ragdoll" in models on asset party)
Repro project: [Ragdoll Repro.zip](https://github.com/Facepunch/sbox-issues/files/14125699/Ragdoll.Repro.zip)

**Comment by aylaylay** [comment]
fixed shrek thanks for repro 

https://github.com/Facepunch/sbox-issues/assets/1667289/23a1b4a5-1c1a-4077-b5b2-7e01f04f9f36
