### ISSUE TITLE
Add `string` support to `[Sync]`

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4488]
### For?

S&Box

### What can't you do?

Sync a string without jumping through hoops

### How would you like it to work?

```cs
[Sync] public string Status { get; set; } = "Chilling";
```

### What have you tried?

Tried using [Broadcast] calls to send a string over the network as a message and store it locally on each client but late joins do not get this replicated so you need a separate broadcast that requests the message on join and another broadcast that returns the message only to the requesting player.

You can also set the name of the GameObject and that usually syncs fine but you can obviously only do that once and it's a janky hack at best.

**Comment by kurozael** [comment]
Should be good now 👍
