### ISSUE TITLE
RigidBody.PhysicsBody.LocalMassCenter resets mass.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4490]
### Describe the bug

As the title suggests, changing the RigidBodies center of mass using Physicsbody.LocalMassCenter resets the previously set mass of this rigidbody.

### To Reproduce

1. Set the rigidbodies mass to something custom using RigidBody.PhysicsBody.Mass = 50.0f;
2. Set the center of mass to anything using RigidBody.PhysicsBody.LocalMassCenter = Vector3.Down * 5.0f;
3. Notice how the mass is reset to the default mass again.

### Expected behavior

Setting the LocalMassCenter should not modify the objects mass.

### Media/Files

<img width="642" alt="image" src="https://github.com/Facepunch/sbox-issues/assets/35051017/ae98d1e8-0ba2-4c7d-99c6-b78aaba1a8d9">

**Comment by aylaylay** [comment]
Should be fixed now
