### ISSUE TITLE
Add IsVr to Connection

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4493]
### For?

S&Box

### What can't you do?

Currently the way to check if a connecting player is using VR is very convoluted and you cannot see from the connection itself.

### How would you like it to work?

Add a variable to Connection for checking if the connecting user is in VR.

### What have you tried?

It's possible to do this by spawning an object on the net that will check if the owner is in vr when enabled, but it seems buggy and does not work for me personally.

**Comment by handsomematt** [comment]
Makes sense, maybe it's UserData though

**Comment by DevulTj** [comment]
I've added this to UserData, so for example using OnActive, you can check the player using VR by using `channel.GetUserData( "vr" )`, worth noting that currently GetUserData returns strings, so you'll have to convert to bool.
