### ISSUE TITLE
Scene camera jumps after mouse enter scene view

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4494]
### Describe the bug

Scene camera jumps after mouse enter scene view to last position saved by movement using WASD

### To Reproduce

Not sure but the following causes this bug at my end:
1. move cam by WASD in scene view
2. choose some object in hierarchy
3. move mouse to scene view
4. camera jumps to last position saved by movement using WASD

### Expected behavior

camera should remain position set by choosing an object in hierarchy

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/9992453/e730a3a0-3a97-40ff-92b9-931e9ed3eadd

**Comment by garrynewman** [comment]
Should be fixed now
