### ISSUE TITLE
TGAs aren't previewing in the asset inspector

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#4498]
### Describe the bug

Tga files show up fine in item view but they don't show up in the inspector preview.

### To Reproduce

1. Import a tga file
2. Inspect it in the inspector
3. Look at the preview

### Expected behavior

You should be able to see a preview of the tga file in the preview window.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/e4346a4b-104e-4d77-bb5e-02829a0ce0cb)
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/0e8d87d2-6c0f-4c46-b533-18ff855ba5ed)
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/fb8b2631-33a0-46d1-bbdb-afe5472aeba2)
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/3e4842ad-a066-4df2-89a1-747cc1d1dab9)

### Additional context

It seems to work fine for pngs and textures which have the tga applied, but it doesn't seem to work for tgas.

**Comment by aylaylay** [comment]
Done


https://github.com/Facepunch/sbox-issues/assets/1667289/039dfc45-bb57-4275-8c0f-14a6e0f25b81
