### ISSUE TITLE
Infinity multiplayer loading

### ISSUE THREAD

**Issue by 5FB5** [Facepunch/sbox-issues#450]
I tried to connect to sandbox server and game has started infinity loading. Idk how to reproduce it but this is my screenshot from console
![unknown](https://user-images.githubusercontent.com/15859698/124636369-22c6a500-de91-11eb-85f9-d94370308512.png)

**Comment by FlorianLeChat** [comment]
I experienced this issue 2 days ago, I even had a crash after a while (however, no crash dump file was created).
