### ISSUE TITLE
Project manager refuses to load the last accessed project if the editor cannot compile a tool addon

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4500]
### Describe the bug

I had a hammer addon that broke due to pretty obvious changes, before this would show the editor and just not let you do anything, now you can actually view the project manager, but you can't load the last accessed project.
This is not the case if you load any other project however, it loads just fine, it's just the last accessed project that gets fucked I guess.

### To Reproduce

1. Install a tool addon
2. load a project 😄 
3. Quit editor
4. Break it 😠 
5. Try and load the project you just accessed 😕 

### Expected behavior

S&box should ideally just let you load into that project and tell you that you have a fucked tool addon as one of those big red error messages, rather than hiding it in the log.

### Media/Files

`2024/01/16 18:55:03.3901	[Generic] Compile of 'retroeer.hammerplogin' Failed:`

`2024/01/16 18:55:33.1392	[GameMenu] Errors when loading 'Sandbox.Project'`
`2024/01/16 18:55:33.1392	[GameMenu] An exception happened when changing active game: Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.`
  ` at Editor.EditorUtility.Projects.ShowloadingErrors(Project project)`
  ` at Editor.EditorUtility.Projects.SetActiveGame(Project project, Action``2 onProgress, CancellationToken ct)`

**Comment by garrynewman** [comment]
Should be fixed next update
