### ISSUE TITLE
RigidBody component set custom mass.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4501]
### For?

S&Box

### What can't you do?

Currently mass is set automatically ( assuming based on size/phys mat? ). It would be nice to be able to set the mass of a rigidbody ( in my case I want a very specific number, 1000kg ).

You can set it through a script, but this can get annoying if you want to do this for many physics props in the scene.

### How would you like it to work?

The rigid body component currently exposes linear damping, angular damping etc. Another property/field for 'Mass' would have to be added.

### What have you tried?

I can change it through a script, so it's possible, but maybe overkill for just setting the mass?

**Comment by aylaylay** [comment]
Add Rigidbody.MassOverride
