### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by KaanSacma** [Facepunch/sbox-issues#4502]
### Describe the bug

So if someone creates a lobby without a Network Session component and someone else tries to join it, it joins and disconnects it from the host and creates the lobby as a local host with an error: Object reference not set to an instance of an object

This is the output of someone joining the lobby:
<img width="647" alt="Screenshot 2024-01-16 at 15 20 48" src="https://github.com/Facepunch/sbox-issues/assets/91870254/a6e35660-a94c-4d12-adf0-b0484875faff">

This is the output of someone hosting the lobby:
![LobbyHost](https://github.com/Facepunch/sbox-issues/assets/91870254/7c06baa4-1eab-4631-a37f-64534593e52a)

### To Reproduce

**In Scene**
1. Add GameNetworkManager as a component (check on Media/Files).
2. If Network Session is activated then deactivate it.

**Host**
1. Create a Lobby with the GameNetworkSystem.

**Client**
1. Join the Lobby with the GameNetworkSystem.

### Expected behavior

It should join the host without disconnecting and be together in the same lobby.

### Media/Files

This is the GameNetworkManager in the code:
<img width="753" alt="Screenshot 2024-01-17 at 11 09 00" src="https://github.com/Facepunch/sbox-issues/assets/91870254/3cafd66b-87f0-444d-afe5-24ea55cdcd5c">

This is the component of GameNetworkManager in the scene:
<img width="348" alt="Screenshot 2024-01-17 at 11 13 27" src="https://github.com/Facepunch/sbox-issues/assets/91870254/1bfbd6f5-ba50-4aae-8028-bdd157cbf47a">

This is the Network Session in the code:
<img width="307" alt="Screenshot 2024-01-16 at 10 58 10" src="https://github.com/Facepunch/sbox-issues/assets/91870254/dc025305-66c5-4f21-a636-f8a900be2781">

This is the component of the Network Session deactivated in the scene:
<img width="348" alt="Screenshot 2024-01-17 at 11 19 37" src="https://github.com/Facepunch/sbox-issues/assets/91870254/690b985c-36a4-4f64-a6c6-c2a3999cefb8">

**Comment by badandbest** [comment]
Didn't you already make this issue?

**Comment by KaanSacma** [comment]
Sorry I forgot to send this image, we are using this function to create and connect to the lobby:
<img width="457" alt="Screenshot 2024-01-17 at 15 20 29" src="https://github.com/Facepunch/sbox-issues/assets/91870254/ef0165e7-a825-4347-86ff-9e89365619da">

Yes I already made an issue about it but Garry told me to make another issue because I was talking about 2 issues in 1.
