### ISSUE TITLE
GameObject with 90 degree pitch rotation distorts after being set in editor

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4505]
### Describe the bug

Saving, closing, and re-opening a scene modifies the rotation of a GameObject when pitch equals 90.

Before:
![image](https://github.com/Facepunch/sbox-issues/assets/33941498/c0eaed4c-31e5-4b7d-ace2-622ea85eabbc)

After:
![image](https://github.com/Facepunch/sbox-issues/assets/33941498/663fe500-b14c-421e-bc59-85b1f8e7a497)

### To Reproduce

1. Rotate a GameObject to 90 degrees pitch
2. Save, close, and re-open the scene

### Expected behavior

Rotation shouldn't change itself after being set

### Additional context

Also happens when deselecting the GameObject and selecting it again.
Possibly related to #2863

**Comment by garrynewman** [comment]
This is a byproduct of converting from euler angles to quaternions internally. There's not a lot we can do since it's technically correct.

**Comment by handsomematt** [comment]
We weren't handling singularities properly in Rotation.Angles() and a lack of precision with deg<->rad was causing this.

It should work as expected now.
