### ISSUE TITLE
Ability to Delete Folder

### ISSUE THREAD

**Issue by portalmaster137** [Facepunch/sbox-issues#4508]
### For?

S&Box

### What can't you do?

Let us delete a folder in the editor damnit.

### How would you like it to work?

Right Click Folder -> Delete Folder.

It deletes the folder.

:)

### What have you tried?

I Gotta alt tab to an explorer, and i have like 20 open so its always a pain. Please, let us delete the folders in the editor :(

### Additional context

I'm being serious, this is a (mostly) serios issue.

Thx. :)

**Comment by DevulTj** [comment]
Added
