### ISSUE TITLE
[Sync] For Lists

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4510]
### For?

S&Box

### What can't you do?

`[Sync]` supports value types (and strings) so far, but it seems there is currently no support for collections/arrays like List etc 

### How would you like it to work?

Just like you'd expect I guess

```
[Sync] public List<int> SomeNumbers { get; set; }
```

Whether it's List or an array or something entirely custom it doesn't really matter, so long as it can network collections of value types (and strings)

There were issues previously where people would replace the list without realising, causing it to break. Might be worth seeing if there is a way to prevent that

### What have you tried?

You can send JSON over the network and then convert that back to a list with INetworkSerializable, but that says that it's being deprecated

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/7bbdd9b1-ff60-428e-ab16-1447996fc62d)

**Comment by dch-GH** [comment]
Dictionaries as well would be nice. Or some other way to network collections/data structures now that INetworkSerializable is defunct.

**Comment by garrynewman** [comment]
You should be able to sync lists now - I haven't tested it but in theory it should work.

**Comment by anthonysharpy** [comment]
cool i will try and test this soon

**Comment by anthonysharpy** [comment]
s@box a little bit broken for me at the moment so can't test this just yet. but will let you know if there's any issues 😄
