### ISSUE TITLE
Loading screen gets stuck, cancel button passes clicks to whatever is behind itself

### ISSUE THREAD

**Issue by James76931** [Facepunch/sbox-issues#4513]
### Describe the bug

Sometimes when opening games the loading page gets stuck. When pressing the Cancel button, the button seems to act as though it doesn't exist and clicks press through to whatever content is behind it. In this video demo, the cancel button ends up making me click a game on the main menu and start launching it.

https://github.com/Facepunch/sbox-issues/assets/15969024/45b86320-4d98-4c83-9f85-dce606233ace

### To Reproduce

1. Sometimes games won't load properly. I honestly have no idea what causes this.
2. When this does eventually happen, try pressing cancel on the stuck loading screen.
3. After usually one click (...but in the demo video it took a few of them...), whatever content is behind the loading screen ends up getting clicked on.

### Expected behavior

The loading sequence should be cancelled and the user returns to the main menu/wherever they were before the loading begun.

### Additional context

Windows 11 23H2 (build 22631.3007), AMD Ryzen 9 3900x, NVIDIA RTX 2080 Super, 16GBs RAM

**Comment by handsomematt** [comment]
Fixed stuck
