### ISSUE TITLE
S&box hard crashes when disabling a GameObject with a Map Instance component

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4518]
### Describe the bug

Game hard crashes with this log: [Log.log](https://github.com/Facepunch/sbox-issues/files/13991231/Log.log)

### To Reproduce

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/9382c7c5-bcc8-4343-a6ff-73ba495d9b84)

### Expected behavior

The map should disappear, similarly to how it works when you disable the Map Instance component (which does work):
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/ea46e9c7-09d3-4438-ad87-61ef84a2fe12)

**Comment by garrynewman** [comment]
Does the map have a 3d skybox? Has this started happening in the last few days?

**Comment by CarsonKompon** [comment]
> Does the map have a 3d skybox? Has this started happening in the last few days?

The map has a 3d skybox. Honestly not sure if it started recently because I don't think i've tried doing it before today.

**Comment by MrBrax** [comment]
this is very recent, it happened to me yesterday. worked fine a week ago or more

**Comment by handsomematt** [comment]
Probably my 3d skyboxes, I'll get to the bottom of it

**Comment by handsomematt** [comment]
I can't get this to happen anymore, let me know if it's fine for you.

**Comment by MrBrax** [comment]
crashes for me when enabling the gameobject again but on this pc i have a 2gb gtx 770 so it might just be an oom ctd

**Comment by handsomematt** [comment]
that is certainly a low amount, I suppose I can check if you have a log file, mdmp files, steamid64

in the meanwhile, does it work okay for you @CarsonKompon with a normal amount of vram

**Comment by MrBrax** [comment]
even on my 8gb vram machine it still crashes to desktop when re-enabling it, so unfortunately not fixed

**Comment by handsomematt** [comment]
what map are you testing with

**Comment by MrBrax** [comment]
https://asset.party/brax/newcity2

could it be too heavy?

**Comment by handsomematt** [comment]
that was hard to find, it kept crashing my debugger - should be flawless now

**Comment by MrBrax** [comment]
nice, works now.
