### ISSUE TITLE
Some odd behaviours with Map Instances and 3D Skyboxes

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4519]
### Describe the bug

1. Creating a Map Instance and entering a map with a 3D Skybox will create both the map and the skybox, but disabling the Map Instance component will not hide the Skybox. Neither does deleting the Map Instance GameObject (until you save the scene, close it, and re-open it)

https://github.com/Facepunch/sbox-issues/assets/5159369/84baf64a-fa20-47c9-b74b-2fafa13c75b7

2. Creating a Map Instance and entering a map with a 3D Skybox will create both the map and the skybox. If you disable the Map Instance component and then save the scene, close it, and re-open it... Both the map and the skybox will be created despite the Map Instance component remaining disabled

https://github.com/Facepunch/sbox-issues/assets/5159369/2fca077c-9180-4821-a697-418c78bda3ab

3. The 3D Skybox of a Map renders underneath the map's geometry. This may be intentional (for optimization purposes, since you are never meant to be *in* a skybox) but I thought i would bring it up regardless

https://github.com/Facepunch/sbox-issues/assets/5159369/1cffed94-d216-4dab-a485-e887b742476f

### To Reproduce

See videos above

### Expected behavior

These things should not happen (except maybe the 3rd one)

**Comment by handsomematt** [comment]
1/2 should be fixed now. 3 is intentional yeah.
