### ISSUE TITLE
Component Class Name Generation Adds Whitespace

### ISSUE THREAD

**Issue by gidgeesheep** [Facepunch/sbox-issues#4527]
### Describe the bug

When creating a new component attached to a gameobject, if there is whitespace, the class name is also given whitespace. Not detrimental, but annoying.

### To Reproduce

1. Add a component, choose new component, the add a space into it
<img width="386" alt="Screenshot 2024-01-19 173136" src="https://github.com/Facepunch/sbox-issues/assets/55063683/6dd97df7-f1d6-4130-8f24-b02a21732e72">

2. Save the file
<img width="557" alt="Screenshot 2024-01-19 173203" src="https://github.com/Facepunch/sbox-issues/assets/55063683/96cffc69-fc49-40a2-b6d8-a3dabe1b7ed1">

3. Check the Class Name
<img width="531" alt="Screenshot 2024-01-19 173233" src="https://github.com/Facepunch/sbox-issues/assets/55063683/2262276e-416d-404e-aa60-03714a1bef8d">

### Expected behavior

The whitespace in a name should be ignored, or an underscore should replace the space. Maybe toggle-able?

**Comment by aylaylay** [comment]
Title cased and whitespace removed now
