### ISSUE TITLE
Remove PropertyAttribute.FGDType, PropertyAttribute.Hammer

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#453]
Since these properties are used on other classes (not just entities) we should find another way to set and store these.

Maybe we make Hammer.PropertyAttribute? Could be derived from PropertyAttribute so we don't have multiple properties?

**Comment by robotboy655** [comment]
Ended up doing the following:
* Obsolete `PropertyAttribute.FGDType` & `PropertyAttribute.Hammer` in favor of `FGDTypeAttribute` and `Hammer.SkipAttribute`
* `ResourceTypeAttribute` and `BitFlagsAttribute` now derive from `FGDTypeAttribute`
