### ISSUE TITLE
Animgraph - Treadmill is fucked up

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#4530]
### Describe the bug

https://i.gyazo.com/1903fff8319eab71b2481ce018600779.mp4

### To Reproduce

Play an animation with ExtractMotion in Animgraph.

### Expected behavior

It should work as usual.

**Comment by handsomematt** [comment]
Can you explain this better? I can't see the problem.

**Comment by garrynewman** [comment]
Is it the ground grid movement?

**Comment by KaesarZZ** [comment]
Yeah, the grid movement isn't working. I've used "Treadmill" because that is how it is called in ModelDoc.

**Comment by aylaylay** [comment]
Should work now

**Comment by KaesarZZ** [comment]
Fixed 👍
