### ISSUE TITLE
Built in CharacterController functionality

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4531]
Right now the character controller's built in functionality is

* Movement
* Collision
* Sliding
* Grounding
* Stepping

Because the character controller could be used for things like NPCs we don't offer any built in input, or move modes. Which I think is the correct thing to do.

There is perhaps other functionality that could be built in, but with a toggle.

## Ground Velocity

If you're standing on an object and the object moves, you should move with it. This would make moving platforms and elevators really easy to implement. 

## Pushing

Some objects should have the ability to push the character controllers. This was a really nice thing to have built into Source, which I think we probably lost in the transition.

## Crushing

We should be able to respond to crush forces from these pushers. If you're underneath an elevator and it goes down, it shouldn't clip through you; there should be some kind of negotiation there where it's decided whether you get crushed and die or the elevator stops moving.

# Implementation

We should consider what's going to push, and what's going to be pushed. 

Is the pusher a special component, or could it be a part of all keyframe colliders?

Is the ability to be pushed something that's built into the CharacterController, is it its own component, is it an interface that CharacterController implements. What defines the bounds that the controller is able to push? Is it something that the controller queries to respond to, or is it something the pusher triggers.

**Comment by Fortune117** [comment]
I'd like there to be some way for character controllers to collide with one another. It's a bit hacky to work around it right now.
