### ISSUE TITLE
Bone proxies don't respect parent transformations

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4533]
### Describe the bug

I'm trying to animate a slingshot model via code by setting the bone proxy objects for direct manipulation of the mesh, but the bones only seem to care about local changes as opposed to the proxy's worldspace position as dictated by their parent

### To Reproduce

https://github.com/Facepunch/sbox-issues/assets/11138884/b27bac28-9382-465f-8c03-a0fa27c605ad

### Expected behavior

https://github.com/Facepunch/sbox-issues/assets/11138884/816648bd-1ab3-4112-8679-424530f31d92

**Comment by garrynewman** [comment]
Any chance you could make a small repo project for me, so I can verify that my changes worked?

**Comment by ShadowBrian** [comment]
Will put something together tomorrow!

**Comment by ShadowBrian** [comment]
This works as expected now, closing
