### ISSUE TITLE
HighlightOutline does not respect non-uniform scaling

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4535]
### Describe the bug

HighlightOutline seems to only change based on the X component of a GameObject's scale

### To Reproduce

1. Create a GameObject with a model and HighlightOutline
2. Change the various components of Local Scale on the GameObject
3. Observe that only the X component has any effect.

### Expected behavior

The highlight effect should scale in all axes to match the scale of the GameObject

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/8889285/adf07420-2508-4510-bc32-d55c0d271943

**Comment by handsomematt** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/1388267/8dd1cddb-5a67-421e-bef4-8cb81e857851)
