### ISSUE TITLE
Fixed Joint component in Scene Editor is broken/partially implemented

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4538]
### Describe the bug

Adding a Fixed Joint component to a physics object within the scene editor and plugging in the other object does not respect the initial offset and instead teleports one to the other.

### To Reproduce

1. Add the Fixed Joint component to a GameObject with a RigidBody.
2. Plug in another physics object.

### Expected behavior

It should respect the initial offset so that things are fixed together as they were and not always inside of each other.

### Additional context

Would make messing around in the scene editor even more fun.

**Comment by aylaylay** [comment]
Should be fixed now
