### ISSUE TITLE
Destroying a Trigger upon entering it hard crashes your game

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4543]
### Describe the bug

SteamID: 76561198414744723

No logs for this one, hopefully Sentry was able to pick something up (Crashed at around 10:40pm EST on 20/1/24)

As you would expect, Destroying the GameObject that has the trigger component hard crashes the game.

```
using Microsoft.VisualBasic;
using Sandbox;

public sealed class TriggerTest : Component, Component.ITriggerListener
{



	void ITriggerListener.OnTriggerEnter(Collider other)
	{	
		//This just makes it so you can visibly confirm its the entry of a collider that makes the game crash
		if(other.GameObject.Tags.Has("player"))
		{
			GameObject.Destroy();
		}
	}

	void ITriggerListener.OnTriggerExit(Collider other)
	{

	}
	
}
```

### To Reproduce

1. Create a GameObject with a Collider tick "Is Trigger" blah blah blah you know how to set one up
2. Attempt to GameObject.Destroy(); it via the OnEnter method
3. goodnight sweet prince.

### Expected behavior

Game should *probably* not be hard crashing with no logs on why.
If Destroying the GameObject this way isn't intended, I'm sure there's *probablyyyy* something more graceful. (And if there is a better way, do let me know)

**Comment by garrynewman** [comment]
Seems to be fixed now?

**Comment by aylaylay** [comment]
Might have been fixed, there was a similar issue and I didn't see this one.
