### ISSUE TITLE
Allow BoxCollider Size and Center to be adjusted with bounding box controls in scene editor

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4545]
### For?

S&Box

### What can't you do?

In the scene editor, I cannot click and drag on arrows to define the edges of a box collider.

### How would you like it to work?

The Box Collider component should have a button to enter a mode where the bounds of the collider are editable via some gizmo that would appear in the scene view. It should behave similarly to existing bounding box controls in Hammer, pictured below. Adjustments to the sides of the bounding box should respect grid snapping.

### What have you tried?

Manually typing in values for bounding box size. Doing math in my head to figure out the Size and Center values that I want.

### Additional context

![image](https://github.com/Facepunch/sbox-issues/assets/8889285/f3069999-58cb-4c44-8ea1-287e6def2ca6)

**Comment by KETALss** [comment]
Would be nice to have it also snap to grid/vertex
