### ISSUE TITLE
SceneModel.GetAttachment Returning Incorrect Values

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-issues#4546]
### Describe the bug

GetAttachment seems to return completely incorrect values whether `worldSpace` is true or not.

### To Reproduce

1. Create a SceneModel or GameObject with SkinnedModelRenderer and use the model `https://asset.party/facepunch/w_mp5`
2. Attach a component that logs the position of `ModelRenderer.GetAttachment( "muzzle", true or false )` or draw a gizmo at the position
3. Observe the position is wrong

In my case the GameObject with the `SkinnedModelRenderer` is a child of another GameObject, if that makes any difference.

### Expected behavior

The position should be correct whether `worldSpace` is true or false.

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by kurozael** [comment]
All working now! Thanks @aylaylay 👍
