### ISSUE TITLE
Collision matrix tag entry is more restrictive than GameObject tag entry

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4548]
### Describe the bug

The entry validation for collision matrix tags varies heavily from GameObject tags.

### To Reproduce

Give a GameObject some weird tags. Try to enter them into the collision matrix editor.

### Expected behavior

Input validation for these entry fields, and anywhere else that tags can be typed, should be identical.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/33941498/f89cadc5-a845-428d-99dc-977e3107f6dd)
Some examples of weird GameObject tags that are "allowed", but not possible in the collision matrix editor.

**Comment by Gmod4phun** [comment]
Also came across this, the collision matrix editor restricts us from using any special characters or numbers, not even underscores. Looks like only a-z is allowed.

**Comment by Gmod4phun** [comment]
Seems like it is
