### ISSUE TITLE
Trigger collider default behavior is incorrect

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4549]
### Describe the bug

Trigger colliders will have interaction on by default, even when their collision matrix tag specifies a default of no interaction.

### To Reproduce

1. Clone [this project](https://github.com/Willco2/TriggerTagBug)
2. Play the default scene
3. One of the pairs of cubes triggers, while the other does not

### Expected behavior

Neither pair of cubes should be triggering.
![image](https://github.com/Facepunch/sbox-issues/assets/33941498/37cdbc20-21a1-432c-916c-757581a0f842)

Since the red/blue pair is explicitly set to ignore, it works as expected and doesn't trigger.
The green/yellow pair shouldn't trigger, according to their default behavior, but they do.

**Comment by aylaylay** [comment]
Defaults should now be respected, although having trigger is the collision rules seems confusing to me now we set trigger on the shapes.
