### ISSUE TITLE
Prefabs dont deserialize Lists of GameObjects/Components correctly

### ISSUE THREAD

**Issue by qualitykk** [Facepunch/sbox-issues#4550]
### Describe the bug

When trying to make a prefab with components that contain list of GameObject/Component references, those lists will break once the prefab is placed into a scene.

### To Reproduce

1. Create a component which has a List of references to GameObjects or Components like this:

```cs
public class Repro : Component
{
	[Property] public List<GameObject> OtherObjects { get; set; }
	[Property] public List<Collider> OtherComponents { get; set; }
}
```

2. Create a prefab using this component, with the list of references created
![image](https://github.com/Facepunch/sbox-issues/assets/57487634/244b7edd-56c0-48a2-94cb-89e6f8a2b84a)

3. Place prefab in a scene

4. Observe warnings in the console and missing references 
![image](https://github.com/Facepunch/sbox-issues/assets/57487634/bc80aa45-68f3-44e4-8bc0-69965a0527bc)
![image](https://github.com/Facepunch/sbox-issues/assets/57487634/97fef578-3fbe-4f60-a88a-4e6aa906bcaf)

### Expected behavior

The object references should carry over from the prefab.

**Comment by garrynewman** [comment]
Give that a go

**Comment by qualitykk** [comment]
This is fixed now, thanks 👍🏻
