### ISSUE TITLE
Capsule collider fires OnTriggerEnter/Exit 3 times instead of 1

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4552]
### Describe the bug

Passing a capsule collider into a box collider trigger causes 3 separate OnTriggerEnter/Exit pairs to be called in succession.

### To Reproduce

1. Clone [this project](https://github.com/Willco2/TriggerCapsuleBug)
2. Play the default scene
3. Watch the console to see when OnTriggerEnter/Exit is called

### Expected behavior

Only one pair of OnTriggerEnter/Exit messages should appear when the capsule collider passes through the trigger.

### Media/Files

The console output from passing the capsule through a trigger once:

![image](https://github.com/Facepunch/sbox-issues/assets/33941498/f6c41ffa-103a-43ec-b36f-5607ee8756d9)

### Additional context

This issue doesn't happen with any other pairing of collider shapes, only with capsule ↔ box.

**Comment by aylaylay** [comment]
Thanks for the repro, I'll look into it

**Comment by Gmod4phun** [comment]
Could it be related to #4419 ? If the capsule consists of 3 shapes - middle, and the ends, that would explain it.

**Comment by aylaylay** [comment]
no

**Comment by aylaylay** [comment]
This shouldn't happen anymore
