### ISSUE TITLE
Scene camera sometimes uses wrong background color

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4553]
### Describe the bug

Scene camera not always uses background color of the most prioritized game camera

P.S. i'm not sure if it even should use background color of game camera

### To Reproduce

1. add 2 cameras
2. change background color on both
3. find which camera does not change background color in scene view -> increase it's priority
4. scene camera still uses background color of another(less prioritized) cam

### Expected behavior

Scene camera uses background color of the most prioritized game camera

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/9992453/0431b7c0-88bd-4e8c-b7bc-b0073cdbdbcf)
![image](https://github.com/Facepunch/sbox-issues/assets/9992453/2156a222-4b27-452e-9d43-eba50f4a1696)

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by GavrilovNI** [comment]
> Should be fixed now

doesn't seem so

https://github.com/Facepunch/sbox-issues/assets/9992453/180abaf8-f189-4d4b-bd22-ce571b4b0750

**Comment by garrynewman** [comment]
You should only have one main camera
