### ISSUE TITLE
Attribute to specify file type(s) for string Property

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4555]
### For?

S&Box

### What can't you do?

I want to be able to drag a png or jpg file into the inspector of my component without having to create a vtex since I only want the file path.

### How would you like it to work?

```cs
[Property, FileType("png", "jpg", "jpeg")] string MyFile { get; set; }
```

### What have you tried?

I tried using `[Property, ResourceType("png")]` since `[ResourceType("vmat")]` works in a GameResource but it didn't work when used on a Property.

**Comment by chrisspieler** [comment]
This would also be useful for a video player component that has an MP4 file path property.

**Comment by garrynewman** [comment]
We need a better way to handle this. They should really be usable as assets, so you would do Texture instead of string.
