### ISSUE TITLE
Can't upload big file to asset.party

### ISSUE THREAD

**Issue by AfteraOfficiel** [Facepunch/sbox-issues#4559]
### Describe the bug

Hello,

We can't upload big file to asset.party, for example, a .vpk ( map 354 MB ), after few minutes we have a timeout and a error : GameMenu Backend error - returned 524

![image](https://github.com/Facepunch/sbox-issues/assets/99672629/c2bb2145-592b-4b35-bfe7-adbb1f149057)

### To Reproduce

1 : Upload big file on asset party ( maybe 150mb ? ) 
2 : See you can't upload

### Expected behavior

We need to upload big file on asset party

**Comment by garrynewman** [comment]
Did a bunch of work on this today - should be a LOT better

**Comment by AfteraOfficiel** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/99672629/27a27df5-fe54-434f-ba29-bd88ba275b66)

![image](https://github.com/Facepunch/sbox-issues/assets/99672629/278b9e46-878d-4cea-a8a0-56d593b3be0d)

The source files (.vmat , .vmap, .scene ) are now in the pending upload, I think there is a problem

**Comment by garrynewman** [comment]
Yeah that's weird - I didn't change any of that.

**Comment by AfteraOfficiel** [comment]
> Yeah that's weird - I didn't change any of that.

Humm ok because other gamemode upload today all their source file like https://asset.party/based/bydrive/version/45339 or
https://asset.party/vidya/heli-chan/version/45337
