### ISSUE TITLE
Sandbox.Websocket - Add Headers

### ISSUE THREAD

**Issue by victiondev** [Facepunch/sbox-issues#456]
**What can't you do?**
Add headers to the `Sandbox.WebSocket` client

**How would you like it to work?**
It would be useful for there to be a function similar to `AddSubProtocol` on the class.

**What have you tried?**
N/A

**Additional context**

The function for adding a header would be `this._socket.Options.SetRequestHeader(key, value);`

**Comment by Rohansi** [comment]
Any specific reasons to allow specifying headers?

**Comment by Yomanz** [comment]
> 
> 
> Any specific reasons to allow specifying headers?

Headers are crucial to most web services, mainly for giving authentication.

**Comment by birdbrainswagtrain** [comment]
> Headers are crucial to most web services, mainly for giving authentication.

Sure, but you should probably be careful about this kind of thing. If you're allowed to edit arbitrary headers, you might be able to bypass . The fetch API is [kinda restrictive](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) about what headers you're allowed to modify, and restricts you to the same origin for a lot of modifications.

I almost feel like sbox websockets should only function if a specific response header is present, to prevent any weird fuckery with services that don't want you messing with them. Same business with a HTTP API if it ever gets added.

**Comment by Yomanz** [comment]
> 
> 
> > Headers are crucial to most web services, mainly for giving authentication.
> 
> Sure, but you should probably be careful about this kind of thing. If you're allowed to edit arbitrary headers, you might be able to bypass some security measures. The fetch API is [kinda restrictive](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) about what headers you're allowed to modify, and restricts you to the same origin for a lot of modifications.
> 
> I almost feel like sbox websockets should only function if a specific response header is present, to prevent any weird fuckery with services that don't want you messing with them. Same business with a HTTP API if it ever gets added.

I'm not really sure how this changes the fact that headers are still a crucial part of most APIs.
I'd expect the internal WebSocket client provided within C# to restrict setting these, and if not it can just be added within s&box.

> I almost feel like sbox websockets should only function if a specific response header is present, to prevent any weird fuckery with services that don't want you messing with them. Same business with a HTTP API if it ever gets added.

A response header specific to s&box?

**Comment by TheBerkin** [comment]
> I almost feel like sbox websockets should only function if a specific response header is present, to prevent any weird fuckery with services that don't want you messing with them. Same business with a HTTP API if it ever gets added.

If someone doesn't want their **public** API used a certain way, I feel like it's the API owner's responsibility to control access. I don't see why we need to solve this by making things harder for everyone else.

**Comment by birdbrainswagtrain** [comment]
The **entire issue** here is that setting arbitrary headers can break some access controls.

OWASP says:

> When implementing servers, check the Origin: header in the Websockets handshake. Though it might be spoofed outside a browser, browsers always add the Origin of the page that initiated the Websockets connection.

And sure, you shouldn't exclusively rely on this, but when you're shipping software that implements web APIs it's responsible to not totally break systems people rely on for security.

If you want to assume the library handles it, fine. I'm just bringing this up, because it probably doesn't.

**Comment by thegrb93** [comment]
The question is, can a mod use this to control a user's pc to perform illegal activity? If the answer is ever yes, then you can bet it will be abused.

**Comment by Yomanz** [comment]
> 
> 
> The question is, can a mod use this to control a user's pc to perform illegal activity? If the answer is ever yes, then you can bet it will be abused.

What

**Comment by thegrb93** [comment]
I wonder what nefarious stuff you can do with a cookie

**Comment by Yomanz** [comment]
sheesh yea I do wonder

**Comment by GGG-KILLER** [comment]
Cookies are sent through headers.

**Comment by Yomanz** [comment]
Realistically, whatever the implementation on s&box's side filters doesn't really matter to 99% of people; most people are going to be sending custom `X-` headers or a simple `Authorization` header, base header modifyability like cookies etc,. are just a bonus, but it's really not within the scope of this incredibly basic request for a crucial feature.

**Comment by GGG-KILLER** [comment]
The issue is that we need to prevent people from abusing the ability to set headers, not what the original request was about.

**Comment by Rohansi** [comment]
There's no security concern with allowing headers - client-side security isn't a real thing. Access controls are a browser concept which wouldn't apply to S&box. There is no such thing as "header abuse".

I think we can allow anything except a few on [this list](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name). Plus we'd take control over things like User-Agent, Referer, Origin, etc. to allow hosts to identify where the connections are coming from.

Request headers make sense. I don't think we'll need *response* headers though - not with WebSocket.

**Comment by GGG-KILLER** [comment]
I'm not against setting headers in requests, I'm just against indiscriminately allowing any header to be set.
I think that list should be a good starting point though.

**Comment by GGG-KILLER** [comment]
Also, for what it's worth, browsers' websockets API do authorization with URI arguments and doesn't allows any headers to be set: https://stackoverflow.com/a/41521871
```js
var ws = new WebSocket("ws://username:password@example.com/service");
// or
var ws = new WebSocket("ws://my_token@example.com/service");
```
which then generates a Basic Authentication `Authorization` HTTP header.
So that list wasn't really designed for use with websockets.

**Comment by Rohansi** [comment]
>browsers' websockets API do authorization with URI arguments and don't allows any headers to be set

This is not supported everywhere anymore. This means the only way to do it in browsers is cookies or over the WebSocket itself. This means we'd need to allow setting the cookie header too. :)

>Microsoft's own WebSockets API also doesn't allow any headers to be set apparently

It does, through ClientWebSocketOptions.SetRequestHeader.

**Comment by GGG-KILLER** [comment]
> This is not supported everywhere anymore. This means the only way to do it in browsers is cookies or over the WebSocket itself. This means we'd need to allow setting the cookie header too. :)

Yes, which pretty much means most websocket servers aren't going to react well to being sent headers (as websockets is primarily a browser communication method).
Maybe a different API for this would be better than just blindly allowing headers to be set.

**Comment by Rohansi** [comment]
> Maybe a different API for this would be better than just blindly allowing headers to be set.

I'm already going to add request header support. It's standard and WebSocket isn't only used for communication from browsers.

**Comment by Yomanz** [comment]
Any update on this?

**Comment by victiondev** [comment]
@Rohansi is there any updates on this yet? was kinda hoping it wouldnt take nearly 4 months for this to go anywhere...

**Comment by Yomanz** [comment]
@Rohansi Any updates?

**Comment by Rohansi** [comment]
@victiondev @Yomanz Sorry for the delay - was busy with non-S&box things. Just submitted a PR adding this in so should be available soon.

**Comment by Yomanz** [comment]
> @victiondev @Yomanz Sorry for the delay - was busy with non-S&box things. Just submitted a PR adding this in so should be available soon.

Looking forward to it.

**Comment by Rohansi** [comment]
This feature was added a few days ago - you can now specify headers when connecting to the WebSocket.
