### ISSUE TITLE
Never network certain objects/components.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4561]
### For?

S&Box

### What can't you do?

Right now it seems that upon connection, a client will receive every gameobject + components, even if those components are not set to be networked. This makes it hard to spawn local-only components on the server.

Example: 
Initially I had a camera in the scene. When a player received a pawn I would attach a screen panel to said camera to be used as a hud. The issue was that late-joining clients would have 2 screen panel components ( one synced from when server created one, and one they created on their own ). This was all done with the !IsProxy etc ofc.

### How would you like it to work?

Whether a component automatically gets spawned on new connections should be configurable.

### What have you tried?

My attempted solution was to not have a camera initially in the scene, but rather spawn one whenever a player received a pawn. This worked until I realized now I would have 2 cameras on late-joining clients ( one from server and of their own ).

The only 'real' solution is to destroy all existing cameras, then spawn your own, but this feels weird.

**Comment by badandbest** [comment]
I agree. We should also be able to whitelist objects from being destroyed when the owner disconnects.

**Comment by osmanlodzero** [comment]
Yeah wanted to make another issue for that, but forgot. At the moment when a player leaves it takes everything with them.

**Comment by Matt9440** [comment]
Garry added `GameObjectFlags.NotNetworked` recently

**Comment by garrynewman** [comment]
GameObjectFlags.NotNetworked should allow you to prevent GameObjects from networking

**Comment by osmanlodzero** [comment]
Nice one, so its for the full game object, I can see needing a per component based one, but will make a specific issue once I need it.

( Off the top: having a networked object that the local player attaches a component on temporarily, such as a ‘target’ component on a replicated pawn that only works per client ). Theres ways to work around it ( instead if a component use a game object as child, but I can see it being useful nonetheless) )

For now this is great, thanks!

**Comment by Guilhem-Pech** [comment]
Kind of related to this issue but it would be nice to flag some property as "non-networkable"? - Prevent them from being transmitted in the snapshot?

For example, things UI related (like preferences or runtime selection) that I put in properties get replicated and I don't want that.

The workaround "Not flagging them as property" works most of the time but I often use the inspector as a debug view for runtime values :(
