### ISSUE TITLE
Scene window inputs lagging behind after tabbing out while moving

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4562]
### Describe the bug

Sometimes the scene window inputs will get screwed up after tabbing in/out, especially while moving around in the scene view. Some issues I've observed:
1. After moving full speed and then tabbing out, the scene window won't continue updating until moused over. Once moused over, moving starts again.
2. Sometimes after tabbing out and back in, clicking and attempting to move in the scene view won't work. After unfocusing the scene window, it will move as if all the inputs were buffered. Problem persists until tabbed out and in again.

### To Reproduce

1. Open scene window
2. Fuck around with tabbing in and out
3. Fuck around with movement, mouse hover, etc
4. Hope to observe said issue

### Expected behavior

The scene window should process inputs normally

**Comment by GavrilovNI** [comment]
probably related to #4494
