### ISSUE TITLE
Certain files are not loading from Content projects

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4565]
### Describe the bug

Videos inside of content projects don't seem to get loaded by the game. Other assets like models, materials, shaders, particles, even fonts do work, but video does not. When copying the video into the game project, it has no problem loading from there.

### To Reproduce

1. Make a content project with a video file in it
2. Try to access the video (either VideoPlayer, or loop through the FileSystem to see its not listed)

### Expected behavior

Video files should be loaded from content projects fine

### Media/Files

Showcase of the video in content project not being loaded, but loads fine if its in the game project.

https://github.com/Facepunch/sbox-issues/assets/5991682/1f4294e6-5c95-402f-860f-8867d6683d91

**Comment by Gmod4phun** [comment]
It also seems like images are not being loaded, too. (in this case it is PNG images used for parts of my UI)

**Comment by handsomematt** [comment]
Why are you using a content project for these? How do you expect these to upload when you publish?

**Comment by Gmod4phun** [comment]
You got me there. I kinda forgot that you can't upload content projects to asset.party like game or addon projects.

What would be the best way of doing it? I can move the images/videos to the game project, but I wanted to only keep code/scene files in the game project itself, and have all other assets, be it models, materials, or just textures and videos in a separate project.

If I want to make another game project that will require the same files, I have to include them in that project, too, which feels wrong, having duplicate files in two or more projects for things like UI textures.

**Comment by MrBrax** [comment]
isn't this what the addon system with content is supposed to handle?
