### ISSUE TITLE
Load addons in a similar way to maps

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4568]
### For?

S&Box

### What can't you do?

I can't let people load addons into my game without making my own menu for it.

### How would you like it to work?

1. Open a game's properties
2. Under "Game Setup" have a checkbox to enable addon loading, which would add a modal when clicking on the game similar to the map modal

### What have you tried?

I tried making my own addon menu, but I felt like it was a bit time consuming for a quick feature.

**Comment by Nolankicks** [comment]
I think instead of having a thing in the game setup, the developer could enable something similar to the map select screen to select add-ons. In addition fp could also make it easier to implement an addon select ui.

**Comment by DrakeFruit** [comment]
> I think instead of having a thing in the game setup, the developer could enable something similar to the map select screen to select add-ons. In addition, fp could also make it easier to implement an addon select ui.

that is literally what I typed out? it would just have a toggle in game setup, like maps...

**Comment by garrynewman** [comment]
We're not gonna bother with addons for a while. It distracted us the first time and made everything confusing. We will implement addons, just not this early.

**Comment by DrakeFruit** [comment]
completed? not low priority?

**Comment by garrynewman** [comment]
Not a priority, we'll think about it when we need to.
