### ISSUE TITLE
When switching project, old project scene is still loaded.

### ISSUE THREAD

**Issue by TomYeoman** [Facepunch/sbox-issues#4569]
### Describe the bug

S&Box bugs when switching between projects. The video most clearly shows this - note how the old scene is still being played after I switch projects.

https://github.com/Facepunch/sbox-issues/assets/14075632/4bcd4b7b-42db-44fa-a97f-9f69ce1cf090

In addition to this bug, upon exiting the second project, it also breaks my first one. In the video you can see;

1) I restart the game (or just reload it from project view), and try to load the initial project it will complain that the script files are missing.

Note: No file changes have been made in source control, so it's not modifying the scene file, or anything I can see on my end.

2) After a second full reload, the first scene detects the scripts again! 

https://github.com/Facepunch/sbox-issues/assets/14075632/5b61894f-dc0a-46a8-b629-ef8221a49058

### To Reproduce

Create basic new project, and clone the staging repo, and switch between as shown in my video's.

### Expected behavior

Correct project scene's should be loaded when switching projects via the UI.

**Comment by handsomematt** [comment]
Dupe #4496
