### ISSUE TITLE
Add ability to break conical joints

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4570]
### For?

S&Box

### What can't you do?

I have a skeleton ragdoll with a bunch of conical joints. I'd like to be able to make those joints break once enough force is applied.

### How would you like it to work?

Same sort of way the weld joint is set up.

### What have you tried?

Manually deleting the joints, without much luck.

**Comment by aylaylay** [comment]
Setting `PhysicsJoint.Strength` and or `PhysicsJoint.AngularStrength` on the joints of the ragdoll should now break them and deactivate the joint.

**Comment by Fortune117** [comment]
Am I unable to set these from model doc at the moment?

**Comment by aylaylay** [comment]
There was modeldoc code that did allow for setting these but it was either commented out a while ago or since day one.

I don't have a strong opinion on if we should add it back. @garrynewman

**Comment by aylaylay** [comment]
I have added linear and angular strength properties to joint nodes in modeldoc @Fortune117

**Comment by Fortune117** [comment]
Perfect, thanks
