### ISSUE TITLE
Gizmo.Draw.ScreenText uses center of text for position instead of top left

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4572]
### What it is?

When using Gizmo.Draw.ScreenText, the position parameter is where the _center_ of the text is located. With dynamically changing text, the start and end of your screen text is misplaced. This feels unintuitive.

### What should it be?

The position entered is the top left of the text instead. This way, I can set ScreenText at 0,0 and none of my text will be cut off.

**Comment by handsomematt** [comment]
Does the flags parameter do what you want

**Comment by bakscratch** [comment]
"flags:TextFlag.Left" is what you are after

**Comment by trundlr** [comment]
Oh yeah, missed that. Thanks!

**Comment by chrisspieler** [comment]
It would make sense for the default value of the TextFlag to be Left since most screen text drawn will be in a left-to-right script. I pretty much _always_ set TextFlag to left myself whenever using Gizmo.Draw.ScreenText

**Comment by trundlr** [comment]
Agreed ^ if FP wants to change it I'm sure it would take no time
