### ISSUE TITLE
Transform.Scale should default to 1 instead of 0

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4573]
### What it is?

The default value of Transform.Scale is 0. This is seen when you make a `new Transform()` or get `default(Transform)`. 

### What should it be?

`new Transform()` and `default(Transform)` should produce a transform with a scale of 1, the same as `Transform.Zero`

I don't think I've ever wanted a Transform with a scale of zero, but I do want new Transforms with a scale of 1 all the time.

**Comment by DevulTj** [comment]
This should be the case now.
