### ISSUE TITLE
Flags parameter of Gizmo.Draw.ScreenText should default to TextFlag.Left

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4574]
### What it is?

`Gizmo.Draw.ScreenText` has a `flags` parameter of type `TextFlag` that has a default value of `TextFlag.Center`.

### What should it be?

The default value of `flags` should be `TextFlag.Left` since:
1. It's common to want to write debug information in the top-left corner of the screen.
2. It makes arranging text in to columns and rows a lot nicer.
3. Most of the debug text is (at least for now) written in a left-to-right script, and it's more natural to think of the position of the text as being the start of the text.

**Comment by garrynewman** [comment]
Top left or center left?

**Comment by chrisspieler** [comment]
> Top left or center left?

Top-left's probably better, come to think of it.
