### ISSUE TITLE
Color Picker becomes obscured if it's at the bottom of your monitor

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4575]
### Describe the bug

Color Picker box gets obscured preventing you from accessing pretty much half the options if too close to the bottom of your screen.

### To Reproduce

1. Have a Particle Effect Component (for example, probably works on anything, but this is what I've used)
2. Have the "Tint" near the bottom of your monitor
3. Only the Color box shows, everything below is cut off

### Expected behavior

The box should probably be display above the Tint setting rather than below if whats being displayed is going to get cut off. 
Ex: how Steam does it basically
![d3arzGA07d](https://github.com/Facepunch/sbox-issues/assets/44037603/2629c962-6853-4829-9c3e-8c3a616791a5)

![ieMYPe5f4R](https://github.com/Facepunch/sbox-issues/assets/44037603/1ebac2d2-c2d4-42fd-abf5-e367d2972801)

### Media/Files

The full Color Picker:
![firefox_KywLAKNxEY](https://github.com/Facepunch/sbox-issues/assets/44037603/04aa481f-44e0-4ace-a57c-94ba93e9d44e)

The bugged Color Picker (note the gray bar at the bottom is my taskbar, everything below the main color box gets obscured)
![ITuwOoLJ4d](https://github.com/Facepunch/sbox-issues/assets/44037603/3e1a0841-4bb2-4623-84f7-8874bd57e312)

**Comment by aylaylay** [comment]
Should be fixed now
