### ISSUE TITLE
Provide default transparent material

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4576]
### For?

S&Box

### What can't you do?

I am unable to find a material I can use on models that allows for transparency and does not have the dithering/dissolve effect.

### How would you like it to work?

Some model material in the default folder that's easy to find, clearly labelled, and otherwise functions like `materials/default/white`.

### What have you tried?

Using materials meant for Hammer. Had rendering order issues.

### Additional context

This looks kinda bad.
![VFvSZFV 1](https://github.com/Facepunch/sbox-issues/assets/100040020/1c7efa13-4d71-4e8b-975c-b2a2877e4fd5)

**Comment by garrynewman** [comment]
You're looking for a material that support transparency I guess

**Comment by bakscratch** [comment]
There were already some in core "primary_white_*" I've switched the shaders so they should work a bit nicer now.
