### ISSUE TITLE
Clients who join after an element is added to a [Sync]'d list get a network crash.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4579]
### Describe the bug

@kurozael

Host (before any client has joined or is in the process of joining):
```
 08:00:56   GameMenu List: System.Collections.Generic.List`1[MyComponent+TestEnum]
 08:00:56   GameMenu Entry: One
 08:00:56   GameMenu Error when getting value MyComponent._list - Type 'MyComponent+TestEnum' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
 ```

Client after joining:
```
> connect local
Connecting to localclient..
Loading Network Assembly: [package.base]
Loading Network Assembly: [package.local.list_error_repo]
Failed to read System.Int32
TODO - Disconnect, connection has crashed, remove it
```

### To Reproduce

Here's the repro repository: https://github.com/dch-GH/sbox-list-neterror-repo
1. Start the scene in-editor, press the jump button to add an element to the [Sync]'d list
2. Join with another instance, experience the crash.

### Expected behavior

.

**Comment by kurozael** [comment]
All sorted for the next build. If you have any more problems let me know 👍
