### ISSUE TITLE
Error when Generating Code

### ISSUE THREAD

**Issue by Sampleeeee** [Facepunch/sbox-issues#458]
**Describe the bug**
I'm trying to re-create the chatbox for my game. I'm having trouble with codegen and Client(Rpc/Cmd). 

**To Reproduce**

```cs
[ClientRpc] // Also would do the same thing with ClientCmd
public static void AddChatMessage( string name, string message ) { }

AddChatMessage( To.Everyone, "test name", "test message" );
```
I'm not too sure what exactly is causing this issue. Here's the full file. https://gist.github.com/Sampleeeee/64d5e82a8efdbdfe8e79692194c3e362

**Expected behavior**
It should generate another method with the receiver parameter. Instead it just throws the error `Method 'AddChatEntry' has 2 parameter(s) but is invoked with 3 argument(s)`

**Screenshots**
https://sample.wtf/i/sample/big-headed-bone-idle-belief.png

**Additional context**
Using Rider but I get this error both in-game and in my IDE. Sorry if this is the wrong spot, but no one in discord was able to help at all and it seems like an engine error. If I'm doing something wrong then I think the error should give more information

**Comment by handsomematt** [comment]
I can not reproduce with the code you posted to reproduce.

In your full code provided you are using lambdas on the methods marked as [ClientRpc] for some reason, remove them and define them as normally and it will work.

**Comment by Sampleeeee** [comment]
> In your full code provided you are using lambdas on the methods marked as [ClientRpc] for some reason, remove them and define them as normally and it will work.

Removing the lambda worked. Not sure why you aren't able to reproduce it though.
