### ISSUE TITLE
Can't assign a component to a property on the same game object if the component is one of multiple components with the same base type

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4580]
### Describe the bug

I have a state machine on a game object and the different states are represented by different components on the game object. Each component shares a base class `StateComponent`

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/15195687-06d6-4c24-99a1-d6717080da89)

I am trying to assign the different states to the properties section, which is just a property like this:

```CS
	/// <summary>
	/// The state that we return to when we have no target.
	/// </summary>
	[Property]
	private StateComponent ReturnState { get; set; }
```

However, no matter which state I drag into the property it always assigns the first StateComponent in the list, in this case the Idle State.

https://github.com/Facepunch/sbox-issues/assets/7847372/e6c79e03-dd4e-4eb2-89da-4004d2e4b7d7

### To Reproduce

1. Create a bunch of components with the same base class and put the on one game object.
2. Try and assign them to a property on that same game object.

### Expected behavior

Should allow me to use the appropriate state when I drag it in.

**Comment by garrynewman** [comment]
This might be fixed now, with component ids added?

**Comment by Fortune117** [comment]
Yep, this is fixed now!
