### ISSUE TITLE
OnNetworkSpawn() only works for descendants.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4583]
### Describe the bug

Networked game objects only finds Component.INetworkSpawn in descendants. The game object itself is ignored.

### To Reproduce

```c#
public class MyComponent : Component, Component.INetworkSpawn
{
	public void OnNetworkSpawn( Connection owner )
	{
		Log.Info( "Test" );
	}
}
```

1. Put the component on a descendant of a networked gameobject. ( It works. )
2. Put the component on the networked gameobject itself. ( It doesn't work. )

### Expected behavior

OnNetworkSpawn() should also work on itself.

**Comment by garrynewman** [comment]
Should be an easy fix

**Comment by badandbest** [comment]
Thanks, Conna
