### ISSUE TITLE
Map Instance components don't load local map file collision

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4584]
### Describe the bug

While you can specify a map in your project that has not been published, and it appears, it does not have any collision.

### To Reproduce

1. Add a Map Instance component to a GameObject.
2. Specify a `.vmap` you've compiled but haven't published. (ex: "my_map")

### Expected behavior

You should collide with them.

### Additional context

I can just publish it privately, but that wastes a significant enough amount of bandwidth and time for me to want to make this issue.

**Comment by handsomematt** [comment]
Dupe #4564
