### ISSUE TITLE
Z-Index has no effect on the Screen Panel Component

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4585]
### Describe the bug

This value doesn't change the draw order of different UI panels as you'd expect:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/d450737e-fd86-4b41-b32e-fa38f36edb4d)

### To Reproduce

Create 2 panels and play with their z-index

### Expected behavior

The z-index should affect draw order

**Comment by garrynewman** [comment]
Should be fixed now
