### ISSUE TITLE
Allow custom cursors

### ISSUE THREAD

**Issue by TehFlaminTaco** [Facepunch/sbox-issues#4588]
### For?

S&Box

### What can't you do?

Set a Panel's Cursor Style to `grab` or `grabbing`

### How would you like it to work?

```
cursor: "grab";
cursor: "grabbing";
```

### What have you tried?

```csharp
Panel.Style.Cursor = "grab";
Panel.Style.Cursor = "grabbing";
```

**Comment by garrynewman** [comment]
There isn't actually a built in cursor for these, with windows, so we'd have to provide our own  I think?

**Comment by TehFlaminTaco** [comment]
Huh. Could there be an option to provide custom cursors per game..?

**Comment by garrynewman** [comment]
Yeah we need to do that at some point

**Comment by aylaylay** [comment]
I've added initial support for custom cursors in project settings

**Comment by matekdev** [comment]
Nice
