### ISSUE TITLE
Allow selected elements to be deselected, improve multi-select behavior

### ISSUE THREAD

**Issue by JasonO3D** [Facepunch/sbox-issues#4590]
For?
S&Box

**What can't you do?**

When selecting multiple objects in the Scene, I'm unable to easily deselect on a per-object basis, forcing me to find an object in the distance to click to.

**How would you like it to work?**
![multi-select behavior](https://github.com/Facepunch/sbox-issues/assets/123948489/14a501a7-96d0-4b51-9bda-06ce0d214506)

Ideally, I'd be able to Ctrl + LMB to deselect each element. I should also be able to just click on something I have selected and it deselect everything else I had previously selected.

**Comment by MrBrax** [comment]
similar to #4517

**Comment by badandbest** [comment]
I reviewed it and found two problems:
1. Holding CTRL toggles the selection off or on instead of only unselecting.
2. Holding SHIFT / CTRL and clicking the sky will unselect everything.

**Comment by handsomematt** [comment]
1 is intentional to how multi-select works in other game engines and even Windows, not just Hammer.
2 should now be fixed.
