### ISSUE TITLE
Blend painting thumbnails are broken in Hammer

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#4591]
### Describe the bug

Can't see what blend material I'm painting

### To Reproduce

1. Select blend material
2. Select blend tool
3. See no material

### Expected behavior

Seeing blend material thumbnails

### Media/Files

![1706186692544](https://github.com/Facepunch/sbox-issues/assets/1517911/6233f164-2841-42d7-8abf-5fdaa7ad7c90)

**Comment by garrynewman** [comment]
I though this was the thumbnail changes I made, but I don't really think it is now
