### ISSUE TITLE
Map Instances on disabled GameObjects still start enabled

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4594]
### Describe the bug

`MapInstance` components spawned in the scene as disabled will still load maps.

The only way to start them disabled is, weirdly, to enable them in the editor and then disable them at game start.

### To Reproduce

1. Create a `GameObject` and add a `MapInstance` component.
2. Disable the `GameObject`.
3. Load the scene.

### Expected behavior

It should not be enabled upon play if disabled in the editor.

**Comment by aylaylay** [comment]
Should be fixed when the game next updates
