### ISSUE TITLE
Camera Settings should save per project

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4595]
### For?

S&Box

### What can't you do?

Have my camera settings persist between sessions.

### How would you like it to work?

Camera settings saved per project, due to differences in scale.

### What have you tried?

Setting the values back to comfortable amounts. Gets annoying.

### Additional context

Also the default "Camera Speed" should probably be raised from 1 to 7-10. A value of 1 is.. time consuming.

**Comment by garrynewman** [comment]
Which camera settings?

**Comment by MrBrax** [comment]
i'm guessing the camera fov, grid enabled, etc should be saved

**Comment by DevulTj** [comment]
This should be the case now (since https://github.com/Facepunch/sbox-issues/issues/4747).
