### ISSUE TITLE
Disable `Collider` Component with active `Rigidbody` crash s&box

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#4596]
### Describe the bug

Hi,

For my carriable Weapon system, i need to disable my Carriable BoxCollider trigger when the weapon is picked up by the player.

However, is just discovered that disabling through `Collider.Enabled = false` has a strong chance of creating an s&box crash if you have a `Rigidbody` enabled.

### To Reproduce

Look at my reproduction steps:
1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `NetworkTest.cs` -> `TryPickup()` with my code :
```
void TryPickup()
{
	var pc = Components.Get<PlayerController>();
	var lookDir = pc.EyeAngles.ToRotation();
	var eyePos = Transform.Position + Vector3.Up * 60;

	var tr = Scene.Trace.WithoutTags( "player" ).Sphere( 16, eyePos, eyePos + lookDir.Forward * 100 ).Run();
	if ( !tr.Hit ) return;

	if ( tr.Body.GetGameObject() is not GameObject go )
		return;

	if ( !go.Tags.Has( "pickup" ) )
		return;

	go.Network.TakeOwnership();

	Carrying = go;
	Carrying.SetParent( GameObject, true );
	Carrying.Tags.Add( "carrying" );

	// NEW CONTENT
	var collider = Carrying.Components.Get<ModelCollider>();
	if ( collider is not null)
	{
		collider.Enabled = false;
	}

	// DISABLE
	//var rb = Carrying.Components.Get<Rigidbody>( true );
	//if ( rb is not null )
	//{
	//	rb.Enabled = false;
	//}

	var ca = Components.Get<Sandbox.Citizen.CitizenAnimationHelper>();

	ca.IkLeftHand = Carrying.Children.FirstOrDefault( x => x.Name == "hand_left" ) ?? Carrying;
	ca.IkRightHand = Carrying.Children.FirstOrDefault( x => x.Name == "hand_right" ) ?? Carrying;
}
```
3) Start `networking.scene` and try to pick up Wooden Box
4) Crash

**You will get a better chance to crash if you use BoxCollider instead of ModelCollider**

### Expected behavior

No crash

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5229571/ea6f9469-cce0-42cd-8037-946b760dc2ca

**Comment by aylaylay** [comment]
Should be fixed when the game next updates

**Comment by PolSpock** [comment]
Confirmed 😎
