### ISSUE TITLE
Hammer failing to compile

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4597]
### Describe the bug

Hammer is failing to compile. Someone very recently posted the exact same log(except file paths were different of course) with compile failure, so I'm led to believe this is a general issue.

### To Reproduce

1. Attempt to compile a map with hammer.

### Expected behavior

Maps should compile.

### Media/Files

```
Start build: 2024-01-26T10:56:39
Hammer: Attempting incremental build.
Hammer: Copying previously compiled map to temp directory.
WARNING: resource 'postprocess/standard.vpost' is an unrecognized resource type!
WARNING: resource 'postprocess/standard.vpost' is an unrecognized resource type!
WARNING: resource 'postprocess/standard.vpost' is an unrecognized resource type!
WARNING: resource 'postprocess/standard.vpost' is an unrecognized resource type!
WARNING: resource 'postprocess/standard.vpost' is an unrecognized resource type!
WARNING: resource 'postprocess/standard.vpost' is an unrecognized resource type!
"SplitFullPath" failed on s:\projects\scene_testing\scene testing\maps\hc_flyzone.vmap.
-----------------------------------------------------------------
OK: 0 compiled, 0 failed, 1 skipped, 0m:00s
-----------------------------------------------------------------
ID3D11Device has 1 outstanding references indicating leaked D3D11 resources. Hammer: Copying compiled map to game directory.
From: S:\SteamLibrary\steamapps\common\sbox\.source2\mapbuild-output\vidya.heli-chan\maps\hc_flyzone.vpk
To: s:/projects/scene_testing/scene testing/maps/hc_flyzone.vpk
End build: 2024-01-26T10:56:40, elapsed time 0h:00m:01s.016ms

```

### Additional context

I have no custom textures, cloud content et cetera in my map yet. It's just dev textures.

**Comment by handsomematt** [comment]
That makes sense. I need to pass search paths to the external process

**Comment by osmanlodzero** [comment]
Happens to me as well, now it compiles unlike yesterday and it seems it copies, but I do get a small red warning saying it could not copy the map.
<img width="722" alt="Schermafbeelding 2024-01-27 123742" src="https://github.com/Facepunch/sbox-issues/assets/35051017/6b31a55d-f4c7-4ae3-b6ff-7732316e5c74">

The log looks similar/identical to the one posted above

**Comment by handsomematt** [comment]
Thanks - will investigate

**Comment by handsomematt** [comment]
Should be fixed in new build now
