### ISSUE TITLE
Re-add a way to listen for hotload like in the old API.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4599]
### For?

S&Box

### What can't you do?

I'd like to run some code when a hotload is detected. 

In my case I'd like to dynamically add new dependencies to my dependency injection container without having to restart the scene. 🤓

### How would you like it to work?

Maybe:
`Sandbox.Component.IHotloadListener`
`public void OnHotloaded();`

### What have you tried?

Nothing.

**Comment by Metapyziks** [comment]
As a workaround for now, you can use `IHotloadManaged` to handle when a particular instance gets replaced by hotload.

```csharp
public class ExampleComponent : Component, IHotloadManaged
{
	void IHotloadManaged.Created( IReadOnlyDictionary<string, object> state )
	{
		Log.Info( $"Hello, I got replaced during a hotload!" );
	}
}```

This should work well enough for your use case, assuming your code is only in one assembly.

**Comment by dch-GH** [comment]
> As a workaround for now, you can use `IHotloadManaged` to handle when a particular instance gets replaced by hotload. It doesn't need to be a Component type, but that works too.
> 
> ```cs
> public class ExampleComponent : Component, IHotloadManaged
> {
> 	void IHotloadManaged.Created( IReadOnlyDictionary<string, object> state )
> 	{
> 		Log.Info( $"Hello, I got replaced during a hotload!" );
> 	}
> }
> ```
> 
> This should work well enough for your use case, assuming your code is only in one assembly.

Cool, thanks. I'll leave the issue up to you guys if this is just a workaround for now. ❤️
