### ISSUE TITLE
New Shaders fail to compile

### ISSUE THREAD

**Issue by TehFlaminTaco** [Facepunch/sbox-issues#4600]
### Describe the bug

When attempting to create a new Shader, it fails to compile with the error

### To Reproduce

Create a new `.shader` file. Attempt to compile.

### Expected behavior

Shader should compile.

### Media/Files

```
Cannot find shader shaders/portalview.shader in the current content folder G:\SteamLibrary\steamapps\common\sbox\addons\citizen\;G:\SteamLibrary\steamapps\common\sbox\addons\base\;G:\SteamLibrary\steamapps\common\sbox\core\;G:\SteamLibrary\steamapps\common\sbox\.source2\cloud\;G:\SteamLibrary\steamapps\common\sbox\.source2\temp\!
```

### Additional context

Latest staging branch

**Comment by TehFlaminTaco** [comment]
Resolved by latest version

**Comment by Retroeer** [comment]
I seem to be getting this issue again 😢 
`Cannot find shader models/specter/shaders/source 2/specter.shader in the current content folder C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\citizen\;C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\base\;C:\Program Files (x86)\Steam\steamapps\common\sbox\core\;C:\Program Files (x86)\Steam\steamapps\common\sbox\.source2\cloud\;C:\Program Files (x86)\Steam\steamapps\common\sbox\.source2\temp\!`
