### ISSUE TITLE
[Scene Particles] Let Scene Particles get locked to a specific Axis

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4602]
### For?

S&Box

### What can't you do?

I'm unable to create a scene particle that stays locked to a certain axis. 

### How would you like it to work?

I suppose in the Particle Renderer component, have a axis lock option.

### What have you tried?

Nothing, I could write a shader, but I'd really rather not. 

### Additional context

What a nice looking particle, ripe for usage on an object you want the player to notice, I sure hope it doesn't rotate if you look down at it
![image](https://github.com/Facepunch/sbox-issues/assets/44037603/b5e64e31-c272-4d7d-9a21-fb4989d0ed60)
:(
![image](https://github.com/Facepunch/sbox-issues/assets/44037603/64ad4881-41a9-4b84-87ca-fec1fe5ce3d0)

**Comment by garrynewman** [comment]
What would be better, if they render always on an axis, or if they simulate on an axis?

**Comment by Retroeer** [comment]
What exactly do you mean by that?

**Comment by Retroeer** [comment]
After asking around it seems like the former would be better.

**Comment by Retroeer** [comment]
I know this is in the backlog still but any updates on this? As I progress with scenes and my game it's becoming a bit hard to continue ignoring this :(

**Comment by Retroeer** [comment]
This is done, and is good stuff too
