### ISSUE TITLE
Download on assets not completing s&box hammer 2

### ISSUE THREAD

**Issue by 22max5** [Facepunch/sbox-issues#4603]
### Describe the bug

I drag an asset from asset.party into the game, or select one from the browsers (materials or models i.e) and they get a download symbol and never finish.

### To Reproduce

1. open material tool
2. browse for a material
3. click the material
4. download icon pops up
5. never finishes downloading (i've let it run for an hour)

### Expected behavior

Material or model is downloaded and can then be used in the hammer 2 editor for s&box.

### Media/Files

![image (1)](https://github.com/Facepunch/sbox-issues/assets/1621739/62a067b9-e20a-4ac3-996d-2811c31c207a)
![image](https://github.com/Facepunch/sbox-issues/assets/1621739/86342f30-ff7d-4ed1-8d58-21d5b72eff96)

### Additional context

In Hammer 2, running on latest windows, did restarts and re-installs of s&box too.

**Comment by CarsonKompon** [comment]
This is also happening in the s&box inspector 
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/9c22e379-faf0-4b9c-8b92-e0f57c724398)
