### ISSUE TITLE
Sphere vs Sphere collision callbacks return reversed speed

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4605]
### Describe the bug

OnStartCollision is returning the wrong `Contact.Speed` when two spheres are involved. The direction is reversed.

### To Reproduce

1. Create a component with `Component.ICollisionListener` interface.
2. Add a Gizmo.Draw representing `collision.Contact.Speed` at contact point.
3. Give a GameObject the component and a sphere collider.
4. Collide it with another sphere.

### Expected behavior

Spheres against spheres should return the velocity you were going, instead of the reverse.

### Media/Files

```
Gizmo.Draw.Color = Color.White;
Gizmo.Draw.SolidSphere( bouncePos, 4f );
Gizmo.Draw.Color = Gizmo.Colors.Red;
Gizmo.Draw.Line( bouncePos, bouncePos + speedNormal * 50f );
```

**Comment by aylaylay** [comment]
Speed and normal now get flipped for the other collider, see if that gives you what you want
