### ISSUE TITLE
TypeLibrary couldn't find Component type ...

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4606]
### Describe the bug

i can't open my project withount getting
```TypeLibrary couldn't find Component type```

### To Reproduce

open the project (for me i am getting this error all the time, some people don't get this error)

### Expected behavior

not getting
```TypeLibrary couldn't find Component type```

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/14070854/Log.log)

### Additional context

some people don't have it happening
that wasn't happening some days ago

**Comment by badandbest** [comment]
Yeah this happens all the time. The trick is to restart the project without saving until it works.

I think these issues are related: 
* https://github.com/Facepunch/sbox-issues/issues/4236
* https://github.com/Facepunch/sbox-issues/issues/4273

**Comment by MrBrax** [comment]
for me it fixes if you just close the scene and open it again

**Comment by garrynewman** [comment]
Duplicate
