### ISSUE TITLE
PanelComponent not visible when gameobject it's attached to is re-enabled

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4607]
Setting Enabled to `false` then `true` again on a PanelComponent itself will hide it then show it as expected.
But toggling Enabled on the gamebobject that has the PanelComponent will not show the (enabled) PanelComponent when the gameobject is re-enabled.

https://github.com/Facepunch/sbox-issues/assets/1173137/3d464c88-c24a-42ef-854c-0bcf0eeff8f6

**Comment by garrynewman** [comment]
This seems to have gotten fixed at some point in the last month
