### ISSUE TITLE
Thread created by Task.RunInThreadAsync can continue working even after scene was stopped

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4608]
### Describe the bug

thread created by Task.RunInThreadAsync can continue working even after scene was stopped

### To Reproduce

1. use code below
2. add component to gameobject
3. start scene then immediatly stop it
4. message "disabled" will be shown first, then there will be another message from thread (if it doesn't happens so, increase the value it iterates to)

```
using Sandbox;
using System;
using System.Threading.Tasks;

public class Testing : Component
{
    [Property] bool _start { get; set; } = true;

    protected override void OnUpdate()
    {
        if(_start)
        {
            _start = false;
            _ = Task.RunInThreadAsync(() =>
            {
                _ = Test();
            });
        }
    }

    protected async Task Test()
    {
        long x = 0;
        for(long i = 0; i < 4_000_000_000; ++i)
            x += i;
        Log.Info($"from thread: {x}");
        throw new Exception();
    }

    protected override void OnDisabled()
    {
        Log.Info("disabled");
    }
}
```

### Expected behavior

thread should be killed when scene stops

### Additional context

it can be a big problem if it can run not in editor

**Comment by Metapyziks** [comment]
I don't think there's a nice way to abort threads any more. There's [Thread.Interrupt](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.interrupt?view=net-8.0) but that will only affect blocked threads.

We also rely on being able to suspend / resume worker tasks when performing an assembly hotload, which only works if they await regularly.

My first choice would be to enforce worker thread stuff to be async and await often:
- Deprecate `RunInThreadAsync( Action )`, only allow `RunInThreadAsync( Func<Task> )`
- We already have a mechanism of aborting tasks started this way if their sync context expires
- Log a warning if a task started this way doesn't await after some timeout (maybe 1 second)

Alternatively:
- Add a lightweight `AssertThreadNotAborted()` method
- Generate calls to it at the start of each block in user code, like we do with `EnsureSufficientExecutionStack()`
- This will let us abort quickly when switching games / stopping play mode, but doesn't let us suspend and resume

**Comment by Metapyziks** [comment]
I guess we want to do this kind of thing in EditorScene.Stop():

```csharp
TaskSource.OnSessionEnded();
GameTask.Reset();
```

**Comment by Metapyziks** [comment]
Played around with this a bit. Adding a warning for actions that don't yield after a second works well.

I also got thread aborting working using code generation. It just checks an int and a bool at the start of each block of user code, so shouldn't have much more of an impact than the `EnsureSufficientExecutionStack()` calls we're already injecting.

@garrynewman would you prefer just the warning, or aborting too when hotloading / exiting a game?
