### ISSUE TITLE
Asset browser window widens to try and fit the full path, this feels weird if you have the asset browser in a portrait configuration

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4609]
### Describe the bug

Asset browser window widens to try and fit the full path, this feels weird if you have the asset browser in a portrait configuration.
Video:
https://github.com/Facepunch/sbox-issues/assets/11138884/d66ffdd7-c8ac-4b01-a532-6b3e9babc362

### To Reproduce

Click on any long path while the asset browser window is not set to be very wide

### Expected behavior

I feel like maybe the path should only show the last 2 folders or something rather than try to fit every folder you've gone through, if it doesn't fit in the width?

**Comment by garrynewman** [comment]
The asset browser was one of the first things we made with the editor UI code, and there have been a lot of advancements over the past year - there is a lot we can improve.
