### ISSUE TITLE
Sound Class is limited

### ISSUE THREAD

**Issue by VladUndying** [Facepunch/sbox-issues#461]
**What can't you do?**
Can't get Position, Pitch / Random Pitch, Volume fields value.
Can't get the state of the current sound. IsPlaying would be nice.

**How would you like it to work?**
Being able to see all the fields of Sound class + having a way to see if the current sound has stopped.

**Comment by goaaats** [comment]
This would be very helpful to me as well, as I'm trying to sync gameplay events to music and need the position of the sound from Sound/SoundStream to not encounter desyncs.

**Comment by GamerXCZ** [comment]
Sound.FadeIn, Sound.FadeOut it is also needed

**Comment by VladUndying** [comment]
Solved with newest push ❤
