### ISSUE TITLE
Can't override a Rigidbody's mass

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4612]
### Describe the bug

Trying to set the mass of a rigid body does nothing.

### To Reproduce

1. Create a rigidbody with collider.
2. Override its mass both OnStart and OnFixedUpdate.
3. `[Property] public float Mass => RB?.PhysicsBody?.Mass ?? 0f;`

### Expected behavior

You should be able to override the mass.

### Additional context

Worth noting that it also did not used to work `OnStart` either so it had to be ran afterwards, like in `OnFixedUpdate`. But now it doesn't work at all.

My helicopter is so sloooww now.

**Comment by aylaylay** [comment]
Are you setting it before or after adding shapes

**Comment by aylaylay** [comment]
Should work now
