### ISSUE TITLE
Map Instance does not correctly assign models to model physics components

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4613]
### Describe the bug

When using the Map Instance component to load a map that has objects with a Model Physics component, the model renderer of that object is not assigned properly and it behaves incorrectly.

### To Reproduce

1. Load a map that has some objects with Model Physics (like flatgrass)
2. Enable physics debug and try to interact with said object to see the problem

### Expected behavior

Model renderer should be correctly assigned for Model Physics objects loaded by Map Instance.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/f788eb90-83cc-4375-8f5c-283c4ec92450

**Comment by aylaylay** [comment]
Fixed

**Comment by Gmod4phun** [comment]
Thanks, works fine
