### ISSUE TITLE
Add something similar to Entity.FindInSphere from old entity API

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#4616]
### For?

S&Box

### What can't you do?

Right now there is no equivalent for the old API's `Entity.FindInSphere` and the other related methods.

### How would you like it to work?

Something like `IEnumerable<GameObject> GameObject.FindInSphere( Sphere sphere )` to just fetch all the GameObjects within a sphere.

### What have you tried?

I've tried doing traces, but I don't want it to rely on colliders or anything. 
It would just be nice to have!! :P

**Comment by garrynewman** [comment]
Remind me, did this API used to find only entities with physics objects

**Comment by Gmod4phun** [comment]
Yeah the FindIn* methods relied on physics. It would be nice to have both physics based and position based versions of this.

**Comment by aylaylay** [comment]
Add Scene.FindInPhysics( sphere ) and Scene.FindInPhysics( bbox )

**Comment by ceitine** [comment]
Works nicely, but there is an issue with ModelColliders that use procedural models, because it seems like FindInPhysics doesn't catch those ModelColliders.

Here's a minimal repro: https://github.com/ceitine/collider_repro

**Comment by aylaylay** [comment]
Thanks for the repro, it should be fixed now

**Comment by ceitine** [comment]
looks like everything works now, thanks !!!
