### ISSUE TITLE
Add ProceduralHitReactions extension method

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4617]
### What it is?

There used to be an extension method designed for procedural hit reactions that you could call on model entities like 
`this.ProceduralHitReaction( <args> )` but there's no equivalent in the scene system at the moment.

### What should it be?

Same thing as how it used to be but for a skinned model renderer this time.

**Comment by garrynewman** [comment]
Should be easy enough for us to copy this over

**Comment by Fortune117** [comment]
Awesome, exactly what I wanted.
