### ISSUE TITLE
SoundEvent.SelectionMode isn't hooked up 

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4618]
### Describe the bug

SoundEvents with the `RandomExclusive` selection method can still play the same sound effect multiple times in a row.

### To Reproduce

1. Create a sound event with the `RandomExclusive` setting
2. Play the sound event.

### Expected behavior

Should play randomly without playing the same sound twice.

**Comment by garrynewman** [comment]
The sound event system is really pending a big rewrite, so I would think this'll get fixed during that.

**Comment by aylaylay** [comment]
Tricky one, I don't see anywhere to keep the state of last index played to implement these modes. @garrynewman would have a better idea.

**Comment by garrynewman** [comment]
It would have to be a private var in the SoundEvent itself I would imagine

**Comment by aylaylay** [comment]
I've supported these modes, give them a try for me please
