### ISSUE TITLE
Terrain collisions with colliders cause alot of lag

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4622]
### Describe the bug

When a terrain collider collides with a big collider, or with many smaller colliders, it causes severe lag. I can imagine it is because of the terrain density.

### To Reproduce

1. Have a terrain
2. Place some big colliders into it and see the FPS go down, possibly even stall the game

### Expected behavior

Probably better performance, if it is even possible.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/d84c051a-3d60-4333-a690-fba7afc09aa3

https://github.com/Facepunch/sbox-issues/assets/5991682/0f74abfe-8662-424b-9df5-54705ecf5a3e

**Comment by aylaylay** [comment]
They're not optimized, it's temporary until Izabu adds it officially

**Comment by aylaylay** [comment]
It's now using the official one, the performance should be better but obviously can still slow it down
