### ISSUE TITLE
Launch option for editor in VR

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4625]
### For?

S&Box

### What can't you do?

open s&box editor with vr enabled conveniently.

### How would you like it to work?

just a fourth launch option right next to start s&box in VR

### What have you tried?

adding the editor as a non steam game with -VR or just adding / removing -VR to s&box itself and launching in editor mode

**Comment by xezno** [comment]
I think we'll end up adding a button to switch to VR both in the game and the editor for convenience's sake, rather than making people restart the game every time they want to switch modes

**Comment by DrakeFruit** [comment]
is that possible now because of vulkan? I remember hearing that was impossible to do

**Comment by xezno** [comment]
I added this ages ago
