### ISSUE TITLE
VR is stuck loading in headset

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4626]
### Describe the bug

when I press play mode in a vr scene, I can see what I should see in vr properly in the game tab on my desktop, but in vr it says s&box is loading indefinitely.

### To Reproduce

1. launch s&box with vr enabled in editor mode
2. press play
3. nothing shows in headset, but the desktop view looks fine.

### Expected behavior

play mode renders the camera to the headset.

**Comment by handsomematt** [comment]
I'm sure you could be more helpful here. Does it work outside of editor mode? What VR headset do you have? Can you provide your Log.txt?

**Comment by xezno** [comment]
Sounds like you probably haven't set the camera up properly, impossible to tell with no context

**Comment by xezno** [comment]
Can't repro this at all, everything works fine for me on my Quest 2 with the current Steam build.
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/78133582-7467-43d0-9fd6-e9438981bf8f)

**Comment by DrakeFruit** [comment]
sorry,
Everything works in non-editor mode, looks like someone else was able to replicate it by following the setup I put on the getting started page of the wiki. Clearly I'm doing something wrong there but I'm not home to test.

**Comment by DrakeFruit** [comment]
Confirmed that this was caused by putting the tracked object component on a parent of the camera instead of the camera itself, is this intentionally impossible or just a bug?

**Comment by DrakeFruit** [comment]
the issue was that I needed to set the eye render target to both, I thought that was already set
