### ISSUE TITLE
Strange behavior when cloning prefabs in `OnEnabled` and `OnAwake`

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4627]
### Describe the bug

Unexpected behavior occurs when cloning a prefab in a component's `OnEnabled` and `OnAwake` methods.
There may be more, but I've noticed these:
* Modifying properties on the clone's components doesn't have any effect
* Component references within multiple clones all point to the same Component instance

### To Reproduce

1. Clone [this project](https://github.com/Willco2/PrefabCloneBug)
2. Play the default scene
3. Watch the console for logs showing that `ModelRenderer`s on cloned prefabs are the same, as well as the cubes staying white instead of turning red and blue.

### Expected behavior

A cloned prefab's component references should be fully resolved and valid when cloning inside `OnEnabled` and `OnAwake`

### Additional context

In the repro project I linked, try changing `OnEnabled` in *CubeSpawner.cs* to `OnStart` or `OnAwake`. `OnAwake` has the same strange behavior, but using `OnStart` fixes it.

**Comment by garrynewman** [comment]
This should be fixed now - thanks for the repro project, it was really useful
