### ISSUE TITLE
Hotload hang when managed debugger is attached

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#4629]
![parsecd_sxsHT2wr4a](https://github.com/Facepunch/sbox-issues/assets/22372616/65bc92f4-574f-445a-95cd-d93b508a2be1)

![parsecd_bAHEYI8Ynd](https://github.com/Facepunch/sbox-issues/assets/22372616/dac8d932-36d8-4477-adb5-714b0986cfbd)

**Comment by handsomematt** [comment]
Yeah

**Comment by Metapyziks** [comment]
Oops forgot about this!
