### ISSUE TITLE
Whitelist System.Version

### ISSUE THREAD

**Issue by Ryhon0** [Facepunch/sbox-issues#463]
**What can't you do?**
Use System.Version

**How would you like it to work?**
Whitelist System.Private.CoreLib/System.Version

**What have you tried?**
Using System.Version

**Comment by Rohansi** [comment]
Curious what you're using this one for

**Comment by Ryhon0** [comment]
Loading Beat Saber maps, they have a _version field which is used to check if the map is compatible with this version of the game. System.Text.Json has a built in converter for it so I don't have to worry about writing that. I don't think it exposes anything dangerous so I don't see why it shouldn't be included

**Comment by Ceveos** [comment]
I would also be able to use this. I created a modular addon-type system, and it would be nice to have a proper version field for each addon vs a double.

**Comment by Rohansi** [comment]
This should be good now. Give it a bit to build and update on Steam
