### ISSUE TITLE
Components of the same Type share values when added to a single GameObject

### ISSUE THREAD

**Issue by Matt9440** [Facepunch/sbox-issues#4630]
### Describe the bug

Components of the same Type share values when added to a single GameObject

### To Reproduce

- Create a component with a property
```
public class MyAwesomeComponent : Component
{
    [Property] public int MyAwesomeInt { get; set; }
}
```
- Add two of the same component to a GameObject
- Change the integer in one component
- Observe that the changes are produced on both components

### Expected behavior

The component should be treated as a different object

**Comment by ObsidianPlague** [comment]
had this issue happen to me today, tried to add 2 skinned renderers and they both copied eachother, couldn't modify one without modifying the other

**Comment by DevulTj** [comment]
this hasn't happened for a while now
