### ISSUE TITLE
Shader Translucency

### ISSUE THREAD

**Issue by N0tiK44** [Facepunch/sbox-issues#4631]
### Describe the bug

Recent update in the last few hours has caused translucent materials to not work whilst inside the scene system.

Error doesn't appear in the main scene system, only whilst playing and testing said game.

### To Reproduce

1. Create a material with Alpha Test Rendering on a Foliage Shader
2. Apply said material to a model or mesh
3. Press play in scene system

### Expected behavior

Translucency should work when applied to the required texture.

### Media/Files

![Screenshot 2024-01-30 040332](https://github.com/Facepunch/sbox-issues/assets/141003308/5334594f-9b9c-42a2-9a58-5572f176841b)
![Screenshot 2024-01-30 040713](https://github.com/Facepunch/sbox-issues/assets/141003308/ac37dfcd-54c1-4b6f-9dd7-116fcdd9f53b)
![Screenshot 2024-01-30 040800](https://github.com/Facepunch/sbox-issues/assets/141003308/92de7d85-6df2-4a37-99e4-c139266ac4b3)

### Additional context

After numerous updates and verifying game files, this issue still occurs.

**Comment by handsomematt** [comment]
Is this only on the foliage shader? Or does it happen with others?

**Comment by Gmod4phun** [comment]
For me, doesn't seem to happen with a material that uses the complex shader:

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/2200e609-9386-4910-9897-27bdd96a3f37)


Not sure about the trees in the Square map, but I think those use the Foliage shader and those seem to be fine (the leaves do look a bit weird from a distance, like being semi transparent or having a dithering-like effect)

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/a2fe7ab5-5f04-47f4-908b-ed8fd44f15eb)

**Comment by N0tiK44** [comment]
> For me, doesn't seem to happen with a material that uses the complex shader:
> 
> ![image](https://private-user-images.githubusercontent.com/5991682/300551830-2200e609-9386-4910-9897-27bdd96a3f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTA4MjgsIm5iZiI6MTcwNjU1MDUyOCwicGF0aCI6Ii81OTkxNjgyLzMwMDU1MTgzMC0yMjAwZTYwOS05Mzg2LTQ5MTAtOTg5Ny0yN2JkZDk2YTNmMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTc0ODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZkZDUwOGZjMzllNjdiZDJhNDRjYTE4MTcwNmIzZDdkMjAxZjUyOGMzNmViMGRlZTY2MjgwZWFiYzY4NGQyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tV0YTySarkZLrJGMy6PBfG_PrV7zi-UwO-31z-he9I8)
> 
> Not sure about the trees in the Square map, but I think those use the Foliage shader and those seem to be fine (the leaves do look a bit weird from a distance, like being semi transparent or having a dithering-like effect)
> 
> ![image](https://private-user-images.githubusercontent.com/5991682/300552093-a2fe7ab5-5f04-47f4-908b-ed8fd44f15eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTA4MjgsIm5iZiI6MTcwNjU1MDUyOCwicGF0aCI6Ii81OTkxNjgyLzMwMDU1MjA5My1hMmZlN2FiNS01ZjA0LTQ3ZjQtOTA4Yi1lZDhmZDQ0ZjE1ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTc0ODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1MjI5ZWVjMjM5MjBiNTQ3N2FjMzkwNGJmYWNhNTg4MzkxZjQ0NTc3MjVjZWU3MWFlMjRhMzU5NDQ4ODNjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FADj7RX6RpTiI_lnrCdXOincqqxObsv2VpQMpEQ5Ei0)

In the 2nd photo you can see the shadows casting on the ground are solid textures, it doesn't look like light isn't passing through the transparent image. do you mind sending another photo of square map?

**Comment by Gmod4phun** [comment]
I have not noticed that, good catch. It seems the shadows are fucked indeed 
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/a4e04597-1468-44cc-8c54-c3cf75fabc6a)

The non-foliage material seems to cast shadows fine
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/aa353753-5915-44ca-9ff1-f995f85ec4e6)

**Comment by handsomematt** [comment]
I think it's specifically a problem with shaders that use alpha to coverage, I will look into it thanks for checking the other ones
