### ISSUE TITLE
Dragging GameObjects to the inspector does not work properly

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4633]
### Describe the bug

I'm unable to drag a gameobject as a property.

### To Reproduce

Create a skinned model render property.

### Expected behavior

I should be able to set the property.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/62ed6cec-4a78-47b6-b3b5-8de7f79439f7

**Comment by Nolankicks** [comment]
Still getting this bug and its not just for the Skinned Modelrender.

**Comment by DevulTj** [comment]
I broke this yesterday when supporting multiple components - this functionality should be restored now.
