### ISSUE TITLE
Creating a new game project creates the project folder but does not open the editor

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4634]
### Describe the bug

![RNR8qUb](https://github.com/Facepunch/sbox-issues/assets/66768086/2645887f-5965-41d6-bcf8-1c24dc25e2f5)
I'm clicking but you can't tell! 😅 
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/2f971f02-d365-4f1c-ba36-0f6972388a05)

### To Reproduce

I have no idea how you could repro this, it seems like its only affecting me. I've verified integrity of the files

### Expected behavior

I didn't know this was supposed to automatically open the editor for that project, I assumed it was broken for everyone else. I'd like it to do that for me too.

**Comment by handsomematt** [comment]
Do you have a log from it doing this? And just to clarify this is from the start screen right?

**Comment by dch-GH** [comment]
> Do you have a log from it doing this? And just to clarify this is from the start screen right?
```
2024/02/02 13:18:19.8925	[GameMenu] Copying Minimal template to destination folder: D:/test\My Project	
2024/02/02 13:18:19.8925	[GameMenu] OK	
2024/02/02 13:18:19.8995	[Interop] The file 'D:\test\My Project\.gitignore' already exists.	System.IO.IOException: The file 'D:\test\My Project\.gitignore' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Editor.ProjectCreator.CreateProject() in S:\SteamLibrary\steamapps\common\sbox\addons\tools\code\Editor\AddonManager\ProjectCreator.cs:line 242
   at Editor.Button.OnClicked()
   at Editor.Button.InternalOnClicked()
   at Managed.SourceTools.Exports.Editor_Button_InternalOnClicked(UInt32 self)
```
Yes, from start screen or from inside the active editor using the New Project dropdown
