### ISSUE TITLE
Headless editor's API

### ISSUE THREAD

**Issue by Walrusking16** [Facepunch/sbox-issues#4635]
### For?

S&Box

### What can't you do?

I want the ability to control some of the built-in editors and control them headlessly.

For example:  Model Doc

I have hundreds of meshes that are used to procedurally generate content, and it takes a while when you have to open each fbx, set the material so that overrides work, compile and enter the name to save. I would like the ability to make a custom context button that would set up a model for me without having to actually open 30+ instances of model doc and manually enter the information.

The ability to do this could allow editor tools that accelerate the process for the different editors, such as the example I am trying to do.

### How would you like it to work?

This is a rough example on how it might work for a model doc editor, it is missing most of what you might expect it to have, but this should provide an overview on what it might do.

This example sets the name of the file for you, sets a material for the first material, and then compile and save the asset.

```cs
public partial class ContextMenuExt
{
	[Event( "asset.contextmenu", Priority = 50 )]
	private protected static void OnFbxFileAssetContext( AssetContextMenu e )
	{
		var FBXs = e.SelectedList.Where( x => x.AssetType.FileExtension == "fbx" );
		if ( FBXs.Any() )
		{
			var count = FBXs.Count();

			// ModelDoc has native code to do this for us
			e.Menu.AddOption( count > 1 ? $"Setup {count} models" : "Setup Model", "open_in_new",
				() => FBXs.ToList().ForEach( CreateAsset ) );
		}
	}

	// Example class
	public class Editor
	{
		// Allow us to set the filename
		public string FileName { get; set; }
		
		// Access the material groups on the mesh
		public List<MaterialGroup> MaterialGroups { get; set; }
		
		// Compiles the asset
		public Editor Compile()
		{
			return this;
		}
		
		// Saves the asset to the file path
		public void Save() {} 
	}

	private static void CreateAsset( Asset asset )
	{
		// assumes UseEditor is created
		var editor = asset.UseEditor( "modeldoc_editor" );

		editor.FileName = asset.Path;
		
		var materialGroups = editor.MaterialGroups;

		materialGroups[0].material = "materials/dev/primary_white_vertexcolor.vmat";
		
		editor.MaterialGroups = materialGroups;

		editor.Compile().Save();
	}
}
```

### What have you tried?

I tried to use the same code that was used for the Create Model context button, but it just returns a void and does not seem to allow any control over what happens

```cs
[Event( "asset.contextmenu", Priority = 50 )]
	private protected static void OnFbxFileAssetContext( AssetContextMenu e )
	{
		var FBXs = e.SelectedList.Where( x => x.AssetType.FileExtension == "fbx" );
		if ( FBXs.Any() )
		{
			var count = FBXs.Count();

			// ModelDoc has native code to do this for us
			e.Menu.AddOption( count > 1 ? $"Setup {count} models" : "Setup Model", "open_in_new",
				() => FBXs.ToList().ForEach( asset => asset.OpenInEditor( "modeldoc_editor" ) ) );
		}
	}
```

### Additional context

This feels like it could just be a request for specifically what I want it to do, but I figured maybe others would find this useful for use in custom editor tools.

**Comment by handsomematt** [comment]
We're not gonna expose native tools like that. In the distant future we may replace the native tools like ModelDoc & MatEd with C# tools that you'd be able to interact with their APIs
