### ISSUE TITLE
Hammer-like resize tool

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4636]
### For?

S&Box

### What can't you do?

Quickly resize any GameObject's dimensions like how it works in Hammer using a dedicated tool.

### How would you like it to work?

Press Q and you get a widget like this when you select an object.
![image](https://github.com/Facepunch/sbox-issues/assets/100040020/97109e78-3bec-4587-897c-56c1e1aa6c53)

A box surrounds the object. Colored handles let you drag one side of the object, scaling it in *that direction* and automatically translating its position. White handles let you drag the object in 2 axes at once, though I don't fuck with those usually cause they're a bit sensitive.

To simplify, if you wanted to resize the mesh to the left of the camera it would look like this.

![image](https://github.com/Facepunch/sbox-issues/assets/100040020/69906018-c5b7-4f8c-8845-331b0d1741ca)

It would automatically snap to the grid unless you held CTRL. Numbers indicate the new dimensions resulting from your dragging.

Hammer, in this mode, also allows you to drag the object on the axis of the side you are dragging relative to the camera. We have W already right now but implementing this would improve workflow further.

This would be a good intermediary alternative to the mesh editing stage of the scene editor as it would allow me to quickly resize cubes and planes just like you can in Hammer, letting me prototype levels n shit really fast. Also very useful for *precisely* scaling objects without having to do math and input numbers in fields manually.

### What have you tried?

Putting numbers in fields manually. Not fun.

I'd consider trying to make the widget myself if I had any idea what the fuck I was doing in that regard. Too busy making games. I assume people will find this useful enough to have it on the Q button officially.

**Comment by handsomematt** [comment]
This will be part of a mesh editor, it wouldn't make sense to shoe horn it in here
