### ISSUE TITLE
Expose SkiaSharp bindings/image manipulation

### ISSUE THREAD

**Issue by m0uka** [Facepunch/sbox-issues#464]
**What can't you do?**
It would be nice to have the possibility to manipulate images, draw custom images, encode/decode image formats

**How would you like it to work?**
I have noticed that s&box already uses SkiaSharp, so maybe it could be wrapped.
This could be used for some very basic video streaming (currently it's almost impossible)

**Comment by handsomematt** [comment]
(Posted on your other issue, but will repeat here.)

You can already do this with Sandbox.TextureLoader.Image.Load which is wraps SKBitmap.Decode and returns a Sandbox.Texture.

```csharp
var stream = new MemoryStream( imgData.Data );
Texture tex = Sandbox.TextureLoader.Image.Load( stream );
```

**Comment by m0uka** [comment]
I was thinking more like a direct access to the bitmap, maybe SKPaint for painting images, etc..
