### ISSUE TITLE
Ability todo simple math in numerical input fields

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#4640]
### For?

S&Box

### What can't you do?

It would be nice if you were able todo simple math inside a numerical input fields like in other software such as Blender, Unreal, or Unity.

### How would you like it to work?

In any Numerical Input Field for example you could do something like : **128*4**, which would then immediately result in **512**

### What have you tried?

just doing the shrimple math and then inputting the value into the input field.

**Comment by garrynewman** [comment]
Done

**Comment by QuackCola** [comment]
Lovely stuff!
