### ISSUE TITLE
ModelDoc forgot about GameData again

### ISSUE THREAD

**Issue by MaxLebled** [Facepunch/sbox-issues#4642]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/3624123/80937529-b82d-4ea0-b55a-d27b1b924753)

![image](https://github.com/Facepunch/sbox-issues/assets/3624123/47a5f26d-8731-48db-b676-0e88ddebeca5)

### To Reproduce

This should show up on citizen.vmdl

### Expected behavior

No warnings, properties of the AO nodes should not be showing as red / "undefined"

### Additional context

This is an issue that has come up a few times in the past already

**Comment by garrynewman** [comment]
This should be fixed now
