### ISSUE TITLE
Video capture colors are messed up

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4645]
### Describe the bug

When I record a video using F6, the output file shows incorrect colors, as shown in attached media. The S&box logo appears orange instead of blue. But the green L4D background still appears green.

I'm using an RTX 3080 (driver 537.42) and Ryzen 7 5800X on Windows 11. No command line args for S&box, so I assume it's Vulkan.

### To Reproduce

1. Open S&box
2. Press F6 to record a video
3. Check the output video in steamapps\common\sbox\screenshots

### Expected behavior

The colors you see on your screen when recording should match the colors in the output video.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/8889285/c758e457-1901-4c39-b416-2138318bfdf1

### Additional context

The issue began in the past day or two.

**Comment by DevulTj** [comment]
Getting this too on a Ryzen 9 3900x paired with a RTX 3090.

**Comment by chrisspieler** [comment]
I updated to NVIDIA driver 551.23, and now the colors look correct, or maybe some S&box change coincidentally fixed it for me?

https://github.com/Facepunch/sbox-issues/assets/8889285/77b7964c-d4d6-41cd-83b3-640bb2cf88b7
