### ISSUE TITLE
Prop Component - Changes get stomped on play mode (Show Created Components)

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#4648]
![image](https://github.com/Facepunch/sbox-issues/assets/8184184/9a09fddd-4231-4971-a8ee-21f6ba8695f0)

![image](https://github.com/Facepunch/sbox-issues/assets/8184184/63615da2-73f8-4272-ad14-d4647878dee4)

Enabling "Show Created Components" and making any changes do not save when you hit play mode, I don't know if we should expose setting on the Prop Component for materials, tint?

**Comment by garrynewman** [comment]
This is by design, you're not meant to know those other things exist

**Comment by bakscratch** [comment]
It would be nice to be able to change the material groups/ tint if possible
