### ISSUE TITLE
Prop Component - ModelPhysics models don't initialize their physics upon component creation

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4650]
### Describe the bug

When creating a GameObject with the Prop component, the physics is not initialized if the model is a 'ragdoll' aka ModelPhysics one. The component has to be disabled and enabled again in order for the physics to kick in. Classic models initialize their physics fine on the first try.

### To Reproduce

1. Create a GameObject with Prop component
2. Use a model that would use ModelPhysics - for example the toilet
3. See that the prop has no physics unless the component is re-enabled

### Expected behavior

The physics should be initialized upon component creation/model set.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/1b893b5a-a656-47cb-a688-3f63f9a0070f

**Comment by garrynewman** [comment]
This is fixed now I believe

**Comment by Gmod4phun** [comment]
Nope, still seems to fail a physics init the first time.

https://github.com/Facepunch/sbox-issues/assets/5991682/a477c0c7-655d-4271-83b2-7196beb99263

**Comment by aylaylay** [comment]
Just pushed a fix for this, FYI that toilet prop has weird physics because it's using a mesh physics shape, we should make it impossible to enable physics on meshes because it's not supported.

**Comment by Gmod4phun** [comment]
Yep, seems to be good now. I did find another problem with modelphysics and tags, but I believe it is related to something else so I will close this and make a new issue.
