### ISSUE TITLE
Prop Component - Add a toggle for using ModelPhysics or regular ModelCollider

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4652]
### For?

S&Box

### What can't you do?

When creating a prop, using a model that is a 'ragdoll' (aka a model that would use ModelPhysics) will always apply the `ModelPhysics` component onto the prop.

When I want to make a prop that moves, has that kind of a model, but I only want to use standard `ModelCollider`, I have to do that manually by enabling IsStatic, and then adding a Rigidbody component to it.

I am not sure if it makes sense to do this, but I can see having the ModelPhysics vs ModelCollider as a user option, rather than automatic decision in the component based on the model.

### How would you like it to work?

I'd like it to work by having an option on the Prop component itself, similiar to Prop.IsStatic. It could be called lets say `Prop.UsesModelPhysics`.

UsesModelPhysics would use ModelPhysics instead of ModelCollider.

That way I can have toilets or shopping carts that can be thrown/pushed like normal props, but wouldn't simulate the individual physics parts, they would act as one collider.

### What have you tried?

I worked around it by enabling IsStatic on the prop, which provides it with ModelCollider, and then adding a Rigidbody component to it manually, to make it have actual simulated physics.

**Comment by garrynewman** [comment]
This makes no sense to me, but I get a feeling we're going to end up with a million options on prop. I want to keep it simple - so I added a button to break it into sub-components.
