### ISSUE TITLE
Cannot use env_sky entity in hammer due to it having no editable properties 

### ISSUE THREAD

**Issue by jkinz3** [Facepunch/sbox-issues#4655]
### Describe the bug

The env_sky entity in hammer has no editable attributes and cannot be used in maps. It also isn't visible in the viewport.

### To Reproduce

Steps:
1. Boot up s&box
2. Open up hammer
3. Try to place an env_sky entity.
4. Notice that the entity is placed but has no icon, and no attributes other than the transform are editable, rendering it useless.

### Expected behavior

The entity should be able to be modified and used in the maps lighting

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/6319937/2fc5c809-39fd-460f-9671-b95bc3214ae8)

**Comment by jkinz3** [comment]
I would respectfully argue that this should be placed at a higher priority. Not being able to use the env_sky lighting severely diminishes the quality of the graphics the game can do.

**Comment by bakscratch** [comment]
@handsomematt fixed this last week
![image](https://github.com/Facepunch/sbox-issues/assets/8184184/018d986a-8e8d-43db-a46b-c8a6b41fb389)
