### ISSUE TITLE
Huge delay when trying to upload a game

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4658]
### Describe the bug

When trying to upload a game I get a massive amount of warnings in the console, here's a log file:

[Log.log](https://github.com/Facepunch/sbox-issues/files/14109795/Log.log)

Takes ages to actually get to the file uploading stage.

### To Reproduce

1. Have game project with a decent amount of files
2. Try and upload it

### Expected behavior

Doesn't spend 30 minutes giving non-compile errors.

**Comment by handsomematt** [comment]
It shouldn't get stuck trying to compile things it shouldn't now.

**Comment by Fortune117** [comment]
Seems fixed now, thanks.
