### ISSUE TITLE
Add Require attribute to automatically GetOrCreate components on start

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4659]
### For?

S&Box

### What can't you do?

I am mildly inconvenienced by needing to null check and possibly get-or-create component properties of components. There should just be an attribute I can add to properties to make sure the component is created by the time OnStart is called.

### How would you like it to work?

```csharp
[Property, Require] public CharacterController Character { get; set; }
```
If a `Component` property with the proposed `Require` attribute is null right before OnStart, it should be automatically populated via `Components.GetOrCreate`.

### What have you tried?

```csharp
[Property] public CharacterController Character { get; set; }

protected override void OnStart()
{
	Character ??= Components.GetOrCreate<CharacterController>();
}
```

**Comment by GavrilovNI** [comment]
It would be better if it will work like in unity, so "required" will create required component if possible when component is added to gameobject or will not allow adding component with required attribute (in case of it being abstract). And then in on awake/on start you would get it being sure it exists.
Also if it will be attribute for property, how should it handle multiple properties of same type? Should it create one for each or should it share same component?

**Comment by garrynewman** [comment]
Added [RequireComponent]

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/658995e6-ee76-43f2-901b-0fdd5934091f)
