### ISSUE TITLE
Camera controls shouldn't snap cursor to centre of screen

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#4661]
> When orbiting/zooming the cursor hides and snaps back to the centre of the screen. I don’t see why you would want to hide the cursor, and orbiting/zooming should just move the cursor position like normal. Many programs have an icon for each operation which is nice.

Sbox: https://files.facepunch.com/Taylor/1b2711b1/sbox-dev_avtMdz8tBo.mp4
Maya: https://files.facepunch.com/Taylor/1b2711b1/maya_QA6QJOZE3o.mp4

Unity behaves the same as Maya.
Hammer hides the cursor and returns it to the original position.

**Comment by xezno** [comment]
Made it so they'll wrap around and stay inside the canvas now while remaining visible

https://github.com/Facepunch/sbox-issues/assets/12881812/955bda33-d0be-43bf-b0b0-854ccf19eacd

**Comment by handsomematt** [comment]
Nearly perfect - I'm having issues when the cursor leaves the scene view the camera goes to fuck

**Comment by xezno** [comment]
I can't reproduce that but I've pushed some stuff that might hopefully help

**Comment by handsomematt** [comment]
Works great, good job
