### ISSUE TITLE
Alt rc Zoom should use X axis too

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#4663]
Alt rc Zoom is only up/down - most programs have it up/down AND left/right. 

https://files.facepunch.com/Taylor/1b2711b1/maya_yZZsJl0wge.mp4

This is really useful because the most natural hand movement is probably diagonal.

The zoom and pan also feel inverted to most programs (it would be good to have these as an option in the settings?) both feel quite slow (again options to change this speed would be helpful)

The same goes for the scale function, it’s only up/down currently.

**Comment by MaxLebled** [comment]
Excellent idea +1

**Comment by xezno** [comment]
Added everything mentioned - you can find the settings for inverting & speed under the camera button in scene view:
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/76a8812f-13f4-476b-9fba-112557b7503d)

Max speed is 10x, let me know if that's not enough, it's the most I thought was really sensible for most use cases.
I've also made the default behaviour inverse to what it is now - so it'll match programs like maya instead - cos I think that's going to be the best going forward, sorry if it breaks your existing muscle memory.
