### ISSUE TITLE
Screen UI becomes invisible if there is a second camera rendering only depth and stencil

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4664]
### Describe the bug

Any screen UI disappears if there is a second camera rendering only depth and stencil with a higher priority than the main camera.

### To Reproduce

![sbox-dev_bNho008grt](https://github.com/Facepunch/sbox-issues/assets/11138884/4e6b754a-5d36-4d53-b668-dffe74f044b0)
In this picture I'm using a second camera to render world panels through the world.
Whenever I make a screen panel and try to have it display anything it doesn't appear on the screen at all.

### Expected behavior

I would expect the screen UI to appear in front of whatever other cameras might be rendering, maybe even just on top of the first camera rendered, as opposed to just not showing anything at all.
Maybe screen panel components need a camera reference to render to?

**Comment by fantasticaneer** [comment]
Can confirm after talking about this with Nolankicks, this means if you try to create a 'viewmodel' by drawing another camera with specific render tags on top of the main camera, all your UI gets erased by the presence of the second camera.

Maybe there should be a 'UI' clear flag for cameras?

**Comment by DevulTj** [comment]
The clear flags have no involvement in this, even if you've got 2 cameras it'll just render on the first camera's viewport. I'm looking into this currently.

**Comment by DevulTj** [comment]
![sbox-dev_3GOBPSIXii](https://github.com/Facepunch/sbox-issues/assets/22372616/5a25f7d4-c4a2-4d16-8353-db4a8f0043c1)
This should be working as intended now

**Comment by DeltaDesigns** [comment]
Normal razor panels work now but post processing components and other custom ui this isnt just a razor panel component that are on the main camera dont get passed through 

Uploading vlc-record-2024-02-24-00h36m07s-Desktop 2024.02.23 - 21.47.34.01.mp4-.mp4…
