### ISSUE TITLE
Game takes up to 20 mins to upload

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4669]
### Describe the bug

The game takes an unusual amount of time to upload and gives asset compile errors.

### To Reproduce

1. Try to update a project.

### Expected behavior

I should be able to upload my game within a few minutes.

### Media/Files

![Screenshot 2024-01-31 172317](https://github.com/Facepunch/sbox-issues/assets/95300917/cd40a45d-641c-4e02-a592-f6bcb47f7152)
![Screenshot 2024-01-31 171927](https://github.com/Facepunch/sbox-issues/assets/95300917/fc3f81fb-c7dd-4d46-bdce-20ac0f332e0f)

**Comment by xezno** [comment]
#4658
