### ISSUE TITLE
Some World Panels are functioning in the Editor but missing in the live version of the game

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4673]
### Describe the bug

In play mode in the editor there are two world panels that are visible to the player:
![image](https://github.com/Facepunch/sbox-issues/assets/7847372/2d6b4faa-2d1c-47dc-9eab-b42d61bab5be)

However in the live version of the game the panels are missing:
![image](https://github.com/Facepunch/sbox-issues/assets/7847372/6759a3b9-71bd-49e7-85ed-1a169391dcf4)

The world panels are really simple, just a little bit of razor and some scss.

### To Reproduce

1. Create world panels
2. Upload game to asset party
3. World panels are missing

### Expected behavior

Live version should match play mode in the editor.

### Media/Files

[Tutorial.razor.zip](https://github.com/Facepunch/sbox-issues/files/14118822/Tutorial.razor.zip)

This is the code for the world panels I use.

**Comment by Fortune117** [comment]
I just updated my game to the most recent build and the world panels appear now. I believe the bug still exists though, I'll see if it still happens. 

The world panels definitely existed in the scene for the live build where they didn't show up.

**Comment by garrynewman** [comment]
We'd need a repro for this
