### ISSUE TITLE
Move getting connections from Networking => Connection

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4676]
### What it is?

Currently we get connections from the Networking class.
( `Networking.Connections`, `Networking.HostConnection`, `Networking.FindConnection( Guid )` )

### What should it be?

They all return a connection. It would be more intuitive if they were in the Connection class like Connection.Local.
( `Connection.All`, `Connection.Host`, `Connection.Find( Guid )` ) 

![image](https://github.com/Facepunch/sbox-issues/assets/91832803/dc9aaa10-f950-4556-a945-a0419a3162eb)

**Comment by badandbest** [comment]
Was keeping Networking.HostConnection intentional?

**Comment by garrynewman** [comment]
No it was not - just done that
