### ISSUE TITLE
CSS Transitions Don't Work With `box-shadow`

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#4679]
### Describe the bug

`box-shadow` isn't affected by a transitions

### To Reproduce

Put `box-shadow` on an element with `transition: all ...` or `transition: box-shadow ...` and cause the `box-shadow` to change. It modifies instantly instead of going with the transition.

### Expected behavior

`box-shadow` should follow transitions.

### Media/Files

Browser:
https://github.com/Facepunch/sbox-issues/assets/33941498/4fe76b40-a380-4fdc-b4a8-a8e669299cbc

s&box:
https://github.com/Facepunch/sbox-issues/assets/33941498/c567e5cb-675a-47e9-bac7-b92198fb48e1

**Comment by xezno** [comment]
Should be fixed on next update
