### ISSUE TITLE
Camera Preview causes lag in Editor since Vulkan changes

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4681]
### Describe the bug

Having a GameObject with a CameraComponent selected shows the Camera Preview window which causes a lot of lag in the Editor.

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/9e5ad9db-5122-40ed-82d4-198f61ca208e)

### To Reproduce

Click on a GameObject with a CameraComponent

### Expected behavior

It shouldn't lag

**Comment by handsomematt** [comment]
#4644
