### ISSUE TITLE
Display static properties with `[Property]` attribute in the inspector

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4683]
### For?

S&Box

### What can't you do?

Make variables that are shared across all instances AND editable in the inspector.

### How would you like it to work?

I mark a variable as static and give it the `[Property]` attribute and it shows up in the inspector.

Would be good if it were also highlighted somehow, like if it were italic or colored differently or had an icon indicating it is static.

### What have you tried?

Setting the static variables in code, but it's more convenient to set them in the inspector.

### Additional context

This used to be a feature but was removed. I think there are valid use cases for it being allowed.

My current use case is that I would like to edit the tint of a powerup when it is active/inactive without having to set this across all of my levels. There are prefabs of course but then I wouldn't be able to set variable respawn delays, so having a mix of global and localized variables by allowing editable static properties is thus useful.

Also, why not?

**Comment by garrynewman** [comment]
This doesn't seem like a good idea.

**Comment by garrynewman** [comment]
Using statics like this isn't recommended, and by adding this feature we'd be encouraging it. Use a singleton component or a GameObjectSystem to hold state in a single place.,
