### ISSUE TITLE
Add `PrefabFile.Clone` method

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4684]
### For?

S&Box

### What can't you do?

Spawn a GameObject using a PrefabFile in a way that is intuitive and doesn't involve a method tucked in a seemingly unrelated class.

### How would you like it to work?

```csharp
public PrefabFile Prefab { get; set; }
...
var gameObject = Prefab.Clone();
```

### What have you tried?

```csharp
public PrefabFile Prefab { get; set; }

public GameObject SpawnPrefab()
{
  if ( Prefab is null ) return null;
  
  var scene = SceneUtility.GetPrefabScene( Prefab );
  return scene.Clone();
}
```

### Additional context

GameResource does not accept GameObject references so I have to refer to PrefabFiles and do it as written above.

**Comment by garrynewman** [comment]
Could a better option be to let GameResource's accept GameObject references?

**Comment by MrBrax** [comment]
I dragged a prefab file onto my GameObject property and it worked, was this not intentional?

**Comment by MrBrax** [comment]
<img width="744" alt="1706858994029" src="https://github.com/Facepunch/sbox-issues/assets/1517911/52d5813e-acfd-46d7-b3dd-6d328cdba5c2">

yea, can't show with dragging or fields because component system is still broken, but it's assigned as a gameobject
