### ISSUE TITLE
Properties don't hotload.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4688]
### Describe the bug

Changes made to properties don't hotload. This forces me to restart to get my changes.

### To Reproduce

1. Create a property with a backing field.
```c#
using Sandbox;

public sealed class MyComponent : Component
{
	bool _myProperty;
	
	[Property]
	public bool MyProperty
	{
		get => _myProperty;
		set
		{
			_myProperty = value;
			
			Log.Info( "Value has been changed." );
		}
	}
}
``` 
2. Make a small change in the set method ( e.g edit the log ) and compile again.
3. The changes don't hotload. Forcing you to restart to get your changes.

### Expected behavior

The changes made to my property should be hotloaded.

### Media/Files

As you can see in my console, the Set method doesn't seem to hotload. It even logs when there's no Log.Info left in the code.

https://github.com/Facepunch/sbox-issues/assets/91832803/3122745d-1e56-4bfe-9d2a-c1f731fcac52

### Additional context

* I am using Rider as my IDE. But I also tried Notepad++ just to make sure. The bug still happens.
* Tested with and without [Property] to see if it was some kind of code generation bug.
* The logs don't say anything.

**Comment by garrynewman** [comment]
If you deselect that GameObject and select it again, is it correct?

**Comment by badandbest** [comment]
I tried that. I also tried destroying the game object and remaking it. The console still doesn't log the correct message.

**Comment by badandbest** [comment]
Update: It seems to work if I do `hotload_fast 0`

**Comment by Metapyziks** [comment]
This might be specifically if only a string literal changes, I remember that being an edge case.

**Comment by Metapyziks** [comment]
Looking into this again now
