### ISSUE TITLE
Testing multiplayer with new instance of s&box broken

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4689]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/57276947/d28629c9-17c5-46f9-b042-2aeeb02601e3)

Gets stuck and never passes to game.

Client logs are pretty empty:

```Loading Network Assembly: [package.base]
Loading Network Assembly: [package.local.testing]
Error loading resource file "materials/decaltests/dirt_rocks_decal.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/particles/simulated/fireballs/fireball_v2.vtex_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/particles/electrical/electrical_arc_looping_e.vtex_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/decals/scorch1.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/particle/fire_burning_character/fire_burning_character.vtex_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/decals/molotovscorch.vmat_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/particle/fire_particle_4/fire_particle_4.vtex_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/particles/electrical/electrical_arc02.vtex_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/particles/lasers/beam_laser_soft_01.vtex_c" (Error: ERROR_FILEOPEN: File not found)
Error loading resource file "materials/particles/fpstest/fps30_flw.vtex_c" (Error: ERROR_FILEOPEN: File not found)
```

Host logs show it joining:
```
 02:38:36   GameMenu Player 'Trundler' has joined the game
 02:38:45   GameMenu 'Trundler (2)' has joined the game
```

### To Reproduce

1. Add Network to game
2. Press play
3. Join with new instance
4. Observe

### Expected behavior

Can join on second instance successfully

**Comment by trundlr** [comment]
May be related:
Can't seem to upload my game at all.
![image](https://github.com/Facepunch/sbox-issues/assets/57276947/aa6b2fd9-3afb-4239-a913-c138a6839e2b)

```
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_height.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_explode.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_emissive.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_eyesclosed.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu Not Compiled: maps/gr_beach.vmap.meta (IgnoreCompiledState set for type (asset_metadata))
 02:45:53   GameMenu Not Compiled: maps/gr_menu.vmap.meta (IgnoreCompiledState set for type (asset_metadata))
 02:45:53   GameMenu Not Compiled: materials/effects/lightcookies/tree_canopy_trans.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: materials/effects/water/water_deform.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: materials/reticle/reticle.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: materials/reticle/reticle_trans.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/bots/cogs_animated.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/bots/cogs_animated_alpha.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/bots/cogs_cloud.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_metal.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_fire_shotgun.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_normal.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_idles.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_opacity.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_incline_correct.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_rough.jpg (IgnoreCompiledState set for type (jpg_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_jetpack_poses.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/character_animations/citizenworm_backflip.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_minigun_aim.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/character_animations/citizenworm_backflip_charge.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_radiohold.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/character_animations/citizenworm_baseballbat_hit.fbx (IgnoreCompiledState set for type (fbx_asset))
 02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_slide.fbx (IgnoreCompiledState set for type (fbx_asset))
```

**Comment by Matt9440** [comment]
If it's helpful, I do not get any errors loading resource files but I get stuck here
![image](https://github.com/Facepunch/sbox-issues/assets/78914427/843d7670-8cbb-45f1-b82b-832db5cc1b6c)

**Comment by cs716** [comment]
> May be related: Can't seem to upload my game at all. ![image](https://private-user-images.githubusercontent.com/57276947/301940833-aa6b2fd9-3afb-4239-a913-c138a6839e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDAxODYsIm5iZiI6MTcwNjg5OTg4NiwicGF0aCI6Ii81NzI3Njk0Ny8zMDE5NDA4MzMtYWE2YjJmZDktM2FmYi00MjM5LWE5MTMtYzEzOGE2ODM5ZTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE4NTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjOTliYmY3NzJkNTVmZjBlNzlhOGRkMDgyMmM2MDczZWUwYmI5ZmQ0OGE4ZTI0NTgyYTEyYTg3MjJkYTg1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GrSEyW5Xv-C0m0M3zk68VyQWNz8CE8h_aBOJ0_ttdrE)
> 
> ```
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_height.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_explode.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_emissive.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_eyesclosed.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu Not Compiled: maps/gr_beach.vmap.meta (IgnoreCompiledState set for type (asset_metadata))
>  02:45:53   GameMenu Not Compiled: maps/gr_menu.vmap.meta (IgnoreCompiledState set for type (asset_metadata))
>  02:45:53   GameMenu Not Compiled: materials/effects/lightcookies/tree_canopy_trans.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: materials/effects/water/water_deform.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: materials/reticle/reticle.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: materials/reticle/reticle_trans.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/bots/cogs_animated.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/bots/cogs_animated_alpha.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/bots/cogs_cloud.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_metal.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_fire_shotgun.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_normal.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_idles.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_opacity.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_incline_correct.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/bots/materials/phong1_rough.jpg (IgnoreCompiledState set for type (jpg_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_jetpack_poses.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/character_animations/citizenworm_backflip.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_minigun_aim.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/character_animations/citizenworm_backflip_charge.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_radiohold.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu CompileIfNeededAsync took over 30 seconds models/character_animations/citizenworm_baseballbat_hit.fbx (IgnoreCompiledState set for type (fbx_asset))
>  02:45:53   GameMenu Not Compiled: models/character_animations/citizenworm_slide.fbx (IgnoreCompiledState set for type (fbx_asset))
> ```

I have the same issue, but the uploading is not an issue for me so I think it's unrelated.
![image](https://github.com/Facepunch/sbox-issues/assets/29966072/1bf97f20-0025-409a-b360-5e23603d2036)
![image](https://github.com/Facepunch/sbox-issues/assets/29966072/846d6763-296d-496a-9410-092574bb3653)

**Comment by garrynewman** [comment]
Fixed it

**Comment by trundlr** [comment]
Working now! Thanks garry!
