### ISSUE TITLE
NavMeshAgent.SetAgentPosition does nothing unless the Scene NavMesh is disabled.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4691]
### Describe the bug

I tried playing with SyncPosition and UpdatePosition, but nah. I sorta understand whats going on, but maybe some clarification is needed on what this method is really for.

### To Reproduce

Try to override the agent position, doesn't work.

### Expected behavior

unsure.

### Media/Files

![aaaaaaaaaaaaaaaaaaaaaaat](https://github.com/Facepunch/sbox-issues/assets/66768086/6e3f726a-adef-45a0-ba0d-fac701e8cda5)

### Additional context
```cs
	protected override void OnFixedUpdate()
	{
		_agent.SetAgentPosition( Vector3.Up * 32 );
	}
```

_No response_

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by dch-GH** [comment]
Works like how I expected now. Thanks
