### ISSUE TITLE
Get navmesh errors when reloading a scene

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4693]
### Describe the bug

When you respawn in my game, you reload the scene, since I've implemented navmesh, I've been getting these errors when I respawn.

### To Reproduce

Reload a scene with nav mesh.

### Expected behavior

I should not be getting errors.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/8be9eaae-4bb8-4e46-9d30-85e5ee05fece
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/6cd358e3-3a60-41d5-9648-9bca0e589b6a)

**Comment by garrynewman** [comment]
Should be fixed now
