### ISSUE TITLE
Scene version control detection broken

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4694]
### Describe the bug

When swapping a branch on Github or something you used to get a little "hey, we detected changes, want to reload whatever was changed?" 
This appears to have stopped working? And now you're left with an incredibly broken version of that project, which doesn't resolve until you reload. 

### To Reproduce

1. Attempt to swap to a branch with a changed .scene or so
2. Observe the lack of it detecting a change
3. If your scene is different enough you'll also see that it's probably fucked.
4. Restart s&box
5. God is good again 🙏 

### Expected behavior

Version control detection should be appearing, reloading everything and not completely breaking the scene.

**Comment by DevulTj** [comment]
Not super sure what happened here. We're not getting PostReload calls for GameResources when they're edited externally right now.
