### ISSUE TITLE
"Talker" game is client crashing

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#4697]
### Describe the bug

I'm having a client crash when I try to load "Talker". I've already contacted with Carson but apparently it's a crash that only happens to me.

[Log.log](https://github.com/Facepunch/sbox-issues/files/14152638/Log.log)

### To Reproduce

Just try to play Talker (?)

https://github.com/Facepunch/sbox-issues/assets/40291120/9927fb63-8b8a-48f3-b8c5-cca6fb89eceb

### Expected behavior

Get it fixed.

### Additional context

Other games works well to me.

**Comment by garrynewman** [comment]
This seems fixed now

**Comment by KaesarZZ** [comment]
Yeah all good
