### ISSUE TITLE
Allow extending ScreenPanel rendering logic

### ISSUE THREAD

**Issue by cohaereo** [Facepunch/sbox-issues#4698]
### For?

S&Box

### What can't you do?

Currently (at least to my knowledge), rendering RootPanels to a texture and back to the screen for panel specific effects (eg. a distortion effect) *is* possible by implementing a custom ScreenPanel with custom drawing logic, but this comes with a few annoying downsides (see below)

### How would you like it to work?

Making `ScreenPanel` extendable and allowing `OnRenderOverlay` (or a separate method) to be overridden to allow for custom rendering logic would remove the need for a custom ScreenPanel implementation, thus getting rid of any weird quirks related to ScreenPanel/IPanelComponent-specific logic.

### What have you tried?

Reimplementing `ScreenPanel`
- New component based on the ScreenPanel code
- add a render hook to the active camera in order to draw the RootPanel
- manually assign all parents of `PanelComponent`s, as `IPanelComponent` and `IRootPanelComponent` are marked as `internal` and cannot be implemented project-side
    - Disabling and re-enabling the panelcomponents makes them search for a new parent, which causes the panel to disappear.

Additionally, the custom ScreenPanels are not picked up by the z-sorting logic in `Scene.OnRenderOverlayInternal`, and thus can't be drawn inbetween regular ScreenPanels

**Comment by cohaereo** [comment]
Custom ScreenPanel implementation for reference: https://gist.github.com/cohaereo/5642e6d4d13bb25c843247f09214eb8e

**Comment by garrynewman** [comment]
What is it that you want to do?
