### ISSUE TITLE
2D Sprite Animation Helper

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4699]
### For?

S&Box

### What can't you do?

You’re unable to easily create 2d sprite animations.

### How would you like it to work?

I’m thinking something similar to the Citizen Animation helper, being able to change which sprites your want to use for different actions.

### What have you tried?

I’ve heard in the discord it’s technically possible. And I think it would be very useful. So instead I’m proposing an easy to use solution.

**Comment by B0zy** [comment]
It list on their Documentation ( https://docs.facepunch.com/s/sbox-dev/doc/project-status-jdXQfVS3NL ) that there is no 2d editor support atm and with only basic sprite support
![image](https://github.com/Facepunch/sbox-issues/assets/40073828/3b64e3ba-2a3c-418b-8271-fb670f5722ff)

**Comment by garrynewman** [comment]
This is better of as a discussion rather than an issue
