### ISSUE TITLE
Addon/Gamemode compression, encryption and security. 

### ISSUE THREAD

**Issue by McCheekiBreeki** [Facepunch/sbox-issues#47]
**How would you like it to work?**
Similar to how Garry's Mod had access to the LZMA compression algorithm through `util.Compress` and `util.Decompress,` could that be replaced with access to LZ4 which on paper is a much faster option?

**Additional context**
LZ4 used alongside AES (and the AES-NI instructions built into CPU's of the past decade or so) and OpenSSL or LibSodium could be used as an incredibly fast, secure, signed packaging method for gamemodes. LZ4 can net gigabytes per second for random access on either normal or HC (high compression) modes. This is perfect for a release system, you work on the branch of your gamemode using hot-loading and once you are done, you sign it and secure it through the online portal which could potentially also allow you to set up a CDN-like system for downloading and loading the content on the client. Where AES and OpenSSL come in are encryption and signing/verifying packages, both used hand in hand, working together almost to load the content and prevent any potential tampering/man-in-the-middle attacks that could arise (though that is a very unlikely scenario.) This could greatly benefit S&box, and I do feel that as the successor to Garry's Mod it should have features that help content creators secure their own work and prevent it from being stolen.

**Comment by garrynewman** [comment]
You guys don't really need to worry about this stuff.
