### ISSUE TITLE
Shader Graph Compile Error

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-issues#4700]
### Describe the bug

Shader graph does not compile any shader

### To Reproduce

1. Go Make a Shader Graph File
2. Add a Color Modifier 
3. Save it to compile
4. Error Compiling

### Expected behavior

For it to compile successfully 

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/40073828/06a2c7f9-d76b-43a8-a4ae-f7f8f26b1b60

Shader Compile Error out 
```
Cannot find shader shaders/bozshader.shader in the current content folder D:\SteamLibrary\steamapps\common\sbox\addons\citizen\;D:\SteamLibrary\steamapps\common\sbox\addons\base\;D:\SteamLibrary\steamapps\common\sbox\core\;D:\SteamLibrary\steamapps\common\sbox\.source2\cloud\;D:\SteamLibrary\steamapps\common\sbox\.source2\temp\! 
```
Nothing else is logged even in log files

**Comment by Retroeer** [comment]
getting this error again even on normal shaders, was fixed in #4600, but i guess re-broke
