### ISSUE TITLE
Model Renderer Tint Issue

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-issues#4702]
### Describe the bug

Not really how to verbally describe it however when adjusting the alpha of a tint on a Model Renderer it leaves a sort of textured opacity in a way. 

### To Reproduce

1. Create GameObject with Model Renderer
2. Adjust Tint to any colour & its alpha down

### Expected behavior

Shouldn't result in any textured like opacity instead it should appear smooth.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/40073828/4f764dfc-efc4-4d25-bb59-11d6c930b529)

**Comment by B0zy** [comment]
This also happens on Skinned Model Renderers

**Comment by Gmod4phun** [comment]
Looks like dithering, happens with materials that don't have the Translucent option enabled.

**Comment by B0zy** [comment]
> Looks like dithering, happens with materials that don't have the Translucent option enabled.

Tried it with both a material that had Translucent enabled ( in the screen shot ) and one without resulted in the same effect

**Comment by garrynewman** [comment]
This is really just how it is, unless the shader itself supports it.
