### ISSUE TITLE
NavMesh.GetRandomPoint gives strange results

### ISSUE THREAD

**Issue by CASHNOW** [Facepunch/sbox-issues#4703]
### Describe the bug

As the title suggests `NavMesh.GetRandomPoint()` is giving me strange results, either with the vector 3 position and radius, or given a bbox. It feels like the box isn't getting calculated correctly.

### To Reproduce

Use `NavMesh.GetRandomPoint` as I have in `randomidlepoint = (Vector3)Scene.NavMesh.GetRandomPoint( BBox.FromPositionAndSize(destination, Idle_Radius ));
navMeshAgent.MoveTo( randomidlepoint );`

Display it with
`Gizmo.Draw.LineBBox( BBox.FromPositionAndSize( destination, Idle_Radius  ) );`

### Expected behavior

The returned point to be within the box.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/36146531/16a8cab9-5524-48ac-a463-4039323fd2a5

**Comment by CASHNOW** [comment]
@garrynewman 

I had a sudden thought about the shape of those random points I was getting and decided to make another test. They aren't quite so random. They are stuck to the triangle of the navmesh, sorta. The bounding box is not touching some triangles in the video.

https://github.com/Facepunch/sbox-issues/assets/36146531/f65c4c13-7f2c-4eeb-a993-22dd31e66826

**Comment by garrynewman** [comment]
Yeah this is working correctly, actually. The random point radius is for capturing the polygons in the navmesh, not the point itself.
