### ISSUE TITLE
Using NavAgent crashes the editor

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4704]
### Describe the bug

Whenever I call anything related to the nav agent, my editor just crashes.

### To Reproduce

Unsure what exactly is causing the problem but my repo is uploaded [here](https://github.com/ScoutWozniak/RetroFPS).

### Expected behavior

The editor shouldn't crash.

### Media/Files

Here is my [log file](https://github.com/Facepunch/sbox-issues/files/14156096/Log.884.log) from one of the crashes.  Unsure if it's completely related as newer attempts don't show this error.

**Comment by garrynewman** [comment]
When you say crash, do you mean it exits to desktop?

**Comment by ScoutWozniak** [comment]
Yep, whenever anything from NavAgent is called in code (in this video its on OnEnabled)
https://github.com/Facepunch/sbox-issues/assets/99102549/16d7a185-0b14-4663-9c7b-cd9676da835c

**Comment by ScoutWozniak** [comment]
Fixed with latest update
