### ISSUE TITLE
Save camera settings in view layouts.

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#4705]
### For?

S&Box

### What can't you do?

Every time i reboot s&box, camera settings on scene are reset.

### How would you like it to work?

Save camera settings in view layouts.

### What have you tried?

Save camera settings

**Comment by aylaylay** [comment]
These settings save and load for me already, have you got repro steps of this not working?

**Comment by aylaylay** [comment]
We had an internal report about it. It all seems fine to me so I'm seeking repro steps if this is still happening. @somethink000
