### ISSUE TITLE
Cloud components

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4706]
### For?

S&Box

### What can't you do?

Download and use community-made components off of https://asset.party/.

### How would you like it to work?

When you go to add a component to a GameObject, you can click "Pick From Cloud" and search through components that people have uploaded to the site. Or it could have its own category.

Just like models, you can preview the code in the file before downloading it to make sure it's not a joke or might do something you don't want to your project.

When you select a file, it is downloaded into your cache. Then it is copied to `code/cloud/<component-name>.cs` and added to the GameObject. The local copy is so that you can edit it for your purposes.

### What have you tried?

I've shared a useful component before on the Discord, but you can't easily search it up.

### Additional context

I think this could be a great feature because components can do so many amazing things that we might not have individually thought of. And there are plenty of things that you wouldn't have to spend time making yourself.

You could, for example, select various character controllers and see which one is the best fit for your game. And interactables like spinners, doors, buttons. Why waste time programming that stuff yourself when it's on the cloud?

**Comment by garrynewman** [comment]
I think this kind of speculative idea stuff is best off as a discussion
