### ISSUE TITLE
Event.Register 'Collection was modified. Enumeration operation may not execute'

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/sbox-issues#471]
**Describe the bug**
![image](https://user-images.githubusercontent.com/6713261/125222514-22b31480-e298-11eb-9fdf-d145829999ce.png)

**To Reproduce**
https://github.com/Nebual/sandbox-plus/pull/1/files#diff-121b05cabbf09c1373a4c61a52351233a569c2eba70e44b68e67aa21ea61126fR325

**Expected behavior**
The new object will use the Tick event until unregistered.

**Comment by thegrb93** [comment]
Yes it's still an issue

**Comment by robotboy655** [comment]
I think this is fixed. Both running your code (fixed up) and what I believe a minimal repro would be given the error message:
```csharp
	[ServerCmd("event_test2")]
	public static void EventTest2(int num)
	{
		Event.Run( "event.test2" );
	}

	[Event("event.test2")]
	public void OnEventTest2()
	{
		DuplicatorPasteJob testInst = new();
	}

	public class DuplicatorPasteJob
	{
		public DuplicatorPasteJob( )
		{
			Event.Register( this );
		}

		[Event.Tick]
		public void Tick()
		{
		Log.Info( $"DuplicatorPasteJob Tick" );

		}
	}
```  

Appear to be working.
