### ISSUE TITLE
Two component references with different components inheriting the same class will have one overriding the reference of the other

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4710]
### Describe the bug

If you have two components inheriting the same component, and you reference both of them inside properties, they will have the same component ID, causing the first reference to override the second.

### To Reproduce

1. Clone https://github.com/yuberee/bugrepro/tree/main/bugrepro
2. Open minimal.scene
3. Inspect the TESTOBJECT to see that both components are referenced
4. Go to play mode
5. Check console to see that the first component fired twice

or alternatively, view the .scene file directly from github:
https://github.com/yuberee/bugrepro/blob/b90818526b30d3dc1ca7a92147272e5c77639f69/bugrepro/Scenes/minimal.scene#L114
https://github.com/yuberee/bugrepro/blob/b90818526b30d3dc1ca7a92147272e5c77639f69/bugrepro/Scenes/minimal.scene#L119

Their ID is the same.

### Expected behavior

I assume since the property takes in OriginalComponent it's casting both of them as that before generating an ID/serializing them to json instead of using their actual type of InheritedComponentFirst and InheritedComponentSecond.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/59583743/28c492a1-3283-4492-b61e-3c0c8898df39

**Comment by DevulTj** [comment]
This is because they don't have IDs yet

**Comment by DevulTj** [comment]
Is this still happening @yuberee?

**Comment by yuberee** [comment]
Oh right, the component ID updated fixed this.

**Comment by DevulTj** [comment]
Good to hear
