### ISSUE TITLE
Map Instance doesn't reload map sometimes

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#4716]
The Map Instance Component doesn't reload the map correctly at random points forcing you to restart the engine to get the changes.

I am compiling the map then toggle the map instance component to get the changes, sometimes it works fine but sometimes I am forced to reload the engine to get the latest changes. Would it also be possible to automatically update the map with the new changes from the vpk without having to enabled/disable the component?

**Comment by kurozael** [comment]
@bakscratch Is it a local map or you're re-compiling and then publishing to Asset Party and expecting it to reload?

**Comment by bakscratch** [comment]
Local maps is where I was having the issue

**Comment by MrBrax** [comment]
i've noticed it in the past week

**Comment by kurozael** [comment]
> > > i've noticed it in the past week
> 
> > 
> 
> > This is after a map compile you aren't seeing it update in the editor / map instance?
> 
> 
> 
> it never updates by itself, i have to disable and re-enable the map instance component, but sometimes even that doesn't work so i have to restart the editor

It's so weird, it updates automatically every time for me, what kind of map compile options are you using?

**Comment by MrBrax** [comment]
> It's so weird, it updates automatically every time for me, what kind of map compile options are you using?

![1709281575368](https://github.com/Facepunch/sbox-issues/assets/1517911/fee72bab-d1f7-46a0-a053-047802812705)
![1709281627627](https://github.com/Facepunch/sbox-issues/assets/1517911/b9a1685e-e3e0-4dec-8355-b4548b7cc36e)

i changed the map instance path from maps/climb.vmap to climb.vpk earlier and thought that would make a difference but it doesn't

**Comment by bakscratch** [comment]
> @bakscratch have you experienced this again recently? :)

Yes I've still noticed it happening

**Comment by andy013** [comment]
If you delete and retype the map instance name in the scene component, does it still load the old version?

**Comment by MrBrax** [comment]
> If you delete and retype the map instance name in the scene component, does it still load the old version?

yes it does. i think this might have something to do with closing the scene and re-opening it again. it still never auto-updates.

**Comment by Fortune117** [comment]
I have this issue as well, but disabling and then enabling my map component loads the newly compiled version.

**Comment by kurozael** [comment]
I'm fairly sure I've finally fixed this. Try with the next build and lemme know, thanks @Fortune117 for letting me test on your project.
