### ISSUE TITLE
Implement melee animations and hold types

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4717]
### For?

S&Box

### What can't you do?

For melee, there is currently only a punching animation, I think there was different melee types to select but they've never been implemented and are missing animations.

### How would you like it to work?

The following melee holdtypes and animations would be nice:

- Two handed melee (Sledge hammers, baseball bats, big swords)
- One handed melee (Small hammer, crowbar, small sword)
- Knife (Could be just one handed melee?)
- Spear (Could also work for battering ram or fighting stick)

Different types of swing animation to specify would be great as well, for example left to right, up to down, stab etc... For example I don't see people stabbing with sledge hammers.

### What have you tried?

Most games just reuse the punching animation and parent whatever weapon they have to the hand, which needless to say looks awful.
A few games have custom animations, but from what I've heard the process of adding animations to the citizen is currently undocumented and uncomfortable.

### Additional context

Tagging @MaxLebled because I noticed a similar request that ended up going stale. It's not urgent but I'm putting this up for the future.

Here's a funny task list to keep the developers entertained:

- [ ] Two Handed Hold Type
- [ ] Two Handed Swing Animations
- [ ] One Handed Hold Type
- [ ] One Handed Swing Animations
- [ ] Animgraph Implementation

**Extra goals:**

- [ ] Knife Hold Type
- [ ] Knife Swing Animations
- [ ] Spear Hold Type
- [ ] Spear Swing Animations

**Comment by MaxLebled** [comment]
Already on my list internally — but not very high up the priority list yet. I'll close this one as duplicate
