### ISSUE TITLE
Add arbitrary pre-computed lipsync for use with the MusicPlayer class when it is playing an audio clip through a Citizen model

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4723]
### For?

S&Box

### What can't you do?

Right now you can only use lipsync when the audio stream is of a microphone, either you own or other players', I'd like to be able to use it for making NPCs talk with their lips moving correctly.

### How would you like it to work?

I'm thinking a "LipSync" component you can just run LipSync.PlayAudio("path/to/file.mp3").
Could also let you put in a sound event but my use for it requires external MP3 paths...

### What have you tried?

Right now I'm just approximating mouth opening through the amplitude of the audio clip but it looks very rough and I'd love to have nice lipsync on it instead.

**Comment by aylaylay** [comment]
This most likely will be implemented on sound handles, like I've done for amplitude, opt in to them with flags

**Comment by ShadowBrian** [comment]
Completely unrelated to what I'm requesting brax I think you should probably ask shit like that on discord...

**Comment by MrBrax** [comment]
then you are probably misunderstanding my question? or are you not talking about lip syncing an audio file on the citizen model?

**Comment by ShadowBrian** [comment]
> then you are probably misunderstanding my question? or are you not talking about lip syncing an audio file on the citizen model? and i will not join the discord again because the record of people speaking are not publically visible

A while back Layla implemented automated lip syncing for people using microphones in multiplayer, what I'm asking for is for that system to be usable for any sound clip so we get automated lip syncing, it has nothing to do with the old source 2 specific lip sync tool because that requires a bunch of up-front setup whereas this new lip sync system is like 80-90% as good but just runs on the fly at runtime.

**Comment by MrBrax** [comment]
> > then you are probably misunderstanding my question? or are you not talking about lip syncing an audio file on the citizen model? and i will not join the discord again because the record of people speaking are not publically visible
> 
> A while back Layla implemented automated lip syncing for people using microphones in multiplayer, what I'm asking for is for that system to be usable for any sound clip so we get automated lip syncing, it has nothing to do with the old source 2 specific lip sync tool because that requires a bunch of up-front setup whereas this new lip sync system is like 80-90% as good but just runs on the fly at runtime.

gotcha, i thought facepunch made that lipsync tool. if it's as good as you say i probably won't mind, i just enjoy when the lipsync is more than just half life 1-esque mouth dropping.

**Comment by aylaylay** [comment]
I tool I made to manually make phonemes is probably broken now. It'll have to be remade at some point with a way to use the automatic lipsync that you can edit after and save to the sound meta.

**Comment by ShadowBrian** [comment]
Yeh makes sense, you'd just have it estimate phonemes and then you can scrub through and edit what isn't quite right.
Doesn't apply to my use for it since I'm not setting stuff up upfront but generating AI voices through HTML calls and getting mp3s back.

**Comment by ShadowBrian** [comment]
> > The tool I made to manually make phonemes is probably broken now. It'll have to be remade at some point with a way to use the automatic lipsync that you can edit after and save to the sound meta.
> 
> that sounds like a great idea, best of both worlds. touching up the automated sequence 👍 i don't wanna go too off-track here, but are broader facial expressions like eyebrows or mouth smiling part of this, or is that a whole another can of worms? it looks very robotic with only the mouth moving.

phonemes are just blend shapes, I'd guess you'd be able to add any other blendshapes to whatever phoneme data you're using anyway and it'd layer ontop.

**Comment by aylaylay** [comment]
I'll get to all this after hack week

**Comment by aylaylay** [comment]
This will have to be done after the new audio stuff is merged. (which should make it even easier to implement)

**Comment by aylaylay** [comment]
SoundHandle can now choose to process lipsyncing

**Comment by ShadowBrian** [comment]
https://github.com/Facepunch/sbox-issues/assets/11138884/9ac730d0-c7b3-4421-9156-3b441bbae285
