### ISSUE TITLE
Bring back the functionality of old particles.

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4724]
### What it is?

Working with particles is a pain, in the olden times you'd make your particles, play them from anywhere in the code and be done with it.
Now you need components, emitters, handlers to destroy both if you want it to play once, prefabs, and whatnots.

### What should it be?

Particles should be treated exactly like SoundEvent, just play them and pack up for the day, or let them loop and handle them later.

There's many advantages to the new particle component but they are very limiting with what you're able to do with them and feel like an odd step in between the transition from Particle Editor to Particle Graph. (Which I'm hoping is the final goal since Particle Editor isn't being supported)

**Comment by Matt9440** [comment]
Agree with this, I don't know what the future plans for the particle system are but at the time of writing I feel that having a component solely for the purpose emitting particles is unnecessary (the equivalent of having a component for emitting a sound). I'd love it if I could reference a `ParticleSystem` in a `[Property]` on any component and just call something like `Emit( Transform ) `on it.

**Comment by garrynewman** [comment]
That's cool Matt because that's exactly what you can do 👍

**Comment by yuberee** [comment]
I've tried 
```
var particle = new SceneParticles( Scene.SceneWorld, Particle );
particle.SetControlPoint( 0, Transform.World );
particle.Transform = Transform.World;
```
and wasn't able to get much out of it.
Going through other Particle* classes I couldn't find any other Emit like method.
Are there any examples we could look through?

**Comment by Willco2** [comment]
The `ParticleEffect` component is what you'll want, not `SceneParticles`. It has an `Emit(position)` method.

**Comment by Fortune117** [comment]
The new particle system does have a way to destroy itself once the effect is done, so it can be as simple as cloning a prefab in one line and then forgetting about it.

**Comment by yuberee** [comment]
@Willco2 @Fortune117 
The point of this is that you shouldn't need a component or prefab to create a particle. Imagine if you needed to do all of that to play a sound or display gizmos. (Hoping this doesn't give the developers an idea)

**Comment by garrynewman** [comment]
I disagree, this particle system is component based. If you want to make your own particle system that isn't particle based it's totally possible - but I don't think we should include that by default.

**Comment by Fortune117** [comment]
> @Willco2 @Fortune117 The point of this is that you shouldn't need a component or prefab to create a particle. Imagine if you needed to do all of that to play a sound or display gizmos. (Hoping this doesn't give the developers an idea)

In my mind it's a lot more powerful to spawn a prefab. It's not really any more effort than setting up a vpcf, and since particles can delete themselves it's about as much code to manage. You can even let the particle handle all the messy stuff if it's going to stick around.

This is how I spawn particles on weapon hits.

```CS
	if ( effectPrefab is not null )
	{
		effectPrefab.Clone( hitEvent.TraceResult.HitPosition, Rotation.LookAt(hitEvent.DamageEvent.Direction) );
	}
```
Do you have an example of what you're trying to do that this doesn't work for?

**Comment by yuberee** [comment]
Just for transparency, is particle components the new standard or will there be a Particle Graph to replace the old Particle Editor in the future?
Because much of what I dislike about particle components is how unintuitive they are.
They've got their uses, but as of now you're stuck tweaking variables in a shrunken inspector with no real indication of what you're making, to check your progress you have to manually play the particle in play mode or create a separate component to display them as gizmos in the editor. As a visual effect it's important to have the "visual" part when creating it.
Now I'm not here to rant about the situation since clearly it will be worked on in the future, just saying we're in an awkward spot right now.

**Comment by garrynewman** [comment]
I don't understand, how are they not visible? They should play when you have them selected in the editor

**Comment by yuberee** [comment]
I'm getting off topic now, it was particle components that only emitted once that in my experience didn't show up, I'll test them later with my same setup when home and open an issue if it persists.

I guess all I wanted to know if a Particle Graph is planned, if it is then all my complaints are irrelevant and I'll gladly wait it out, promising I won't complain for at least 6 months.

**Comment by garrynewman** [comment]
No not planned
