### ISSUE TITLE
Editor loads most recently opened scene upon relaunching project, rather than the scene(s) that were still open on exit

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4726]
### Describe the bug

This may seem a little confusing but it makes sense in terms of use case.
When you close a project and reopen it, you expect that the scene(s) you _had_ open is what will be resumed upon reloading the project.
But instead, what happens is that _the scene that was most recently opened_ will resume.

For example: if you open Scene1, Scene2, and Scene3, and then close Scene3, leaving Scene1 and Scene 2 open, then close the editor, and then reopen your project, the editor will launch with Scene3 open, rather than Scene 1 and/or Scene 2, which is what I would expect.

### To Reproduce

1. Open three scenes (ie: 1, 2, and 3)
2. Close scene 3
3. Close the editor / project, leaving scenes 1 and 2 open
4. Reopen the editor / project
5. The editor will launch with Scene 3

### Expected behavior

The scene or scenes that you left open upon exiting the project should open.
This is because you may be working in, for example, 'MainScene' and need to open 'Reference Scene 1' and then close it again. It doesn't make sense if you then close the editor with 'MainScene' saved and open, for the editor to only open 'Reference Scene 1' upon relaunch.

**Comment by CarsonKompon** [comment]
Added this in the most recent commit, will restore any opened scenes/prefabs you had instead of just the most recently opened 👍
