### ISSUE TITLE
Collider component changes the physics behaviour of rigidbody object

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4727]
These 2 cubes have the same script - the only difference is that one has a collider enabled and the other doesn't. 
Why is their physics behaviour different (as if the collider is causing massive damping?)
Even if the collider is a trigger, same thing happens.

https://github.com/Facepunch/sbox-issues/assets/1173137/8921937a-1070-404e-9941-c644f2eebfa9

Movement is handled like this:
```
protected override void OnFixedUpdate()
{
	Rigidbody.ApplyForce( Transform.Rotation.Forward * 500f );
	Rigidbody.PhysicsBody.SmoothRotate( Rotation.LookAt( Vector3.Zero - Transform.Position ), 0.3f, Time.Delta );
}
```

Repro project: 
[ColliderTest.zip](https://github.com/Facepunch/sbox-issues/files/14181351/ColliderTest.zip)

**Comment by Metapyziks** [comment]
I'm guessing it's because the masses will be different.

Try doing this:

```csharp
Rigidbody.ApplyForce( Transform.Rotation.Forward * 500f * Rigidbody.PhysicsBody.Mass );
```

**Comment by ryleigh** [comment]
Thank you! I thought Mass only cared about the rigidbody, didn't know it was based on the dimensions of the collider.

**Comment by Metapyziks** [comment]
It's not always clear why / when the mass gets recalculated, so maybe there's something we can rethink here.

**Comment by ryleigh** [comment]
Also a bit unintuitive that adding a trigger collider adds more mass... triggers seem weightless to me.

**Comment by aylaylay** [comment]
Mass is calculated from shapes
