### ISSUE TITLE
Console Command "Disconnect" not working

### ISSUE THREAD

**Issue by craighulme** [Facepunch/sbox-issues#4728]
### Describe the bug

typing "disconnect" into the client console ( ` ) usually disconnected you to the main menu, like many source games.

### To Reproduce

1. Press `
2. Type "disconnect"
3. Broken?

### Expected behavior

Takes you to main menu

### Additional context

Last I remember, this actually worked on s&box. It even is registered as an active valid command.
I've just installed the game fresh, with no modifications at all since its fresh PC, fresh install.

Unsure if this is game specific but I had this with 2 games so far. Works when I'm "downloading/connecting" but once I've connected the command doesnt work.

**Comment by DevulTj** [comment]
Should be the case now.
