### ISSUE TITLE
ICollisionListener does not work on Model Physics component

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4730]
### Describe the bug

None of the methods ICollisionListener implements are called, I think it just doesn't recognize model physics.

### To Reproduce

- create a ragdoll / other modelphysics object
- implement ICollisionListener in a script on the object
- Log.Info() in OnCollisionStart()

### Expected behavior

OnCollisionStart() should print something

**Comment by garrynewman** [comment]
ModelPhysics should really be creating rigidbody components rather than how it works now.

**Comment by aylaylay** [comment]
This should work now
