### ISSUE TITLE
Editor displays duplicate components

### ISSUE THREAD

**Issue by kira0x1** [Facepunch/sbox-issues#4733]
### Describe the bug

When searching for a component when adding a component in the inspector, it will display duplicates of all components.

### To Reproduce

Im not entirely sure on how to repro this issue, I havent done anything special besides possibly removing and re-adding [Property] tags a couple times and then reordering variables but thats just a guess.
sorry i couldnt be more helpful, just wanted to bring this issue up.

its still a basically blank project from the initial minimal template, and only added 2 new components which have a few lines of code in them.

### Expected behavior

Display only one of each component

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/13779328/fee17af9-aa0c-4cd9-8740-0cc5d308a615)

### Additional context

os: windows 11
gpu: 3070ti
ram: 32gb ram,
cpu: intel i5-12400F

**Comment by DevulTj** [comment]
can't seem to repro this

**Comment by kira0x1** [comment]
> can't seem to repro this

when i get home im going to try doing what i did this morning, and see if I can find a reproducible way to get this error to show up.

but tbf it was a pretty blank project and not much happened between creation  and this error showing up besides me creating components and reopining the project.

**Comment by kira0x1** [comment]
i dont seem to be able to repro, so ill just close it for now i guess.
