### ISSUE TITLE
Input Action remapping ingame

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4735]
### For?

S&Box

### What can't you do?

Remap what the inputs are at runtime, thus I have no way of allowing players to rebind their controls to their liking.

### How would you like it to work?

`Input.RemapAction( "Action Name", Input.LastKeyCodePressed );`
and/or
`Input.RemapAction( "Action Name" ); Input.StopRemapping();`
-which would grab the next key you press and set the supplied action's key.

### What have you tried?

I tried looking through the Input class and the API and asking on Discord but it's not there.

### Additional context

We used to have a way. I have a game that calls for an unconventional control scheme so I know some people may want to rebind it.

**Comment by DevulTj** [comment]
We have an API for this, but not sure if it works right now: `IGameInstance (SetBind, GetBind, ResetBinds, SaveBinds)`

**Comment by DevulTj** [comment]
Thanks for letting me know. This is something we'll look into soon.

**Comment by DevulTj** [comment]
I think our best approach should be to implement a modal for you to update your game-specific binds. I'll get on that this week.

**Comment by DevulTj** [comment]
![sbox_1wbbS8A88U](https://github.com/Facepunch/sbox-issues/assets/22372616/7231e166-cc2f-4a36-8595-efbad5f48cb1)
Pending a proper UI design pass, I've added a modal that lets you do this. `Game.Overlay.ShowBinds()`

**Comment by DrakeFruit** [comment]
just so not every single game has to implement a button for this, could there be a console command to show the modal too?

**Comment by DevulTj** [comment]
I'm pretty sure I'm using all public API stuff for this modal, so it should be working for you too. Look at BindsModal.razor in the menu addon that's shipped with the game.

**Comment by DevulTj** [comment]
I'll look into this

**Comment by PolSpock** [comment]
Also, i would like to mention another sub-question :
What about in-game editing of `Sandbox.Preferences.FieldOfView` and `Sandbox.Preferences.Sensitivity` (and others)?

Currently, these fields are only `get` and the only solution currently is to quit the current game and edit values: which is quite annoying for the gaming experience

**Comment by DevulTj** [comment]
Ideally they'd be editable in-game from the menu

**Comment by DevulTj** [comment]
Let me know how this is for you now, it's working for me. I'm going to add a quick utility to testbed for this now.

**Comment by ceitine** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/19620198/8a01b6a8-262a-4bf1-beb3-e5f98cae78ac)
Is this still the preferred way of doing this?
If so, how long will till we have to change it again? :D
