### ISSUE TITLE
ModelCollider not updated in game but updated in Scene when playing animation

### ISSUE THREAD

**Issue by quntherdev** [Facepunch/sbox-issues#4736]
### Describe the bug

On a fridge model, I've made an animation to open the door, parented to the bone Door_1. On scene, I added a child GO to this bone, containing the ModelCollider of the door.

Just like this (due to testing, I spaced the collider from the door):
![image](https://github.com/Facepunch/sbox-issues/assets/125770500/92ad1a28-f7cc-40f6-930b-0d06565e82a4)

When playing, on the stage, the collider is moved as expected. But when I move with my player controller, the obstacle (the collider) is at its original location, it seems that it does not follow the rotation of its bone parent ingame :
![image](https://github.com/Facepunch/sbox-issues/assets/125770500/e427b975-0c22-4605-9600-af78e9c1d08a)

### To Reproduce

1. make a model
2. make an animation on it
3. on the bone animation in scene, add a child GO
4. on this GO, add a modelcollider
5. play game,
6. run animation 
7. see the collider moving well on scene, but feel the obstacle at the original collider location

### Expected behavior

In game, the collider should be felt just as we see it in the scene when playing the animation

**Comment by aylaylay** [comment]
please include a downloadable repro

**Comment by aylaylay** [comment]
@quntherdev

**Comment by quntherdev** [comment]
Reproduction: https://github.com/quntherdev/issue4736/tree/main

![sbox-dev_d6BZyMXLHV](https://github.com/Facepunch/sbox-issues/assets/125770500/9f30b87b-2b5f-4338-a268-7da9bcaec825)
![image](https://github.com/Facepunch/sbox-issues/assets/125770500/2e7d335e-e7c9-4018-a1a1-a364a5014361)

**Comment by aylaylay** [comment]
Thank u

**Comment by aylaylay** [comment]
I'll try to support this, but I'll be supporting it on ModelPhysics instead of ModelCollider, it will have modes for physical and animated. Is that okay for you?

**Comment by aylaylay** [comment]
The initial issue about parenting a collider to an animated bone object seems to work. The repro seems to be a different feature you're wanting.

**Comment by aylaylay** [comment]
I've added support for this through ModelPhysics component with MotionEnabled set to false - the physics bodies will be driven by the renderer.


https://github.com/Facepunch/sbox-issues/assets/1667289/adee1c12-a56f-4799-a4d7-bcb4c7a3d9ff

**Comment by quntherdev** [comment]
It works like a charm 🙏 Thanks a lot!
