### ISSUE TITLE
Ability to toggle gizmos on/off with a keybind

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#4739]
When trying to dress a scene, found myself wanting to toggle gizmos on/off without having to go to the dropdown. What about a key, maybe G? Unreal does the same stuff iirc.

**Comment by andy013** [comment]
It would be nice if there was an option for gizmos to scale based on distance from the camera. It can sometimes be hard to tell what's going on when you have all these icons the same size.

**Comment by DevulTj** [comment]
Grid snapping toggle is G, so I put this on SHIFT+G. It's probably not the most ideal hotkey right now, but changing it is dead easy.
