### ISSUE TITLE
Drag GameObjects into the Asset Browser to instantly save a prefab

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4740]
### For?

S&Box

### What can't you do?

Quickly create prefabs by dragging GameObjects into the Asset Browser:

### How would you like it to work?

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/546f3e2e-cee3-4da3-8cbd-d0318c87f961)

### What have you tried?

I've tried doing the above several times since you can do it in Unity. It'd be much faster than the current way of doing things which requires 2 steps (when you don't want to change the name of the object 99% of the time):
1.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/1731a91e-a741-47f9-94ee-2de14378154c)
2.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/b973977a-99e8-420c-932f-9a38c5001912)

**Comment by fantasticaneer** [comment]
I definitely agree with this, and wish I could see/affect the child gameobjects and components within a prefab without opening it up in another tab as though it was a scene.

**Comment by dch-GH** [comment]
Yes. I have the impulse from using Unity so much. Would be really nice.

**Comment by ryleigh** [comment]
I'd also like to be able to do the reverse, dragging a prefab from Asset Browser directy into the Hierarchy.

Currently you can drag it onto gameobjects in the hierarchy to add it as a child, but often I just want to dump a prefab into the root of the scene. 

It's not any better than dragging it into scene view but i'm used to using the hierarchy from Unity.
