### ISSUE TITLE
Let us debug errors in "New Instance" windows

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4741]
### For?

S&Box

### What can't you do?

You cannot get a proper stack trace from the debug console in new instances
1. Create a "New Instance" window:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/47ca8ee9-0d0a-490c-9a8a-bef75abb0383)
2. If you get an error, clicking on it will not show you a stack trace
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/d64c94af-0dfd-4300-b026-271cbb54796e)

### How would you like it to work?

Clicking on an entry in the console should show the full stack trace when run from the editor.

Or a dropdown in the top-right of the console in the editor that allows you to look at the consoles for each connected instance:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/d11326ea-788b-4440-85b4-92c8e3261037)

### What have you tried?

I tried adding a server list to my game so that I can host on the new instance and my editor can be the connected client. However this didn't allow me to connect to the lobby (likely another issue i'll have to make)

I also tried to see if someone else already made an issue for this but I couldn't find one. This is super crucial and it's becoming increasingly more difficult to develop networked games without a proper stack trace on connected clients.

**Comment by dch-GH** [comment]
Even if we need to set a console variable like "developer 1" to be able to see stack traces, would help a lot. I understand not wanting to bombard a normal end-user with stuff like this.
