### ISSUE TITLE
Asset Browser Issues/Missing Features

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4742]
### For?

S&Box

```[tasklist]
### What can't you do?
- [x] You cannot click-and-drag folders in the Asset Browser
- [x] You cannot click-and-drag a file from the Asset Browser into a folder on the left-hand sidebar
- [x] You cannot rename folders
- [x] You cannot use CTRL+D to quickly duplicate files
- [x] You can't drag more than one item into the Asset Browser from File Explorer at once
```

### How would you like it to work?

I would like a lot of these issues resolved so the Asset Browser has parity with File Explorer or Unity's Asset Browser.

### What have you tried?

Having 2 or 3 asset browsers open at once or simply using File Explorer to do certain tasks. Would be really nice if this was all streamlined in the engine.

**Comment by DrakeFruit** [comment]
a "show all files" toggle would be nice. Even if s&box can't do anything with them just give them a generic icon and let you open / move them.
