### ISSUE TITLE
GameResource inspector should have parity with the GameObject/Component inspector

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4744]
### What it is?

The inspector for GameResources is oddly different from the inspector for GameObjects/Components.  You cannot use the new Custom Class/Struct editor that Garry made, you cannot reference GameObjects you must use PrefabFile, ect. Lots of weird oddities that are slowly becoming more apparent as the Component inspector becomes more feature-complete.

### What should it be?

They should have parity.

**Comment by garrynewman** [comment]
GameResource inspector uses thew new ControlWidget stuff, added Dictionary support to it to have parity.

One thing that isn't supported right now is arrays, so advice would be to switch all arrays in your GameResources to use List<>, which should be 100% compatible, from a serialization point of view

**Comment by CarsonKompon** [comment]
Works perfectly! Thanks :)
