### ISSUE TITLE
Can't launch Projects with Libraries.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4745]
### Describe the bug

If your gamemode uses a Library it fails to launch.

### To Reproduce

1. Add a library to your project. ( e.g https://asset.party/videogames/testlibrary )
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/8dc76a48-04cd-4f55-b1af-a15be5d2b7cc)
2. Try to launch the project. It will fail to compile and not launch. The logs say it can't find the package.

### Expected behavior

Games should be able to use libraries. I miss library support.

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/14229763/Log.log)

https://github.com/Facepunch/sbox-issues/assets/91832803/7f804829-1196-4dfd-b0d2-412bdc2052e4

`videogames.testlibrary` is on asset.party and already referenced in the project. It only contains a single component called LibraryComponent.

[Project.zip](https://github.com/Facepunch/sbox-issues/files/14229722/Project.zip)
[Library.zip](https://github.com/Facepunch/sbox-issues/files/14229723/library.zip)

**Comment by badandbest** [comment]
It works for the most part. But I am still having problems when I use the #local suffix. (e.g `videogames.testlibrary#local`) 

Is that something you could look into?

[Log.log](https://github.com/Facepunch/sbox-issues/files/14279414/Log.log)

**Comment by handsomematt** [comment]
Why are you adding a #local suffix? If you have the library enabled locally it should use the local version automatically.
