### ISSUE TITLE
Cannot change the anchor and/or style of a tooltip

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4746]
### Describe the bug

Adding a "Tooltip" property to a panel will create the tooltip but has no options for styling it or positioning it relative to your mouse (since it is always created in the gamerootpanel)

It's especially strange when you have tooltips that anchor to the left when the panel is on the right like so:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/789f4dc6-0019-4adb-a454-ba17569b7fc8)

While tooltips anchor to the right when a panel is on the left-hand side of the screen:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/97c21403-6caf-462e-81d9-1acd0cbc708f)

### To Reproduce

Have something with a tooltip like so:
```razor
<i Tooltip="Test">settings</i>
```

The only way to style it is with
```css
gamerootpanel .tooltip
{

}
```

which means you cannot style on a per-panel basis.

### Expected behavior

There should be a class passthrough and/or an anchor property.

**Comment by garrynewman** [comment]
The tooltip is created on a panel like this

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/73d991ee-186a-4087-81fa-4f185bb74d04)

It has a tooltip property that lets you style it. How would you suggest to style it?

**Comment by CarsonKompon** [comment]
Maybe something like TooltipClass="centered" does `SetClass(TooltipClass, true)` under the hood when the tool tip is created. That way you can pass along any class(es) to the tool top that's created?

**Comment by garrynewman** [comment]
let me have a think on this
