### ISSUE TITLE
Scene Settings don't save when closing/opening editor.

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4747]
### Describe the bug

None of the following settings save to be loaded upon restarting:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/7d226363-72cb-4ae4-aa75-045b83ab0a5f)

### To Reproduce

Change any of the settings and restart.

### Expected behavior

They should save maybe? I'm not really sure if it should be per-project or overall.

**Comment by DevulTj** [comment]
They're saved into a project cookie now and loaded back up on boot
