### ISSUE TITLE
F2 Rename does not work when selecting multiple GameObjects

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4748]
### Describe the bug

![b](https://github.com/Facepunch/sbox-issues/assets/66768086/f313a054-8b8a-47e2-9b92-f505a1ace39d)

### To Reproduce

.

### Expected behavior

.

**Comment by DevulTj** [comment]
https://github.com/Facepunch/sbox-issues/assets/22372616/4b59bb96-92c0-43be-b323-a73cf0f03a5d

This should be working as intended now
