### ISSUE TITLE
`PhysicsJoints.Spring` - Inconsistent Behavior with Ragdolls

### ISSUE THREAD

**Issue by AMastryukov** [Facepunch/sbox-issues#475]
**Describe the bug**
When creating a PhysicsJoints.Spring between a ragdoll bone and a static wall, the behavior is different based on the ragdoll bone chosen. When done with the head bone, the spring is very responsive and tight and the ragdoll hangs as expected. When done with the foot, the ragdoll sags far too low by comparison.

**To Reproduce**
1. Check out this PR: https://github.com/TTTReborn/tttreborn/pull/104
2. Add some bots
3. Wait for round to start
4. Kill a bot
5. Select ttt_magnetostick as active weapon
6. Press and hold LMB to pick up ragdoll by the foot
7. Walk up to wall, RMB to pin (hang) ragdoll
8. Pick up ragdoll by head and repeat 7 to see expected behavior

**Expected behavior**
Spring behaves consistently regardless of PhysicsBody ragdoll bone chosen as one of the attachment points (distance between PhysicsBody and attachment point is roughly the same).

**Screenshots**
Expected (head joint):
![20210717120844_1](https://user-images.githubusercontent.com/12959805/126043089-6e9254ee-16fa-4f3c-8d6f-9e5139f2df84.jpg)

Actual (foot joint):
![20210717120854_1](https://user-images.githubusercontent.com/12959805/126043091-9a1c17e8-754f-4277-b2cb-ec03bf6d75e7.jpg)

**Comment by aylaylay** [comment]
Try setting WithReferenceMass on the spring. I tested this in sandbox where I'm using the spring joints and it seems to work.

<img width="1400" alt="sbox_vhqFJ1x2lN" src="https://user-images.githubusercontent.com/1667289/126405557-157d786c-34bf-4986-86c8-74c05e559290.png">

https://github.com/Facepunch/sandbox/commit/63fb7a10395a760aaaedec7d34ec3f5da2696e81

**Comment by AMastryukov** [comment]
> Try setting WithReferenceMass on the spring. I tested this in sandbox where I'm using the spring joints and it seems to work.
> 
> <img alt="sbox_vhqFJ1x2lN" width="1400" src="https://user-images.githubusercontent.com/1667289/126405557-157d786c-34bf-4986-86c8-74c05e559290.png">
> 
> [Facepunch/sandbox@63fb7a1](https://github.com/Facepunch/sandbox/commit/63fb7a10395a760aaaedec7d34ec3f5da2696e81)

It still doesn't seem to work:
![image](https://user-images.githubusercontent.com/12959805/126915091-fcde81d0-8f12-43cc-8457-75788079d4d4.png)

Here is the bit of code I'm using to test this:

```
playerCorpse.RopeSprings.Add(
                    PhysicsJoint.Spring
                        .From(_heldBody)
                        .To(tr.Body)
                        .WithPivot(tr.EndPos)
                        .WithDampingRatio(5f)
                        .WithFrequency(8f)
                        .WithReferenceMass(10000f)
                        .Create()
```
In this case, `_heldBody` is the `PhysicsBody` we are grabbing, and `tr.Body` is the body that is his by the ray trace result.
Regardless of the number I set in the reference mass setting, the result is the same.

**Comment by aylaylay** [comment]
Use the mass of the body for the reference mass. Look at the rope tool in the sandbox code. 
https://github.com/Facepunch/sandbox/blob/master/code/tools/Rope.cs#L82

**Comment by AMastryukov** [comment]
> Use the mass of the body for the reference mass. Look at the rope tool in the sandbox code.
> https://github.com/Facepunch/sandbox/blob/master/code/tools/Rope.cs#L82

Sorry to get back about this after so long but the solution with reference mass doesn't seem to be working.
Here is the code snippet I'm using:
```
playerCorpse.RopeSprings.Add(
    PhysicsJoint.Spring
        .From(_heldBody)
        .To(tr.Body)
        .WithPivot(tr.EndPos)
        .WithDampingRatio(5f)
        .WithReferenceMass(_heldBody.Mass)
        .WithFrequency(8f)
        .Create());
```

The result is as follows for the hand:
![20210817190653_1](https://user-images.githubusercontent.com/12959805/129812208-46efb884-687b-4343-beed-be01dd4ec722.jpg)

**Comment by aylaylay** [comment]
does it work in sandbox?

**Comment by AMastryukov** [comment]
> does it work in sandbox?

In Sandbox, the rope behavior attaches two different bodies (i.e., balloon to ragdoll). In this instance we are attaching a ragdoll to a wall.

I think this has something to do with why it behaves in this way.

**Comment by aylaylay** [comment]
Sandbox has a rope tool too. Try that and see if it has the same issues.

**Comment by aylaylay** [comment]
It looks like your issue is because you're not setting the min and max rest length

**Comment by aylaylay** [comment]
You also will want to lower your damping ratio. Mess with the values until it feels right. I don't consider this a bug or anything to change, you want to pick the right values based on what you're doing.

**Comment by AMastryukov** [comment]
Fixed, thank you @aylaylay!
