### ISSUE TITLE
Updating Texture.CreateArray with Update3D with data from Texture.Load is buggy

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#4751]
### Describe the bug

For some reason calling Update3D with data from Texture.Load, sometimes the texture will end up having garbage pixels from Gizmo.ScreenText and such.

### To Reproduce

Sam has the repo!!

### Expected behavior

The texture should just be the pixels I give it, not with stuff from Gizmo.ScreenText!! 

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/19620198/63902428-2d2d-4bb0-beab-89a7a5bd263c)

### Additional context

Started happening after Vulkan merge.

**Comment by handsomematt** [comment]
The behaviour on the DX11 code for this changed with https://github.com/Facepunch/sbox/commit/82228c803b9cbd234c9313978093e2393c11e277#diff-d8bd9346a4d2ba057c1d0521b7650f595e8d032e4fbf3b4fb9077ac4ba5d0d7e

It likely needs to be replicated to Vulkan.

**Comment by aylaylay** [comment]
Send the repro here please

**Comment by ceitine** [comment]
https://github.com/Small-Fish-Dev/deathcard

Relevant file: `code/Voxel/Texture/TextureAtlas.cs`

**Comment by aylaylay** [comment]
I made my own repro for this, I can successfully get pixels from a texture and update a texture array with them.

Are you still running into this issue?

**Comment by aylaylay** [comment]
@ceitine

**Comment by aylaylay** [comment]
```cs
		var texture = Texture.Load( "dev/helper/testgrid_color.vtex" );
		var width = texture.Width;
		var height = texture.Height;

		var pixels = texture.GetPixels();
		var albedoPixels = pixels
			.SelectMany( v => new[] { v.r, v.g, v.b, v.a } )
			.ToArray();

		albedo = Texture.CreateArray( width, height, 10 )
			.WithName( $"albedo" )
			.Finish();

		albedo.Update3D( albedoPixels, 0, 0, 1, width, height, 1 );

		var material = Material.FromShader( "test.shader" );
		so = new SceneObject( Scene.SceneWorld, Model.Load( "models/dev/box.vmdl" ) );
		so.SetMaterialOverride( material );
		so.Attributes.Set( "Albedo", albedo );
```

**Comment by ceitine** [comment]
wheatley confirmed everything works currently! thanks to whoever fixed it!!
