### ISSUE TITLE
Black screen on opening s&box editor

### ISSUE THREAD

**Issue by canoom** [Facepunch/sbox-issues#4752]
### Describe the bug

When i open the editor from Steam, after opening a project, a black screen appears with the s&box ribbon on the top right.

### To Reproduce

1. Open S&box Editor
2. Select Project
3. Black screen appears

### Expected behavior

I would expect the editor to open properly.

### Additional context

When i alt+tab, i can briefly see the editor. I found a temporary fix by closing the "Scene" tab, and then opening it again. This resolves the issue. I am unable to take a screenshot as whenever i do take one, i only see the editor in the screenshot. I am happy to provide more information regarding this issue.

**Comment by canoom** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/72504193/9aa7f7c5-209e-4484-8773-e983c36dd3af)
Basically this appears on screen, have to alttab to remove it for a second so i can lineup the scene window's exit button

**Comment by garrynewman** [comment]
This is also resolved by changing the screen size slightly.

**Comment by handsomematt** [comment]
Dupe #4398
