### ISSUE TITLE
CSS vw and vh values do not update when resizing window or toggling F3

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4753]
### Describe the bug

If you have a panel that is sized/positioned using `vw` or `vh` then those values will not be updated when resizing the view or toggling F3 in the editor. The changes are only made if you exit play mode and re-enter play mode when at the desired size.

### To Reproduce

Create a panel that looks like the following:
```razor
<div style="width: 50vw; height: 100vh; position: absolute; background-color: pink;" />
```

Entering play mode looks like this:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/7b894eea-4da4-4d22-b116-9bfef840e0ab)

Pressing F3 while in play mode looks like this:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/4ccbbeb5-e80b-4a81-88fa-c3e6e41586de)

Exiting play mode and then entering it again while still in the F3 size looks like this:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/2bc8dc76-fa47-43d4-a2cc-77ba2355ff04)

And finally pressing F3 to switch it back while in play mode looks like this:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/0142b25b-b2b6-43fc-a775-53faf31497e7)

### Expected behavior

It should update properly. It seems like it just caches `vw` and `vh` on game start and then never again 👍

**Comment by CarsonKompon** [comment]
I've been told to use flex for my issue but it's worth noting that what I'm specifically trying to do is not achievable with flex (to my knowledge)

Here is what I am able to achieve by using vw to ensure that the left and right panels will never touch the inventory at any resolution:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/897f128f-d7b2-49e7-98a5-b6eb380f9e1f)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/9d1c250e-bbe2-48bf-8268-6ca270377596)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/87220b14-6f4d-4443-a4fd-07c42670059d)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/6e1983ab-9166-4b89-87ce-fcdf10a5c043)


As you can see, when I attempt the same thing in flex, the inventory will never properly be centered since the text contents on the left and right sides will never have an identical width.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/e6004eb9-43c8-4ef5-89d8-1eb7a07d0a02)
(left has flex-grow, center has flex-shrink: 0, right has flex-grow)

And giving the left and right panels a min-width works for 16:9 resolutions but give less-than-ideal results on 4:3:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/7b0bea80-a6e4-4fb0-b91b-3e08bded9fbc)

Just wanted to add this additional information in hopes vw/vh continue to be supported since they have valid use cases 👍

**Comment by xezno** [comment]
Should be fixed, let me know if not
