### ISSUE TITLE
Prefab not found error when loading game outside of editor context

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4755]
### Describe the bug

After uploading and attempting to play my game outside of the editor, my game throws an error while trying to deserialize my player prefab. This understandably stops me from playing my game. I'm not sure why this is happening, and it's very difficult to debug since it only happens outside of the editor. In order to investigate, I would need to continuously re-upload the game with minimal changes.

https://github.com/apetavern/grubs/tree/scene-rewrite/code
https://asset.party/apetavern/grubs

I have verified that the grub.prefab file is uploaded, so I assume the error message is either inaccurate or something else is going on.

Logs:
```
2024/02/11 17:27:26.8355	[Generic] Waiting for Web Auth Ticket..	
2024/02/11 17:27:27.6736	[engine/RenderSystem] Vulkan Physical Device: NVIDIA GeForce RTX 3070 Ti	
2024/02/11 17:27:27.8015	[engine/RenderSystem] VK_EXT_graphics_pipeline_library and dependent extensions enabled.	
2024/02/11 17:27:27.8015	[engine/RenderSystem] Unable to open Vulkan pipeline cache shadercache\vulkan\shaders.cache file - might not exist yet.	
2024/02/11 17:27:27.8015	[engine/RenderSystem] Vulkan driver version: 546.17.0.0	
2024/02/11 17:27:36.0934	[Menu] Couldn't join a lobby - making a game	
2024/02/11 17:27:36.7089	[Generic] Downloading 2 files (270.50kb)..	
2024/02/11 17:27:36.9407	[Generic] ..done in 0.23s	
2024/02/11 17:27:36.9407	[engine/ResourceSystem] Reloaded 1 resident symlinked resources in 1ms	
2024/02/11 17:27:37.1684	[GameMenu] Error when deserializing Grubs.Helpers.NetHelper.PlayerPrefab (Prefab not found 'prefabs/grub/grub.prefab')
{
  "_type": "gameobject",
  "prefab": "prefabs/grub/grub.prefab"
}	System.Exception: Prefab not found 'prefabs/grub/grub.prefab'
   at Sandbox.GameObject.JsonRead(Utf8JsonReader& reader, Type targetType)
   at Sandbox.JsonSerializedConvert`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadNode[TValue](JsonNode node, JsonTypeInfo jsonTypeInfo)
   at Sandbox.Json.FromNode(JsonNode node, Type type)
   at Sandbox.Component.DeserializeProperty(PropertyDescription prop, JsonNode node)
   at Sandbox.Component.PostDeserialize()
2024/02/11 17:27:37.3200	[GameMenu] Exception when calling INetworkListener.OnActive	System.NullReferenceException: Object reference not set to an instance of an object.
   at Grubs.Helpers.NetHelper.OnActive(Connection conn) in Helpers/NetHelper.cs:line 27
   at Sandbox.SceneNetworkSystem.<>c__DisplayClass11_1.<OnJoined>b__0()
   at Sandbox.SceneNetworkSystem.OnJoined(Connection client)
2024/02/11 17:27:37.5051	[engine/ResourceSystem] Error loading resource file "materials/skybox/beach_01.vmat_c" (Error: ERROR_FILEOPEN: File not found)
```

### To Reproduce

- Try to play Grubs outside of the s&box editor.
- Observe error

### Expected behavior

No error should occur.

**Comment by trundlr** [comment]
grub.prefab is spawned in the network helper - I believe that is it. Some components within the grub.prefab spawn other prefabs, such as weapon prefabs, on start, but it's just the network helper that spawns the grub.

**Comment by trundlr** [comment]
Any update on this? I tried uploading and networking spawning the same prefab in another ident and it seemed to work fine, but I didn't 1:1 recreate the entire scene, but I am not certain if it matters. `apetavern.grubs_duel` if you're interested.

**Comment by MrBrax** [comment]
i had to add prefabs to the menu resources to get them to upload

**Comment by trundlr** [comment]
> i had to add prefabs to the menu resources to get them to upload

The prefabs were already uploaded, but I did notice between grubs and grubs_duel, grubs was missing the prefabs in the Startup Resources. I assume this is the underlying issue - it is not clear to me how startup resources differs from other uploaded resources, or why they were not included in grubs but were in grubs_duel.

**Comment by trundlr** [comment]
Even though I can actually load into my game now, I still find myself very confused with everything. I zeroed out my menu / resource files, uploaded again, and the resources I expect to be there show up in the [upload](https://asset.party/apetavern/grubs/version/48765), but error still when I try to join the game.

```
2024/02/28 13:30:33.1685	[engine/ResourceSystem] Reloaded 1 resident symlinked resources in 0ms	
2024/02/28 13:30:33.6265	[engine/ResourceSystem] Error loading resource file "particles/explosion/grubs_explosion_fireball.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:33.6707	[GameMenu] Error opening stylesheet: ui/inventorydisplay.razor.scss (File not found)	System.IO.FileNotFoundException: File not found
File name: 'ui/inventorydisplay.razor.scss'
   at Sandbox.UI.StyleSheet.UpdateFromFile(String name, Boolean failSilently)
2024/02/28 13:30:33.6744	[GameMenu] Error opening stylesheet: ui/grubtag.razor.scss (File not found)	System.IO.FileNotFoundException: File not found
File name: 'ui/grubtag.razor.scss'
   at Sandbox.UI.StyleSheet.UpdateFromFile(String name, Boolean failSilently)
2024/02/28 13:30:33.9782	[engine/ResourceSystem] Error loading resource file "materials/skybox/beach_01.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1103	[engine/ResourceSystem] Error loading resource file "models/weapons/bazooka/materials/bazooka_translucency.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1103	[engine/ResourceSystem] Error loading resource file "models/weapons/bazooka/materials/bazooka.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1103	[engine/ResourceSystem] Error loading resource file "models/weapons/bazooka/materials/bazooka_homing.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1366	[engine/ResourceSystem] Error loading resource file "models/weapons/grenade/materials/grenade_cluster.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1366	[engine/ResourceSystem] Error loading resource file "models/weapons/grenade/materials/grenade.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1366	[engine/ResourceSystem] Error loading resource file "models/weapons/baseballbat/materials/baseballbat.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1366	[engine/ResourceSystem] Error loading resource file "models/weapons/baseballbat/materials/baseballhelmet.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 13:30:34.1422	[engine/ResourceSystem] Error loading resource file "models/weapons/brassknuckles/materials/brassknuckles.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
```

**Comment by MrBrax** [comment]
am i getting the same error too where there are missing assets when playing the game from the regular sbox client then? made a discussion post about wondering if you had to upload assets separately

**Comment by MrBrax** [comment]
i think i'm onto something, do you load into the game on a different scene than your assets? it seems that only the start scene assets get downloaded/activated in, and changing scene will break everything

**Comment by anthonysharpy** [comment]
Had this happen just now too when a scene object was referencing a prefab. If I had to guess it's because it's looking for .prefab and not .prefab_c

**Comment by anthonysharpy** [comment]
> Even though I can actually load into my game now, I still find myself very confused with everything. I zeroed out my menu / resource files, uploaded again, and the resources I expect to be there show up in the [upload](https://asset.party/apetavern/grubs/version/48765), but error still when I try to join the game.
> 
> Edit: Saving didn't work the first time for the menu files. So I think it's the menu files in particular that are fucking things up.

And same, also getting this too

```
2024/03/02 03:08:10.7165	[GameMenu] Error opening stylesheet: gui/guimaster.razor.scss (File not found)	System.IO.FileNotFoundException: File not found
File name: 'gui/guimaster.razor.scss'
```

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/2033e2e0-25e1-4084-be96-188a339dbc45)


It also fails to find the map, even if I use the full path (maps/sc_southampton_v2_fix.vpk)

```
2024/03/02 03:16:29.3452	[engine/WorldRenderer] Failed to mount world vpk file sc_southampton_v2_fix.vpk, file could not be found.	
2024/03/02 03:16:29.3452	[GameMenu] Couldn't load map (Unable to create world for map 'sc_southampton_v2_fix')	System.Exception: Unable to create world for map 'sc_southampton_v2_fix'
   at Sandbox.SceneMap.CreateWorld(SceneWorld sceneWorld, String map, Boolean async)
   at Sandbox.SceneMap..ctor(SceneWorld sceneWorld, String map, MapLoader loader)
   at Sandbox.Map..ctor(String mapName, MapLoader loader)
   at Sandbox.MapInstance.LoadMapAsync(String mapName)
```

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/10c40f6c-1167-4b38-9b29-346f7acf5faf)

**Comment by MrBrax** [comment]
the menu files are definitely part of this. when carefully adding basically all the project assets except for xml and text files, the game started working. i had to upload texture source files and raw .vmat files, otherwise it couldn't find them.

**Comment by anthonysharpy** [comment]
Brax is right. So it seems the workaround is to include everything in menu files. Putting stuff in resource files doesn't work for some reason. Adding all this seemed to fix it for me, some of it is probably unnecessary but eh

```
*.prefab
*.prefab_c
*.vpk
*.los
*.vmap.meta
*.scss
*.razor.cs
/images/*
*.vmat
*.vmat_c
*.vmdl
*.vmdl_c
*.sound
*.sound_c
*.vsnd_c
*.razor
```

**Comment by MrBrax** [comment]
since the scene update, it's as if there is no concept of in-game and menu anymore, everything runs in the menu. so for the game to work, everything has to be included in menu assets to function

**Comment by trundlr** [comment]
For me the fix was to remove everything from menu files, making it blank. This category should really just be removed from the project settings.

**Comment by garrynewman** [comment]
I agree with that shit

**Comment by garrynewman** [comment]
MenuResources has gone now - so I assume that fixes this

**Comment by MrBrax** [comment]
when the update dropped, the assets stopped working for me again until i copied the removed menu list to the resource list

**Comment by garrynewman** [comment]
The way the upload logic should work is that it should automatically upload all asset files - so that would include prefabs. If it's not doing that, then something is wrong. Could you link the two versions you made, before and after changing the resource list, just to confirm that the prefabs weren't included?

**Comment by MrBrax** [comment]
i'm not certain the prefabs in particular were missing, but menu assets and music were which was previously solved by menu wildcards which fixed prefabs too.

broken: https://asset.party/brax/terrytarget/version/50716

fixed manifest: https://asset.party/brax/terrytarget/version/50717

**Comment by garrynewman** [comment]
Okay, that adds up, thanks
