### ISSUE TITLE
Default project has `Scenes` folder instead of `scenes`

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4757]
### Describe the bug

A default project has `Scenes` instead of `scenes`. Typically, package structure has tried to follow a consistent pattern of casing for folders. While I prefer lowercase, I just want consistency. Whenever someone commits the uppercase version to a git repo, it is a pain in the butt to fix it.

### To Reproduce

1. Start a project
2. Notice the casing of the folder

### Expected behavior

All folders have the same casing

**Comment by DevulTj** [comment]
That should be the case now. Windows sucks, we ended up having a `Scenes\minimal.scene` and a `scenes\minimal.scene` for a moment there.
