### ISSUE TITLE
ModelRenderer bodygroup list doesn't update until restart

### ISSUE THREAD

**Issue by RickGreeve** [Facepunch/sbox-issues#4760]
### Describe the bug

If I add a bodygroup to a vmdl I have to restart sandbox for the bodygroup options to appear in the model renderer component

### To Reproduce

1. have a model open in scene
2. add a bodygroup to said model
3. change does not appear in the model renderer component 

### Expected behavior

instead of having to restart I expect it to live update 

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/125879070/7ec5fe27-f178-4a50-8b50-6e313d381fff

**Comment by handsomematt** [comment]
Related: #4376

**Comment by aylaylay** [comment]
This should be fixed now


https://github.com/Facepunch/sbox-issues/assets/1667289/7ba84597-6381-42f8-87d2-98d798e8c613
