### ISSUE TITLE
Toggling Angle Snap / Global Space in the editor unselects current selection

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4761]
### Describe the bug

This is more of a usability / quality of life thing than a bug in exact terms, but it's been driving me crazy since I started using the editor so figured I'd submit it.
When you toggle Angle Snap or Global Space in the top left of the Editor view, the currently selected object becomes unselected, assumedly because it needs to change the way the gizmo is drawn/etc. It's really quite annoying and unlike behavior in pretty much any other editor.

### To Reproduce

1. Click Angle Snap or Global Space with a GameObject selected
2. The GameObject becomes unselected

### Expected behavior

The GameObject should remain selected despite the gizmo changing to respect the new setting.

**Comment by cr4yz** [comment]
This should be fixed in the next build, please let us know if you have any more issues
