### ISSUE TITLE
Prefabs need visual feedback to indicate saving/unsaved changes

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4763]
### For?

S&Box

### What can't you do?

When working on a feedback, sometimes it is very unclear whether my changes are saved. There is currently no indication of whether a prefab needs to be saved or not. I find that I sometimes will save, and then start my scene, and the changes I just saved are not reflected. Closing and re-opening the prefab will often indicate I never saved in the first place, even though I'm sure I pressed Ctrl+S.

### How would you like it to work?

Like scenes, show an asterisk for unsaved changes on a prefab. Upon saving, remove the asterisk.

### What have you tried?

N/A

**Comment by handsomematt** [comment]
The asterisk shows in the window title next to the prefab name already, no?

**Comment by trundlr** [comment]
Nope, this does not occur for prefabs. Only for scenes. At least for me!

**Comment by trundlr** [comment]
https://github.com/Facepunch/sbox-issues/assets/57276947/ff17cedd-f33f-461c-ba02-c052d09c085e

**Comment by cr4yz** [comment]
Scenes weren't being marked dirty when modifying transform or name from the inspector.  Modifying the string property in your custom component I couldn't repro, it may have been fixed already.

Please give it a try in the next update and let me know if you're still having troubles.

Also note the scene won't be marked dirty until you focus away from the active input field, which is a separate issue to consider.

**Comment by trundlr** [comment]
When I made this issue, scenes were not dirtying at all, which seems to have changed. I can go through and look for any strange behaviour and update this issue later today.

**Comment by trundlr** [comment]
Looking great, thanks Crayz!
