### ISSUE TITLE
Quick selection hotkey/menu to open scenes and prefabs without needing to dive through the asset browser

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4764]
### For?

S&Box

### What can't you do?

When I want to open a scene or a prefab, I need to manually go through the nested folders in my asset browser. This usually involved at least 2-3 clicks, perhaps a search, clearing an existing filter, etc. The process is tedious and I believe it could be much faster.

### How would you like it to work?

Similar to Shift+Shift in JetBrains IDEs, Ctrl+P in Visual Studio Code, or Ctrl+Space in MacOS, a small textbox appears somewhere in the editor by pressing a hotkey. As you type, there are auto-filled search results that you can use your arrow keys or mouse to navigate to. 

![image](https://github.com/Facepunch/sbox-issues/assets/57276947/de859bc0-de72-4dad-9181-7b32c5a02f2c)

![image](https://github.com/Facepunch/sbox-issues/assets/57276947/3443fba1-518b-4c5d-a7e9-4b97c16ec53d)

When selected, the selected scene/prefab is automatically opened in your `Hierarchy`.

### What have you tried?

Navigating the asset browser.

### Additional context

I think there is a chance this will be rejected due to wanting to simply improve the asset browser experience instead, but I promise that once you start using a feature like this, it is just infinitely better than selecting filters or navigating through folders.

**Comment by garrynewman** [comment]
I get it, as a power user feature, but right now I want to focus on simplifying and improving the features we have rather than cramming more in.
