### ISSUE TITLE
Borderless fullscreen acts like exclusive fullscreen

### ISSUE THREAD

**Issue by ItsRifter** [Facepunch/sbox-issues#4766]
### Describe the bug

When you're on Borderless mode (or Exclusive), its treated as entirely fullscreen and un-focusing the game with alt-tabbing causes a black screen for a few seconds, same applies to refocusing.

However playing on Windowed acts as borderless rather than a windowed application.

### To Reproduce

1. Go into options
2. Set video mode to Borderless or Exclusive
3. Alt-tab out of the game
4. Black screen occurs then disappears

### Expected behavior

Obviously the video modes shouldn't behave this way and should be performing as its named.

### Additional context

Playing on -dx11 gives the normal results.

**Comment by handsomematt** [comment]
I can't get borderless to behave like exclusive fullscreen like you said. Could you perhaps try running with `-coop_fullscreen`, that might be a more well behaved borderless fullscreen.

**Comment by chrisspieler** [comment]
- Windowed at less than screen resolution has a border, but at full screen resolution does not.
- Borderless windowed _looks like_ how I'd expect it to look, but when I click on or outside of S&box (switching focus to/from Sandbox) there is a flash of black.
- Exclusive has a flash of black and S&box appears minimized when not in focus.

I haven't messed with the different video modes enough to know which behaviors are wrong except that the black flashing should not be occurring on borderless.

**Comment by handsomematt** [comment]
Got this to happen on Nvidia, fullscreen borderless windows get silently promoted to an exclusive fullscreen mode by the Nvidia Vulkan driver. Not really an easy option to stop that.

If it bothers you a lot you can get it to work the way you want by setting Vulkan/OpenGL present method to "Prefer layered on DXGI Swapchain".

![image](https://github.com/Facepunch/sbox-issues/assets/1388267/31254090-dbdb-4e1f-990c-0ef3f3013f2b)

In the future we could write a layer to use a DXGI Swapchain with Vulkan on Windows, it has some additional benefits with flip modes and better vrr support, but it's essentially what the driver option is doing and maybe it'll become the default in the future.

**Comment by ItsRifter** [comment]
> Got this to happen on Nvidia, fullscreen borderless windows get silently promoted to an exclusive fullscreen mode by the Nvidia Vulkan driver. Not really an easy option to stop that.
> 
> If it bothers you a lot you can get it to work the way you want by setting Vulkan/OpenGL present method to "Prefer layered on DXGI Swapchain".
> 
> ![image](https://private-user-images.githubusercontent.com/1388267/306445776-31254090-dbdb-4e1f-990c-0ef3f3013f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDk0NzYsIm5iZiI6MTcwODU0OTE3NiwicGF0aCI6Ii8xMzg4MjY3LzMwNjQ0NTc3Ni0zMTI1NDA5MC1kYmRiLTRlMWYtOTkwYy0wZWYzZjMwMTNmMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMjA1OTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjFjMmFmNzg2MWNjODg3NGM4NTJhNzE4NTNiODI5ZGI3NmQwMmUxOTgzOGViOGQ1NGMzNGY2YWJkN2Q0NjRlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZoETknJjFZCJ0STlQfqQAZZXHoBLBQT5PS5LiRHylj0)
> 
> In the future we could write a layer to use a DXGI Swapchain with Vulkan on Windows, it has some additional benefits with flip modes and better vrr support, but it's essentially what the driver option is doing and maybe it'll become the default in the future.

That solution works so I'll close this for now

Probably be beneficial to provide my GPU and driver specs

Nvidia RTX 3070 TI - Driver 551.52 (as of 02/13/2024)
