### ISSUE TITLE
Tooltips for editor UI elements should include their existing hotkeys / keyboard shortcuts

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4768]
### For?

S&Box

### What can't you do?

Had to figure out editor hotkeys through trial and error and write a wiki page for them.
Would be very nice if tooltips for things showed their hotkeys, and/or the Help dropdown at had a listing.

### How would you like it to work?

Hovering over a UI element currently shows a tooltip but not the associated hotkey.

![image](https://github.com/Facepunch/sbox-issues/assets/5409303/5a600bd0-40aa-4d34-a343-2999d93702bd)
This would say something like "Toggle Gizmos (Shift+G)"

### What have you tried?

Figuring out through trial and error and making a section on the wiki for it

### Additional context

I am aware this may be currently waiting due to a desire to have these be user-configurable before showing the keybind in the tooltip

**Comment by handsomematt** [comment]
Yep, and this should be automatic - not solved just by manually putting the bind in the string.

**Comment by DevulTj** [comment]
https://github.com/Facepunch/sbox-issues/assets/22372616/8197920e-ba00-4db6-971a-afc3e513f87f
