### ISSUE TITLE
Add EditorHandle to TextRenderer

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4773]
### For?

S&Box

### What can't you do?

I can't easily select the many TextRenderer objects I have in my scene because there is no EditorHandle for TextRenderer that would make the gizmo icon appear in the world.

### How would you like it to work?

It should work just like any other EditorHandle, like the one for PointLight.

### What have you tried?

I have to search for text objects by typing "Text" in to the Hierarchy search bar

**Comment by DevulTj** [comment]
![sbox_QaTjrkmULD](https://github.com/Facepunch/sbox-issues/assets/22372616/d96f1fab-8f59-494f-8b99-40b2e7cd0273)
