### ISSUE TITLE
Old version of scene is uploaded when publishing project

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4775]
### Describe the bug

Often when I make a change to my scene (e.g. the position of an object), save the scene, and then upload the project, the change to the scene will not exist when I play the game outside of the editor.

### To Reproduce

1. Open the S&box editor
2. Open a game project you've already uploaded to Asset Party
3. Open a scene and change something obvious
4. Hit Ctrl+S to save
5. Go to Edit -> Publish Project and upload the game
6. Exit the S&box editor and open S&box in play node
7. Run your game
8. Observe that changes to your scene have not applied

### Expected behavior

If changes to a scene are saved to disk, those changes should be included when uploading the game to Asset Party.

**Comment by fantasticaneer** [comment]
This happened to me recently when uploading Terryrarium too but I don't know quite what causes it

**Comment by fantasticaneer** [comment]
I don't know why this is happening but my project is stuck on an older version of the scene with new code. I've tried uploading three times, have tried closing and reopening the editor before upload, and the uploaded version is still using some old version of the scene. :/

**Comment by CarsonKompon** [comment]
I think this was fixed a while ago, as I haven't experienced this in months. Can you confirm @chrisspieler?

**Comment by chrisspieler** [comment]
Yeah, I don't think I've run in to this in a long time. Closing.
