### ISSUE TITLE
Selecting GameObjects dirtys the scene

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4776]
### Describe the bug

You could change literally nothing about the GameObject, simply clicking it causes it to "change" somehow. 
This ultimately results in the scene wanting to save, and if you oblige, creates a nothing change if you're using git.
![sbox-dev_dnYfOejXtg](https://github.com/Facepunch/sbox-issues/assets/44037603/54ba6364-2a74-4361-8938-ccd823d45f13)

This, oddly enough, doesn't occur on prefabs

### To Reproduce

1. Open a scene
2. Click a GameObject
3. Proceed to save literally nothing

### Expected behavior

Nothing should be getting changed, nor should the scene want to save.

**Comment by trundlr** [comment]
Agreed, I would appreciate proper scene dirtying. Navigating a scene just to look at something and then seeing the unsaved changes asterisk makes me nervous that I changed something I did not intend to. The asterisk should only show up if a value has been changed.
