### ISSUE TITLE
Menu Load Error: Couldn't create MenuSystem!

### ISSUE THREAD

**Issue by benrirdawd** [Facepunch/sbox-issues#4777]
### Describe the bug

I start the game and text boxes appear saying that the menu cannot be created, and the game close

### To Reproduce

1. Start the game
2. Error box appears
3. Press OK game closes

### Expected behavior

The game should start

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/115178731/9549fbfc-05ab-458c-bb0a-79495fc29322)
![image](https://github.com/Facepunch/sbox-issues/assets/115178731/69147e6c-0c79-4e42-9023-c7a22dd52524)

**Comment by handsomematt** [comment]
Verify your game files - if that doesn't work upload your log here. https://docs.facepunch.com/doc/reporting-errors-2OTPIafqCJ
