### ISSUE TITLE
Rendertags don't work on hammer maps

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4778]
### Describe the bug

Render tags don't work with hammer maps, meaning it's not possible to exclude or include hammer lights. 

### To Reproduce

1. Make a new camera
2. Attach a mesh to the camera (give it tag of 'arms' )
3. Load a hammer map with some lights in them ( give the lights the tag of 'light')
4. Setup render tags for this cam to only include 'arms' and 'light'

### Expected behavior

The camera should only render the arms with some lighting on them.

Instead, it will render the arms either fully black or only with ambient light ( from probe lights I assume ). 

### Additional context

This works fine with normal lights, only seems to be hammer lights that are ignored when it comes to tags.

Additionaly: it would be nice if all (hammer) lights have a certain tag on them, so that the user does not have to set a 'light' tag on each light in hammer that they want to show up. So I guess the design decision is should they be opt in or opt out. I have not given it much thought but it's something to consider.

**Comment by handsomematt** [comment]
So tags on hammer entities aren't copied to their gameobjects? That should be simple enough to fix

**Comment by kurozael** [comment]
Have a go after the next build is complete, gimme a shout if you're having any more issues :)
