### ISSUE TITLE
Disable/remove camera previews.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4779]
### For?

S&Box

### What can't you do?

When selecting a camera in the scene, it shows a camera preview. This preview, especially on smaller screens takes too much space, often hiding gizmos for moving objects etc. 

### How would you like it to work?

I should be able to click a 'x' and close it and/or have a project wide setting to never render camera previews.

### What have you tried?

I checked the editor settings and could not find any option. The little preview also has no x to close it so not much else to try.

**Comment by handsomematt** [comment]
#4472
