### ISSUE TITLE
Set Model.AnimGraph at runtime.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4780]
### For?

S&Box

### What can't you do?

I was not able to set the animgraph asset at runtime. I would like to change which animgrap a skinned model renderer uses at runtime. The AnimGraph property is a getter only atm.

### How would you like it to work?

Perhaps I should be able to say Model.AnimGraph = MyAnimGraph;

### What have you tried?

I have tried to find a setter method of any kind, but could not find it. The only way to do it for me currently is to create a copy of the source model and set a different anim graph but this seems overkill?

**Comment by Gmod4phun** [comment]
You can already do this by setting it on the SceneModelRenderer's SceneModel
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/a0fa9ddd-7623-41f0-8c44-026bc966cb0f)

**Comment by DevulTj** [comment]
Setting Model.AnimGraph isn't where you're wanting to do this. "Model" is not the instance of the model renderer in this case. @Gmod4phun's advice will work for you. Might be worth adding an accessor to SkinnedModelRenderer.

**Comment by aylaylay** [comment]
I've added SkinnedModelRenderer.AnimationGraph, this is useful because you can set it in the editor
