### ISSUE TITLE
2D box select in scene view

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4781]
### For?

S&Box

### What can't you do?

Box select a bunch of gizmos/gameobjects in a 2D box projected into 3D

### How would you like it to work?

Like Unity probably.

### What have you tried?

Nothing

**Comment by garrynewman** [comment]
Can now box select gameobjects in the scene view

**Comment by dch-GH** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/25caa71d-489e-4fb7-8d8e-6aff73d76000)
the future is here 💖
