### ISSUE TITLE
Vulkan assert on first play

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#4782]
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/1ff89415-d7f6-42e7-b4ef-39c6a09caf83)

Repro:
- Make a new project, or use any project
- Hit play

**Comment by handsomematt** [comment]
Added a nicer assert but this is gonna happen when you try to dispatch an invalid compute shader. I can't get it to happen but I assume somewhere you don't have a material built, so you'd need to break it and see where isn't checking validity properly.

**Comment by handsomematt** [comment]
Did find a couple of bad ones actually, should be fine now.

**Comment by DevulTj** [comment]
awesome ty, I'll let you know if this persists
