### ISSUE TITLE
Add Up/Down movement in the editor.

### ISSUE THREAD

**Issue by jkinz3** [Facepunch/sbox-issues#4787]
### For?

S&Box

### What can't you do?

In the editor, I can fly around just fine but there isn't a key to fly up or down. 

### How would you like it to work?

There should be movement keys for moving up and down, similar to hammer and other editors. For example, in my opinion, Unreal is the most intuitive. While flying, E moves up (along the world Up axis) and Q moves down. This enables you to zoom around the map quickly and easily and provides easier maneuverability 

### What have you tried?

Right now, the closest thing is the mouse pan. I have to let go of the movement keys, and use the middle mouse button to pan. And this still only moves up relative to the camera, which isn't the same as moving along the world Up axis.

**Comment by DevulTj** [comment]
Added this (E to go up, Q to go down)
