### ISSUE TITLE
Remove GameFeatureSet limitations from Hammer

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#479]
**What can't you do?**

Access full tileset editor or other tools locked behind GameFeatureSets.

You can access them by changing `GameFeatureSet` in `sbox/core/gameinfo.gi` between various values:

- HalfLife (Default)
- Dota (Tileset editor)
- CounterStrike (Vertex normal paint + tileset editor)

All tool feature sets should be available without modifying this.

**Comment by gabengaGamer** [comment]
Also source 2 have https://www.youtube.com/watch?v=ZLQnzE_s4FI bake ambient occlusion tool

**Comment by aylaylay** [comment]
Disabled game feature sets. It does mean we'll have to go through and either fix the hidden tools or remove them if they're bullshit but it doesn't make sense for us to use game feature sets anyway.

**Comment by handsomematt** [comment]
Works perfect mate, nice one x
