### ISSUE TITLE
Weird editor crash upon rearranging Game view/widget 

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4790]
### Describe the bug

My editor crashed twice in a row in a weird way upon trying to rearrange the 'Game' view tab. Video and logs below.

### To Reproduce

1. Open the editor
2. Move the 'Game' tab to the bottom of the window
3. Reproduces... _sometimes_, unsure how.

### Expected behavior

Not crashing.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5409303/d47c3657-d4bb-47da-a7ae-e69bd8b0bfd9

[Log.225.log](https://github.com/Facepunch/sbox-issues/files/14284830/Log.225.log)
[Log.226.log](https://github.com/Facepunch/sbox-issues/files/14284829/Log.226.log)

### Additional context

RTX 3090, 551.23

**Comment by garrynewman** [comment]
Lots of vulkan errors at the end of these logs @handsomematt / @samzanemesis

**Comment by handsomematt** [comment]
Should never happen now, I added safety and asserts around video modes being 0 height, and then plugged it at the root of the Qt container widget.

You'll know if it's worked because you'll see something like `[engine/Qt] CHostedWidget::SizeToParent invalid width/height ( 1714, 0 )` in the console.
