### ISSUE TITLE
 Object reference not set to an instance of an object. Error pops out in an empty project

### ISSUE THREAD

**Issue by Chesno4ok** [Facepunch/sbox-issues#4792]
### Describe the bug

Whenever I launch an empty project this error pops out in console.

### To Reproduce

1. Create an empty project
2. Run it

### Expected behavior

Don't break ,i guess.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/109698281/55ab3d2f-efd1-4ddd-ae06-171487691af1)

**Comment by handsomematt** [comment]
#4791
