### ISSUE TITLE
Editor crashing when making structural changes to code in specific project

### ISSUE THREAD

**Issue by SharpMars** [Facepunch/sbox-issues#4794]
### Describe the bug

If I add/remove property/method from a class(tested on my GameManager component) it shows succesful compilation notification after which it crashes.
Edit(15.02.2024): creating new code files also makes it crash(tested on creating razor file)
Edit(16.02.2024): its project specific

### To Reproduce

1. Add/remove method or property in class
2. Crash

### Expected behavior

Should not crash

### Additional context

Here's my repo: https://github.com/SharpMars/motivational-lizard/tree/scenes
And here's my SteamID: 76561198391811856
Tested on staging branch latest as of 14.02.2024 (c1d01fb)
Windows 11

**Comment by garrynewman** [comment]
Does this look like a possible hotload error @Metapyziks 

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/ea2a1e24-52a5-4036-80b2-2eb64b921414)

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/b0bb9c86-a752-43cf-b60e-5ad2d54569d1)

I managed to isolate it. Removing the highlighted line here prevents the crash on hotload

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/f97cf8e4-eff9-4d7f-ad68-891e9d681980)

**Comment by Metapyziks** [comment]
Seems to be a bug with ArrayUpgrader.BlockCopyStructArray, if I disable it for only TimeEvent[] it doesn't crash.
