### ISSUE TITLE
Add PerlinNoise To MathX lib

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-issues#4796]
### For?

S&Box

### What can't you do?

There is no current implementation of the perlin noise function inside any available Math lib.

### How would you like it to work?

For a Perlin Noise Implementation to be added to the MathX  lib rather then having to make a new file for it each time.

### What have you tried?

.

**Comment by dch-GH** [comment]
https://asset.party/api/Sandbox.Utility.Noise/Perlin

**Comment by B0zy** [comment]
I looked for so long and didnt even see that
