### ISSUE TITLE
Singleton components.

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4797]
### For?

S&Box

### What can't you do?

We used to be able to have components that would replace eachother if they were the derived from the same type, this was useful for things like swapping out movement controllers easily (walking -> noclip) etc

### How would you like it to work?

just like it used to

### What have you tried?

nothing i can think of trying really

**Comment by garrynewman** [comment]
Explain how it used to work, how you would expect it to work

**Comment by Xenthio** [comment]
So we used to have components that you could only have one of its type, i could have components derived from 'movementcontrollercomponent' that are 'walkcontroller' and 'noclipcontroller' 
adding noclipcontroller while walkcontroller was active would remove walkcontroller, it was just a convenience thing really. not super important.

**Comment by garrynewman** [comment]
I don't really love it to be honest. We should just be blocking adding components, not magically removing them.. as I feel like that would cause a lot of confusion.
