### ISSUE TITLE
Auto saving scenes

### ISSUE THREAD

**Issue by trende2001** [Facepunch/sbox-issues#4798]
### For?

S&Box

### What can't you do?

 I'm annoyed having to press Ctrl+S every few seconds or so

### How would you like it to work?

Just saving scenes, automatically.

### What have you tried?

N/A

**Comment by handsomematt** [comment]
Why do you need to save every few seconds

**Comment by trende2001** [comment]
@handsomematt It's kind of related to issue #4776, but i think some people would want to have it. not just a me thing

**Comment by trende2001** [comment]
what I meant by auto save is, auto saving always (like in VS code for example), not based on a time interval

**Comment by Retroeer** [comment]
I agree with this, autosave is just a nice to have layer of protection against a crash. no sense for an engine like s&box to not have the option of having it.

**Comment by trende2001** [comment]
Why???

**Comment by MrBrax** [comment]
> Why do you need to save every few seconds

it's the burned in response for having worked with early hammer and other software, i constantly press ctrl+s after basically every action i do, but autosave is nice too

**Comment by Retroeer** [comment]
Hammer has auto save, I don't understand why the editor shouldn't?

**Comment by anthonysharpy** [comment]
Bit baffling that this got closed with no reason given really. Should be a basic feature of any editing program.

**Comment by DrakeFruit** [comment]
I would really love for this to be a thing, saved my ass in hammer so many times

**Comment by Jammie3d** [comment]
As long as it doesn't mess with the .scene file this would be nice to have eventually, it'd probably have to save to the sbox directory instead of the project one so it doesnt get picked up by Git.

**Comment by brannanz** [comment]
We need to save every few seconds because the editor is too shitty and buggy for it to run for more than 3 minutes without crashing and burning while violently tumbling into a ditch
