### ISSUE TITLE
ModelDoc: AddMeshes selects wrong path

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#48]
**Describe the bug**

When adding meshes to a new model in ModelDoc the Add Meshes adds the path of a model as the following: `addons/addon_name/models/model_name.fbx`

When it should be `models/model_name.fbx`

You can easily workaround this by editing the path manually and removing `addons/name`, but the error upon initial import is confusing.

**To Reproduce**

1. Go to ModelDoc, AddMeshes and select a mesh from your addon folder.
2. Save / Compile.
3. See error

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by walllable** [comment]
Update broke modeldoc, it seems. 
![image](https://user-images.githubusercontent.com/10066958/116362066-a9933d80-a7cf-11eb-89b9-624869300ff7.png)

**Comment by garrynewman** [comment]
this fucking build system 🤕

**Comment by walllable** [comment]
lol yeah it looks like it's causing a lotta headaches

**Comment by handsomematt** [comment]
Just got around to testing this again, works fine now 👍
