### ISSUE TITLE
Camera Component Render Exclude Tags do not exclude Particles with Tags

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4800]
### Describe the bug

The "Render Exclude Tags" property on the Camera Component does not exclude Particles.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/7fbc7e93-332e-43d5-b4ea-a9f028cac11b)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/e46fccee-0441-44fa-ae83-c364f47fa12e)

### To Reproduce

Create the default smoke particle gameobject, tag it with "player" and add "player" to the Render Exclude Tags on the main Camera Component.

### Expected behavior

It should hide the particles.

**Comment by kurozael** [comment]
I'll fix this, but for now just add `particles` tag to the exclude tags list.

**Comment by kurozael** [comment]
You should find this works in the latest build. Have a go - if you have any issues let me know :)
