### ISSUE TITLE
When launching from sbox-launcher.exe, custom components present as `Missing Component`

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4802]
### Describe the bug

Launching from sbox-launcher.exe leads to all components in the codebase missing from the GameObjects in the scene.
![image](https://github.com/Facepunch/sbox-issues/assets/57276947/018e545a-1aa6-4d99-895a-97abb3e02da0)

### To Reproduce

1. Open sbox-launcher.exe
2. Click on a GameObject with a component that isn't included in the base group of components (ie your own Component made for this project)
3. Notice the component is replaced with Missing Component

### Expected behavior

The components should load as normal

**Comment by handsomematt** [comment]
The scene is getting loaded before the components are fully loaded, you should be able to reload the scene and it'd work for now.

I'll have a look after dinner if garry doesn't beat me to it. This stuff gets a lot neater from here now since we only have reliable startup path

**Comment by kira0x1** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/716e3caf-f182-43d9-ac3f-eaabfb804ac1)

same thing for me, and like @handsomematt said reloading the scene fixed it back for me

**Comment by trundlr** [comment]
Reloading the scene doesn't appear to be resolving it for me, not sure why. But I appreciate you looking into it.

**Comment by trundlr** [comment]
I tried that too with no luck 😛

**Comment by kira0x1** [comment]
> I tried that too with no luck 😛

damn

**Comment by PolSpock** [comment]
I have the same issue with "Missing Component" and "[GameMenu] TypeLibrary couldn't find Component type"
I have it since the end of January, and this is my trick to get fixed :

> hi, i'm the only one who had trouble with  [GameMenu] TypeLibrary couldn't find Component type  since yesterday ???
> No one complains about so, yes i think i'm the only one, but i have no fucking hint to fix that shit
> 
> edit: ok i have no fucking idea why, but i have created a Component through the + Add Component  button and magically TypeLibrary has reloaded all my shitty components, and then its works again.(https://discord.com/channels/833983068468936704/837215495496663040/1200363278967255080)

**Comment by anthonysharpy** [comment]
> I have the same issue with "Missing Component" and "[GameMenu] TypeLibrary couldn't find Component type" I have it since the end of January, and this is my trick to get fixed :
> 
> > hi, i'm the only one who had trouble with  [GameMenu] TypeLibrary couldn't find Component type  since yesterday ???
> > No one complains about so, yes i think i'm the only one, but i have no fucking hint to fix that shit
> > edit: ok i have no fucking idea why, but i have created a Component through the + Add Component  button and magically TypeLibrary has reloaded all my shitty components, and then its works again.(https://discord.com/channels/833983068468936704/837215495496663040/1200363278967255080)

Oh damn that actually worked for me too, thanks. I had to reload the scene after doing it though.

**Comment by MrBrax** [comment]
is this the same as #4273 ?
