### ISSUE TITLE
Collider Hull 'Type' property weird UI interaction with RigidBody

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4803]
### Describe the bug

The "Type" property in the new Collider Hull component seems to have a weird interaction with the RigidBody (Or more?).
When rigidbody isn't collapsed, and has at least one other uncollapsed component, the type selection window seems to appear at the bottom right corner of the screen rather than on top of the property itself.
It doesn't happen when the other two components are uncollapsed and the rigidbody is collapsed.

### To Reproduce

1. Add a Model Renderer component
2. Add a Box Collider component
3. Add a Rigid Body component
4. Add a Hull Collider component
5. Keep them all uncollapsed, try opening the "Type" property in Hull Collider
6. Now either collapse the rigidbody component, or both the box and model, open the "Type" property

### Expected behavior

.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/59583743/ae5d332d-bd02-4d18-b348-062765247fe0

### Additional context

No errors in the console.
Haven't tried any other component combination.
Doesn't seem to happen to other enum properties

**Comment by aylaylay** [comment]
I can't get this to happen. I highly doubt this has anything to do with that specific property or anything to do with the other components

**Comment by aylaylay** [comment]
I've pushed a change that might fix it but probably not. If I can't repro it there's not much I can do.

**Comment by yuberee** [comment]
Doesn't seem to happen anymore!
