### ISSUE TITLE
Closing all scenes throws an error

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4804]
### Describe the bug

If you close every scene, the last frame of what scene you were looking at still shows and clicking anywhere throws an "object reference not set to an instance of an object" error. Sometimes I need to close a scene to sort of "refresh" it when something is behaving weird, and just closing and reopening the scene doesn't actually work, I have to load another scene first.

### To Reproduce

1. Open a scene
2. Close the scene with no other scenes open
3. Click anywhere in the viewport

### Expected behavior

this should be handled a bit more elegantly, I'm not sure in what way, but having no scene loaded at all should be a possible state instead of the last scene you had open being half loaded.

**Comment by garrynewman** [comment]
I get the last scene showing, but I don't get any error

**Comment by DrakeFruit** [comment]
if I try to click on the viewport or hierarchy I get an error. Doesn't really annoy me but the scene not fully unloading does.

**Comment by garrynewman** [comment]
I am getting no errors
