### ISSUE TITLE
You should not be able to join lobbies of previous versions of games

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4805]
### Describe the bug

My game is a Quick Play game like such:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/4ef4e5b4-d803-4fee-8fd7-6683d0d414dc)

So people automatically join live lobbies when they play. This means when I push an update, people are still connecting to the servers running the old version. This should not be possible

### To Reproduce

Kind of tough to repro but set your game to quick play like above and then push an update while other people have a lobby going and try to play the game in a new instance while their lobby still exists

### Expected behavior

You should not be able to join mismatched game versions

**Comment by Retroeer** [comment]
I feel like this could also be extended to games checking for updates everytime they're launched rather than per-s&box launch. 
Kind of annoying to have to restart the entire game just to get an update.
