### ISSUE TITLE
Saving prefab in prefab editor replaces reference to root gameobject with reference to prefab file

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4808]
### Describe the bug

When a prefab is initially created from a GameObject in the scene, its components' properties that reference the root GameObject use the GUID as expected. For example:
```
"Body": {
          "_type": "gameobject",
          "go": "7568fd5b-3a56-4323-b984-abd71a2c4370"
},
```
But after opening the prefab in the editor and hitting Ctrl+S to save, the property then stores a reference to the prefab file instead:
```
"Body": {
          "_type": "gameobject",
          "prefab": "prefabs/floating_cube_2.prefab"
},
```
This makes it so that any code using this property will end up not having an effect on the actual GameObject in the scene. In the case of the attached repro project, the SineHover component no longer makes the cube float up and down.

### To Reproduce

1. Import the attached Prefab Root Reference Repro.zip
2. Open minimal.scene
3. Duplicate the "Floating Cube" object
4. Convert that object to a prefab (e.g. "floating_cube_3.prefab")
5. Hit play and confirm that the new cube hovers up and down
6. Open the newly created prefab file
7. Hit Ctrl+S to save the file in place
8. Run the minimal scene again
9. Observe that the cube linked to the new prefab no longer moves at all

### Expected behavior

When saving a prefab in the editor, references to specific GameObjects should not be converted to references to a prefab file.

### Media/Files

[Prefab Root Reference Repro.zip](https://github.com/Facepunch/sbox-issues/files/14303410/Prefab.Root.Reference.Repro.zip)

**Comment by garrynewman** [comment]
This should be fixed now
