### ISSUE TITLE
Error loading any local game

### ISSUE THREAD

**Issue by accurateisaiah** [Facepunch/sbox-issues#481]
**Describe the bug**
When loading local game it does not load and gives an error of `Couldn't find property GameScreen.JoinGameButton Object reference not set to an instance of an object. `

**To Reproduce**

1. Go to 'local game button (the floppy disk)'
2. Click on 'your local game'
3. Click on 'Start Game'

**Expected behavior**
`Load the gamemode`

**Screenshots**
![image](https://user-images.githubusercontent.com/44090193/126521936-508ab542-eec8-4475-b61e-fd8f754335eb.png)

**Additional context**
None

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by Jaydawg8888** [comment]
I'm also getting a very similar issue where I cannot create any local games. 
![image](https://user-images.githubusercontent.com/36142372/126566984-681f6a50-5fac-48a0-b331-402e8d225a77.png)
(tried sandbox, poole etc and none of it works for me)

Joining games through party seems fine, its just creating a game no longer works. Not sure how I can resolve this?

**Comment by accurateisaiah** [comment]
Fixed with update
