### ISSUE TITLE
Citizen "break pieces" to show damage / dismemberment

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4810]
### For?

Other

### What can't you do?

except for decals, there's no way to show Terry has been damaged in any way.

### How would you like it to work?

I'm not sure how you do this in modeldoc, but being able to swap parts of Terry's body out for damaged or even missing versions would be really useful in any context where you would shoot or otherwise hurt Terry.

### What have you tried?

placing some decals on terry's body or shrinking the bones to make it look like parts are missing, really jank and doesn't look right.

**Comment by garrynewman** [comment]
I don't know how possible this is. If we make him lose am arm for example, every clothing item would have to have an alternate version with no arm?

**Comment by DrakeFruit** [comment]
I think that's for devs to deal with. Not every clothing option has to work perfectly with everything else imo. Even just some visible damage on him would be nice.

**Comment by MaxLebled** [comment]
> I don't know how possible this is. If we make him lose am arm for example, every clothing item would have to have an alternate version with no arm?

Could use bone scaling on the clothing mesh to hide the cut off bit

**Comment by DrakeFruit** [comment]
I just realized there's a fucking word for this, it's gibs 😭

**Comment by DrakeFruit** [comment]
[sbox](https://commits.facepunch.com/Danduw/sbox)[/master](https://commits.facepunch.com/Danduw/sbox/master)[#97633a](https://commits.facepunch.com/471303)
