### ISSUE TITLE
Ignore or limit decals to certain tags / objects

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4811]
### For?

S&Box

### What can't you do?

When using a decal, there's no way to control which objects it can and can't project on to.

### How would you like it to work?

Either a tag or gameobject field for ignoring / restricting the decal to projecting on to.

### What have you tried?

making the decal box really small and placing it really close to the object.

**Comment by handsomematt** [comment]
Not feasible

**Comment by badandbest** [comment]
Shouldn't this be reopened?
