### ISSUE TITLE
Stats.SetValue() adds to the stat instead of setting it.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4812]
### Describe the bug

Right now Stats.SetValue() does the same thing as Stats.Increment. It adds to the current stat instead of setting it.

### To Reproduce

1. Make a stat.
2. Try using Stats.SetValue(). It adds to the stat instead of setting it.

### Expected behavior

Stats.SetValue() should override the stat with the new value.

**Comment by agincel** [comment]
Still an issue. Creative use of Leaderboards as a hacky way of filtering for lowest/highest submission can be used to kinda work around the issue, but definitely not working as desired or expected.

**Comment by TrvsF** [comment]
still seeing this
