### ISSUE TITLE
Library .razor classes can't find files in the same library.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4813]
### Describe the bug

I'm making a library with a few components, and I've found that .razor classes can't find stylesheets, images, etc placed in the same library.

### To Reproduce

1. Create a .razor class in a library
2. Try to load a stylesheet from the same library.

### Expected behavior

It should be able to use stylesheets, images, etc from the library it's in.

### Media/Files

Using the Razor Panel template

![image](https://github.com/Facepunch/sbox-issues/assets/91832803/9c9b5a1e-b6aa-47ae-9cae-b4a5ec93ba38)

![image](https://github.com/Facepunch/sbox-issues/assets/91832803/b4c65a65-b882-4c71-960e-d02f5d8b0c88)

Doesn't load the style sheet
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/8ee44521-0582-41cc-91b4-32777140902d)

**Comment by garrynewman** [comment]
Libraries no longer exist so I guess we solved that one

**Comment by badandbest** [comment]
This is still an issue in the new library system.

**Comment by Xenthio** [comment]
bump

**Comment by Xenthio** [comment]
reopening new issues as #5522 since this issue might be different from what is happening now.
