### ISSUE TITLE
Render tag for lights

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4815]
### For?

S&Box

### What can't you do?

I'm unable to make lights loaded from a map affect my viewmodel (rendered on a seperate camera), Lights used to automatically have a lights tag that was place on them, this doesn't seem to be the case anymore

### How would you like it to work?

It would be nice if lights had tags for being a light and what kind of light they are, the wiki says the game used to do this
```
Lighting
All lights automatically have the light tag applied, but some lights will have additional tags applied such as spotlight, ortholight, or envlight. - From the Wiki
```

### What have you tried?

I've tried iterating through all lights after a map load to assign them their tags, but it seems kinda dumb to do this when I feel like it should be built in.

**Comment by handsomematt** [comment]
Duplicate #4778

**Comment by Xenthio** [comment]
Not duplicate, the other issue seems to be about hammer entities not having their tags loaded onto gameobjects.
This is about all lights, hammer or not, having that their own tags.
