### ISSUE TITLE
Cant create List with Models 

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-issues#4818]
### Describe the bug

Can't create a List that features Models. Each time I try to it results in the following error 
```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Editor.ListControlWidget.OnPaint() in D:\SteamLibrary\steamapps\common\sbox\addons\tools\code\Widgets\ControlWidgets\ListControlWidget.cs:line 94
   at Editor.Widget.InternalPaintEvent(QPainter e, Int32 flags)
   at Managed.SourceTools.Exports.Editor_Widget_InternalPaintEvent(UInt32 self, IntPtr e, Int32 flags)
```

### To Reproduce

1. Make Component
2. Add 	[Property] private List<Model> modelList;
3. Look as it dose not show the list 

### Expected behavior

It should show the List.

**Comment by Gmod4phun** [comment]
You have to make it a property, not a field.

```cs
[Property]
private List<Model> modelList { get; set; }
```

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/dcb7f471-ae34-4fbb-a02c-19f351b917b7)

**Comment by Fortune117** [comment]
fields can also be serialized, this is probably a bug

**Comment by cr4yz** [comment]
This seems to be fixed, please re-open with reproducible code if it's still happening for you.
