### ISSUE TITLE
Settings button in welcome screen does nothing

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4819]
### Describe the bug

After a recent update, the settings button does nothing.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/7757d64d-70cd-4831-bf36-d1504e346bf6)

This makes it impossible to change the code editor before launching a project, which for some reason seems to now be Visual Studio, despite having set it to VSCode before.  Its now only possible to access the editor settings after loading a project, then going to Edit -> Editor Settings.

### To Reproduce

1. Start editor
2. Try to open settings

### Expected behavior

Settings button should open the settings menu

**Comment by garrynewman** [comment]
Fixed thanks
