### ISSUE TITLE
Libraries stopped working today

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4820]
### Describe the bug

My libraries completely stopped working today. Is it because of the new ProjectList?

### To Reproduce

1. Try to add a package reference
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/20ec6f92-5bb1-494f-bd61-6becd2182f73)

2. Nothing happens 😭

### Expected behavior

It should load the library either from asset.party or locally if it's in the project list.

**Comment by garrynewman** [comment]
Yep these won't work anymore until we re-implement them. That is going to be a low priority so you should move the code into your game project for now.
