### ISSUE TITLE
Sound definitions are broken for older .sound versions

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4821]
### Describe the bug

I am unsure when this issue started happening, but I've been moving some sounds from a content project (since they got removed) to the game project, and to my surprise, sounds are not playing anymore. It seems like the .sound file structure is different than when I made the sounds, and the sound is not parsed properly from the definition.

Here are the contents of the current version of the .sound file:
```
{
	"data":
	{
		"UI": false,
		"Volume": 1,
		"VolumeRandom": 0,
		"Pitch": 1,
		"PitchRandom": 0,
		"Decibels": 50,
		"Sounds":
		[
			"sounds/sbox_stargate/dhd/atlantis/press.vsnd"
		],
		"SelectionMode": "Random",
		"MaximumDistance": 599.313050,
		"MinimumDistance": 29.965652
	}
}
```

If I modify the file to look like this (basically just moving it out of the 'data' block), the sound works fine:
```
{
	"UI": false,
	"Volume": 1,
	"VolumeRandom": 0,
	"Pitch": 1,
	"PitchRandom": 0,
	"Decibels": 50,
	"Sounds":
	[
		"sounds/sbox_stargate/dhd/atlantis/press.vsnd"
	],
	"SelectionMode": "Random",
	"MaximumDistance": 599.313050,
	"MinimumDistance": 29.965652
}
```

After forcing a re-save on the new file, the final format looks like this:
```
{
  "UI": false,
  "Volume": "1.00,1.00,0",
  "Pitch": "1.00,1.00,0",
  "Decibels": 50,
  "SelectionMode": "Random",
  "Sounds": [
    "sounds/sbox_stargate/dhd/atlantis/press.vsnd"
  ],
  "__references": []
}
```

Here is how it looks in the inspector before and after the changes:
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/0f1b18cf-d50e-4b8d-a41b-8238924a1ef1)

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/fedfca8a-340b-4db5-a90f-44bc51b887a6)

### To Reproduce

1. Have an older .sound file definition
2. Try to play the sound ingame/check the inspector to see if its loaded correctly
3. See that it does not play/is not loaded correctly

### Expected behavior

The sound definition should be updated to the current format without losing any necessary data.

**Comment by garrynewman** [comment]
Thanks - I fixed the conversion code that was causing this.

If you revert your assets back to the old keyvalue format, they should now get upgraded properly.

**Comment by Gmod4phun** [comment]
Thanks, I will check it as soon as the build goes live
