### ISSUE TITLE
Saving Project Settings has no effect

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4822]
### Describe the bug

After changing Project Settings in the S&box Editor and hitting Save, the sbproj on disk is not modified at all. I can close and reopen the Project Settings window to view the change, but after closing and reopening the editor, the old settings are used again.

### To Reproduce

1. Open a project in the S&box editor
2. Open project settings and modify a setting (e.g. the name of an input)
3. Click the blue save button
4. Observe that the change is not reflected in the sbproj file
5. Close and reopen the S&box editor
6. Open the project settings again
7. Observe that your previous change did not save

### Expected behavior

Project settings should be saved to disk immediately after you click save in the Project Settings window.

**Comment by garrynewman** [comment]
Should be fixed next build

**Comment by chrisspieler** [comment]
It works now, thanks!
