### ISSUE TITLE
Game shows a black screen when closing a scene

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4824]
### Describe the bug

The game shows a black screen when closing a scene

### To Reproduce

Create a new scene a play it.

### Expected behavior

The scene should close properly.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/bf9c602d-fd66-4fab-bae3-c84c640fb8a1

**Comment by garrynewman** [comment]
Can't reproduce here. I see in the video you get errors, can you provide them?

https://docs.facepunch.com/s/sbox-dev/doc/reporting-errors-2OTPIafqCJ

**Comment by Nolankicks** [comment]
Can't find the correct log. Must have been deleted. I'll send a new one once I get the bug again. I was still getting it as of last night.

**Comment by Nolankicks** [comment]
Ignore my Log.Info's, just scroll to the bottom
[Log.1143.log](https://github.com/Facepunch/sbox-issues/files/14319324/Log.1143.log)
