### ISSUE TITLE
Model Renderer Tint at runTime 

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-issues#4825]
### Describe the bug

The Tint on the Model renderer is just completely messed up when setting it at runtime compared to yesterday. For example ( 50, 153, 37 ) this should be some sort of green is instead a odd purple colour. 

### To Reproduce

1. Add new Component to Empty Game Object 
2. Add this code 
```
public class Test : Component
{
	[Property] private Model _prefabFi;


	protected override void OnEnabled()
	{
		base.OnEnabled();
		
		var tile = new GameObject();
		var model = tile.Components.Create<ModelRenderer>();
		model.Model = _prefabFi;
		model.Tint = new Color( 50, 153, 37);
	}
}
```
3. Watch as green turns to purple.

### Expected behavior

It should be the correct colour. 

### Additional context

All the Code I shared worked as of yesterday night before the change to the new standalone engine or whatever happened.

**Comment by garrynewman** [comment]
Colors are from 0-1 - Color( 0, 1, 0 ) is green

**Comment by B0zy** [comment]
Got it, so confused how it worked fine few days ago then.
