### ISSUE TITLE
Ability to move map instances.

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4826]
### For?

S&Box

### What can't you do?

I'm unable to move around a map instance once it's loaded, only the collision and objects parented to it get moved.

### How would you like it to work?

It would be really helpful if we could have the map parented to the object that the maploader component is on

### What have you tried?

I have tried to see if I could get the sceneobject of the map to move it directly, but it seems I can't.

**Comment by the-remeko** [comment]
At least spawn the map at the Map Instance's position instead of 0,0,0.

**Comment by B0zy** [comment]
> At least spawn the map at the Map Instance's position instead of 0,0,0.

Isn't spawned at 0,0,0 already? Its built off to the top right corner of it, unless you mean for it to be centered on 0,0,0?

**Comment by the-remeko** [comment]
> > At least spawn the map at the Map Instance's position instead of 0,0,0.
> 
> Isn't spawned at 0,0,0 already? Its built off to the top right corner of it, unless you mean for it to be centered on 0,0,0?

We can't pick where the map spawns, it's always spawned at 0,0,0.

**Comment by KingOfTheFBI** [comment]
Bump

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/beee7b77-1159-44d0-926a-bb4b046cc5aa
