### ISSUE TITLE
Focus behavior when nothing is selected.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4828]
### Describe the bug

Currently when you press 'F' to focus while having no object selected, it focuses on 0,0,0. Not sure if this is a bug or intended, but the behavior imo is odd. 

### To Reproduce

1. Create a scene with some objects
2. Press F while having one selected, this works fine.
3. Press F while having none selected, now it zooms in at 0,0,0?

### Expected behavior

It should not do anything.

**Comment by fantasticaneer** [comment]
I don't think this is unusual or a bug, it's nice to have. But I do wish that it didn't zoom in quite so close so that it's literally exactly at 000.
