### ISSUE TITLE
Opening a project causes to screen to go black

### ISSUE THREAD

**Issue by CinarBayramic** [Facepunch/sbox-issues#4830]
### Describe the bug

when i open a project the entire screen becomes black but you can interact with it and see it when in tabbing menu

### To Reproduce

1. open the editor
2. open a project
3. view another tab(updating the window the project is in works too)
4. go back to the project
5. the screen goes entirely black except for the steam notifications

### Expected behavior

the window should visible

### Media/Files

[Log.19.log](https://github.com/Facepunch/sbox-issues/files/14318380/Log.19.log)

### Additional context

I'm running on Windows 11
i just updated my graphics drivers
also when i open an app over it like the screenshot tool it becomes visible for the duration

**Comment by CinarBayramic** [comment]
clicking on the assets browser fixed it.

**Comment by garrynewman** [comment]
Can you post a screenshot. Is just the game window black, or all windows? If you resize the window, does it change?

**Comment by CinarBayramic** [comment]
the file is too big would you mind if i cut the loading process or can i send it from discord

**Comment by garrynewman** [comment]
Sure DM me on discord

**Comment by handsomematt** [comment]
I fixed this a few weeks ago, could you let me know if it's still happening

**Comment by CinarBayramic** [comment]
yeah it stopped happening thanks
