### ISSUE TITLE
RSS feed for Asset.Party URLs

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4832]
### For?

Other

### What can't you do?

Most Facepunch websites have an RSS feed. 
(https://sbox.game/rss) (https://rust.facepunch.com/rss)
Would be awesome if asset.party had some sort of dynamic RSS feed for any page.

### How would you like it to work?

Due to how naming works in asset.party, you couldn't just add /rss to the end of the URL.
I don't know how it could be achieved, perhaps a special character at the end of the url like this:

asset.party/fish$rss
asset.party/$rss
asset.party/t/map/newest$rss
asset.party/api$rss

or even a subdomain

rss.asset.party/fish
rss.asset.party/t/map/newest

### What have you tried?

I'm currently using an RSS feed creator to detect when new games are added to asset.party.
It either costs money or updates only once a day.

### Additional context

Not sure how feasible or scalable it is.
When S&box grows I can see it becoming expensive to keep up, but I wouldn't know.

**Comment by garrynewman** [comment]
Is it being RSS a hard requirement?

https://services.facepunch.com/sbox/package/list
https://services.facepunch.com/sbox/package/find?q=type:game%20sort:updated
https://services.facepunch.com/sbox/package/find?q=type:game%20sort:updated%20org:facepunch

**Comment by yuberee** [comment]
Yep got that hooked up now.
Pretty epic, thanks.
