### ISSUE TITLE
Can't drag models from asset browser into component properties

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4834]
### Describe the bug

When you try and drag a model from the asset browser into a component's model property it won't work yet it will still highlight as if you can.

### To Reproduce

Reproduction above

### Expected behavior

Dragging the model in should work.

### Media/Files

Only started happening recently, around a few days to a week ago.

**Comment by garrynewman** [comment]
Can you show me a screenshot? I swear this worked for me last time I did it

**Comment by ScoutWozniak** [comment]
Seems like it specifically happens when trying to drag a model while having the cloud tag applied in the asset browser?
https://github.com/Facepunch/sbox-issues/assets/99102549/2b4dcf8d-63ca-4216-b31d-f1cd19c84a7b

**Comment by garrynewman** [comment]
This should work now - let me know

**Comment by ScoutWozniak** [comment]
Sorry for the late response but thanks for the quick fix!
