### ISSUE TITLE
Add VS Codium support

### ISSUE THREAD

**Issue by bailmast** [Facepunch/sbox-issues#4836]
### For?

S&Box

### What can't you do?

I can't use VS Codium as default editor

### How would you like it to work?

To stop notifying that I probably need Visual Studio and just open VS Codium

### What have you tried?

I have tried to open project in VS Codium by myself

**Comment by DevulTj** [comment]
You're free to implement your own support using the CodeEditor class, but I don't think we should be supporting every IDE under the sun.

**Comment by DrakeFruit** [comment]
would it be possible to just let the user choose "other" and select an exe? you're just opening the file or solution with the exe under the hood aren't you?

**Comment by bailmast** [comment]
I'm not saying that every code editor should be supported, but VSCodium is one of the most popular "alternatives" to Visual Studio. And probably Code - Insiders support would be great.

**Comment by Retroeer** [comment]
I'm gonna agree with Tony on this one, this is a slippery slope, if adding a Code Editor is as easy as he proposes then it should be fine, people using obscure editors probably know what they're doing anyway.
