### ISSUE TITLE
Prefabs are caching improperly and requires restart to instantiate new versions

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4837]
### Describe the bug

Whenever I make a change to any of my prefabs I have to restart s&box to see the changes since my game continues to instantiate a previously cached version of the prefab.

### To Reproduce

1. Make a prefab of a cube or something.
2. Have a component in your game that instantiates a new cube every second.
3. Running the game will instantiate cubes.
4. Open the prefab and change the cube to a sphere
5. Save the prefab
6. Running the game will *still* instantiate cubes
7. Restart s&box
8. Running the game will instantiate spheres

### Expected behavior

It should dirty the cache when you save changes to a prefab

**Comment by kurozael** [comment]
Hey @CarsonKompon is this still an issue? I can't seem to reproduce it.

**Comment by CarsonKompon** [comment]
I havent experienced the issue since the game jam ended I don't think. Been using prefabs in my latest project without issues.

**Comment by NotGaylien** [comment]
someone seemed to have fixed this issue around the last few days of the game jam or just after it ended.

only issue like it now is this one, https://github.com/Facepunch/sbox-issues/issues/5133

**Comment by kurozael** [comment]
Great stuff.
