### ISSUE TITLE
[Launcher] Project selection should provide visual feedback

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#4838]
### For?

S&Box

### What can't you do?

Select a project without clicking it more than once. This is entirely my fault and dumb, but I'm not the only person this happens to and it's annoying wasting time because a second editor instance is now opening.

### How would you like it to work?

On selection of a project, either minimize the launcher, or disable selection controls (+ greyout, visual feedback) for a few seconds.

### What have you tried?

Slapping myself every time I double-select so I drill into my brain not to do it.

**Comment by DrakeFruit** [comment]
maybe minimize to tray as an editor preference?

**Comment by handsomematt** [comment]
I just made it so it doesn't open the same project more than once.
