### ISSUE TITLE
Can't host game...

### ISSUE THREAD

**Issue by Acecool** [Facepunch/sbox-issues#484]
**Describe the bug**
When trying to host a game of any type ( either up-to-date local github clones, my library, random downloadable gm ) it hangs on Creating game after showing an issue about being an uninitialized object with no other information in terms of path, line, etc...

**To Reproduce**

**Expected behavior**
Expected to launch the game...

**Screenshots**

**Additional context**

It started after one of the latest update ( where the create game with player count became a column instead of its own page ).

**Comment by Acecool** [comment]
Note: I have verified integrity and 4 files were replaced ( StackTrace.cs being one I edited ) and I ran it again after the fact with no files being incorrect and the problem persisting.

I did try connecting with the default StackTrace.cs file - problem persisted... The change I made was a simple word-wrap and adding new lines to ensure the first line is below the "compile failed" or "compile succeeded" message as one of those sticks around for about a minute..

**Comment by garrynewman** [comment]
The actual error would be useful here

**Comment by Acecool** [comment]
It gets stuck and eventually the hang screen shows - attached is the output trying to launch the latest git-cloned sandbox..

```
![Screenshot 2021-07-22 08 15 00](https://user-images.githubusercontent.com/4174280/126637497-1f08c120-534e-43da-aaf5-45fa8eb7ebfb.png)
![Screenshot 2021-07-22 08 14 48](https://user-images.githubusercontent.com/4174280/126637504-f94042e2-2dd4-4b96-b3bb-111435211b0e.png)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Acecool** [comment]
Awaiting update and when I see it I'll close if resolved, or update / reply if it isn't.
