### ISSUE TITLE
Can't disable physics of Map Instance

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4844]
### Describe the bug

The Map Instance component creates a Map Collider component, which I would assume acts as the physics for the map. However, disabling the Map Collider does not disable the physics of the map instance. Even removing every single child from the Map Instance does not do anything to the physics.

### To Reproduce

1. Create a Map Instance
2. Try to disable the physics

### Expected behavior

Disabling the Map Collider should disable the map physics.

**Comment by aylaylay** [comment]
Should be working now

**Comment by Gmod4phun** [comment]
Indeed seems to work, however there is a new issue now. When I play the scene, disable the map collider and then stop the scene, the whole editor stalls, I suspect an infinite loop somewhere?

**Comment by aylaylay** [comment]
What map does this happen on? I'm trying on datacore and it doesn't stall

**Comment by Gmod4phun** [comment]
Tried it with Flat Grass. I will do some more testing tomorrow in a clean game, other maps, combo of those. It could be that something in my game causes it, but it definitely should not happen tho.

**Comment by aylaylay** [comment]
Yep it stalled on flatgrass, pushed a fix

**Comment by Gmod4phun** [comment]
No stalling anymore, seems good :)
