### ISSUE TITLE
Middle mouse to close scenes/prefabs in Hierarchy Tab list

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#4848]
### For?

S&Box

### What can't you do?

I can't quickly close specific open Scenes/Prefab tabs in the Hierarchy via middle mouse like I could with browser or file explorer tabs. Editor tool window tabs also close this way.

![sbox-dev_CLuW2ZUvxb](https://github.com/Facepunch/sbox-issues/assets/12602100/c9df76b1-dea0-4130-bf48-4115edd84b89)

### How would you like it to work?

Just Middle clicking on one of these should be like rightclick > close, including any save notifications for unsaved scenes etc.

### What have you tried?

There's some nice Closing options via the tab context menu, but if you want to delete specific tabs out of a list, you need to rightclick each first

![CnTbq3IWW2](https://github.com/Facepunch/sbox-issues/assets/12602100/5b39fbb5-9148-4b94-a9d5-bd8573f79bb2)

**Comment by DevulTj** [comment]
Added
