### ISSUE TITLE
Synced properties do not update properly on inherited component classes

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4850]
### Describe the bug

When using inheritance, properties on the parent that are synced do not seem to sync to clients consistently.

Example:
```cs
public abstract class MyParent : Component
{
    [Sync] public Vector3 WishVelocity { get; set; }

    protected override void OnUpdate()
    {
        if ( IsProxy ) return;
        WishVelocity = Vector3.Random;
    }
}
```

```cs
public class MyChild : MyParent
{
    protected override void OnUpdate()
    {
        base.OnUpdate();
        
        // This WishVelocity is not properly synced up on clients
        Log.Info( WishVelocity );
    }
}
```

### To Reproduce

1. Use the [Sync] attribute on a property on a parent component class
2. Make a child component class that attempts to reference the synced property
3. Test in multiplayer - value is updated on the host but not the clients

Feel free to message me on Discord (trundler) or within this issue if you are having trouble reproducing the issue.

### Expected behavior

The synced properties should sync to clients as expected.

**Comment by kurozael** [comment]
This should be sorted in the next build - lemme know if you have any problems :)
