### ISSUE TITLE
Game not on correct version despite saying its on the latest version.

### ISSUE THREAD

**Issue by WhalesMW** [Facepunch/sbox-issues#4851]
### Describe the bug

My game is published to asset.party/s&box and its stuck on an older version even thought the newest one is the live version. 

### To Reproduce

No Idea How.

### Expected behavior

It should be on the Live version.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/147272332/80565f8b-3471-4ced-8655-d7342ec4602f)
Stuck on the circled one.

**Comment by garrynewman** [comment]
What makes you think it's on the older version?

**Comment by WhalesMW** [comment]
Fixed itself a few hours later now. So im gonna close this but. Nothing was changing ingame from the version highlighted. Despite it showing it was on the latest version which in editor has tons of changes.
