### ISSUE TITLE
Allow Prefabs to Be Selected In Editor

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#4853]
### For?

S&Box

### What can't you do?

![image](https://github.com/Facepunch/sbox-issues/assets/15205856/390a9c82-f045-4e3a-b232-db8d97bc1451)
When I select an empty prefab reference on a game object I should be able to select that prefab from the asset browser.

### How would you like it to work?

Similar to how textures can be assigned in game resources. 

### What have you tried?

Right now you just drag it directly from the asset browser.

**Comment by DevulTj** [comment]
https://github.com/Facepunch/sbox-issues/assets/22372616/7294b31e-65d2-498a-bad5-58b10c48ef44

Added
