### ISSUE TITLE
Better Component Reordering

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4857]
### For?

S&Box

### What can't you do?

I currently cannot quickly and easily reorder components, you have to right click the component and select "Move Up" or "Move Down" to reorder it.

### How would you like it to work?

A drag and drop reorder system.

### What have you tried?

Crying to myself for a bit I suppose.

**Comment by DevulTj** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/4254
