### ISSUE TITLE
Component Categories

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4859]
### For?

S&Box

### What can't you do?

Currently, all Components get stacked onto a GameObject, this can eventually get pretty messy and there's no real way to properly organize it. (Aside from shifting them up and down)

### How would you like it to work?

Categories for Components that you'd be able to drag and drop them into via #4857. 
Ex: 
```
CameraComponents/
├─ CameraMovement
├─ etc.
PlayerComponents/
├─ PlayerHealth
├─ PlayerController
├─ etc.

```

Hell you could even make it colorable, would be alot easier on the eyes than the current implementation 

### What have you tried?

Moving related components together helps but ultimately just feels kinda gross. Everything is colored the same and the only real way to tell at a glance is what the component starts with

**Comment by garrynewman** [comment]
This would still be messy
