### ISSUE TITLE
Allow gamemodes to use no map

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#486]
**What can't you do?**

I have to make an empty map in Hammer if I'm making something purely procedural generated.
Not the most annoying thing to workaround, but seems like a common enough use case and saves a download of an empty map to clients.

Some sort of map to override the map name (in steam status or server browser?) from the Game would also be great for some games where maps are loaded at runtime completely.

**How would you like it to work?**

Tick box on the dev site would be good.

**Comment by AdamSai** [comment]
+1, I'm also making a gamemode where I dont need a map. Atm I use Gavarados empty.map

**Comment by handsomematt** [comment]
not stale
