### ISSUE TITLE
Multi Select Rotation doesn't behave as expected

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4861]
### Describe the bug

I would expect objects to maintain their relative positions when rotating a multi selection, however you can see that is not the case:

https://github.com/Facepunch/sbox-issues/assets/7847372/dab61e68-bce2-4d19-8575-5b68ba12e0f7

### To Reproduce

1. Select several objects
2. rotate them

### Expected behavior

Multi selected objects should maintain their relative positions when rotated as a group.

**Comment by Fortune117** [comment]
There's a similar issue with moving multi selected objects with grid snapping enabled
https://github.com/Facepunch/sbox-issues/assets/7847372/8a5bdffa-0bd8-4ebb-a2ab-0991f31496b3

**Comment by chrisspieler** [comment]
A good default behavior would be to rotate around an invisible pivot that exists at the average of every object's position. Ideally we'd eventually get the ability to adjust the pivot, like in Hammer or Blender.

**Comment by aylaylay** [comment]
Done

https://github.com/Facepunch/sbox-issues/assets/1667289/8f2e17dc-9428-4872-8b0f-bb4f4f3bf443

**Comment by aylaylay** [comment]
Fix grid snapping when translating too

https://github.com/Facepunch/sbox-issues/assets/1667289/2eaee84e-6150-4a99-b348-95e98f521981
