### ISSUE TITLE
Renaming a project should update its name in launcher/menu bar/etc

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4862]
After renaming a project in Project Settings,
![sbox-dev_2024-02-18_21-32-09](https://github.com/Facepunch/sbox-issues/assets/1173137/1c003419-cc2c-436c-9641-f1661fe6623f)

Note that the old project name persists in the Project Settings window (this is fixed when you next open Project Settings)
![sbox-dev_2024-02-18_21-33-14](https://github.com/Facepunch/sbox-issues/assets/1173137/c75bedd6-fa22-4ffd-938e-c44dbf0c4304)

And in the editor menu bar (this lasts until you next open the editor)
![sbox-dev_2024-02-18_21-33-57](https://github.com/Facepunch/sbox-issues/assets/1173137/f1b8b31d-54f0-4089-a0b3-4d732ea7ace0)

And in the launcher (this lasts until you click it or re-open the launcher)
![sbox-launcher_2024-02-18_21-35-04](https://github.com/Facepunch/sbox-issues/assets/1173137/e6e1f6e7-6b39-4f0c-8c3b-807b93e3b068)

Also the Save button in Project Settings could really use some more feedback that it's having an effect when you click it:
Before clicked:
![dopus_2024-02-18_21-40-07](https://github.com/Facepunch/sbox-issues/assets/1173137/7306aecb-521b-44fe-997a-0712df455b5f)
After clicked:
![sbox-dev_2024-02-18_21-38-34](https://github.com/Facepunch/sbox-issues/assets/1173137/774abeb2-4441-496f-b93f-fef294ba7f10)

A `*` at the top of the window to indicate unsaved changes would help a lot.

**Comment by xezno** [comment]
Added all this, I think - but let me know if I missed anything

**Comment by ryleigh** [comment]
The project name in the launcher still doesn't update until selecting project/reopening launcher, but not sure how feasible that is anyway
