### ISSUE TITLE
Support Hammer more properly for now until it's replaced so people stop whining and worrying about it, release a public stance on Hammer's future in s&box

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4864]
### For?

S&Box, Hammer

### What can't you do?

I (think I) understand why Hammer support is in the state that it's in, but it's wonky and frustrating right now and doesn't make a good impression on new people getting keys this week and going forward.

- Doors are only sorta supported
- Can't load collision on local hammer maps without using the full local file paths in the Map Instance component (bug?)
- Back faces don't block lighting
- Spot Lights (ie in construct warehouse/parking structure) don't load
- Lighting behaves weirdly per willow in discord:
![sbox-dev_5uYg0IrhwF](https://github.com/Facepunch/sbox-issues/assets/5409303/23c5c7ab-afa3-45f0-ae63-7adb5e23fc25)
- You can spawn multiple maps with multiple Map Instance components... but you can't move the Map Instance spawned map from 0,0,0
- Compiling and choosing to run afterwards just doesn't do anything
- Is compiling/quick build/full build even necessary? That stuff is unclear

Not only is this stuff really bad UX right now, few people in the community seem aware of / agreed upon what Facepunch plans to do with Hammer. A public stance (blog post, #dev-announcements post) would do a lot to help developers understand what the plan is for Hammer.

### How would you like it to work?

Until Hammer is replaced with something better, Hammer should be more properly supported. It should do the things you expect it to do, smoothly. Map Instances should be nice and powerful and work like you'd expect. Maybe even a rudimentary Door and/or Button Component in the mean time.

I understand the fact that you don't want to support something and then be forced to deal with legacy maps expecting them to exist forever, but that doesn't mean doors and buttons and spot lights etc should just be totally broken until the solution is in place.

![Screenshot_20240218-234031](https://github.com/Facepunch/sbox-issues/assets/5409303/8a2eb9cf-c02f-4067-94f5-5a30083f58eb)
*Hammer, as advertised*

As it stands, new people get access to the game and editor, try making something in Hammer, and not just have a bad experience being informed they have to:
- create a new project
- code a playercontroller or nab one from scenestaging/examplecomponents and set it up
- add a Map Instance
- Type the file path to their local vmap file in a text box instead of an asset browser
- Make sure it's the *full* filepath or collision doesn't load 

Then they get it all working and only a basic handful of entities are converted and the lighting is fucky.

And what do they do? They go to discord and go, "what's up with Hammer?" 

And people say, "it only kind of works and Facepunch is getting rid of Hammer one day."

And everyone starts fighting about whether Hammer is the best thing ever, or if it will be wonderful actually when it gets replaced, etc, etc. And people complain they don't want to fuck with the scene system and they just want to do level designing in Hammer because that's what they're used to, and it's all a big mess.

I can see the big picture, but right now people get the impression that Facepunch is a bunch of evil dummies who don't care about dearly beloved Hammer 2 and are going to remove it forever and replace it with Unity Probuilder But Worse one day, and in the meantime Hammer will be a broken mess and fuck anyone who wants to make levels and test them locally without becoming a C# developer and rolling their own player controller etc.

### What have you tried?

Talking to people and convincing them the sky is not falling and Hammer will be better supported soon, and when it's inevitably replaced, the replacement will be better anyway.

### Additional context

I've had a few conversations in the discord over the past month and they often devolve into people being scared or frustrated about Hammer and the future of Hammer support.

I wasn't sure about submitting this but I wrote it on my phone and can't easily save it as a draft somewhere so I'm going to hit submit. Love ya lads thanks for reading my fuckin blogpost.

**Comment by garrynewman** [comment]
Thanks for writing this up, but I think this would have been best as a separate issues, rather than one mega issue. I'm going to close this but feel free to make issues for each of your specific points (assuming the issue doesn't already exist)
