### ISSUE TITLE
Component interfaces not present on the docs

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#4866]
### Location

https://docs.facepunch.com/s/sbox-dev/doc/components-zIujvXKpIl

### Summary

Adding a list of all the different interfaces a component can have (e.g. CollisionListener, TriggerListener) and explanations of such would be really nice to have as they aren't really shown anywhere.

**Comment by cr4yz** [comment]
https://docs.facepunch.com/s/sbox-dev/doc/component-markers-xtiSAW7DiL

Please let me know if there's any confusion or improvements to be made.
