### ISSUE TITLE
Component Tagging/Naming

### ISSUE THREAD

**Issue by rlenhub** [Facepunch/sbox-issues#4868]
### For?

S&Box

### What can't you do?

I'm unable to easily differentiate between multiple instances of the same component on one game object.

For example: I have two Sound Point components on a GameObject. One plays Sound A and the other plays Sound B. The issue is that there is no easy way to tell which one is which.

### How would you like it to work?

The way I want it to work is that every component has a little tag icon next to the enable state check box. You click on it, and a list pops up that shows you all the tags on that component and lets you push or remove to your heart's content. This is how the JSON would look:

```json
{
  "__type": "SoundPointComponent",
  "__name": "wee",
  ...
  "Volume": 1
}
```

```json
{
  "__type": "SoundPointComponent",
  "__name": "ouch",
  ...
  "Volume": 1
}
```

When I need to play a "wee" sound effect, I can run `Components.GetByName<SoundPoint>("wee")?.StartSound()` and rest easy knowing it's my fault it played the wrong sound.

### What have you tried?

A simple workaround would be to just add a `Name` property to every component that I fully intend on having multiple of in a given object. A slightly more sophisticated approach would be to create the child class `StackableComponent` that has a `Name` property built-in. I can then run `Components.GetAll<T>( (t) => { return t.Name.Equals("somethingorother"); } )`. The issue comes when you wish to "stack" engine components like Cameras or sound emitters, which obviously don't natively support this.

Another one would be to split the object into multiple, each having one instance of the component you were planning on stacking, thus avoiding the concept of onymous components entirely. This is feasible, it just seems unnecessary to me and possibly even bad for networking since now all these components have 3D transforms attached to them that also need to be synced across the network for no good reason.

### Additional context

I have no idea the performance implications of a feature like this. I can imagine adding a new string property to every instanced component will impact memory usage to some extent, so I'm not really expecting this to go anywhere.

**Comment by garrynewman** [comment]
This seems like a solution looking for a problem. Just make a child GameObject, then you can have names, tags and a different location.
