### ISSUE TITLE
Actiongraph failing to resolve method

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#4869]
### Describe the bug

When using action graph and actively developing my project (i.e hotreloads, entering/exiting game mode), one of the nodes ends up failing to resolve
![image](https://github.com/Facepunch/sbox-issues/assets/32153021/55d0319b-84a1-407f-9f1a-f8bd329f8caf)

In my case, I keep the action graph property inside of a list of structs
```csharp
public struct Interaction
{
	/// <summary>
	/// The keybind used to trigger this interaction
	/// </summary>
	[Property]
	[InputAction]
	public string Keybind { get; set; }

	/// <summary>
	/// The UI description displayed when interacting
	/// </summary>
	[Property]
	public string Description { get; set; }

	/// <summary>
	/// The action that is performed when interacted with
	/// </summary>
	[Property]
	public InteractionEvent Action { get; set; }
	public delegate void InteractionEvent( Player interactor, GameObject obj );

	/// <summary>
	/// Whether or not the interaction is able to be performed
	/// </summary>
	[Property]
	public Func<bool> Disabled { get; set; }

	/// <summary>
	/// Whether or not the interaction is able to be performed
	/// </summary>
	[Property]
	public Func<string> DynamicText { get; set; }

	/// <summary>
	/// The text that should actually be displayed.
	/// </summary>
	public string Text => DynamicText?.Invoke() ?? Description;
}

public class Interactions : Component
{
	[Property]
	public List<Interaction> ObjectInteractions { get; set; }

	protected override void DrawGizmos()
	{
		
	}
}
```

1. The node does 100% exist
2. Restarting the game fixes it
3. It looks like the prefab file contains the relevant data

### To Reproduce

I don't have an exact repo, this seems to be some weird behaviour going on with prefab saving.

### Expected behavior

The node should resolve and the function call should work without any issues.

**Comment by Metapyziks** [comment]
Could you send me the raw JSON of a prefab file that contains a graph that breaks like this? Thanks!

**Comment by matekdev** [comment]
Sent repo and prefab file over discord, feel free to contact me for any other questions, thanks!!

**Comment by Metapyziks** [comment]
Got a fix building now, thanks for your help!

The problem would happen if two types have the same name, even if they're in different namespaces. Now it'll serialize type references as "AssemblyName/Namespace.TypeName", and if it finds an old-style type reference it'll use the one with the shortest full name.

In your case it'll now prefer ProjectName.Inventory over ProjectName.UI.Inventory, so your existing Action Graphs should fix themselves.

**Comment by matekdev** [comment]
Thanks a bunch!!
