### ISSUE TITLE
Punch command to Nav Mesh Agent

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4870]
### For?

S&Box

### What can't you do?

I’m unable to have the nav mesh agents jump. 

### How would you like it to work?

I would like this to work similar to the character controller. Where you could add a punch to have the agent jump. 

### What have you tried?

I’ve tried and there is no such command.

**Comment by garrynewman** [comment]
I suspect the right move would be to disable the navmesh agent at the point where you want this to happen. The agent should be seen as a way to keep a GameObject on a navmesh, once you want to leave the navmesh you should disable it.

This is an assumption, I haven't played with it myself.

**Comment by Nolankicks** [comment]
When disabling the nav mesh it messes up all other navmesh agents. Maybe a command for it to leave the nav mesh? I could also disable it, but it gives me ref errors.

**Comment by garrynewman** [comment]
No sorry, not disable the navmesh, disable the agent component
