### ISSUE TITLE
Clone option startEnabled = false is not working for GameObject which is PrefabScene

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4871]
### Describe the bug

When cloning GameObject which is PrefabScene with ```startEnabled = false```, it clones prefab and enables it

### To Reproduce

1. Clone Prefab (exactly prefab, not gameobject from scene) with option ```startEnabled = false```
2. resulting gameobject will be enabled

### Expected behavior

Calling Clone method on prefab with ```startEnabled = false``` doesn't enable cloned gameobject

### Additional context

I think it enables it in ```GameObject.Deserialize``` method

**Comment by garrynewman** [comment]
This should be fixed now

**Comment by garrynewman** [comment]
Will investigate
