### ISSUE TITLE
Add support for font-smooth, disabling anti-aliasing on text

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#4873]
### For?

S&Box

### What can't you do?

Currently there is no way to disable font anti-aliasing and it can look really bad on pixelated fonts.

### How would you like it to work?

Just the way it works on browser:
https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth

### What have you tried?

-

**Comment by xezno** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/9823061b-507d-4c2f-9e48-11ed5b3a2fb8)

Added this, works the same as css (`font-smooth = auto | never | always`). Let me know if you've got any problems with it.

**Comment by Xenthio** [comment]
We're so back

**Comment by Xenthio** [comment]
relevant original issue: #2291
close that too when this one is close.

**Comment by ceitine** [comment]
looks perfect! thank you<3

**Comment by matekdev** [comment]
Thank you Alex !!
