### ISSUE TITLE
Border image linear gradient is fucked

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#4874]
### Describe the bug

Seems like one of the ways to do a gradient on a border in css is via `border-image` (https://stackoverflow.com/a/6441510). Right now, the following results in...

```
border-image: linear-gradient(#f6b73c, #4d9f0c);
```
![image](https://github.com/Facepunch/sbox-issues/assets/32153021/60364479-8eb6-40ed-9c72-486cc95ca29c)

### To Reproduce

1. Use border image and view the result `border-image: linear-gradient(#f6b73c, #4d9f0c);`

### Expected behavior

It should produce a nice linear gradient.

**Comment by xezno** [comment]
Fixed this now, we weren't properly allowing for border images to be stretched
