### ISSUE TITLE
Introduce Content Project replacement.

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#4875]
### For?

S&Box, Hammer

### What can't you do?

I'm unable to centralize a collection of assets for general purpose content creation like maps and reference it in any of my game projects to use the assets from the editor. I am also unable to develop maps alongside a game in the same project without automatically uploading them alongside the game.

### How would you like it to work?

We already had this before, it was called content projects. I'd imagine we should just be able to add an "external" project as an additional reference to any existing game project.

In my specific case: one project would host an asset collection, the other the content (maps) specifically developed for the game (which get uploaded to asset.party) and then the game has all the content needed for its own asset.party upload.

### What have you tried?

Project settings has a Packages tab that seems to reference remote asset party packages, but that doesn't seem properly tested and also not viable for my case.
Simply moving/copying all the assets or uploading them to asset party is not an option.

**Comment by garrynewman** [comment]
No plans to do this in the near future. We have switched to a single project system to simplify things.

I would encourage moving everything to your project folder.
