### ISSUE TITLE
Terrain bounding box seems to be wrong, terrain can be selected by clicking on empty space

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4876]
### Describe the bug

Pretty sure this was not an issue yesterday, but the Terrain seems to be fucked a bit, to me it seems like the bounding box is wrong. Clicking an empty space in the scene can sometimes select the terrain, too.

### To Reproduce

1. Have terrain in your scene
2. Click around

### Expected behavior

Only select terrain if terrain is clicked

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/5f4252b8-65f1-49a4-878d-e640423d041e

https://github.com/Facepunch/sbox-issues/assets/5991682/e1690089-80d5-49d3-b279-0e40135a10a8

**Comment by aylaylay** [comment]
Repro project?

**Comment by aylaylay** [comment]
Looks like it's already been fixed
