### ISSUE TITLE
Improved support for multiple PhysicsWorlds

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4877]
### For?

S&Box

### What can't you do?

I am unable to create groups of physics objects that should simulate in their individual physics worlds, ignoring all other objects in different physics worlds, so that each group is completely isolated from interacting with one another, even when occupying the same space.

From my experimenting, we can only create a new PhysicsWorld, but not much after that.

### How would you like it to work?

I would like it to work by being able to create individual PhysicsWorlds, and then be able to create new physics objects (either static or rigidbodies) in those worlds, and the ability to change the target world of a physics body so that its possible to move them between worlds.

If I am understanding the existing code correctly, this is already handled in-engine, but every physics body is automatically assigned to the default Physics World.

### What have you tried?

Tried creating a new PhysicsWorld, then adding/cloning some shapes in it, having Physics Debug enabled to see if something is happening, but nothing happened.

**Comment by garrynewman** [comment]
I don't see any reason to add this extra layer of complcation

**Comment by Gmod4phun** [comment]
Looks like I managed to utilize the tag system for this after all. Good enough I guess.
