### ISSUE TITLE
The "Refract Background" option in the Particle Editor is broken.

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#488]
**Describe the bug**

Trying to use the "Refract Background" option in the Particle Editor will not refract the background correctly

**To Reproduce**

Create a "Render sprites" and use a normal map as it's texture then check "Refract Background"
![image](https://user-images.githubusercontent.com/17112771/126731467-8518ab1c-dc55-4c8a-8934-354f21615bba.png)

**Expected behavior**

It should look like this.
![steamtours_jLqx0XoJS0](https://user-images.githubusercontent.com/17112771/126731159-45a57b84-5bb5-40fe-93c3-d94f85856a3c.png)

Instead it will render one single color that is behind the particle.
![image](https://user-images.githubusercontent.com/17112771/126731665-05494cca-9e34-4996-b762-2b3f8e5e0069.png)
![image](https://user-images.githubusercontent.com/17112771/126731709-f536e66a-cacd-454b-9c64-0026d9f904be.png)

**Additional context**

This option is also broken in Half-Life Alyx.

**Comment by justynboi** [comment]
A example particle that uses refraction. 

[refractionbug.zip](https://github.com/Facepunch/sbox-issues/files/7154103/refractionbug.zip)

**Comment by bakscratch** [comment]
Still an issue, would be wonderful to have this working for us.

**Comment by GunnarKafel** [comment]
Bump

**Comment by ogniK5377** [comment]
Should be fixed in the next update 👍
