### ISSUE TITLE
Opening Material Browser in Material Editor crashes both Material Editor and S&Box

### ISSUE THREAD

**Issue by ElmarTalibzade** [Facepunch/sbox-issues#4881]
### Describe the bug

When I try to open a material using the Material Browser, it crashes both the Material Editor and S&Box.

### To Reproduce

1. Open S&Box
2. Open Material Editor
3. Open Material Browser
4. Observe crash

### Expected behavior

Shouldn't crash

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/14337344/Log.log)

Video of the crash

https://github.com/Facepunch/sbox-issues/assets/8478519/05e960f8-2a1d-4d64-82a6-c390b4155779

### Additional context

I had no problems doing that before, and successfully managed to create a material. After that, I can no longer use Material Editor without crashing everything.

I can avoid the crash by using the file browser, but this is unavoidable when I try importing material in the Model Editor, as it opens the same Material Browser, which causes a crash.

I reinstalled s&box and used blank project. No dice.

**Comment by handsomematt** [comment]
This is DX11 specific
