### ISSUE TITLE
Texture.Create with ImageFormat.Default crashes

### ISSUE THREAD

**Issue by kodi022** [Facepunch/sbox-issues#4882]
### Describe the bug

`Texture.Create` with `ImageFormat.Default` crashes me

        Log.Info("before");
        var tx = Texture.Create(128, 128, ImageFormat.Default).Finish();
        Log.Info("after");

It does not crash using `ImageFormat.RGBA8888`

### To Reproduce

try `var tx = Texture.Create(128, 128, ImageFormat.Default).Finish();`

### Expected behavior

default should be one of the safest options in the format enum, its expected that default should function

### Media/Files
ran 1s after starting my game
![notepad++_VvqjXkrA1y](https://github.com/Facepunch/sbox-issues/assets/29390269/231f865d-6864-4cf1-bf04-543b12c29bbb)

### Additional context

Win 11, ryzen 5 2600X, RX 6950 XT

**Comment by aylaylay** [comment]
Default now uses RGBA8888
