### ISSUE TITLE
Saving prefabs does not replicate changes to other scenes

### ISSUE THREAD

**Issue by rlenhub** [Facepunch/sbox-issues#4885]
### Describe the bug

When editing a prefab, sometimes I want to just tweak some values on a component without adding or removing objects. The editor seems to be a bit too conservative on when to replicate prefab changes to other scenes, resulting in the prefab remaining in it's outdated state.

The prefab updates as soon as I create a new GameObject. Any changes in the prefab's hierarchy trigger a refresh. Just not component values.

The prefab itself is properly saved to disk every time. The instances are the issue.

### To Reproduce

1. Create a prefab with a component
2. Place the prefab in a scene
3. Modify properties on the component
4. Check back on the scene and experience pain (in editor and play mode)

### Expected behavior

If a property is edited by the developer on a prefab, that change should replicate to all instances of the prefab in all scenes, no matter how small the change.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/33167901/5da0b704-80ac-4b82-8e73-04da17db9c2a

### Additional context

S&Box is stored on my C: drive.

**Comment by Metapyziks** [comment]
Might have been me that broke this, I'll have a look.

**Comment by yuberee** [comment]
I can confirm it happens to all prefabs.
Manually recompiling the prefab or reloading the scene doesn't work, it requires a full project restart or replacing the prefab.

**Comment by Metapyziks** [comment]
A fix is building now, thanks for reporting!

**Comment by yuberee** [comment]
I can confirm that it works as expected on my side now!
