### ISSUE TITLE
Time.Now always returns the same number

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4886]
### Describe the bug

Time.Now seems to always return the same number after launching the scene.

### To Reproduce

1. Run scene, log Time.Now in an update call.
2. Prints the same number every time

### Expected behavior

Time.Now should be updating.

**Comment by garrynewman** [comment]
![Image](https://github.com/Facepunch/sbox-issues/assets/928843/e90121cf-2a02-4378-969a-99bc764be697)


```
public sealed class PrintTime : Component
{
	protected override void OnUpdate()
	{
		Log.Info( Time.Now );
	}
}
```

**Comment by Fortune117** [comment]
Ok, I should've double checked. In my case Time.Now is being called in `CameraComponent.ISceneCameraSetup.SetupCamera`

It actually does seem to be increasing in the editor, but it freezes at whatever the last value was when I launch the game.

```CS
	public void SetupCamera( CameraComponent camera, SceneCamera sceneCamera )
	{
		Log.Info( Time.Now );
		sceneCamera.Position += GetViewBobOffset();
	}
```

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/e8c2cb35-1f67-479e-baed-7e9177137c29)
