### ISSUE TITLE
Some lights only show at a certain distance away

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4887]
### Describe the bug

This could be opium specific, but many lights just disappear when you get close enough.

### To Reproduce

- Launch Opium
- Walk in front of bathroom
- light at entrance turns on

### Expected behavior

Lights should stay on when visible.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/94070205/3c77114a-b550-4d79-97ff-3200cc3a3b4f

### Additional context

this is most likely just an issue with how opium is set up, but I wanted to make an issue just in case.

**Comment by handsomematt** [comment]
This is the projects own light culler turning lights on/off with triggers
