### ISSUE TITLE
Prefab.Clone lerps from 0,0,0 to spawned location

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4891]
### Describe the bug

As of recently, when spawning a prefab at a certain location, it quickly lerps there and then resumes normal behavior. This only happens if you're updating the Transform.Position in FixedUpdate however.

The following causes the behavior described above:

``` 
using Sandbox;
public sealed class PosTest : Component
{
	protected override void OnFixedUpdate()
	{
		base.OnFixedUpdate();
                Transform.Position = Transform.Position + Vector3.Right * Time.Delta * 10.0f;
        }
}
```

### To Reproduce

1. Make a new component, paste the code from above.
2. Turn it into a prefab.
3. Make a nother empty game object with a basic new script called Spawner.cs or whatever.
4. In the Spawner.cs expose a GameObject prefab property, set it to the previously created prefab.
5. In the Spawner.cs spawn the prefab at random locations

Notice how it lerps from 0,0,0 to the desired spawn location.

### Expected behavior

It should not lerp from 0,0,0 but just spawn at the normal transform position

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/35051017/b2c99743-3378-4426-8e98-dc02bf83a753

**Comment by garrynewman** [comment]
What's your code to spawn the prefab?

**Comment by osmanlodzero** [comment]
```
projectilePrefab.Clone( Transform.Position + Vector3.Up * 8.0f, dir);
```
gets spawned from the players position

**Comment by garrynewman** [comment]
Thanks - will investigate

**Comment by osmanlodzero** [comment]
Something I noticed just now: when I add a sphere collider component ( I do this in the OnStart ) then everything is fine. It spawns and moves correctly. I added the collider for a completely different reason but noticed it fixed this issue. Maybe it will give some clues.

**Comment by garrynewman** [comment]
What other components does your prefab have?

**Comment by osmanlodzero** [comment]
In the initial test it was just a model renderer and my own projectile component. This is the version that seems glitched.

```
{
  "RootObject": {
    "Id": "15fcfaba-d37c-4f25-9f77-d5ae7bc70a7d",
    "Name": "proj",
    "Enabled": true,
    "Components": [
      {
        "__type": "ModelRenderer",
        "BodyGroups": 18446744073709551615,
        "MaterialGroup": null,
        "MaterialOverride": null,
        "Model": "models/bullet.vmdl",
        "RenderType": "On",
        "Tint": "1,1,1,1"
      },
      {
        "__type": "Projectile"
      }
    ],
    "Children": []
  },
  "ShowInMenu": false,
  "MenuPath": null,
  "MenuIcon": null,
  "__references": []
}
```

The bullet.vmdl has a single RenderPrimitiveSphere in it.

**Comment by osmanlodzero** [comment]
Ok seems it's also happening to another object, the mobs in my project. This also used to work fine before. 

When a monster falls in the pit, I create a clone it and spawn it at the top of the screen and destroy the current one. You can see the same lerping issue here.

https://github.com/Facepunch/sbox-issues/assets/35051017/8d3c648f-d3da-4d4c-a51b-e1e9d6b74b73

The code
```
				var newMonster = GameObject.Clone( new Vector3( 0.0f, 0.0f, 300.0f ) ).Components.Get<Monster>();
				newMonster.IsAngry = true;
				newMonster.IsLarge = IsLarge;
				GameObject.Destroy();
```

**Comment by garrynewman** [comment]
It's super odd because iirc the only thing that even lerps is rigidbody, or networking. If your gameobject doesn't do either of those I can't really explain the lerp.

**Comment by osmanlodzero** [comment]
I will try and upload a quick repro project when I get home. I saw a few other users mention issues with it as well.

**Comment by garrynewman** [comment]
I just realised why this might happen

**Comment by garrynewman** [comment]
Alright I will be shocked to my core if this isn't fixed now

**Comment by osmanlodzero** [comment]
Yep works, thanks!
