### ISSUE TITLE
Scenes can't be saved if scene file exists or existed

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4892]
### Describe the bug

Scenes can't be saved if scene file exists or existed

### To Reproduce

1. open scene
2. make changes
3. click ctrl+s or save it using menu
4. close scene
5. open scene
6. no changes were saved

scenes can be saved to new files
BUT can't be saved to files that were in project and were removed (until editor restart)
1. remove scene file
2. save scene to same location and same file name that you just removed
6. scene does't save (file doesn't appear)

### Expected behavior

scenes can be saved

**Comment by garrynewman** [comment]
I just had this too. The problem seems to be that the scene isn't being compiled when it's saved. 

Anyone got any ideas what might have changed @handsomematt @DevulTj

**Comment by GavrilovNI** [comment]
doesn't work for me

actually if i save scene and reopen it - it doesn't work
if i save scene and reopen editor - it works

**Comment by handsomematt** [comment]
Wasn't what I thought I'd done, I'll have a proper look now

**Comment by handsomematt** [comment]
I rolled back a bunch, I'm pretty sure this never worked. But now it does.

**Comment by GavrilovNI** [comment]
saving works, but it looks like i still can't save scene if that file was previously removed
[Log.884.log](https://github.com/Facepunch/sbox-issues/files/14348959/Log.884.log)

https://github.com/Facepunch/sbox-issues/assets/9992453/1a5c0cb1-aead-4c29-b5df-dceb6e602721
