### ISSUE TITLE
Add .sln to default gitignore

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#4895]
### Describe the bug

The default gitignore is great, but should also include *.sln or an equivalent. The generated Solution file contains user paths and will therefore do nothing good on git besides mess up the commit history

### To Reproduce

1. Make a new project and add it as a new repository to git
2. Note the initial commit will include the sln because it's not on gitignore, it also contains user paths, so every commit from another person will change it

### Expected behavior

default gitignore should contain .sln or the generated solution file should not contain user paths.

**Comment by bakscratch** [comment]
Added the .sln to the template
