### ISSUE TITLE
Physics objects collide even when they should not

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4896]
### Describe the bug

Under some specific condition which I am not sure of, physics objects that should not collide with each other (as specified in collision rules) do infact collide.

In the video example I am creating new props with a tag that makes them ignore collisions with the right plane, but even despite that, they sometimes collide. It's just my guess but it seems to happen usually when the prop's collider was touching the plane's collider at the moment the prop was being spawned.

### To Reproduce

1. Add a rule to the project's collision matrix that says 'Tag A' should not collide with 'Tag B'
2. Make a surface (a plane) and give it 'Tag A'
3. Spawn a rigidbody with 'Tag B' on the plane
4. Notice that the rigidbody can sometimes collide with it, despite that it should not

### Expected behavior

The two should never collide.

### Media/Files
Disclaimer: The right plane is invisible because its in the camera's ignore render tags.

https://github.com/Facepunch/sbox-issues/assets/5991682/aada87f1-b456-43cc-9024-e57402c67fdc

In case the video is too blurry, here is the collision matrix:
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/1dfd5814-8317-435b-a55c-a2c9594bef7b)

And here are the two plane objects:
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/5aa72573-f44e-4555-9fea-b54608e45c72)

And the code used to spawn the props:
```cs
	public static async Task<GameObject> SpawnProp( Vector3 pos, Rotation rot, string ident )
	{
		var prop_object = new GameObject();
		prop_object.Name = "Prop";
		prop_object.Transform.Position = pos;
		prop_object.Transform.Rotation = rot;

		var package = await Package.FetchAsync( ident, false );
		await package.MountAsync();
		var model = Model.Load( package.GetMeta( "PrimaryAsset", "" ) );

		var prop = prop_object.Components.Create<Prop>();
		prop.Model = model;

		prop.Tags.Add( "worlda" );

		return prop_object;
	}
```

**Comment by Gmod4phun** [comment]
Adding a small repro project

[collision-problem-repro.zip](https://github.com/Facepunch/sbox-issues/files/14349739/collision-problem-repro.zip)

**Comment by garrynewman** [comment]
Does this also happen when the prop is not spawned async?

**Comment by Gmod4phun** [comment]
Yeah, seems to happen even when its not async.

**Comment by garrynewman** [comment]
This should be fixed now, please let me know

**Comment by Gmod4phun** [comment]
Yeah seems to be fixed now, thanks :)
