### ISSUE TITLE
NavMesh.GetRandomPoint's output is affected by the scale of the ground's collider

### ISSUE THREAD

**Issue by the-remeko** [Facepunch/sbox-issues#4897]
### Describe the bug

The randomly chosen point can be much further away than the supplied radius depending on the scale of the box collider.

### To Reproduce

I attached a repro project that displays the generated point and the distance on the screen, but here's what it does:

Using the default minimal scene when creating a new project, enable the NavMesh and use this code to generate a random point:
`Scene.NavMesh.GetRandomPoint( Vector3.Zero, 100f );`

Using the Scene editor, scale up the default Plane or its box collider. The output of GetRandomPoint will on average be even further away from the supplied point.

### Expected behavior

The randomly chosen point should be within the supplied radius regardless of the scale of the colliders involved.

### Media/Files

[navmeshtesting.zip](https://github.com/Facepunch/sbox-issues/files/14350049/navmeshtesting.zip)

**Comment by garrynewman** [comment]
Yep, the radius is the radius to find the navmesh polygon - not a radius to restrict the point to. I can appreciate this is confusing, so will update it.
