### ISSUE TITLE
"Reset to Default" not working on some base types

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#4902]
### Describe the bug

The default Camera component shows this well. Most of its properties either dont reset at all or dont reset to the default Property value.

### To Reproduce

1. Go to a new camera component
2. Change some values, try to reset them to default via "Reset to Default"

- Clear Flags will just be cleared to 0, instead of the default flags
- Color does nothing
- bool Main Camera does nothing
- float slider and entry fov, znear, zfar etc do nothing
- TagList resets fine

### Expected behavior

It would probably be best if Reset To Default worked for most base types out of the box. It should reset to the Property's default value or the types default value if none is given.

### Media/Files

![sbox-dev_7cPM3azPVr](https://github.com/Facepunch/sbox-issues/assets/12602100/3091c65f-df7e-4901-9bb4-9f8facb17e50)

**Comment by DevulTj** [comment]
This should work properly now, let me know if you encounter any more issues
