### ISSUE TITLE
Scene "LastSaved" property updates with no actual changes being saved.

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#4905]
### Describe the bug

Just "saving" a scene with no unsaved changes will update the "LastSaved" property of a scene and change the file.

### To Reproduce

1. Go to any scene, preferrably one tracked by git
2. Save it without changes
3. Note the file change 

### Expected behavior

The file should only update when there's any actual changes to save, right now it just adds extra noise to git changes.

### Media/Files

![GitHubDesktop_HHpFccVOxK](https://github.com/Facepunch/sbox-issues/assets/12602100/ffa1218d-5798-4fa1-8e85-d84c96f64c02)

**Comment by garrynewman** [comment]
I'm not sure this is a bug. You're saving, this is the last saved time.

**Comment by DoctorGurke** [comment]
Not a point of discussion at all? Shame, seems like overly aggressive file changes to me and have never seen another program do this to my git staging

**Comment by garrynewman** [comment]
Maybe bring it up in 6 months, doesn't seem worth anyone's runtime right now
