### ISSUE TITLE
git revert doesn't update scenes in the editor.

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#4906]
### Describe the bug

Reverting file changes via git revert doesn't affect the editor until you restart it

### To Reproduce

1. Open a scene on a git project
2. make some changes
3. revert them via git revert
4. Note the scene in-editor remains unchanged until a full editor restart

### Expected behavior

The editor should properly update based on the external file updates. Oddly enough it seems to realize there's unsaved changes after the revert, just doesn't update to the new state of the scene resource

**Comment by DevulTj** [comment]
This works for me currently, can you try again - and if this continues, supply me with the repo you're using for a repro?

**Comment by DevulTj** [comment]
I tested this, and it's working - I'm gonna close this issue - If it happens again, feel free to open the issue with the project you're using
