### ISSUE TITLE
[Shader Graph] Allow Custom Texture Name Extensions

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#4907]
### For?

S&Box

### What can't you do?

I can't set custom texture name extensions (i.e. _color, _mask, _normal) in the Texture 2D node in the shader graph.

### How would you like it to work?

Add a "Custom" option in the Extension dropdown that lets me type in a custom extension.

### What have you tried?

Editing the .shader file manually, which works but it will be overwritten if I recompile in shadergraph again.

**Comment by aylaylay** [comment]
Huh, this already exists?

**Comment by Jammie3d** [comment]
Does it? I want to be able to input my own text in this dropdown list, so that I can have things like "_ORM" or "_RGB".

https://github.com/Facepunch/sbox-issues/assets/60801006/f5fa40d4-8f28-42ae-b3e0-3da873a2245e

**Comment by aylaylay** [comment]
You can now set a custom file ext, it will hide the built in file ext property if you provide your own

**Comment by Jammie3d** [comment]
Perfect, thanks!
