### ISSUE TITLE
Add `FileSize` to `Sandbox.Package`

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4908]
### For?

S&Box

### What can't you do?

Estimate how long it would take to download a package based on its file size.

### How would you like it to work?

Add `FileSize` to `Sandbox.Package` so that a 500MB package would have a value of `500f`.

### What have you tried?

Downloading maps larger than I would have liked to on accident.

### Additional context

Would be a lot easier to estimate the map download time if you could see the file size in MB.
![image](https://github.com/Facepunch/sbox-issues/assets/100040020/344bbd3a-be46-4a4b-b89f-faf1c62abcc6)

**Comment by kurozael** [comment]
Added Package.FileSize (MB) which is calculated for packages from Asset Party.
