### ISSUE TITLE
`Camera.Pos/.Rot` is not synced on server

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#491]
**Describe the bug**
As it seems, `Camera.Pos` and `Camera.Rot` isn't synced on server, even if the camera was created on the server.
This is needed to check interactions of a player on the server. E.g. if the player is in FreeSpectateCamera, looking at a specific object and presses E (InputButton.Use), you can't check on the server whether the player is really looking at the object (important for anti-cheat as well as if you want to run certain logics on the server).

**To Reproduce**
Set a player's camera to a camera that is not synced with `Player.EyeRot` or `Player.EyePos` and print on the server the Position of the player's camera. It will always print `(0, 0, 0)`.

**Expected behavior**
Updated `Camera.Pos` and `Camera.Rot`

**Comment by handsomematt** [comment]
This really isn't a bug, a camera is a clientside concept and not an entity. If you want a synced position + rotation use an entity / pawn.
