### ISSUE TITLE
Triggers don't work right with map instances.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4910]
### Describe the bug

I am moving a Sphere Collider ( IsTrigger=true) with a Collider.ITriggerListener hooked throgh my scene. It reacts fine with other colliders that I've placed in the scene manually, but does not respond to map instance collision at all. Unsure if this intended/bug or I'm missing something.

### To Reproduce

1. Load a map instance ( we want to collide against this )
2. Create a new game object, add a sphere collider ( we also want to collide against this ).
3. Create a new game object, add a sphere collider, enable IsTrigger ( we will move this ).
4. Add a new script to the moving sphere, implement the Collider.ITriggerListener
5. Notice how the OnTriggerEnter/Exit functions are called when this moving sphere overlaps the scene-placed collider and does not respond with the map instance at all.

### Expected behavior

I expect to get notified when my moving trigger enters the walls of a map instance.

**Comment by aylaylay** [comment]
We specifically filter triggers against the world, maps have the "world" tag, maybe we should have an option to disable this

**Comment by aylaylay** [comment]
Okay, maps don't add world tags to collision by default, so triggers can now detect maps. In the situation where you want the old behavior, you can just add a world tag to the map instance.

**Comment by osmanlodzero** [comment]
It seems that it's back to adding the 'world' tag. I was messing with trigger and it was ignoring the map again.
