### ISSUE TITLE
Allow dragging and dropping of scripts from the asset browser

### ISSUE THREAD

**Issue by Jake-Man-124** [Facepunch/sbox-issues#4913]
### For?

S&Box

### What can't you do?

I'm unable to drag scripts from the asset browser and it's infuriating.

### How would you like it to work?

Be able to see and drag scripts from the asset browser onto any gameobject as a component. Especially razor scripts as they seem to disappear into thin air if you accidently delete them.

### What have you tried?

Nothing really helps aside from remaking the script or searching for it under uncategorized hoping it's there. Sometimes it even saves to a different project for some reason?

### Additional context

It's present in Unity and would just be a nice quality of life thing to add.

**Comment by garrynewman** [comment]
- [ ] Show scripts in asset browser
- [ ] Drag Drop script onto gameobject inspector creates component
- [ ] Drag drop script to scene creates gameobject with component (?)

**Comment by fantasticaneer** [comment]
My vote would be for all three, honestly, but mostly the first two. The third sounds nice but I feel like in most cases you'd just make a prefab of an empty game object with the script.
