### ISSUE TITLE
Asset dependencies sometimes aren't collected

### ISSUE THREAD

**Issue by KaesarZZ** [Facepunch/sbox-issues#4914]
### Describe the bug

I'm working on a functional replacement to citizen and I would like people to be able to use playermodels directly from asset.party in a future "Sandbox" game or whatever and use the inspector without the need to use code.

Currently, this is what happens if you try to do it (Tested in Talker):

https://i.gyazo.com/94150afd36cf2c3cf02f857c8cc0abac.mp4

It seems that you need the .vmdl decompiled to work correctly and that sucks:

https://i.gyazo.com/4a5a04ad8e0b33d428ba6d16990f20cc.mp4

### To Reproduce

Search for hazmatsuit in cloud and try to replace the model.

### Expected behavior

It would be nice to have it working properly or at least keep it in mind when you are programming "Sandbox" someday.

**Comment by garrynewman** [comment]
I don't totally understand what's happening here. Is it messing up because another model exists with the same name, or are all cloud models like this?

**Comment by KaesarZZ** [comment]
Ok my bad but this is weird, looks like a problem with the haztmatsuit model itself, for some reason doesn't use dependencies anymore.

https://github.com/Facepunch/sbox-issues/assets/40291120/f71d31ab-8de8-4be3-9277-8ce52874f28e

https://asset.party/sboxmp/hazmatsuit/version

So he has stopped uploading textures/animgraph for some reason. I have no idea what's causing it, was working before. My other playermodels are working just fine. 

Any idea?

**Comment by garrynewman** [comment]
That is odd, so the issue is that when publishing a model, such as this, it no longer includes its dependencies (like textures and animgraph. I wonder if this could be something to do with the startup time improvements we've been making @handsomematt - looks like it stopped working properly on the 17th or 18th.

**Comment by handsomematt** [comment]
Dependencies are working fine for me.

![image](https://github.com/Facepunch/sbox-issues/assets/1388267/2e1eeadc-418e-42bc-8222-6db4690f7cce)
![image](https://github.com/Facepunch/sbox-issues/assets/1388267/85403876-03be-4e66-a9b0-ed26e5130d94)

There was equally a time on 2024-01-27 that there were no dependencies uploaded for this model.

Other models are uploading their dependencies fine too: https://asset.party/stir/aps/version/47648

I'd have to see the source files for hazmatsuit, but I suspect they're probably trying to upload something that was sprawling across content projects

**Comment by KaesarZZ** [comment]
Alright I found the bug lol, I think it's filters fault (?). I usually use the model/animgraph filter, if I activate the materials and I recompile the model I get the dependencies again.

https://i.gyazo.com/379396f4405d54667a78e25bbf46f64a.mp4

If you open me dm in discord I can give a you the source files if needed.

**Comment by KaesarZZ** [comment]
It's not a filter fault sorry checked again, I just need to recompile the model every time start the project for some motive. I have no idea what's happening.

**Comment by handsomematt** [comment]
Didn't mean to close, but I think this should be fixed as it seems to be the same problem as #5013 - let me know if it's not though
