### ISSUE TITLE
Cannot assign value to [Sync]ed Guid anymore

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4916]
### Describe the bug

I have the following:
```cs
[Broadcast]
public void SetCurrentUser( Guid user )
{
	Log.Info( user );
	CurrentUser = user;
	Log.Info( CurrentUser );
}
```
which logs as the following:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/3853ded5-422a-4ddf-a7d2-080dee7fd350)

This has only begun as of the most recent networking changes that were merged in.

### To Reproduce

See above

### Expected behavior

You should be able to assign this. I tried only assigning `if(!IsProxy)` but that yields the same result.

**Comment by kurozael** [comment]
It should be the case that only the owner (or host if using HostSync) can actually set the value of a Sync property.

**Comment by CarsonKompon** [comment]
> It should be the case that only the owner (or host if using HostSync) can actually set the value of a Sync property. This is intended behaviour because otherwise the property might get out of sync.

Wouldn't my IsProxy check get around that then? Or is "HostSync" a new attribute I have to use when a gameobject has no ownership?

**Comment by kurozael** [comment]
Hm no if the networked object is unowned (no owner) and you're the host, then you should have authority to set it. Is the networked object a child of another networked object by any chance?

**Comment by CarsonKompon** [comment]
> Is the networked object a child of another networked object by any chance?

No, the networked object is just instantiated in the scene root

**Comment by CarsonKompon** [comment]
> @CarsonKompon Can you verify that the object has no owner set (log GameObject.Network.OwnerId) and, who is calling the RPC? Is it the host or another client?

Can confirm there is no owner set, OwnerId is returning Guid.Empty and when I NetworkSpawn the object i do `NetworkSpawn(null)`. The RPC is called on the host in this instance but it happens if I call on host or client

**Comment by kurozael** [comment]
If you could send me a repro project it might help - because I'm trying to make a similar setup as you but it's working for me.

```csharp
public sealed class TestRpcComponent : Component
{
	[Sync] public Guid CurrentUser { get; set; }
	
	[Broadcast]
	public void SetCurrentUser( Guid guid )
	{
		Log.Info( "Try setting to: " + guid );
		Log.Info( "Our owner is: " + Network.OwnerId );
		CurrentUser = guid;
		Log.Info( CurrentUser );
	}
}
```
```
03:39:27   GameMenu Try setting to: 9c219eb9-fa21-4e77-9eb8-c7467c19952a
 03:39:27   GameMenu Our owner is: e97179ea-f9f6-4dd9-bf27-4821d3fe6f65
 03:39:27   GameMenu [9c219eb9-fa21-4e77-9eb8-c7467c19952a](arg:0)
```

```csharp
	void INetworkListener.OnActive( Connection connection )
	{
		var player = PlayerPrefab.Clone();
		var playerSlot = FindFreeSlot();

		if ( playerSlot < 0 )
		{
			throw new( "Player joined but there's no free slots!" );
		}

		var playerComponent = player.Components.Get<Player>();
		AddPlayer( playerSlot, playerComponent );
		player.NetworkSpawn();

		if ( connection.IsHost )
		{
			var obj2 = new GameObject();
			obj2.Components.Create<TestRpcComponent>();
			obj2.NetworkSpawn( null );
		}
	}
```

```csharp
		if ( Input.Released( "Jump" ) )
		{
			var comp = GameManager.ActiveScene.GetAllComponents<TestRpcComponent>().FirstOrDefault();
			comp.SetCurrentUser( Connection.Local.Id );
		}
```

**Comment by CarsonKompon** [comment]
I'll try making a repro and I'll get back to you :)

**Comment by CarsonKompon** [comment]
I have been unable to reproduce the issue in another project. I made a repro project with the identical scripts but it is working...
Here is that for the sake of posterity:
[networking_guid_repro.zip](https://github.com/Facepunch/sbox-issues/files/14362746/networking_guid_repro.zip)

I can share the project where it's been happening with you privately if that's okay?

**Comment by kurozael** [comment]
> I have been unable to reproduce the issue in another project. I made a repro project with the identical scripts but it is working... Here is that for the sake of posterity: [networking_guid_repro.zip](https://github.com/Facepunch/sbox-issues/files/14362746/networking_guid_repro.zip)
> 
> I can share the project where it's been happening with you privately if that's okay?

Sure Carson feel free to DM me on Discord or something. Or you can e-mail it to me - [find my e-mail here](https://github.com/kurozael/) 👍

**Comment by CarsonKompon** [comment]
Awesome, thank you so much. I've sent you an email :)

**Comment by CarsonKompon** [comment]
@kurozael After some further investigation I have found the issue. It lies within inheritence. Here's a proper repro: 
[networking_guid_repro.zip](https://github.com/Facepunch/sbox-issues/files/14384659/networking_guid_repro.zip)

You'll see that `BonfireInteractable` inherits `CraftingStation`, and pressing space in-game is not allowing you to set the `CurrentUser` Guid.
However, if you go into the thing.prefab file and change the BonfireInteractable component for a CraftingStation component, you'll see it works just fine.

Hope this helps :)

**Comment by kurozael** [comment]
Should be good now... thanks for the repro <3
