### ISSUE TITLE
project start

### ISSUE THREAD

**Issue by somewhere-in-the-universe** [Facepunch/sbox-issues#4918]
### Describe the bug

always getting an error message and stall detection when trying to open a project

### To Reproduce

![изображение](https://github.com/Facepunch/sbox-issues/assets/146519784/8a550d63-da3a-468d-8045-a5bfb8ad7b48)

### Expected behavior

the s&box editor window with project must show up

[Log.log](https://github.com/Facepunch/sbox-issues/files/14364133/Log.log)

### Additional context

I`m running on windows 11 22h2

**Comment by trundlr** [comment]
Did you try checking log file

**Comment by somewhere-in-the-universe** [comment]
yes, I did

**Comment by somewhere-in-the-universe** [comment]
it says that something went wrong in Files (x86)\Steam\steamapps\common\sbox\addons\base\code\Components\Citizen\PlayerController.cs

**Comment by ceitine** [comment]
try verifying your game files, or just reinstall your whole game

**Comment by CarsonKompon** [comment]
I was going to make an issue for this. The real issue here is that your code has errors in them, but now that the engine tools load after selecting a project instead of before it doesn't properly tell you what the errors in your code are. Everything just breaks 😅

**Comment by handsomematt** [comment]
> I was going to make an issue for this. The real issue here is that your code has errors in them, but now that the engine tools load after selecting a project instead of before it doesn't properly tell you what the errors in your code are. Everything just breaks 😅

This is saying there are errors in the base game files (these are obviously old ones that would be solved by verifying game files), not that there's an error in the project. Errors in your own project still show the dialog specifying errors.

**Comment by handsomematt** [comment]
https://help.steampowered.com/faqs/view/0C48-FCBD-DA71-93EB

**Comment by somewhere-in-the-universe** [comment]
![Снимок экрана 2024-02-21 231347](https://github.com/Facepunch/sbox-issues/assets/146519784/ce6d906a-f224-4e3a-a5fc-9a837d40f5f1)


> https://help.steampowered.com/faqs/view/0C48-FCBD-DA71-93EB
