### ISSUE TITLE
Rigidbodies should be able to ignore certain tags

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4919]
### For?

S&Box

### What can't you do?

We used to have collision masks before scene, now the only way we can ignore collision tags is with a CharacterController.

I want to have a physics object that can go through players but not through other objects.

### How would you like it to work?

Similarly to the CharacterController Component where you can supply ignore tags.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/45900984-7fae-42f7-809e-558be39f2356)

### What have you tried?

There's really no other option.

**Comment by Fortune117** [comment]
We still have a collision matrix in the project settings, you should be able to add tags for players and make objects ignore it.

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/2e9b293f-4f3f-41cd-b095-b59845a911a3)

**Comment by CarsonKompon** [comment]
I didn't know that still worked. I'll test it later but I still think there's validity to having parity with something like the character controller and allowing you to simply ignore tags from scene on a per-component basis instead of on a per-tag basis.

**Comment by CarsonKompon** [comment]
Yeah it doesn't look like this is working for me. Might be because of the recent tag changes or because of my lack of understanding though 😅

**Comment by CarsonKompon** [comment]
Update: I was able to get around this by including the projectile tag in the character controller's ignore tag on the player combined with my use of the collision mask. Seems good enough so I'll close the issue :)
