### ISSUE TITLE
Adding a game project to the launcher shows the LAUNCHING feedback even though it isn't launching

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4920]
### Describe the bug

Adding a game project to the launcher shows the LAUNCHING feedback even though it isn't launching

### To Reproduce

1. Add a game project to the launcher
2. LAUNCHING LAUNCHING LAUNCHING LAUNCHING LAUNCHING 

### Expected behavior

Doesn't show launching

**Comment by DevulTj** [comment]
Should be fine on next build

**Comment by trundlr** [comment]
Looks good. Thanks, I guess.
