### ISSUE TITLE
Project settings under game setup do not save

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4923]
### Describe the bug

I wanted to change my game's launch mode to quick play, and the save popup isn't showing and it reverts back to "normal" when I close and re-open the project settings window.

### To Reproduce

- Open project settings
- Under game setup, change any settings
- Press save button, no save popup
- Close and re-open project settings, changes have been reverted.

### Expected behavior

Game setup changes should be saved.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/94070205/3beedc40-5f29-423f-8488-1933276f461f

**Comment by garrynewman** [comment]
I can't repro this, seems like it's saving for me?

**Comment by cr4yz** [comment]
I can repro this @garrynewman, got a fix coming.
