### ISSUE TITLE
Orphaned GameObjects have their world position set to their former local position

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4926]
### Describe the bug

If a GameObject's parent is set to null, its world position becomes whatever its local position previously was when it was a child of a GameObject.

### To Reproduce

1. Open the project in the attached ZIP file
2. Open minimal.scene
3. Observe that the the Sphere child of Cube has a local position of 0,0,32
4. Observe that the Sphere child of Cube has an Action Graph that will set its parent to the scene on start
5. Press F5 to play
6. Observe that once orphaned, the Sphere GameObject has a world position of 0,0,32

### Expected behavior

When an GameObject's parent is changed, its world position should not change.

### Media/Files

[repro_orphan_world_pos.zip](https://github.com/Facepunch/sbox-issues/files/14370165/repro_orphan_world_pos.zip)

**Comment by garrynewman** [comment]
- [ ] When a GameObject is parent changes from something to nothing, store its world position and restore it when changed
- [ ] Add a unit test to assert this

**Comment by Metapyziks** [comment]
Could be, I'll investigate after lunch.

**Comment by kurozael** [comment]
Is this still an issue?
