### ISSUE TITLE
Allow multiple controllers to connect to a single game (Local multiplayer)

### ISSUE THREAD

**Issue by Adazartar** [Facepunch/sbox-issues#4927]
### For?

S&Box

### What can't you do?

Currently only one controller input is detected at a time, if two controllers are connected one of them is ignored, meaning it's impossible to support local multiplayer past a keyboard + mouse player and a single controller player.

### How would you like it to work?

Be able to connect multiple controllers to a single game, track and take input/differentiate input between them all

### What have you tried?

Looked through the API to see if this was supported and tried to connect multiple controllers

**Comment by MrBrax** [comment]
I'm guessing this could be useful for accessibility too?

**Comment by garrynewman** [comment]
I suspect we could do something like this to enable this

```
using ( Input.PlayerScope( 0 ) )
{
 // player 0 inputs
}

using ( Input.PlayerScope( 1 ) )
{
 // player 0 inputs
}
```

Then further down the line, we could make it so you can assign GameObjects to players, and the scoping would happen automatically in engine before Update/FixedUpdate.

```
Input.SetController( gameObject, 1 )
```

That makes the most sense to me right now, if anyone has any better ideas let us know

**Comment by DevulTj** [comment]
Had a chat with @handsomematt about this, and he described the exact same API, so we'll go for it.
