### ISSUE TITLE
Gizmos are not showing up on DX11

### ISSUE THREAD

**Issue by Pumpblench** [Facepunch/sbox-issues#4929]
### Describe the bug

Using Shift+G hotkey is not solving the problem. It just turns off icons, as seen on the image. They are techincally there, and i can use them to move oobjects, but they're invisible

### To Reproduce

Enter any project in the editor

### Expected behavior

Gizmos should show up as expected

### Media/Files

![s box1](https://github.com/Facepunch/sbox-issues/assets/160887370/5f9ffc28-bf6f-4433-b970-c6118f13110f)
![s box](https://github.com/Facepunch/sbox-issues/assets/160887370/432a9d51-dbf7-4cee-a4bd-070395e38d1d)

**Comment by garrynewman** [comment]
Have you verified content on Steam?

Do you have any errors in your log files?

When did this start happening?

Does it happen in any other projects?

**Comment by Pumpblench** [comment]
yes, i have verified content on steam. Besides, i've even reinstalled s&box, but nothing is changing.

Yes, i have some errors in the logs - "Failed to create D3D11 pixel shader!" "Failed to on-demand compile shaderFailed to create D3D11 pixel shader!". But I don't think they can have anything to do with it.

This started immediately after I installed the update.

Yes, it happens in all of my projects.

**Comment by MrBrax** [comment]
i see that the move tool is selected, but is the state stuck? you can for some reason deselect the tool making no gizmo at all show up

**Comment by handsomematt** [comment]
Is there a reason you're running in dx11? Those errors are definitely relevant.

**Comment by Pumpblench** [comment]
yeah, i'll try to launch on vulcan, maybe that's the case
