### ISSUE TITLE
Changing GameObject parent does not update tags properly until object is re-enabled

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4931]
### Describe the bug

When changing a parent of a GameObject, the tags don't seem to update correctly. The object will show the correct tags in the inspector, but things like camera rendering or physics collisions will behave like it was before changing the parent.

Demonstration in the video, and a quick explanation of what is happening in it:
Working with a MultiWorld system, where I have World gameobjects with their own **world_n** tag (**n** is index of the world).
The player can only see and collide with objects in the same world as the player's assigned world.

Now, I spawn a new prop, set its parent to World 0, prop inherits the **world_0** tag. After a second, I change (in code) the parent of the prop to the World 1, which adjusts the prop's tag to **world_1**.

In the inspector, the parent changed, the tag seems to be updated, but unless the prop object is disabled and re-enabled again, the rendering/physics still does not know about the tag update.

The same thing happens when you change the parent by dragging the object in the inspector into a different parent object.

### To Reproduce

1. Have a GameObject with a certain tag on it
2. Have a second GameObject with a different tag on it
3. Create a new child object in the first GameObject, and add a renderer to the child object
5. Have a camera that will only render objects with the same tag as the first GameObject
6. Play the scene
7. Change child's parent (in code, or through inspector) from the first to the second object
8. See that the child's tags updated in the inspector
9. See that the camera still renders it, even when it should no longer do that
10. Disable and re-enable the child, so the tags update properly and the camera will stop rendering it, as it should

### Expected behavior

Tags (and possibly other things) should update properly after a GameObject's parent changes.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/b344075f-929a-45e7-abd1-23729dbd94d3

**Comment by garrynewman** [comment]
- [ ] When a parent changes, update all gametags recursively

**Comment by DoctorGurke** [comment]
Possibly related, ran into some issues updating collision tags between a player and a ragdolled enemy. Adding the ragdoll tag via code to the object before enabling the ModelPhysics component didn't seem to copy the tags. Setting the tag after the component is enabled updates the tags fine to all physicsbodies.

**Comment by cr4yz** [comment]
@DoctorGurke @Gmod4phun I've pushed a fix for this, please let us know if these problems are resolved after the next update.

**Comment by Gmod4phun** [comment]
Yep, seems to work nicely, thanks. I will keep this open for a bit and then close it.
