### ISSUE TITLE
Add .flac file extension support

### ISSUE THREAD

**Issue by shurahgolden** [Facepunch/sbox-issues#4932]
### For?

S&Box, Other

### What can't you do?

I'm unable to use .flac audio files with S&Box's engine.

### How would you like it to work?

Exactly the same as .wav and .mp3 files.

### What have you tried?

I have to convert all .flac files manually to .wav files, which is quite tedious.

**Comment by DoctorGurke** [comment]
Just curious cause I've never seen this format before, where are you sourcing your audio files that you only get .flac?

**Comment by shurahgolden** [comment]
I don't source them, I make them myself. Most stock audio websites use .wav, .mp3, .ogg, and/or sometimes .flac though.

**Comment by aylaylay** [comment]
I've added .flac support. If you come across one of your files not compiling properly let me know and attach the file here please.
