### ISSUE TITLE
Map Instance component should have an asset browser instead of a string entry

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4934]
### For?

S&Box

### What can't you do?

Can't browse for maps with the Map Instance component.

### How would you like it to work?

You should be able to browse for a Map in the Asset Browser. The existing Asset Browser should work fine for this.
Maybe you could switch the component to 'filepath mode' if you wanted to.

### What have you tried?

I don't know if this is still a bug, but for a long time you've had to type the entire full filepath of a local map including .vmap if you want the collisions to load properly. Cloud maps work fine with just `organization/mapname`.

**Comment by garrynewman** [comment]
- [ ] Can browse for maps on local path
- [ ] Can browse for maps from asset party
- [ ] Can manually type in map name/ident

**Comment by aylaylay** [comment]
Map now uses a resource control widget, is there any benefit to manually typing the map name?

**Comment by DoctorGurke** [comment]
With the name being switched to vmap will that break any asset party idents that were used instead? I presume that's what the manual entry is for.

**Comment by aylaylay** [comment]
Yeah it doesn't work for cloud maps, let me come up with something, I still think we wont need manual entry, we just need a control that handles picking both local and cloud maps with asset browser.

**Comment by DoctorGurke** [comment]
I remember we had a cloud+local map picker for project settings (default map?) at some point back in entity days

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/6647685c-287f-47c5-9025-c1e11ef5e15c
