### ISSUE TITLE
Issue with CharacterController

### ISSUE THREAD

**Issue by OlziYT** [Facepunch/sbox-issues#4937]
### Describe the bug

When i'm crouched with the CharacterController and i jump (CTRL stay pressed), the collision box and camera of the player does not reset her size to default, she stay to crouched size.

### To Reproduce

Stay press CTRL button and press once SPACE button

### Expected behavior

The size of the player box collider need to be reset when i stay press on CTRL and press once SPACE button

**Comment by andy013** [comment]
You can check CharacterController.IsOnGround and then uncrouch if it's false.

**Comment by cr4yz** [comment]
This is expected.  We recommend writing your own controller or modifying the default one to achieve the exact behaviour you want.
