### ISSUE TITLE
API / engine should be more opinionated about developers using player defined mouse sensitivity

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4940]
### For?

S&Box

### What can't you do?

I keep playing FPS-style games people have made that don't respect my mouse sensitivity settings so my high dpi mouse flies around everywhere.

### How would you like it to work?

API should be 'more opinionated' about suggesting or requiring developers use player's mouse sensitivity options when creating components that use non-absolute mouse. IE it should nag people, or require them to specifically turn it off rather than requiring people to opt *in*.

### What have you tried?

To be fair I'm not super researched on it, maybe the api already is set up in a way to discourage not using sens, but i seem to regularly play games that ignore it.

**Comment by DevulTj** [comment]
I don't understand

**Comment by fantasticaneer** [comment]
> I don't understand

Basically, people make first person games that don't respect the mouse sensitivity you have set in the ingame s&box settings menu. The engine should discourage this somehow, for UX reasons.

**Comment by DevulTj** [comment]
This is already the case, Input.AnalogLook takes your mouse sensitivity preference into account.

Is there something it's not doing right now that you need?

**Comment by fantasticaneer** [comment]
> This is already the case, Input.AnalogLook takes your mouse sensitivity preference into account.
> 
> Is there something it's not doing right now that you need?

My bad, I had assumed this wasn't the case and you had to specifically incorporate the mouse sensitivity yourself in some way in order to get it to be respected.
