### ISSUE TITLE
A cloned prefab does not inherit the prefab name

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#4942]
### Describe the bug

Previously, I could check if there was a prefab instance in my inventory by its name, but now this method does not work and all cloned prefabs have the name GameObject(#) on scene. 

### To Reproduce

Try to clone prefab and NetworkSpawn() this

### Expected behavior

Inheriting a name from a prefab or the ability to get the identifier of the parent prefab from a cloned object

### Media/Files

![Screenshot (125)](https://github.com/Facepunch/sbox-issues/assets/86604770/df5635c1-cb59-465f-8c40-5e75a9f9fb55)

### Additional context

Maybe im just have skill issue

**Comment by DoctorGurke** [comment]
Pretty sure this also affects adding prefabs in-editor? Would for sure love that to copy the name/title. I set the name of my runtime prefabs manually right now, so I also see that being nice for Cloned prefabs.
![sbox-dev_UfPRHU4dE4](https://github.com/Facepunch/sbox-issues/assets/12602100/e6876a5a-e0e7-4f46-8924-f386498be3b1)

**Comment by DevulTj** [comment]
This should work in both of your circumstances now, let me know if that's the case - this was working in local testing.

**Comment by somethink000** [comment]
Yes it works, but is it possible to find out the name of the prefab from which the object is cloned? Or should I make a way to find it myself?

**Comment by DevulTj** [comment]
If you think this is something you need, make an issue for it
