### ISSUE TITLE
[Sync] values propagation delay

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#4943]
### Describe the bug

Hi,
Since i haven't any answer on Discord yet, i prefer creating an issue
(link to my discord message https://discord.com/channels/833983068468936704/895597253316714497/1210255798144475136)

I recently discovered there is a little delay, sometimes 1 or 2 frames, between the propagation of [Sync] values for each client.

So does it seem normal to wait for 1 (or sometimes 2) frames to get a `[Sync]` property propagated to clients?

Let's jump to the reproduction steps

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) For the `networking.scene`, create a test component :
```
public class SyncLatence : Component
{
    [Sync] public Guid OwnerId { get; set; }

    protected override void OnUpdate()
    {
        if ( OwnerId != Guid.Empty ) {
            return;
        }

        Log.Info( "I'm null" );
    }
}
```

2) Edit the `Gun.cs` Component with :
```
// [TRUNC CODE]
o.NetworkSpawn();
// NEW CODE
var syncLatence = o.Components.Get<SyncLatence>();
syncLatence.OwnerId = pc.GameObject.Network.OwnerId;
```

3) Add the created `SyncLatence` Component to the `Network Object Test` GameObject of the `networking.scene`
4) Play scene, connect a secondary user
Press `Attack1` to "fire" with the `Gun.cs`
5) Look result in the console: during 1 or 2 frames, the `OwnerId` of the generated `Network Object Test` is null for other client

### Expected behavior

No delay ?

### Media/Files

Reproduction steps in video:

https://github.com/Facepunch/sbox-issues/assets/5229571/c2361d89-5a5f-44b4-9d8a-1351d40e6573

**Comment by kurozael** [comment]
@PolSpock I think the problem you're having here is that you're calling `NetworkSpawn` but _then_ you're setting `OwnerId`.

Here it the process:

1. You call NetworkSpawn
2. The GameObject gets immediately serialized (OwnerId is empty at this point)
3. The serialized GameObject is immediately put into a packet and sent to other clients
4. You then set OwnerId
5. The change to OwnerId is detected, in the following frame a new packet is created to send synchronized variable changes to clients
6. Your other client sees: an object was created, a few frames later or whatever it receives an update telling it that OwnerId has changed

**Comment by PolSpock** [comment]
> @PolSpock I think the problem you're having here is that you're calling `NetworkSpawn` but _then_ you're setting `OwnerId`.
> 
> Here it the process:
> 
> 1. You call NetworkSpawn
> 2. The GameObject gets immediately serialized (OwnerId is empty at this point)
> 3. The serialized GameObject is immediately put into a packet and sent to other clients
> 4. You then set OwnerId
> 5. The change to OwnerId is detected, in the following frame a new packet is created to send synchronized variable changes to clients
> 6. Your other client sees: an object was created, a few frames later or whatever it receives an update telling it that OwnerId has changed
> 
> I'd bet that if you set OwnerId before calling NetworkSpawn that it'd be fine.

Ok i see. Yeah if i set the `OwnerId` before the `NetworkSpawn()` it's working fine. But it's not what i'm looking for.

I used this logic for my Weapon system: i was using a `[Sync] public Guid OwnerId { get; set; }` Property for handling who was the Owner of the Weapon.

So then my weapon was picked up / dropped, i set the `Guid.OwnerId` with the `PlayerGameObject.Network.OwnerId`
But due to this latency of propagation of my `Guid.OwnerId`, i get some issues for the secondary client where the `OwnerId` of the weapon was not updated for him yet.

So, for this case, i have fixed my issue by using the `Network.OwnerId` which perfectly works without any delay when a TakeOwnership();
So i removed my `[Sync] public Guid OwnerId { get; set; }` shit logic

But is this latency of propagation normal?

If not, it's a real issue, if not, you can close it

**Comment by kurozael** [comment]
Some latency can be expected when networking... however it may be good for us to defer sending spawn messages until the end of the frame.

**Comment by MrBrax** [comment]
really hitting this issue hard right now with multiple gameplay elements, setting a variable on a player from the server and then checking for that variable in the same function. value should probably be set on the host first?

**Comment by kurozael** [comment]
It is... but you can only set the value if you own the GameObject, or if you are the host and the property is HostSync. The value of the property will not change if you don't have authority to write to it.

**Comment by MrBrax** [comment]
right, so what i'm doing to change the value from the host is a broadcast function on the player that just sets the variable
```csharp
[Broadcast( NetPermission.HostOnly )]
public void SetPlayerState( PlayerState state )
{
	State = state;
}
```
but the host doesn't know about this change in time so a sync function won't work

**Comment by kurozael** [comment]
Yeah of course because while the RPC method will be invoked immediately for the host, the host doesn't have permission to set the State variable. So it has to wait for the owner to receive the RPC, set the State variable, then replicate it to the host.

As I say, only the owner of the GameObject can change the value of a Sync property.

The way around this would be allow you to mark a property as both Sync and HostSync - but it may be problematic if you set the value on the host but before the other clients receive the value change, the owner changes it as well.

I'll consider letting a property have both Sync and HostSync.

**Comment by MrBrax** [comment]
yup, it's related to the issue i made #5153 , i might be able to hack around this using async delays and hope for propagation but i'm not sure

**Comment by kurozael** [comment]
I believe this is resolved. HostSync and Sync are usable together.

**Comment by PolSpock** [comment]
To be honest, no. But i think it's the expected behavior;

For example:
I haven't created an Authoritative logic yet, but i'm looking to network who has damaged a player.
So currently every player handles his own `TakeDamage` and populate his own `Attackers` Dictionary:
```
// Player Component

[Sync] public NetDictionary<Guid, float> Attackers { get; set; } = new NetDictionary<Guid, float>();

[Authority]
public void TakeDamage(Guid attackerId)
{
	// [...]
	Attackers[attackerId] += damage;
}
```

However during this frame, if i broadcast an event like `OnKilled.Invoke( this )` broadcastly, every player who tries to retrieve the PlayerComponent.Attackers will not be able to retrieve the last updated value since the `Attackers` are not propagated to the network yet. I need to wait for the next frame, which is quite annoying.

In the future, i need to create a strict authoritative Host logic cause currently a player has to much power to cheat in my game. But this does not exclude that behavior is annoying.

**Comment by kurozael** [comment]
I'm sorry @PolSpock but I'm still having a hard time grasping this. Are you expecting that Sync var values are sent before any RPCs?

**Comment by MrBrax** [comment]
that's exactly what i was trying to work around, have to send multiple things in one rpc instead of sync vars to ensure they're available at the same time

**Comment by PolSpock** [comment]
Here is an example :

```
// PlayerComponent
public delegate void KilledEvent( PlayerComponent player );
public static event KilledEvent OnKilled;

[Sync] public bool IsDead { get; set; }

[Authority]
public void OnKilled() {
	IsDead = true;
	
	BroadcastEvent();
}

[Broadcast(NetPermission.OwnerOnly)]
public BroadcastEvent() {
	OnKilled.Invoke(this);
}
```

When my other players subscribed to `OnKilled` event will receive a message, the `PlayerComponent.IsDead` will still be false cause it's running in the same tick i guess

**Comment by kurozael** [comment]
> Here is an example :
> 
> ```
> // PlayerComponent
> public delegate void KilledEvent( PlayerComponent player );
> public static event KilledEvent OnKilled;
> 
> [Sync] public bool IsDead { get; set; }
> 
> [Authority]
> public void OnKilled() {
> 	IsDead = true;
> 	
> 	BroadcastEvent();
> }
> 
> [Broadcast(NetPermission.OwnerOnly)]
> public BroadcastEvent() {
> 	OnKilled.Invoke(this);
> }
> ```
> 
> When my other players subscribed to `PlayerComponent.OnKilled` event will receive a message, the `PlayerComponent.IsDead` will still be false cause it's running in the same tick i guess

Yeah this is because RPCs are sent immediately, but changes to Sync vars are only sent at the next network tick. Therefore in your case, other clients are first receiving the RPC and then later receiving the change to the Sync var.

I'm working on a message queue system that should resolve the order of things.

**Comment by MrBrax** [comment]
would be quite interesting, i don't think i had issues like this before the scene system so it was probably stricter before
