### ISSUE TITLE
Objects excluded from camera still render their AO proxies

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4944]
### Describe the bug

Objects that are excluded from rendering by a camera still render their AO proxies.

### To Reproduce

1. Create a prop that uses a model with AO proxies
2. Add a tag to it
3. Add that tag to the exlude tag list of a camera
4. See that the AO proxies still render

### Expected behavior

AO proxies should not render if the object is not being rendered

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/546e57c0-68e0-44ad-9607-dc6b18e35adb

**Comment by DevulTj** [comment]
This should work as intended now

**Comment by Gmod4phun** [comment]
Seems to be fixed, thank you
