### ISSUE TITLE
[Editor] Drop object to floor via keystroke

### ISSUE THREAD

**Issue by BlizzCrafter** [Facepunch/sbox-issues#4948]
### For?

S&Box

### What can't you do?

I'm unable to drop an object in the editor so that it snaps to the object below (like the floor plane).

### How would you like it to work?

I want to press a key on the keyboard to drop the object to the floor. In other game engines or editors it is the "End" key.

### What have you tried?

n/a

### Additional context

n/a

**Comment by DrakeFruit** [comment]
is this not just vertex / edge / face snapping?

**Comment by BlizzCrafter** [comment]
It seems you are referencing how it works in [unity](https://youtu.be/t_xxsCcM60k?si=ENur05a_ZOaTBh_X&t=37) and yes, it would be very nice to have a feature like this.

Sometimes it would be enough for me if I could press just a single key and then the object would snap to the next object below. But yes, vertex / edge / face snapping would make it even more complete.

**Comment by DrakeFruit** [comment]
This is a basic feature of modelling software, including hammer. I assume this will come with the mesh editor Layla is working on.

**Comment by chrisspieler** [comment]
Ctrl+1 will snap an object to the floor below it.

**Comment by bakscratch** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/8184184/ef46bd25-88f0-40fc-8b53-05b7cc8411d3)
I added something like this a while back

**Comment by BlizzCrafter** [comment]
Indeed this is exactly what I was looking for.
