### ISSUE TITLE
Allow loading new scenes while keeping the current lobby connected

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#4949]
### For?

S&Box

### What can't you do?

`OnChangingScene()` is being called from `Scene.Load()` which in turns calls `GameNetworkSystem.Disconnect()`. It seems that you can't keep your lobby and change scenes.

### How would you like it to work?

`SceneLoadOptions` could have a boolean if to disconnect or not

### What have you tried?

Extending the `GameNetworkSystem` which caused more errors

**Comment by Guilhem-Pech** [comment]
Can't do "lobby scenes" because of that or switch players from one level to another it's annoying

We also can't use additive scenes as workaround :(

**Comment by Retroeer** [comment]
Any progress on this? I've hit a bit of a block without this

**Comment by MrBrax** [comment]
If this change goes through, it should probably show a warning if your code is left untouched, as I assume most people just change scene without manually disconnecting. Having your joined players be brought with you back to the menu when exiting would be strange.

**Comment by DevulTj** [comment]
I've added a basic version that'll let you do what you want here. It'll behave like Source, by having you reconnect to the server for now. 

In the future, we'll want to do this in a better way, maintaining the connections, and sending a message to load the new scene for everyone, send a snapshot, and run INetworkListener callbacks.

**Comment by rcnoob** [comment]
It seems this is still an issue at least with the base Scene.Load or Scene.LoadFromFile. All players are disconnected upon load, and I cant seem to find any way to keep them around after the scene change
