### ISSUE TITLE
Can ent_door entity support sounds, slave door

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#495]
Ent_door is a very truncated entity, compared to prop_door_rotating, you removed the "slave name" "door sounds" and other useful old features

"slave name" was used to create double doors 

"door sounds" for easy work with sounds, without third-party entities like snd_event_point

OLD

![image](https://user-images.githubusercontent.com/54669564/126897344-ef4c4fe2-468d-4292-b066-ac7f7be147cb.png)

NEW (BAD)

![image](https://user-images.githubusercontent.com/54669564/126897273-80b3ca5d-727d-4c7d-bbb1-952ec3c60075.png)

**How would you like it to work?**

I suggest bringing back these very important features

**Comment by robotboy655** [comment]
Anything else besides "slave name" and door sounds you are missing?

**Comment by gabengaGamer** [comment]
I think that's enough

**Comment by MARK2580** [comment]
@robotboy655 
Why are you breaking this game too? Why did you delete a bunch of necessary door parameters? You also need at least Spawn Position, Health, Open Direction, Hardware type.
And of course the above sounds and slave name.

**Comment by walllable** [comment]
> 
> 
> @robotboy655
> Why are you breaking this game too? Why did you delete a bunch of necessary door parameters? You also need at least Health and Hardware type.
> And of course the above sounds and slave name.

> Why are you breaking this game too? Why did you delete a bunch of necessary door parameters?

They're redoing entities in c#. Garry's explained the reasons why in two dev blogs.
https://sbox.facepunch.com/news/may-2021#MapEntities
https://sbox.facepunch.com/news/march2021#EntityImplementations

> We have a unique opportunity right now to liberate the engine from its 20 years of iteration. To remove old entities, to give things logical names, to make things easier for everyone.
> 
> The Entity Input/Output system is now totally in c#. Entities trying to do input stuff in c++ do nothing. This just means we need to delete the c++ entity and rewrite it in c#.
> 
> This is what we've been doing this week. It's less of a recreation and more of a curation. When we're converting these things, can we make it better, can we add features that mean mappers don't have to create a IO web to do something.

**Comment by gabengaGamer** [comment]
and ? Entities are poorly ported to C #

**Comment by ogniK5377** [comment]
There's no need to be aggressive and constantly open and close the issues, if something needs to be changed it will. If not, the entity is in C#, you can inherit from it and make any changes you wish and make your own doors too

**Comment by walllable** [comment]
Yeah, they're gonna be like that when the game's in an alpha state. Nothing's done yet. That's why they're taking suggestions and feature requests from mappers so that features they want can be implemented, and new quality-of-life features that weren't in the legacy entities can be implemented as well.

**Comment by gabengaGamer** [comment]
We're not all coders, do you know?

**Comment by walllable** [comment]
> 
> 
> We're not all coders, do you know?

That's what feature requests like this one are for

**Comment by gabengaGamer** [comment]
That is why you need to transfer entities to C # in a high-quality manner.

**Comment by lamalome** [comment]
@robotboy655 I agree with him, fix it.

**Comment by lamalome** [comment]
> Вам не хватает чего-нибудь еще, кроме "имени раба" и дверных звуков?

 turn off the lights limit👈

**Comment by gvarados1** [comment]
Hardware type doesn't make any sense in s&box. Use bodygroups instead.
Health can be setup in the model.
Slave name is obsolete. If two doors have the same name, they're a double door and open at the same time (idk if s&box has this yet)

The only thing that needs to be added is sounds. Let's not fill these entities with redundant garbage.

**Comment by gabengaGamer** [comment]
> Hardware type doesn't make any sense in s&box. Use bodygroups instead.
> Health can be setup in the model.
> Slave name is obsolete. If two doors have the same name, they're a double door and open at the same time (idk if s&box has this yet)
> 
> The only thing that needs to be added is sounds. Let's not fill these entities with redundant garbage.

"Slave name is obsolete. If two doors have the same name, they're a double door and open at the same time (idk if s&box has this yet)" no, it won't work

**Comment by garrynewman** [comment]
In that case does one door open and the other stand still?

**Comment by gabengaGamer** [comment]
yep

**Comment by VanderAGSN** [comment]
> Slave name is obsolete. If two doors have the same name, they're a double door and open at the same time (idk if s&box has this yet)

"Slave Name" used in Source for other reason. Imagine that you have some different models that you want to parent to different doors with sync opening them, and with same door name you cannot do this, that's why "slave name" is still useful in Source 2.

**Comment by gvarados1** [comment]
I guess that could be useful. I've always just used io

**Comment by robotboy655** [comment]
Added sounds, doors with the same name opening together, initial position slider and the "open away from player" thing.

Still not sure about "slave door" thing. Breakable doors and animated model doors is something to look into still.

**Comment by VanderAGSN** [comment]
> Still not sure about "slave door" thing. 
Add it please, that's still some needed stuff when working with parenting, I wrote above where it can be useful

**Comment by robotboy655** [comment]
Added "slave door" as "Other doors to open" keyvalue.
