### ISSUE TITLE
Terrain doesn't work in multiplayer.

### ISSUE THREAD

**Issue by rbwldrf** [Facepunch/sbox-issues#4951]
### Describe the bug

When I enter the game in multiplayer as another instance, the terrain refuses to display, citing an object reference error.

### To Reproduce

1. Create a project with the 'Minimal' template.
2. Add a Terrain to the scene.
3. Play the scene, and host it.
4. Join via new instance.

### Expected behavior

I'm assuming the intention is to have Terrains that work in multiplayer eventually.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/53384860/96e26ab1-25de-479d-91b6-eb961c850740)

### Additional context

I am running the Windows 11 23H2 beta, but I don't think that's relevant to the issue.
I'm running Build ID: 13569185, which I updated to just minutes ago, and still have the issue.

**Comment by handsomematt** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/1388267/d1f2b12c-21b7-4190-a466-506ae4aef699)

should be good now

**Comment by Josh-AS** [comment]
This seems to still be happening for me.
Creates whatever that monstrosity is in the background.

![image](https://github.com/Facepunch/sbox-issues/assets/37937117/dd9780db-6403-4481-a695-9b07a32fc6c1)

**Comment by chrisspieler** [comment]
Multiplayer terrain is working fine in Idaho RP. Are you still having this issue, @Josh-AS ?
