### ISSUE TITLE
game loding and closing

### ISSUE THREAD

**Issue by somewhere-in-the-universe** [Facepunch/sbox-issues#4953]
### Describe the bug

when I`m trying to load the game with -dx11 command in startup options the game is opening and closing quickly

### To Reproduce

1. go to startup options
2. type in command -dx11
3. start the game

### Expected behavior

the game must start

### Additional context

I`m running on windows 11 22h2 version on unsupported card(by vulkan)

**Comment by handsomematt** [comment]
If your card doesn't support Vulkan, it's very unlikely you'd be able to run under DX11 either... What are your system specs, can you provide your Log.txt and also your steamid. https://docs.facepunch.com/doc/reporting-errors-2OTPIafqCJ

**Comment by handsomematt** [comment]
Was missing AMD drivers
