### ISSUE TITLE
GameObjects assigned in a GameResource don't save when you close your editor

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4956]
### Describe the bug

GameObjects reference in a GameResource don't save between Editor sessions

### To Reproduce

1. Create a GameResource with a GameObject Property
2. Assign a GameObject to it.
3. Close the Editor
4. It's gone :(

### Expected behavior

It should probably save

**Comment by Retroeer** [comment]
this, somehow resolved itself, you facepunch guys really work fast!

**Comment by drongood12** [comment]
If you restart the project, your GameResource
 will not be saved. PrefabFile for prefabs works well instead of Gameobject
![image](https://github.com/Facepunch/sbox-issues/assets/73915636/3ee5ccf8-dc3c-4a8d-8d7f-5a0eea40332b)
![image](https://github.com/Facepunch/sbox-issues/assets/73915636/6aee2230-245c-46ff-a030-f2cb84d809d7)

**Comment by Retroeer** [comment]
That actually does seem to be the case, reopening the issue then.

**Comment by drongood12** [comment]
I also want to point out that when the prefab is changed, the GameResource is not updated automatically, although this does not apply to this bug, it also applies to GameResource

**Comment by DevulTj** [comment]
I'm not getting this issue

![image](https://github.com/Facepunch/sbox-issues/assets/22372616/89c78475-34df-4cf7-911d-ec0faf1d3449)
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/804f171f-05a0-4f74-b0c2-7c43d9bf25c0)

**Comment by DevulTj** [comment]
This should be fixed, let me know if you're still having this issue when the latest build hits Steam

**Comment by Retroeer** [comment]
Everything seemingly works, thanks!
