### ISSUE TITLE
Changing the scale or position of bone objects created with SkinnedModelRenderer.CreateBoneObjects true causes them to explode

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4958]
### Describe the bug

If you change the scale or position of the bone objects created on a SkinnedModelRenderer with CreateBoneObjects = true, they just explode-- meaning, the position and scale goes absolutely crazy.
This seems to happen with any model that has bones.

### To Reproduce

1. Create a new SkinnedModelRenderer with a model that has bones like the Citizen.
2. Toggle Create Bone Objects
3. Modify the position or scale of those bone objects
4. They go crazy!

### Expected behavior

Other engines (eg: Unity) allow scaling and moving the transforms of bones and simply applies that transformation to the bones in a way that works seamlessly and works at runtime.

### Media/Files

![sbox-dev_R78OY4emMy](https://github.com/Facepunch/sbox-issues/assets/5409303/8ae2c1ca-509e-4560-9c80-4d22815b4f29)

### Additional context

@Game4Freak in discord reported same issue. This happens when modifying the bone position/scale/etc in code as well, not just manually with the gizmos.

**Comment by aylaylay** [comment]
They shouldn't blow up now. Not sure what the plan is for transforming these bones because currently they will just get reset when playing the game but at least they wont blow up now.
