### ISSUE TITLE
Ability for third party server to verify steam user authenticity

### ISSUE THREAD

**Issue by ryangrahamnc** [Facepunch/sbox-issues#496]
Currently if a game mode communicates with a third party webserver, we can pass the steam id to indicate which user is performing the action. But thats vulnerable to spoofing: anyone would be able to put other peoples steam id's in the request and claim they are that user.

What I'd like is a way for the third party webservers to check whether or not a user is who they say they are. It could be done similarly to how steam does tickets: https://partner.steamgames.com/doc/features/auth#client_to_backend_webapi

In that case, theres three pieces:
1. Steam backend server
2. Player's local client
3. Third party server

And the communication process looks like this:
1. Player's local client talks to steam backend. Steam backend gives a "ticket", which is just garbled data linked to that steam user.
2. Player's local client sends that ticket to third party server
3. Third party server sends given ticket to steam backend server. Steam backend says it was the ticket generated for steam id xyz. Third party server now knows the user is who they say they are.
4. Third party server can do whatever they want now. i.e. send back a jsonwebtoken to the client indicating they're authed for that particular steam id. And then trust all future requests with that jwt.

Existing alternative approaches:
- use steamworks ISteamUser::GetAuthSessionTicket and ISteamUserAuth/AuthenticateUserTicket. I actually dont think this works now do to limited c# api access. And it seems like it would be a security issue, because those tickets give more access than just user verification.
- use steam's openid/oauth. the problem here is itll open up a modal asking the user to login, which is just tacky. And would get annoying for users if many addons use the same tool that requires user verification. I'd prefer something that works automatically in the background.

**Comment by garrynewman** [comment]
Closing this in favour of #507 since it's closer to what we should do
