### ISSUE TITLE
Ability to press F1 to open console while testing game in editor no longer works

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4960]
### Describe the bug

You used to be able to press F1 to use the console while playing your game in the editor. Now you can only use ` to focus the console if the widget is part of your current layout.

### To Reproduce

1. Play a game
2. Press F1
3. No console :(

### Expected behavior

Open the console. It was nice to have multiple options to do so.

### Additional context

I've been told this may have been intentionally removed but I don't know why. Having an additional floating console window you can use while in fullscreen is nice for quality of life.

**Comment by badandbest** [comment]
I think the missing console and the version splash text was a side effect of them no longer loading the main menu in tools mode.

**Comment by garrynewman** [comment]
^ this is correct. This might come back, but it's no priority right now..
