### ISSUE TITLE
Typo in scene view option

### ISSUE THREAD

**Issue by u254254** [Facepunch/sbox-issues#4961]
### Describe the bug

Scene view option panel has a typo ("Gimzo Scale")

### To Reproduce

1. Open any project
2. Click triple-dot (<img width="15" alt="sbox-dev_sIOIOaIDyY" src="https://github.com/Facepunch/sbox-issues/assets/72965213/ac4666fe-cbc2-471d-9be4-5180e310d4f4">) button in scene view
3. Typo in opened panel

### Expected behavior

It should say "Gizmo Scale" instead of "Gimzo Scale"

### Media/Files

<img width="450" alt="J4kN1kGRwJ" src="https://github.com/Facepunch/sbox-issues/assets/72965213/5e4fe6a1-3c06-44f5-884a-12e040908d31">

**Comment by aylaylay** [comment]
fixed thanks
