### ISSUE TITLE
💖 Prettier Hierarchy in the Editor! Wouldn't it be nice?

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4962]
### For?

S&Box

### How often do you say to yourself:
> "Gosh, my Hierarchy of GameObjects in the Editor is just too dull, drab and boring! 😔" 

You know what'd be a wonderful and enjoyable quality of life improvement that would *also* be a fun and easy afternoon of coding for one lucky Facepunch developer?

That's right-- you guessed it-- ✨Prettier Hierarchy in the Editor! ✨

But what does that entail? You might even ask... _"How would you like it to work? Describe in detail how this wonderful feature should work."_

### How would you like it to work?

* [ ] _Right Click > Color_ option for GameObjects in the Hierarchy. 
There would be a few default choices and a custom color picker option.
![image](https://github.com/Facepunch/sbox-issues/assets/5409303/4164b304-b849-422a-8a02-4c1d5cdd6bb6)
Like this, but implemented better, by the sexy Facepunch developer who takes on this feature request!
* [ ] _Right Click > Create Folder_ when selecting empty space in the Hierarchy. These would simply have the folder icon and create a subtle outline around a group of items that contain the folder. 
Something like this (ignore my shit image editing work)
![image](https://github.com/Facepunch/sbox-issues/assets/5409303/c33d84bf-0334-48c6-81f6-9297fe58253f)
* [ ] _Right Click > Set Icon_ option for GameObjects in the Hierarchy.
This would not only change the icon in the Hierarchy, but also the icon that appears in the top left of the Inspector. Clicking that icon-- the smiley face, currently, would also be a shortcut to change the icon.
I didn't take the time to image edit this one but you can just imagine how great it would be.
Also, the default GameObjects would ideally have icons set by default - luckily we already have those! They just need to appear in the Hierarchy and the top left part that currently displays the smiley face.
![image](https://github.com/Facepunch/sbox-issues/assets/5409303/894ee218-2120-4794-997e-21f0b2213a25)

### What have you tried?

Long have I tried coping with the fact that my Hierarchy is dull and boring, and lacking icons, folders, and pretty colors, but every day it wears upon me further. Woe is me. I can only hope that one day my troubles will be eased.

### Additional context

_I have mental illness._

**Comment by GavrilovNI** [comment]
What is the point of folders when you can just have parent GameObject? Just for outline?

**Comment by fantasticaneer** [comment]
> What is the point of folders when you can just have parent GameObject? Just for outline?

Yeah, to have the items in the folder highlighted/differentiated in some way, and to also give it a folder icon automatically.
The folders are honestly the weakest element of this, I think, I could take or leave them, since like you said, you can just have an empty gameobject.
Also, perhaps coloring the folder would also color the items inside, but maybe you'd want to be able to set them manually, I dunno.

**Comment by badandbest** [comment]
# Colors
Blue, green and dark gray are used by networked objects. I believe a pink-ish color is also used by bones.

All of this would need to be redesigned to allow for custom colors.

# Folders
Garry has clowned on this idea on multiple occations.

# Icons
I'm for this idea.

Bones, networked objects and prefabs all get their own icons. But that shit is hardcoded.

**Comment by handsomematt** [comment]
All this stuff adds more noise. Automatic colors are already reserved for purpose, Folders are confusing too.
