### ISSUE TITLE
Delete key doesn't work to delete the stops/nodes in the Gradient property editor

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#4963]
### Describe the bug

It's pretty clear the Gradient editor isn't finished but dragging the nodes away in order to remove them is pretty unintuitive.

### To Reproduce

1. Set a Particle's Color > Gradient property Type field from Constant to Gradient and edit it.
2. Create a node / stop on the gradient and then try to remove it with Delete.
3. Doesn't work, you have to drag it up and away from the editor to remove it, which is unintuitive.

### Expected behavior

Delete key should work, or there should be a delete button on the editor popout.

**Comment by Brassx** [comment]
Yes please, I couldn't figure out how to delete these until you told me to drag 'em out.

![fa748174e90f9c6d4996e79ae5bfb933](https://github.com/Facepunch/sbox-issues/assets/6100996/05adf2fe-a651-473b-b643-2adae47d071d)
