### ISSUE TITLE
Hitbox Surface Property doesn't work

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#4965]
### Describe the bug

Hi,

I'm looking to use another Hitbox Surface Property than the `default.surface` but i was surprised to see that doesn't work at all.

Running a `SceneTrace` with `UseHitboxes(true)` must be able to return the correct `SceneTraceResult.Surface` defined in the ModelDoc Hitbox settings, but it doesn't.

Let's jump to the reproduction steps

### To Reproduce

0) Constate that the default Surface Property Hitboxes are `flesh`
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/11c84f23-ab58-45b3-a428-52f312f9fedf)

1) Download https://github.com/Facepunch/sbox-scenestaging/
2) Edit the `CameraPhysicsDebug.cs`, and edit the `OnUpdate()` func with my piece of code :
```
if ( TraceType == TraceTypes.Ray )
{
	t = Scene.Trace
		.Ray( start, end )
		.UseHitboxes( Hitboxes )
		.Run();

	// NEW CODE
	if (t.Hitbox is not null )
	{
		Log.Info( t.Surface + " " + t.Hitbox.Tags.TryGetAll().Aggregate( ( a, b ) => a + " " + b ).ToString() );
	}
}
```

3) Start `hitbox.scene`
4) Look at the Terry: no Surface returning `Surface:flesh`, only `Surface:default`

### Expected behavior

Returns the correct `Surface Property` defined in ModelDoc Hitbox

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5229571/7fe01fcc-3def-4e7b-bf85-d8b5887f28ca

**Comment by aylaylay** [comment]
Should be fixed now
