### ISSUE TITLE
Game resource’s values don’t reset when you exit the scene

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4966]
### Describe the bug

I use game-resources to keep track of my ammo values and when I set them in the scene it saves the file values when I close the scene. Watching the video attached below will explain better than words. 

### To Reproduce

1. Create a game resource with some int.
2. Change the value within the scene

### Expected behavior

The value should be resetting to the value outside the scene.

### Media/Files

Uploading 2024-02-25_11-13-09.mp4…

**Comment by DoctorGurke** [comment]
I don't think you should treat game resources like containers you update at runtime.

**Comment by Nolankicks** [comment]
> I don't think you should treat game resources like containers you update at runtime.

How else would you save ammo values? I think it makes sense.

**Comment by DoctorGurke** [comment]
On your weapon or player, use a game resource for default and maximum ammo etc.

**Comment by Nolankicks** [comment]
> On your weapon or player, use a game resource for default and maximum ammo etc.

Just another component on a long list of components.

**Comment by DoctorGurke** [comment]
Yes that's how the engine works

**Comment by CarsonKompon** [comment]
Yeah this is purely user error. You should not be setting values of a GameResource at runtime like this. Put your ammo count in a Weapon Component and decrement that 👍

**Comment by Nolankicks** [comment]
User error
