### ISSUE TITLE
Component Property sets to wrong component on starting scene

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4967]
### Describe the bug

if a gameobject has 2 components derived from same class
after scene starts properties will be set to first component found derived from that class

### To Reproduce

1. use code below
2. add components to gameobject like in screenshot
![image](https://github.com/Facepunch/sbox-issues/assets/9992453/e88517ab-d639-4df3-8d35-7d87815ad529)
3. run scene
4. component2 will be set to component1
![image](https://github.com/Facepunch/sbox-issues/assets/9992453/2bad0bd3-23c3-4bb6-a5d9-d655a5a4713c)

```
using Sandbox;


public class TestComponent : Component
{

}

public class TestComponent1 : TestComponent
{

}

public class TestComponent2 : TestComponent
{

}

public class Test : Component
{
    [Property] TestComponent Component1 { get; set; } = null!;
    [Property] TestComponent Component2 { get; set; } = null!;
}
```

### Expected behavior

properties being set to values they were set before scene was started

**Comment by handsomematt** [comment]
#4286
