### ISSUE TITLE
Add `Stats.Update` method to retrieve newest stats

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#4968]
### For?

S&Box

### What can't you do?

Get up to date local/global stats after the game has been loaded.

### How would you like it to work?

Similar to how you can call `Flush` to instantly push your stats, you could call an `Update` or `Retrieve` method to update the values normally only updated at boot.

Might also be a good idea to have a built-in auto-refresh option so we don't have to program it ourselves. Something like `Stats.AutoRefresh = 60f;`. Then add a `Stats.OnRefresh` callback we can hook into.

Put a 30s or so cooldown on it if you're worried about API spam.

### What have you tried?

Making a custom cache for the affected values that aren't actually up to date, but at least are visibly incremented immediately.

### Additional context

I have a "likes" stat for each map in my game, and it would be nice to have that count update live immediately after you press the button.
![image](https://github.com/Facepunch/sbox-issues/assets/100040020/7da1728d-e173-4a35-980b-3ecc5d548cfb)

**Comment by garrynewman** [comment]
The ways these stats and leaderboards work need to be thought about more.
