### ISSUE TITLE
assets dont appear on the assets browser

### ISSUE THREAD

**Issue by CinarBayramic** [Facepunch/sbox-issues#4969]
### Describe the bug

the asset i created doesnt appear on the assets browser and gives the error "someting went wrong with registering (asset name)"

### To Reproduce

1. Open a project of your choice
2. create an asset on the asset browser

### Expected behavior

the files should appear on the asset browser

### Media/Files

[Log.49.log](https://github.com/Facepunch/sbox-issues/files/14397206/Log.49.log)

**Comment by handsomematt** [comment]
`C:/Users/lenovo/ı9 Dropbox/Çınar Bayramiç/`

Does it work if you put your project somewhere without all the weird characters

**Comment by CinarBayramic** [comment]
umm idk the weird characters appeared when i installed dropbox i'll try putting it somewhere else

**Comment by CinarBayramic** [comment]
yep it works i think it was just because of the foreign characters
