### ISSUE TITLE
SCSS masks break overflow: scroll culling

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#4971]
### Describe the bug

When I have a parent panel with `overflow: scroll`, and children that use masks, the culling of panels breaks.

### To Reproduce

1. Copy and add the following child to your panel: https://gist.github.com/ceitine/e145ecaa5d087f0e94f85ef2e69a86c2
Also download the mask: https://i.imgur.com/YyT8nBD.png

2. See the culling break.

### Expected behavior

The culling shouldn't break because of masks.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/19620198/ff20171a-afda-4a53-b19c-29de34330846)

**Comment by handsomematt** [comment]
@xezno is this the same as https://github.com/Facepunch/sbox/issues/1453 ?

**Comment by xezno** [comment]
> @xezno is this the same as [Facepunch/sbox#1453](https://github.com/Facepunch/sbox/issues/1453) ?

Looks like it.
Should be fixed on next build.
