### ISSUE TITLE
Can not start sbox.exe

### ISSUE THREAD

**Issue by 0x646F317068696E3732** [Facepunch/sbox-issues#4975]
### Describe the bug

error on start

### To Reproduce

1. Download game in steam
2. Try to start and catch error

### Expected behavior

Starting game, but bruh

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/108773646/1c087f2f-4aec-4b3c-acc7-5bb10cab28c7)

debug

**Comment by handsomematt** [comment]
Does engine2.dll exist? Do you have an anti virus? Do you have the game on Steam?
