### ISSUE TITLE
ActionGraph custom enums get turned into strings

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4976]
### Describe the bug

Having a custom enum defined inside of the class used to define a custom actiongraph node, and using that enum as a parameter for the node, will have it turn into a string inside of the actiongraph after a while.

### To Reproduce

1. Create a custom enum
2. Use that enum as a parameter for a node
3. Add the node in an actiongraph
4. Save
5. Force recompile on scene/prefab where the component is located
6. Close Project
7. Open Project
8. Play Scene
9. Inspect raw binary of the node (Somehow there's a cached, working version of the node if you inspect it in the actiongraph, doesn't appear to be the case after a few restarts)

Those steps might not be the correct ones but they seem to do it for me, here is the code I used:

```
public enum CookedLevel
{
	Rare,
	Medium_Rare,
	Medium,
	Medium_Well,
	Well_Done,
	Congratulations
}

[ActionGraphNode( "custom.withenum" ), Pure]
[Title( "Steak Doneness" ), Group( "Steak" ), Icon( "lunch_dining" )]
public static void SteakDoneness( CookedLevel level )
{
	Log.Info( $"I'm hungry for some {level} steak!" );
}
```

### Expected behavior

Remain stored as the enum

### Media/Files

Here's an example of what the changes look like in the json:

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/164f2613-3f97-423a-bcb5-69c5ce959149)

As you can see in this example, the enum type "EasingFunction" gets all omitted, leading to the value becoming a normal string.

### Additional context

If you're unable to recreate it with the given setup I can provide the repo where we're encountering the issue.

**Comment by Metapyziks** [comment]
I've tried your repro steps in a scene, prefab, and resource, but it's always getting serialized property for me:

```json
{
  "Value": "Medium",
  "DstId": 14,
  "DstName": "level"
}
```

Are you testing in an otherwise empty project?

**Comment by yuberee** [comment]
I was testing that on our game project.
I've set it to public so you can pull, these are the nodes in the screenshot: https://github.com/Small-Fish-Dev/Sauna/blob/main/code/Event/Nodes/InterpolationNodes.cs

You can find them inside of the creepy peeper prefab: https://github.com/Small-Fish-Dev/Sauna/blob/main/prefabs/events/creepy_peeper.prefab (In the ScaredEvent child -> Event Component -> Actions)

But from what I can see, the serialized format you gave me is also incorrect, no? 
Missing the "Type: CookedLevel" stuff and all like seen in the screenshot. Unless that has changed.

**Comment by Metapyziks** [comment]
Thanks, I'll give that a try!

> But from what I can see, the serialized format you gave me is also incorrect, no? Missing the "Type: CookedLevel" stuff and all like seen in the screenshot. Unless that has changed.

It'll only add the "$type" stuff if it can't infer the expected type. In your example it shouldn't be ambiguous, so when "$type" appears something has gone wrong.

**Comment by Metapyziks** [comment]
I can reproduce it finally 🎉

**Comment by Metapyziks** [comment]
Possible fix should be on staging now.

**Comment by yuberee** [comment]
Alrighty, if I don't encounter within a week I'll close this. If I do I'll try to trace back my steps.

**Comment by Metapyziks** [comment]
All working for you @yuberee?
