### ISSUE TITLE
ActionGraph groups not removed when updated

### ISSUE THREAD

**Issue by akaadream** [Facepunch/sbox-issues#4977]
### Describe the bug

When you got a custom node from a script and you rename the Group name, the old group name is still visible and you can put the old group name node inside an Action Graph.

### To Reproduce

1. Create a new node in a script with a specific Group name like "Test"
2. Save and put it inside an Action Graph
3. Modify the Group name with like "Test 2"
4. You should have both groups and eventually, an "Unable to resolve method binding" error

### Expected behavior

By saving the script with the action graph nodes updates, the Action Graph should remap if possible the updated node *or* delete the node.
And when we want to add a new node, the old Group should not be visible anymore if there is no node inside.

**Comment by Metapyziks** [comment]
Thanks for the report. I think this will be the same cause as #4946, I'll find out tomorrow.

**Comment by akaadream** [comment]
I don't have any warning when I'm saving my code. 
Maybe because of creating sub folders? In my case, I was moving my custom nodes from a Group subfolder to another one.
Another guess would be the use of the character "&" inside the name of the folder.
Maybe I have to give more try to it.

**Comment by akaadream** [comment]
I created the minimal project and then tried to reproduce the issue, but even with errors or warnings inside Action Graph, I was not able to reproduce it.
Maybe it happens in a very rare cases so maybe when the #4946 happens, I don't really know then, I'm sorry to not being able to reproduce it.

**Comment by Metapyziks** [comment]
Did you get a chance to test this out @akaadream ?
