### ISSUE TITLE
Links in project description not work

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#4979]
### Describe the bug

When im create link this guides me on https://www.google.com

### To Reproduce

Create link in project description

### Expected behavior

The link directs me to the link

### Media/Files

![Screenshot (140)](https://github.com/Facepunch/sbox-issues/assets/86604770/d89fe442-9f75-4794-950d-62a1d3640bd4)

**Comment by somethink000** [comment]
https://asset.party/evilinc/stol

**Comment by cr4yz** [comment]
Google is the default url if none is specified, you can specify a link by clicking it in the block editor:

https://github.com/Facepunch/sbox-issues/assets/9637557/e2420f7d-65d5-4822-9f24-68c099dfaa0a

Please re-open if you have further issues with it
