### ISSUE TITLE
GameObject created from the Editor dont keep the Editor instance when scene starting

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#4980]
### Describe the bug

When you MyComponent on a GameObject from the Editor, the child is created and `_go` have an object reference. But when you start your scene, `_go` doesn't keep the same instance as the Editor

### To Reproduce

- Create a component with the code below:

```csharp
public sealed class MyComponent : Component, Component.ExecuteInEditor
{
	private GameObject _go = null!;
	
	protected override void OnAwake()
	{
                // Without this, a second GameObject is created when the scene start.
		if ( !Scene.IsEditor ) return;
		
		_go = Scene.CreateObject();
		_go.Name = "Child";
		_go.Parent = GameObject;
	}

	protected override void OnStart()
	{
		Log.Info("My Component Children Count: " + GameObject.Children.Count);
		Log.Info("My Component Child is null ? " + string.Join(", ", (_go is null)));
	}
}
```

- Add the component on any GameObject, the log should print that:
 GameMenu My Component Children Count: 1
 GameMenu My Component Child is null ? False
 
 - Next, start your scene. The component should print that:
 GameMenu My Component Children Count: 1
 GameMenu My Component Child is null ? True

### Expected behavior

`_go` should keep the Editor instance when the scene start

**Comment by Metapyziks** [comment]
This might not be a bug, iirc when you play a scene a copy is created by serializing the edited scene to JSON and back.

Only properties marked with `[Property]` are serialized, so the value stored in your `_go` won't be preserved.

**Comment by bub-bl** [comment]
> This might not be a bug, iirc when you play a scene a copy is created by serializing the edited scene to JSON and back.
> 
> Only properties marked with `[Property]` are serialized, so the value stored in your `_go` won't be preserved.

I see. I thought instances of variables were kept
Thanks for the quick response, i close this issue
