### ISSUE TITLE
Game view is not updating

### ISSUE THREAD

**Issue by ElmarTalibzade** [Facepunch/sbox-issues#4981]
### Describe the bug

Game view is not updating when running in editor/designer mode. This only happens when Scene view is not visible. It works fine when they're displayed side-by-side.

Switching to Scene view and back to Game view updates it.

### To Reproduce

1. Add a Cube
2. Select a Cube and make sure you can modify its values via Inspector
3. Ensure that Scene view is hidden and the Game view is visible
4. Using the Inspector, manipulate the transform values

### Expected behavior

Game view should reflect transform changes of the Cube (but it doesn't)

### Media/Files

Shows the bug and its workarounds

https://github.com/Facepunch/sbox-issues/assets/8478519/de1a9978-dd86-4e8a-a0d6-e29e5d2d40be

### Additional context

This only happens outside of Play mode.

**Comment by cr4yz** [comment]
Fixed with https://github.com/Facepunch/sbox/commit/d88721d92128f6e29ba1457e0c1a32c6b9fd120b
