### ISSUE TITLE
Clientside GameObjects

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4982]
### For?

S&Box

### What can't you do?

I noticed that if you spawn a GameObject without calling NetworkSpawn on it, it will still get sent to players who join, even though it's not "networked".

Similarly, if you put objects in your scene that aren't networked, they will still get sent to joining players. For example, all of this will get sent to anyone who joins, even though networking is not enabled.

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/4dfc1f45-4671-40b5-806e-177e3ec789e6)

I feel like there should be some way of having objects that are meant to be clientside only?

One area where this is causing me trouble is view models and the GUI. I have a host, who spawns their own view model and GUI. E.g:

```
private void CreateHUD()
{
	NetworkingHelpers.AssertOurPlayer( this );

	var hudObject = new GameObject();
	hudObject.Name = "GUI";
	hudObject.Components.Create<ScreenPanel>();
	hudObject.Components.Create<GUIMaster>();
}
```

Even though it's not spawned on the network, whenever a player joins, they will also receive this object, meaning they end up with two GUIs and two view models. Maybe I could just delete them locally? But I feel like they should never have to get sent in the first place.

### How would you like it to work?

IMO I think disabling networking here should completely stop the object from even being sent.

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/8ae4ae86-0df2-434c-98f3-404e19209bfd)

### What have you tried?

Not much...

**Comment by garrynewman** [comment]
This isn't going to happen. We want it so when players join a game, they get the whole scene sent to them, so everyone has the same scene.

You can mark GameObjects to never send using GameObject.Flags (https://asset.party/api/Sandbox.GameObjectFlags/NotNetworked)

**Comment by anthonysharpy** [comment]
That's fair enough, didn't know about GameObject.Flags, that does what I wanted anyways so I'm happy

It's a useful feature IMO so could be worth popping it in the documentation at some point, especially in networking section
