### ISSUE TITLE
GameResources do not save between sessions

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4985]
### Describe the bug

GameResources do not save between sessions.

### To Reproduce

1. Create a GameResource.
2. Try to save it.
3. Observe it not saving when you reload your client.

### Expected behavior

It should be saving.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/d2a94906-8847-458d-8ef5-b95b7b412379

### Additional context

Here is my GameResource
`[GameResource( "Weapon", "weapon", "A item game resource", Icon = "track_changes" ) ]
public sealed class WeaponData : GameResource
{
    public string Name { get; set; } = "MP5";
    public int MaxAmmo { get; set; } = 32;
    public int Ammo { get; set; }
	public int Damage { get; set; } = 50;
    public float FireRate { get; set; } = 0.1f;
	public Model WeaponModel { get; set; }
	public SoundEvent ShootSound { get; set; }
}`

**Comment by Retroeer** [comment]
Most likely related to #4956

**Comment by DevulTj** [comment]
Check the uncompiled source file, does it change? 

Also, try again, while fixing something else, I might've coincidentally addressed this.

**Comment by Nolankicks** [comment]
> Check the uncompiled source file, does it change?
> 
> Also, try again, while fixing something else, I might've coincidentally addressed this.

Still looks like him getting the issue. The source file doesn't save when I change it in the editor.

**Comment by DevulTj** [comment]
Try when the next build hits, that should solve your problems. Make sure you are hitting save.

**Comment by chrisspieler** [comment]
I'm getting the same issue, even after downloading the new build.
https://github.com/Facepunch/sbox-issues/assets/8889285/a1de965f-45ab-4bef-a900-ea49edcc9693

**Comment by Nolankicks** [comment]
> Try when the next build hits, that should solve your problems. Make sure you are hitting save.

Seems to be working after the newest build, thanks Tony.

**Comment by chrisspieler** [comment]
I guess my issue isn't exactly the same. Should I make a new issue?

**Comment by DevulTj** [comment]
yeah please
