### ISSUE TITLE
Razor panels don't seem to update every frame

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#4986]
### Describe the bug

I have a razor panel with a screen panel component that I'm using to act as a world panel so it can render in front of everything, though it seems like the panel isnt updating every frame as currently moving the camera around causes the panels position to become lag behind 

### To Reproduce

I've made an example repository with a basic scene setup to demonstrate the issue ("code/ui/HudMarker.razor" )
https://github.com/DeltaDesigns/marker_lag_example

### Expected behavior

I think the best solution would to give the option to allow world panels to render on top of everything, but having the 'lag' on a normal screen panel would be nice also

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/50308149/80027379-fa73-421b-a0cf-d97be36444b6

**Comment by andy013** [comment]
Try using OnPreRender() instead of OnUpdate()

**Comment by DeltaDesigns** [comment]
> Try using OnPreRender() instead of OnUpdate()

I've tried that also, doesn't seem to help

**Comment by CarsonKompon** [comment]
I got around this by adding a 0.01s transition to the ui element:
```
transition: all 0.01s linear;
```

**Comment by DeltaDesigns** [comment]
> I got around this by adding a 0.01s transition to the ui element:
> 
> ```
> transition: all 0.01s linear;
> ```

This doesn't seem to do anything either. I put the transition on the root class, unless I put it in the wrong place?

**Comment by CarsonKompon** [comment]
The transition should be on the thing that's moving

**Comment by DeltaDesigns** [comment]
> The transition should be on the thing that's moving

I've tried it on every class, nothing

**Comment by Retroeer** [comment]
i was hoping this would get fixed in-time for the jam but i guess i was wrong :(

**Comment by garrynewman** [comment]
I fixed this, but what you need to do us update the  position in PreRender. This is called after all the Updates, which means that it'll be updating the position AFTER the camera position is worked out - which is what you want.

```
    protected override void OnPreRender()
    {
        PositionAtWorld();
    }
```

**Comment by DeltaDesigns** [comment]
> I fixed this, but what you need to do us update the position in PreRender. This is called after all the Updates, which means that it'll be updating the position AFTER the camera position is worked out - which is what you want.
> 
> ```
>     protected override void OnPreRender()
>     {
>         PositionAtWorld();
>     }
> ```

Everything looks great now, love you Garry ❤️
