### ISSUE TITLE
Vulkan not working properly

### ISSUE THREAD

**Issue by osas319** [Facepunch/sbox-issues#4991]
### Describe the bug

Hello when i play s&box after like 3-5 minutes my gpu driver crash but its only happening on s&box. First i think i have problem on my pc but i see problem is in s&box vulkan update i installed old version on s&box when vulkan update doesnt launched and its working fine after testing 1 hour.

### To Reproduce

Fix vulkan.

### Expected behavior

The game shouldn't crash

### Additional context

I 'm running on Windows 11 My pc specs: CPU: AMD Ryzen 5 3600 6-Core Processor, GPU: RX5600XT, RAM: 32gb

**Comment by handsomematt** [comment]
What makes you say its a GPU driver crash? There are tons of changes since the Vulkan update.

Can you provide your log.txt and steamid64 https://docs.facepunch.com/s/sbox-dev/doc/reporting-errors-2OTPIafqCJ

**Comment by osas319** [comment]
2024/02/28 18:03:35.3948	[engine/Engine] SteamAPI_Init succeeded.  SteamID is [U:1:1086628939] (76561199046894667), AppID is 590830	
2024/02/28 18:03:35.4343	[engine/Steam] CSteam3Client::Activate succeeded.  SteamID is [U:1:1086628939] (76561199046894667), AppID is 590830	
2024/02/28 18:03:36.4579	[Generic] Trying to restore tools cookies from a backup...	
2024/02/28 18:03:36.4579	[Generic] Failed to load tools cookies from disk!	
2024/02/28 18:03:36.6314	[engine/RenderSystem] Couldn't find driver version for device 'ASUS Radeon RX 5600 XT'	
2024/02/28 18:03:36.6364	[engine/RenderSystem] Couldn't find driver version for device 'Microsoft Basic Render Driver'	
2024/02/28 18:03:36.6364	[engine/RenderSystem] Couldn't find driver version for device 'Microsoft Basic Render Driver'	
2024/02/28 18:03:38.2654	[Generic] Waiting for Web Auth Ticket..	
2024/02/28 18:03:38.2839	[engine/Engine] Console command or convar "package_list" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2839	[engine/Engine] Console command or convar "package_install" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2839	[engine/Engine] Console command or convar "package_unmount_tag" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "hotload_log" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "hotload_fast" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "interopsystem.status" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "interopsystem.dump" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "host" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "joinlobby" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "connect2" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "status2" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "disconnect2" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.2900	[engine/Engine] Console command or convar "reconnect" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.3094	[engine/Engine] Console command or convar "perf_time" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.3094	[engine/Engine] Console command or convar "vr_force_interleaved_projection" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.3094	[engine/Engine] Console command or convar "vr_predict" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.3094	[engine/Engine] Console command or convar "vr_use_predicted_hmd_tracking" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.3094	[engine/Engine] Console command or convar "vr_depth_submit" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:38.3094	[engine/Engine] Console command or convar "vr_gpu_flush_timer" is being ignored because it conflicts with a menu convar with the same name	
2024/02/28 18:03:39.1625	[engine/AssetSystem] AssetSystem pruned 299 stale assets	
2024/02/28 18:03:42.3629	[engine/AssetSystem] AssetSystem initialized in 3.31 seconds. [0.04 load, 0.07 scan, 3.18 dependencies, 0.01 save]	
2024/02/28 18:03:43.3014	[Generic] Took 5.0564607s to get steam auth ticket	
2024/02/28 18:03:43.9552	[Generic] Create Compiler `base`	
2024/02/28 18:03:43.9895	[Generic] Create Compiler `local.menu`	
2024/02/28 18:03:43.9978	[Generic] Create Compiler `toolbase`	
2024/02/28 18:03:43.9978	[Generic] Create Compiler `local.entityprefabed`	
2024/02/28 18:03:43.9978	[Generic] Create Compiler `local.shadergraph`	
2024/02/28 18:03:49.8103	[engine/ToolsStallMonitor] Stall detected.	
2024/02/28 18:04:40.8663	[Generic] Trying to restore local.map cookies from a backup...	
2024/02/28 18:04:40.8680	[Generic] Failed to load local.map cookies from disk!	
2024/02/28 18:04:40.8680	[Generic] Create Compiler `local.map`	
2024/02/28 18:04:55.0432	[GameMenu] Copying Shooter Game template to destination folder: c:/users/yigit/documents/s&box projects/my_shooter_game	
2024/02/28 18:04:55.0551	[GameMenu] OK	
2024/02/28 18:04:55.0551	[Generic] Create Compiler `local.my_shooter_game`	
2024/02/28 18:04:55.2654	[Generic] Trying to restore local.my_shooter_game cookies from a backup...	
2024/02/28 18:04:55.2654	[Generic] Failed to load local.my_shooter_game cookies from disk!	
2024/02/28 18:04:55.6756	[GameMenu] Couldn't find menu in [null assembly] - using fallback	
2024/02/28 18:05:02.0509	[engine/Console] Loading map "facepunch.construct23"	
2024/02/28 18:05:02.2854	[Generic] Downloading 283 files (683.97mb)..	
2024/02/28 18:06:28.5649	[Generic] ..done in 86.28s	
2024/02/28 18:06:28.9416	[engine/Server] SV:  maxplayers set to 8	
2024/02/28 18:06:29.2123	[ServerDll] CurrentGamemode: My Shooter Game	
2024/02/28 18:06:29.3821	[ServerDll] Found 1 GameManagers	
2024/02/28 18:06:29.3821	[ServerDll] 1. MyGame.MyGame (package.local.my_shooter_game, Version=0.0.107.0, Culture=neutral, PublicKeyToken=null)	
2024/02/28 18:06:30.3579	[engine/Engine] WARNING: resource 'maps/construct23.vmap' is an unrecognized resource type!	
2024/02/28 18:06:31.1166	[engine/ResourceSystem] Reloaded 237 resident symlinked resources in 751ms	
2024/02/28 18:06:31.3862	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.	
2024/02/28 18:06:33.5511	[engine/Entity System] ExecuteQueuedCreation() took 520152us [ Spawned: 164, Activated 164, PostDataUpdate: 0, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]	
2024/02/28 18:06:33.6109	[Server] "MOSTERCOCKLORD2000TR" has joined the game	
2024/02/28 18:06:33.7079	[engine/ResourceSystem] Error loading resource file "decal_renderer.shader_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/28 18:06:33.8442	[engine/Entity System] ExecuteQueuedCreation() took 231080us [ Spawned: 1, Activated 1, PostDataUpdate: 0, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]	
2024/02/28 18:06:34.2561	[engine/Entity System] ExecuteQueuedCreation() took 148750us [ Spawned: 135, Activated 0, PostDataUpdate: 135, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]	
2024/02/28 18:06:34.4034	[engine/Engine] Building cubemap #26	
2024/02/28 18:06:34.4034	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:34.4034	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:35.6346	[engine/Engine] Building cubemap #25	
2024/02/28 18:06:35.6346	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:35.6346	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:35.7814	[engine/Engine] Building cubemap #24	
2024/02/28 18:06:35.7814	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:35.7814	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:35.9448	[engine/Engine] Building cubemap #23	
2024/02/28 18:06:35.9458	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:35.9458	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:36.0423	[engine/Engine] Building cubemap #22	
2024/02/28 18:06:36.0423	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:36.0423	[engine/Client] MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false	
2024/02/28 18:06:36.4731	[engine/Engine] Building cubemap #21	
2024/02/28 18:06:36.5621	[engine/Engine] Building cubemap #20	
2024/02/28 18:06:36.6535	[engine/Engine] Building cubemap #19	
2024/02/28 18:06:36.7438	[engine/Engine] Building cubemap #18	
2024/02/28 18:06:36.8330	[engine/Engine] Building cubemap #17	
2024/02/28 18:06:36.9232	[engine/Engine] Building cubemap #16	
2024/02/28 18:06:37.0071	[engine/Engine] Building cubemap #15	
2024/02/28 18:06:37.0992	[engine/Engine] Building cubemap #14	
2024/02/28 18:06:37.2023	[engine/Engine] Building cubemap #13	
2024/02/28 18:06:37.2984	[engine/Engine] Building cubemap #12	
2024/02/28 18:06:37.4633	[engine/Engine] Building cubemap #11	
2024/02/28 18:06:37.5782	[engine/Engine] Building cubemap #10	
2024/02/28 18:06:37.6829	[engine/Engine] Building cubemap #9	
2024/02/28 18:06:37.7848	[engine/Engine] Building cubemap #8	
2024/02/28 18:06:37.8734	[engine/Engine] Building cubemap #7	
2024/02/28 18:06:38.0091	[engine/Engine] Building cubemap #6	
2024/02/28 18:06:38.1040	[engine/Engine] Building cubemap #5	
2024/02/28 18:06:38.1930	[engine/Engine] Building cubemap #4	
2024/02/28 18:06:38.2789	[engine/Engine] Building cubemap #3	
2024/02/28 18:06:38.3672	[engine/Engine] Building cubemap #2	
2024/02/28 18:06:38.4539	[engine/Engine] Building cubemap #1	
2024/02/28 18:06:38.5431	[engine/Engine] Building cubemap #0	
2024/02/28 18:06:41.2493	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.	
2024/02/28 18:06:41.4904	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.	
2024/02/28 18:06:41.7437	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.	
2024/02/28 18:06:42.0068	[engine/Engine] CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.	
2024/02/28 18:09:35.4761	[Generic] Trying to restore content.project cookies from a backup...	
2024/02/28 18:09:35.4768	[Generic] Failed to load content.project cookies from disk!	
2024/02/28 18:09:35.6826	[engine/Client] CL:  disconnect	
2024/02/28 18:09:35.7529	[engine/Client] CL:  Server disconnected: 2: NETWORK_DISCONNECT_DISCONNECT_BY_USER	
2024/02/28 18:09:35.7529	[engine/Server] SV:  Server shutting down: NETWORK_DISCONNECT_DISCONNECT_BY_USER (2)	
2024/02/28 18:09:35.7529	[engine/Server] SV:  Disconnect client 'MOSTERCOCKLORD2000TR' from server(1): NETWORK_DISCONNECT_SHUTDOWN	
2024/02/28 18:09:35.7710	[engine/Client] CL:  Disconnecting from server: NETWORK_DISCONNECT_DISCONNECT_BY_USER	
2024/02/28 18:09:39.9890	[Generic] EngineLoop::Exiting	
2024/02/28 18:09:39.9950	[engine/ToolFramework2] Shutting down Qt windows.............	
2024/02/28 18:09:39.9950	[engine/Engine] Source2Shutdown	
2024/02/28 18:09:39.9950	[engine/Engine] ShutdownSource2Logging

**Comment by handsomematt** [comment]
That's a log of an old version of the game running on DirectX?

**Comment by osas319** [comment]
sorry I accidentally posted the wrong log

**Comment by osas319** [comment]
[Log.25.log](https://github.com/Facepunch/sbox-issues/files/14438105/Log.25.log)

**Comment by handsomematt** [comment]
Is this a specific game/map this is happening on? Are you on the latest AMD drivers?

**Comment by osas319** [comment]
I am using latest AMD drivers and its happening on all games.

**Comment by osas319** [comment]
Its crashing on menu too. I opened s&box wait some minutes in menu doing nothing and again amd drivers crashed.

**Comment by handsomematt** [comment]
I will try to investigate on an rdna1 gpu, in the mean while [can you run vulkaninfo](https://nvidia.custhelp.com/app/answers/detail/a_id/5429/~/running-vulkan-info) and post the results here.

**Comment by osas319** [comment]
[VULKAN İNFO.txt](https://github.com/Facepunch/sbox-issues/files/14462332/VULKAN.INFO.txt)

**Comment by handsomematt** [comment]
Is it Riva doing this, can you disable it

**Comment by osas319** [comment]
What is Riva ? Where can i disable it ?

**Comment by handsomematt** [comment]
Rivatu﻿ner Statistics Server / MSI Afterburner

**Comment by osas319** [comment]
I uninstalled Rivatuner and problem is fixed thank you for helping.

**Comment by andy013** [comment]
For what it's worth, I have RivaTuner installed and have no issues in s&box. If you set the application detection level to something below High then it won't load the overlay in s&box.
