### ISSUE TITLE
GameResource GameObject prefab property is empty after loading editor

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4992]
### Describe the bug

I've found a case where a custom GameResource has a GameObject Property that will not be populated in the inspector or set in-game after the S&box editor is loaded. Even though the prefab path appears to have been serialized to disk, it somehow gets ignored, and the editor acts like there was no value.

### To Reproduce

The video attached in media/files contains the repro steps, but also demonstrates that clicking and dragging the prefab on to the GameResource _does_ affect the game despite the GameResource file on disk not changing at all.

1. Clone this repo (at this commit): https://github.com/chrisspieler/sbox-space-game/tree/2bd851d434065f4373f5dcb7c8bcbd4bad7af6fa
2. In the S&box editor, open this repo's S&box project
3. In the Asset Browser, click on `data/cargo/iron_ore.cargo`
4. In the inspector, see that the "Pickup Prefab" property shows "None (GameObject)"
5. Open `data/cargo/iron_ore.cargo` in a text editor and see that the property _does_ have a value.
6. In the S&box editor, click and drag `data/cargo/iron_ore_pickup.prefab` on to the aforementioned Pickup Prefab property.
7. Save and recompile `data/cargo/iron_ore.cargo`
8. View that GameResource in your text editor again, and see that nothing has changed
9. Close the S&box editor
10. Repeat steps 2 - 4
11. See that saving and compiling this GameResource has done nothing

### Expected behavior

When viewing the GameResource in the S&box editor inspector, the prefab specified in its uncompiled file should appear as the value for Pickup Prefab. After setting Pickup Prefab to a prefab then saving and recompiling the GameResource and restarting the editor, the correct value for Pickup Prefab should be shown in the inspector.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/8889285/24bc5e85-0f7f-4231-a79f-34d99c6541b2

**Comment by drongood12** [comment]
#https://github.com/Facepunch/sbox-issues/issues/4956

**Comment by badandbest** [comment]
Since #4956 was fixed, wouldn't this be fixed too?
