### ISSUE TITLE
LODS models do not work if the models are placed in a hammer

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#4994]
### Describe the bug

LODS models do not work if the models are placed in a hammer

two models. left im put on scene, right im put in hummer
https://github.com/Facepunch/sbox-issues/assets/86604770/cb21a40b-b312-4648-a3b9-d987f1371750

### To Reproduce

https://github.com/Facepunch/sbox-issues/assets/86604770/0fd961a5-7285-4bc1-84a3-3512493054aa

![Screenshot (153)](https://github.com/Facepunch/sbox-issues/assets/86604770/a1c31ac3-4b33-410c-9a85-f439ae621ceb)

https://github.com/Facepunch/sbox-issues/assets/86604770/8ddc6611-2c7c-4477-96b1-d66d907e7c38

### Expected behavior

LODS should work

### Additional context

I don’t know how relevant this is if a hammer replacement is already being created

**Comment by somethink000** [comment]
> It looks like prop_static has a fixed LOD level that is set under the rendering properties in Hammer.
> 
> ![Screenshot 2024-02-28 185929](https://private-user-images.githubusercontent.com/10728824/308680967-7f5176ba-0a52-4e23-ac61-a7b48afc9752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDc5NTcsIm5iZiI6MTcwOTE0NzY1NywicGF0aCI6Ii8xMDcyODgyNC8zMDg2ODA5NjctN2Y1MTc2YmEtMGE1Mi00ZTIzLWFjNjEtYTdiNDhhZmM5NzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE5MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTJjMmFkM2NiMGYwYmQzYWQxZGJlN2JkMzU4MTQ0ODczMThkZmY0YmY2MjM2ZGQ5YTM5YjUxZWFiMzAyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNGGoxKYSk72lpwzTNfLCEaO2uQLMBv1WfrIlxbAeNQ)
> 
> Setting it to prop_physics seems to work as expected.

yep im set this on -1 and lods works but im think this should be by default

**Comment by somethink000** [comment]
How exactly is the LODS distance calculated when switching to another resolution? Is it different?

https://github.com/Facepunch/sbox-issues/assets/86604770/49dfb8c0-7e6a-4f5e-b5ef-9a1b601cbeb4

**Comment by handsomematt** [comment]
prop_static are baked into maps
