### ISSUE TITLE
Have the ability to make your networking server private in the dev client

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#4996]
### For?

S&Box

### What can't you do?

When I have a server open in from the dev client people can join it, but sometimes I don't want that. Sometimes it just breaks things, I think this would be less of an issue if you fix issue #4466, I find this to be the most annoying bug, You have to re-upload your game each time you want to test something with another client. So even if I want them in my game, I have to re-upload it so as not to get tons of errors. (pls fix)

### How would you like it to work?

I would like it to be a toggle setting when you start your server, or have it in preferences.

### What have you tried?

Yep, there is no way to do it.

**Comment by handsomematt** [comment]
#5089
