### ISSUE TITLE
Adding multiple of the same component type in-editor requires inspector refresh

### ISSUE THREAD

**Issue by rlenhub** [Facepunch/sbox-issues#4998]
### Describe the bug

When adding more than one of a given component type, the new component will appear to have the same properties copied to it as the top component of it's type. If the properties are changed in either the new or the first, the changes will be applied to the first component. This problem goes away as soon as the inspector is switched to another object and back, and the new component will have it's default values, however any changes applied to the first component remain.

### To Reproduce

1. Create a GameObject in the editor
2. Add any component to it
3. Modify any value
4. Add another of the same type of component

### Expected behavior

The expected behavior is that the new component starts with it's default values and is immediately editable.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/33167901/1c1de2fc-bedc-411a-91b9-c982f4c44530

**Comment by handsomematt** [comment]
pretty much #4710 resolved once we add component ids
