### ISSUE TITLE
background-size doesn't repeat properly when using auto and a percentage

### ISSUE THREAD

**Issue by rtm516** [Facepunch/sbox-issues#5]
When setting something like `background-size: auto 100%;` on an element with a background image it seems to tile strange and not be displayed how it should.
Comparison shot of the same code, web on the left sandbox on the right
![image](https://user-images.githubusercontent.com/5401186/115607160-8acb0d80-a2dc-11eb-874f-c38359138878.png)
https://jsfiddle.net/e8w5ytrq/4/ is the web version

**Comment by garrynewman** [comment]
I don't think we handle the auto parameter in backgrounds, I'll fix that.
