### ISSUE TITLE
My game has itself as a dependency, downloading files that override local ones on project launch

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5001]
### Describe the bug

Somehow my project has itself as a dependency, which is probably the reason why sometimes folders are just empty in the asset browser. It downloads old compiled files into the .source2/cloud directory.

It spams `Was unable to determine package for x, deleting` on project launch, and i briefly see "downloading org.projectname" or similar with the current project on load.

### To Reproduce

I don't know how this happened. In some of my scenes, my own "org.projectname" can be seen sometimes in the references.

### Expected behavior

A project should not be able to break itself by downloading an older version of itself.

**Comment by DevulTj** [comment]
Need a bit of info on this. Is this a direct package reference in your .sbproj file, or do you have a Resource that's referencing your game's package?

1. (Check .sbproj "PackageReferences")
2. (Check your resource's "__references")

**Comment by MrBrax** [comment]
I had this issue when developing terry target, it got added to scene file resources. I'm not sure if it has happened in a while now, will have to check git changes.
