### ISSUE TITLE
Installing map from Assets Browser Cloud not appearing in project

### ISSUE THREAD

**Issue by Sakiskid** [Facepunch/sbox-issues#5007]
### Describe the bug

When trying to Install map from cloud asset browser, nothing happens. There is no error detailing why the map isn't importing. The map does not import or appear in local project files. 

The only feedback is that the Install button grays out for a few seconds.

### To Reproduce

1. New project
2. In Assets Browser, go to cloud > everything
3. Sort by "maps", search for "Flat Plane" (voximity.flat_plane)
4. Right click and "Install"

### Expected behavior

Map should appear in local project files, or an error should throw.

### Media/Files

![zQN0X2F](https://github.com/Facepunch/sbox-issues/assets/33964795/dbc9a447-91d8-4417-abbc-2bf33476d7b6)

**Comment by DrakeFruit** [comment]
that's not how the download button works at all 😂

**Comment by Sakiskid** [comment]
This is specifically in reference to the maps, I don't believe they go anywhere at all, not even local storage.

**Comment by MrBrax** [comment]
maps download and mount automatically in the map instance component

**Comment by handsomematt** [comment]
Removed the install option for maps, they're not meant to be used like this
