### ISSUE TITLE
MusicPlayer DistanceMin and Max

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#5010]
### For?

S&Box

### What can't you do?

We used to have DistanceMin and Max for the MusicPlayer class to adjust the distance you could hear it from.

### How would you like it to work?

The same way it used to.

### What have you tried?

Using low values of volume but it feels like a bad workaround and doesn't actually limit the hearing distance at all.

**Comment by aylaylay** [comment]
I've added Distance/Falloff to music player to match sound handle
