### ISSUE TITLE
The option to reverse the depth buffer.

### ISSUE THREAD

**Issue by rbwldrf** [Facepunch/sbox-issues#5012]
### For?

S&Box

### What can't you do?

I've been implementing absurdly large objects with absurdly fine details into the game and have been trying to find ways to reduce the z-fighting, and I haven't been able to implement a solution so far. I figured other people might want to do the same thing, be it for space sims or open-world games or just general experimentation, especially now that the bounds of the Source 2 engine have been removed, so I thought I'd request it as a feature.

### How would you like it to work?

The basic idea, should you choose to make it optional (there are a couple of benefits to not hard-coding it in) would be to have it be accessible via a settable property (reverseZ) in the Camera class, along with an option to enable/disable it in the inspector. 

Once enabled, the depth range will be multiplied with a matrix with these values:

```
 0,  0,  0,  0,
 0,  0,  0,  0, 
 0,  0, -1,  0,
 0,  0,  1,  0
```

the depth clear value would be `0.0f` and the depth comparison will be set to `Greater` to account for the reversed Z-buffer.

> _(I'm pretty sure this would be the procedure on the Vulkan pipeline, I'm just going off the WebGPU sample listed below.)_

In doing this, we increase the accuracy of the Z-buffer by a 125 its original size, as **99.21%** of the values that can be stored in-between 0 and 1 in a 32-bit float (total of 1065353216 values) are within the lower half of the range (1056964608 values), as opposed to the **0.79%** provided by the upper half (8388608 values). ([Source](https://tomhultonharrop.com/mathematics/graphics/2023/08/06/reverse-z.html#:~:text=the%20total%20range%20between%200.0%20and%201.0%2C%20only%20approximately%200.79%25%20of%20all%20representable%20values%20are%20between%200.5%20and%201.0%2C%20with%20a%20staggering%2099.21%25%20between%200.0%20and%200.5))

An example of a reverse depth buffer working as intended can be found [here](https://webgpu.github.io/webgpu-samples/samples/reversedZ).

### What have you tried?

I did try implementing this myself in the Shader Graph, but didn't quite get the expected result.

**Comment by handsomematt** [comment]
We've got an internal issue to reverse the z depth buffer - this absolutely wouldn't be a toggle.
