### ISSUE TITLE
Local assets break map asset.party uploading

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#5013]
### Describe the bug

An uploaded map will have parts of or all of its custom local content references broken when restarting the editor. Re-Publishing the map will update the backend to remove the references, despite them still being used by the map.

### To Reproduce

1. Create a barebones map using a custom material and compile it, fast compile is fine
![sbox-dev_5LMEN302Sl](https://github.com/Facepunch/sbox-issues/assets/12602100/c87c1215-517d-4429-9667-d5edc615369b)

2. Upload the map to asset party, note that the custom material gets picked up and is uploaded
![sbox-dev_7NMJII1hvp](https://github.com/Facepunch/sbox-issues/assets/12602100/29f5f27f-5707-44e8-a595-a0db96b1d03c)

3. Restart your editor, open hammer. Note the missing asset dialogue and no assets in the `@inmap` asset browser.
![sbox-dev_X4UfcJ80vo](https://github.com/Facepunch/sbox-issues/assets/12602100/776c173d-aa6a-4dbd-acdd-d269e40ec7fc)

4. Re-Publish the map, this will remove the custom asset from the backend version.
![sbox-dev_3BxB2pPZeH](https://github.com/Facepunch/sbox-issues/assets/12602100/d2ca0f72-b256-4539-b3c0-16cd5a2c7cc8)

### Expected behavior

Mixing core, cloud and local project content should work with asset.party uploaded maps.

From doing a bunch of tests around this issue I have found that using cloud assets in general seems to mess with local content and maps. The `@inmap` asset browser would only show core and asset.party assets, but also fail to load them occassionally... removing the asset.party materials brought back part of the local assets in `@inmap`, but didn't fix the uploading issue entirely. Using mostly asset party assets in a map seems to work relatively well from asking around however.

### Media/Files

The initial upload will work fine with custom assets, also when used in a scene through a map instance and the backend ident. 
![sbox-dev_6r12n1AT4e](https://github.com/Facepunch/sbox-issues/assets/12602100/e5215f71-4018-4238-a0da-d755a5cfd407)

**Comment by Retroeer** [comment]
Yeah this is starting to blow, trying to get people to test a map only to have to have them open the map in hammer just to get the mats is just inconvenient

**Comment by handsomematt** [comment]
I reverted all recent changes to the asset system and that didn't fix it. Will investigate more tomorrow

**Comment by handsomematt** [comment]
I've pushed a small change to the asset inspector, can you see if your missing assets appear in red on there when selecting the map asset? It'd help a lot with debugging this

**Comment by MrBrax** [comment]
<img width="258" alt="1709912623480" src="https://github.com/Facepunch/sbox-issues/assets/1517911/b5239bfb-84ac-48c4-b680-212c260c1afd">

mine does

**Comment by handsomematt** [comment]
Nasty fucker. Give the latest build a go

**Comment by MrBrax** [comment]
<img width="270" alt="1709920306056" src="https://github.com/Facepunch/sbox-issues/assets/1517911/5a1c3d79-73a0-407b-b0ae-0d463ea922ce">

works for me

**Comment by KaesarZZ** [comment]
Yeah fixed, good one matt

**Comment by eagleonedevteam** [comment]
Not working when uploaded fully

Try my map

eagleone.colosseum

![image](https://github.com/Facepunch/sbox-issues/assets/70182442/984d230c-f247-40f0-a3c6-790e4e735784)

**Comment by eagleonedevteam** [comment]
IT WORKS BEAUTIFULLY NOW THANK YOU MATT <3<3<3

**Comment by MrBrax** [comment]
does the actual playing of uploaded maps work for anyone else without issues? i'm getting pink and black checkerboards on some materials

**Comment by DoctorGurke** [comment]
Is it metallic surfaces? Could just be cubemaps being broken too

**Comment by MrBrax** [comment]
<img width="285" alt="1710093288313" src="https://github.com/Facepunch/sbox-issues/assets/1517911/a4b22ffd-e003-4173-82a0-1cfdef26d923">

nope, some cloud textures turn up as errors, they're not mine

**Comment by MrBrax** [comment]
<img width="265" alt="1710097291662" src="https://github.com/Facepunch/sbox-issues/assets/1517911/c079e2d5-323f-465d-9dad-af8f9d67abae">

deleted all the download caches, doesn't seem like the game auto downloads map references
