### ISSUE TITLE
Saving a Prefab gaslights the Editor into thinking it's a new Prefab

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5014]
### Describe the bug

If you save a prefab, and then try to open that prefab, a new prefab tab opens instead of taking you back to that original prefab tab. 
ex: I have a player prefab tab, i save my player, i re-open the player prefab, it opens a new tab instead of re-using the old one.
If this stacks you'll eventually wound up with 4 different player prefabs each with conflicting versions. 

### To Reproduce

1. Create a prefab
2. Save the prefab
3. Change the prefab in some way
4. Save it again
5. Attempt to open it
6. Congratulations, you've discovered an infinite prefab glitch! 

### Expected behavior

Trying to re-open the same prefab should bring you back to the original prefab rather than duplicating it. 

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/44037603/59c9b084-9320-4748-adca-2d5eeeab4153

**Comment by CarsonKompon** [comment]
This doesn't seem to happen with the new scene tabs.
