### ISSUE TITLE
Opening a cloned Prefab via the Hierarchy (or Inspector) 

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5015]
### For?

S&Box

### What can't you do?

Currently a cloned Prefab loses all connection of ever being a prefab, thus not letting you see the "Open X" button in the hierarchy a normally dragged in Prefab would have.

### How would you like it to work?

Perhaps a cloned Prefab could keep a reference of it's origin, and let you open it that way? 
(As a QoL Change: Add a "Open Prefab" button the right click menu on a GameObject in a Scene) 

### What have you tried?

Lying in the victory position 🦅

**Comment by garrynewman** [comment]
Yep this is the intention. The prefab breaking was to get around a network serialization problem IIRC.

**Comment by Retroeer** [comment]
I don't even remember what this was about, but this is probably fixed
