### ISSUE TITLE
Referenced GameObjects in a GameResource do not automatically update

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5017]
### Describe the bug

If you change anything about a GameObject that's referenced in a GameResource, and then use that GameResource to clone the reference GameObject, it uses the old version rather than the newly updated one. 

### To Reproduce

1. Make a GameObject reference in a GameResource
2. Change that GameObject reference (IE: disable the model renderer)
3. Save it
4. Clone it from GameResource
5. Observe as it still has a model renderer. 

### Expected behavior

The GameResource should automatically get the update reference.

**Comment by handsomematt** [comment]
A GameResource should not be allowed to reference a GameObject, unless you mean a prefab?

**Comment by Retroeer** [comment]
> A GameResource should not be allowed to reference a GameObject, unless you mean a prefab?

I'm using a Prefab but I'm using it under the GameObject class, similar to how the Network Helper uses GameObject but accepts a prefab. Rather than a Prefab under the Prefab class.

**Comment by Retroeer** [comment]
this is seemingly resolved?
