### ISSUE TITLE
Colliders inherit Scale from Parent GameObject

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5018]
### Describe the bug

I'm actually unsure if this is intentional, but I'm putting it here.

If you have a Parent with a scale of 0.50, 0.50, 0.50 and then have a child with a collider, the collider inherits the scale.
This, however, appears to conflict with Model Renderer's way of handling the parent scale, which instead chooses to ignore it. 

### To Reproduce

1. Have a Parent GameObject with a non-default scale
2. Have a Collider Child
3. Collider inherits the Scale 

### Expected behavior

The Collider should instead ignore the Parent's Scale? Or maybe the Model Renderer should be changed to inherit the Parent's scale? I'm unsure.

**Comment by garrynewman** [comment]
Model Renderer should inherit scale, are you saying it doesn't?

**Comment by Retroeer** [comment]
> Model Renderer should inherit scale, are you saying it doesn't?

It doesn't inherit the position either, if that's the actual issue feel free to change the title

**Comment by garrynewman** [comment]
Yeah it should definitely inherit size and scale
