### ISSUE TITLE
Position/Rotation/Scale local values should have an option of displaying their World counterpart. 

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5019]
### For?

S&Box

### What can't you do?

Properly get the World Position/Rotation/Scale of a Child GameObject. 

### How would you like it to work?

The Editor already has a button for "Global Space", perhaps toggling it on will show World values while off shows Local? Or perhaps a new button entirely. 

### What have you tried?

Nothing, there's no real way of getting the global values. 

### Additional context

This would be pretty handy with getting a Child to 0, 0, 0 in World space, or resetting scale to 1, 1, 1.

**Comment by garrynewman** [comment]
Right click option on the gameobject header to enable showing world transform too?
