### ISSUE TITLE
Right Clicking Position/Rotation/Scale text of a GameObject doesn't give the "Copy Value" prompt

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5020]
### Describe the bug

Right Clicking the Text of these properties does not give the prompt, however, clicking slightly to the right of them does. 

### To Reproduce

1. Right Click the Text
2. Observe as the prompt doesn't appear

### Expected behavior

The Prompt should appear as long as you're right clicking in the general "box" of the property. 

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/44037603/96a9d91f-843a-4769-b0e3-97a223efca43

**Comment by DevulTj** [comment]
This was added at some point in the last 4 months
