### ISSUE TITLE
Add Vector3.Direction

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5026]
### For?

S&Box

### What can't you do?

It's annoying to keep having to write `(to - from).Normal;` each time I want to get a direction from one position vector to another.

### How would you like it to work?

It should behave like this.
```csharp
public static Vector3 Direction( this Vector3 from, Vector3 to )
{
	return (to - from).Normal;
}
```
So I can just write
```csharp
var direction = Transform.Position.Direction( Other.Transform.Position );
```
Instead of
```csharp
var direction = ( Other.Transform.Position - Transform.Position ).Normal;
```
They are each about the same amount of typing, but one is far more intuitive than the other. The math feels backwards to me because I often think "I'd like a direction from here to there", but the math has me writing "there minus here". Even though I've gotten a direction vector this way _a lot_, it still makes my brain stumble a little each time.

### What have you tried?

Just doing it the usual way.

**Comment by garrynewman** [comment]
I think 

```
Vector3.Direction( a, b );
```

makes sense, but 

```
Transform.Position.Direction( Other.Transform.Position );
```

is a bit confusing

**Comment by garrynewman** [comment]
```[tasklist]
### Tasks
- [ ] Add `Vector3.Direction( from, to );` static - `(to - from).Normal;`
```
