### ISSUE TITLE
Audio Mixer System

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#5029]
We've taken over the audio system, and can do whatever we want now. We have Steam Audio with occlusion and dynamic reflections, but there is more work to do.

I'm making a list here, mainly for myself, so everyone knows what's planned to avoid making a bunch of duplicate issues.
```[tasklist]
### Steam Audio
- [x] Allow turning off Steam Audio reflections
- [x] Process reflections better (this can be done in a thread, over multiple frames, with some tricks)
- [ ] Allow further configuration of reflections
- [ ] Allow further configuration of direct effects (occlusion, transmission, distance attenuation)
- [x] Customizable tracing
```

```[tasklist]
### Mixers
- [x] Allow saving mixer changes to project
- [x] Allow creating alternate mixers
- [x] Allow adding processors to mixers
- [x] Allow removing processors from mixers
- [x] Allow deleting mixers
- [ ] Add more processors
- [ ] Allow directing output from a mixer to another mixer
- [ ] Solo and Mute should work
- [ ] Allow selection of mixer in Components
```

**Comment by MrBrax** [comment]
it will only be a matter of time until someone ports soundgoodizer to the mixer

**Comment by MrBrax** [comment]
on a serious note, audio seems pretty broken. previews have a ton of reverb and when going into the game in the editor all audio stops working

**Comment by garrynewman** [comment]
So, quick update on Steam Audio before I take the next steps.

# Occlusion

I'm gonna move this to our own system, since it's relatively simple, and the current one does a couple of things I don't like.

# Transmission

I've tweaked this a bit, but I think we need to offer more control over how transparent walls are, for which sounds.

# Reflection 

On release the performance was terrible, so I disabled it. Since then I've tweaked performance and fixed a couple of bugs. I'm still not super happy with the effects we're getting from it.

We're currently gathering reflection from the listener position, which is more efficient since it only has to work out reflection once. The issue is that if a sound is in front of you, and an echoey room is on your left, you'll hear the sound coming from the echoey room.. which feels really odd to me.

So my next steps on this are to test reflection from each source, to see what kind of terrible performance that gets. Then I'll look at what kind of performance difference embree gives us vs our own tracer. If it's massively better I'll put in the work to switch to that, it it's not, then I'll put in the work to make our implementation work in a background thread.

**Comment by Gmod4phun** [comment]
Things like Mute and Solo on mixers still don't work. Should we make new issues for those?
