### ISSUE TITLE
multi ultra door parrent bug 

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#503]
**Describe the bug**

All unnamed doors are now parrented :3 watch the video to understand everything

After Update:

https://www.youtube.com/watch?v=a4aTB1eiSSs

Before the update:

https://youtu.be/vBUPdu4Pn7Y?t=37

**To Reproduce**

1. Create many unnamed doors 
2. Open one door
4. See bug

**Comment by gabengaGamer** [comment]
And also all doors now have common output / input

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
