### ISSUE TITLE
WorldInput components

### ISSUE THREAD

**Issue by Guilhem-Pech** [Facepunch/sbox-issues#5031]
### For?

S&Box

### What can't you do?

Maybe I missed something but I can't interact with buttons or panel the same way if its a world panel or a screen panel 

### How would you like it to work?

I want to interact with world UI, be able to have UI buttons on them for example

We could:
  - Have a simulated mouse pos at the center of the screen if not visible
  - Have a simple function that make mouse visible (and consume the input) if we "focus" the panel

Have a simple way to display a cursor on the panel?

![image](https://github.com/Facepunch/sbox-issues/assets/15714248/c188ac49-d990-4f23-9234-77e980f554d9)

### What have you tried?

Made a simple razor file with a button in it 
Enable pointer events, works if its a screen panel but 0 effect if world

**Comment by MrBrax** [comment]
this (was) a thing with worldpanels before the scene update, i'm guessing it's going to be added back in

**Comment by handsomematt** [comment]
We have an API for this https://asset.party/api/Sandbox.UI.WorldInput but it needs some components for it
