### ISSUE TITLE
Camera effects don't work when you have a viewmodel camera

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5032]
### Describe the bug

Camera effects don't work when you have a viewmodel camera.

### To Reproduce

1. Create a viewmodel camera.
2. Use a camera effect.

### Expected behavior

The camera effect should be working on the main camera.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/16f2354b-5794-43b0-a0cc-f4a094a2a077

**Comment by somethink000** [comment]
You have 2 cameras and each has this effect?

**Comment by DevulTj** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/4827
