### ISSUE TITLE
Sometimes the local connection doesn't join the lobby after creation

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5037]
### Describe the bug

I'm essentially using the NetworkHelper component but extended, and everything just hangs after CreateLobby() since OnActive/OnConnected never fires. Either the lobby does not get created or it does not get joined locally.

### To Reproduce

1. Add networkhelper component or code to an object
2. Start the game
3. OnActive will not fire.

### Expected behavior

Local connection should join the lobby

### Media/Files

Nothing gets logged from the network manager object except that it runs OnStart.

<img width="369" alt="1709323731636" src="https://github.com/Facepunch/sbox-issues/assets/1517911/55b6dada-9919-438e-9ea2-d69f76dbfbee">

**Comment by MrBrax** [comment]
looking at the trace logs, it does say entered lobby, so probably a race condition somewhere?

**Comment by badandbest** [comment]
Local connections tend to not work unless a build of the game is first uploaded to asset.party. Could that be the case here?

**Comment by MrBrax** [comment]
My game is on asset.party, and it works sometimes. I cannot find a reliable way to reproduce either it working or not working.

**Comment by MrBrax** [comment]
I have now been able to to a repro.

1. Launch game with game editor.
2. Open project. Keep launcher open.
3. Start scene/game with multiplayer
4. Close game editor window
5. Open project in launcher again
6. Multiplayer is now broken. Have to close both editor and launcher to fix it.

**Comment by MrBrax** [comment]
I can't seem to reliably reproduce it, but if i keep removing/adding a whitespace and continually save and try starting the scene it will fail like 80% of the time by not running OnActive, and it will go from broken to working to broken again after hotloading.

**Comment by MrBrax** [comment]
For three weeks i sabotaged myself. I feel like jumping into a hole right now. At least it came in clutch before the end of the jam.

For some reason, this goddamn file that i created to try and get around #4949 caused all this headache:

<img width="218" alt="1710120851054" src="https://github.com/Facepunch/sbox-issues/assets/1517911/1511d235-6f17-456e-913e-fd4f6ab6aed6">

Even though i never used it for anything past that initial test, it somehow completely broke the lobby system. Godspeed everyone, always check everything when something goes wrong.
