### ISSUE TITLE
When using the USP viewmodel, it gives and error

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5039]
### Describe the bug

When using the USP viewmodel, it gives and error.

### To Reproduce

1. Use the USP viewmodel in a scene.

### Expected behavior

I should not be getting an error.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/7a8c37d0-36ef-4665-98eb-9fb8f1d724fc

**Comment by kira0x1** [comment]
did you figure out what the problem was ?
