### ISSUE TITLE
Serializing Rotation to JSON creates a cyclic error

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#504]
**Describe the bug**
Trying to serialize Rotation to JSON creates a cyclic error

**To Reproduce**

1. Run code `Log.Info( "Serialize: " + JsonSerializer.Serialize( Rotation.From( new Angles(20, 30, 40) ) ) );`
2. Get error

**Expected behavior**
Serialized Rotation data

**Screenshots**
![1627340888648](https://user-images.githubusercontent.com/1517911/127144867-8b18b3fe-06c5-41b8-ad2a-c633eafff946.png)

**Additional context**

From what i can see, Rotation is from Sandbox, so maybe it's just not implemeted with serialization?
Trying to save entity data would be a bit easier if this worked i think.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
