### ISSUE TITLE
Group attribute not working properly in inspector

### ISSUE THREAD

**Issue by Guilhem-Pech** [Facepunch/sbox-issues#5042]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/15714248/2c3de512-a778-4db9-85a8-bfc6587f86d3)

As you can see here only the "RuntimeValues" group is displayed when you have Action fields alongside "regular" fields

### To Reproduce

Create a class with those fields 

```csharp
//Actions
	[Property, Group("Hover")] Action<GameObject>? OnCharacterStartHovered { get; set; }
	[Property, Group("Hover")] Action<GameObject>? OnCharacterHovered { get; set; }
	[Property, Group("Hover")] Action<GameObject>? OnCharacterEndHovered { get; set; }
	
	[Property, Group("Selection")] Action<GameObject>? OnCharacterSelected { get; set; }
	[Property, Group("Selection")] Action<GameObject>? OnCharacterUnselected { get; set; } 
	
// Others
	[Property, Group("Reference")] private CameraComponent? CameraComponent;
	[Property, Group("Settings")] private TagSet? FilterTags = new TagSet(); 

	[Property, Group("RuntimeValue")] public GameObject? HoveredCharacter { get; private set; } 
	[Property, Group("RuntimeValue")] public GameObject? SelectedCharecter { get; private set; } 
```

See in the inspector

### Expected behavior

Have the foldable group displayed

**Comment by DevulTj** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/bf800a7c-b473-4289-8193-4ead65148b30)
Worth noting all of your Actions should be there, it's intended

**Comment by Guilhem-Pech** [comment]
Yep @DevulTj  actions work as intended but CameraComponent is not in reference group and filter tags is not in settings!

**Comment by DevulTj** [comment]
Please try again as this should work now
