### ISSUE TITLE
The int slider inside of Dictionary properties works as a float, returning error.

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5044]
### Describe the bug

https://github.com/Facepunch/sbox-issues/assets/59583743/b6d6ba59-b879-4ea2-9740-af33766c25e6

This only happens to the value of the dictionary, not the key.

### To Reproduce

1. Create a new property that is Dictionary<int, int>
2. Try to use the slider

### Expected behavior

.

**Comment by DevulTj** [comment]
This should be fine now
