### ISSUE TITLE
Properties of type List<int> don't let you input values in the inspector

### ISSUE THREAD

**Issue by andy013** [Facepunch/sbox-issues#5048]
### Describe the bug

If you create a property with the type `List<int>` when you try and input values in the inspector you get this error message in the console: 

`The value "0" is not of type "System.Int32" and cannot be used in this generic collection. (Parameter 'value')`.

I think the input box might be casting the value to a float.

### To Reproduce

1. Create a property like this on a component: 
```csharp 
[Property] public List<int> Test { get; set; }
```
2. Try and set the property values in the inspector.

### Expected behavior

The inspector should allow you to input values of type int.

**Comment by andy013** [comment]
Seems related to #5044

**Comment by DevulTj** [comment]
This should be fine now
