### ISSUE TITLE
Editor Tools that create GameObjects sometimes create them in a "different scene" from the object they're being applied on.

### ISSUE THREAD

**Issue by kouta-kun** [Facepunch/sbox-issues#5050]
### Describe the bug

When creating an Editor Tool that as part of its' action creates a GameObject, sometimes I get an error "Assert: Can't parent to a gameobject in a different scene" due to the GameObject being effectively created in a different scene from the parent object, as checked using a debugger where I can see that the parent gameobject is in a scene with 8 objects and the created object is in a scene with 0 objects.

### To Reproduce

I don't currently have a replication step, sometimes it works correctly and randomly starts throwing the issue.

### Expected behavior

GameManager.ActiveScene should always coincide with the scene of the object selected when in an editor. Or, alternatively, a way to specify which scene an object should be created in.

**Comment by handsomematt** [comment]
This is usually what Scene.Push() is for, can you show some code that's not working like you'd expect

**Comment by kouta-kun** [comment]
@handsomematt Hi, I can get some code but I can't find a consistent way to replicate it (seems to be after playing and stopping a scene in the editor but not always), I'll upload it here as soon as I get back to my gamedev PC

**Comment by garrynewman** [comment]
You need to push the scene you want to use. This is the way it works, it's never gonna fallback to GameManager.ActiverScene. This also isn't going to be thread safe.
