### ISSUE TITLE
Can't edit ImpactEffectData when editing Surface.

### ISSUE THREAD

**Issue by LucasPaglia3** [Facepunch/sbox-issues#5051]
### Describe the bug

When trying to change the particle effects of a surface in the inspector, the list of Impact Effects is empty and uneditable.

The following error is thrown in the console stating that array of strings are not supported in editor:

"Couldn't create ControlObjectWidget: [System.MissingMethodException: Cannot dynamically create an instance of type 'System.String[]'. Reason: Type is not supported.]"

### To Reproduce

1. Search for a surface on the asset browser.
2. Press on edit button for Impact Effects in the inspector.
3. Impact Effects Data is not editable and the previous mentioned error is shown on console..

### Expected behavior

Should be able to edit the list of impact effects when trying to change particle effects of a surface.

**Comment by aylaylay** [comment]
Should be fixed now
