### ISSUE TITLE
Particle System Improvements

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5056]
### For?

S&Box

### What can't you do?

I've been making a bunch of particle effects for the game jam and I wanted to make a list of my ideas for improving the system while they're in my mind:

- [ ] Add rotation speed option for particles, alongside a drag value for it. Ideally allow this to be impacted by collisions as well. (i.e. collisions reduce rotation speed)
- [ ] Allow some way to sync multiple particle effects/trigger all particle effects with a button in the editor. 
    
 I have a particle that looks like this in the editor:
     
![image](https://github.com/Facepunch/sbox-issues/assets/7847372/5d6b5fa8-8abc-440f-9529-6ff0fdfc2d1e)

The two game objects both have separate particle effects on them that are designed to run at the same time when the object is created. This works fine when you initially open the prefab, but quickly become out of sync when editing one of the effects.

- [ ] More in built particle textures.
- [ ] Model particle renderer.
- [ ] Some way for particles to inherit the velocity of their parent game object. Not entirely sure how you'd go about this, but it was very useful for making particles feel more natural in the old system.
- [ ] You could have particles start at different sizes in the legacy particle editor, and then scale their radius multiplier over time. This allowed you to have a lerping over time particle size while also having some variation in the individual particle sizes. Doesn't seem to be a way to do this right now.

### How would you like it to work?

Particles are ok, but definitely need some work.

### What have you tried?

Can't fix these myself without some lame hacks.

**Comment by Jammie3d** [comment]
I've been running into the particle desync issue a lot too, it's only a minor annoyance but I'd love to have some playback controls like Unity has.

![image](https://github.com/user-attachments/assets/0d84ecb2-21d7-4b33-ab2d-5b56b3e14693)

**Comment by Fortune117** [comment]
Personally don't think this issue should've been closed, most of these are not in the new particle system and are still features that I'd like to see. I can create some of these missing effects in the legacy particle system if you want examples.

**Comment by garrynewman** [comment]
I'd love more specific issues on this, so we can discuss them individually rather than as a whole

**Comment by Fortune117** [comment]
That's easy enough then.

**Comment by Jammie3d** [comment]
I made an issue for the sync/playback controls here: https://github.com/Facepunch/sbox-issues/issues/6390
