### ISSUE TITLE
Steam Notifications take over your Scene window

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5058]
### Describe the bug

Steam Notifications sometimes aren't scaled correctly, ranging from being tiny to so big they cover the entire window.

### To Reproduce

I'm not really sure, it seems to not happen if I've had S&box open for a while

### Expected behavior

Either show the notifications at normal scale, or show them at the bottom right of the tools.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/594e25e1-0639-43d0-ad66-8f83d012dcef)

### Additional context

My resolution is 16:9, this happens on the Game Window as well when in Play Mode.
The notifications don't seem to be clickable.

I believe this to be a targetted attack as to hinder my progress on the contest. People in my friend list are probably taking turns to maximize the time my screen is covered.

**Comment by DevulTj** [comment]
There's not much we can do here. As of right now, SteamInput (required for gamepad controls) relies on the steam overlay, so we had to disable the vulkan environment variable to disable the overlay.

If that ends up getting addressed, we can re-add it.

**Comment by Gmod4phun** [comment]
At least from my experience, this only seems to happen when you first launch the editor. Once you play the scene, then the notifications will be sized correctly. Also, this issue happens with the steam builtin FPS counter (I guess everything thats a part of the overlay)
