### ISSUE TITLE
Gamemode console commands don't auto-complete on non-host clients

### ISSUE THREAD

**Issue by rugg0064** [Facepunch/sbox-issues#506]
**Describe the bug**
If I have a console command like this for instance:
```[
ServerCmd( "trySwitchTeam" )]
public static void trySwitchTeamCmd(string team)
{
        //lots of stuff here
}
```
The player that is hosting the game can see the command in the auto-fill suggestions, but connected users cannot.

**To Reproduce**

Make any console command for a gamemode and this seems to happen.

**Expected behavior**

The joined client should get the same autocomplete options as the host

**Screenshots**

On the HOSTING client, I can see this:
![image](https://user-images.githubusercontent.com/35048262/127215859-67cbd063-a705-4e77-9b6b-66fe0f699609.png)
On a joined client, I don't get the same behavior:
![image](https://user-images.githubusercontent.com/35048262/127215943-b1b69cbe-a307-4efc-95e2-4ade6be777be.png)

**Comment by garrynewman** [comment]
This is normal and expected, the client doesn't know of the console commands that exist on the server.

**Comment by rugg0064** [comment]
It seems like clients should either see the commands and be able to run them, or they should be invisible and not runnable by clients.
