### ISSUE TITLE
`ShowIf` does not work within categories

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#5060]
### Describe the bug

`ShowIf` does not function if both properties are within a category.

### To Reproduce

```
	[Property, Category( "Optional" )]
	public bool HasBounds { get; set; } = false;

	[Property, ShowIf( "HasBounds", true ), Category( "Optional" )]
	public Vector3 Position { get; set; }
```

### Expected behavior

Toggling `HasBounds` should show/hide `Position`

**Comment by aylaylay** [comment]
This seems to be working?

**Comment by matekdev** [comment]
Yeah seems to have been fixed.
