### ISSUE TITLE
Reading structs in Action Graph

### ISSUE THREAD

**Issue by rlenhub** [Facepunch/sbox-issues#5063]
### For?

S&Box

### What can't you do?

Accessing structs seems to be entirely unsupported in the action graph. When a struct is exposed as an input to an action, the parameter will be visible, but cannot be read from. For context, I am trying to write a simple "Projectile" component that has an "OnCollision" action. The action is invoked by `Rigidbody.PhysicsBody.OnIntersectionStart`, which includes the struct `PhysicsIntersection` as the input. I am completely unable to access the collision data in Action Graph.

### How would you like it to work?

List all public properties of the struct when dragging out a new node, allowing the developer to use the data within.

### What have you tried?

I was going to try to create wrappers for the structs I want to use in the graph, but there's a lot of structs involved and a lot of fields between them, and the time-sink defeats the purpose of using graphs.

### Additional context

A nice bonus would be to allow constructing structs.

**Comment by Metapyziks** [comment]
I think this is because we have to manually expose types defined in the engine, this might not be specific to structs.

I'm off today but I can expose that stuff for you tomorrow.

**Comment by Metapyziks** [comment]
Exposed these:
* PhysicsIntersection
* PhysicsIntersectionEnd
* PhysicsContact
* PhysicsContact.Target

Please let me know if there's any more you need!
