### ISSUE TITLE
SkinnedModelRenderer garbled bones

### ISSUE THREAD

**Issue by Weldify** [Facepunch/sbox-issues#5064]
### Describe the bug

Sometimes network spawning a gameobject with a SkinnedModelRenderer causes it to look all garbled. I couldn't get much info on this because it's rare and inconsistent.

### To Reproduce

1. Have a SkinnedModelRenderer with `CreateBoneObjects = true`
2. Network spawn it
3. Observe the bug happen a very small percentage of times

### Expected behavior

The bones shouldnt explode!

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/66477673/098a3cb6-7bfb-400c-a8f2-50a8cbee742b)
![image](https://github.com/Facepunch/sbox-issues/assets/66477673/dd411f99-d097-4630-a333-f797148f060d)
![image](https://github.com/Facepunch/sbox-issues/assets/66477673/20f959ef-980d-4b90-ae99-80d9e92bf1d3)

**Comment by Weldify** [comment]
Starting yesterday, this bug now happens about 90% of the time. Only the host can see it. This makes the game almost unplayable.
The model seems to be offset now which didn't happen before, but it still gets garbled from time to time.

https://github.com/Facepunch/sbox-issues/assets/66477673/2b60008c-91f0-46f0-8666-60edc7849b51

I am not touching the model's transform or any of its bones at all in my game. The model GameObject not networked, but it is a child of the player GameObject which is networked.

**Comment by Weldify** [comment]
I would really appreciate it if someone from Facepunch could take a deeper look at this because this makes my game completely unplayable for the host.

**Comment by aylaylay** [comment]
Is this still happening?

**Comment by aylaylay** [comment]
I've tested this and I'm unable to reproduce it.

**Comment by Weldify** [comment]
Doesn't seem to be happening anymore. Cheers Facepunch!
