### ISSUE TITLE
ActionGraph: Connecting "All.Body" to AndAlso operator crashes sbox

### ISSUE THREAD

**Issue by Sakiskid** [Facepunch/sbox-issues#5066]
### Describe the bug

In ActionGraph, connecting `All.Body` to `AndAlso.B` will crash s&box.

PFA action graph in additional context

![image](https://github.com/Facepunch/sbox-issues/assets/33964795/0bc26fbb-e17d-4412-88c1-25fd6ed5e0f6)

### To Reproduce

1. Import linked actiongraph
2. Connect All.Body to AndAlso.B

### Expected behavior

Should not be crashing but instead throwing an error

### Additional context

[Action Graph](https://gist.github.com/Sakiskid/0cd732e3d6e4ac3c5ca5921f04cec4cb)

**Comment by Metapyziks** [comment]
Thanks for the report!
