### ISSUE TITLE
Renaming file in IDE removes component from gameobject

### ISSUE THREAD

**Issue by Sakiskid** [Facepunch/sbox-issues#5068]
### Describe the bug

When renaming a file in IDE, the components are removed from GameObjects. It seems like it loses the reference and just deletes the component.

### To Reproduce

1. Attach a component with custom script to a gameobject
2. Go into your IDE, and use "refactor" on the class name, which should rename the file as well
3. Look at gameobject in editor

### Expected behavior

GameObject should either:
A) update reference and properties to maintain the component
B) keep an empty "null reference" component to give feedback on error, which will throw an error on scene load/reload to keep notifying the user

### Additional context

I am using JetBrains Rider 2021.2.2

**Comment by DevulTj** [comment]
When refactoring, it's renaming the component type, which is serialized in the scene - so it won't know what type to expect, we can't do anything about that
