### ISSUE TITLE
ShowIf/HideIf don't update inside of GameResources

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5070]
### Describe the bug

The attributes ShowIf and HideIf don't update inside custom GameResources. You have to close and reopen the resource editor for the properties to hide/show

### To Reproduce

```
	/// <summary>
	/// Does the player need to complete this task within a time limit before it automatically fails?
	/// </summary>
	[Property]
	public bool TimeLimited { get; set; } = false;

	/// <summary>
	/// How many real-life seconds the player has to complete the task before it's automatically failed
	/// </summary>
	[Property]
	[ShowIf( "TimeLimited", true )]
	[Range( 10, 600, 10 )]
	public int TimeLimitInSeconds { get; set; } = 120;
```

### Expected behavior

.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/ab7c429a-f70c-4ac2-ad57-01fae224e876)

**Comment by yuberee** [comment]
Yes, this is only inside gameresources

**Comment by aylaylay** [comment]
This seems to be working now?
