### ISSUE TITLE
Surface friction on map surfaces doesn't apply to rigidbodies

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5071]
### Describe the bug

All rigidbodies roll the same distance even though the friction is set lower/higher on a material. I think this will prevent some mechanics from being possible.

I don't think surfaces are taken into consideration at all, i don't hear any collision sound either even though there is an option to disable them on rigidbodies.

### To Reproduce

1. Make two surfaces with varying friction
2. Have two spheres roll down two hills with differing surfaces

### Expected behavior

The frictionless one should roll much much further.

### Media/Files

<img width="310" alt="1709583375495" src="https://github.com/Facepunch/sbox-issues/assets/1517911/092708dd-210d-4cee-b81c-b74dc4a1bcb8">
<img width="268" alt="1709583391097" src="https://github.com/Facepunch/sbox-issues/assets/1517911/ce058a63-573d-4046-8cf5-6bbac6793a23">
<img width="274" alt="1709583395950" src="https://github.com/Facepunch/sbox-issues/assets/1517911/71fa1df5-63fe-45ac-aa53-96d9ba2c95fb">

**Comment by aylaylay** [comment]
How is the geometry being made? Could you make a small downloadable repro for me please?

**Comment by aylaylay** [comment]
This is working fine for me? @MrBrax 

https://github.com/Facepunch/sbox-issues/assets/1667289/2b21447b-5608-4783-b433-621f8591b6d9

**Comment by MrBrax** [comment]
could this be after that physics fix earlier? i'm in total crunch mode for the jam right now so haven't had time to look at this, but i'll get back to this after that

**Comment by aylaylay** [comment]
it shouldn't be, surfaces have always been applied to physics shapes. It matters what you're using for the collider

**Comment by MrBrax** [comment]
something has definitely changed, i added two slabs next to eachother and put a surface override on the box collider, and now i'm suddenly slipping around.

it seems to work right now, even putting friction to 0 makes me slip uncontrollably.

**Comment by MrBrax** [comment]
ok scratch that, it works on the simple colliders, but on a map it seems broken

**Comment by MrBrax** [comment]
repro: https://github.com/MrBrax/slippy

**Comment by aylaylay** [comment]
Thanks for repro

**Comment by aylaylay** [comment]
Should work now (This was unsupported in rubikon too!)

https://github.com/Facepunch/sbox-issues/assets/1667289/f685673b-ea7b-4301-990d-b0afb1a23c40

**Comment by MrBrax** [comment]
very cool, confirmed working in my game. i feel like a lot of maps are gonna break for the wrong reason because of this lol
