### ISSUE TITLE
Requesting clarification on the use of core/physics/props sounds in contest games

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5075]
In `core/sounds/physics/props` there are many different sounds. Based on the naming (e.g. `xen_resin_puck`) and sheer volume (over 1,000) of these sounds, I assume that these come from Half-Life: Alyx.

1. Are these meant to be included with S&box?
2. Am I allowed to use these sounds in my Game Jam 1 contest game?

**Comment by garrynewman** [comment]
Yeah you can use them for now, but we do need to go in and swap these out with Rust sounds.

**Comment by chrisspieler** [comment]
Sounds good, thanks for clarifying!
