### ISSUE TITLE
GameObject in multiple child have slow transform update

### ISSUE THREAD

**Issue by dictateurfou** [Facepunch/sbox-issues#5076]
### Describe the bug

GameObject in multiple child have slow transform update
after several tests it is the gameObject of the bones which seems to have this problem and not only the children

in my hierarchy the rear wheel is only in a child GameObject but the front wheel is in 7-8 child GameObject
![image](https://github.com/Facepunch/sbox-issues/assets/12927420/58095260-4461-4b28-a1c7-0c2d5d362e16)

in this example we can see that the rear wheel follows well and that the front wheel does not follow correctly.
The white lines are drawn in the update of the component which is located on the relevant gameObject and the green sphere is drawn in the update of the root GameObject

https://github.com/Facepunch/sbox-issues/assets/12927420/ef102061-2935-4c4b-b41f-ca023e013ffd

### To Reproduce

draw something in multiple child GameObject that moves
or just log the distance between the two object while moving
Log.Info(FrontWheel.Transform.Position.Distance(BackWheel.Transform.Position)); he give inconsistent result

### Expected behavior

it should have the same effect as the rear wheel

**Comment by Titanovsky** [comment]
😫

**Comment by garrynewman** [comment]
You're gonna have to explain this one better to me.

Are you saying that in OnUpdate they're different distances apart? Because that would be somewhat expected, because at that point animation/bones haven't been calculated yet.

**Comment by dictateurfou** [comment]
The issue is that any GameObject or component attached to a bone GameObject, even if it doesn't move or undergo any transformation and doesn't use any animation, returns values that are offset with Transform and LocalTransform in FixedUpdate and on Update while my entity moving.

What I don't understand is that the mesh component follows the bone's position without shifting, but in the code, the values returned have an offset (I should mention that I only change the position of my entity in the OnFixedUpdate).

For example, if we follow the logic of GameObjects created by bones, their local position isn't updated if no animation is playing, which would be logical. However, they still experience an offset even if my GameObject is attached to the root, which never moves. This piece of code, which should work, doesn't, and it creates the same offset.
Exemple:
```csharp

	private List<GameObject> FindGmHierarchy( GameObject gm )
	{
		var actualGm = gm;
		var list = new List<GameObject>();
		while ( actualGm.IsRoot == false )
		{
			list.Add( actualGm );
			actualGm = actualGm.Parent;
		}
		return list;
	}

	private Transform RealLocalTransformIssue( GameObject gm )
	{
		if ( gm.IsRoot ) return new Transform(Vector3.Zero,Rotation.Identity);
		var finalTransform = new Transform( Vector3.Zero, Rotation.Identity );
		var all = FindGmHierarchy( gm ).Reverse<GameObject>();
		var cumRot = Rotation.Identity;
		foreach ( var child in all )
		{
			if(child.Parent.IsRoot == true )
			{
				finalTransform.Position += child.Transform.LocalPosition;
			}
			else
			{
				cumRot = cumRot * child.Parent.Transform.LocalRotation;
				finalTransform.Position += child.Transform.LocalPosition * cumRot;
			}
			
		}
		return finalTransform;
	}
	var realLocalPos = RealLocalTransformIssue( FrontWheel ).Position;//FrontWheel is the object Attached to Bone if no attache to a bone he work
	draw2.SolidSphere( GameObject.Transform.Position + realLocalPos * GameObject.Transform.Rotation, 5f );
```

**Comment by garrynewman** [comment]
Because the game loop runs like this

> Run Updates
> Run Fixed Updates
> Work out Bones
> Run PreRender (position scene objects)
> Render Frame

You're doing stuff in update/fixed update, where the bone positions haven't been changed yet

**Comment by garrynewman** [comment]
Alright, I'm still trying to work out your problem.

What you're saying is that the object on the bone should move relative to the game object that the SkinnedMeshRenderer is on, right?

Current Behaviour:  Front wheel transform stays where the bones were last worked out
Required Behaviour: Front wheel transform moves relative to closest non-bone transform, but using the local transform offsets

Is that right?

**Comment by dictateurfou** [comment]
It's pretty much that. I've created a demo project to explain better. I've placed a bone on the cube.

The green sphere is just a child GameObject.
The red sphere is just a bone GameObject created by the model.

![image](https://github.com/Facepunch/sbox-issues/assets/12927420/32311beb-8e8e-4da1-9bde-627201b5ea67)

the current behavior
https://github.com/Facepunch/sbox-issues/assets/12927420/ccbd3336-fd67-496c-b48c-129aa08f94c7

The expected behavior
https://github.com/Facepunch/sbox-issues/assets/12927420/37cedfbf-b887-41e1-8e18-93880ffc793b

the project test file is here
https://github.com/dictateurfou/gameobjectboneissue
