### ISSUE TITLE
Dragging Prefabs into Scenes is broken

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#5079]
### Describe the bug

Dragging prefabs into the scene from the asset browser doesn't add the object to the scene. It will show the preview while dragging but delete the object and give you an empty gizmo. When interacted with it'll spam NRE and if you try to delete the object it'll lock your scene view.

### To Reproduce

1. Open any project
2. Try to drag a prefab into the scene view
3. Note it doesn't get added

### Expected behavior

I assume this broke with a recent commit, dragging models and other assets seems to work fine.

**Comment by WtrpXcal** [comment]
I am also getting the same issue, I have some footage of the problem.

 I am also noticing if I delete the prefab and recreate it with the same name it will not create the prefab files. Infact it seems I can never create a prefab with the same name I have to use a new name for the prefab to show up on the asset explorer and windows explorer.
 
 The primary gameObject the prefab is converted from is working correctly with no issues.
 
 Other than that same issues as above. Heres the images
 
 https://gyazo.com/3dd95d51f56a4c8875f56b952b036ac8
 
 https://gyazo.com/ede5ccf589f9da07e2bbe2ee60172272

**Comment by LucasPaglia3** [comment]
Also getting this issue.

**Comment by DevulTj** [comment]
Will fix this tomorrow

**Comment by DoctorGurke** [comment]
seems to be fixed now, both hierarchy and scene view works, cheers
