### ISSUE TITLE
UI: Panel transition lags/jitters when a mouse event is called

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#508]
**Describe the bug**
If a panel is hovered over during its transition, it'll lag the transition out. It's fixed by doing `pointer-events: none;`

Please note in the video: First couple of times, the cursor doesn't intersect with the panel that's transitioning. Then it does - and the lag starts.

**Expected behavior**
It's not meant to lag

**Screenshots**

https://user-images.githubusercontent.com/22372616/127248319-9b2a9b8b-7868-44fe-bca2-e62df1245d6c.mp4

**Additional context**
I'm using flexbox, maybe it matters?

**Comment by garrynewman** [comment]
I noticed this too

**Comment by louiefox** [comment]
This seems to have changed recently, it looked normal before but now it is jittery.
Current - https://user-images.githubusercontent.com/16431607/127789164-6a7977b2-2bb6-4e2b-8c95-e56a47db3f1c.mp4
Before (0:09 - 0:14) - https://www.youtube.com/watch?v=F1wLsUs6Tdc&t=9s&ab_channel=Brickwall

**Comment by Alf21** [comment]
https://user-images.githubusercontent.com/11843790/127923878-7b0927c2-a538-42be-baf0-7afb7e5f4657.mp4

Yea, on the first click / mouse hover during animation, it's obviously visible :)

**Comment by Hlowy** [comment]
There are no solutions?
Still an urgent problem, very strongly spoils the animation

**Comment by Fortune117** [comment]
Just ran into this issue myself.

**Comment by cr4yz** [comment]
This should be fixed in the next update, please let me know if you find any issues with it
