### ISSUE TITLE
Baked direct lighting isn't working anymore,

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#5080]
### Describe the bug

Direct lighting is no longer baked, they're forcefully dynamic. This means when set to baked only they don't even cast shadows at all. This sucks for performance and the overall quality of lights.
Older compiled maps it seems this isn't an issue, baked direct lights still work as they used to ingame.

### To Reproduce

1. Create a map, place a light.
2. Compile.
3. Load in game.

### Expected behavior

Direct lighting should be able to be baked into the lightmap similar to how it used to.

**Comment by MrBrax** [comment]
<img width="548" alt="1709653559295" src="https://github.com/Facepunch/sbox-issues/assets/1517911/bbada305-0764-474d-89f2-ab2c1bafa118">

casting shadows only or bounce lighting too? because i'm not sure i have that problem

**Comment by Xenthio** [comment]
only direct lighting. all shadows are cast in real time.

**Comment by MrBrax** [comment]
ok i see it now, definitely something funky going on with geometry lighting too. earlier today when i compiled it was bouncing fine, but now i just get a regular clipped spotlight cone

**Comment by Xenthio** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/28588188/95c11101-38ae-44a3-b305-e1c84652980a)
okay, so, here's a light with Shadows to "Baked Only", we can see that VRAD is compiling them as if they're set to be Dynamic lights. Scene is loading them as dynamic lights with dynamic shadows disabled. 

On an older map, compiled pre scene system, Scene loads this correctly.
![image](https://github.com/Facepunch/sbox-issues/assets/28588188/d902319c-92fb-4329-8283-5dcd56564115)

**Comment by Xenthio** [comment]
both images have r_shadows 0

**Comment by handsomematt** [comment]
Can a proper mapper explain this. @bakscratch ?

**Comment by MrBrax** [comment]
@Xenthio i think i found something, when on lightmap res 512 it's completely broken, but on 1024 it works fine
<img width="683" alt="1710088920683" src="https://github.com/Facepunch/sbox-issues/assets/1517911/751c8b0d-f94d-4d16-827f-3185b3f02744">

**Comment by Xenthio** [comment]
> @Xenthio i think i found something, when on lightmap res 512 it's completely broken, but on 1024 it works fine <img alt="1710088920683" width="683" src="https://private-user-images.githubusercontent.com/1517911/311525798-751c8b0d-f94d-4d16-827f-3185b3f02744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTA1NjUsIm5iZiI6MTcxMDE1MDI2NSwicGF0aCI6Ii8xNTE3OTExLzMxMTUyNTc5OC03NTFjOGIwZC1mOTRkLTRkMTYtODI3Zi0zMTg1YjNmMDI3NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDk0NDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkyNTRhNmE0NTA4YWNkOWE1YmE0YmFhYzRhMjc4N2IxOGRkNGQ4ZTE5OTY2NzFmNTkwYTM0NzFhMjdkY2FjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fl4jSCJXwBQsJ2cHwYsRhU3KaPpag0RQP1rPHPdO-jQ">

I think you have a different issue, compiling on both is fine for me.

**Comment by MrBrax** [comment]
you're right, i was confusing it again. issue still persists even with baking to world

**Comment by garrynewman** [comment]
This is because we removed mixed mode right? @samzanemesis?

**Comment by garrynewman** [comment]
Can you shed any light on this @samzanemesis

**Comment by Xenthio** [comment]
Works! thx :D!

**Comment by MrBrax** [comment]
Does this also fix rect lights being broken?

**Comment by samzanemesis** [comment]
Not until they're reimplemented as barn lights
