### ISSUE TITLE
Cubemaps are no longer baked when maps are loaded.

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#5081]
### Describe the bug

Cubemaps aren't baked anymore when a map is loaded, this causes maps and textures/objects in them (especially metallic ones) to look extremely incorrect. 

### To Reproduce

1. Create a map.
2. Place a cubemap/combined lightmap probe
3. Load in a scene with a maploader component.

### Expected behavior

Cubemaps should be baked on mapload like they used to be for scene system map loading.

**Comment by handsomematt** [comment]
this is intentional, we dont want to bake cubemaps anymore #4367

**Comment by Xenthio** [comment]
how do we use cubemaps then?
