### ISSUE TITLE
ActionGraph - Get "this" gameobject and "this" component

### ISSUE THREAD

**Issue by the-remeko** [Facepunch/sbox-issues#5082]
### For?

S&Box

### What can't you do?

There are nodes to retrieve the children/parent and various properties of the GameObject on the component that calls the ActionGraph node, but you can't get a reference to that GameObject or the calling component to pass to another node, like a custom node that takes a GameObject or component as a parameter.

### How would you like it to work?

There should be a "this" option in the GameObject and Component sections.

### What have you tried?

I looked through all the options that appear when you right click in empty space in the ActionGraph editor and didn't find anything that would return "this" GameObject or "this" component.

**Comment by the-remeko** [comment]
I just realized you can drag objects from the hierarchy into the ActionGraph. This would still be nice to have for custom action graph files and C# nodes.

**Comment by Metapyziks** [comment]
Added helper nodes to get any input, including "this".

![RkOMLQmLlN](https://github.com/Facepunch/sbox-issues/assets/1110904/e970714e-d057-4ff5-aecc-c4c24f19ef66)
