### ISSUE TITLE
Exception when posting to API

### ISSUE THREAD

**Issue by rlenhub** [Facepunch/sbox-issues#5083]
### Describe the bug

I haven't been able to use S&Box in online mode for a few months now. When I try running in play mode, it won't display any games. I can run it in editor mode, but it shows "Couldn't log in.." in the boot log and puts it in offline mode. It could be due to my VPN (Mullvad), but I have sbox and sbox-dev running through a split tunnel. I have had a similar issue with the website but I have been able to navigate through a split tunnel.

### To Reproduce

1. Open Steam
2. Open S&Box
3. Pick any option

### Expected behavior

My *desired* result would be that I can access asset.party through my VPN. The expected result is that I can use S&Box when it is run through a split tunnel.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/33167901/836f9ac8-e749-4789-8c0f-2eb3d592005e)

### Additional context

I'm running on Windows 11, using Mullvad VPN at all times with a split tunnel setup. S&Box runs through the split tunnel.

**Comment by garrynewman** [comment]
Sounds like a problem with your vpn
