### ISSUE TITLE
Fixed Joint Causes GameObject to snap to postion 0,0,0

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5084]
### Describe the bug

When enabled, a fixed joint causes an object to snap to 0,0,0:

https://github.com/Facepunch/sbox-issues/assets/7847372/95bd8aef-67e5-4c95-8770-7aa8874721aa

### To Reproduce

1. Open repo project
2. See how the joint is set up
3. See the snap to 0,0,0

### Expected behavior

Should not snap to 0,0,0

### Media/Files

[bug_repo.zip](https://github.com/Facepunch/sbox-issues/files/14504225/bug_repo.zip)

**Comment by Game4Freak** [comment]
I used slide joints in the meanwhile as some kind of workaround.
Also there is another issue for it: https://github.com/Facepunch/sbox-issues/issues/4538

**Comment by aylaylay** [comment]
thanks for the downloadable repro

**Comment by aylaylay** [comment]
Should be fixed now
