### ISSUE TITLE
Allow private Steam lobbies for dev sessions

### ISSUE THREAD

**Issue by Weldify** [Facepunch/sbox-issues#5089]
### For?

S&Box

### What can't you do?

Right now I can't distinguish between actual game lobbies and editor lobbies. People keep joining me while I work and it feels rude to kick them or restart the server.

### How would you like it to work?

`LobbyInformation.IsEditor` - adding this field would let me exclude editor servers from my in-game server list.
`GameNetworkSystem.CreateLobby(bool isPrivate)` - letting us create private lobbies that can't be queried would also work.

### What have you tried?

Kicking people once they join if we are in the editor, but this requires additional setup for allowing testers.

**Comment by MrBrax** [comment]
i don't know if this was added recently, but there's a "dev" keyvalue added to the lobby information i found when trying to find fixes for multiplayer again:

![1709897253721](https://github.com/Facepunch/sbox-issues/assets/1517911/5356b082-3dcb-46b6-a1ce-d0be57cd38c1)

**Comment by handsomematt** [comment]
Yeah the dev data can be queried already. It should be really easy to allow private lobbies too.

**Comment by Weldify** [comment]
Yes, thank you!
