### ISSUE TITLE
MusicPlayer or SoundEvent keeps distance attenuation on whether it is deactivated or not.

### ISSUE THREAD

**Issue by ipluxteamx** [Facepunch/sbox-issues#5090]
### Describe the bug

When distance attenuation is supposed to be disabled (either by code or with the Sound Editor), it still is enabled in game (when the player gets distanced from the initial position for example, the sound/music gets progressively more muffled).

### To Reproduce

SoundEvent:
1. Initialize an object with a "World" component for example.
2. In the file, initialize a SoundEvent property (get & set) and play the sound in OnStart() with DistanceAttenuation and Occlusion disabled, and SpacialBlend set to 0.
3. Save and place a sound file in the component.
4. Play and get somewhere far from the position of the object.

MusicPlayer:
1. Initialize an object with a "World" component for example.
2. In the file, initialize a string property for the file path of the sound (mp3).
3. Play the sound using the MusicPlayer.Play() function in OnStart(), with the parameter: ListenLocal = true;
4. Save and place the sound file path in the component.
5. Play and get somewhere far from the position of the object.

### Expected behavior

No distance attenuation should be present

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/49649756/9913edad-176a-4717-94ba-c6d9e7c78a5f

### Additional context

I'm running the latest S&box staging version on Windows 11 23H2.

**Comment by MrBrax** [comment]
How does one turn effects off on a MusicPlayer?

**Comment by ipluxteamx** [comment]
> I believe this is an occlusion / reflection thing, rather than an attenuation thing. Turn those things off.

I tried turning occlusion and reflection off, both in the Sound Editor and in the code itself, but it does the same thing.

![image](https://github.com/Facepunch/sbox-issues/assets/49649756/fb42590e-e63b-4496-a214-722462e4c2de)
![image](https://github.com/Facepunch/sbox-issues/assets/49649756/29ee979b-7025-48e6-a3ad-e9fe78ae0dcf)

**Comment by garrynewman** [comment]
I think it was air absorption, next build should have it fixed - please let me know either way
