### ISSUE TITLE
Customizable Network Snapshot 

### ISSUE THREAD

**Issue by Guilhem-Pech** [Facepunch/sbox-issues#5091]
### For?

S&Box

### What can't you do?

As for now, when a player joins a server, the whole current scene (except GameObject with the NotNetworked flag) is snapshotted and sent to the new player.

While it's what we want most of the time it can make some systems behave strangely or more complex than it needs to be.  

For example: 

I want to highlight "usable object" clientside when I'm close to them.
If a player joins at this time the component will be activated so it'll be highlighted for him too.

### How would you like it to work?

To be honest, I don't have the perfect solution for this

Maybe having more control over what and how the scene is transmitted to the clients would be great than "The whole GO is snapshot or not"

1. Be able to tell if a gameobject should be transmitted as its "original state" as when a client start the scene (flag?)
2. Have a field attribute [DoNotReplicate(T? forceSnapshotValue = default)] ?
3. Having an overridable function that bypasses how the object/scene is snapshotted  ( Maybe a GameObjectSystem ?)

### What have you tried?

For my example, the workaround is pretty simple:

In the onStart function on the gameobject script, I force to disable the Highlight Outline component.
While it works it's a bit of a hassle to force this kind of script on every game object that have this kind of behavior.

### Additional context

https://discord.com/channels/833983068468936704/895597253316714497/1214661223547797515

**Comment by kurozael** [comment]
I'm going to be making the Networking toggle in the Inspector configurable for 3 modes: Don't network at all, network as a network object, network with the scene snapshot (default).

Similarly I'm going to be making it so you can tell a Component not to be included in a scene snapshot, too.
