### ISSUE TITLE
Invalid Model Collider breaks nav gen in scene

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#5093]
### Describe the bug

Having an active Model Collider on a game object will break nav gen in the scene if the referenced model doesn't contain any physics.

### To Reproduce

1. Make a test scene with a floor or any map to generate nav on
2. Generate and view nav, should work
3. Add a cube and a Model Collider component referencing `models/dev/box.vmdl` (model has no collisions)
4. Nav will stop updating, disabling the component or using a valid collision model will resolve it

Using an invalid model in a Model Collider will stop nav from generating at all. Re-opening the scene with the broken object won't let you re-generate nav until the object or component is disabled/removed.

### Expected behavior

Nav shouldn't break with invalid physics like this, but maybe the component should additionally already warn you that the model doesn't have collisions to prevent further headaches. I copied a prefab and replaced part of it with programmer art for my test scene, took me a bit to discover why nav suddenly broke in some scenes but not others.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/12602100/567d99bc-38a1-4664-9554-772e30c77b4b

**Comment by aylaylay** [comment]
Was this fixed recently? I can't get it to happen. If it's still happening could you upload a small repro please?

**Comment by aylaylay** [comment]
@DoctorGurke

**Comment by DoctorGurke** [comment]
Gonna check it again later today, been on Easter vacation.
