### ISSUE TITLE
Just play a single animation on a model via code

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5094]
### For?

S&Box

### What can't you do?

Just wanna play an animation on a model that's already set up in modeldoc. My head hurts from looking at the animation graph editor and I feel like it's extremely overkill.

### How would you like it to work?

Just let me do `PlayAnimationSequence(string name)` on a SkinnedModelRenderer or similar. `SetAnimationSequence(string name)` perhaps.

### What have you tried?

Looking at https://wiki.facepunch.com/sbox/Animations_without_Animgraph but it seems to be out of date and there are no code examples in there or in intellisense. Haven't found any fitting functions.

This didn't work either:
```csharp
SkinnedModelRenderer.SceneModel.UseAnimGraph = false;
SkinnedModelRenderer.SceneModel.CurrentSequence.Name = "open";
```

**Comment by DevulTj** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/e91065fc-4991-48e0-b512-38b887e7c52c)
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/228784eb-22a5-484d-8550-f10c57c34703)

This works for me w/ citizen

```csharp
public sealed class TestSequence : Component
{
	[Property] public SkinnedModelRenderer Renderer { get; set; }

	protected override void OnStart()
	{
		Renderer.SceneModel.UseAnimGraph = false;
		Renderer.SceneModel.CurrentSequence.Name = "Dab";
	}
}
```

**Comment by MrBrax** [comment]
i guess something must have been wrong with my model, the above code now works but it seems to be looping the animation infinitely even though it's not set to loop in modeldoc.

i did manage to make a super simple animgraph in the end, so this is only for posterity for me personally.
