### ISSUE TITLE
Local assets are not replicated to new local instances

### ISSUE THREAD

**Issue by rlenhub** [Facepunch/sbox-issues#5097]
### Describe the bug

Any assets I use that are neither built-in or from asset.party fail to replicate to multiplayer local instances. 

### To Reproduce

1. Create a multiplayer project (not using Network Helper) with a camera and a few objects that use local custom assets
2. Test scene and launch a local instance

### Expected behavior

All local assets should probably (at least) replicate to new instances that are also running locally.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/33167901/5c42ee7f-de5a-45a4-a237-c4ae5e4d8df9)
`                       local instance											  			 editor                        `
Texture and entire map both fail to copy to the local instance (box mesh replicates since it's a built-in asset and separate from the map file).

### Additional context

Windows 11, my sbox projects are on a separate storage drive from the engine itself.

**Comment by MrBrax** [comment]
#4912

**Comment by garrynewman** [comment]
Yep this sucks, but this is a duplicate
