### ISSUE TITLE
Getting sounds associated with a material from Trace.Surface drops ~70 fps.

### ISSUE THREAD

**Issue by LucasPaglia3** [Facepunch/sbox-issues#5098]
### Describe the bug

In my case, i'm playing the sound of bullet impacts from a surface, by getting the trace result's surface. When firing a large number of bullets in a short period of time fps drop by about 60 to 80 frames. Can't really pin if it's a Sound issue, or a SceneTraceResult.Surface issue.

### To Reproduce

1. do a trace to a surface.
2. get the bullet sound impact from: SceneTraceResult.Surface.Sounds.Bullet.
3. See fps drop.

### Expected behavior

I'm expecting some fps drop, but not the amount that much.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/123840902/0b673d94-bd5a-4516-8901-19645b8671ed

First 30 bullets are with sounds being played, other 30 are without the sounds being played. Watch the fps counter.

**Comment by garrynewman** [comment]
There's extra entries in the performance chart now that might help diagnose this. Take a look at that when firing.

**Comment by LucasPaglia3** [comment]
Ok, so sound reflections make a massive performance hit.

**Reflections ON, Fps lower by almost 90**
https://github.com/Facepunch/sbox-issues/assets/123840902/45959c13-4196-438f-990f-be10e63e03af


**Reflections OFF**
https://github.com/Facepunch/sbox-issues/assets/123840902/c0749da7-ab45-4806-a7b1-364f96b4c49b

**Comment by garrynewman** [comment]
Yep - that make sense, it's doing more work. Ultimately the decision is going to be, is this worth it for the better sound.. there will be the ability for you to turn reflections on and off.
