### ISSUE TITLE
TypeLibrary set for unit tests

### ISSUE THREAD

**Issue by Walrusking16** [Facepunch/sbox-issues#5100]
### What it is?

Ability to manually set GlobalGameNamespace.TypeLibrary
This would also need to whitelist the ability to create a new instance of TypeLibrary

### Why do you need to use this?

I am trying to create some tests for code that uses the TypeLibrary, but it does not exist in the unity tests which causes it to throw an error. I thought this was a bug so I created a bug (#5073) but it has come to my attention that was intentionally done.

**Comment by garrynewman** [comment]
We already have code to set up the unit test environment, we can probably do this automatically in there.

**Comment by B0zy** [comment]
Any updates on this, running into the same sorta issue.

**Comment by garrynewman** [comment]
It looks like this is fixed now? TypeLibrary is initialized during Unit Test
