### ISSUE TITLE
Context Menu on certain properties gets cut off

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5101]
### Describe the bug

When you right click on something like the Surface property on a Sphere Collider, the "clear" gets cut off
![sbox-dev_3lilRB0UwD](https://github.com/Facepunch/sbox-issues/assets/44037603/1883b2fb-ec28-4577-9c0f-16a2162689fb)
Perhaps related to #4575?

(To be clear this happens on more than just Surface, this is the one I found the most convenient to showcase)

### To Reproduce

1. Open Surface's context menu
2. Clear button gets cut off

### Expected behavior

The entire context menu should be appearing as intended.

![sbox-dev_gHcXRFjanQ](https://github.com/Facepunch/sbox-issues/assets/44037603/9b4b7736-08f6-4147-9da7-8b5ff85e1c4a)

**Comment by aylaylay** [comment]
I can't get this to happen

**Comment by aylaylay** [comment]
@Retroeer

**Comment by Retroeer** [comment]
It's inconsistent, I'm not really sure what causes it but I'll try and get a video of it

**Comment by Retroeer** [comment]
@aylaylay 
Could you try right clicking on the Model Renderer property?

![sbox-dev_y4lwGJrT40](https://github.com/Facepunch/sbox-issues/assets/44037603/a55c0b90-18ce-485b-8010-26796b29e1c5)

Seem to be getting this happening pretty consistently on that

**Comment by Retroeer** [comment]
did not mean to close 😭

**Comment by aylaylay** [comment]
Nope. doesn't happen for me

**Comment by Retroeer** [comment]
Whats your monitor's resolution? I'm on 1440p

**Comment by Retroeer** [comment]
Actually that seems to be exactly the case, I moved it to my 1080p monitor and the issue no longer happens

**Comment by aylaylay** [comment]
I dunno, I can't get it to happen to matter the resolution. I'll push something but it's just a guess

**Comment by Retroeer** [comment]
seems to be more consistently working now, theres only been a few rare instances of it not working now it seems like
![sbox-dev_b2abCtQvA3](https://github.com/Facepunch/sbox-issues/assets/44037603/f525c5a9-e141-4931-8bfc-cac044f4edc1)

**Comment by aylaylay** [comment]
Not much I can do until we can reproduce it on our end unfortunately

**Comment by MrBrax** [comment]
Are you changing the DPI? Because most of the unfixed bugs are with at least differing DPI's.

**Comment by aylaylay** [comment]
Yeah one of my monitors has a different DPI

**Comment by Retroeer** [comment]
don't seem to be getting this anymore?
