### ISSUE TITLE
GameResource Serialization not working with Lists

### ISSUE THREAD

**Issue by quntherdev** [Facepunch/sbox-issues#5104]
### Describe the bug

Serialization of lists in gameresources does not work.
I wrote something like this :
```
public enum ABC
{
    A,
    B,
    C
}
public class BaseResource : GameResource
{
    public ABC Category;
    public List<ABC> Categories { get; set; } = new List<ABC>();
}
```

In the editor, when you'll choose a value for the attribute **Category**, no problem. But when you add an element to the list **Categories**, and you select a value, this will be displayed :
```
 01:39:19   Interop The value "1" is not of type "ABC" and cannot be used in this generic collection. (Parameter 'value')
 01:39:19   Interop The value "2" is not of type "ABC" and cannot be used in this generic collection. (Parameter 'value')
 01:39:26   Interop  [1] The value "0" is not of type "ABC" and cannot be used in this generic collection. (Parameter 'value')

```

### To Reproduce

Write this code :
```
public enum ABC
{
    A,
    B,
    C
}
public class BaseResource : GameResource
{
    public ABC Category;
    public List<ABC> Categories { get; set; } = new List<ABC>();
}
```
Then create a BaseResource in the editor, add an element to the list, and try to change the value. It will display the error in the console.

### Expected behavior

It should change the value correctly in the list.

**Comment by Nolankicks** [comment]
Seems like you’re misusing GameResources.

**Comment by andy013** [comment]
Lists of enums on components also don't let you set the value in the inspector.

**Comment by DAMIENLRY** [comment]
> Seems like you’re misusing GameResources.

This exact same code was working weeks ago. I didn't change anything.

**Comment by quntherdev** [comment]
> Seems like you’re misusing GameResources.

This exact same code was working weeks ago. I didnt change anything on it.

**Comment by garrynewman** [comment]
Should be an easy enough fix, just a case of converting from an int to the value.
