### ISSUE TITLE
NavMesh Debug gets copied when switching from Play to Edit mode

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5105]
### Describe the bug

When you have your game running in Play mode and enable the NavMesh Debug Draw will make a copy of it when switching back into Edit mode. Trying to disable it will only make a new copy.

### To Reproduce

1. (In Play Mode) Enable NavMesh Debug Drawing
2. Stop playing (Go into edit mode)
3. Observe

### Expected behavior

Either keep the option toggled on or delete the copy when switching.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/59583743/50b324eb-41aa-4f47-9927-b456d8f2fa9a

**Comment by lolleko** [comment]
I can't reproduce this anymore with the tiled nav meshes, either it's something I did for the tiling that fixed it, or it was fixed before.
Let me know if the issue still persists for you.
