### ISSUE TITLE
Mesh tools ignore terrain

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5106]
### Describe the bug

When using the mesh tools they ignore terrain.

### To Reproduce

1. Create a terrain.
2. Use a mesh

### Expected behavior

The mesh should be placed on top of the terrain.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/f1617f79-57e1-450e-9567-e52065e33b93

**Comment by Nolankicks** [comment]
Sidenote all mesh function besides placing is broken.

**Comment by aylaylay** [comment]
Fixed
