### ISSUE TITLE
Disabling the occlusion checkbox in SoundEvent breaks the asset

### ISSUE THREAD

**Issue by Marky-S** [Facepunch/sbox-issues#5109]
### Describe the bug

After disabling occlusion in SoundEvent UI menu editor can't load this asset anymore

### To Reproduce

1. Create `SoundEvent` asset
2. Disable `Occlusion` checkbox
3. Reopen asset in editor

### Expected behavior

Working asset

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/80411728/0118f75b-f6a4-46cc-80e8-844d8489711a)

**Comment by garrynewman** [comment]
Can you load if it if you close the editor and re-open it?

**Comment by GunnarKafel** [comment]
Running into this issue myself, relaunched on the latest build, still doesn't work. Seems like it's treating it as a cloud package for some reason 
![image](https://github.com/Facepunch/sbox-issues/assets/65134886/c5a23100-05ae-489c-8744-ff02b3404c49)
![image](https://github.com/Facepunch/sbox-issues/assets/65134886/6aa581d8-dcf4-4dd5-ab12-bb3b2d421f41)

**Comment by Marky-S** [comment]
> Can you load if it if you close the editor and re-open it?

no, even after deletion i can't create more sound assets in same folder, need to restart whole editor to create others

**Comment by garrynewman** [comment]
Investigating

**Comment by garrynewman** [comment]
I managed to repro it

**Comment by Marky-S** [comment]
> This'll probably be fixed now

Yeah, looks like it's fixed now, can't repro anymore

**Comment by Marky-S** [comment]
But still can't create more than 1 `SoundEvent` at same folder, investigating details..

**Comment by garrynewman** [comment]
Any errors?

**Comment by Marky-S** [comment]
Yeah, there is a short video representing behavior right after S&Box editor whole restart:
https://github.com/Facepunch/sbox-issues/assets/80411728/0ff7778e-7c4c-468f-ae85-ef398ddabb9b

Texted:
- create `SoundEvent` asset
- delete this asset
- try create another `SoundEvent`
- failure

Errors:
```
 01:23:15   GameMenu [GameMenu] Detected Asset File Changed /sounds/untitled.sound_c (-2128831035 vs 525403862)
 01:23:15   FileWatch The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
 01:23:23   engine/AssetSystem Cannot recompile 'sounds/untitled.sound': Source file not present.
```

**Comment by garrynewman** [comment]
This fixed now?
