### ISSUE TITLE
Creating entities from an EntityIO output causes a Collection was modified exception

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#511]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1388267/127339507-66d77226-6a4c-4572-b413-ddb77b005a5f.png)

Saw this in help, so paraphrasing a bit. When you create an entity through an [Input] that is triggered by a map Output a "Collection was modified; enumeration operation may not execute" exception is thrown.

Looking at the exception you can see Sandbox.EntityIO.Output.BuildTargets iterates over Entity.All whilst executing Inputs.
A copy of Entity.All or resolving all targets first would fix this.

**To Reproduce**

Call this from a map entity like a func_button:

```csharp
[Input]
void SpawnSomething()
{
    new MyEntity();
}
```

**Comment by robotboy655** [comment]
Fixed.
