### ISSUE TITLE
NavMesh fails to generate on big meshes like the new terrain system

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5110]
### Describe the bug

NavMesh won't even attempt to generate if there's a Terrain in your scene or you have a big mesh loaded in (In terms of poly count). Removing either works fine.

### To Reproduce

1. Create a new Terrain / Load a model with collider with many poligons / Load a big hammer map
2. Generate a new NavMesh inside of editor / await Scene.NavMesh.Generate()
3. Observe results

### Expected behavior

From decompiling NavMesh.Generate I could determine that it fails to generate instantly, so there's something about the meshes that won't even let the navmesh attempt to generate.

### Additional context

Here's a few things I could come up with:

- Smaller maps load correctly, not small in terms of size but small in terms of polycount
- Small terrain doesn't generate navmesh either
- The big mesh I have is a terrain from another software, compiled into a vmdl with mesh collisions
- Even if I convert the terrain model into editable mesh then compile in hammer, it won't work

**Comment by yuberee** [comment]
Generating on terrain now works, although there's some issues which I reported in #5112 
It still doesn't generate on big models, but it's understandable why since I'm talking about 50MB models.

For now the issue seems to be that I instantly crash when trying to generate a navmesh on a terrain that isn't flat.
Skip to the end of video:

https://github.com/Facepunch/sbox-issues/assets/59583743/4f0f66ef-6268-4a28-b3c7-a20f8a713c7b

And mostly it seems that NavMesh doesn't update at all to follow the height of the terrain, and seems to also be offset.

https://github.com/Facepunch/sbox-issues/assets/59583743/1f376ea1-451b-481b-bbc5-cc4fa4cfa689

You can find the file for the terrain itself in #5112 but I can share the repo as well if needed.

**Comment by lolleko** [comment]
Should be fixed with tiled navmeshes.
