### ISSUE TITLE
Terrain doesn't update collisions after updating terrain height

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5112]
### Describe the bug

The collisions on a terrain won't update when you change the settings. It takes disabling and enabling both to regenerate.
This also happens when importing a new heightmap.

### To Reproduce

1. Create new terrain
2. Add two zeros to terrain height
3. Import [this .raw heightmap](https://drive.google.com/file/d/1SFTYndXP-JU72Y2ouuI81QsDExF4TJtF/view?usp=sharing)
4. Enable physics debug view

### Expected behavior

Updating live is probably unfeasible since it takes a few seconds to update collisions, so perhaps a button to regenerate them?

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/59583743/feaf4de7-bca5-484f-9b5f-9170a70b0901

**Comment by aylaylay** [comment]
Collisions should now update. For what it's worth, it costs nothing to update terrain collisions, it was just steam audio and debug rendering slowing it down.
