### ISSUE TITLE
Vulcan Crash in Game Editor View

### ISSUE THREAD

**Issue by gidgeesheep** [Facepunch/sbox-issues#5115]
### Describe the bug

While using developer view, S&box will crash at random times. Vulcan errors appear in the logs before every crash.

### To Reproduce

1. Open the game in Editor View
2. Develop, open file in a file editor, click off the screen, wait any random amount of time
3. A stall occurs and does not self resolve

### Expected behavior

The crash should not happen.

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/14545020/Log.log)

### Additional context

Windows 11
graphics AMD Radeon RX 6800M

All crash logs contain nearly similar results, did try updating all drivers and redownloading S&box, but no change.

**Comment by handsomematt** [comment]
Can you run vulkaninfo and post the results

And can you make sure you're not using any overlays like MSI Afterburner

**Comment by gidgeesheep** [comment]
Here is the vulkaninfo log
[vulcaninfolog.txt](https://github.com/Facepunch/sbox-issues/files/14546411/vulcaninfolog.txt)

I might have an overlay, Armoury Crate, but it is hard built into my laptop. It doesn't seem to recognize S&box.

I'm also adding some extra screenshots in case they help. The program did snag, but did not crash.
<img width="1280" alt="Screenshot 2024-03-09 083411" src="https://github.com/Facepunch/sbox-issues/assets/55063683/61bd60c2-3482-49ee-9bd2-87d21a8c3864">

<img width="1280" alt="Screenshot 2024-03-09 083415" src="https://github.com/Facepunch/sbox-issues/assets/55063683/81881fa2-eaa8-45a1-9d5a-e2510e48bd6c">

**Comment by gidgeesheep** [comment]
I can consistently trigger a crash by opening the project solution with Microsoft VisualStudio. I was able to receive a new error by keeping the solution open and restarting the sandbox project.
[Log.log](https://github.com/Facepunch/sbox-issues/files/14546522/Log.log)

Then a crash occurred on hotload, after editing a custom component attached to the player.

 I can consistently crash when opening the component directly
<img width="483" alt="Screenshot 2024-03-09 085950" src="https://github.com/Facepunch/sbox-issues/assets/55063683/cd46c492-23ea-43d9-9390-42e73f16b65f">

**Comment by gidgeesheep** [comment]
Update:
- If two instances of the same scene are opened, and a new component added is opened in Visual Studio, the second instance does not crash.
- Once the file is saved in the Visual Studio, and the hotload runs, the second instance will crash.
- Saving and hotloading won't crash if a program like Notepad++ opens a .cs file in Explorer and makes changes.
- The same problems happen when using Visual Studio Code, I can't test on Rider
- If an already implemented .cs file is is removed and reattached it causes no problems.
- This error still appear and I can't reproduce a crash:
`09:06:36   engine/RenderSystem CSwapChainVulkan::SwapBuffers vkAcquireNextImageKHR - completed result = Unknown VkResult value
09:06:36   engine/RenderSystem Vulkan swapchain out-of-date, suboptimal, or surface lost - recreating.  Result: (Unknown VkResult value)`

I feel like a lot of this is pointing to a crash around opening and loading the files in the editors.

**Comment by gidgeesheep** [comment]
### System Info

Device name	Super-Duper-Laptop
Processor	AMD Ryzen 9 5980HX with Radeon Graphics           3.30 GHz
Installed RAM	64.0 GB (63.4 GB usable)
Device ID	1E873601-2555-4DE0-BC11-28F6BD1CF649
Product ID	00342-20724-47490-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

### Windows Info

Edition	Windows 11 Home
Version	23H2
Installed on	‎2/‎17/‎2023
OS build	22631.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0

**Comment by gidgeesheep** [comment]
Uninstalling Armoury Crate did not fix the problem

**Comment by MrBrax** [comment]
My game crashed by just having rockstar social club installed, check if you got that

**Comment by handsomematt** [comment]
I added more diagnostics to the logs - could you post your latest Log.txt and also your steamid64

**Comment by gidgeesheep** [comment]
> My game crashed by just having rockstar social club installed, check if you got that

No Rockstar Social, so unfortunately still something else.

My steamid64 is 76561198041543571

This is the log for a crash when open Microsoft Visual Studio at the tab bar
[OpeningProjectManagerCrash.log](https://github.com/Facepunch/sbox-issues/files/14724333/OpeningProjectManagerCrash.log)

Crash from hotload saving in an instance of VS studio that was left open
[MS-VSHotloadCrash.log](https://github.com/Facepunch/sbox-issues/files/14724386/MS-VSHotloadCrash.log)

Creating a new component, which opens Visual Studio, crash
[NewComponentOpensMS-VSCrash.log](https://github.com/Facepunch/sbox-issues/files/14724446/NewComponentOpensMS-VSCrash.log)

I don't know, guys. This sucks.

**Comment by handsomematt** [comment]
You'd said you'd tried updating your drivers already but your log suggests you're on older drivers.
Updating drivers fixed this for another user, so can you double check what your driver version is and post back here

**Comment by gidgeesheep** [comment]
I've clean reinstalled AMD about 5 times, updated windows 10 times after every clean wipe, I've manually ripped files out of the drivers folder, tried file bashing to see if anything would change.

The Vulkan version installed (for some reason) is currently 2.0.193. Lighting is bugged, but the Visual studio does not crash sbox.

AMD and windows updates are conflicting. Something is causing a ghost gpu to appear in the vulkaninfo summary after a Windows update, I believe windows is handling the integrated graphics, while the AMD Adrenaline is dealing with my rx 6800m.

[vulkaninfo summary - post clean instal windows update.txt](https://github.com/Facepunch/sbox-issues/files/14812478/vulkaninfo.summary.-.post.clean.instal.windows.update.txt)

[vulkaninfo summry.txt](https://github.com/Facepunch/sbox-issues/files/14812479/vulkaninfo.summry.txt)

The Windows AMD conflict is out of my control, I need the update or the laptop graphics are buggy.

Is it possible that sbox could choose to use the newest version of Vulkan installed? There is evidence that 2.0.299 is in the system, but my preload vulkan warning is choosing a lower version of Vulkan

![Screenshot 2024-03-30 113100](https://github.com/Facepunch/sbox-issues/assets/55063683/d10b735b-f1d2-4834-856d-a15d16730e9b)
<img width="463" alt="Screenshot 2024-03-29 220304" src="https://github.com/Facepunch/sbox-issues/assets/55063683/44b6ad99-3400-47ca-801b-8f16581bd08a">
![Screenshot 2024-03-30 105124](https://github.com/Facepunch/sbox-issues/assets/55063683/8669ccb4-a7e7-4730-990e-3e52ee8b3b66)



Even after driver tampering, I can get the later version recognized. This error also occurs after a AMD Clean wipe then AMD Update Utility, but BEFORE a windows update on the integrated graphics.

![Screenshot 2024-03-29 220559](https://github.com/Facepunch/sbox-issues/assets/55063683/c30e1691-12cd-4bbe-a584-90123f3b2f6e)

This might be in the hand of AMD, Windows and God.

**Comment by gidgeesheep** [comment]
Their was a second AMD driver that needed updated inside integrated graphics. Don't be me, remember your graphics integrated CPUs need to be updated separately. Crash resolved.
