### ISSUE TITLE
#nullable error on new projects

### ISSUE THREAD

**Issue by kira0x1** [Facepunch/sbox-issues#5116]
### Describe the bug

Whenever I open a project even fresh ones I get the same error in my log.

"The annotation for nullable reference types should only be used in code within a '#nullable' annotations context."
Trying to clear the log doesnt clear this error.

This could be a duplicate of https://github.com/Facepunch/sbox-issues/issues/4801 im not sure.

I found one workaround which is having to close the console window completely and then create a new one, until this error comes back which is when i recompile again.

### To Reproduce

1. Create project
2. Check log

### Expected behavior

Should not be in my log 🥲
or atleast click the trash icon should clear it.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/13779328/129c0844-13b8-4ec2-ad33-80244a235f0a)

### Additional context

os: windows 11
gpu: 3070ti
ram: 32gb ram,
cpu: intel i5-12400F

**Comment by garrynewman** [comment]
I think this might be @Metapyziks, he keeps trying to make everything nullable enabled

**Comment by kira0x1** [comment]
> I think this might be @Metapyziks, he keeps trying to make everything nullable enabled

lol

**Comment by Metapyziks** [comment]
It's true, I do love putting question marks everywhere ☺️

**Comment by kira0x1** [comment]
@Metapyziks 

> It's true, I do love putting question marks everywhere ☺️

Cant blame you, I do the same thing working in typescript.

**Comment by peter-r-g** [comment]
> It's true, I do love putting question marks everywhere ☺️

A man after my own heart
