### ISSUE TITLE
Getting some issue in citizen Animation helper

### ISSUE THREAD

**Issue by somewhere-in-the-universe** [Facepunch/sbox-issues#5117]
### Describe the bug

when I`m trying to use the citizen animation helper in the cs script im getting this issue

### To Reproduce

use citizen animation helper in some script

### Expected behavior

there mustn`t be any error

### Media/Files

![изображение](https://github.com/Facepunch/sbox-issues/assets/146519784/1fad8aa2-01d0-444f-8a10-dd9c821b34fa)

### Additional context

I`m running on windows 11 23h2
trying to make a player with Carson Compon tutorial (https://carsonk.net/S&box-Tutorial-How-to-create-a-Player-Controller/)

**Comment by MrBrax** [comment]
did you set the skinnedmodelrenderer target?

**Comment by somewhere-in-the-universe** [comment]
> did you set the skinnedmodelrenderer target?

yes, I did it on "Body" child of my player object
