### ISSUE TITLE
Have the ability to extrude down in the terrain editor

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5118]
### For?

S&Box

### What can't you do?

I think it would be cool to create rivers, lakes, ravines, etc with the terrain editor.

### How would you like it to work?

I would like it to work by holding ctrl and extruding down.

### What have you tried?

I have tried, but there is no way to do it right now.

**Comment by handsomematt** [comment]
it already works, you cant extrude below zero height
