### ISSUE TITLE
Crash handler causing amd gpus to crash

### ISSUE THREAD

**Issue by VCSoldier** [Facepunch/sbox-issues#512]
**Describe the bug**
when im playing sandbox, sometimes it will randomly freeze up my computer, and if i look in the reliabilty history i see "sbox.exe" 
and it describes an issue with "crashhandler64.dll"
i have updated drivers after and it has happened again. meaning this must be an issue with the crash handler itself,

**To Reproduce**
Launch sbox on a machine with an amd card, play on a busy multiplayer server, (seems to happen more often online, probably due to the amount of players doing thing), usually happens unexpectedly and out of the blue, really hard to describe how to reproduce
**Expected behavior**
??
**Screenshots**
![image](https://user-images.githubusercontent.com/50423227/127341334-09fa5816-ada6-4965-b40a-8be29980cf65.png)

**Additional context**
this could also be an issue with amd drivers, they are known to be pretty broken and annoying to deal with
Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by Asaduji** [comment]
Same is happening to me, changing video settings (or not changing anything and just pressing apply changes) causes a driver timeout and freezes the whole pc

**Comment by AruMoon** [comment]
> Same is happening to me, changing video settings (or not changing anything and just pressing apply changes) causes a driver timeout and freezes the whole pc

same
