### ISSUE TITLE
Lights Renderer in source particle editor broken

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#5123]
### Describe the bug

Render lights in the source particle editor doesn't work anymore.

### To Reproduce

1. create a particle in the source particle editor.
2. use the lights renderer.
3. load ingame

### Expected behavior

Lights renderer should render lights on particles like they used to.

**Comment by garrynewman** [comment]
This is fixable, but it'd be a day's work, and I can't justify it right now.

For any facepunchers: We need to implement a `IParticleSystemQuery` class, plumb it to use scene/gameobjects, and then make the legacy particle collections use it.

**Comment by aylaylay** [comment]
Lights should work now
