### ISSUE TITLE
UI: Stylesheets linked with <link> in a Template (html file) will not autorefresh

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#513]
**Describe the bug**
Stylesheets linked with <link> in a Template (html file) will not autorefresh

**Expected behavior**
Should refresh

**Additional context**

Example cs:
```csharp
[UseTemplate]
public partial class Skills : Panel
{
// it's empty. UseTemplate will include what I need
}
```

Example html:
```html
<link rel="stylesheet" href="./skills.scss" />

<div class="skills">

</div>
```

**Comment by garrynewman** [comment]
I suspect this is because of the leading "./"  - I'll make it handle that better
