### ISSUE TITLE
Mouse glitches out when moving mouse outside render window while moving camera while on another monitor

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5130]
### Describe the bug

Moving the camera on my other monitors is extremely annoying since the cursor goes crazy when hitting the edge. Might be a differing DPI issue.

### To Reproduce

1. Change DPI on monitor?
2. Move window to second monitor
3. Try to move camera

### Expected behavior

Move like nothing is wrong

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/1517911/ae069ae8-178e-472a-87bf-31cb0462e394

### Additional context

Windows 10, 1920x1080@100%, 3840x2160@150%, 2560x1440@100%

**Comment by aylaylay** [comment]
Should be fixed now
