### ISSUE TITLE
ActionGraph - Let us pass a CancellationToken for async tasks inside of it

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5131]
### For?

S&Box

### What can't you do?

I am unable to stop an actiongraph from finishing once it starts.
Barred for custom nodes with custom signals using some kind of static tokens you can't pass CancellationTokens to an ActionGraph delegate.

### How would you like it to work?

A built-in way to pass CancellationTokens to an ActionGraph, in such a way that sending a cancellation request will stop any async signals from firing off inside of the ActionGraph.

### What have you tried?

For example I was using ActionGraph for AI states, it would have an Idle state and an Attack state.
The Idle consisted of: (async) Wait a few seconds -> (async) Go to a place -> Once you reach the place play an animation -> (async) Wait a few seconds -> Start over
What I needed was a way to stop this if we switched into an attack state, else it would just restart the idle cycle again after a few seconds.
While I did implement a shared CancellationTokenSource which got referenced inside of the "Go to a place" async node, it was useless if we already went over that and were in the phase of waiting a few seconds using the default Delay node.

**Comment by Metapyziks** [comment]
Done, now if you declare an action that accepts a CancellationToken:

```csharp
[Property]
public event Func<CancellationToken, Task> Example;
```

It will automatically forward that cancellation token to any nodes that have CancellationToken parameters:

```csharp
public async Task DoSomethingAsync( CancellationToken ct )
{
	Log.Info( $"Hello: {ct}" );

	await Task.Delay( 2000, ct );
}
```

This includes the default Delay node, which now takes in an optional CancellationToken.
