### ISSUE TITLE
Physics objects can get through Hammer generated collision 

### ISSUE THREAD

**Issue by LVJohnFreeman** [Facepunch/sbox-issues#5132]
### Describe the bug

Interacting with physics seem to be half working rn at times with the map compiled collision.

Generally seem to have props generally fly through certain meshes, in this case on ramps when they are in a specific angle.  Seem to happen most of the time with "tight" phys collision on some custom props of my own. Replicated it with a S&box trashcan seemed to happen less often, but can still happen. Smaller objects however with less accurate collision can still get through the geo, in fact player collider can also push it through by just jumping on it.

### To Reproduce

Map for reproduction. 
Scene+vmap (includes compile)
[debug_sbox.zip](https://github.com/Facepunch/sbox-issues/files/14549821/debug_sbox.zip)

### Expected behavior

Hopefully in this case we just get it not go through geo as easily, would be the expected behavior.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/54272126/b5250d10-2033-49e6-b27f-4f34debe802c

https://github.com/Facepunch/sbox-issues/assets/54272126/fcfe6ca6-4989-488e-9a60-69fdb127bcfb

https://github.com/Facepunch/sbox-issues/assets/54272126/f8e07dc9-4518-4694-bc80-794cfef8e95d

**Comment by aylaylay** [comment]
I'll have to update the physics engine, there might be a fix for this.

**Comment by aylaylay** [comment]
So what's happening is that some of the collision triangles have incorrect winding order. I'm not sure why hammer is generating incorrect winding, I'll have to investigate some more.

**Comment by aylaylay** [comment]
Hopefully will be getting a fix for this tuesday

**Comment by aylaylay** [comment]
I've applied a temp fix, let me know if they still clip through. The player pushing objects through geometry is normal behavior currently.

**Comment by aylaylay** [comment]
This should be fully fixed now!
