### ISSUE TITLE
Scene and prefabs do not load new version from github

### ISSUE THREAD

**Issue by Ethrenduil** [Facepunch/sbox-issues#5133]
### Describe the bug

When I pull the work from GitHub, my local changes are preserved, but my scenes and prefabs don't update automatically. I have to manually delete the .*_c files.

### To Reproduce

1. Pull the changes from GitHub.
2. Notice that your local scenes and prefabs don't reflect the updates.
3. Delete the .*_c files associated with the scenes/prefabs you want to update.
4. S&box will re-import the assets and apply the changes from GitHub.

### Expected behavior

The editor should detect changes in the content.

**Comment by garrynewman** [comment]
```[tasklist]
### Tasks
- [ ] Detect file changes in scene/prefabs
- [ ] Compile/update/reload
```
