### ISSUE TITLE
Component's being removed from Scene Prefabs and GameObjects

### ISSUE THREAD

**Issue by BlakeWinser** [Facepunch/sbox-issues#5134]
### Describe the bug

Custom made components will sometimes be entirely removed after a new compile is completed. It seems to be at random after saving any scripts you have made changes to. The component will either be removed entirely or be replaced with an "unknown component error". 

After a compile and the component disappearing, it won't show up when trying to re-add it to your gameobject. To make it show back up you have to re-save your script.

No console log errors appear other than a potential "Component Missing" if you have any game objects depending on it.

### To Reproduce

1. Place a custom made component on any gameobject.
2. Open the gameobject script in your IDE and compile it a few times after making changes.
3. At what seems to be random, the component may eventually just disappear from your gameobject and is required to be re-added.

### Expected behavior

Once a component has been added to a gameobject it should remain there unless removed or the associated script is deleted and or lost.

### Additional context

Windows 10
VSCode
S&Box Build: Add prefabs for cubemap fog, envmap probe, gradient fog, volumetric fog

**Comment by BlakeWinser** [comment]
> does this happen with `hotload_fast 0`?

Yeah disabled it and am still running into the issue.

**Comment by handsomematt** [comment]
Not seen this before, if you have a more reliable reproduction that'd be good

**Comment by BlakeWinser** [comment]
Issue was resolved with a fresh S&Box and IDE install. I did move my S&Box install and projects into the same directory, could be related to the same issue. Problem solved either way.
