### ISSUE TITLE
For Steam Input, add an extra action set for games that require KBM controls

### ISSUE THREAD

**Issue by Dootama** [Facepunch/sbox-issues#5135]
### For?

S&Box

### What can't you do?

It might sound silly or even redundant, but having the ability for games to manually pick between a controller player using either gamers controls or kbm controls via an extra action set might further simplify things for controller players.

### How would you like it to work?

Add an action set for KBM that will be used by games that don’t have native game pad support, rather than leaving plays to both guess if a game has it and to do it themselves.

![IMG_4966](https://github.com/Facepunch/sbox-issues/assets/138728098/dc7f3cbe-d020-495f-adeb-d1465c2e4e48)
![IMG_4967](https://github.com/Facepunch/sbox-issues/assets/138728098/3e8bf16f-c4c7-47fc-9b11-87f31b1b3767)

### What have you tried?

My current method is just pressing R5 to switch to KBM input as an action layer. I’ve basically just made a manual version of this.

**Comment by Nolankicks** [comment]
I think Tony is reworking the whole steam input system.

**Comment by DevulTj** [comment]
SteamInput is gonna get killed off, so no point in this really
