### ISSUE TITLE
Painting on the edge of Terrain produces errors

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5139]
### Describe the bug

When painting on Terrain, there are errors when painting on the edge. Most likely paint coordinates not getting clamped properly.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/b7b0c808-0578-4307-b227-83e4a516e23b)

### To Reproduce

1. Create a terrain
2. Paint on its edges

### Expected behavior

No errors

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5991682/96eda79a-4415-4bf1-a544-6c924ab35f40

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by Gmod4phun** [comment]
Seems good, thanks
