### ISSUE TITLE
Can't set default value for Vector on Hammer entity.

### ISSUE THREAD

**Issue by AWildErin** [Facepunch/sbox-issues#514]
**Describe the bug**
I can't get a default value working for vector, for example I have this in my code
```cs
[Property( "cover_mins" )]
public Vector3 Mins { get; set; } = new Vector3( 16, 16, 16 );
```
The FGD gen doesn't insert the default value I've specified
```
cover_mins(vector) : "Cover Mins" :  : ""
```
This works with other types such as strings but not vectors and possibly other types I haven't tried

**To Reproduce**

1. Create a new hammer entity and add a vector property with a default value
2. Let the FGD auto gen do its thing
3. Take note of the fact it doesn't insert a default value as it does with strings

**Expected behavior**
It should insert the default value into the FGD, but it doesn't

**Comment by robotboy655** [comment]
This might be a limitation of Reflection that we can't work around.

You can do this however:
```
][Property( "cover_mins" )]
[Internal.DefaultValue( "16 16 16" )
public Vector3 Mins { get; set; } = new Vector3( 16, 16, 16 );
```

**Comment by AWildErin** [comment]
That sucks, but this workaround is better than nothing. If there's not much else to this then this can probably be closed.
