### ISSUE TITLE
LobbyInformation.OwnerId always returns 0

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#5141]
### Describe the bug

Querying lobbies and accessing the lobby's OwnerId always gives you 0.

### To Reproduce

1. Query all the lobbies with Networking.QueryLobbies()
2. Log all the lobbies' OwnerId
3. See that it's always 0

### Expected behavior

LobbyInformation.OwnerId should give the lobby's host's SteamID64 instead of 0.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/19620198/ac7cbd19-972a-41e1-bd97-86ce9aa9ac79)

### Additional context

Would be nice to have this!! I want to use it for our entry's main menu.

**Comment by matekdev** [comment]
Please fix this... we need this for the gamejam... I'm crying right now...

**Comment by ceitine** [comment]
Yeah that'd be nice.

You can get around it by disabling MapInstance MapName updates, setting it to the steam id of the host, and accessing LobbyInformation.Map.

It feels really hacky, so it'd be nice to have a proper alternative.

**Comment by MrBrax** [comment]
being able to set the values on the lobby information dict would probably solve this and a lot of other issues?
