### ISSUE TITLE
Class with the [Proprety] Attribute get their variable reset

### ISSUE THREAD

**Issue by brainkk** [Facepunch/sbox-issues#5142]
### Describe the bug

A Class variable (or class instance rather) inside a class with the Component inheritence doesn't save the changes you do inside the inspector 
![ca5aff52cdcba034bc3f5693676ade3a](https://github.com/Facepunch/sbox-issues/assets/139790506/9a230739-db13-4c2e-84c1-e54e3f3d31dc)

### To Reproduce

1. Make a class component, let's call it 'A' and put it inside a GameObject
2. make another class, let's call it 'B'
3. inside 'A' make a float for exemple.
4. Create a 'B' variable inside the 'A' class with the [Proprety] Attribute
5. Go to the inspector and edit the values
6. press play and check the values on the edit tab

In Scene Mode sometime it has the correct value, but in Game it never does, you can just Log.Info the float to see that the problem persist
### Expected behavior

The expected result should be retaining the values prior pressing play

**Comment by DevulTj** [comment]
Show the code, is it a field, or a property?

**Comment by brainkk** [comment]
i've tried as a field and as a proprety with every combinaison possible (make it public, private, put a default value, remove the "set;" in the proprety...)

![c97f468ba4f1c1176338ff1fa3a791c3](https://github.com/Facepunch/sbox-issues/assets/139790506/dc348843-450b-4f41-8fd3-9b4bf9f36e7b)
--

![9b042b0b3f4743c34418cf79536eab9c](https://github.com/Facepunch/sbox-issues/assets/139790506/0cacc07c-0ccf-4806-a60a-928d0788526a)


keep in mind that in the screenshots i reference the variable alot but this is only because i've given up with changing it in the inspector, on my initial test i only used those variable for logging the value.

**Comment by brainkk** [comment]
OK so i finally figured it out. Basically you need to do Scene -> Save ALL instead of CTRL+S  or Scene -> Save

turns out it was not  a bug, only a feature
