### ISSUE TITLE
Inspector - Quality of Life Feature Requests

### ISSUE THREAD

**Issue by Sunday5465** [Facepunch/sbox-issues#5143]
### Feature Request

- **Drag component headers within the inspector in order to rearrange them.**
_As of now, the only option to move components within the inspector list is either clicking the three-dot menu or right clicking, then selecting the 'Move Up/Down' option. This works just fine, but unfortunately needs repeating however many times you need in order to move the component into place, which can be very tedious._

- **Use a three-dot/right-click menu option to replace one component with another.**
_Not as necessary if the first feature were to be implemented, but I still think it would be a convenient addition._

- **Change an editor setting to adjust 'Add Component' list size.**
_Currently, only a maximum of 10 items may be shown within the add list. With how often this list is used, I think an option to show more would be quite helpful. Maybe in the form of a slider with a range of 10 to X, with the final tick being 'Max' which shows as many as possible within the given screen space? That may seem like going overboard, but I'm sure there will eventually be people with a ton of custom components (probably me) that would like to see as many as possible while also minimizing scrolling._

_PS. I tried using an issue template, but it gave me an error so I'm using a blank one instead._

**Comment by Sunday5465** [comment]
Whoops, apparently the first one already exists in an issue made by ducc in #4254. Sorry about that, I should have done a better search beforehand. That said, since I couldn't find anything on the other two, I'd still consider this open.

**Comment by handsomematt** [comment]
We appreciate the feature requests, but could you create individual issues for each one. I think dragging component headers is already in the backlog too

**Comment by Sunday5465** [comment]
Sure thing 👍
