### ISSUE TITLE
Can't change Hull Cylinder Radius anymore

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5146]
### Describe the bug

Not sure when this happened but the Radius property was removed so I can't change the size of this hull:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/a888047d-6570-4eae-9a40-26288af3eea4)

### To Reproduce

Create a Hull Collider and set the type to Cylinder and see there is no Radius property

### Expected behavior

You should be able to change the radius property

**Comment by aylaylay** [comment]
Should be working now
