### ISSUE TITLE
Protection from cheaters who using ducc injector

### ISSUE THREAD

**Issue by 12Reddit12** [Facepunch/sbox-issues#5149]
### For?

S&Box

### What can't you do?

I cant catch people who use the injector and close the game for them. They inject code which create new convar command
then he open console , write command and call rpc with his own purpose and make anything with game.

### How would you like it to work?

Or suggest a solution yourself that may be useful or add viewing STEAMID64/Profile user to the list of errors
![image](https://github.com/Facepunch/sbox-issues/assets/46645343/d515ea71-2bf2-499d-a633-22c9c2ddfcf4)
here is only count of users and cant get steamid or profile
In future i wonna just make banlist with steamid and when ppl join my game game is close.

Or make obfuscation code, and then ducc injector will be not hackable purpose

### What have you tried?

I tried to close cheat engine and something process which can inject, but s&box gamemode restrict access with system, i cant get processes and close them.

### Additional context

Maybe it’s useless now, but it bothers me that someone breaks the game and then writes in reviews that the game is buggy and broken

**Comment by handsomematt** [comment]
We're not adding an anticheat to a sandbox game. You should code your game so your RPCs can't be abused.
