### ISSUE TITLE
I get an error when i launch s&box in my windows 10

### ISSUE THREAD

**Issue by STROGENUFF** [Facepunch/sbox-issues#5150]
### Describe the bug

my gpu is a rtx 3060. The error says: CAppSystemDict::LoadSystemAndDependencies():AppSystemDict: Error in Init() of interface 'RenderDeviceMgr001'!
![image](https://github.com/Facepunch/sbox-issues/assets/106346017/c5c5a159-43a8-4919-8a29-8202d457908a)

### To Reproduce

1. i click play s&box 2. i select the mainlaunch option 3. and then i get the error

### Expected behavior

The game should just, launch

### Media/Files

This is the log
[Log.log](https://github.com/Facepunch/sbox-issues/files/14563856/Log.log)

**Comment by handsomematt** [comment]
Is this a laptop? If so can you update your integrated graphics drivers.

If not can you [run vulkaninfo](https://nvidia.custhelp.com/app/answers/detail/a_id/5429/~/running-vulkan-info) and post the results here please.

**Comment by STROGENUFF** [comment]
> Is this a laptop? If so can you update your integrated graphics drivers.
> 
> If not can you [run vulkaninfo](https://nvidia.custhelp.com/app/answers/detail/a_id/5429/~/running-vulkan-info) and post the results here please.
[Vulkaninfo.txt](https://github.com/Facepunch/sbox-issues/files/14570704/Vulkaninfo.txt)

I have obtained many results so I have put them in a text file.

**Comment by handsomematt** [comment]
Can you either update or uninstall Twitch overlay and see if that fixes it. If it doesn't can you post your vulkaninfo again to confirm it was removed

**Comment by STROGENUFF** [comment]
i uninstalled twtch overlay 
[Vulkaninfo(1).txt](https://github.com/Facepunch/sbox-issues/files/14573910/Vulkaninfo.1.txt)

**Comment by STROGENUFF** [comment]
it is fixed! it doesn't crash. TYSM
