### ISSUE TITLE
FBX preview

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#5152]
How hard would it be to get the fbx file generating a preview?

![Image](https://github.com/Facepunch/sbox-issues/assets/928843/fa631e39-369f-4b3d-ab9a-c03b51e3e494)

Could we have a 3d preview in the inspector too?

**Comment by aylaylay** [comment]
![sbox-dev_uPe3bKuNAh](https://github.com/Facepunch/sbox-issues/assets/1667289/0eb72894-9337-44f7-a2df-bcea79b31eb8)

**Comment by aylaylay** [comment]
Can you post the full log for fbx

**Comment by aylaylay** [comment]
Can you upload a fbx that it's failing on?

**Comment by KaesarZZ** [comment]
Huh alright, I only have the 2 .fbx's that I use to do the eye blink in Adam/Frank and even when I try to play them in modeldoc I already get the stall, I guess after your update...?

Anyway: 
https://drive.google.com/file/d/1ekbjQF9zYZS6laVpK1PmpcuzHpBSloCH/view?usp=sharing

If you need all the playermodel source files open me dm on discord or give me email.

**Comment by aylaylay** [comment]
Hopefully it shouldn't crash now. It might take a long time to load, we need to async this but your meshes have a crazy amount of data in them for some reason.

**Comment by KaesarZZ** [comment]
Thanks it's working, yeah I just cleaned the .fbx of useless morphs for an eye blink anim

**Comment by aylaylay** [comment]
Fantastic
