### ISSUE TITLE
[Sync] should be able to be set by the host directly, or a shared one between host and owner

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5153]
### For?

S&Box

### What can't you do?

Right now I have to make broadcast functions just to set a variable on something that I want both the host and owner to have access to, which becomes really bloated. Setting the GameObject transform on a player by the host becomes really unwieldy.

### How would you like it to work?

Either [Sync] should become changeable by the host or another attribute that both can change.

### What have you tried?

[Broadcast] spam and directly accessing the variables. [HostSync] can't be changed by client and [Sync] can't be changed by host.

**Comment by MrBrax** [comment]
Thanks very much! Does this change the sync behaviour on GameObject.Transform?

**Comment by kurozael** [comment]
> Thanks very much! Does this change the sync behaviour on GameObject.Transform?

Nope only the owner can change the Transform of an object. You'll need to use a Broadcast or Authority to change that elsewhere.

**Comment by MrBrax** [comment]
Ok, thanks. I will try to find a workaround.
