### ISSUE TITLE
[Shadergraph Bug]

### ISSUE THREAD

**Issue by audiotrope** [Facepunch/sbox-issues#5156]
### Describe the bug

Use of the XY output on the Screen Position node produces an error on compilation.

### To Reproduce

1. Open shadergraph
2. Place a "Screen Position" Node
3. Drag a connection off of "XY" to input any other input.
4. Wait for preview to compile

### Expected behavior

[bugshader.txt](https://github.com/Facepunch/sbox-issues/files/14566023/bugshader.txt)

### Media/Files

{
  "Model": null,
  "Description": "",
  "BlendMode": "Opaque",
  "nodes": [
    {
      "_class": "Result",
      "DefaultOpacity": 1,
      "DefaultRoughness": 1,
      "DefaultMetalness": 0,
      "DefaultAmbientOcclusion": 1,
      "Identifier": "0",
      "Position": "160,-96",
      "Albedo": {
        "Identifier": "1",
        "Output": "XY"
      }
    },
    {
      "_class": "ScreenPosition",
      "Identifier": "1",
      "Position": "-368,-64"
    }
  ]
}

**Comment by aylaylay** [comment]
Should be fixed now
