### ISSUE TITLE
[ModelDoc] Right Click - Create Model Not Automatically Creating LODs

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#5159]
### Describe the bug

When exporting models I usually name my LODs in blender as model_lod0, model_lod1 etc so that once I import it into s&box they are automatically set up in ModelDoc.

This seems to have broken pretty recently as it was working last week.

New vmdl's are also created with "Globally Replace All Materials In Model" ticked and a PhysicsHullFromRender that's not usually there.

### To Reproduce

- Download the example FBX [suzanne.zip](https://github.com/Facepunch/sbox-issues/files/14566425/suzanne.zip)
- Extract in a sbox project folder
- Right Click the fbx in the sbox asset browser and select Create model...
- Save the new vmdl and open in ModelDoc

### Expected behavior

After creating a model there should be LODGroups for each LOD level and a RenderMeshFile for each LOD level with names for each one.
![image](https://github.com/Facepunch/sbox-issues/assets/60801006/7d5942fe-49aa-4305-b8c4-d37b8f2bb097)

### Additional context

Video of how it used to work here: https://wiki.facepunch.com/sbox/automatic_model_setup

I don't mind the automatic PhysicsHullFromRender being added.

**Comment by ShadowBrian** [comment]
Could be good to iterate over the materials it's asking for and letting you select them instead of just the blanket white material set to replace all of them, can be confusing.

**Comment by aylaylay** [comment]
It should be adding all the stuff it did before now

**Comment by Jammie3d** [comment]
Seems to be working nicely now, thanks!
