### ISSUE TITLE
Hide websocket behind the developer site

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#516]
**What can't you do?**

I want my game to connect to a self made server, but don't want the ip of the server to be accessible in my code.

**How would you like it to work?**

When "Custom Networking" is ticked, you should get a textbox input that allows you to input the ip of your custom server
![image](https://user-images.githubusercontent.com/5159369/127419852-0bbcf4a4-13d1-4806-87a8-c8c10f039259.png)

Then, you can get this information through code so it's hidden from anyone who doesn't have access to your organization.

**Comment by Rohansi** [comment]
This doesn't really make sense. The game will need the IP address to be able to connect to your server whether its in the code or not. This wouldn't hide your IP, it will only move it somewhere else.

**Comment by cklidify** [comment]
> This wouldn't hide your IP, it will only move it somewhere else.

That's not true, others can access your source by checking the `sbox\downloads` folder or if your project is open source on Github. I want to hide that IP from being found via those avenues, while still retaining functionality and gaining the ability to update the IP without updating the game mode itself

**Comment by deadmonstor** [comment]
> > This wouldn't hide your IP, it will only move it somewhere else.
> 
> That's not true, others can access your source by checking the `sbox\downloads` folder or if your project is open source on Github. I want to hide that IP from being found via those avenues, while still retaining functionality and gaining the ability to update the IP without updating the game mode itself

I think what Rohan was trying to say is that it wouldn't matter as it would have to be exposed to the code at some point anyways if you wanted to connect to it

**Comment by robotboy655** [comment]
You don't even need to look for it in the code, any packet sniffer will easily get it for you. Unless what you are asking for is a free VPN or something like it.

**Comment by WilliamVenner** [comment]
CloudFlare WebSockets have pretty permissive usage quotas on the free plan.

If you can put a domain in that custom networking field, just use CloudFlare.
