### ISSUE TITLE
Editor - restarting editor invalidates sound events from asset.party

### ISSUE THREAD

**Issue by DarkReaper231** [Facepunch/sbox-issues#5164]
### Describe the bug

When I create a sound event and I put a sound event from asset.party in it, it works fine in the editor but doesn't get published
causing null pointer exceptions. Now the funny part is that even if you have `DeathSound != null` check, it still throws it.

```c#
if ( DeathSound != null )
{
	var sound = Sound.Play( DeathSound, Transform.World.Position );
	sound.Pitch = 1.5f;
	sound.Volume = .5f;
}
```

Because it throws it specifically on line `sound.Pitch = 1.5f;`. My theory is that the sound event itself is getting published but
the corresponding audio file isn't. Or maybe the published game sees that there is actually some sound event cuz the field
in editor isn't left empty so it thinks it is not null but it is down the line.

Also if I drag the sound events, it shows like this
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/7cd432aa-2b48-415b-90a7-a32116e8294b)

But when I restart the editor it suddenly shows like `Unknown Sound Event` so that's probably also related.
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/f57c2b2f-2e6a-447d-9a29-20c2313a59d8)

### To Reproduce

1. Create new sound event
2. Drag a sound event from asset.party into it
3. Publish the game

### Expected behavior

The sound events should get properly published with the game

**Comment by garrynewman** [comment]
Do you have a link to your asset party game? It'll show what files are included in the manifest of the version, can I take a look please.

**Comment by DarkReaper231** [comment]
> Do you have a link to your asset party game? It'll show what files are included in the manifest of the version, can I take a look please.

Sure, here it is 
https://asset.party/daark/hamsterescape

**Comment by DarkReaper231** [comment]
I was sure that I heard the audio at least once before and I was halucinating. In this version it got uploaded:
https://asset.party/daark/hamsterescape/version/50288
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/d033c2f4-24b6-4e2b-a4f7-f21e82add4ab)

However in this version it no longer gets uploaded:
https://asset.party/daark/hamsterescape/version/50687

**Comment by DarkReaper231** [comment]
I'll try removing my custom sound, maybe if you have own sound, it can't upload asset.party one?
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/14aa98b9-087c-456c-b33e-86cd54736dcb)

**Comment by DarkReaper231** [comment]
Yeah that seems to be the case actually
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/fadf1445-8366-4132-953f-7b35b6cbe076)

**Comment by garrynewman** [comment]
thanks, this gave me something to investigate

**Comment by DarkReaper231** [comment]
> thanks, this gave me something to investigate

For now the work around is just re-adding the sounds before publishing to ensure they get published

**Comment by garrynewman** [comment]
I found the problem - this should work lovely now - please let me know

**Comment by garrynewman** [comment]
It just wasn't loading the cloud files on startup for .sound extensions, thanks for confirming!
