### ISSUE TITLE
`Mouse.Delta` no longer works in UI

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#5169]
### Describe the bug

I use `Mouse.Delta` in different parts of my UI and it doesn't report any values anymore after a change made sometime yesterday.

### To Reproduce

In my case...
1. Create a full screen panel with pointer events
2. Print `Mouse.Delta` in the tick method
3. Notice it is 0.0

### Expected behavior

We should be able to get the mouse delta, similar to how `Mouse.Position` works fine in UI.

### Additional context

This worked fine up until a s&box update about a day ago. Would be nice to have an alternative or a fix because there are multiple parts in our gamejam project that use this.

**Comment by matekdev** [comment]
Maybe related to some of the OnPreRender changes Garry made? @garrynewman https://discord.com/channels/833983068468936704/835035328779518023/1217062867858362388

**Comment by garrynewman** [comment]
That is likely the case, I will investigate today
