### ISSUE TITLE
Steam Audio Crashing game

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#5172]
### Describe the bug

Steam Audio is causing game to crash, seems like when sounds are being played. Not sure how to reproduce, might be when multiple are being played.
![image](https://github.com/Facepunch/sbox-issues/assets/105941502/73f2f1e6-9c31-4612-a83c-86b56978d571)

### To Reproduce

Unsure but this shows the line of code that's causing the issue maybe.

### Expected behavior

Should not pop up and crash the game

**Comment by garrynewman** [comment]
I don't suppose you've found a good way to reproduce this? I'm not sure what I could be doing to cause it

**Comment by handsomematt** [comment]
Same as #5140 and there's a reproduction there with NaN rotations
