### ISSUE TITLE
SoundEvent's TypeSerialization Error

### ISSUE THREAD

**Issue by kira0x1** [Facepunch/sbox-issues#5174]
### Describe the bug

Clicking or creating a new sound event will throw a "TypeSerializedProperty" error.

```
TypeSerializedProperty Error setting [System.Collections.Generic.List`1[Sandbox.SoundFile]](arg:0) to [System.Collections.Generic.List`1[Sandbox.SoundFile]](arg:1) ([System.Collections.Generic.List`1[Sandbox.SoundFile]](arg:2))
```

### To Reproduce

1. Click or Create a sound event
2. View console log

### Expected behavior

Should not be causing an error

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/13779328/4fbd3ece-d7c8-497b-a5e9-7a38b8fc92c0)
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/23ffbc95-69ab-4e24-bed7-4da28b0df985)

### Additional context

os: windows 11
gpu: 3070ti
ram: 32gb ram,
cpu: intel i5-12400F

**Comment by aylaylay** [comment]
I'm clicking sound events and it's fine?

**Comment by kira0x1** [comment]
> I'm clicking sound events and it's fine?

![image](https://github.com/Facepunch/sbox-issues/assets/13779328/edc65884-c0fb-47a6-bd33-30d40828af21)
weird it just happened again. does it not happen for you after creating a new asset?
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/ac9cf57f-b8f1-4429-be9b-4184a0499ff3)

**Comment by MrBrax** [comment]
![1712044083 c XHT6d](https://github.com/Facepunch/sbox-issues/assets/1517911/19bf7b9e-cbd8-4450-a0df-4b8f8745aba0)

it indeed happens on a new sound event creation, been for a while now but i don't think it actually breaks anything

**Comment by kira0x1** [comment]
> ![1712044083 c XHT6d](https://private-user-images.githubusercontent.com/1517911/318688995-19bf7b9e-cbd8-4450-a0df-4b8f8745aba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODY1MDIsIm5iZiI6MTcxMjA4NjIwMiwicGF0aCI6Ii8xNTE3OTExLzMxODY4ODk5NS0xOWJmN2I5ZS1jYmQ4LTQ0NTAtYTBkZi00YjhmODc0NWFiYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMTkzMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA1MGE1MTAxNGI1OTQxMWU4NWQ0MDM4ZWZhMGVhOGRkYTRjNWVlNGMyOTY5NDFlMmQ5NDc2MDhmZWE0NjI3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jpKrnfxNMyXehDimSQNXdQtcv6S8UQLRp9T2adC4nd8)
> 
> it indeed happens on a new sound event creation, been for a while now but i don't think it actually breaks anything

yeah its still usable just something that could possibly cause issues in the future. At the moment it doesnt break anything unless its the reason why sometimes my sound event files dont save properly after editor restart
