### ISSUE TITLE
Source Particle System collisions broken.

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#5175]
### Describe the bug

Collisions from traces mode for Source Particle Systems doesn't work ingame.

### To Reproduce

1. Create a particle in source particle editor.
2. Give it 'Basic Movement' and 'Collision via Traces'
3. Load it ingame

### Expected behavior

Particles should collide with the world.

**Comment by garrynewman** [comment]
Same solution as #5123
