### ISSUE TITLE
Crash to desktop whenever hitting asteroid in Aluminum Acrobat

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5178]
### Describe the bug

Hitting an asteroid in Aluminum Acrobat crashes the game if you have no shields.
Steam ID: 76561198000586141

### To Reproduce

1. Open the game Aluminum Acrobat
2. Start a new game or continue an existing game
3. Hold down the space bar
4. Eventually, you're gonna hit an asteroid
5. If you have no shields when hitting the asteroid, the game crashes

### Expected behavior

The game should not crash to desktop

### Additional context

The issue began either today or late yesterday.

**Comment by chrisspieler** [comment]
Here's the repo for the game: https://github.com/chrisspieler/sbox-space-game
main.scene will put you right in to the game so you can easily follow the repro steps from there

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by chrisspieler** [comment]
Yup, no more crashing!
