### ISSUE TITLE
Rpc.CallerId / Rpc.Caller returns the host connection when joining via new instance

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5179]
### Describe the bug

In a broadcast/authority function, CallerId/Caller will always return the host connection even though it's the new instance that's calling.

### To Reproduce

1. Make broadcast function
2. Log the CallerId
3. Run it via new instance

### Expected behavior

Separate caller id's

**Comment by kurozael** [comment]
Hmm can't seem to reproduce this one...

**Comment by MrBrax** [comment]
I will try to investigate more then, maybe I was doing something wrong last night.

**Comment by MrBrax** [comment]
I had accidentally called the entire thing on the host, as I didn't think about trigger listeners being called on everyone. I was calling an authority function from the host itself.
