### ISSUE TITLE
SceneUtility Error

### ISSUE THREAD

**Issue by kira0x1** [Facepunch/sbox-issues#5180]
### Describe the bug

Not really sure how this happened, but got this error 
```
 toolbase  [2] 'SceneUtility.MakeGameObjectsUnique(JsonObject, Guid?)' is obsolete: 'Use MakeIdGuidsUnique'
```

### To Reproduce

I'm really sorry but honestly not sure.

### Expected behavior

Should not be causing this error.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/13779328/4f4781cd-9b64-46ab-a68c-0046bcedf270)
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/73249e37-65b6-4bb3-8fb2-c3cc71578eca)

### Additional context

os: windows 11
gpu: 3070ti
ram: 32gb ram,
cpu: intel i5-12400F

**Comment by kurozael** [comment]
Sorted in next build :)

**Comment by kira0x1** [comment]
> Sorted in next build :)

ty <3
