### ISSUE TITLE
GameTask.Delay (and other variations) do not accept a CancellationToken overload

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5182]
### Describe the bug

System Threading's Task.Delay accepts a CancellationToken, but s&box's GameTask does not.

### To Reproduce

Try to use a CancellationToken in a GameTask.Delay

### Expected behavior

GameTask.Delay should accept the CancellationToken

**Comment by kurozael** [comment]
I think @Metapyziks added this?

**Comment by Retroeer** [comment]
Totally forgot to answer, but yeah its added, thanks ziks
