### ISSUE TITLE
NavMesh Not Creating / Updating when a door with hinge component is in the scene 

### ISSUE THREAD

**Issue by R3N10** [Facepunch/sbox-issues#5184]
### Describe the bug

Navmesh is not creating neither updating when a door with a hinge component is present, as soon as the hinge component is disabled, navmesh generates.
lets say you create, a prefab of a room, that has a door with a hinge component in it, and you make a clone of the gameobject while game is running, and in navmesh properties you have exlcude bodies "trigger", when cloning the room, navmesh wont update 

### To Reproduce

1. create a prefab that has a plane and a door with a hinge
2. exlude bodies with tag trigger in navmesh properties
3. run the game, and in the scene view, add the prefab
4. then update the navmesh

### Expected behavior

Navmesh should be updating without problems, because neither the door  or the plane have a trigger tag

### Media/Files

The prefab:
![image_2024-03-14_090225887](https://github.com/Facepunch/sbox-issues/assets/161184288/d76e06d0-f165-48de-ba48-d29541ec58eb)
The Navmesh properties:
![image_2024-03-14_090322417](https://github.com/Facepunch/sbox-issues/assets/161184288/91203cc3-ab6a-46c3-92cf-cb1f8b951c18)
The Scene (With Prefab Already in it):
![image_2024-03-14_090358200](https://github.com/Facepunch/sbox-issues/assets/161184288/f1cbab14-f4c8-4b94-b866-ea4542b7da50)
The Game When Running as it is :
![image_2024-03-14_090432910](https://github.com/Facepunch/sbox-issues/assets/161184288/b17ebb70-be67-4855-b48b-65f3a9a04acc)
Adding Same Prefab To scene while game is running:
![image_2024-03-14_090504940](https://github.com/Facepunch/sbox-issues/assets/161184288/e55de820-d72f-4206-a8f1-a4b05a993a46)
Error When updating navmesh:
![image_2024-03-14_090544031](https://github.com/Facepunch/sbox-issues/assets/161184288/e5ebdf78-360e-4d1d-bcdc-ab8d43908cbb)

**Comment by aylaylay** [comment]
Downloadable repro, i have no idea what you're doing here

**Comment by aylaylay** [comment]
I have pushed a possible fix, can you test it for me please?
