### ISSUE TITLE
Trace.Ray hit normals on physics traces against terrain have completely illogical values

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#5185]
### Describe the bug

Trace.Ray hit normals on physics traces against terrain have completely illogical values.

https://github.com/Facepunch/sbox-issues/assets/11138884/72aa48d9-70a6-4e38-8f3b-1ad4b3767a7f

In the video I'm just doing a basic ray trace against terrain and against models, you can clearly see the difference

### To Reproduce

Trace against terrain, see normals are all fucked

### Expected behavior

Trace against terrain, normals follow terrain

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by ShadowBrian** [comment]
Works! Thanks!
