### ISSUE TITLE
[Scene Mesh Editor] Gizmos(?) break if selected and then go into play mode

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5187]
### Describe the bug

If you have, for example, an edge of a mesh selected, and then go into play mode, trying to move the edge will create this "phantom" effect.
This effect goes away if you click off and click back on though

### To Reproduce

1. Select the edge of a mesh
2. Go into play mode
3. Transform it

### Expected behavior

The edge should be transforming properly in the play mode version.

**Comment by aylaylay** [comment]
Does this happen to game objects too?

**Comment by Retroeer** [comment]
Nope, only scene mesh, for some reason

**Comment by aylaylay** [comment]
Should be fixed now
