### ISSUE TITLE
change of place in the waiting list

### ISSUE THREAD

**Issue by dev-Rustam** [Facepunch/sbox-issues#519]
**Describe the bug**

1. Go to 's&dev login'
2. Click on 'login'

a few days ago I registered on the site to have dev access on gmod. At that moment I was told that I was 1000th and that I would have access to the game in a few days and now he tells me that I am 10,446 / 16,819 and that I would have access normally in 5 MONTHS

I really want to have the dev access to be able to develop on what will be one or rather the best game ever to create. I hope this bug will be resolved quickly

**Comment by AdamSai** [comment]
It's not a bug. People who have made more contributions to the Garry's Mod workshop joined the queue, or their data was updated and you got pushed back.
![image](https://user-images.githubusercontent.com/11211186/127461819-8ec38d0f-0e74-42aa-8de1-e5e9a1e86d88.png)
