### ISSUE TITLE
OnCollisionStart is capable of running before OnStart finishes 

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5193]
### Describe the bug

If your Object collides immediately upon spawning, OnStart does not properly run/finish, resulting in any references set in OnStart to become null

### To Reproduce

1. Set references in OnStart
2. Use references in OnCollisionStart
3. witness as they are null if the object collides immediately upon spawning

### Expected behavior

OnStart should properly run/finish before OnCollisionStart is called

**Comment by aylaylay** [comment]
Physics step runs before component update, OnStart runs just before the first component update so this is to be expected. If you have references to set you need to do them in OnEnable, instead of OnStart.

**Comment by Retroeer** [comment]
Understandable
