### ISSUE TITLE
Display Guid in Properties

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5195]
### For?

S&Box

### What can't you do?

Can't see a Guid in a GameObject's properties
![sbox-dev_JxK1bCbMXk](https://github.com/Facepunch/sbox-issues/assets/44037603/5914d980-a5e0-4d7f-b244-c128e028c333)
### How would you like it to work?

Convert it to a read-only string for you maybe?

### What have you tried?

Converting the Guid to a string and displaying that instead
![sbox-dev_Mfa6xKqw8W](https://github.com/Facepunch/sbox-issues/assets/44037603/bd4c75fe-ab10-49ba-b9c4-87bfd745b7a2)

**Comment by garrynewman** [comment]
Done

**Comment by MrBrax** [comment]
Where was this added? Am I blind?

**Comment by Retroeer** [comment]
if you make a Guid property it should just display the id now

**Comment by MrBrax** [comment]
Ok i think i misunderstood this, i thought it started showing the currently select gameobject id, that would have been useful.
