### ISSUE TITLE
Modeldoc crashes when parenting an AttachmentList to a bone

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#52]
**Describe the bug**

Modeldoc crashes when parenting an AttachmentList to a bone

**To Reproduce**

1. Open modeldoc and add a few bones and attachments.
2. Right click on the attachment list.
3. Chose a bone to parent to.
4. Crash.

**Expected behavior**

Either parent all the attachments to the same bone or don't give the option to parent an attachment list.

**Screenshots**

![image](https://gyazo.com/1fe3adf4cb17bbdddac38cb161a68989.png)

**Comment by aylaylay** [comment]
I have made it so the "Reparent Attachment" wizard doesn't show up for AttachmentList node. It would be easy enough to support but I don't think it's worth doing seeing as you can just select all the nodes in the list and reparent them.
