### ISSUE TITLE
Local Space Particles Lag Behind

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5200]
### Describe the bug

I have a particle effect component with the movement space set to Local, but as you can see, the particles lag behind the game object they're attached to.

I think this might be because the game object these particles are attached to are part of the same hierarchy as the camera, which might be the cause the lagging effect.

The particles are a child of the sword, which is a child of the players skeleton. The camera is also a child of the players skeleton.

https://github.com/Facepunch/sbox-issues/assets/7847372/2e2a218a-b77e-45b9-9d86-b86340bb680a

### To Reproduce

1. Attach local movement particles to a game object
3. See that it lags behind

### Expected behavior

Particles should not lag behind.

**Comment by Fortune117** [comment]
Can also see something fucky with the velocity of particles in this context as well:


https://github.com/Facepunch/sbox-issues/assets/7847372/5de1e99e-0c3d-467c-bb86-aaf1d47420bc

**Comment by timmybo5** [comment]
Running into the same issue, would be nice if this got fixed :D 


https://github.com/Facepunch/sbox-issues/assets/4988198/b4e293d8-bd98-41d3-a748-a80bc27483bd

**Comment by Fortune117** [comment]
[bug_repo.zip](https://github.com/user-attachments/files/16435128/bug_repo.zip)

repo with bug

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/30bfe1b8-7c06-4fe9-8802-27e417fc7aea

Should be fixed now
