### ISSUE TITLE
References not being reset after Destroying a Referenced GameObject

### ISSUE THREAD

**Issue by xLyviNx** [Facepunch/sbox-issues#5202]
### Describe the bug

(Not sure if it's just me)
Basically I have a GameObject that I later destroy inside of a component attached to it (GameObject.Destroy() or DestroyImmediate()), and if other GameObject had a reference to it inside of its Component, it may even show None in inspector, but even a simple == null check says it's not null (even if Inspector shows None)
If there is a Component reference though that works simply by **get{return GameObject.Components.Get<>}**  the Component reference is visible in the Inspector, but not the GameObject it's attached to.
Tried re-doing it in different package/project, still happened to me.

### To Reproduce

1. Make a GameObject
2. Attach a new Component to it
3. Reference the GameObject in a different GameObject and its component.
4. Make the Component Destroy the GameObject at some point
5. Log.Info the GameObject that you just destroyed
6. GameObject is gone from the Scene and Inspector, it's gone from Scene.Directory.FindByGuid, but it's still being printed in the Console and you can access its properties or even probably clone it. The code still has the reference.

### Expected behavior

GameObject should be gone and reference should become null/none instead.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/51911607/92e38fa3-282d-48fb-bc1b-45bc1fffd2cb)
![image](https://github.com/Facepunch/sbox-issues/assets/51911607/7b2feded-215d-437c-93e5-8448fcf1ec61)

### Additional context

Windows 11, 32 GB Ram DDR4, Ryzen 5 3600

**Comment by garrynewman** [comment]
The object doesn't cease to exist when you destroy it. It only gets fully destroyed when nothing can possibly access it again.

To check whether something exists, you can use .IsValid()

**Comment by xLyviNx** [comment]
Isn't it possible to set all references to none/null if the GameObject is not valid then automatically anyway?
If it's even possible, I know I could just do it manually in Update then, or do a getter that does it (unless the GameObject is not valid also in other scenarios) but if it was automatic then it would be way more comfortable and maybe intuitive and more predictable (at least for people that moved from Unity)

**Comment by garrynewman** [comment]
Unity does this by overriding the null comparer on their objects so that if they're released, `== null` will return true. I don't like that, and I think it causes more trouble than it's worth.

Yeah we can't iterate and destroy. Best to get into the habit of doing `obj.IsValid()` instead of `obj is null`.
