### ISSUE TITLE
prop_physics in Hammer gets turned into SkinnerModelRenderer instead of a normal ModelRenderer

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5203]
### Describe the bug

Using prop_physics in Hammer for stuff like trees is an FPS killer because it uses SkinnedModelRenderer, and using prop_static means the trees can't use LODs so we are at an impasse.

### To Reproduce

1. Mark an object in Hammer as props_physics
2. Compile the map
3. View in scene

### Expected behavior

For prop_physics to have a Model Renderer component instead

### Additional context

Preferrably prop_static should load the LODs but I'm not sure how feasible that is, I swear it used to work though.

**Comment by yuberee** [comment]
EDIT: Seems like prop_static works with LODs but you have to set the LOD Level to -1 instead of the default 0

**Comment by aylaylay** [comment]
Good to know that lods work with prop static, i had a feeling they did. But we'll get this fixed. We shouldn't be creating skinned when not needed.

**Comment by aylaylay** [comment]
I've made it so it will only created skinned model renderer if the model has skinned meshes or morphs
