### ISSUE TITLE
Steam Audio has poor performance

### ISSUE THREAD

**Issue by the-remeko** [Facepunch/sbox-issues#5204]
### Describe the bug

Playing sounds dramatically lowers FPS regardless of the geometry around them. Games that involve multiple guns shooting at a reasonable rate are heavily affected by this.

### To Reproduce

Make a new scene without any physics objects and a component that plays a sound every .12 seconds. I have attached a repro project that does this. My FPS goes down by 26% when I toggle on the sound-playing component, and the scene is just a void. It's even worse in an actual game with visuals, physics, and even more sounds playing.

### Expected behavior

Playing sounds should not tank FPS.

### Media/Files

[steamaudiolag.zip](https://github.com/Facepunch/sbox-issues/files/14620949/steamaudiolag.zip)

**Comment by garrynewman** [comment]
What does the profiler look like when doing this?

**Comment by Xenthio** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/28588188/8cba4bf8-8362-40e8-93ad-36a1f9580672)
The performance graph looks like this, You can see the parts where sounds are being played (yet again, every 0.12 seconds) and where they're not.

**Comment by garrynewman** [comment]
Yep that sucks, I assume it's going to be the occlusion tests
