### ISSUE TITLE
Sound importing is completely broken.

### ISSUE THREAD

**Issue by MarkoKuzmanovic** [Facepunch/sbox-issues#5206]
### Describe the bug

Get a bunch of .wav and .mp3 sound files, drop them into my project library, some of them work great, the rest are completely silent, check files and they all work great. attempted quite litterally everything to fix, recompiles, turning compression on and off, different audio formats, upon reseting the editor, random audio files get broken while random ones start working again..

### To Reproduce

1. Get a bunch of audio files
2. Drop them into your project library
3. Attempt to preview them 
4. Wont work

### Expected behavior

what should be happening is that all of these audio files are getting imported correctly and not half broken.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/52082941/be3df92e-77dd-4e59-b0c4-7534ee9994db)

**Comment by garrynewman** [comment]
The whole sound loading code is a bit confusing and weird, but I think I mostly solved it. We can do a better job in the future, but this should get you back on the road for now.
