### ISSUE TITLE
If a project folder has `-test` anywhere in the name, the project won't launch.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5208]
### Describe the bug

I tried to rename the folder of my project to "sbox-driving-test", but I wasn't able to launch afterwards.
Figured out that including "-test" anywhere in the folder's name will prevents the project from launching.

Katka managed to reproduce this. (ty)

### To Reproduce

Include `-test` anywhere in the folder name.

>Launches
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/64144d67-2e7c-40af-a250-bf8561d4288c)
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/1924965f-3458-4fbb-866f-6ea514f7bec3)
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/61c4ac78-f227-4b0e-9a7b-754216dcd776)

>Doesn't launch
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/6ca32abf-23a6-4704-ab2e-dfbe9c4aba7c)
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/614a9923-17ec-48e9-a8e9-f64627e2da06)

### Expected behavior

You should be able to include "-test" in the name.

### Additional context

Why

**Comment by garrynewman** [comment]
This is unfortunate. We check for -test in the command line. We should really be breaking down the command line into proper parts and checking whether one of them is -test.

**Comment by badandbest** [comment]
I'll try it when it's uploaded.

**Comment by xezno** [comment]
Should be fixed now

**Comment by badandbest** [comment]
Can confirm it works now.
