### ISSUE TITLE
Add ViewModel Camera Mode to the Animgraph Preview viewport

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#521]
**What can't you do?**

You cannot easily preview viewmodels animations on the Animgraph without having to move the camera in a weird way to get some sort of viewmodel camera.

**How would you like it to work?**

Having an option to set the Camera Mode to ViewModel or Default on the Preview viewport of the Animgraph Editor.

**Additional context**

This feature is currently available & working on the ModelDoc:
![MmBRTvQ6A1](https://user-images.githubusercontent.com/67245359/127498077-5f314a3f-57f6-416c-8cd5-bf659a331d7d.png)

**Comment by aylaylay** [comment]
Done, let me know if there's any issues.

<img width="406" alt="sbox_r4tXkPr4gr" src="https://user-images.githubusercontent.com/1667289/127737031-3a67eec8-9ff4-4fec-8e02-0a6497491700.png">

**Comment by KayaDLX** [comment]
Seems to be working just fine! Thanks a lot for this.
