### ISSUE TITLE
.scene changes don't get automatically recompiled on bootup and will use a cached version instead

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5210]
### Describe the bug

It seems that .scene resources have stopped automatically recompiling or loading correctly after changes from github have been made. Resulting in a lot of conflicts and changes being undone.

1. Person A makes a change to the .scene and pushes it through github
2. Person B pulls and receives the new .scene
3. Person B makes no change at all to the scene and pushes an unrelated commit
The unrelated commit will have the old version of the scene with it unless Person B manages to catch it, which is impossible if Person B has also made some changes.
Usually there's a "VS Changes: LOAD?" warning but lately we have not seen it at all, causing people to push their caches scenes undoing any change the others have done.

### To Reproduce

1. Set up github
2. Both clients have the scene loaded in
3. Client A makes a change and pushes it
4. Client B pulls, makes a change to the scene and pushes it
5. Client A's change will be undone and only Client B's change will appear

### Expected behavior

To recompile and reload the scene upon every change to the .scene file

### Additional context

We have been managing by "remembering" to recompile the scene everytime we pull, closing and reopining, but sometimes that doesn't work or isn't an option.

**Comment by garrynewman** [comment]
I suspect that the problem here, and with a lot of stuff, is that we're loading compiled GameResources instead the source of them. In the editor we should always prefer to load the source version.

**Comment by badandbest** [comment]
> In the editor we should always prefer to load the source version.

Would that mean assets only need to compile when uploading? No more _c files in my projects?

**Comment by garrynewman** [comment]
no
