### ISSUE TITLE
[Sync] on fields

### ISSUE THREAD

**Issue by verdie-g** [Facepunch/sbox-issues#5211]
### For?

S&Box

### What can't you do?

I would like to have a sync'd private field but the SyncAttribute uses `AttributeTargets.Property` so it cannot be used on a field. I'm wondering if it by design, does the implementation of Sync needs getter/setter?

### How would you like it to work?

```diff
- [AttributeUsage(AttributeTargets.Property)]
+ [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
public class SyncAttribute : Attribute
```

### What have you tried?

I can instead have a private property but that would be less idiomatic. Though I can understand if it simplifies the Sync implementation.

**Comment by verdie-g** [comment]
Yeah reading [Sync Properties](https://docs.facepunch.com/s/sbox-dev/doc/sync-properties-jKFHwTGVgR) again, it really feels like it's by design. Feel free to close that issue if fields is not something to support.

**Comment by LeQuackers** [comment]
I have a sneaking suspicion that it has to be a property (more specifically a method under the hood) so the code gen stuff can decorate it.
