### ISSUE TITLE
there's a lobby in my username, but I didn't start the game.

### ISSUE THREAD

**Issue by Kolya142** [Facepunch/sbox-issues#5212]
### Describe the bug

there's a lobby with my username in the lobby list.

### To Reproduce

i don't know

### Expected behavior

There shouldn't be such a lobby here.

### Media/Files

![Screenshot_10](https://github.com/Facepunch/sbox-issues/assets/87275865/cb113a50-92a7-46a2-adb9-9dec1f87e44c)

### Additional context

windows 10

**Comment by garrynewman** [comment]
You either did start a lobby, or you joined one and became the owner.

**Comment by Kolya142** [comment]
Probably, but the lobby's already closed.
