### ISSUE TITLE
Let us network GameObject, Components, and GameResource references

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#5214]
### For?

S&Box

### What can't you do?

All of these have some form of IDs I'm pretty sure, we should be able to do normal networking operations like [Sync] and [Broadcast]

### How would you like it to work?

This is already somewhat possible since you just pass the IDs around

### What have you tried?

...

**Comment by ceitine** [comment]
BUMP ! !

**Comment by CyberAgentz** [comment]
bump

**Comment by matekdev** [comment]
![terry-davis](https://github.com/Facepunch/sbox-issues/assets/32153021/1f3ed27f-5e75-45cc-852d-f3c90f91d1ce)
