### ISSUE TITLE
OnTriggerExit is not being called when collider of object inside trigger getting disabled

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#5215]
### Describe the bug

OnTriggerExit is not being called when collider of object inside trigger getting disabled

on other side OnTriggerEnter is being called when collider getting enabled, so i think it is a bug

### To Reproduce

1. implement OnTriggerExit in any component
2. disable collider on object inside trigger
3. OnTriggerExit will not be called

### Expected behavior

OnTriggerExit should be called when collider of object inside trigger getting disabled

**Comment by aylaylay** [comment]
Should be fixed now
