### ISSUE TITLE
Search bar in main menu doesn't unfocus when entering game

### ISSUE THREAD

**Issue by DarkReaper231** [Facepunch/sbox-issues#5216]
### Describe the bug

When you search game using this search bar
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/e154a4c1-9270-4543-bc83-8a3b5c6b9cef)
and then enter the game, your input is still focused to the search bar so you can't move around in that game

### To Reproduce

1. Search a game
2. Enter the game
3. Try to move

### Expected behavior

The search bar should unfocus on game enter

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by DarkReaper231** [comment]
Seems to work flawlessly now, thanks!
