### ISSUE TITLE
Editor - UI Panels inspector :hover, :active, :focus toggles don't update elements properly

### ISSUE THREAD

**Issue by DarkReaper231** [Facepunch/sbox-issues#5217]
### Describe the bug

Let's say I have this slider
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/183cac75-2d80-4ef9-8652-c1fbc305cfbc)
Now this slider has some elements when `:active`
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/84924795-9d1c-4fd0-851e-0b6a6e6f49c4)
Now I would like to get the names of the sub classes using the inspector
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/fe90a548-6e80-48b0-8ce9-a3d89fda252a)
That would usually be under the "thumb" element. So I naturally toggle the `:active` toggle in the inspector
but doing so doesn't update the element to add the elements under it which are there if you do it manually
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/ad9d8598-3263-49db-80ba-bfc2f6ca4f6e)

This is what it looks like if I do it manually
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/737537dd-12e7-4900-ac92-022ca142139c)

A workaround for now is alt tabbing and then it bugs into `:active` tab

### To Reproduce

1. Enable UI Panels window
2. Toggle one of the toggles
3. Nothing happens

### Expected behavior

It should properly update

**Comment by trundlr** [comment]
possible dupe of https://github.com/Facepunch/sbox-issues/issues/3306

**Comment by DarkReaper231** [comment]
> possible dupe of #3306

Not duplicate, if you toggle `:hover` and other, it never forces the element to show it's childeren

**Comment by DarkReaper231** [comment]
The reason was I had to set the `slidercontrol` to `active`, not the `thumb`
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/a619cb2d-f04c-4d9f-a91c-be89cdc662d5)
