### ISSUE TITLE
WorldScreen Not Coming back after GameObject.Enable

### ISSUE THREAD

**Issue by RadioManTheOne** [Facepunch/sbox-issues#5222]
### Describe the bug

WorldScreen Not Coming back after GameObject.Enable

https://github.com/Facepunch/sbox-issues/assets/163954712/f3d5ad9a-fe9d-4490-b457-382ea9c8e618

### To Reproduce

GameObject.Enabled =False (on a object with a world screen panel)
Re Enable it 
Boom done

### Expected behavior

Should Come back with GameObject.Enabled = true;

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/163954712/5ae9abbc-33f0-4346-880f-ee8e6f0d1827

**Comment by aylaylay** [comment]
Do you have a small downloadable repro? I'm toggling game objects in testbed and I don't see this happening.

**Comment by kurozael** [comment]
@RadioManTheOne does `PlayerHealthDisplay` override `OnUpdate` but not call `base.OnUpdate()`?

**Comment by aylaylay** [comment]
Should be fixed now
