### ISSUE TITLE
Particle System control point models

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#5225]
### For?

S&Box

### What can't you do?

.vpcf control points can store model data, which can then be used for the Render Model node. It's not possible to set this value in s&box right now.

### How would you like it to work?

Have another overload for SceneParticles.SetControlPoint and a model value type for the LegacyParticleSystem component.

### What have you tried?

Creating multiple vpcfs. I have 17 duplicate particle systems in Turf with only the rendered model being the difference between them.

### Additional context

It seems like this is already implemented in IParticleCollection as SetControlPointModel, but it's not exposed anywhere.

**Comment by aylaylay** [comment]
I've added SetControlPoint for models
