### ISSUE TITLE
Changing GameObject tags on objects in triggers causes trigger enter/exit to be called

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5227]
### Describe the bug

When an object is inside of a trigger, changing the tags in any way on that object causes the `OnTriggerExit` and `OnTriggerEnter` methods be called on the trigger. This is wrong because the object never left the trigger. Also, when changing the tags on the trigger itself, it will call exit/enter for all the objects in it.

This causes a weird bug when you set tags based on objects entering/exiting triggers, and the enter/exit methods will be called in rapid succession indefinitely.

### To Reproduce

1. Have a trigger that does something upon enter/exit
2. Place an object into the trigger
3. Change tags of the object or the trigger and notice OnTriggerExit/OnTriggerEnter get called

### Expected behavior

Things that never left the trigger should not leave it or re-enter it. Only if the new tags prohibit them from interacting, then calling OnTriggerExit call makes sense.

### Media/Files
Demonstration of the problem where changing tags calls the trigger methods:

https://github.com/Facepunch/sbox-issues/assets/5991682/0e17b5ef-d07f-4ee4-9c32-eebea8cabd99

**Comment by aylaylay** [comment]
Pushed a fix, let me know if it works for you

**Comment by Gmod4phun** [comment]
Yes, it works correctly now, thanks again.

**Comment by MrBrax** [comment]
there seems to have been a regression, i'm getting this now
