### ISSUE TITLE
if (Game.Random.Next(0, 2) == 0) throws array index out of bounds sometimes

### ISSUE THREAD

**Issue by DarkReaper231** [Facepunch/sbox-issues#5229]
### Describe the bug

Using Game.Random.Next causes out of bounds errors even tho using just
```
var random = new Random();
if (random.Next(0, 2) == 0)
```
does not so something funny is happening with Game.Random.Next()

### To Reproduce

1. Use Game.Random.Next() over System.Random.Next()
2. At some point array index out of bounds error happens

### Expected behavior

It should act the same

**Comment by Gmod4phun** [comment]
Are you sure your errors are not caused by something else, like accessing an element of an array? I can't seem to get an error out of `Game.Random.Next` no matter how hard I try.

**Comment by DarkReaper231** [comment]
> Are you sure your errors are not caused by something else, like accessing an element of an array? I can't seem to get an error out of `Game.Random.Next` no matter how hard I try.

Well it happens on this line and Y_Coord is not array:
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/0b0d518a-67e1-49d9-b21f-b2e146ec88ca)
it's a float:
![image](https://github.com/Facepunch/sbox-issues/assets/38611351/ec287683-be1a-4d57-a441-68141d5f07c9)

Also `Game.Random.Int(1) == 0` works flawlessly and so does `System.Random.Next(0,2) == 0`
Only `Game.Random.Next(0,2) == 0` suffers from this issue

I am thinking that maybe the lower limit is exclusive instead of inclusive? Because the original `System.Random.Next(0,2)` has lower limit inclusive and upper exclusive so this would choose 0 or 1 but not 2. If I would do `System.Random.Next(0,1) == 1`, I would get same out of bound array error because the value can be only 0 because 1 is exclusive but I am checking for 1. I don't know how can it throw that error in if check but whatever. So maybe `Game.Random.Next()` has lower bound exclusive.

**Comment by handsomematt** [comment]
it's 100% your `X_Coords[Game.Random.Next( 0, X_Coords.Count )];` line

what do you think happens if X_Coords.Count is 1 and you roll a 1 and access a 1 length array by index 1

**Comment by DarkReaper231** [comment]
@handsomematt X_Coords.Count can't possibly be 1. It's a static list of 5 coordinates. Also wouldn't explain why replacing Game.Random.Next with Game.Random.Int om the second line makes the issue never appear.

**Comment by aylaylay** [comment]
The same thing applies regardless of the size of X_Coords

**Comment by DarkReaper231** [comment]
> The same thing applies regardless of the size of X_Coords

But why this never happened if I use System.Random.Next or Game.Random.Int? That's what confuses me.

**Comment by aylaylay** [comment]
Prove it

**Comment by Gmod4phun** [comment]
The upper bound of Game.Random.Next is exclusive, so even if your X_Coords has 5 items, thus having the indices 0, 1, 2, 3 and 4, using Game.Random.Next(0, X_Coords.Count) should not cause you to go out of bounds. The only reason you would go out of bounds is if the Count is greater than you think, or another line of code is giving you the error.

**Comment by DarkReaper231** [comment]
@Gmod4phun But the weird thing is that that line doesn't affect anything, I left that line unchanged and nothing happened. Only if I change the line bellow from Int to Next, it sometimes rarely throws out of bounds

**Comment by DarkReaper231** [comment]
@aylaylay It is hard to prove it because it happens rarely but I did saw it with my own eyes and changing Next to Int caused the issue to not appear since then. Again, it is only happening with the line bellow the one choosing x coord. Using Random.Next() worked fine for days, changing it to Game.Random.Next() caused it to throw out of bounds from time to time but not for the line above. Changing it to Game.Random.Int() fixed the issue. More testing is required but I swear, there is something silly going on with specifically `Game.Random.Next(0, 2) == 0` check

**Comment by DarkReaper231** [comment]
I have an idea of testing this. I'll run the code over and over with both versions

**Comment by DarkReaper231** [comment]
I am dumb, you can close this issue

**Comment by andy013** [comment]
I guess your array was empty and you tried to access array[0]?
