### ISSUE TITLE
Gamepad code dropdown in Input Actions doesn't open, can't clear

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5232]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/57276947/24bc6423-0a82-49d6-a846-41f30b1b738a)

Clicking on Gamepad Code will not show a dropdown, and it is impossible to clear.

### To Reproduce

1. Open Input Actions
2. Observe described issue

### Expected behavior

We should be able to click the dropdown, and clear the entry.

**Comment by trundlr** [comment]
workaround, just click the slot outside of this tooltip lol

**Comment by garrynewman** [comment]
FYI - to whoever handles this ticket.. I think this happens when the popup widget has no parent. It's usually best to set the parent of the pop widget parent to the control that spawned it.
