### ISSUE TITLE
People can share their components in asset.party

### ISSUE THREAD

**Issue by TiO2EvoLve** [Facepunch/sbox-issues#5236]
### For?

S&Box

### What can't you do?

At present, asset.party can share models, materials, sounds, particles, etc. Why not allow people to share their own components for everyone to use, such as first person controllers, CSS styles, lens shake, and other components

### How would you like it to work?

You can upload your own components, and others can freely download and use them to share with the components

### What have you tried?

null
<img width="1249" alt="hope" src="https://github.com/Facepunch/sbox-issues/assets/49835162/91c262cc-09fe-47f4-b65a-031cfdd46913">

**Comment by garrynewman** [comment]
This is what #5053 is going to be for
