### ISSUE TITLE
Exception on creating GameObjects from prefab with a screen panel component while having pointer-events: all; property on another object.

### ISSUE THREAD

**Issue by ihavefoxdie** [Facepunch/sbox-issues#5238]
### Describe the bug

If there's an active GameObject with a screen panel and a razor component that has ```pointer-events: all;```, creating another, different GameOjbect (from a prefab) with it's own screen panel component causes exception to be thrown (and it pretty much "locks" the first object).

![image](https://github.com/Facepunch/sbox-issues/assets/59480394/77b28ac2-970a-491e-b916-a2bdbc2b3961)
![image](https://github.com/Facepunch/sbox-issues/assets/59480394/b6decbaa-9926-47e0-b22e-9ccaa3a75de1)

### To Reproduce

1. Have a GameObject with a screen panel component and some simple razor component with ```pointer-events: all``` property.
2. Create another GameObject (I used a prefab) that has a screen panel component as well (it doesn't matter if it has a razor component on its own).

### Expected behavior

It shouldn't throw anything.

### Media/Files

Repro:
[bugbed.zip](https://github.com/Facepunch/sbox-issues/files/14669096/bugbed.zip)

In this project, you can spawn a GameObject (that contains a screen panel component) from a prefab with the Clone() method when pressing Escape. This will cause the exception to be thrown.

**Comment by ihavefoxdie** [comment]
i've also found that even if you manually create a screen panel in the editor while ```pointer-events``` is set to ```all``` on any active component, the exception gets thrown.

**Comment by handsomematt** [comment]
Just fixed with #5268
