### ISSUE TITLE
Panel components on game object children not deleted upon destroying the child object

### ISSUE THREAD

**Issue by Brassx** [Facepunch/sbox-issues#5239]
### Describe the bug

Creating a game object, parenting it to a different game object, then destroying the now child object will result in the panel components on the child staying alive. This was not the behavior prior to this morning.

### To Reproduce

Just create a game object, add a panel component to it, then parent it to a different game object that has panel components. Now delete the newly created object, the panel will stay up.

Using this razor component you can recreate the problem:

```
//TestHover.razor
@using Sandbox;
@using Sandbox.UI;
@inherits PanelComponent
<style>
TestHover
{
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	width:50%;
	height:50%;
	background-color: rgba(0,0,0,0);
	justify-content: center;
	align-items: center;
	font-weight: bold;
	border-radius: 20px;
	pointer-events: all;
	.title
	{
		font-size: 25px;
		font-family: Poppins;
		color: #fff;
	}
}
</style>
<root>
	<div class="title" @onmouseover="@OnHover">@MyStringValue</div>
</root>

@code
{

	Panel hovering;
	GameObject hoverObj;
	public void OnHover(PanelEvent e)
	{
		Log.Info("TEST HOVER");
		var obj = Scene.CreateObject();
		//add any panel component here, I just made a dummy one called popup, which is just a default "hello world" razor file.
		obj.Components.Create<Popup>();
		hovering = e.This;
		hoverObj = obj;
		hoverObj.Parent = this.GameObject;
	}

	protected override void OnFixedUpdate()
	{
		if (hovering != null && !hovering.HasHovered)
		{
			Log.Info("Destroying");
			hoverObj.Destroy();
			hovering = null;
		}
	}

	public string MyStringValue { get; set; } = "Hover this...";

	/// <summary>
	/// the hash determines if the system should be rebuilt. If it changes, it will be rebuilt
	/// </summary>
	protected override int BuildHash() => System.HashCode.Combine( MyStringValue );
}
```

https://github.com/Facepunch/sbox-issues/assets/6100996/d53576b9-508e-4b9c-a7cb-b6376db41e12

Calling .Delete on the panel works as a work around, but I'm unsure if this behavior is intended.

### Expected behavior

The panel components attached to the child game object, should be destroyed with the object.

### Additional context
Maybe related to: https://commits.facepunch.com/473370
_No response_

**Comment by aylaylay** [comment]
Downloadable repro please

**Comment by Brassx** [comment]
Incredibly odd, this now seems resolved after restarting then updating S&Box. I recreated it a ton and had the issue all morning, as you see in the clip, but now its not behaving the same at all, despite it being the exact same code. Probably can just close the issue for now.


https://github.com/Facepunch/sbox-issues/assets/6100996/4934d9b1-6ee4-41b5-925a-ee50cda77cc0

**Comment by aylaylay** [comment]
Probably didn't have the update of the commit you linked
