### ISSUE TITLE
Component properties on a component are getting re-added as duplicate components to the GameObject when play is pressed

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5240]
### Describe the bug

https://github.com/Facepunch/sbox-issues/assets/57276947/3ffe01f2-c05a-4743-bbd4-e5bd1210a798

I have a Rigidbody and Wind referenced in ShipController. When I press play, extra Rigidbody and Wind components are being added to the gameobject itself.

Sometimes these are actually sticking around after play, too!

### To Reproduce

1. Reference a component as a property in a component
2. Press play
3. Notice extra components being created

### Expected behavior

No extra components are created

**Comment by aylaylay** [comment]
Can you provide a downloadable repro? I can't get this to happen

**Comment by trundlr** [comment]
https://github.com/trundlr/arrrrr

**Comment by aylaylay** [comment]
RequireComponent seems to be causing it

**Comment by aylaylay** [comment]
Is there a reason you're using RequireComponent here? You're setting the properties in inspector

**Comment by trundlr** [comment]
I was just trying it out lol, I can take it away for now as a workaround.

**Comment by aylaylay** [comment]
I don't know if RequireComponent was designed for [Property] it checks required components before property deserialization so it thinks the properties are null so creates the missing components.

**Comment by trundlr** [comment]
Yeah I was thinking it would be a way to ensure a particular component is not null, like let the compiler know that this component was actually set in the inspector. But all good

**Comment by aylaylay** [comment]
It could be a bug, depends how RequireComponent should work when it has [Property] @garrynewman

**Comment by MrBrax** [comment]
Experienced this issue myself and i didn't even use [Property]

**Comment by aylaylay** [comment]
But isn't that what the attribute is for, it'll add the components if they're null

**Comment by MrBrax** [comment]
i already had components added to it in the editor, and every time you'd save and load it would add a new set of components ending up with a dozen copies if you continued

**Comment by aylaylay** [comment]
How were you setting it in editor when it needs to be [Property] to do that?

**Comment by MrBrax** [comment]
true, you're right about that. i used it without property and it kept adding duplicates every time you saved/opened it so i changed it back to my old method of accessing local components

![1711026397057](https://github.com/Facepunch/sbox-issues/assets/1517911/325ee6e9-63d9-4bd1-83f7-8a6f5833c1f1)

**Comment by aylaylay** [comment]
I've just tested this and it's only creating a single component, not multiple, which is how it's meant to work. If it can't find the component on the object then it'll create one.
