### ISSUE TITLE
Modeldoc - PhysicsBodyMarkup has no effect on Rigidbody Component

### ISSUE THREAD

**Issue by qualitykk** [Facepunch/sbox-issues#5242]
### Describe the bug

When overriding mass, etc with "PhysicsBodyMarkup" the data is ignored by Rigidbody component and uses the default values instead.

### To Reproduce

1. Open model with physics body in ModelDoc
2. Add "PhysicsBodyMarkup" node and set the mass value to whatever
3. Create object with this model in a scene and add a Rigidbody
4. Observe the mass still being the default values

### Expected behavior

The rigidbody component should take into account the PhysicsBodyMarkup node for mass, etc.

**Comment by aylaylay** [comment]
You're using this with a ModelCollider right?

**Comment by aylaylay** [comment]
Mass and damping properties from markup are now used
