### ISSUE TITLE
Quaternion.FromToRotation

### ISSUE THREAD

**Issue by verdie-g** [Facepunch/sbox-issues#5243]
### For?

S&Box

### What can't you do?

I would like to place an object when hitting a ray trace. I believe the code would look like that with Unity:
```csharp
if (Physics.Raycast(ray, out hit))
{
    objectToPlace.transform.position = hit.point;
    objectToPlace.transform.rotation = Quaternion.FromToRotation(Vector3.up, hit.normal);
}
```
but it seems like there is no `Quaternion.FromToRotation` in s&box.

### How would you like it to work?

```diff
class Rotation
{
+    public static Rotation FromToRotation(Vector3 fromDirection, Vector3 toDirection);
}
```

### What have you tried?

I've tried using `Rotation.LookAt` even if it's a similar operation it doesn't give the expected result. For example, if I my ray hit the floor which as a normal (0, 0, 1), `Rotation.LookAt((0, 0, 1), Vector3.Up)` will give (-90, 0, 0). `Rotation.LookAt` is actually equivalent to `Quaternion.LookRotation`.

**Comment by MrBrax** [comment]
`Rotation.LookAt( -hit.Normal )`

**Comment by verdie-g** [comment]
I'll implement my own method for now but I think it should part of the s&box SDK
```csharp
Rotation FromToRotation(Vector3 from, Vector3 to)
{
    Vector3 axis = Vector3.Cross(from, to);
    float angle = Vector3.GetAngle(from, to);
    return Rotation.FromAxis(axis.Normal, angle);
}
```
