### ISSUE TITLE
Massive lag spikes when enabling/disabling networked objects

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#5248]
### Describe the bug

When enabling/disabling a networked gameobject and refreshing it's state I've been noticing massive performance stutters.  This happens primarily in the editor but also outside of it yet is less noticeable.  

### To Reproduce

Unsure how to reproduce but my repo is here: https://github.com/ScoutWozniak/Ringworld/tree/scene-rewrite

### Expected behavior

The game should run as normal with no performance drop.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/99102549/c2e5f15d-154b-43bf-927c-7de0373f396f
Footage of the bug in action.  This was with another local client connected but the same stutters happen when ran on it's own.

**Comment by handsomematt** [comment]
Pretty sure @kurozael fixed this with EditLog shit, please reopen if still applicable
