### ISSUE TITLE
need key

### ISSUE THREAD

**Issue by ruttay** [Facepunch/sbox-issues#525]
**Describe the bug**

**To Reproduce**

key need
**Screenshots*
key needed key neededkey neededkey neededkey neededkey neededkey neededkey neededkey neededkey neededkey neededkey neededkey neededkey neededkey neededkey  need neede kes

**Comment by NotGaylien** [comment]
i dont understand, how can i replicate this bug

**Comment by Ryhon0** [comment]
Cannot replicate

**Comment by xezno** [comment]
I haven't encountered this bug either

**Comment by DoctorGurke** [comment]
Works fine on my machine
