### ISSUE TITLE
CTRL+S is not working for saving scene

### ISSUE THREAD

**Issue by merenyprkc** [Facepunch/sbox-issues#5250]
### Describe the bug

CTRL+S is not saving the scene. if i clicked with mouse right button and choosing "Save Scene" saving the scene.

### To Reproduce

Create a scene, create a object in scene and click CTRL+S. thats not worked.

### Expected behavior

CTRL+S be worked.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/131323341/284b4a2e-88f4-47da-8715-581b979959ad

### Additional context

I'm working with Win11.

**Comment by handsomematt** [comment]
If this is still persisting please reopen the issue
