### ISSUE TITLE
Improve Vector3Int

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#5254]
### What it is?

There is a lot of stuff missing in Vector3Int

### What should it be?

1. add implicit operator from Vector3Int to Vector3
2. add explicit operator from Vector3 to Vector3Int
3. I dont think this operator makes any sense (you have it in Vector3Int)
```
public static Vector3Int operator +(Vector3Int c1, int c2)
{
	return new Vector3Int(c1.x * c2, c1.y * c2, c1.z * c2);
}
```
4. make x,y,z be properties with readonly getter, not fields
5. add copy constructor ```Vector3Int(Vector3Int)``` (we have it in Vector3)
6. add constructor ```Vector3Int(Vector2Int, int z)``` (we have it in Vector3)
7. Vecctor3Int.Distance method should have Vector3 argument and return float
8. Add all the methods, properties and operators (listed below) from Vector3 to Vector3Int (a lot of them should just convert Vector3Int to Vector3 and run method/property, so we dont need to convert it manually to Vectror3)
### **- Properties:**
```public readonly Vector3Int Normal```
```public Angles EulerAngles``` getter only
```public readonly Vector3 Inverse```
### **- Methods:**
```public readonly Vector3 ClampLength(float maxLength)```
```public readonly Vector3 ClampLength(float minLength, float maxLength)```
```public readonly Vector3Int Clamp(Vector3Int otherMin, Vector3Int otherMax)```
```public readonly Vector3Int Clamp(int min, int max)```
```public readonly Vector3 LerpTo(in Vector3 target, float frac, bool clamp = true)```
```public readonly Vector3 LerpTo(in Vector3 target, in Vector3 frac, bool clamp = true)```
```public readonly Vector3Int Cross(in Vector3Int b)```
```public readonly Vector3 Cross(in Vector3 b)```
```public readonly int Dot(in Vector3Int b)```
```public readonly float Dot(in Vector3 b)```
static Dot methods
```public float Distance(Vector3Int other)``` why on earth in current implementation it returns int instead of float?
```public readonly float DistanceSquared(in Vector3 target)```
```public readonly Vector3Int Approach(int length, int amount)```
```public readonly Vector3 Approach(float length, float amount)```
```public readonly Vector3Int Abs()```
```public readonly Vector3 ProjectOnNormal(in Vector3 normal)```
```public readonly Vector3Int ProjectOnNormal(in Vector3Int normal)```
```public static Vector3Int VectorPlaneProject(in Vector3Int v, in Vector3Int planeNormal)```
```public static void Sort(ref Vector3Int min, ref Vector3Int max)```
```public readonly Vector3 SubtractDirection(in Vector3 direction, float strength = 1f)```
```public readonly Vector3Int SubtractDirection(in Vector3Int direction, int strength = 1)```
```public readonly Vector3Int SnapToGrid(int gridSize, bool sx = true, bool sy = true, bool sz = true)```
```public readonly Vector3 SnapToGrid(float gridSize, bool sx = true, bool sy = true, bool sz = true)```
```public readonly int Angle(in Vector3Int v2)```
```public readonly float Angle(in Vector3 v2)```
```public readonly Vector3 AddClamped(in Vector3 toAdd, float maxLength)```
```public readonly Vector3 RotateAround(in Vector3 center, in Rotation rot)```
### **- Operators:**
```public static Vector3 operator +(Vector3Int c1, Vector3 c2)```
```public static Vector3 operator +(Vector3 c1, Vector3Int c2)```
```public static Vector3 operator -(Vector3Int c1, Vector3 c2)```
```public static Vector3 operator -(Vector3 c1, Vector3Int c2)```
```public static Vector3 operator /(Vector3Int c1, float c2)```
```public static Vector3Int operator /(Vector3Int c1, Vector3Int c2)```
```public static Vector3 operator /(Vector3Int c1, Vector3 c2)```
```public static Vector3 operator /(Vector3 c1, Vector3Int c2)```
```public static Vector3Int operator *(Vector3Int c1, int c2)``` (u have this one actually, but not one below)
```public static Vector3Int operator *(int c1, Vector3Int c2)```
```public static Vector3 operator *(Vector3Int c1, float c2)``` (u have this one actually, but not one below)
```public static Vector3 operator *(float c1, Vector3Int c2)```
```public static Vector3Int operator *(Vector3Int c1, Vector3Int c2)```
```public static Vector3 operator *(Vector3Int c1, Vector3 c2)```
```public static Vector3 operator *(Vector3 c1, Vector3Int c2)```
```public static Vector3 operator *(Vector3Int c1, Rotation f)```
```public static Vector3Int operator %(Vector3IntB a, Vector3IntB b)```
```public static implicit operator Vector3(Vector3Int vector)```
```public static explicit operator Vector3Int(Vector3 vector)```
```public static implicit operator Vector3Int(Vector2Int value)``` (you have this for Vector3)
```public static explicit operator Vector3Int(Vector2 vector)```
```public static explicit operator Vector3Int(Vector4 vector)```

### **Things that probably dont make sense, but they are missing**
property ```public static Vector3Int Random```
```public static Vector3Int Reflect(in Vector3Int direction, in Vector3Int normal)```

### **Same thing for Vector2Int**

P.S I am pretty sure I missed something, if I find something missing I'll write an issue for that

**Comment by Pieeer1** [comment]
Is there also a reason why Vector3Int was chosen as the name? I feel like Vector3I is enough to be verbose but that is a personal opinion.

**Comment by garrynewman** [comment]
Hahaha I knew this shit would happen
