### ISSUE TITLE
Dynamic `LegacyParticleSystem`: `IsLooping` attribute not works

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5255]
### Describe the bug

Hi,

On `LegacyParticleSystem` creation through code, the `IsLooping` attribute of the `.vtex` is not working correctly.
Indeed, it seems the `IsLooping` attribute is stuck to the `true` value even if it's unchecked in the s&box vtex editor.

Let's jump to the reproduction steps

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Update the `Gun.cs` with your favorite `.VPCF` to generate a particle on `Attack1`:
```
protected override void OnUpdate()
{
	        // [... SAME CODE]
		o.NetworkSpawn();
		
		// [NEW CODE]
		var goParticle = new GameObject();
		goParticle.Name = "Particle Prop Destroy";

		var propDestroy = goParticle.Components.Create<LegacyParticleSystem>();
		propDestroy.Particles = ParticleSystem.Load( "dev/pathtoyour.vpcf" );

		propDestroy.ControlPoints = new List<ParticleControlPoint>();

		var position = new ParticleControlPoint();
		position.StringCP = "0";
		position.Value = ParticleControlPoint.ControlPointValueInput.Vector3;
		position.VectorValue = Transform.Position;

		var size = new ParticleControlPoint();
		size.StringCP = "Radius";
		size.Value = ParticleControlPoint.ControlPointValueInput.Float;
		size.FloatValue = 50f;

		propDestroy.ControlPoints.Add( position );
		propDestroy.ControlPoints.Add( size );
	}
}
```
3) Edit the `vtex` file attached to your particle, uncheck `Is Looping`
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/30180f17-36dd-4aa3-80f4-9a24528cf630)

This will remove the line `"IsLooping": true,` in the texture `.vtex` file
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/c307dff6-096a-4bbc-b7a5-078139806bf9)

4) Now edit the `networking` scene to attach the `Gun.cs` to your Citizen
5) Create game, press `Attack1`: your particle will be played but trying to loop again
6) Edit the `.vtx` manually set `"IsLooping": false,`
7) Press `Attack1`: your particle will be played without trying to loop again

### Expected behavior

I think all can be easily fixed if unchecking the `Is Looping` field just turns to `false` the `IsLooping` attribute in the `vtex` file instead of removing it

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5229571/896255e1-58e9-4867-aa1a-40ccaccc16a3

**Comment by aylaylay** [comment]
This should be fixed now
