### ISSUE TITLE
BodyGroups and MaterialGroups in Prop Component

### ISSUE THREAD

**Issue by RickGreeve** [Facepunch/sbox-issues#5256]
### For?

S&Box

### What can't you do?

unable to edit bodygroup or materialgroup in the prop component

### How would you like it to work?

be able to change the body and material groups on the component itself instead of having to seperate into multiple components

### What have you tried?

https://github.com/Facepunch/sbox-issues/assets/125879070/b422bbbe-fd5b-4bb6-aba3-1aac54835069

**Comment by aylaylay** [comment]
I'm wary of adding this because we could end up with a bunch of properties on Prop, which might go against the point of the component. Depends what @garrynewman thinks.

**Comment by aylaylay** [comment]
Added

**Comment by garrynewman** [comment]
We should really pick and choose what we add to this. These are fine imo, since they're really common. When things get more granular we'll want to draw a line.

**Comment by RickGreeve** [comment]
The only thing I can think of right now to also be added is the option to change the tint color.
