### ISSUE TITLE
Add a way to get the Vertices of a PhysicsShape

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#5259]
### For?

S&Box

### What can't you do?

I want to be able to read the vertices of a collider that was hit during a trace (in this case the collider of my map)

`SceneTraceResult` has a `Triangle` property which has the index of the triangle that was hit, however there doesn't seem to be anywhere where you can actually get the vertices from (maybe I'm blind?)

I was hoping to find something in `SceneTraceResult.Body.Shapes` but it seems there's no mesh data there either

### How would you like it to work?

`PhysicsShape` has some methods that take vertices and indices, so maybe it could come from there? So maybe `PhysicsShape.Vertices` and `PhysicsShape.Indices`

The trace's triangle index should match the correct index on the mesh

### What have you tried?

Looked for ages but can't seem to find anything

**Comment by PolSpock** [comment]
This reminds me https://github.com/Facepunch/sbox-issues/issues/5259

**Comment by PolSpock** [comment]
This reminds me https://github.com/Facepunch/sbox-issues/issues/2405
(sorry for my previous wrong message)

**Comment by aylaylay** [comment]
Added PhysicsShape.Triangulate

**Comment by anthonysharpy** [comment]
@aylaylay Hiya, thanks for adding it in so quick. Sorry, have only just had a chance to test it. It works mostly great except for a couple of strange things - not sure if it's my fault or not though?

This code works well for me:

```
var result = Scene.Trace.Ray( GetEyePosition(), GetEyePosition() + (GetEyeRotation().Forward * 1000) )
	.WithAnyTags("solid")
	.Run();

if (result.Shape.IsValid())
{
	result.Shape.Triangulate( out Vector3[] positions, out uint[] indices );

	Log.Info( $"Aimed at thing has {positions.Count()} positions and {indices.Count()} indices" );
	Log.Info( $"We hit triangle {result.Triangle}" );

	AimedAtTriangle = new()
	{
		A = positions[ indices[result.Triangle * 3] ],
		B = positions[ indices[result.Triangle * 3 + 1] ],
		C = positions[ indices[result.Triangle * 3 + 2] ],
	};

	using (Gizmo.Scope())
	{
		Gizmo.Draw.IgnoreDepth = true;
		Gizmo.Draw.Color = Color.Red;
		Gizmo.Draw.SolidSphere( AimedAtTriangle.A, 4f );
		Gizmo.Draw.SolidSphere( AimedAtTriangle.B, 4f );
		Gizmo.Draw.SolidSphere( AimedAtTriangle.C, 4f );
	}
}
```
![image](https://github.com/Facepunch/sbox-issues/assets/55365296/84bd7bc8-49e6-44c9-a196-20546d4766f2)

However, it seems not all of the map's collision data is getting copied, as for some triangles, that code is saying that it's trying to access outside the bounds of the array

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/3035e254-fb80-4040-aa03-1b579eb1bc40)

Looking at the console it says the trace hit triangle 32307, which would imply a collision mesh with at least 96921 indices. But the returned mesh data only has ~81,000 indices

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/802b8cf4-a794-4125-be82-08864fdd4b66)

So I suspect either all the mesh data isn't getting returned or I'm having a skill issue

**Comment by aylaylay** [comment]
I fucked it, should be fixed now

**Comment by anthonysharpy** [comment]
@aylaylay Thanks it works great!
