### ISSUE TITLE
Disabling rigidbody sets it's velocity to 0

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#5262]
### Describe the bug

When you disable rigidbody velocity sets to 0
Even disabling and then enabling rigidbody in same frame will reset it's velocity

### To Reproduce

1. add rigidbody to gameobject
2. let it fall
3. disable it when it is falling
4. velocity resets

### Expected behavior

Disabling rigidbody doesn't reset velocity

**Comment by Gmod4phun** [comment]
Why wouldn't it set velocity to 0? You are literally disabling the rigidbody component, therefore disabling the object's ability to move freely. I would say this is pretty much the correct behaviour.

**Comment by GavrilovNI** [comment]
> Why wouldn't it set velocity to 0? You are literally disabling the rigidbody component, therefore disabling the object's ability to move freely. I would say this is pretty much the correct behaviour.

@Gmod4phun, for same reason why for example ModelRenderer doesn't reset it's model when getting disabled OR CharacterController doesn't reset it's velocity when getting disabled.

@aylaylay, I don't understand why it resets velocity. It's not clear that disabling rigidbody will reset velocity. I think if you need to reset velocity you should do it manually.

In my project I disable object that has rigidbody to wait until world around it is loaded, then i reenable it. and I have multiple of objects. So to fix it I should remember all velocities of rigidbodies, or make a component that inherits Rigidbody and remember it´s velocity inside it. It all looks like a bad workaround of the problem.
