### ISSUE TITLE
Inspector mixes up components of same time

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#5264]
### Describe the bug

when adding same type components to object, inspector thinks they are same component until inspector is reloaded

### To Reproduce

use this code:
```
using Sandbox;


public class ComponentMixes : Component
{

}

public class ComponentMixesTest : Component
{
    [Property] ComponentMixes Component1 { get; set; } = null!;
    [Property] ComponentMixes Component2 { get; set; } = null!;
    [Property] bool Component1Enabled => Component1.IsValid() && Component1.Enabled;
    [Property] bool Component2Enabled => Component2.IsValid() && Component2.Enabled;
}
```

repeat as shown on video

https://github.com/Facepunch/sbox-issues/assets/9992453/4a2c11f8-8ad0-4852-bfc4-0b75acdc3a94

### Expected behavior

Inspector doesn't mix up components of same time

**Comment by DevulTj** [comment]
This should be working as intended now with multiple components in one GameObject, of the same type.
