### ISSUE TITLE
Calling Game.Close() in the editor throws a Object reference not set to an instance of an object exception.

### ISSUE THREAD

**Issue by Pieeer1** [Facepunch/sbox-issues#5266]
### Describe the bug

When calling Game.Close(); while in the editor, it throws an exception and does not close the scene runtime. 

### To Reproduce

1. Create a Razor Component and attach it to a GameObject in the Scene. 
2. Call Game.Close(); on a button click to stimulate it.
```CSharp
<root>
<div class="button" onclick="@QuitClicked">Quit</div>
</root>
@code{

private void QuitClicked()
{
Game.Close(); // throws an exception
}

}

```
4. 

### Expected behavior

IMO this should close the currently running scene in the editor, IE closing the Game, instead of throwing an exception.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/11530364/cb1fdd99-a3f5-4309-a075-80e47e0e57b7)

### Additional context

Windows 10. Live Version as of 1:05 pst 3/23/24

**Comment by MrBrax** [comment]
how about stopping the current scene playback?

**Comment by DevulTj** [comment]
That should be the case now, without any errors 👍🏻

**Comment by MrBrax** [comment]
<img width="235" alt="1712333713037" src="https://github.com/Facepunch/sbox-issues/assets/1517911/4810a07a-85ef-4ef4-a00a-1516511b2480">

Editor completely breaks when pressing close, requiring a restart to play the game again
