### ISSUE TITLE
Flickering with multiple World Panels with blur backdrop-filter

### ISSUE THREAD

**Issue by 5xp** [Facepunch/sbox-issues#5267]
### Describe the bug

Having multiple World Panels with backdrop filter blur in view causes one of them to flicker with a checkerboard pattern.

Darker background colors and higher blur values make it more apparent.

### To Reproduce

1. Create multiple GameObjects near by, each with a World Panel component and a panel component.
2. Add the following SCSS to the panels:
```css
background-color: rgba(0, 0, 0, 0.8);
backdrop-filter: blur(30px);
```

### Expected behavior

The panels should not flicker.

### Media/Files

[worldpaneltest.zip](https://github.com/Facepunch/sbox-issues/files/14733476/worldpaneltest.zip)

https://github.com/Facepunch/sbox-issues/assets/62446202/7b2f4af0-356b-441a-80ff-e636e5d24fbb

### Additional context

OS: Windows 11
GPU: 2070 Super
Driver version: 551.86
CPU: Ryzen 5 3600x

**Comment by xezno** [comment]
![Image](https://github.com/user-attachments/assets/d4d90425-8579-42a5-8f10-a96db8bbafda)
These seem to work now
