### ISSUE TITLE
Can't load map in "Map instance" Component

### ISSUE THREAD

**Issue by AfteraOfficiel** [Facepunch/sbox-issues#5270]
### Describe the bug

I have : 64 GB RAM
RTX 7900 XTX / Ryzen 9 5950X

Map : it's a big map that I've been working on for a few years, size : 801 MB

I try to import my map in scene system but i have this error : 

![image](https://github.com/Facepunch/sbox-issues/assets/99672629/0c5e9e4a-2303-46dc-9f3f-11b0b624e6fa)

### To Reproduce

1-Add name of map in "Map Name" in "Map instance" component
2-Crash because exhausted memory allocator

### Expected behavior

The map should import correctly

**Comment by AfteraOfficiel** [comment]
I can't Upload my map :(

**Comment by Nolankicks** [comment]
Try maps/yourmapname.vmap.

**Comment by MrBrax** [comment]
> Try maps/yourmapname.vmap.

from looking at the map loader code, i think the format should be `mapname.vpk` in its entirety

**Comment by handsomematt** [comment]
Make your map smaller, or try to pin down what's pushing it over the edge. It's not feasible for us to debug and fix
