### ISSUE TITLE
Custom fonts are broken

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#5271]
### Describe the bug

Custom fonts don't load anymore, tested with fonts that worked before the scene rework.

### To Reproduce

1. drag font into gamemode/fonts/acustomfont.ttf
2. use font in code `font-family: acustomfont;`
3. Custom font is not used

Tested with:  [acustomfont.zip](https://github.com/Facepunch/sbox-issues/files/14735749/acustomfont.zip)

### Expected behavior

The font loads

**Comment by handsomematt** [comment]
your font name is Conligh DEMO

**Comment by timmybo5** [comment]
That fixed the font I sent here but the other one I have is still broken.

`font-family: FSP DEMO - Integral CF Medium;`
font: [integralcf-medium.zip](https://github.com/Facepunch/sbox-issues/files/14735790/integralcf-medium.zip)

**Comment by handsomematt** [comment]
FONTSPRING DEMO - Integral CF

it works the same as the web or any other program now

**Comment by Gmod4phun** [comment]
How would one get the proper name of the font? (or any font)

Default windows font viewer says this:
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/66f3b7d4-9697-40b9-8cac-8b06e84e0e22)

And fontforge says this:
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/97493eb6-5e90-42c5-b23c-b147c67609f9)

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/858b7a72-6e12-4e64-bab5-a48d3cab489b)

**Comment by Nolankicks** [comment]
My guess is that it’s not broken since there are many games with custom fonts. But I don’t know for sure.

**Comment by handsomematt** [comment]
I dunno those fonts are weird and tampered with by the site, probably for demo purposes. Generally just use the family name from now on like normal web
