### ISSUE TITLE
Add s&box documentation for `Network.SetOrphanedMode`

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5276]
### Location

https://docs.facepunch.com/s/sbox-dev/doc/networking-multiplayer-kaVboe3yRD

### Summary

`GameObject.Network.SetOrphanedMode(NetworkOrphaned)` exists but is never mentioned and explained in the current s&box multiplayer documentation

**Comment by kurozael** [comment]
All done :) check out the Ownership page and see **Disconnection** for information about Orphaned Mode.
