### ISSUE TITLE
Error on the logo when starting the game

### ISSUE THREAD

**Issue by ddos-pro** [Facepunch/sbox-issues#5277]
### Describe the bug

Dialogue notification 1

Menu Load Error
Couldn't create MenuSystem

Dialogue notification 2

Bootstrap::Init Error

Failed to bootstrap engine: One or more errors occurred. (Menu couldn't load. Can't continue.)
at Sandbox.Tasks.SyncContext.RunBlocking(Task task)
at Sandbox.Engine.Bootstrap.Init()

### To Reproduce

Launch the game and wait for a while

### Expected behavior

.

### Media/Files

Log file
[Log.log](https://github.com/Facepunch/sbox-issues/files/14741652/Log.log)

### Additional context

Previously, somewhere I found a pirated version, just to test it, it ran for me, I was even able to load it onto a card, everything worked fine, here, too, only SSE 4.2 was enabled? I used to be able to play CS2 on release, but after some update they removed support for anything less than SSE 4.2

Computer information:
Manufacturer: Gigabyte Technology Co., Ltd.
Model: EP43-DS3L
Type: desktop
Touch input is not supported
CPU:
Processor manufacturer: GenuineIntel
Processor brand: Intel(R) Xeon(R) CPU X5460 @ 3.16GHz
Processor family: 0x6
CPU model: 0x17
CPU stepping: 0x6
Processor type: 0x0
Clock frequency: 3166 MHz
Logical processors: 4
Physical processors: 4
Hyper-Threading: Not supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Not supported
SSE41: Supported
SSE42: Not supported
AES: Not supported
AVX: Not supported
AVX2: Not supported
AVX512F: Not supported
AVX512PF: Not supported
AVX512ER: Not supported
AVX512CD: Not supported
AVX512VNNI: Not supported
SHA: Not supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Not supported
OS version:
Windows 10 (64-bit) Corporate LTSC 1809 11763
NTFS: Supported
Provided crypto codes: Supported 311 0x0 0x0 0x0
Video card:
Driver: Radeon(TM) RX 460 Graphics (Connected Display Port)
DirectX Driver: aticfx32.dll
Driver version: 31.0.21902.5
DirectX driver version: 31.0.21902.5
Driver release date: 8/31/2023
OpenGL version: 4.6
Color depth: 32 bit/pixel
Refresh rate: 60Hz
DirectX Card: Radeon(TM) RX 460 Graphics
Manufacturer ID: 0x1002
Card ID: 0x67ef
Revision: 0xcf
Number of screens: 1
Number of logical video cards: 1
SLI or Crossfire not detected
Main resolution screen: 1280 x 1024
Desktop resolution: 1280 x 1024
Main size screen: 13.27" x 10.63" (16.97" diag), 33.7cm x 27.0cm (43.1cm diag)
Base type tires not defined
Main size video memory not defined
Supported anti-aliasing modes: 2x 4x 8x
Sound card:
Audio Device: Speakers (Realtek High Definiti
Memory:
RAM: 8190 MB DDR2
Virtual reality devices:
VR headset: not detected
Miscellaneous:
Interface language: Russian
Media type: DVD
Total disk space: 607466 MB
Most free disk: 37195 MB
OS installation date:  03 2023
Game controller: None
Number of SSDs: 0
Number of hard drives: 2
Hard drive sizes: 500G,160G
Number of removable media: 0

**Comment by aylaylay** [comment]
Verify your files

**Comment by ddos-pro** [comment]
@aylaylay 
I did it and it doesn’t help, now I’m trying to adjust file permissions, maybe it will help

I tried running it as an administrator, entering some parameters to run it, namely -novid -dx11 -vulkan

**Comment by aylaylay** [comment]
You have old files

**Comment by ddos-pro** [comment]
@aylaylay
Are you talking about what I tested?

**Comment by ddos-pro** [comment]
Oh strange, I ran the check again, something is shaking

**Comment by ddos-pro** [comment]
Still doesn't work with the same error 
[Log.log](https://github.com/Facepunch/sbox-issues/files/14741880/Log.log)

**Comment by aylaylay** [comment]
Delete all files and reinstall the game

**Comment by ddos-pro** [comment]
@aylaylay 
This will be the third reinstallation :D

**Comment by aylaylay** [comment]
You have old files so clearly not

**Comment by ddos-pro** [comment]
@aylaylay Thank you very much for your help, everything works and indeed the old files remained, but I didn’t notice that the folder was not empty after deleting it from Steam, can I put a like or a star somewhere?
