### ISSUE TITLE
Crashes after uploading to the server

### ISSUE THREAD

**Issue by ddos-pro** [Facepunch/sbox-issues#5278]
### Describe the bug

.

### To Reproduce

I turn on the game, go to maps and go to the server
![image](https://github.com/Facepunch/sbox-issues/assets/65665142/13ecd13c-2002-4fc5-b257-a4d9986c735b)

### Expected behavior

.

### Media/Files

Log: 
[Log.log](https://github.com/Facepunch/sbox-issues/files/14743997/Log.log)

**Comment by ddos-pro** [comment]
Checking files doesn't give anything

**Comment by handsomematt** [comment]
can you post your system specs (cpu, ram, gpu) and steamid64

https://docs.facepunch.com/s/sbox-dev/doc/reporting-errors-2OTPIafqCJ

**Comment by ddos-pro** [comment]
@handsomematt 

Computer information:
Manufacturer: Gigabyte Technology Co., Ltd.
Model: EP43-DS3L
Type: desktop
Touch input is not supported
CPU:
Processor manufacturer: GenuineIntel
Processor brand: Intel(R) Xeon(R) CPU X5460 @ 3.16GHz
Processor family: 0x6
CPU model: 0x17
CPU stepping: 0x6
Processor type: 0x0
Clock frequency: 3166 MHz
Logical processors: 4
Physical processors: 4
Hyper-Threading: Not supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Not supported
SSE41: Supported
SSE42: Not supported
AES: Not supported
AVX: Not supported
AVX2: Not supported
AVX512F: Not supported
AVX512PF: Not supported
AVX512ER: Not supported
AVX512CD: Not supported
AVX512VNNI: Not supported
SHA: Not supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Not supported
OS version:
Windows 10 (64-bit) Corporate LTSC 1809 11763
NTFS: Supported
Provided crypto codes: Supported 311 0x0 0x0 0x0
Video card:
Driver: Radeon(TM) RX 460 Graphics (Connected Display Port)
DirectX Driver: aticfx32.dll
Driver version: 31.0.21902.5
DirectX driver version: 31.0.21902.5
Driver release date: 8/31/2023
OpenGL version: 4.6
Color depth: 32 bit/pixel
Refresh rate: 60Hz
DirectX Card: Radeon(TM) RX 460 Graphics
Manufacturer ID: 0x1002
Card ID: 0x67ef
Revision: 0xcf
Number of screens: 1
Number of logical video cards: 1
SLI or Crossfire not detected
Main resolution screen: 1280 x 1024
Desktop resolution: 1280 x 1024
Main size screen: 13.27" x 10.63" (16.97" diag), 33.7cm x 27.0cm (43.1cm diag)
Base type tires not defined
Main size video memory not defined
Supported anti-aliasing modes: 2x 4x 8x
Sound card:
Audio Device: Speakers (Realtek High Definiti
Memory:
RAM: 8190 MB DDR2
Virtual reality devices:
VR headset: not detected
Miscellaneous:
Interface language: Russian
Media type: DVD
Total disk space: 607466 MB
Most free disk: 37195 MB
OS installation date: 03 2023
Game controller: None
Number of SSDs: 0
Number of hard drives: 2
Hard drive sizes: 500G,160G
Number of removable media: 0

**Comment by handsomematt** [comment]
steam id please

**Comment by ddos-pro** [comment]
@handsomematt 
Wait a minute

**Comment by ddos-pro** [comment]
@handsomematt 
STEAM_0:0:23450846

**Comment by handsomematt** [comment]
The crash is a compiler bug on your older CPU not supporting AVX2. I will update the build server as Microsoft say it's fixed. I also think @aylaylay wants to remove this concurrency stuff anyway.

![image](https://github.com/Facepunch/sbox-issues/assets/1388267/a4d05563-950b-4d73-b471-c0b933b9c4f6)

**Comment by handsomematt** [comment]
thats wonderful, i will let you know when its fixed

**Comment by ddos-pro** [comment]
@handsomematt  Waiting for the game update right?

**Comment by ddos-pro** [comment]
Do you also see logs from creating your server? Crashed again, no update arrived

**Comment by ddos-pro** [comment]
Log 
[Log.log](https://github.com/Facepunch/sbox-issues/files/14744702/Log.log)

**Comment by ddos-pro** [comment]
@handsomematt @Nolankicks 
Do you also see logs from creating your server? Crashed again, no update arrived

Log 
[Log.log](https://github.com/Facepunch/sbox-issues/files/14744702/Log.log)

**Comment by ddos-pro** [comment]
I managed to log into my server without crashing, I’ll try to go somewhere else
![image](https://github.com/Facepunch/sbox-issues/assets/65665142/20ca85b9-089f-455a-9ea3-7ba1300e8c84)

**Comment by ddos-pro** [comment]
Almost everything is fine, the only concern is that the processor is eating half and no more than 53%
how can this be fixed?
![image](https://github.com/Facepunch/sbox-issues/assets/65665142/5c3f00bc-7690-4e07-87cf-a1aee8896533)

**Comment by MrBrax** [comment]
i have a sneaking suspicion that's because it's a 17 year old cpu?

**Comment by ddos-pro** [comment]
@MrBrax Yes :D

Surprisingly, earlier when I tested the build from 22, everything was smooth without glitches and slowdowns of 60 fps, just like in cs2 at release, only now you can’t play cs2 without sse4.2 support
