### ISSUE TITLE
CitizenAnimationHelper lacking documentation

### ISSUE THREAD

**Issue by fantasticaneer** [Facepunch/sbox-issues#5279]
### What it is?

CitizenAnimationHelper is lacking any real documentation that I can find, even in the api reference for each method and property... maybe it's assumed these should be self evident but it'd be really nice to say least get a one-line description of what each one does and why you'd use it, as does exist for much of the rest of the API.

I know the basic usage is probably, 'it controls and accesses the parameters that the citizen uses in order to animate' but it's quite vague in many cases how it does so, and you shouldn't have to investigate the citizen's animgraph and scour the code to find out.

If this does exist somewhere it's at least not surfaced on the website or anywhere on the docs site or wiki.

### What should it be?

It'd be really nice to say least get a one-line description of what each method and property is / does and why you'd use it. It seems really useful theoretically and I want to use it but I don't know how.

**Comment by Nolankicks** [comment]
I think using it is pretty straight forward. But it wouldn’t hurt to add some documentation.

**Comment by DevulTj** [comment]
I've documented the properties and methods for this class now.
