### ISSUE TITLE
Dotted grid for source 2 2d View (and possibly 3d)

### ISSUE THREAD

**Issue by VCSoldier** [Facepunch/sbox-issues#528]
**What can't you do?**
I cant enable dotted grid in source 2, seems to not exist at all. its alot easier on my eyes compared to lined, and i like having visible grids since its easier to work with

**How would you like it to work?**
Add a setting similar to source 1s hammer in the tools > option menu with a toggle for 2d grid, and 3d grid, 3d could be seperate but im not the coder here 

**What have you tried?**
i tried gridless but its frustrating to work with as i dont know if its scaled correctly

**Additional context**
also proof on why dotted should be added, (a very exxagerated example to go off but its still an example)
![image](https://user-images.githubusercontent.com/50423227/127578903-ef1a91b9-7c9f-41a6-adc5-9b31c6bfed10.png)
This is what lined looks like at 1 unit snap

![image](https://user-images.githubusercontent.com/50423227/127578918-6f4a5453-a83a-49ba-948c-b0fc5337cafb.png)
this is what dotted looks like at 1 unit snap

dotted is clearly alot easier to read compared to lines.

**Comment by aylaylay** [comment]
Here you go. Please close the issue if you're happy with it.

<img width="810" alt="sbox_7JkbhWwAbW" src="https://user-images.githubusercontent.com/1667289/127763567-f449a460-12ac-4b39-b8f7-f970797fb1c8.png">

**Comment by VCSoldier** [comment]
Thank you layla, this looks great, ill close this issue now

**Comment by VCSoldier** [comment]
eopening to say that if you zoom out far enough, the grid re-appears, but with a dotted outline instead of a full white one
![image](https://user-images.githubusercontent.com/50423227/128422421-7e0737ae-e2fe-47c6-a9cc-2ee9e1d34390.png)

**Comment by aylaylay** [comment]
Just pushed a fix

**Comment by aylaylay** [comment]
Please close the issue if you're happy with the change
