### ISSUE TITLE
Add CreateGibs method to all model renders

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5281]
### For?

S&Box

### What can't you do?

Currently the CreateGibs method is exclusive to the prop component. But sometimes it doesn’t make sense to have all of the components bundled with the prop component to create gibs.

### How would you like it to work?

I would like this method to be added to the skinned model render and model render. 

### What have you tried?

The method only exists for the prop component.

**Comment by handsomematt** [comment]
Nope, the ModelRenderer is for rendering models, the Prop component is for all this extra shit.
