### ISSUE TITLE
listener for animgraph tags

### ISSUE THREAD

**Issue by johncosfm** [Facepunch/sbox-issues#5282]
### For?

S&Box

### What can't you do?

I have status tags set up to trigger for specific animgraph actions that need to be handled by code. However it doesn't seem like there is any way to set up a listener or check the status of animgraph tags from code or action graph.

### How would you like it to work?

something along the lines of this would be convenient, equivalent to what 'RegisterAnimTagListener(handle hAnimTagListenerFunc)' gets in half life alyx vscript except without needing to specifically register it.
```
protected override void OnAnimGraphTag( string tag, AnimGraphTagEvent status) {
    if ( tag == "tag_name" ) {
        if (status == AnimGraphTagEvent.Start) {
            // tag activated
        } else if (status == AnimGraphTagEvent.End) {
            // tag deactivated
        } else if (status == AnimGraphTagEvent.Fired) {
            // tag activated and then deactivated during the animgraph update
        }
    }
}
```

And just for the sake of convenience it would be nice to be able to be able to read the current state of tags with something like this, so that it's easy to use tags in conditional statements without having to store and keep the value updated for any tags you want.
```
SkinnedModelRenderer.AnimTags.Has("tag_name")
```

### What have you tried?

I and several other people have searched high and low for this functionality, with no luck. If it exists it is very well hidden.

It is possible to use animation events rather than animgraph tags in most scenarios, but animgraph tags generally offer a lot more control, and can be used to trigger events outside of specific animations (for example in half life alyx ai will wait for specific animgraph tags to activate before continuing, and these tags are activated from state machines rather than animations).

### Additional context

In half life alyx only the blue status tags will call the listener function. It might be worth having all events call the function, perhaps with any extra information that the tag might contain. For me personally just having it on status tags is perfectly fine though.

**Comment by johncosfm** [comment]
That only fires for anim events (from modeldoc), not anim tags (from animgraph). I need the animgraph ones
![image](https://github.com/Facepunch/sbox-issues/assets/69829964/a4ec1f49-8b0e-4b27-91cb-ed2946248aae)

**Comment by aylaylay** [comment]
SceneModel and SkinnedModelRenderer now has OnAnimTagEvent
