### ISSUE TITLE
ModelBuilder enhancements

### ISSUE THREAD

**Issue by Marky-S** [Facepunch/sbox-issues#5284]
### For?

S&Box

### What can't you do?

1. Change the `pivot`/`origin` of `Model` by `ModelBuilder`
2. Change distance for each LOD manually by `ModelBuilder`, only for all LODs same distance now

### How would you like it to work?

1. Some API such as `modelBuilder.SetModelOrigin(Vector3 origin)` or overload for `modelBuilder.Create()`
2. Some API such as `modelBuilder.SetLODDistance(int lod, float distance)`

### What have you tried?

I don't tried anything because i can't imagine other ways to achieve this features

### Additional context

I procedurally created large sphere from origin point `0, 0, 0` and divide it into small chunks. Every chunk has it's own `GameObject` and `LOD`, but `LOD` don't works well due origin point of this chunks (i think `LOD` switching binded to origin of `GameObject`)
![image](https://github.com/Facepunch/sbox-issues/assets/80411728/504c38a3-4ed1-4909-99af-918eb5ca56c1)

_P.S. Any one of this requested API will resolve this problem_

**Comment by aylaylay** [comment]
Why do you need model origin? Just offset the vertices to be local to origin, that's all it would be doing internally anyway.

**Comment by Marky-S** [comment]
> Why do you need model origin? Just offset the vertices to be local to origin, that's all it would be doing internally anyway.

might be i stupid(, but i can't figure out how to do it, there is my code

```csharp
var pointOnCube = _localUp + ( tx - 0.5f ) * 2 * _tangent + ( ty - 0.5f ) * 2 * _biNormal;

var x2 = pointOnCube.x * pointOnCube.x;
var y2 = pointOnCube.y * pointOnCube.y;
var z2 = pointOnCube.z * pointOnCube.z;
				
var pointOnSphereX = pointOnCube.x * float.Sqrt(1 - (y2 + z2) / 2 + (y2 * z2) / 3);
var pointOnSphereY = pointOnCube.y * float.Sqrt(1 - (z2 + x2) / 2 + (z2 * x2) / 3);
var pointOnSphereZ = pointOnCube.z * float.Sqrt(1 - (x2 + y2) / 2 + (x2 * y2) / 3);
				
var pointOnSphere = new Vector3( pointOnSphereX, pointOnSphereY, pointOnSphereZ );

var vertex = new Vertex( pointOnSphere * _radius, pointOnSphere, _tangent, new Vector4( 0, 0, 0, 0 ) );
```

**Comment by aylaylay** [comment]
Subtract the origin from the vertices

**Comment by Marky-S** [comment]
> Subtract the origin from the vertices

My origin is `new Vector(0.0f, 0.0f, 0.0f)` there is the whole generation. 
![image](https://github.com/Facepunch/sbox-issues/assets/80411728/32a87709-33de-4f44-9679-8a06fcb6e1e7)
The way i generating this sphere is calculating direction of every vertex and multiply it then by `radius`

**Comment by aylaylay** [comment]
1. Calculate chunk origin, bounds center of all vertex in that chunk
2. Subtract that origin from all the vertices in that chunk
3. Move the gameobject to that origin

**Comment by aylaylay** [comment]
Added `modelBuilder.SetLODDistance(int lod, float distance)`

**Comment by Marky-S** [comment]
> 1. Calculate chunk origin, bounds center of all vertex in that chunk
> 2. Subtract that origin from all the vertices in that chunk
> 3. Move the gameobject to that origin

`bounds.Center` returns weird value due, i think, negative min/max values.. investigating...
