### ISSUE TITLE
Bring back search to the API page on asset.party

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5286]
### For?

Other

### What can't you do?

It used to be so easy to search through the api with a single keyword, looking through not only class/function names but also their descriptions made it easy to find anything you wanted in a flash. With the way it is now, it's impossible to research whether or not certain functionality exists since namespace/class/function names might not always be immediately obvious.

### How would you like it to work?

The way it used to.

EXAMPLE:
Searching for `gamemode` returns results with "gamemode" in the name or summary
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/caf28556-17eb-4c4b-963f-fbe14d811749)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/d63befec-cd72-4ac7-bb15-7fe18481c722)

### What have you tried?

Asking the discord blindly. There's probably ways to do it with dotpeek too but it should really be part of asset.party again.

**Comment by ScoutWozniak** [comment]
I'd argue having the old search functionality in full would be nice

**Comment by Retroeer** [comment]
Yeah I came here to say that aswell, really wish the search bar came back all together rather than exclusively on specific pages

**Comment by Nolankicks** [comment]
I just use crl f but it wouldn’t hurt to have the search functionality back.

**Comment by CarsonKompon** [comment]
> I just use crl f but it wouldn’t hurt to have the search functionality back.

CTRL+F doesnt work for functions, only class names (unless you already know the class name and go that that class and CTRL+F. But then you're not searching the entire API)

**Comment by Nolankicks** [comment]
Didn’t know that. Thanks for telling me

**Comment by MD485** [comment]
I was wondering why I remember being able to search the documentation on some of the portals earlier, but seem to have lost that ability now.  

I'd really appreciate this also.  
I wanted to help someone with an issue earlier but couldn't find the documentation page in the api.
