### ISSUE TITLE
Grid Snapping In Scene go lower than 1+ keybind doesn't go to 1.

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#5289]
Similar to hammer there are grid snapping options below 1;
![image](https://github.com/Facepunch/sbox-issues/assets/8184184/3f80d97a-c016-47ee-8f9c-d2221f147105)

I would like to be able to go lower than 1, also the using the brackets "[ ]" doesn't allow you to go below 4 (and sometimes 2).

**Comment by DevulTj** [comment]
You can now push the grid all the way down to 0.125 like you wanted, with the keybind or in the gizmo preferences menu
