### ISSUE TITLE
SystemAccessViolation when constructing a default Mesh

### ISSUE THREAD

**Issue by p0gchamp** [Facepunch/sbox-issues#529]
Constructing a mesh throws SystemAccessViolation. It does work with the one with material as argument. (This is probably a duplicated issue if this happen im sorry!)

**To Reproduce**

Construct a default mesh.

```csharp
public override void Simulate( Client cl )
{
	if(Input.Pressed(InputButton.Use) && IsClient)
	{
		Mesh mesh = new();
		VertexBuffer buffer = new();
		buffer.AddQuad( new Rect( 0, 0, 40, 40 ) );
		mesh.CreateBuffers( buffer );
				

		var modelBuilder = new ModelBuilder();
		var m = modelBuilder.AddMesh( mesh ).Create();

		var modelEntity = new ModelEntity();
		modelEntity.SetModel( m );
		modelEntity.Position = cl.Pawn.Position + Vector3.Up * 5;
	}
	base.Simulate( cl );

}
```

System.AccessViolationException
  HResult=0x80004003
  Mensaje = Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Origen = <No se puede evaluar el origen de la excepción>
  Seguimiento de la pila:
<No se puede evaluar el seguimiento de la pila de excepciones>

**Expected behavior**

A nicely done Quad with debugmaterial.

**Screenshots**

![Captura](https://user-images.githubusercontent.com/52977370/127584424-dd0f8c22-2305-4d7e-be1f-eb14862b5c13.PNG)

**Additional context**

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by p0gchamp** [comment]
Fixed thanks!
