### ISSUE TITLE
Transforms Sometimes Randomly Break

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#5290]
### Describe the bug

I've been getting this weird issue in my project for a while where the transforms suddenly seem to break. I might be doing something weird but the issue seems to be internal, judging from the stack trace?

```
2024/03/27 22:15:31.3448	[GameMenu] Exception when calling 'FixedUpdate' on Player on (player)	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.GameTransform.set_Local(Transform value)
   at Sandbox.GameTransform.set_LocalPosition(Vector3 value)
   at SandboxCity.SkeletonCarBase.RaycastWheels() in C:\Users\antho\Documents\s&box projects\sandbox_city\code\entities\vehicles\SkeletonCarBase.cs:line 521
   at SandboxCity.SkeletonCarBase.DoUpdate() in C:\Users\antho\Documents\s&box projects\sandbox_city\code\entities\vehicles\SkeletonCarBase.cs:line 440
   at SandboxCity.DriveableCar.DoUpdate() in C:\Users\antho\Documents\s&box projects\sandbox_city\code\entities\vehicles\driveable\DriveableCar.cs:line 128
   at SandboxCity.SkeletonCarBase.FixedUpdate() in C:\Users\antho\Documents\s&box projects\sandbox_city\code\entities\vehicles\SkeletonCarBase.cs:line 402
   at SandboxCity.Player.OnFixedUpdate() in C:\Users\antho\Documents\s&box projects\sandbox_city\code\player\RolePlayer.cs:line 1569
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

The line of code that triggers it is this:

```
FrontLeftWheel.Transform.LocalPosition =
	FrontLeftWheel.Transform.LocalPosition.WithZ( Math.Clamp( WheelDiameter - FrontLeftDistance, 0, float.MaxValue) );
```

If I log the value being used in WithZ it seems reasonable, it's just a regular float

### To Reproduce

I have a way of reproducing this... it's sort of specific to my game but it's:

- Player enters vehicle (player becomes a child of the vehicle object)
- Press play (to stop the game)
- Press play again (to start the game)
- Try and enter same vehicle
- Spams errors

I can (usually) avoid the issue by doing this:

- Player enters vehicle (player becomes a child of the vehicle object)
- Player exits vehicle (player is unparented form the vehicle)
- Press play (to stop the game)
- Press play again (to start the game)
- Try and enter same vehicle
- No errors

My guess is that when you stop the game, the transforms somehow are not getting reset properly, or are getting corrupted?

Sometimes this issue randomly happens even if I leave the vehicle before stopping the game though

BTW, once this error starts happening on a particular car, I have to reset s&box to get it to work again. But one workaround for me is to just duplicate the car, and then that car starts working (so the issue definitely seems to be tied to the gameobject becoming corrupted somehow)

### Expected behavior

No errors

### Additional context

Might be able to fix this just looking at the stack trace, but if not then let me know and I can email over a smallish repro project or something

**Comment by kurozael** [comment]
Hey @anthonysharpy can ya send a repro project to the email in my profile?

**Comment by anthonysharpy** [comment]
@kurozael Yeah sure no worries, will try and send one over asap

**Comment by anthonysharpy** [comment]
@kurozael Hey, sorry for the wait, have just sent this over today

**Comment by kurozael** [comment]
Weirdly, @anthonysharpy, herein lies the root of your issue: it's your caches in `EntityHelper`. If you disable / remove all your caching for ComponentCache and GOCache, you should find everything works as normal.

I believe the problem is that the GOCache and ComponentCache static Dictionaries are not being reset each time you start the game / load the scene. Meaning old references to components and GameObjects are being used - and for those references the `GameObject.Scene` is null. This causes your errors.

We should figure out internally how we wanna handle this kind of thing.
