### ISSUE TITLE
Masks cause issues for World Panels

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5295]
### Describe the bug

I've managed to make a repo for this bug, which you can see in the video below:

https://github.com/Facepunch/sbox-issues/assets/7847372/4afccd2e-11ea-43be-abe3-29dcd292504e

https://github.com/Facepunch/sbox-issues/assets/7847372/dcd3e41e-9df4-4c33-9449-4cede0b412de

The issue is only present when I enable masks in my scss like this:
```css
    mask-size: 100% 100%;
    mask-image: url("textures/ui/bars/resource_bar_mask.png");
    mask-position: left;
    mask-repeat: no-repeat;
    mask-mode: alpha;
```

### To Reproduce

1. Download the bug repo, play the scene
2. Move back and forth away from panels, you can see they start to render unexpectedly.

### Expected behavior

Should look basically the same as they do when the mask is disabled.

### Media/Files

[bug_repo.zip](https://github.com/Facepunch/sbox-issues/files/14797537/bug_repo.zip)

**Comment by xezno** [comment]
Masks are just fancy filters, which I've fixed now
