### ISSUE TITLE
Camera.RenderToTarget doesn't work on secondary cameras

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#5296]
### Describe the bug

In reference to this issue:
https://github.com/Facepunch/sbox-scenestaging/issues/68

Camera.RenderToTarget seems to work fine on any camera with the "IsMainCamera" flag set to true, but if you try using it on a camera which is not the MainCamera, IsMainCamera == false, the game immediately crashes.

@handsomematt Given that you moved the issue to ready in the tracker I'm assuming you're famililar with the implementation?

### To Reproduce

1. Open up a new scene.  
2. Make two gameobjects with cameras.
3. Turn off one of those cameras IsMainCamera.
4. Use that camera to RenderToTexture.
5. Game crashes.

### Expected behavior

Rendering to a target should work just as well on non-main cameras as the main camera, failing that a meaningful error message would be preferred to the game just closing and leaving no information in the logs to figure out why.

### Media/Files

```cs
public sealed class CameraTest : Component
{
	[Property] public GameObject CameraObject { get; set; }
	[Property] public int Counter { get; set; }
	[Property] public Texture Tex { get; set; }
	protected override void OnEnabled()
	{
		base.OnEnabled();
		var camera = Components.Get<CameraComponent>();
		var cameraRect = camera.ScreenRect;
		
		Tex = Texture.CreateRenderTarget()
			.WithSize( cameraRect.Width.CeilToInt(), cameraRect.Height.CeilToInt() )
			.Create();
		
		camera.RenderToTexture( Tex );
		Counter++;
	}
}
```
The component I was using to help with verification.

**Comment by GavrilovNI** [comment]
Was working fine in my project yesterday

**Comment by MD485** [comment]
> Was working fine in my project yesterday (now have no idea) Try to do it not in onenable Also I think showing logs would be appreciated

The logs tended to cut out without showing any extra information.
Sometimes they would say:
`2024/03/29 02:15:34.7358	[engine/ToolFramework2] Shutting down Qt windows.............	
2024/03/29 02:15:34.7358	[engine/Engine] Source2Shutdown	
2024/03/29 02:15:34.7358	[engine/Engine] ShutdownSource2Logging	`
Or something similar, but that doesn't really explain anything.

OnEnable was so it was easy to verify, you can start the scene with it unenabled, then enable it to make sure it's only related to the method running. As opposed to adding more logic.

But I can no longer reproduce this issue since an update I installed today, it's possible only I was experiencing this issue at all, given some esoteric hardware configuration or software installation issue.

I'll close it since I can no longer reproduce it.
