### ISSUE TITLE
Api error on new and existing projects

### ISSUE THREAD

**Issue by kira0x1** [Facepunch/sbox-issues#5297]
### Describe the bug

Constantly getting this api error in my s&box projects, tested on a new project and would still get this error 

```
Exception when getting API "https://services.facepunch.com/sbox/package/get/local.citadel"
System.InvalidOperationException: Backend error - returned BadRequest
   at Sandbox.Api.GetAsync[T](String url, Dictionary`2 values, Single cacheSeconds, CancellationToken token)
```

### To Reproduce

Open already existing sbox project or create a new one from scratch, and then just check the console	

### Expected behavior

Should not be spamming console with errors every few minutes

### Media/Files

> new project
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/5253d5e9-d455-4873-9b1f-6d049c97fce4)
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/daa708b9-8b53-4d70-b0ad-effd280bd355)

> existing project
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/fcc1e378-e524-425a-9b8d-5a95dda8baa1)

### Additional context

os: windows 11
gpu: 3070ti
ram: 32gb ram,
cpu: intel i5-12400F

**Comment by kira0x1** [comment]
any updates on this?

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by kira0x1** [comment]
> Should be fixed now

thank you.

**Comment by ryleigh** [comment]
This is happening to me on a newly created project

```
2024/04/29 19:56:59.4640	[Generic] Exception when getting API "https://services.facepunch.com/sbox/package/get/local.ss1"	System.InvalidOperationException: Backend error - returned NotFound
   at Sandbox.Api.GetAsync[T](String url, Dictionary`2 values, Single cacheSeconds, CancellationToken token)
```

[Log.log](https://github.com/Facepunch/sbox-issues/files/15157313/Log.log)

**Comment by kira0x1** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/74b55a7f-f796-4f51-98b5-bb14121feeef)
seems to keep happening ( this is on a new pc with a fresh install of sbox aswell )
