### ISSUE TITLE
MusicPlayer.Seek doesn't work when called immediately after MusicPlayer.Play

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5299]
### Describe the bug

This does not work:
```cs
Music = MusicPlayer.Play(FileSystem.Mounted, "mysound.mp3");
Music.Seek(15f);
```

However the following **DOES** work for whatever reason:
```cs
Music = MusicPlayer.Play(FileSystem.Mounted, "mysound.mp3");
Log.Info("Logging something to console in-between playing and seeking makes this work for some reason...");
Music.Seek(15f);
```

My assumption is that it takes 0.001s to log to console which is enough delay to allow the Seek to go through? Idrk 😅 

### To Reproduce

Try the code I posted with any mp3/ogg/ect file.

### Expected behavior

It should seek properly.

**Comment by aylaylay** [comment]
I've not got a repro to test this but I've pushed a fix that might fix this

**Comment by CarsonKompon** [comment]
Didn't seem to fix it for me. I'll try making a repro.

**Comment by CarsonKompon** [comment]
Here's a simple repro project with a quick video showing the behaviour I'm experiencing.
[music_seek_repro.zip](https://github.com/Facepunch/sbox-issues/files/14815516/music_seek_repro.zip)

https://github.com/Facepunch/sbox-issues/assets/5159369/9894458c-1010-446d-9e36-85e3023bdd2d

**Comment by aylaylay** [comment]
Thanks, I'll have a fuck around with it

**Comment by CarsonKompon** [comment]
In my own project I also noticed that sometimes seeking will cause no audio to play and my console will be spammed with the following until I exit and re-enter play mode:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/152d40d5-492b-44b6-a5ee-42a0f0de03f5)

**Comment by aylaylay** [comment]
Seek should be fixed now
