### ISSUE TITLE
duplicated maps in map search

### ISSUE THREAD

**Issue by JustPlayerDE** [Facepunch/sbox-issues#530]
**Describe the bug**

If you search for a specific map there are sometimes up to 3 lists.

**To Reproduce**

1. Select any gamemode (with map selector)
2. Open Map selector for the gamemode
3. Search for anything specific (e.g. `sandbox` or  `construct`)
4. You may need to select a different order
5. See the same items 4 times

**Expected behavior**
It should only show every item once

**Screenshots**
![image](https://user-images.githubusercontent.com/19864478/127613128-81a3ddf5-d0d7-433f-bcff-e90b862ad05d.png)

https://files.justplayer.de/justin/f044411d44661ff001de979328bee6521af125bc.mp4

**Comment by garrynewman** [comment]
Fixed
