### ISSUE TITLE
SegmentedControl Widget has no public method to set the Selected option

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5300]
### For?

S&Box

### What can't you do?

Currently, the SegmentedControl widget does not allow for programmatic selection control. The only way to change these options are manually clicking. I want to make the widget responsive to the tab key, so allowing me to set the index manually would be greatly appreciated.

### How would you like it to work?

Expose selectedIndex as public

### What have you tried?

Easy workaround: make your own widget. But it makes sense to have it on this widget imo 😸

**Comment by xezno** [comment]
Should be fixed next update
