### ISSUE TITLE
[Launcher] Newly created projects should show up at the top

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#5303]
When you create a new project while having lots of existing projects, there's no indication where the new one is.

After you figure out that it's at the bottom (with all your oldest projects) and open it, it'll move to the top of the list.

Feels a bit janky.

https://github.com/Facepunch/sbox-issues/assets/1173137/daf72fb1-3ef8-4272-aa46-057fd60ce81a

**Comment by handsomematt** [comment]
#5162 - but also why the fuck isn't a project opening after being created, we should fix that too
