### ISSUE TITLE
Voice Component is unclear/lack of functionality

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5304]
### What it is?

Hi,

I would like to create a Team Voice Chat, but currently, it's impossible or it's very unclear:
- Voice component is sealed, so i cannot extend it
- Only `Voice.IsListening` has a setter
- `VoiceManager` static class is private, so i cannot test anything thing like `VoiceManager.OnCompressedVoiceData`
- `Application.IsMicrophoneRecording` and `Application.IsMicrophoneListening` work but are not helpful for creating a Team Voice Chat

### What should it be?

I dunno what would be the correct API for creating a voice chat logic, but if you can bring something clear like the old Voice API from the Entity system it would be cool.

Regards

**Comment by aylaylay** [comment]
You can do team voice chat now by overriding ExcludeFilter
