### ISSUE TITLE
`animation-iteration-count: infinite` doesn't work anymore

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5306]
### Describe the bug

Hi,
Today i was surprised to see that `animation-iteration-count: infinite` doesn't work anymore.
This worked well a few days before, and putting numbers still works; only `infinite` is bugged

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `MockHudPanel.razor.scss` :

a) Add keyframes
```
@keyframes spin {
    from {
        transform: rotate(0deg);
    }

    to {
        transform: rotate(360deg);
    }
}
```
b) Put css attributes on the panel you want to spine :
```
animation-name: spin;
animation-iteration-count: infinite;
animation-duration: 1s;
```

3) Start `test.ui.scene`, see no spinning running.
4) Change `infinite` to number, it's work

### Expected behavior

Working `infinite` attribute

**Comment by CarsonKompon** [comment]
Yup, just came to make this issue cause I was experiencing the same thing. Current workaround is to have 99999 iterations or something but that's a bit silly

**Comment by PolSpock** [comment]
[MbK gave me another workaround](https://discord.com/channels/833983068468936704/902501842724978699/1223701743242838057) : `animation-fill-mode: revert;` but still weird

**Comment by xezno** [comment]
Should be fixed next update
