### ISSUE TITLE
Polish: Restarting or Creating server with sv_password set prevents you from creating the server unless password set too.

### ISSUE THREAD

**Issue by Acecool** [Facepunch/sbox-issues#531]
**What can't you do?**

I wouldn't call this a bug necessarily but more of an ease of use feature / gray area because if you are creating a server it shouldn't ask you to supply the password you just supplied to protect it... 

It falls in-between because you are creating a local server, and if you are creating it, why do you need to set the client password variable if you have access to, and have defined sv_password yourself because it prevents the server from being created which defeats the purpose of clicking create server...

When dedicated servers come around, I 100% agree with this behavior. However, if you are hosting on the same computer / ip, then maybe allow bypassing this. Not necessary but could be a nice feature.

I'm putting it under feature requests because it could be seen as a bug in the sense of creating a local server, but on the other hand it is logically doing exactly what it is supposed to do which is prevent someone from connecting unless their local password variable is set to the same as sv_password..

It kind of is a polish issue because sv_password could be checked on the client to see if it is the same as the current server, or if you are creating the server then ignore the need for a password unless you are creating a dedicated server. If creating a dedicated server and connecting from the host box, maybe allow connecting without a password?

**To Reproduce**

Create a server
type sv_password 123 in console and press enter
type restart in console and press enter
You'll get the following error: loopback:0:  password failed.

**How would you like it to work?**

If you create a local server with sv_password defined, then do not require password to be defined on the local machine OR have it check the sv_password var on the client to see if it is the same as the server so it doesn't have to be entered multiple times.

If you create a dedicated server, when this becomes available, retain this behavior - although a polish / useful feature could be if connecting from the host box, allow to join without a password.

**What have you tried?**

I've now added the password command to my sv_password bind so this issue won't occur again for me.

**Additional context**

Low priority ease of use polish update...

**Comment by ischmal** [comment]
Yes, please. This has been neglected for too long. 

I get that this is merely a quality-of-life feature, but having to constantly set and unset passwords, session-after-session, week-after-week, is becoming profoundly obnoxious.

**Comment by robotboy655** [comment]
This should be fixed with the next game update. Feel free to close this issue if you can confirm its fixed.

**Comment by FlorianLeChat** [comment]
I just did the test, it works perfectly, thank you! Also, the issue #132 which was in a way linked is also fixed and can be closed.
