### ISSUE TITLE
Implement IEnumerable<T> by NetList<T>, implement IEnumerable<KeyValuePair<TKey, TValue>> by NetDictionary<TKey, TValue>

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#5310]
### What it is?

NetList<T> doesn't implement IEnumerable<T>
NetDictionary<TKey, TValue> doesn't implement IEnumerable<KeyValuePair<TKey, TValue>>

### What should it be?

NetList<T> should implement IEnumerable<T>
NetDictionary<TKey, TValue> should implement IEnumerable<KeyValuePair<TKey, TValue>>

This will allow using linq

these classes already have corresponding GetEnumerator() method, they just don't implement those interfaces

**Comment by anthonysharpy** [comment]
I think it's to do with the fact that it doesn't implement IList and IDictionary, but yeah would be nice to have those LINQ methods on there

**Comment by kurozael** [comment]
Should be groovy.
