### ISSUE TITLE
Cannot download cloud assets

### ISSUE THREAD

**Issue by KETALx** [Facepunch/sbox-issues#5311]
### Describe the bug

When downloading any asset from asset.party, it gets fetched but doesn't proceed further to download (stuck on 0%)

### To Reproduce

1. Make any addon
2. Add item on scene from asset.party
3. Expect that model isn't downloading

### Expected behavior

asset should be downloading

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/14822174/Log.log)
![image](https://github.com/Facepunch/sbox-issues/assets/81901907/3976d48c-dff9-49d7-aeea-4285ce03338a)
[Log2.log](https://github.com/Facepunch/sbox-issues/files/14822196/Log2.log)
![image](https://github.com/Facepunch/sbox-issues/assets/81901907/1f030315-42a9-45ab-a0e1-81fdc912d803)

**Comment by handsomematt** [comment]
are you able to open https://cdn.sbox.game/asset/fpopium.psxassets/logo.92ee4561.png in your browser without issue

**Comment by KETALx** [comment]
yes, loads fine
![logo 92ee4561](https://github.com/Facepunch/sbox-issues/assets/81901907/9c18ca81-0bd9-4eff-8db4-b8c6515ad29b)

**Comment by handsomematt** [comment]
do you have any sort of firewall blocking requests from sbox-dev

**Comment by KETALx** [comment]
It worked fine few days ago and i haven't changed any firewall settings. Tried disabling firewall fully now and it didn't help, download is still stuck on 0%.

**Comment by KETALx** [comment]
odd, preview images also don't get loaded inside of sbox
![image](https://github.com/Facepunch/sbox-issues/assets/81901907/6b83af74-da7d-4517-8512-2ab46ccd3f86)

**Comment by handsomematt** [comment]
yeah your game isn't able to make http requests to cdn.sbox.game for whatever reason - usually firewall or isp

we haven't changed any of this code in the past week

**Comment by KETALx** [comment]
Enabling vpn fixed this issue, time to kick isp ass i guess
