### ISSUE TITLE
Blender 4.1 FBX import materials/uv broken

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5312]
### Describe the bug

I'm getting this error now when importing an FBX exported from Blender 4.1:

`Warning! Unsupported FBX Normal Mapping/Reference Mode 1/2`

Exporting the same model from 4.0 works fine.

### To Reproduce

1. Export FBX from Blender 4.1
2. Import into modeldoc

### Expected behavior

Work like previously

### Media/Files

[snake.zip](https://github.com/Facepunch/sbox-issues/files/14824398/snake.zip)

**Comment by MrBrax** [comment]
I found out why at least, the new smoothing stuff in 4.1 breaks exporting when selecting the old smooth option.

<img width="379" alt="1711986899821" src="https://github.com/Facepunch/sbox-issues/assets/1517911/dbd87637-d746-41e9-b8b0-763e3b19b91b">

**Comment by aylaylay** [comment]
I've added support for this but it's untested so can you test it for me please

**Comment by aylaylay** [comment]
Update your game

**Comment by aylaylay** [comment]
![sbox-dev_dLM93WimOE](https://github.com/Facepunch/sbox-issues/assets/1667289/5fd41783-408e-4b4a-9646-e0fb7e1ff5fa)

**Comment by MrBrax** [comment]
I was mistaken, it works on snake.fbx, but on my cockroach it's still broken.

[cockroach.zip](https://github.com/Facepunch/sbox-issues/files/14935152/cockroach.zip)

**Comment by aylaylay** [comment]
Should be fixed now
