### ISSUE TITLE
Transform.Position returns different values in OnFixedUpdate and OnUpdate after movement

### ISSUE THREAD

**Issue by the-remeko** [Facepunch/sbox-issues#5313]
### Describe the bug

Even after movement has stopped, the position returned by Transform.Position is different between OnFixedUpdate and OnUpdate.

### To Reproduce

Move any GameObject and then log Transform.Position in OnFixedUpdate and in OnUpdate. I attached a repro project that draws the position on the screen and lets you move a box around with WASD.

### Expected behavior

Transform.Position should be the same between OnFixedUpdate and OnUpdate after movement has stopped and lerping is finished.

### Media/Files

[onupdatepos.zip](https://github.com/Facepunch/sbox-issues/files/14827447/onupdatepos.zip)

![sbox-onupdatepos](https://github.com/Facepunch/sbox-issues/assets/94231804/f2b838db-5af9-4a4c-8543-db8d286ad7d9)

**Comment by the-remeko** [comment]
The incorrect OnUpdate position is also what gets networked to other players:
![sbox-onupdatepos2](https://github.com/Facepunch/sbox-issues/assets/94231804/f8d333ce-ba12-4029-b853-546a383e0684)

Here's an updated repro that supports multiplayer:
[onupdatepos.zip](https://github.com/Facepunch/sbox-issues/files/14827862/onupdatepos.zip)

**Comment by kurozael** [comment]
Related to #5321

**Comment by the-remeko** [comment]
This is fixed now.
