### ISSUE TITLE
[Sync] does not work with regular List

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5318]
### Describe the bug

I tried to use Sync on a regular List, but the list did not sync. Switching it to a NetList did work, however I believe that Lists should still work, they would just be less efficient since they will be sending the whole thing. I am basing my beliefs on this:

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/05a1d306-c881-408e-87db-45dff5fe5562)

I have not tested if Dictionary/NetDictionary is affected like this, too.

If regular Lists should not be networked, then please disregard this issue and feel free to close it, but in that case it would be useful to have this information mentioned somewhere easily accessible.

### To Reproduce

1. Have a synced list on an object
2. TakeOwnership of the object on a client (and make sure you really do own it)
3. Try changing the list
4. Check the list on other client to see that it did not sync

### Expected behavior

The List should be synced

**Comment by kurozael** [comment]
Hey @Gmod4phun can you send me a repro project? I'm seeing it work just fine for regular List and Dictionary with:

```csharp
	[Sync] public Dictionary<string,int> TestDictionary { get; set; } = new();
	[Sync] public List<int> TestList { get; set; } = new();
```

**Comment by Gmod4phun** [comment]
My bad, it seems to be working fine. The list was showing up as empty because of a piece of code that kept Clearing the list. Funnily enough it did not matter when I was using NetList, so there probably is an issue somewhere, but it's a different kind of issue. If I manage to get to the bottom of it, I will make another issue. Cheers :)
