### ISSUE TITLE
Rotating scaled object resets scaling

### ISSUE THREAD

**Issue by kira0x1** [Facepunch/sbox-issues#5322]
### Describe the bug

If you scale an object in the editor and then try rotating it the scaling resets.

### To Reproduce

1. Create cube in scene
2. scale cube in any axis
3. rotate cube in editor

### Expected behavior

model scaling should not be reset when rotating in the editor

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/13779328/cca3bef8-edfe-4430-8099-597f0e8a34e7

### Additional context

os: windows 11
gpu: 3070ti
ram: 32gb ram,
cpu: intel i5-12400F

**Comment by aylaylay** [comment]
Should be fixed now
