### ISSUE TITLE
V-Sync not working.

### ISSUE THREAD

**Issue by MrDaveDev** [Facepunch/sbox-issues#5323]
### Describe the bug

Everything, including the main menu, has a visual glitch. There’s a difference between the top and the bottom of the screen.

### To Reproduce

It happens on any change to the screen, in game. Mouse movement doesn’t do anything.

### Expected behavior

The screen should be producing one image, not two seperate ones.

**Comment by handsomematt** [comment]
I don't understand, can you take a screenshot and reopen if this is still an issue.
