### ISSUE TITLE
Incorrect scale/resize in Asset Browser

### ISSUE THREAD

**Issue by Titanovsky** [Facepunch/sbox-issues#5324]
### Describe the bug

Two bugs:

1 - When you click on files with different types in Asset Browser, the whole s&box editor changes height and goes to the bottom of the screen
2 - You can't resize the bottom panel normally (Console, Asset Browser are in default)

### To Reproduce

the first bug:
1. Click on Material file (any type)
2. Click on Scene file (any another type)

the second bug:
1. Just try resize the bottom panel and it doesn't work 

### Expected behavior

Obviously these are bugs and shouldn't be there

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/64440118/7e0cad6c-f73b-4159-9deb-ba08d79405c3

### Additional context

1366x768 
100% scale 
Windows 10
650 Ti

**Comment by ProgressTeamRU** [comment]
Good

**Comment by ProgressTeamRU** [comment]
Fix pls @garrynewman
