### ISSUE TITLE
Add ability to preview anim bools in the inspector

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5325]
### For?

S&Box

### What can't you do?

Currently, you are unable to preview animations in the inspector.

### How would you like it to work?

I would like it to work like in this picture: 
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/84a35637-86fc-4775-b0d6-9ba215769fed)

### What have you tried?

There is no way to do this except in the anim graph source file. If you try to do this for models that are from asset.party, you get this error when trying to open them:
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/4abfb3a8-1aa9-4482-8fec-948fd17d8263)

### Additional context

![image](https://github.com/Facepunch/sbox-issues/assets/95300917/ace53322-e728-4c39-8e29-77d6b3b98de2)

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/ecd2ad97-1fe7-42a1-bf0a-13e7eafcc9a2
