### ISSUE TITLE
Controller input does not work in editor

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5327]
### Describe the bug

I think since the new controller update the editor doesn't receive any inputs anymore. Might be an issue with button actions in-game too.

### To Reproduce

1. Connect controller
2. Launch editor
3. Try to press buttons on controller in editor

### Expected behavior

For controller debugging to work without publishing a new version for every test

### Additional context

Xbox One Controller on Windows 10

**Comment by DevulTj** [comment]
What controller are you using?

When you go to s&box Properties -> Controller on Steam, what do you see? It should be this (where your controller is lit up): 
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/57b28029-c64f-4eaa-9441-73811cde711a)

Are you making sure that your game viewport is focused? The new system requires you to have focus on the game's viewport because it is running through the same path as keyboard input.

**Comment by MrBrax** [comment]
Xbox One S Wireless Controller

<img width="632" alt="1712238140095" src="https://github.com/Facepunch/sbox-issues/assets/1517911/bcd9a6dd-b64e-48be-89d7-e05f6ad26325">

Viewport is focused, keyboard+mouse works fine.

Regular game non-editor works fine.

**Comment by DevulTj** [comment]
Weird. It shouldn't be enabled for your controller type. We updated this over on steamworks but it hasn't cascaded to cached controllers for some reason. You may have to disable it locally.

**Comment by MrBrax** [comment]
What does that mean? That Xbox controllers don't work right now?

I've tried disabling steaminput and it doesn't do anything.

**Comment by DevulTj** [comment]
Worth noting that changing the settings require a restart of the game, so make sure you're doing that. It works for me on both my PlayStation and Xbox controller currently.

**Comment by MrBrax** [comment]
Restarting the editor did not help.

Changing profiles did not help.

Enabling the desktop controller layout starts sending button inputs to the editor, but only for those keys and not gamepad buttons

<img width="960" alt="1712320878197" src="https://github.com/Facepunch/sbox-issues/assets/1517911/d296801c-bf9a-4871-b476-d288425c6251">

**Comment by DevulTj** [comment]
Dunno what you're doing with SteamInput there... of course it'll act like a keyboard if you're making it press keyboard keys. 

Make sure you disable SteamInput, then restart steam and the game, boot it up again, and see what happens there.

If it still doesn't work for you, I can dig even deeper.

**Comment by MrBrax** [comment]
That's the default mode when having a controller connected and no game running, it will control the desktop from your couch so you can start games etc.

I'll try disabling steaminput again, but it didn't work the last time i tried.

**Comment by MrBrax** [comment]
Nope, I'm just controlling my desktop. Some desktop controls overlap with the game but I can't rely on them since in-game in the main game client it's different.


https://github.com/Facepunch/sbox-issues/assets/1517911/66c2bf38-f828-4e46-ac68-a52d00141841

**Comment by MrBrax** [comment]
The mouse movement thing is part of steam, not an external program. When you don't have a game running, your controller will control your mouse and some keyboard inputs. I'll try to see what I have installed, but from what I know it's pretty clean.

![1713948405508](https://github.com/Facepunch/sbox-issues/assets/1517911/43173795-7dc2-4993-9070-5e92b0e29765)

(screenshot not from my main pc)

**Comment by MrBrax** [comment]
Is steaminput for s&box supposed to be disabled by the user for the editor to receive inputs? Because it works in the regular game just fine with steaminput enabled. Disabling it makes the controller stop working in the regular game too.
I don't have any other input software installed/running as far as i know.

Then there's this:

<img width="293" alt="1713973159310" src="https://github.com/Facepunch/sbox-issues/assets/1517911/1e69874c-28fa-4034-96de-d222bc857b8a">

**Comment by MrBrax** [comment]
<img width="631" alt="1713989489033" src="https://github.com/Facepunch/sbox-issues/assets/1517911/2f2804c2-d5cb-4fbc-b4b9-a266bdc8c956">

I dug up an old PS2 controller adapter and connected two controllers, those show up. Inputs get detected in scopes but won't control my car which uses just regular old input code, only keyboard will. Xbox controller still doesn't get detected by the game whatsoever.

**Comment by MrBrax** [comment]
Suddenly, it works out of nowhere when i disabled steaminput for s&box specifically. I don't know what happened but it seems to work now. I hope my computer doesn't restart or something happens now :(

<img width="632" alt="1714160430687" src="https://github.com/Facepunch/sbox-issues/assets/1517911/1ce5391d-576c-4fc8-acd6-564b68aaea36">

Weird how steaminput has to be disabled for controllers to work though.

**Comment by DevulTj** [comment]
Button inputs should be working now. Can you please verify?

**Comment by MrBrax** [comment]
works now, nice
