### ISSUE TITLE
Add isFocused to Sandbox.Application

### ISSUE THREAD

**Issue by Louis-Ladd** [Facepunch/sbox-issues#5330]
### For?

S&Box

### What can't you do?

Unable to check if the game window (in editor or not) is focused by the user.

### How would you like it to work?

If the game window is in focus, this member should be true.
Elsewise, it should be false.

### What have you tried?

Looked around definitions for a isFocused method or member.
Couldn't find anything.
Can't use user32.dll to get the window and check focus due to DLLImport being blacklisted.

**Comment by CarsonKompon** [comment]
I meant to make an issue for this a week or so ago. Would love this 👍

**Comment by garrynewman** [comment]
Makes sense, don't see any harm

**Comment by DevulTj** [comment]
Added `Application.IsFocused`
