### ISSUE TITLE
The networked Snapshot uses the wrong namespace

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5331]
### Describe the bug

Hi,

I have discovered that a player who joins a current lobby will load the wrong `Component` if the Class name attached to this component is existing twice. Ignoring the namespace context.

In fact, S&box seems to choose the first Class name found for the Snapshot, ignoring the real context (like the namespace of the class).

I have been able to bring you a project to reproduce the issue

### To Reproduce

1) Download my updated https://github.com/PolSpock/sbox-timeuntilbug
2) Look at my code :

`NetworkLogic.cs` is the Core of the project, creating the Lobby and a Networked GameObject with a `TimerLogic` Component.
This `TimerLogic.cs` will create a **`TimeUntilBug.Two.ChildComponent.DynamicChildComponent`**

`DynamicChildComponent.cs` class exists twice:
One in a `One/DynamicChildComponent.cs` and another in `Two/DynamicChildComponent.cs`
This `DynamicChildComponent.cs` is a child of `DynamicBaseComponent.cs`

These 2 files are compiling cause they are not in the same location and namespace.

3) Now start a game and join it with a secondary account.
4) Take attention to logs on the secondary account :
```
// From `One/DynamicChildComponent.cs`
protected override void OnStart()
{
	base.OnStart();
	Log.Info( "One.DynamicChildComponent OnStart IsHost " + Networking.IsHost );
}
```

On the secondary account, you will get a strong chance to fire the `OnStart` log : `One.DynamicChildComponent OnStart`.
And this an issue: my `TimerLogic.cs` is creating a `Two.DynamicChildComponent`, never a `One.DynamicChildComponent`. So why the secondary account is creating it?

### Expected behavior

Snapshot must load the correct component (in this example `Two.DynamicChildComponent`)

**Comment by kurozael** [comment]
Thanks for the repro case, I'll look into this 😊
