### ISSUE TITLE
Certain assets don't recompile with Version Control

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5335]
### Describe the bug

If you swap to another branch while the game is closed, and then open the game, s&box doesn't detect any changes, however, if you open a scene that your branch updated, it'll still be the last compiled version. 
This applies to pretty much everything, but it's specifically awful with Prefabs and Scenes.

### To Reproduce

1. Have Prefab1 on branch 1
2. Have Prefab1 on branch 2
3. Edit Prefab1 while s&box is open
4. Close s&box
5. Swap branches
6. Prefab1 remains on its branch 1 state, rather than what it is in branch 2

### Expected behavior

Frankly, this sucks, because surely you wouldn't want the solution to be recompiling every single prefab and scene everytime you open the game, so I'm frankly not sure what the solution should be

**Comment by MrBrax** [comment]
this has started happening again, happens both to me and another person on my team

**Comment by handsomematt** [comment]
Everything compiles when you open your project. If it's not please make an issue including the offending files, logs, etc
