### ISSUE TITLE
Making a component abstract breaks prefab it's attached to

### ISSUE THREAD

**Issue by verdie-g** [Facepunch/sbox-issues#5339]
### Describe the bug

I wanted to refactor a component to make it abstract and replace the component by a child class on the prefabs but it turns out that after making the component abstract, the prefab can't be opened anymore.

### To Reproduce

1. Create an empty object
![image](https://github.com/Facepunch/sbox-issues/assets/9092290/ad434691-499e-4a26-8e53-04cabe6b1867)
2. Add a new component
![image](https://github.com/Facepunch/sbox-issues/assets/9092290/a67ebdd9-dc42-4734-834e-26b6834c5106)
3. Convert the object to a prefab
![image](https://github.com/Facepunch/sbox-issues/assets/9092290/c8fa38ac-0487-4966-8dcc-e44bc498f035)
4. Make the component abstract
5. Try to open the prefab in the editor
![image](https://github.com/Facepunch/sbox-issues/assets/9092290/3c5bc377-cfdc-49eb-bfc7-541fbf1c444b)
![image](https://github.com/Facepunch/sbox-issues/assets/9092290/f1c388f3-e062-4296-9816-f168e6d27803)

### Expected behavior

I'm not exactly sure what would be the best behavior but I think it should at least let me open the prefab so I can replace the component.

**Comment by DevulTj** [comment]
This should be fine now.
