### ISSUE TITLE
Cloth Tarp Model

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#534]
HLA has a very useful tarp model. S&box should have something like it by default.
A way to create a tarp from a quad (or other shapes?) in hammer would be even better.

For reference, the model in HLA is models/personal/sergiy/cloth_tarp3_mesh.vmdl
https://user-images.githubusercontent.com/39461072/127713874-a7d9b001-2941-4f93-a2a5-7e72a527bc96.mp4

**Comment by bakscratch** [comment]
https://files.facepunch.com/louie/1b3111b1/Hammer%20-%20%5Bcloth_demo.vmap%20_%5D%202021-07-31%2015-30-23.mp4

I have created a similar version to this, It has more lods too. Should work basically the same way.
Let me know if there are any changes or improvments you want.

**Comment by gvarados1** [comment]
This works. Thank you <3
