### ISSUE TITLE
Viewers don't have download permissions for presskit

### ISSUE THREAD

**Issue by Louis-Ladd** [Facepunch/sbox-issues#5342]
# Viewers don't have download permissions for presskit

## Description
When attempting to download assets from the Sandbox google drive, There is no way to download due to viewers not having permission to.

## Screenshots (if applicable)
![image](https://github.com/Facepunch/sbox-issues/assets/16233776/ba2390d3-5bf0-4999-977d-40a0d2e52cb2)
(You can see in the bottom right that viewers do not have download permissions)

**Comment by Louis-Ladd** [comment]
I am unable to access it in incognito mode either
![image](https://github.com/Facepunch/sbox-issues/assets/16233776/7e2d0ef8-9dca-4cc9-95eb-3fe52ad6b579)

**Comment by DevulTj** [comment]
@lewisainslie made a change to our shared drive policy that has fixed this issue now
