### ISSUE TITLE
Compilation error dialog ignores favorite editor

### ISSUE THREAD

**Issue by verdie-g** [Facepunch/sbox-issues#5344]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/9092290/1d3263bf-59c9-47fa-9fe3-71000dd21050)
When opening a project with compilation errors, one of the option is "Open in VS" even though my favorite editor is Rider.

Could be related to https://github.com/Facepunch/sbox-issues/issues/5205.

### To Reproduce

1. Make Rider the favorite editor
2. Open a project that doesn't compile

### Expected behavior

A button with "Open in Rider"

**Comment by handsomematt** [comment]
this would be #5205
