### ISSUE TITLE
Inconsistent collisions with BoxCollider

### ISSUE THREAD

**Issue by verdie-g** [Facepunch/sbox-issues#5345]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/9092290/135d2437-27e2-4682-974a-2919f9669673)

In this screenshot:
- the small cubes have a scale of (0.1, 0.1, 0.1)
- the big cubes have a scale of (1, 1, 1)
- all cubes have a BoxCollider of (50, 50, 50), which according to the BoxCollider's gizmo, should be the size of the cube
- the red cubes are moving towards the blue cubes using Sanbox.CharacterController

At the end of the simulation, the big cubes overlap with each others when the small cubes don't touch.

The issue title mentions BoxCollider but maybe it's a misunderstanding of CharacterController.

### To Reproduce

1. Open [sbox-issue-5345.zip](https://github.com/Facepunch/sbox-issues/files/14898000/sbox-issue-5345.zip)
2. Run the simulation

### Expected behavior

I would expect the cubes to touch but not to overlap.

**Comment by aylaylay** [comment]
CharacterController doesn't use colliders for movement, colliders are for physics
