### ISSUE TITLE
Undoing a change of a property value takes 4 CTRL+Z

### ISSUE THREAD

**Issue by verdie-g** [Facepunch/sbox-issues#5348]
### Describe the bug

In the editor, after modifying the property value of a component, you need to smash CTRL+Z 4 times to undo it.

### To Reproduce

![image](https://github.com/Facepunch/sbox-issues/assets/9092290/45fd830e-c846-460b-b9a5-f337d3fd669a)
Consider this BoxCollider. I want to change X from 32 to 10.

1. Double click on 32 to select it
2. Type 10
3. Click anywhere else to remove the cursor from the X input
4. Press CTRL+Z. The X value doesn't change
5. Press CTRL+Z. The X value is now 1
6. Press CTRL+Z. The X value doesn't change
7. The X value is finally back to 32

### Expected behavior

I would expect a single CTRL+Z to undo the change.

**Comment by garrynewman** [comment]
This should be a shit load better now, let me know pelase

**Comment by verdie-g** [comment]
Not working on s&box these days, I won't be able to confirm.

**Comment by MrBrax** [comment]
https://github.com/user-attachments/assets/df346c02-18b4-482a-a756-4f4778a71a75

nope
