### ISSUE TITLE
`ComputedStyle.Width` is not set/updated if `min-width` or `max-width` is used

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#535]
**Describe the bug**
If you are trying to access `ComputedStyle.Width`, it will be `null` if you didn't set the width via CSS (`Panel { width: ...; }`) or `Style.Width = ...` before.

**To Reproduce**

1. Do not set `width` of a panel, but `min-width` or `max-width`
2. Output the `Panel.ComputedStyle.Width`

**Expected behavior**
`ComputedStyle.Width` should always display the current width like in every browser

**Why is it needed**
I need it to calculate whether my panel is still in the screen (Drag&Drop calculations).

**Template to test in browser**
```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Test</title>
	
	<style>
	div {
		display: flex;
		
		position: absolute;
		min-width: 600px;
		max-width: 800px;
		height: 400px;
		left: 50%;
		top: 50%;
		transform: translateX(-50%) translateY(-50%);
		
		color: white;
		background-color: black;
	}
	</style>
</head>
<body>
	<div />
</body>
</html>
```

**Comment by Rohansi** [comment]
Like https://github.com/Facepunch/sbox-issues/issues/536, this is not how `ComputedStyle` should work. Even in browsers. You want `Panel.Box` instead.

**Comment by Alf21** [comment]
Thanks for the hint with `Box`, gonna make my life such a way easier :D

Anyways: In my browser (chrome-based), `ComputedStyle.Width/Left/Top` is updated regarding the given style (transforms, min- or max-width/height). Imo this is the correct behavior as `ComputedStyle` != `Style`. If you wanna get the current e.g. `width`, you have to use `Style.Width`. I know that - if it would work like in browsers - we would run into the problem on "How to access the via CSS set pure `width`?"

Anyways, if `Box` solves this as well, I gonna close both issues. Thanks!

**Comment by Alf21** [comment]
https://user-images.githubusercontent.com/11843790/127726830-ec19bbc7-a737-41a4-9969-92b86ca3a169.mp4

Solved, thanks @Rohansi !
