### ISSUE TITLE
[Scene Mesh] - Ability to delete drawn meshes before placing them

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5352]
### For?

Other

### What can't you do?

Sometimes you fuck up with a box or something, but you can't delete it instantly, you have to click out of the mesh editor (into the hierarchy or something), wait for it to exist in the hierarchy, and then delete it.
This is an issue in Hammer aswell, but its a bit more annoying because there's no way to swap to the transform/rotate/scale tool (another feature requests soon:tm:)

### How would you like it to work?

Mesh in the state of being placed should be able to get deleted.

### What have you tried?

Clicking off and deleting it through the hierarchy

**Comment by Retroeer** [comment]
could delete just do what esc does then? in my mind it's much more obvious to use the delete key to delete a drawn mesh just like you'd delete a placed mesh

**Comment by aylaylay** [comment]
Delete now also cancels the placement

**Comment by Retroeer** [comment]
works great, thanks for listening to my silly preference 😅

**Comment by Retroeer** [comment]
Would it be silly to ask for Undo to do the same thing?
