### ISSUE TITLE
[Scene Mesh] - Saving changes made in Play Mode

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5354]
### For?

Other

### What can't you do?

Unlike Hammer, Scene Mesh has the potential to allow map creators to play their map in their own game *while* they work on it. This would just be awesome to have and make the days of placing 5 million scale player_info's a thing of the past. 

### How would you like it to work?

Frankly, I like what Garry proposed in #4515 
> "I could imagine, for example, right clicking and going to "apply to scene", on GameObjects or on Components."

### What have you tried?

I mean, you can copy the mesh in play mode, quit, and paste the mesh, but this just blows dude. 

### Additional context

This is technically the same thing as #4515, but hopefully Scene Mesh can get this in a quicker time frame, it'd just be awesome.

**Comment by aylaylay** [comment]
This is a feature we should add for everything, not specific to mesh editor
