### ISSUE TITLE
[Scene Mesh] - NRE if you go into Play Mode while in Block Tool mode.

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5355]
### Describe the bug

If you go into Play Mode while in Block Tool mode you get this error:

`ToolsDll Error calling event 'tool.frame' on '[Editor.SceneTreeWidget](arg:0)' (Object reference not set to an instance of an object.)`

### To Reproduce

1. Go into Block Tool mode
2. Go into Play Mode
3. Observe

### Expected behavior

No NRE

**Comment by aylaylay** [comment]
Should be fixed now
