### ISSUE TITLE
Change the active scene in a lobby

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#5356]
### For?

S&Box

### What can't you do?

Currently in a networked lobby we are unable to change the active scene without transferring all players.

### How would you like it to work?

Whenever someone with permission to do so (e.g. the host) changes the active scene, the scene should change for each player as they connect to the new scene.  Ideally the ability to change the scene would either be locked to the host or able to be set via the connection permissions system.  
Ideally this would also still call OnActive on any Network Listeners.

### What have you tried?

You're able to get around this currently by spawning in a prefab of the scene, yet this feels messy to work with.

**Comment by MrBrax** [comment]
#4949

**Comment by handsomematt** [comment]
Yeah #4949 - @kurozael talk to garry to see where he got to or if there's a specific approach for it
