### ISSUE TITLE
SoundEvent `Decibels` doesn't work

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5358]
### Describe the bug

Hi,

I would like to create a sound that doesn't be heard throughout the entire scene. But currently, the SoundEvent `Decibels` property seems to be broken.
If i change any of his values, i still be able to hear the sound independently of my camera distance.

I think i'm using the right property cause `Sandbox.SoundEvent` says:
```
[DefaultValue(70)]
[Display(Name = "Decibels", Description = "How loud is this sound, affects how far away it can be heard")]
[Editor("decibels")]
public int Decibels { get; set; } = 70;
```

### To Reproduce

Reproduce steps:

1) Create a `New Sound Event` Game Resource
2) Change the `Decibels` property to 1
3) Add custom Sound (better if it's a Looping sound)
4) Play sound in a specific Position
5) You will still hear the sound even if you are far away

### Expected behavior

A correct distance attenuation from decibels

**Comment by matekdev** [comment]
@garrynewman What is the replacement for decibels now that it is obsolete? Does it just use `Volume`? Not related... but I liked the iteration of the decibel slider where it listed sounds that you'd expect to be similarly loud (i.e revolver -> helicopter -> explosion, etc.).

**Comment by garrynewman** [comment]
Volume and distance really. I agree that it was nice to just choose a comparable sound, a lot more fool proof.

**Comment by matekdev** [comment]
I'll go ahead and make an issue for this since it would be nice to have it back again.
