### ISSUE TITLE
`ComputedStyle.Left/Top` is not updated correctly if using css `translate` transforms

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#536]
**Describe the bug**
If you are trying to get the current `ComputedStyle.Left/Top`, it won't return the correct position (left / top pixel) if the Panel has a css `translate` transform like `Panel { transform: translateX(-50%) translateY(-50%); }`

**To Reproduce**

1. Add `transform: translateX(-50%) translateY(-50%);` to your panel
2. Output the `Panel.ComputedStyle.Left` or `Panel.ComputedStyle.Top`

**Expected behavior**
`ComputedStyle.Left/Top` should always display the current left/top pixel like in every browser

**Why is it needed**
I need it to calculate whether my panel is still in the screen (Drag&Drop calculations). As an alternative, access to the transform function and a check what transform flag is set would work as well.

**Template to test in browser**
```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Test</title>
	
	<style>
	div {
		display: flex;
		
		position: absolute;
		min-width: 600px;
		max-width: 800px;
		height: 400px;
		left: 50%;
		top: 50%;
		transform: translateX(-50%) translateY(-50%);
		
		color: white;
		background-color: black;
	}
	</style>
</head>
<body>
	<div />
</body>
</html>
```

**Comment by Rohansi** [comment]
This shouldn't be the case for `ComputedStyle.Left` or `Top`. Those will be reported as `50%` in browsers and not the top left corner.

Try taking a look at `Panel.Box`. It might work for this already but I've not tried it yet. It tells you the bounding box for the panel.

**Comment by Alf21** [comment]
I can get the Box and do calculations with it, but sadly, I can't set it without having access to the transform nor a way to set the width of the box / the left position of the box (without transform calculations).

Example without transforms:
https://user-images.githubusercontent.com/11843790/127726975-3b7cc8bc-9e8f-424e-a9ff-b5c14e23b723.mp4

Example with transforms (`transform: translateX(-50%) translateY(-50%);`; same calculations):
https://user-images.githubusercontent.com/11843790/127727068-64c8d4f2-d473-46a0-8dc2-16915fd8393d.mp4

Setting the vars of the `Box.Rect` directly does do the trick, BUT these vars are getting reset immediatly.

**Comment by Rohansi** [comment]
So, do you even need the transform then? I don't see a reason why it's required here.

`ComputedStyle` is only telling you how the styles cascade. In browsers you can see that in the developer tools:

![image](https://user-images.githubusercontent.com/1319884/127741223-f838c046-7fa5-454e-9594-5e8bd3d4c22f.png)

Even with your test, Chrome shows `left` and `top` set to half of the viewport size. That's the center of the screen - not the top left corner.

**Comment by Alf21** [comment]
Yea, for my resizing calculations, I need to know the position of the anchor (mid screen e.g., not top left corner). That's why you can see in the second video that the repositioning and resizing is bugged.

I could add a workaroung with an own positioning function to center the panel on opening on the screen (no transform support)... That would be my next step.

With my test, `left` is on my device `480px` and without transform `491px` (like in your screenshot). That's why calculation issue appear: `Parent.Box.Rect.left` returns the mid now instead of the top left corner (in repositioning) and the width is now set based on the anchor (resizes in both directions instead to the right side). This won't work with Styles without knowing the exact transform.

**Comment by garrynewman** [comment]
This works exactly how it should. ComputedStyle is the style that is calculated as a result of cascading the applicable styles together. It's not meant to property report the actual screen coordinates.

**Comment by Alf21** [comment]
Hmm okay, but isn't it intended that `Box.Rect.left` should return the correct value then? This isn't the case:

![image](https://user-images.githubusercontent.com/11843790/127743061-6cf6e8c3-fcba-4fa2-aeb3-85902ded55e7.png)

Code i used:
```cs
public class TestPanel : Panel
{
    public TestPanel(Panel lockedPanel) // the provided panel should have css `transform: translateX(-50%) translateY(-50%);` enabled, the `TestPanel` should not have a transform enabled to test properly
    {
        Parent = lockedPanel;
    }

    public override void Tick()
    {
        Style.Left = Parent.Box.Rect.left;
        Style.Top = Parent.Box.Rect.top;
        Style.Dirty();
    }
}
```

**Comment by garrynewman** [comment]
Yeah, it returns the right value with no translations applied
