### ISSUE TITLE
[Scene Mesh] Pivot Point Tool

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5360]
### For?

Other

### What can't you do?

In Scene mesh you can't control the pivot point of your mesh

### How would you like it to work?

Pretty much the same as Hammer

### What have you tried?

Don't think there is anything you can do to work around this

**Comment by aylaylay** [comment]
Done


https://github.com/Facepunch/sbox-issues/assets/1667289/32df7ab5-02a9-47c2-97b8-814310c4e5c6
