### ISSUE TITLE
[Scene Mesh] Holding left click to select multiple things

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5362]
### For?

Other

### What can't you do?

In Hammer, if you hold left click you can continuously select multiple things while in either vertex, edge or face mode 

### How would you like it to work?

Pretty much the same as Hammer

### What have you tried?

developing carpal tunnel from spamming left click on everything i want to select

**Comment by aylaylay** [comment]
Done

**Comment by Retroeer** [comment]
holy shit that was quick

**Comment by Retroeer** [comment]
literally fucking perfect
