### ISSUE TITLE
Surface properties are not applied to physics sim in scene editor

### ISSUE THREAD

**Issue by johncosfm** [Facepunch/sbox-issues#5364]
### Describe the bug

The `Friction` property in a .surface file applies correctly in valve tools (modeldoc and hammer) but seems to make no difference to the physics sim whilst running the game in the scene editor.

Edit: further testing reveals that interactions between 2 rigid bodies work as intended (even when one rigid body has motion disabled), friction settings are only not taken into account when interacting with static stuff

### To Reproduce

1. Create a surface property with `Friction` set to 0
2. Apply it to a model in modeldoc
3. Observe that the physics sim behaves as expected in the modeldoc physics preview. It also behaves as expected in the hammer physics tool thing
4. Spawn the model as either a prop or a ModelRenderer+ModelCollider+Rigidbody combo in a scene and run the scene
6. Model incorrectly displays the effects of friction
7. Override the surface in the ModelCollider component
8. Model still incorrectly displays the effects of friction

### Expected behavior

The physics sim in the scene editor should react to the values of the properties set in the .surface file.

### Media/Files

the .surface file I am using
```
{
  "BaseSurface": "surfaces/default.surface",
  "AudioSurface": "Leather",
  "Description": "",
  "Friction": 0.0,
  "Elasticity": 0.3,
  "Density": 900,
  "Thickness": 0.3,
  "Dampening": 0,
  "BounceThreshold": 40,
  "ImpactEffects": {},
  "ScrapeEffects": {},
  "Sounds": {},
  "Breakables": {},
  "Tags": null,
  "__references": []
}
```

https://github.com/Facepunch/sbox-issues/assets/69829964/545f7a84-8392-4551-a9c5-4afc56372292

https://github.com/Facepunch/sbox-issues/assets/69829964/817500fa-feca-4218-b904-dbc3a45320a8

2 identical slabs, one of which has a Rigidbody component with motion disabled. Bug only occurs on the slab with no Rigidbody

https://github.com/Facepunch/sbox-issues/assets/69829964/0f184272-0489-48db-b72e-86842a2f3c30

### Additional context

I haven't tested the other properties, they might also be broken, Friction is just particularly notable in that it is very easy to see.

**Comment by johncosfm** [comment]
Seems I was mistaken with the whole rigidbody component thing, the ground actually just needs the collision type to be hull instead of mesh

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by johncosfm** [comment]
looks good on my end, thanks
