### ISSUE TITLE
Putting "A" as a controller input key refuses to save

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5365]
### Describe the bug

Visually it stays as "A" until you restart, but it's actually never saved to the sbproj file. In fact, it completely removes the "GamepadCode" key.

### To Reproduce

1. Set input button of controller to "A" on an action
2. Save
3. Restart editor
4. Input button is now cleared

### Expected behavior

Saving inputs properly

### Media/Files

![1712912384723](https://github.com/Facepunch/sbox-issues/assets/1517911/577b63a8-5904-4be5-92bd-3abe142ffa56)

![1712912470344](https://github.com/Facepunch/sbox-issues/assets/1517911/85ec5512-5b87-48fb-882b-81b8e54425b6)

**Comment by DevulTj** [comment]
Noticed this yesterday - cheers, will look into it

**Comment by MrBrax** [comment]
Any enum value specified as 0 will not save into json, it's affecting this and custom assets too

<img width="453" alt="1714931812706" src="https://github.com/Facepunch/sbox-issues/assets/1517911/57b08a97-d19d-43be-8580-57e99c8b0c45">

**Comment by DevulTj** [comment]
This should be sorted now.
