### ISSUE TITLE
Support justify-self css style

### ISSUE THREAD

**Issue by the-remeko** [Facepunch/sbox-issues#5366]
### For?

S&Box

### What can't you do?

I can't use something like `justify-self: flex-end;` to position an element. S&box already has align-self, which works the same, just on the opposite axis.

### How would you like it to work?

`justify-self: flex-end;` should align the element with the end of the parent's flex axis.

### What have you tried?

Currently I put the element inside another and put `justify-content: flex-end;` on the parent. Having justify-self will simplify things greatly when I'm already using align-self for one axis and there are multiple elements involved that need to be aligned differently.

**Comment by xezno** [comment]
We can't add this because it only applies to layouts we don't support (grid, block):

> In flexbox layouts, this property is ignored.

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
