### ISSUE TITLE
Viseme not working locally with loopback disabled on Voice Component

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5367]
### Describe the bug

Lipsync on the citizen model is only visible when you can actually hear the audio. So it's only working when loopback is enabled like so:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/d1f06d64-d4c7-46a9-99c5-e8b48240b36f)

### To Reproduce

1. Voice Transmitter Component with a Citizen SkinnedModelRenderer as the Viseme Renderer
2. Enter play mode and start talking. The citizen's mouth will not move.
3. Exit play mode and set Loopback to true on the Voice Transmitter Component
4. Enter play mode and start talking. The citizen's mouth will move, but you'll also hear your own voice (which may not be desired)

### Expected behavior

It should do the lipsync regardless of whether or not you can hear your own voice.

**Comment by aylaylay** [comment]
Should be fixed now
