### ISSUE TITLE
[ShaderGraph] Render Options popup isn't constrained to the window 

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5369]
### Describe the bug

When the preview dock is setup as shown to the right of the shadergraph window , clicking on the cog to open render options   will result in the  popup getting cut off when the shadergraph window is maximized.

### To Reproduce

1. Open ShaderGraph and maximize it.
2. Setup Preview Dock on the right of the window.
3. Open render options
4. Observe that render options is cut off.

### Expected behavior

Render options popup should open to the left . Pretty much constrain it  to the bounds of the window.

### Media/Files

![Screenshot 2024-04-15 001506](https://github.com/Facepunch/sbox-issues/assets/23345567/b109451a-41e4-4a95-baeb-36df3add6c7a)

**Comment by aylaylay** [comment]
Fixed
