### ISSUE TITLE
Collision matrix ignore has no effect

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5375]
### Describe the bug

Even if two tags are set to ignore each other in the collision matrix, colliders with the corresponding tags will collide with each other in-game.

### To Reproduce

1. Open the attached example project
2. Open minimal.scene
3. See that the red cube on top has `thing` tag, and blue cube on bottom has `thing_allow` tag.
4. Open the project settings and see that `thing_allow` and `thing` are supposed to ignore each other.
5. Play minimal.scene
6. See that the cubes collide despite the collision matrix rules

### Expected behavior

In the set of all tags that are found in either collider of a possible collision, if any of those tags are set to ignore any of the other tags, then the collision is ignored.

### Media/Files

[collision_ignore_issue.zip](https://github.com/Facepunch/sbox-issues/files/15015600/collision_ignore_issue.zip)

### Additional context

This was working as expected a little over a week ago, but I haven't checked again until just now.

**Comment by aylaylay** [comment]
Looks like the ProjectSettings is failing to mount after recent changes @garrynewman

**Comment by garrynewman** [comment]
Looking into this

**Comment by aylaylay** [comment]
Confirmed fixed
