### ISSUE TITLE
[Asset Browser] Enter Code, Editor, and UnitTest folders within Asset Browser

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5378]
### For?

S&Box

### What can't you do?

With the recent changes to how project structure is, the ability to enter the above folders has been removed. 
I'm hopeful this isn't deliberate and this isn't de-confirmation of ever getting the ability to open CS files within Asset Browser

### How would you like it to work?

Show the entire directory within Asset Browser

### What have you tried?

Nothing, for there is nothing to do.

**Comment by handsomematt** [comment]
Nah, code isn't an asset
