### ISSUE TITLE
[Scene Inspector] Lack of "Open in Editor" for referenced Prefabs 

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5379]
### For?

S&Box

### What can't you do?

If you make a GameObject property and drag in a Prefab, there's no "Open in Editor" for it in the context menu

### How would you like it to work?

The same way other referenced files like .vmdls work, right click gives you the option to Open in Editor, copy or paste

### What have you tried?

Nothing

### Additional context

![sbox-dev_6FDJ4Z6qQB](https://github.com/Facepunch/sbox-issues/assets/44037603/3cd090f8-e421-4ea3-9bfe-91f7fe0e7327)

Ideally it should be like this:
![sbox-dev_QrPETyJz90](https://github.com/Facepunch/sbox-issues/assets/44037603/3ccc8b05-58fb-4c66-9cba-526b2cdb0e2f)

**Comment by Retroeer** [comment]
Kind of wish Copy and Paste was there, but this is fine for now

**Comment by DevulTj** [comment]
Added this last month
