### ISSUE TITLE
When editing component name in New Component menu, left arrow shouldn't return to previous screen

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#5381]
When you're creating a new component and the component name textbox has focus, left arrow should only move the text cursor and not go back to the previous menu level. Currently it does both.

https://github.com/Facepunch/sbox-issues/assets/1173137/9b9031a3-648f-4319-ac52-8a1c8a6bbe82

**Comment by DevulTj** [comment]
I'll sort this out for ya

**Comment by DevulTj** [comment]
Should be working now

**Comment by ryleigh** [comment]
yup works ❤️👍
