### ISSUE TITLE
[Editor] Shadow Culling view in editor

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5384]
### For?

S&Box

### What can't you do?

I want to view the new shadow culling in the editor. It would be a good quality of life feature. As seen in screenshots from Sam.

### How would you like it to work?

I would like it to work by adding a tab in this drop-down: 
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/bde28773-6acf-4303-b237-28fc24b23d75)

### What have you tried?

I don't believe that there is a way to view it currently.

**Comment by handsomematt** [comment]
lb_show_rejected_shadowlights 1

It's not useful to have in those menus, there's no meaningful information you're getting from it
