### ISSUE TITLE
GameObjects DontDestroyOnLoad

### ISSUE THREAD

**Issue by BlakeWinser** [Facepunch/sbox-issues#5388]
### For?

S&Box

### What can't you do?

There is currently no way to mark a game object to not be destroyed when loading into a different scene.

### How would you like it to work?

Basically how Unity handles it: Allow us to set an object to not destroy when loading a new Scene.

https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

### What have you tried?

Creating a simple save state system to track variables needed between scenes.

**Comment by CarsonKompon** [comment]
This is one of the biggest things holding me back from making anything real big in s&box. Needs to happen real soon imo

**Comment by MrBrax** [comment]
I'm using static classes to keep data between scene loads and it's messy for sure just hoping things stick around, and that data even persists when you stop the scene playback so i have to make workarounds when loading the menu etc. Starting to get really wavy updating every scene's ui/game/network manager objects too if i want to change something, so yes I agree it would be a big thing
