### ISSUE TITLE
Creating a camera in a blank scene throws errors and provides no properties in Inspector

### ISSUE THREAD

**Issue by R3DActual** [Facepunch/sbox-issues#5393]
### Describe the bug

Creating a camera in a blank scene throws errors and provides no properties for said camera in Inspector

![sbox-dev_dIKeXOYEkr](https://github.com/Facepunch/sbox-issues/assets/96969021/bfc76f8f-2873-423a-9b97-19d5d1ac86bf)

### To Reproduce

1. Create new project
2. Create blank scene
3. Create a camera
4. Reproduced errorrr

### Expected behavior

Should have properties in the inspector when the camera is created & selected.

**Comment by DevulTj** [comment]
Can you click the error and copy the stack trace here? or provide your latest log file?

**Comment by handsomematt** [comment]
https://docs.facepunch.com/doc/reporting-errors-2OTPIafqCJ
