### ISSUE TITLE
MusicPlayer Spectrum only populating first-half of array

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5394]
### Describe the bug

The `Spectrum` property from a MusicPlayer is only populating indexes 0-256 in the array, while indexes 257-511 all return 0.

Upon some investigation, I found demos such as [this one](https://academo.org/demos/spectrum-analyzer/) which seem to only cover frequencies ranging from 0KHz-23.6KHz. This leads me to believe that the 256 currently being outputted are averaged ranges of 100Hz, so the `Spectrum` property likely only needs an array size of 256 (instead of 512).

I was trying to create a spectrogram that displays the spectrum over time based on the demo seen above, and immediately noticed the 256 cutoff.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/b2cbb255-34d7-4919-a1fb-b7172eb44adc)

### To Reproduce

I've included a repro project which includes the spectrogram I made in a single component for ease-of-testing. May need to change some of the properties if you fiddle with array size.

### Expected behavior

If only 256 values are needed, it shouldn't return a 512 size array.

**However**, it'd also be nice to specify spectrum resolution so you *could* have it return a 512 or even 1024 size array with each value being a smaller sized average (allowing for more accuracy)

### Media/Files

[spectrum_repro.zip](https://github.com/Facepunch/sbox-issues/files/15052059/spectrum_repro.zip)

**Comment by aylaylay** [comment]
You're right, it looks like only 256 was being used so spectrum will now return 256 instead of 512
