### ISSUE TITLE
Convert Prop_Physics into Prop Component

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5395]
### For?

S&Box

### What can't you do?

Currently, hammer converts Prop_Physics into this GameObject: 
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/9fdf5d6e-5f2e-4e93-a1de-53c2de4b7372)
This is good and fine, but it has a disadvantage, you can't break it into gibs.

### How would you like it to work?

Instead of converting it to what it is doing right now, replace that with the Prop Component.

### What have you tried?

There is no way to tell hammer to convert this into a prop component.

**Comment by bakscratch** [comment]
Should be good now
