### ISSUE TITLE
[World Panel] Allow World Panels to render over world via a bool property

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5399]
### For?

S&Box

### What can't you do?

World Panels don't have the option to render over meshes without presumably doing some weird stuff I wouldn't know about? Or maybe it isn't supported at all

### How would you like it to work?

Some kind of "Render over World" bool property or something, this would simply just make the entire panel ignore everything, with no user defined exceptions, which is different from what i believe #5260 is talking about

### What have you tried?

Nothing, well, I could make it a screen panel, but that would just be overly complicated for what im doing

**Comment by handsomematt** [comment]
#5260 is this
