### ISSUE TITLE
Officially add Ctrl+Shift+Z as another universal Redo bind

### ISSUE THREAD

**Issue by shurahgolden** [Facepunch/sbox-issues#5407]
### For?

S&Box, Material Editor, Other

### What can't you do?

When I press Ctrl Shift Z in basically any other engine, it'll redo just like Ctrl Y, yet with S&box I have to go into the files and manually edit code to add in this functionality.

### How would you like it to work?

I press Ctrl+Shift+Z down and the engine Redos whatever, just as Ctrl+Y would.

### What have you tried?

Manually replacing nearly every instance of Ctrl+Y with Ctrl+Shift+Z. (juust pretend like nyanity is \steamapps\common\sbox)
![Code_B89vCxk3f8](https://github.com/Facepunch/sbox-issues/assets/87254883/0e6147a1-2e9f-4adc-a7b0-1ca115be1605)

### Additional context

Also, occasionally, nearly every S&box micro-update patches my keybind and I have to manually redo it over and over again via visual studio code. Facepunch, please fix 😭

**Comment by handsomematt** [comment]
Nah, there's a proposal for configurable editor keybinds that would cover this
