### ISSUE TITLE
.flac file extensions spaz out when changing/enabling Bitrate, & will speed up/down when initially changing Sample Rate

### ISSUE THREAD

**Issue by shurahgolden** [Facepunch/sbox-issues#5408]
### Describe the bug

When I initially change Sample Rate, .flac files will be temporarily pitched and slowed, till you re-click the asset.
When I initially change the Bitrate (usually happens only after changing the Sample Rate for some reason), ear-piercing (depending on how high the set Bitrate is..) static overpowers the original audio. You must re-click the asset icon to fix it, but then the icon will usually change to look almost as if the audio file was shortened. 
Before enabling 256 Bitrate:
![sbox-dev_Fa2eaHgXak](https://github.com/Facepunch/sbox-issues/assets/87254883/a6a7b07b-9cbf-4214-8bcf-18f415818188)
After enabling 256 Bitrate:
![sbox-dev_d20lgT4Bem](https://github.com/Facepunch/sbox-issues/assets/87254883/53459871-e6e5-4726-a3ad-3bbec18b5342)

### To Reproduce

https://github.com/Facepunch/sbox-issues/assets/87254883/587402da-801b-4842-a68d-53dc9602363b

### Expected behavior

when initially changing values before re-clicking on the .flac asset, i expect the audio to not be slowed or sped up when changing the **Sample Rate**, and i expect the **Bitrate/compression** to not rape my ears.

### Media/Files

ear warning 😭

https://github.com/Facepunch/sbox-issues/assets/87254883/587402da-801b-4842-a68d-53dc9602363b

it sounds to me though, that when you change the compression it's audibly running through all the audio signals till it finishes compression, then it finalizes and replays the now-compressed audio.

### Additional context

windows 10, here's my audio output settings for my Reltek driver.
![rundll32_o3up9juvXA](https://github.com/Facepunch/sbox-issues/assets/87254883/07c5bd49-d5fd-43e5-ac4e-4112773539b9)
(same settings on mic if that matters).

**Comment by shurahgolden** [comment]
from my testing, no, but the other formats don't even seem to be effected by Bitrate & Sample Rate to begin with.

**Comment by aylaylay** [comment]
This happened with all sounds if the sound was currently playing on sound recompile, I've made it stop sounds on reload.
