### ISSUE TITLE
Allow decal dragging from the asset browser

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5409]
### For?

S&Box

### What can't you do?

You cannot drag decals from the asset browser into the game, like other asset types.

### How would you like it to work?

I would like it to work like placing a model. It creates the game object, with the proper size for the decal.

### What have you tried?

You have to create the game object and then use the vmat, but I also noticed that many decals are broken.

**Comment by badandbest** [comment]
> I also noticed that many decals are broken.

Most asset.party decals use the `static_overlay` shader, which isn't supported. https://github.com/Facepunch/sbox-issues/issues/4945

**Comment by MrBrax** [comment]
> > I also noticed that many decals are broken.
> 
> Most asset.party decals use the `static_overlay` shader, which isn't supported. #4945

Which shader is recommended anyway? static overlay is what i use for maps since it's the easiest to adjust

**Comment by badandbest** [comment]
> Which shader is recommended anyway? static overlay is what i use for maps since it's the easiest to adjust

The only shaders that work right now are the decal and projected_decal shaders. I don't know why there are two of them.

![image](https://github.com/Facepunch/sbox-issues/assets/91832803/0235709c-a4e8-4bfb-9afe-116770d334b4)
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/29a7bc7c-7670-4fa5-892d-c0159aaa27ab)

**Comment by Nolankicks** [comment]
> > Which shader is recommended anyway? static overlay is what i use for maps since it's the easiest to adjust
> 
> The only shaders that work right now are the decal and projected_decal shaders. I don't know why there are two of them.
> 
> ![image](https://private-user-images.githubusercontent.com/91832803/307325855-0235709c-a4e8-4bfb-9afe-116770d334b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAyNDUsIm5iZiI6MTcxNDA1OTk0NSwicGF0aCI6Ii85MTgzMjgwMy8zMDczMjU4NTUtMDIzNTcwOWMtYTRlOC00YmZiLTlhZmUtMTE2NzcwZDMzNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1NDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTEyNjY0NTFjNzc5ZTFiOGY0Mzk2YTA5MDQ2YWFhN2YzNDJjNWE4NjkxNGQ5NWRjNmIzODc0N2YzOTVmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J2do8zHRtp5X2fndiWFkKv5OfdsuDrbXtwvzvPcTB5w) ![image](https://private-user-images.githubusercontent.com/91832803/307325787-29a7bc7c-7670-4fa5-892d-c0159aaa27ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAyNDUsIm5iZiI6MTcxNDA1OTk0NSwicGF0aCI6Ii85MTgzMjgwMy8zMDczMjU3ODctMjlhN2JjN2MtNzY3MC00ZmE1LTg5MmQtYzAxNTlhYWEyN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1NDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYjAwOTVkYzBmYjg1OTQwMGZlYTkyMTIzMmJmZTViMjE3NjQ1ZmFiNTZlM2RhNzQzMzY3ZjgzMWMzN2UyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ksoXsXAp6YQXGRVxZpoXp5H6-uUN9LdN8wnBpF8qnk)

I feel like Facepunch should maybe rework decals in general and merge all the diffrent materials into one.

**Comment by DevulTj** [comment]
Didn't realize @aylaylay had this claimed, sorry - but I've implemented a first version of this now.

This doesn't resolve the problem with us having multiple types of shaders for decals, that's outside of the scope of this issue. This just adds the ability to drag decals into the scene from the asset browser like so:

https://github.com/Facepunch/sbox-issues/assets/22372616/f23e0112-8da8-484e-83d2-c7f08dc6f45b
