### ISSUE TITLE
Whitelist `System.Timers` namespace

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/sbox-issues#541]
**What can't you do?**
Be able to use the `System.Timers` namespace.

**How would you like it to work?**
Like described in the Microsoft documentation: https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer?view=net-5.0

**What have you tried?**
A combination of `GameTask.Delay( <time> )` and `while ( true )`.

**Additional context**
This problem is easily solved (using other ways) but I highly doubt that this library has security problems or anything. Also, it seems to me easier to use especially for newbies.

**Comment by thegrb93** [comment]
Doesn't the game already have timer stuff?

**Comment by FlorianLeChat** [comment]
If I had found them, I wouldn't have asked that but I found no stuff.

**Comment by Alf21** [comment]
Please post the answer so others don't have to search on their own again and close the issue then :)

**Comment by Rohansi** [comment]
We wouldn't whitelist those timers because they're not the most friendly to use. The callbacks would run on the wrong thread etc so if anything we'd have our own timer class. Under the hood I imagine it would effectively be the async delay loop you already tried.

**Comment by FlorianLeChat** [comment]
Seen from that angle, you're absolutely right and if you make your own system, it's not really a priority because it's not really obstructive. Thank you anyway for this answer!
