### ISSUE TITLE
Add ability to create libraries within editor

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5412]
### For?

S&Box

### What can't you do?

You cannot create a lib similar to how you would create a game.

### How would you like it to work?

I would like it to be an option in the new project popup. It doesn't necessarily need to be in this popup, just anywhere in the editor where it makes sense.
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/4731fa90-a7c3-4a2a-a646-1f594a84d6fe)

### What have you tried?

You can create one by changing the package type in the .sbproj file.

**Comment by garrynewman** [comment]
Committed something for this this morning. It isn't the great template selector, but what do you think?
