### ISSUE TITLE
[VR] Input deltas return value instead of delta

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-issues#5414]
### Describe the bug

When getting the delta of an input's value, it returns the value instead of its change.

### To Reproduce

1. Get the analog input of a VR controller, like Grip or Trigger.
2. Log the value and it's delta.
3. The delta and value will be identical

```C#
//Delta and Value will be identical
Log.Info( Input.VR.RightHand.Trigger.Value );
Log.Info( Input.VR.RightHand.Trigger.Delta );
```

### Expected behavior

The delta should be the change in the value, not the same as the value.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/65134886/ba048017-296d-4bb2-be42-177d9436b8fd

### Additional context

This is an issue with SteamVR, not s&box's implementation

**Comment by xezno** [comment]
Should be fixed on next update
