### ISSUE TITLE
Previewing a procedural material can sometimes not work

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5416]
### Describe the bug

For some reason the material preview of a simple checkerboard pattern generated from a shadergraph shader in my case fails to preview correctly in the following areas:  * in the thumbnail preview in the assets browser 
* The preview in the inspector when the material is selected.
* in the material editor on the cube and plane primitives.

### To Reproduce

1. open attached test project .
2. goto and click once on checkerboard.vmat in the materials folder.
3. observe reported bug.

### Expected behavior

for the checkerboard pattern to be able to be previewed.

### Media/Files

example 1 :
![Screenshot 2024-04-26 183144](https://github.com/Facepunch/sbox-issues/assets/23345567/9a47d95d-d620-4c26-9a61-853c448af851)
example 2 :
![Screenshot 2024-04-26 183251](https://github.com/Facepunch/sbox-issues/assets/23345567/c3581a30-b77d-4480-88f7-4e1570be0a37)

example of preview working fine in shadergraph :

![Screenshot 2024-04-26 183432](https://github.com/Facepunch/sbox-issues/assets/23345567/dfde2b4d-5ec2-4694-b4f5-759cc5d443a9)

example of preview working fine in MET only on the sphere primitive :

![Screenshot 2024-04-26 184340](https://github.com/Facepunch/sbox-issues/assets/23345567/367d221c-3eca-4e20-8f35-481bd2c13246)

[testproject.zip](https://github.com/Facepunch/sbox-issues/files/15135699/testproject.zip)

**Comment by aylaylay** [comment]
Not a bug, your min max range for tiling is set to 0-1 so in material editor it clamps tiling to 1, which is just going to show a black square.

If you set the max range to 4 (or whatever) then material editor will show it fine.

![sbox-dev_nhSCuL8Sgs](https://github.com/Facepunch/sbox-issues/assets/1667289/8849cc49-7821-465d-bf47-5245a4dd994b)

![sbox-dev_S57ArlgmCx](https://github.com/Facepunch/sbox-issues/assets/1667289/488f2504-a04a-4d37-9c03-90342ef65ba3)
