### ISSUE TITLE
`Component.OnEnabled` is called before `Component.OnStart`

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5422]
### Describe the bug

Hi, since a [recent commit](https://discord.com/channels/833983068468936704/835035328779518023/1233375790331199529) from @handsomematt (yes i want to accuse him directly 👀),

`Component.OnEnabled` is now called before `Component.OnStart`, creating several issues for my project.

The [documentation specifies](https://docs.facepunch.com/s/sbox-dev/doc/component-methods-OCvoNh8ByW#h-onstart) `OnStart: Called when the component is enabled for the first time. Should always get called before OnEnabled.` which is not true anymore

### To Reproduce

Add log to a Component:
```
protected override void OnEnabled()
{
	base.OnEnabled();
	Log.Info( "OnEnabled" );
}

protected override void OnStart()
{
	base.OnStart();
	Log.Info( "OnStart" );
}
```

Start game:
OnEnabled is called before OnStart

### Expected behavior

OnEnabled must be called after OnStart

Regards

**Comment by handsomematt** [comment]
Sorry the order changed, it would've been going Awake() -> OnStart() -> OnFixedUpdate() -> OnEnabled() -> OnUpdate() which made no sense.

Here's the order now:

![image](https://github.com/Facepunch/sbox-issues/assets/1388267/78a42ce4-89f4-469c-97b1-37b0bec516a2)

I've updated the documentation, and I'll push a better lifecycle graph to docs too.
