### ISSUE TITLE
Asset Party website - Adding Collection to Organization doesnt work

### ISSUE THREAD

**Issue by tastez** [Facepunch/sbox-issues#5425]
### Describe the bug

To get assets into tool it seems you need to add them to a collection. To create a collection you need to create an organization.
creating organization works but making a collection through the Asset Party website errors out.

### To Reproduce

go to and login to asset party
create organization
create a collection
see error.

### Expected behavior

a collection is created that you can add assets to

### Additional context

might be related to account, since this is the first collection and organization ive made

**Comment by badandbest** [comment]
Since this is still a problem, are there any methods of creating collections other than from the website or are we completely screwed?

**Comment by garrynewman** [comment]
Let me look into this error

**Comment by badandbest** [comment]
The collection I tried to make a few days ago magically appeared now.
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/d6cdf774-5dc1-4088-b54b-1cb19b7948e2)


But it's not showing up in the collections list?
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/6a098729-62f2-48fe-ad2c-aea5978bb42f)
