### ISSUE TITLE
Error that doesn't let me play

### ISSUE THREAD

**Issue by JThompson000** [Facepunch/sbox-issues#5426]
### Describe the bug

An error that appears and blocks my character from moving[
![Screenshot 2024-04-28 145149](https://github.com/Facepunch/sbox-issues/assets/167894530/c9abb8b9-2955-4402-9885-a431224f4944)
](url)

### To Reproduce

1. Downloaded the game.
2. Game broke.

### Expected behavior

I should  be able to play.

### Media/Files

![Screenshot 2024-04-28 145149](https://github.com/Facepunch/sbox-issues/assets/167894530/a72a6754-42ab-4a3d-9953-e6c265302c8b)

### Additional context

Im running on an hp laptop.

**Comment by somethink000** [comment]
ma bad

**Comment by somethink000** [comment]
![Снимок экрана (48)](https://github.com/Facepunch/sbox-issues/assets/86604770/6e6fbb22-1352-4fff-975e-85d18b3362bd)
idk why

**Comment by badandbest** [comment]
Errors that are specific to gamemodes should generally be reported to the creator of that gamemode. 

There's not much Facepunch can do about it.
