### ISSUE TITLE
Getting a whitelist error and non of my scripts are compiling and becoming components

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5427]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/160753124/87b74065-3548-40fa-9265-1cf78ebaa8a3)

### To Reproduce

1. Open the project
2. Compile

### Expected behavior

Compiling scripts into components

### Media/Files

https://github.com/SwagAccount/the_second_coming_of_k

steamid64: 76561198193615491

### Additional context

Win 11

Ryzen 7 5700g

3080

**Comment by badandbest** [comment]
Whitelist error just means you're using banned code ( which is why it won't let you compile )

To fix it, you can:
1. Remove the banned code.
2. Make a feature request to whitelist specific code.

**Comment by SwagAccount** [comment]
I know and I have been looking apparently it has something to do with these two lines
`var set = Attributes.ConvertFromString(value, attribute.attributeType);
attribute.SetValue(set);`

both of these lines are in the command dealer script, if i change set to 0 it compiles.

ConvertFromString and SetValue are on this script
https://github.com/SwagAccount/the_second_coming_of_k/blob/main/code/Attributes.cs
