### ISSUE TITLE
[Library Manager] "Create" is spelled "Craete"

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5428]
### Describe the bug

In the Library Manager, Create is spelled Craete
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/e3726643-4718-4f3e-8878-651e5fbc716b)

### To Reproduce

1. Go to the library manager.
2. Hover over create new library. 

### Expected behavior

It should be spelled correctly.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/95300917/6045cac1-b429-43ac-bae2-f1886cf1e3ee)

**Comment by badandbest** [comment]
huge blunder
