### ISSUE TITLE
Need help playing S&Box

### ISSUE THREAD

**Issue by RustmDz** [Facepunch/sbox-issues#5430]
I got early access, downloaded the game and logged into it, logged into the play and wanted to play in the play, but I can't move, what to do, please help,there will be a photo below that I see in the game, I can move the camera, and that's it
![2024-04-29_00-51-23](https://github.com/Facepunch/sbox-issues/assets/168366737/1508dd50-eae7-470f-9c62-81f42dc1e09b)

**Comment by badandbest** [comment]
I tried joining a few gamemodes and I'm not having any problems at all.

It'd be a lot more helpful if you went into more detail. Like does this happen on every gamemodes? What are your computer specs? If you also attach your log file the devs might better understand what the problem is.

**Comment by qxxst** [comment]
So when you went to play in the play, what gamemode did you launch?

**Comment by RustmDz** [comment]
Alas, this happens in all the modes I enter

**Comment by handsomematt** [comment]
what is the exception https://docs.facepunch.com/s/sbox-dev/doc/reporting-errors-2OTPIafqCJ

**Comment by eni3ex** [comment]
I have the same problem. I downloaded the game for the first time today.
But this is not the main problem. In other mods movement is not blocked, but I get 0-20 avg fps, I do not understand how to do anything here? (i78750h/gtx1070/32gb) My steam64: 76561198881642778

Games/mods that cause this problem:
https://asset.party/sandcube/voxelworld/
https://asset.party/evilinc/real_fps_base/ (only first few times, i think)
https://asset.party/cflo/gauntlet/

Logs: (one error looped endlessly in the console)
https://mclo.gs/ytDr1rc
https://mclo.gs/aYLpVMX
https://mclo.gs/qo1OSCm

[GameMenu] Exception when calling 'FixedUpdate' on PlayerController on (player)	System.Exception: Default Surface not found!

**Comment by handsomematt** [comment]
#5429
