### ISSUE TITLE
Reset button for a Component in the Inspector window does nothing

### ISSUE THREAD

**Issue by collinstevens** [Facepunch/sbox-issues#5434]
### Describe the bug

reset button for a component in the inspector does nothing

### To Reproduce

1. Create a component with a property initialized to a value
2. Attach the component to a GameObject and modify the Property's value
3. Click the ellipsis on the component in the inspector and select "Reset"

### Expected behavior

the Reset button should set the properties to their default values

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/19230602/48d29748-7605-403e-b973-1235e1a4442b)
![image](https://github.com/Facepunch/sbox-issues/assets/19230602/67c21272-2037-4f93-b4e0-29ed64d92008)

**Comment by DevulTj** [comment]
Added this now

**Comment by PolSpock** [comment]
@DevulTj since your [last change](https://discord.com/channels/833983068468936704/835035328779518023/1234464556814958633)
```
public override void Reset()
{
  base.Reset();
}
```
is now breaking the Component behavior. I had to remove the base function call in order to restore the previous behavior.

I'm not sure if this is expected.

**Comment by DevulTj** [comment]
Yeah, fair enough, I'll fix that properly.

**Comment by PolSpock** [comment]
Calling `MapInstance.Reset()` is now throwing error:
```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.MapInstance.LoadMapAsync(String mapName)
```

This breaks my Reset logic for my project :/

**Comment by DevulTj** [comment]
This isn't happening anymore
