### ISSUE TITLE
`IsProxy` returns `false` for Host on `Component.OnEnabled()`

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5436]
### Describe the bug

Hi,

Since the recent https://github.com/Facepunch/sbox-issues/issues/5422#issuecomment-2082391195 components order (once again, i guess)

Using `IsProxy` `Component.OnEnabled()` always return `false` on the Host context

**also**, it's the same for `OnAwake()` but i don't know if it's the expected behavior ; poke https://github.com/Facepunch/sbox-issues/issues/4950

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `NetworkTest.cs` :
```
protected override void OnAwake()
{
	base.OnAwake();
	Log.Info( "NetworkTest OnAwake " + IsProxy + " " + Network.OwnerConnection?.DisplayName );
}

protected override void OnEnabled()
{
	base.OnEnabled();
	Log.Info( "NetworkTest OnEnabled " + IsProxy + " " + Network.OwnerConnection?.DisplayName );
}

protected override void OnStart()
{
	base.OnStart();
	Log.Info( "NetworkTest OnStart " + IsProxy + " " + Network.OwnerConnection?.DisplayName );
}
```
3) Start a game `networking.scene`, join with another player
4) Look console

![image](https://github.com/Facepunch/sbox-issues/assets/5229571/b2dacc9d-cef4-4120-874b-e53244d36467)

### Expected behavior

Is it the new expected behavior? Is it a bug?

**Comment by handsomematt** [comment]
It was accidentally returning true before because of the misorder (OnEnabled after first update), and would have always been false in OnAwake too. I don't think it makes any sense when you consider how you spawn a networked object:

```
// OnAwake and OnEnabled will get called here
// But not OnStart because it is not the first update
var player = PlayerPrefab.Clone( startLocation, name: $"Player - {channel.DisplayName}" );
// Networking is set up at this point
player.NetworkSpawn( channel );
// After this OnStart will get called just before OnUpdate with valid networking
```

How come you're doing so much logic in OnEnabled vs OnStart too?

**Comment by PolSpock** [comment]
I like to use `OnStart` & `IsProxy` for subscribing to static events from another component.

An example:
When i update my `PlayerModelComponent` by changing the Player's `SkinnedModelRenderer`, i need to tell other connected players to change it as well.

So i'm using a `Broadcast` function and then i `Invoke` static events, something like `PlayerModelComponent.OnModelChanged.Invoke(GetOwner())`.

This event will be listened to by other components. Like a `CosmeticComponent` which will be in charge of reloading the `Cosmetic` specified for the new PlayerModel set.

And since every new player & current player is loading every component attached to my player (through the Snapshot), i have to make an `IsProxy` verification for my `CosmeticComponent`.
Indeed, i don't need to subscribe multiple times to `PlayerModelComponent.OnModelChanged`. Only one time is needed, so I'm subscribing to this event only for the `CosmeticComponent` that I own. So I have:
```
protected override void OnStart()
{
            if ( IsProxy ) { return; }
            PlayerModelComponent.OnModelChanged += OnModelChanged;
}
```


With the recent Components Order, i have several components that are not loading in the same order as before, creating some late Event subscriptions. So, throwing some issues causes some events not subscribed by components because they are not loaded yet.
So this part is my fault, I have to create a better "boot order" for my components & subscriptions. But yeah, _ça fait chier_ when something starts to bug.

If you have any reflections or suggestions to improve my logic, i'm listening

**Comment by handsomematt** [comment]
It's hard to fix something that was only working because it was broken.

Like I said before you're calling NetworkSpawn after the components have been created (calling OnAwake, OnEnabled) so it'll only be valid in OnStart(). It was only working before because OnEnabled() was being called after OnStart().

This article might have some applicable design patterns https://gamedevbeginner.com/start-vs-awake-in-unity/ for you, stuff like constructing references and subscribing to events should usually be done in OnAwake, and then you'd do everything else in OnStart.

**Comment by PolSpock** [comment]
I never said i want to bring back the old logic, I just want to be sure is not a regression

Since last weekend, several S&box commits have broken some components logic in my project. So, I have to rewrite some of my shit : I want to ensure i won't change these due to a bug

also, thanks for the link 💌
