### ISSUE TITLE
vulkan problem

### ISSUE THREAD

**Issue by sboxtop** [Facepunch/sbox-issues#5438]
### Describe the bug

how i can lauch game without vulkan?

### To Reproduce

help with error pls

### Expected behavior

i dont know how to fix this

### Media/Files

![Снимок экрана (441)](https://github.com/Facepunch/sbox-issues/assets/168536303/34c65ea7-b577-4cec-b786-04e3b700ebe7)

### Additional context

im running on windows 10

**Comment by UAVXP** [comment]
No way to launch anything but Vulkan. They've mentioned in their blog that they gonna use only Vulkan from now on

**Comment by MrBrax** [comment]
windows 11 and no vulkan support on the gpu doesn't check out

**Comment by UAVXP** [comment]
https://sbox.game/news/vulkan

**Comment by handsomematt** [comment]
is this a laptop
what cpu + gpu do you have
do you have the latest drivers installed for both your cpu and gpu

**Comment by adev111** [comment]
I want to say the same thing as matt said
