### ISSUE TITLE
Weird lighting/rendering after some gamemode reloads

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/sbox-issues#544]
**Describe the bug**
Since a couple of time, I started to observe some lighting/rendering problems on some maps after several reloads (back to the main menu and quick launch of a gamemode). At first I thought it was related to the gamemode I was using but after some tests (`Sandbox`, `Wirebox` and `DM98` gamemodes for example), I think it's more related to an internal problem.

To illustrate this issue, I have included a few screenshots to show you the difference and also the pretty rare error I got between each reload (the map used is `dm_industrial`).

**To Reproduce**

Try to do several "reloads" at varying intervals (**no matter how long between each one**, this bug can occur minutes/**hours** after the initial launch of the game).

**Screenshots**

_Normal map view._
![590830_20210801141214_1](https://user-images.githubusercontent.com/26360935/127770595-7b8d6f82-5525-4022-8652-161a4ebf3352.png)

_Weird preview of the map (after building error or some reloads)._
![590830_20210801141117_1](https://user-images.githubusercontent.com/26360935/127770594-62c06658-9dc3-4ec3-a703-4104a77f78d9.png)

_In the weird view, it seems that the shadow of Terry is no longer reflected on the ground._
![590830_20210801141853_1](https://user-images.githubusercontent.com/26360935/127770597-f6e91b94-4eb1-4c23-8b48-d9fcff9da511.png)

_Appears some times without any real reason (most of the time, my reloads are spaced of about ten/thirty minutes)._
![590830_20210801142209_1](https://user-images.githubusercontent.com/26360935/127770730-49a4da2f-1123-47d9-b61f-89acb20b07e2.png)

**Additional context**

Outside of testing, I'm mainly working on a derivation of the Sandbox gamemode (with very few modifications for the moment) and where I can meet this problem.

**Comment by justynboi** [comment]
I have experience with this bug and is very annoying. It happens on every map.

**Comment by goaaats** [comment]
I can confirm this, working on my gamemode - I can't trigger it reliably but it seems to happen about 1 in 15 restarts I'd say. Entity models also won't show up in certain cases when this is happening.

GTX 1080 on Intel/Windows 10

**Comment by KayaDLX** [comment]
I can confirm this aswell, the cubemaps keep getting randomized or break after reloading a gamemode, or just simply rejoining the map.

This is noticeable specially after compiling a map and asking to build cubemaps on load, as the gamemode will reload itself, the cubemaps will just break until the game is restarted.

Also can confirm the entities missing on the maps when this is happening, at some rare occasions my doors would stop rendering in the map.

This very old video of mine can even demonstrate the bug happening.

- At first, the door would not show up, but the cubemaps are correct for the map, but not the viewmodel.
- After reloading, the door is showing up again and the cubemaps broke for the map.
https://files.amperpowered.com/kaya/1cE4LM/Desktop_2021.06.29_-_23.11.42.08.mp4
