### ISSUE TITLE
Inspector UI is broken for assets

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5442]
### Describe the bug

All of the data for assets in the inspector is broken.
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/55cfd73a-ad48-40e8-b9ae-49a6c8004792)

### To Reproduce

1. Click on the inspector
2. Observe the UI being broken

### Expected behavior

It should look like this:
![318986978-84a35637-86fc-4775-b0d6-9ba215769fed](https://github.com/Facepunch/sbox-issues/assets/95300917/857b4cce-3214-4e62-932f-1696651ffc72)

**Comment by Nolankicks** [comment]
Seems to be fixed

**Comment by aylaylay** [comment]
Is it? It's still broken for cloud assets and I don't think we've pushed any fixes for it yet.

**Comment by Nolankicks** [comment]
> Is it? It's still broken for cloud assets and I don't think we've pushed any fixes for it yet.

Not sure. It was doing that earlier in the day. Seems to fixed with a few restarts. Maybe the issue is still present for other people. I’ll reopen to see if there are any other reports.

**Comment by aylaylay** [comment]
Should be fixed now
