### ISSUE TITLE
XML escape doesn't work for the inspector.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5447]
### Describe the bug

XML escape (e.g `&amp;`) doesn't work in the inspector.

### To Reproduce

1. Make a property
2. Write a summary
```c#
/// <summary>
/// I like s&amp;box
/// </summary>
``` 
3. Hover over the property in the inspector. It still says `&amp;`.
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/93d77c5e-147b-4cae-96ce-7e15be626ec7)

### Expected behavior

Here's how it should look like when hovering.
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/a12a8d1b-f232-4e26-a26c-500d4515bb69)

### Additional context

Just using `&` won't work either.
```c#
/// <summary>
/// I like s&box
/// </summary>
``` 
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/d12f474b-12b4-48a9-ba75-c7e280abcda3)

**Comment by badandbest** [comment]
Kind-of related. Asset.party has the same problem apparently. https://github.com/Facepunch/sbox-issues/issues/3521

**Comment by DevulTj** [comment]
this should be fine now in-game, let me know if it is?

**Comment by badandbest** [comment]
@DevulTj It stopped working for some reason.
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/d3671454-b813-4533-b78f-52fb8b50b9ef)
