### ISSUE TITLE
Players are not networked properly

### ISSUE THREAD

**Issue by Sampleeeee** [Facepunch/sbox-issues#5448]
### Describe the bug

I am attempting to make a multiplayer gamemode. I have copied some code for a basic walk controller from sbox_walker and stolen the code from NetworkHelper to initialize my players.

### To Reproduce

Start the game in the editor
Start another instance
Move around with one player
Notice the others dont move

### Expected behavior

The players are networked properly

### Media/Files

https://cdn.discordapp.com/attachments/895597253316714497/1235428646408421386/babysports.zip?ex=66345616&is=66330496&hm=7de318235026ceab5dd5a0a91538544117410266430db41a0210657230bdc175&

repro

### Additional context

I have tried enabling networking on multiple objects, tried the walk controller from sbox_scenetesting. I am at a loss as to what I am doing wrong

**Comment by handsomematt** [comment]
ask for support in discord
