### ISSUE TITLE
Default value for [Property] is ignored when [Net] is also set

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#545]
**Describe the bug**
Default values for properties are not set in the FGD if a variable has a [Net] attribute.

**To Reproduce**

1. Declare a new variable in an entity with an initial value.
2. Add [Net] and [Property] attributes to variable.
3. Default value of the property in Hammer is incorrect.

**Comment by robotboy655** [comment]
This was fixed.
