### ISSUE TITLE
My game stays in offline mode

### ISSUE THREAD

**Issue by OlziYT** [Facepunch/sbox-issues#5452]
### Describe the bug

Hello I've had this bug for several weeks and the game tells me I'm in offline mode. I've tried checking the game files and clearing the cache in the game settings and reinstalling.

### To Reproduce

Run the game

### Expected behavior

The game should show me things like [this](https://asset.party/)

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/90570808/f3cd2fe4-4b54-4c1c-ade5-1f01224aace8)
[Log.108.log](https://github.com/Facepunch/sbox-issues/files/15200521/Log.108.log)

**Comment by handsomematt** [comment]
You have some firewall either on your PC, router or ISP blocking access

**Comment by OlziYT** [comment]
I've deactivated the firewall and I've also tried 4g but it doesn't work, but the ‘asset.party’ site works correctly.

**Comment by OlziYT** [comment]
> You have some firewall either on your PC, router or ISP blocking access

I've deactivated the firewall and I've also tried 4g but it doesn't work, but the ‘asset.party’ site works correctly.

**Comment by MrBrax** [comment]
can https://services.facepunch.com/sbox/package/list/?count=16&engineVersion=17 be accessed in a web browser?

**Comment by OlziYT** [comment]
> can https://services.facepunch.com/sbox/package/list/?count=16&engineVersion=17 be accessed in a web browser?

yes

**Comment by OlziYT** [comment]
Hello, do you have any news about this bug?

**Comment by OlziYT** [comment]
> You have some firewall either on your PC, router or ISP blocking access

Bonjour, je suis désolé, cela est dû à mon pare-feu. Comment puis-je résoudre ce problème ?

**Comment by spaghettigoth** [comment]
how did you fix this issue
