### ISSUE TITLE
"Unable to initialize Vulkan" message.

### ISSUE THREAD

**Issue by ukerat** [Facepunch/sbox-issues#5458]
### Describe the bug

Whem im opening the game, game dont want to open and showing message "Unable to initialize Vulkan".
I tried to update and reinstall my Nvidia drivers, but it isnt helping. 

### To Reproduce

1. Opening the game 
2. Getting the message

### Expected behavior

The game should RUN.

### Media/Files

![ssss](https://github.com/Facepunch/sbox-issues/assets/148714983/a883ca27-3dab-4e6a-acff-ba853c7c46d7)

### Additional context

My PC have:

Nvidia GTX 1650 GPU
AMD Ryzen 5 4600H with Radion Graphics as the CPU
OS is Windows 10 PRO
8 GB of RAM

**Comment by Gmod4phun** [comment]
In case this is something facepunch can't fix, try looking into this solution https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps%2Fgame-on-notebooks-with-amd-radeon-igpus

**Comment by handsomematt** [comment]
Update your AMD AND NVIDIA drivers

**Comment by ukerat** [comment]
> In case this is something facepunch can't fix, try looking into this solution https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps%2Fgame-on-notebooks-with-amd-radeon-igpus

It worked, thanks!

**Comment by ukerat** [comment]
> In case this is something facepunch can't fix, try looking into this solution https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps%2Fgame-on-notebooks-with-amd-radeon-igpus

**Comment by ukerat** [comment]
It worked! Thanks for helping!
