### ISSUE TITLE
citizen.fbx erroneously(?) exported as ASCII FBX

### ISSUE THREAD

**Issue by iguneesu** [Facepunch/sbox-issues#546]
As of the update that upstreamed the Citizen asset sources directly into the game's content folder, citizen.fbx is exported as ASCII FBX 7.5, whereas the LoD assets, animations and sample clothing files are in binary FBX. This poses an additional problem for Blender users, as Blender does not support directly importing ASCII FBX files.

**Comment by robotboy655** [comment]
I think this was fixed @MaxLebled ?

**Comment by MaxLebled** [comment]
Yup, was fixed yesterday! Cheers
