### ISSUE TITLE
PolygonMesh TexCoords

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#5461]
### What it is?

The current version of PolygonMesh doesn't seem to support per-vertex texcoord, instead exposing per-face Properties like Offset, Angle, Scale and Texture align functions. 

### What should it be?

The old PolygonMesh API used a MeshVertex type which let you set position and tex coords. I like being apply to just supply my vertex positions with the correct winding indices and have it work, but being able to give them proper mesh uvs would be lovely.

**Comment by aylaylay** [comment]
I'm not going to be adding texcoords to PolygonMesh, that's dumb. I can however add a function to compute face texture parameters from texcoords.

**Comment by DoctorGurke** [comment]
Does this not limit what kind of uvs you could have on an editable mesh face, if they're only described as offset, rotation and scale? If this works with other uv transforms across the face (ie feed in all uvs?) then I guess that works? Not sure why texcoords are dumb, although I do get that this is mostly for the editable half-edge meshes.

**Comment by aylaylay** [comment]
When you're editing the mesh, it's going to be uving the mesh based on these properties so any per vertex UV it has is going to get scrapped. Hammer meshes save UVs too and I think it's dumb, I can't find a valid reason for it.

**Comment by DoctorGurke** [comment]
Would make it super easy to use this to import models as editable within scene, ideally I'd kind of like to keep original uv without having to trade for vmf style texture transforms

**Comment by DoctorGurke** [comment]
I understand, I'm saying that blows

**Comment by aylaylay** [comment]
Let me have a think on it some more, I might add them.

**Comment by aylaylay** [comment]
PolygonMesh uses texture coords now. You'll probably want to use `PolygonMesh.SetFaceTextureCoords`

**Comment by DoctorGurke** [comment]
uvs seem to work nicely, thanks a lot. One thing I noticed that gave me bit of debugging trouble was that I need to assign a material to a face before I set FaceTexCoords. Not a big deal, should probably be documented though as my Material and geometry logic were separate so I didn't immediately think of it 😅 
![sbox-dev_3L5eGQV6mC](https://github.com/Facepunch/sbox-issues/assets/12602100/e52ce38f-edeb-4914-adf6-0f2db571660f)

**Comment by aylaylay** [comment]
You shouldn't need to apply a material, what was happening?

**Comment by DoctorGurke** [comment]
switching them like this will just error from Interop with IndexOutOfRange
![devenv_QLboXTdyNc](https://github.com/Facepunch/sbox-issues/assets/12602100/e9545836-41c6-4ec0-95be-7a26da3162d9)

![sbox-dev_piPSsqsnxq](https://github.com/Facepunch/sbox-issues/assets/12602100/96d58648-203d-4e4e-950e-8f06333bb884)

**Comment by aylaylay** [comment]
I will fix this

**Comment by aylaylay** [comment]
Should be fixed now, obviously it's wise to set a material before setting coords though
