### ISSUE TITLE
Optional setting to download a game and never have to download it again

### ISSUE THREAD

**Issue by adev111** [Facepunch/sbox-issues#5463]
### For?

S&Box

### What can't you do?

The title, download game and keep it so you can play offline 

### How would you like it to work?

Simple setting in the options in the "Game" tab. Concept of what i want:
![example](https://github.com/Facepunch/sbox-issues/assets/95112313/d80fb275-1fb3-4e02-a477-880093b60eec)

### What have you tried?

Trying to download github projects but you need to launch it through the editor

**Comment by handsomematt** [comment]
All game assets stay downloaded already
