### ISSUE TITLE
Create custom loading screens similar to entity system

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5468]
### For?

S&Box

### What can't you do?

Currently, you are unable to modify the loading screen of your game, besides tweaking the text that shows up. I know before the scene system, developers were able to create their own loading screens.  Currently what you see is just a very generic loading one.
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/35985be7-c3d1-474d-8457-8e6fe20d0a74)
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/d42f186c-a9a2-4653-ad40-1672146a2dbc)

### How would you like it to work?

I would like it to work similar to how it used to work. Or defining a panel to display for the loading screen.

### What have you tried?

There is no way currently after the scene system.

**Comment by garrynewman** [comment]
Planned, but not really a priority

**Comment by badandbest** [comment]
We got background images now.
