### ISSUE TITLE
Envmap probe (cubemaps) appear broken

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#5469]
### Describe the bug

Looks like the envmap probe component is broken. When you uncheck "Render Dynamically" it will appear fixed in scene but on play still be broken
![image](https://github.com/Facepunch/sbox-issues/assets/105941502/75b19d54-dee7-4bab-ae2f-df1382929a63)

### To Reproduce

Make a envmap probe in a map in scene

### Expected behavior

Should not look all broken

**Comment by KingOfTheFBI** [comment]
It seems to not be an issue on upload

**Comment by LVJohnFreeman** [comment]
Got a similar issue to this, been having issue weith combined light probes, lighting gets very messy after being compiled in Hammer.
![Screenshot_790](https://github.com/Facepunch/sbox-issues/assets/54272126/b3d7e88a-2f31-4a8c-89a8-63c4b50bfbc3)
![Screenshot_789](https://github.com/Facepunch/sbox-issues/assets/54272126/46ba1e2e-24ac-43de-a9fa-56cf5ac686a2)
![Screenshot_787](https://github.com/Facepunch/sbox-issues/assets/54272126/7a7775a4-f3dd-47e6-8ad2-fc7eeb04870f)
![Screenshot_791](https://github.com/Facepunch/sbox-issues/assets/54272126/e61836f9-9732-406c-a0b2-159a1d7a23dc)


Issue seems to disappear when turning off dynamic rendering for the cubemaps. Adding the vmap and the compiled vpk for repro.
[tzoo.zip](https://github.com/user-attachments/files/15827350/tzoo.zip)
