### ISSUE TITLE
Citizen graph animation parameter doesnt seem to work

### ISSUE THREAD

**Issue by DoctorWhoFR** [Facepunch/sbox-issues#5470]
### Describe the bug

I saw in the Citizen Graph that 
![image](https://github.com/Facepunch/sbox-issues/assets/26010905/bb0e82bb-d1e4-41a0-9b7c-58702d8d55cd)

Exist and it's usable in the graph editor
![image](https://github.com/Facepunch/sbox-issues/assets/26010905/2e7ba389-27fa-41a7-86c7-ce3216033abc)

i dont think this is a code fault because the hold type change in the same code is working
![image](https://github.com/Facepunch/sbox-issues/assets/26010905/868cd9b0-eea0-4e3f-a6d5-4adf39a155d8)

```
CitizenAnimationHelper.HoldType = CitizenAnimationHelper.HoldTypes.HoldItem;
CitizenAnimationHelper.Handedness = CitizenAnimationHelper.Hand.Right;
skinnedModelRenderer.Set( "ik.hand_right.enabled", true );
```

### To Reproduce

Just create a blank project and add a basic player controller with animation helper and Set ik.hand_right.enabled to true, nothing change.

### Expected behavior

Move the hand

**Comment by aylaylay** [comment]
You're not setting the position of it?
