### ISSUE TITLE
Select Engine Version in Game Projects

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5472]
### For?

S&Box

### What can't you do?

You can't opt-out of future versions of the engine, and always forced to use the latest/staging builds. These existing versions are ever-evolving (which is fantastic for developers), but are always bringing breaking changes with every few updates.

Being able to stay on a specific engine version allows you to keep your project stable while facepunch is working on a new feature that may not be production-ready just yet or a new pain day has come that you are not yet equipped to take-on (eg. if there was a mesh editor update destroying all existing models you had made for your game. you would be better off waiting until facepunch implements a proper JsonUpgrader for older model versions before updating your engine version.)

### How would you like it to work?

You should be able to select an engine version when creating a project (or select staging/latest to always be using the latest engine version which would be the default):
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/28c65ad3-879a-47ca-85af-693dd53b9a33)

This request would go hand-in-hand with #5471

### What have you tried?

There' really no other option for engine versioning.

**Comment by handsomematt** [comment]
Not feasible for platform projects, this would probably be a thing eventually with standalone but we have no idea what that'll look like yet.
