### ISSUE TITLE
[Action Graph] Not able to reference components within libraries in action graph

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5473]
### Describe the bug

When using components from libraries in Action Graph it gives type binding errors. 
`Aggregate of 3 exceptions:
>>> Exception 0:
Unable to resolve type binding.
   at ActionGraph.e1c33c0d-0a17-4fce-8c0d-71ba7bc3c321.Node6()
>>> Exception 1:
Missing value for required parameter.
   at ActionGraph.e1c33c0d-0a17-4fce-8c0d-71ba7bc3c321.Node6.Property[T]()
>>> Exception 2:
Type mismatch: expected 'FootstepSoundsComponent', but found 'T'.
   at ActionGraph.e1c33c0d-0a17-4fce-8c0d-71ba7bc3c321.Node1.Input[footstepSoundsComponent].Link()
`
![Screenshot 2024-05-06 143308](https://github.com/Facepunch/sbox-issues/assets/95300917/6f066b5a-686d-45f7-a74a-cb6d49b9056f)

### To Reproduce

1. Open the attached project.
2. Upload to asset party. NOTE; this bug does not occur in the editor, only in the client.
3. Open the game in the client and observe the errors.
[action_graph_lib_bug (2).zip](https://github.com/Facepunch/sbox-issues/files/15225231/action_graph_lib_bug.2.zip)

### Expected behavior

You should be able to reference components from the library.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/95300917/ea759b5c-cc10-42a0-ad08-ecde3e678009)
`public void BugGraph(FootstepSoundsComponent footstepSoundsComponent)
	{
		Log.Info(footstepSoundsComponent);
	}`

**Comment by Metapyziks** [comment]
Looks to be caused by an inconsistency in how we name library assemblies in editor vs published.
