### ISSUE TITLE
Animated Textures broken, showing wrong order of frames

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#5476]
### Describe the bug

Seems something is wrong with animated textures, on preview for cube and plane they work but on the preview for sphere and in hammer/scene they just don't work.

Here is an animated texture on cube preview:

https://github.com/Facepunch/sbox-issues/assets/105941502/a6faeb38-7e8e-4f0b-b2d0-4ee67df8bbcf

Here is the same unaltered texture in action in hammer (appears the same in scene):

https://github.com/Facepunch/sbox-issues/assets/105941502/08937c98-8477-4a61-92af-b6880a9f26f2

### To Reproduce

Make animated texture
Put in hammer/scene

### Expected behavior

It plays the frames correctly

### Additional context

Tried two different textures with way different resolutions same issue

**Comment by aylaylay** [comment]
I have no idea how you're using an animated in hammer or scene

**Comment by aylaylay** [comment]
Can you provide the files for this? The material and images

**Comment by KingOfTheFBI** [comment]
> Can you provide the files for this? The material and images

Here is an example of it not working. It's not the same texture but it does the same exact thing.

**Comment by KingOfTheFBI** [comment]
> Can you provide the files for this? The material and images

[asset.zip](https://github.com/user-attachments/files/15936104/asset.zip)

**Comment by aylaylay** [comment]
Okay so this isn't working because the complex shader is doing the animation in vertex shader, we're not going to change this because we're likely going to get rid of animation support on complex, you can easily do an animated texture sheet in shadergraph

**Comment by Gmod4phun** [comment]
I think I just encountered this, it looks like its offset by one cell. Is this really something not worth fixing?

https://github.com/user-attachments/assets/be533a43-e5cf-4d88-8820-763f90df1446
