### ISSUE TITLE
The default .gitignore file is not ignoring the obj/Debug folders in Libraries

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5479]
### Describe the bug

With Libraries now having their own obj/ and Debug/ folders in the `Code/`, `Editor/` and `UnitTests/` folders of each library, the default gitignore does not accommodate for these files and they will be commit to git if they aren't manually dealt with.

### To Reproduce

1. Create a new project and commit it to git.
2. Create a new library in that new project
3. Notice that in the diffs there will be tons of binary/cache files that should be ignored by the gitignore

### Expected behavior

The default gitignore should ignore libraries

**Comment by badandbest** [comment]
I always add `**/obj`, `**/Properties` etc to my .gitignores ![image](https://github.com/Facepunch/sbox-issues/assets/91832803/c4b0a57a-8425-47e8-b040-76f7ae4937f8)


| Before| After |
|--------|--------|
| ![image](https://github.com/Facepunch/sbox-issues/assets/91832803/e606edb1-25a2-45df-bd16-1fbbd4180b21) | ![image](https://github.com/Facepunch/sbox-issues/assets/91832803/fb80bacf-864d-4454-a1af-76652caf39ce) |

**Comment by DevulTj** [comment]
Sorted if you grab the new template gitignore 👍🏻
