### ISSUE TITLE
Expose API to Upload Projects to Asset.Party

### ISSUE THREAD

**Issue by Pieeer1** [Facepunch/sbox-issues#5481]
### For?

S&Box

### What can't you do?

I am unable to automatically upload new versions of my code to Asset.Party through a CICD Pipeline, as there is no non-ui based way exposed to the end user. 

### How would you like it to work?

I would like there to be an exposed API or CLI functionality to upload a project to asset.party. This would allow CICD pipelines to automatically upload new versions without having to do it through the UI

### What have you tried?

I have tried scouring the documentation to see if this is possible. I was unable to find any solutions

**Comment by CarsonKompon** [comment]
Seems a bit overkill for the 2 seconds it takes to publish a project. I think having cmd functionality for export when that comes around is a necessity but otherwise I don't think anything is needed for uploading to asset.party

**Comment by Pieeer1** [comment]
> Seems a bit overkill for the 2 seconds it takes to publish a project. I think having cmd functionality for export when that comes around is a necessity but otherwise I don't think anything is needed for uploading to asset.party
> 
> (Mostly cause it sounds like it would encourage more bad actors that there would be good actors to use it in the first place)

Same argument could be made for publishing a visual studio project to azure or literally any other publishing platform. It isn’t the fact that it takes two seconds, it’s about the ability to do it automatically after a successful run of tests, at triggered times, without having to have a certain version of the code checked in locally. 

Every other service (to varying degrees of success) weed out bad actors, and there are lessons learned there that can be applied to such service. 

Inherently forcing the end user to have the client installed to publish is weird, considering that almost all other services handle it through a CLI (often given through the sdk)

**Comment by Nolankicks** [comment]
> > Seems a bit overkill for the 2 seconds it takes to publish a project. I think having cmd functionality for export when that comes around is a necessity but otherwise I don't think anything is needed for uploading to asset.party
> > (Mostly cause it sounds like it would encourage more bad actors that there would be good actors to use it in the first place)
> 
> Same argument could be made for publishing a visual studio project to azure or literally any other publishing platform. It isn’t the fact that it takes two seconds, it’s about the ability to do it automatically after a successful run of tests, at triggered times, without having to have a certain version of the code checked in locally.
> 
> Every other service (to varying degrees of success) weed out bad actors, and there are lessons learned there that can be applied to such service.
> 
> Inherently forcing the end user to have the client installed to publish is weird, considering that almost all other services handle it through a CLI (often given through the sdk)

Just don’t see the need for this. Just upload it after.

**Comment by chrisspieler** [comment]
Allowing the whole build and release process to be automated on a headless server will be very important for some teams. Deploying to Asset Party is an important part of that.

**Comment by Pieeer1** [comment]
> > > Seems a bit overkill for the 2 seconds it takes to publish a project. I think having cmd functionality for export when that comes around is a necessity but otherwise I don't think anything is needed for uploading to asset.party
> > > (Mostly cause it sounds like it would encourage more bad actors that there would be good actors to use it in the first place)
> > 
> > 
> > Same argument could be made for publishing a visual studio project to azure or literally any other publishing platform. It isn’t the fact that it takes two seconds, it’s about the ability to do it automatically after a successful run of tests, at triggered times, without having to have a certain version of the code checked in locally.
> > Every other service (to varying degrees of success) weed out bad actors, and there are lessons learned there that can be applied to such service.
> > Inherently forcing the end user to have the client installed to publish is weird, considering that almost all other services handle it through a CLI (often given through the sdk)
> 
> Just don’t see the need for this. Just upload it after.

There is a massive need for this. 

If I want to upload a specific version of the codebase the solution is what? With no cli or api ability, you have to do the following:

Checkout to a specific tag (if the tag exists) or a specific commit version locally, build, and then upload?

This is an insane task that could literally be automated through a CICD job that should be done through a cli.

I should NOT be forced to again download steam, download the full client, checkout to a specific version, and then upload it through the client. This should be done through an automated job if needed.

Anyone who has done any production level deployments to actual clients in a professional setting would understand this, the ability to revert and dynamically push changes is essential to high quality software.

**Comment by handsomematt** [comment]
The uploader is very integrated with the assetsystem to compile and figure out references and dependencies. This wouldn't work.
