### ISSUE TITLE
Skinned mesh renderer lags behind

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5484]
### Describe the bug

I am moving an object using my follow attachment script.
As a child the object has an arm which uses a skinned mesh renderer.

That mesh renderer and any other skinned mesh renderers as a child will always lag behind. In the scene view this doesn't occur

### To Reproduce

1. Move an object using pre render
2. Have a child with a skinned mesh renderer
3. Do the hanky panky

### Expected behavior

Not lagging behind

### Media/Files

https://github.com/SwagAccount/the_second_coming_of_k/blob/main/code/FollowAttachment.cs

https://github.com/Facepunch/sbox-issues/assets/160753124/36c24333-efbf-4deb-80b5-52d698b4b302
^ I have also attached a normal model to show its not the script that is lagging behind.

**Comment by garrynewman** [comment]
Does the same occur if you do it in OnUpdate?

**Comment by SwagAccount** [comment]
Yes, ive tried all updates

**Comment by SwagAccount** [comment]
I've now changed my system so the arms attach to the camera and the ik is to move the hand to the gun, still the same effect.

**Comment by PolSpock** [comment]
Hi,

Since [this commit](https://discord.com/channels/833983068468936704/835035328779518023/1237836486997708881), i guess cause i didn't have this issue yesterday,
it looks like the `GetAttachment` position is now incorrect during the first tick :

![image](https://github.com/Facepunch/sbox-issues/assets/5229571/b5c494ed-b91e-41d6-bd5d-905a34de495d)
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/67dfd7f3-2095-4073-a97f-a437c436a602)

I am currently investigating to find a scenario to reproduce the issue. I will edit this comment

**Comment by garrynewman** [comment]
I made a change that should fix the first frame being wrong position.

This won't fix the OP request though. This is a chicken and egg problem, and the only way I can see to fix it would be to allow you to set IK bones to offsets from GameTransforms.

**Comment by PolSpock** [comment]
> I made a change that should fix the first frame being wrong position.
> 
> This won't fix the OP request though. This is a chicken and egg problem, and the only way I can see to fix it would be to allow you to set IK bones to offsets from GameTransforms.

Nothing change for the sub issue (my AppId : 590830), i have created a issue in order to stop off topic for this issue : https://github.com/Facepunch/sbox-issues/issues/5493

**Comment by SwagAccount** [comment]
Is there a reason that the skinned mesh renderer is updating after the camera, that is the only understandable thing that is happening. I can make any normal model renderer I want follow something by setting the position and it's perfect, but as soon as I change the model renderer to a skinned renderer it lags a frame behind.

**Comment by SwagAccount** [comment]
Ok strange thing happening. When I move the gun around it leaves a ghost of an arm that is perfectly connected to the gun, how I want, whilst the rest of the arm is stuck a frame behind. However, when I record it the ghosting doesn't appear in the recording. What on earth is happening.

**Comment by SwagAccount** [comment]
Ok, solved the issue by using SetIK and using the correct naming for parameters in anim graph.
https://cdn.halend.dev/retro/1105/sbox-dev_1xz8x0h9y0.png
`if ( IkRightHand.IsValid() && IkRightHand.Active ) Target.SetIk( "hand_right", IkRightHand.Transform.World );
        else Target.ClearIk( "hand_right" );`

**Comment by SwagAccount** [comment]
https://github.com/user-attachments/assets/d833240f-98b6-41f2-be3f-2dab0b7d0c85

Still happens, please fix.

<3
