### ISSUE TITLE
Add `Type.GetTypeCode` to the white list or add an equivalent method to `TypeLibrary`

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5485]
### For?

S&Box

### What can't you do?

I'm trying to add this library to my project: https://github.com/bijington/expressive

But it doesn't work because of the whitelist.

`Whitelist Error: System.Private.CoreLib/System.Type.GetTypeCode( System.Type )`

### How would you like it to work?

Allow it in the API.

### What have you tried?

I can replace the code that relies on TypeCodes to use pure types but that's a lot messier.

**Comment by DevulTj** [comment]
I've whitelisted this for you now
