### ISSUE TITLE
Movements stutter when turning

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5486]
### Describe the bug

Movement in general seems to stutter sometimes, most notably whenever you turn your mouse, Character Controller as well.
Logging the velocity, mouse angles, and position before/after matches with the expected velocity, but I'm clearly moving slower.

### To Reproduce

This seems to be happening with any type of movement, these are the ones I've tested with:

- The base Character Controller
- A custom character controller implementing [Slide and Collide](https://www.peroxide.dk/papers/collision/collision.pdf)
- Straight up setting the position (Noclip)

All of these solutions set the EyeAngles by adding the Input.AnalogLook, nothing else.
If unable to replicate I'll share our repo, where I'm hoping this isn't isolated to.

### Expected behavior

Responsive movement.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/59583743/89168b18-9141-4032-978a-c5d77adeb89a

### Additional context

I've tried lerping the velocity as well, and the results are the same.

**Comment by chrisspieler** [comment]
This or a similar issue seems to be affecting the game "ducc 3".

**Comment by yuberee** [comment]
Hope this videos helps displaying the issue.
At first I am moving forward and strafing by tapping A and D.
Then on the way back I just move forward and strafe by moving my mouse.
You can see that on the second attempt the gaps are uneven and sometimes bunched up.
In the video I am noclipping, so just setting the position with Input.AnalogMove * Input.AnalogLook 

https://github.com/Facepunch/sbox-issues/assets/59583743/6009b27b-d27c-413d-a59b-1b796eee31e7

**Comment by kurozael** [comment]
With the "noclip" one are you setting the position in FixedUpdate or Update and are you multiplying by Time.Delta? Infact can you just post repro projects it'll make it a lot easier to fix.

**Comment by yuberee** [comment]
Sure give me one sec I'll set up a repro

**Comment by yuberee** [comment]
There we go, a shrimple repro.

[movementrepro.zip](https://github.com/Facepunch/sbox-issues/files/15267665/movementrepro.zip)

https://github.com/Facepunch/sbox-issues/assets/59583743/1e5485f2-2535-41eb-94b8-15b78c79e15b

**Comment by andy013** [comment]
I think when you assign Transform in OnUpdate it clears the interpolated values assigned in OnFixedUpdate without applying them. It's using the old position values.

**Comment by kurozael** [comment]
I'm gonna say this is currently by design. Here's why:

We automatically interpolate transforms that are set within a Fixed Update context so that movement appears smooth. But, when outside of a Fixed Update context, setting a transform will clear any interpolation and set it to whatever you want it to be immediately.

The problem you're experiencing is not knowing this behavior.

Really you should either do all of your Transform updates in OnFixedUpdate _or_ OnUpdate but mixing both will conflict.

You can see the problem in the repro is resolved by simply moving
`Transform.Rotation = Rotation.FromYaw( EyeAngles.yaw );`
from `OnUpdate` to `OnFixedUpdate`.

**Comment by chrisspieler** [comment]
Per Conna's advice, changing the code of ducc 3 so that the player transform is only updated in FixedUpdate fixed the issue. This incorrect code came from the Walker player controller, so that should probably be updated: https://github.com/Facepunch/sbox-walker/blob/main/Libraries/playercontroller/Code/PlayerController.cs

**Comment by johncosfm** [comment]
Seems like the behavior used to be that setting only rotation in update wouldn't effect the interpolation of position, which seems like it would be the ideal behavior, any chance we could get that back? It isn't very intuitive that setting rotation would fuck up position

**Comment by yuberee** [comment]
That makes sense, although I see a lot of people encountering this in the future.
I'll make sure to go over it in future tutorials as my current ones use the old method.

**Comment by kurozael** [comment]
Don't just yet - nothing is final - I want to find the right balance for all the use cases and for it to feel intuitive.

**Comment by andy013** [comment]
What are the use cases for wanting to set rotation in OnUpdate and position in OnFixedUpdate? Wouldn't setting both in OnFixedUpdate and interpolating achieve the same result?

**Comment by johncosfm** [comment]
Generally games have player movement code (dealing with position) in fixed update, but camera movement has to be in update to avoid it feeling floaty. My project had the position of the camera gameobject set in fixedupdate by the ducking logic and the rotation set in update by the mouse look logic. Now I have 2 gameobjects, one dealing with position set in FixedUpdate and the other dealing with rotation set in update (which works fine but I don't think I would have ever thought to do it without seeing the comments here)
![image](https://github.com/Facepunch/sbox-issues/assets/69829964/0a45d0da-d3fb-48a5-8ed8-88820c76a3a5)
