### ISSUE TITLE
F5 no longer starts the game/scene if GameFrame is undocked and focused

### ISSUE THREAD

**Issue by Ninjadude101** [Facepunch/sbox-issues#5488]
### Describe the bug

If the GameFrame panel is floating / undocked, then pressing F5 no longer toggles the Play/Stop state if it is the focused window. To use F5, you must now focus the main window first.

### To Reproduce

1. Open any project
2. Un-dock the GameFrame window to have it floating
3. Click into the GameFrame window to ensure it is focused
4. Press F5
5. Observe nothing happening

### Expected behavior

Pressing F5 should still toggle the Play/Stop state of the game/scene when the GameFrame window is undocked and focused.

**Comment by DevulTj** [comment]
the issue here is that the play_toggle command no longer does anything - we have some code that's meant to be forwarding function keys to tools but it doesn't seem to function as intended currently.

**Comment by DevulTj** [comment]
Fixed this now.
