### ISSUE TITLE
Clipping plane set too far from camera in VR

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#549]
**Describe the bug**
The clipping plane is set too far from the player's field of view in VR, causing players to be able to see inside of objects and past walls when it's a couple inches away (Maybe 7 inches or so? I'm not great at discerning distance.)

**To Reproduce**

1. Open any map (I personally used Construct)
2. Use the playspace mover in OVR Advanced Settings (https://store.steampowered.com/app/1009850/OVR_Advanced_Settings/) to move around 
3. Get close to any object
4. witness your unintended x-ray vision

**Expected behavior**
Clipping plane should be about where the player's eyes actually are.

**Screenshots**
In the parts where I open the dashboard, I'm putting my controller in pretty much the same spot as the object I'm clipping into, to show what the clipping distance should be.
https://user-images.githubusercontent.com/10066958/127777077-76c2d198-df8d-4370-80dd-881861e93d8f.mp4

**Additional context**
For the playspace mover, I set the binding up like this, so that when I double-click the B button, I can move my left hand around to move in space. Double-clicking my B button on my right hand resets my playspace to its normal offsets. 
![image](https://user-images.githubusercontent.com/10066958/127776267-f7f0cf5a-ae05-4d05-9dd6-fb87ab5b00ad.png)
 You can set these to whatever buttons you like of course, figured I'd put this here so you know how to set it up.

I'm using an HTC Vive in case that helps, I figure that should be the only relevant info that could help.

**Comment by aylaylay** [comment]
The default camera znear is pretty far because we have a large default zfar. We should have a better way to configure this but if you make your own camera you can set it to whatever you want.

**Comment by walllable** [comment]
Got it. In the future once VR support is more robust, it would be nice to have the ability to set separate camera code for desktop and VR so each platform can have its own znear/clipping plane. I figure making a feature request for that right now would be jumping the gun a bit though
