### ISSUE TITLE
menu background

### ISSUE THREAD

**Issue by somewhere-in-the-universe** [Facepunch/sbox-issues#5495]
### Describe the bug

when I play sandboxed: beta game mode for some time and closing it something always happen with the main s&box launcher munu background 

### To Reproduce

1. click on "sandboxed: beta" game mode
2. click "create lobby"
3. play  itfor some seconds
4. close it with esc

### Expected behavior

nothing should happen with the background 

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/146519784/2e87b257-2cf7-43df-9e67-9a3e53a4fa3d

### Additional context

I`m running on windows 11
gpu-nvidia rtx 3060

**Comment by blazebrown87221** [comment]
me too 
![image](https://github.com/Facepunch/sbox-issues/assets/96564866/7934174a-f4f0-44e5-b315-3715287a3247)

**Comment by aylaylay** [comment]
This should be fixed now
