### ISSUE TITLE
Exporting this specific bowling lane model I made with the editor mesh tools hard-crashes my editor and doesn't export anything

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#5496]
### Describe the bug

Exporting this specific bowling lane model I made with the editor mesh tools hard-crashes my editor and doesn't export anything
[crashing_lane.zip](https://github.com/Facepunch/sbox-issues/files/15286088/crashing_lane.zip)

### To Reproduce

Open the prefab, it should show you a bowling lane model.
Try to export it.
Hard crash.

### Expected behavior

I would expect it to export the model and not crash.

**Comment by aylaylay** [comment]
Should be good to go now

nice bowling lane

**Comment by ShadowBrian** [comment]
Lovely, thanks layla
