### ISSUE TITLE
Library with GameResource class causes Local GameResource to no longer be registered by asset system

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#5498]
[gameresource.zip](https://github.com/Facepunch/sbox-issues/files/15286164/gameresource.zip)

If a Library contains a GameResource it seems to cause GameResources inside the game to not appear.

![image](https://github.com/Facepunch/sbox-issues/assets/8184184/201ba631-5c9c-42ed-aa0a-c61078f62de9)
![image](https://github.com/Facepunch/sbox-issues/assets/8184184/879a5d43-ec32-4d8a-a792-001550dacb08)

**Comment by DevulTj** [comment]
Gave this a bit of a look, and it's an annoying one - ResourceLibrary picks it up fine, AssetSystem (tools) doesn't. Doesn't even need an existing resource, just the type defined.

**Comment by garrynewman** [comment]
That doesn't make a ton of sense, unless somewhere it's only ever looking in the last added path. Here's some questions.

1. If you add another library, with more GameResources inside, do they both show?
2. What does the output of the console command "path" (or paths) show?

**Comment by CarsonKompon** [comment]
> That doesn't make a ton of sense, unless somewhere it's only ever looking in the last added path. Here's some questions.
> 
> 1. If you add another library, with more GameResources inside, do they both show?
> 
> 2. What does the output of the console command "path" (or paths) show?

1. Just tested this by creating another lib alongside spritetools with it's own GameResource and both were showing for me.

2. Here's what I'm seeing when I enter "path" 
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/b69620ca-7bb3-4c14-be45-f570c78d1e13)
