### ISSUE TITLE
remake map entities in C#

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#55]
I/O doesn't work when mixing C# and non-C# entities. Some of these entities (ex. trigger_hurt) were already remade, but the I/O wasn't added.

Here's what I'm already using in my maps. They all need to be converted with proper I/O or the maps won't work.

* [ ] logic_relay
* [ ] trigger_push
* [x] trigger_hurt (I can't enable / disable)
* [X] trigger_once
* [x] trigger_multiple
* [ ] point_teleport
* [x] func_physbox
* [x] func_movelinear (I can probably just swap this out for func_door)

**Comment by robotboy655** [comment]
trigger_hurt was fixed, and can now be enabled/disabled.

**Comment by Jac0xb** [comment]
Really need prop_dynamic or some way to animate static models with animations and set those animations programatically.

Here is my attempt to create something like that, for some reason the angle hammer sets is completely ignored and attempting to set any angle/rot is ignored. The animation also either played instantly or not at all.
```
	[Library( "prop_dynamic" )]
	public class PropDynamic : AnimEntity
	{

		private string sequence;
		public new string Sequence {
			set {
				base.Sequence = value;
				sequence = value;
			} get { 
				return sequence; 
			}
		}

		[HammerProp( "DefaultAnim" )]
		public string defaultAnim { get; set; }

		public override void Spawn()
		{
			UsePhysicsCollision = true;
			PhysicsEnabled = false;
			SetupPhysicsFromModel( PhysicsMotionType.Static, false );

			Log.Info( this.WorldAng.ToString() );
			Log.Info( this.WorldRot.ToString() );
			this.Sequence = defaultAnim;
			this.PlaybackRate = 15f;

			base.Spawn();
		}

```

**Comment by Jac0xb** [comment]
Here are also some brush entities I did get working (albiet they are stubbed but can be improved upon).

```
[Library( "func_brush" )]
public partial class FuncBrush : KeyframeEntity
{
	public enum SolidityType { 
		Toggle = 0,
		NeverSolid = 1,
		AlwaysSolid = 2
	}

	private SolidityType solidity;
	[HammerProp( "Solidity" )]
	public SolidityType Solidity { 
		get { return solidity; } 
		set {
			solidity = value;
			this.PhysicsBody.CollisionEnabled = value == SolidityType.AlwaysSolid;
			this.PhysicsBody.Enabled = value == SolidityType.AlwaysSolid;
		}
	}

	public override void Spawn()
	{
		base.Spawn();

		SetupPhysicsFromModel( PhysicsMotionType.Keyframed );
		this.PhysicsBody.MotionEnabled = false;
	}
}
```

```
[Library( "func_physbox" )]
public partial class FuncPhysbox : ModelEntity
{
	[Flags]
	public enum Flags
	{
		SleepAsleep = 4096,
		IgnoreUse = 8192,
		DebrisCollide = 16384,
		MotionDisabled = 32768,
		UseCarryAngles = 131072,
		EnableMotionOnPhyscannon = 262144,
	}

	[HammerProp( "massScale" )]
	public float MassScale { get; set; }

	public override void Spawn()
	{
		base.Spawn();
		this.PhysicsEnabled = this.SpawnFlags.Has( Flags.MotionDisabled );
		SetupPhysicsFromModel( PhysicsMotionType.Keyframed );
	}
}
```

**Comment by robotboy655** [comment]
Implemented func_brush, other things will follow soon, trying to shed these entities from useless legacy stuff while I am at it.

**Comment by kote2345** [comment]
There are also important entities that are needed on C#

point_template
env_entity_maker
logic_timer
logic_case
math_counter

**Comment by robotboy655** [comment]
With the logic entities we really need to take a good look at what we want to keep and what we want to get rid of completely. 

Like why not merge logic_timer and logic_relay? What other things we can do to help mappers with map logic? If you guys have ideas, do not hesitate to make them known.

**Comment by VanderAGSN** [comment]
> Like why not merge logic_timer and logic_relay

Well that's really bad idea in my opinion, because this will confuse experienced mappers. Also leaves entities such as logic_branch / logic_case / logic_compare unchanged, but on C# side will be good beginning in this major migrating to C#

**Comment by Jac0xb** [comment]
> With the logic entities we really need to take a good look at what we want to keep and what we want to get rid of completely.
> 
> Like why not merge logic_timer and logic_relay? What other things we can do to help mappers with map logic? If you guys have ideas, do not hesitate to make them known.

I would prefer a more clean solution [like this], if people want legacy logic entities then they can write C# ones. But a lot of these logic entities are redundant or could be improved. The spaghetti is the half life FGDs are confusing for beginners and simplifying the entities could definitely help newbies more than hurting experienced programmers.

**Comment by JanWerder** [comment]
I've had a similar problem as @gvarados1, but thank to @robotboy655 I found a workaround that works for now.
I'd still like to make the case for implementing logic_relay, since it would solve a lot of use-cases because you can use the relay as a starting point to trigger other entities that are not implemented yet.

**Comment by gabengaGamer** [comment]
Prop_dynamic, very important entity, is a port planned for C# ?

**Comment by DevulTj** [comment]
Prop types should be combined into one, who needs prop_physics, prop_static, prop_dynamic, that's shit

**Comment by gabengaGamer** [comment]
Yes it would be nice "ent_prop"

**Comment by robotboy655** [comment]
prop_static will probably remain, it is not an actual entity in-game, It gets baked into the map.  At least that's how it worked in S1.

**Comment by Adesii** [comment]
> prop_static will probably remain, it is not an actual entity in-game, It gets baked into the map. At least that's how it worked in S1.

i think by default they are still just normal entities ingame, but they can be baked to world through a setting. atleast that is the way it is in HLA. Atleast there is a Bake To World setting, i assume that is what it's doing.
