### ISSUE TITLE
Vulkan Device Lost error when opening S&box project in editor

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5501]
### Describe the bug

I get a "Vulkan Device Lost!" error pop up when I try to open a project in the S&box editor, but I can run the game without any issues.

### To Reproduce

1. Be me
2. Open S&box editor
3. Open a project
4. Notice the scene view is a black square
5. See Vulkan Device Lost error pop up

### Expected behavior

I should be allowed to use the S&box editor 🥺🙏

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/8889285/bd8242ee-8d56-48d6-b3a5-d5c47ad860be)
[Log.log](https://github.com/Facepunch/sbox-issues/files/15288152/Log.log)
[vulkaninfo.txt](https://github.com/Facepunch/sbox-issues/files/15288154/vulkaninfo.txt)

### Additional context

The issue started today. I was able to use the editor a few hours ago. The issue persists after restarting my computer. Issue persists after updating my NVIDIA driver to 552.44.

**Comment by samzanemesis** [comment]
Try now, I was reworking how we handle resizing on editor widgets

**Comment by chrisspieler** [comment]
> Try in a bit on staging branch, I was reworking how we handle resizing on editor widgets

I'm still getting the same error

**Comment by chrisspieler** [comment]
I no longer get the error after the "Revert to NativeRenderingEngine hack" build. It works now.

**Comment by emilsCokies** [comment]
Hi. I have same error, how did you get rid of this mistake? Can you describe the process?
