### ISSUE TITLE
Allow maps from asset.party to be dragged into the Map Instance component

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5505]
### Describe the bug

When dragging a map asset from asset.party into the new map control widget, the map is not changed.

### To Reproduce

1. Go to asset.party
2. Drag the map into the map instance component.

### Expected behavior

The map should change to the drag and drop from asset.party.

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/53f6b101-12a8-4662-93a8-f2e0d2b1e28d
