### ISSUE TITLE
[Input Actions] Support for separate left and right Shift/Ctrl/Alt etc

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5506]
### For?

S&Box

### What can't you do?

Use right shift to do something and use left shift to do something else 

### How would you like it to work?

In the input settings let left and right versions of those keys be differentiated

### What have you tried?

Nothing, attempting is futile 😔

**Comment by DevulTj** [comment]
I don't think this is worth it really

**Comment by Retroeer** [comment]
I don't see how it isn't? Letting the user have access to them as separate keys should be a thing, I mean when have you ever used right shift in a game to run? 
Being able to take those practically useless inputs and make them productive to the game would be really nice, like if I wanted to have right shift swap teams or something

**Comment by DevulTj** [comment]
When have you ever used the right shift / right alt keys in a game to do something that is different to the original? I can't say that I have.

**Comment by Retroeer** [comment]
It is typically common for people to find uses where other people don't, in my game I have a team switch button that I don't want to take up any other key, so I'm using right shift, converting an other wise pointless key into something with use

**Comment by handsomematt** [comment]
We should do this
