### ISSUE TITLE
[Action Graph] Create a labeled output for position, rotation, and transform

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5507]
### For?

S&Box

### What can't you do?

In Action Graph, I would like to be able to have a variable position/rotation of the GameObject the graph is located on.

### How would you like it to work?

I would like it to work like the "this" labeled output, just add another one for the transforms of the object.
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/04dea4fb-871a-4670-86fb-8c88f6735fd7)

### What have you tried?

You could manually set the position as a variable, but I think it would be a good quality-of-life feature. It would help clean up the messiness of some of my graphs.

**Comment by Metapyziks** [comment]
Have you seen the functionality to expand outputs and label them? I think this lets you do what you want, if I understand correctly.

https://github.com/Facepunch/sbox-issues/assets/1110904/ccaaf7b3-a856-457a-95ae-da843ea1105f

You should also be able to just paste this code into your graph to have access to these labelled outputs without setting them up yourself:

```
actiongraph:H4sIAAAAAAAACsWTUWuDMBDH3wv9DpJnHbZ2me65MAalK2u3l1EkauyyWSNJOlZKv/uMUWMzuspgzBe9u9z97345D8OBZYEw/MCME5qDW+vGrl2bHUlKG/gYuin0XQcG49SZXAfQQanrOZMo9WCMAxjFKVBJz4gRFGWYl3kva+Wb00TZ0rKsg3qVgXtZ3bdbe7UvsNQrGC0wE3ugQwvlIlWhtoLsMkfbKmnFUM5TyrY6S4ZFXXOJ8iSin1d35fGH6A3HAjTHjlrmiWM2RQIZIgvKiVBwgDOCtuON3ROZGYpwNiP5e2dO9XTK6JOyThiKV8K7Var4lIt5PVEoENtg3WfVqzbWbf/qoxnD4Bv044sYzoV5IZept2QuQtf30597BcvQlvUZ5rtMSAXJ0Coo70A69uMycv8UzCMV6N/BsKaJH+jIV/2jGgusgS1ZbBIoXe2e1qo6WC6xuXtn9/r79fxWrXuj5+WqeYeD4xf4IFp4+AQAAA==
```
