### ISSUE TITLE
Pressing "Clear" on the map control widget, does not clear the map.

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5508]
### Describe the bug

When pressing "Clear" on the map control widget, does not clear the map and sends a NRE.
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/61cf525e-6a59-402e-aa68-2591d6b10356)
https://github.com/Facepunch/sbox-issues/assets/95300917/2c3acabf-8c8a-477e-a3a1-d48b9931655f

### To Reproduce

1. Use a map in the widget
2. Right-click and press clear.

### Expected behavior

The map should be cleared. When compiling a hammer map, sometimes both of the maps are spawned, so before I would just clear the string.

**Comment by aylaylay** [comment]
Done
