### ISSUE TITLE
[Base Model] AnimSubtract node is broken and spits errors.

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5512]
### Describe the bug

When trying to subtract an anim with the Anim Subtract node, it yields an error and ceases to work when using the base model feature. Convo with eEight: https://discord.com/channels/833983068468936704/882910248317362177/1240108585870954627
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/c98a8a99-6ae1-455d-8a6a-1222e80726a7)

### To Reproduce

1. Add an anim clip.
2. Try to subtract an animation.

### Expected behavior

The animation should be subtracted without any errors.

### Media/Files
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/68b6925e-98d9-4bb6-88cb-7b961c2da625)

**Comment by MaxLebled** [comment]
This seems "normal" to me. In the sense that you're trying to subtract an animation that exists, sure, but which exists only in the compiled model already.

Not being able to reference compiled animations _in the "base model"_ is a logical limitation of how that system works. The anim picker doesn't know about this limitation, though.

Easiest solution would be to grab the animation you're trying to reference from the provided FBX files and include it (but with a different name)
