### ISSUE TITLE
Applying RenderHooks to a ScreenPanel component

### ISSUE THREAD

**Issue by Asphaltian** [Facepunch/sbox-issues#5516]
### For?

S&Box

### What can't you do?

It seems there is currently no way to make RenderHooks for a ScreenPanel that could be used by shaders to render post-processing effects (e.g. a CRT monitor).

### How would you like it to work?

I'd like it to work the same way the base post-processing components handle them, that is by applying RenderHooks to the current target camera.

### What have you tried?

Creating a custom version of the ScreenPanel component was impossible since most interfaces/classes being used were protected.

**Comment by handsomematt** [comment]
Panel.DrawBackground is what you're looking for
