### ISSUE TITLE
Can't open project in code editor from welcome screen

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5519]
### Describe the bug

When trying to open the project from the welcome screen by right clicking the project -> Open in Code Editor, an error message pops up saying there is no code editor found.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/41161483-96c2-4ee2-a496-44a6f6ff650a)

However, once the project is opened in sbox, clicking on Project -> Open Solution works just fine and opens up in VSC.

### To Reproduce

1. Start sbox editor
2. Try opening a project in code editor by right clicking it
3. It does not open

### Expected behavior

Should open

**Comment by DevulTj** [comment]
The way that the code editor API is set up, doesn't really allow for this in the launcher project - so for now I've removed it. We might re-add it in the future, but for now no.

**Comment by Gmod4phun** [comment]
Makes sense. Would be nice to have sometime in the future.
