### ISSUE TITLE
Mesh with "put your text here.vmat" is extremely large in lightmap 512x - 8192x

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#552]
**Describe the bug**

Baking lighting, even for the smallest mesh, throws an error ( 512x - 8192x lightmap)

Error 

![image](https://user-images.githubusercontent.com/54669564/127778700-aaf654a1-c492-4296-aa05-a55952b6f1dc.png)

Map 

![image](https://user-images.githubusercontent.com/54669564/127778726-4fe0a441-8565-41cb-b93c-ef289f1c40a0.png)

Example map

[lightmap_test.txt](https://github.com/Facepunch/sbox-issues/files/6913035/lightmap_test.txt) ( change .txt to .vmap ) 

**To Reproduce**

1. Open lightmap_test.vmap or create own map
2. Try compile it
3. See Mesh with "materials/dev/reflectivity_30.vmat" is extremely large in lightmap

**Additional context**

lighting is weird at baking.

![eGlIS7cnds](https://user-images.githubusercontent.com/54669564/127778852-fea1b2c2-2f68-4f2c-8020-b9e3293b2c6b.png)

**Comment by gabengaGamer** [comment]
![image](https://user-images.githubusercontent.com/54669564/127783960-c25b4b1e-f072-452f-b05d-59ec65ef59c1.png)

( Big Map Example )

**Comment by dj-34** [comment]
^ I can confirm this, same is on my side too

**Comment by wouterpleizier** [comment]
I don't see how these are bugs. If you have a tiny map with only a couple of faces, then obviously each of those faces is going to take up a large percentage of the lightmap atlas. It's just a warning, not an error. In this case you can ignore it.

The in-game screenshot you posted looks like it might have too many baked indexed lights hitting the same surface, which is an inherent restriction to the way lightmaps are stored. You have to work around this by disabling indexing on lights that are less important.

> 
> 
> ![image](https://user-images.githubusercontent.com/54669564/127783960-c25b4b1e-f072-452f-b05d-59ec65ef59c1.png)
> 
> ( Big Map Example )

This is likely also something you'll need to fix on your own. It looks like you're using using a lightmap resolution of 512, which is way too small for big maps. The number of UV charts is simply too large to physically fit within the texture (keep in mind that each chart needs to be at least 1 pixel large and that it needs some padding around it).

**Comment by dj-34** [comment]
I compiled a regular map with 1024 lightmaps, but before i turned off all light indexing except light_environment, but I still get this "warning" (Mesh with material materials/dev/reflectivity_30.vmat is extremely large in lightmap (7.3%), 336x229) and some lighting bugs.
Also my friend reports same issue with his map, he hadn't such warnings before.

![image](https://user-images.githubusercontent.com/20109643/128261669-0b6493ad-d766-4ffb-bb5e-f64088c01746.png)
![image](https://user-images.githubusercontent.com/20109643/128261691-0eefc9da-4ce7-4b1f-a7a2-0de985b54ae7.png)
![image](https://user-images.githubusercontent.com/20109643/128261740-b91f70f2-279f-4b05-9efe-e498992c9da6.png)

**Comment by dj-34** [comment]
New info, for some reason it only happens for materials/dev/reflectivity_30.vmat

**Comment by gabengaGamer** [comment]
> I don't see how these are bugs. If you have a tiny map with only a couple of faces, then obviously each of those faces is going to take up a large percentage of the lightmap atlas. It's just a warning, not an error. In this case you can ignore it.
> 
> The in-game screenshot you posted looks like it might have too many baked indexed lights hitting the same surface, which is an inherent restriction to the way lightmaps are stored. You have to work around this by disabling indexing on lights that are less important.
> 
> > ![image](https://user-images.githubusercontent.com/54669564/127783960-c25b4b1e-f072-452f-b05d-59ec65ef59c1.png)
> > ( Big Map Example )
> 
> This is likely also something you'll need to fix on your own. It looks like you're using using a lightmap resolution of 512, which is way too small for big maps. The number of UV charts is simply too large to physically fit within the texture (keep in mind that each chart needs to be at least 1 pixel large and that it needs some padding around it).

"I don't see how these are bugs. If you have a tiny map with only a couple of faces, then obviously each of those faces is going to take up a large percentage of the lightmap atlas. It's just a warning, not an error. In this case you can ignore it.

The in-game screenshot you posted looks like it might have too many baked indexed lights hitting the same surface, which is an inherent restriction to the way lightmaps are stored. You have to work around this by disabling indexing on lights that are less important." No, this limit was removed, and there were no problems with this in other rooms.

I tried 2k lightmap and got an error https://drive.google.com/file/d/1LZLnStr8rjBvTkgHMIqhtciIoe72YsqL/view?usp=sharing

just check this mdmp
