### ISSUE TITLE
Dynamic cubemaps eat up system memory almost instantly, game becomes unresponsive

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5520]
### Describe the bug

Having an envmap probe and enabling 'Render Dynamically' causes the system memory to geat eaten up almost insantly, and the game becomes unresponsive.

Looks like an issue with mipmap loading
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/bc518682-9925-472d-8394-3ad6f5d986fc)

### To Reproduce

1. Add an Envmap Probe to your scene
2. Enable dynamic rendering

### Expected behavior

No ram eating please :)

**Comment by KingOfTheFBI** [comment]
Can confirm, cannot work in scene currently with this bug if the map has a cubemap in it, will just crash after a minute

**Comment by KingOfTheFBI** [comment]
Looks like laylad pushed a fix this should be good to close
