### ISSUE TITLE
Mesh Editor - Texture Wrapping

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#5525]
https://github.com/Facepunch/sbox-issues/assets/8184184/b2435714-b0e6-4f57-ac33-dc8ee9cae152

Select one face with a material, then alt right click another to apply that material (basically lifts the material and applies it to the hovered face)

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/502fd2b8-9a66-4195-8fd7-6c781a2c8d72

**Comment by aylaylay** [comment]
interesting

**Comment by DoctorGurke** [comment]
Might be important to note that in hammer it will seamlessly wrap uv across faces, like if you did this on the side of a cylinder you'd get continuous uv. Possibly another reason for #5461? 😅

Left unwrapped with alt+click, Right is Grid Align
  
![sbox-dev_b6friIZ0nG](https://github.com/Facepunch/sbox-issues/assets/12602100/04a836bc-724d-47af-b8f0-7c5a4dba952f)
![sbox-dev_0g1cZRLZfE](https://github.com/Facepunch/sbox-issues/assets/12602100/216a7b7a-bf53-4161-942e-24a6c2d8b9a4)

**Comment by aylaylay** [comment]
So this is now working for the most part but doesn't work well in some situations, I have to rework some things to get it right

**Comment by aylaylay** [comment]
Texture wrapping should now work the same as it does in hammer

https://github.com/Facepunch/sbox-issues/assets/1667289/d730795c-cacc-40fb-b9ce-35cb6031086f

**Comment by bakscratch** [comment]
There is also the reverse but allows for more texture application options, WrapTextureToSelection (done with shift-alt-rmb) Texture gets applied to the selected faces based on the hovered face.

https://github.com/Facepunch/sbox-issues/assets/8184184/3ef82773-4f5e-4a59-bbfc-3daa42672d23

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/331393fd-3343-47b4-a64b-fdaa802cbffc

**Comment by bakscratch** [comment]
Awesome Thanks! Think we can close this for now
