### ISSUE TITLE
Asset Party - Library Tab Not Present

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#5529]
### Describe the bug

The tab to view libraries is not present on the home page on asset.party, but is still accessible via selecting the library asset type when viewing a package 

### To Reproduce

1. Go on asset.party

### Expected behavior

It should show up with all the other asset types!!!!

**Comment by Gmod4phun** [comment]
Same goes for Collections

**Comment by ScoutWozniak** [comment]
It exists now, thanks!
