### ISSUE TITLE
Define culling distance in scene through properties

### ISSUE THREAD

**Issue by e1m1j** [Facepunch/sbox-issues#5536]
### For?

S&Box

### What can't you do?

I am unable to directly control the render distance of things. This means if I want to make a big open world I can't control what's rendered and what isn't with simple sliders or values. For example I don't know where to define particle distance draw values, and so on.

### How would you like it to work?

I want it to work by being able to just control the performance and instant optimisation of the scene with simple in-built sliders. I am pretty sure Unity has this feature, at least for models. It would be nice if we had draw distance control for everything we put in a scene.

### What have you tried?

I have thought about this as a component but it should just be default for everything you put in a scene. I don't always want certain things like lights rendered beyond a certain distance. 

Then I can just open a prefab and control how far I want X lights to be seen from, or could just control the whole prefab's draw distance myself. Or even just an object directly.

**Comment by handsomematt** [comment]
You can set a zfar on your camera? Lods are setup in models.
