### ISSUE TITLE
Can't connect to any game

### ISSUE THREAD

**Issue by Joka19** [Facepunch/sbox-issues#5545]
### Describe the bug

When I try to connect to any game, the text at the bottom says: "0mbps / 0%" and it will never load. After sometime it gives me an error, that says something like: failed to download something.

### To Reproduce

1. Go to "Games"
2. Click on any game
3. See error

### Expected behavior

I should load to the game... I guess?

**Comment by handsomematt** [comment]
Use a VPN, Russia blocks a lot of cloudflare sites
