### ISSUE TITLE
Adding a child to an unsaved particle crashes the game

### ISSUE THREAD

**Issue by AdamSai** [Facepunch/sbox-issues#555]
**Describe the bug**
If you try to add a child to a **new** and **unsaved** particle effect, the game crashes

**To Reproduce**

1. Open the particle editor
2. Ctrl + N to create a new particle effect
3. Add child and select one
4. Crash

**Expected behavior**
The child particle is added to the new unsaved particle effect

**Comment by DoctorGurke** [comment]
This was saved a while ago with #876
