### ISSUE TITLE
[Scene Mesh] Separate selected faces into its own mesh

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5551]
### For?

S&Box

### What can't you do?

I'm unable to separate parts of an existing mesh into another mesh.

### How would you like it to work?

Most likely a button in the inspector that would separate selected faces into a new mesh.

### What have you tried?

Deleting old faces from one mesh, creating a new mesh and adding the missing faces manually (tedious).

**Comment by aylaylay** [comment]
You can now extract faces, these faces will be put into a new mesh
