### ISSUE TITLE
Set line renderer to show a tiling texture instead of a gradient

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#5552]
### For?

S&Box

### What can't you do?

Linerenderer's appearance tab only has "color" and "width", the "color" one is just a gradient

### How would you like it to work?

 I'd like for the appearance tab to have a dropdown selection for multiple things, I could approximate a rope if I could rotate the gradient and how it tiles, but ideally there's a texture option I can just plop a tiling material into...

### What have you tried?

I have tried there's nothing I can do right now to make it look like a tiling rope.

**Comment by Tweety-lab** [comment]
Would love this, working with Line Renderers without textures is incredibly annoying.

**Comment by ShadowBrian** [comment]
Yup it cheapens their capabilities a lot for sure.
Thinking back, a proper material would be best since it'd let us use normals and stuff to give extra depth too.

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/9a43d491-8cf5-4ebe-802f-825de08722e9

**Comment by ShadowBrian** [comment]
Perfect thanks!
