### ISSUE TITLE
Creating `GameObject` in `FixedUpdate` doesn't exit the FixedUpdate Interpolation context

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5553]
### Describe the bug

According to [this discord discussion](https://discord.com/channels/833983068468936704/895597253316714497/1242760994531577919) with conna,

Currently creating a `GameObject` in an `OnFixedUpdate()` will not leave the fixed update interpolation context, creating some confusing behavior between the `OnUpdate` and `OnFixedUpdate` behavior

Let's take a look at the reproduction steps

### To Reproduce

1) Download https://github.com/PolSpock/sbox-updatefixedupdate/tree/main/code
2) Look at `NetworkTest.cs`, it's the player component.
By pressing `attack1`, 2 identicals gameobject will be spawned :
- One from `OnUpdate` context
- One from `OnFixedUpdate` context

`Money.cs` is just a simple GameObject with a `MoneyChild` child GameObject who rotating on himself & has `Transform.LocalRotation = Rotation.FromPitch( 90f );` on `OnAwake`

3) Starts a game, look at the log : the transform are different between the 2 gameobjectfs cause the `OnFixedUpdate` aren't leaving his interpolation context even if the GameObject is in his `OnAwake` context

This is confusing.

### Expected behavior

As conna says :

> it makes sense we shouldn't be interpolating values set in OnAwake etc just because we're in a fixed update context, when you are setting transform in OnAwake you'd expect it set immediately regardless

### Media/Files

Reproduction steps in video:

https://github.com/Facepunch/sbox-issues/assets/5229571/6a25f6cb-a391-425f-aa7d-7e182937a602

**Comment by PolSpock** [comment]
Also, note this issue only happens if i'm spawning the `Money.cs` component that will spawn [his `ChildMoney.cs` in his `OnAwake`](https://github.com/PolSpock/sbox-updatefixedupdate/blob/c9ef36561301e179b978632dafcbbfec2bb3040b/code/Money/Money.cs#L37) func.

If I'm [spawning directly `ChildMoney.cs`](https://github.com/PolSpock/sbox-updatefixedupdate/blob/c9ef36561301e179b978632dafcbbfec2bb3040b/code/NetworkTest.cs#L36) the issue seems not to be reproducible

weird

**Comment by kurozael** [comment]
Can you try to reproduce this when the next Steam build finishes @PolSpock ?

**Comment by PolSpock** [comment]
It's good 👌 thx!
