### ISSUE TITLE
Colliders without rigidbodies lerp despite ClearInterpolation being called

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5555]
### Describe the bug

When a GameObject with a box collider has its position changed, the physics of the collider seems to lerp even though the model does not. Even if I call ClearInterpolation on the transform of the GameObject that has the collider, the colliders lerp. Colliders on a GameObject that has a rigidbody component are not affected by this issue.

### To Reproduce

1. Open the attached project
2. Open repro.scene
3. Run the console command `physics_debug_draw 1`
4. See  that some green cubes are flying around because the orange cube's collider lerped through them when it teleported (via RapidTeleporter.cs)
5. See that as the player moves around, the origin shift logic (in BallController.cs) that translates all GameObjects in the scene causes green cubes to be pushed away from the yellow cubes.

### Expected behavior

I don't know whether colliders without a rigidbody are meant to lerp, but in any case, I would expect that after calling ClearInterpolation on the transform of a GameObject, none of its physics shapes would be lerping. 

What this means for the repro scene is that none of the green cubes would be moving around unless the player is pushing on them.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/8889285/d6c76fba-537c-4192-be96-0c7a3943eace

https://github.com/Facepunch/sbox-issues/assets/8889285/ef12644f-6c60-46a4-8208-703cc5fb0700

[origin_shift_collider_lerp.zip](https://github.com/Facepunch/sbox-issues/files/15409335/origin_shift_collider_lerp.zip)

**Comment by aylaylay** [comment]
So the problem here is that these colliders are keyframed, keyframed colliders use a physics shadow which moves the body to the target.

I could potentially automatically reset the physics shadow when it detects interpolation has been cleared but you could argue that gameobject interpolation is unrelated to collider physics shadow.

**Comment by aylaylay** [comment]
Okay I decided it makes sense to teleport the collider (wipe the physics shadow target) on clear interpolation. The reason being that you're usually clearing interpolation to teleport an object, so we also want the collider to teleport too.

**Comment by aylaylay** [comment]
Done


https://github.com/Facepunch/sbox-issues/assets/1667289/c13ff046-c771-449a-badb-e1b24c8eb92f
