### ISSUE TITLE
Vulkan Device Lost

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5557]
### Describe the bug

Getting this error message

### To Reproduce

1. open s&box editor

### Expected behavior

be able to use s&box

### Media/Files

[Log.txt](https://github.com/Facepunch/sbox-issues/files/15414466/Log.txt)

[core_9.nv-gpudmp.json](https://github.com/Facepunch/sbox-issues/files/15414486/core_9.nv-gpudmp.json)

![Screenshot 2024-05-23 152253](https://github.com/Facepunch/sbox-issues/assets/160753124/4fa38897-7a8e-491e-9cbc-b4e9e5c175f3)

### Additional context

Windows 11 up to date
Updated 3080 drivers today to 555.85
Ryzen 7 5700g

**Comment by SwagAccount** [comment]
it is specific to this project for some reason
https://github.com/SwagAccount/the_second_coming_of_k

**Comment by samzanemesis** [comment]
Use the asset.party version of it
https://asset.party/facepunch/goback_material

**Comment by SwagAccount** [comment]
Happening again today after working on the game some more yesterday. It is no longer working at all, giving me the same error even after reinstalling sbox

**Comment by samzanemesis** [comment]
I'm on it

**Comment by crush3000** [comment]
This is also happening to me on my project
[Log.log](https://github.com/Facepunch/sbox-issues/files/15444556/Log.log)
[core_6.nv-gpudmp.json](https://github.com/Facepunch/sbox-issues/files/15444558/core_6.nv-gpudmp.json)
:

**Comment by SwagAccount** [comment]
> This is also happening to me on my project [Log.log](https://github.com/Facepunch/sbox-issues/files/15444556/Log.log) [core_6.nv-gpudmp.json](https://github.com/Facepunch/sbox-issues/files/15444558/core_6.nv-gpudmp.json) I have an RTX 2070 SUPER and a Ryzen 5 3600X
> 
> Project: https://github.com/crush3000/RTS-Base-for-S-box

Yeh, we are both getting
`ERROR!` VK call failed! result = VK_ERROR_DEVICE_LOST`

**Comment by samzanemesis** [comment]
Try now, I reworked how things work but I cannot reproduce the issue myself, hopefully it's sorted

**Comment by crush3000** [comment]
> Try now, I reworked how things work but I cannot reproduce the issue myself, hopefully it's sorted

Working for me now, thanks!
