### ISSUE TITLE
The method or operation is not implemented.

### ISSUE THREAD

**Issue by DoctorWhoFR** [Facepunch/sbox-issues#5560]
### Describe the bug

When using `GameNetworkSystem.CreateLobby();` or just by using the 
![image](https://github.com/Facepunch/sbox-issues/assets/26010905/d159d5e0-23c6-49d4-8a79-5288b0fd4ba8)

Their is an error in the console : `The method or operation is not implemented.`

```c#
The method or operation is not implemented.
System.NotImplementedException: The method or operation is not implemented.
   at Sandbox.Network.SteamLobbySocket.Sandbox.ILobby.get_Id()
   at Sandbox.LobbyManager.<>c__DisplayClass15_0.<EnumerateLobbies>b__2(ILobby x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Sandbox.LobbyManager.EnumerateLobbies(UInt64 id)
   at Sandbox.LobbyManager.OnDataUpdate(UInt64 lobbyid, UInt64 targetid)
   at Managed.SandboxEngine.Exports.Sandbox_LobbyManager_OnDataUpdate(UInt64 lobbyid, UInt64 targetid)
```

It seem that the message is also sent two times.
![image](https://github.com/Facepunch/sbox-issues/assets/26010905/cf5aac8c-b2d4-4488-92e9-9bd8a2e326c7)

### To Reproduce

1 - Just start a new Lobby

### Expected behavior

It seem to work, but i report the issue because it seem new (like today)

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/26010905/ca041043-4948-4ff7-bc3b-2c866a48ebe6

**Comment by Nolankicks** [comment]
Works fine for me. Take a look at some other network code to see what you are doing wrong.

**Comment by DoctorWhoFR** [comment]
wtf so you have updated your game "full stop".

Created a new scene, starting network and you dont have any error ? 

Like i said i have this when using the default button no code dude

**Comment by Nolankicks** [comment]
> wtf so you have updated your game "full stop".
> 
> Created a new scene, starting network and you dont have any error ?
> 
> Like i said i have this when using the default button no code dude

You need to have a network helper. Why are you even starting the server. There is nothing to handle the joining of the server

**Comment by DoctorWhoFR** [comment]
"You **can** use the network helper if you want".

You dont need to.

And even using the Network Helper, that in fact use the same method as the button.

The error also append , please stop doing that, and please try before answering or even send additional information like video to prove it, with that kind of information, we can't in fact say if this is a s&box bug or hardware one.

As i said this error message also appear on new project without any code.

**Comment by DoctorWhoFR** [comment]
https://github.com/Facepunch/sbox-issues/assets/26010905/b4cde979-1ba5-4bb5-ad3d-84fece27b5cb

Also never said that it's not working, just saying that their is a new error message.

**Comment by DoctorWhoFR** [comment]
I have also tested with a friend and he also have the same error msg.

**Comment by Nolankicks** [comment]
Yeah just got the same error, sorry

**Comment by DoctorWhoFR** [comment]
No problem ^^' its seem you are  motivated by s&box, and helping with issue is a good way to help so no prob

**Comment by trundlr** [comment]
Happening for me too
