### ISSUE TITLE
ActionGraph: Show populated Actions in Component view without pressing toggle button

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5563]
### For?

S&Box

### What can't you do?

Currently, you need to press the lightning icon to show action graphs. This is nice because it hides a lot clutter, but it can be confusing for developers who aren't aware that some of the actions are indeed filled out.

### How would you like it to work?

By default, it would be nice to show Actions in the Component property view if the Action is not empty.
![image](https://github.com/Facepunch/sbox-issues/assets/57276947/c614dba8-19bc-4d4e-af3b-e02b8b6b2f7e)

In the above image, OnFire would show in the base Component view below:
![image](https://github.com/Facepunch/sbox-issues/assets/57276947/cc2d3c27-164f-48cb-83e8-25c43f736103)

Empty actions would continue to be omitted as they are currently.

### What have you tried?

I have chatted with multiple developers about this, and they all agree it's confusing to have actions hidden by default when there is behaviour behind it.

**Comment by Nolankicks** [comment]
Maybe add an attribute to make it show up not behind the bolt icon.

**Comment by Metapyziks** [comment]
Something like this is needed, for sure. I'm not a huge fan of each component having all those generic "On Component Update" etc actions, since it feels arbitrary on which component I add a handler to, then I have to hunt for it later.

As a quick compromise, how about we make the lightning icon lit up if there are populated actions?

**Comment by Metapyziks** [comment]
Something like this? 

![Image](https://github.com/Facepunch/sbox-issues/assets/1110904/fee915c1-18c4-4695-bd1f-aab5e151e5b7)

**Comment by Nolankicks** [comment]
> Something like this?
> 
> ![Image](https://private-user-images.githubusercontent.com/1110904/333541891-fee915c1-18c4-4695-bd1f-aab5e151e5b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTA5MzEsIm5iZiI6MTcxNjU1MDYzMSwicGF0aCI6Ii8xMTEwOTA0LzMzMzU0MTg5MS1mZWU5MTVjMS0xOGM0LTQ2OTUtYmQxZi1hYWI1ZTE1MWU1YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjRUMTEzNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzU0M2Y0MTE3ZTUwOTgxOTNmZTNmODg0MzhiMzI3NGM3N2VjNzJhODZkYmIwZjAzOWNkODYwZGNiMTUxZmM1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tv3hqSFgX1bArpXOPpJCbr7_7CwJ3eCh54mqQJxwFRw)

I think he is talking about the actions not showing up behind the bolt icon if they are not empty.

**Comment by trundlr** [comment]
This is clear enough imo - thanks a ton!
