### ISSUE TITLE
Overflow-X only Scrollable with mousewheel not with Leftclick or rightclick

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#5568]
### For?

S&Box

### What can't you do?

.scrolling without pressing left or rightclick , its always on

### How would you like it to work?

that you can only scroll with mousewheel not with right and leftclick 

### What have you tried?

disabling overflox x - , certain other ways but not working

**Comment by xezno** [comment]
You can already do that, see #3491
