### ISSUE TITLE
Expose map object in a way that allows replacement of them

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5570]
### For?

S&Box

### What can't you do?

Currently, you're unable to replace old hammer entities in the scene.

### How would you like it to work?

I would like this to work by being able to select an entity, for example, if you wanted to replace ent_door, you could replace it with your door prefab.

### What have you tried?

There is no way to do this.

**Comment by garrynewman** [comment]
I suspect that this might be already be somewhat possible by deriving your own component from the map loader and overriding the create entity methods.

If not, that's the cleanest path, and it's easy to add.

**Comment by Nolankicks** [comment]
@garrynewman is there a way to see all the methods I need to override?

**Comment by Nolankicks** [comment]
Carson made the same issue and was done
