### ISSUE TITLE
Legacy Light Probes Should Not Render Dynamically

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#5571]
### Describe the bug

Just noticed that disabling the light probes in my map almost triples the framerate. These light probes come from Hammer. If you look at `EnvmapProbe.InitializeFromLegacy` you'll see that it sets Hammer probes to `RenderDynamically = true`, which seems to make it update every frame, making it super laggy. Think a better default for this would be if it was updated only on scene start.

Related to #5494 

### To Reproduce

- Have like 10-20 probes in the map from Hammer
- Start the map
- Disabling the probes triples framerate

### Expected behavior

See above

**Comment by samzanemesis** [comment]
It's more to do with slow shading/tiled culling than the envmapper, CubemapDynamicUpdate.OnEnabled makes sure it only enables once, I want to rewrite a lot of this soon

**Comment by anthonysharpy** [comment]
@samzanemesis FPS doesn't change anymore when disabling ~15 of them, so looks like they are basically free now. Cheers!

**Comment by samzanemesis** [comment]
💋
