### ISSUE TITLE
Models in SkinnedModelRenderer vanishing under certain circumstances

### ISSUE THREAD

**Issue by ItDama** [Facepunch/sbox-issues#5574]
### Describe the bug

Solid models used on a SkinnedModelRenderer tend to vanish under certain circumstances.
When you have SkinnedModeRenderer rendering a citizen or a cloth (gloves, bullet-proof vest, boots) and then you replace it (in the editor or programatically) by a solid model, the model tends to vanish at some camera angles (wether it's from a camera component in game or the scene view perspective) 

### To Reproduce

1. Make a GameObject in the editor and add a SkinnedModelRender
2. Add a citizen model or a cloth model to the renderer
3. Change the model of the renderer to a solid model
4. ! IMPORTANT ! Moove the gameobject away enough from it's original position so you can look at it without seeing it's original position
5. If you look at the model from a perspective where you can't see it's original position it vanishes

### Expected behavior

The model should be rendered at all time

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/145212140/bc7de888-9485-47cd-be0f-4d1c0d1ed2aa

### Additional context

PolSpock helped me issuing you this bug :)
He also managed to reproduce it so i don't think it's a problem related to hardware

**Comment by aylaylay** [comment]
Should be fixed now
