### ISSUE TITLE
Set `Collider.IsTrigger = true` during the first frame is ignoring Collision settings

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5576]
### Describe the bug

Hi,

I just discovered that creating a `Collider` and turning it directly to `IsTrigger = true` will totally ignore Collision rules specified in the Project Settings.
This looks like to only appends when `Collider.IsTrigger` is turned to `true` during the first frame.

Let's jump to the reproduction steps

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging/
2) Create a simple `PhysicBug.cs` component:
```
public class PhysicsBug : Component
{
	public Rigidbody Rigidbody { get; set; }
	public BoxCollider BoxCollider { get; set; }

	protected override async void OnAwake()
	{
		base.OnAwake();

		GameObject.Name = GetType().Name;

		Tags.Add( "solid" );

		BoxCollider ??= Components.GetOrCreate<BoxCollider>();

		Rigidbody ??= Components.GetOrCreate<Rigidbody>();

		/* */

		// TODO Uncomment
		// await GameTask.DelaySeconds( 2f );

		BoxCollider.IsTrigger = true;

	}
	protected override void OnStart()
	{
		base.OnStart();

		var baseModel = Model.Load( "models/citizen/citizen.vmdl" );

		var SkinnedModelRenderer = Components.GetOrCreate<SkinnedModelRenderer>();
		SkinnedModelRenderer.Model = baseModel;
	}

}
```
3) Edit `GameNetworkManager.cs`, add component creation :
```
public async void OnActive( Connection channel )
{
	var goPhysicBug = new GameObject();
	goPhysicBug.Components.Create<PhysicsBug>();

	// [...] SAME
}
```
4) Start `networking.scene`, you will get the PhysicBug fall into darkness even if he has the `solid` tag.
According to the Collision settings of `sbox-scenestaging`, this must collide
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/57ce4eb0-68f8-4be9-901d-69de24cbb934)

5) Edit the `PhysicBug.cs`, uncomment the `await GameTask.DelaySeconds( 2f );`
6) Recreate a game, and see that the correct Collision is applied

### Expected behavior

Collision settings must be applied even if `Collider.IsTrigger` is set to `true` during the first/init frame

### Media/Files

Reproduction steps in video, im also adding a `solid` tag to a sphere of the environment in order to get a solid <> solid collision

https://github.com/Facepunch/sbox-issues/assets/5229571/95a819e2-5395-4a61-a462-06a0e5626e33

**Comment by PolSpock** [comment]
Hi,

It looks like more complicated than i thought, after new tests, i discovered different behaviors :
The rigidbody seems to be more implicated in this physics ignoring than the Collider himself
The `MapInstance` .vmap doesn't act like a traditional `Collider`

Here's a new reproduction step project: https://github.com/PolSpock/sbox-physicsbug
Where collisions are set by default :
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/a3d23676-a839-4f55-8f87-e79dd1b3a718)

So the expected behaviors explained is may be not what i thought.
This physics behavior is very strange...

Another video:

https://github.com/Facepunch/sbox-issues/assets/5229571/37b72ae5-9417-4fa3-bd84-46831bcb72a1

**Comment by aylaylay** [comment]
Is this still happening? I don't understand the repro
