### ISSUE TITLE
When changing the model of skinned renderer during runtime, the animations stop working

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5579]
### Describe the bug

I change the model (that I know works with the anim graph)
The animations stop

### To Reproduce

1. change the skinned renderer model
2. animations no work :(

### Expected behavior

animations working when changing the model

### Media/Files

https://github.com/SwagAccount/the_second_coming_of_k/blob/main/code/NpcmodelAnimationManager.cs - bad code that does the changing of the model. (also the project)

### Additional context

It is not the model I'm turning into because when I turn the model back to the model before it still doesn't work.

I've tried removing the skinned renderer and adding it again with the new model before, but that didn't work.

**Comment by SwagAccount** [comment]
I've tried that, no luck

**Comment by aylaylay** [comment]
Alright I'll look into it

**Comment by aylaylay** [comment]
Please reopen when you have a repro, I don't see any bug here.
