### ISSUE TITLE
Stop All Sounds on a specific Mixer

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5580]
### For?

S&Box

### What can't you do?

You cannot stop all the sounds being played on a specific mixer. You can only stop all sounds being played across all mixers.

### How would you like it to work?

`Sound.StopAll( fade )` should take an optional argument `Sound.StopAll( fade, [mixer] )`

There could also be a `.StopAll( fade )` function on the `Mixer` directly for ease-of-access.

### What have you tried?

Keeping track of sound handles myself but I'm trying to handle it all in a static class (so I can manage music across scene changes) and storing a sound Handle in a static variable doesn't allow the sound to play at all so I'm checking the mixer directly instead (and need this functionality as a result)

**Comment by aylaylay** [comment]
Decided against a mixer arg on Sound.StopAll but I've added Mixer.StopAll
