### ISSUE TITLE
UI Sounds should automatically attempt to be routed through the "UI" Mixer

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5583]
### For?

S&Box

### What can't you do?

It's not that I can't do anything, it's that I want the default behaviour to change.

### How would you like it to work?

Since we got the lovely addition of Mixers, there is now a default Mixer setup that looks something like this:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/7ce36607-a21b-4dba-95a4-7aaaf7540eb0)

But when you play sound events via css:
```css
.btn
{
    &:hover
    {
        sound-in: ui.button.over;
    }
}
```

The sound will play through the "Game" Mixer by default. It would be nice if tried to play through the "UI" Mixer instead (if one exists)

### What have you tried?

I could code the sound events in C# and set their target mixer manually but that is so much more hassle than just being able to keep the UI sounds in the css like I usually do.

**Comment by DevulTj** [comment]
Added this now
