### ISSUE TITLE
Add cylinder trace

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5584]
### For?

S&Box

### What can't you do?

I'm unable to cast a cylinder trace

### How would you like it to work?

SceneTrace.Cylinder
PhysicsTrace.Cylinder etc..

### What have you tried?

Closest we have is Capsule

**Comment by aylaylay** [comment]
The physics engine doesn't have support for cylinders, they're approximated by hull. I agree I've never seen a good reason why physics engines usually don't support this because I don't see much difference in cylinders and capsules mathematically.

I will request support for it but don't expect it anytime soon. Your best bet is to make a cylinder body and trace using that.

`PhysicsBody.AddCylinderShape`

**Comment by MD485** [comment]
> I'm not very knowledgeable with this but what's the difference between a capsule trace (a cylinder with two half spheres) and a cylinder trace (a capsule without the two half spheres)?

It's a physics optimisation, a capsule is treated mathmatically like a line of sphere traces, which allows certain optimisations to be made.

I forget what it is they do exactly, maybe they literally do a bunch of sphere traces close enough to make the effect of impercision minimal, but I imagine it's something else that makes the operation very cheap.

And doing "Check collisions everywhere but here", to exclude the end caps, I believe would be an expensive operation.
That's part of the reason why convex collisions are easily supported but concave collisions have a bunch of issues, there's an algorithm that minimises a lot of the complexity when something is convex.

@aylaylay You could probably just cache the hulls right?
If you cook and store a couple cylinders and swap them out based on size of trace to lower error, then change the scale to adjust for differences in size? Assuming that works it won't have the overhead of cooking a new hull every time.

Might not be worth the effort though.

**Comment by aylaylay** [comment]
This is most likely not going to happen, physics guys hate cylinders and it's not something I'm gonna spend time on adding. Hulls are the way to go if you need a cylinder, sorry.

**Comment by aylaylay** [comment]
Creating a physics body just to trace a cylinder sucks. I've added `Trace.Cylinder` the cylinder is defined by height and radius but you can do a rotated cylinder by using `Trace.Rotated`
