### ISSUE TITLE
Expose `SceneMap.Bounds` to the `MapInstance` component

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5585]
### For?

S&Box

### What can't you do?

I cannot get the bounds of the currently loaded map made via the MapInstance.

### How would you like it to work?

There is `SceneMap.Bounds` which I would like exposed to the `MapInstance` class somehow :)

### What have you tried?

I *could* make my own MapLoader or something but that's wayyyy too overkill for what I'm trying to do. Just want to find the lowest point on a map (geometry-wise, not gameobject-wise)

**Comment by CarsonKompon** [comment]
I found that you can do Scene.PhysicsWorld.Body.GetBounds() but that isn't very intuitive and is also a mouthful.

I imagine this also returns the bounds of ALL physics objects, even if they might be beyond the bounds of the map and I only want to get the bounds of the newly instantiated map.

**Comment by aylaylay** [comment]
Are you wanting the render bounds then?

**Comment by aylaylay** [comment]
Oh I see, scene map already has it, you just want it accessed on the component

**Comment by aylaylay** [comment]
Added MapInstance.Bounds
