### ISSUE TITLE
Cloud.Model Doesn't Seem To Work

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#5586]
### Describe the bug

I think this is more or less the same as https://github.com/Facepunch/sbox-issues/issues/4485

### To Reproduce

Have this code

```
public static Model LoadModel(string path)
{
    Model model;

    if ( path.Contains( "/" ) )
	model = Model.Load( path );
    else
	model = Cloud.Model( path );

    if ( model.Name.Contains("error.vmdl") || model.IsError || model == null)
    {
	model = Cloud.Model( "jodiscontent.duck" );
	Log.Warning( $"failed to load model {path}, creating duck instead..." );
    }

    return model;
}
```

Call it like this

```
LoadModel("facepunch.w_usp");
```

It throws an error

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/791365da-6bb5-437b-9f66-81a75bddd233)

Even though the package does exist

https://asset.party/facepunch/w_usp

Interestingly the duck fallback model does work

### Expected behavior

Loads the model

**Comment by anthonysharpy** [comment]
Sorry if this is not helpful but seems from looking at the code that GetCloudAsset only tries to get it from the cloud if it already exists in cache, which obviously it might not

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/5713a274-c2cb-4865-a3a1-f293dafb06df)

**Comment by handsomematt** [comment]
What should happen is at compile time the references are collected and added to the package.

I wonder since we changed from shipping compiled dlls to code archives if that's broken this.

**Comment by anthonysharpy** [comment]
> What should happen is at compile time the references are collected and added to the package.
> 
> I wonder since we changed from shipping compiled dlls to code archives if that's broken this.

@handsomematt So like does it do some kind of static analysis to figure out which packages you're passing into Cloud.Model? If so I wonder if the problem is that when you pass them in indirectly/dynamically the analyser isn't able to figure out what's going on

**Comment by garrynewman** [comment]
you should never pass them in dynamically, that's definitely gonna not work.

**Comment by handsomematt** [comment]
Missed your non string literal usage in your example and assumed this was a regression oops. Made it error when used wrong

![image](https://github.com/Facepunch/sbox-issues/assets/1388267/0aded396-9159-4002-9f8f-f5f0ee5d0c6a)

**Comment by anthonysharpy** [comment]
@handsomematt Sorry been away for a bit. Makes sense, thanks for looking into it
