### ISSUE TITLE
add css "clip-path" property

### ISSUE THREAD

**Issue by quntherdev** [Facepunch/sbox-issues#5587]
### For?

S&Box

### What can't you do?

I'd like to create a radial menu, with segmented buttons using the "clip-path" property.
More generally, the addition of "clip-path" would allow developers and designers to create really nice user interfaces, which is somewhat limited at the moment.

### How would you like it to work?

Just as in web css, for example:
clip-path: rect(5px 5px 160px 145px round 20%) ;

It should support basic shape functions (rect, polygon...)

### What have you tried?

I could use "mask-image", but that's not really practical:
- you must have an image of your shape ;
- if you add a border to the region, the border will also be applied to the hidden part;
- it's less precise: you can't use % or pixel positions

**Comment by xezno** [comment]
Vector clipping regions are definitely not something I think we should have.
If you want to clip as a circle, use `border-radius: ...;`, or `mask-image: radial-gradient( .... );`
