### ISSUE TITLE
Scene viewport becomes unusable when it's undocked

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5592]
https://github.com/Facepunch/sbox-issues/assets/22372616/7cc872fa-5688-4ea6-8d82-8d349f02f958

If the scene viewport is its own window, you can't use any shortcuts or mouse actions, you can only click on objects.

**Comment by CarsonKompon** [comment]
I swear this wasn't happening a month or so ago. Might have been a recent change that did this.

**Comment by DevulTj** [comment]
This was fixed with the scene viewports branch
