### ISSUE TITLE
Editor breaks when starting the game or pressing F3 to focus game view after compiling shadergraph

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5593]
### Describe the bug

After compiling shadergraph and pressing either F3 to focus the game view or F5 to start the game the editor will look like the following:

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/2a7ad381-4701-4ba2-93ac-c44c4029acf4)

### To Reproduce

1. Create a new shadergraph asset
2. Make a 2D Texture and hook it up to the Albedo
3. Save the shadergraph and wait for the compile to complete
4. Close or minimize the shadergraph window and go back to the main Editor window
5. Press F3 to focus the Game View, OR press F5 to Start Game.
6. Notice the behaviour above, rendering the editor unusable unless you restart
7. Also notice the error that was given in the console:

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/19081f78-ef73-49a1-910b-9af0d06cd642)

### Expected behavior

The editor should continue to function as normal

**Comment by aylaylay** [comment]
Should be fixed now
