### ISSUE TITLE
You can't hide all bodygroups at once on citizen.vmdl

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/sbox-issues#560]
**Describe the bug**
I'm trying to create my custom player models, found out that the best method according wiki is to hide all bodygroups and then parenting your mesh into the skeleton, and that sounds great!
But when attempting to hide all bodygroups, it won't disable none of those, like all those keep active

**To Reproduce**

This works
`SetModel( "models/citizen/citizen.vmdl" );
SetBodyGroup("Head", 1);`

This doesn't work
`
SetModel( "models/citizen/citizen.vmdl" );

SetBodyGroup("Head", 1);
SetBodyGroup("Chest", 1);
SetBodyGroup("Legs", 1);
SetBodyGroup("Hands", 1);
SetBodyGroup("Feet", 1);
`

**Expected behavior**
Being able to hide all meshes for once

**Screenshots**
https://i.imgur.com/jpxqW8z.png

**Additional context**
This seems to work if you disable first few bodygroups and then reload the file with all the other bodygroups, but when you run restart, it won't hide any
Other way to solve this is to use RenderAlpha = 0, but i'm not sure if the mesh it's still being computed

**Comment by aylaylay** [comment]
I have pushed a fix for this, what was happening is when hiding all groups, the mesh mask became zero, so the engine thought it should reset them back to default. If it's fixed for you and there's no other problems, please close the issue.

**Comment by gonzalologorg** [comment]
All fixed!
