### ISSUE TITLE
Panel Labels should support Tabs and Newlines

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5601]
### For?

S&Box

### What can't you do?

If you have a txt file with tabs and newlines, reading it and displaying that string in a label will look like the following:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/b1dbe3aa-3dd6-41b8-bd67-d430af5737a2)

And I can confirm the formatting exists because after reading the file I save the resulting string to a new file and it is formatted properly:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/8391caff-4ed6-431f-a220-33a0b38f3ba6)

### How would you like it to work?

Labels should just inherently support tabs and newlines.

### What have you tried?

I could make a label per-line but that will get incredibly slow incredibly fast for any file with more than 100 lines (which will be most in my experience). It's a temporary workaround for sure but it's one that adds a MASSIVE performance overhead :/

**Comment by CarsonKompon** [comment]
I am baffled because this seems to work in the ui_lab repo..?
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/adfee1f9-1901-4593-a30d-e44fec8d861e)

**Comment by CarsonKompon** [comment]
I did some further testing in the ui_lab project since it has a Text Align section which seems as though newlines are working:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/0061bd29-9a58-487b-8d66-e4677b5da80f)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/6c2bd1a7-bab4-4aa3-b566-fdada7506247)

I started messing with the CSS and noticed that if you remove the `padding: 20px` then suddenly the newlines stop working...
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/01581c57-c5d8-431c-8ff4-ed623bb41b7c)

So I set the padding to a really small number (2px) which revealed to me that newlines NEVER actually worked.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/83711cba-a0cc-4891-820a-e15580375640)

The UI Lab misleads you into believing the `\n` is causing the newline, but it is actually the padding cutting each line perfectly. Returning the CSS to it's original state and then modifying one of the lines to be shorter will reveal the trick being done.
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/b4587342-025b-420c-9a01-30d99169378c)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/45e6fec5-1b30-4473-b3e2-6323442377f9)

This is all to basically confirm my original speculation and say that the ui_lab doesn't actually have this working.

**Comment by Fortune117** [comment]
New lines and tabs are supported with the `white-space: pre;` property from my own tests.

```CSS
  .body
  {
    width: 100%;
    padding: 5px;

    color: white;
    font-size: 18px;
    text-stroke: 2px black;
    text-align: left;
    
    white-space: pre;
  }
 ```

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/b0d7ce42-2bd6-44dc-ae14-d7f30852058f)

**Comment by CarsonKompon** [comment]
> New lines and tabs are supported with the `white-space: pre;` property from my own tests.

Holy shit you are a legend!! Thank you.

This should be documented somewhere if it isn't already and the ui_lab should probably reflected to update that.
