### ISSUE TITLE
Camera Offset Property

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#5604]
### For?

S&Box

### What can't you do?

Currently there is no built in way to offset the position of a camera from the game objects position.  This makes creating things such as camera shake incredibly hacky to create.

### How would you like it to work?

An additional property in the camera component for an offset position.  This should only effect the camera's position and not it's GameObject.  

### What have you tried?

It is possible to get this to work already.  @chrisspieler has an example [here](https://github.com/chrisspieler/sbox-space-game/blob/main/code/Utility/OffsetCombiner.cs).  It would be nice to have this built in however so we can access the offset directly from Scene.Camera.

**Comment by garrynewman** [comment]
Wouldn't you make a child object on the gameobject and put the camera on that?

**Comment by CarsonKompon** [comment]
I don't think this should be an engine feature. I typically do what garry is suggesting and have a parent object which I control the transform of (acting as the camera's global position) and then offset the child camera object to determine shake. Not every game needs this
