### ISSUE TITLE
`Vector2Int` s and `Vector3Int`s do not have a [CustomEditor] ControlWidget

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5606]
### For?

S&Box

### What can't you do?

I have a resource with a Vector2Int property and that property doesn't show in the inspector properly:
![image](https://github.com/Facepunch/sbox-issues/assets/7847372/d50e059c-6103-4cac-afb8-984eeec661a8)

```CS
public class Container
{
	public Vector2Int Size { get; set; }
}
```

### How would you like it to work?

Show work like a vector editor.

### What have you tried?

Can use regular vector2s but then I'm adding some annoying boilerplate for it.

**Comment by badandbest** [comment]
Is it the same for Vector3Ints?

**Comment by chrisspieler** [comment]
My workaround
```csharp
[Property, Hide] public Vector2Int Size { get; set; } = new Vector2Int() { x = 8, y = 5 };
[Property, Title("Size")] public Vector2 SizeFloat
{
	get => new Vector2( Size.x, Size.y );
	set
	{
		Size = new Vector2Int( (int)value.x, (int)value.y );
	}
}
```
