### ISSUE TITLE
After selecting an object, the deselection of the object is blocked for a few seconds.

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5607]
### Describe the bug

After selecting an object, the deselection of the object is blocked for a few seconds.

### To Reproduce

1. Select an object.
2. Try to deselect an object by left-clicking.

### Expected behavior

The object should be selected for deselected.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/874e3eed-4658-4f05-a457-5106340da398

Note: Each time after selecting I am spamming left click.

**Comment by handsomematt** [comment]
Tony fixed in another dupe issue
