### ISSUE TITLE
`GameResource` properties on component can't be assigned subclasses of that `GameResource`.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5609]
### Describe the bug

I have a component with a property like this:
```CS
public class TestComponent : Component
{
	[Property]
	public TestResource Resource { get; set; }
}
```

These are the two resources I want to be able to assign to that property.
```CS
[GameResource("Test Resource", "test", "Wowee")]
public class TestResource : GameResource
{
	public int Wow { get; set; }
}
```

```CS
[GameResource("Inherited Resource", "testsrc", "Wowee")]
public class InheritedTestResource : TestResource
{
	public int Wow2 { get; set; }
}
```

However, when I click on the property to assign a resource it doesn't show anything:

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/f0776ecf-0186-42a7-ac28-b0bbb3c1f0a4)

This used to work fine in the entity system but doesn't seem to work here. I should be able to assign any game resource that inherits from the class in the property.

Additionally, if I remove the `[GameResource]` attribute from the `TestResource` class, it simply throws an error when I try to assign a game resource to the property. This isn't ideal, as in my project I don't want to be assigning the base class to resources, it's simply meant to be a baseline that other resources inherit and expand upon.

### To Reproduce

1. Download the bug repo
2. Try and assign a resource to the property on the test component
3. See that it can't find it

### Expected behavior

Should allow you to assign subclass components.

### Media/Files

[bug_repo.zip](https://github.com/user-attachments/files/15746152/bug_repo.zip)

**Comment by DevulTj** [comment]
![sbox-dev_YJS6hP69DC](https://github.com/Facepunch/sbox-issues/assets/22372616/45d78b61-c604-403f-93b1-9fefe18e8634)

I believe this is what you want

**Comment by Fortune117** [comment]
Perfect, thanks
