### ISSUE TITLE
Shadergraph preview exception

### ISSUE THREAD

**Issue by TiO2EvoLve** [Facepunch/sbox-issues#5610]
### Describe the bug

<img width="952" alt="PixPin_2024-06-08_16-39-25" src="https://github.com/Facepunch/sbox-issues/assets/49835162/746663dc-d9af-4f0d-92e4-70d512dbc8be">
This is strange, isn't it

### To Reproduce

1：Open shadergraph editor
2：Error generation

### Expected behavior

The preview should display its original appearance

**Comment by aylaylay** [comment]
What's the exception?

**Comment by TiO2EvoLve** [comment]
Now it's fixed！
