### ISSUE TITLE
Entering full screen in the editor doesn't work anymore

### ISSUE THREAD

**Issue by Asphaltian** [Facepunch/sbox-issues#5611]
### Describe the bug

When pressing F3 to enter full screen mode, it will throw the following NRE:
`Error calling event 'command editor.fulltoggle' on '[Editor.GameFrame](arg:0)'`

### To Reproduce

1. Press F3
2. Game view will not render, and scene view will not enter full screen

### Expected behavior

The editor viewport should enter full screen mode without any issues.

**Comment by DevulTj** [comment]
Should be good on next build
