### ISSUE TITLE
[Modeldoc] RemoveBoneAndChildren flag doesn't work with LODs

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#5613]
### Describe the bug

This is a pretty big performance issue,
In models, one of the biggest FPS killer is bones, we found you could use the RemoveBoneAndChildren flag on a mesh and use that for LODs to increasingly discard bones according to the LOD, which boosted FPS massively, especially when Max implemented it on the citizen.
![citizen](https://github.com/Facepunch/sbox-issues/assets/86626409/da046ab7-1ec5-4242-8513-44124feaf454)
This no longer works, bones aren't getting culled correctly with LODs.
I've troubleshooted a couple factors:
1.  With multiple RenderMesheFiles, the behavior is it will only cull whatever the first mesh added has, meaning it will not cull at all if it has no "RemoveBoneAndChildren"
2. If there are LODs, even when the first mesh is not rendered, the bones are not culled according to the current LOD, but according to the first mesh's
3. Even when nothing is rendered (LOD is left empty), it will still have the bones of the first mesh.
![nothing](https://github.com/Facepunch/sbox-issues/assets/86626409/43218cef-3c38-4eb1-8b55-44cb550d17e0)
4. The same applies with the other flag, "DiscardSkeleton"

### To Reproduce

1. Create a model with LODs
2. Add the "RemoveBoneAndChildren" flag to one of the latter LOD meshes
3. Test LOD with "Rendering Info" to see the number of bones doesn't change

Alternatively, download the vmdl file below for a quick setup (place in assets folder).

### Expected behavior

The bones should be getting discarded on the fly using the current rendered mesh's flags.

It using only the first mesh for the bones is probably intentional, as all the files contain the armature (culling bones in one file still leaves them in the others), however, this issue isn't as it's recent behavior.

### Media/Files

[models.zip](https://github.com/user-attachments/files/15749629/models.zip)

Example of first mesh not having any culling, LOD1 has RemoveBoneAndChildren, and LOD2 has DiscardSkeleton:

https://github.com/Facepunch/sbox-issues/assets/86626409/99f16652-6e8e-4419-834a-e804bb670074

**Comment by matekdev** [comment]
holy carp

**Comment by aylaylay** [comment]
I've restored it to how it used to compile skeletons. Note that the bone count that's printed has always been the number of bones in the model, not the number of bones in the mesh.

**Comment by Grodbert** [comment]
I see, could've sworn they updated on the fly! That could be a cool feature, but that's for another issue.

I've confirmed it works by comparing 500 models with a weak LOD (remove fingers and penis bones) and then without.

### WITHOUT: _(Peak of 84 FPS)_
![no_lod](https://github.com/user-attachments/assets/fde896fb-5562-4105-b4fd-e65183be8ffd)

### WITH LODs: _(Peak of 112 FPS)_
![lod](https://github.com/user-attachments/assets/2697575b-9f1d-426c-a036-a067b3122d0f)

An increase of 33%! Not too shabby for removing only 4 bones out of 32.

**Comment by aylaylay** [comment]
Fantastic
