### ISSUE TITLE
Add InputAction attribute to Voice Transmitter Component

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5614]
### For?

S&Box

### What can't you do?

Currently, the Voice Transmitter uses a normal string for its push-to-talk input. I would like the string to have the InputAction attribute to show the Input Action popup.
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/2c0f7375-5021-4097-8ab6-b4853324c3b2)

### How would you like it to work?

I would like it to have the input action popup. 
Pasting this code should work (depending on syntax): `[Property, InputAction] public string pushToTalkInput { get; set; }`
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/e121dcee-fb97-4cfe-b5da-32cdc4f72bab)

### What have you tried?

There is no way to achieve this unless creating your own component deriving from the Voice Transmitter.

**Comment by handsomematt** [comment]
hell yeah noland
