### ISSUE TITLE
Add "Clear On Play" option to the Console

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#5615]
Unity has a "Clear On Play" option, that when enabled, clears the console whenever you start Play mode. 

This is useful because it wipes the slate clean without needing to manually click the trashcan each time, and you don't get confused by messages that were left over from the last time you ran the game.

**Comment by DevulTj** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/1b074abd-d19f-449e-ab14-44b0cd7547e6)

Added that here. There's probably a better place to put it eventually.

**Comment by ryleigh** [comment]
It seems like this isn't saved between sessions - the checkbox gets unchecked when restarting s&box

**Comment by ryleigh** [comment]
If I log something in OnAwake, on a component that already exists in the scene, that log won't show up when this setting is enabled.

The console is getting cleared after OnAwake is called, but before OnStart is called.
