### ISSUE TITLE
Inspector: Double-Clicking an Entry in a `List<GameResource>` Property Doesn't Open the "Select Resource" Dialog If The `List<GameResource>` Property Doesn't Have a Setter

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/sbox-issues#5616]
### Describe the bug

In the inspector if you double-click a `GameResource` property or an entry in a `List<GameResource>` property, it displays a "Select Resource" dialog, which is really convenient; however, if the `List<GameResource>` property doesn't have a setter, it doesn't open the dialog.

### To Reproduce

1. Copy-paste example code into a test project
2. Create an empty game object and add a "Test Component" to it
3. Notice that double-clicking the "Resource Property" property and entries in the "Resource List" property opens a "Select Test Resource" dialog
4. Notice that double-clicking the "Resource List Without Setter" property doesn't open a "Select Test Resource" dialog

```csharp
using Sandbox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestNamespace
{
    [GameResource("Test", "test", "Some test resource.")]
    public class TestResource : GameResource
    {
        public string Test { get; set; }
    }

    public class TestComponent : Component
    {
        // double-clicking this in the inspector brings up a "Select Test Resource" dialog
        [Property]
        public TestResource ResourceProperty { get; set; }

        // double-clicking an entry from this in the inspector brings up a "Select Test Resource" dialog
        [Property]
        public List<TestResource> ResourceList { get; set; } = new();

        // double-clicking an entry from this in the inspector does nothing?
        [Property]
        public List<TestResource> ResourceListWithoutSetter { get; } = new();
    }
}
```

### Expected behavior

Double-clicking an entry from a `List<GameResource>` property should open a "Select Resource" dialog even if the `List<GameResource>` property doesn't have a setter.

**Comment by DevulTj** [comment]
For what it's worth, if there's no setter, this makes sense. You can't set the values. 

You shouldn't even be able to add new entries for this property. It's possible if you've added them while the setter was defined, then removed the setter.
