### ISSUE TITLE
All custom components become missing 

### ISSUE THREAD

**Issue by TheOnlyThing** [Facepunch/sbox-issues#5617]
### Describe the bug

the code "Process process = new Process();" seems to break all components
component code will stop updating and on scene refresh or restart of the editor all components become missing
I think this has something to do with the whitelist

### To Reproduce

1 Make new custom component
2 add code: "Process process = new Process();"
3 save

### Expected behavior

components not go missing and requiring a restart and troubleshooting to find out what broke it

### Media/Files

![sbox-dev_s1nkdn9sm1](https://github.com/Facepunch/sbox-issues/assets/90431059/7fe92740-1899-4f44-a4a8-f2bf96924693)
![sbox-dev_gpgFXHcdbv](https://github.com/Facepunch/sbox-issues/assets/90431059/03575638-299d-43ee-b0d9-f22014f10d9e)
![sbox-dev_oZpRgmfzLL](https://github.com/Facepunch/sbox-issues/assets/90431059/5aeaf63e-f390-47e2-adfe-516221f05a62)

**Comment by handsomematt** [comment]
If your code can't compile it's not going to be able to find the components. You can't use Process, why would we let you run random programs on players

**Comment by TheOnlyThing** [comment]
> If your code can't compile it's not going to be able to find the components. You can't use Process, why would we let you run random programs on players

yea I figured more so the issue is its not clear whats happening, im a new coder and I didnt know s&box even had a whitelist, when the compiling first stops working all components still appear enabled, I didn't know what the problem was so I restarted and everything was missing, I then went through all kinds of troubleshooting before finding out the problem.

It was hard to pinpoint when it broke, aswell as pinpoint what the problem specifically was.
