### ISSUE TITLE
Input.GetGlyph for action bound to "ALT" returns "unknown" glyph image

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#5622]
### Describe the bug

When attempting to fetch the input glyph for an action bound to the ALT keycode, the "unknown" glyph image is returned instead. This is due to the SVG file for ALT mistakenly being named "keyboard_alt.svg", while the rest of the files are simply named after their keycode. 

### To Reproduce

1. Bind an action to the ALT keycode.
2. Fetch the glyph texture with ```Input.GetGlyph()```
3. Observe the unknown glyph image being returned.

### Expected behavior

ALT keycode should return the correct glyph:
![image](https://github.com/Facepunch/sbox-issues/assets/43252311/853a84a5-6bbe-480d-8709-351dc9065244)

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/43252311/0949cbe1-be00-4f92-9151-c4e3cfb1fbd7)

**Comment by chrisspieler** [comment]
Can confirm that the workaround to this issue is:
1. Navigate to `%FACEPUNCH_ENGINE%\addons\base\Assets\ui\glyphs\default`
2. Rename `keyboard_alt.svg` to `alt.svg`
