### ISSUE TITLE
Can't change Default Project Location from Launcher

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5628]
### Describe the bug

There is no longer an option to change the default project location from the Launcher (you must open a project first...)

### To Reproduce

1. See that there are no longer settings in the launcher:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/14d19826-97de-49cd-9523-e7703ae95061)

2. Observe that the S&box Editor does in-fact have settings under Edit -> Preferences (once a project is launched)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/47aa9485-bf95-48cf-aacb-90509c4543f7)

### Expected behavior

You should be able to change things like the default project location from the launcher

**Comment by handsomematt** [comment]
We shouldn't have the entire settings menu accessible from the launcher, and it would feel weird to add one for 1 option.

Perhaps a check box when creating a new project to set the default there.
