### ISSUE TITLE
Can we have a naming system for class/struct variables in the inspector?

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5629]
### For?

S&Box

### What can't you do?

If I have a list of a structs or classes it becomes hard to know which is which due to not being able to name them.

### How would you like it to work?

I would like it to work similar to unity's struct/class naming and have it name the class by the first variable string or some attribute to assign a variable to be the title.

For the games I'm working on in s&box I've converted my gun script from unity so here is the mode and bullet type structs as seen in the inspector.
![Screenshot 2024-06-12 180953](https://github.com/Facepunch/sbox-issues/assets/160753124/e8346679-cdfd-48fc-8d1b-fc7a417f8bd8)

![Screenshot 2024-06-12 181118](https://github.com/Facepunch/sbox-issues/assets/160753124/e7e39807-96b9-4774-919f-ec7a6264b126)

### What have you tried?

I have tried adding this to my class/struct
`public string ToString() => modeName;`

no luck

**Comment by DevulTj** [comment]
You can do this already with ToString, like you mention, but it's an override.

Example:
```csharp
public override string ToString()
{
	return $"Outfit, {Items.Count} item(s)";
}
```

**Comment by SwagAccount** [comment]
I also saw your discord message about using the [KeyProperty] attribute, which is exactly what I wanted, thanks.
