### ISSUE TITLE
Vulkan rendering backend

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#563]
**What can't you do?**
Add `-vulkan` to launch options.

**How would you like it to work?**
Adding `-vulkan` will result in using Vulkan rendering backend.

**What have you tried?**
`engine_rendersystem_used = -vulkan`
`engine_rendersystem_init = -vulkan`
Adding `-vulkan` to launch options

**Comment by garrynewman** [comment]
Why?

**Comment by SupinePandora43** [comment]
> Why?

Better proton performance since it will not use dxvk to translate dx11 to vulkan.

**Comment by Rohansi** [comment]
How much better?

**Comment by SupinePandora43** [comment]
> How much better?

DX11 to vk - 2-5 fps
Vulkan - 8-12 fps

(My personal Scp:sl experience)

**Comment by ogniK5377** [comment]
You would need to get a benchmark of half-life alyx instead of a completely different game. The way vulkan is implemented would differ between engines

**Comment by SupinePandora43** [comment]
> You would need to get a benchmark of half-life alyx instead of a completely different game. The way vulkan is implemented would differ between engines

I can't afford hl:a, but there's dota 2 reborn.
In my personal tests on windows:
DX 9 is faster than any other backend.
Vulkan is almost same as dx11.

**Comment by gabengaGamer** [comment]
With the Vulkan , we can get DLSS, RTX, GPU VRAD 3

**Comment by SupinePandora43** [comment]
> With the Vulkan , we can get DLSS, RTX, GPU VRAD 3

Lol no. *Not only with vulkan, but also dx12*
DLSS - DX12/Vulkan
RTX - DX12/Vulkan
Gpu Vrad 3 - something mapping related idk i'm not a mapper.

**Comment by gabengaGamer** [comment]
> > With the Vulkan , we can get DLSS, RTX, GPU VRAD 3
> 
> Lol no. _Not only with vulkan, but also dx12_
> DLSS - DX12/Vulkan
> RTX - DX12/Vulkan
> Gpu Vrad 3 - something mapping related idk i'm not a mapper.


I know

**Comment by KingKrouch** [comment]
> Better proton performance since it will not use dxvk to translate dx11 to vulkan.

There's also the fact that Vulkan and DirectX 12 are generally more multi-threaded, and especially more performant on AMD GPUs compared to DirectX 11 (Due to both GPU architecture and driver reasons). If it's implemented in a decent manner, than it will probably be more performant than DirectX 11. UE4 is one engine where even when I use an NVIDIA GPU, I notice better performance in games that use it by forcing the d3d12 command-line parameter.
