### ISSUE TITLE
[ShaderGraph] Ability to create custom shadergraph nodes in your own Editor Project and or Libraries

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5634]
### For?

S&Box, Other

### What can't you do?

Currently you are unable to create a custom shadergraph node that inherits  the base node or something like Unary nodetype for example. outside of the shadergraph project. which kind of sucks atm.

### How would you like it to work?

Make it so you are able to access Shadergraph stuff from an editor project and or library.

### What have you tried?

Just putting the custom node code inside the shadergraph project.

**Comment by aylaylay** [comment]
You can create your own nodes in tool libraries now

```cs
using Sandbox;

namespace Editor.ShaderGraph.Nodes;

[Title( "My Shader Node" ), Category( "Doggy" )]
public class MyShaderNode : ShaderNode
{
	[Input( typeof( float ) ), Hide, Title( "" )]
	public NodeInput In { get; set; }

	[Output, Hide]
	public NodeResult.Func Out => ( GraphCompiler compiler ) =>
	{
		var result = compiler.ResultOrDefault( In, 0.0f );
		return new NodeResult( result.Components, $"1 - {result}" );
	};
}

```

**Comment by QuackCola** [comment]
Lovely stuff! , seems to work fine on my end :)
