### ISSUE TITLE
Error when deserializing Prefab

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#5635]
### Describe the bug

Due to a new update today, converting prefab to gameobject none of my inspector assigned prefabs work and they are NULL even though they are assigned in the editor.

Strang thing is that the uploaded gamemode still works but when I open it up in the editor its botched.

![image](https://github.com/Facepunch/sbox-issues/assets/4988198/4b57520c-cc89-4b4d-9ba6-e773945fc359)

### Before Play:
![image](https://github.com/Facepunch/sbox-issues/assets/4988198/da7b6173-07f0-496b-9234-f7afc913b3d9)

### After Play:
![image](https://github.com/Facepunch/sbox-issues/assets/4988198/dd896cb5-0bbd-4828-a54a-1be7e6532b5a)
![image](https://github.com/Facepunch/sbox-issues/assets/4988198/cf235ede-d8ed-477a-9f42-be2f9af000ec)

**Comment by garrynewman** [comment]
Can you try to explain a bit better please

**Comment by timmybo5** [comment]
Ill make a recording, one sec

**Comment by timmybo5** [comment]
All code can be found here: https://github.com/timmybo5/simple-weapon-base/blob/master/code/DemoNetworkManager.cs


https://github.com/Facepunch/sbox-issues/assets/4988198/f29b9672-5fb0-41f9-b7d8-9d0a9054ddbd
