### ISSUE TITLE
[REGRESSION] GameObject references become null when the scene is started

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5636]
### Describe the bug

GameObject references become null when the scene is started

### To Reproduce

1. Create a component with a GameObject references.
2. Start the scene.

### Expected behavior

The GameObject should be in the reference 

### Media/Files

Uploading 2024-06-12 14-21-28.mp4…

### Additional context

When updating from one of these 2 commits from @garrynewman broke it:
https://discord.com/channels/833983068468936704/835035328779518023/1250504952879513620
https://discord.com/channels/833983068468936704/835035328779518023/1250511186881937458

**Comment by timmybo5** [comment]
Yes, it's the same issue xD
