### ISSUE TITLE
Game View in Dev Tools doesn't capture inputs when PlayerController component is not working

### ISSUE THREAD

**Issue by Kaydax** [Facepunch/sbox-issues#5637]
### Describe the bug

When in dev tools, clicking play and trying to do any inputs (mouse / keyboard) just don't work when the PlayerController is broken in some way. This is currently happening on testbed as an example.

### To Reproduce

1. Open Dev Tools
2. Open a Project (Testbed)
3. Open a Scene
4. Click play, see inputs don't work

### Expected behavior

Inputs should work. Even if the PlayerController is broken, it should capture inputs at least

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/11893096/aff4faa0-9bc6-4747-beab-6633741a18c6

[Log.log](https://github.com/user-attachments/files/15809639/Log.log)

### Additional context

I'm running Windows 10 LTSC, specs:
Ryzen 7 5800x
NVIDIA GTX 1660 Ti
16GB DDR4 Ram

**Comment by Nolankicks** [comment]
Ermm, why is your repo not working?!?!?!?
https://github.com/Facepunch/sbox-issues/assets/95300917/a46b85a7-4b57-4838-948b-dcf6ae4031b0

**Comment by handsomematt** [comment]
Fix the error

**Comment by Kaydax** [comment]
Well the issue still stands that its inconsistent with input capture. Focus should always be taken when Play is clicked, PlayerController or not

**Comment by Nolankicks** [comment]
Have you ever checked to see if there was a null check in the player if the references were not set?
