### ISSUE TITLE
Props kill you or send you flying when some parts go under map

### ISSUE THREAD

**Issue by ledusa** [Facepunch/sbox-issues#564]
**Describe the bug**
Some props can send you flying or kill you if you rotate them under map

**To Reproduce**

1. Spawn the props i showed in the video 
2. Rotate the props (don't freeze them)
3. Try to walk on them

**Additional context**
https://youtu.be/FCKgeLQUVRE

**Comment by FlorianLeChat** [comment]
I don't know if this is already the case, but some checks should be done internally to avoid having objects spawn under the floor or in a invalid position, a bit [like Garry's Mod](https://github.com/Facepunch/garrysmod/blob/be251723824643351cb88a969818425d1ddf42b3/garrysmod/gamemodes/sandbox/gamemode/commands.lua#L6-L33) (?).

**Comment by aylaylay** [comment]
This happens because when physics objects get stuck, rubikon is applying massive forces to them. This should be fixed in rubikon but also we can be a bit more careful when spawning props
