### ISSUE TITLE
Spotlight with light cookie projects magenta checkerboard on to materials with certain shaders

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5641]
### Describe the bug

When using a spotlight with a light cookie, the light that is cast will appear as a magenta checkboard over the surface of any models that are using the goback_material (Opium) or saunasimple (My Summer Cottage) shaders.

### To Reproduce

1. Open the attached projected
2. Play main.scene
3. See that the magenta checkboard appears over some (but not all) models in the scene
4. Press Space to replace the spotlight in the scene with one that has no light cookie
5. See that everything is lit correctly

### Expected behavior

Light cookies should automatically work with any shader that can be lit by a regular spotlight.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/8889285/50dcdf2f-66dc-4c08-8c75-852663865aed

[light_cookie_checkerboard.zip](https://github.com/user-attachments/files/15824087/light_cookie_checkerboard.zip)

**Comment by handsomematt** [comment]
Shaders need to be recompiled sorry
