### ISSUE TITLE
Opening up groups in sceneeditor 

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#5642]
### For?

S&Box

### What can't you do?

Opening up groups with shift + left click to open all group items in scene editor

### How would you like it to work?

Shift+ leftclick

### What have you tried?

ctrl + leftclick and other things 

### Additional context

https://github.com/Facepunch/sbox-issues/assets/98539318/00be609e-ea6b-4c8f-951a-8ce437545269

**Comment by Nolankicks** [comment]
#4962

**Comment by garrynewman** [comment]
Please explain that to me, what does opening a group mean?

**Comment by MrBrax** [comment]
https://github.com/Facepunch/sbox-issues/assets/1517911/4c68ed4c-5f39-4365-9aee-391a22841b41

open all children i presume

**Comment by EternalDawn1** [comment]
yes open all the children , i mean , like with shift rightclick , cause its annoying to open up one by one 

thanks for the quick answer

**Comment by Nolankicks** [comment]
> yes open all the children , i mean , like with shift rightclick , cause its annoying to open up one by one
> 
> thanks for the quick answer

I just make them child’s of a gameobject as a solution for groups. But if you could make actual groups. It would be cool.

**Comment by EternalDawn1** [comment]
> > yes open all the children , i mean , like with shift rightclick , cause its annoying to open up one by one
> > thanks for the quick answer
> 
> I just make them child’s of a gameobject as a solution for groups. But if you could make actual groups. It would be cool.


yes , to group them , as an example  model -> so expanding all components all one by one is really time consuming or atleast when you got larger groups , to expand everything and de-expand it back , would be fire c:

**Comment by Nolankicks** [comment]
> > > yes open all the children , i mean , like with shift rightclick , cause its annoying to open up one by one
> > > thanks for the quick answer
> > 
> > 
> > I just make them child’s of a gameobject as a solution for groups. But if you could make actual groups. It would be cool.
> 
> yes , to group them , as an example model -> so expanding all components all one by one is really time consuming or atleast when you got larger groups , to expand everything and de-expand it back , would be fire c:

I think what you are looking for is an open all children button like for the child bones.

**Comment by EternalDawn1** [comment]
> > > > yes open all the children , i mean , like with shift rightclick , cause its annoying to open up one by one
> > > > thanks for the quick answer
> > > 
> > > 
> > > I just make them child’s of a gameobject as a solution for groups. But if you could make actual groups. It would be cool.
> > 
> > 
> > yes , to group them , as an example model -> so expanding all components all one by one is really time consuming or atleast when you got larger groups , to expand everything and de-expand it back , would be fire c:
> 
> I think what you are looking for is an open/collapse all children button like for the child bones.

exactly ,c:
