### ISSUE TITLE
Prop.CreateGibs() should return the created Gibs

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5645]
### For?

S&Box

### What can't you do?

I can't do anything with the gibs that are created. There's no way for me to reference the objects in order to do things like network them or change their colour/scale/ect.

### How would you like it to work?

```cs
public void CreateGibs() { ... }
```
should become:
```cs
public List<Gib> CreateGibs() { ... }
```

### What have you tried?

Making my own Prop component... but I really didn't want to have to do that

**Comment by aylaylay** [comment]
I don't see any harm in this so I added it.
