### ISSUE TITLE
Derived classes use the wrong inspector.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5647]
### Describe the bug

I have classes Entity, ModelEntity and AnimatedEntity
```csharp
[Icon( "people" )]
public class Entity : GameObject {}
```
```csharp
[Icon( "view_in_ar" )]
public class ModelEntity : Entity {}
```
```csharp
[Icon( "directions_run" )]
public class AnimatedEntity : ModelEntity {}
```

The Entity class has a custom inspector.
```csharp
[CanEdit( typeof( Entity ) )]
public class EntityInspector : InspectorWidget
{
	public EntityInspector( SerializedObject so ) : base( so )
	{
		Layout = Layout.Column();
		Layout.Alignment = TextFlag.Center;

		// Display icon
		Layout.Add( new IconButton( so.TypeIcon )
		{
			FixedHeight = 352,
			FixedWidth = 352,
			IconSize = 216,
			Background = Theme.Primary,
			Foreground = Theme.White
		} );
		
		Layout.AddStretchCell();
	}
}

```
When I select the Entity in the hierarchy it uses the EntityInspector.

But when I select either the ModelEntity or AnimatedEntity it defaults back to GameObjectInspector, despite them being derived from Entity.

### To Reproduce

1. Create class Entity that derives from GameObject.
2. Give Entity a custom inspector. This will show when you select the Entity in the hierarchy.
3. Derive classes from Entity.
4. The classes will default back to GameObjectInspector, despite being derived from Entity.

In this video I instantiate them all and only the Entity object uses the correct inspector.

https://github.com/Facepunch/sbox-issues/assets/91832803/e29464c7-caa0-4f5e-847f-325758a3cc59

### Expected behavior

The inspector should find the InspectorWidget that most closely matches the type.

In this case that would be the EntityInspector and would look like this:

https://github.com/Facepunch/sbox-issues/assets/91832803/8f3474a5-7484-4f48-8e10-ff806a9de26b

### Media/Files

[My Project.zip](https://github.com/user-attachments/files/15828918/default.Bug.Tests.zip)

**Comment by garrynewman** [comment]
Wtf

**Comment by handsomematt** [comment]
Your use case is insane, but it does seem like a genuine bug
