### ISSUE TITLE
Bone merge to an already bone merged renderer doesn't work

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5657]
### Describe the bug

https://github.com/Facepunch/sbox-issues/assets/160753124/5c8bb068-aab3-4f5e-82a2-f489693494e6

In the video I:
- Show the arms only snapping to merged model when disabled and enabled
- Show disabling and enabling the skinned model renderer every frame creates a clone of the same model
- Quoting out all the code that effects the model

huh?

### Expected behavior

Bone merge merging

### Media/Files

https://github.com/SwagAccount/Todd_Howard_Simulator

### Additional context

help

**Comment by aylaylay** [comment]
I have tested bone merging and it's working fine.

You'll need to make an actual repro (in a blank project) showing what the actual issue is. I don't know what you're doing.

**Comment by SwagAccount** [comment]
that's the thing, I'm doing nothing. It is a simple bone merge with no code effecting the model that's having issues

**Comment by SwagAccount** [comment]
I'll make a repo with just the model then

**Comment by Nolankicks** [comment]
Maybe a repo using one of the sbox official weapons? To make sure it’s not an issue with the model you are using.

**Comment by aylaylay** [comment]
It looks like your problem is that you're bone merging to something that itself is being bone merged, which doesn't make much sense

**Comment by aylaylay** [comment]
This situation should be fixed when the game next updates.

**Comment by SwagAccount** [comment]
thanks laylad, sorry for being unresponsive it was 6am when I posted this
