### ISSUE TITLE
`Component.IsValid()` returns true after calling `Component.Destroy()`

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5659]
### Describe the bug

After calling `Destroy()` on a Component, any references to that component will return `true` when calling `Component.IsValid()`.

### To Reproduce

1. Have a property with a reference to your component that you're about to destroy
2. Destroy the component
3. Call IsValid on the reference

### Expected behavior

It shouldn't be valid

**Comment by aylaylay** [comment]
IsValid should now return false after destroying the component, obviously it'll still be valid until after OnDestroy has finished.
