### ISSUE TITLE
Bone Merge on to Bone Merged model a frame behind

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5661]
### Describe the bug

I had an issue yesterday where bone merge wouldn't work on bone merge, luckily, laylad fixed it. However, whilst somewhat working, it is still a frame behind.

The reason I need to bone merge to a bone merge is due to me bone merging the players customized arms (skin colour) to the gun and then bone merging the players apparel, armour/clothes, to the customized arms.

https://github.com/Facepunch/sbox-issues/assets/160753124/1a456b6d-270f-4321-9a08-41872f4f9d42

### To Reproduce

1. Bone merge a model to another model
2. Bone merge another model to the previously bone merged model
3. Have a stroke after reading steps 1 & 2

### Expected behavior

All bone merges happening before render pass.

**Comment by aylaylay** [comment]
This should work now

https://github.com/Facepunch/sbox-issues/assets/1667289/fd570743-a9da-4a73-b7df-297817f6fdcf
