### ISSUE TITLE
Networking falls apart  as non-host when there's 3 or more clients in a game

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5662]
I can see people moving around as the host.

People can see me moving around as the host.

Other players cannot see other players moving, when they're not the host.

Test case:

- **Launch HC1** with 3 players.
- Observe that the non-host players won't be able to see eachother moving around.

https://github.com/Facepunch/sbox-issues/assets/22372616/aef4f37a-4f74-46d1-a1a5-7ccd094857ff

**Comment by CarsonKompon** [comment]
Can confirm this happens in the game I'm currently working on. I've had some people join my lobby and tell me they can't see me moving when it's just me and them. Definitely much more common when there's 3+ people though for sure (where only one person has the issue typically)

**Comment by handsomematt** [comment]
resolved
