### ISSUE TITLE
`CSceneLightObject was null when calling SetLightCookie` when disabling Light GameObject with Cookie

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5666]
### Describe the bug

I have a flashlight that I can turn on and off with the F key. This light GameObject has a light cookie, and looks like the following:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/b87a5e8a-c1ba-450d-b853-875811e7b42a)

Enabling the GameObject gives no issues, but disabling it after it's been enabled will yield the following error:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/d63a84f9-8c13-4cf1-81ea-4dfea89462d0)

### To Reproduce

1. Create a GameObject similar to the one above (with the same light cookie or similar)
2. Create a script that allows you to toggle `GameObject.Enabled` on the light gameobject
3. Notice the error when disabling the GameObject

### Expected behavior

There should be no error.

**Comment by handsomematt** [comment]
You are probably out of date, I fixed this before

**Comment by CarsonKompon** [comment]
Oops, you're so right. Thanks :P
