### ISSUE TITLE
Better way to load custom MapInstance Entities without making own MapInstance Component.

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5667]
### For?

S&Box

### What can't you do?

I cannot easily hook into the creation process of a MapInstance and add my own entity parsing unless I fork my own MapInstance component from dotpeeking MapInstance.cs in order to use my own MapLoader.

### How would you like it to work?

Ideally you should be able to specify the MapLoader that is used by the MapInstance component. That way I can make a class that extends SceneMapLoader with the necessary overrides added and simply specify something like:
```cs
mapInstance.MapLoader = new CustomMapLoader();
```

### What have you tried?

Forking the MapInstance component. But I don't think that should be necessary if you just want to implement a few entity -> prefab conversions such as health kits, ammo packs, jump pads, ect.

**Comment by aylaylay** [comment]
I have added MapInstance.OnCreateObject so you can override MapInstance and add support for custom map objects
