### ISSUE TITLE
maps use incorrect sun angles.

### ISSUE THREAD

**Issue by Hamburger12343** [Facepunch/sbox-issues#5668]
### Describe the bug

the sun angles appear to have defaulted to an incorrect value, resulting in weird looking lighting.

### To Reproduce

simply load a map. I have only tested this on construct.

### Expected behavior

the shadows should be calculated using correct sun angles

### Media/Files

![Untitled drawing (4)](https://github.com/Facepunch/sbox-issues/assets/156494582/49eaed51-fa87-4945-a54e-0972efc2f443)

### Additional context

this does not appear to be affected by hardware.

**Comment by aylaylay** [comment]
Fixed - I fucked it
