### ISSUE TITLE
Joint Components don't work on ModelPhysics Ragdolls with Create Bone Objects

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5669]
### Describe the bug

I'm creating a Weld Tool for my Sandbox game and I'm using the FixedJoint component (which is working great) but it doesnt work at all when placing the FixedJoint on a bone object created by a SkinnedModelRenderer moved by a ModelPhysics component.

I've tried adding the `GameObjectFlags.ProceduralBone` flag to both objects as well as just the jointed object or just the object targeted by the joint (and none seen to work).

### To Reproduce

1. Drag in two `citizen.vmdl` models into your scene so they are placed as Prop ragdolls
2. Break the Prop components on both into their individual components (SkinnedModelRenderer and ModelPhysics)
3. Create Bone Objects on both SkinnedModelRenderers
4. Place a FixedJoint on any of the bones on citizen 1 and set it to target a bone on citizen 2
5. Notice that they are not jointed together

### Expected behavior

The joints should work as expected

**Comment by aylaylay** [comment]
Done

https://github.com/Facepunch/sbox-issues/assets/1667289/833d801a-b0d1-4ecc-ae73-c83c00e57a8e

**Comment by CarsonKompon** [comment]
I'm noticing some issues with this. I took some videos of all the weird behaviours I'm noticing...

1. Welding Rigidbody to Bone and then unfreezing both causes both to fly and then causes game to freeze before crashing:

https://github.com/Facepunch/sbox-issues/assets/5159369/5dc9ff87-4b91-4f12-960c-4350468cdb3d

2. Welding Bone to Rigidbody and then unfreezing both causes both to fly without game crashing:

https://github.com/Facepunch/sbox-issues/assets/5159369/44d2031b-b647-4371-b050-9bf4974471fa

3. Welding Bone to Bone doesn't work sometimes but will not cause both to fly. You can see that the first weld I make does not do anything while the second weld does. I show the created components on both bone object at the end of the video to show that the first joint was in-fact created but not doing anything:


https://github.com/Facepunch/sbox-issues/assets/5159369/9624a3ee-a9fe-4194-9528-75e6fa21940d

**Comment by aylaylay** [comment]
Not all bones are physics bones, I've made it so it will go up to parents to find the closest physics bone.

For the unfreezing you're going to have to give more infomation on this. How exactly are you unfreezing?

**Comment by CarsonKompon** [comment]
> Not all bones are physics bones, I've made it so it will go up to parents to find the closest physics bone.
> 
> For the unfreezing you're going to have to give more infomation on this. How exactly are you unfreezing?

I'm not home at the moment but I believe I'm just setting the physicsbody to Dynamic. I think I also set DontSleep to true or similar if that matters. Can give you a proper code example/repro in 3-4 hours when I'm home

**Comment by CarsonKompon** [comment]
Alright it took me a good amount of time to figure it out but I finally got a repro. Here's a video of the repro in action along with the project itself:

https://github.com/Facepunch/sbox-issues/assets/5159369/ba17adfb-c323-4f4c-90c0-e63af923ce1e

REPRO PROJECT: [joint_repro.zip](https://github.com/user-attachments/files/15893437/joint_repro.zip)

**Comment by aylaylay** [comment]
Thank u

**Comment by aylaylay** [comment]
Should be good now. I've also added frequency and damping properties to FixedJoint

https://github.com/Facepunch/sbox-issues/assets/1667289/e432751f-b0bb-476c-b4cd-f412b5bf1d63

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/a559d23c-7ea0-479b-8231-b7e10830704e

**Comment by CarsonKompon** [comment]
Seems like everything is working great now. Thanks for all your help!
