### ISSUE TITLE
`System.ArgumentOutOfRangeException: Position is NaN (Parameter 'value')` on ModelPhysics and RigidBodies 

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5671]
### Describe the bug

When joining some maps I get errors on ModelPhysics and RigidBodies. I'm not doing anything to them.

### To Reproduce

1. Load Flatgrass
2. Get the NREs

### Expected behavior

There should be no errors.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/3e619cd8-0f66-4e68-91c5-05eb9ae9ea3d

**Comment by aylaylay** [comment]
Fixed
