### ISSUE TITLE
MapInstance component leave previous map behind in editor

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5672]
### Describe the bug

Components Deriving from MapInstance leaves the previous map behind

### To Reproduce

1. Create a MapInstance Component
2. Change maps multiple times.
3. See the previous map.

### Expected behavior

No map should be left behind. 

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/1c3dc660-1e12-4808-95ab-62a9b1869d96

**Comment by aylaylay** [comment]
Fixed
