### ISSUE TITLE
Can't change a Scene Viewport (eg. from 3D to 2D Top-Down)

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5675]
### For?

S&Box

### What can't you do?

I want to occasionally change my one Scene Viewport from 3D to 2D Side-View or 2D Top-Down but I can't do it without creating a split and dragging the views I don't want away.

### How would you like it to work?

When you click on the scene view button you should get options to set that selected view:

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/36f49e42-099a-4f62-9096-27be5417c95e)

Here's how it is in Hammer:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/f7309b5f-7bc5-4a74-90fa-0a896f719ffd)

### What have you tried?

The best you can do is the following which is really annoying/cumbersome:

https://github.com/Facepunch/sbox-issues/assets/5159369/18fd33d3-7f72-4474-9516-402f7871827b

**Comment by solwllms** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/7689429/27de993f-54f2-47e9-90c0-3de9cdf0f2af)
Added in the viewport settings
