### ISSUE TITLE
Add all Layout Options from Hammer to Scene Viewports

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5676]
### For?

S&Box

### What can't you do?

You can't change your Scene Viewport to have the 3 view with the primary view wherever you'd like. Only left/right.

### How would you like it to work?

We should have the same options that hammer has to reach parity:

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/401d7c1f-47eb-4630-b9f1-cffdfaf854b4)

### What have you tried?

These are the only options we have:

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/1b50b327-cb3a-4953-9812-39c37a198aaa)

### Additional context

Also the "Two (Horizontal)" layout icon shows 3 instead of 2.....

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/6f8f44b4-2256-4c1b-9505-94103be8c077)

**Comment by solwllms** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/7689429/ce9d70d6-01c1-4f10-bdc2-cb3ce6808413)
Added Three (Top) and Three (Bottom) layouts, and also now using proper representative icons for all presets
