### ISSUE TITLE
Changing from 2D Side View to 3D leaves the Grid in 2D

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5677]
### Describe the bug

Switching from the 2D Side-View to 3D will leave the grid on it's side. This is honestly nice to have but should be a specific feature instead of an accidental byproduct of switching views:

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/142bace1-88f8-4ea3-bc23-9c90a58c9671)

### To Reproduce

1. Change the View from 3D to any of the 2D Views
2. Change back to 3D
3. Notice that the grid remains in the same position it was in the previous view.

https://github.com/Facepunch/sbox-issues/assets/5159369/461617ac-d03c-4c86-94f3-648832b15e71

### Expected behavior

There should just be an option for which axis the grid is on when in the 3D View added here:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/1ca91a1f-dcc4-4e05-83a7-e66a8d7f8c43)

**Comment by solwllms** [comment]
Cheers - not super useful to have the different grid planes in 3d view at the moment tho imo, so for now just setting it to the X/Y plane when entering 3d view (like it was before) to keep things simple.

Definitely something to consider for the future tho.
