### ISSUE TITLE
Allow overriding Base Editor Library

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#5679]
### For?

S&Box

### What can't you do?

If one needs to edit base editor tools, for one reason or another, they are able to do so by editing the contents of Base Editor Library, or the Editor folder of it specifically. However, that would mean that any change is applied globally to everything, instead of per project, which would allow you to do project specific changes that are only required on that and nowhere else (also any update would wipe your changes clean, without any way to get them back)

You _can_ put the contents of that Editor folder into your project's `Editor` folder, and after fixing some missing directives or assembly references (idk whats that about), it works.
Unfortunately, it does not recognize this is the same portion from the Base Editor Library, which means now you have two of whatever it is that has been taken.
![2024 06 18_21 36 56](https://github.com/Facepunch/sbox-issues/assets/25704828/b29d622e-e987-47ff-92d7-d9ee389e7975)

Funny, but very uncool.

### How would you like it to work?

I brained two options, but it is possible there are other solutions that are unknown to me.

1. Somehow magic into existence overriding of the base library, so that the project's editor code "takes priority" once it exists (check folder paths and file names or something).

2. Supply Base Editor Library folder with the user projects, so that it's just there already, ready to be edited per project. (Perhaps this means it still needs the overriding from option 1, I am not sure)

### What have you tried?

Doing the thing from the first section with the per-project `Editor` folder, getting a double toolbar.

**Comment by garrynewman** [comment]
We won't be doing this. What do you want to do, specifically?

**Comment by MD485** [comment]
I like the idea of added extensibility in the editor to do what you like, since a lot of it is written in C# we could have that flexibility.

But yeah I suspected Garry's response, being technically able to do something and committing to supporting that functionality long term unfortunately aren't equivalent.

**Comment by rzkid** [comment]
It is very unfortunate this would not be done. Seems very misleading that the base library is a public open thing (as opposed to some components, shaders, etc, which are not and therefore you wouldn't try editing it) and it is completely not useful for literally anything, and it would seem something like this would be it's primary use were this an actual thing; I guess not.

I saw Base Library, noticed it has literally everything, and thought "Wow! I can move this small thing without making feature request and getting yelled at because the editor is not broken enough yet to justify moving a thing for all users ever, all by myself!" Turns out that no, I can't even do _that_, even though the code is right there.

If you want even more specific, I just was curious if I could reorder some buttons (only within specific project, not whole sbox wide). Curiosity burned alive and dumped at the bottom of the ocean.

**Comment by Nolankicks** [comment]
@rzkid your able to make derived components from base lib components to override those methods.
