### ISSUE TITLE
Hotloading not working (Visual Studio)

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#5683]
### Describe the bug

So I primarily use Visual Studio, so does John, I'm not sure if this effects other editors.
The bug is hotloading is simply not triggered on file changes.

@Metapyziks my beloved, I can't seem to @ you directly.

### To Reproduce

Right now I have turned off all startup programs, to stop issues theoretically from occuring because of applications like Everything or DropBox tying up file handles.

I'm opening sbox-dev.exe from the file explorer so that it runs in administrator mode to avoid issues with permissions.

I've created a new folder in the root of C drive, to avoid issues from path length being too long.

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/cd56ac73-b67f-4821-b79e-faefc93e56eb)

Initial load of the scene is fine:

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/21ce90a7-ab43-426e-9e34-b0d1fb534554)

I create an empty gameobject and put a new script on it using the editor:

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/4dd7e4a4-fe14-42f8-b941-d0e9c95d77d7)

This is also fine:

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/eb8d2034-8afe-4a3f-b1a8-5571a78f9dee)

I change the class:

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/25b44075-8508-40d5-b13e-77d6867bdf13)
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/bb5a50de-d41a-4f88-884b-38347b206d90)

No response:
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/53118367-1e22-4ad9-bef4-f697ac733627)

Update hotreload_fast to 0:

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/461b4c2b-e45f-4880-8ec9-5f3e5351ae90)

Try again:

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/31124d96-0da6-4568-a49d-50f81e853417)
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/31077b88-d37a-4e3b-a3f2-c334ccaa01b4)
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/0e6e1047-592b-46d2-ab6c-1f9572495aa6)

Nothing:
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/355321fd-7d2a-446b-a1c9-0c89b9e4e3c0)

If I make some "more meaningful" change than adding more fields and new operations however, like adding a new using directive:
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/2b5c01f9-f441-44a4-a550-89d1e3094d22)
(This is supposed to say `using System;` and `Random.Shared ...`, please don't make me take more screenshots.)

Or adding a new method:
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/f77523fe-a6eb-428a-b426-c87b3f357f5b)
It can work.

The issue now however is that:
1. It only works the first time, if you remove the using directive/method, save, then add them again, it won't hot reload any of those saves, and given that hotreload_fast is at 0 this shouldn't be necessary for it to work.
2. This also can permanently break hotreloading, seemingly by causing issues with the dependencies.

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/894872d1-7269-4c18-b73f-110fc5b2e9e5)
In all my broken projects my depedencies look like this, they don't seem to hotload from any changes made in visual studio regardless if it's a new class, new file, whatever.

Implying some configuration issue has gone wrong with the base project causing hotreloading to be on the fritz.

When editing source files from an application like notepad it is still 100% reliable.
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/d3e8b8ac-6f26-4cdd-a21b-25665ee8ad64)
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/f1dc8350-0030-4ad6-bc57-6bbe52fca88a)

This seems to be primarily a Visual Studio issue.

### Expected behavior

Hotreload. >:(

### Additional context

I don't know where I'd go in Visual Studio to verify this but I'm pretty sure I have installed the latest .Net like I'm supposed to be. .Net 8 I believe?

So I don't believe it's caused by compiler issues related to that.

**Comment by handsomematt** [comment]
So. It works with notepad and not Visual Studio?

I guess Visual Studio saves to a new file and renames it and that's not being detected by our FileWatchers.

It's odd it works for most people though.

**Comment by MD485** [comment]
Apparently.

I believe something internally is stopping Visual Studio from "fully compiling" it, due to the dependancy block, but I don't know why that would stop the file watchers, maybe it's tying up the dll or csproj or something and preventing the process from happening.

The notepad file I open up is the recently saved file from visual studio, in theory either way the last modified date should be getting updated, it's hard for me to imagine why the filewatchers would see alterations made by the different programs uniquely.
If VS is making a new file that the filewatchers aren't tracking, then the notepad changes shouldn't work either.

VS or notepad, the accessed/modified dates both change and the created doesn't.
I don't think VS is making a new temp file and replacing the old, but hopefully ziks can find some more insight into this.

**Comment by Metapyziks** [comment]
Which drive is the game installed on, is it the same as your project? Maybe this is #262 again.

**Comment by Metapyziks** [comment]
Also could you please send an example .csproj that has this warning in its dependencies:

![341032967-894872d1-7269-4c18-b73f-110fc5b2e9e5](https://github.com/Facepunch/sbox-issues/assets/1110904/e8fbcf61-41da-4f48-9dce-0b3066aaeba0)

**Comment by Metapyziks** [comment]
I've added some trace logging in the file watcher, when you get the time could you enable this:

![image](https://github.com/Facepunch/sbox-issues/assets/1110904/ae3a7422-bd14-4a8d-b384-fe9231275f21)

Then a few times in a row, until you see examples of both successful compiles and the bug you reported:

1. Type `echo TEST` in the console
2. Make a change in your code and save it
4. If you saw a compilation popup, type `echo PASS`, otherwise type `echo FAIL` in the console

Then please send me your log.

**Comment by MD485** [comment]
Sbox, steam, visual studio and all my sbox projects are on my C drive, which is an SSD.

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>hotreloading</AssemblyName>
		<PackageId>hotreloading</PackageId>
		<LangVersion>11</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX;ADDON;DEBUG</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<DefaultItemExcludes>$(DefaultItemExcludes);**\editor\**\*;**\unittest\**\*</DefaultItemExcludes>

	</PropertyGroup>

	<ItemGroup>
		
		<None Update="**\*.cs.scss" DependentUpon="%(Filename)" />
		<Compile Update="**\*.razor.cs" DependentUpon="%(Filename)" />
		<None Update="**\*.razor.scss" DependentUpon="%(Filename)" />

	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="**/*.razor" Exclude="**\editor\**\*;**\unittest\**\*" />
	</ItemGroup>



	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
	</ItemGroup>

  <PropertyGroup>
	<OutputPath>..\..\..\Program Files (x86)\Steam\steamapps\common\sbox/.vs/output/</OutputPath>
	<DocumentationFile>..\..\..\Program Files (x86)\Steam\steamapps\common\sbox/.vs/output/hotreloading.xml</DocumentationFile>
	<RootNamespace>Sandbox</RootNamespace>
	<Nullable>disable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Analyzer Include="..\..\..\Program Files (x86)\Steam\steamapps\common\sbox\bin\managed\Sandbox.Generator.dll"/>
		<Reference Include="..\..\..\Program Files (x86)\Steam\steamapps\common\sbox\bin\managed/Sandbox.System.dll" />
		<Reference Include="..\..\..\Program Files (x86)\Steam\steamapps\common\sbox\bin\managed/Sandbox.Engine.dll" />
		<Reference Include="..\..\..\Program Files (x86)\Steam\steamapps\common\sbox\bin\managed/Sandbox.Filesystem.dll" />
		<Reference Include="..\..\..\Program Files (x86)\Steam\steamapps\common\sbox\bin\managed/Sandbox.Game.dll" />
		<Reference Include="..\..\..\Program Files (x86)\Steam\steamapps\common\sbox\bin\managed/Sandbox.Reflection.dll" />
	</ItemGroup>

  <ItemGroup>
		<ProjectReference Include="C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\base\Code\Base Library.csproj" />

  </ItemGroup>

</Project>
```

Is my csproj.
When I changed `<TargetFramework>net7.0</TargetFramework>` to target `net8.0` it began sporadically working for a bit, but after hotloading for a bit and restarting it had stopped working, I checked the csproj again and net7.0 was the target framework again.
[Log.log](https://github.com/user-attachments/files/15904010/Log.log)
Here's the log, unfortunately I restarted in between tests so the part you're looking for is near the end.
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/2f5dc7ce-33cb-4452-a656-0e51c408c4df)
Before I started testing I checked whether hotreload_fast was on and turned it off.
The first fail the code change was appending to a string before it's used in a log.

**Comment by MD485** [comment]
I tried my net8.0 trick again but it doesn't seem to be working anymore.
[Log.log](https://github.com/user-attachments/files/15904421/Log.log)
Here's another log, I made sure to do everything in Visual Studio, it seems new file creation is the only thing that works.

![image](https://github.com/Facepunch/sbox-issues/assets/36082767/c270b235-fed7-402d-add8-23a0ab2d0893)
.Net is also correctly installed if you wanted to verify.

**Comment by Metapyziks** [comment]
Thanks for your help so far!

> Is my csproj.

I can reproduce the project reference warnings by using absolute paths instead of relative ones, but I'm guessing this is unrelated to the hotreload bug. We're not using VS / MSBuild for compilation, so VS is just a fancy text editor.

> When I changed <TargetFramework>net7.0</TargetFramework> to target net8.0 it began sporadically working for a bit, but after hotloading for a bit and restarting it had stopped working, I checked the csproj again and net7.0 was the target framework again.

S&box only targets .NET 7 at the moment, and it'll ignore the .csproj when compiling anyway. I'm guessing the temporary relief you were getting from switching it to .NET 8 was coincidental, or at least not directly related to .NET 8.

> Here's the log, unfortunately I restarted in between tests so the part you're looking for is near the end.

Perfect, looks like that confirms the FileSystemWatcher iteself isn't picking up all changes. I'm only seeing Created and Changed events, no renaming. I'll investigate some more and get back to you soon.

> Here's another log, I made sure to do everything in Visual Studio, it seems new file creation is the only thing that works.

> Installing the latest .Net 8 didn't seem to do anything, a code error did seem to trigger hotloading properly when testing the new install though:

Looks like Trace Logging got disabled for these ones sadly.

**Comment by MrBrax** [comment]
is the project inside dropbox or any other cloud folder? i've always had issues in the past with editors messing up their hotloading

**Comment by MD485** [comment]
I think we can eliminate folder syncing issues, I haven't intentionally downloaded any software that does that, I disabled all startup software through the task manager which should disable any background processes that mess with file handles, and the hotloading test project I'm currently running is in a brand new folder that's in `C:/sbox`.

It's possible Windows is doing something without my knowledge, but if it's that pervasive an issue it's hard to believe it wouldn't effect everyone.

On the discord someone recently mentioned that Visual Studio was somehow causing their computer to crash and blue screen, it could be some complicated configuration/installation problems with my copy of Visual Studio.

I'll try reinstalling it but unfortunately if it is visual studio doing something funky and a somewhat common issue then the issue might be "unavoidable", "unfixable" and entirely out of ziks's control.

**Comment by Metapyziks** [comment]
Here's something interesting. If I run this:

```csharp
static void RenameTest()
{
	const int count = 1000;

	MoveFile( "C:\\sbox\\hotreloading\\code\\Die.cs", $"C:\\sbox\\hotreloading\\code\\Die~0.tmp" );

	for ( var i = 0; i < count; ++i )
	{
		MoveFile( $"C:\\sbox\\hotreloading\\code\\Die~{i}.tmp", $"C:\\sbox\\hotreloading\\code\\Die~{i + 1}.tmp" );
		Thread.Sleep( 1 );
	}

	MoveFile( $"C:\\sbox\\hotreloading\\code\\Die~{count}.tmp", "C:\\sbox\\hotreloading\\code\\Die.cs" );
}
```

It'll rename a Die.cs file 1000 times to different variants of Die~123.tmp, like VS does once when saving. I can see the renamings happen live, but S&box doesn't see any changes at all. If I change it to not have a tilde in the name, the changes all get picked up.

**Comment by MD485** [comment]
That is interesting, Microsoft does often use ~ when naming their temporary files.
Obviously they control the watchers too, what if there are hard coded exceptions to ignore certain file changes?

**Comment by handsomematt** [comment]
We do explicitly ignore those @Metapyziks in BaseFileSystem.AddChangedFile - we're only interested when they get renamed to a real file, which is how VS saves files.

**Comment by Metapyziks** [comment]
> We do explicitly ignore those @Metapyziks in BaseFileSystem.AddChangedFile - we're only interested when they get renamed to a real file, which is how VS saves files.

My tracing should be happening before that filter, but I'll double-check that.

**Comment by MD485** [comment]
Something interesting on my end, if I spam `Ctrl+S` and save repeatedly, that'll trigger hotloading even if there aren't file changes.
If we can't figure out the cause at least now I have a work around for the issue.

This confusingly happens regardless of whether hotload_fast is set to true or false, I was under the impression that hotload_fast prevents recompiling when there aren't any code changes?

https://github.com/Facepunch/sbox-issues/assets/36082767/773308b6-323f-48c1-9d5b-6ba07b2e02a2

As you can see it's seemingly random which save will trigger it.

**Comment by Metapyziks** [comment]
I've got a lead now. The internal System.IO.FileSystemWatcher is firing the events as expected, but they're getting lost somewhere in the Zio filesystem library we're using.

**Comment by Metapyziks** [comment]
Paths without a `~`:
```
[2024-06-20T14:50:02, subfs] OnRenamed: "/mnt/c/sbox/hotreloading/Code/Die.cs", "/mnt/c/sbox/hotreloading/Code/Die.0.tmp"
[2024-06-20T14:50:02, subfs]   IsInDirectory( "/mnt/c/sbox/hotreloading/Code/Die.0.tmp", "/mnt/c/sbox/hotreloading/Code" ): True
```

Paths with a `~`:
```
[2024-06-20T14:50:51, subfs] OnRenamed: "/mnt/c/sbox/hotreloading/Code/Die.cs", "/mnt/c/sbox/hotreloading/code/Die~0.tmp"
[2024-06-20T14:50:51, subfs]   IsInDirectory( "/mnt/c/sbox/hotreloading/code/Die~0.tmp", "/mnt/c/sbox/hotreloading/Code" ): False
```

The case is changing of the containing directory if there's a `~` in the file name, and Zio's doing a case-sensitive string equality test.

**Comment by Metapyziks** [comment]
It's `System.IO.Path.GetFullPath`:

```csharp
const string path1 = "C:\\sbox\\hotreloading\\Code\\Die~123.tmp";
const string path2 = "C:\\sbox\\hotreloading\\Code\\Die.123.tmp";

Log.Info( string.Equals( path1, Path.GetFullPath( path1 ), StringComparison.Ordinal ) ); // False
Log.Info( string.Equals( path2, Path.GetFullPath( path2 ), StringComparison.Ordinal ) ); // True
```

**Comment by Metapyziks** [comment]
I've got a fix that works for me, hopefully it's the same cause for you.

Could you try replacing `sbox/bin/managed/Zio.dll` with this:

https://files.facepunch.com/ziks/2024-06-20/Zio.dll

Then test some small code changes like before, making sure Trace Logging is enabled. Thanks!

**Comment by MD485** [comment]
[Hotloading Project.log](https://github.com/user-attachments/files/15917816/Hotloading.Project.log)
[Old project.log](https://github.com/user-attachments/files/15917818/Old.project.log)
I am happy to report that regardless of changes it now does seem to always hotload on save, which for me is bloody fantastic.
hotload_fast may be broken though since it's hotloading when it's set to true even if there aren't any code changes.

Thank you for tracking down the issue.
I'll keep this issue up because I'm assuming it's not pushed to live yet and you'll close it when you've merged the changes in, but from my testing yeah this seems to completely fix it, I didn't miss a hotload!

**Comment by Metapyziks** [comment]
Thanks a ton for all the help tracking this down!

I'll push a fix to live soon, will need to do a PR for Zio.
