### ISSUE TITLE
Allow Asset.Party materials to be used when creating new terrain materials

### ISSUE THREAD

**Issue by BlakeWinser** [Facepunch/sbox-issues#5686]
### For?

S&Box

### What can't you do?

Currently you are unable to use any Asset.Party materials when creating a new terrain material. The current UI to create a tmat file requires the individual source image texture files which we cannot currently directly access.
![image](https://github.com/Facepunch/sbox-issues/assets/47652506/e0aede12-8744-4a9b-94e2-b316df3b992e)

### How would you like it to work?

When creating a new terrain material, simply allow us to use Asset.Party materials as the tmat file. When creating a new tmat file, if we drag an asset.party material into the terrain materials section it should auto create one using that material.

### What have you tried?

Current work-around is to either decompile already downloaded materials and create them into usable tmat's or create your own textures entirely.

**Comment by handsomematt** [comment]
Yeah it sucks you can't use the existing vmats from asset.party but the goal is these tmats are cloud uploadable.

We tried originally with them being vmats and it adds a ton of limitations and some terrible ux.
