### ISSUE TITLE
Ambient Occlusion draws over everything

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5690]
### Describe the bug

When using the ambient occlusion post processing component. It draws over everything.  

### To Reproduce

1. Use a model using ambient occlusion.
2. Put it in front of the camera.
3. Look though it seeing the occlusion seeping though. 

### Expected behavior

It should not draw over it. 

### Media/Files

https://discord.com/channels/833983068468936704/833983416390385685/1253153155244621896

![image](https://github.com/Facepunch/sbox-issues/assets/95300917/c1976b53-ae96-42d7-ab0d-78644c36ee7f)
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/ebabcec2-9aae-463a-979f-667ca2b37e95)
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/c89c5cf4-5d4c-442d-8615-b9b8f2d3c979)

**Comment by handsomematt** [comment]
What else are you doing because this doesn't happen for me. AO draws after the opaque pass since it only affects opaque objects. Do you have strange transparent flags? Are you using multiple cameras?

**Comment by Nolankicks** [comment]
> What else are you doing because this doesn't happen for me. AO draws after the opaque pass since it only affects opaque objects. Do you have strange transparent flags? Are you using multiple cameras?

Not using any second camera, just looking through the "facepunch.ticket_dispenser" prop, without doing anything.

https://github.com/Facepunch/sbox-issues/assets/95300917/793dddc3-06bd-4a7a-8a9d-243424d77abe

https://github.com/Facepunch/sbox-issues/assets/95300917/592b590b-25c7-4128-96fb-67db73bb7a8f

**Comment by bakscratch** [comment]
Seems like it was due to the Ticket machines using "Static Overlay" shader for the text and icons

**Comment by handsomematt** [comment]
Yeah that model was poorly configured. SSAO works on the opaque layer only, objects with translucency do not write to depth and can not have their ao calculated, this is standard across all engines.

![image](https://github.com/Facepunch/sbox-issues/assets/1388267/c1b8cdbc-34ac-436f-a7a3-88c01185e80a)

Citizen works fine for me

**Comment by Nolankicks** [comment]
For me, it happened after looking through the model ticket model for the ao on the citizen to look transparent.
