### ISSUE TITLE
Custom grid size option

### ISSUE THREAD

**Issue by YtnomSnrub** [Facepunch/sbox-issues#5691]
### For?

S&Box

### What can't you do?

Set a custom grid size in the scene editor. Previously I could set the grid size to any value, whereas now it seems to be limited to only powers of 2 using the increase/decrease grid size buttons.

I designed my assets around a 5-foot grid, and having the option to set the grid to 12 inches and 60 inches was very useful for me.

### How would you like it to work?

Have something similar to the old input to set a custom grid size.

### What have you tried?

Setting the grid size to a factor of the desired grid size works (i.e. 4 inches in my case), but makes custom assets harder to line up.

**Comment by MD485** [comment]
Is this not #2187 ?

**Comment by yuberee** [comment]
I assume this one is for the scene system grid while that older one is for Hammer.

**Comment by YtnomSnrub** [comment]
Yep this is for the scene system grid. There used to be a slider in the scene editor to set a custom grid size, but one of the updates this week removed it when the UI was moved to the header bar.

**Comment by solwllms** [comment]
Replaced the increment/decrement buttons with spin boxes that let you stick in whatever values you want:
![image](https://github.com/Facepunch/sbox-issues/assets/7689429/5a4ad5f5-fcfc-40ee-8794-92bc2ee2f80a)
