### ISSUE TITLE
Cloud assets don't update to latest version on load

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5692]
In HC1, we're having issues where cloud assets (in our case, the ViewModels for weapons), will receive updates, but we will have to double click the assets in the asset browser to catch those updates, they're not being grabbed automatically.

**Comment by DevulTj** [comment]
I made some improvements to this, but @solwllms is working on something more solid.

**Comment by solwllms** [comment]
Moved to explicit manual update flow for cloud assets now.
