### ISSUE TITLE
Cloud assets can sometimes fail to load entirely 

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5693]
Again, in HC1, we are having issues where cloud assets just won't load on startup. This happens a lot with our weapon prefabs. w_usp is a good example, it'll just turn into an error model and you can't fetch the asset until you reboot the editor entirely. This doesn't happen all the time, I don't have a solid repro.

In the prefab JSON, it'll remove the package from _references, and set the model to error.vmdl.

**Comment by handsomematt** [comment]
It's a bit chicken and egg

1. We load the game package to register the GameResource assets so we can check the __references
2. DownloadCloudAssets iterates the __references and downloads the cloud models, but the GameResources have already loaded their models as errors.

Getting a hook just after the asset types have been registered would probably work

**Comment by DevulTj** [comment]
I'm 90% sure I sorted this a few weeks ago
