### ISSUE TITLE
Join via new instance crashes the instance

### ISSUE THREAD

**Issue by kodi022** [Facepunch/sbox-issues#5695]
### Describe the bug

When trying to "join via new instance" to my editor game, the new instance crashes

### To Reproduce

1. start game in editor
2. join via new instance
3. it would probably be okay for not my game

ive always had issues with join via new instance for my game, though this is new and easier to share

### Expected behavior

i join with new instance

### Media/Files

Log of new instance
[Log.log](https://github.com/user-attachments/files/15919210/Log.log)

**Comment by CarsonKompon** [comment]
Does this happen for you with an empty project? Are you able to send a repro?

**Comment by kodi022** [comment]
> Does this happen for you with an empty project? Are you able to send a repro?

No it does not happen with an empty project
I don't know if I can send a repro because ive had issues with starting a instance ever since migrating this project to the scene system, it's never worked (with a different error in the past, previously it would make an empty error and be unresponsive to the cursor and keyboard in the main menu) so I have no clue how to repro. The project is quite a bit older than the scene system updates, so there is a possibility its related to that.

Here is a log from trying today
```
2024/06/27 20:12:06.5173	[Menu] Created Main Menu	
2024/06/27 20:12:06.9968	[Generic] Connecting to localclient..	
2024/06/27 20:12:07.4882	[engine/RenderSystem] Texture manager doesn't know about texture "avatar.vtex" when setting "" - returning error texture in CTextureManagerVK::GetImageView	
2024/06/27 20:12:07.4882	[engine/RenderSystem] Texture manager doesn't know about texture "avatar.vtex" when setting "" - returning error texture in CTextureManagerVK::GetImageView	
2024/06/27 20:12:08.8635	[Generic] Downloading 138 files (168.59mb)..	
2024/06/27 20:12:15.0053	[Generic] ..done in 6.14s	
2024/06/27 20:12:15.0053	[engine/ResourceSystem] Reloaded 3 resident symlinked resources in 0ms	
2024/06/27 20:12:15.2545	[Generic] Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.FontManager.Load(Stream stream)
   at Sandbox.FontManager.LoadAll(BaseFileSystem fileSystem)
   at Sandbox.GameMenu.GameInstance.LoadAsync(Enroller enroller, CancellationToken token)
   at Sandbox.GameMenu.GameMenuDll.LoadGamePackageAsync(String ident, GameLoadingFlags flags, CancellationToken ct)
   at Sandbox.Network.NetworkSystem.On_Handshake_ServerInfo(ServerInfo data, Connection source)
   at Sandbox.Network.NetworkSystem.<>c__DisplayClass77_1`1.<<AddHandler>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Sandbox.Network.NetworkSystem.ExceptionWrapAsync(Func`1 method)
2024/06/27 20:12:15.2545	[Generic] TODO - Disconnect, connection has crashed, remove it
```
The instance then shut down fully. People online connect fine, its just the local instance is doing this. The host see's no errors at all.

Guessing from the stack, I have tried to repro test the 2 custom fonts in the game, but moving and testing them in another project was led to no issues.

**Comment by kodi022** [comment]
For the first time in scene sbox, my multiclient worked. Guess the problem, whatever it was, is fixed now. very cool thank you fp
