### ISSUE TITLE
Rendering getting funky at a distance

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#5696]
### Describe the bug

Recently I've been having issues with z-fighting on shadows and things not rendering properly.

https://github.com/Facepunch/sbox-issues/assets/36082767/982eabe0-ca95-4824-bcb8-b5a5ead811a6

Here's a video of things not rendering properly.

https://github.com/Facepunch/sbox-issues/assets/36082767/ada92e41-cc67-4cd1-bdcd-907acb8fd6c5

Here's a video of the "shadow z-fighting" I was talking about.

### To Reproduce

First video:
1. Create a new project
2. Go to the minimalist scene
3. Fly the camera around

Second video:
1. Download SceneStaging
2. Go to the joints scene
3. Look at the doors and fly around

### Expected behavior

Things to render like they did a week ago, I'm assuming this is some recent change that you guys could probably guess would cause it?

### Additional context

Damn floating point imprecision, if only we were using meters! _`I'm joking, matt please spare me.`_

**Comment by CarsonKompon** [comment]
Any chance you have a camera in any of your scenes with a znear of less than 0?

**Comment by MD485** [comment]
Ah okay that explains it, I must have messed with the editor settings at some point and tried moving the znear back to the default of 1 but went too far. I didn't realise editor settings persisted between projects.

@handsomematt could you put a lower limit to the znear on the editor settings for the scene camera too?
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/55f151a7-6cbd-4214-b2ad-0f03f2c7e3b6)
