### ISSUE TITLE
Cannot drag objects in ModelDoc when physics simulation is active

### ISSUE THREAD

**Issue by genericicon** [Facepunch/sbox-issues#570]
**Describe the bug**

https://user-images.githubusercontent.com/75807239/127938570-6a5b0248-6949-4612-90b6-d7cc4f5676b6.mp4

This drags a selection box over the model instead of selecting/picking it up.

**Expected behavior**

https://user-images.githubusercontent.com/75807239/127938607-a1e9c470-d700-4732-abf2-4db10e10e0ef.mp4

This is in Half-Life Alyx, the model is selectable and can be picked up

**Comment by justynboi** [comment]
This bug is very annoying! Would really like to see this get fixed. :D

**Comment by aylaylay** [comment]
Finally got this working. Let me know if it works for you when the build hits steam and close the issue if you're happy with it.

**Comment by justynboi** [comment]
I can confirm that it works!

https://user-images.githubusercontent.com/17112771/127951239-cae7df99-c029-4ad1-a296-6840c41e68a8.mp4

**Comment by genericicon** [comment]
Works great. Thanks!
