### ISSUE TITLE
Inspector not usable (Clicking on the Inspector sending mouse inputs to scene view instead)

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5701]
### Describe the bug

I have a video of me trying to click, click-and-drag, and right click on different things in the Inspector. All inputs instead get sent to the scene view and render the Inspector unusable:

https://github.com/Facepunch/sbox-issues/assets/5159369/7c672a68-f79d-4258-805e-cfaf94adf106

### To Reproduce

Try clicking/dragging on something in the inspector and notice behaviour similar to what is seen in the video above

### Expected behavior

The inspector should have input priority here.

**Comment by DevulTj** [comment]
I'm not able to repro this, was it fixed?

**Comment by CarsonKompon** [comment]
Yeah doesn't seem to be happening anymore. I don't think I was up-to-date at the time.
