### ISSUE TITLE
Stats.GetPlayerStats only caches/returns first call's PlayerStats

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#5707]
### Describe the bug

Sandbox.Services.Stats.GetPlayerStats() (and I suspect GetLocalPlayerStats()) caches, and therefore returns, only the stats of the ```steamid``` given in the first execution of the function. I believe this is due to a bug with the caching logic, wherein it only caches the PlayerStats objects on ```packageIdent```, meaning subsequent calls (with different SteamID's) return the value cached in the first call.

I'm currently experiencing this in Grubs; we fetch stats right on join for our player list, and the stats returned for each player are only the stats for one player (usually the local player).

![image](https://github.com/Facepunch/sbox-issues/assets/43252311/2ff83fa8-8038-4a25-8842-12b0e4169053)

### To Reproduce

1. Download and open [repro project.](https://github.com/user-attachments/files/15935152/statsrepro.zip)
2. Start repro.scene and observe identical stats for both entries.
3. Click "Increase Stat" a few times, then "Refresh Stats", and observe either both values or neither values changing (depending on whether it has loaded mine or your stats).

### Expected behavior

Fetching PlayerStats should always return stats for the given SteamId.

### Media/Files

The code in question (GetLocalPlayerStats() caches identically):

![image](https://github.com/Facepunch/sbox-issues/assets/43252311/1f6cb7d9-ca83-4be7-9288-fa78fa8dd2ae)

**Comment by garrynewman** [comment]
100% correct - thanks
