### ISSUE TITLE
Add CurrentAngle property to HingeJoint

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5712]
### For?

S&Box

### What can't you do?

I don't have an easy way to move a rigid body to a specific angle along a HingeJoint, nor to read what the current angle is. I just have to work backwards by rotating the transform or something. It would be great if the current angle of a HingeJoint could be get/set easily.

The lack of a current angle also leads to any newly created hinge joint assuming that the current position is the MinAngle, which works fine for single player games where a hinge might be guaranteed to always start in its closed/MinAngle position, but causes a desync when a new player joints and a new HingeJoint is created locally.

### How would you like it to work?

Add a `CurrentAngle` property to the `HingeJoint` component.

```csharp
[Property] public HingeJoint Hinge { get; set; }
[Property] public bool IsOpen => Hinge.CurrentAngle >= 5f;

private void Open()
{
    if ( IsOpen )
        return;
        
    Hinge.CurrentAngle += 5f;
}
```

Also, when a HingeJoint is created from a network snapshot and it has a nonzero value for CurrentAngle, the joint's range of movement from the new player's perspective should match that of the host.

### What have you tried?

Whenever a player takes ownership of a door that's constrained by a HingeJoint, I call the ResetJoint method to make the rigidbody _pretty much_ line up with what I'd expect to see. However, this seems to somehow be causing the door to slightly drift away from the hinge over time, and it just feels overall very hacky and gross.

```csharp
[Property] public float CurrentAngle
{
	get
	{
		return Axis switch
		{
			LockAxis.Pitch	=> Transform.LocalRotation.Pitch(),
			LockAxis.Roll	=> Transform.LocalRotation.Roll(),
			_		=> Transform.LocalRotation.Yaw()
		};
	}
	set
	{
		var angles = Transform.LocalRotation.Angles();
		Transform.LocalRotation = Axis switch
		{
			LockAxis.Pitch => angles.WithPitch( value ),
			LockAxis.Roll => angles.WithRoll( value ),
			_ => angles.WithYaw( value )
		};
	}
}

[Property] public Rotation JointRotation
{ 
	get
	{
		var progress = StartAngle - CurrentAngle;
		return Axis switch
		{
			LockAxis.Pitch => Rotation.FromPitch( progress ),
			LockAxis.Roll => Rotation.FromRoll( progress ),
			_ => Rotation.FromYaw( progress )
		};
	} 
}

[Sync] public float StartAngle { get; private set; }

public void ResetJoint()
{
	var tx = Transform.World;
	Transform.World = tx.RotateAround( Joint.Transform.Position, JointRotation );
	Joint.Enabled = false;
	Joint.Enabled = true;
	Transform.World = tx;
}

protected override void OnStart()
{
	if ( !IsProxy )
	{
		// If we're just starting the game, assume that the hinge is in a shut position.
		StartAngle = CurrentAngle;
	}
}
```

**Comment by aylaylay** [comment]
I've added Angle, Axis, Speed getters to hinge joint. I'm still deciding if an angle setter makes sense, really you should be setting this on the body and not the joint

**Comment by chrisspieler** [comment]
Thanks for looking at this! 

I tried getting Angle, but the value returned is in radians. I feel it should be in degrees like MinAngle and MaxAngle.

**Comment by aylaylay** [comment]
I agree

**Comment by aylaylay** [comment]
Done

**Comment by aylaylay** [comment]
Are you still needing the setter for angle? I think the issue you were having was that the local frames for the joint were incorrect for network snapshots. I've added a way for joints to set their local frames which should help you.

**Comment by chrisspieler** [comment]
> Are you still needing the setter for angle? I think the issue you were having was that the local frames for the joint were incorrect for network snapshots. I've added a way for joints to set their local frames which should help you.

I have a workaround, but it's rather convoluted. I'll try using the new setter and let you know how that goes.

**Comment by aylaylay** [comment]
From what you explained, a angle setter wouldn't work here. I'll still be adding an angle setter but it will be to control the target angle for the joint motor

**Comment by aylaylay** [comment]
https://github.com/Facepunch/sbox-issues/assets/1667289/e8a24d86-59c8-4228-8ee2-c69992ba37a2
