### ISSUE TITLE
Clicking Reset on the camera component crashes the editor

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5713]
### Describe the bug

When you click on "Reset" on a camera component within the inspector by either of the  ways below the editor will crash.
 - Right Click ---> Reset 
 - Click On 3 Dots ---> Reset 
 
### To Reproduce

1. Click on a game object with the camera component 
2. Right click on the camera component tab and click "Reset"
3. Observe Crash.

### Expected behavior

To not crash.

### Media/Files

[Log.log](https://github.com/user-attachments/files/15942603/Log.log)

**Comment by aylaylay** [comment]
I've fixed the NRE's but it looks like Reset is messing up a few of our components

**Comment by aylaylay** [comment]
Should be good now

**Comment by QuackCola** [comment]
> I've fixed the NRE's but it looks like Reset is messing up a few of our components



> Should be good now

Lovely  👍
