### ISSUE TITLE
Physics Debug does not work in Game View

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5715]
### Describe the bug

Enabling Show Physics Debug works in Scene View, but not in Game View.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/40c295b7-2d9f-4351-ac7f-bbf7d99646e6)
![image](https://github.com/Facepunch/sbox-issues/assets/5991682/abb6b1d8-e2d8-4827-9d6a-968ef0a0941c)

### To Reproduce

1. Launch game
2. Enable physics debug
3. See that it does not work

### Expected behavior

Should work

**Comment by aylaylay** [comment]
Fixed
