### ISSUE TITLE
Dark lighting modes

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/sbox-issues#572]
**Describe the bug**
Lighting mode in ModelDoc editor and in Material editor shows empty scenes with darkness.
Only "Default", "Headlight" and of course "Basic dark" works fine.

**To Reproduce**

1. Go to ModelDoc editor and open any model;/Go to Material editor and open any editable material;
2. Click on the light bulb at the top of the 3d viewport;/Click on the gear at the top-right of the 3d viewport and choose "Lighting Preview"
3. Select any lighting mode except "Default", "Headlight" and "Basic dark";
4. See darkness

**Expected behavior**
The lighting and reflection cubemap changes depending on the selected mode

**Comment by aylaylay** [comment]
Them light rigs don't exist anymore, I have removed them from the lightrigs file so they wont be listed. You can edit toolscenelightrigs.txt to add more. There probably should be a better way to control lighting in the future.

**Comment by garrynewman** [comment]
We should really add our own for these, since they're useful. I'm sure Valve wouldn't mind us copying theirs over.
