### ISSUE TITLE
Shaders with transparent areas display abnormally after starting the game.

### ISSUE THREAD

**Issue by TiO2EvoLve** [Facepunch/sbox-issues#5723]
### Describe the bug

In the editor
<img width="788" alt="PixPin_2024-06-26_21-09-32" src="https://github.com/Facepunch/sbox-issues/assets/49835162/1bc2b8b0-b3b3-4938-8d88-389f409240d3">
In the game
<img width="787" alt="PixPin_2024-06-26_21-09-45" src="https://github.com/Facepunch/sbox-issues/assets/49835162/9c44baf9-316b-4109-89f7-c9dc97b29220">

### To Reproduce

[ShaderBug.zip](https://github.com/user-attachments/files/15988820/ShaderBug.zip)
Here's one of the source files

### Expected behavior

Transparent areas should be displayed correctly

**Comment by samzanemesis** [comment]
Thanks for the repro, we had this issue internally recently and I was looking into it, will get sorted asap

**Comment by samzanemesis** [comment]
Yeah Material Overrides aren't setting the flags correctly, I'll push a fix
![image](https://github.com/Facepunch/sbox-issues/assets/6563447/ff1380c8-ed94-45fe-9848-322ba00cdde1)

**Comment by TiO2EvoLve** [comment]
> 是的，Material Overrides 没有正确设置标志，我会推送修复程序 ![图像](https://private-user-images.githubusercontent.com/6563447/343205504-ff1380c8-ed94-45fe-9848-322ba00cdde1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjY3ODksIm5iZiI6MTcxOTY2NjQ4OSwicGF0aCI6Ii82NTYzNDQ3LzM0MzIwNTUwNC1mZjEzODBjOC1lZDk0LTQ1ZmUtOTg0OC0zMjJiYTAwY2RkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMTMwODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjIyMzc0ZWRmNGM0MTY1MzI0NGRhZDRhN2U4MWE0Mzg4YjAxZTY2ZmNjNzYzZTU3NmY4MTRhMWYxMzlmN2M1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0wrJP-VJTl66iqOk30V8p27U-dtDg0DgLSSbUnWquzo)

<img width="1066" alt="PixPin_2024-06-29_21-10-08" src="https://github.com/Facepunch/sbox-issues/assets/49835162/0d2d76df-1e9d-4d9b-844b-a3315ca38f00">
Doesn't seem to have been resolved -_-
