### ISSUE TITLE
Prefab Variables layout preventing other widgets from being dragged up

### ISSUE THREAD

**Issue by ringadongdillo** [Facepunch/sbox-issues#5726]
### Describe the bug

The Hierarchy when viewing a prefab doesn't allow itself to be shrunk even though there is a ton of empty space, as shown in the video below.

https://github.com/Facepunch/sbox-issues/assets/173723830/f40a2383-1f73-43cc-a469-44bc83e3128a

### To Reproduce

-

### Expected behavior

-

**Comment by solwllms** [comment]
Can now grab the Prefab Variables header to resize that section to whatever you like
