### ISSUE TITLE
SpriteRenderer Bounds are not properly set.

### ISSUE THREAD

**Issue by siasur** [Facepunch/sbox-issues#5727]
### Describe the bug

When moving a GameObject that has a SpriteRenderer Component - with a size above 101 - out of the cameras view its getting culled before the sprite is completly out of the frame. Resulting in objects disapearing at the screen boundary when part of it should still be visible.

### To Reproduce

1. Create Gameobject with Sprite Renderer
2. set the size to anything above 101 (for easy recognition go even higher)
3. Move the objects 65 units out of the cameras view
4. Run the game

### Expected behavior

The sprite should be visible until it is completly out of the cameras view.

### Media/Files

![grafik](https://github.com/Facepunch/sbox-issues/assets/2236705/bcc5d5f3-a2c9-4b6d-8cc9-fa8cb4e57e84)
Origin of object is `< 64f` out of the cameras view. You can see the red area at the left border in the game view (left side)

![grafik](https://github.com/Facepunch/sbox-issues/assets/2236705/3d13f519-b933-4c5b-a613-59ed6bca6af2)
Origin of object is now 1 unit further (now `> 64f`) out of the cameras view. The red area that should be still visible (as seen in the scene view on the right side) is now gone.

### Additional context

![image](https://github.com/Facepunch/sbox-issues/assets/2236705/45bf0e84-52a4-42bd-abcf-81a92722e5df)
There is a line in `OnPreRender` of the `Sprite Renderer` that sets the bounds to a hardcoded size of 64f.

**Comment by aylaylay** [comment]
Should be fixed now
