### ISSUE TITLE
Mouse hover determines active Scene window

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5728]
### Describe the bug

Mouse hover is what causes the active window to switch, rather than clicking inside of it, this is kind of annoying because if you have a prefab you're editing to the left and a game window or something to the right, you have to maneuver your cursor around the right window just to have the hierarchy and inspector not switch

### To Reproduce

1. Have 2 back to back windows (Preferably a prefab window a scene window so you can observe the changes in the inspector and such)
2. Mouse hover switches between them

### Expected behavior

This should be on click, not a hover 

### Media/Files

https://github.com/user-attachments/assets/37894417-a3d4-48e7-9cce-c454875bd77e

**Comment by solwllms** [comment]
Some changes for this: setting active scene now requires some input in that viewport so should feel more deliberate, won't do it just from hover over.
Doing things like moving the camera, selecting etc shouldn't require a 2nd input or anything either, and interactions with gizmos should work as expected (hover highlight etc).

**Comment by Retroeer** [comment]
This works exactly how I expect it to now, huge thanks sol
