### ISSUE TITLE
Tags from Hammer maps do not carry over to scene

### ISSUE THREAD

**Issue by trende2001** [Facepunch/sbox-issues#5738]
### Describe the bug

Tags that are set on objects of a map made in Hammer do not carry over to the Scene System

### To Reproduce

1. Make a map (for example place a physics prop with a 'prop' tag)
2. Compile
3. Drag it into a map instance in scene
4. Press Play and check the prop in question in the hierarchy (will not have any tags named 'prop') 

### Expected behavior

Tags being correctly compiled into objects of a Hammer map.

**Comment by aylaylay** [comment]
Should be working now - can you test for me please

**Comment by trende2001** [comment]
@aylaylay works thank you sm
