### ISSUE TITLE
SceneModel bone transforms reset on bodygroup change

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#5741]
### Describe the bug

Our slot machine for My Summer Cottage uses bone transforms to roll the slot wheels around, but their bone transform resets to default when a bodygroup is set.

This completely breaks the slot machine, which used to work just fine.

### To Reproduce

1. Use the following model https://sbox.game/fish/slot_machine
2. Copy slot machine logic from https://github.com/Small-Fish-Dev/My-Summer-Cottage/blob/main/code/Components/SlotMachine/SlotMachine.cs#L215 
3. See that the bone transform is reset every time a bodygroup is changed.

### Expected behavior

I'm not sure if resetting the bone transforms is expected behavior on a bodygroup change, but it does not feel like it is.
I'd like to at least be able to decide if the bone transforms should reset.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/19620198/c80c39dd-6c8b-4485-bc0a-308ff70cdd2d

**Comment by aylaylay** [comment]
You shouldn't really be using SetBoneWorldTransform for this, the world transform is the final bone transform and is recomputed every frame by SceneAnimationSystem.

The prefered way is to create bone objects and set the wheel bones to procedural, you can then just rotate the bone object locally.

https://github.com/Facepunch/sbox-issues/assets/1667289/a26751dc-7978-4f5f-af95-d94ea8f51533

If for whatever reason you can't or wont create bone objects, you can use SetBoneOverride instead like this:

```cs
	[Property] public SkinnedModelRenderer Model { get; set; }
	[Property] public float Yaw { get; set; }

	protected override void OnPreRender()
	{
		base.OnPreRender();

		var tx = Model.Model.GetBoneTransform( 2 );
		tx.Rotation *= Rotation.FromYaw( Yaw );
		Model.SceneModel.SetBoneOverride( 2, tx );
	}
```

But it's advised to use procedural bones.

**Comment by aylaylay** [comment]
Closing as wont fix - SetBoneWorldTransform is only really there if you're managing a scene model directly, the component is gonna be stomping world transform every frame.

**Comment by ceitine** [comment]
alright, thanks for letting me know <3
