### ISSUE TITLE
[Terrain] Unclear error when importing splatmap 

### ISSUE THREAD

**Issue by wheatleymf** [Facepunch/sbox-issues#5744]
### Describe the bug

This is more QOL than a bug report, sorry I couldn't find more matching category for this kind of stuff. 

### To Reproduce

1. Try importing splatmap that does not match the heightmap resolution (e.g. 2048x2048 splatmap while heightmap is 4096x4096) 
2. You will get "Index was outside the bounds of the array."   

### Expected behavior

IMO perfectly such user errors should be properly handled, it's always better when program explains where did you mess up. Just before the `for` loop on line 165 in `TerrainComponentWidget.Settings.cs`, something like this would be enough I guess: 

```csharp
if ( pixels.Length != storage.Resolution * storage.Resolution )
{
	Log.Error( $"Splatmap does not match the heightmap resolution! Splatmap length is {pixels.Length} while heightmap is {storage.Resolution * storage.Resolution} " );
	return;
}
```

Or, not sure if it's the best course, automatically resize splatmap to fitting heightmap resolution.

**Comment by aylaylay** [comment]
Looks like I already resize the splatmap?
