### ISSUE TITLE
ReadOnly doesnt work with lists and enum properties

### ISSUE THREAD

**Issue by johncosfm** [Facepunch/sbox-issues#5749]
### Describe the bug

Despite using the ReadOnly attribute the value can still be changed in the inspector.

![image](https://github.com/Facepunch/sbox-issues/assets/69829964/a33365b7-c93a-4d4a-9374-05ad9782014d)

![image](https://github.com/Facepunch/sbox-issues/assets/69829964/fa77739a-bc35-493f-916a-0cfc3304f7e1)

![image](https://github.com/Facepunch/sbox-issues/assets/69829964/276628f3-7bf2-4eeb-94bd-ad86ce52f42b)

![image](https://github.com/Facepunch/sbox-issues/assets/69829964/5c3ecc07-77eb-4129-be98-2f7f28e73f6d)

Of course I can simply avoid changing the value, but that could be said for any use of the ReadOnly attribute

### To Reproduce

create a list or dictionary or enum property
add the ReadOnly attribute
value can still be edited

### Expected behavior

The value should be greyed out in the inspector, similarly to how bools and floats and whatnot work.

**Comment by aylaylay** [comment]
These should be disabled now

**Comment by johncosfm** [comment]
looks like you can still add and delete with read only dictionaries

**Comment by aylaylay** [comment]
Gave the same treatement to dictionary
