### ISSUE TITLE
Default surface types do not have the right file paths for sounds

### ISSUE THREAD

**Issue by Doodl0** [Facepunch/sbox-issues#5750]
### Describe the bug

The default surface types still use the old file path for sounds (e.g. `sounds/impacts/impact-bullet-concrete.sound`), even though the sounds folder has be reorganised and the file path should use `sounds/impacts/bullets/impact-bullet-concrete.sound`. This creates errors when trying to have a collider use a surface, as it ouputs `Couldn't find sound event sounds/impacts/impact-bullet-concrete.sound` in the console and does not play any sounds.

### To Reproduce

1. Create a default cube with a collider and rigidbody.
2. Make a scenario where the cube would create a sound, such as dropping it onto a plane.
3. Check the console for the afformentioned error.

### Expected behavior

The default surfaces should be redirected to the correct folder for their respectives sounds, and the game should play the sound without issue

### Additional context

I have already verified my game files to prevent any version mismatched assets, and the problem still occurs

**Comment by aylaylay** [comment]
Fixed

**Comment by Doodl0** [comment]
Thanks 👍
