### ISSUE TITLE
Use [KeyProperty] to display delegates/actions/events with other properties instead of the actions page

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5752]
### What it is?

If I have

```
	[Property]
	public EventComponent.SaunaEvent OnTriggered { get; set; }
```

This is where it displays:

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/c90326ed-a38a-4bbc-9a1d-6583593e3357)

### What should it be?

To be like this

```
	[KeyProperty]
	public EventComponent.SaunaEvent OnTriggered { get; set; }
```

And it would display in here with the other properties

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/c4776ad5-f6c9-46fb-9113-b279e8c9f9e7)

**Comment by Metapyziks** [comment]
Watch out, you'll need both `[Property, KeyProperty]` atm.
