### ISSUE TITLE
Changing the Scale of a BoxCollider triggers ITriggerListener's OnTriggerExit and then OnTriggerEnter

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5753]
### Describe the bug

Something like a crouching behaviour where you change the scale of the player's collider while inside of an ITriggerListener mesh will retrigger the OnTriggerExit and OnTriggerEnter methods.

### To Reproduce

1. Create a component that implements ITriggerListener
2. Move a BoxCollider inside of it
3. Change the BoxCollider's Scale (You can skip step 2 and 3 by using a character controller with crouching like Facepunch's)

### Expected behavior

For the trigger not to fire off twice

### Additional context

I assume this is happening because the collider needs to rebuild.
Right now I'm double checking every OnTriggerExit to see if they actually exited

**Comment by aylaylay** [comment]
I guess ideally we should only be rebuilding scale in editor

**Comment by aylaylay** [comment]
Resizing the box via scale or changing center/size wont remake the shape anymore so it shouldn't retrigger the trigger.

If this works well I'll give the other colliders the same treatment where possible.

**Comment by yuberee** [comment]
Ye I removed the workarounds and they don't retrigger, seems good to me!
