### ISSUE TITLE
Control Widgets log in the console

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5754]
### Describe the bug

Control Widgets' names log in the console.

### To Reproduce

1. Click on a GameObject with a control widget.
2. Look at the console.
3. See the logs.

### Expected behavior

There should be no logs in the console.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/95300917/04426309-dce6-4aae-b0db-cbe7f13e197e)

**Comment by aylaylay** [comment]
I'm seeing no logs

**Comment by Nolankicks** [comment]
> I'm seeing no logs

I think it could be when I click on a game object with a custom editor:
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/de4b51ab-7cd2-4d3d-9552-6617e864c5b3)
