### ISSUE TITLE
When unloading a map instance on start `Exception when calling 'Update' on MapCollider on (World Physics) System.NullReferenceException: IPhysicsBody was null when calling SetTransform    at Sandbox.PhysicsBody.set_Transform(Transform value)    at Sandbox.Collider.TeleportKeyframeBody(Transform transform)    at Sandbox.Collider.RebuildImmediately()    at Sandbox.Collider.OnUpdate()    at Sandbox.Component.ExceptionWrap(String name, Action a)` is thrown

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5755]
### Describe the bug

When starting a scene where you are unloading a map instance on start, it throws errors. I've been doing this for 2 weeks and it just broke today.

### To Reproduce

1. Create a component that unloads a map instance on start.
2. Start the game.
3. Watch the errors.

### Expected behavior

There should be no errors.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/95300917/aa055627-f0a3-45a2-b4d0-33c5d8a7e745

**Comment by Nolankicks** [comment]
This issue still occurs, I recorded this video just now. I've updated my game.

https://github.com/Facepunch/sbox-issues/assets/95300917/cb838e49-f822-40a7-90bc-1a9f0467dab6

**Comment by aylaylay** [comment]
Should be good now
