### ISSUE TITLE
Doors constrained by hinge joints move several units lower on game start

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5756]
### Describe the bug

When starting a game, if you have a door with a rigidbody that is constrained by a hinge joint, the door will sink a few units lower when the game starts.

### To Reproduce

1. Open the attached project
2. Open minimal.scene
3. See that the counter door model is properly aligned with the counter
4. Play the scene
5. See that the counter door model sinks a few units lower, becoming visibly misaligned with the counter

### Expected behavior

When the game starts, the position of the door should not be shifted. Only its rotation should change.

### Media/Files

[sunken_hinge.zip](https://github.com/user-attachments/files/16063672/sunken_hinge.zip)

### Additional context

The issue began in the last 12 hours or so. Previously, the doors were working just fine.

**Comment by aylaylay** [comment]
Should be good now - why it recently broke I'm not sure, the order of things might have changed so the physics step was running before joint got created.
