### ISSUE TITLE
State Machines like editor in ActionGraph

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5757]
### For?

S&Box

### What can't you do?

I'm unable to create my own State Machines editor due to skill issue

### How would you like it to work?

The workflow in ActionGraph is perfect for State Machines, especially defining your own .action with variables.
Some kind of contained looped ActionGraph to define State Machines that can be used for NPCs or Game Logic.

### What have you tried?

I attempted to create looped actiongraph logic during the 2024 Contest but failed.

### Additional context

I'm probably overshrimplifying how much of a feat it is to implement this, I'm opening this feature request just to put the idea out there.

**Comment by Metapyziks** [comment]
Might do this as a hackweek thingy

**Comment by yuberee** [comment]
As this is already available I'm closing this feature request
