### ISSUE TITLE
not working button on sbox.game profile settings

### ISSUE THREAD

**Issue by somewhere-in-the-universe** [Facepunch/sbox-issues#5758]
### Describe the bug

I know that it's not important, but there's an invite codes button in profile settings left from the invite system on sbox.game that takes you to the 404 error page

### To Reproduce

1. go to sbox.game
2. go to profile settings
3. click on the invite codes button

### Expected behavior

it shouldn`t be there

### Media/Files

![изображение](https://github.com/Facepunch/sbox-issues/assets/146519784/ced28ce4-666b-4b99-9c2c-cf97e03fa11f)
![изображение](https://github.com/Facepunch/sbox-issues/assets/146519784/f2972d54-92ed-4a10-9f7b-bd53aa08f5f3)

**Comment by DevulTj** [comment]
Deleted
