### ISSUE TITLE
[Terrain] Odd acne shadows on terrain when shadow cast is enabled

### ISSUE THREAD

**Issue by WheatleyMF** [Facepunch/sbox-issues#5760]
### Describe the bug

Shadows appear incorrectly on the terrain. 

### To Reproduce

1. Create a new blank scene, you can change default rotation values for the built-in directional light object as you wish
2. Create a new terrain, import any heightmap (2048 / 4096 resolution will probably make this problem more apparent). For the reference, terrain size in my case was `79872` and terrain height `10000`. You can try significantly lowers values, this issue will appear anyway
3. Go to terrain settings tab, and set "Cast Shadows" to "On"
4. Fly around, try changing light direction, you'll notice this shadow acne that keeps becoming less or more detailed depending on your camera position and rotation.

### Expected behavior

This looks like shadows are being cast from terrain's clipmap instead of what you actually see. I am not sure what actually is happening here. 

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/20972271/750396ca-ad23-4539-90a0-823125b0e479)
Heightmap: (16bit / Windows) http://files.smallfi.sh/u/heightmap16bit.raw

**Comment by samzanemesis** [comment]
should be good, still sucks a bit that it fades out early

**Comment by WheatleyMF** [comment]
> should be good, still sucks a bit that it fades out early

Shadows look good now, thank you. Though I've just noticed that there might be something else incorrect with terrain shading, it looks like there's no lighting based on normals are applied. I've checked the world space normals and it looks like whole terrain is in tangent space, while normally shaders are required to transform normals to world space. Is this correct? 

![image](https://github.com/user-attachments/assets/82393508-a1de-4164-808d-4f0d4b9b2437)

**Comment by handsomematt** [comment]
Not sure what you mean, these are tangent and these are world space normals

![image](https://github.com/user-attachments/assets/db1e9def-fc31-4104-96f7-8b14d1fc991e)
![image](https://github.com/user-attachments/assets/12fed958-e51f-471d-8143-00c3e5a81e43)

**Comment by WheatleyMF** [comment]
Ah, I must have been wrong then, my bad. Yeah, that would be nice - currently terrain feels like it's being shaded flat, even near steep slopes. Normals highlighting bumps and terrain relief more noticeably would be great.
