### ISSUE TITLE
[Terrain] Add support for TGA format when importing splatmaps

### ISSUE THREAD

**Issue by WheatleyMF** [Facepunch/sbox-issues#5761]
### For?

S&Box

### What can't you do?

Currently you can select only PNG images when importing the splatmap, which is pretty inconvenient. Most terrain editors will export the splatmap only in TGA format since it properly supports alpha channels, that is used as 4th terrain splat layer. 

### How would you like it to work?

Allow TGA files for splatmap import.

### What have you tried?

PNG has layer transparency, which works too, but this means that you have to go in Photoshop, copy the contents of alpha channel, then create layer opacity mask, insert the copied alpha channel, apply the layer and then save as PNG. Not a big issue, however this feels quite redundant.

**Comment by aylaylay** [comment]
No reason why we can't support all the image formats we already load

**Comment by aylaylay** [comment]
You can now import splatmap from png, tga, jpg, psd
