### ISSUE TITLE
Add `Network.OrphanMode` and `Network.TransferMode` to the gameobject inspector

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5763]
### For?

S&Box

### What can't you do?

Right now I often need to set these values manually inside of components when it'd be much cleaner if I could just set these on the gameobject in the inspector.

### How would you like it to work?

Similar to how setting the network mode currently works in the inspector.

### What have you tried?

I can run Network.SetOrphanedMode() & Network.SetOwnerTransfer() inside on OnStart method on a component, but it feels like boilerplate we should be able to skip.

**Comment by kurozael** [comment]
These options can now be found here ( https://files.facepunch.com/conna/1b0911b1/sbox-dev_Ej9Kk8WU3y.mp4 ) the dropdown is enabled as long as the Network Mode is set to Network Object.
