### ISSUE TITLE
`Assertion Failed in function CSceneSystem::DeleteSceneObject(); !pObj -> !isDeleted()` Error before game crashes

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5765]
### Describe the bug

When using the s&box editor. This error will pop up. Accepting it will crash the game.
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/9f3431ba-ecde-416b-82f6-52ad3874688c)

### To Reproduce

I've got it twice in the last 5 mins of using the editor. So I'd guess it's pretty common. Not a good way to repo.

### Expected behavior

I should not be crashing.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/95300917/094eb3ef-2fb1-42ec-8fc5-8dd8d96bea29)

**Comment by CarsonKompon** [comment]
"I've got it twice in the last 5 mins of using the editor. So I'd guess it's pretty common. Not a good way to repo."
What happened right before you got the error? Were you deleting a GameObject? Opening a scene? More information would be nice

**Comment by Nolankicks** [comment]
> "I've got it twice in the last 5 mins of using the editor. So I'd guess it's pretty common. Not a good way to repo." What happened right before you got the error? Were you deleting a GameObject? Opening a scene? More information would be nice

Iirc I was messing around with prefabs.
