### ISSUE TITLE
Various members missing from SpotLight and PointLight

### ISSUE THREAD

**Issue by Bilbard** [Facepunch/sbox-issues#5771]
### For?

S&Box

### What can't you do?

I am systematically spawning lights, and I need to modify brightness and range on light_spot and light_omni in code. SpotLight and PointLight simply do not have members for these controls.

### How would you like it to work?

They just need those members.

### What have you tried?

I don't think there is a reasonable workaround for this. The only workaround I see is to spawn multiple lights in the scene editor with different values and swap their places to achieve the same effect, but that's really stupid.

### Additional context

I don't need these controls, but it may be worthwhile to also expose linear attenuation/quadratic attenuation (currently there is an attenuation control, but there's only one and it does not specify which of these two it controls), size and falloff.

**Comment by aylaylay** [comment]
These already exist?

**Comment by Nolankicks** [comment]
> These already exist?
> 
> Do you mean lights loaded from map instance?

I think they mean that the light is not given an actual component and it’s just a map object.

**Comment by Bilbard** [comment]
What I mean is, if I create a new light in code (eg. new PointLight()), I then cannot access or change its brightness in code. The member does not exist.

**Comment by Nolankicks** [comment]
> What I mean is, if I create a new light in code (eg. Scene.Components.Create()), I then cannot access or change its brightness in code. The member does not exist. I understand that they can be changed from within hammer or in the scene editor, but I need to be able to do this in code.

Why are you not able to do this? `	
foreach (var light in Scene.GetAllComponents<PointLight>())
		{
			light.Attenuation = 1000.0f;
		}`

**Comment by Bilbard** [comment]
That works. That labelling is very confusing, given that there are two other values with attenuation in the name that exist.

**Comment by Nolankicks** [comment]
> That works. That labelling is very confusing, given that there are two other values with attenuation in the name that exist and this doesn't specify what attenuation it controls.

Can't you just do this? 
![image](https://github.com/Facepunch/sbox-issues/assets/95300917/dc7ad7c5-d697-4598-99c5-58277fda58ed)

**Comment by Bilbard** [comment]
I'm not trying to turn the lights off, I was trying to change the intensity of their output, their brightness. That attenuation member accomplishes that.

**Comment by Nolankicks** [comment]
> I'm not trying to turn the lights off, I was trying to change the intensity of their output, their brightness. That attenuation member accomplishes that.

I'm talking about showing all the methods and members by pressing .

**Comment by Bilbard** [comment]
Yes. Attenuation has no description. It is not obvious that it controls the brightness. Maybe it's a regional thing that attenuation doesn't make sense to me.

**Comment by Bilbard** [comment]
What it's named is beyond the scope here; regardless, thank you for pointing that out.

**Comment by Nolankicks** [comment]
@Bilbard if you want, I think it would be helpful. You should create an api issue which adds a description to that property.
