### ISSUE TITLE
CSS Overflow not working on borders as of today.

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#578]
**Describe the bug**
As of the 3rd of August it seems that borders ignore the overflow property and go beyond the container's boundaries.

**Screenshots**

![image](https://user-images.githubusercontent.com/59583743/128081503-e8bcc0e8-9bf8-4342-80ea-00b1d5ae9a6f.png)
![image](https://user-images.githubusercontent.com/59583743/128081524-bbd808c3-7c60-413d-8e48-b3ee1dada6b7.png)

**Additional context**

It was working fine as of 10pm GMT, it was first noted to have stopped working the next day at 5pm GMT.

**Comment by Alf21** [comment]
Yea, doesn't work anymore for long labels as well since today

![image](https://user-images.githubusercontent.com/11843790/128085562-2cd94897-1035-4322-b7f6-fbb1aba4d120.png)

**Comment by yuberee** [comment]
It seems like this has been fixed. I will be closing this, if anybody experiences it again just reply.
