### ISSUE TITLE
Empty GameObject keeps spawning on Scene every time editor is opened

### ISSUE THREAD

**Issue by ringadongdillo** [Facepunch/sbox-issues#5781]
### Describe the bug

Every time I open my editor, there is a random empty GameObject that is not in the .scene file
![image](https://github.com/Facepunch/sbox-issues/assets/173723830/449a063f-20bb-4031-8ac8-beedef50e9bb)

![image](https://github.com/Facepunch/sbox-issues/assets/173723830/c5691670-8453-45f4-8e0e-c00b2a5ac929)

### To Reproduce

1. I'm not sure
2. It doesn't happen on all my projects
3. But if you want access to my scene just let me know

### Expected behavior

Empty gameobject is not created when editor starts

**Comment by DevulTj** [comment]
Can you provide your project please?

**Comment by ringadongdillo** [comment]
> Can you provide your project please?

Invited you to the project on GitHub.

**Comment by DevulTj** [comment]
This was a fun rabbit hole I went down. Fixed.

**Comment by ringadongdillo** [comment]
Verse 1:
In a world of code and dreams,
Where bugs can make us scream,
You brought a ray of light,
Turned our darkness into bright.

Pre-Chorus:
Tony, we call your name,
In the game of s&box fame,
You fixed what was broken,
Now our gratitude is spoken.

Chorus:
Thank you, Tony, for saving the day,
For making the empty GameObject go away,
Your skill and dedication,
Are the heart of our creation.

Verse 2:
Lines of code, they intertwined,
But you found a way to unwind,
Where others saw frustration,
You brought a new sensation.

Pre-Chorus:
Tony, we celebrate,
Your work that’s truly great,
You’ve set the game world free,
From the endless, empty spree.

Chorus:
Thank you, Tony, for saving the day,
For making the empty GameObject go away,
Your skill and dedication,
Are the heart of our creation.

Bridge:
Now we build and we play,
In a world that you’ve made,
With every fix and every patch,
You’ve created quite the catch.

Chorus:
Thank you, Tony, for saving the day,
For making the empty GameObject go away,
Your skill and dedication,
Are the heart of our creation.

Outro:
So here's to Tony, cheers to you,
For all the magic that you do,
In the land of s&box, you’re the star,
Our hero near and far.

**Comment by badandbest** [comment]
It was reverted so you have to make a diss track now 😂
