### ISSUE TITLE
Skyboxes are rendering weirdly

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5785]
### Describe the bug

Skyboxes seem to be rendering weirdly, you can see the edges of each face. I did not notice this before the reverse Z update.

![image](https://github.com/Facepunch/sbox-issues/assets/5991682/77f7cd33-dc7c-4bfd-8344-f2dd5acae8c1)

### To Reproduce

1. Have a skybox
2. Look at it and see the edges

### Expected behavior

Not see the edges of skybox

### Media/Files

Video of the problem:

https://github.com/Facepunch/sbox-issues/assets/5991682/818b7973-2aca-416e-aa0e-efdce5a9e577

**Comment by garrynewman** [comment]
Do you have SSAO on?

**Comment by Gmod4phun** [comment]
If you mean Ambient Occlusion component on a camera, nope, don't have that. As for other AO options, can't seem to find any, if they exist.

**Comment by samzanemesis** [comment]
Should be good

**Comment by Gmod4phun** [comment]
Still seems to be an issue:
![image](https://github.com/user-attachments/assets/1243db98-1bbc-42ff-bf5d-b21991793b8e)

Harder to see here, but still there
![image](https://github.com/user-attachments/assets/fe2694cc-9291-4d85-b0dd-7a4f3eb295b8)

**Comment by badandbest** [comment]
Can confirm
![image](https://github.com/user-attachments/assets/5cd514b2-5413-473f-9b64-ee0ec63f86c1)

**Comment by Gmod4phun** [comment]
Seems to be fixed now.
