### ISSUE TITLE
Make `Model.GetVertices()` and `Model.GetIndices()` work with terrain's SceneObject

### ISSUE THREAD

**Issue by WheatleyMF** [Facepunch/sbox-issues#5788]
### What it is?

Not sure if it's something possible (and reasonable) to do from technical standpoint, but it'd be nice to have access to terrain's vertex and index buffers. Currently both methods return `null`. 

### What should it be?

Make vertex and index buffers from terrain's SceneObject readable and accessible from code. I've been currently experimenting with an idea of passing position of terrain's vertices into compute buffer for a little project I was working on, (probably not a wise decision) but I can imagine it could be used for some other purposes as well.

I don't know if keeping vertices & indices on CPU is too bad for performance - but if it is, it could be a checkbox option in Terrain component, making it optional.

**Comment by handsomematt** [comment]
Not possible sorry, they don't exist until rendered on GPU as they use a geometry clipmap. You should pass the heightmap to your compute shader instead
