### ISSUE TITLE
Copying Position/Rotation/Scale transforms is unnecessarily complicated

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5792]
### Describe the bug

Currently this feature is right next to the copying of individual properties, which feels not the greatest and is quite confusing. 
It's completely unknown to the user that clicking between the text and the values would even have a context menu without knowing prior. 

https://github.com/Facepunch/sbox-issues/assets/44037603/6e3da1a0-c86b-4d83-a235-600f118a3088

### To Reproduce

See above, the feature request template didn't feel like it fit the issue?

### Expected behavior

I'm not sure how you'd want to go about making this not suck, but in my small opinion I would expand the context menu for the text to consume that entire row, and then maybe put the copying of all transforms and resetting into the GameObject context menu in the hierarchy?

**Comment by solwllms** [comment]
![image](https://github.com/Facepunch/sbox-issues/assets/7689429/4b2f91a6-83ff-42fc-a241-c5578d793541)
Reworked how we're displaying transform to be more consistent with components, chucked in more options for copy/pasting transform in both local and worldspace

**Comment by Retroeer** [comment]
Not sure how I feel about a non-component being given a component look, but I'll probably adapt
