### ISSUE TITLE
Lists/Dictionaries don't automatically update in the inspector

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5794]
### Describe the bug

Unlike other value types, Lists and Dictionaries don't automatically update in the inspector. You have to manually refresh the GameObject by re-selecting it.

If the player, for example, picks up an item, it would be useful to see the list in the inspector update in real-time.

### To Reproduce

1. Create a List with a [Property] attribute.
2. Add an entry with code.
3. The list doesn't update in the inspector unless you manually refresh it.

### Expected behavior

The list in the inspector should immediately update like other value types.

https://github.com/Facepunch/sbox-issues/assets/91832803/8b226b42-2392-4547-94f0-fe2ecbb24498

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/91832803/cf275029-6915-444b-9ea6-7487c5cf6970

[Project.zip](https://github.com/user-attachments/files/16169455/default.Bug.Tests.zip)

**Comment by matekdev** [comment]
This still occurs

**Comment by aylaylay** [comment]
Fixed

**Comment by ryleigh** [comment]
I'm getting a similar issue, not when changing the list with code, but when using the context menu "Paste as" or "Reset to default". The list doesn't update until the component is minimized and re-opened or the gameobject reselected.

https://github.com/user-attachments/assets/4f0749ac-1b3f-4422-9919-dcbdf677b8ab
