### ISSUE TITLE
Cannot change the compiler settings of a project

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#5808]
### Describe the bug

For some reason the save button in Compiler Setup does not work.

### To Reproduce

1. Open any project
2. Click on Project -> Settings -> Compiler Setup
3. Change any setting (e.g., Root Namespace or No Warn) and press Save
4. Close the window and open it again
5. The compiler settings have been reverted

### Expected behavior

Changes here should be saved just like on any other page of the Project Settings.

**Comment by solwllms** [comment]
Cheers for flagging this, sorted now
