### ISSUE TITLE
[Inspector] Add Prefab Path Property under Open prefab button

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5809]
### For?

S&Box

### What can't you do?

Currently when you have a Prefab selected in the scene hierarchy, all you will have in the inspector is a button to open the prefab and maybe some prefab variables. There currently isn't a way to change the path of the prefab that's being referenced without manually modifying the scene file in a text editor which isn't a problem until you relocate the prefab to another folder then open the scene that referenced that prefab with the old path which of course wont show up. Thus requiring you to either place the prefab again in the very same spot or fix the prefab path in the scene file manually via text editor.

### How would you like it to work?

 Have the path to the prefab be shown & changeable in the inspector under the open prefab button. And also have the path shown in place of the open prefab button when the prefab itself that's being inspected is missing.

### What have you tried?

- Fixing the path manually in the scene file via text editor.

- Placing the prefab in the same spot of the missing prefab.

**Comment by solwllms** [comment]
You can do this now
![image](https://github.com/user-attachments/assets/b62d4404-2cca-41ae-acf0-609e6dd412d6)
