### ISSUE TITLE
Online api documentation

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#581]
**What can't you do?**
See classes of  `Sandbox` namespace

**How would you like it to work?**
Have `Sandbox` in `API DOCUMENTATION` wiki section

**What have you tried?**
Looking at `sandbox` repo

**Comment by WYVERN2742** [comment]
The `Sandbox` namespace is used as part of the `base` addon within your `\sbox\addons` folder. Generally you can just open it up in an IDE and take a look around at all the definitions.

**Comment by Rohansi** [comment]
There's already some on the wiki but it's not complete. https://wiki.facepunch.com/sbox/

**Comment by robotboy655** [comment]
I might be too early to document stuff on wiki as its constantly changing right now. Using an IDE like Visual Studio works too, most of the important stuff should already have C# autodoc comments.

**Comment by thegrb93** [comment]
> **What can't you do?**
> See classes of `Sandbox` namespace

You can use the visual studio object browser which is helpful.
