### ISSUE TITLE
Category Emoji break visually, depending on OS

### ISSUE THREAD

**Issue by Nekkowe** [Facepunch/sbox-issues#582]
**Describe the bug**  

The emoji that act as category filters in the Games menu don't pull from twemoji or the like.  
This can lead to missing categories and ZWJ sequences (e.g. Female Astronaut) breaking apart.  

**To Reproduce**  

1. Install S&box on e.g. Windows 7/8  
2. Start S&box  
3. Go to 'games'  
4. See error in the Category pane  

**Expected behavior**

Consistent display of Category pane between platforms

**Screenshots**

Win 8.1:  
![image](https://user-images.githubusercontent.com/28980049/128211058-90b70027-4387-4f36-b7f6-65baa02a97ce.png)

Win 10:  
![image](https://user-images.githubusercontent.com/28980049/128211308-d9f0172b-03f8-47b0-aca4-a08839b82ca6.png)

**Additional context**

Rendering the category emoji as SVGs should address the issue.  
[Twemoji](https://twemoji.twitter.com/) offers open-source SVGs for the entire set of characters.  

Right now, S&box is presumably relying on OS-side unicode support by displaying them as text characters. This approach breaks in the absence of an emoji font, the presence of a *different* emoji font, or general lacking support for multi-coloured characters.

**Comment by Ryhon0** [comment]
SVG fonts are not supported. I've gotten SBIX fonts to work. Including a default emoji font would be a good option but supporting font fallbacks (#381) would would be needed unless the emojis are packed with the default fonts

**Comment by Rohansi** [comment]
We may include an emoji font later but nobody is going to bend over backwards to support Win 7/8 because they aren't supported anymore.

**Comment by walllable** [comment]
How well are the emoji supported on Proton? That could be another reason to include a font if it's not well supported there.

**Comment by SupinePandora43** [comment]
> How well are the emoji supported on Proton? That could be another reason to include a font if it's not well supported there.

Emojis is the last thing you will care about when running on proton.

**Comment by Nekkowe** [comment]
To clarify why this was closed for anyone notified of it:
The games list no longer uses emoji categories.
It looks like this now, and works perfectly fine on the mentioned systems:
![image](https://user-images.githubusercontent.com/28980049/158818881-ea85a558-d514-40de-b557-4ad45509e645.png)
