### ISSUE TITLE
Vector2Int x and y values won't serialize to JSON

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5821]
### Describe the bug

When I try to serialize a Vector2Int (named "Position") to JSON, I get this:
```json        
"Position": {
    "Length": 2,
    "LengthSquared": 4
},
```

### To Reproduce

Try JSON serializing a Vector2Int

### Expected behavior

The x and y fields should be serialized. Length and LengthSquared should not be serialized, as these are calculated from x and y.

### Additional context

You could probably fix this just by making x and y properties instead of fields. And maybe add [JsonIgnore] to Length and LengthSquared while you're at it, but I just noticed that Vector3 has [JsonIgnore] over LengthSquared but not Length, so I dunno.

**Comment by MD485** [comment]
I think Vector2Int and Vector3Int are a little undercooked right now.
![image](https://github.com/user-attachments/assets/c5cd73a0-490d-4821-9e21-888901a58ca8)
![image](https://github.com/user-attachments/assets/ff54be53-e81c-4ec2-bf08-2c2b54ec39df)

Obviously #5606 which you also commented on:
![image](https://github.com/user-attachments/assets/8de62465-9655-4354-bc54-d71cb725eee1)
There isn't editors for them either currently.
