### ISSUE TITLE
Add Terrain custom shader

### ISSUE THREAD

**Issue by dictateurfou** [Facepunch/sbox-issues#5827]
### For?

S&Box

### What can't you do?

I would like to add a custom shader to the terrain. This would allow me to get good results quickly without needing to paint everything and take into account the variation of a slope... It would enable a lot more possibilities than currently.

### How would you like it to work?

Also, please replace Terrain.mat with terrain.shader and add the default shader used

### What have you tried?

I tried to create a terrain with variations using the shader (to avoid texture repetition and add a variant for the slopes)

**Comment by handsomematt** [comment]
I've added material override for the component. If you're writing custom shaders for it I'm gonna be shuffling stuff around still into better structs / buffers, nothing that isn't too easy to work around though.
