### ISSUE TITLE
sbox.game: Screenshot thumbnails sized incorrectly 

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5833]
![image](https://github.com/user-attachments/assets/e590b18f-19a3-458c-95bd-9dca36402439)

Not sure if this happened recently, but I guess these should  `background-size: cover;`

**Comment by MrBrax** [comment]
this was a thing for at least 6 months, does not seem to be fixed?

**Comment by DevulTj** [comment]
I think I know what it is, will fix

**Comment by DevulTj** [comment]
There, should be all good now

![image](https://github.com/user-attachments/assets/1ab3d1bf-fbdd-4f79-8bcf-ef5fed146e13)
