### ISSUE TITLE
Going in and out of fullscreen (F3) makes hierarchy window behave incorrectly

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#5835]
### Describe the bug

When going into fullscreen mode on the F3 button (game doesn't have to be started on F5) and then back, anything you click in hierarchy becomes deselected instantly, removing your ability to do anything. There is a 1/10 chance your selection stays, but clicking anything in the object's inspector will deselect it again.

You can remove the effect of the bug by switching to the "Game" tab without being in fullscreen, that removes the effect (you can switch back to scene view afterwards).

### To Reproduce

1. Go fullscreen with F3
2. Go out of fullscreen with F3 again
3. Click on anything in the hierarchy
4. The selection doesn't stay

To "undo":
1. Go to the "Game" tab
2. The behavior is no longer present

### Expected behavior

It should not do that

### Media/Files

https://github.com/user-attachments/assets/71fd7728-bbb5-4bef-9ff9-ecc9e6ed6d38

**Comment by DevulTj** [comment]
Yep this is something I've noticed and only now just realized it's the fullscreen stuff causing it

**Comment by rzkid** [comment]
Seems to be fixed, thanks!
