### ISSUE TITLE
When clicking on an asset to 'view online' it brings you to asset.party and not sbox.game

### ISSUE THREAD

**Issue by Gamblingpizza** [Facepunch/sbox-issues#5838]
### Describe the bug

like the title says when you are in the asset browser if you right click on an asset and click 'view online' it brings you to a dead asset.party link instead of sbox.game.

### To Reproduce

1. go to asset browser
2. find an asset
3. click 'view online'
4. get wrong site

### Expected behavior

It should bring you to the sbox.game page instead.

**Comment by DevulTj** [comment]
I'm surprised your links are dead for asset.party, we are serving a redirect for this. But I've fixed this anyway.
