### ISSUE TITLE
dedicated server immediately crashes

### ISSUE THREAD

**Issue by willox** [Facepunch/sbox-issues#584]
**Describe the bug**
When you run `sbox.exe -dedicated` the game will crash. Seems like something trying to check game ownership with steam is failing. A bunch of people have mentioned this on the discord so I think it might happen for everybody.

(i just patched out the steam api checks locally and now it works)

**Comment by willox** [comment]
It seems like this doesn't happen on dedicated servers. I'm thinking it might be something to do with the way modules are loaded multiple times when on a listen server.

**Comment by garrynewman** [comment]
Does it make a mdmp?

**Comment by willox** [comment]
[sbox_2021_0804_191711_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/6933535/sbox_2021_0804_191711_0_accessviolation.zip)

**Comment by willox** [comment]
It's fixed

**Comment by garrynewman** [comment]
thanks <3

**Comment by Ryhon0** [comment]
Doesn't seem to crash immediately anymore but now it prints some warnings, likely unrelated and crashes a second later.
![Untitled](https://user-images.githubusercontent.com/21126698/128510187-77aceebf-7882-4e3c-9367-b915bd845b91.png)
Crash dump: [sbox_2021_0806_142149_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/6945469/sbox_2021_0806_142149_0_accessviolation.zip)

**Comment by garrynewman** [comment]
This looks like a lightcookie crash - is this known @samzanemesis?

**Comment by samzanemesis** [comment]
Yep, I am aware of it and tackling it now
