### ISSUE TITLE
Input.ReleaseAction Doesn't release mouse buttons

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#5844]
### Describe the bug

Doing something like `Input.ReleaseAction("Attack1");` doesnt release click when it should.
Even releasing everything with Input.ReleaseActions() doesnt release the mouse button

### To Reproduce

1. On input.pressed attack1 do input.release attack1 (I'm doing it in UI)
2. check if input.down attack1 is true next FixedUpdate. (Im doing this in a component)

### Expected behavior

it should release attack1 until it is pressed again.

**Comment by Louis-Ladd** [comment]
bump 🗡️

**Comment by DevulTj** [comment]
This wasn't exclusive to just mouse buttons - this happened in all cases when doing something like that in any update context, and checking in another context (like fixed updates). 

Pushing a fix now.
