### ISSUE TITLE
Scene view doesn't stay where I put it between editor starts

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#5845]
### Describe the bug

Scene view doesn't stay where I put it between editor starts.
I have my layout like this:
![image](https://github.com/user-attachments/assets/b23777f1-93a2-492a-bfc1-7fe7902b3d57)
But whenever I start the editor it looks like this:
![image](https://github.com/user-attachments/assets/585a79fd-4da9-408c-abc2-30cc6612befe)
So I have to do this every time:
![sbox-dev_Qq472Vaxuo](https://github.com/user-attachments/assets/e25a5199-2e0e-4e1c-9ca2-e3065bab41d5)

### To Reproduce

Dock your scene view window somewhere that isn't the same tab row as the game window.
Restart your editor.
Your scene view window is now on the same tab row as your game window.

### Expected behavior

I would expect scene view tabs to show up where I put them last time the editor was open.

**Comment by solwllms** [comment]
Not tried docking in funky ways but should be good now I think, same logic as scene tab now anyway.

**Comment by ShadowBrian** [comment]
This appears to be fixed! Thanks!
