### ISSUE TITLE
SoundHandle.Stop fadeTime parameter does nothing

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5846]
### Describe the bug

Stopping a sound is instant, instead of fading out if fadeTime is specified.

### To Reproduce

1. Play a sound
2. Stop the sound with a fadetime
3. Notice it stops immediately

### Expected behavior

The sound should fade out with respect to the fadeTime.

**Comment by matekdev** [comment]
This is still the case, can this get looked at?

**Comment by Gmod4phun** [comment]
Coming back to this again, maybe also instead of just providing the time, it would be handy if we could provide a curve for the fading, too.

**Comment by aylaylay** [comment]
fade time on stop is now supported, also added a fadeout curve to control it
