### ISSUE TITLE
Dedicated Scene tab in sbox.game / asset.party

### ISSUE THREAD

**Issue by ItsNotPaths** [Facepunch/sbox-issues#5849]
### For?

S&Box

### What can't you do?

view scenes in a dedicated tab on the site, instead of sift through assets

### How would you like it to work?

a dedicated tab just like maps

### What have you tried?

n/a

### Additional context

level creation for games has moved from hammer to the scene system, which means making maps for games other people make will as well. this means we will move from loading hammer maps to loading scenes which contain the gamemode objects (things coded for the gamemode, jump pads, weapon pads, etc). new users should see these scenes as the new "maps" and should be able to search them for use.

**Comment by CarsonKompon** [comment]
The Asset page has tabs for different file extensions, so you can browse scenes via [this link](https://sbox.game/t/asset/?q=type%3Aasset%20ext%3Atmat%20ext%3Ascene).
![image](https://github.com/user-attachments/assets/cef1d5be-e34a-4519-b57c-541e407f5695)

**Comment by ItsNotPaths** [comment]
a new player will never find this. nor will they see "maps" and know they arent supposed to choose that. they will see scene and be like "scene, i dont want a scene i want a map"

**Comment by ItsNotPaths** [comment]
@CarsonKompon please reread my post, i believe you did not read it fully. putting scenes (the new maps) behind the assets tab is pointless and poor obfuscation that ruins it for the average player browsing asset party. since scenes have replaced maps, it would make sense to swap them. maps in assets and scenes in a dedicated tab. behind assets is not a dedicated tab

**Comment by Retroeer** [comment]
Scenes are not maps and they should not be maps until the foreseeable future. A "new player" should never even really be browsing asset party aside from games, otherwise they're probably looking at asset party for maps and models for something like a sandbox gamemode  
And if you mean a new developer, I'd hope they'd be able to explore a website :p

**Comment by ItsNotPaths** [comment]
a new player may browse for maps (scenes for say, a multiplayer shooter) to play with friends before loading it up in game since its easier to browse on the site. if i want to make a level for a game that has the games' custom objects (jump pads, weapon spawns, doors, etc) that needs to be done in scene and cannot be done in hammer anymore, thus scenes have replaced maps in that regard.

**Comment by Retroeer** [comment]
Hammer will be getting scene prefabs, this situation is only a temporary issue.
Once scene mesh actually is capable of taking over Hammer then I could maybe see the need for this, but even then iirc scene mesh might just get saved as a vmap letting the map tab both have legacy and "modern"

**Comment by ItsNotPaths** [comment]
> Scenes are not maps and they should not be maps until the foreseeable future. A "new player" should never even really be browsing asset party aside from games, otherwise they're probably looking at asset party for maps and models for something like a sandbox gamemode And if you mean a new developer, I'd hope they'd be able to explore a website :p

https://sbox.game/news/september-update-9209a15d

nice prediction, try using some brainpower next time
