### ISSUE TITLE
Curve type support for .asset

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#585]
**What can't you do?**
Currently curves cannot be added to custom assets.

**How would you like it to work?**
In HLA, some entities have a curve property that looks like this:
![curve](https://user-images.githubusercontent.com/65136069/128239643-f0d14ef3-e62c-458c-9636-8b7aff2ae334.png)

It'd be nice if they could be used in .asset files, maybe with a struct/class for getting their values. This would probably be useful for a bunch of cases (vehicle handlings in my case).

**What have you tried?**
Adding one to an .asset file by setting the property type to ( curve ), but only an input box is shown in the inspector tool.

**Comment by robotboy655** [comment]
This should now be fully supported via the `FGDCurve` class, used as such:
![image](https://user-images.githubusercontent.com/3299036/134527776-bea9bd06-e107-4735-aa66-d339023ebb52.png)


Let me know if the class is missing something you'd need, otherwise feel free to close this issue.

**Comment by krotter0** [comment]
It shows up in Hammer when it's used as an entity property, but I can't get it to show up in the inspector for assets.
I didn't check its' functionality yet.

**Comment by robotboy655** [comment]
It definitely works on my end:

![image](https://user-images.githubusercontent.com/3299036/134568156-087ff82a-0771-46b3-baae-6f618581d3d5.png)

Did you make sure you have ran the gamemode associated with the asset? Are you on the latest version of the game?

**Comment by krotter0** [comment]
Sorry, my bad. I left out the editor part since I've just copied it over from the hammer fgd. I'll test it more thoroughly later today.
