### ISSUE TITLE
Add more granularity to GameObjectSystem.Stage

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#5851]
### For?

S&Box

### What can't you do?

Listen Before/After OnUpdate/OnFixedUpdate.

### How would you like it to work?

I'd like to have some more granular and clearer options: BeforeUpdate/AfterUpdate, BeforeOnFixedUpdate/AfterOnFixedUpdate.

### What have you tried?

The existing stages don't work for me unless I'm doing something dumb.

**Comment by MD485** [comment]
Erm so you can kinda do this already.
`OnComponentUpdate` and `OnComponentFixedUpdate` exists, these are delegates you can append to, allowing for "AfterUpdate" functionality pretty easily.

`OnComponentFixedUpdate += AfterUpdate;` and wa-blamo.

You could also stipulate that people should always use `base.OnUpdate()` before extending a class, but I imagine you guys will shoot that down.

The only thing preventing full functionality of what's requested is if you reassign `OnComponentUpdate`, that does not work.
`OnComponentUpdate = ExperimentalUpdate` essentially works the same way as `OnComponentUpdate += ExperimentalUpdate`.

I believe this is a bug/design oversight? But it could also be a safety measure put intentionally to avoid people accidently disabling their update loop.

I don't really agree with cluttering the API with Before/After Update methods for the niche scenarios which they are helpful.
I understand that even with full functionality my suggestion has the limitation of you having to manually write:

```cs
OnComponentUpdate = null;
OnComponentUpdate += PreUpdate;
OnComponentUpdate += OnUpdate;
OnComponentUpdate += PostUpdate;
```
In start/awake or something similar, and thus requiring people to always call `base` if those methods are extended.
But I believe given that flexibility is the least invasive solution to this problem.

Either that or an attribute with a params field allowing you that customisation in the base class.
`[EventOverride("OnComponentUpdate", "PreUpdate", "OnUpdate", "PostUpdate")]`

```cs
[AttributeUsage(AttributeTargets.Class)]
public class EventOverrideAttribute : Attribute
{
    public string Value { get; set; }
    public string[] methodList { get; set; }

    public CategoryAttribute(string value, params string[] methods)
    {
        Value = value;
        methodList = methods;
    }
}
```
Then putting some backing logic in for the codegen.

This would probably be the least invasive solution, provides function without being intrusive and still being somewhat easy to remove, I'm not going to lie though even this compromised solution I don't like too much.

**Comment by dch-GH** [comment]
> I don't really agree with cluttering the API with Before/After Update methods for the niche scenarios which they are helpful.
> I understand that even with full functionality my suggestion has the limitation of you having to manually write:

I believe you may have not read my issue closely. Stage is an enum, it wouldn't "clutter the API" with methods. They would add 4 new members to the enum... that's it. 

Please refer to this doc page for more information on the issue I am talking about:
https://docs.facepunch.com/s/sbox-dev/doc/gameobject-systems-6vakGETtA4

**Comment by MD485** [comment]
You are correct I've read your issue incorrectly.

**Comment by Nolankicks** [comment]
I think it would be very helpful to have a stage for before and after scene start.

**Comment by dch-GH** [comment]
> I think it would be very helpful to have a stage for before and after scene start. Using the constructor only fires at game start. Not on scene change.

I tested this myself out of curiosity and yep, it only works once since `GameObjectSystem`s are created once and then last throughout the lifetime of the game. I think this could be useful to have too.

**Comment by chrisspieler** [comment]
> I think it would be very helpful to have a stage for before and after scene start. Using the constructor only fires at game start. Not on scene change.

I'd like for the ability to run code at the point where everything's been deserialized but no OnAwakes have been called yet. Not sure which of kicks' proposed stages that would be.

**Comment by garrynewman** [comment]
I think this is done now, any more specific stages that people want I would suggest an issue to justify them

**Comment by dch-GH** [comment]
> I think this is done now, any more specific stages that people want I would suggest an issue to justify them

Thanks, this has fixed my exact use case. :)
