### ISSUE TITLE
OnCollisionUpdate doesn't work.

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#5854]
### Describe the bug

```cs
namespace Sandbox;

public sealed class MyComponent : Component, Component.ICollisionListener
{
    public void OnCollisionUpdate( Collision collision )
    {
        Log.Error( "this won't be printed" );
    }
}
```

### To Reproduce

Run this repro project:
https://github.com/dch-GH/OnCollisionUpdate_broke

### Expected behavior

It should work

### Media/Files

My output when running the repro project.
Expected behavior is that "Update" should be spewed in the console.
![image](https://github.com/user-attachments/assets/8ec23abf-719e-474a-a153-0e6b878c75b6)

**Comment by aylaylay** [comment]
Thanks, I'll check it out

**Comment by aylaylay** [comment]
I don't think this was ever hooked up btw

**Comment by dch-GH** [comment]
> I don't think this was ever hooked up btw

I thought I was crazy but I remember it not working months ago. Thanks

**Comment by aylaylay** [comment]
garry added this, you can enable with CollisionUpdateEventsEnabled
