### ISSUE TITLE
Colliders dont update their transform relative to parents if parent is non-static

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5855]
### Describe the bug

Let's hope the title makes sense. Basically when you have a child collider following a parent collider that is not static, changing the child's transform relative to the parent does not move its physics where it should be. If the parent collider is static, it does work as intended.

### To Reproduce

1. Have a collider
2. Add another child collider
3. Play scene, move child collider
4. If the parent collider is not static, the child's physics won't correctly adjust its position

### Expected behavior

The child collider should move with the parent with respect to updating its relative transform.

### Media/Files

Video of the issue:

https://github.com/user-attachments/assets/5a317127-2f8b-4485-ba5d-b5d794135d51

Here is the repro scene
[repro_physics_scene.zip](https://github.com/user-attachments/files/16288510/repro_physics_scene.zip)

**Comment by aylaylay** [comment]
thanks for the repro

**Comment by aylaylay** [comment]
Works now

https://github.com/user-attachments/assets/14f4b170-ab0f-4067-b121-1383262be140

**Comment by Gmod4phun** [comment]
Thank you :)
