### ISSUE TITLE
Ragdoll freezes in Modeldoc simulation when using Physics Shapes

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#5856]
### Describe the bug

My ragdoll that uses physics shapes freezes if it stops moving in the modeldoc physics simulation, behavior similar to the "sleeping" physics optimisation method.
You can cause this more reliably by interacting with it while it's falling, sometimes the ragdoll explodes first, video explains the problem.

This seemingly does not happen if you're using another method for physics such as many "HullFile"s.
This seemingly does not happen to the citizen.

I'm told this was caused by something called "Izabu".

### To Reproduce

Download the files and place the models folder in your assets folder.
1. Try the physics simulation on the "buge_shapes" and throw it around until it stops
2. Try the physics simulation on the "buge_hulls" and throw it around until you stop

### Expected behavior

It should not be freezing.

### (Turn on audio, very important)

https://github.com/user-attachments/assets/5898cedd-2a6e-4a16-aa2b-3c20808f1116

### DOWNLOAD:

[models.zip](https://github.com/user-attachments/files/16289537/models.zip)

### Additional context

Yesterday I was using the ragdoll for a tutorial series and it was working, today when I picked back up the recording I couldn't work on it.

**Comment by Grodbert** [comment]
Did a little more tests, it seemingly works in scene and presumably in-game as well. (pardon the giffard)
![in scene](https://github.com/user-attachments/assets/c2258331-afbc-4792-87bd-77730dd62d2b)

So it's just in modeldoc that it's broken, also it's not frozen completely, but more like stuck in super dense molasses:
![molasses](https://github.com/user-attachments/assets/a50bb547-1012-46d6-94da-549ab694ea12)

**Comment by aylaylay** [comment]
This should be fixed now

**Comment by NotGaylien** [comment]
Here on GroggyBeers behalf, works perfect now! all good!

https://github.com/user-attachments/assets/f5889dd9-4340-4a39-80f7-52a8126f5b58

**Comment by aylaylay** [comment]
fantastic
