### ISSUE TITLE
s&box editor preferences are not saving

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#5857]
### Describe the bug

When I change my code editor to `Visual Studio Code`, it does not remember this option on the next launch of the s&box editor.

### To Reproduce

1. Change editor settings to `Visual Studio Code`
2. Relaunch
3. Notice that it changed back to `Visual Studio`

### Expected behavior

^

**Comment by dch-GH** [comment]
I believe this is also happening to the Layout too. Layout is set to the default every time I open a project.

**Comment by matekdev** [comment]
Have the changes been pushed yet? I'm still encountering this.

**Comment by Gmod4phun** [comment]
Has been fixed since yesterday, at least for me. IDE stays the same, layout too

**Comment by matekdev** [comment]
> Has been fixed since yesterday, at least for me. IDE stays the same, layout too

1. I launch up the s&box game editor
2. Click preferences, change it to Visual Studio Code
3. Close the entire editor
4. It does not save

I'm on staging and tested it this morning. Anyone else also experiencing this?

**Comment by badandbest** [comment]
I'm still experiencing this.

**Comment by solwllms** [comment]
@badandbest @matekdev The change is in yeah, must be something else going on here breaking it for you guys. I'll have another look to see if there's a different issue causing this I can repro.

Few things if you wouldn't mind:
- I assume opening the solution does still open Visual Studio?
- Anything in the log when reopening the editor? "X not found", "X not installed" etc
- Is the "CodeEditor" setting being written properly to `[steam path]\steamapps\common\sbox\config\tools.json`?
The value should be saved when you close the editor, does it get overwritten/reset at any point?

**Comment by badandbest** [comment]
I'll check these right now and get back to you

**Comment by badandbest** [comment]
* When I change my preferences they only last for the current session.
* Nothing in the logs I can find. But here it is anyway. 
[Log.log](https://github.com/user-attachments/files/16332285/Log.log)
* Notepad++ tells me tools.json is being modified by another program. But I was keeping my eye on the "CodeEditor" value and it never changed. Maybe this video tells you anything?

https://github.com/user-attachments/assets/baa5950f-dc1c-461a-ba64-9177b2afa69e

**Comment by solwllms** [comment]
Cheers for the info, looks like my cockup.

I've pushed a fix which should be live now if you can give this another whirl

**Comment by badandbest** [comment]
It works now. Thanks a million. This issue was bugging me a lot.

**Comment by matekdev** [comment]
thank you
