### ISSUE TITLE
Prefabs in GameObject properties of GameResources are not being saved

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5858]
### Describe the bug

When I have a GameResource with a GameObject property, if I set that property to a prefab and restart the editor, the prefab does not appear in the property when I look at the GameResource again.

### To Reproduce

1. Open the attached project
2. Open `data/test.example` in the inspector
3. Set the "Prefab" property to `prefabs/example.prefab`
4. Save the GameResource
5. Restart the editor
6. Re-open the project
7. Open `data/test.example` again
8. See that the "Prefab" property is unset.

### Expected behavior

The prefab property should retain its value after restarting the editor.

### Media/Files

[gameresource_prefab.zip](https://github.com/user-attachments/files/16301209/gameresource_prefab.zip)

**Comment by DevulTj** [comment]
This'll be me.

**Comment by Nolankicks** [comment]
I've also noticed I don't have a save button I can press.

**Comment by Nolankicks** [comment]
Discard this, you can serialize System.Type

**Comment by DevulTj** [comment]
I'm confused as hell lol

**Comment by Nolankicks** [comment]
> I'm confused as hell lol

I was not able to save a GameResource because I had a Type property.

**Comment by DevulTj** [comment]
So you're still unable to save a gameresource because it's trying to serialize System.Type? We should be supporting that now so make a new issue if that's the case

**Comment by Nolankicks** [comment]
Just created the issue, turns out it doesn't have anything to do with System.Type, but has something to do with having a CustomEditor for a class.
