### ISSUE TITLE
Lighting/reflection flicker after loading a second map instance

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5859]
Happens after loading a second map instance - so a good repro is to open [HC1](https://github.com/Facepunch/sbox-hc1) into the main menu then open a match on refinery. Look at the video below.

https://github.com/user-attachments/assets/9607067e-1fb4-4f62-a7f3-7b547cd1cc19

**Comment by aylaylay** [comment]
Should be fixed now
