### ISSUE TITLE
Can't load a custom asset

### ISSUE THREAD

**Issue by LunaRyuko** [Facepunch/sbox-issues#586]
**Describe the bug**
When I try to use `Resource.FromPath` to load an asset, I get null, no matter which path I try.

**To Reproduce**

Use `Resource.FromPath` to load the asset and try to access info.

**Expected behavior**

In the screenshot below, WeaponDef should have been not null and the weapon's world model would have been set to the SMG (as I've set it in the asset)

**Screenshots**
![devenv_aVWgVJY8ZV](https://user-images.githubusercontent.com/10626859/128240726-b42585f6-6b10-46bb-a7c0-982681fc96c2.png)
![sbox_XE7De3kbU6](https://user-images.githubusercontent.com/10626859/128240734-d66b0c11-3486-4eb5-ba39-d4f59ba154dd.png)
![explorer_sSP1QuN8tN](https://user-images.githubusercontent.com/10626859/128240832-401323ce-9c9f-4044-a4c6-3aa666513174.png)

**Additional context**
I've followed the wiki article (https://wiki.facepunch.com/sbox/Custom_Asset_Types) on this.

**Comment by handsomematt** [comment]
Asset system looks for compiled files I think, your file needs compiling so it's `default.weapondef_c` - although inspector should do this automatically.

**Comment by LunaRyuko** [comment]
![image](https://user-images.githubusercontent.com/10626859/128244749-6a5c8418-6faf-4f44-a31e-261969138d01.png)
It says it's not a compileable resource for some reason.

**Comment by DoctorGurke** [comment]
Open and resave in the inspector. That should compile it

**Comment by LunaRyuko** [comment]
I tried that multiple times, it didn't work.

**Comment by xrayhunter-git** [comment]
Same Issue, I'm unable to do pretty much the same objective that @LunaRyuko is trying to do.

**Comment by DoctorGurke** [comment]
Pretty sure the extension is limited to 8 chars

**Comment by xrayhunter-git** [comment]
> Pretty sure the extension is limited to 8 chars

Not true, I have `.npc` otherwise this would've worked.

**Comment by DoctorGurke** [comment]
Doesn't make my statement untrue but at least that's not what's causing your problem

**Comment by xrayhunter-git** [comment]
I would say that `Resource.*` is not setup fully or that it is looking at the wrong folder directory paths, if it doesn't look in the `Mounted`. Then that needs to be specified in the wiki (https://wiki.facepunch.com/sbox/Custom_Asset_Types) .

**Comment by StinkyFeets** [comment]
@xrayhunter-git I saw your post in the s&box discord. You checked for the .resourceAsset file with the `FileSystem` to confirm that it exists. I looked under the hood and it seems like it only checks for file extensions that end in `_c`. It doesn't look like it's going through the file system when you call `Resource.FromPath`. Others have said that the extension is limited to a length of 8 characters, otherwise you won't be able to compile the file. That seems consistent with both the original post and your problem.

If you shorten the file extension and it still doesn't work, I can try to help you figure out what's going on.

**Comment by xrayhunter-git** [comment]
> @xrayhunter-git I saw your post in the s&box discord. You checked for the .resourceAsset file with the `FileSystem` to confirm that it exists. I looked under the hood and it seems like it only checks for file extensions that end in `_c`. It doesn't look like it's going through the file system when you call `Resource.FromPath`. Others have said that the extension is limited to a length of 8 characters, otherwise you won't be able to compile the file. That seems consistent with both the original post and your problem.
> 
> If you shorten the file extension and it still doesn't work, I can try to help you figure out what's going on.

Interesting... So I have a `test.npc` that is supposed to have all the information that my gamemode will have about that specific npc... It created the `_c` next to the file. And I can see the asset in the `Asset Browser`... but my gamemode cannot find it. 

If I cannot find a fix for this, I'm just gonna use JSON files or parse my own file format to solve this issue.

**Comment by garrynewman** [comment]
Did you define an asset class?

**Comment by xrayhunter-git** [comment]
> Did you define an asset class?

Asset:
```cs
using Sandbox;
using System.Collections.Generic;

namespace terrydungeons.Core.NPC
{
	[Library("NPC"), AutoGenerate]
	public partial class NPCGameAsset : Asset
	{
		[Property]
		public string Title { get; set; }

		[Property, ResourceType("vmdl")]
		public string Model { get; set; }

		[Property]
		public string JsonData { get; set; }

		public static IReadOnlyList<NPCGameAsset> All => _all;
		internal static List<NPCGameAsset> _all = new();
		protected override void PostLoad()
		{
			base.PostLoad();

			if ( !_all.Contains( this ) )
				_all.Add( this );
		}
	}
}
```

Entity Handler:
```cs
[ServerCmd("td_npc_spawn")]
		public static void DevSpawnNPC( string name )
		{
			if ( !ConsoleSystem.Caller.IsListenServerHost )
				return; // You need to be the host!

			string targetPath = $"config/{name}.npc";

			Log.Info( $"`{targetPath}` Exists?: {FileSystem.Mounted.FileExists(targetPath)}" );
			var NPCResource = Resource.FromPath<NPCGameAsset>( targetPath );
			if ( NPCResource == null )
			{
				Log.Error( $"Failed to spawn NPC: `{name}` - because it doesn't exist!" );
				return;
			}
			Log.Info( $"Spawning: `{name}` from {ConsoleSystem.Caller.Name}" );
			
		}
```

**Comment by garrynewman** [comment]
Try lowercasing "NPC" in your library name

**Comment by xrayhunter-git** [comment]
No difference.

**Comment by garrynewman** [comment]
Try looking in `NPCGameAsset.All` - does that have any assets loaded?

**Comment by xrayhunter-git** [comment]
Added a
```cs
Log.Info( $"{NPCGameAsset.All.Count}" );
```
Result:
```
0
```

**Comment by garrynewman** [comment]
Let me go through the code to see what I can do to make the case not important.

**Comment by garrynewman** [comment]
I committed some stuff that should make this problem go away
