### ISSUE TITLE
Ambient Occlusion shows outline for objects in front of transparent materials

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5862]
### Describe the bug

With Ambient Occlusion (any settings, even everything set to 0), when looking at object A, behind it is object B (transparent), and behind it is object C, you can see an outline of object A with the color of object C.

![image](https://github.com/user-attachments/assets/859b0875-221d-4dd1-a55f-bfd4c03ded9c)

### To Reproduce

1. Have a white object (box, plane)
2. Put a transparent plane infront of it
3. Put a dark object in front of it
4. Look at it with AO enabled to see an outline

### Expected behavior

There should be no visible outline

### Media/Files

Here is a showcase of the issue:

https://github.com/user-attachments/assets/6b58bebe-5269-45fb-a056-c946765d9f26

Here is where I first noticed it in a regular use case:

https://github.com/user-attachments/assets/b51bb4e4-3181-4ff8-b27f-9e816b1ee5c0

**Comment by mdvFacePunch** [comment]
This was fixed with outline fix
