### ISSUE TITLE
With SSAO enabled, large parts of the world are black depending on camera direction

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5863]
### Describe the bug

An enormous black plane appears when using ambient occlusion in a large world.

https://github.com/user-attachments/assets/dbfb213c-bc0e-4cbd-946c-7f58579339f9

### To Reproduce

1. Open scene with a large playable area (e.g. something with terrain)
2. Ensure that your camera has an Ambient Occlusion component
3. Zoom far out so that you can see the whole scene
4. See that a plane of blackness sweeps across the world as you turn your camera

### Expected behavior

Ambient occlusion should not break large open scenes.

### Additional context

I don't think this issue occurred yesterday, and so I think it was introduced with today's changes to SSAO.

**Comment by Nolankicks** [comment]
Bump 🙏

**Comment by SwagAccount** [comment]
bump 🙏- kicks

**Comment by chrisspieler** [comment]
This is fixed now, thanks!
