### ISSUE TITLE
I would really like it to have some described use cases as I have no idea how to use this

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5864]
### Location

https://sbox.game/api/Sandbox.SceneUtility/MakeIdGuidsUnique

### Summary

I need to use this to make all the guids unique before I duplicate something.

**Comment by MD485** [comment]
A lot of our documentation is lacking, it's part of the growing pains of working within an engine in development.

Looking at the source code I believe the JsonObject you pass in is mutated, so you can just keep using that.
The return type just shows you which Guids were changed and to what values.

**Comment by SwagAccount** [comment]
I figured it out, just needed to run it as a void🤦. 

To used to stuff having a return I guess
