### ISSUE TITLE
Error when serializing WeldContext on (GameObject).body

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5865]
### Describe the bug

When i try to serialize a physicsbody field it has too much depth, i think, meaning i cant serialize it.

Anyway around this

### To Reproduce

1. Serialize a Component that has a PhysicsBody

### Expected behavior

Serializing

### Media/Files

![image](https://github.com/user-attachments/assets/669a2608-c869-41c2-87b6-1ceda41c545f)

**Comment by aylaylay** [comment]
What is a weld context

**Comment by aylaylay** [comment]
Also serializing a physics body makes no sense
