### ISSUE TITLE
ActionGraph Able to reference hidden properties

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5868]
### Describe the bug

When populating a component's properties to select inside of an ActionGraph node, old properties still show up, even when not defined in the code itself.
I can only assume they are still serialized, but in reality they are unused and outdated. 

For example: In the screenshots below you can see that the Player component has properties for a Move Helper and a Character Controller, both of those were used in old iterations but have all been removed from the code and replaced by the new Simple Move Helper.
Trying to access them will give you a NRE.
I've looked through the player.prefab but there isn't any mention of Character Controller, even searching with CTRL+F on the entire project shows that there is no Character Controller anywhere.

### To Reproduce

1. Clone https://github.com/Small-Fish-Dev/Sauna/ (If you're not Ziks let me know I'll add you as well)
2. Create a new ActionGraph anywhere
3. Get<Player> component
4. When accessing the properties, the Move Helper and Character Controller properties get added

### Expected behavior

Those options should not appear

### Media/Files

![image](https://github.com/user-attachments/assets/0126edfa-dacd-4551-9c2d-27d46220507f)

![image](https://github.com/user-attachments/assets/5dce58cc-cf02-45e8-92a3-59c1b98f2af4)

### Additional context

Today I also recloned the repository, so I guess it's not old compiled prefabs.
The MoveHelper property still exists in the Player component to reference the new Simple Move Helper component, but using it returns the old MoveHelper. And the old SimpleMoveHelper property is still there which is what I use, when it should also not be there as it was updated to MoveHelper property.

**Comment by Metapyziks** [comment]
Do these only show up when you put text in the filter? When filtering I include all component types so you can use ones that are added at runtime, not just the ones on the containing object while editing.

**Comment by yuberee** [comment]
Yea only when I search up "Controller" or "Helper"

**Comment by Metapyziks** [comment]
I think there's nothing to fix here then? Unless I've misunderstood the issue.

**Comment by yuberee** [comment]
Among the things that get populated:

- SimpleMoveHelper property: Old property on the Player component that was removed a few weeks ago. If I select this I get an NRE because it's always null
- CharacterController property: Old property on the Player component that was removed a few months ago. Always null
- MoveHelper property: Current property I use to reference the new move helper component, but it still returns null because it's looking for the old MoveHelper component instead of the new SimpleMoveHelper component

2 properties out of 3 that get populated are no longer on the component and aren't found anywhere in the code, the third one is the correct property but it's still of the wrong type.
If I want to get the current move helper component I can't use these properties in actiongraph and rather I have to get it manually with the Get<SimpleMoveHelper> component node.

When I'm home I'll double check to see if they also appear when not writing anything. But you can go in the solution and CTRL+F "CharacterController" and "MoveHelper" and you'll see that those properties are not found anywhere.

**Comment by Metapyziks** [comment]
To be clear, those 3 aren't properties but are component getter nodes. When you type in the filter, it'll include all component types in your project as search results.

**Comment by yuberee** [comment]
Hmm ooh
I'll check and close the issue when I'm home

**Comment by Metapyziks** [comment]
Maybe there's an argument that we could make that more clear, like change component getter node names to look less like properties in that list.

**Comment by yuberee** [comment]
I see now, yea they are components and in theory I can get any component from Player even when it's not there.

The one that still troubled me was CharacterController which I was 100% sure wasn't in our code.
But then I found that I can add the component and when looking at the source it's one of the default scene components.

![image](https://github.com/user-attachments/assets/5dcc0cb8-2777-4134-847c-44a93fec61a9)

I'll close this issue then, thanks for looking into it
