### ISSUE TITLE
Can't delete selected objects in Inspector by pressing DEL

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5869]
### Describe the bug

Clicking on something in the inspector and pressing DEL used to delete the object, it no longer does so. Selecting it in the 3D view and then pressing DEL deletes it just fine.

### To Reproduce

1. Select something in inspector
2. Press DEL key
3. See that it does not delete

### Expected behavior

Should delete

**Comment by DoctorGurke** [comment]
Seems like it'll work as long as the scene view is focused, even if you selected it via the hierarchy. Very annoying indeed though that it doesn't work in the hierarchy directly anymore

**Comment by MD485** [comment]
Del isn't working in the asset browser for me either.

**Comment by CarsonKompon** [comment]
I fixed this in my editor-keybinds branch which will be merging soon.

**Comment by CarsonKompon** [comment]
Should be fixed now that everything's merged :)
