### ISSUE TITLE
Testing local multiplayer should use local build

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#5870]
### What it is?

If you want to test multiplayer locally you HAVE to upload your build to `sbox.game`. Since the local multiplayer client joining downloads the files from `sbox.game`. This sucks because you can't even test your game locally without potentially breaking your main `sbox.game` build.

This has been mentioned briefly inside of https://github.com/Facepunch/sbox-issues/issues/3042, but, I think a new issue for this makes sense.

### What should it be?

Local multiplayer clients should download from your local build instead of asset party.

**Comment by MD485** [comment]
I agree but isn't this a duplicate of #4466 ?

**Comment by matekdev** [comment]
Yeah it is, thanks, I was searching for the words `multiplayer` and `asset.party` and didn't find this issue.
