### ISSUE TITLE
Box Hitbox Ray Tracing Does Not Hit

### ISSUE THREAD

**Issue by Andrei15193** [Facepunch/sbox-issues#5872]
### Describe the bug

While reporting #5871, I managed to get a few box hitbox hits with ray tracing, however the behavior is odd now that I have the wireframe preview to see what the hitbox should be.

### To Reproduce

1. Create a new Scene
2. Add a GameObject
3. Add a Hitbox Component having the following properties
  Target: leave blank  
  Shape: Box  
  Radius: 25  
  Center A: 25, 25, 25  
  Center B: 50, 50, 50  
  Hitbox Tags: leave blank
4. Add a custom component that runs traces when an input is pressed
    ```c#
    public sealed class HitboxRayTest : Component
    {
        protected override void OnFixedUpdate()
        {
            base.OnFixedUpdate();

            if ( Input.Pressed( "Forward" ) )
                foreach ( var offset in new[] {
                        new Vector3( 50, 0, 0 ),
                        new Vector3( 0, 50, 0 ),
                        new Vector3( 0, 0, 50 ),
                        new Vector3( 50, 50, 0 ),
                        new Vector3( 0, 50, 50 ),
                        new Vector3( 50, 50, 50 )
                    } )
                {
                    var result = Scene
                        .Trace
                        .Ray(
                            new Vector3( 25 ) + offset,
                            new Vector3( 25 )
                        )
                        .UseHitboxes()
                        .Run();
                    Log.Info( new { result.StartPosition, result.EndPosition, result.Hit, result.Distance } );
                }
        }
    }
    ```
5. Run the scene and trigger the traces, check the logs for results.
6. None of the traces hit.

### Expected behavior

All traces should hit the box hitbox.

### Media/Files

![image](https://github.com/user-attachments/assets/6ebc0aff-3ed3-4871-acaf-0b80d98a18c6)

### Additional context

I'm running on Windows 11.

Changing the hitbox shape from Box to Sphere makes all traces hit as expected.

**Comment by aylaylay** [comment]
Fixed
