### ISSUE TITLE
Host via new instance

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5873]
### For?

S&Box

### What can't you do?

Host as a new instance

### How would you like it to work?

Hosting as a new instance

### What have you tried?

I have tried stuff and it has worked, but it is silly.
I dont want to have to open sbox by the exe, and then using a command to create a new game from the instance. It should be here in the editor

**Comment by MD485** [comment]
![image](https://github.com/user-attachments/assets/d768d98d-d109-4ee4-b73f-fc950fe2638f)

**Comment by Nolankicks** [comment]
> ![image](https://github.com/user-attachments/assets/d768d98d-d109-4ee4-b73f-fc950fe2638f)
> 
> You have to upload any changes to sbox.game first.

This is only for models. It fetches any code changes.

**Comment by DevulTj** [comment]
This already exists
