### ISSUE TITLE
[Shadergraph] Sampler Node

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5877]
### For?

S&Box

### What can't you do?

At the moment samplers are tied to their respective texture 2d nodes which sucks. they should be their own node that you can reuse for multiple textures as described here : https://docs.facepunch.com/s/sbox-dev/doc/sampler-states-LlJc7ymJkq

### How would you like it to work?

-  Sampler node which can be configured with a name Along with the usual options.
- texture 2d which can take in the sampler output of a sampler node. if one is not connected then default back to the old coupled behavior.

![Screenshot 2024-07-21 135604](https://github.com/user-attachments/assets/ae57bbc1-a075-4b26-a2c6-bf7fc9ec715f)

### What have you tried?

Dealing with  the directx9 era behavior 

### Additional context

I have taken the liberty of making the changes myself. attached the modified files for you guys to look over for any issues or bugs i may have missed. also included a shadergraph asset to demonstrate functionality. do note i haven't added the ability to switch back to the old functionality if a sampler node isn't connected to a texture 2d. 

[Sampler Node.zip](https://github.com/user-attachments/files/16325437/Sampler.Node.zip)

**Comment by WheatleyMF** [comment]
Honestly I don't really understand the exact point of this change. It does take extra few seconds to set up sampler state in each Texture2D node you have, but IMO it makes more sense to keep such features inside a single node. 

Not to mention that shadergraph optimizes output code to avoid duplicate SamplerStates anyway: 
![image](https://github.com/user-attachments/assets/ca61043a-1196-420e-be82-9497c35ad169)

**Comment by handsomematt** [comment]
Yeah the code generates the non dx9 way
