### ISSUE TITLE
Properties that are nullable lose Range slider functionality

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5879]
### Describe the bug

If you make a nullable property and give it the range attribute, the slider that comes with it becomes nonfunctional 

### To Reproduce

this works
`[Property, Range( 0, 20, 1)] public int Difficulty { get; set; }`
this doesn't
`[Property, Range( 0, 20, 1)] public int? Difficulty { get; set; }`

### Expected behavior

The slider should function

### Media/Files

https://github.com/user-attachments/assets/11bf0b82-88d0-47f7-a08e-cac83e8d02a8

https://github.com/user-attachments/assets/720e3ad5-e335-43b6-ae76-ad9837d27f05

**Comment by MD485** [comment]
This seems to work fine for `float?`, I think it's an `int?` issue.
It's weird that the value being nullable breaks it though, `int` uses a float slider in the ui anyway, maybe some conversion error when toggling the null state of the property?
