### ISSUE TITLE
GetAttachment(string) gives random data if attachment point does not exist

### ISSUE THREAD

**Issue by deadmonstor** [Facepunch/sbox-issues#588]
**Describe the bug**
model.GetAttachment(string) has no protection if the model does not have the attachment point however model.GetAttachment(int) throws if you try to select something that is out of range.

This is currently the bug that constructs gibs are having on the walls because placementOrigin is not defined. 
addons/base/Code/Utility/Breakables.cs would most likely have to be fixed with this change so it doesn't create errors too. 

**To Reproduce**

```
var mdl = Model.Load( piece.Model );
				
Log.Info($"mdl.GetAttachment Pos: {mdl.GetAttachment( "placementOrigin" ).Position}");
Log.Info($"mdl.AttachmentCount: {mdl.AttachmentCount}");
Log.Info($"Will error: {mdl.GetAttachment( mdl.AttachmentCount + 1 ).Position}");
```

				
**Expected behavior**
I feel like they both should throw so we can handle not being able to find an attachment point instead of throwing random data at them as the string version does.  

**Screenshots**

[https://i.imgur.com/46Sztkt.png](https://i.imgur.com/46Sztkt.png)

From addons/base/Code/Utility/Breakables.cs: 
[https://i.imgur.com/AmW3MRI.png](https://i.imgur.com/AmW3MRI.png)

**Comment by aylaylay** [comment]
I made it return identity instead of junk, seems to fix the wall gibs going off into infinity

**Comment by garrynewman** [comment]
These should really be returning a nullable transform, this'd fit in better with what we do with the ModelEntity version.

**Comment by aylaylay** [comment]
I agree although there's a gotcha with using default for transform, default isn't identity, i think rotation (quats) has this same problem

**Comment by aylaylay** [comment]
Done

**Comment by deadmonstor** [comment]
Looks great, Thanks!
