### ISSUE TITLE
Error when building render tree on Softsplit.UI.FileTreeItem - Tried to include element 'FileTreeItem' recursively!

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5880]
### Describe the bug

I cant recursively include this element and I see no reason why I cannot do that, how do I get around this

### To Reproduce

1. Recursively reference FileTreeItem

### Expected behavior

Being able to do this

### Media/Files

https://github.com/Softsplit/sandbox-classic/blob/main/Code/UI/MenuSystem/Shared/Settings/FileTree.razor 
https://github.com/Softsplit/sandbox-classic/blob/main/Code/UI/MenuSystem/Shared/Settings/FileTreeItem.razor

Files in question

**Comment by MD485** [comment]
Can you just make a `FileTreeItem` contain a `FileTree`?
Recursion might be helpful in niche scenarios, but I'm not sure it's necessary for a proper UI API.

**Comment by SwagAccount** [comment]
its needs to recurse because a file tree can be any size and depth

**Comment by MD485** [comment]
I don't see why that doesn't apply to the `SubItems` array you made? It has the same info as a `FileTree`.
You're still recursing, just not recursing using the defining element.
