### ISSUE TITLE
(Regression) GameObject needs to be networked to invoke broadcast RPCs

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#5881]
### Describe the bug

Trying to patch up rogue arena and getting a warning for player sound broadcasts: "GameObject must be networked to invoke RPC". During the game jam all gameplay sounds worked fine in multiplayer, so this must have been introduced afterwards and then got a specific exception later (???)

### To Reproduce

1. Call Broadcast from a non-networked object
2. Throws exception

### Expected behavior

GameObjects should be able to invoke Broadcast RPC without being actively networked.

### Media/Files

![sbox-dev_cEbeZyF22U](https://github.com/user-attachments/assets/72020c7f-db79-4356-8264-dae15a6eaf0b)

### Additional context

@kurozael

**Comment by DevulTj** [comment]
I don't see the point in blocking them if they work fine, but maybe there was a reason for it

**Comment by kurozael** [comment]
> I don't see the point in blocking them if they work fine, but maybe there was a reason for it

Yeah it's an unintended side effect of something I fixed. I asked for this issue to be made - will resolve 👍

**Comment by kurozael** [comment]
Just to check though @DoctorGurke - the Component you're calling the RPC is on is a component on a GameObject that does somewhere up the hierarchy have a parent that _is_ a networked object, right?

**Comment by kurozael** [comment]
Fuck it, let's allow it. If a GO and Comp doesn't exist with those Guids on the other end it's just gonna moan it can't find them and that's okay.
