### ISSUE TITLE
Hammer meshes with tags don't get forwarded 

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5885]
If you run a trace on any hammer map, returned tags will always be empty. Default tags on a mesh in hammer are 'solid' so most maps are easy to test on.

**Comment by aylaylay** [comment]
Tried in testbed, working fine

**Comment by aylaylay** [comment]
This looks like sometimes the string token for a tag isn't cached because the tag is added in native

**Comment by aylaylay** [comment]
There's no real way to fix this, we can fix it going forward but physics resource saves the string token hash code and it can't really be reversed.

**Comment by Metapyziks** [comment]
Maybe it's okay to only be able to reverse the ones in the project's collision config.

**Comment by aylaylay** [comment]
Found a way to fix this properly, collision data actually had the actual strings on disk so we now string token cache them
