### ISSUE TITLE
Trace tag filtering for hammer meshes isn't respected

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5886]
In my case for Nicked, we have meshes in the map with a player_clip tag so we can exclude it from bullet traces, but they're always getting hit.

(I believe this is a separate problem to #5885)

**Comment by aylaylay** [comment]
Tried in testbed, working fine

**Comment by aylaylay** [comment]
Should be fixed now, tool materials were replacing tags, now we just add both

**Comment by DevulTj** [comment]
Legend, I'll run a compile now and let you know

**Comment by DevulTj** [comment]
Works a treat ❤️
