### ISSUE TITLE
UI 2022 VS UI 2023(2024)

### ISSUE THREAD

**Issue by AdamKuza** [Facepunch/sbox-issues#5889]
Why is this masterpiece 
![image](https://github.com/user-attachments/assets/e87901bc-4811-458e-8050-31c11b083b36)
betrayed for this shit 
![image](https://github.com/user-attachments/assets/b874bf78-a895-47d2-8312-588e7a351ef9)
?

**Comment by CALLlA1011666** [comment]
# Well, Let's Wait!

**Comment by CALLlA1011666** [comment]
-# Some markdown test for issue opener...

**Comment by Nolankicks** [comment]
What's the issue?

**Comment by AdamKuza** [comment]
> What's the issue?

Why did they change the UI, in this issue

**Comment by Nolankicks** [comment]
> > What's the issue?
> 
> 
> 
> Why did they change the UI, in this issue

Because the game is in development. There is a ui concept branch that was being worked on. It's no priority since the scene system is still being worked on.

**Comment by AdamKuza** [comment]
> > > What's the issue?
> > 
> > 
> > Why did they change the UI, in this issue
> 
> Because the game is in development. There is a ui concept branch that was being worked on. It's no priority since the scene system is still being worked on.

Well, 2022 ui in my heart

**Comment by CALLlA1011666** [comment]
> > > > What's the issue?
> > > 
> > > 
> > > Why did they change the UI, in this issue
> > 
> > 
> > Because the game is in development. There is a ui concept branch that was being worked on. It's no priority since the scene system is still being worked on.
> 
> Well, 2022 ui in my heart

Also, As I know, They've deleted SFM.

**Comment by AdamKuza** [comment]
> > > > What's the issue?
> > > 
> > > 
> > > Why did they change the UI, in this issue
> > 
> > 
> > Because the game is in development. There is a ui concept branch that was being worked on. It's no priority since the scene system is still being worked on.
> 
> Well, 2022 ui in my heart
