### ISSUE TITLE
Move action graph properties into the main tab

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#5890]
### What it is?

Some people might disagree... but I thought I should still make this issue. I don't think action graph should have its own tab inside of the inspector. 
![image](https://github.com/user-attachments/assets/17343168-5386-41d0-b087-0175e7c6c21e)
Clicking the little lightning bolt moves you to the action graph tab
![image](https://github.com/user-attachments/assets/6822c9d9-6149-488b-b931-bf2a2960320b)

### What should it be?

Move the action graph properties into the main tab where all the other properties live. Let the code definition order dictate their order like all other properties. If there are too many properties group them under a category like they already are in the previous picture and leave them collapsed.
![image](https://github.com/user-attachments/assets/00a74a88-75f0-4646-ae86-43237fcd39f2)

Why should action graph properties be in their own tab? People can just group them together if need be. Maybe let users define their own tabs? Although that seems a bit overkill.

**Comment by MrBrax** [comment]
when action graph was added i was confused for a long time, had to look up the docs to find where they could be accessed. wouldn't say it's very intuitive.

**Comment by Metapyziks** [comment]
This should now be the case.

The built-in "On Component XYZ" actions are deprecated, you should now use this component for those kinds of events:

![Image](https://github.com/user-attachments/assets/75afb92f-f737-4746-a6ca-b693a08a8553)

![Image](https://github.com/user-attachments/assets/09d7f535-102a-4b05-b02e-41a3d985422c)
