### ISSUE TITLE
Request for fakelag / artificial ping

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#5894]
### For?

S&Box

### What can't you do?

I'm unable to simulate latency on a client for testing purposes.

### How would you like it to work?

I would like it to work like a convar or setting that i can set to a value in milliseconds

### What have you tried?

I haven't tried any workarounds

**Comment by DevulTj** [comment]
If we'll add something in an official capacity, I don't know - but I would suggest using https://jagt.github.io/clumsy/ for now.

**Comment by handsomematt** [comment]
@kurozael can we do this - steam networking has something built in I think, we can just expose that

**Comment by kurozael** [comment]
I'll check that Matt, if it works for P2P as well that's great - otherwise there's a different way to approach this generically so that it works for our local instance connections as well 👍

**Comment by kurozael** [comment]
You can use the `net_fakelag` ConVar on the client or the server - and you can also enable it in the editor like this: https://files.facepunch.com/conna/1b1211b1/sbox-dev_jpOfxVrwEr.mp4
