### ISSUE TITLE
[Shadergraph] More explicit error for missing a vector input on Apply TRS node

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5896]
### What it is?

if you simple add the Apply TRS node to a graph without connecting anything to any of its inputs. you will get the compiler error below.
![Screenshot 2024-07-23 091228](https://github.com/user-attachments/assets/53055ac4-59ef-4fa8-897c-5652b3c50fbd)

Shadergraph should have a more explicit error for missing the vector input rather than just the above.

### Solution

add the following before  `var vector = compiler.Result( Vector );` from within the `ApplyTrs class`

```
if ( !Vector.IsValid() )
{
	return NodeResult.Error( "Missing Vector Input!" );
}
```

### Result

![Screenshot 2024-07-23 092012](https://github.com/user-attachments/assets/6938e01b-479e-4715-be5f-0259b51c1b09)

**Comment by Metapyziks** [comment]
Thanks!
