### ISSUE TITLE
Creating a CustomEditor for a class property on a GameResource breaks saving

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5902]
### Describe the bug

If you have a class on GameResource with a custom editor, such as
`
[GameResource( "Bug Resource", "bug", "A GameResource to show off a bug" )]
public class BugGameResource : GameResource
{
	public BugClass BugClass { get; set; }
}
//Bug class has a custom editor
public class BugClass
{
	public GameObject CustomResource { get; set; }

	public BugClass()
	{
		CustomResource = null;
	}

	public BugClass( GameObject customResource )
	{
		CustomResource = customResource;
	}
}
`
This will break saving and will give this error:
`
Error setting BugClass to BugClass (BugClass)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Editor.Inspectors.AssetInspector.<>c__DisplayClass19_0.<CreateContentUI>b__2(SerializedProperty x) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Inspectors\AssetInspector.cs:line 180
   at Sandbox.SerializedObject.NoteChanged(SerializedProperty childProperty)
   at Sandbox.Internal.TypeSerializedObject.NoteChanged(SerializedProperty childProperty)
   at Sandbox.SerializedProperty.NoteChanged()
   at Sandbox.Internal.TypeSerializedProperty.SetValue[T](T value)
`

### To Reproduce

Attached is the repo, included are 2 GameResources, with properties of 2 identical classes, except one has a custom editor and one does not. You will be able to set the property for the one with the custom editor, but after restart it will not be saved.
[gameresourcebug - Copy.zip](https://github.com/user-attachments/files/16352527/gameresourcebug.-.Copy.zip)

### Expected behavior

The GameResource should save.

### Additional context

@DevulTj

**Comment by aylaylay** [comment]
They way you're doing the custom editor is very wrong. The correct way to do it is like this:

```cs
[CustomEditor( typeof( BugClass ) )]
public class BugCustomEditor : ControlWidget
{
	public BugCustomEditor( SerializedProperty property ) : base( property )
	{
		Layout = Layout.Column();

		property.TryGetAsObject( out var so );

		var controlSheet = new ControlSheet();
		controlSheet.AddRow( so.GetProperty( nameof( BugClass.CustomResource ) ) );

		Layout.Add( controlSheet );
	}
}
```
