### ISSUE TITLE
png is crashing editor when trying to render thumbnail

### ISSUE THREAD

**Issue by kodi022** [Facepunch/sbox-issues#5905]
### Describe the bug

This image specifically is crashing me, it does not give any logs when the crash happens.

Here is all the things ive tried:
- recompile in a image editor
- have someone else try viewing it (did not crash them)
- try in another project (still crashes)
- clear all cookies
- verified game files within an hour before the other attempts

Many of these were suggested by the discord

### To Reproduce

1. Put image in assets folder of any project
2. view asset explorer in any icon view mode or shadergraph when visible in a Texture 2D

### Expected behavior

It shouldnt, and it didnt until recently. Unsure when exactly it started happening, within a few days.

### Media/Files

Notes about log:
This log is an empty project containing the image where the game crashes viewing it in asset browser
`2024/07/23 16:25:44.9117	[engine/Qt] invalid splitter encountered` shows up at startup at the line `Compiling Assets` with or without the image present
[Log.log](https://github.com/user-attachments/files/16355193/Log.log)

The image
![hotspot_mask](https://github.com/user-attachments/assets/45462659-6386-4e40-86c0-3842024e9729)

### Additional context

Windows 11, image compiled using GIMP

**Comment by aylaylay** [comment]
This might have been fixed

**Comment by kodi022** [comment]
Yes, I can view them in the Asset Browser again. Thank you!
