### ISSUE TITLE
Fix terrain please

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#5907]
### Describe the bug

terrain doesn't work

### To Reproduce

 create terrain -
![Снимок экрана (97)](https://github.com/user-attachments/assets/ce43bc0e-7464-45f7-8146-6c10cd2779a6)

### Expected behavior

terrain works

**Comment by chrisspieler** [comment]
What is the problem that you're having with terrain? I see that the material for the entire terrain is overridden, which is probably not what you want. By following these instructions, you can make Terrain Materials and then paint the terrain: https://docs.facepunch.com/s/sbox-dev/doc/terrain-materials-fv8grvoWTS

**Comment by somethink000** [comment]
> What is the problem that you're having with terrain? I see that the material for the entire terrain is overridden, which is probably not what you want. By following these instructions, you can make Terrain Materials and then paint the terrain: https://docs.facepunch.com/s/sbox-dev/doc/terrain-materials-fv8grvoWTS

I’m not the only one having this problem btw, perhaps I just can’t understand how exactly it should look because the tutorial shows the steps but not their result

![Снимок экрана (98)](https://github.com/user-attachments/assets/9f36b6fa-da26-4079-88a5-f29e1bd90364)

**Comment by aylaylay** [comment]
It should be possible now to create new terrain without errors
