### ISSUE TITLE
Hidden Directional light seems to still affect the scene

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5910]
### Describe the bug

It looks like having a directional light that is not supposed to be rendering affects the brightness of the rest of the scene that is visible. The more lights you have, the more it brightnes the scene.

### To Reproduce

1. Have a scene
2. Create a directional light and add some tag to it
3. Add that tag to your camera's ignore render tags list
4. Turn the light on/off to see that it affects the scene even when it should not be rendering
5. Optionaly make a bunch of copies of the light for a more pronounced effect

### Expected behavior

Lights that are ignored by a camera should not affect the brightness of anything that is rendered by a camera.

### Media/Files

Example video of me toggling on and off a directional light that has its tags set up so that it does not contribute to the scene lighting.

https://github.com/user-attachments/assets/0cfbec8c-e871-4b67-ab2d-d2df73a1d311

**Comment by Gmod4phun** [comment]
Seems to be the Sky Color of the light causing issues and affecting the rendered scene. Added a small simple repro scene

[repro_light_bleed.zip](https://github.com/user-attachments/files/16365545/repro_light_bleed.zip)

**Comment by Gmod4phun** [comment]
Added a video of how to use the repro (kinda forgot to do that the first time). I also believe the same thing is happening for the Skybox IBL (aka hidden skyboxes affect the lighting of the scene if they have IBL enabled)

https://github.com/user-attachments/assets/7001e48d-54be-4bb6-b593-a31c08848def

**Comment by aylaylay** [comment]
Fixed
