### ISSUE TITLE
Tag Masks on Scene.FindInPhysics

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5911]
### For?

S&Box

### What can't you do?

Mask tag FindInPhysics

### How would you like it to work?

Accept a List<string> for a tag mask

### What have you tried?

Setting up a sphere collider as a trigger and setting the collision tags, too hacky and unintuitive

### Additional context

![image](https://github.com/user-attachments/assets/74807e50-b375-44f1-b1ff-6d83973deedc)

**Comment by aylaylay** [comment]
Can you not just filter the result?

**Comment by aylaylay** [comment]
I've thought about this and it would just gunk up the API, these functions are treated as (give me everything in this volume) you're then free to filter the result however you want. This is all it would be doing internally anyway.

**Comment by SwagAccount** [comment]
I thought tag masks lower the cost of calling it as your only checking for that set of tags and not every collider.

**Comment by SwagAccount** [comment]
I know from unity that adding a layer mask to an overlap sphere lowers the performance impact.
