### ISSUE TITLE
Larger scenes take a while to load into play mode after recent updates

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5912]
### Describe the bug

I noticed my scene takes around 3-4 seconds to load into play mode after some recent updates (used to be almost instant before), and the console is spammed with this:

![image](https://github.com/user-attachments/assets/6af33688-5f65-45f9-a4ae-2c1ab036510e)

 Almost empty scenes are pretty fast to play, so I suspect its just the leftover prints that are hogging the startup performance.

**EDIT: It only happens if a network helper is present in the scene.**

### To Reproduce

1. Have a scene with a bunch of assets used and has a network helper
2. Press Play scene
3. Observe noticeably longer times and unnecessary console spam

### Expected behavior

No spam, no lag

**Comment by solwllms** [comment]
Stuck all these verbose logs behind a convar and disabled by default, outputting the elapsed time these things take to give a more accurate measure in the future if this is something to keep an eye on

**Comment by Gmod4phun** [comment]
Yup, the spam is gone, and even the long load times. It does however take a bit more time to run the scene than it was before, but I suspect that is inevitable because of the network files having to be built on start.
