### ISSUE TITLE
Map Loader should load/recreate map hierarchy.

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#5919]
### For?

S&Box

### What can't you do?

Children of objects (like door handles on doors) from hammer maps aren't parented to their parent by the maploader.

### How would you like it to work?

Objects should be parented in the scene like they are in hammer.

### What have you tried?

I tried coding it myself, but there's seemingly no way to search these objects by their original hammer names, so it can't be done easily from my end.

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/3f843633-7f5b-418b-857b-64dbf3d1dfd6

Map objects should now have their correct parent, let me know if you find a situation where this doesn't work correctly
