### ISSUE TITLE
Numeric keypad `ENTER` key isn't supported by the Console

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/sbox-issues#592]
**What can't you do?**
The console does not seem to support executing commands with the `ENTER` key on the numeric keypad like the other regular `ENTER` key does.

**How would you like it to work?**
Make this key do the same thing as the regular `ENTER` key.

**Additional context**
I still tested with another keyboard to see if it was not mine. Also, this key is perfectly supported on games based on Source 1 and similar.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by FlorianLeChat** [comment]
Sorry for the delay, this is obviously well fixed, thanks Rubat!
