### ISSUE TITLE
Rect Light and Capsule Light components

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5931]
### For?

S&Box

### What can't you do?

The old Rect Light and Capsule Light are available in Hammer but not in the new Scene System.

### How would you like it to work?

They need a component equivalent with Gizmos similar to the ones in hammer

### What have you tried?

.

**Comment by Gmod4phun** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/4452
