### ISSUE TITLE
Asset browser automatically adding "popular" tag

### ISSUE THREAD

**Issue by BlakeWinser** [Facepunch/sbox-issues#5936]
### Describe the bug

When navigating through the assets browser's cloud section, the asset search and filter field will automatically add the "popular" tag, sometimes limiting search results.

### To Reproduce

1. Open assets browser
2. Go to Cloud -> Everything
3. Look at search/filter input, should have Popular tag (happens 100% of the time for me)

### Expected behavior

Popular tag should be applied if the user selects it, if not don't add by default.

### Media/Files

https://github.com/user-attachments/assets/55bd4805-679e-4324-9906-39d5e9008173

### Additional context

Win 10, latest S&Box build at time of writing.

**Comment by DevulTj** [comment]
I fucked this, should be fine now
