### ISSUE TITLE
game crashes on startup

### ISSUE THREAD

**Issue by toilet-master** [Facepunch/sbox-issues#5939]
### Describe the bug

when i open sandbox nothing happens and then i get an error

### To Reproduce

1.open s&box
2. wait 3-5 seconds
3. crash

### Expected behavior

game had to start

### Media/Files

https://github.com/user-attachments/assets/9d8f2ab2-9963-4077-8484-7cb4e9c8f073

### Additional context

i use windows 7. I have: 12 ram, amd athlon x4 830, nvidia geforce gt 1030,

**Comment by SharpMars** [comment]
wish you could at least attempt to translate what error says or provide logs, but you most likely wont get help from facepunch because you're using windows 7 which isn't supported by anyone in current times

**Comment by AnywayFarus** [comment]
> wish you could at least attempt to translate what error says or provide logs, but you most likely wont get help from facepunch because you're using windows 7 which isn't supported by anyone in current times

The error in the video does not carry any useful information, ala "process terminated".

However, I have the same problem, but without the error output on Windows 11. Starts running, the game appears in the tray (apparently in the processes too), but does not pass and two seconds as it disappears, and in the styme appears the ability to start the game again.

Log: 
`2024/07/26 17:24:21.5785	[Generic] Waiting for Web Auth Ticket..	
2024/07/26 17:24:23.4004	[engine/RenderSystem] Layer VK_LAYER_fpsmon uses API version 1.1 which is older than the application specified API version of 1.2. May cause issues.	
2024/07/26 17:24:23.4166	[engine/RenderSystem] Layer VK_LAYER_ROCKSTAR_GAMES_social_club uses API version 1.0 which is older than the application specified API version of 1.2. May cause issues.	
2024/07/26 17:24:26.4062	[engine/RenderSystem] Vulkan Physical Device: NVIDIA GeForce RTX 2060 SUPER	
2024/07/26 17:24:26.4943	[engine/RenderSystem] VK_EXT_graphics_pipeline_library and dependent extensions enabled.	
2024/07/26 17:24:26.4943	[engine/RenderSystem] Unable to open Vulkan pipeline cache shadercache\vulkan\shaders.cache file - might not exist yet.	
2024/07/26 17:24:26.4943	[engine/RenderSystem] Vulkan driver version: 560.70.0.0	
`

**Comment by handsomematt** [comment]
Windows 7 isn't supported.

@AnywayFarus uninstall / disable FPS Monitor
