### ISSUE TITLE
Linux Crash on Startup: CAppSystemDict::LoadSystemAndDependencies():AppSystemDict: Error in Init() of interface 'RenderDeviceMgr001'!

### ISSUE THREAD

**Issue by cherryceri** [Facepunch/sbox-issues#5942]
### Describe the bug

When I try to launch the game, i get an error pop up: "CAppSystemDict::LoadSystemAndDependencies():AppSystemDict: Error in Init() of interface 'RenderDeviceMgr001'!"
Most of the information online about this error is related to DotA 2, and the other reported issue here for this same error message is unfortunately not relevant to me as I do not have the module found in the other issue that was uninstalled to fix the problem.

### To Reproduce

1. I click play on steam
2. The game processes vulkan drivers
3. The aforementioned error message pops up

### Expected behavior

The game should launch, as other steam games launch no problem

### Additional context

GPU: Nvidia 4070
OS: Arch Linux
Compositor: Wayland (Hyprland)
Drivers which may be relevant: 
- lib32-nvidia-utils 555.58.02-1
- lib32-opencl-nvidia 555.58.02-1
- nvidia-dkms 555.58.02-1
- nvidia-settings 555.58.02-1
- nvidia-utils 555.58.02-1
- opencl-nvidia 555.58.02-1
- lib32-vulkan-icd-loader 1.3.279-1
- vulkan-headers 1:1.3.285-1
- vulkan-icd-loader 1.3.285-1
- vulkan-tools 1.3.269-1
- lib32-mesa 1:24.1.4-2
- mesa 1:24.1.4-2
- mesa-utils 9.0.0-4
- dxvk-bin 2.4-2

I'm using proton and have tried experimental and the 3 most recent versions and it didn't make any difference.
I've tried using a few different launch options including -gl, -dx12, -dx11, -dx10, STEAMDECK=1, SDL_VIDEODRIVER=x11.

Also here is the output of vulkaninfo: [vulkan.txt](https://github.com/user-attachments/files/16393990/vulkan.txt)

**Comment by handsomematt** [comment]
This is a proton issue
