### ISSUE TITLE
S&Box Editor UI Looks not very good on resolution  1280x1024.

### ISSUE THREAD

**Issue by alex4nd3r666** [Facepunch/sbox-issues#5944]
### Describe the bug

The right window on the monitor is not fully displayed, part of it goes beyond the monitor, which is why it cannot be used normally.

### To Reproduce

Just use square(5/4) monitor.

### Expected behavior

I think, UI of windows should resize a bit better to fully display on the screen.

### Media/Files

![image](https://github.com/user-attachments/assets/bae7aec2-17c8-4238-8555-472ccff1f25f)

### Additional context

Please, don't tell me to buy a new monitor, I can't.

Also, Sorry for my English, I don't speak it, so I've particular used a translator.

**Comment by Nolankicks** [comment]
This has to do with the ui widgets minimum height and width. My guess is that they are picked for a reason. But they could be rescaled better.

**Comment by garrynewman** [comment]
The thing that's restricting with the width here is the Mixer tab. I would close it or redock it so it takes the full width of the bottom.
