### ISSUE TITLE
Map names missing from Server Info

### ISSUE THREAD

**Issue by Nichhh** [Facepunch/sbox-issues#5945]
### Describe the bug

Some server instances in a server list would return it's map with either nothing or "Scene," (see media) causing users who join to be faced with a black screen despite being connected to the server. Usually following this, the console parses `Tried to add two of the same equipment (?)` either once or multiple times. This might be the reason why many people are complaining about them joining a gamemode/server and being brought to a black screen.

### To Reproduce

1. Open S&Box and open the server list for any gamemode
2. Try and find a server with either "Scene" or an empty space where the map name would be (see media)
3. Join and be met with the _vooooiiiiidddd_

### Expected behavior

The player should be able to experience regular gameplay with the map loaded, but since there is no map, there is no game. Tragedy!

### Media/Files

![sbox_PYV4zEc7oJ](https://github.com/user-attachments/assets/f32b9ea7-b46a-448d-80ef-f44de929f121)

### Additional context

The setup I am currently using is on Windows 10 22H2, with up to date drivers.

**Comment by Nolankicks** [comment]
My guess is that the map is null. I've been getting this in prop hunt. So I just do a null check for them. Which I assume facepuch is doing as well.

**Comment by PacketAuditor** [comment]
I am also getting black screens intermittently upon joining servers.


https://github.com/user-attachments/assets/a1fc11a1-13a3-4b28-8f37-31663a2482ea

**Comment by Nichhh** [comment]
> I am also getting black screens intermittently upon joining servers.
This seems to be relating to a different issue. This is an issue tracking servers that are missing map/scene names which causes black screens upon connecting to the server.
