### ISSUE TITLE
Stuck on "Connected" screen

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5947]
### Describe the bug

Trying to connect to a game's server will have you stuck at the "Connected!" screen.

### To Reproduce

1. Pick a multiplayer game (I picked Scenebox)
2. Join

If step 2 fails to reproduce try again or another game

### Expected behavior

.

### Media/Files

![image](https://github.com/user-attachments/assets/b840583e-10f0-408f-9082-155cd7bc54fd)
[Log.log](https://github.com/user-attachments/files/16396626/Log.log)

### Additional context

I have fiber so this is most likely related to the host's connection speed.
But it seems like a large amount of players are encountering this, might happen more on some games compared to others depending on what needs to be networked.
The host changing while you're loading might be related, hard to tell.

**Comment by yuberee** [comment]
Might be happening when the host disconnects
Maybe related to #5951

**Comment by Louw123** [comment]
I have the same problem

**Comment by yuberee** [comment]
This seems to not happen anymore
