### ISSUE TITLE
Black screen after loading game

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5951]
### Describe the bug

Some games after you're done downloading will display a black screen and will never progress.

### To Reproduce

1. Navigate the game menu
2. Select "Scenebox 2" by CarsonK
3. Wait for files to finish downloading

### Expected behavior

.

### Media/Files

[Log.log](https://github.com/user-attachments/files/16397065/Log.log)

**Comment by KingOfTheFBI** [comment]
It seems pretty random. Sometimes people will just not be able to join any game due to this until they play around with steam files or just keep restarting. Hopefully this can get fixed as it is blocking a ton of people from playing games.

**Comment by yuberee** [comment]
Might be happening when the host disconnects
Maybe related to #5947

**Comment by garrynewman** [comment]
I think this was happening due to the lobby becoming toxic, when someone becomes host as they join. This should be fixed now - let me know if you're still seeing it.

**Comment by yuberee** [comment]
Haven't seen anyone complain about it, looks good.
