### ISSUE TITLE
Assets not downloading / ERROR models when Sbox.Game is under heavy load

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5952]
### Describe the bug

Downloading assets fails and your game boots up with ERROR models when the Sbox.Game servers are under heavy load.

### To Reproduce

1. Get 500 users to download games on S&box
2. Boot up a game you haven't downloaded yet

### Expected behavior

.

### Media/Files

[Log (5).log](https://github.com/user-attachments/files/16397168/Log.5.log)

^^  This log is of someone who couldn't see the main menu because games weren't being displayed, will attach a more relevant log once this gets reproduces again

### Additional context

Might be a server scaling issue, but if it fails to fetch a file it should retry or in desperate cases kick you off.

**Comment by handsomematt** [comment]
that log is unrelated to server load or anything similar
