### ISSUE TITLE
Keep a reference of Models (Or assets in general) in [Property] properties even when not valid

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5953]
### What it is?

Currently if you modify, remove, or screw up a model that is being referenced in a [Property] inside of a component, it will start referencing the error.vmdl model. 
Fixing or bringing back the original model doesn't fix this, as the reference has been changed to error.vdml and you'll be forced to manually update it.

### What should it be?

The reference to the asset shouldn't update to the error.vmdl but instead invalid references should default to showing up as error.vmdl, this way if you fix the reference it goes back to displaying the asset properly.

**Comment by solwllms** [comment]
Should be working now, no longer losing paths to the missing resource and the inspector is a bit more obvious when it happens:

![image](https://github.com/user-attachments/assets/eebd14a0-9813-4e41-8bba-8d0e37fcbf7b)
