### ISSUE TITLE
[Shadergraph] High-Res Graph Screenshots

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#5955]
### For?

S&Box

### What can't you do?

At the moment if you wish to take a screenshot of your graph you'll find that its hard todo so without manually stitching together a bunch of closeups up your nodes. Or just dealing with the blurry lq mess when you take a screenshot of your node setup.

### How would you like it to work?

With the nodes that you want to be included in the screenshot selected ( all of your nodes for example ). you should be able to right click and select _"Take High-Res Screenshot of selection"_ .  

### What have you tried?

Stitching many screenshots together .

**Comment by aylaylay** [comment]
Done

https://github.com/user-attachments/assets/29e7992c-4ca6-49f8-bbe4-df1181266e2b
