### ISSUE TITLE
Large lag spikes seemingly due to GC

### ISSUE THREAD

**Issue by IMCraytex** [Facepunch/sbox-issues#5957]
### Describe the bug

The game and editor will randomly spike in frametimes causing a hitch, for afew frames. Seems to happen every 2-8 minutes with varying intensity, In the Editor's Performance profiler it shows the rendering jump up to the triple digits like so
![image](https://github.com/user-attachments/assets/f559003d-fe61-4e03-906e-83c55d50c77a)
This is what the Profiler looks like in Superluminal when the spikes occur.
![image](https://github.com/user-attachments/assets/0c69d732-c683-40ec-bac6-22ee0fbac443)

The Superluminal session is too big to share here please contact me If needed.

Afew of my main thoughts of what this could have been was maybe background asset loading/shader compilation and whilst it does happen more when loading in an asset at runtime I don't think they are the same thing.

### To Reproduce

1. Open Either S&Box and play a Random game or The Editor, 2. Playtest or play the game and randomly you will get large hitches in framtimes causing the game to freeze for afew frames

### Expected behavior

The gameplay should be as smooth as possible with no hitches. especially on a mainly empty game

### Additional context

OS : Windows 11 Pro 23H2
Processor : AMD Ryzen 7 5800x Stock
Memory : 32gb DDR4 3600mhz
GPU : NVIDIA RTX 2070 Super
Drive S&box is installed to : Samsung 990 PRO M.2 2tb

If you have any questions I would be happy to help.

**Comment by IMCraytex** [comment]
Seemed to narrow it down a little with this being one of my largest spikes yet.
![image](https://github.com/user-attachments/assets/e78b3baa-25b0-4e33-8603-c7405e3c8d9f)
![image](https://github.com/user-attachments/assets/798f81df-5b48-4956-8ca9-b0edb9282660)
Seemingly the issue is with garbage collection. Here are the callstacks aswell if they prove useful
![image](https://github.com/user-attachments/assets/7ab9abc2-d087-4c03-83c1-5be7e372c483)

**Comment by IMCraytex** [comment]
Did some more testing, By changing this line on sbox.runtimeconfig.json "System.GC.Server": true to "System.GC.Server": false
It almost eliminated these hitches, They were still there just less frequent and not as intense. But this was at the cost of a much lower performance, This is all I can report from my end. Hope its enough!

**Comment by IMCraytex** [comment]
Quick update. and bump, But changing System.GC.Server to false seemed to work yesterday but today it stopped working. The spikes occur in every single game. including a blank scene. Hope this gets looked at soon

**Comment by handsomematt** [comment]
I had the same and solved it by updating .NET 7 - feel free to reopen if this isn't the solution
