### ISSUE TITLE
Terrain is throwing an exception

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5958]
### Describe the bug

Having terrain in the scene suddenly keeps throwing an exception:

![image](https://github.com/user-attachments/assets/6a6e6c98-8cce-4661-9c64-4de67894c4f5)

### To Reproduce

1. Create new scene
2. Add a terrain
3. Create the actual terrain that saves into a .terrain file
4. Observe exception

### Expected behavior

No exceptions :)

**Comment by handsomematt** [comment]
Oops no camera, fixed in next update
