### ISSUE TITLE
Shadow bug

### ISSUE THREAD

**Issue by Rytrak** [Facepunch/sbox-issues#596]
**Describe the bug**

**To Reproduce**

1. Go to 'in all maps'
2. Take 'flashlight'
3. See error

**Expected behavior**
Have the flashlight in shadow instead of a gun

**Screenshots**
![unknown](https://user-images.githubusercontent.com/62937157/128396066-ead19fe4-f66e-4b61-9315-767c904f63f5.png)

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by robotboy655** [comment]
This is not a bug. All default weapons currently have the same world model ( the weapon mode that appears in 3rd person )
