### ISSUE TITLE
Goback Material Shader needs to be recompiled

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#5960]
### Describe the bug

There are currently numerous Opium models and materials that do not properly react to light cookies or ambient lighting from environment probes. From what I understand, the Goback Material Shader needs to be recompiled for these issues to be fixed. The package in the cloud seems to have been last updated several months ago.

https://sbox.game/facepunch/goback_material
Related issue: https://github.com/Facepunch/sbox-issues/issues/5641

### To Reproduce

The attached project has a scene with a spotlight that you can use to test whether the recompiled shader properly reacts to the light cookie.

### Expected behavior

Shaders maintained by Facepunch should be compatible with common features like light cookies and ambient lighting.

### Media/Files

[light_cookie_checkerboard.zip](https://github.com/user-attachments/files/16400347/light_cookie_checkerboard.zip)

**Comment by CarsonKompon** [comment]
Should be all good now :)
