### ISSUE TITLE
Game doesn't launch

### ISSUE THREAD

**Issue by mir0shjr** [Facepunch/sbox-issues#5962]
### Describe the bug

After I start the game, Steam shows that it's running for a few seconds and then it closes. If I try to launch it directly in its folder, nothing changes, it briefly appears on the Task Manager and closes. The same thing goes to sbox-dev and sbox-laucher, the only thing that I managed to find out is that when I launch sbox-server - it tells me that it can't load engine2.dll and closes

### To Reproduce

Try to launch a game

### Expected behavior

.

### Media/Files

![изображение_2024-07-27_200722206](https://github.com/user-attachments/assets/1319aa88-c635-4066-a85a-a1dc5aefb1eb)

### Additional context

I'm running on Windows 10. I have Ryzen 5600x and RTX 3060

**Comment by garrynewman** [comment]
You might be missing the MSCV runtime - do you think you could install this and try again?

https://aka.ms/vs/16/release/vc_redist.x64.exe

I'll add some more diagnostics around startup errors to see if we can get something more useful

**Comment by mir0shjr** [comment]
Sadly, it didn't help. I already had MSCV installed. I deleted all my other versions of runtime, installed yours and rebooted my PC just to be sure, but the issue didn't change. It still gives me the same error.
![image](https://github.com/user-attachments/assets/6204af41-28de-4a94-8970-81e069d8c345)
Also my issue seems to be a pretty common one, I've messaged another guy in Steam Discussions and he sent me a screenshot with a same problem.
https://steamuserimages-a.akamaihd.net/ugc/2486634182041614215/18E5118100E409B14713830D6D10F28B8FA9887B/

**Comment by garrynewman** [comment]
I am adding further diagnostics to try to find the reason, please keep trying to launch it

**Comment by garrynewman** [comment]
Okay I think I might have fixed this. Build is building - should be on Steam in 15 mins

**Comment by mir0shjr** [comment]
Still doesn't work, the only difference is that after the first launch sbox-server didn't give as much text as in pictures below, only said that it can't open library engine2.dll, closed itself and in all other attempts after there's no text at all
![image](https://github.com/user-attachments/assets/94d7f5af-59aa-4fb2-ba84-dff2a522d4c0)
I have also installed WinDbg to see processes the executable goes through before closing, hope this can help
![image](https://github.com/user-attachments/assets/799afeea-10f9-4921-b6fa-bfe717dae4fa)

**Comment by mir0shjr** [comment]
Oh, wait, the update just dropped that I can't install for some reason
![image](https://github.com/user-attachments/assets/e8d066f4-af19-4315-8a29-a7b1feded8f1)

**Comment by MamaSantaLucia** [comment]
I have the same issue o; surprisingly, I was able to launch a game once in the morning, but after another update a menu with dotnet appeared, I believe it was on 26th of July in the evening, I was not able to launch it anymore ;c I didn't even have a chance to play it, because I was in a hurry and just watned to verify that it's launching

When I try to open S&box server, it just silently closes

**Comment by garrynewman** [comment]
Can you give it another try now, on the latest version?

Do you have any log files in /logs/ ?

**Comment by mir0shjr** [comment]
Nothing changed, the game closes so fast that it doesn't even make any logs nor the logs folder.
![image](https://github.com/user-attachments/assets/355c4fe4-d35d-4afb-88ad-fed48bcf852b)

**Comment by garrynewman** [comment]
Can you tell me more about your computer?

What windows version? Is it up to date?
Is it pirated? (shouldn't matter)
Did you install the MSVC redist? (https://aka.ms/vs/16/release/vc_redist.x64.exe)

If you go into bin/win64 and delete dbghelp.dll, then run sbox.exe direclty - does it work?

**Comment by handsomematt** [comment]
Anti virus software too?

**Comment by mir0shjr** [comment]
There's reports folder with DMP files in it, maybe these can help if I send them?
![image](https://github.com/user-attachments/assets/b238f7f8-0c42-4765-b25d-1d7fab3cb70b)

**Comment by garrynewman** [comment]
Oh yes please can you drop a few here

**Comment by mir0shjr** [comment]
[12a98e19-8a0d-4333-b456-701ba08cde98.dmp](https://github.com/user-attachments/files/16440751/12a98e19-8a0d-4333-b456-701ba08cde98.dmp)
[1787bb53-7f7e-4a94-836e-732f406baf6f.dmp](https://github.com/user-attachments/files/16440761/1787bb53-7f7e-4a94-836e-732f406baf6f.dmp)
[19ed44d0-a650-4134-b73e-812a0d20028d.dmp](https://github.com/user-attachments/files/16440771/19ed44d0-a650-4134-b73e-812a0d20028d.dmp)
[23d42a3b-17b6-4856-ace3-bf6acf33f7c1.dmp](https://github.com/user-attachments/files/16440782/23d42a3b-17b6-4856-ace3-bf6acf33f7c1.dmp)
[24d7f1b0-ad0f-49a8-8c93-a121e48cc63c.dmp](https://github.com/user-attachments/files/16440790/24d7f1b0-ad0f-49a8-8c93-a121e48cc63c.dmp)
[5cc817aa-dcf5-4e22-8744-0e211f052e43.dmp](https://github.com/user-attachments/files/16440791/5cc817aa-dcf5-4e22-8744-0e211f052e43.dmp)
[5dfc879c-2828-4019-b7d5-bb39dc6ef1f7.dmp](https://github.com/user-attachments/files/16440795/5dfc879c-2828-4019-b7d5-bb39dc6ef1f7.dmp)
[74893f20-8d37-4292-b05f-efd64a289cf9.dmp](https://github.com/user-attachments/files/16440800/74893f20-8d37-4292-b05f-efd64a289cf9.dmp)
[9a46b70a-ede7-416f-b888-45510010f7c7.dmp](https://github.com/user-attachments/files/16440805/9a46b70a-ede7-416f-b888-45510010f7c7.dmp)
[a76756bd-0918-4c61-88b9-8eb680aa311d.dmp](https://github.com/user-attachments/files/16440809/a76756bd-0918-4c61-88b9-8eb680aa311d.dmp)
[b1dbd0d4-0aa9-4589-a940-75442b5c7e52.dmp](https://github.com/user-attachments/files/16440817/b1dbd0d4-0aa9-4589-a940-75442b5c7e52.dmp)
[b35dc981-7e82-44f5-9568-ddfa85028a15.dmp](https://github.com/user-attachments/files/16440822/b35dc981-7e82-44f5-9568-ddfa85028a15.dmp)
[bc60969d-a4c6-4e20-b78e-85c925f93094.dmp](https://github.com/user-attachments/files/16440828/bc60969d-a4c6-4e20-b78e-85c925f93094.dmp)
[c45f5152-ce32-440e-ad07-8947071f295d.dmp](https://github.com/user-attachments/files/16440834/c45f5152-ce32-440e-ad07-8947071f295d.dmp)
[d5508e3c-784e-43f9-a567-07209f1558c0.dmp](https://github.com/user-attachments/files/16440837/d5508e3c-784e-43f9-a567-07209f1558c0.dmp)

**Comment by garrynewman** [comment]
These are all coming from vrad2.exe - which is kind of weird if the game won't launch

**Comment by mir0shjr** [comment]
After fooling around with WinDbg a little more, I found out that I'm a dummy and I didn't press a button to proceed
![image](https://github.com/user-attachments/assets/b1148a7a-40f4-4af9-9a98-e648fa0902e7)
After that I've tried to launch sbox.exe through it and I've also launched a pirated version of sbox that actually launched(the site where I downloaded it from says that it is version 27112021)
Also after I reinstalled sbox again through steam, it started to give me a different error
[Pirated.txt](https://github.com/user-attachments/files/16446542/Pirated.txt)
[License.txt](https://github.com/user-attachments/files/16446543/License.txt)
[License after reinstalling.txt](https://github.com/user-attachments/files/16446546/License.after.reinstalling.txt)

**Comment by mir0shjr** [comment]
The other guy also sent me his txt
[License other guy.txt](https://github.com/user-attachments/files/16469946/License.other.guy.txt)

**Comment by garrynewman** [comment]
Can you try this.. download dependencies, and run DependanciesGui.exe. Drag and drop SDL2.exe onto it.

You should see this, no red dlls, nothing missing.

![image](https://github.com/user-attachments/assets/9fe6a904-0407-40e3-a017-3ecaa94a4fac)

If that works, can you try the same with engine2.dll

![image](https://github.com/user-attachments/assets/89ce00e3-9b4a-4b4c-bd7b-8ecea87faa9b)

**Comment by mir0shjr** [comment]
![image](https://github.com/user-attachments/assets/2ed5124c-b0d6-4b74-9b66-3d6f1cf220a2)

![image](https://github.com/user-attachments/assets/bfc34920-a5b9-496f-a8ad-d9e13837c7aa)

**Comment by mir0shjr** [comment]
Actually, I found a few red dlls, after I opened dlls from message above

![image](https://github.com/user-attachments/assets/997be1fd-ddd9-4e64-ab0b-2c27d7d28efb)

![image](https://github.com/user-attachments/assets/dbe1e4cc-1aa5-462f-870e-a5c61bc39684)

![image](https://github.com/user-attachments/assets/be528d96-955f-4950-8df2-8503a4925887)

![image](https://github.com/user-attachments/assets/f8298b9e-1851-416a-834b-fcd519df58a2)

**Comment by garrynewman** [comment]
Something odd I'm seeing is that you don't have nethost.dll in your engine2.dll for some reason

**Comment by mir0shjr** [comment]
I have also opened sbox.dll in dependancies, it says that it misses "clr", "perfcounter.dll" and "Sandbox.AppSystem"

![image](https://github.com/user-attachments/assets/86959150-4cc4-45e5-91c8-fd60d21fa0fc)

![image](https://github.com/user-attachments/assets/107e63ab-0c7c-48ff-8985-8c4eabe39d4b)

**Comment by garrynewman** [comment]
I think that's pretty normal. I pushed an update earlier - can you see if you're still seeing the problem

**Comment by mir0shjr** [comment]
Still doesn't work

**Comment by kumulkumul** [comment]
![image](https://github.com/user-attachments/assets/a08e500b-9623-4223-bf41-563de610a867)
![image](https://github.com/user-attachments/assets/85fa6943-ee53-43eb-ae5e-e4a9f3c3fb81)
After installing smartsteamemu the game stopped working for me

**Comment by kumulkumul** [comment]
I found a problem with the game not starting. The pirated software created a steam_api64.dll file in the C:\Windows\System\ directory and when I deleted it, everything was fixed. If anyone has the same problem, they can try it.

**Comment by mir0shjr** [comment]
OH MY GOD MAN HOW DID YOU FIGURE THAT OUT

I've deleted those 2 files

![image](https://github.com/user-attachments/assets/0d6e0b35-f92e-4b01-9688-d9961bcbb116)

And guess what happened

![image](https://github.com/user-attachments/assets/410e26e7-b73f-4f53-a8fc-47540cc03d6c)

**Comment by mir0shjr** [comment]
I'll ask the other guy if this worked for him and close the issue if it did.
