### ISSUE TITLE
[ShaderGraph] Unhide Range Values on Floats

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#5966]
### Describe the bug

By default the Range values are now hidden in the properties for the Float, Float2 and Float3 nodes.
Because they used to be visible I assumed that they had been removed, I know that's not the case but I can imagine it may confuse other people too.

### To Reproduce

Add a Constant Float node, look at the Properties.

### Expected behavior

The range drop down should be shown by default, or put in the same category as the Value.

**Comment by handsomematt** [comment]
![image](https://github.com/user-attachments/assets/b6a5ab83-2ce3-4a9a-a91f-94d47b007a4e)

?

**Comment by Jammie3d** [comment]
![image](https://github.com/user-attachments/assets/a7b1e2da-a19d-47b3-864a-90a5ff978096)

Just verified files and it's still like this for me.

**Comment by Gmod4phun** [comment]
I believe Range was not always collapsed, and it would probably be a good idea to have it open by default
