### ISSUE TITLE
Morphs explode if there is morphs for different mesh components in the same file

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#5971]
### Describe the bug

Morphs explode if there is morphs for different mesh components in the same file
![sbox-dev_kjbeKLyv7G](https://github.com/user-attachments/assets/eac28378-85f0-4500-9058-07b5d4e1e7f2)

### To Reproduce

Here's a project with reproduction of the issue as well as what I did to work around it:
[morph_fuckup_repro.zip](https://github.com/user-attachments/files/16403082/morph_fuckup_repro.zip)

### Expected behavior

I would hope I can just have morphs for separate mesh elements in the same file and have them apply correctly, seems to be fucked in scene while looking fine in modeldoc so I know this setup should be possible.

**Comment by aylaylay** [comment]
I'm not sure if this has anything to do with morphs

**Comment by aylaylay** [comment]
It seems the one with morphs gets rid of the skeleton above the neck, causing the head to be skinned to root (pelvis)
I need to find out if this is something the importer is discarding or a fuck up in your exporter.

![Image](https://github.com/user-attachments/assets/d979291e-247c-482f-8821-31c33ca8ca2d)

**Comment by aylaylay** [comment]
Skinning weights seem to get fucked up around the head

**Comment by aylaylay** [comment]
Okay yeah loading the morphs are somehow fucking up the skinning, this might take a while to figure out

**Comment by aylaylay** [comment]
Fixed

![Image](https://github.com/user-attachments/assets/67575b1b-7850-45e6-90c9-5fc9ef703297)

**Comment by ShadowBrian** [comment]
Thank you layla very cool!
