### ISSUE TITLE
Move some of these sound settings to `.sound`

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#5978]
### For?

S&Box

### What can't you do?

There are sound settings when you click on a `.wav` file such as looping, sample rate, compression, etc. Why are these modified on the actual `.wav` file instead of the `.sound` file? Is there a case where this makes sense?
![image](https://github.com/user-attachments/assets/5376f851-e4d1-42b0-9fb5-1674f734ed9d)

### How would you like it to work?

I'd probably move a setting like `looping` to the `.sound` file itself, maybe the others as well?

### What have you tried?

...

**Comment by aylaylay** [comment]
These are on the wav meta file, they're needed here because they're used for compiling the sound. Sound event assets can be a collection of sounds.

**Comment by matekdev** [comment]
Yeah, I can understand that perspective. But even if sound events are a collection of sounds... could you imagine a case where you mix and match sound files where some are loops and others are not?

Anyways, it isn't too much of an issue, I just always found it an option that I'd expect in a `.sound` file, but I can see the justification for it remaining as is.
