### ISSUE TITLE
Traces can only ignore two entities

### ISSUE THREAD

**Issue by taek-dev** [Facepunch/sbox-issues#598]
**What can't you do?**
I can't have a trace ignore more than two entites. For example:
`			var tr = Trace.Ray( origin, destination )
					.Ignore( ent1 )
					.Ignore( ent2 )
					.Ignore( ent 3)
					.Run();
`
will return an error stating "Traces can only ignore two entities right now - need more? Tell me."

**How would you like it to work?**
I want to have a trace ignore more than two entities

**Comment by Rohansi** [comment]
What are you trying to ignore?

**Comment by taek-dev** [comment]
> What are you trying to ignore?

three entities
