### ISSUE TITLE
`OnAwake()` behavior is called Late

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5982]
### Describe the bug

Hi,

Since Saturday, July 28th, around the afternoon CEST, the behavior of the OnAwake() component seems to have changed, causing several Null Reference Exception issues in my project (m).

### To Reproduce

Here are the reproduction steps:

1) Download https://github.com/Facepunch/sbox-scenestaging.
2) Edit `NetworkTest.cs` with:
```
protected override void OnFixedUpdate()
{
    base.OnFixedUpdate();

    if (Input.Pressed("attack1"))
    {
        Log.Info("Attack1");

        ThrowEntity();
    }
}

public void ThrowEntity()
{
    Log.Info("ThrowEntity");
    var pc = GameObject.Components.Get<PlayerController>();
    var cc = GameObject.Components.Get<CharacterController>();
    var rotation = Rotation.LookAt(pc.EyeAngles.Forward);

    var goGrenade = new GameObject();
    var grenade = goGrenade.Components.Create<GrenadeEntity>();
    Log.Info("Grenade infos 1");
    Log.Info( grenade.WorldModel );

    grenade.WorldModel.Model = Model.Load("models/citizen/citizen.vmdl");

    grenade.Transform.Position = pc.Eye.Transform.Position;

    Log.Info("Grenade infos 2");
    Log.Info(grenade.Rigidbody);
    Log.Info(grenade.CapsuleCollider);

    grenade.Rigidbody.Velocity = rotation.Forward * 1000.0f;
}
```
3) Create a `GrenadeEntity.cs` file with the following content:

```
public class GrenadeEntity : Component
{
    [Property] public SkinnedModelRenderer WorldModel { get; set; }
    [Property] public Rigidbody Rigidbody { get; set; }
    [Property] public CapsuleCollider CapsuleCollider { get; set; }

    protected override void OnAwake()
    {
        Log.Info("OnAwake");
        GameObject.Name = GetType().Name;

        Rigidbody ??= GameObject.Components.GetOrCreate<Rigidbody>();

        CapsuleCollider ??= GameObject.Components.GetOrCreate<CapsuleCollider>();
        CapsuleCollider.Radius = 3f;
        CapsuleCollider.Start = new Vector3(0, 0, -2f);
        CapsuleCollider.End = new Vector3(0, 0, 3f);
    }
}
```
4) Start `networking.scene`, press `Attack1`, and look at the log.
You will notice that the `OnAwake` method of `GrenadeEntity` is called late, after the `Grenade infos 1` log.

This behavior was different before this day.

### Expected behavior

`OnAwake()` must be called directly after `var grenade = goGrenade.Components.Create<GrenadeEntity>();` calling

### Media/Files

![image](https://github.com/user-attachments/assets/733ddf8d-2d6f-495c-9708-cf8d2806804f)

**Comment by handsomematt** [comment]
I'd imagine this is your callback changes @garrynewman
