### ISSUE TITLE
Allow reshaping panels or using them as textures

### ISSUE THREAD

**Issue by GNUGradyn** [Facepunch/sbox-issues#5985]
### For?

S&Box

### What can't you do?

Do anything involving panels that are anything but flat rectangles. Cannot make wrap-around VR UIs, cannot curve HUDs, etc. 

### How would you like it to work?

Either allow using a panel as a material/texture or allow reshaping panels

### What have you tried?

A number of increasingly complex workarounds have come and gone with the API changes. Some examples
https://github.com/chrisspieler/sbox-rpg/blob/main/code/Components/MonitorComponent.cs
 https://github.com/Facepunch/sbox-issues/issues/3689
https://github.com/Facepunch/sbox-issues/issues/5591 (Linked repro projects)
ALL of these solutions are way too complex and don't work anymore anyway

**Comment by CarsonKompon** [comment]
You can definitely do this. In fact, all of the links under "What you have tried" still work to this day.

Simply follow the instructions in this comment: https://github.com/Facepunch/sbox-issues/issues/3689#issuecomment-1687219462
And **make sure you read the final sentence**. The code ***must*** be inside of a render block 👍 

If you want to see a practical example of it in action, you can clone [Rhythm4K](https://github.com/CarsonKompon/rhythm4k) and look at the Ring around the Sphere in the Main Menu scene. The texture of the ring is a UI Panel.
