### ISSUE TITLE
info_player_start cannot be rescaled.

### ISSUE THREAD

**Issue by michaelsucks** [Facepunch/sbox-issues#5986]
### Describe the bug

Changing the "Scales" for info_player_start in the Transform tab does not save. If the value is changed in Hammer, it will not save onto scenes and will remain as 1. The player model cannot be downscaled or upscaled. 

### To Reproduce

1. Go into Hammer and spawn a info_player_start entity.

2. Click on the info_player_start entity and change the value in Scales to make Terry bigger or smaller.

3. Fast compile the map.

4. In scenes, the value will always yield to 1 and discards the changed value. 

### Expected behavior

Changing the scale of info_player_start should make Terry either bigger or smaller. The value of 1 should be changed to whatever was inputted in Hammer. 

### Media/Files

![1](https://github.com/user-attachments/assets/2be87354-cc60-4d0c-b24f-9ba4aff0051e)
![2](https://github.com/user-attachments/assets/853442a4-4c34-4558-b123-0585a3a84dbc)
![3](https://github.com/user-attachments/assets/81d2cffc-a52c-40b3-b6cd-726073050e5b)
![4](https://github.com/user-attachments/assets/36a835ba-af24-44d5-92fd-6e32249fe200)

**Comment by aylaylay** [comment]
Map objects now use the scale from the keyvalues, note though that this doesn't scale your player, if that's what you're expecting. Player scale is up to each game to implement how they want.
