### ISSUE TITLE
Game keeps crashing every time i try to start it

### ISSUE THREAD

**Issue by motherfortress2** [Facepunch/sbox-issues#5988]
### Describe the bug

I've been trying to try out s&box ever since i joined the dev program. Every time results in a strange crash and a Vulkan error, but now it doesnt show. Another thing is when it misbehaves like this, an update rolls out. What could be the issue?

### To Reproduce

Unsure...

### Expected behavior

It should be starting up like normal.

**Comment by spacewd69** [comment]
Update: it will not start up anymore.

**Comment by spacewd69** [comment]
Update 2: i thought adding optimization launch commands would work but removing them made it work.

**Comment by PuzzlingGGG** [comment]
this happened to me too. i got screenshots of the errors:
![image](https://github.com/user-attachments/assets/1fa8e70e-174d-4ab4-9ec8-f4b4fe239b73)
![image](https://github.com/user-attachments/assets/d1f97de4-35b1-4864-9234-5ec869bba159)
i want this to be fixed too

**Comment by IMCraytex** [comment]
Puzzling, Can you try update your Nvidia Drivers?

**Comment by garrynewman** [comment]
> Update 2: i thought adding optimization launch commands would work but removing them made it work.

What commands had you added?

**Comment by bub-bl** [comment]
- Update your graphics drivers
- Uninstall some overlays like Overwolf, Rockstar Social club, Twitch, etc..
- Remove command line arguments
- Reset your NVIDIA settings by default in the Nvidia control panel

I had some problem with it in the past

**Comment by bub-bl** [comment]
You can also publish the latest log file located into the sbox installation folder at sbox/logs

**Comment by handsomematt** [comment]
not really any info to work with here
