### ISSUE TITLE
Crashing in map office and my own map.

### ISSUE THREAD

**Issue by Arturvitormb** [Facepunch/sbox-issues#599]
for some reason the game started crashing the game on the office map after game update

**To Reproduce**

1. open office map in any gamemode

**Expected behavior**

game crash

my map started to crash too which makes me think that the problem is in the game it tries to load the map assets, because I was using the office map as a placeholder

**Comment by gabengaGamer** [comment]
In a recent update, original valve light_cookies, has been broken , and now cause a crash, delete them

![image](https://user-images.githubusercontent.com/54669564/128520065-1ffaf163-549d-4614-8d59-ff88b92feff3.png)

**Comment by Arturvitormb** [comment]
> In a recent update, original valve light_cookies has been broken , and now cause a crash, delete them
> 
> ![image](https://user-images.githubusercontent.com/54669564/128520065-1ffaf163-549d-4614-8d59-ff88b92feff3.png)

weird, light cookies wasn't enabled here, but when I deleted the light_spots from my map it stopped crashing

**Comment by garrynewman** [comment]
Any news on this fix @samzanemesis?

**Comment by Arturvitormb** [comment]
ok i found something that can help with these lightcookie problems, i deleted the only lightspot that was parented in a prop and the crash stopped (just remembering i didn't have lightcookie enabled)

**Comment by Arturvitormb** [comment]
and the bakscratch office map also had light parent to prop_physics, I remember it had some light bulbs

**Comment by samzanemesis** [comment]
Should be fixed now
