### ISSUE TITLE
hotload_fast compile issues

### ISSUE THREAD

**Issue by BlakeWinser** [Facepunch/sbox-issues#5991]
### Describe the bug

With hotload_fast true some of my code is not compiling as expected and is still running even when deleted or commented out.

### To Reproduce

1. Remove/Comment out any function, after saving and compiling said function may still act as if working normally.

### Expected behavior

When saving and compiling, my code changes I have made should work as displayed within editor. Disabling hotload_fast fixes the bug instantly but this setting gets reset each time the editor is restarted.

### Media/Files

https://github.com/user-attachments/assets/fab0655b-ca4e-453b-b62c-ebe388aed4ab

### Additional context

VSCode latest build, C# and C# Dev kit extensions fully up to date. Is not happening in my main project, only a new project created specifically for the current game jam.

**Comment by BlakeWinser** [comment]
Essentially all I am doing in the uploaded video is:
1. Checking current fast_hotload setting
2. Commenting out my Crouch function and checking console after compiling to see if the Log.Info is still running even when the function is commented out.
3. Disabling fast_hotload, re-saving project. Fixes issue.

**Comment by Metapyziks** [comment]
I think I'll need to try it in your new project, unable to reproduce in HC1:

https://github.com/user-attachments/assets/ccdf9a4b-e6ce-4973-9719-4b505a6e7a95

Would you be okay with giving me access to your repo?

**Comment by BlakeWinser** [comment]
> I think I'll need to try it in your new project, unable to reproduce in HC1:
> 
>  fRUuTWQ32f.mp4 
> Would you be okay with giving me access to your repo?

Added you as a collaborator.

**Comment by Metapyziks** [comment]
Can reproduce it there, thanks!

**Comment by Metapyziks** [comment]
Fix is building now, thanks for your help!

**Comment by BlakeWinser** [comment]
No worries, thanks!
