### ISSUE TITLE
Editor Crashes when opening and previewing .png files

### ISSUE THREAD

**Issue by lu2000luk** [Facepunch/sbox-issues#5992]
### Describe the bug

The editor crashes when you double click on a .png file or when you set the view mode to small/medium/large icons.

### To Reproduce

1. Import a png
2. Double click
3. Crash (:

1. Import a png
2. Click view mode
3. Set it to one of the icon preview mode
4. Crash (:

### Expected behavior

It should open an image editor/OS's preferred image viewer

Generate the thumbnail normally

### Media/Files

In my case the .pngs where generated from importing a model

### Additional context

Windows 11 Pro Insider
x64
32 GB of ram
Ryzen 7 5700G
CPU's integrated GPU

Build ID: 15181917

**Comment by bub-bl** [comment]
PNG file doesnt have any editor widget binded for file type. So, that maybe the issue

**Comment by DoctorGurke** [comment]
Doesn't happen for me, using a png works fine and trying to open it will just tell you that there's no tool for it. `WARNING: No tool (internal or external) found for asset 'my/image.jpg'` ("jpg" being the internal asset type for any image file)

**Comment by CarsonKompon** [comment]
For me double clicking a png/jpg has always opened it as if it were a normal file (opens Paint.NET in my case since thats my default image editor). Odd that it would exhibit different behaviour for the 3 of us

**Comment by lu2000luk** [comment]
I can provide a video of the issue or any other info regarding my configuration

**Comment by lu2000luk** [comment]
Now the editor dosent crash but just plays the winodws error sound

**Comment by linkpy** [comment]
After mentioning an issue i had with 4k .png files on discord (just clicking on them in the asset browser crashes the editor), Carson told me to upload them here. 

Sadly they are a bit big due to being 4k. Here's where i got them : https://ambientcg.com/view?id=Rocks025 (4k-PNG is the one i used).

Hopefully this help with this issue.

**Comment by CarsonKompon** [comment]
@linkpy I was unable to replicate the issue on my end. I assume the reason this is happening is simply because you do not have enough VRAM to load the image due to it's size.
That being said, I also pushed a minor change I noticed I could make that *could* solve the issue but is highly unlikely.

**Comment by linkpy** [comment]
I doubt it @CarsonKompon :
![image](https://github.com/user-attachments/assets/64e47eab-7cb5-4a54-b7c6-63896ae9c04a)
The red line is when the crash happens. There is *plenty* of vram to spare here.

The crash also happens when enabling icons in the asset browser.

**Comment by lu2000luk** [comment]
> I doubt it @CarsonKompon :
> ![image](https://github.com/user-attachments/assets/64e47eab-7cb5-4a54-b7c6-63896ae9c04a)
> The red line is when the crash happens. There is *plenty* of vram to spare here.
> 
> The crash also happens when enabling icons in the asset browser.

ye the same happened to me. it somehow got fixed duh
