### ISSUE TITLE
Ambient Occlusion draws over World panels

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5996]
### Describe the bug

Having a world panel, you can see the AO of stuff behind it if AO is present on the camera.

### To Reproduce

1. Enable AO on camera
2. Make a world panel
3. See stuff through it

### Expected behavior

AO should not draw over world panels

### Media/Files

![image](https://github.com/user-attachments/assets/c04d30d4-6721-4980-a7d9-384bde321859)

**Comment by handsomematt** [comment]
#6429
