### ISSUE TITLE
Create Bone Objects not Creating all Bone Objects

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#5998]
### Describe the bug

When I activate the create bone objects bool, it only creates the first part of the skeleton chain, stopping at a twist bone.

### To Reproduce

1. Enable the skinned mesh renderer on a model rigged similar to mine (no clue what makes my model invalid)

### Expected behavior

Creating all the bone objects.

### Media/Files

![image](https://github.com/user-attachments/assets/c74c505c-9f75-4e84-b9e7-e6e2e985a119)
![image](https://github.com/user-attachments/assets/64d9be74-bd9a-4fee-8c1b-5e6f47bcd8d8)
https://github.com/SwagAccount/Sewer_Hell/tree/main/Assets/models/player -Vmdl, Fbx, anim graph

### Additional context

All the bones that I want to show are connected to the model and work in animation, even bone markups are not being created

**Comment by SwagAccount** [comment]
It seems to end where it reaches a bone that has no weights, it is still a bone markup though

**Comment by aylaylay** [comment]
All bones should show up as game object bones now
