### ISSUE TITLE
CameraComponent frustum gizmo shows incorrectly

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#5999]
### Describe the bug

The view frustum preview that a `CameraComponent` shows is incorrect. The most visible issue is that near and far planes aren't at correct distances. This issue affects both perspective and orthographic cameras.

### To Reproduce

1. Select a GameObject with a `CameraComponent` attached to it
2. Adjust the Znear, Zfar, and FOV properties

### Expected behavior

The frustum preview should accurately reflect the camera's settings.

**Comment by aylaylay** [comment]
It looks correct to me, can you show me how it looks incorrect for you?

**Comment by aylaylay** [comment]
This is how it works in unity

**Comment by Metapyziks** [comment]
Sorting out orthographic now, looks like Frustum.FromCorners doesn't quite work there?

**Comment by Metapyziks** [comment]
Thanks for the report!
