### ISSUE TITLE
Add Keyboard Shortcuts to TextEntry fields

### ISSUE THREAD

**Issue by EmNudge** [Facepunch/sbox-issues#6]
Currently, the cursor does not move any differently when navigating across text with <kbd>ctrl</kbd> held down in TextEntry fields. This feature request lists out what is needed for S&box's TextEntry fields to get on par with software such as Windows Notepad (which should serve as a decent base).

Rules vary across environments, so these were written when testing with Windows Notepad as it provides the bare minimum when it comes to text editing environments.
While the sample TextEntry fields in S&box are not multiline, I think it would be wise to allow for the possibility of multiline TextEntry fields in the future, so the rules here are written with that in mind (thus the term `newline` being mentioned in several rules).

Movement subrules have been written out in the form of regex for precision. 
`^` signifies the beginning of input, which in this case is right after the cursor.
`$` signifies the end of input, which in this case is right before the cursor/

- [ ] <kbd>ctrl</kbd>+<kbd>RIGHT</kbd>
next character is newline -> move right to the length of `/^\n\t* */`
next character is " " or "-" -> move right to the length of `/^-* +/`
next character is tab -> move right to the length of `/^\t* */`
else -> move right to the length of `/^[^- \n\t]+-*\t* */`

- [ ] <kbd>ctrl</kbd>+<kbd>LEFT</kbd>
previous character is newline -> move left one character
previous character is "-" -> move left to the length of `/\S+$/`
else -> move left to the length of `/[^- \t]+\t* *$/`

- [ ] <kbd>ctrl</kbd>+<kbd>BACKSPACE</kbd>
use <kbd>ctrl</kbd>+<kbd>LEFT</kbd> algorithm, but erase text passed over

- [ ] <kbd>HOME</kbd>
move cursor to after previous newline (or to beginning of text)

- [ ] <kbd>ctrl</kbd>+<kbd>HOME</kbd>
move cursor to beginning of text

- [ ] <kbd>END</kbd>
move cursor to before next newline (or to end of text)

- [ ] <kbd>ctrl</kbd>+<kbd>END</kbd>
move cursor to end of text

**Comment by garrynewman** [comment]
Want to do this @aylaylay ?

**Comment by Trojaner** [comment]
dont forget ctrl + shift + left/right for selecting text

**Comment by aylaylay** [comment]
Only just seen this, I'll check it out

**Comment by garrynewman** [comment]
Want me to do this @aylaylay?

**Comment by aylaylay** [comment]
Go for it, you're more familiar with the textbox stuff
