### ISSUE TITLE
hate me for it, but I asked the discord

### ISSUE THREAD

**Issue by Idiot64** [Facepunch/sbox-issues#60]
a LOT of people wanted a linux version, many many, more than I expected

close it, whatever, but please, don't ignore it :<

sorry for wasting you time..

im desperate..

**Comment by Idiot64** [comment]
:<

**Comment by ahhhh6980** [comment]
less than 1% of users on the steam hardware and software survey use linux

**Comment by Idiot64** [comment]
yes, but a LOT of them are interested in this

**Comment by Idiot64** [comment]
actually more than 1%

**Comment by JustPlayerDE** [comment]
I Can understand that you want linux support
but alot of 2.4% stays at max 2.4% of the potential playerbase

they wont add it now at least

**Comment by AdamSai** [comment]
Linux users are a very vocal minority. Also, this is the wrong place to ask for this.... you should close it

**Comment by Idiot64** [comment]
yes, but a LOT of the "2.4%" are interested in THIS

**Comment by Idiot64** [comment]
and that still is a lot

**Comment by JustPlayerDE** [comment]
yet they arent even finished making the game playable on windows, just wait and they maybe add it in the future when it increases

**Comment by ahhhh6980** [comment]
The steam software and hardware survey show 0.85% run a linux distro and 3% run Mac, I wish for linux support too, but it seems like the better option for them to develop for the dominant platform first.

**Comment by Yiluxius** [comment]
love how you're opposing "2.4% of the playerbase" with "IT'S ALOT OF PEOPLE THOUGH!!!!"

**Comment by JustPlayerDE** [comment]
also dont forget that those 2.4% are split up into differend distros
which means even more issues supporting it as maybe 40% of them use ubuntu based stuff for example while 30% are arch based

just adding linux support is not easy as it sounds
