### ISSUE TITLE
Networked Scene.Load doesn't work sometimes.

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#6000]
### Describe the bug

In a networked game, calling Scene.Load doesn't always load the new scene for the clients.

### To Reproduce

1. Create a simple networked game.
2. Call Scene.Load on the host.
3. The connected clients will not change scene after the host has finished loading.

### Expected behavior

The connected clients should change scene after the host has finished loading.

**Comment by handsomematt** [comment]
#6129
