### ISSUE TITLE
FOV seems lower than slider says when playing on ultrawide aspect ratio (32:9)

### ISSUE THREAD

**Issue by Kat299** [Facepunch/sbox-issues#6001]
### Describe the bug

When playing on a ultrawide monitor (in my case a 32:9 5120x1440 monitor), the fov  feels much lower than the slider says. 

### To Reproduce

Open s&box
play game on 32:9 resolution
realise that even if slider is 100fov the game feels zoomed in.

### Expected behavior

the game should not feel zoomed in on the monitor.

### Media/Files

![Untitled](https://github.com/user-attachments/assets/95323255-5ffc-4aea-8c29-ee0fd6f843f8)

**Comment by MD485** [comment]
If I put my camera on 100 FoV on my 12:9 screen I'm pretty sure it would look like this:
![image](https://github.com/user-attachments/assets/00231c60-c4ac-49e0-939a-1294ce8c4afa)
I'm a little confused on what you expect the scene to look like?
It's still 100 FoV, you just have more horizontal pixels so the frustrum is adjusted to account for that.
