### ISSUE TITLE
[Shadergraph] Open Generated Shader Button

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#6004]
### For?

S&Box, Other

### What can't you do?

Cannot open the generated shader from within shadergraph to quickly debug the output. I don't really see any reason you shouldn't be able todo that.

### How would you like it to work?

Add the following within the `CreateToolBar()` function in `MainWindow.cs` before  the line `_undoOption.Enabled = false;`

`toolBar.AddOption( "Open Generated Shader", "txtedit/appicon.png", () => OpenGeneratedShader() ).StatusText = "Open Generated Shader";`

Then add the following function 

```
private void OpenGeneratedShader()
{
	// If we are an untitled asset the user must have just opened the tool with no shadergraph asset. Make them save. Otherwise open the generated shader in a text editor.
	if ( _asset == null )
	{
	        
		Log.Warning( $"Asset not saved! please save now." );
		Save();
	}
	else
	{
	        var shadergrph_path = _asset.AbsolutePath;
	        var asset = AssetSystem.FindByPath( shadergrph_path.Replace( $"{_asset.Name}.sgrph", $"{_asset.Name}.shader" ) );
	        asset.OpenInEditor();
	}
}
```

### Result 
https://github.com/user-attachments/assets/efd94488-a49f-431d-83d8-730ee4c3f223

### What have you tried?

just opening the shader via the asset bowser in the main editor window.

**Comment by aylaylay** [comment]
Useful, I don't see any harm in adding this. Added.
