### ISSUE TITLE
Multiple [ShowIf] & [HideIf] attributes don't work

### ISSUE THREAD

**Issue by gio3k** [Facepunch/sbox-issues#6005]
### Describe the bug

Can't use multiple HideIfs (a property can have multiple, but it won't have the intended behaviour)

(note: should this be `!Any(x => !x.TestCondition(Parent))`?)
![image](https://github.com/user-attachments/assets/63d95e18-42a0-4a35-b8aa-04b5afd6491f)

### To Reproduce

```csharp
[Property]
private bool RequirementA { get; set; }

[Property]
private bool RequirementB { get; set; }

/// <summary>
/// requires RequirementA == true and RequirementB == true
/// </summary>
[Property, HideIf("RequirementA", false), HideIf("RequirementB", false)]
private bool TestProperty { get; set; }

/// <summary>
/// also requires RequirementA == true and RequirementB == true but uses ShowIf for B 
/// </summary>
[Property, HideIf("RequirementA", false), ShowIf("RequirementB", true)]
private bool TestProperty2 { get; set; }

```

### Expected behavior

TestProperty and TestProperty2 shouldn't show up without RequirementA and RequirementB being ticked

### Media/Files

![July2024-Tuesday30-12_02_56-sbox-dev](https://github.com/user-attachments/assets/62f56481-baf9-42c4-8407-9105521d4fc7)

**Comment by aylaylay** [comment]
It's a || not a &&, this would break how we're using them, and for other people.

```cs	
[Property, Title( "Radius" ), Group( "Hull" ), Resize]
[ShowIf( nameof( Type ), PrimitiveType.Cone )]
[ShowIf( nameof( Type ), PrimitiveType.Cylinder )]
public float Radius { get; set; } = 25.0f;
```

I agree that it's annoying we can't do both situations but this would be a breaking change.

**Comment by gio3k** [comment]
@aylaylay Do you think it's worth it to make this an API Design issue instead, or do you think this is off the table?

**Comment by aylaylay** [comment]
It's hard to say, you could argue for both ways. This should also work too

```cs
	[Property]
	private bool RequirementA { get; set; }

	[Property]
	private bool RequirementB { get; set; }

	private bool RequirementAB => RequirementA && RequirementB;

	/// <summary>
	/// requires RequirementA == true and RequirementB == true
	/// </summary>
	[Property, HideIf( "RequirementAB", false )]
	private bool TestProperty { get; set; }
```

**Comment by gio3k** [comment]
I'll give that a go - thanks for the help!
