### ISSUE TITLE
Re-add VideoPlayer.PlayAudio

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6007]
### For?

S&Box

### What can't you do?

I can no longer play audio from an online video using VideoPlayer.

### How would you like it to work?

Reimplement the VideoPlayer.PlayAudio method that used to exist.

### What have you tried?

It seems that the only way to get audio from online videos is to use a WebPanel, which lacks positional audio.

**Comment by aylaylay** [comment]
Sound should now play, and you've now got an audio accessor to set listen local and position of the sound

```cs
		Player.Audio.ListenLocal = false;
		Player.Audio.Position = Transform.Position;
```

**Comment by chrisspieler** [comment]
I can play audio from the VideoPlayer now. Thanks!
