### ISSUE TITLE
Give Sound.Play a target Mixer overload

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6008]
### What it is?

Sound.Play("whatever.sound") will play whatever sound on the default mixer, in order to send it to another mixer you need to do something like
```
var sound = Sound.Play("whatever.sound");
sound.TargetMixer = Mixer.FindMixerByName("notdefault");
```
which is frankly just annoying 

### What should it be?

Sound.Play("whatever.sound", Mixer.FindByName("notdefault")); would be hella nice

**Comment by aylaylay** [comment]
Added
