### ISSUE TITLE
Strange rope position

### ISSUE THREAD

**Issue by Bilwin** [Facepunch/sbox-issues#601]
**Describe the bug**
When trying to create a rope for welded objects, one of them gives the wrong rope vector.

**To Reproduce**
https://youtu.be/boKgZibkW7k
1. Create 4 boxes (or any prop)
2. Weld first box to second, 3 to 4
3. Create rope for 1-3, 2-4 boxes

OPTIONAL
5. Remove "strange" box
6. See error

**Expected behavior**
Correct position of the ropes

**Screenshots**
https://i.imgur.com/WCAJ0ms.png
https://i.imgur.com/mkf40gt.png

**Additional context**
Gamemode used to test bug: facepunch.sandbox
Map used to test bug: facepunch.construct
Using last s&box version

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by Bilwin** [comment]
Fixed,
