### ISSUE TITLE
Can we change bones from being procedural to animated in script?

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6020]
### For?

S&Box

### What can't you do?

I want to match a certain part of  skeleton to something else and to do that I want to be able to modify the bone positions to match. I want to move parts of my skeleton from being procedual to animated to do this. Is this possible?

### How would you like it to work?

I don't understand how the procedual to animated system works in the first place so I can't really suggest anything

### What have you tried?

bone merging but that does the entire skeleton

**Comment by CarsonKompon** [comment]
Yep, should totally be possible. All that the widget is doing is flipping the `GameObjectFlags.ProceduralBone` flag on `GameObject.Flags`.

**Comment by SwagAccount** [comment]
ahhh it is a flag, thanks carson
