### ISSUE TITLE
RenderFragment doesn't always re-render when a child has changed

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6023]
### Describe the bug

I have a component with a RenderFragment property called Content.
I have been added the Content property to the BuildHash override, but when the content of the Content render fragment change, the content is not updated.

### To Reproduce

- Create a Panel component named "MyComponent":
```html
@using Sandbox
@using Sandbox.UI
@inherits Panel
@attribute [StyleSheet]

@namespace Sandbox

<root>
	@Content
</root>

@code {
    public RenderFragment Content { get; set; }
    protected override int BuildHash() => HashCode.Combine(Content);
}
```
- Create a PanelComponent named "MyPage"
```html
@inherits PanelComponent
@namespace Sandbox

<root>
	@* This code is updated *@
	<span>A value: @MyValue</span>
	@* --------------- *@
	
	<MyComponent>
		<Content>
			<div>
				@* This code is not updated *@
				<span>A value: @MyValue</span>
				@* --------------- *@
			</div>
		</Content>
	</MyComponent>
</root>

@code {
    private int MyValue { get; set; }

    protected override void OnUpdate()
    {
        MyValue = Game.Random.Next();
    }

    protected override int BuildHash() => HashCode.Combine( MyValue );
}
```

### Expected behavior

The Content Fragment must be updated when the value of MyValue is updated.
In the real razor world (Blazor), the RenderFragment is updated when the value of any of his child is updated

### Media/Files

https://github.com/user-attachments/assets/06a432f6-e9f9-4d32-9066-6ec241c65ce4

**Comment by solwllms** [comment]
This has been fixed I think, working as expected now
