### ISSUE TITLE
Unable to delete/remove nodes from ActionGraph

### ISSUE THREAD

**Issue by chuntfungus** [Facepunch/sbox-issues#6027]
### Describe the bug

Whenever I add a node or a comment into the ActionGraph, I am unable to delete it either by pressing the delete key or right-clicking it to remove it. The only way I have found to clear the graph is to remove it from the component and then re-make it. 

### To Reproduce

1. Create an action graph
2. Add a node
3. Select it
4. Try to hit delete/Right click it to select delete.

### Expected behavior

Node should be deleted after hitting delete

**Comment by prboba** [comment]
Delete button works but on selected object in scene overlaping action graph even if its selected, other hotkeys like cut, copy, paste affects both selected gameobject and node at same time

**Comment by Metapyziks** [comment]
@CarsonKompon is this related to a fix you're working on atm, or shall I have a go?

**Comment by CarsonKompon** [comment]
> @CarsonKompon is this related to a fix you're working on atm, or shall I have a go?

I'm taking a look right now, will keep you posted

**Comment by CarsonKompon** [comment]
This is resolved in my latest commit :)
