### ISSUE TITLE
[ShaderGraph]  Having a constant that is marked  "isattribute" in the chain of nodes before time breaks time.

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#6028]
## Describe the bug

Time will break if there is a constant marked as `is attribute` is in the chain of nodes before `time` is multiplied in ( See Attached Video ).

## To Reproduce

1. Open Supplied Project.
2. Notice that initially the waves on either of the meshes in the scene are not moving. They appear static unless you move them. 
3. Open `shaders\garstner_test.shdrgrph`
4. Notice how within the shadergraph preview the waving motion is present on the model while in scene it is not.
5. Go to the constant called `Gravity Constant`  within the `Wave Speed Comment` and Uncheck `is attribute`.
6. Compile and save the shader.
7. Go back to the editor and notice that the waving motion on the meshes is occurring as it should.

## Expected behavior

For the waving motion to work regardless if a constant that is marked `is attribute` is before the time node.

### Demonstration 

https://github.com/user-attachments/assets/aed72345-e47d-40ef-bf51-cc248a2fc60e

### Repro Project
[attributetime_bug.zip](https://github.com/user-attachments/files/16434943/attributetime_bug.zip)

**Comment by aylaylay** [comment]
So this has nothing to do with messing up time. Because you have gravity as an attribute, you're expected to set that attribute in code. I'll see if we can set defaults on them.

**Comment by aylaylay** [comment]
Attributes now set their default value

**Comment by QuackCola** [comment]
Oh that makes sense  thanks layad!
