### ISSUE TITLE
Editor Hotkeys ignore active window

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6030]
### Describe the bug

When using any tool that opens a separate window, be it hammer, action graph or hotspot editor, if you press any of the function key shortcuts that are set, the editor will prioritize them, instead of intended shortcut in the active tool window.

I think this only happens with function keys, as it didn't appear to happen with say, CTRL+G from my testing

### To Reproduce

1. Open any separate window tool, for example hammer
2. Have a map open so you had a reason and ability to switch views on function keys
3. Try switching to fullbright 3D view if it isn't open (F5)
4. Start the game instead of switching to fullbright view :(

### Expected behavior

The Editor hotkeys should not override the keys of the active window, allowing you to use shortcuts of the tool you are using, like hammer

**Comment by CarsonKompon** [comment]
Ive fixed this in my latest few commits: https://github.com/Facepunch/sbox-issues/issues/6039
