### ISSUE TITLE
MeshTraceRequest.Result VertexDetail data not populated

### ISSUE THREAD

**Issue by YtnomSnrub** [Facepunch/sbox-issues#6033]
### Describe the bug

The `Vertex0`, `Vertex1`, and `Vertex2` properties in the `MeshTraceRequest.Result` returned by `modelCollider.Model.Trace.Run()` don't have data.

I've attached a .zip with a simple repro of the issue that logs the vertex data from `MeshTraceRequest.Result`, along with the `HitPosition` just to show that the trace is working properly.

[MeshTraceVertexRepro.zip](https://github.com/user-attachments/files/16435996/MeshTraceVertexRepro.zip)

### To Reproduce

In the attached repro, run the scene and hover the mouse over the curved mesh. The "Vertex positions" log entry only contains `0, 0, 0` for all three vertices, but should contain the appropriate vertex data.

### Expected behavior

The `Vertex0`, `Vertex1`, and `Vertex2` properties from the `MeshTraceRequest.Result` should contain the relevant `Position`, `Uv0`, etc values for the vertices from the hit triangle.

### Media/Files

![image](https://github.com/user-attachments/assets/51f67673-037b-4e2c-82c3-a52e3f97b3e8)

Here is a snippet of the logs I get from running the repro.

**Comment by aylaylay** [comment]
You should be able to access the vertices now

**Comment by YtnomSnrub** [comment]
Can confirm this is working correctly for me now on the most recent build:
![image](https://github.com/user-attachments/assets/ddff64b0-aff4-4fe4-9bc0-9aefa6be812e)
