### ISSUE TITLE
Add the ability to disable shadows on line renderers

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6037]
### For?

S&Box

### What can't you do?

I am currently unable to turn off the shadows on line renderers resulting in stuff like this:
![image](https://github.com/user-attachments/assets/3934a97a-4ba4-4c32-96a8-c3c90b597ac8)

### How would you like it to work?

A button that disables shadows on the component editor.

### What have you tried?

The line renderer particle on the scene staging branch doesn't have the issue!

**Comment by aylaylay** [comment]
Added LineRenderer.CastShadows
