### ISSUE TITLE
Function keys are being used in scene when hammer window is active

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#6039]
### Describe the bug

Using the function keys in hammer no longer functions and instead get used in scene (ie f5 for fullbright will play your game etc). It is possibly related to the editor keybinds merge.

### To Reproduce

1. Open anything in hammer
2. Try to switch between F5 and F6 or something similar

### Expected behavior

Should change view in hammer and not do anything in scene while hammer window is active

**Comment by CarsonKompon** [comment]
Should be good after my latest commits :)

**Comment by bj0key** [comment]
The F5 keybind's now working properly after your commit (<3), though the issue's still there for me with F3, just as a heads-up

**Comment by CarsonKompon** [comment]
> The F5 keybind's now working properly after your commit (<3), though the issue's still there for me with F3, just as a heads-up

Should be fixed in the next build 👍
