### ISSUE TITLE
Editor Keybinds don't support non-english layouts

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6044]
### Describe the bug

When using a non english layout (language), pressing any button that would change when swapping the language doesn't perform the bound action.
This is actually so bad, that it literally prevents editor camera movement, but somehow combos like CTRL C are unaffected.

### To Reproduce

1. Change keyboard layout to anything that isn't English
2. Try to move the editor camera with WASD
3. Observe NRE spam in console

### Expected behavior

It should not do that and just let you use the buttons regardless of language

### Media/Files

![2024 07 31_17 46 19](https://github.com/user-attachments/assets/35b2f108-f3a5-4a28-8954-0aa2039e21f5)

**Comment by CarsonKompon** [comment]
@rzkid Give the latest build a try once it's finished and let me know if it works for you :)

**Comment by rzkid** [comment]
@CarsonKompon Good news! NRE is gone.

Bad news: the actions still don't register, aka I still can't move while in non-english.

**Comment by CarsonKompon** [comment]
> @CarsonKompon Good news! NRE is gone.
> 
> Bad news: the actions still don't register, aka I still can't move while in non-english.

Doesn't allow you to rebind at all? What is your keyboard layout?

**Comment by CarsonKompon** [comment]
Let me know if everything's working after this most recent commit builds 👍
