### ISSUE TITLE
Editor running slowly while complaining many errors

### ISSUE THREAD

**Issue by AnpyDX** [Facepunch/sbox-issues#6045]
### Describe the bug

As the title says, editor runs slowly (2 FPS) and outputs endless errors, but basically these two
- **Call to vkCreateSwapchainWSI returned an error.**
- **invalid texture handle for "xxx"!**

### To Reproduce

It is confusing that this error only happens on my computer, which just happened when the eidtor window showing up. So i cannot give such detail of how to reproduce this issue.

### Expected behavior

Eidtor shouldn't report these two errors and should run smoothly (faster than 2 fps at least).

### Media/Files

![editor-screenshot 2024-07-31 224813](https://github.com/user-attachments/assets/406108e5-daf6-4a5d-bfad-ae44e470c5f7)
[Log.log](https://github.com/user-attachments/files/16443709/Log.log)

### Additional context

OS: Windows 11 23H2
CPU: Intel Core i5 12600K
GPU: AMD Radeon RX 6600 XT

VulkanSDK 1.3.216.0 and 1.3.261.1 installed additionally

**Comment by AnpyDX** [comment]
**Uninstalling RenderDoc can fix this confusing bug.**

**Comment by handsomematt** [comment]
Likely had outdated renderdoc trying to hook incorrectly
