### ISSUE TITLE
F6 Videos don't work anymore

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6049]
### Describe the bug

Capturing a video with F6 instantly just prints "Video finished" in chat and if you look at the exported video in your screenshots folder they're all 261 bytes, I assume a header or metadata. 

### To Reproduce

1. Boot up a game
2. Press F6 to start recording
3. View your screenshots folder

### Expected behavior

![image](https://github.com/user-attachments/assets/c81f19b3-2440-4b49-a243-473e3472bb54)
Required field chihuahua.

### Media/Files

![image](https://github.com/user-attachments/assets/30d61595-1b23-44c9-ad52-c2d71e1cad55)

https://github.com/user-attachments/assets/81d7ce7c-c25c-410d-9f38-6f6ed7b334f9

**Comment by yuberee** [comment]
UPDATE:
Updated S&box and now it does generate videos but they are all 00:00 seconds long because they start and stop instantly.
![image](https://github.com/user-attachments/assets/45863027-c81d-434f-ac5d-5ba78105fe1c)

**Comment by Gmod4phun** [comment]
On my end I see no issues, videos save and play properly. Sbox is updated to the latest version. In case its not a keybinds problem and is system specific, my specs are: Windows 10, RTX 3060 Ti and Ryzen 5 5700X.

**Comment by CarsonKompon** [comment]
Seems to be happening because the `video` command is getting called while you have focus of the game view (while also calling the video shortcut). It shouldn't be able to invoke that command at all. I'll take a look

**Comment by CarsonKompon** [comment]
Should be good on the latest build 👍
