### ISSUE TITLE
Game can't find Steam while launching from Steam

### ISSUE THREAD

**Issue by 7ez** [Facepunch/sbox-issues#6050]
### Describe the bug

I'm trying to launch the game via Steam, but instead of the game launching, I get an error that Steam was not found.
I've tried reinstalling the game and Steam, but none worked.

### To Reproduce

1. Open the game

### Expected behavior

Game launches without any issues

### Media/Files

![image](https://github.com/user-attachments/assets/aa8d9e6e-4ed5-42c6-88ab-633b8b136305)

### Additional context

I'm on Windows 11, my computer specs are: Intel Core i5-12400F, NVIDIA GeForce RTX 3060 and 16GB of RAM (DDR4 3200MHz).

**Comment by garrynewman** [comment]
Is steam up to date? Are you out on a beta version?

**Comment by 7ez** [comment]
Steam is up to date, and I'm not on a beta version.

![image](https://github.com/user-attachments/assets/2f42d667-e1f5-48a9-a600-09d719a0e645)
![image](https://github.com/user-attachments/assets/3ea5af52-b69f-4432-938b-0a596478d109)

**Comment by 7ez** [comment]
It appears to have fixed itself.
Sorry for any inconvenience.
