### ISSUE TITLE
2D Skybox "Tint" lighting keeps resetting

### ISSUE THREAD

**Issue by FawasInteractive** [Facepunch/sbox-issues#6054]
### Describe the bug

Changing the tint variable in the 2D Skybox component will impact both lighting and the actual skybox color. However, switching between game and scene views will reset the lighting impact, but retain the skybox color.

### To Reproduce

1. Enter a scene
2. Change skybox tint
3. Switch to game view (the lighting tint will be reset)

-

1. Load a scene and click "Play"
2. Change skybox tint
3. Exit play mode (the lighting tint will be reset) EDIT: upon further testing this seems to only happen sometimes, not entirely sure why or how it can be reproduced.

You can also change the tinted value to the same value it is already set as to reproduce. For example:
1. Change skybox tint in scene mode to any tint value, but an example is "#9500FF"
2. Click Play, in the game view the lighting should now be back to the default sky tint
3. Click on skybox tint value, copy it, click backspace, then paste the values back
4. Lighting should now be tinted as intended

### Expected behavior

Skybox tint should save

### Media/Files

![image](https://github.com/user-attachments/assets/cb989498-84d8-4c51-95c4-b88c0d37ba08)
![image](https://github.com/user-attachments/assets/224bd109-3bb7-4f8c-be12-0a8efa783f76)

![image](https://github.com/user-attachments/assets/fa7bc141-b61b-47f6-8eed-ca8307275aec)
![image](https://github.com/user-attachments/assets/65b479c3-010c-435f-a74c-17416bffc21e)

**Note how the lighting is the same as the Game View Default Tint Value image, meanwhile the skybox color tint is the same as it should be.**
![image](https://github.com/user-attachments/assets/c11edb46-208f-4d4c-9b40-60a5c610efdd)

**Comment by aylaylay** [comment]
Fixed
