### ISSUE TITLE
Sync Attribute isn't allowing compiling due to missing attribute System namespace

### ISSUE THREAD

**Issue by dudetru25** [Facepunch/sbox-issues#6055]
### Describe the bug

when trying to hot reload I get this attribute error only when using sync attribute
![image](https://github.com/user-attachments/assets/3b7e91bd-66e5-4927-88ae-7f29485ab4a7)

So far there isn't anything specific to the code itself that is causing this issue you can see the script below
![image](https://github.com/user-attachments/assets/3b3858dd-20ba-4e00-bfd6-2a07a6e0e60c)

### To Reproduce

Create a new class, add the [Sync] attribute to any type. Trigger a hot-reload.

### Expected behavior

should allow a recompile

**Comment by CarsonKompon** [comment]
You shouldn't have your code in the namespace `Sandbox.System.Modules`, you should have your own namespace.

Besides that, your code looks like it should run otherwise. Resolve the namespace issue and you should be good.

**Comment by dudetru25** [comment]
> You shouldn't have your code in the namespace `Sandbox.System.Modules`, you should have your own namespace.
> 
> Besides that, your code looks like it should run otherwise. Resolve the namespace issue and you should be good.


So far I've updated the namespace on it and I still get the same problem with it?
![image](https://github.com/user-attachments/assets/07d47ae6-61f7-4613-b7a3-a03a963d0bea)


it seams from the cached decompiled version of the code rider shows. It seams like sync doesn't have the System namespace compared to other decompiled properties?

PropertyAttribute
![image](https://github.com/user-attachments/assets/149ba927-0efb-4897-aa7d-b5ac5d5f8c02)

SyncAttribute
![image](https://github.com/user-attachments/assets/c8ebc5e8-5071-4de4-a24c-6bd795eab6a4)

**Comment by CarsonKompon** [comment]
Have you tried verifying integrity of game files on steam? Maybe even uninstalling and re-installing? Seems like there might be some sort of weird file desync. Could you also paste the entire file just for 100% clarity?

**Comment by dudetru25** [comment]
I verified the integrity of the files. Only 20 weren't in. But it's currently still returning the same problem
![image](https://github.com/user-attachments/assets/93125724-db73-46c5-9a9c-b52e74454cf1)
![image](https://github.com/user-attachments/assets/06e029d0-8c1d-4657-be39-3e10fd04eb72)


here is the current sync file from the cache. It wouldn't allow me to upload directly the csharp file
[Sync.json](https://github.com/user-attachments/files/16459497/Sync.json)

**Comment by CarsonKompon** [comment]
I'm not sure what you're sending here.
I need to see your EntityComponent file in order to know what the issue is (since that's the source of the error as shown in the image you have sent). If you cannot include the contents of the c# file in a comment then use pastebin and supply a link to that

**Comment by dudetru25** [comment]
here is a paste bin of the whole file. it's not a big file I will note. I've tried using it on other types as well but it seams like a universal problem. 
[https://pastebin.com/xkkhbLsj](https://pastebin.com/xkkhbLsj)

**Comment by CarsonKompon** [comment]
Is it perhaps because your namespace contains "System" in it? If changing that doesnt fix it I would appreciate it if you could send a zip of your project

**Comment by dudetru25** [comment]
okay so I changed the namespace from "RankUpGamesLLC.System.Module" to "RankUpGamedLLC" only removing the System. From the looks of it did fix it where I can reference Sync now in the attribute and it compiles correctly.  My question now is what's the reason for System within the namespace name cause this problem?

**Comment by CarsonKompon** [comment]
I *believe* this is because CodeGen adds some code when using [Sync] attributes that attempt to reference `System`, which conflicts and returns your namespace's `System` instead since the generated code is within that namespace.

@kurozael / @Metapyziks not sure if this is something we could detect/throw a better error for?
