### ISSUE TITLE
Copying / Pasting Component Variable Also Copies / Pastes Selected GameObject

### ISSUE THREAD

**Issue by FawasInteractive** [Facepunch/sbox-issues#6057]
### Describe the bug

Selecting, for example, a string input field or a color value input field in a component, doing Ctrl+A to select all the text, and copying or pasting will not only copy paste the value in the input field, but also the entire selected GameObject.

### To Reproduce

1. Click on an input field in a GameObject's component
2. Ctrl+A
3. Ctrl+C
4. Ctrl+V. There will now be a duplicate GameObject of the object with the component you had selected.

### Expected behavior

The component value that you're copying or pasting should be the only thing copied / pasted.

### Media/Files

Not visible in the video, but after selecting the color value I hit "CTRL+C" and "CTRL+V".

https://github.com/user-attachments/assets/03fc3b1d-ad29-46fa-bc0d-0d02a73a037f

**Comment by CarsonKompon** [comment]
I didn't even know you could do CTRL+C/V on components so I haven't converted them to the new system yet 😅

Will do this first thing tomorrow morning
