### ISSUE TITLE
Add local space option for particle angles

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6059]
### For?

S&Box

### What can't you do?

I'm trying to create a particle effect that has a flat surface with a rocket trail:

https://github.com/user-attachments/assets/3d902b14-45d9-4f59-b749-826c5478bffe

As you can see in the video however, the flat particles don't follow the rotation of the game object.

### How would you like it to work?

Having an option to make the particles rotation follow local space would be ideal.

Maybe slap it in here:
![image](https://github.com/user-attachments/assets/e0ae3caa-1b6e-4bd7-86a9-df326f402a4b)

### What have you tried?

Manually calculating the appropriate angles and applying them in a component

**Comment by Fortune117** [comment]
Here's the prefab if that helps:
[projectile_rocket.zip](https://github.com/user-attachments/files/16450432/projectile_rocket.zip)

**Comment by aylaylay** [comment]
you're missing a bunch of things from your prefab repro

**Comment by Fortune117** [comment]
Woops, let me double check it

**Comment by Fortune117** [comment]
[rocket.trail.zip](https://github.com/user-attachments/files/17499472/rocket.trail.zip)

This one should work. The rocket_heater game object is responsible for the flat flame particle, which is supposed to orient itself to face the direction of the game object, but that's not possible at the moment.

**Comment by aylaylay** [comment]
How's that?

https://github.com/user-attachments/assets/c67ac278-a866-4453-ac9f-12515a640960

**Comment by Fortune117** [comment]
> How's that?
> sbox-dev_wPXQU0YbTa.mp4

Exactly the effect I'm looking for

**Comment by Fortune117** [comment]
Messing around with the change, this is almost what I want. It's better than how it was but I'd like the ability to have the particles angles be relative to its gameobject, rather than the angles being set to the same as the game objects.

https://github.com/user-attachments/assets/ac22f58a-1aa9-45ed-9abb-08e4efc2917d

I believe it'd be better to be able to make the angles supplied in the particle effect component be set to local:
![Image](https://github.com/user-attachments/assets/f06e8464-7585-40fe-b09c-efbc23328844)

You can see in the video I've provided that the particles, when set to follow the game objects rotation, all are rotated exactly the same. This makes the appearance of the effect weaker as it loses some of the naturalness that comes with randomized per-particles rotation.

**Comment by Fortune117** [comment]
Some images to highlight loss of effect detail:

Using particle rotation:
![Image](https://github.com/user-attachments/assets/b4a52d94-c038-47a4-b21f-b9219748bc97)

Using object rotation:
![Image](https://github.com/user-attachments/assets/5c05c74b-32a1-4546-af51-53cbe54077b2)

When every particle is the same orientation it makes the effect look somewhat unnatural.

**Comment by aylaylay** [comment]
I weighed up the options and decided it's still better as an alignment mode. Pitch yaw and roll is applied to it.

https://github.com/user-attachments/assets/b6ec0466-40f0-45e2-a9bf-1c111d95e21f

**Comment by Fortune117** [comment]
Excellent, works great. Thanks :D
