### ISSUE TITLE
EnumWidget doesn't display key using a (bitwise or) value

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6065]
### Describe the bug

EnumWidget doesn't show key with a bitwise or value

### To Reproduce

- Create an enum like:
```csharp
[Flags]
public enum Fruits : ulong
{
    Apple = 1 << 0, // Visible
    Banana = 1 << 1, // Visible
    Another = 1 << 2 | Apple, // Visible
    All = Apple | Banana // Not visible
}
```

### Expected behavior

The EnumWidget must be show (bitwise or) values

**Comment by aylaylay** [comment]
Fixed, it will now show them all so you can opt out with HideAttribute
