### ISSUE TITLE
Set the centre of mass of a rigidbody.

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6070]
### For?

S&Box

### What can't you do?

I'm trying to move a rigidbodys collider the physics will still rotate around the original centre of mass.

### How would you like it to work?

Either let us recalculate the centre of mass or set it manually.

### What have you tried?

I have tried to disable and enable the motion enabled function bool, it only seems to work in the editor.
When I do that it recalculates the centre of mass and the physics work how I want, you can see me doing it in this video.

https://github.com/user-attachments/assets/cf124aa5-4886-4599-9455-cb2390085c2d

**Comment by SwagAccount** [comment]
I was switching motion on and off before I changed the collider lol.

This is still a thing we should have though

**Comment by MD485** [comment]
```cs
Rigidbody rb;

//Setting the center
var myVector = new Vector3( 0, 10, 0 );
rb.PhysicsBody.LocalMassCenter = myVector;

//Rebuilding the mass
rb.RebuildMass();
```
Do neither of these work?

**Comment by SwagAccount** [comment]
> ```cs
> Rigidbody rb;
> 
> //Setting the center
> var myVector = new Vector3( 0, 10, 0 );
> rb.PhysicsBody.LocalMassCenter = myVector;
> 
> //Rebuilding the mass
> rb.RebuildMass();
> ```
> 
> Do neither of these work?

I haven't, didn't think about the physics body. It might work, not sure as Laylad has assigned it

**Comment by SwagAccount** [comment]
Yeh, there is no rebuild mass.

**Comment by MD485** [comment]
`rb.PhysicsBody.RebuildMass();`
Sorry, typo.
![image](https://github.com/user-attachments/assets/42d651e9-3785-485d-bce3-2cd3205d7f7d)

**Comment by aylaylay** [comment]
There's a few options here. We can have a center mass override or have a center mass offset which is an offset to the calculated shapes center of mass.

**Comment by Gmod4phun** [comment]
A center mass override feels like a more user friendly approach compared to the offset.

**Comment by aylaylay** [comment]
I agree, unity also does it that way

**Comment by aylaylay** [comment]
Added mass center override

https://github.com/user-attachments/assets/c7fd42dc-f8da-4344-874d-0d44fda6f86d
