### ISSUE TITLE
Clear Console On Play throwing ToolsDLL Error

### ISSUE THREAD

**Issue by tylerstraub** [Facepunch/sbox-issues#6073]
### Describe the bug

When the "Clear Console On Play" option from Editor Settings is checked it does not perform the expected result, instead throwing an error to the console on trying to Play the scene. 

`ToolsDll Error calling event 'scene.play' on 'Editor.ConsoleWidget' (QPushButton was null when calling setText)`

### To Reproduce

0. be on current Steam release branch of the editor
1. enable the "Clear Console On Play" option
2. play the scene
3. observe console output

### Expected behavior

Clear Console On Play works

### Media/Files

![image](https://github.com/user-attachments/assets/36c256f4-eb66-4c1c-b905-1535bc923b46)
![image](https://github.com/user-attachments/assets/dccd9d8d-9017-4e16-a3c8-7b9311fd1b87)

**Comment by kurozael** [comment]
I think this got fixed but the issue was never closed. Unable to reproduce.
