### ISSUE TITLE
VR Resolution is wrong

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#608]
VR Resolution seems to use the screen/viewport resolution instead of the native HMD resolution.

This is quite easy to replicate since when opening the console the HMD display will go lower resolution as the game window is viewported.

**Comment by walllable** [comment]
This also seems to affect object culling, though this seems like it has more to do with the aspect ratio of the window rather than resolution, strictly speaking. When the window is square culling is fine, but when the window is wide things cull away too early on the top and bottom.
