### ISSUE TITLE
steam was not found

### ISSUE THREAD

**Issue by Alexleu49** [Facepunch/sbox-issues#6081]
### Describe the bug

when starting the game via steam, it writes the error "steam not found"

### To Reproduce

starting the game

### Expected behavior

starting the game

### Media/Files

![как](https://github.com/user-attachments/assets/7c8091fc-af99-4e34-b705-420e28d5a36f)
[Log.log](https://github.com/user-attachments/files/16473249/Log.log)

**Comment by handsomematt** [comment]
I think this might be because you have some steam emulator running from pirated games
