### ISSUE TITLE
[Standalone] Add ability to use Facepunch `Auth Tokens` service

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6083]
### For?

S&Box

### What can't you do?

Hi,

Adding the ability to use the current [Facepunch Auth Token service](https://docs.facepunch.com/s/sbox-dev/doc/auth-tokens-qGVLV3Chzn) to ensure requests are sent by a specific Steam user would be cool.

Or getting an "official" workaround/advice.

### How would you like it to work?

Ability to use the Facepunch Auth Token in standalone mode

On [Discord](https://discord.com/channels/833983068468936704/1267416344899354646/1268992970393391225), *mike is also mentioning the [Facepunch.Steamworks](https://github.com/Facepunch/Facepunch.Steamworks) library as workaround.

### What have you tried?

- Used the Facepunch Auth Token in standalone mode (not working)
- Read the current standalone statement in [the July blog post](https://sbox.game/news/july-update-97c0fa3c/standalone-exporter)

**Comment by xezno** [comment]
Not planned right now
