### ISSUE TITLE
`[Sync] Component` are not synchronized for new users

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6086]
### Describe the bug

Hi,

I would like to implement the recent feature for networking a component, but I’m having trouble with a secondary user instance. After a new user joins, it seems that the snapshot doesn’t correctly establish the link between the already existing components in the network.

Let’s jump to the reproduction steps.

### To Reproduce

1) Download my reproduction project: https://github.com/PolSpock/sbox-componentnetwork
This contains a simple debug project:

- NetworkedLobby.cs creates the networking logic: lobby creation, player state game object, player pawn game object.
- Pawn.cs is an empty component.
- PlayerState.cs waits for a Pawn assignment.

2) Start `minimal.scene`

3) Join with a secondary user and check the console logs.
- Each second, it prints the current state of player connections and Pawn assignments for each PlayerState component.
- Every 10 seconds, a `Network.Refresh()` is called to highlight the issue. Before this refresh, on the secondary user’s console, the previous Pawn of the already connected user (the host) appears as null.

Additionally, if you recompile or perform a `Network.Refresh()`, the synchronization issue will be resolved, and the Pawn will no longer be null.

### Expected behavior

The new user should receive the `[Sync] Component` already synchronized upon joining, without needing any `Network.Refresh()`.

### Media/Files

Reproduction steps in video:

https://github.com/user-attachments/assets/2911fdc3-9cfd-45bf-bd3a-febe929a7622

**Comment by the-remeko** [comment]
I ran into this the other day, and I worked around it by making sure the component to be Synced came before the component with the Sync property in the hierarchy.

I think the Sync references are resolved before all components have been loaded, so any Synced properties whose components haven’t been loaded yet won’t be resolved properly.
