### ISSUE TITLE
Replacing components faster

### ISSUE THREAD

**Issue by l0000000000000000000l** [Facepunch/sbox-issues#6087]
### For?

S&Box

### What can't you do?

Can't switch component fast
![image](https://github.com/user-attachments/assets/e3879822-238e-4437-add3-ccbad99a48eb)

### How would you like it to work?

Add option to replace component when you right click it

### What have you tried?

Delete the unwanted component add the one I want

**Comment by aylaylay** [comment]
Added

https://github.com/user-attachments/assets/f7068f7c-3f32-4024-8785-bfea9553f713
