### ISSUE TITLE
Export Feature: GameMenu Failed to copy vmat_c deps

### ISSUE THREAD

**Issue by tylerstraub** [Facepunch/sbox-issues#6088]
### Describe the bug

I've encountered an issue with the new project binary export functionality. When I attempt to launch my project as a binary export, it freezes on a blue screen. However, the project works fine when published to the main hub. I have to terminate the process via Task Manager to exit.

During the export process, multiple errors indicate that certain `.vmat_c` files are missing from the core library. Here are the error logs:

```
05:08:09   CompileGroup/Publish Building 2 compilers
05:08:23   GameMenu Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/core/envmap_filtering_cs.vmat_c, file doesn't exist
05:08:23   GameMenu Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/core/lpvgridmaterial.vmat_c, file doesn't exist
05:08:23   GameMenu Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/core/downsample_cs.vmat_c, file doesn't exist
05:08:23   GameMenu Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/core/tiled_light_culling_cs.vmat_c, file doesn't exist
05:08:24   GameMenu Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/dev/rtx/binlights.vmat_c, file doesn't exist
05:08:24   GameMenu Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/dev/rtx/hitgroup_default_opaque.vmat_c, file doesn't exist
05:08:24   GameMenu Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/dev/rtx/hitgroup_default_transparent.vmat_c, file doesn't exist
05:08:24   GameMenu  [1] Failed to copy C:/Program Files (x86)/Steam/steamapps/common/sbox/core/materials/core/lpvgridmaterial.vmat_c, file doesn't exist
```

I verified that these file paths indeed do not exist in my core library.

**Steps to Reproduce:**

1. Export the project as a binary.
2. Attempt to launch the exported binary.
3. Observe the blue screen and the need to terminate the process via Task Manager.

Has anyone else experienced similar issues with the new binary export functionality? Is this a known issue or something that needs to be addressed?

*Strauberry* on Discord suggested I submit this as an issue and post it in the `📤standalone` channel.

### To Reproduce

1. Export the project as a binary.
2. Attempt to launch the exported binary.
3. Observe the blue screen and the need to terminate the process via Task Manager.

### Expected behavior

Binary Export works and does not complain about missing vmat_c files

### Media/Files

![image](https://github.com/user-attachments/assets/474ba908-6184-43d3-ba49-2cd6bd6b4718)

### Additional context

- The issue does not occur when the project is published to the main hub.
- This problem has been observed on the following setup:

**Comment by xezno** [comment]
Yeah, these aren't of any concern but are annoying

**Comment by xezno** [comment]
Fixed this a while back
