### ISSUE TITLE
s&box editor crashes upon pressing shift

### ISSUE THREAD

**Issue by Moth-Soup** [Facepunch/sbox-issues#6089]
### Describe the bug

I was working on my game in the editor and I was going to select multiple items in the asset browser but it crashed, I went to report it thinking it was just that but then when recording it for the report it turned out to just be when I pushed shift.

### To Reproduce

1. Press shift

### Expected behavior

It shouldn't crash when shift is pushed.

### Media/Files

https://github.com/user-attachments/assets/51098e76-c8e9-4249-b081-cc204c3533f5

### Additional context

I doubt it would be caused by this but might as well try since Fallout 76 breaks because of this but my monitor did broke so I'm using an old square monitor I found laying around till I can afford a new one. It has a resolution size of 1280x1024, I don't know when it was made probably 2010 - 2015 and I have no idea what it's called but its a DELL monitor.

**Comment by handsomematt** [comment]
we can't really do anything with this information
