### ISSUE TITLE
FMOD Studio Library

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6090]
### For?

S&Box

### What can't you do?

Everyone knows that middlewares are cool. They provide you with features the base engine does in a different way, or doesn't do something outright. FMOD Studio is no exception to this, and provides very good set of audio features, that the base engine might not have in a good way for a long time or not at all. You can come from any engine to any other engine, and not have to code or relearn anything (besides the implementation itself but that sounds less cool), the FMOD is a constant that is good enough to keep.

I am not so sure on how the API is currently able to be stretched to allow a whole middleware implementation, which is why this is a request here, rather than just doing it ourselves.
And with standalone in sight, this would be a great addition to the heap of existing libraries, as "actual games" would benefit greatly from something as substantial as a mature, solid audio backend that was already went through fire by years of many A's.

[AND the free indie license is good enough for people to actually use it, without paying 5 thousand billion dollar.](https://www.fmod.com/licensing)

### How would you like it to work?

There are "official" implementations for [Unreal](https://www.fmod.com/docs/2.03/unreal/welcome.html) and [Unity](https://www.fmod.com/docs/2.03/unity/integration-tutorial.html), that have entire documentation pages dedicated to their integration, and many many open sources implementations as well, which even have multiple godot implementations [(1)](https://github.com/alessandrofama/fmod-for-godot) [(2)](https://github.com/utopia-rise/fmod-gdextension)
It would probably be logical to take cues from how unity does it, but it has a long install wizard with a million steps, that might not be desirable, or maybe it's fine, I don't know.

### What have you tried?

I have tried using the S&Box's native audio solution, and while it is nothing bad, FMOD is still better in almost all ways (and my FMOD addiction is stronger and requires another dose which this great engine does not have yet). It would be a great hackweek project to fix this mistake, by expanding engine to allow for more middleware like this, and implementing this as an example middleware library.

### Additional context

If you are scared about licensing or the whole corporate side of distributing a library, as long as it's an optional library that doesn't ship natively it is most likely fine (it would be weird if it wasn't fine). If you want to be **extra** sure, you can make supplying your own .lib files (that you can only get from a download locked behind creating a free account on their site - basically agreeing to their ToS) a mandatory step.

**Comment by bub-bl** [comment]
s&box use SteamAudio. I think Facepunch will not add support for FMOD

**Comment by handsomematt** [comment]
Not for a long time if at all
