### ISSUE TITLE
[Standalone] Map Instance fails to function leaving a blue void

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#6091]
### Describe the bug

When running an exported project that makes  use of a map instance . In my case the map `facepunch.square`. the standalone exe runs fine its just the upon load all that exists is a  blue void with a lonely black terry.

### To Reproduce

1. clone this project : https://github.com/QuackCola/sbox-kuwahara-filter
2. launch the project  and then export it.
3. run the exported project and then upon loading you  shouldn't see any of the map `facepunch.square` at all. all you should see is a blue void and a lonely pitch black terry.

### Expected behavior

To see everything as it appears in the editor in the exported project.

### Media/Files

![Screenshot 2024-08-03 005217](https://github.com/user-attachments/assets/29b326ed-696b-4934-8d02-45bbf7305cec)

[Log.log](https://github.com/user-attachments/files/16478181/Log.log)

**Comment by xezno** [comment]
This is intentional, you can't access the backend in standalone games. If you want to use a map then it'll have to be a local one
