### ISSUE TITLE
Mixer settings don't save

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6092]
### Describe the bug

When clicking off a mixer, the float slider values are not saved:
![image](https://github.com/user-attachments/assets/269b92ad-1f60-4a3c-976c-1a1c591275be)

### To Reproduce

1. Open mixers
2. Click on mixer of choice
3. drag the sliders around
4. click on a different mixer and then back
5. values have reset

### Expected behavior

Values should save.

**Comment by Rylius** [comment]
Happens for me too.
Ctrl+S triggers a "Save Mixer!" log message and immediately resets all "Voice Handling" sliders ("Volume" stays on the same value, but hasn't actually changed).
It did create the `ProjectSettings/Mixer.config` file, but its contents don't reflect the sliders either (it's all default values).
