### ISSUE TITLE
Game not start

### ISSUE THREAD

**Issue by Slowmoney** [Facepunch/sbox-issues#6096]
### Describe the bug

I click launch in steam and game not started

### To Reproduce

1 Launch on Steam

### Expected behavior

game started

### Media/Files

[Log.log](https://github.com/user-attachments/files/16480657/Log.log)

### Additional context

Ryzen 7 5800x
Nvidia 1070
48gb ram

**Comment by Slowmoney** [comment]
[1]    2101 segmentation fault  ./sbox.exe

**Comment by Slowmoney** [comment]
jan 2024 can started

**Comment by handsomematt** [comment]
uninstall or update rtss & fpsmon

**Comment by Slowmoney** [comment]
solved
