### ISSUE TITLE
border-style does not exist

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#6098]
### What it is?

You can set the border's style with a `border` shorthand, but there is no property for it.

### What should it be?

Formal syntax according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/border-style):

```
border-style = 
  <line-style>{1,4}

<line-style> = 
  none | hidden | solid | ...........
```

which also defines [border-top-style](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-style), [border-right-style](https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-style), [border-bottom-style](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-style) and [border-left-style](https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-style).

**Comment by xezno** [comment]
#2726
