### ISSUE TITLE
Persistent Data

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#61]
Opening up discussion on persistent data.  

Will there be an API to let us save data?

I've got a few ideas here:

1. In case of dedicated servers, give a launch parameter that lets those who know what they're doing run System.IO etc server-sided.
2. HTTP requests allowing me to make calls to my own API on the web.
3. A database API and a mysql/nosql/similar database for each gamemode (could be cheated pretty easily, might require fp servers to host gamemodes)
4. Not a big fan of Steamworks like leaderboard system.  It would be nice for some quick and easy leaderboards but beyond that, not enough power.

**Comment by Erlite** [comment]
Isn't persisting data more up to the gamemode/addon/server owner than Facepunch? 

`System.Net.HttpClient` is plenty enough along with `System.Text.Json` to communicate with an API. Both *should* be safe, IIRC `System.Text.Json` can de-serialize to types, but you have to explicitly use a generic or a `Type` variable (so as long as there's no way to get the type of a dangerous class, it shouldn't cause any issue. Even then, it'll probably refuse to de-serialize any class that shouldn't be). 

If an API isn't required or overkill/a bad idea for what you're working on, you could probably just use SQL libraries serverside (or better yet, EFCore so you can play a game of switcheroo and support local databases and remote databases with the same code, even though I'd always recommend remote databases, I like giving the choice to the server owner). 

Classic JSON files are still possible. I mostly use them for configuration files, not for persisting player data, not the best idea for that.

**Comment by cr4yz** [comment]
JSON is great.  It would be useful to have a something like Protobuf or MessagePack as well for data that needs the extra compression to save on disk or bandwidth.  I.e. my speedrun gamemode would like to save replays.  A replay consists of thousands of ticks worth of position and rotation data.

About HTTP requests, it's probably enough for the well-versed devs.  But giving an easy data api would accommodate everybody and allow for quick prototyping, no need to program a web server.

**Comment by Erlite** [comment]
S&box should allow newer developers to learn and improve their skills, so I don't think it'll be much of an issue. There's no real catch-all for APIs, so I don't think FP can even hand out one for developers to use. If anything, it'll push people to learn to make their own APIs, even in C# with ASP.NET Core which makes it simple.

**Comment by trundleroo** [comment]
For dedicated servers, I think a web API is the smartest way to handle persistent data, but it's not a catch-all. Dedicated servers aren't even implemented yet. Data persistence, and especially statefulness, need to be considered for gamemodes that you can spin up simply to play with friends (the current method to play). 

If someone creates an open source gamemode like an MMORPG and wants progression and data persistence across a server network, that is one problem. But allowing a user to download that gamemode and play it themselves is another problem entirely. Other issues arise, such as allowing users to reset/delete their data if they want to replay a gamemode from scratch. Is this an issue for the gamemode developer or should s&box have built-in (and local, of course) statefulness? I think the latter is much more user friendly.

**Comment by Trojaner** [comment]
This was discussed on the old Discord and garry was not a fan of connecting to databases directly. Instead he suggested using APIs instead which lead to some controversy. After the discussion he was looking into a C# NoSql solution and liked LiteDB.

**Comment by garrynewman** [comment]
I think you want to deal with this on a case by case basis, depending on what you want to do.

Your speedrun gamemode, for replay uploads, should totally be using steamworks imo. Is there any reason you wouldn't want to use it for this?

**Comment by cr4yz** [comment]
> Your speedrun gamemode, for replay uploads, should totally be using steamworks imo. Is there any reason you wouldn't want to use it for this?

I think it's okay for storing replay files, I used SteamRemoteStorage before for it.  Steamworks Leaderboards though, I'll dodge that if I can.

It's nice to have a relational database to keep track of players, points awarded, maps completed/maps left to complete, official/approved maps, in-depth player profiles, etc.  For this http requests to my web server might be ideal, have a fileid column that points to the UGC

Another thing I'm considering is SteamRemoteStorage lets clients store files on Steam, but in case of dedicated servers it would be best to let the server record & save the replay.  Idk if SteamRemoteStorage works without a SteamClient or has an alternative.

**Comment by Jake-Rich** [comment]
Does local filesystem access fall under the same umbrella as Persistant Data?

**Comment by Ceveos** [comment]
I think this is a very much needed implementation for certain gamemodes.

Lets take a hypothetical RPG game. It would be nice if I could create "RPG World" where you have character stats that you can level up. Now, you can join my dedicated server of it or spin up your own private session. Regardless of what you do, your stats carry with you. You can play with friends alone and still feel accomplished. Then join the main server when desired.

If we can do HTTP requests or websockets, that would be enough. I can load and save changes on-the-fly and have it be persistent between servers. However, the only requirement I believe is this **can't** be done on the client side. If a client could access their "save" file for a game mode, it would be trivial to cheat.

**Comment by HydroCG** [comment]
I'd like to leave my 50 cents here and say that a library for SQL access would be very good.

I see the arguments in allowing people to write their own HTTP server and access SQL through that, but that just adds another potential point of failure and a potentially massive security vulnerability because there are plenty of developers who won't write a secure application to host their API on, or who could just mess up when deploying it into their hosted environment. 

It seems sensible to just allow direct connection to something like an AWS RDS instance and then for the host to only need to keep their credentials secure. Also, this is just a massive nice-to-have.

**Comment by sanny-io** [comment]
The solution is to allow loading external dlls with a launch parameter. Not everyone uses an SQL database or wants to roll their own API or websocket server.
