### ISSUE TITLE
Can't focus on the ActionGraph window anymore when struct editor is open

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6109]
### Describe the bug

I have a [Property] struct that contains an ActionGraph for interactions.
Now when opening the struct editor and then opening the ActionGraph, I am forced to focus on the editor, making editing the actiongraph impossible.

### To Reproduce

```
	public struct MyCoolStruct
	{
		[Property]
		public Action MyAction { get; set; }
	}

	[Property]
	public MyCoolStruct MyCool { get; set; }
```
Put this in a component, start editing the struct, create a new actiongraph.

### Expected behavior

![image](https://github.com/user-attachments/assets/11bf1bdb-f859-47c1-be53-418d77be573b)

### Media/Files

[AUDIO ON]

https://github.com/user-attachments/assets/8aa8c3f5-69d3-44d0-bb3c-41e57bc0897d

**Comment by Metapyziks** [comment]
I guess the struct editor is modal. I could try making the AG editor window a child of it for this kind of case.
