### ISSUE TITLE
Change callback for console variables

### ISSUE THREAD

**Issue by FullStack0verfl0w** [Facepunch/sbox-issues#612]
**What can't you do?**
I'd like to track whenever my console variable changes, validate and set it to default/previous value if the value is not valid. 

**How would you like it to work?**
Something similar with network callbacks.
```
[ClientVar("my_variable"), OnChangedCallback]
public static string MyVariable { get; set; } = "Hello";

private void OnMyVariableChanged(string currentValue, string nextValue)
{
    if ( /* Something happened */ )
    {
        SetClientVar("my_variable", "bla bla bla");
    }
}
```

**What have you tried?**
A porn with ```{ get { return MyVariable; } set { /* Do some shit here*/ } }``` which crashes the game. xD

**Additional context**
Or is there a way to do this that I don't know?

**Comment by handsomematt** [comment]
Sorry this took so long, should be as simple as:

```csharp
[ConVar.Replicated( "my_variable" ), Change]
public static float MyVariable { get; set; } = 100.0f;

public static void OnMyVariableChanged( float oldValue, float newValue ) { }
```

Let me know if it doesn't work as expected.
