### ISSUE TITLE
The Hitbox Component Doesn't Seem To Work With UseHitboxes()

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6120]
### Describe the bug

For some reason the hitbox component doesn't work, but hitboxes from model works

### To Reproduce

1. Place an object
2. Add a hitbox component.
3. Shoot raycast at object with UseHitboxes().
4. Check if hitbox hits the object.

### Media/Files

A video of my guns working on a hitboxes from model component and not working on hitbox component.

https://github.com/user-attachments/assets/e2a53117-d010-4be5-9470-f2f2e623a9d6

**Comment by SwagAccount** [comment]
bump, pretty please

**Comment by SwagAccount** [comment]
https://github.com/SwagAccount/Sewer_Hell - Please

here is the repository, I've set up a gameobject with a raycast pointed towards a hitbox, it doesn't work on this project.

I got it to work on someone elses project though so it is unique to mine

**Comment by SwagAccount** [comment]
I got someone to test my repository, the same person who had it working in their own project, it doesn't work on there end either.

I need this for my game desperately, thanks

**Comment by SwagAccount** [comment]
For some reason, removing the target made it work, why?

**Comment by SwagAccount** [comment]
^ sometimes it doesn't, sometimes is does, sometimes doing something completely different on the hitbox works, idk

**Comment by SwagAccount** [comment]
https://github.com/user-attachments/assets/776d7a7a-86e8-41cf-b552-6d62b27cbef7

**Comment by aylaylay** [comment]
they should work now

**Comment by aylaylay** [comment]
Keep in mind that hitboxes don't support game object scale
