### ISSUE TITLE
Generic Exception when getting API "https://services.facepunch.com/sbox/package/stats/[game ident]/u/[steam id]

### ISSUE THREAD

**Issue by agincel** [Facepunch/sbox-issues#6122]
### Describe the bug

```
Stats.PlayerStats playerStats = Sandbox.Services.Stats.GetLocalPlayerStats( "marble_racer" );
await playerStats.Refresh();
if ( playerStats.TryGet(ident, out var stat))
{
    Log.Info( "Retrieved stat: " + ident + " with value: " + stat.ValueString );
    return stat;
}
```

This feels correct as far as the documentation for querying stats goes, but this is returning an exception on the web request with no additional details.

All of the stats in question exist in the web interface and submitting to them with `Sandbox.Services.Stats.SetValue( ident, value )` works as expected.

### To Reproduce

Attempt to use the attached StatsHelper to query any stat, and see an error.

### Expected behavior

Querying stats works as expected. (Unless I'm doing something stupid here?? In which case maybe better docs / error messaging?)

### Media/Files

[StatsHelper.zip](https://github.com/user-attachments/files/16492224/StatsHelper.zip)
![image](https://github.com/user-attachments/assets/793c1e52-559a-4b15-a468-0e4037fa3012)

**Comment by garrynewman** [comment]
Hey is this still happening?
