### ISSUE TITLE
cmemory

### ISSUE THREAD

**Issue by themunchkincutie** [Facepunch/sbox-issues#6123]
### For?

S&Box

### What can't you do?

so basically i cannot run the game because i guess my ram on my laptop or whatever doesn't have enough memory to run it. is there any way i can get it to where s&box can run on my computer or do i just have to get a whole new laptop entirely? i just got the laptop not too long ago and it runs very well on everything I've ran it on, was even able to do some complex things in blender on it. its a semi modern computer that came with windows 11. i have 8 gb of ram
and a 11th gen intel-i3 1124G4, i dont know about the graphics card, it could be intergrated but i have no clue but im pretty sure it is it doesnt say anything about it in the about computer in the settings

it seems like it should run well on my computer yet i get this message every time.

### How would you like it to work?

maybe doing some setting that helps s&box run on lesser software if thats possible

### What have you tried?

i have tried closing everything i could close but steam and sandbox

**Comment by Nolankicks** [comment]
I don't think it's a ram issue. I just think you have unsupported hardware.

**Comment by themunchkincutie** [comment]
> I don't think it's a 100% ram issue. I just think you have unsupported hardware along with a very low amount of ram.

i mean i looked up the specs needed for s&box and they seem to fit well within my spec range and it did say atleast 8 gbs of ram, i hope it's not entirely because it's source 2 or else i probably wouldn't  be able to play any other source 2 games

**Comment by Nolankicks** [comment]
> > I don't think it's a 100% ram issue. I just think you have unsupported hardware along with a very low amount of ram.
> 
> 
> 
> i mean i looked up the specs needed for s&box and they seem to fit well within my spec range and it did say atleast 8 gbs of ram, i hope it's not entirely because it's source 2 or else i probably wouldn't  be able to play any other source 2 games

This was probably before they switched to vulkan. So if your computer can't run vulkan it can't run s&box.

**Comment by cs716** [comment]
I assume you mean 11th gen intel-i3 112**5**G4? I can't find anything for 1124G4. It shouldn't be a Vulkan issue. Onboard graphics would be Intel UHD Graphics for 11th Gen Processors which supports Vulkan 1.2 (unless s&box requires support for 1.3 but I'm not sure on that). 

Are you getting an error when you try to launch it, or just low performance? 
Have you checked your used physical memory usage with only s&box and Steam open?

**Comment by themunchkincutie** [comment]
> > > I don't think it's a 100% ram issue. I just think you have unsupported hardware along with a very low amount of ram.
> > 
> > 
> > i mean i looked up the specs needed for s&box and they seem to fit well within my spec range and it did say atleast 8 gbs of ram, i hope it's not entirely because it's source 2 or else i probably wouldn't  be able to play any other source 2 games
> 
> This was probably before they switched to vulkan. So if your computer can't run vulkan it can't run s&box.

im pretty sure it runs vulkan? idk maybe maybe not idk, ive seen some games I've played before say vulkan in the name of their windows

**Comment by themunchkincutie** [comment]
> I assume you mean 11th gen intel-i3 112**5**G4? I can't find anything for 1124G4. It shouldn't be a Vulkan issue. Onboard graphics would be Intel UHD Graphics for 11th Gen Processors which supports Vulkan 1.2.
> 
> Are you getting an error when you try to launch it, or just low performance? Have you checked your used physical memory usage with only s&box and Steam open?

its an error message

ill probably check it but it doesn't seem to put much noticable strain on my computer when i do run it

**Comment by themunchkincutie** [comment]
> > > > I don't think it's a 100% ram issue. I just think you have unsupported hardware along with a very low amount of ram.
> > > 
> > > 
> > > i mean i looked up the specs needed for s&box and they seem to fit well within my spec range and it did say atleast 8 gbs of ram, i hope it's not entirely because it's source 2 or else i probably wouldn't  be able to play any other source 2 games
> > 
> > 
> > This was probably before they switched to vulkan. So if your computer can't run vulkan it can't run s&box.
> 
> im pretty sure it runs vulkan? idk maybe maybe not idk, ive seen some games I've played before say vulkan in the name of their windows

im pretty sure it means it's running on a version using vulkan

**Comment by handsomematt** [comment]
you dont have enough memory
