### ISSUE TITLE
Support for legacy GPUs

### ISSUE THREAD

**Issue by thesquaredude1** [Facepunch/sbox-issues#6126]
### For?

S&Box, Other

### What can't you do?

Currently, I cannot play S&box due to my GPU not supporting Vulkan.

### How would you like it to work?

Add support for OpenGL (anything before OpenGL 4), or DirectX 12 (or lower).

### What have you tried?

Adding -dx12 to launch options, did not work.

**Comment by samzanemesis** [comment]
What's your system specs? How come your system supports D3D12 but not Vulkan?

**Comment by thesquaredude1** [comment]
> What's your system specs? How come your system supports D3D12 but not Vulkan?

intel hd 5500 - supports dx12, but not vulkan, supports most open gl versions below 4

**Comment by Nolankicks** [comment]
The flag is -dx11 if you want to give it a try.

**Comment by thesquaredude1** [comment]
> The flag is -dx11 if you want to give it a try.

i already asked this on reddit, reddit member said that dx11 does not work anymore.

**Comment by thesquaredude1** [comment]
https://www.reddit.com/r/sandbox/comments/1eks15t/play_on_nonvulkan_supported_hardware/

**Comment by Nolankicks** [comment]
That was me lol 😅

**Comment by Nolankicks** [comment]
It may still work. I haven't checked. It's not supported though

**Comment by thesquaredude1** [comment]
oh

**Comment by thesquaredude1** [comment]
> It may still work. I haven't checked. It's not supported though

does not work

**Comment by samzanemesis** [comment]
We only plan to support Vulkan at the moment, sorry

Seems Intel supports Vulkan on Linux but this is a configuration that is not officially supported by us either

**Comment by thesquaredude1** [comment]
> Seems Intel supports Vulkan on Linux but this is a configuration that is not officially supported by us either

windows 11, oof

**Comment by thesquaredude1** [comment]
i use a laptop so i can't change the gpu
