### ISSUE TITLE
[Shadergraph] shaders fail to compile

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#6128]
### Describe the bug

Upon opening a graph even a blank one. Shaders will not compile.

### To Reproduce

1. open shadergraph.
2.  try to compile empty shadergraph.
3. see that there is a compile failed in console.

### Expected behavior

for the shaders to compile

### Media/Files

![Screenshot 2024-08-05 160748](https://github.com/user-attachments/assets/87137ff2-f69a-4e33-8885-ec4febf336f0)

**Comment by tylerstraub** [comment]
https://github.com/user-attachments/assets/0c62ec7d-e18c-42fc-82b7-b142c97a4bfc

**Comment by tylerstraub** [comment]
is there any known workaround to this problem right now?

**Comment by aylaylay** [comment]
Fixed
