### ISSUE TITLE
Add a texture size clamp option for vtex files

### ISSUE THREAD

**Issue by stellawisps** [Facepunch/sbox-issues#6130]
### For?

S&Box, Material Editor

### What can't you do?

Limit the resolution of a texture on export in the engine, you have to open the image in editing software and manually lower the resolution and save it again. This feature does exist in the material editor, however it doesn't apply when you save.

### How would you like it to work?

a slider in VTex assets that goes from 64x64, 128x128, 256x256, etc, and upon export the texture is limited to that resolution to save storage space

### What have you tried?

I have been manually lowering image resolutions but this takes a long time when you have a lot of textures.

**Comment by Generalisk** [comment]
Such A thing already exists, at least in the Material Editor.
![image](https://github.com/user-attachments/assets/8fd5ad0c-4111-4069-a5bc-2b871c34e956)
![image](https://github.com/user-attachments/assets/72578784-b8b1-43a7-896f-c37279d5f686)
