### ISSUE TITLE
VR heavy stutters - frame timing issue in editor play mod

### ISSUE THREAD

**Issue by Holydh** [Facepunch/sbox-issues#6131]
### Describe the bug

VR framerate seems inconsistent when in playmod in editor. Even though Virtual desktop performance overlay displays 90fps, it's stuttering heavily.
The issue seems less visible when the game view is docked to the editor, and worse when the game view is set aside in it's own window.
A few people in the VR discord channel mentioned it's a frame timing issue : https://discord.com/channels/833983068468936704/834357840646504478/1269830788262789192

### To Reproduce

Launch any project in VR.

### Expected behavior

Some sweet butter smooth frames please <3

### Additional context

Steam ID 64 = 76561198072754594
Win10

**Comment by xezno** [comment]
Not much I can do about this without more info. We're rendering the game twice anyway, so it's always going to run worse than non-VR mode

**Comment by Holydh** [comment]
I see. But the issue doesn't seem related to performance. I reach to get 120 fps on my project. And the issue is less visible at 120 fps. Don't you experience it yourself on your machine ? It's like a subtle "something feels off" feeling, it's a different feel than just low fps stuttering. But it's definitely there.
I'll try to dig it and find you some more info after the gamejam. 
Thanks a lot for your follow up in any case.

**Comment by Retroeer** [comment]
I ran a series of tests using several pieces of software, I used the scenestaging repo to test these, heres what I found

Hardware:
- RTX 2070 (non-super)
- AMD Ryzen 7 5800X3D
- 32GB Ram
- USB 3.(something) Link Cable
- Quest 3
- Windows 11

## Virtual Desktop: 
https://github.com/user-attachments/assets/8bb3e57e-2f66-4dae-8c85-8422867ccb08
I'm unsure if you can see it through video, but I'm getting constant stuttering, this makes me almost immediately nauseous
![image](https://github.com/user-attachments/assets/67c8c582-e947-4336-9e64-557e53df173f)

## Oculus Air Link:
![image](https://github.com/user-attachments/assets/636ea7da-10f4-4c38-80e6-85695555b09b)
The video would be identical to the one posted previously, the only difference is that this ran worse (stutterin remained constant)

## Oculus Cable Link:
For whatever reason this refused to work (thanks shitty oculus software), however, I did catch a glimpse of it for a second, while the image quality was a bit better, the stuttering was still constant

## Steam Link
Did not work, did not test, presumably has the same issues
