### ISSUE TITLE
Scroll Wheel Default Bindings

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#6132]
### For?

S&Box

### What can't you do?

Scrolling is currently only analog, so by default it can't be bound to any actions, and I feel like it should be.

### How would you like it to work?

Keep the current implementation of the scroll wheel, but allow binding scroll up or down to input actions as well (a lot of people have complained about this as they want scroll jump)

### What have you tried?

manually coding it into my game is fine, but I should be able to bind buttons to scroll wheel in any game without them specifically coding it (maybe let them disable it as it could be used for cheating)

**Comment by DevulTj** [comment]
I agree
