### ISSUE TITLE
RunAll trace with UseHitboxes only returns the first object with a hitbox

### ISSUE THREAD

**Issue by Rylius** [Facepunch/sbox-issues#6134]
### Describe the bug

Scene setup:
![image](https://github.com/user-attachments/assets/04ecd549-3bcf-406d-a5c9-2f5ec6f24c2a)

Citizens are just this, duplicated twice:
![image](https://github.com/user-attachments/assets/a8ac11ce-abe9-4be0-99a4-2a42636523a5)

The Trace object runs this component:
```
		var results = Scene.Trace
			.Sphere( 500f, GameObject.Transform.World.Position, GameObject.Transform.World.Position )
			.UseHitboxes()
			.RunAll()
			.ToList();
```

Which results in
```
12:32:34   GameMenu found 5
 12:32:34   GameMenu - [GameObject:Plane](arg:0)
 12:32:34   GameMenu - [GameObject:Cube](arg:0)
 12:32:34   GameMenu - [GameObject:Cube (1)](arg:0)
 12:32:34   GameMenu - [GameObject:Cube (2)](arg:0)
 12:32:34   GameMenu - [GameObject:Citizen](arg:0)
```

The trace sphere should be large enough to cover all citizens but it will only ever return one of them.
Moving the logged citizen far away (or deleting it) makes another one show up instead.

### To Reproduce

[runall_hitboxes_repro.zip](https://github.com/user-attachments/files/16503339/runall_hitboxes_repro.zip)

### Expected behavior

All matching game objects should be returned

**Comment by aylaylay** [comment]
Hitbox traces now support RunAll
