### ISSUE TITLE
New particle system particles aren't lit

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#6136]
### Describe the bug

Particles in the new particle system aren't lit like legacy particles are.

### To Reproduce

Create a particle and spawn it in a dark area

### Expected behavior

The particles should take ambient lighting like the legacy particle system particles do

### Media/Files

![image](https://github.com/user-attachments/assets/4fa229bb-489f-4db2-bd61-a6540bdefd03)

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/567af45b-d80c-450a-9002-8a767918891a
