### ISSUE TITLE
ADD THIS MAN TO YOUR TEAM

### ISSUE THREAD

**Issue by DarkspiderM8** [Facepunch/sbox-issues#614]
There's this man on the garry's mod workshop who has made these amazing addons that fixed so many issues with the game.
His name is WFL. He has made addons such as the forge tool and make cylindrical. He also made friction and prop engine tools.
He's a legend among legends. Please get this guy a s&box code he deserves it. I'm not going to link anything but you should be able to find him easily if you search his name up on the garrys mod workshop.

**Comment by WYVERN2742** [comment]
Sounds like they've got quite the workshop contribution. If they sign up at https://sbox.facepunch.com/dev/.login/ They'll join the queue and get developer access within a few days.

**Comment by Vurv78** [comment]
Joined 14 days ago just to make this issue? Also this is meant for bugs by people with access to the game. If you literally even glanced at the s&box discord you'd know there's a queue now.
