### ISSUE TITLE
"Reset to Default" on individual GameTransform properties are wrong.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#6142]
### Describe the bug

Clicking "Reset to Default" on the rotation and scale properties sets them to the wrong values.

World/Local rotation default is `(-0,180,180)`.
World scale default is `(0,0,0)`.

### To Reproduce

In local/worldspace, reset rotation.
In worldspace, reset scale.

### Expected behavior

World/Local rotation should be `(0,0,0)`.
World scale default should be `(1,1,1)`.

### Media/Files

https://github.com/user-attachments/assets/2025731d-9a22-4779-9d56-71256f507966

### Additional context

Why is pitch always `-0` instead of `0`?
```[tasklist]
### Tasks
- [ ] World/Local rotation default is `(0,0,0)`
- [ ] World scale default is `(1,1,1)`
```

**Comment by aylaylay** [comment]
Rotation is incorrect but scale is fine for me?

**Comment by aylaylay** [comment]
Rotation should get set to identity now, ignore the -0, it will be some kind of float to string inaccuracy and should be harmless

**Comment by badandbest** [comment]
The scale is still fucked. Are you sure you absolutely were displaying worldspace?

https://github.com/user-attachments/assets/0290c833-f71b-41e7-a2f0-a9968b9dc8bb

It could probably be fixed by adding `[DefaultValue( 1f )]` because that seems to be the only difference between the ( working ) localspace scale

![image](https://github.com/user-attachments/assets/7b560a8c-d0ee-4484-a9e6-b2eccd97c23b)

and the ( not working ) worldspace scale.

![image](https://github.com/user-attachments/assets/a8f59041-03cb-4570-9617-28acd75e13b1)

**Comment by aylaylay** [comment]
Fixed
