### ISSUE TITLE
S&Box does not start

### ISSUE THREAD

**Issue by kumulkumul** [Facepunch/sbox-issues#6143]
### Describe the bug

I say start the game, it appears to be running in the task manager for 5-10 seconds and then closes, it does not respond, it does not create a log file
, There were no problems before and it was working properly,
I was able to get a dump file when it appeared in the task manager for 5-10 seconds and dropped it below.

### To Reproduce

https://drive.google.com/file/d/1igP-ZhCcXwtxgT-UxGHCPqY0q4bgErgD/view?usp=sharing

### Expected behavior

n

![Recording_2024-08-06_at_11 11 13](https://github.com/user-attachments/assets/a2b849a1-8165-4bb0-be0d-5c8e4d4d533e)

### Additional context

windows 11
lenovo loq 15irh8 laptop

**Comment by CaPix-REAL** [comment]
Yo i have the same problem so how did you solve it? 
Did you delete the steam_api64.dll in **system** or **system32**?
