### ISSUE TITLE
Add a way to have props start asleep like we had with entities 

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#6145]
### For?

S&Box

### What can't you do?

Unable to make props start asleep until they are activated/hit like with prop_physics. This is useful if you have something like a painting that you want to start static floating on a wall until it is hit by a player

### How would you like it to work?

Add it as an option in the component 

### What have you tried?

The option does not exist to try

**Comment by Gmod4phun** [comment]
Couldn't this be done with a joint component with extremely small break force? Basically a weld/axis if you want, which holds the thing in place, and breaks when a certain force is applied to the joint.

**Comment by KingOfTheFBI** [comment]
> Couldn't this be done with a joint component with extremely small break force? Basically a weld/axis if you want, which holds the thing in place, and breaks when a certain force is applied to the joint.

That's a lot for something that used to just be a checkbox

**Comment by Gmod4phun** [comment]
I guess so. Rigidbody has StartAsleep on itself, so I guess it would be just a matter of adding a property to the Prop component

**Comment by aylaylay** [comment]
Instead of start alseep we could build something into props to be static until enough force is applied

**Comment by aylaylay** [comment]
Saying that though, if start asleep is common enough, we should add it to prop

**Comment by aylaylay** [comment]
Added Prop.StartAsleep
