### ISSUE TITLE
[Standalone] Standalone.VersionDate and Standalone.Version

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6148]
### For?

S&Box

### What can't you do?

In the API there are two functions that give you the date of the build and unique build id string, however, they are for the build at the FP's side, and not anything in-editor related. For standalone, that's not useful, because you dont care when the engine was updated, when trying to version an exported build.

### How would you like it to work?

In the API there's Application.VersionDate for the build date, and Application.Version for build "id". It would be nice if there were equivalents for standalone, something like **Standalone.VersionDate** and **Standalone.Version** that would change every time you export, so you have something to put in the debug overlay to know what version of the game is this, as opposed to having to ask your playtesters "what build is this" and then finding out the folder wasn't named with export time.

### What have you tried?

Using Application.VersionDate/Version and it's not built for this purpose at all.

**Comment by xezno** [comment]
Added
