### ISSUE TITLE
Add `OnDuplicate(GameObject prevObj)` virtual method to Component.

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#6151]
### For?

S&Box

### What can't you do?

Conveniently know when you SHIFT+drag a widget or click Duplicate and what the object is was duplicated from was while in the editor.

### How would you like it to work?

```csharp
// In GoalComponent.cs file:
protected override void OnDuplicate(GameObject prevObj)
{
   if (prevObj.Components.TryGet<GoalComponent>(out var goal))
      goal.NextGoal = this;
}
```

### What have you tried?

I could get the last ordered/created gameobject in the child/root but there are flaws to this.

### Additional context

I have implemented a feature like this for my own ingame editor for easily connecting chained objects together. Carson liked it, so hopefully he'll pick this issue up soon?

**Comment by handsomematt** [comment]
We're not going to add editor-only methods to components

**Comment by MrBrax** [comment]
what about drawgizmos?

i tried cloning a gameobject on a [Button] but it just threw errors, didn't seem possible for a duplication
