### ISSUE TITLE
Inspector: Component property rendering stuck until restart after changing an attached component

### ISSUE THREAD

**Issue by Smilindeth** [Facepunch/sbox-issues#6152]
### Describe the bug

Inspector becomes unrecoverable until restart when an attached component changes to an invalid type.

### To Reproduce

1. Create empty
2. Add new Razor panel component
3. Edit type from:
  @inherits PanelComponent
  To:
  @inherits Panel
5. Save
6. Return to editor UI, inspector panel for the empty created in step 1 is now unviewable
7. Revert the code, return to UI, and inspector does not recover.

### Expected behavior

Inspector should at least try to refresh the component view when focus is shiften to another then back at least in the case of failed render.

### Media/Files

Working inspector before changing the inherits:
![image](https://github.com/user-attachments/assets/e1883999-bc11-40c8-834b-d646d2105ed5)

After:
![image](https://github.com/user-attachments/assets/68ce9688-4506-4ae7-9ad3-4283438e5959)

### Additional context

```
10:23:52   hotload/GameMenu Object of type 'LevelTime' cannot be converted to type 'Sandbox.Component'.
 10:30:45   CompileGroup/local  [1] Building 2 compilers
 10:30:45   hotload/GameMenu Object of type 'LevelTime' cannot be converted to type 'Sandbox.Component'.
 10:30:45   hotload/GameMenu The value "LevelTime" is not of type "Sandbox.Component" and cannot be used in this generic collection. (Parameter 'value')
 10:30:45   hotload/GameMenu The value "LevelTime" is not of type "Sandbox.Component" and cannot be used in this generic collection. (Parameter 'key')
 10:30:45   hotload/GameMenu Object of type 'LevelTime' cannot be converted to type 'Sandbox.Component'.
 10:30:45   hotload/GameMenu The value "LevelTime" is not of type "Sandbox.Component" and cannot be used in this generic collection. (Parameter 'value')
 10:30:45   hotload/GameMenu Object of type 'LevelTime' cannot be converted to type 'Sandbox.Component'.
 10:30:45   hotload/GameMenu  [6] Object of type 'LevelTime' cannot be converted to type 'Sandbox.Component'.
 10:30:45   ToolsDll Error calling event 'tool.frame' on '[Editor.Inspectors.GameObjectInspector](arg:0)' (Can't serialize object type 'LevelTime')
 10:30:48   GameMenu  [1] TypeLibrary could not find [LevelTime](arg:0)
 10:30:48   GameMenu Couldn't create [Editor.Inspectors.GameObjectInspector](arg:0) (Exception has been thrown by the target of an invocation.)
```

**Comment by CarsonKompon** [comment]
I'll need to take another look at this since it seemed to be deleting everyone's components
