### ISSUE TITLE
World Mapping Missing from Complex Shader

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#6157]
### Describe the bug

We can no longer set the world mapping settings on any material that uses the complex shader.

This was really useful for aligning textures to the grid in hammer with the desired texel density.

### To Reproduce

1. Open a material that's using the complex shader
2. Go to the Attributes tab
3. See that the "System Material Attributes" section is missing

### Expected behavior

The System Material Attributes section should be back in the Attributes tab.

### Media/Files

![image](https://github.com/user-attachments/assets/51c0ec22-64f3-48fe-bc14-c738a9f494c6)

**Comment by handsomematt** [comment]
Try now

**Comment by Jammie3d** [comment]
Yep, all good now, thanks!
