### ISSUE TITLE
the menu is bugged

### ISSUE THREAD

**Issue by Turromemexd** [Facepunch/sbox-issues#6158]
### Describe the bug

![imagen_2024-08-07_214835097](https://github.com/user-attachments/assets/080578a4-0193-41d0-894b-f9f46dff28fe)

### To Reproduce

Its on the menu, its bugged and i can change the settings

### Expected behavior

fix it to change my avatar and settings

### Media/Files

https://github.com/user-attachments/assets/789230c1-a36d-4635-a852-31ac6e999ac3

### Additional context

Im on windows 10 and my specs are
Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
16,0 GB
Intel(R) UHD Graphics 620

**Comment by Gamblingpizza** [comment]
menu is bugged for me too like this, the styling got messed up or something.
