### ISSUE TITLE
Possible Issues with SSL connection

### ISSUE THREAD

**Issue by legoj15** [Facepunch/sbox-issues#616]
**Describe the bug**
Upon starting the game and reaching the home menu, "An error occurred while sending the request" pops up. Navigating around the menu causes this error to continuously pop up. Clicking on the `games` tab yields "The SSL connection could not be established", and no icons will load. Additionally, no online maps or game modes can be played, starting one just causes the game to go back to the Start Game page.

**To Reproduce**

1. Start the game
2. Go to games tab
3. No icons will load and no games will start (other than local maps loaded via the console)

**Expected behavior**
No errors upon startup and game mode/map icons load

**Screenshots**
![20210806172119_1](https://user-images.githubusercontent.com/7399802/128574208-2d1e686b-8315-4f8d-8f4a-0ff0d6940ef4.jpg)
![20210806172207_1](https://user-images.githubusercontent.com/7399802/128574216-cb42df63-a70e-482e-941a-1655c2bfaab3.jpg)

**Additional context**

I originally thought it could be my SSL/TLS settings in Window's Advanced Internet options, but even after resetting these options and rebooting, the issue persists.

**Comment by deadmonstor** [comment]
This is most definitely your pc/internet issue, have you tried restarting them both?

**Comment by legoj15** [comment]
Yes, I've already restarted bough, though I didn't think to test another computer. Let me download s&box on another computer and see if it happens there.

**Comment by legoj15** [comment]
Hmm, can't reproduce the issue on another computer, I'll dig deeper on my main computer and report back if I find a fix, so if anyone else comes across this they will know what to do.

**Comment by legoj15** [comment]
Yep, I had some unnecessary registry entries (specifically the ones in HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols) causing all my grief. Removing them allows the game to operate as per usual.
