### ISSUE TITLE
Mouse settings carrying over from one game to another. 

### ISSUE THREAD

**Issue by SpiltBeanz** [Facepunch/sbox-issues#6160]
### Describe the bug

We use this code to enable the mouse but keep it invisible so we can use our custom crosshair as the cursor in our game Stack&box:

`protected override void OnStart()
	{
		Mouse.Visible = true;
		Mouse.CursorType = "none";
	}
`

But this seems to cause the mouse to be enabled after quiting and joining another game. For FPS games this means no control of the camera, just a mouse moving around the screen.

### To Reproduce

1. Launch Stack&box AND click "Start Game"
2. Leave Stack&box and then launch any other game (God Ray Sim, SWB etc..) 
3. Mouse is visible when it should not be. 

### Expected behavior

Mouse settings from one game should not affect another game. 

### Media/Files

https://github.com/user-attachments/assets/c4771adc-ef74-471a-a1e5-9974ecfc4bb8

**Comment by CarsonKompon** [comment]
This was fixed shortly after the Game Jam
