### ISSUE TITLE
State machine contents can be modified while Animgraph preview is active (can cause crashes)

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#617]
**Describe the bug**
The contents of a State Machine node can be modified while the Animgraph preview is still running. Making enough modifications will crash the engine immediately.

**To Reproduce**

1. Open `citizen.vanmgrph` from the Asset Browser
2. Click "Toggle Preview Mode" to start the preview
3. Open the contents of the "Tag Movement SM", or any other state machine node that is currently being used by the graph
4. Start deleting animation states

**Expected behavior**
Just like the animgraph nodes themselves, the contents of a state machine should be read-only while the preview is active.

**Comment by aylaylay** [comment]
I have pushed a fix for this, please close the issue if it works for you
