### ISSUE TITLE
Allow rendering a CameraComponent to a Texture without rendering it twice

### ISSUE THREAD

**Issue by Dudejoe870** [Facepunch/sbox-issues#6170]
### For?

S&Box

### What can't you do?

Currently, when you try to render a Camera to a texture, it will first render that Camera normally as if it's going to be rendered to the main swapchain, then it gets rendered **again** when rendered to a texture when you call the `RenderToTexture` method from code. I checked this behavior myself in RenderDoc.

### How would you like it to work?

I suggest either a flag on the CameraComponent that allows *not* adding it to the main RenderList; maybe `RenderToTextureOnly` (default false) or `RenderToSwapchain` (default true) or even `RenderToScreen` (also default true), or perhaps just the ability to have negative priority values do the same thing; disable from rendering to the main swapchain.

### What have you tried?

I tried disabling the CameraComponent itself, but that causes lots of problems, and a lot of outside code relies on that Component being active (like scripts that try to control the main camera etc.) Unless I'm missing something, I can't see a way to accomplish this very simple performance optimization. Wanting a Camera to **only** render to a texture is a very common use-case, and rendering an entire scene twice, is really... really bad for performance. Especially when it's a very easy fix. You can of course, use SceneCamera I think, but that is way more low-level than you really need to go when a CameraComponent will work just fine ***except*** for this one problem.

**Comment by handsomematt** [comment]
Yeah we should really have a Texture / RenderTarget property on the Camera Component

**Comment by aylaylay** [comment]
Added
