### ISSUE TITLE
ExecuteInEditor not working for OnFixedUpdate

### ISSUE THREAD

**Issue by the-remeko** [Facepunch/sbox-issues#6177]
### Describe the bug

When I add Component.ExecuteInEditor to MyComponent.cs in a new project, OnFixedUpdate is not run in the editor.

### To Reproduce

[executeineditor.zip](https://github.com/user-attachments/files/16568497/executeineditor.zip)

### Expected behavior

According to https://docs.facepunch.com/s/sbox-dev/doc/component-markers-xtiSAW7DiL, OnFixedUpdate should be run with ExecuteInEditor.

**Comment by aylaylay** [comment]
It does now!
