### ISSUE TITLE
ExecuteInEditor doesn't run OnAwake and OnEnabled when opening the project

### ISSUE THREAD

**Issue by the-remeko** [Facepunch/sbox-issues#6178]
### Describe the bug

OnAwake and OnEnabled are not run when opening a project and the starting scene has an ExecuteInEditor component.

### To Reproduce

My repro project logs "OnAwake" in OnAwake and "OnEnabled" in OnEnabled for MyComponent, which has ExecuteInEditor.
1. Launch the repro project, the default scene should have MyComponent in it
2. OnAwake and OnEnabled are not logged
3. Close the scene
4. Open the scene again using the Asset Browser
5. OnAwake and OnEnabled are logged

[executeineditor.zip](https://github.com/user-attachments/files/16568501/executeineditor.zip)

### Expected behavior

According to https://docs.facepunch.com/s/sbox-dev/doc/component-markers-xtiSAW7DiL, OnAwake and OnEnabled should be logged when using ExecuteInEditor.

**Comment by aylaylay** [comment]
They are called, it's just that you're not seeing the log at the time they get called.
