### ISSUE TITLE
`MorphCollection.Set` restricted in [0,1] range

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6187]
### Describe the bug

Hi,

I'm trying to set my morph to a value below 0 or above 1, but it doesn't apply in the game.
Lets jump to the reproduction steps

### To Reproduce

1) Use a model with Morphs
2) Set its morph to a value greater than 1f:
`SkinnedModelRenderer.SceneModel.Morphs.Set( "my_morph", 100f );`

or to a negative value :
`SkinnedModelRenderer.SceneModel.Morphs.Set( "my_morph", -1f );`

3) Print the returned value :
`Log.Info( "my_morph " + SkinnedModelRenderer.SceneModel.Morphs.Get( "my_morph" ) );`
This will print "100" for the positive value and "0" for the negative value.

Additionally, even though the 100 weight is printed, the Morph behaves the same as if the value were set to 1f.

### Expected behavior

`Set()` in https://sbox.game/api/Sandbox.MorphCollection/Set should not be restricted to the [0;1] range 

### Media/Files

Positive value:
![image](https://github.com/user-attachments/assets/690945a5-b24e-4f69-a78c-da3407c864f1)
![image](https://github.com/user-attachments/assets/42308f9b-5410-4877-bf6c-0ea9611902cf)

Negative value:
![image](https://github.com/user-attachments/assets/20101ac8-fafb-408f-a5c1-c88a9ad89f05)
![image](https://github.com/user-attachments/assets/20208e8f-2664-4a71-ac5b-d4d2589a5a9d)

**Comment by aylaylay** [comment]
Flex overrides were clamping to flex controller min/max, I've removed that limitation. Let me know if it works for you.

**Comment by PolSpock** [comment]
> Flex overrides were clamping to flex controller min/max, I've removed that limitation. Let me know if it works for you.

It looks like it only works for positive values, but negative values are still stuck at 0

Here's my code if you want it yourself: `https://github.com/Facepunch/sbox-scenestaging` > `NetworkTest.cs`
```
	protected override void OnStart()
	{
		base.OnStart();

		var pc = Components.Get<PlayerController>();
		var skinnedModelRenderer = pc.Body.Components.Get<SkinnedModelRenderer>();

		Log.Info( skinnedModelRenderer.SceneModel.Morphs.Count );
		for ( int i = 0; i < skinnedModelRenderer.SceneModel.Morphs.Count; i++ )
		{
			//skinnedModelRenderer.SceneModel.Morphs.Set( i, 10f ); // Works
			skinnedModelRenderer.SceneModel.Morphs.Set( i, -10f ); // Not works
		}
	}

	protected override void OnFixedUpdate()
	{
		base.OnFixedUpdate();

		var pc = Components.Get<PlayerController>();
		var skinnedModelRenderer = pc.Body.Components.Get<SkinnedModelRenderer>();

		for ( int i = 0; i < skinnedModelRenderer.SceneModel.Morphs.Count; i++ )
		{
			Log.Info( skinnedModelRenderer.SceneModel.Morphs.GetName(i).ToString() + " " + skinnedModelRenderer.SceneModel.Morphs.Get( i ) );
		}
	}
```

negative value :
![image](https://github.com/user-attachments/assets/c3c7c92c-4b11-48f7-b76d-1997f0590e29)

positive value:
![image](https://github.com/user-attachments/assets/b16899ff-4d73-4bc4-b989-6cbbaa927c8f)

**Comment by aylaylay** [comment]
I missed a clamp, should work now

**Comment by PolSpock** [comment]
Mhhhhh thx 💌

![image](https://github.com/user-attachments/assets/277af128-c520-48db-8693-af577d538e0e)
