### ISSUE TITLE
Allow Style Editor to change active and inactive states of tools windows that are behind it

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#619]
**What can't you do?**
When changing colors of elements in the Style Editor, I can't see what the active colors in tool windows look like unless I click onto the tool window. This is particularly annoying when the window I want to preview my changes on is maximized, since elements often aren't easily visible when the window isn't maximized, and as a result I have to go to my taskbar to swap back to the Style Editor and choose a different color, each time I want to see what a different color looks like.

**How would you like it to work?**
A checkbox next to the "Same Color" checkbox at the top (Which, to be honest, I'm not sure what that does) that says something like "Force background windows to be active", which, when clicked, forces all inactive windows to use the active color scheme. To prevent this from accidentally being left on, it would probably be ideal to have this checkbox untick itself when the Style Editor loses focus.

**What have you tried?**
N/A

**Comment by garrynewman** [comment]
Are you talking about the style editor to change the style of the tools?

**Comment by walllable** [comment]
Yep

**Comment by garrynewman** [comment]
We're not really interested in making this any better, sorry

**Comment by walllable** [comment]
No worries, figured I might as well write those up as a 'better safe than sorry' sorta thing
