### ISSUE TITLE
Disabling the Console on a per game basis

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6190]
### For?

S&Box

### What can't you do?

Every game has a console, it's iconically Source Engine. 
However, I'd rather not have my player be able to access it, if a player absolutely needs to go into the console for something I have failed as a developer. 

### How would you like it to work?

In Project Settings, add a "disable console" button.
Ideally this would disable it for everyone except those within the game's organization. 

### What have you tried?

Nothing

**Comment by handsomematt** [comment]
Nah

**Comment by Retroeer** [comment]
...Any particular reason?

**Comment by garrynewman** [comment]
There is no justification for letting games define whether the console should be accessible or not.

**Comment by Retroeer** [comment]
The console takes up 2 keys (tilde and f2) for no reason, it's a sloppy dev tool that's great for devs but players shouldn't even have to learn that it exists, at the minimum have it be enabled by default but give developers the option of a bool to implement their own "enable console?" toggle in their games
Valve hid this thing by default, and I would very much like the ability to do the same

**Comment by handsomematt** [comment]
You want to use those keys for your game? That's even worse

**Comment by Retroeer** [comment]
No? If the player wanted to use those keys for some reason they would be able to, but that's not really the point, there's no way to disable the console at all right now, even across the entire game itself, which is fine for a dev preview, but I hope this would get revisited when it releases and the majority of the playerbase aren't developers

**Comment by MrBrax** [comment]
are you afraid of people using dev console commands to ruin their experience? as long as you have a cheat cvar i think it would be fine

**Comment by kEllieGit** [comment]
I agree with Retro on this.

It's called a "developer console" for a reason. As the developer, would you wish for the end user to go input random console commands they have no clue as to what they even do? It feels like a relic of the past, and while I do think it is very useful for stuff like modding, error logging, etc etc, if you don't offer better alternative ways as the developer, it does sort of feel like you are failing in providing the best experience you can.

Right now it doesn't matter too much, but as we progress on the path to standalone, do you see games made in Unity or Unreal Engine providing such a feature by default? I do think this should be at least thought about further than just a simple "no".

**Comment by andy013** [comment]
What exactly is the problem with having the developer console available to players? What problem would disabling the console solve? It's optional. No one is forced to use it. 

Every source engine game I've played has had the developer console available to players and it's invaluable for quickly changing settings and managing dedicated servers. I used to use it to change key bindings, change map, spawn bots, position bots in position to practice against etc. Without it, developers would need to design a menu for all of this which is just a waste of time and would take longer to use than simple console commands. Why do you want to remove all of this potential functionality? There is no benefit that I can see.

**Comment by kEllieGit** [comment]
> What exactly is the problem with having the developer console available to players? What problem would disabling the console solve? It's optional. No one is forced to use it.
> 
> Every source engine game I've played has had the developer console available to players and it's invaluable for quickly changing settings and managing dedicated servers. I used to use it to change key bindings, change map, spawn bots, position bots in position to practice against etc. Without it, developers would need to design a menu for all of this which is just a waste of time and would take longer to use than simple console commands. Why do you want to remove all of this potential functionality? There is no benefit that I can see.

Because we can do better. We should do better. It's 2024, not 2004. This was useful in the olden days, where stuff like this was way harder to do than it is now. We have stuff like steam networking, better graphical settings, more solutions. It's not about completely removing the ability, it's just about adding a toggle for it. Are you making a simple 2D singleplayer game? Why would the end player ever need to use the console there?

It's a developer feature, for developers. Always strive to do better, don't bug out your game, add good solutions that your end users will enjoy. Optimize your experience so they should **NEVER** have to access random shit they'll have no clue what they're even changing.

**Comment by yuberee** [comment]
This makes sense for standalone games, but not much for platform games.
I can think of many commands that should always be available to all players inside of S&box, regardless if you're a developer or a player.
kick, ban, stats_display, restart, quit, fps_max, even the command to disable the version banner on the top right.
