### ISSUE TITLE
[Platform] Per player data store.

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#6191]
### For?

S&Box, Other

### What can't you do?

I'd like to store data per game, per player, on sbox.game.

I want a way to store data I can personally audit as a game's developer.

If as a developer I want to know how many people complete the first boss for example, I don't think there's a way for me to tell right now, outside of maybe forcing an unconventional exception to trigger after that boss is defeated.

**EDIT**: Someone on the discord has mentioned that stats allow you to do the first boss example pretty easily, I wasn't fully aware of this feature on the website or how it worked, it actually is mainly what I was looking for. 
A good few people seem to want cloud saves though and I don't really see that as a bad feature either, so I'll keep this up.

### How would you like it to work?

I imagine some API you can access in a similar way to the leaderboard?
But also perhaps a way to view data stores from sbox.game.

### What have you tried?

I think you can technically put any data type you want in the leaderboard?
It's not really designed around this purpose though.

### Additional context

Obviously this has the possibility of exploding in terms of data storage, but even a small limit of data stored, in the KB range, can still be useful to developers. If save data is bit packed instead of turned to json, even a few KB would be very accomodating.

**Comment by trende2001** [comment]
Like roblox's data stores that store stuff on the serverside rather than the data folder of the player?

**Comment by agincel** [comment]
Even being able to store 1kb of data per player backend side would be huge.

Though, if the Stats API SetValue worked properly, we might be able to work around not having something like this
