### ISSUE TITLE
[Scene Mesh] Ability to center the origin of a SceneMesh mesh

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#6193]
### For?

S&Box

### What can't you do?

Once you create a mesh via the block tool and then edit the mesh , you will find  that you cannot to center the origin to the center of mass. This is something that hammer could do.

### How would you like it to work?

A way to center the origin of the mesh on the mesh component.

### What have you tried?

Just dealing with it.

**Comment by aylaylay** [comment]
Added
