### ISSUE TITLE
Game will not boot in VR mode when running in proton 

### ISSUE THREAD

**Issue by jurassicjordan** [Facepunch/sbox-issues#6196]
### Describe the bug

I am attempting to try and run the game on linux in VR mode, I am using ALVR with an Oculus quest headset, when attempting to start the game I get an error that says "Required Vulkan extension "VK_WINE_openxr_device_extensions" is not supported. Please update your Vulkan driver." Being that this is linux I doubt theres any driver I can actually "update" I think the game isn't detecting the provided openXR runtime or something like that.

### To Reproduce

1. run steamVR
2. install s&box
3. enable proton compatiblity (proton experimental)
4. start game and select VR mode
5. Receive error
6. be very sad :(

### Expected behavior

In a similar way that running ALYX or any other windows VR game in VR I expect the game to at least boot, connect to steamVR and display on the headset. It might crash after that, but thats more expected than not booting at all.

### Media/Files

![Screenshot_20240810_231221](https://github.com/user-attachments/assets/5d5d301b-b27c-4242-bc98-4624630e421f)

### Additional context

Running on Linux EndeavourOS, kernel 6.9.8-zen1-1-zen, Plasma 6.1.2, NVIDIA GeForce RTX 3060, 32gb ram, Intel i7-10700K, blablabla computer stuff
game version: s&butt 8/11/2024/ efc769a

**Comment by handsomematt** [comment]
https://github.com/ValveSoftware/Proton/issues/7737

proton issue
