### ISSUE TITLE
Hitboxes are acting as if they are double the size when using hitboxes from model

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6198]
### Describe the bug

The hitboxes appear to be double the size, I tested this by using my knife weapon (which has a 0 radius ray) around my enemies head. In the video I display the hitbox and the knife test. I also tried halfling all the values of the head hitbox and it felt correct.

The model does not use any scale or mirror protocols and it's import scale is 1.

### To Reproduce

1. Create model with skeleton
2. add hitboxes to model
3. use hitboxes from model and ray to detect hits

### Expected behavior

Not being double the size

### Media/Files

https://github.com/user-attachments/assets/873563fd-9ffd-4b7e-b12e-9194c3372181

**Comment by aylaylay** [comment]
does the gameobject have any scale? let's rule that out first

**Comment by SwagAccount** [comment]
no

**Comment by aylaylay** [comment]
Fixed
