### ISSUE TITLE
NullReferenceException when using Sound.Play with SoundEvent that has no sounds

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6205]
### Describe the bug

When Sound.Play is called with a SoundEvent as an argument and sounds list of the SoundEvent is null, a NullReferenceException is thrown. 

The following unit test throws a NullReferenceException:
```cs
namespace Sandbox;

[TestClass]
public class SoundTests
{
	[TestMethod]
	public void PlaySoundEvent_WithNoSounds_ReturnsNull()
	{
		var soundEvent = new SoundEvent();

		var result = Sound.Play( soundEvent );

		Assert.IsNull( result );
	}
}
```
Stack trace:
```
ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
SoundEvent.GetNextSound() line 125
Sound.Play(SoundEvent soundEvent) line 28
SoundTests.PlaySoundEvent_WithNoSounds_ReturnsNull() line 11
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### To Reproduce

1. Open the attached project
2. Run the unit test: `PlaySoundEvent_WithNoSounds_ReturnsNull`
3. See that the test fails

### Expected behavior

The test should pass, indicating that a null was returned by `Sound.Play`.

### Media/Files

[getnextsound_nre.zip](https://github.com/user-attachments/files/16576361/getnextsound_nre.zip)

**Comment by aylaylay** [comment]
Fixed
