### ISSUE TITLE
Add RGBA16161616F option to Texture Editor

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6208]
### For?

S&Box

### What can't you do?

There are many texture compression options in the drop down menu, having a compressed 8 bit format, and uncompressed 8 bit format. For HDR, there's a compressed format, but no uncompressed (RGBA16161616F) format, rendering (lol) any lookup table with HDR values meaningless.
![image](https://github.com/user-attachments/assets/32ad8536-f318-4c4b-bcf7-ad83b709d22e)

### How would you like it to work?

Add the format into the dropdown menu, plain and simple

### What have you tried?

Typing it into the uncompiled vtex manually, but I don't think that does anything; Even if this actually doesn't solve my current obstacle, it would still be nice to have this as it is weird to not have 16F option for textures.

**Comment by aylaylay** [comment]
Added some more common formats, for what it's worth, editing the file with RGBA16161616F should have worked.
