### ISSUE TITLE
Hotkeys in Hammer don't work with a different keyboard language

### ISSUE THREAD

**Issue by GlebXleb1** [Facepunch/sbox-issues#621]
**Describe the bug**
Hotkeys in Hammer don't work with a different keyboard language

**To Reproduce**
1. Open Hammer
2. Switch to any keyboard language that's not English 
3. Try using any Hammer keybind

**Expected behavior**
Keybinds should be working with any keyboard language

**Screenshots**

**Additional context**
The same problem goes with Dota and HL:A

**Comment by robotboy655** [comment]
https://github.com/Facepunch/sbox-issues/issues/700

Should be fixed.
