### ISSUE TITLE
The ceramic Surface Type is missing sounds

### ISSUE THREAD

**Issue by jkinz3** [Facepunch/sbox-issues#6213]
### Describe the bug

When an object with the ceramic surface type has an impact event, there is an error about missing impact sounds
```
 11:02:47   Generic Couldn't find sound event sounds/physics/props/pottery_flowerpot/impact_soft_pottery.sound
 11:02:51   Generic Couldn't find sound event sounds/physics/props/pottery_flowerpot/impact_hard_pottery.sound
```

### To Reproduce

1. Open up minimal scene or any scene with a floor.
2. Create a sphere and raise it above the ground.
3. Add a rigid body and a sphere collider. 
4. Set the collider's surface type to ceramic
5. Play the game

### Expected behavior

The sphere should fall and when it hits the floor, no errors should appear and the impact sounds for ceramic should play.

**Comment by aylaylay** [comment]
Fixed
