### ISSUE TITLE
Make the Button attribute pull the method name as the button's title if not specified

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6214]
### For?

S&Box

### What can't you do?

I can't just add a parameterless Button attribute and it pulls the method's name as the button's title
```cs 
[Button]
public void Test()
{
	Log.Info("Button Test was pressed!");
}
```

### How would you like it to work?

I'd like to be able to just add the Button attribute and it pull the button title from the method name, but still be able to specific the title if wanted.

So in this example, it would be the same as `[Button("Test")]`
```cs
[Button]
public void Test()
{
	Log.Info("Button Test was pressed!");
}
```

### What have you tried?

Write out the function name manually, which obviously works but is just a small bit of boilerplate that isn't needed and need's maintaining.
```cs
[Button("Test")]
public void Test()
{
	Log.Info("Button Test was pressed!");
}
```

### Additional context

Being able to specify a title is super useful, but in my experience 95% of editor buttons can be left as the method name.

I think this is what the code would have to be changed to.
```cs
[AttributeUsage(AttributeTargets.Method)]
public class ButtonAttribute : Attribute
{
	public string Icon { get; set; }

	public string Title { get; set; }

	public ButtonAttribute([CallerMemberName] string title = "", string icon = "")
	{
		Title = title;
		Icon = icon;
	}
}
```

**Comment by MD485** [comment]
Add a tack-on requirement to this it would be nice that, if using a default `[Button]`, buttons were full width.
Since they'll just have the same name as their label anyway.
I've got something going with a default button and it being full width as an option in my own projects, it's convenient.
