### ISSUE TITLE
`Component.INetworkListener` is not triggering anymore

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6215]
### Describe the bug

Today (13/08/2024 ~19:10 CEST), I updated my S&box to build ID `15356374`, and it seems that `Component.INetworkListener` is no longer being triggered.

This is causing several issues with pawn creation in my game & other games.

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging/ or https://github.com/Facepunch/sbox-hc1.
2) Start a networked game (either `networking.scene` or a game in `nicked` with S&box editor).
3) You'll notice that `Component.INetworkListener` does not trigger, so no pawns are created.

I’m not sure if this is only related to the S&box editor, cause games published in sbox.game are still working.

### Expected behavior

`Component.INetworkListener` should function correctly.

### Media/Files

`networking.scene` example:

https://github.com/user-attachments/assets/9bd1b08e-283d-43ba-a29a-f77775ec5ef2

`nicked` example:

https://github.com/user-attachments/assets/5b0f9d26-fdea-48fd-b7d5-0b5c6d9e33e1

### Additional context

build id : 15356374

**Comment by trende2001** [comment]
The method where it creates the lobby shouldn't be in OnStart anymore, but OnLoad instead

**Comment by PolSpock** [comment]
you're right! that's a sneaky breaking change!

**Comment by PolSpock** [comment]
Okay, but it looks like `OnLoad()` is only called when the component already exists in the scene. My current approach is to have only one ScreenPanel component in my scene and use a GameObjectSystem (https://docs.facepunch.com/s/sbox-dev/doc/gameobject-systems-6vakGETtA4) to create my lobby.

Now, since this change, how can I create a lobby?

If I create a lobby like this:
```
	internal partial class GameTest : GameObjectSystem
	{
		public static GameTest Instance { get; internal set; }
		public GameTest ( Scene scene ) : base( scene )
		{
			Log.Info( "GameTest constructor " + scene );

			Instance = this;

			Listen( Stage.SceneLoaded, 10, StartNetworkManager, "StartNetworkManager" );
		}
		
		public void StartNetworkManager()
		{
			var gameObject = new GameObject();
			gameObject.Components.Create<NetworkManager>();
			gameObject.Parent = this.Scene;
		}
	}
```

Where `NetworkManager.cs` is defined as:
```
	public class NetworkManager : Component, Component.INetworkListener
	{
		protected override async Task OnLoad()
		{
			if ( !GameNetworkSystem.IsActive )
			{
				await Task.DelayRealtimeSeconds( 0.1f );
				GameNetworkSystem.CreateLobby();
			}
		}

		public void OnActive( Connection channel )
		{
			Log.Info( $"Player '{channel.DisplayName}' is becoming active (" + channel.Id + ")" );

		}
	}
```

`NetworkManager.OnLoad()`  is not being called, so no lobby is created, and no `Component.INetworkListener` functions are triggered!
Let me keep creating the lobby without adding an ugly component/prefab to my scene!

**Comment by kurozael** [comment]
This may be related to @xezno's change to resolve networked scene loading?

**Comment by xezno** [comment]
I don't see why that would've broken but maybe we're not waiting long enough between making a lobby and firing OnJoined

**Comment by xezno** [comment]
Should be sorted on next build
