### ISSUE TITLE
Particle Effect should remember last tab instead of always switching to General

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#6216]
![sbox-dev_2024-08-13_13-40-04](https://github.com/user-attachments/assets/a6492547-ceb2-4714-a8c1-b5515a3ca93e)

When adjusting particle effect values on one of the category tabs, the selected tab will switch to General whenever the inspector changes focus to something else.

This makes it pretty annoying to make changes, as every time you test them, you have to remember which of the tab symbols represents the settings you were adjusting and click it again.

**Comment by aylaylay** [comment]
The tab should now be remembered
