### ISSUE TITLE
Arrow Keys are no longer functionable inputs 

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6218]
### Describe the bug

Arrow Keys no longer function if used as an input action 

### To Reproduce

1. Bind an Input Action to the Arrow Keys
2. Setup a log event to happen if you press one of them
3. Observe the distinct lack of functionality 
```
if (Input.Pressed("LeftArrowKey")) Log.Info("I sure wish i had functionality!");
```

### Expected behavior

Arrow Keys should function just as any other key on the keyboard

**Comment by B0zy** [comment]
To add to the issue it seems like the arrow keys are registered as ( Up, Down, Right, Left ) as apposed to ( RightArrow, leftArrow etc ). https://discord.com/channels/833983068468936704/837215495496663040/1273053783164719216

**Comment by CarsonKompon** [comment]
Should be good now 👍
