### ISSUE TITLE
Whitelist Object.MemberwiseClone

### ISSUE THREAD

**Issue by dotryen** [Facepunch/sbox-issues#6219]
### What it is?

The MemberwiseClone function from Object in System.
Whitelist Error: System.Private.CoreLib/System.Object.MemberwiseClone()

### Why do you need to use this?

While I don't need it, it makes my life easier by making me not have to constantly update my cloning methods as I iterate on a world state system.
All it does is make a shallow copy of an object.

**Comment by handsomematt** [comment]
No can do, we had security issues previously with this method

**Comment by dotryen** [comment]
Ah ok, I knew there must've been a security issue. Thanks for letting me know!

**Comment by garrynewman** [comment]
We could probably offer a comparable, but generally you'd be using a struct for this, making cloning kind of easy
