### ISSUE TITLE
Graphics.Render doesnt render with the RenderAttributes of the supplied SceneObject 

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#6220]
### Describe the bug

When you render a sceneibject with Graphics.Render, it wont use the renderattributes its supposed to.

### To Reproduce

Draw a Scene object with Graphics.Draw, youll immediantly know if its working or not if its unlit by ambient / direct light.

### Expected behavior

It should be use the render attributes correctly

**Comment by samzanemesis** [comment]
Does it work on game viewport but not on editor viewport?

**Comment by Xenthio** [comment]
> Does it work on game viewport but not on editor viewport?

Not in the game viewport, haven't looked in editor viewport

**Comment by aylaylay** [comment]
@Xenthio This seems to be working fine, they're lit for me, where are you calling render?

**Comment by Xenthio** [comment]
I was calling it in a camera render hook

**Comment by aylaylay** [comment]
That might explain why it was working for me, I was trying it in a custom scene object

**Comment by Xenthio** [comment]
I vaguely recall trying it in one of those too with the same results, can
you check if it's still lit when the light is from a loaded map instance?

**Comment by aylaylay** [comment]
Graphics.SetupLighting puts the attributes into Graphics.Attributes, not the scene object attributes. Graphics.Render now renders scene object using provided attributes or Graphics.Attributes by default.
