### ISSUE TITLE
Let the user hide the mouse cursor on all camera movements, not just rotation

### ISSUE THREAD

**Issue by jkinz3** [Facepunch/sbox-issues#6224]
### For?

S&Box

### What can't you do?

I realize this is partially personal preference but it's annoying when i'm trying to orbit around something, and the mouse cursor keeps flying around the screen. Since we already have an option to hide the cursor on rotate, could there be an option to hide it on all camera movements? So orbiting, panning, and zooming as well?

### How would you like it to work?

Probably the simplest solution is to change the "Hide Cursor on Rotate" so that it disables the cursor on all movement. I don't really see why someone would want to have some movements show the cursor while others hide it.

### What have you tried?

There really isn't an alternative.

### Additional context

I understand the change was originally meant to replicate some functionality in programs like Maya or Blender, but this is a game engine and a lot of people (like me) are coming from Unreal, where it hides the mouse cursor on all movements. This is nice for when i'm moving around props or environments to see how the light plays off the surface since I don't have a flinging flanging cursor flying around like a mosquito.

**Comment by aylaylay** [comment]
I hate this wrapping cursor too. I've added two more preferences to hide it when panning or orbiting. I'd have just had a single preference for it but I can appreciate that some people will have different preferences to this
