### ISSUE TITLE
Menu Doesn't Load.

### ISSUE THREAD

**Issue by DJNEFFYFRESH** [Facepunch/sbox-issues#6227]
### Describe the bug

I launch sbox and i can see the face punch background but this error shows up after and force closes the game, all i know is its not an account error because i couldnt load sbox on my friends steam account either. 

### To Reproduce

Idk what to put here cause I have no clue so I'm going to put the error here.

2024/08/14 15:27:35.2481	[Generic] Error | 'Sound' does not contain a definition for 'HasValue' and no accessible extension method 'HasValue' accepting a first argument of type 'Sound' could be found (are you missing a using directive or an assembly reference?) - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:958,26	
2024/08/14 15:27:35.2481	[Generic] Error | 'Sound' does not contain a definition for 'Value' and no accessible extension method 'Value' accepting a first argument of type 'Sound' could be found (are you missing a using directive or an assembly reference?) - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:962,22	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'PlaySound' does not exist in the current context - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:970,3	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'Camera' does not exist in the current context - _gen_MotionBlurPanel.razor_48d170db.cs:87,22	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'Camera' does not exist in the current context - _gen_ColorPanel.razor_910c98d9.cs:280,22	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'Camera' does not exist in the current context - _gen_FilmGrainPanel.razor_a4e34c81.cs:118,22	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'LocalVelocity' does not exist in the current context - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:1080,3	
2024/08/14 15:27:35.2481	[Generic] Error | 'Sound' does not contain a definition for 'HasValue' and no accessible extension method 'HasValue' accepting a first argument of type 'Sound' could be found (are you missing a using directive or an assembly reference?) - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:1084,27	
2024/08/14 15:27:35.2481	[Generic] Error | 'Sound' does not contain a definition for 'Value' and no accessible extension method 'Value' accepting a first argument of type 'Sound' could be found (are you missing a using directive or an assembly reference?) - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:1088,23	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'PlaySound' does not exist in the current context - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:1096,4	
2024/08/14 15:27:35.2481	[Generic] Error | 'ScenePanelObject' is inaccessible due to its protection level - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\UI\WorldPanel.cs:215,23	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'Camera' does not exist in the current context - _gen_VignettePanel.razor_15940512.cs:150,22	
2024/08/14 15:27:35.2481	[Generic] Error | The name 'Position' does not exist in the current context - F:\SteamLibrary\steamapps\common\sbox\addons\base\Code\Entity\Hammer\PathPlatformEntity.cs:1240,3	
2024/08/14 15:27:38.8959	[engine/Engine] File sounds/kenney/ui/mouseclick1.wav missing vsnd extension (wav). Fixing for now.	
2024/08/14 15:27:39.0803	[engine/Engine] File sounds/kenney/ui/maximize_008.wav missing vsnd extension (wav). Fixing for now.	
2024/08/14 15:27:40.1293	[Menu] Loading startup scene: scenes/menu-main.scene	
2024/08/14 15:27:40.2113	[Menu] Tonemapping on (Camera) needs an API update, running upgraders	
2024/08/14 15:27:40.2178	[Menu] TypeLibrary couldn't find Component type MainMenu	
2024/08/14 15:27:41.2862	[TypeLibrary/Menu] Unknown Type MenuSystem	
2024/08/14 15:27:41.3130	[TypeLibrary/Menu] Unknown Type ModalSystem	
2024/08/14 15:27:44.6970	[Generic] One or more errors occurred. (The menu couldn't load. Can't continue.)	System.Exception: Menu couldn't load. Can't continue.
   at Sandbox.MenuDll.Sandbox.Engine.IBaseDll.Initialize() in C:\build\_work\sbox\sbox\engine\Sandbox.Menu\MenuDll.cs:line 183

I hope I didn't dox myself or some shit

### Expected behavior

The game opens.

### Media/Files

![Screenshot 2024-08-14 005221](https://github.com/user-attachments/assets/d4a2f7d5-0ae9-442d-9f32-b719a8e34d21)
![Screenshot 2024-08-14 150242](https://github.com/user-attachments/assets/500cd814-c9ac-41a7-a6cc-b41984f15657)

### Additional context

Running Windows 11, CPU: 13th Gen Intel(R) Core(TM) i5-13400F, GPU: NVIDIA Geforce RTX 4060

**Comment by handsomematt** [comment]
uninstall, delete your game folder, reinstall

you have loads of old files
