### ISSUE TITLE
Weird behavior with NavMesh agent + Skinned Mesh Model + Animation

### ISSUE THREAD

**Issue by Guilhem-Pech** [Facepunch/sbox-issues#6230]
### Describe the bug

If a nav mesh agent have a skinned mesh model, it behaves differently depending of the "Create bone objects" button

### To Reproduce

1. Create an object with an navmesh agent, a skinned model renderer and the model is animated
2. Make it wander around
3. Check/uncheck the create bone objects option

### Expected behavior

Same behavior with bones object or without

### Media/Files

https://github.com/user-attachments/assets/85a1f528-5817-4faa-9f33-fe8bc78fec93

**Comment by aylaylay** [comment]
Repro project please

**Comment by Guilhem-Pech** [comment]
Here you go @aylaylay 

Simple scene with one agent with bone object generated and the other without the bones objects

[navmeshagent_project.zip](https://github.com/user-attachments/files/16975576/navmeshagent_project.zip)

**Comment by aylaylay** [comment]
Thank you sir

**Comment by aylaylay** [comment]
Should be fixed now
