### ISSUE TITLE
Keep remaining world particles on GameObject deletion

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6232]
### For?

S&Box

### What can't you do?

When deleting the GameObject holding particle effects, every particle that was still alive gets deleted as well.
There should be an option, if not default, to keep world space particles and let them finish after the deletion of the parent.
This is different from deleting the gameobject when the particle is done. In our case we are manually deleting the gameobject and the particle is just decoration.

### How would you like it to work?

Similar to the legacy particle systems endcaps.

### What have you tried?

When we want to delete the gameobject we are currently disabling everything except the particle renderer and particle effect, then wait an arbitrary amount of time and finally delete the gameobject.
We have many systems that would require this, and it's implement in some of them, but it's not feasible or annoying in others.

### Additional context

Here's how they just disappear when deleted:

https://github.com/user-attachments/assets/fc2ac62d-f2d5-4dda-a078-be90e01ba525

https://github.com/user-attachments/assets/590c0354-9e5d-4c47-8a13-b9dd40d50e9a

**Comment by aylaylay** [comment]
I think a way to do this will be to move the component to a temp hidden game object and then delete that when all particles are finished

**Comment by aylaylay** [comment]
So after thinking about this, we shouldn't be moving a live component to other gameobjects so moving them to a temp object isn't the way.

The solution in other engines is to unlink the particle object from the parent and set the particle to DestroyOnEnd.

While I'd like there to be a built in way to keep playing particles after gameobject deletion, it's just not possible.
