### ISSUE TITLE
Hull cylinder colliders don't trigger.

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#6235]
### Describe the bug

A component with `Component.ITriggerListener` interface will not fire its methods when using a hull trigger of cylinder type.

### To Reproduce

1. Create a component that implements `ITriggerListener`.
2. Add a hull cylinder trigger.

See that it does not call those methods.

### Expected behavior

Cylinder hulls should be compatible with `ITriggerListener`.

### Media/Files

Here's a picture of my taxi in space with gravity fields on planetoids. My trigger component checks both `Collider.Touching` and on enter/exit. As you see here, the taxi is within the chocylinder(short for "chocolate cylinder") and yet it is not being considered as being within or entering/exiting even though it works for other types.

![sbox-dev_lYmCZgQEGc](https://github.com/user-attachments/assets/7f31bb22-04ef-4829-a529-bd16dddf899b)
![sbox-dev_OxFdrmmm8S](https://github.com/user-attachments/assets/7d37375e-510e-4fe9-8551-b2444a15170d)
![sbox-dev_KukeskddR9](https://github.com/user-attachments/assets/635dbf2f-0bb4-4727-a37d-8e4d8804c2c7)

**Comment by aylaylay** [comment]
What about the other hull types in that component?

**Comment by aylaylay** [comment]
I have tested this in testbed and they're working fine for cones and cylinders? The only difference I see is that they don't respect scale

**Comment by aylaylay** [comment]
Cylinder and cone respect game object scale now, if that was the problem you were having

**Comment by aylaylay** [comment]
Is it working now then?
