### ISSUE TITLE
[Terrain] Nav mesh has artifacts & nav agents can't move

### ISSUE THREAD

**Issue by AnthonyPython** [Facepunch/sbox-issues#6237]
### Describe the bug

Terrain's can generate navmesh with height but there is artifacts caused by it and nav agents absolutely refuse to use it despite a new navmesh is made.

### To Reproduce

create a new terrain
import a height map
nav mesh will generate
look at navmesh
place a nav agent down

### Expected behavior

Terrain nav mesh should not have artifacts
and nav agents should be-able to navigate with said navmesh

### Media/Files

![image](https://github.com/user-attachments/assets/47225d7c-4a43-4092-bd23-f608c633897b)

**Comment by MD485** [comment]
Is there any relation to this issue when it comes to NavAgent movement?
https://github.com/Facepunch/sbox-issues/issues/5878

Do they refuse to move, or can you not make valid paths/get valid points, so they can't move due to not having a path?

**Comment by AnthonyPython** [comment]
> Is there any relation to this issue when it comes to NavAgent movement? #5878
> 
> Do they refuse to move, or can you not make valid paths/get valid points, so they can't move due to not having a path?
I just tested it and it is indeed related to no valid paths so they can't move. I never get any points for a path.

**Comment by AnthonyPython** [comment]
Update I was able to get a couple points at least one time, but the nav agent still fails, despite simple path returning a couple of points am not sure what exactly is going on but it appears nav agents are broken with terrain navmesh in general.

**Comment by AnthonyPython** [comment]
More info it seems this is more of a general problem with navmesh generation on large meshes I got the same result using a large .vmap and it also created these artifacts, and it seems the navmesh having these artifacts is causing problems for nav agents.
[navmesh_problem.zip](https://github.com/user-attachments/files/16644172/navmesh_problem.zip)

**Comment by lolleko** [comment]
Should be fixed.
Tested the provided .vmap, the navmesh is now correctly generated. It should also work for terrain.
Let us know if the issue persists.
