### ISSUE TITLE
GLTF/GLB support

### ISSUE THREAD

**Issue by AnthonyPython** [Facepunch/sbox-issues#6240]
### For?

S&Box

### What can't you do?

Currently it is unsupported for GLTF/GLB models

### How would you like it to work?

Importing GLTF/GLB should work just like normal importing, but also create materials with or without embedded textures, it is also more extendible, as well as giving more freedom to add other data if needed.

### What have you tried?

While I could parse them myself, it would be better if s&box supported this out of the box. and since it is json it can easily be extended by developers.

**Comment by handsomematt** [comment]
#1671
