### ISSUE TITLE
[Terrain] splat map is bugged until painted in area's.

### ISSUE THREAD

**Issue by AnthonyPython** [Facepunch/sbox-issues#6241]
### Describe the bug

splat doesn't show up until painted into area's on the terrain.

### To Reproduce

create a terrain
export a heightmap
export a splat map (16bit png in this case dunno if it matters)
load height map and then splat map
observe splat map does not show till painted on

### Expected behavior

the painted area's from the splat map should already appear with out needing to paint to see it.

### Media/Files

[splat_map_bug.zip](https://github.com/user-attachments/files/16634269/splat_map_bug.zip)

https://github.com/user-attachments/assets/730e3f86-74f3-4123-8616-2ceb1ccaada8

### Additional context

I have provided the test files to use to fix this.

**Comment by AnthonyPython** [comment]
update, they also don't appear when opening a saved scene, this is problematic as my jam game uses terrains. I rather not have to use a giant mesh for performance related but I may have to since terrains are a mess right now and need some major fixes.

**Comment by aylaylay** [comment]
Because your splatmap had alpha, it was dominating all the other channels. I've changed splatmap import to bias against alpha, so if RGB totals 255, there will be no alpha in the splatmap. Your splatmap should import as you'd expect now.
