### ISSUE TITLE
Unable to change controls in game

### ISSUE THREAD

**Issue by Zac0511** [Facepunch/sbox-issues#6248]
### Describe the bug

When i try to edit controls in game (from the pause menu), i have 2 problems : 

- The custom controls i selected in the s&box settings (in the s&box main menu) are not applied
- When i try to edit a control in game, it says that it waits for me to press a key, but nothing happens even after pressing the key.

### To Reproduce

1. Open any game
2. Open the pause menu
3. Click the `Controls` button  (or, if on a game like Sandbox search the in game `edit controls` button)
4. Press one of the controls to edit
5. Try pressing a key and see nothing happens

### Expected behavior

What should happen is that the key i pressed should be saved, but here it justs waits for me to press a key, even tough i already pressed it.

### Additional context

I've set the language to French in the settings, maybe this could somehow break the controls edition.
I'm on Windows 11 23H2

**Comment by Zac0511** [comment]
This is a very annoying bug for me as i use an AZERTY keyboard

**Comment by garrynewman** [comment]
Settings modal should fix this

**Comment by PolSpock** [comment]
Related issue and my comment :
https://github.com/Facepunch/sbox-issues/issues/6279#issuecomment-2337782123

**Comment by Zac0511** [comment]
I can confirm that this bug has been fixed
