### ISSUE TITLE
The console doesn't open in some keyboard languages 

### ISSUE THREAD

**Issue by pBinarySoul** [Facepunch/sbox-issues#625]
**Describe the bug**
The console doesn't open in some keyboard languages 

**To Reproduce**

1. Add a new keyboard language (russian for example).
2. Change your keyboard language.
3. Try to open the console.

**Expected behavior**
The console won't open.

**Comment by deadmonstor** [comment]
This is basically the same as #127 however it should work on F1 or you could change the binds in the file to con_toggle

**Comment by garrynewman** [comment]
Duplicate of #127
