### ISSUE TITLE
GameObjectSystem Listen Order not being respected/followed

### ISSUE THREAD

**Issue by dotryen** [Facepunch/sbox-issues#6251]
### Describe the bug

Different listen events on the same stage do not follow the order they are set. Their execution order is determined by creation order.

### To Reproduce

1. Make two systems
2. Give them listen events on the same stage but different order. (Preferably `SceneLoaded`)
3. Log a message on each system
4. Start the game.
5. Restart the editor.
6. Watch it randomize.

### Expected behavior

The calls should ALWAYS be within the specified order. Things in people's games can break if they use these systems. (like me)

### Media/Files

`StateSystem` has a `SceneLoaded` listener set at -1000
`EnemySquadSystem` has a `SceneLoaded` listener set at 100

![image](https://github.com/user-attachments/assets/4fbc04bf-04b4-464b-b3c0-9123bae3a2fc)
![image](https://github.com/user-attachments/assets/8b5458b3-8ac1-4ac0-b8e7-b903a2a6169c)

**Comment by aylaylay** [comment]
Listen order should now be respected
