### ISSUE TITLE
Random crash to desktop when using VideoPlayer

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6255]
### Describe the bug

Recently I've had some crashes to desktop when using the VideoPlayer. These crashes seem to happen when a video stops or gets restarted by my hitch detection code, but it's not very consistent.

My steam ID is 76561198000586141

### To Reproduce

1. Open the attached project
2. Play the scene 
3. In the textbox on screen, enter this URL: https://www.youtube.com/watch?v=WePNs-G7puA
4. Click the play button
5. Wait until like the third episode where you see the big toilets on the highway
6. The video **might** hitch around that point and you **might** see a crash to desktop.

### Expected behavior

No crash to desktop

### Media/Files

[video_stop_ctd.zip](https://github.com/user-attachments/files/16650554/video_stop_ctd.zip)
[Log.2044.log](https://github.com/user-attachments/files/16650575/Log.2044.log)

https://github.com/user-attachments/assets/7763200f-0065-4dbc-953b-81101a0efce7

**Comment by aylaylay** [comment]
This repro doesn't crash for me anymore, at least the times I tried it

**Comment by gunnar-hensel** [comment]
I can confirm that this is happening with me, too. I have only used local files, though.

**Comment by chrisspieler** [comment]
> I can confirm that this is happening with me, too. I have only used local files, though.

Is it still crashing today? There was a fix pushed today.

**Comment by Nolankicks** [comment]
I can try to turns ours on and see if we still get the same issues.

**Comment by gunnar-hensel** [comment]
All is good. The first time I tried it crashed. Got it to work.

**Comment by Nolankicks** [comment]
Fixed I think?

**Comment by chrisspieler** [comment]
It works for me now without crashes.
