### ISSUE TITLE
Scene spot lights display misleading degree in property sliders

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#6257]
### Describe the bug

The Cone Inner/Outer values on scene spot lights go from 0-90 when it should be 0-180, because that makes sense for degrees.
So when you max out the slider at 90, its actually 180.

### To Reproduce

1. Add spot light to scene
2. Max out cone sliders
3. Question why its max displays as 90

### Expected behavior

Should display actual fov value.

### Media/Files

![image](https://github.com/user-attachments/assets/3914bb6f-b98e-4909-9468-424b167f0ef8)

**Comment by aylaylay** [comment]
This is correct, they're in half angles in the engine. Even if we were to change this is would be game breaking. I've updated the comments to help with any confusion.
