### ISSUE TITLE
Kaspersky IS thinks the executable is trojan

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/sbox-issues#626]
**Describe the bug**
When the game was running in a window, I lost ficus for a bit and the executable got deleted by the AV

**To Reproduce**
1. Run Sandbox
2. Go to video settings
3. Chose Window mode
4. Enter game
5. Lose focus from the window

**Expected behavior**
The game executable must not be detected as a virus

**Screenshots**
https://cdn.discordapp.com/attachments/833983435092525147/873120238898671646/unknown.png

**Additional context**
https://cdn.discordapp.com/attachments/873120241360715816/873500397891911720/Capture.JPG

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by Rohansi** [comment]
https://support.kaspersky.com/viruses/answers/1870

**Comment by pBinarySoul** [comment]
Uninstall.

**Comment by dvdvideo1234** [comment]
`*box.exe`: https://opentip.kaspersky.com/DC0C07AEE6D8B4B977A9A518BBF148E748F387AD07FB85F99088ACE18AA49353/
`*dev.exe`: https://opentip.kaspersky.com/5765DEC9338B9A2BA086D8EC6411BBC624914687D03102DD6B53090650585A55/

This appears to be really a false positive. Whitelisted! Thanks !

**Comment by MrAmos123** [comment]
Uninstall Kaspersky and use Windows Defender. No need for 3rd party AVs.

**Comment by SupinePandora43** [comment]
> Uninstall Kaspersky and use Windows Defender. No need for 3rd party AVs.

Use linux.
No need for AVs.
Viruses can't break your system if you will do it by yourself.
