### ISSUE TITLE
Voxel model transparency causes issues with SSAO

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6265]
### Describe the bug

When looking through a voxel model, you will be able to see SSAO through it.

### To Reproduce

1. Create a voxel model.
2. Add SSAO to your camera.
3. Look through it.

### Expected behavior

It should not be shown.

### Media/Files

![image](https://github.com/user-attachments/assets/05ea1309-680e-42d3-9112-a7483e7ad8b7)
![image](https://github.com/user-attachments/assets/ae4c2e27-042f-4d72-9a73-0c21201cb107)

**Comment by aylaylay** [comment]
a voxel model how?
what material?

**Comment by Nolankicks** [comment]
> a voxel model how? what material?

No material, a .vox file using made using Magicavoxel.

**Comment by Nolankicks** [comment]
![image](https://github.com/user-attachments/assets/7f10af86-d962-4cc6-834f-75f5a6742b13)

**Comment by Nolankicks** [comment]
It shows like this with transparency. Not sure if this is a bug.

**Comment by Nolankicks** [comment]
![image](https://github.com/user-attachments/assets/8b0e799d-2585-4c2c-9b3f-dadd315aa49e)

**Comment by Nolankicks** [comment]
![image](https://github.com/user-attachments/assets/570e452d-7f08-45ca-a60e-d24f16a3e7fa)

**Comment by aylaylay** [comment]
vertex_color now works with opaque fade. SSAO will show through but it looks like that's how it works for anything using opaque fade. If you don't like that or think it's wrong then you'll have to open another issue specifically about SSAO
