### ISSUE TITLE
NavMeshAgent isn't doing a null check for internal agent

### ISSUE THREAD

**Issue by dotryen** [Facepunch/sbox-issues#6271]
### Describe the bug

Calling `Stop()` on a NavMeshAgent that hasn't had a destination yet shouldn't throw an `NullReferenceException`. It should check for null beforehand.

### To Reproduce

1. Make a `NavMeshAgent`
2. Call `Stop()` on it before setting a destination

### Expected behavior

It shouldn't throw an exception, even if it hasn't gotten a destination before.

**Comment by aylaylay** [comment]
Done - thanks
