### ISSUE TITLE
Random crashes when auto-reloading model assets

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6277]
### Describe the bug

Started noticing this a few days ago when I started re-exporting meshes more often. Sometimes when a model gets reloaded/recompiled because of an outside change, the editor just crashes unexpectedly.

I am not sure what causes this, but It has been happening with obj files regularly. It also does not happen each time, but it does happen very often.

### To Reproduce

1. Have a model which references an .obj mesh
2. Export a new version of the .obj, triggering an asset recompile
3. See if the editor crashes or not (sometimes it does, sometimes it does not)

### Expected behavior

No crashing please

### Additional context

Some additional stuff from logs just before the crash:

```
2024/08/21 12:41:12.1147	[engine/AssetSystem] Reloading Resource [1/1]: models/map_parts/sgc/railing/sgc_railing_cr_stairway.vmdl	
2024/08/21 12:41:12.1147	[engine/AssetSystem] On-demand recompile of asset models/map_parts/sgc/railing/sgc_railing_cr_stairway.vmdl	
2024/08/21 12:41:12.1147	[engine/AssetSystem]  -> reason: At least one out-of-date dependency: models/map_parts/sgc/railing/sgc_railing_cr_stairway.obj (file CRC changed)	
2024/08/21 12:41:12.2218	[engine/AssetSystem] Reloading Resource [1/1]: models/map_parts/sgc/railing/sgc_railing_cr_stairway.vmdl	
```

**Comment by Gmod4phun** [comment]
Happens with any model, so I didnt bother sending any, but in case something is in the file by any chance, sure. This is a model that just crashed when re-exported:

[rims.zip](https://github.com/user-attachments/files/16694655/rims.zip)

**Comment by Gmod4phun** [comment]
Could be a shot in the dark, but I feel like it has something to do with rebuilding the thumbnails in the asset browser.

These are two lines I have been occasionally seeing in my crash logs after the model (and its thumbnail) was reloaded (havent seen both happen at once, just one of them individually):

```
[engine/Qt] QPaintDevice::metrics: Device has no metric information

[engine/Qt] QPixmap::operator=: Cannot assign to pixmap during painting	
```

**Comment by aylaylay** [comment]
is the model being used in the scene at the time of reload?

**Comment by aylaylay** [comment]
Nevermind I get the crash when the thumbnail is showing

**Comment by Gmod4phun** [comment]
I probably could have mentioned that I also had Hammer open at the same time, with its own asset browser window and those models being reloaded. I once even caught a glimpse of the icon being the default blue box just before the crash occured.

It seems to b e random, no idea why. I can sometimes reload the model 2 times and it crashes the next, sometimes its fine for even 10+ reloads.

**Comment by aylaylay** [comment]
Still trying to get this to trigger, only had it happen once but I wasn't debugging at the time

**Comment by Gmod4phun** [comment]
I have been getting this pretty often :D Basically just have the asset browser with the folder where the mesh is opened, and it crashes when it tries to regenerate the icon.

**Comment by aylaylay** [comment]
Right, I managed to get a repro and fixed the crash I was getting. Hopefully it was the same crash you were getting and it's fixed now.

**Comment by Gmod4phun** [comment]
Thank you. I will do some more exporting in the following days and close the issue if it no longer keeps crashing :)

**Comment by Gmod4phun** [comment]
Haven't encountered a crash since I think, so looks like it is working now, closing the issue :)

**Comment by aylaylay** [comment]
Fantastic
