### ISSUE TITLE
Bind editore modal broken

### ISSUE THREAD

**Issue by ivan2282-i28** [Facepunch/sbox-issues#6279]
### Describe the bug

Im clicking to "B (default)"(or etc.), see "Click a button", clicking a button and nothing happen!

### To Reproduce

1.Open "Bind editor"
2.Click to any bind
3.See "Click a button"
4.Click a button keyboard 
5.Nothing Happened 

### Expected behavior

"Click a button" should be like "A" or etc.

### Additional context

Windows 11

**Comment by CarsonKompon** [comment]
Where are you experiencing this problem? In the pause menu of your game, or someone elses game? Could you provide a video and/or the name of the game this happened in?

**Comment by PolSpock** [comment]
The issue is marked as closed, but it still occurs:

https://github.com/user-attachments/assets/f60e48b5-235c-49a7-9b9c-c30853d830a6


Every AZERTY player has been experiencing this issue for a few months, and it's very annoying.
