### ISSUE TITLE
Big feet - Feet bones are not scaled properly when scaling the model.

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6280]
### Describe the bug

When scaling a skinned model renderer the feet are scaled incorrectly.

### To Reproduce

1. Create a SkinnedModelRenderer and use the citizen model
2. Scale on all axis

### Expected behavior

To scale correctly

### Media/Files

![image](https://github.com/user-attachments/assets/b9e6d4f5-f52b-469b-ab0f-ff6f39a012d7)

![image](https://github.com/user-attachments/assets/b874b978-06a8-4d38-b9b6-42372d4ebbf2)

### Additional context

Might be related to the fact that the feet are near the origin point? It seems that the scale of the feet depend on the rotation and position, but I can't find any correlation.

**Comment by eEight-dev** [comment]
I tested it and it seems that the feet IK have something to do with it. Specifically this section here:
![1](https://github.com/user-attachments/assets/702ba407-9b3c-408e-8e00-67bc4a2a17f6)
If I unplug these and plug in the "Procedural Hit Reactions" instead the feet are no longer big and scale accordingly with the rest of the model.

**Comment by aylaylay** [comment]
I've fixed the big feet. Just check for me that the IK still works as expected when scaled

**Comment by eEight-dev** [comment]
I've tested it with our micro mayhem characters and they seem to work as expected now even when scaled

**Comment by aylaylay** [comment]
Fantastic
