### ISSUE TITLE
Assets Browser: Add option to sort all orphaned compiled assets

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6285]
### For?

S&Box

### What can't you do?

Working in a team and using GitHub leads to compiled assets being left orphaned when their uncompiled counterpart gets deleted. This is an issue because everyone else now has to find the problem compiled asset and delete them manually.
We have some systems that look up all resources of a type, and if there's orphans they will be picked up as well and return errors.

### How would you like it to work?

![image](https://github.com/user-attachments/assets/6579f793-1aca-413a-b78d-55c21fb98c4a)

Somewhere in this list, preferrable around the top.

### What have you tried?

Manually searching and deleting, wastes time for everyone involved.

**Comment by NotGaylien** [comment]
cant get this to work, i tried @orphaned but no text filters in my asset browser works,
could we get it in the little list like in the picture above,
i feel like its a really important thing to have

**Comment by CarsonKompon** [comment]
> cant get this to work, i tried @orphaned but no text filters in my asset browser works, could we get it in the little list like in the picture above, i feel like its a really important thing to have

I can probably add it to that list when I get back home. Have you tried putting a SPACE after `@orphaned`?

**Comment by NotGaylien** [comment]
yeah idk why nothing seems to work,
t:vmdl works,
but anything with @ seems to not work for me, no clue why
