### ISSUE TITLE
Decouple Particle Effect's "Apply Color" and "Alpha" settings

### ISSUE THREAD

**Issue by Willco2** [Facepunch/sbox-issues#6288]
### For?

S&Box

### What can't you do?

I can't set each particle's color individually when "Apply Color" is checked. However, "Apply Color" is still needed for the "Alpha" setting to have any effect.

### How would you like it to work?

I want the "Alpha" setting to have its own toggle, separate from the "Apply Color" setting. Then a Particle Effect can drive the particles' alpha without modifying the `Color` field.

### What have you tried?

Writing a custom Particle Listener and modifying particle color and alpha manually.

**Comment by aylaylay** [comment]
I've added apply alpha, alpha will still get applied when applying color though as changing this would break current particles

**Comment by aylaylay** [comment]
Nevermind, I added an upgrade, color and alpha should now be properly decoupled
