### ISSUE TITLE
Ability to shift anchor for hinge joints

### ISSUE THREAD

**Issue by Northalicious** [Facepunch/sbox-issues#6294]
### For?

S&Box

### What can't you do?

I was working on a pinball game when I noticed I couldn’t shift the anchor point for the hinge joints. This is a feature present in Unity, but seems to currently be missing from s&box, and I think it would be super helpful for increasing ways to interact with the physics engine.

### How would you like it to work?

I just want a Vector3 that I can shift around in properties to change the point around which the hinge joint rotates.

### What have you tried?

I’m currently using a physics object with a position that will center to my desired anchor point, and then welding a longer stick to that to help shift everything over. Admittedly, it works pretty well in-physics-engine, but still feels a little jank and harder to control.

**Comment by aylaylay** [comment]
We usually try to avoid offsets like this on the component because you can just have the joint in a child game object and offset that. Is there something that doesn't make this an option for you?

**Comment by Northalicious** [comment]
I see. No, this option actually does work out well for me. Thanks!
