### ISSUE TITLE
Cannot delete a leaderboard from the stat web panel

### ISSUE THREAD

**Issue by Reece-Carruthers** [Facepunch/sbox-issues#6297]
### For?

S&Box, Other

### What can't you do?

When using the stat web panel for a game  https://sbox.game/<org>/<GAME_NAME>/stats/ and you click on a leaderboard and edit, there is currently no way to remove it.

### How would you like it to work?

I would like a button to delete the leaderboard, like the way deleting a stat works.

No delete button visible

![image](https://github.com/user-attachments/assets/dc488838-b923-4b71-a079-853c8e4bfcfc)

Stat delete button

![image](https://github.com/user-attachments/assets/d9b6a4f5-adcb-4f60-9408-d584761216a0)

### What have you tried?

I have clicked around the UI to see if it is possible to delete, but could not find any options

**Comment by Dimmies** [comment]
I believe it's planned #4814
