### ISSUE TITLE
Add interface for entity ticking

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/sbox-issues#63]
**What can't you do?**
Implementing any kind of deterministic logic is currently impossible/hard to do. One way around is currently using OnPostPhysicsStep but that requires entities to have physics. For entities that act as systems don't require any physics and should also not rely on the physics steps this is not necessarily the same as the tick rate, that depends on how its implemented I can't tell.

**How would you like it to work?**
Maybe another interface such as ```ITickUpdate``` or ```ITickable``` whatever the better name is, the entity should implement ```void OnTick(float dt)``` which runs on the client and server.

**What have you tried?**
The current work-around is ```OnPostPhysicsStep```

**Additional context**
I think this will also be eventually required when it comes to porting native entities to C#, logic_timer would probably be one of the kind that needs this. @garrynewman mentioned on Discord the use of ```async``` potentially, this is fine if we have a way to wait based on (predicted) host time rather than system clock.

**Comment by cr4yz** [comment]
I was looking for this too.

Could _maybe_ forgo the dt parameter (in OnPostPhysicsStep too?), Time.Delta should cover it right?

**Comment by garrynewman** [comment]
So I did this, you can do this on entities now

![image](https://user-images.githubusercontent.com/928843/116614032-4faa8900-a931-11eb-9ff7-70f89cdf3a37.png)

You can also do this

![image](https://user-images.githubusercontent.com/928843/116614069-5b964b00-a931-11eb-8389-a4e5bae97a28.png)

Let me know if this solves your problem

**Comment by cr4yz** [comment]
Works for me

**Comment by Jake-Rich** [comment]
Could there be a static helper class with common event names?

```
public static class EventTypes
{
    public const string ServerTick = "server.tick"
    public const string Tick = "tick"
}
```

```
[Event( EventTypes.Tick )]
public void Blah
```

**Comment by Erlite** [comment]
Looks cool, will it be possible to create your own events in the feature?

**Comment by ZehMatt** [comment]
Might be note worthy, DebugOverlay.ScreenText seems to be different in such event function, I do not need to supply the lifetime anymore for it to work, outside of it I need to have something like Time.Delta * Something.
