### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by CritickalGames** [Facepunch/sbox-issues#6301]
### For?

S&Box

### What can't you do?

+Sorry if i miss selecting the "for?" but, im new. Thanks for your patience.+

I don't reconoce easy the element on the hierarchy

### How would you like it to work?

Like godot engine and use icons for the element.

If a have a light: the icon is the light icon and not that flat cape icon.

### What have you tried?

Organice the proyect.

### Additional context

Im new and my first was godot engine, so, i like so much the icons to read easyest the hierarchy of godot.

And, sorry for my english, i realy speak spanish.

**Comment by badandbest** [comment]
Adding icons to game objects in the hierarchy has already been suggested. https://github.com/Facepunch/sbox-issues/issues/5605

**Comment by xezno** [comment]
Dupe of #5605
