### ISSUE TITLE
Amd driver crash issue in Micro Mayhem

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6318]
### Describe the bug

Under the following Steam Ids are a crash that have been identified to be an Amd driver crash issue. This is pretty easily reproducible, but not sure how easy the fix is.

Some affected SteamIds: 
76561198055543044
76561198416851894

### To Reproduce

1. Open Micro Mayhem
2. Join or create a lobby
3. Open the wardrobe
4. Navigate to the Dances tab
5. If your card is affected, your game will crash

### Expected behavior

No crash

**Comment by aylaylay** [comment]
Should be fixed now
