### ISSUE TITLE
Controllers without Gyroscope support outputs non-zero Gyro values

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#6319]
### Describe the bug

Controllers that lack gyroscope hardware (ex. entire line of Xbox controllers) report gyro values greater than 0. Some of these can be detected and worked around because they report astronomical values, like the Xbox Series X controller:
![image](https://github.com/user-attachments/assets/d8670bb5-4c57-4fc3-adc0-a92739c30293)

However, one of our Micro Mayhem players reported issues with their Xbox One controller, which we've deduced is from false gyro values (we support gyro for obstacle placement, and they reported their obstacle as infinitely spinning when just trying to rotate it normally). While we can continue lowering our sanity check threshold, the engine should handle this.

### To Reproduce

1. Download and run [repro scene.](https://github.com/user-attachments/files/16775808/gyrorepro.zip) This just logs Input.MotionData.Gyroscope every frame.
2. Plug in an unsupported controller and observe non-zero Gyro values. Sometimes it spits out erroneous values constantly, and sometimes it takes a few seconds of pressing buttons before it pops out.

### Expected behavior

Controllers without gyro hardware should always output 0 for their gyro values. Ideally y'all can identify specific models and stomp the values for non-supported ones.

### Additional context

As an aside, I tested both Wired and Bluetooth connections and both reported erroneous values. Unfortunately the only unsupported controller I have is a Series X controller, so I cannot report updates with say Xbone or Switch controllers.

**Comment by DevulTj** [comment]
Hey, I've pushed something that should fix this for you. Let me know if it doesn't!
