### ISSUE TITLE
Traces collide with scene meshes with no collision

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#6320]
### Describe the bug

When doing a trace in the scene, it collides with any scene meshes in the scene regardless of the collision type.  I'm using this to make prototype shapes for a game so each mesh component is set up like such:
![image](https://github.com/user-attachments/assets/a6bd6ee2-c8da-436f-bf94-7d59430d2536)
There is no physics objects shown in the physics debug mode, yet it still recognises the mesh as one.
This is the code I used to trace an object:
```var tr = Scene.Trace.Ray(startPos,endPos).Radius(5.0f).WithoutTags(IgnoreTags).Run();```

### To Reproduce

1. Create a scene mesh and remove all collision
2. Trace through the mesh
3. View hit object, it should be the mesh

### Expected behavior

The mesh should be ignored

**Comment by aylaylay** [comment]
I can't repro this. I'm tracing against a scene mesh with no collision and it's not hitting. Could you provide a downloadable repro please?

**Comment by aylaylay** [comment]
Closing because I can't repro this
