### ISSUE TITLE
Add a scroll bar to gamepad input dropdown in input settings

### ISSUE THREAD

**Issue by nol3w** [Facepunch/sbox-issues#6321]
### For?

S&Box

### What can't you do?

I tried binding my right trigger to a new action but since the action is towards the bottom of the screen the drop down menu falls off and i cant select "Right Trigger" at the bottom of it
![image](https://github.com/user-attachments/assets/40679768-db7c-4d3a-9bc9-6b3f7c1aa2eb)

### How would you like it to work?

Add a scroll bar to the drop down

### What have you tried?

Adding more actions so my action is higher up and i can see the whole drop down

**Comment by aylaylay** [comment]
I've made it constrain to screen so it should never flow outside of the window. A scrollbar shouldn't be necessary because it's a finite number of menu options.
