### ISSUE TITLE
Objects drawn through Graphics.DrawModel aren't rendered to Depth buffer?

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#6327]
### Describe the bug

Currently the only way to use Graphics.DrawModel or Graphics.DrawModelInstanced is through a rendering hook, all of which are after the depth pass, so anything drawn at that time simply ignores any depth based effects such as ambient occlusion?
Discord topic: https://discord.com/channels/833983068468936704/837215495496663040/1275640950860812360

### To Reproduce

I have a basic component that draws instances through the AddHookAfterOpaque rendering hook, so add a model and some transforms. Look at depth buffer. Profit..?

```cs
public sealed class InstanceRenderer : Component, Component.ExecuteInEditor
{
    [Property] public Model InstanceModel;
    [Property, Hide] public Transform[] Transforms;
    [Property] public SceneLayerType RenderLayer;

    private IDisposable renderHook;
    protected override void OnStart()
    {
        renderHook?.Dispose();
        if ( RenderLayer == SceneLayerType.Translucent )
            renderHook = Game.ActiveScene.Camera.AddHookAfterTransparent( "TransparentRenderer", 0, RenderInstances );
        else
            renderHook = Game.ActiveScene.Camera.AddHookAfterOpaque( "OpaqueRenderer", 0, RenderInstances );
    }
    protected override void OnDisabled()
    {
        renderHook?.Dispose();
        renderHook = null;
    }

    private void RenderInstances( SceneCamera c )
    {
        Graphics.DrawModelInstanced( InstanceModel, Transforms );
    }
}
```

### Expected behavior

I'm not sure how it would work since everything is done after the depth pass but being able to have the option to allow Graphics.DrawModel to access depth or have a depth rendering hook?

**Comment by handsomematt** [comment]
I wouldn't expect this to. Render hooks are at the specified point in the render loop. The depth prepass and shadows are their own passes.

You should use a SceneCustomObject
