### ISSUE TITLE
NetworkComponent codegen error between namespaces

### ISSUE THREAD

**Issue by Sampleeeee** [Facepunch/sbox-issues#633]
**Describe the bug**
NetworkComponent cannot be networked between different namespaces. Don't really know how to explain it too well, just take a look at the reproduction steps.

**To Reproduce**
Try to use the NetAttribute on a NetworkComponent class from a different namespace. Take a look at these examples

The broken gist throws the error you linked in the screenshots section

Broken: https://gist.github.com/Sampleeeee/3d8fd2e611c3565b67b7795a3595fc74
Working: https://gist.github.com/Sampleeeee/ca19147a1c2743fd1955acab846fe619

**Expected behavior**
it should not error

**Screenshots**
https://sample.wtf/i/sample/untrustworthy-coral-minister.png

**Comment by Acecool** [comment]
Additional information:

Correct using statement and no issues with the code itself: ( no invisible characters or odd chars - you'd be surprised how many times this made code which looked perfect not properly compile )

Note: If you remove [Net] then it compiles fine, so something within that component is trying to access the element directly as defined.

ie: If you type the full access out ie: 
```
[Net] public Broken.DifferentNamespace.NetworkComponentTest Test { get; set; } = new Broken.DifferentNamespace.NetworkComponentTest();
```

then it compiles fine so something within the Net attribute is causing the issue.
