### ISSUE TITLE
Game is not launching, logs are not creating

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#6333]
### Describe the bug

So far 2 people have described this case, I’m just passing on information in general.

**attempts to solve:** 

> NET 7.0 installed,
> new build versions installed, 
> -dx11 -vulkan -safe_mod already tried,
> the game was reinstalled several times from different accounts,
> specs rtx 3060, 11th i7-11700F, 16gb ram, 64x  and  gtx 1650 i312100f 16gb ram

**information that may help** 

>error when starting s&box server:

![image](https://github.com/user-attachments/assets/1d5804cf-a3dc-47f4-a726-1d5fb96d860f)

>I don’t know if this error or not, perhaps these directories are created during work, but half of them are missing
![image](https://github.com/user-attachments/assets/9879efa3-e1cf-4d1c-879e-b2a36165f067)
![Снимок экрана (190)](https://github.com/user-attachments/assets/26635e99-d7c0-432f-bb14-82d2255ee818)

**discord nicknames of those who had this happen**
@da_poebat_mne7705  @ilkino

### To Reproduce

launch s&box

### Expected behavior

s&box lauching - everyone happy

**Comment by handsomematt** [comment]
do you not personally have this problem? it's not that helpful making issues you're not experiencing but random people on discord are

the last few times this happened was because they were using a steam emulator

**Comment by AdoptMeIlkinoReal** [comment]
> do you not personally have this problem? it's not that helpful making issues you're not experiencing but random people on discord are
> 
> the last few times this happened was because they were using a steam emulator

I am one of the people who are facing the issue. No, I am not using a steam emulator

**Comment by Fenek413** [comment]
> у вас лично нет этой проблемы? это не так уж и полезно, создавать проблемы, с участием вы не сталкиваетесь, но случайные люди в Discord
> 
> в последние несколько раз это случалось из-за того, что они использовали эмулятор Steam
Что делать если я не использую эмулятор steam?

**Comment by Fenek413** [comment]
> у вас лично нет этой проблемы? это не так уж и полезно, создавать проблемы, с участием вы не сталкиваетесь, но случайные люди в Discord
> 
> в последние несколько раз это случалось из-за того, что они использовали эмулятор Steam


Что делать если я не использую эмулятор steam?

**Comment by Fenek413** [comment]
> у вас лично нет этой проблемы? это не так уж и полезно, создавать проблемы, с участием вы не сталкиваетесь, но случайные люди в Discord
> 
> в последние несколько раз это случалось из-за того, что они использовали эмулятор Steam



What should I do if I don't use the steam emulator?

**Comment by somethink000** [comment]
> do you not personally have this problem? it's not that helpful making issues you're not experiencing but random people on discord are
> 
> the last few times this happened was because they were using a steam emulator

ok...

**Comment by MD485** [comment]
> error when starting s&box server:

Is the issue starting sbox.exe, sbox-dev.exe, or just sbox-server.exe?
Because I'm pretty sure sbox-server.exe isn't currently supposed to be working.

![image](https://github.com/user-attachments/assets/7b035cc1-fea5-48d7-a992-0b6fbe21d295)
Well technically it's working, but the message of the day says that it currently does not work.

**Comment by somethink000** [comment]
> > error when starting s&box server:
> 
> Is the issue starting sbox.exe, sbox-dev.exe, or just sbox-server.exe? Because I'm pretty sure sbox-server.exe isn't currently supposed to be working.
> 
> ![image](https://private-user-images.githubusercontent.com/36082767/363447850-7b035cc1-fea5-48d7-a992-0b6fbe21d295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTA3MDksIm5iZiI6MTcyNTIxMDQwOSwicGF0aCI6Ii8zNjA4Mjc2Ny8zNjM0NDc4NTAtN2IwMzVjYzEtZmVhNS00OGQ3LWE5OTItMGI2ZmJlMjFkMjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE3MDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDIyYmNlMjM3YzVmYjE2OGJkZWRjMDU5NDRhZmQxMDRmNjNhYzUwNzIwOGEyZmE3MWQyNzE5NzM4YzM4MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VcT1Owu82RioD3SZGi86QG39dmJ_kQeKsivZzfluqdw) Well technically it's working, but the message of the day says that it currently does not work.

everything

**Comment by somethink000** [comment]
solution - https://github.com/Facepunch/sbox-issues/issues/5962

**Comment by handsomematt** [comment]
that is what I said, a steam emulator
