### ISSUE TITLE
Stop people opening VR only games oustide VR.

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6335]
### For?

S&Box

### What can't you do?

Stop people from opening the game outside VR

### How would you like it to work?

If the game is marked VR only, if the game has not been launched in steam VR mode it stops them from opening it.

Also a popup that explains why the game won't open and an icon before the title might be nice.

### What have you tried?

- I added a scene that checks if the player is in VR, and if not, it displays big text that says "VR Only" in English, Russian and French. Which stops the errors happening that occur when VR is not active, but people can still open the game and I've watched people open the game, leave and leave a dislike through the session list.
- Including VR and the Batak letter ᯅ (looks like a headset) in the title.

### Additional context

Also would be nice is there was a play limit before someone can leave a dislike/like. Even just 30 seconds would be fine (some games might be completely broken before you get to even 1 minute, so it is reasonable to have this time short.)

**Comment by DrakeFruit** [comment]
Carson seems to have fixed this on his branch
![image](https://github.com/user-attachments/assets/bcd318a2-3a16-481d-a0be-0a4ab8917733)
