### ISSUE TITLE
Polish / bug: Bind not retained through restart for / / ? key

### ISSUE THREAD

**Issue by Acecool** [Facepunch/sbox-issues#634]
Low Priority - only appears to affect a single key but I haven't tested that many.

**Describe the bug**
When typing bind / "restart" in console, it properly binds the "/", "?" key to restart. Likewise I can bind it to any other command and have it work. However, when the game is restarted ( closed and opened ) the bind is removed.

Other keys such as the ",", ".", " ' " keys retain their binds properly through restart.

**To Reproduce**

- Start a game ( likely optional )
- Type 
```
bind / "restart"
```
In console.

- Press it to verify it is bound.

- type quit in console, or exit the game normally.

- restart the game

- start a game

- press the key.

**Expected behavior**

The key should be bound and retain through restart...

**Additional context**

Other keys work, is this one being processed as a special char? I have also tried bind "/" "restart" and without quotes with the same result so it is related to the key itself. Even binding other keys during the same restart - they work fine and change properly but the / key is ignored through game restarts..

For others: the restart command restarts the server not the game.

**Comment by handsomematt** [comment]
Uses our own input action system now
