### ISSUE TITLE
Rotate trace boxes

### ISSUE THREAD

**Issue by dotryen** [Facepunch/sbox-issues#6340]
### For?

S&Box

### What can't you do?

Currently you cannot rotate a box trace. As in `Scene.Trace.Box(Vector3 center, Vector3 size)`. It is always axis aligned.

### How would you like it to work?

Ideally another builder method could be made, probably called `Rotate(Rotation rot)`.
This can let us rotate all traces in the future, in case anything changes.
But another `Box` overload with a rotation parameter would suffice as well.

### What have you tried?

I've tried using `PhysicsBody` to test for overlaps. I've tried using triggers.
However currently the best solution is to make an approximation of the box using capsules.

**Comment by aylaylay** [comment]
I've added Scene.Trace.Rotated, rotated box traces was already possible through Scene.Trace.FromTo( Transform, Vector ) but seeing as no one knew it did that justifies having a rotated function.
