### ISSUE TITLE
[Terrain] Terrain is not rendered in editor if there are no cameras in the scene.

### ISSUE THREAD

**Issue by surv0013** [Facepunch/sbox-issues#6344]
### Describe the bug

Terrain is not visible **in editor** unless there is a camera on scene.

### To Reproduce

1. Create new scene
2. Create terrain
3. ???
4. Profit

### Expected behavior

Terrain should always be visible in the **editor**.
The scene can be without a camera.

### Media/Files

![image](https://github.com/user-attachments/assets/62da96f9-6020-486b-9ecb-f154ac591f87)

**Comment by aylaylay** [comment]
Fixed
