### ISSUE TITLE
Default plane model won't render backfaces when given a material with "Render Backfaces"

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6347]
### Describe the bug

The default plane model seems to not render from the back, even if it has a material that has render backfaces enabled. Other models seem to work fine (like the box model). This affects all materials, not just glass.

Also don't mind the weird glass backfaces, that is a separate issue.

### To Reproduce

1. Add a plane
2. Add a material that renders backfaces
3. Look through the back and see that it does not render

### Expected behavior

Should render backfaces, just like other models.

### Media/Files

https://github.com/user-attachments/assets/73958ef8-3f09-45e4-8999-2be43460a870

**Comment by CarsonKompon** [comment]
This is intentional, as the model itself doesn't have a backface.
Typically planes don't need their backfaces so the given plane model doesn't have one.
If you need a 2-sided plane you can quickly create one of any shape/size/material using the Scene Mesh Editor tools following my latest push:

![image](https://github.com/user-attachments/assets/36cad031-fa2a-46a5-bac7-c2cdf44e5806)

**Comment by Gmod4phun** [comment]
I thought all faces of any mesh have a front and back direction, automatically. And enabling backface rendering would just, you know, render it when viewed from the other direction.

Not an issue for me personally, it just boggles my mind.

**Comment by CarsonKompon** [comment]
Oh I see what you mean now, I misunderstood. I notice what you mean on the plane... Doesn't happen on box or sphere.
This might be an issue with RenderPrimitivePlane in ModelDoc (since that's how the plane is constructed)

**Comment by Gmod4phun** [comment]
Oh, that could be something. I haven't tried personally but I bet if you just imported a random plane model into modeldoc, it would render a material on its backfaces if that material supports that.

**Comment by Gmod4phun** [comment]
Can confirm its fixed, thank you
