### ISSUE TITLE
JSON doesn't serialize property if class sets default different from the types default

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6349]
### Describe the bug

Setting a property's default value in a class you want to use as a JSON that isn't the same as that types default value, causes it to not serialize if you set the property's value to the same as the default.

### To Reproduce

1. Make a class you want to save as a JSON
2. Add a property that has a default value set different from it's type's default value
3. Set instance of class property to the type's default value
4. Save JSON
5. Load JSON
6. Notice that the loaded version uses the class's default value instead of the type's, even though we set it to the type's value

```cs
public class JSONs_Issue : Component
{
	[Property] public Example example {  get; set; } = Example.A;

	[Button("Test")]
	public void Test()
	{
		var inst = new JSONTest();
		inst.example = example;
		FileSystem.Data.WriteJson("JSONTest.json", inst);

		var loadedInst = FileSystem.Data.ReadJson<JSONTest>("JSONTest.json");
		Log.Info($"loadedInst.example: {loadedInst.example} example: {example}");
	}
}

public enum Example
{
	A,
	B,
	C
}

public class JSONTest
{
	public Example example { get; set; } = Example.B;
}
```

### Expected behavior

JSONs should properly serialize the value you set

### Additional context

I think the JsonSerializerOptions needs `DefaultIgnoreCondition = JsonIgnoreCondition.Never` instead of `JsonIgnoreCondition.WhenWritingDefault`

**Comment by timmybo5** [comment]
Related to: https://github.com/Facepunch/sbox-issues/issues/6995
