### ISSUE TITLE
Elements inside a foreach loop in razor doesn't clear if the new value is empty

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6352]
### Describe the bug

When you're looping through a data structure and printing stuff to the layout, changing the data for pagination or just pure chance when it redraws, it won't clear it when it should.

### To Reproduce

1. Click cycle items
2. Notice that some element texts are not clearing when it should be empty

### Expected behavior

Clear when value is null or empty

### Media/Files

https://github.com/user-attachments/assets/6973c900-1de2-4bd2-9585-e336c216e6eb

[razor_foreach_repro.zip](https://github.com/user-attachments/files/16839783/razor_foreach_repro.zip)

**Comment by solwllms** [comment]
Think this should've been fixed with recent changes. Can you give it a check in your real-world use case and let me know? I can't repro on this (v handy!) repro project either

**Comment by MrBrax** [comment]
fixed
