### ISSUE TITLE
Steam ID number in stats is off by 1

### ISSUE THREAD

**Issue by DaiterGG** [Facepunch/sbox-issues#6353]
### Describe the bug

wrong number
I assume it's a long ulong problem

### To Reproduce

1. set stat 
![2024-09-02 19_27_22-Leaderboards cs - s box (Workspace) - Visual Studio Code  Administrator](https://github.com/user-attachments/assets/c83f6be6-8a73-456c-b089-7ef7e4e5279f)
2. request leaderboard
https://services.facepunch.com/sbox/package/leaderboard/move.stasis/?stat=move.plground&aggregation=min
3. for some users ID is different
![2024-09-02 19_16_38-⭐Daiter⭐ · Steam Calculator · 76561198198173471 · SteamDB — Mozilla Firefox](https://github.com/user-attachments/assets/f1d79e8e-2ed8-4ec3-bd0c-ed069e582238)
![2024-09-02 19_15_14-Mozilla Firefox](https://github.com/user-attachments/assets/e6c20c0b-ac31-457d-84f9-7446db915be9)

### Expected behavior

right number and may be type here should be consistent
![2024-09-02 19_31_06-● Leaderboards cs - s box (Workspace) - Visual Studio Code  Administrator](https://github.com/user-attachments/assets/cc076e1a-0033-494a-955d-52eaa3c37f93)
![2024-09-02 19_30_16-Leaderboards cs - s box (Workspace) - Visual Studio Code  Administrator](https://github.com/user-attachments/assets/ff827c14-94e3-4345-a501-3081749fdeb6)

**Comment by handsomematt** [comment]
```json
{"Rank":6,"Value":4.499996662139893,"SteamId":76561198198173471,"CountryCode":"nl","DisplayName":"\u2B50Daiter\u2B50","Timestamp":"2024-09-01T11:22:35.1784959+00:00","Data":null}],"Query":null,"DateDescription":null,"Milliseconds":54}
```

is your browser displaying the large number incorrectly, try looking at the raw json? the steamid is fine

**Comment by MDFL64** [comment]
TIL JSON doesn't specify that numbers *need* to be IEEE 754 doubles. Still seems like you might save a lot of headaches by encoding it as a string instead.

**Comment by DaiterGG** [comment]
> ```json
> {"Rank":6,"Value":4.499996662139893,"SteamId":76561198198173471,"CountryCode":"nl","DisplayName":"\u2B50Daiter\u2B50","Timestamp":"2024-09-01T11:22:35.1784959+00:00","Data":null}],"Query":null,"DateDescription":null,"Milliseconds":54}
> ```
> 
> is your browser displaying the large number incorrectly, try looking at the raw json? the steamid is fine

JSON view in FireFox and any view in Chrome, wasn't expecting that
