### ISSUE TITLE
Game doesn't launch, Leave no logs

### ISSUE THREAD

**Issue by n1ckibreeki** [Facepunch/sbox-issues#6358]
### Describe the bug

# 👋 Hey there,
I got a new laptop two days ago, and today I wanted to try out S&box. However, it turns out that the game doesn’t load at all... When I press the Play button, nothing happens there’s no sight of that the game will boot up

## Issues
It’s not a boot problem because the process is killed within 3 seconds after clicking **Play**
This behavior seems like a crash, but when **I checked the logs folder in the game directory, I found that no logs were created**

## Troubleshoot
I decided to try running the game on my old, ancient ass laptop, I downloaded the game, and it ran without any issues....
I then uninstalled the game on the new laptop and reinstalled it about ten times, but still had no luck

## Research
I checked GitHub for similar issues and found issue #6333 I read through it and tried the suggested solutions but eventually gave up
I also asked for help in the S&box server in the **"#general-dev"** and **"#general"** channels, but unfortunately, I didn't find a solution....

Some people suggested checking the `C:/Windows/System32` or `C:/Windows/SysWOW64` directories for the `steam_api64.dll` file, but I couldn’t find it in either the game directory or the system folder
![image](https://github.com/user-attachments/assets/d073eb4d-7c45-4280-a87b-8f2e767826ff)

# I would really appreciate any help with this issue. I just want to enjoy S&box...
2 Minutes Video is attached, check down below

## Contact
Contact via Discord: nickibreeki#2742
Contact via Twitter: www.twitter.com/@nickibreeki

## Additional Information
- can't run `sbox.exe, benchmark.exe, sbox-server.exe`
- can run `sbox-dev.exe ` (of course it's a tool for making game, it's not associate with sbox.exe until you create new project and launching the project, you can't even open it cuz it is launching sbox.exe and sbox.exe isn't working😿)
- I obtained from the **`Developer Preview`** Not take a copy of the game from the third-party website, If Facepunch Team have an access look-up who's obtained the **`dev-preview`** check my name "nickibreeki", You'll see that I did obtain via website or Looking into my video that i show you guys a downloading process, which you cannot download third-party game via Steam.

## Attemption
- Reinstalled the game on Current Laptop 
- Uninstalled the game on Old Laptop
- Check Steam Update
- Check DotNet Runtime
- Reinstalled DotNet Runtime

## System Information
Current Laptop Specs that can't run/launching S&box
- Processor: AMD Ryzen 7 7435HS
- Graphic Card: NVIDIA GeForce RTX 3050
- Memory: 16 GB

Ancient Ass Laptop Specs that can run/launching S&box for some reason
- Processor: Intel i3 6006u
- Graphic Card: NVIDIA GeForce 940mx
- Memory: 12 GB

# ————————————————————

# To Reproduce
Launching **s&box** via Steam

# Expected behavior
Wanted this to be solve, so I can run the s&box on new laptop....

# Media/Files
## 2 Minutes Long Video, please grab your drink or popcorn while watching this video, the video is shown the full process of trying to solve the problem
- Validating the Game File
- Game Reinstallation

https://github.com/user-attachments/assets/ca241694-543e-49e4-a153-b2a346d2889b

# Additional context
Please don't close the close this "Issue" just yet, let's me read and response to your message!
Because my time zone is GMT+7:00, Thanks you!!

**Comment by Nolankicks** [comment]
Sorry but I don’t believe you have the specs to be able to run the game.

**Comment by n1ckibreeki** [comment]
> Sorry but I don’t believe you have the specs to be able to run the game.

https://github.com/user-attachments/assets/fd147c0b-5bb9-4ec1-bd79-2b63c831cb77

Well, here's the video, of showing `Device Manager` and `System Information` and also running `Counter-Strike: Global Offsensive 2` which is Source 2 same as S&box Engine
The old computer is barely can run the game within' only 3-5 frames per seconds, but the game is at least launched while the current laptop can't launch anything, nothing has appeared...

**Comment by n1ckibreeki** [comment]
# I FUCK AROUND AND FIND OUT,
I've been waiting for a response for two days, and I don't know if you guys have looked into this issue or not. So, I decided to take matters into my own hands. Using my dumb brain, I thought, 'What if we move all the DLL files from the old laptop to the new one?' It turns out it worked with no issues at all.

However, from my perspective, could this be a hardware log issue? Because if the new laptop can't launch the game, why does it work when I move the DLL files from the old laptop?

So strange...

![image](https://github.com/user-attachments/assets/ead8d5d2-8c22-4487-96e1-ffc4ab40ce67)
