### ISSUE TITLE
Upload prefabs game resources scenes etc. to a library files Or S&box killer feature

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#6362]
### For?

S&Box

### What can't you do?

Maybe, someone already asking about this and you have already thought about it. At the moment, we can only load code into libraries, but due to the fact we cannot load prefabs, everything becomes inconvenient because the configuration of something large in our own prefabs will be very complicated. And here the question arises: why not add the ability to upload prefabs game resources scenes etc. to a library, these are just prefabs, they can attract assets from party assets and at the same time they will weigh very little and provide a huge number of opportunities. We can forget about copying projects from GitHub!

### How would you like it to work?

**The above is a small part of the capabilities that downloadable resources can provide, and I will list things that may completely change s&box with the addition of this feature:**

>There will be quick interaction available with downloads of various systems for the game, for example: I need a weapon system >and there is a libraries with a weapon system with attachments, just weapons, mele weapons, for dark souls gamemode or some >kind of RPG, I just download this system which may already have an example of a player model of his movement controller and >several weapons that will immediately be drawn from the asset party and at the same time you won’t need delete files on upload >as you would with a GitHub repository

>We can load not only systems, but also entire game modes and scenes with maps from asset party, which will add the >ability to create custom scenes for other games. I don’t think there’s even a need to explain what potential this has.

>If in Garry's mod or anywhere else we only have control over existing system API, then in the box it will be possible to load >another gamemode on top of everything in project, and instead of interactions everything will work.

### What have you tried?

I know that s&box describes a completely different structure for modifying projects in the FAQ, but it seems to me that uploading such modifications will make the game in S&box much more interesting and there will be much more content in the asset party and more earning opportunities in the future, of course.

### Additional context
What you think about this?

_No response_

**Comment by kEllieGit** [comment]
#5812 and #5522 related.

**Comment by GavrilovNI** [comment]
#5802 related

**Comment by MD485** [comment]
I was also personally thinking about this, let's say you download yourself a Shrimple Character Controller, but you don't know what classes it comes with, which Components to put on a GameObject, which configuration options to turn on, etc.

It would be much shrimpler and much easier if any library could simply come with prefab examples of it's proper use.

I do think there is some UI/Organisational difficulty here, but I prefer a more steamlined and simple development process, and poking through the source code and docs or whatever else is necessary to learn how to properly use a library adds a decent amount of overhead which could be minimized.

Theoretically getting some other issues done in the process of dealing with this would also be a nice bonus.
