### ISSUE TITLE
Add already instancied component to Object using code like  Components.Add

### ISSUE THREAD

**Issue by DoctorWhoFR** [Facepunch/sbox-issues#6367]
### For?

S&Box

### What can't you do?

I want to create a Component of X kind and add already instancied Component classes to a game object

### How would you like it to work?

```
GameObject.Components.Add(<my component>)
```

### What have you tried?

Everything and read the 3 docs ^^' 

### Additional context

![image](https://github.com/user-attachments/assets/ecc822f0-53c0-4cd5-8cc0-a36cb6a62def)

**Comment by MD485** [comment]
This doesn't really make sense to do, Unity doesn't allow it either.
A Component without a GameObject shouldn't exist.
