### ISSUE TITLE
Change the FBX Ascii exporter for Hammer to Binary

### ISSUE THREAD

**Issue by PixelQubed** [Facepunch/sbox-issues#637]
**What can't you do?**
I cant export segments of my map easily without scale and materials messing up in blender. FBX is the only format to my knowlage that imports scale correctly into blender.

**How would you like it to work?**
The easiest way it can. Select the FBX format and it should export in the binary format. I should be able to import the fbx into blender without issue as blender does not support ascii FBX.

**What have you tried?**
Converting the FBX with this old obscure tool linked below.

https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives

**Additional context**
I know the Model Doc FBX Binary Exporter has just been added so I hope it is just a simple copy and paste for you peeps. I would be very greatful if this was changed.

**Comment by aylaylay** [comment]
I don't know what you're asking for. It used to export as ascii, now it's binary, why do you now need ascii?

**Comment by aylaylay** [comment]
It now exports as binary, which is what I think you were asking for.

**Comment by PixelQubed** [comment]
Yes, I appologise for the miscomunication. I shall attempt to make my subsuquent requests more understandable.

**Comment by aylaylay** [comment]
No worries mate

**Comment by aylaylay** [comment]
Please close the issue if it's working fine for you.

**Comment by PixelQubed** [comment]
Works perfectly, thanks.
