### ISSUE TITLE
Component accessor methods should only return Valid components

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6370]
### What it is?

Currently, component accessor methods null check a component before returning. This leads to components returning that are not valid - they have been destroyed already. I can't think of a scenario where I want a destroyed component. This result is also a very high vector for unintended behaviour or errors in games.

### What should it be?

Replace the null checks with IsValid() checks. This method null checks and ensures they are valid for use.

**Comment by aylaylay** [comment]
I've gone through all the base code and made sure everything is using IsValid
