### ISSUE TITLE
Missing Aggregation (Highest)

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#6373]
### For?

S&Box

### What can't you do?

setting the Aggregation from a Leaderboard to Highest

### How would you like it to work?

public void SetAggregationHighest()
        {
            ((LeaderboardQuery)(ref query)).Aggregation = (AggregationType)5;
        }

### What have you tried?

tested out every Aggregation but , some doesent even exist in the sbox. website

**Comment by garrynewman** [comment]
Isn't this AggregationType.Max?

**Comment by EternalDawn1** [comment]
> Isn't this AggregationType.Max?

This is Max
![Aggregation max](https://github.com/user-attachments/assets/0db2e8b6-f8b8-4892-8984-d5291e9ebd2d)
![highest != max ](https://github.com/user-attachments/assets/8110a26f-1d75-42e3-b921-4480eb45f3b1)


This is sum 
![Aggregation sum](https://github.com/user-attachments/assets/022c03a2-b272-45c8-9d98-720bf749d8dd)
![sum = sum](https://github.com/user-attachments/assets/17fd3a6b-032b-4203-beac-b6c522ed49e8)


No, Max is completly different , sum is working fine , but highest is not max , those are different things

**Comment by EternalDawn1** [comment]
I tested out the other aggregations but nothing seems like max .. some aggregations even gave other numbers than on the website

**Comment by garrynewman** [comment]
There's a builder on the website now, which should help you create a leaderboard query.
