### ISSUE TITLE
CameraComponent clip planes

### ISSUE THREAD

**Issue by Manonox** [Facepunch/sbox-issues#6374]
### For?

S&Box

### What can't you do?

- Seamless(?) portals using `CameraComponent.RenderToTexture` (they will work, but objects behind the "exit" portal will render infront of the desired geometry)
- Maybe mirrors

### How would you like it to work?

World(or local) space clip planes for cameras, would be cool to be able to override the projection matrix of the camera too (for other reasons)

### What have you tried?

I think there were ScenePortals or something like that, was looking for anything clip plane/oblique projection/custom camera projection matrix related the whole evening

### Additional context

Old issue, talking about ScenePortals being buggy or something like that - https://github.com/Facepunch/sbox-issues/issues/2264
There are clip planes mentioned in the code (PortalDoor.cs)

**Comment by Gmod4phun** [comment]
I dont believe ScenePortals are a thing anymore, but in case you want to try some experiments, you can set clip planes per sceneobject. Sadly they have their own issues, but are at least usable.

**Comment by Manonox** [comment]
@Gmod4phun,
> I dont believe ScenePortals are a thing anymore

Yeah, they are gone, there's a commit about removing them
Setting clip planes for all SceneObjects before rendering the portal camera view seems very fooky

**Comment by chrisspieler** [comment]
I think you might be able to set the clip plane for the SceneCamera itself like:
```cs
_sceneCamera.Attributes.Set( "ClipPlane0", new Vector4( clipPlane.Normal, clipPlane.Distance ) );
```

**Comment by aylaylay** [comment]
> I think you might be able to set the clip plane for the SceneCamera itself like:
> 
> ```cs
> _sceneCamera.Attributes.Set( "ClipPlane0", new Vector4( clipPlane.Normal, clipPlane.Distance ) );
> ```

This needs a little engine change to work. I did get it working recently but it had issues with shadows not showing up.

https://github.com/user-attachments/assets/e550e310-f76a-4209-bd1c-008344d66047

**Comment by Manonox** [comment]
So, oblique projection/rotated near plane? When rotating the near plane you also need to rotate the far plane so it doesn't break depth; I still don't know if that's the best method for portals, probably fucks with shadows too

**Comment by Manonox** [comment]
For anyone looking for portal thingies:
Thanks, garry ([Garry: Add CameraComponent.CustomProjectionMatrix](https://commits.facepunch.com/496945))
Clip planes are still wip, ig, can keep this open for now

**Comment by aylaylay** [comment]
I don't think CustomProjectionMatrix would have any effect yet. It overrides the frustum projection but we're not using that frustum to render by the looks of it

**Comment by Manonox** [comment]
Yeah, just tested that, doesn't do anything :')

**Comment by aylaylay** [comment]
I'll see what I can do

**Comment by aylaylay** [comment]
Yeah this all needs to be unfucked, we have a frustum on the C# side but then the renderer is creating its own.

I couldn't get oblique projections to work anyway, reverse Z might be fucking us.

**Comment by Manonox** [comment]
Maths are fucky, but I don't think reverse Z locks us out of anything, not sure

**Comment by aylaylay** [comment]
Added with CameraComponent.CalculateObliqueMatrix fed into CustomProjectionMatrix
