### ISSUE TITLE
Can't open the game

### ISSUE THREAD

**Issue by alomeme** [Facepunch/sbox-issues#6377]
### Describe the bug

When I try to open the game, it doesn’t load. It only shows a black screen for a few seconds and then closes

### To Reproduce

1. Open the game
2. That's it

### Expected behavior

The game should be opening, but it only shows a black screen for a few seconds and then closes.

### Media/Files

[Log.log](https://github.com/user-attachments/files/16923089/Log.log)

### Additional context

I'm running in Windows 10 Pro 64-bit Build 19045 (Pirated), CPU: Ryzen 5 3600, RAM: 24576 MB (24GB), GPU: GTX 1650 Super

**Comment by handsomematt** [comment]
update or uninstall fpsmon & rtss

**Comment by alomeme** [comment]
Thanks that fixed it
