### ISSUE TITLE
[ModelDoc] Multiple mesh parts with OBJ dont work properly

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6379]
### Describe the bug

When using an OBJ file that has multiple meshes, all of the imported mesh parts are named the same (it uses the file name), with an added number suffix. Instead, it should use the actual name of the mesh part that is present in the OBJ file itself, like FBX does.

One of the meshes (I believe the first one) gets replaced with a bulk of all of the meshes combined, so that mesh cannot be selected to be individually rendered.

### To Reproduce

1. Make a model out of an OBJ source file that has multiple meshes
2. Notice that the meshes dont have the names they should have
3. First mesh will become a big mess (all the meshes will combine into one)

### Expected behavior

Mesh parts should be named according to how they are named inside of the OBJ file, and th e first mesh should work properly.

### Media/Files

Sample OBJ file
[door_single.zip](https://github.com/user-attachments/files/16923462/door_single.zip)

OBJ Mesh:
![image](https://github.com/user-attachments/assets/7d1e6d80-f203-4444-a711-01dbc9210d2a)

Same meshes, exported as FBX:
![image](https://github.com/user-attachments/assets/c0b8b2b5-2228-4f99-b7e0-fe9d6462314d)

**Comment by aylaylay** [comment]
![sbox-dev_Lop14DzL3V](https://github.com/user-attachments/assets/136b4a89-e272-4b2b-bb05-3d2342f16892)

Fixed
