### ISSUE TITLE
Toggle rigidbody creation for props

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#6388]
### For?

S&Box

### What can't you do?

When I drag some models into my scene and hit play, they all have physics and will fall out of the sky. I want to be able to toggle this so I can mindlessly place assets I want to be static without needing to remove the rigidbody or mark it static each time.

### How would you like it to work?

a button or setting.In the asset browser to toggle creating a prop when dragging something into the scene.

### What have you tried?

manually removing the rigidbody or marking it as static per object, which doesn't seem to support multi edit and is really annoying.

**Comment by aylaylay** [comment]
Wonder if this would be good use of model metadata

**Comment by aylaylay** [comment]
Models will be dropped as a static prop now based on if you set it to static prop in modeldoc

![Image](https://github.com/user-attachments/assets/3fe839d0-fa7b-4d20-a775-36ef33a38a94)
