### ISSUE TITLE
point_template's ForceSpawn is not functional in Hammer

### ISSUE THREAD

**Issue by alexavil** [Facepunch/sbox-issues#639]
**Describe the bug**
When trying to fire ForceSpawn on a `point_template` via a trigger, the template specified does not spawn.

**To Reproduce**

1. Create a brush trigger (like `trigger_once` or `trigger_multiple`), a `point_template` and a template.
2. Specify the template in `point_template`'s settings.
3. Fire a ForceSpawn on a `point_template` via the trigger.
4. Observe

**Expected behavior**
The template spawns.

**Screenshots**
Hammer view. In this map, the player touches a trigger upon start. `point_template` here is called `crate_spawner` and it should spawn a `prop_physics` named `crate`.

![изображение](https://user-images.githubusercontent.com/32246131/128738768-7a17d14d-53c8-41c2-ae1d-2f67e467d429.png)

Trigger output.

![изображение](https://user-images.githubusercontent.com/32246131/128737898-f1142107-bf89-400a-ad14-26bd10e31ea3.png)

In-game view. The crate didn't spawn, despite the player being in the trigger area.

![изображение](https://user-images.githubusercontent.com/32246131/128739204-7d56776e-30de-4b47-98f8-21dd5eb67ad7.png)

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/55

**Comment by alexavil** [comment]
No longer relevant.
