### ISSUE TITLE
Particle Playback Controls

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#6390]
### For?

S&Box

### What can't you do?

In the new component particle editor it's quite common for particles with multiple elements to get out of sync, especially when adjusting lifetimes and durations.

It can also be quite unclear where a particle's sequence starts and stops.

### How would you like it to work?

In Unity there's a widget with playback controls, something like this could work well I think.

![357568127-0d84ecb2-21d7-4b33-ab2d-5b56b3e14693](https://github.com/user-attachments/assets/150a06fd-ddbb-4e34-83e9-d11b0a809fba)

In the legacy particle editor there's also these controls:
![image](https://github.com/user-attachments/assets/76d7156a-5d3b-4f2e-9dfa-05e8b688532b)

### What have you tried?

I have tried closing and re-opening the prefab that I'm working in which will sync the particles back up together.

**Comment by aylaylay** [comment]
Are these playback controls purely an editor thing or serialized and effect in game too?

**Comment by Jammie3d** [comment]
Just for the editor

**Comment by aylaylay** [comment]
Fab, I'll see what I can do

**Comment by aylaylay** [comment]
I didn't add stop, seemed a bit pointless, but there's play, pause, restart.

https://github.com/user-attachments/assets/944461f4-6789-4aac-b28a-ff15cabbd721

**Comment by Jammie3d** [comment]
Awesome, thank you!

When in a prefab it looks like Particle Count can be exposed as a variable, is that intentional?
![image](https://github.com/user-attachments/assets/b6756be7-7e0a-4498-87d5-ffee53ce02df)

**Comment by aylaylay** [comment]
Fixed

**Comment by Jammie3d** [comment]
Sweet, thanks!
