### ISSUE TITLE
Add `[Change]` attribute overload that accepts delegate (instead of method name as a string) and if possible picks up the oldValue and newValue's type from the propperty it is applied to

### ISSUE THREAD

**Issue by mmjr-x** [Facepunch/sbox-issues#6397]
### For?

S&Box

### What can't you do?

At the moment the usage of the `[Change]` attribute and the method that it calls is not type check-able by intellisense.
At the moment a property with a `[Change]` attribute with no specified method does mark the autogenned OnSomePropertyNameChanged method as used (and thus you get a `.. member 'SomeClass.OnSomePropertyNameChanged' is unused` warning.
At the moment refactoring of a property with a `[Change]` attribute with no specified method does not update its OnSomePropertyNameChanged method's name.

### How would you like it to work?

```c#
[Property, Change( (oldValue, newValue) => { ... } )] public SomeType SomeProperty { get; set; }
```
and/or
```c#
[Property, Change(someOnChangedMethod)] public SomeType SomeProperty { get; set; }

private void someOnChangedMethod(SomeType oldValue, SomeType newValue) {
...
}
```

### What have you tried?

Just using the the name of the method in the attribute `Change(nameof(someOnChangedMethod))` works fine however for the above mentioned reason's I would rather use a delegate.

Just using an explicit setter implementation, however this seems less clean that using the `[Change]` attribute.

### Additional context

I read that this might not be possible without an explicit cast of the delegate [until c#10](https://stackoverflow.com/questions/31473865/implicitly-convert-method-group-to-delegate-for-argument-of-control-invoke), if this is true it kind of defeats the purpose. However it might still be nice to have the option to pass a delegate. In any case I am interested in the opinion's of the dev's on this subject. :)

**Comment by kurozael** [comment]
This isn't possible, that's why it is the way it is, sorry. I don't see this ever being possible because attribute parameters must be compile-time constants.

**Comment by mmjr-x** [comment]
Ah no problem and thanks for taking the time to respond! :)
