### ISSUE TITLE
Graphics.DrawModelInstanced causing consistent lag spikes

### ISSUE THREAD

**Issue by stellawisps** [Facepunch/sbox-issues#6398]
### Describe the bug

When Graphics.DrawModelInstanced is used, there will be fairly consistent lagspikes with the game freezing. The issue becomes worse the more instances are drawn.

### To Reproduce

1. create a custom scene object and use Graphics.DrawModelInstanced to draw a lot of triangles (approx 500K is when the issue starts in my experience)
2. witness lag spikes

### Expected behavior

There should be no lagspikes

### Media/Files

https://github.com/user-attachments/assets/ce32544c-9e66-45a4-b248-3067da2ec6af

In this video you can see the lagspikes in the performance viewer, once I comment out Graphics.DrawModelInstanced they stop. I have replicated this over 3 seperate projects.

**Comment by handsomematt** [comment]
How are you calling it? Allocating a new transforms array each time? How many instances? Triangles is irrelevant
