### ISSUE TITLE
Having windows think there are more than 4 gamepads connected crashes s&box on startup

### ISSUE THREAD

**Issue by agincel** [Facepunch/sbox-issues#6399]
### Describe the bug

To play certain GameCube and Steam games, I use a Mayflash adapter which Windows interprets as 4 distinct controllers. Plugging in an XInput controller as well results in s&box crashing upon startup, when loading the menu scene.

If I wait to connect the XInput controller (the 5th controller) until after launch, there's no crash, but the controller doesn't work.

### To Reproduce

1. Connect https://www.amazon.com/Mayflash-GameCube-Controller-Adapter-Switch/dp/B00RSXRLUE or a similar controller adapter (or just any four gamepad controllers windows recognizes) into your machine.
2. Connect a 5th controller.
3. Boot s&box in play mode.
4. Observe it crash shortly after launch - right around the time it tries to load the menu scene.

Additionally
1. Launch s&box 4 controllers (or aforementioned adapter) connected. Observe no crash.
2. Connect a 5th controller.
3. Observe that it doesn't work with any game. This may be intended/expected.

### Expected behavior

At a minimum, s&box should not crash if >4 controllers are connected on startup. Ideally, whatever controller is being used should be the one games interpret, or it should be possible to specify what gamepad you're using.

### Media/Files

[Log.415.log](https://github.com/user-attachments/files/16958835/Log.415.log)

**Comment by DevulTj** [comment]
This shouldn't be a problem anymore
