### ISSUE TITLE
Steam Input support

### ISSUE THREAD

**Issue by xenonnsmb** [Facepunch/sbox-issues#64]
**What can't you do?**
Play s&box with a controller

**How would you like it to work?**
Using [the Steam Input API](https://partner.steamgames.com/doc/features/steam_controller) for S&box's controller support would be a good way to implement it, allowing users to benefit from universal support for PS4/PS5/Switch/Xbox/Steam controllers and easy button remapping, and exposing the Steam Input button prompts to gamemode developers as a UI element would allow easy creation of console-style UI for gamemodes. I think Source 2 already has some Steam Input stuff built-in, but I don't know if it would be better to use that or reimplement it in C#.

**Comment by garrynewman** [comment]
We already have controller support.
