### ISSUE TITLE
s&box crash when trying to load a map

### ISSUE THREAD

**Issue by Sherlock2004** [Facepunch/sbox-issues#640]
**Describe the bug**

I caught an incomprehensible bug. I compile the most noticeable map, it runs in s&box and the engine immediately crashes without any errors.

**To Reproduce**

I am attaching the vmap, map and dump. Just compile this map to fast or any other way.
[disp_test.zip](https://github.com/Facepunch/sbox-issues/files/6955941/disp_test.zip)

**Comment by DoctorGurke** [comment]
Update your game and try again. There was a crash issue for a bit earlier that got fixed a minute ago.

**Comment by aylaylay** [comment]
This was due to a recent VR related commit. It should be fixed when the build hits steam.

**Comment by Sherlock2004** [comment]
> This was due to a recent VR related commit. It should be fixed when the build hits steam.

No, unfortunately this is happening with the latest update. 😥

**Comment by deadmonstor** [comment]
Make sure you restart steam to see it sometimes it breaks

**Comment by Sherlock2004** [comment]
> Make sure you restart steam to see it sometimes it breaks

Oh, you're right. Indeed, after restarting steam downloaded another update and the problem was gone! Thanks. 😎
