### ISSUE TITLE
Set the projection matrix of a camera

### ISSUE THREAD

**Issue by dotryen** [Facepunch/sbox-issues#6400]
### For?

S&Box

### What can't you do?

I am unable to set the projection matrix of a camera. This could let us do more advanced effects like oblique projections and planar reflections.

### How would you like it to work?

A property on `CameraComponent` or `SceneCamera` would work perfectly. Probably named `ProjectionMatrix`.

### What have you tried?

I have thought about making a shader to override projection but this wouldn't work in a lot of situations. (In my case, planar reflections)

**Comment by FlooferLand** [comment]
Garry did reply to a discussion thread related to custom projection matrixes over at https://github.com/Facepunch/sbox-issues/discussions/960 all the way back in 2021, might be related.
I'm not sure if anything came out of it though, can't check rn

**Comment by garrynewman** [comment]
I added CustomProjectionMatrix to the camera

**Comment by garrynewman** [comment]
Saw @aylaylay say what I added actually does nothing so gonna look into making it do something
