### ISSUE TITLE
[Shadergraph] Setting normals breaks preview on everything but the sphere

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6402]
### Describe the bug

The shadergraph preview breaks when you set a normal to something, like a texture or a float3 input. However, for some reason, the preview works on the default in-shadergraph sphere, but nothing else.

### To Reproduce

1. Open shadergraph and set something as the normal input
2. Switch between the preview models and see that only the sphere will render correctly

### Expected behavior

Should render correctly on any model.

### Media/Files

https://github.com/user-attachments/assets/a871f9f6-3462-4d90-9c84-fef3880d0a0c

**Comment by Jammie3d** [comment]
I'm getting this too when using Fresnel, Repro project here: [fresnel.zip](https://github.com/user-attachments/files/17483510/fresnel.zip)


Open up shaders/fresnel.shdrgrph and compare to scenes/minimal.scene

Shadergraph Preview
![Image](https://github.com/user-attachments/assets/54e720b2-33f2-4dea-94b4-b7a609bb1b97)
Editor Viewport
![Image](https://github.com/user-attachments/assets/4c5d349b-5c12-4975-920f-5dacb4b31cc5)

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by Jammie3d** [comment]
Seems good to me, thanks!
