### ISSUE TITLE
Change attribute triggers when you open a scene in editor

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6406]
### Describe the bug

The Change attribute fires the callback when you open a scene in editor (edit time, not sure about runtime)

### To Reproduce

1. Make a component with the Change attribute on it
2. Add that component to a GameObject in the Scene
3. Reload the scene and notice the Change event fires

```cs
public class Example : Component
{
	[Change(nameof(Change_example))] public bool example { get; set; }

	void Change_example(bool oldValue, bool newValue)
	{
		Log.Info($"Example::Change_example() oldValue: {oldValue}, newValue: {newValue}");
	}
}
```

### Expected behavior

I expect the Change attribute to not fire it's callback from loading a scene at edit or runtime.

### Additional context

My use case is I have the change callback tied to a method that randomises based on the input.
This means if it's triggered by scene load at edit or runtime, I can't use it as I don't want it re-running by just loading the scene.

**Comment by kurozael** [comment]
Maybe change callbacks shouldn't be invoked in an editor scene at all?

**Comment by Coomzy** [comment]
It's super useful to have in an editor scene, but maybe it should be split out into it's own attribute if this is used for console/networking things?

**Comment by kurozael** [comment]
We should be good now - let me know if you have any other problems! :)

**Comment by kurozael** [comment]
Huh, I wasn't getting it with your repro, are you sure Steam build updated properly?

**Comment by Coomzy** [comment]
Steam said it was up to date, is there any way to check a build version?

**Comment by Coomzy** [comment]
Restarted again and got another update that fixed it. Sorry about that, guess I was getting an old update
