### ISSUE TITLE
NRE on Editor.SceneViewWidget Breaking Transform gizmo

### ISSUE THREAD

**Issue by IMCraytex** [Facepunch/sbox-issues#6413]
### Describe the bug

Essentially when disabling a game object from a loaded hammer map you will get an NRE breaking the transform gizmo eventually leading it to disappear. The only way to fix this is to fully restart the editor

### To Reproduce

1. Load a hammer map into your scene
2. Find a child object of that hammer map and disable it
3. You will get your NRE errors and will break your gizmo

### Expected behavior

We shouldn't get an NRE upon doing what was described above

### Media/Files

Before : 
![image](https://github.com/user-attachments/assets/14a5f6dd-5029-400c-addc-1c469ac0bce7)
After :
![image](https://github.com/user-attachments/assets/a67212b2-fefe-41cc-9f98-67b3f533bfd6)

**Comment by garrynewman** [comment]
Should be good now
