### ISSUE TITLE
Using an Extension Method within a Library it compiles but fails compile when you go to publish

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6414]
### Describe the bug

If you use an extension method that you created in a library within the library, it will compile fine locally, but when you go to publish it will fail the pre-publish compile check.

### To Reproduce

1. Create a library
2. Add an extension method in the library
3. Use the extension method in the library
4. Notice it compiles fine
5. Try to publish and notice the compile fails

```cs
// All of this is within a library
public static class MyExtensionMethod
{
	public static void PrintToLog(this GameObject gameObject)
	{
		Log.Info($"gameObject: {gameObject}");
	}
}

public class MyComponent : Component
{
	protected override void OnStart()
	{
		GameObject.PrintToLog();
	}
}
```

### Expected behavior

I expect to be able to make and use extension methods within a library and publish that

**Comment by kEllieGit** [comment]
Is this whats causing [6410](https://github.com/Facepunch/sbox-issues/issues/6410)?
Great catch, I would have had no idea how to debug this in my code base, haha.

**Comment by Coomzy** [comment]
Seems like it could be, the compiling window for libraries is really difficult to read and I can't scroll on it.

**Comment by kEllieGit** [comment]
I tested it by removing my extension methods and yes, this is what is causing #6410. Heck!
