### ISSUE TITLE
Edge selection in scene does not align with visuals

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#6416]
### Describe the bug

When hovering over the edge of a mesh in scene, I can't click on it. I have to click far above it to actually select the edge

### To Reproduce

place a plane mesh in the scene and attempt to select an edge

### Expected behavior

the edge you hover over should be selected

### Media/Files

https://github.com/user-attachments/assets/78bb8557-ba20-4a45-bcce-521e633c03f2

**Comment by aylaylay** [comment]
Fixed?
