### ISSUE TITLE
Some AnimationGraph paramaters doesnt work in a loaded game

### ISSUE THREAD

**Issue by DoctorWhoFR** [Facepunch/sbox-issues#6417]
### Describe the bug

After the new update by Laylad with the skinned model paramaters i achieved to debug one of the first "bug" i found in s&box.

When using animation_graph, and in exemple the citizen graph we can see that their some parameters called "ik"
![image](https://github.com/user-attachments/assets/df27b0ee-a023-4837-8e00-8be372f11665)

this things seem to only work directly in anim-graph not in game.

But after some try i found that renaming the paramater by replacing every dot by _ made the things work everywhere.
Idk if their is a particular problem with "dot" and boolean parameter.

### To Reproduce

https://github.com/user-attachments/assets/550c379b-510a-42bc-97ed-a705b237520a

### Expected behavior

For me everything work when changing with "_" but changing it everytime make it impossible to follow the versionning and update of the citizen graph.

Maybe can you just found if this is a bug or something special with naming convention to do and so update the doc concerning this naming part.

**Comment by DoctorWhoFR** [comment]
also dont work using api

**Comment by aylaylay** [comment]
They work but animation helper is controlling them. The params in inspector are meant to just debug for now, so they don't act like overrides. This could change in the future.
