### ISSUE TITLE
De-clutter Object and Component creation menu

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6428]
### For?

S&Box

### What can't you do?

The "issue" is applicable both to gameobject menu and component menu, and for sake of not going insane I will be mentioning only one, implying both.

![image](https://github.com/user-attachments/assets/978b6d60-d74e-4e14-b1fb-85b08b6d776f)

Currently every template gameobject goes into the same menu, custom new ones live alongside facepunch's default ones. That is not a problem only in a very few circumstances, where there is not a lot of custom objects. But as soon as the project size grows, and you start having a lot of custom things, and/or your custom things inherit and build on top of inaccessible default components, suddenly there comes a problem of either not needing "the original" objects or there becoming too much of them in the same menu (you also can't do subcategories for components, which makes this worse).

### How would you like it to work?

I am aware that the current state of being is just how Unity does it, but that does not mean things must now suck forever.

Instead, to help alleviate this problem at least somewhat, both menus could be automatically sorted by the project/library they come from, like the current "projects" tab in asset-browser.
![image](https://github.com/user-attachments/assets/2a006300-c530-426e-912e-e5d72c6f622b)
![gameobjectmenu](https://github.com/user-attachments/assets/09b3b92e-e675-412e-b227-353d1aae383c)

### What have you tried?

Crying and not having billion objects. Not possible.

**Comment by LVJohnFreeman** [comment]
Would love either just doing this or outright hiding base components and game objects completely. Love doing my own thing and having my workspace only have stuff I need for my project, as it currently stands it bloats up really quickly and I think we could have it better. Don't think it has to be forced either, think for people who can go by making their games inside S&box you can go by with what you have for the most part, but say long term for standalone especially I'd really want to have the freedom to decide what I need and thus make my own dev environment, how I want it to be. Having just this thing, would already save of my time, personally  speaking.
