### ISSUE TITLE
Add rotation to Trail/Line renderer

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6430]
### For?

S&Box

### What can't you do?

With Trail Renderer and Line Renderer, you are able to have a fixed width only and it always faces the camera.

![image](https://github.com/user-attachments/assets/702648d8-0dd4-454c-a222-66038783a50f)

### How would you like it to work?

Would be nice to have multiple rotation options, one for facing the camera (default), and one for facing a given rotation at the given point.

### What have you tried?

For example, here we have a sword swing, I had to use a combination of dot products and cross products to change the width of the trail with mixed results. Would be much easier to just use the sword's rotation together with the sword's position.

https://github.com/user-attachments/assets/899df9af-4e90-4256-b698-e60aee60edfb

**Comment by aylaylay** [comment]
For line renderer

https://github.com/user-attachments/assets/d408fc25-7eca-484f-acca-b58d86e1ab24

**Comment by yuberee** [comment]
Getting this when I have more than two gameobjects for the line:

```Exception when calling 'OnPreRender' on LineRenderer on (Object)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Sandbox.LineRenderer.OnPreRender() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Render\LineRenderer.cs:line 163
   at Sandbox.Component.ExceptionWrap(String name, Action a) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Component.cs:line 322
```

**Comment by aylaylay** [comment]
Wasn't happening for me but should hopefully be fixed now

**Comment by yuberee** [comment]
Yep it works now, I actually think I'll switch to Line Renderer for my swords rather than Trail Renderer, the spline functionality is good.
Plus it can wiggle:

![92a4ce6c0bfeab6085ebce96d80f681e](https://github.com/user-attachments/assets/5a33351d-c5b7-4cb5-a66e-0817cb62e130)

**Comment by aylaylay** [comment]
We should add this for trail renderer now it's proven it's useful for line renderer?

**Comment by aylaylay** [comment]
Added to trail renderer too

**Comment by yuberee** [comment]
Thanks!
