### ISSUE TITLE
[REGRESSION] GameTask.Delay and DelaySeconds get stuck and never resolve

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6431]
### Describe the bug

After [garry's recent commit](https://discord.com/channels/833983068468936704/835035328779518023/1284434843626635304), GameTask.Delay and DelaySeconds now just hang the async method. DelayRealtime and DelayRealtimeSeconds work as expected. 

Also happens to Task

### To Reproduce

Throw this component anywhere on a blank project

```cs
public sealed class MyComponent : Component
{
	[Property] public string StringProperty { get; set; }

	protected override void OnStart()
	{
		base.OnStart();

		_ = MyMethod();
	}

	private async Task MyMethod()
	{
		Log.Info("test");
		await GameTask.DelaySeconds(1);
		Log.Info("test 1 second later");
	}
}
```

test 1 second later does not get called

### Expected behavior

Delay and DelaySeconds should work

**Comment by trundlr** [comment]
@garrynewman

**Comment by garrynewman** [comment]
Reverted

**Comment by Gmod4phun** [comment]
Stuff seems to work again

**Comment by trundlr** [comment]
Thanks for the fix!
