### ISSUE TITLE
Vulkan Device Lost when opening project

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6432]
### Describe the bug

Whenever I try to open a particular project in the editor, I get the Vulkan Device Lost error. Another project launches without any issue.

![Screenshot 2024-09-14 075114](https://github.com/user-attachments/assets/dc732346-3f7d-46c8-b11c-e6899a6e029e)

Prior to the project being unable to launch, I was doing terrain painting. While painting with the terrain in slot 3, I noticed nearby terrain rapidly oscillating between terrain slots 0 and 1 in a glitchy pattern. I saved my project and reopened it in an attempt to maybe bring the terrain back in to a useable state, and that's when I started receiving this error.

I am using an RTX 3080 with driver version 552.44.

### To Reproduce

1. Open the attached project
2. Open main_menu.scene
3. See the Vulkan Device Lost error

### Expected behavior

The projects launches without an error.

### Media/Files

[smooth.zip](https://github.com/user-attachments/files/17002672/smooth.zip)

### Additional context

I can work around the issue by manually removing the Terrain GameObject from the main_menu.scene JSON and deleting the main_menu.scene_c

**Comment by MrBrax** [comment]
#6041

**Comment by Araxyllis** [comment]
Happens to me on any completly new project file. It opens once on first generation, but is unable to load again afterwards.

**Comment by handsomematt** [comment]
I refactored this a ton so it's not doing things in a stupid order anymore, the project no longer crashes for me - can you verify @chrisspieler

**Comment by chrisspieler** [comment]
Just checked, and I no longer get the error. Thanks!
