### ISSUE TITLE
VR Resolution seems to be tied to game launch resolution

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#644]
**Describe the bug**
In-game resolution in VR headset seems to be tied to the resolution that the game is launched at. Resizing the window does not affect the resolution in-headset, nor does setting the resolution in SteamVR's settings.

**To Reproduce**

1. Set the launch options for s&box to `-vr -windowed -w 800 -h 600`
2. Launch s&box
3. Enter a gamemode (I tested in Sandbox VR)
4. See low resolution. You can also try this with `-vr -windowed -w 1919 -h 1079` (each one pixel below my monitor's full resolution to stay in windowed mode) and see the increase in resolution in the headset.

**Expected behavior**
Resolution should be independent of the game window on the monitor, and should instead be set automatically by in-game performance, or by SteamVR's resolution settings.

**Screenshots**
The additional feed in the top-right corner is a view directly (ish, I cropped it in OBS) from SteamVR.
The first game launch was in 800x600, second launch was in 1919x1079
https://www.youtube.com/watch?v=KLiXl5RMUhk

**Additional context**

I'm using an Oculus Quest in the video, but this also affects the HTC Vive.
I also noticed some weirdness with the game window's VR view on the monitor. It seems to be tied to the game window's size/aspect ratio and has some weird "squishing," as can be seen in the video, instead of just cropping the view of the left or right eye, as seen in other VR games. This also affects the viewport of the game in the console, though I did a shit job of showing that by covering it with the feed from SteamVR.

**Comment by samzanemesis** [comment]
Can you verify this is fixed? Possibly include a renderdoc capture, I can't replicate this anymore

**Comment by walllable** [comment]
Tested at 800x600 again, this still seems to be an issue. I'll grab a renderdoc capture

**Comment by walllable** [comment]
Here's the captures. The four I included are one at 800x600, one from the 800x600 window getting maximized, one at 1919x1079, and one with the 1919x1079 window after getting resized to be smaller
These are pretty big so I uploaded them to Drive instead of here
https://drive.google.com/drive/folders/1M3tcFnyPTvF_J1IKWYKuv0e--7g_5q3t?usp=sharing

**Comment by handsomematt** [comment]
Should be fixed now.

**Comment by walllable** [comment]
Yep, fixed. There are still a few resolution-based issues, but I'll open separate issues for those.
