### ISSUE TITLE
collision of 2 objects persists after tags changes(that changes collision rule) while objects stay in each others bounds

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#6441]
### Describe the bug

collision of 2 objects persists after tags changes(that changes collision rule) while objects stay in each others bounds

### To Reproduce

add collsion rule to not collide for tag A and tab B

create 2 cubes, give them box collider and rigidbody,
add tag A to cube 1 and tag B to cube 2
rotate them so they are not aligned with axes
put them close together, so theirs bounds intersects

run scene

now they should not collide (move into each other to see)
then
remove tag B from cube 2
move cube 2 inside cube 1 (there is still no collision when it should collide)

and only after moving cube B to make that their bounds dont intersects
they will collide

### Expected behavior

collision updates imidiatly when tags are changed

**Comment by aylaylay** [comment]
Where's the repro?

**Comment by GavrilovNI** [comment]
> Where's the repro?

You want me make a scene with 2 cubes?😁
I'll make it for you and will also do a video if you want, but tomorrow

**Comment by aylaylay** [comment]
```
add collsion rule to not collide for tag A and tab B

create 2 cubes, give them box collider and rigidbody,
add tag A to cube 1 and tag B to cube 2
rotate them so they are not aligned with axes
put them close together, so theirs bounds intersects
```

A project that does this

**Comment by GavrilovNI** [comment]
[collisiontest.zip](https://github.com/user-attachments/files/17029633/collisiontest.zip)

https://github.com/user-attachments/assets/080e5aff-3b2d-4a54-92c6-6ab7b18dbe01

Also I found out that it only works if collision rule is set to trigger, sorry for misinformation

**Comment by aylaylay** [comment]
Thanks for the repro. When changing tags I'm refreshing the contacts, I'll see if I can refresh the proxy bounds too which should fix this.

**Comment by aylaylay** [comment]
Oh it's because it's trigger, I might not be refreshing contacts for triggers

**Comment by aylaylay** [comment]
Should be fixed now
