### ISSUE TITLE
Physics simulation tool in the scene editor

### ISSUE THREAD

**Issue by brookination** [Facepunch/sbox-issues#6442]
### For?

S&Box

### What can't you do?

I would like to simulate physics objects in the scene editor like you can do in Hammer.

### How would you like it to work?

I would like to have a button or something that simulates the physics object. I can stop it when it's done, and the transforms post-physics simulation are applied.

### What have you tried?

I have tried placing the object where I think it should go, and playing the scene and then copying the transforms of the object after it did what I wanted it to do. They're both a bit time consuming, and the second option is even more so when you're editing a prefab.

**Comment by LVJohnFreeman** [comment]
Since Source 2 Hammer had this for props and ragdolls, I don't see why we shouldn't have this in Scene since we ultimately want to preserve good features like that. Defn want this myself too, it's a nice way to quickly add variation to prop placement that feels natural.

**Comment by aylaylay** [comment]
We for sure should have it, I just need to come up with a nice implementation for it

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/3a259842-7288-48f9-9b0c-6650317c2e51
