### ISSUE TITLE
Make `Scene.AddLoadingTask()` public.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#6444]
### For?

S&Box

### What can't you do?

In my library, my backend doesn't always respond in time for `Component.OnStart`, so I added [`WaitForLoad()`](https://github.com/s8bux/sbux-api/blob/0af80200940a83d35565ef976e3bba913f4b5183/Code/Monetization.cs#L51) to let users await it manually after the fact. 

`Component.OnLoad()` allows me to do this automatically. It ensures the backend responds before `Component.OnStart` is called. That way users don't need to await anything.

https://github.com/user-attachments/assets/ed5c6944-60d3-4eec-8ffc-58ab19f02d94

It's super useful but it only supports components. I'm trying to avoid making the user create any unnecessary components when a GameObjectSystem works just as well across every scene and doesn't require setup.

### How would you like it to work?

Make `Scene.AddLoadingTask()` public. It would make it possible to add loading tasks anywhere. Like for example a GameObjectSystem. I imagine that could be useful.

### What have you tried?

 From testing (using reflection in editor) it works just like how you'd expect.
# [project.zip](https://github.com/user-attachments/files/17018957/bug_tests.zip)

https://github.com/user-attachments/assets/fedc556f-2924-45be-bec6-84dc8db355eb

**Comment by DrakeFruit** [comment]
no way you used that texture in your repro

**Comment by garrynewman** [comment]
Should be able to use ISceneLoadingEvents.OnLoad for this now

![image](https://github.com/user-attachments/assets/adfc382e-3e80-4957-819e-008f7dcd8715)

**Comment by badandbest** [comment]
This is much better than what I could have hoped for. 😃

I do have one issue though. AfterLoad doesn't have brackets so I'm required to implement it. If you could fix that you can close this issue as completed.

**Comment by badandbest** [comment]
Looks like OnLoad is fired every time a scene preview is loaded.

https://github.com/user-attachments/assets/581cebff-d318-47ed-bc6d-6ec88321a22e

And AfterLoad is sitll fired twice when you start a scene.

**Comment by badandbest** [comment]
I've made separate for these.
https://github.com/Facepunch/sbox-issues/issues/6671
https://github.com/Facepunch/sbox-issues/issues/6672
https://github.com/Facepunch/sbox-issues/issues/6673
https://github.com/Facepunch/sbox-issues/issues/6674
