### ISSUE TITLE
Implement Panel.RayToLocalPosition(Ray, out Vector2, out Float)

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#6446]
### For?

S&Box

### What can't you do?

I tried using Panel.RayToLocalPosition but it wasn't working as expected so I decompiled it and checked then I found this:

![devenv_YMvJOiEdpg](https://github.com/user-attachments/assets/6b459e44-be52-481f-883e-edd6a6a07b71)

Clearly it isn't implemented, so I figured I'd make an issue.

### How would you like it to work?

I would like that feature to work as described in the summary of it.

### What have you tried?

I tried using it but it defaults to returning false and default values.

**Comment by xezno** [comment]
This looks intentional, it's implemented on WorldPanel

**Comment by ShadowBrian** [comment]
It should probably give you an error when you try using it explaining that you probably need to cast to worldpanel?

**Comment by ShadowBrian** [comment]
Got it working using worldpanel!

**Comment by DrakeFruit** [comment]
running into the same issue myself trying to do VR UI, an easier way to get the 3D position of the cursor would be nice.

**Comment by DrakeFruit** [comment]
A method to convert a vector2 position on the world panel to a vector3 world space position would let me avoid writing this bullshit
![Image](https://github.com/user-attachments/assets/bf5008af-6daf-498d-87f2-f585e8ef5cb5)

**Comment by DrakeFruit** [comment]
gonna make this a separate issue nvm

**Comment by aylaylay** [comment]
Which part don't you like? Do you already have the screen position and you want to convert that back to worldspace?

```cs
	public Vector3 LocalToWorldPosition( Vector2 localPosition )
	{
		localPosition *= ScenePanelObject.ScreenToWorldScale;
		return Transform.PointToWorld( new Vector3( 0, localPosition.x, -localPosition.y ) );
	}
```

If so it should be something like that
