### ISSUE TITLE
Better constructors for events within action graph

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6455]
Currently, you're unable to dispatch events within action graph. You could do some custom nodes but it's kind of messy. The nodes in action graph currently are like this:
![image](https://github.com/user-attachments/assets/a4383fa8-3ec2-4338-b10e-095ba3d6b786)
They don't work and spit errors:
![image](https://github.com/user-attachments/assets/06a489f5-5608-42a2-b04b-ae43cd8f0133)
I would like to be able to create and dispatch events directly within action graph.

**Comment by Metapyziks** [comment]
I'll build it on top of `ISceneEvent` instead of being limited to libevents.

**Comment by Metapyziks** [comment]
![devenv_VvsrGGEi2v](https://github.com/user-attachments/assets/6b7b034a-16d3-4dae-9720-1a35c35fbe8c)

https://github.com/user-attachments/assets/32529d27-891f-4c4c-b060-0645463a2281
