### ISSUE TITLE
[Regression?] OnValidate no longer acts as advertised/intended

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6456]
### Describe the bug

Per it's definition, OnValidate is fired every time a property of that component is changed.
![2024 09 19_21 00 24](https://github.com/user-attachments/assets/98ade315-5b65-4b3f-9c0b-e829e6f2254c)

It used to do that, until some unspecified recent moment, which made it not do it's primary function, which is update on property change.

![2024 09 19_21 06 52](https://github.com/user-attachments/assets/c3292188-a102-4375-952e-a8b4ca008989)
For testing purposes I created a very basic component that overrides lights color from my own property, and if we were in the past (as far as like, a week ago), it would change it instantly.

**BUT**
![2024 09 19_21 08 10](https://github.com/user-attachments/assets/5e62880d-1f0b-4ce4-ac8e-2509da61c5a9)
If you change the "Change Me" property now, the actual light color is unchanged, in this case blue, while the property clearly says red.
![2024 09 19_21 08 21](https://github.com/user-attachments/assets/54d4dd94-078e-484d-bf38-09756b737ee2)
Start the game, it's red. Stop the game, return to editor, it's blue again. 

### To Reproduce

1. Open Repro project
2. Find "Test Light" game object, it has one custom light component that is used for testing.
3. Set the actual light color property to something you can recognize. Like blue.
4. Set the "Change Me" property to something clearly not blue. Like Red.
5. Observe the light still being blue (or your color from step 3) IN THE EDITOR.
6. Start the game with F5, observe the light becoming red (or your color from step 4)
7. Observe that the console prints the color only once when you start the game, instead of every time you change the color in the "Change Me" property.
8. Cry

### Expected behavior

It should do what the OnValidate tooltip says, aka the behavior that used to be for 50 thousand years.

### Media/Files

# Repro project
# [onvalidate_issue.zip](https://github.com/user-attachments/files/17064178/onvalidate_issue.zip)

### Additional context

I asked another person to confirm the steps and unfortunately it didnt work for them as well.

Also, *potentially* unrelated and i'm wrong, but whatever this is, *potentially* affects probe generation, as usually running the game would update them in the editor as well, but not anymore.

Here you can see the cubemap reflect the light that's been turned off, and running the game doesn't update it, only toggling the component/gameobject off/on does.
![image](https://github.com/user-attachments/assets/b234a606-bbbf-49a6-a0ed-fffdc5dc5ec7)

**Comment by aylaylay** [comment]
We'll get this fixed but just a suggestion, it's advised to mark properties as Dirty and use OnDirty for doing this kind of thing.

**Comment by aylaylay** [comment]
This should be fixed now.
