### ISSUE TITLE
[REGRESSION] All Model Physics are teleported to 0, 0, 0 upon playing the scene

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6457]
### Describe the bug

When placing a ragdoll within the scene using model physics, they are teleported to 0, 0, 0.

### To Reproduce

1. Place a ragdoll in your scene.
2. Notice them move to 0, 0, 0 upon play.

### Expected behavior

They shouldn't be doing this.

### Media/Files

https://github.com/user-attachments/assets/dc008da7-29b6-4375-9d81-2883fe92eee1

**Comment by aylaylay** [comment]
should be fixed

**Comment by Nolankicks** [comment]
https://github.com/user-attachments/assets/1a735581-d18d-40b7-9d15-0dee4bb6eba8

Still seems to happen to me.

**Comment by PapaBeefolini** [comment]
Still acting odd.

https://github.com/user-attachments/assets/f3ea1d02-66b5-491e-82be-a2d9362b6f27

**Comment by Nolankicks** [comment]
Fixes this morning. Thanks
