### ISSUE TITLE
Properties of some standard types cannot be edited

### ISSUE THREAD

**Issue by surv0013** [Facepunch/sbox-issues#6458]
### Describe the bug

I created a resource where some properties are of type `sbyte`, and when I tried to edit it through the editor, I found that properties of this type cannot be edited.

### To Reproduce

1. Create resource.
2. Paste code:
```CS
public sbyte TestSByte
{
	get;

	private set;
} = 0;

public short TestShort
{
	get;

	private set;
} = 1;

public ushort TestUshort
{
	get;

	private set;
} = 2;
```

### Expected behavior

The properties should be editable, as it works with the `int` type.

### Media/Files

![image](https://github.com/user-attachments/assets/c78ef994-76c5-4eb9-b4d5-5baf8b6c05b9)

**Comment by aylaylay** [comment]
Should work now

**Comment by surv0013** [comment]
Thanks.
