### ISSUE TITLE
Editor crash to desktop when calling Graphics.Clear()

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6463]
### Describe the bug

I have some code that attempts to manually render a panel to a texture. When I call `Graphics.Clear()` in my method `TexturePanel.Render`, the editor crashes to desktop.

In the attached log, you can see that the last thing logged is `Call Graphics.Clear()`

### To Reproduce

1. Open the attached project, and ensure that the scene `test_hud` is open.
2. Play the scene
3. See that the editor has crashed

### Expected behavior

The editor should never crash without some sort of error telling me what I did wrong.

### Media/Files

[smooth.zip](https://github.com/user-attachments/files/17078374/smooth.zip)

[Log.log](https://github.com/user-attachments/files/17078318/Log.log)

**Comment by handsomematt** [comment]
The texture you're providing isn't a render target, use Texture.CreateRenderTarget. I've added exceptions to prevent misuse now
