### ISSUE TITLE
Allow [Change] attribute to have parameterless callback

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6468]
### What it is?

Having oldValue and newValue on the Change callback is super useful, but most of the time I just want the callback and don't care about the old vs new values. After using it a lot, copy/pasting the method and change the parameter types feels like extra uneeded boilerplate for most cases.

### What should it be?

I'd like to be able to make a parameterless callback as well as the original old/new value one.

```cs
[Sync, Change] public bool isDead { get; set; }

// Instead of having to do this
public void OnisDeadChange(bool oldValue, bool newValue)
{
    
}

// I want to be able to this as an alternative
public void OnisDeadChange()
{

}
```

**Comment by aylaylay** [comment]
Agreed & Added
