### ISSUE TITLE
Add Editor [Event("scene.preplay")] event that is called before loading the scene

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6469]
### For?

S&Box

### What can't you do?

You can't get an editor event for on play but BEFORE the scene loads. [Event("scene.play")] happens even after GameObjectSystems are loaded.

### How would you like it to work?

Same as [Event("scene.play")] but before the scene loads

### What have you tried?

I can't think of anything I can do that would be reasonable

**Comment by DevulTj** [comment]
Does this do what you need? https://docs.facepunch.com/s/sbox-dev/doc/iscenestartup-UaHEQHresW

**Comment by Coomzy** [comment]
Not really, I wanted a callback to clean up static variables before play in editor starts. But I've stopped using GameObjectSystem constructors for logic, so I solved it a different way.

I still think this would be useful, but feel free to close.

**Comment by handsomematt** [comment]
It'd be good if you said your use case was to workaround another issue.
