### ISSUE TITLE
Add a function/event to be called after BuildCamera, but before the actual rendering phase

### ISSUE THREAD

**Issue by LunaRyuko** [Facepunch/sbox-issues#647]
**What can't you do?**
I'm trying to make it so that the crosshair is stuck onto the place in the world where the bullets would hit, but it's "delayed" by one frame, so it looks like it "leads" the aim and it looks very jittery too. In the UI I do `.ToScreen();` on the Vector3 with the target position in the world and it seems to use the camera data from the previous frame to calculate the screen position.

**How would you like it to work?**
Maybe add the ability to pass the camera setup to the `.ToScreen()` function?

**What have you tried?**
`[Event.Frame]`
It still seems to use the camera setup from the previous frame

**Additional context**

https://user-images.githubusercontent.com/10626859/128769638-ae11e017-b625-45bd-8d47-35a3416746a6.mp4

**Comment by garrynewman** [comment]
![image](https://user-images.githubusercontent.com/928843/128849638-090e45bc-3cfa-4803-aa37-7c9dc521dc37.png)

 on Game class

**Comment by LunaRyuko** [comment]
Right, sorry, I meant after that, when the engine is already aware of the new CameraSetup.

**Comment by garrynewman** [comment]
I committed something that should put this callback in a more expected place
