### ISSUE TITLE
Mouse inputs don't works when UI has focus with pointer-events: all

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6472]
### Describe the bug

Mouse buttons is not triggered when a panel has pointer-events set to `all` or `auto`. But keyboard inputs works fine

### To Reproduce

- Create a component and place it on a gameobject
```csharp
public sealed partial class MyComponent
{	
	protected  void OnUpdate()
	{
                // use will print true when pressed
                // attack1 will print false when pressed
		Log.Info( "Inputs: " + Input.Down( "use" ) + ", " + Input.Down( "attack1" ) );
	}
}
```
- Place a screen panel with any `PanelComponent` and enable the `pointer-events: all` on this panel from the scss

### Expected behavior

Mouse inputs should works, like keyboard inputs

### Media/Files

https://github.com/user-attachments/assets/fcd4b9a3-5943-4ca9-94c5-2c2c35e796b9

**Comment by handsomematt** [comment]
They're not supposed to work, the UI is meant to swallow the inputs, so you dont fire a gun when clicking a button for example
