### ISSUE TITLE
`Property or indexer 'Game.ActiveScene' cannot be assigned to -- it is read only 

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#6475]
### Describe the bug

normally , you could set the Game.ActiveScene = newScene; to avoid multiple scenes , or scenes overlapping , or even that a scene already has been loading , now it says its only read only , and scene change doesent work 

### To Reproduce

var newScene = new Scene();
        newScene.Load( resource );

        var oldScene = Game.ActiveScene;

 
        Game.ActiveScene = newScene;
        oldScene?.Destroy();

### Expected behavior

hours before it was working

**Comment by MD485** [comment]
Shouldn't Scene.Load do this for you automatically?
Having `Game.ActiveScene` be `internal set;` makes a lot of sense to me, it's a field you query, not assign.

**Comment by Coomzy** [comment]
It also breaks the workaround for https://github.com/Facepunch/sbox-issues/issues/6169

**Comment by handsomematt** [comment]
Sorry it broke your stuff but it's the wrong way to have been doing it
