### ISSUE TITLE
The Mute and Solo checkboxes in the Mixer window do nothing

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#6476]
### Describe the bug

See the title.

### To Reproduce

1. Go to the Mixer window while in game
2. Try to mute or solo any channel

### Expected behavior

These checkboxes should do what they're supposed to.

### Media/Files

https://github.com/user-attachments/assets/dc67391d-b774-47bd-be7c-e2794c8d0918

**Comment by aylaylay** [comment]
Done
