### ISSUE TITLE
Particle Trail Renderer Crashing Game

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#6477]
### Describe the bug

Whenever opening a scene with the particle trail renderer, the editor instantly crashes.  This happened a week or two ago but then stopped, now it's happening again.  This seems to be specific to my project as creating a new one doesn't have this issue.

### To Reproduce

Create a particle effect and attach a trail renderer to it.  As it's project specific I've attached a repro project (particle effect in question is in the playergibs prefab) and the logs that seem to relate to crashes (both end with different messages)

### Expected behavior

Shouldn't Crash

### Media/Files

[trailrendererrepo.zip](https://github.com/user-attachments/files/17087981/trailrendererrepo.zip)
[Log.1636.log](https://github.com/user-attachments/files/17087982/Log.1636.log)
[Log.1633.log](https://github.com/user-attachments/files/17087983/Log.1633.log)

**Comment by ScoutWozniak** [comment]
After a reinstall I am still experiencing issues.  Here is an updated log file
[Log.log](https://github.com/user-attachments/files/17095543/Log.log)

**Comment by handsomematt** [comment]
#6276
