### ISSUE TITLE
Undo does not undo stuff

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6479]
### Describe the bug

Placing some stuff into scene and performing undo, nothing happens. I am not sure what stuff is affected, so far I tried placing decals/models/prefabs, all have the same issue.

### To Reproduce

1. Drag stuff from asset browser into scene
2. Try to undo it
3. Nothing undos, and possibly errors occur

### Expected behavior

No errors, stuff should get undoed.

### Media/Files

https://github.com/user-attachments/assets/11cdf78c-77a6-4ee4-9d9c-819cc1d47142

**Comment by anthonysharpy** [comment]
#4477

**Comment by Gmod4phun** [comment]
> #4477

I'd say thats related to some undo system changes, but its a different issue (working feature, with optimization vs a feature not working at all)

**Comment by anthonysharpy** [comment]
@Gmod4phun Sorry I was just tagging because this issue is causing an issue in the other issue 😄
