### ISSUE TITLE
Expose Physics Substeps to the editor

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6480]
### For?

S&Box

### What can't you do?

There is no way to increase physics substeps outside of code, many newer developers don't even know about its existance.

### How would you like it to work?

We'd like it to have it exposed in the scene's inspector together with the fixed update rate, time scale, etc...

![image](https://github.com/user-attachments/assets/bfcced0c-b385-4b2a-b4ef-9283d741fbdb)

### What have you tried?

Game.ActiveScene.PhysicsWorld.Substeps

**Comment by DevulTj** [comment]
Added
