### ISSUE TITLE
`NetworkSpawn(null)` no longer assigns no owner to the GameObject

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6481]
### Describe the bug

Hi,

Since a recent commit, at least within the last 2 days, `NetworkSpawn(null)` no longer spawns a non-owner GameObject as it did before.

It seems that `NetworkSpawn()` now always assigns ownership to the connection that runs the code.

### To Reproduce

- Download https://github.com/Facepunch/sbox-scenestaging
- Edit `Gun.cs`
- Change `o.NetworkSpawn();` to `o.NetworkSpawn(null);`
- Start `networking.scene` and press `Attack1` to spawn a cube.
- The cube should have no owner, but it still gets ownership from the player running the code.

### Expected behavior

The old behavior: no owner.

or

Is this a new behavior? Does every `GameObject.NetworkSpawn()` now require an owner?
If so, it might be time to [update the documentation](https://docs.facepunch.com/s/sbox-dev/doc/networked-objects-tZyFBYMMYu#h-instantiating-a-networked-object) with: "Every networked game object **must** have an owner." 🤓

**Comment by kurozael** [comment]
I believe this may be an unintended side effect of a recent change to consolidate NetworkSpawn logic. We'll look into this 👍

**Comment by DevulTj** [comment]
This has been solved afaik
