### ISSUE TITLE
News from https://sbox.game/news in discord server 

### ISSUE THREAD

**Issue by somethink000** [Facepunch/sbox-issues#6490]
### For?

Other

### What can't you do?

watch news in discord server

### How would you like it to work?

New news was added to a separate discord channel

### What have you tried?

Communication with comunity is better on the discord server than on s&box.game

### Additional context

It would be very convenient

**Comment by DevulTj** [comment]
We don't really have plans for this - if we post something, we share it to discord and our socials anyway

**Comment by somethink000** [comment]
> We don't really have plans for this - if we post something, we share it to discord and our socials anyway

i mean comunity games news 
![Снимок экрана (273)](https://github.com/user-attachments/assets/f70e544b-53c0-4eb2-a870-0aa80a481f0f)

**Comment by yuberee** [comment]
There's this issue open for that:

https://github.com/Facepunch/sbox-issues/issues/5433

**Comment by MrBrax** [comment]
mine is also a bit related #6392
