### ISSUE TITLE
Scene.GetAll<T> no longer returns classes extended from the specified type

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6491]
### Describe the bug

Running `Scene.GetAll<BaseType>()` will not return `ClassDerivedFromBaseType`, breaking multiple parts in my games.

### To Reproduce

1. Create a base and a derived component
2. Try to get all of them by fetching the base type in getall
3. Only get the base type

### Expected behavior

Either a second method to mimic the original behaviour or to return all the extended types too

**Comment by handsomematt** [comment]
This works fine for me right now, can you provide some code if it's still not working for you

**Comment by MrBrax** [comment]
issue was a red herring, carson fixed the original problem
