### ISSUE TITLE
When selecting two capsule colliders a weird distortion appears.

### ISSUE THREAD

**Issue by CaptainLegoDev** [Facepunch/sbox-issues#6492]
### Describe the bug

Kind of a minor bug but still a visual issue technically, even if just in editor as far as I'm concerned.

### To Reproduce

1. Add two capsules, -10 and 10 in start and end. Both on a scale of 0.5, both rotated on 90 degrees, and both with a model child for representation.
2. Select both of these in a prefab

### Expected behavior

No distortion should appear when I select both, and it wont go away unless I deselect them, even if I delete them.

### Media/Files

![bugcol](https://github.com/user-attachments/assets/aa515561-2748-4b1b-825c-503ef861cdd4)

### Additional context

The capsule model was modeled in blender.

**Comment by aylaylay** [comment]
I can't repro this

**Comment by CaptainLegoDev** [comment]
It went away and I haven't either so I'm going to close this.
