### ISSUE TITLE
FBX imported model parts have wrong names

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6493]
### Describe the bug

An imported FBX model into Modeldoc that has multiple parts will have those parts use the wrong names - it seems to use the mesh datablock name instead of the object datablock name.

This was recently fixed for OBJ's, and from some discord research, FBXes have been inconsistent - sometimes using mesh name, other times using object name. Inspecting the exported FBX files, it seems to also include the object name, so it should probably always use that.

What is even worse, some multi-mesh models I have exported before as FBX have retained the proper part name (object name), but I don't have those files anymore to repro.

### To Reproduce

1. Make your own multi-mesh model and export as FBX (or use the provided files from the included zip)
2. Create a ModelDoc model out of those files and notice the part names

### Expected behavior

Part names should always use the name of the object, not the underlying mesh.

### Media/Files

[test_cubes.zip](https://github.com/user-attachments/files/17100944/test_cubes.zip)

Hierarchy in Blender
![image](https://github.com/user-attachments/assets/b2a4eae5-d477-4afe-b397-e515aae37fa3)

Part names when using FBX:
![image](https://github.com/user-attachments/assets/e235a8c1-d655-4fc5-bf7b-4835d758485c)

Part names when using OBJ:
![image](https://github.com/user-attachments/assets/05ae7e43-7dcf-4872-8867-342b89b41829)

**Comment by aylaylay** [comment]
Why is this a problem exactly?

`Part names should always use the name of the object, not the underlying mesh.`
Who says?

**Comment by aylaylay** [comment]
How it works is that it will try to use mesh name, if that's empty, it will fall back to object name. This is how I'd expect it to work, obj uses object name because that's all it has. If there is a major reason why this needs to be object name (I don't see one) I'll reopen the issue.

**Comment by Gmod4phun** [comment]
I believe it did in fact use object names in the past, it probably should do that even now, but I am not a 100% sure what is going on.

Even the citizen/human files that come with the game, you can see that those do infact use the object names, and the mesh names are irrelevant.

Citizen:
![image](https://github.com/user-attachments/assets/d5c39f93-295e-41fe-891d-679a9d524f0a)
![image](https://github.com/user-attachments/assets/b00ad9c3-aad9-441d-adfe-41b77d16ca56)

Human:
![image](https://github.com/user-attachments/assets/24a42a94-659d-4ebe-8562-32bfed3d3865)
![image](https://github.com/user-attachments/assets/31e13976-5dcd-4b82-9c48-7a068993469a)

I don't think I have ever seen a software that would use the mesh name as opposed to object names, I think everything I have ever come across has always used object names.
 
For example, importing a model into something like Marmoset to bake the High poly to Low poly requires the objects to be named properly for the auto importer to work. An example:

In Blender:
![image](https://github.com/user-attachments/assets/ea2ef6b5-7481-4098-99b8-4ab005947245)

In Marmoset:
![image](https://github.com/user-attachments/assets/b31ee861-d879-4ad9-b6c3-9c39c8c2b51c)

This is also a picture of what the part names looked like for a model I had imported about 3 weeks ago (it used the object names, not the mesh names (those were all cube.001/circle.001 garbage random names)) (I don't have that model file anymore sadly)
![image](https://github.com/user-attachments/assets/982bad58-be7b-4d3b-84c2-bd0c424aadc5)

It makes no sense to me why s&box would suddenly use the mesh names instead of object names.

**Comment by aylaylay** [comment]
The fbx import code for setting the names hasn't changed since we got it. I debugged it when importing citizen meshes and the mesh names are empty so it falls back to object name. Is it possible that the fbx exporter you're using has changed/updated?

I'm not totally against prioritizing the object name but I want to find out why it has changed for you first.

**Comment by Gmod4phun** [comment]
I am using the standard Blender FBX exporter (which is supposedly shit, and I can probably see why), so unless that was changed in a Blender update, I have no idea.

**Comment by aylaylay** [comment]
Well nothing has changed on our end when it comes to this

**Comment by Gmod4phun** [comment]
In that case I would humbly ask if the object name could be prioritized, as you will always have an object name. That would also make it pretty consistent across programs. I assume your 3D artists use Maya or Max, and if those export out an FBX with empty mesh names, I think it makes sense to always just use the object names when importing a model.

**Comment by aylaylay** [comment]
Okay, only if you agree to take the blame if someone needs it the other way.

**Comment by Gmod4phun** [comment]
I agree to that :)

**Comment by MrBrax** [comment]
i've noticed this too, much prefer the object names instead of the mesh data block names

**Comment by aylaylay** [comment]
Done

**Comment by Gmod4phun** [comment]
Works perfectly, thank you :)
