### ISSUE TITLE
Using "Break into separate components" on a deactivated Prop component just removes it

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#6494]
- On a gameobject with a Prop component, deactivate Prop then click "Break into separate components"
- Prop is completely removed

![sbox-dev_2024-09-23_10-37-15](https://github.com/user-attachments/assets/2e5df83f-7eac-4f54-9089-fa831333aad4)
![sbox-dev_2024-09-23_10-37-24](https://github.com/user-attachments/assets/e92b69d8-d2b4-436f-90a9-ce61b26228c9)

I would expect that it would still separate into components, deactivated or activated. Deleting completely feels the most unexpected result of clicking the button.

**Comment by aylaylay** [comment]
Fixed

**Comment by badandbest** [comment]
I tested this and I have a few notes:
* I think it'd make more sense if a disabled prop separated into disabled components.
* If you undo the separation the components stay. This doesn't happen with enabled props.

  https://github.com/user-attachments/assets/f681338f-3d46-4a38-9f81-22ae5a72f4d9

**Comment by aylaylay** [comment]
I think i agree

**Comment by aylaylay** [comment]
Fixed
