### ISSUE TITLE
sbox.game error "Seen in Versions" doesn't work

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#6498]
### Describe the bug

The "Seen in Versions" bit on sbox.game doesn't actually display any of the game package versions the error occured on, it's always just 0.

### To Reproduce

1. Open any of the following error links:
https://sbox.game/fish/sauna/errors/view/484ce2475c6b098884c4acb75b43784962e72eb8379b960a9b3b306090c47ef0
https://sbox.game/fish/deathcard/errors/view/0b5db961b5dc800ba59f4c2b81338d19804418e7f9a60b9a807b2f3d6cd33c6d
https://sbox.game/brax/cargame/errors/view/40a5db724599f77b248ac49068c244ca9374fc96aadc3ddd9c983af7db386d2e

2. See that "Seen in Versions" is always just 0.

### Expected behavior

"Seen in Versions" should display the game package versions that the error happened in.

### Media/Files

![image](https://github.com/user-attachments/assets/2a11f75e-9a0e-45c6-a2b6-5f06e0f4c1f7)

### Additional context

IIRC this used to work.

**Comment by DevulTj** [comment]
Garry fixed this the other day I believe, looks like we're tracking versions again on https://sbox.game/fish/deathcard/errors - closing
