### ISSUE TITLE
AE_CL_PLAYSOUND doesn't seem to work on viewmodels.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#650]
**Describe the bug**
Attaching sound events to animations in modeldoc doesn't seem to work for view models. I've attached numerous events to the animations of a model I'm working on, I can hear all the sounds fine in modeldoc, but then when used in-game none of the sounds can be heard.

Cloaker#2459 on discord also mentioned that he was having a similar issue with AE_CL_CREATE_PARTICLE_EFFECT
**To Reproduce**

1. Create a model to be used as a viewmodel.
2. Attach sounds to the animations.
3. Play the animations on the viewmodel.

**Expected behavior**
The sounds play when the animations run.

**Screenshots**
![image](https://user-images.githubusercontent.com/7847372/128836644-ae263877-65ab-4c23-81b1-16ea7671552e.png)

**Comment by realpack** [comment]
Similar problem, I hope to fix it soon.

**Comment by timmybo5** [comment]
Glad you made an issue, they used to work perfectly fine you know, then some random update broke it unfortunately. They are very much aware of the problem but its just not a priority atm, just wanted to let you know :) 
I hope they fix it when they find some time.

(Deleted User = My old account)
![image](https://user-images.githubusercontent.com/4988198/132729181-fdafe548-ae44-4acd-93ee-cbc048858102.png)

**Comment by robotboy655** [comment]
Related issue: https://github.com/Facepunch/sbox-issues/issues/1156

**Comment by Fortune117** [comment]
This seems to be working as expected now.
