### ISSUE TITLE
Better Editor Project Examples

### ISSUE THREAD

**Issue by Bozcx** [Facepunch/sbox-issues#6502]
### Location

https://docs.facepunch.com/s/sbox-dev/doc/editor-apps-3zkbxm7msB

### Summary

Overall the documentation around Editor Projects is very limited, with the Editor tools only being the most fleshed out, out of the 2 that even have documentation at the moment.

**Comment by CarsonKompon** [comment]
I've added some more docs/examples under the [Editor Page](https://docs.facepunch.com/s/sbox-dev/doc/editor-tuqJFIQJaj). Let me know if there are any other questions/things that need clearing up.
