### ISSUE TITLE
Add "PLAY" button to sbox.game pages to open the game in s&box

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#6504]
### For?

S&Box

### What can't you do?

Open a game from sbox.game for quickly sharing games with other peoplee

### How would you like it to work?

PLAY button on sbox.game launches s&box and opens the game modal
![image](https://github.com/user-attachments/assets/0b266080-93cd-40f9-be2f-a986a3247a77)

### What have you tried?

telling people the name of the game and having them look it up to join me is a little inconvenient, though this feature is probably low priority

**Comment by handsomematt** [comment]
Wouldn't be hard, would be kinda nice

**Comment by DevulTj** [comment]
![image](https://github.com/user-attachments/assets/04aebc28-8a27-4cb3-b6b0-49550d474f40)
Added
