### ISSUE TITLE
Creating a new UI component in the picker doesn't include the project namespace

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6505]
### Describe the bug

Have to add the namespace to the component and then it disappears from the object, having to re-add it again.

### To Reproduce

1. Create new game object
2. Create a new UI/Razor component on it
3. Notice that the .razor file does not have a namespace

### Expected behavior

Project namespace should be included like .cs files do

**Comment by aylaylay** [comment]
Fixed
