### ISSUE TITLE
Add IsOrganizationMember to Connection

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6509]
### For?

S&Box

### What can't you do?

I'm not sure there is any way to check if a user is a part of the game's organization, this would be useful for admin things

### How would you like it to work?

```cs
if (Connection.Local.IsOrganizationMember)
{
    Log.Info("I'm a developer!");
}
```

### What have you tried?

I know I could check their SteamID but updating that requires patching the game and is less nice

**Comment by trende2001** [comment]
Related-ish #6513
