### ISSUE TITLE
Application.IsDebug just returns true

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6511]
### Describe the bug

Application.IsDebug just returns true

### To Reproduce

N/A

### Expected behavior

I expect it to tell me if it's a debug session, for now can it just return `IsEditor || IsJoinLocal`?

**Comment by Coomzy** [comment]
Now it's just returning false?

**Comment by aylaylay** [comment]
That's because it's not debug

**Comment by Coomzy** [comment]
Oh it's for Sandbox itself, not relative to my project?

**Comment by aylaylay** [comment]
Yup. Tbh I don't know why we have it public.
