### ISSUE TITLE
[sbox.game] Organization permissions

### ISSUE THREAD

**Issue by trende2001** [Facepunch/sbox-issues#6513]
### For?

S&Box

### What can't you do?

I want to be able to assign different permissions to members of my organization

### How would you like it to work?

Have **Manager** and **Playtester** roles;
Managers can upload and update existing games and change info about them and the organization, playtesters can see hidden games and play them

### What have you tried?

Everytime I host a playtest for something private I have to give the players the server id and tell them to open the console and type `connect [id]`

**Comment by kEllieGit** [comment]
Kinda wish we could define our own roles, and set their permissions for stuff, somewhat like how steam allows us for steamworks groups. I unno how much of this is me asking for too much though.

**Comment by brannanz** [comment]
You need the wood & gravel to made that sandbox ..
