### ISSUE TITLE
Physics Debug in Scene View

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#6519]
### For?

S&Box

### What can't you do?

This is a minor issue but I want to be able to visualise collisions in the scene view easily, without having to enter play mode.

### How would you like it to work?

The "Show Physics Debug" option from play mode should also be in the scene view settings panel.

### What have you tried?

Switching to the play tab, enabling physics debug and then switching back to my scene tab, which works but is cumbersome.

**Comment by aylaylay** [comment]
I have added this to Debug > Show Physics Debug

I put it there because this convar is for both scene view and game so it wasn't really suitable putting it in viewport settings.

**Comment by Jammie3d** [comment]
That works for me, thanks!
