### ISSUE TITLE
Double click object from scene view during runtime causes it to be stuck in nothing forever.

### ISSUE THREAD

**Issue by itsbeary** [Facepunch/sbox-issues#6530]
### Describe the bug

During runtime, when you go to the scene view of the current running game scene and try to double click an object from Hierarchy it causes that scene runtime view to get stuck forever. 
example is Game: Minimal tab will now be stuck in this cyan colour view forever even after editor restart

### To Reproduce

1. Click play with an active scene (minimal for example)
2. Click on the 'Game: Minimal' tab
3. Double click a gameobject in the Hierarchy 
4. Permanently not be able to see from this view

### Expected behavior

It should be taking the scene camera to where the object that was double clicked is 

### Media/Files

![image](https://github.com/user-attachments/assets/4c34c1b3-8cf8-4db3-b6fe-988b6818f752)

**Comment by aylaylay** [comment]
Unable to repro

**Comment by itsbeary** [comment]
I uninstalled sbox completely and it stopped causing the problem

**Comment by ceitine** [comment]
I get this a bunch too, happens sometimes when double clicking a GameObject from the hierarchy.
