### ISSUE TITLE
The "View Settings" and "Layout" buttons in the editor behave weirdly

### ISSUE THREAD

**Issue by rndtrash** [Facepunch/sbox-issues#6534]
### Describe the bug

I have noticed that these buttons are not like the others, as if they're overlaid over the editor, see the Media/Files section. This is a really weird bug, and I can't replicate it reliably, so you've got to just believe me on this one :)

### To Reproduce

See Media/Files

### Expected behavior

-

### Media/Files

Video 1: The buttons show up before the editor window itself pops up. It also shows the inconsistency in their position between the tabs.

https://github.com/user-attachments/assets/8add0f2b-3464-4d57-9ba8-3edfa7f1fd5d

Video 2: After putting down the PC to sleep and waking it back up, these buttons showed up on the desktop by themselves.

https://github.com/user-attachments/assets/ac7eee5d-471d-4d33-828e-5927ca1709f7

### Additional context

OS: Windows 10 22H2

**Comment by Gmod4phun** [comment]
Got those sometimes showing up on my desktop, too. Not sure what causes it, I believe some sort of alt tabbing also triggers it.
