### ISSUE TITLE
Fixed Joint Mysteriously Stopped Working

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6537]
### Describe the bug

I'm using the Sandbox.Physics joints for my game as I find them to be more convenient and adjustable than the components. However, I open up a project that I haven't opened since sep 1st and suddenly my fixed joint for my hands stopped working. I can only find one commit from that time from laylad, "Fixed joint sets linear angular spring maximum force to float max, this is the default, not zero". However it doesn't seem it should matter

### To Reproduce

1. create fixed joint using physics points
2. set the spring values
3. doesn't work?

### Expected behavior

Fixed Joint Working

### Media/Files

[https://github.com/SwagAccount/Sewer_Hell/blob/main/code/Player/HandsDealer.cs ](https://github.com/SwagAccount/Sewer_Hell/blob/main/code/Player/HandsDealer.cs) - Script from main project
[https://github.com/SwagAccount/Sewer_Hell/blob/main/code/Player/HandsDealer.cs ](https://github.com/SwagAccount/s_box_issue_testing/blob/main/code/JointTester.cs) - Script from test project

**Comment by aylaylay** [comment]
Fixed
