### ISSUE TITLE
`Collider.KeyframeBody.GetBounds()` is incorrect during the initialization Frame

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6543]
### Describe the bug

Hi,

When you create a `GameObject` with `ModelCollider` and try to use [`ModelCollider.KeyframeBody.GetBounds()`](https://sbox.game/api/Sandbox.PhysicsBody/GetBounds), it returns incorrect and overly large bounds instead of the actual bounds of the ModelCollider.

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `Gun.cs` in the `OnUpdate()` method by adding:
```
if ( Input.Pressed( "Attack2" ) )
{
   var model = Model.Load( "models/sbox_props/wooden_crate/wooden_crate.vmdl" );

   var go = new GameObject();
   go.SetParent( Game.ActiveScene, false );

   var modelCollider = go.Components.Create<ModelCollider>();
   modelCollider.Model = model;

   var modelRenderer = go.Components.Create<ModelRenderer>();
   modelRenderer.Model = model;

   Log.Info( "before" );
   Log.Info( modelCollider.KeyframeBody.GetBounds() );

   await Task.DelayRealtimeSeconds( 0.1f );

   Log.Info( "after" );
   Log.Info( modelCollider.KeyframeBody.GetBounds() );
}
```

3) Start the `networking.scene`
4) Press Attack2 and check the console :
![Image](https://github.com/user-attachments/assets/294a8636-4177-4995-94f3-16e7b11e8497)

### Expected behavior

`KeyframeBody.GetBounds()` should return the correct bounds immediately after the `ModelCollider` is created.

**Comment by aylaylay** [comment]
Fixed
