### ISSUE TITLE
Probes causing lighting to be fullbright or too dark on certain materials (?)

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#6549]
### Describe the bug

https://github.com/user-attachments/assets/e5b3a7cb-f5ae-43f0-9273-a6b68c1640c8

![Image](https://github.com/user-attachments/assets/1c2562cd-8565-499f-8a76-c4d2171816ed)
![Image](https://github.com/user-attachments/assets/7ec0909e-e946-489b-b34e-71f3554d1845)

It seems like lightprobes or lighting are not working correctly. This setup I show was working perfectly fine before Oct 1st, possibly this commit by @samzanemesis ?
![Image](https://github.com/user-attachments/assets/321c7af8-d02d-496d-9843-6a8cd3d09902)

It only starting happening on new compiles from what I was able to see (tested an old vmap and it only showed up after new compile). It doesn't appear to happen on all materials (it is only happening to plastic_trim and metal_trim_painted_blend_02 from Facepunch.

### To Reproduce

Don't have a great reproduce but I can dm the vmap if needed

### Expected behavior

Can dm vmap if needed

**Comment by samzanemesis** [comment]
Send me the VMAP, I was just fixing something similar in regards to probes, does your map have compiled lighting?

**Comment by KingOfTheFBI** [comment]
> Send me the VMAP, I was just fixing something similar in regards to probes, does your map have compiled lighting?

I sent it over discord. Yes it is all baked. I saw you pushed something with lighting an hour ago and I tested it after, still does it.

**Comment by KingOfTheFBI** [comment]
Not sure what commit fixed this but it looks to be all good now. Thanks!
