### ISSUE TITLE
Typo in base game BaseWeapon.cs

### ISSUE THREAD

**Issue by JetBoom** [Facepunch/sbox-issues#655]
**Describe the bug**

BaseWeapon.cs in base game, line 51
```
//
// AttackPrimary could have deleted us
//
if ( !player.IsValid() )
	return;
```
Should be
```
if ( !this.IsValid() )
```
to match with the previous sanity check about reloading.

**To Reproduce**

1. Delete the weapon in AttackPrimary

**Expected behavior**

You don't get an error.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by aylaylay** [comment]
Even though this seems to be a typo from when the API changed, I don't see how this would result in an error.

I've changed it back to how it used to be although these checks are possibly redundant now.
