### ISSUE TITLE
Hardcrash by Highlight for model with no material

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#6553]
### Describe the bug

If you have hightlight setup (Highlight on camera and HighlightOutline on model renderer)
and model in model renderer has no material
hard crash happens

### To Reproduce

here is the project
just start the scene

[highlighttest.zip](https://github.com/user-attachments/files/17251605/highlighttest.zip)

### Expected behavior

no hardcrash

### Additional context

I create porocedural model without material
Probably it can also be a reason of hard crash

used code:
```
using Sandbox;

public sealed class ModelTest : Component
{

	[Property, RequireComponent]
	public ModelRenderer ModelRenderer { get; set; } = null!;

	protected override void OnStart()
	{
		var mesh = new Mesh( ); // If passing materail - no crash
		VertexBuffer vertexBuffer = new();
		vertexBuffer.Default.Color = Color.Red;
		vertexBuffer.AddCube( 0, 40, Rotation.Identity );
		mesh.CreateBuffers( vertexBuffer );

		var model = new ModelBuilder().AddMesh( mesh ).Create();
		ModelRenderer.Model = model;
		ModelRenderer.Enabled = Active;
	}
}
```

**Comment by solwllms** [comment]
Fixed
