### ISSUE TITLE
Animgraph parameters on SkinnedModelRenderer do not stay set on play

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#6554]
### Describe the bug

Whenever you try and change the animgraph parameters on a SkinnedModelRenderer component, they reset when the game starts.  This makes sense if it is the intended behaviour, but I think allowing these parameters to trigger when the scene starts would be quite useful (e.g. starting the citizen off sitting, making weapons start in their two handed mode).

### To Reproduce

Self explanatory

### Expected behavior

Animgraph parameters should be set on play.

**Comment by aylaylay** [comment]
Yes, we should save these if modified in the editor

**Comment by ScoutWozniak** [comment]
This exists now, thx laylad
