### ISSUE TITLE
`[HostSync, Sync]` should be Sync with arguments

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6559]
### For?

S&Box

### What can't you do?

https://github.com/Facepunch/sbox-issues/issues/6467

It seems like a lot of users don't know that you can use `[HostSync]` and `[Sync]` together. The only reason I found out about it was when I was reading the documentation. I think we should change the way this attribute is used.

### How would you like it to work?

Here is a suggestion from Trundler https://github.com/Facepunch/sbox-issues/issues/6467#issuecomment-2364769599
Maybe we have a single attribute where you can pass in an enum to determine who is allowed to set the value of the property?
- Owner
- OwnerHost
- Host

I haven't thought about this too much, but, I'm sure you'll have a good idea.

### What have you tried?

N/A

**Comment by handsomematt** [comment]
[HostSync] should be a parameter on [Sync], there's a lot of other API changes we want to do around here but we're probably blocked by needing proper code upgraders.

**Comment by garrynewman** [comment]
HostSync should certainly be [Sync( From.Host )] somehow.

With HostSync, something I'd like to be able to do is have a [Sync(host)] so the host is authoritive over the value, and authoritive over sending it to everyone else, but I'd like to be able to have changes predicted locally, and only corrected if they're wrong.

For example

```
[Sync( host, predicted )]
public int AmmoCount {get; set;}

// called on weapon owner, and host - somehow, maybe [Rpc( HostPredicted )] I dunno
void ShootGun( ray etc )
{
   AmmoCount--;

if ( IsHost )
{
  //    Do Damage
}
   FireWeapon();
}
```

In the scenario above the gun shot would happen locally and on the host, the host would be responsible for dealing damage, and would be authoritive on the ammo count. 

This would obviously need some careful logic so we don't update the value on the client if it was correct at the time of prediction.

**Comment by garrynewman** [comment]
I do wonder whether instead of hiding all the prediction we'd be better off doing something like

```
[Sync( host )]
public Predicted<int> AmmoCount { get; set; }
```

although going down that line fruther

```
[Sync( host )]
public PredictedLerped<float> AmmoCount { get; set; }
```
