### ISSUE TITLE
Editing file names to change capitalization does not let you save

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#6564]
### Describe the bug

when I go to edit the name of an asset in the asset browser, it doesn't let me change capitalization because it still recognizes it as the same word.

### To Reproduce

1. click on an asset
2. press f2 and change the capitalization of a letter
3. try to press enter or save
4. asset name doesn't change

### Expected behavior

it should let me change capitalization without renaming it to something else first

**Comment by solwllms** [comment]
This works now, but won't show up as capitalised in the asset browser until the new branch is merged as it's all normalised lowercase internally.
