### ISSUE TITLE
Editor silently fails to open project

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#6565]
### Describe the bug

From the editor project select window, I select my project that I want to open.

It pops up with the "Opening S&box Editor" window, does some stuff. And right after it finishes "Compiling Assets" the window closes and then nothing happens.

In the logs I see

```
2024/10/06 15:24:35.6876	[engine/RenderSystem] Vulkan Physical Device: NVIDIA GeForce RTX 3090 Ti	
2024/10/06 15:24:35.7714	[engine/RenderSystem] Unable to open Vulkan pipeline cache shadercache\vulkan\shaders.cache file - might not exist yet.	
2024/10/06 15:24:35.7714	[engine/RenderSystem] Additional fossilize database path: G:\SteamLibrary\steamapps\common\sbox\core\vulkan_shader_cache.foz	
2024/10/06 15:24:35.7714	[engine/RenderSystem] Vulkan driver version: 560.94.0.0	
2024/10/06 15:24:35.9258	[engine/RenderSystem] Loaded fossilize database in 0.15 seconds total (serial: 0.12s parallel: 0.03s)	
2024/10/06 15:24:35.9258	[engine/RenderSystem] Successfully loaded Steam Shader Pre-cache database and pre-warmed registered shaders, total time: 0.15s (pre-warm time: 0.00s).	
2024/10/06 15:24:36.3259	[Generic] Waiting for Web Auth Ticket..	
2024/10/06 15:24:36.8374	[Generic] Waiting for Web Auth Ticket..	
2024/10/06 15:24:37.3407	[Generic] Waiting for Web Auth Ticket..	
2024/10/06 15:24:38.6885	[CompileGroup/local] Building 5 compilers	
2024/10/06 15:24:42.1785	[engine/Engine] File sounds/kenney/ui/mouseclick1.wav missing vsnd extension (wav). Fixing for now.	
2024/10/06 15:24:42.1785	[engine/Engine] File sounds/kenney/ui/maximize_008.wav missing vsnd extension (wav). Fixing for now.	
2024/10/06 15:24:42.9209	[Generic] Unable to fetch package info for base: invalid ident.	
2024/10/06 15:24:43.0927	[Generic] Unable to fetch package info for toolbase: invalid ident.	
2024/10/06 15:24:43.2304	[CompileGroup/local] Building 3 compilers	
2024/10/06 15:24:45.3011	[GameMenu] Installing Cloud Assets took 0.045s	
2024/10/06 15:24:45.3650	[GameMenu] Compiling assets took 0.057s	
2024/10/06 15:24:45.3893	[GameMenu] Creating physics world	
2024/10/06 15:24:45.3893	[GameMenu] TeamStateSystem loaded	
```

I don't know where the 2 sound files are coming from (I don't have any sound in my project, or reference them.)

But I do see the lines about unable to fetch package info.

### To Reproduce

No idea.

There is a compiler code in my project. Where a class is defined twice (was in the middle of something last time I shut down the editor) but in the past the editor loads fine if there's a compiler error.

### Expected behavior

The editor should launch, or give me an error message on why it failed.

### Additional context

Loading an old commit allows me to open the editor, then I can checkout the HEAD of my repository. Code will compile fine but when I hit Play it immediately crashes the editor too.

**Comment by Remscar** [comment]
I solved the issue; turns out I had an infinite loop somewhere that was being triggered on Scene Load. Would still be nice to have some sort of error logged.

**Comment by handsomematt** [comment]
Infinite loops aren't something we can handle for you
