### ISSUE TITLE
Where is Steam? error

### ISSUE THREAD

**Issue by h12136** [Facepunch/sbox-issues#6566]
### Describe the bug

I can't launch the game and I keep getting this error. I don't have a steam emulator or have ever pirated games. People in the discord told me to post here because they couldn't fix my error. my username is "George Washington Gamin" in the discord.

### To Reproduce

1. click play
2. Where steam??
3. "im staring at it"

### Expected behavior

it should be starting the game

### Media/Files

![Image](https://github.com/user-attachments/assets/2154aad8-18ec-413a-b9c2-6d1bc178c63c)

**Comment by h12136** [comment]
I managed to fix it by deleting all files in steam dir except steam.exe and steamapps folder

**Comment by handsomematt** [comment]
Great
