### ISSUE TITLE
Transform.PointToWorld() is not working properly

### ISSUE THREAD

**Issue by surv0013** [Facepunch/sbox-issues#6567]
### Describe the bug

Method `Transform.PointToWorld()` has an incorrect order of multiplication of terms, which leads to an **incorrect result when rotating an object**.

### To Reproduce

Position: `-489.3602, 324.7535, 161.426`
Rotation: `0, 0, 0.3826834, 0.9238796`
Scale: `0.8, 0.1522163, 5.597954`

Center: `0, -100, 0`

INVALID: `Position + Center * Rotation * Scale` = `-432.7917, 313.9902, 161.426`
VALID: `Position + (Rotation * (Scale * Center))` = `-478.5969, 313.9902, 161.426`

### Expected behavior

This method should work like the method `TransformPoint` in Unity.

### Media/Files

![Image](https://github.com/user-attachments/assets/4699cdb5-47f7-419a-baf4-da64ba2f240e)

**Comment by aylaylay** [comment]
I assume PointToLocal is also incorrect then?

**Comment by aylaylay** [comment]
Should be fixed
