### ISSUE TITLE
env_sky in hammer causes error and does not show reflections

### ISSUE THREAD

**Issue by stellawisps** [Facepunch/sbox-issues#6568]
### Describe the bug

After one of the most recent commit loading a hammer map with a env_sky in it provides the following error:
```OnEnabled on SkyBox2D on (env_sky <sky>) failed from Enabled: Assert: True```
and excludes the env_sky from reflections and lighting

### To Reproduce

1. Make a new hammer map with an env_sky
2. build the map
3. load the map into scene
4. get error

### Expected behavior

env_sky should still allow reflections and not give an assert failed

**Comment by samzanemesis** [comment]
Hammer skybox really shouldn't affect indirect global lighting, you get those with what you have in combined envmap probes and VRAD, this is a behavior that changed when I added skybox IBL but it's not correct for existing maps
