### ISSUE TITLE
Hammer remove defaulting to full build when previous build not found

### ISSUE THREAD

**Issue by randomperson189** [Facepunch/sbox-issues#657]
**What can't you do?**
I can't compile a map the first time without it defaulting to the long and tedious full compile for no real reason

**How would you like it to work?**
By removing that because it's annoying and pointless

**What have you tried?**
Deleting everything on the map and then compiling so it doesn't take forever and then undoing the deletion

**Comment by bakscratch** [comment]
You have to compile vis on the first compile unless you disable in the map properties menu.
