### ISSUE TITLE
Balls suddenly not colliding on the S&Bash game

### ISSUE THREAD

**Issue by WolfRayet11** [Facepunch/sbox-issues#6571]
### Describe the bug

When playing S&Bash the balls seem to fall through the game board after 1 second, as if parts of the board suddenly don't collide with balls.

### To Reproduce

1. Launch the game S&Bash
2. While the game runs notice how every ball seems to noclip through board after 1 second.

### Expected behavior

The balls should have collided with the game board indefinitely.

### Additional context

I'm running on a Windows 11

**Comment by aylaylay** [comment]
It looks like the goal triggers are in the wrong place. I would need the project to debug this.

**Comment by aylaylay** [comment]
Fixed
