### ISSUE TITLE
After the new lighting update my scenes are pitch black

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#6572]
### Describe the bug

A few days ago my scenes loaded and the map and the objects inside were all lit. Now the objects are no longer lit.

If I go into hammer and recompile my map, everything is dark, maps and entities.

I am using a `env_sky` and `light_environment` in my map

### To Reproduce

Create a light_environment in hammer, it (sometimes) seem to light the map in game. Other times it does not.
Regardless, entities are not lit.

### Expected behavior

light_envionment should be used

### Additional context

Some logs i've noticed:

```
2024/10/07 23:18:31.4974	[engine/ResourceSystem] Error loading resource file "maps/devtestmap/lightmaps/direct_light_strengths.vtex_c" (Error: ERROR_FILEOPEN: File not found)	
2024/10/07 23:18:31.4980	[engine/ResourceSystem] Error loading resource file "maps/devtestmap/lightmaps/direct_light_indices.vtex_c" (Error: ERROR_FILEOPEN: File not found)	
2024/10/07 23:18:31.4980	[engine/ResourceSystem] Error loading resource file "maps/devtestmap/lightmaps/directional_irradiance.vtex_c" (Error: ERROR_FILEOPEN: File not found)	
2024/10/07 23:18:31.4980	[engine/ResourceSystem] Error loading resource file "maps/devtestmap/lightmaps/debug_chart_color.vtex_c" (Error: ERROR_FILEOPEN: File not found)	
2024/10/07 23:18:31.4980	[engine/ResourceSystem] Error loading resource file "maps/devtestmap/lightmaps/irradiance.vtex_c" (Error: ERROR_FILEOPEN: File not found)	
```

**Comment by samzanemesis** [comment]
Try now

**Comment by Remscar** [comment]
> Try now

Works great! Thanks @samzanemesis
