### ISSUE TITLE
Poor visibility of triggers during physics debug on bright background

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6574]
### Describe the bug

Enabling Physics debug to visualize colliders and triggers, triggers have very poor visibility on bright backgrounds.

### To Reproduce

1. Have some triggers and a bright background
2. Enable physics debug
3. See (or don't see the trigger bounds)

### Expected behavior

Triggers should be nicely visible on all background types

### Media/Files

Comparison of bright vs dark background:

![Image](https://github.com/user-attachments/assets/8496f651-fd73-4729-b12f-d60c40aa3ea1)

![Image](https://github.com/user-attachments/assets/1f95d6fe-e43a-48ae-a5fb-45fad4c63317)

**Comment by aylaylay** [comment]
I agree, physics wireframe no longer draw with alpha
