### ISSUE TITLE
Triggers contribute to mass of PhysicsBody

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6575]
### Describe the bug

When you have a rigidbody, it can be thrown off balance by a trigger in a child GameObject.

https://github.com/user-attachments/assets/47bec3e8-a903-48f5-a5d9-a0c5bcdbdc64

### To Reproduce

1. Open minimal.scene in the attached project
2. Press Play
3. See the TV fall off balance
4. See that the TV does not fall off balance if the trigger in its child GameObject is disabled

### Expected behavior

A trigger should not affect how its PhysicsBody moves.

### Media/Files

[trigger_mass.zip](https://github.com/user-attachments/files/17317215/trigger_mass.zip)

**Comment by aylaylay** [comment]
Fixed ur telly
