### ISSUE TITLE
Backport smart props from CS2.

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/sbox-issues#6577]
### What can't you do?

I cannot use  smart props becouse they are not suported 

### How would you like it to work?

Add support in hammer (or scene system) for smart props and implement the editor.

### What have you tried?

Nothing since the engine doesnt have support for this format.

### Additional context

This addition would be very useful for hammer users, because smart props add a lot of customization in one single prop. (and also they are more powerful than tile sets)

**Comment by handsomematt** [comment]
No sorry

**Comment by LVJohnFreeman** [comment]
Although this is not planned, would be cool if there was something similar to smart props of FP creation, but for scene in the future IMO
