### ISSUE TITLE
Hotreload starts to get progressively slower on larger projects

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6578]
### Describe the bug

I've noticed that on larger projects the hot reload starts to become fairly slow. I'm creating this issue to serve as a generic hot reload performance can be further improved in the future.

### To Reproduce

1. Talk to someone in Small Fish and get access to the "Death Card" repo (some Facepunch developers already have access)
2. Make a change in a razor file (add a log statement for instance)
3. Hot reloads take up to 6-7 seconds in total

https://github.com/user-attachments/assets/98019d14-b538-4533-b9ed-92d45456e6b7

### Expected behavior

Quicker reloads!

### Additional context

The video I recorded was also the first hot reload within the project. I wouldn't be surprised that as you develop the hot reload gets worse and worse.

**Comment by QuackCola** [comment]
I've noticed this too . Mainly on shadergraph fork I have . After I make quite a lot of edits  performance on hot reloading degrades

**Comment by handsomematt** [comment]
Can you turn on hotload_log when this happens, it should be really obvious what the problem is then.

**Comment by Metapyziks** [comment]
It's because of how you're storing voxels, it'll be much easier for you to fix in your project than us. You really shouldn't be using reference types for voxel arrays, a struct array would be way more cache friendly and can be hotloaded in a fraction of the time.
