### ISSUE TITLE
Render.Set for colors only respects the red channel

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-issues#658]
I used Render.Set( "Color", Color.Green ) and it came out black. This is because it only respects the red channel.

**To Reproduce**

1. Use Render.Set( "Color", Color.Green ) with a dynamic expression linking Color to Tint Color on the Complex shader
2. Notice that it's black

**Expected behavior**

It should respect all channels.

**Comment by handsomematt** [comment]
#613
