### ISSUE TITLE
`Scene.Trace.Body()` doesn't use the current PhysicsBody rotation

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6580]
### Describe the bug

Hi,

I'm using `Game.ActiveScene.Trace.Body()` to detect collisions between two `ModelCollider` instances. However, I discovered that the rotation of the PhysicsBody is being ignored.

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Create a `ColliderPreview.cs` component:
```
namespace Sandbox.ExampleComponents
{
	public class ColliderPreview : Component
	{
		[Property, RequireComponent] public ModelCollider ModelCollider { get; set; }

		protected override void OnAwake()
		{
			base.OnAwake();

			Tags.Add( "trigger" );

			ModelCollider.Model = Model.Load( "models/sbox_props/wooden_crate/wooden_crate.vmdl" );
		}
	}
}
```
3) Edit `NetworkTest.cs` -> `OnUpdate()` function:
```
	[Property] public ColliderPreview ColliderPreview { get; set; }

	protected override void OnUpdate()
	{
		if ( IsProxy )
			return;

		UpdatePickup();

		if ( !ColliderPreview.IsValid() )
		{
			var go = new GameObject();
			ColliderPreview = go.Components.Create<ColliderPreview>();
			ColliderPreview.WorldPosition = GameObject.WorldPosition;
		}

		var tracesBody = Game.ActiveScene.Trace.Body( ColliderPreview.ModelCollider.KeyframeBody, ColliderPreview.ModelCollider.KeyframeBody.GetBounds().Center )
			.IgnoreGameObject( Game.ActiveScene.GetAllObjects( true ).FirstOrDefault( x => x.Name == "Surface" ) ) // Ignore networking.scene Surface GameObject
			.IgnoreGameObject( ColliderPreview.GameObject )
			.WithCollisionRules( "solid", false ).Run();

		Log.Info( tracesBody.Component );
	}
```
4) Run `Networking.scene` ;
Change the rotation of the `ColliderPreview` GameObject and try to collide its body with another object.
It seems like the rotation of the `PhysicsBody` is being ignored.

(I also tried changing the GameObject's WorldRotation through code)

### Expected behavior

According to the documentation, `Trace.Body` should "cast a PhysicsBody from its current position and rotation to the desired end point."
However, it seems that the rotation is currently being ignored.

### Media/Files

Reproduction steps in video

https://github.com/user-attachments/assets/719101d9-5be1-498e-bdc9-414be02dced1

**Comment by aylaylay** [comment]
Not tested but should be fixed now

**Comment by PolSpock** [comment]
https://github.com/user-attachments/assets/987e0f4b-f997-444a-b864-ff689474c9a2

Thx 💌
