### ISSUE TITLE
Old packages show up in game

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6581]
### Describe the bug

Old pacakges show up in game and online.

### To Reproduce

1. Open the library manager.
2. See the old libs.
Or open sbox.game

### Expected behavior

It should only show new libs.

### Media/Files

![Image](https://github.com/user-attachments/assets/a6f00c28-8f95-4e48-8804-47633d43c55a)
![Image](https://github.com/user-attachments/assets/df07d635-51f1-437c-b3d1-8e5b3542b1d3)

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by Nolankicks** [comment]
Seems to be good
