### ISSUE TITLE
`Scene.Trace.Body().RunAll()` returns empty list

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6582]
### Describe the bug

Hi,

I'm using `Game.ActiveScene.Trace.Body()` to detect collisions between two `ModelCollider` instances.
However, I discovered that calling `RunAll()` always returns an empty list, whereas `Run()` correctly returns a hit object with the same trace parameters.

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Create a `ColliderPreview.cs` component:
```
namespace Sandbox.ExampleComponents
{
	public class ColliderPreview : Component
	{
		[Property, RequireComponent] public ModelCollider ModelCollider { get; set; }

		protected override void OnAwake()
		{
			base.OnAwake();

			ModelCollider.Model = Model.Load( "models/sbox_props/wooden_crate/wooden_crate.vmdl" );
		}
	}
}
```
3) Edit `NetworkTest.cs` -> `OnUpdate()` function:
```
	[Property] public ColliderPreview ColliderPreview { get; set; }

	protected override void OnUpdate()
	{
		if ( IsProxy )
			return;

		UpdatePickup();

		if ( !ColliderPreview.IsValid() )
		{
			var go = new GameObject();
			ColliderPreview = go.Components.Create<ColliderPreview>();
			ColliderPreview.WorldPosition = GameObject.WorldPosition;
		}

		var tracesBody = Game.ActiveScene.Trace.Body( ColliderPreview.ModelCollider.KeyframeBody, ColliderPreview.ModelCollider.KeyframeBody.GetBounds().Center )
			.IgnoreGameObject( Game.ActiveScene.GetAllObjects( true ).FirstOrDefault( x => x.Name == "Surface" ) )
			.IgnoreGameObject( ColliderPreview.GameObject )
			.WithCollisionRules( "solid", false ).RunAll();

		Log.Info( tracesBody.Count() );
	}
```
4) Run `networking.scene` ;
Check the console, it returns "0".

Then, edit the trace to use `Run()` instead of `RunAll()` and update the log accordingly.
Check the console: it correctly returns the hit object.

### Expected behavior

`Game.ActiveScene.Trace.Body().RunAll()` should return hit objects

### Media/Files

Reproduction steps in video

https://github.com/user-attachments/assets/3e0cc2e3-e3e0-4e2e-851b-8a047282649d

**Comment by aylaylay** [comment]
TraceAll for physics body isn't implemented, I was probably waiting until someone used it. I'll do it now.

**Comment by aylaylay** [comment]
Not tested but should work now

**Comment by PolSpock** [comment]
Good 💌

https://github.com/user-attachments/assets/c4d98b84-d210-413d-a1cd-182a29aa74b8
