### ISSUE TITLE
Group under parent in hierarchy tab

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6587]
### What can't you do?

1. I want to be able to select a group of objects...
![Image](https://github.com/user-attachments/assets/ce8be452-668a-449c-b562-6d3604f2eacb)

2. Right click one of the selected objects
3. Then have the option to create a new object where all the grouped objects are automatically set as children
![Image](https://github.com/user-attachments/assets/e75b5d3f-d018-4b24-8714-13f4f5eabc6c)

### How would you like it to work?

As described above

### What have you tried?

The only option right now is to create a new parent, select all of the objects, then move them as children.

### Additional context

I just found this process a bit tedious when you are dealing with a large list of objects. Also, the opposite also exists since you can click on an object and automatically create a child.

**Comment by CarsonKompon** [comment]
I agree, Unity also has this and is super useful:

![Image](https://github.com/user-attachments/assets/5d90ccc7-b9f6-4b60-a729-299a8cf22388)

**Comment by matekdev** [comment]
I didn't know this... this is still my idea...
