### ISSUE TITLE
Gizmo text depth gets overridden by solid gizmos

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6588]
### Describe the bug

Solid gizmos like `Gizmo.Draw.SolidBox` draw over gizmo text, For example...

![Image](https://github.com/user-attachments/assets/1b7812e6-494c-47e7-a71a-35f967a4dee8)
![Image](https://github.com/user-attachments/assets/ef944883-ebf6-460b-b9f8-9c06d179fac0)

### To Reproduce

```csharp
protected override void DrawGizmos()
{
	Gizmo.Draw.WorldText(
		"This is my text",
		new Transform() { Position = new Vector3( 0.0f, 0.0f, 10.0f ), Scale = new Vector3( 0.1f ) },
		"Roboto",
		28
	);

	if ( Gizmo.IsSelected )
	{
		Gizmo.Draw.Color = Color.FromBytes( 117, 184, 46 );
		Gizmo.Draw.SolidBox( BBox.FromPositionAndSize( BoxCollider.Center, BoxCollider.Scale ) );
	}
}
```

### Expected behavior

The gizmo text should draw ontop of the gizmo box.

**Comment by aylaylay** [comment]
Fixed

![Image](https://github.com/user-attachments/assets/9006f734-b5dc-4000-a9da-054cbc9f762c)
