### ISSUE TITLE
Add library tab to sbox.game

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6589]
### What can't you do?

Add a tab to this list so we can search for libraries easily. The endpoint already exists... https://sbox.game/t/library/
![Image](https://github.com/user-attachments/assets/db676172-285e-494c-9069-8b788c6131b4)

### How would you like it to work?

^

### What have you tried?

^

**Comment by Jammie3d** [comment]
The Material, Sound, Shader, Addon, Asset & Collection tabs are missing now.
![Image](https://github.com/user-attachments/assets/2f3b5500-367e-4267-9e40-434d71ce3bd4)
