### ISSUE TITLE
Gizmo line thickness doesn't change based on distance from the camera

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6592]
### Describe the bug

Gizmo line thickness doesn't seem to change based on the distance to the camera
![Image](https://github.com/user-attachments/assets/4917fbf7-9d5f-43d0-a937-3e37e43d2967)

You get these incredibly thick lines moving just slightly away from the gizmo.
![Image](https://github.com/user-attachments/assets/1b20673e-2ea5-42c4-88e0-703333582297)

### To Reproduce

Create a gizmo similar to the following...
```csharp
protected override void DrawGizmos()
{
	Gizmo.Draw.LineThickness = 6f;
	Gizmo.Draw.LineSphere( Vector3.Zero, 5f );
}
```

### Expected behavior

I would expect the gizmo line thickness to respect the distance it is away from the camera.

**Comment by aylaylay** [comment]
I would imagine it's intended to be a screenspace thickness, I could be wrong

**Comment by matekdev** [comment]
Yeah could be, personally I find it a bit weird to be in screenspace, so feel free to close if this issue if intended.
