### ISSUE TITLE
Project.json will prevent you launching other scenes, if last opened scene is missing

### ISSUE THREAD

**Issue by LVJohnFreeman** [Facepunch/sbox-issues#6594]
### Describe the bug

As title says, if in .sbox/project.json it references a non existent scene in "scene.lastopened" (for instance if you've deleted a scene for whatever reason) it will prevent you openning up any other scene and you would be stuck in a default one instead.

With the only this error being present if you try to open any other scene:
![Image](https://github.com/user-attachments/assets/4b4cd2b4-0e98-46da-9a1e-77565460dd04)

### To Reproduce

1) Create any scene
2) Save a duplicate of it with any other name
3) Close S&box with having original scene being open
4) Delete the last open scene
5) Now if you try to open S&box your whole project is broken! Unless in project.json you get rid of: 
`"scene.lastopened": {
    "Value": "[\u0022scenes/deleted_scene.scene\u0022]",
    "Timeout": 1731413219,
    "DeleteAt": 0
  },` 
Also can just delete the json itself and let S&box remake it.

**Or just download the attached repro project!**

### Expected behavior

If you are missing something, it should notify you about it and redo the json (similar to how it would do it if you've deleted it), but otherwise not prevent you from working at all.

### Media/Files

Repro project:
[scenecookies_repro.zip](https://github.com/user-attachments/files/17355571/scenecookies_repro.zip)

**Comment by CarsonKompon** [comment]
I couldn't seem to reproduce this issue on my end, even with your provided repro project/steps.

I've added a few checks that should resolve the issue, so please try it again and let me know if you still encounter it :)

**Comment by LVJohnFreeman** [comment]
> ![Image](https://github.com/user-attachments/assets/9b6f6967-7dfc-491d-9f27-0d4360fb69b6)

After this push the issue is _partially_ fixed. Right now if you load your project same problem greets you in the same repro I've attached:
![Image](https://github.com/user-attachments/assets/b5cd008e-af87-44da-81a8-87dc304690c7)

**However,** if you save your empty scene instead of trying to open any existent one editor will notice a change and will let you work further, and lets you open other scenes, thus return the functionality.
![Image](https://github.com/user-attachments/assets/fd3e9ab3-1f38-43fc-9c2e-05f71b085384)

While partially fixes the problem, could still be confusing for some. I've tested this on the same repro I've attached, so should be good to try it on it.

**Comment by LVJohnFreeman** [comment]
I've tried again an hour ago, I should be on latest. 
Here's proof:
https://github.com/user-attachments/assets/b4e3bb27-3031-4a1a-b8a6-a2ade0ef8feb

**Comment by CarsonKompon** [comment]
@LVJohnFreeman Try again once that commit builds, still unable to encounter it on my end but seeing your error in that video was some help. If you still get an error after this commit please copy and paste the full error in a reply

**Comment by LVJohnFreeman** [comment]
@CarsonKompon still have the issue. Don't have much besides this:

![Image](https://github.com/user-attachments/assets/6357ff52-a431-48ae-aca7-567d79454f09)

**Comment by CarsonKompon** [comment]
Try the most recent commit 🙏

**Comment by LVJohnFreeman** [comment]
Still have this.

What I've tried to do:

1) I've tried it in a sample project Sweeper, still happened there
2) Reinstall S&box and storing it on a different drive all together (was on C previously)
3) Completely new empty project after that reinstall

Did all of these several times to make sure it's consistent as well.

All futile, same issue and nothing new of note. Asked another person I know to try and they couldn't reproduce on their end even when manually changed stuff in json. 

Now technically I can go around this by deleting the json with it redoing it on launch and just move on with my day. However the fact its happening consistently on my end and completely halts the project without readable error is unfortunate. I hope nobody will have this issue, but you never know.

I guess we sleep on this until anyone besides me can reproduce it.

**Comment by solwllms** [comment]
The mystery of this was too much to ignore haha. Think this should be sorted now if u can give it a whirl @LVJohnFreeman

**Comment by LVJohnFreeman** [comment]
@solwllms this seems to have fixed it, can now load other scenes and it seems functional again!

Only QoL feature that would be nice in addition to this fix is for console to tell the developer they are missing a scene from their last session, might be good for transprency and readability. Say if somebody messed up during a git commit and accidentally deleted someone's scene and it wasn't noticed until a person working on X scene loaded their session, that kind of case scenario. But that's a separate thing I reckon, closing now.
