### ISSUE TITLE
Cannot drag already downloaded model in to scene

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6597]
### Describe the bug

When a model has already been downloaded from the cloud (there will be an icon in the top-right of its thumbnail), you will be unable to click and drag the model from the Asset Browser to a scene in the scene editor.

https://github.com/user-attachments/assets/9d57af90-1729-4b0a-8ddf-8487335086f3

### To Reproduce

1. Open a scene in the scene editor
2. In the Asset Browser, navigate to a model that you have not yet downloaded
3. Click and drag the model in to the scene
4. See that the model is now in your scene and has been downloaded
5. Click and drag the model in to the scene again
6. See that clicking and dragging no longer does anything

### Expected behavior

When clicking and dragging a model in to the scene, a bounding box should appear showing you where the model will be placed. Upon releasing your mouse button, the model should be placed in the scene.

**Comment by trende2001** [comment]
Just experienced the same thing

**Comment by aylaylay** [comment]
Fixed
