### ISSUE TITLE
Testing via local instance with cloud materials you have not uploaded yet show up as errors

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6598]
### Describe the bug

Testing via local instance with cloud materials you have not uploaded yet shows up as errors

### To Reproduce

1. Create a networking game.
2. Add a new cloud model.
3. Test it

### Expected behavior

The asset should be mounted.

### Media/Files

https://github.com/user-attachments/assets/a29ef72f-59c0-46b3-9b79-a0f63af4e145

### Additional context

Uploading the game to sbox.game fixes it.

**Comment by solwllms** [comment]
This should be working now

**Comment by Nolankicks** [comment]
There is another issue, networked props on cloud maps don't show up.![Image](https://github.com/user-attachments/assets/61288fa2-cfeb-4da8-be9d-1e3e8d6482cf)
![Image](https://github.com/user-attachments/assets/8d474cf3-630d-43ea-bca8-c98f0bfa9213)
Let me know if you want me to create a different issue.
