### ISSUE TITLE
Project Keybinds not updating

### ISSUE THREAD

**Issue by Bozcx** [Facepunch/sbox-issues#6599]
### Describe the bug

When creating or updating a keybind in your project it wont be added / updated till you restart the editor.

### To Reproduce

1. Change or Add a new keybinding
2. Try calling the keybind in code ( If adding a new one it will say it cannot find x keybind )
3. Tada broken

### Expected behavior

It shouldn't require a Editor restart.

**Comment by matekdev** [comment]
Sounds related to https://github.com/Facepunch/sbox-issues/issues/6590, I didn't realize the keybind broke as well until restart.
