### ISSUE TITLE
Allow custom cursors

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#66]
**What can't you do?**
At the moment there is no way for us to unlock the cursor from the center of the screen and simultaneously hide it. 

**How would you like it to work?**
I would like it to work very similar to Unity where there is cursor lock mode and cursor visibility options. Working on polystrike, we have the player point to the mouse but at the moment we have no way of drawing a crosshair because the cursor is always visible.

**What have you tried?**
Several variations of various pointer-events: all in my SCSS files for the UI, and so far I have been unable to find the setting I am looking for.

**Comment by garrynewman** [comment]
So you want to define custom cursors, right?

**Comment by Geeknerd1337** [comment]
Yes, ideally we would be able to tie it to a UI panel so we can do fancy animations for cross hairs if we'd want, rather than just simply overriding the cursor with an image. It is possible currently to have a UI element follow the mouse position, which could be used to make custom cursors easily enough, but being able to disable the mouse visibility (without also re-enabling the mouse lock) would be nice.

**Comment by aylaylay** [comment]
I'd like this too.

**Comment by Geeknerd1337** [comment]
This technically exists now, closing the issue.
