### ISSUE TITLE
Game upload fails if any files are empty

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6608]
### Describe the bug

I know this issue is a bit stupid, but, I guess a regression occurred.
https://github.com/Facepunch/sbox-issues/issues/6167

### To Reproduce

1. Create an empty file `myfile.razor.scss`
2. Try to upload the project
![Image](https://github.com/user-attachments/assets/f20199f3-891a-406f-9892-10fe2f920668)

It'll be blocked until you give it some content or remove the file.

### Expected behavior

Just ignore the file or allow it to be uploaded.

### Additional context

This issue was previously closed as completed, not sure if this is a regression or maybe the fix just exists on a branch?

**Comment by DevulTj** [comment]
Strange - I thought I fixed this. Will take another look

**Comment by DevulTj** [comment]
should be good now
