### ISSUE TITLE
Include the project ident in the location of where the project is stored

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6609]
### What can't you do?

When creating a project the location section doesn't make it clear whether or not the path will create a new folder, or store the contents of the project directly within the selected path. For example...
![Image](https://github.com/user-attachments/assets/fa8754f4-10b9-46c7-8b19-ba846d461615)

This will create a brand new folder called "my_project" inside of `C:/Dev`. It should add in the project ident inside of the path to let users know this is the case (the UI should automatically update with `C:/Dev/my_project`). 

### How would you like it to work?

The location path should automatically update with the ident `C:/Dev/my_project`. Right now it looks like the root directory of the project will be `C:/Dev`.

### What have you tried?

...

**Comment by handsomematt** [comment]
Yucky ident
