### ISSUE TITLE
Allow custom default namespace for addon project generation

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#661]
**What can't you do?**
When the project generator runs, it replaces the project's default namespace with the addon root directory name, which causes inconsistent namespace naming when adding new `.cs` files in Visual Studio. I am unable to override this behavior.

**How would you like it to work?**
It should be a setting in `.addon`:
```jsonc
{
  "ident": "berkin.c9t",
  "sharedassets": "*.*",
  "namespace": "C9T"
}
```

**What have you tried?**
I have tried setting the default namespace in the project settings, but because the `.csproj` is regenerated by the game, this setting isn't retained.

**Comment by ogniK5377** [comment]
This is also helpful since adding `-` to folders ends up breaking how classes are generated by an IDE, example

`sbox-game` will generate `namespace sbox-game`

**Comment by ogniK5377** [comment]
In the next update under "rootnamespace" 👍

**Comment by TheBerkin** [comment]
Thanks!
