### ISSUE TITLE
Folder browser for new project location begins in a folder other than the default project location

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6613]
### Describe the bug

When selecting a location for a new s&box project, the folder browser begins in a path other than the default project location. In my case, it starts searching where s&box is installed.

### To Reproduce

1. On the welcome screen for the s&box editor, click the New Project button
2. Take note of the path displayed in the Location field
3. Click on the folder icon in the location field as shown below
![Image](https://github.com/user-attachments/assets/cc74532f-9534-4b4a-813b-c38f27b28120)
4. See that the folder shown in the window that pops up is not the same as the path that was displayed in the Location field
![Image](https://github.com/user-attachments/assets/bee28fad-848b-4a86-8494-03de74d1468f)

### Expected behavior

When selecting the location for a new s&box project, the folder browser should start by showing the default project location.

**Comment by aylaylay** [comment]
Fixed
