### ISSUE TITLE
Add a "Edit Prefab" button to the right of a Prefab Field

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6616]
### What can't you do?

In order to edit a prefab you need to right click and then press "edit prefab", this is fine, honestly, but I think having a button on there as well would be very nice. 

### How would you like it to work?

![Image](https://github.com/user-attachments/assets/141440e1-4802-4e4c-9f9c-c5a5c8e50eee)
Basically, just having a separated by border button right there with the pencil icon, clicking it would take you to edit the prefab. 

### What have you tried?

Nothing

**Comment by QuackCola** [comment]
Wasn't there a button there before?

**Comment by Retroeer** [comment]
Completed by Laylad with latest commit, another massive W for QoL fans everywhere

**Comment by aylaylay** [comment]
![Image](https://github.com/user-attachments/assets/57b19893-29ea-43d9-8292-f7a6b8fe93a5)
