### ISSUE TITLE
Dragging anything out of a field doesn't create a new version of it

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6617]
### Describe the bug

This occurs regarding anything, model fields, GameObjects, etc, however I'm going to use prefabs specifically as an example

If you drag a prefab onto a scene, the Prefab in the inspector can be dragged out, there's even like a box that gets created, but nothing actually happens.

### To Reproduce

1. Make a prefab
2. Drag that prefab onto the Scene
3. Click the prefab
4. Drag the prefab from the prefab field into the scene
5. nothing happens

### Expected behavior

I would presume a prefab would get created and place into the scene

### Media/Files

https://github.com/user-attachments/assets/9252d4ca-e455-4e02-a42a-e5fb99cfd6be

**Comment by aylaylay** [comment]
Done

https://github.com/user-attachments/assets/524e9654-dddc-494c-b1ab-637be6df65c2
