### ISSUE TITLE
Update networking docs regarding supported types

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6618]
### Location

- Might be worth to explicitly mention that game objects, game resources, and components can now be synced.
https://docs.facepunch.com/s/sbox-dev/doc/sync-properties-jKFHwTGVgR#h-supported-types

- Same goes for here, game objects, components, and game resources can be passed in as params for an RPC
https://docs.facepunch.com/s/sbox-dev/doc/rpc-messages-u5EwxSsBrD#h-arguments

### Summary

^

**Comment by DevulTj** [comment]
Edited those pages to include more up to date information, cheers
