### ISSUE TITLE
Crash when adding particle trail renderer

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6624]
### Describe the bug

When I added a particle trail renderer to my effect prefab it leads to hard crash of the engine.

![Image](https://github.com/user-attachments/assets/544fa1e0-8e62-47ad-a378-bf81e613b8e0)

### To Reproduce

1. Open the bug repo
2. Try opening the `treasure_chest_open_effect` prefab
3. engine crashes

### Expected behavior

Shouldn't crash!

### Media/Files

[bug_repo.zip](https://github.com/user-attachments/files/17396038/bug_repo.zip)

**Comment by aylaylay** [comment]
I wasn't getting a crash but I was getting a main thread assert - I've fixed that so hopefully it also fixes the crash

**Comment by Fortune117** [comment]
Seems fixed now! Will reopen if it happens again

**Comment by aylaylay** [comment]
Fantastic
