### ISSUE TITLE
Option for World Panel to look at the camera only on Y axis

### ISSUE THREAD

**Issue by eEight-dev** [Facepunch/sbox-issues#6631]
### What can't you do?

https://github.com/user-attachments/assets/9e0a11e3-a888-45ac-a1a4-a9aa52a69044

As seen in this example, the icons are rotating when I'm moving the camera up and down. I'd like them not to.

### How would you like it to work?

I'd like to have a toggle option on the World Panel component that gets rid of that behavior.

### What have you tried?

.

**Comment by handsomematt** [comment]
code a component to rotate it how you want
