### ISSUE TITLE
Unintended behavior with trigger and model collider

### ISSUE THREAD

**Issue by eEight-dev** [Facepunch/sbox-issues#6633]
### Describe the bug

2 days ago I was able to walk in this trigger multiple times and spawn multiple pistols. Now it seems like even after I exit it for the first time, it still thinks I'm inside it?

https://github.com/user-attachments/assets/1dadaffa-df26-42ac-b706-387a1b06a378

Maybe this has something to do with it: https://discord.com/channels/833983068468936704/835035328779518023/1296405717825355806

### To Reproduce

1. Have a player with a model collider (Static: Disabled, Is Trigger: Disabled)
2. Have another model (the cylinder in the video) with a model collider (Static: Enabled, Is Trigger: Enabled)
3.  Watch the trigger not noticing when the player with model collider is exiting.

### Expected behavior

I expect to be able to walk in the trigger multiple times and spawn multiple pistols like before.

### Additional context

I can't zip up the project however I can add people to the github repository if needed.

**Comment by Gmod4phun** [comment]
From what Im experiencing, the triggers got a bit busted after the update. It looks like if you disable the motion of a rigidbody while its in the trigger, the trigger will stop firing the Enter/Exit events even if you re-enable the object's motion.

https://github.com/user-attachments/assets/463404d3-c9ed-4abe-b76d-55cc8c036358

**Comment by DaiterGG** [comment]
it also happens when you attach something with model collider to another collider (body fall through a trigger but OnTriggerExit never execute)
![Image](https://github.com/user-attachments/assets/96a50dbc-2f49-4317-a598-92a053a8cf0e)
![Image](https://github.com/user-attachments/assets/571fa147-e88f-45b3-8926-7864ed1e8823)
![Image](https://github.com/user-attachments/assets/1beb5309-9dca-49c9-b460-5bbc44399e96)
![Image](https://github.com/user-attachments/assets/f5955da7-9160-4a96-b48b-86a61169868d)
![Image](https://github.com/user-attachments/assets/dbb4f70a-f7b2-45b5-b3ee-a37559398010)

**Comment by aylaylay** [comment]
> From what Im experiencing, the triggers got a bit busted after the update. It looks like if you disable the motion of a rigidbody while its in the trigger, the trigger will stop firing the Enter/Exit events even if you re-enable the object's motion.
> 2024-10-17.21-04-15-1.mp4

should be fixed

**Comment by aylaylay** [comment]
> it also happens when you attach something with model collider to another collider (body fall through a trigger but OnTriggerExit never execute)
> screenshots
> 
> ![Image](https://github.com/user-attachments/assets/96a50dbc-2f49-4317-a598-92a053a8cf0e) ![Image](https://github.com/user-attachments/assets/571fa147-e88f-45b3-8926-7864ed1e8823) ![Image](https://github.com/user-attachments/assets/1beb5309-9dca-49c9-b460-5bbc44399e96) ![Image](https://github.com/user-attachments/assets/f5955da7-9160-4a96-b48b-86a61169868d) ![Image](https://github.com/user-attachments/assets/dbb4f70a-f7b2-45b5-b3ee-a37559398010)

Works for the repro I did. If yours doesn't work, attach the repro

**Comment by aylaylay** [comment]
I know what the issue is, working on it

**Comment by aylaylay** [comment]
Should be fixed

https://github.com/user-attachments/assets/dda90dda-41ab-40a2-9935-cea4faef9863

**Comment by eEight-dev** [comment]
It works now, thank you.
