### ISSUE TITLE
Restored scene/prefab editor tabs on editor launch don't load the newest compiled version from disk

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6635]
### Describe the bug

After pulling git changes and opening the editor, things that were still open from last time haven't been updated to the newest version, closing the tab and reopening the scene/prefab fixes it.

Previously related to #5335

### To Reproduce

there's nothing specific in here this time except a normal team git workflow

### Expected behavior

Assets should reload properly when starting the editor

### Media/Files

https://github.com/user-attachments/assets/c3da8ac1-26f1-4a21-b272-6109fd1d154d

**Comment by MrBrax** [comment]
[sbox-dev.log](https://github.com/user-attachments/files/17430578/sbox-dev.log)

**Comment by trundlr** [comment]
This is still an issue

**Comment by trundlr** [comment]
I still get this issue when pulling and then opening s&box. The scene just loads from whatever existed last time I closed s&box.
