### ISSUE TITLE
[AnimGraph] Blend states from the current pose not current states

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#6638]
### What can't you do?

When switching a state, you enter the new state and the pose blends from the old state's pose to the new state's pose, however, if you switch state before it is finished blending, the blend is skipped and the pose snaps to the state's pose to start a new blend, I assume this means animgraph can't blend from a blend.

Example video:
![Image](https://github.com/user-attachments/assets/e52abf4b-27f2-4efb-a02d-ecb25661b502)
The 2 states are single frame poses, there is no resetting and they have a lengthy blend, all to make it easier to see (Gif still murders it), as soon as you switch before the blend is done, the pose snaps.

### How would you like it to work?

It would be better if it used the "current pose" to blend rather than the "current state's pose", since I assume it's like this because the blend uses the state's poses, so it can't "blend from a blend".

### What have you tried?

As for what I've tried, there are plenty of workarounds for this, one being forcing the blend to finish with a time condition before allowing another transition, however, this slows down a lot of the actions/animations that require quick switching of the states. (A very basic example would be a shooting state machine for a rifle).

Another workaround I do is adding another "spam" state to switch into when done in quick succession.

### Additional context

[snaprepro.zip](https://github.com/user-attachments/files/17440724/snaprepro.zip)
Insert this shrimple repro in your assets/models folder and use the boolean to quickly switch the states.

I really am not sure how feasible this change would be, but it would be really awesome, this is an issue we've all silently accepted but recognize as bullshit we shouldn't deal with.

**Comment by johncosfm** [comment]
current workaround is to use a float instead of a bool and use the 1d blend node instead of a state machine, you can set up the easing in the 1d blend node then just set the parameter to 1 or 0 in code

**Comment by Grodbert** [comment]
That's cool but there shouldn't be a need for a workaround, especially one
that requires you to discard the state machine.

**Comment by aylaylay** [comment]
Thanks for the repro, someone said I had already looked into this but I don't remember what my conclusion was. I'll have a second look. Surely we can just have a mode that enables the desired effect you want.

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/ed086a18-167d-421a-8f64-69629ab6129d

![Image](https://github.com/user-attachments/assets/72a335d1-51b7-44a7-896f-ceef64077c75)
