### ISSUE TITLE
[DM98] Weapons do not get added to inventory occasionally if dropped 

### ISSUE THREAD

**Issue by MackenzieShirk** [Facepunch/sbox-issues#664]
**Describe the bug**
Sometimes weapons when dropped will either disappear (from world and inventory) or when picked up will only give ammo and not add to inventory

**To Reproduce**

1. Make sure multiple weapons in inventory (Pistol, SMG, Shotgun, Crossbow)
2. Press 'G' to drop all weapons
3. Repeat several times until a weapon is lost

**Expected behavior**
All weapons should drop into the world and be able to be picked back up and added to inventory 

https://user-images.githubusercontent.com/9064885/129116328-211ff19d-63fd-4f8a-bc34-197369181b14.mp4

**Additional context**

Doesn't seem to be based on time between drops or picking up, adding a TImeSince delay makes no difference. Weapons are not clipping through world and disappearing. Maybe this is related to a prediction issue.

**Comment by SupinePandora43** [comment]
Move issue to https://github.com/Facepunch/dm98.
It's not S&Box's issue.
