### ISSUE TITLE
Razor generic fails to pickup stylesheet

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6642]
### Describe the bug

If you create a razor generic panel it will not apply the stylesheet. I attempted using `@attribute [StyleSheet]` (technically you don't even need it anymore) and `Stylesheet.Load`, the path is correct but it seems like it fails to apply the stylesheet.

https://wiki.facepunch.com/sbox/ui-razor-generics

### To Reproduce

`Selector.razor`
```
@namespace MyGame
@inherits Panel
@typeparam T

<root>
	<text>hello</text>
</root>
```

`Selector.razor.scss`
```
Selector {
    font-size: 40px;
    color: white;
}
```
```
<Selector T="string" />
```

### Expected behavior

It should apply the stylesheet.

**Comment by bub-bl** [comment]
I already created an issue for that: #6424

**Comment by matekdev** [comment]
Thanks for the heads up, I searched for the word generic and couldn't find this post, closing.
