### ISSUE TITLE
Spot light radius gizmo displays incorrectly

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6647]
### Describe the bug

The Spot Light component cone doesn't correctly display the radius and angle, approaching 90° will make the cone shoot off to infinity.

We had the same issue in our DebugOverlay.Cone and this is how we fixed it: https://github.com/Small-Fish-Dev/DebugOverlay/blob/1aa725364120f496408ee2acaba5adb6e6ceb6f2/Code/DebugOverlay.cs#L155
It also handles above 90°

### To Reproduce

Spot Light component "Cone Outer" gizmo

### Expected behavior

Correctly display the radius and the angle of the cone, the gizmo should always follow the radius.

### Media/Files

Yellow is a sphere with radius of 500, imagine that as the actual spot light radius
![Image](https://github.com/user-attachments/assets/8f28d507-ab17-45ba-af0c-cc6f35afe64d)
This is what outer cone radius of 45 looks like
![Image](https://github.com/user-attachments/assets/35a0261c-c142-42c5-af9b-547054fac548)
This is what 67.5 looks like
![Image](https://github.com/user-attachments/assets/559c4104-5750-4a9f-8155-4b80d11a6d23)
90° goes on forever

**Comment by aylaylay** [comment]
Fixed
