### ISSUE TITLE
[Hammer] Tool buttons get blocked after closing map even if another map is opened

### ISSUE THREAD

**Issue by Marss0** [Facepunch/sbox-issues#665]
**Describe the bug**
When having multiple maps opened in Hammer and closing one of them all tool buttons(Selection Tool etc.) get locked. Buttons get unlocked after opening map.

**To Reproduce**
1. Open min. 2 maps in Hammer
2. Close one of them
3. Look at tool buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/70289680/129121093-26091e8a-e6ae-4e64-bfef-8e3a931ec82c.png)

**Comment by Willco2** [comment]
Aha, about time an issue was made for this. It's been around since HL:A as well.

**Comment by QuackCocaine** [comment]
yeah quite an annoying little bugger

**Comment by KayaDLX** [comment]
Been happening to me too, only way to unblock it was either to open a map or do shift+b.

**Comment by aylaylay** [comment]
I have pushed a fix for this. Please close the issue if it's working for you and you're happy with it

**Comment by Marss0** [comment]
Seems to work perfectly. Thanks
