### ISSUE TITLE
Rotation property pitch is negative 0

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6652]
### Describe the bug

Every gameobject's rotation defaults to 0,0,0 but the pitch displays as -0
It's only the pitch, even if set manually to 0 so it's not a rounding error.

### To Reproduce

1. Create a new GameObject
2. Observe the Rotation

### Expected behavior

Should be 0

### Media/Files

![Image](https://github.com/user-attachments/assets/fe701ee4-8520-4517-b2c8-e9e6efe19b42)

**Comment by aylaylay** [comment]
fixed sir
