### ISSUE TITLE
Scene: Close all other tabs

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#6653]
![Image](https://github.com/user-attachments/assets/ec78fb8a-dc77-459e-ac5c-336962e10116)

Add a context menu that lets me close all other tabs

![Image](https://github.com/user-attachments/assets/ad6e7d65-a4ef-4944-b57a-a5749a226d8d)

**Comment by DevulTj** [comment]
Added

https://github.com/user-attachments/assets/e4bc4df5-7a62-4c40-8f8c-5c4a687c741b
