### ISSUE TITLE
Add local space option for force applied to particles

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6657]
### What can't you do?

Right now I'm unable to make a particle that is effectively a candle flame that points in a specific direction in the way I'd like.

You can see my issue in this particle effect:
![Image](https://github.com/user-attachments/assets/ce8681ce-9e3c-4b31-917d-0cb0f01a7470)

The particles game object is point in the direction of the red arrow, but the force applied to the particles is always relative to the world, resulting in them going upwards.

### How would you like it to work?

Add a local option to this:
![Image](https://github.com/user-attachments/assets/cdbff653-ffd6-493b-bd55-6b20cd702bbc)

### What have you tried?

I can get a similar effect by having the particles use the starting velocity from the cone emitter, but it doesn't result in the kind of behavior I want.

### Additional context

[enchantment_flaming_particles.zip](https://github.com/user-attachments/files/17492798/enchantment_flaming_particles.zip)

Here's the prefab file if it helps.

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/654a02e5-dfde-4139-8ed1-2a4d271fc406
