### ISSUE TITLE
Satan has taken over my game

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#666]
**Describe the bug**
I've had satan take over my game and everything is red and scary. I no longer have any control over it!

**To Reproduce**
Look into the mirror in your bathroom at 3am and say garry newman 3 times.

**Expected behavior**
Satan should not be controlling my game

**Screenshots**

**Additional context**
Issue 666 👍

**Comment by tristan-sladek** [comment]
If you try not looking at him, maybe he'll go away.
