### ISSUE TITLE
"Threaded Animation" scene option makes the body lag behind by a few frames when enabled.

### ISSUE THREAD

**Issue by eEight-dev** [Facepunch/sbox-issues#6663]
### Describe the bug

Title. With that option enabled, the model lags behind during the leg shuffle animation. With it disabled, it acts completely normal.

### To Reproduce

1. Be layla and have access to my repro.
2. Tick "Threaded Animation" in the scene settings.
3. ![Image](https://github.com/user-attachments/assets/9e830758-5187-43e0-a17a-fb33e6f990f7)
4. Cap the fps to a lower number like 60 so that it happens more often and more obvious.
5. Start the game and look down.
6. Move the mouse left or right until the leg shuffle animation plays (usually after +-90 degrees threshold)
7. See the very obvious lag.

### Expected behavior

"Threaded Animation" shouldn't lag the model behind during the leg shuffle animation. Without it enabled, the model doesn't lag.

**Comment by aylaylay** [comment]
I don't think there's much I can do here sorry. The whole logic in RotateBody is confusing and has async mixed in with it. It's no surprise it doesn't play nicely with threaded animation.
