### ISSUE TITLE
Editor freezes up on play for some games

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6666]
### Describe the bug

Started sometime in the last day. When pressing play on Micro Mayhem, the editor freezes up and just gets stuck. ShadowBrain says it also happens for him on his LLM Dungeon game.

### To Reproduce

1. I can add whoever wants to look at this to the micro mayhem repo
2. And then you can add it as a project and press play to reproduce

### Expected behavior

No freeze

**Comment by Nolankicks** [comment]
Happens for me as well 🙃

**Comment by trundlr** [comment]
Fixed by Sol, thanks!
