### ISSUE TITLE
Networked props on cloud maps don't show up

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6669]
### Describe the bug

Networked props on cloud maps don't show up

### To Reproduce

1. Set a cloud map to a new cloud map you have not uploaded.
2. Join via a second client.
3. See that the map props are gone

### Expected behavior

The props should be loaded

### Media/Files

https://github.com/user-attachments/assets/430cefe4-b759-47d8-a5aa-5a505195a7ac

This is a video of an unuploaded walker addon project.

### Additional context

@solwllms

**Comment by solwllms** [comment]
This should be working properly now

**Comment by Nolankicks** [comment]
Working great for me. Sol good man
