### ISSUE TITLE
ISceneLoadingEvents.OnLoad get invoked in scene previews.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#6671]
### Describe the bug

ISceneLoadingEvents.OnLoad get invoked in scene previews.

### To Reproduce

1. Make a GameObjectSystem with ISceneLoadingEvents.OnLoad.
    ```c#
    public async Task OnLoad( Scene scene, SceneLoadOptions options )
    {
        Log.Info( "OnLoad" );
    }
    ``` 
2. Click on a scene asset to load the preview.

### Expected behavior

The event should only be invoked when you open the scene.

### Media/Files

https://github.com/user-attachments/assets/82bf33e2-75ce-412e-be3a-25c7f32c507c

**Comment by handsomematt** [comment]
The scene loads to preview
