### ISSUE TITLE
`ModelCollider` from procedural Model not correctly replicated

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6675]
### Describe the bug

Hi,

*Edited 26/10/2024 17:30 CEST (simpler example)*

I'm working with ModelCollider from a Procedural Model (`sbox_procedural_model.vmld`) attached to a Network GameObject that i refresh through `GameObject.Network.Refresh()` for other clients.

However, it seems that the Convex Hull collision model is not correctly replicated to other clients.
![Image](https://github.com/user-attachments/assets/d30eb906-4388-4562-b69d-9dae9321664a)

Let's jump to the reproduction steps

### To Reproduce

1) Download the [sbox-scenestaging repository](https://github.com/Facepunch/sbox-scenestaging).
2) Update the `Gun.cs` file with the provided `OnUpdate()` code.
```
protected override void OnUpdate()
{
	if ( IsProxy )
		return;

	var pc = Components.GetInAncestors<PlayerController>();
	if ( !pc.IsValid() )
		return;

	if ( Input.Pressed( "Attack1" ) && Game.ActiveScene.GetAllObjects( true ).FirstOrDefault( x => x.Name == "TestCollider" ) == null )
	{
		Log.Info( "Attack1" );

		var go = new GameObject();
		go.Name = "TestCollider";
		go.WorldPosition = pc.WorldPosition;

		/* */

		var goSubColumn = new GameObject();
		goSubColumn.Name = "Column";
		goSubColumn.SetParent( go, false );
		goSubColumn.WorldPosition = go.WorldPosition;
		goSubColumn.WorldRotation = go.WorldRotation;
		goSubColumn.LocalPosition = new Vector3( 0, 0, 0);

		go.NetworkSpawn();
	}

	if ( Input.Pressed( "Attack2" )  )
	{
		Log.Info( "Attack2" );

		var go = Game.ActiveScene.GetAllObjects( true ).FirstOrDefault( x => x.Name == "TestCollider" );
		if ( !go.IsValid() ) { return; }

		foreach ( var goColumn in go.GetAllObjects( true ).Where( x => x.Name.Contains( "Column" ) ) )
		{
			float factor = 64f;

			Vector3[] myCube = new Vector3[]
			{
				new Vector3(-0.5f, -0.5f, -0.5f) * factor,
				new Vector3(0.5f, -0.5f, -0.5f) * factor,
				new Vector3(0.5f, 0.5f, -0.5f) * factor,
				new Vector3(-0.5f, 0.5f, -0.5f) * factor,
				new Vector3(-0.5f, -0.5f, 0.5f) * factor,
				new Vector3(0.5f, -0.5f, 0.5f) * factor,
				new Vector3(0.5f, 0.5f, 0.5f) * factor,
				new Vector3(-0.5f, 0.5f, 0.5f) * factor
			};

			var modelBuilder = new ModelBuilder();
			modelBuilder.AddCollisionHull( myCube );
			var model = modelBuilder.Create();

			var mainCollider = goColumn.Components.GetOrCreate<ModelCollider>();
			mainCollider.Model = model;
		}

		go.Network.Refresh();
	}
}
```
4) Start the `networking.scene`.
5)
- Connect a secondary user.
- Using the Host, press "Attack1" to spawn box.
- Using the Host, press "Attack2" to create a `ModelCollider` from a procedural model.
Collider is now looking as:
![Image](https://github.com/user-attachments/assets/8b6aad07-e609-4c46-b0af-1d2dd11ead84)
- Using the secondary user, test the collision ; This does not match the Host collider.
even after calling `GameObject.Network.Refresh()`

6) Extra:
- Set `Connection.CanRefreshObjects` to `true` in `GameNetworkManager.cs`.
- Restart the scene.
- Connect a secondary user.
- Using the secondary, press "Attack1" to spawn box.
- Using the secondary, press "Attack2" to create a `ModelCollider` from a procedural model.
- Using the Host, observe the collider; it does not match the secondary user's collider
![Image](https://github.com/user-attachments/assets/640fe6bc-2099-4263-b1a2-767b4e1a1203)

### Expected behavior

The `ModelCollider` from this Procedural Model must be correctly replicated

Also I’m wondering if I might be doing something wrong, as @Metapyziks has successfully worked on procedural models using the SDF library without encountering this issue.
Could it be that each client needs to rebuild the collider logic on their side?

### Media/Files

(old) Reproduction steps in video:

https://github.com/user-attachments/assets/58b1c149-f85a-4d76-bcfc-865f6ac5ba3e

**Comment by aylaylay** [comment]
Procedural models are not networked for obvious reasons. The model has to be built on clients. The collision model you're seeing is the collider of an error model.
