### ISSUE TITLE
Add ability to check mouse inputs in PanelComponent similarly to Panel

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6678]
### Describe the bug

If a panel has `pointer-events: all` set and you try to check for mouse clicks or scrolls inside the panel component it won't work. Other inputs work.

Due to panel components being unable to override the underlying panel, it's quite janky or even impossible to check mouse events, especially scrolling. `ButtonInput` doesn't seem to care.

### To Reproduce

1. Try to check for mouse-related inputs when a pointer enabled panel is visible

### Expected behavior

Mouse state checking should work in UI

**Comment by handsomematt** [comment]
They're not supposed to, otherwise you'd be shooting your gun when you're using UI? Why can't you use mouse events?

**Comment by MrBrax** [comment]
I see nowhere in my panel component where I can check the mouse wheel. Mouse clicking was possible to do with html attribute events.

**Comment by CarsonKompon** [comment]
So you'd like the `OnMouseX` overrides from the Panel class to also be available on PanelComponent? That seems doable

**Comment by MrBrax** [comment]
yeah that sounds useful

**Comment by CarsonKompon** [comment]
Here's an epic example PanelComponent:

```razor
@using Sandbox;
@using Sandbox.UI;
@inherits PanelComponent
@namespace Sandbox

<root>
	<div class="title">@MyStringValue</div>
</root>

@code
{

	[Property, TextArea] public string MyStringValue { get; set; } = "Hello World!";

	protected override int BuildHash() => System.HashCode.Combine(MyStringValue);

	protected override void OnMouseDown(MousePanelEvent e)
	{
		MyStringValue = "Clicked!";
	}

	protected override void OnMouseMove(MousePanelEvent e)
	{
		MyStringValue = "Mouse Move!";
	}

	protected override void OnMouseUp(MousePanelEvent e)
	{
		MyStringValue = "Mouse Up!";
	}

	protected override void OnMouseOver(MousePanelEvent e)
	{
		MyStringValue = "Mouse Over!";
	}

	protected override void OnMouseOut(MousePanelEvent e)
	{
		MyStringValue = "Mouse Out!";
	}

	protected override void OnMouseWheel(Vector2 value)
	{
		MyStringValue = $"Mouse Wheel: {value}";
	}
}
```

**Comment by CarsonKompon** [comment]
BTW You can also change Panel.ButtonInput from `PanelInputType.UI` to `PanelInputType.Game` to have inputs sent to the game instead of the panel:

https://sbox.game/api/Sandbox.UI.Panel/ButtonInput

**Comment by MrBrax** [comment]
my input actions are always sent to the game regardless of buttoninput

**Comment by CarsonKompon** [comment]
> my input actions are always sent to the game regardless of buttoninput

Even when you have focus on a UI panel? Because that's what it is for.
If what you're saying is true, then typing "WASD WASD WASD" in a TextEntry would make you move and jump around, no?

**Comment by MrBrax** [comment]
text entry doesn't make me walk around, but having my ui panel with `pointer-events: all;` and buttoninput default set to ui, all keyboard button actions will get sent to the game as well as the ui, as it has always done

**Comment by MrBrax** [comment]
@CarsonKompon can you clarify on this so it's not ambiguous anymore?
