### ISSUE TITLE
[Asset Browser] Pressing the everything tab slows down the editor

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6680]
### Describe the bug

Pressing the everything tab crashes the editor.

### To Reproduce

1. Press the everything tab.
2. Watch the game slow down

### Expected behavior

It should not slow down.

### Media/Files

https://github.com/user-attachments/assets/80d1c465-8e8c-4d91-a72a-37fcb6ef392d

**Comment by LVJohnFreeman** [comment]
Same here, this can lag quite a bit in anempty project:
[](https://github.com/user-attachments/assets/7882d3fd-8d7a-4fee-b51f-710482096478)

In a populated project this gets even worse as you wait for 15 minutes for it to get back to you on an average machine. Reckon on slower machines for simple games, it can get even worse.

**Comment by garrynewman** [comment]
From @handsomematt - seems like it's rendering all thumbs

![Image](https://github.com/user-attachments/assets/177f2e3a-fdaf-4790-9fc8-570f952af4a0)

**Comment by xezno** [comment]
Won't slow down anymore but I need to make it so that it loads more when you scroll to the bottom of the list, so I'll leave this open for now
