### ISSUE TITLE
GameObjectSystem is not working properly.

### ISSUE THREAD

**Issue by surv0013** [Facepunch/sbox-issues#6682]
### Describe the bug

There is a class in the engine called "GameObjectSystem" that is automatically loaded at the start of a scene. **Right now this is the ONLY way to do something like an event that fires when the game starts.** If there is another way, please write in the docs. The problem is that it fires twice, but it would be tolerable if it didn't fire in the editor when the game is not running. So it fires every time I go from scene to scene in the EDITOR, but I thought it was an in-game class. The second problem with this class is that if I give it an interface called "ISceneLoadingEvents", the "BeforeLoad" and "OnLoad" events fire in the EDITOR when play mode is disabled, and the "AfterLoad" event doesn't work, but the "AfterLoad" event fires TWICE when play mode is enabled, but then the first two events don't work. I don't understand how this works. Is this how it's supposed to work?

### To Reproduce

1. Create a class inherited from the "GameObjectSystem" class.
2. Switch to another scene.
3. Run the game (not in the editor).

### Expected behavior

I think that the "GameObjectSystem" class should only work in play mode. That is, it should not work in the editor, because it was clearly not intended for this. Well, the events in it should work properly. That is, all three events should work only in play mode.

### All scenes are disabled, I open the starting scene in the editor without play mode and see this:
![Image](https://github.com/user-attachments/assets/c5a3fc92-8f90-42d1-8d08-d7e045314d41)
### Launched the play mode in the editor:
![Image](https://github.com/user-attachments/assets/890c82a8-2543-458d-8e0e-bca8bda1c729)
### Connected to the game via the editor (Join via new instance):
![Image](https://github.com/user-attachments/assets/41f62aa7-2ead-4d86-8340-a7ca1709c326)
### My test class:
```cs
internal class ManagementSystem : GameObjectSystem<ManagementSystem>, ISceneStartup, ISceneLoadingEvents
{
    public ManagementSystem(Scene scene) : base(scene)
    {
        Log.Info($"[DEBUG] ManagementSystem: {RealTime.Now}, scene.Source: {scene.Source?.ResourceName}, scene.Name: {scene.Name}");
    }

    private void SceneLoaded()
    {
        Log.Info($"[DEBUG] SceneLoaded: {RealTime.Now}");
    }

    void ISceneStartup.OnHostInitialize()
    {
        Log.Info($"[DEBUG] OnHostInitialize: {RealTime.Now}");
    }

    void ISceneStartup.OnHostPreInitialize(SceneFile scene)
    {
        Log.Info($"[DEBUG] OnHostPreInitialize: {RealTime.Now}, scene.Source: {scene.ResourceName}");
    }

    void ISceneStartup.OnClientInitialize()
    {
        Log.Info($"[DEBUG] OnClientInitialize: {RealTime.Now}, scene.Source: {Game.ActiveScene.Source?.ResourceName}, scene.Name: {Game.ActiveScene.Name}");
    }

    void ISceneLoadingEvents.AfterLoad(Scene scene)
    {
        Log.Info($"[DEBUG] AfterLoad: {RealTime.Now}, scene.Source: {scene.Source?.ResourceName}, scene.Name: {scene.Name}");
    }

    void ISceneLoadingEvents.BeforeLoad(Scene scene, SceneLoadOptions options)
    {
        Log.Info($"[DEBUG] BeforeLoad: {RealTime.Now}, scene.Source: {scene.Source?.ResourceName}, scene.Name: {scene.Name}, options: {options.GetSceneFile().ResourceName}");
    }

    Task ISceneLoadingEvents.OnLoad(Scene scene, SceneLoadOptions options)
    {
        Log.Info($"[DEBUG] OnLoad: {RealTime.Now}, scene.Source: {scene.Source?.ResourceName}, scene.Name: {scene.Name}, options: {options.GetSceneFile().ResourceName}");

        return Task.CompletedTask;
    }
}
```

**Comment by aylaylay** [comment]
These systems are meant to run in both editor and game, you can check which by using `Scene.IsEditor`

**Comment by surv0013** [comment]
> These systems are meant to run in both editor and game, you can check which by using `Scene.IsEditor`

Hmm, ok, thanks, but what about events? Why do they work differently in the game and in the editor, or rather, do not work at all, and in the game only one works and twice at a time?
