### ISSUE TITLE
[Asset Browser] Various issues with searching in Asset Browser

### ISSUE THREAD

**Issue by LVJohnFreeman** [Facepunch/sbox-issues#6683]
### Describe the bug

There's several confusing things about searching in Asset Browser 2 right now.

1) You cant seem to search for anything in Everything.
![Image](https://github.com/user-attachments/assets/e1a6a735-91b5-4ff3-99a7-aea3831303bb)
2) Going into assets directory and looking for an asset finds nothing. 
![Image](https://github.com/user-attachments/assets/082af9f4-eea3-43ce-ad88-ba266549fb2e)

However if you go into the root directory (that being the project's directory), the search gives you what you want. 
![Image](https://github.com/user-attachments/assets/7c874df8-5997-4afe-8738-42019bb2eea9)

3) In fact you cant even find what's in the asset directory itself by file name 
![Image](https://github.com/user-attachments/assets/1bfd6791-72f4-489d-ba4c-dd957d7d50c9)
![Image](https://github.com/user-attachments/assets/6d3fc0dd-f655-4c9d-87de-655c591c4d60)

4) I couldn't find any filter in Everything to filter only for project files. I'm aware I could use the Assets option, but if I bare list of my own stuff it's not there it seems? If that existed, then this wouldn't be that much needed. Also filters didn't seem to work?
![Image](https://github.com/user-attachments/assets/bad67465-3eec-479d-ac6f-db69eaabeee5)

### To Reproduce

N/A

### Expected behavior

N/A

**Comment by Fortune117** [comment]
I opened the 'Everything' tab and its caused my asset browser to become pretty much unusable.

Here's a video of me trying to click stuff

https://github.com/user-attachments/assets/f9443022-6930-4a23-a1aa-74c92a2b15f8
