### ISSUE TITLE
[Asset Browser] Categories could be more readable UX wise

### ISSUE THREAD

**Issue by LVJohnFreeman** [Facepunch/sbox-issues#6684]
### What can't you do?

The category layout is a bit confusing and could be streamlined a bit. A lot of similar terminology used several times in a diff way, this could and should be more effecient. Everything being higher isn't ideal too IMO. 

![Image](https://github.com/user-attachments/assets/dbe3fead-6269-4916-b186-f4964fcbd4c5)

### How would you like it to work?

So my problem right now is that we have a directory called assets, but it's also the whole tab being called that already and then the "Everything" option is higher than my own assets, which also includes base content which I don't need.

Why's that?

I already know I'm looking for my own assets. I feel like in either of the instance it would be better to have the project's name and preferably an icon of it to stick out for me (this can use the same icon the project is using and I think standalone games should have an option to set any icon they want regardless!), eyes immediately are drawn to it instead of generic folder icon. I sometimes find myself accidentally pressing Everything instead, its just draws the eye more and it's higher.
![Image](https://github.com/user-attachments/assets/6c02b76a-0f9d-492d-aa87-2138891173e1)

Alternatively if we want to keep the Assets pick to still address what directory we are specifically openning, we could update the logic for headers to be less inconsistent. For instance your project goes first, then the base engine stuff and then you could have an everything option so its still something easily visible, but doesn't get in the way of your own stuff. Doesn't necessarily need to be done like this, but it would feel more consistent and use the space better!

![Image](https://github.com/user-attachments/assets/592dc4eb-9141-401d-b9a5-2d8b77ab0b1d)

### What have you tried?

N/A

**Comment by garrynewman** [comment]
I agree that everything and recent shouldn't be under the main category. I would probably add a row of buttons at the top and have them there instead, outside of the tree completely. Could have buttons there to open and switch to library and cloud browser tabs too.

Assets should really be renamed Project, and I think it's important that it shows the real filesystem under the project folder rather than a bunch of special stuff.
