### ISSUE TITLE
[Asset Browser] Cloud Assets should install on double click, not single click

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6685]
### What can't you do?

Single clicking an asset to inspect it ultimately just downloads the model, making the inspection process pointless 

### How would you like it to work?

Double clicking should install the model instead

### What have you tried?

Right clicking it, like a loser :(

**Comment by garrynewman** [comment]
This is by design, it really shouldn't matter.

**Comment by Retroeer** [comment]
I'm not a heavy cloud user by any means, so having it immediately download while I was trying to inspect it felt rather bad, especially since there's no way to delete it, which I guess could be its own issue

**Comment by handsomematt** [comment]
How are you going to inspect something you haven't downloaded
