### ISSUE TITLE
[Asset Browser] Right clicking installed assets should show a "Installed" text in place of "Install"

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6686]
### What can't you do?

When you right click an installed asset, theres no actual indication its installed, aside from inherently knowing that no "Install" text = installed

### How would you like it to work?

Right clicking installed assets should show a "Installed" text in place of "Install" 

### What have you tried?

crying a little, maybe even a bit

**Comment by solwllms** [comment]
Is this cloud assets? It should be showing "Up to date" or "Update" buttons if the package is installed. Seems to be working fine for me, is there a specific case/repro you've got?

**Comment by Retroeer** [comment]
no longer get this i guess?
