### ISSUE TITLE
[Asset Browser/Tools] Default Browser tab should be "Recent" rather than the Cloud Browser

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6687]
### What can't you do?

Currently when you try and open a material through material editor, it'll default you to the Cloud Browser tab, which is pretty useless. This also occurs with the magnifying glass for animgraphs on ModelDoc, and I'd imagine a few other places that open the Asset Browser
 

### How would you like it to work?

I believe previously it was defaulted to Recent, but even switching it to the just the normal Asset Browser would be fine

### What have you tried?

nothing really

**Comment by xezno** [comment]
It should generally pick the most suitable tab - if you've selected an asset already then it'll focus on that in either browser. For things like the Material Editor where cloud assets don't make sense, I've made it so that the cloud tab doesn't show at all
