### ISSUE TITLE
[Asset Browser] Attempting to go to the C: folder (or whatever the root is) causes odd behavior

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6689]
### Describe the bug

This is obviously a niche issue, no one is doing this, but if you go to the C: folder the Path bar completely loses the plot
https://github.com/user-attachments/assets/0b34f6c0-49a5-4392-b5e3-96ca18610483

### To Reproduce

1. From a "normal" folder, go to an engine folder, and start spamming up
2. Click on any root folder
3. Several dots should appear, clicking on them tries to take you back to your User folder
4. The dots should persist and give no real information regarding where the hell in the sauce you are

### Expected behavior

The correct path should be getting displayed

**Comment by Retroeer** [comment]
This seems better, although it tried to path to an Arma 3 install I don't even have, but most of the really weird shit was fixed so 👍

**Comment by xezno** [comment]
it tried to what
