### ISSUE TITLE
[Asset Browser] "Copy as Path" ignores capitlization, doesn't give you the full path, and uses / instead of \

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6693]
### Describe the bug

Copying the path of an asset at `C:\User\Player\sboxprojects\mygame\Assets\Models\Skibidi.vmdl` would give you `assets/models/skibidi.vmdl`
this, in most cases, is usually fine, however the path is utterly useless in most applications, ignoring capitalization will also inevitably cause issues with case sensitive programs and drive formats, and / instead of \ is just annoying and even sbox tools are picky about this.

### To Reproduce

1. Copy an asset's path
2. observe all of the above

### Expected behavior

The path given should be the full and whole path, the path should respect the path's capitilization, and the path should be using \ instead of /

**Comment by garrynewman** [comment]
The general purpose of this copy path is to be able to paste it into code, in a `Model.Load( "" )` etc. This is why it formats the way it formats. This IIRC is what it did in the previous iteration too.

**Comment by Retroeer** [comment]
Oh, that makes sense, I would probably more often use it for external applications like quickly exporting to a folder from blender without having to open file explorer, but if thats the intended use case I guess its fine

**Comment by xezno** [comment]
Works as intended
