### ISSUE TITLE
[Asset Browser] Attempting to open a file with no associated application throws an error (such as fonts)

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6694]
### Describe the bug

If you try to open a file, such as a font, sbox will throw an error saying there is no associated application.

### To Reproduce

1. Try and open an (unsupported?) file, such as a font
2. Get thrown an error

### Expected behavior

If a file has no associated application, the Windows "What program would you like to open this with" popup should appear, otherwise open with Window's default application (in the cast of fonts, whatever the hell the name of the default font viewer is)

**Comment by aylaylay** [comment]
It opens that dialog for me, what error is it giving you?

**Comment by xezno** [comment]
I've added a fallback but at the end of the day it's really up to Windows whether it shows that dialog or not
