### ISSUE TITLE
WalkController properties are not predicted

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#67]
**Describe the bug**
The properties are currently not predicted leading to unexpected results and choppy movement, all properties should include `[NetPredicted]`

**To Reproduce**
Set any property

**Expected behavior**
Prediction

**Screenshots**
Without NetPredicted

https://user-images.githubusercontent.com/25727384/116640699-84105a80-a9ae-11eb-84ca-8d83aec9e2e8.mp4

With:

https://user-images.githubusercontent.com/25727384/116640713-88d50e80-a9ae-11eb-8108-46b842423929.mp4

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by garrynewman** [comment]
Which properties?

**Comment by ogniK5377** [comment]
Every property should be predicted. Whatever you create a controller and set any properties it causes some weird movement as shown above. Specifically in the example above it was friction, air acceleration and auto jump
