### ISSUE TITLE
[REGRESSION] Dragging in a cloud model already in your project fails

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6703]
### Describe the bug

Dragging in models already in your project fails

### To Reproduce

1. Drag in a cloud model
2. Drag it in again
3. See it fail

### Expected behavior

It should continue to drag in.

### Media/Files

https://github.com/user-attachments/assets/88f115bc-fc80-4dc7-87c4-4750d83406e1

**Comment by aylaylay** [comment]
Looks like a regression, I had already fixed this
