### ISSUE TITLE
[Asset Browser] Can't navigate directories using forward/back buttons on a mouse

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#6706]
### Describe the bug

The new asset browser does not seem to react to forward/back buttons on a mouse to go up/down a directory.

### To Reproduce

1. Open asset browser
2. Navigate somewhere
3. Try using forward/back mouse buttons

### Expected behavior

Should be able to navigate forward/back a directory.

**Comment by xezno** [comment]
Was this a thing before?

**Comment by MrBrax** [comment]
yes

**Comment by xezno** [comment]
added

**Comment by Gmod4phun** [comment]
Thank you, the navigation now works. But I have a feeling it does not always respond to a click, sometimes you can double/triple click the forward/back button and it takes you where you want, but most often than not, at least for me, it doesnt trigger the desired action. Also a debug print was forgotten.
