### ISSUE TITLE
[Editor] Dragging a .vmap directly into the scene results in an "illegal path"

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6710]
### Describe the bug

Dragging a .vmap directly into the scene results in an "illegal path"

### To Reproduce

1. Create a map, compile it
2. Drag that .vmap into the scene
3. "Illegal Path"

### Expected behavior

It should probably not result in an illegal path

**Comment by aylaylay** [comment]
I don't get this anymore, must have been fixed?
