### ISSUE TITLE
[Editor] Creating an Envmap Probe GameObject gives it a default texture that does not exist

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6711]
### Describe the bug

If you create an Envmap Probe GameObject from right clicking on the hierarchy and going to the create menu, it gives it a default texture that doesn't exist, resulting in an error. 

### To Reproduce

1. Make a Scene
2. Create an Envmap Probe GameObject

### Expected behavior

Texture path should be blank or direct to a functional texture 

### Media/Files

![Image](https://github.com/user-attachments/assets/4f5a166c-865f-425e-b520-c414e46a130b)

**Comment by aylaylay** [comment]
Fixed
