### ISSUE TITLE
[Editor] Creating an Cubemap Fog GameObject gives it a default sky material that does not exist

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6712]
### Describe the bug

If you create an Cubemap Fog GameObject from right clicking on the hierarchy and going to the create menu, it gives it a default sky material that doesn't exist, resulting in an error.

### To Reproduce

1. Make a Scene
2. Create an Cubemap Fog GameObject

### Expected behavior

Sky material path should be blank or direct to a functional texture

**Comment by aylaylay** [comment]
Fixed
