### ISSUE TITLE
Add an 'Active' property (or similar idea) to the TrailRenderer component.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6713]
### What it is?

I am trying to make some sword swing vfx using the trail renderer, which is working well for the most part. However, I only want the trail to be active while swinging.

Currently if I have it active all the time it looks like this:

https://github.com/user-attachments/assets/06c087fc-3962-4960-9105-2acbad5a0b55

While this looks natural and fades away correctly, I don't want the trail enabled all the time.

If I implement something to enable it only during swings it looks like this:

https://github.com/user-attachments/assets/a3487edc-5981-49d3-bad8-78bbdf1ac61c

As you can see the snap disappearance looks very unnatural.

### What should it be?

Currently I'm disabling the trail renderer component. It'd be much better if I could just disable it adding new points to the trail, maybe through a property called 'Active' or 'Emitting' or something to that effect.

**Comment by aylaylay** [comment]
Good point, the component should really have a way to stop points being emitted.

Added TrailRenderer.Emitting
