### ISSUE TITLE
Web: Image embed in News post header can be massive

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#6718]
### Describe the bug

Noticed this while making a blog

![Image](https://github.com/user-attachments/assets/ca15c30a-eb58-4823-baf0-591633f1f326)

### To Reproduce

Make a blog

### Expected behavior

Shouldn't be massive

**Comment by garrynewman** [comment]
I think you probably have styles cached

**Comment by DevulTj** [comment]
Yup, that's it
