### ISSUE TITLE
[Physics Controller] Undo-ing changes made to Body Height and Radius don't display correctly within the scene

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6720]
### Describe the bug

Changing the Body Height or Radius values and then Undo-ing them don't update the gizmo within the scene.
This is probably an issue with other things, but I noticed it with the physics controller first.

### To Reproduce

1. Create a Physics Controller component
2. Change the aforementioned values
3. Undo these changes
4. Scene Gizmo does not update

### Expected behavior

Gizmo should update with the redo

**Comment by lolleko** [comment]
What do you mean by physics controller?

**Comment by Retroeer** [comment]
This was made when the default player controller was called physics controller, or something, let me see if this is still the case

**Comment by Retroeer** [comment]
Seems this was indirectly fixed by moving the colliders off of the main player controller
