### ISSUE TITLE
`ParticleSpriteRenderer` : Add an Offset to Texture

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6725]
### What can't you do?

Hi,

Currently, it looks like the `ParticleSpriteRenderer` only displays a particle texture from the center of the texture image.

It would be great to add a feature similar to the Legacy Particle Editor, where it was possible to apply an offset to the particle (using `m_flForwardShift`). Although it only allowed shifting in one direction, it was still quite useful.

### How would you like it to work?

Maybe by adding X and Y offset sliders with a range from 0 to 1, relative to the size of the texture?

### What have you tried?

As workaround:
- I manually edited my sprite with an offset from its center to get my desired rendering.
- I created a special attachment for my particle in my VMDL with an offset.

**Comment by aylaylay** [comment]
Just to clarify.. you want the sprite to be offset or the UVs?

**Comment by garrynewman** [comment]
I added a pivot var to the sprite shader recently that we can use for this

**Comment by aylaylay** [comment]
Both sprite components use pivot now

**Comment by PolSpock** [comment]
Thx a lot 💌
