### ISSUE TITLE
Add `ref` support to action graph methods

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6727]
### What can't you do?

I have a very simple method I would like to add to my action graph:

```CS
	public void GetScaleAmount(ref float scaleAmount)
	{
		scaleAmount += ScaleFactor * EnchantmentComponent.Strength;
	}
```
Sadly this does not seem to appear in the action graph editor. However, the same method without `ref` does appear.

### How would you like it to work?

Exactly the same as other methods.

### What have you tried?

I can work around it but it'd be convenient.

**Comment by Metapyziks** [comment]
This isn't really possible at the moment, I would just do this as a workaround:

```csharp
[Pure]
public float GetScaleAmount(float scaleAmount)
{
	return scaleAmount + ScaleFactor * EnchantmentComponent.Strength;
}
```

The `[Pure]` means the node won't have input / output signals, and will instead run when the result value is used.

**Comment by Metapyziks** [comment]
Also since you're just adding to the input, maybe consider having this:

```csharp
public float ScaleAmount => ScaleFactor * EnchantmentComponent.Strength;
```

Then you can more easily add it to a property by right-clicking on a property node, and selecting "Add":

![Image](https://github.com/user-attachments/assets/a419fa09-aab6-48af-94bd-19f0b36ee916)

**Comment by Fortune117** [comment]
I was able to get basically what I wanted with a custom method:

```CS
public interface IStatusEffectScaler : ISceneEvent<IStatusEffectScaler>
{
	/// <summary>
	/// Returns a number to add to our scaling.
	/// It will be added to 1 before being applied (so a 10% scaling would be 0.1 rather than 1.1)
	/// </summary>
	/// <param name="scaleAmount"></param>
	public void GetScaleAmount(ref float scaleAmount);

	[ActionGraphNode( "status.getscaling" ), Pure]
	[Title( "Get Status Effect Scaling" ), Group( "Status Effects" ), Icon( "" )]
	public static float GetScalingFrom(GameObject gameObject)
	{
		var scale = 0f;
		
		PostToGameObject(gameObject, x => x.GetScaleAmount(ref scale));

		return scale;
	}
}

```
You can see the reason I wanted it to be a ref here. This solution ended up being fine though!
