### ISSUE TITLE
Razor stylesheets aren't found in published games if the razor files has partial code-behinds (.cs)

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6729]
### Describe the bug

This has worked in the past for me, it must be a recent issue. It works fine in the editor but not for published games.

### To Reproduce

1. Create code-behind (.cs) file alongside the razor component, optionally with a second partial
2. Try to have a stylesheet work with it

### Expected behavior

Should work like before

### Media/Files

![Image](https://github.com/user-attachments/assets/ca2ef2ea-8a13-4d61-8481-2ad6f84a0c56)
![Image](https://github.com/user-attachments/assets/c7c9b137-0e7b-4c3e-a829-8c1efe234e6f)

![Image](https://github.com/user-attachments/assets/70a093a7-f38c-4da0-a0c4-d27941ce24f0)
![Image](https://github.com/user-attachments/assets/610907e9-1d5f-4804-bfb2-5f57eaf42d4a)

**Comment by MrBrax** [comment]
seems to be solved #6755

**Comment by DevulTj** [comment]
Yep
