### ISSUE TITLE
[Physics Controller] Option to rotate the GameObject based on camera direction rather than velocity

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6730]
### What can't you do?

With the current physics controller the GameObject rotates with velocity, which is fine in third person games, but traditionally in first person games the camera should be what dictates the player's rotation

### How would you like it to work?

A bool or something in the "Animator" feature tab maybe?

### What have you tried?

Doing it myself, but when it becomes a base component that'll be a bit harder

**Comment by badandbest** [comment]
I think it rotates the gameobject based on the camera in firstperson now.

**Comment by Retroeer** [comment]
yeah i just forgot about it
