### ISSUE TITLE
Large numbers aren't properly stored in properties

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6731]
### Describe the bug

Any number above 7 digits, int float or others, won't be correctly translated into a property's field.
Instead it will either round to the nearest multiple of 100 for floats, or multiple of 16 for integers.

### To Reproduce

1. Create a new [Property] int or float
2. In the editor, write a number larger than 7 digits in the field, I suggest 9 digits (Make sure the number already isn't a multiple of 16 or 100)
3. Press ENTER or leave the input field

Here's a repro:
```
[Property]
public string StringProperty { get; set; }
[Property]
public float FloatProperty { get; set; }
[Property]
public int IntProperty { get; set; }
[Property]
public long LongProperty { get; set; }

[Button( "Random Number" )]
public void DebugTest()
{
	var random = Game.Random.Int( 1000000000, 1999999999 );
	StringProperty = random.ToString();
	FloatProperty = (float)random;
	IntProperty = random;
	LongProperty = random;
}
```

### Expected behavior

The resulting number should match whatever you write

### Media/Files

![Image](https://github.com/user-attachments/assets/eff3769a-0be5-4bf0-b4d9-a231335dc03f)

![Image](https://github.com/user-attachments/assets/d8974ede-edca-43b6-9587-d135f7edc70b)

### Additional context

I have dungeon generation tied to a seed represented by an integer, if I find an issue with a certain seed I usually debug it with my tools, but I am unable to input the correct seed since it always changes and gets rounded.

**Comment by Metapyziks** [comment]
Thanks for the report. Fixed for int / long, can't do anything about float since it stops being able to represent some integers after 16,777,216.
