### ISSUE TITLE
[ActionGraph] `Collections - GetItem` fails to serialize the type correctly

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6736]
### Describe the bug

Whenever I launch s&box my action graphs with this method break and show me this error:
![Image](https://github.com/user-attachments/assets/a8c9013e-1a26-4f77-be9d-3f156de9e5cc)

Clicking on the GetItem node shows the following:
![Image](https://github.com/user-attachments/assets/19433303-6f47-40a7-8847-9430c0f70622)

### To Reproduce

1. Create an action graph that uses `GetItem`
2. Save it
3. Restart the editor

### Expected behavior

Should serialize and behave correctly

**Comment by Metapyziks** [comment]
Maybe related:

![Image](https://github.com/user-attachments/assets/1845081a-241e-4dac-af3f-5e6466c6f02e)

**Comment by Fortune117** [comment]
Seems to have fixed itself? I'm not sure what changed but I haven't gotten this issue in the last couple days. I will close for now and reopen it if it appears again.

**Comment by MrBrax** [comment]
still getting this

**Comment by Metapyziks** [comment]
@MrBrax I haven't been able to reproduce it in your project yet. Next time it happens please could you tell me:

- Was it right after an editor restart, or after hotloading code
- Where is the graph exactly, like which property of which GameResource / prefab / scene file
- Could you paste the contents of the graph here / in a DM, or commit to a branch

Thanks!

**Comment by MrBrax** [comment]
Happens on hotload.

dialogue/shop/sell_item.dlg

```actiongraph:H4sIAAAAAAAACsVaW2+jOBR+H2n+A5tnEmFwuOzLqNtKq0qjTqV2R1rtjioH3IQtsSNwuo2q/vexgbamMeWYNLtPJAbznfv5fJLHz58cZ3Jzc0/LKuds8qsTu+3Scptn8vsEZzgkIcXTJEVoijMvmC7mUTglIQqCLEnCLKOTZtN3UuZkUdBK7vtLrTjOY3ORNy/Imqr3sU3aPF6vXu829eoVYdmCP8x+l099W/xDUzFpnnly+160KciOloZ3nRZc6jO7rO+3l9MVKUkq5PPta9XlRyP2Bc/MIp8rA3j7ADnbbIUG/EdFyzMiiLz3slkuX/IqF41VJ1M/xO4Uxy18K4BJvRrU3wct8krMltQSF/nu1AOComgfNW1smeWk4MstnVGW2Qngh1HoTn0MlAEnwzKkK56nlEmv2YmCsXRBCLVGZLDGPdHj7bLkG1qKvA4eHfRGPdeG+guYndusRE2SIzgu8j0XHK/Ij4dFyAVdV7SQuW3vOyUNPH1QZLDIpnHXDuRB1haZc3ZPmeCltkvdFhalxtr3c5kwKAZnbex9kK6nnAmSM72mGnR9scjrp5GK1vlooygGxNizTDnL6AOtBK8KLirLohnUknngcIsBlVOW7joBZAYUm1IWsJmSzFKw0IvtBIsPLmJtmx3n4mldyMDVH8XJ/ytv63kMFjj5sOSrw+U3UhCWUpWJJS+KgVT82LKDZbBYqY4MQU+KAqR2Xl0JIvJUrt+SoqKuySYnWdZoCrFC+63PjuOM4keeZ1WjEv94/MUPFIdEgQ8lkXOAMBUVmYK1i5VEtWMLSaTge5IwvrGlkh52JTQYdD6svqAPI9hIoExrERaBNz8CQwuwbP1WUoQf4AUU+6qkRyEY1dAcb3lJSbqy1NfDskIFCBoAgWyWR65Q1+SOfmP0W3kmea2gtsTpSjKAv7eeF3poZIEKfMm8p34MZQQBAjYsUkoR97n9cCP7StlSrMyWuNpVkgLNTsqS7MACG9oM38yWMoBksxMrwuyiKAk9F5wxKDCc/m8tE8ZTnCIA5wvCxypbsmB7Lpw9BugYVQvNZRabhNAmMl9zdtc/kQkCra99J8VWCaaF9VnVBK7fWXoeG9UHg97h0lWZvp36yKXnvYKUksbrp4n3sdTMZhCqwxk0MM5OV5xXFBng9FGNhndT5UtGikFIfbahIT5v38fTxzIWeK27gn13Tf6kZAUHaijTW8PXnpS+GoDHBviLD0NHfehyGmqeeQ6gVRsqu8rLoLJPq9BkVL51/iVMOII76pzpVHxNnfrY+QUugCouw1GrHy1BMRQdFrPmJLkpabUthAXcfW2sITTdNMCc1KdwI/QbQPRMVUDvzPZpGe1H0BwOsiYP5yqwRpbSven9a2nrsWNTfIcDU98PipTOBG0EYocl6N2ilDY1weGDAqUjLlBBM2L6MvAbxNSD4CDMdi4H0BJb1pfOFG6UXbG1jmbEZuQ4Li/e029cto/Nwz44WAHtjPJg1tRnaWMSf4BHGSuoPsQaEzO6zEAt0UFadkYpupZbGzSSZSdrvmUAPH2IBItT3Q/2XSmGk8U+pIPYYgJmi6Pgx9PFPjgYX8TIoNcZd3ZvKaM8UQtHzmecx8drLkhxqX6reHr6YiERkEDaHkI6oWgdWNhwaJy8amiBd0d347XrLQx9aNBya40X9jXoYcLjWbtOn8VauG4wKfpeDEwK09HwWo6U7lReuE6qjk8Lkt45hO0cka/pLxYygNKgsxlky84w+T/hOZ3BsV2odBoQUL3DaFxH2MEG2YdG2XZNS/VnptHZsODZzoh4GI17D27WFAsLUCi3sub/nUHzqEOVLbPqTIp1rjNUBOagaWLf6xfjjdefA/qJckyM6LICjRf0HRGzZnQ79hRc/3hiRMTHaQl9Lwa2BMNURP4z5rkP5LeqM6jfbPzonjqp7BVLmqm10lnLs+3MQiBQf+hsBgYPqD+oy4/Pn55+AlNB9pADKgAA```

**Comment by Metapyziks** [comment]
Perfect, I got the same error. Thanks!

**Comment by Metapyziks** [comment]
Thanks for the help, should be sorted with the next build.
