### ISSUE TITLE
Minimum size of Asset Browser is too large on 1440p resolution

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6741]
### Describe the bug

Whenever an Asset Browser is docked, panels docked either sides of it are squished unacceptably small on 1440p resolution.

Here's a before and after of having the Asset Browser docked in the middle bottom.

### To Reproduce

1. Ensure that your monitor uses 1440p resolution
2. Dock your Asset Browser between the hierarchy and inspector as shown in the attached video in Media/Files
3. Note that the hierarchy and/or the inspector will be too narrow all times.

### Expected behavior

The minimum width of the Asset Browser should be small enough to accommodate three-column layouts on 1440p.

### Media/Files

https://github.com/user-attachments/assets/8c826062-1abd-4792-b337-7c0df0ffd8ff

**Comment by xezno** [comment]
#6699
