### ISSUE TITLE
UI sounds are impacted by Distance Attenuation and Occlusion

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6742]
### Describe the bug

UI sounds with Distance Attenuation and Occlusion will not play correctly. Ideally, UI sounds should just disable these properties and hide them.

### Expected behavior

The sound should play for the client as any regular UI sound should.

### Additional context

Probably related to @CarsonKompon changes

**Comment by CarsonKompon** [comment]
Do u have a repro? 🥺

**Comment by matekdev** [comment]
give me a sec

**Comment by matekdev** [comment]
I spoke with Carson and we figured out the root cause of this issue, updated this ticket to reflect the actual issue.
