### ISSUE TITLE
Draw Gizmos Button Should Hide Camera Frustrum Lines

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#6745]
### Describe the bug

When disabling the draw gizmos button in scene view it should hide the camera frustrum lines as well as the decal renderer lines.

There may be other gameobjects that also do this, I assume it's ones that use the line renderer.

### To Reproduce

1. Load up a scene that has a camera
2. Click the draw gizmos button
3. See that lines still appear

[gizmo.zip](https://github.com/user-attachments/files/17577331/gizmo.zip)

### Expected behavior

Toggling draw gizmos should hide anything that also gets hidden in play mode.

### Media/Files

![Image](https://github.com/user-attachments/assets/c8cf1568-d48a-44cb-9dd6-c3373301e511)
![Image](https://github.com/user-attachments/assets/87761fe3-0b0d-40a4-879c-ab917649f8dc)

**Comment by DrakeFruit** [comment]
forgot to make an issue on this, it's really annoying trying to take screenshots!

**Comment by Jammie3d** [comment]
Looks like this has been fixed now, cheers
