### ISSUE TITLE
Add `[Hide]` attribute support to Components to stop them appearing in the editor.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6751]
### What can't you do?

I've run into a use case where I have several components being added to an item with `[RequireComponent]` but I do not wish to see them in the editor.

Currently I am simply doing this in their code:
```CS
	protected override void OnAwake()
	{
		Flags = Flags.WithFlag(ComponentFlags.Hidden, true);
	}
```

### How would you like it to work?

It would be nice if I could just add a `[Hide]` attribute to the components code.

### What have you tried?

```CS
	protected override void OnAwake()
	{
		Flags = Flags.WithFlag(ComponentFlags.Hidden, true);
	}
```
This solution works but it's a bit of boiler plating that could be skipped.

**Comment by garrynewman** [comment]
I don't think this makes any sense. Hide is already used here to hide them from the Add Component dialog

**Comment by Fortune117** [comment]
> I don't think this makes any sense. Hide is already used here to hide them from the Add Component dialog

They aren't being added by the Add Component dialog, they're being added by a `RequireComponent` attribute. I don't want them to be visible in the component editor.
