### ISSUE TITLE
[Regression] Published games load scss files incorrectly

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6753]
### Describe the bug

In my project I have razor files set up like so:
![Image](https://github.com/user-attachments/assets/6cebfb0b-83a1-48c0-a9cc-cb9efb47224a)

However in the live version of the game I've started getting errors:
```
[GameMenu] Error opening stylesheet: ui/crosshair.razor.cs.scss (File not found)
System.IO.FileNotFoundException: File not found
File name: 'ui/crosshair.razor.cs.scss'
   at Sandbox.UI.StyleSheet.UpdateFromFile(String name, Boolean failSilently) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\UI2\Styles\StyleSheet.cs:line 98
```

You can see that it is searching for `crosshair.razor.cs.scss` rather than `crosshair.razor.scss`. I'm not sure when this started happening but it's completely broken several UI components.

### To Reproduce

1. Create a razor + scss setup with the same naming conventions as above
2. Publish the game and play it
3. See that it loads the wrong scss file

### Expected behavior

It was previously working as expected, only broke recently.

**Comment by DevulTj** [comment]
At first I thought my change I made a couple weeks ago was not at fault - but it was. Upon re-publishing my own repro project game without the code, it's fine now. Which makes total sense. My code was preventing SourceLocation from being added for the `.razor` file.. 🤦🏻
