### ISSUE TITLE
Add component menu show 2 times the same component

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6754]
### Describe the bug

When using a partial class to split the razor and the csharp logic, the `Add Component` menu show 2 times the same component, but its random.. Sometimes it does the duplication, sometimes not

### To Reproduce

- Create a panel component with the following code

Hud.razor
```html
@namespace YourNamespace;
@inherits PanelComponent

<root>
	
</root>
```

Hud.razor.cs
```csharp
namespace YourNamespace;

public sealed partial class Hud : PanelComponent
{
	
}
```

- Click on the `Add Component` button in thee gameobject inspector and type "Hud", you should see 2 times the "Hud" component in the list

### Expected behavior

The menu should only display one component instead of two

### Media/Files

![Image](https://github.com/user-attachments/assets/6eaf58ec-59fb-43de-bf52-3b70c81c2e6d)

**Comment by DrakeFruit** [comment]
![Image](https://github.com/user-attachments/assets/1fb7842b-4c40-4bdf-ba26-2690a141402b)
having a similar issue, I made a simple cs component and it's showing twice in the add components menu. The second one has all the properties I added and the first one doesn't

**Comment by solwllms** [comment]
No longer occuring it seems?
