### ISSUE TITLE
[UI] Wrong StyleSheet path (.cs.scss)

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6755]
### Describe the bug

Randomly after creating or editing a new razor file, we get the following error:
GameMenu Error opening stylesheet: ui/hud.razor.cs.scss (File not found)

The `scss` file path seem to be wrong now

### To Reproduce

- Create a razor file with a scss file attached to them like:
Hud.razor
```html
@namespace YourNamespace;
@inherits PanelComponent

<root>
	
</root>
```

Hud.razor.scss
```scss
Hud {
    width: 100vw;
    height: 100vh;
    background-color: red;
}
```

- You will get the error after some modification in the razor or scss file

### Expected behavior

The stylesheet path must be `Hud.razor.scss instead` of `Hud.razor.cs.scss`

### Media/Files

![Image](https://github.com/user-attachments/assets/59be2a83-c3fb-4072-9c6b-bb309e487805)

**Comment by DoctorGurke** [comment]
#6753

**Comment by bub-bl** [comment]
> [#6753](https://github.com/Facepunch/sbox-issues/issues/6753)

This is not only when your are publishing, i have created a new project and i have the error

**Comment by DevulTj** [comment]
This should be fine now, please verify!

**Comment by bub-bl** [comment]
> This should be fine now, please verify!

When opening the game, i get the same error
![Image](https://github.com/user-attachments/assets/d8cd7c68-a1cc-473a-b432-41595da08600)
![Image](https://github.com/user-attachments/assets/2c35837e-cc03-4157-a6c7-80ade16343e5)

**Comment by bub-bl** [comment]
Last night, the code worked despite the problem. Now I have no style at all. It may be due to a recent change, I don't have any style at all

**Comment by bub-bl** [comment]
I have found the issue, that seem to be caused when the C# partial class is not ended with `.razor.scs`
In my case, my partial class is `Phone.cs` and that doesn't work, but its works fine when renaming the file `Phone.razor.cs`
