### ISSUE TITLE
-tools stops certain models and materials from loading in custom gamemodes

### ISSUE THREAD

**Issue by SpoodyTheOne** [Facepunch/sbox-issues#676]
**Describe the bug**
When starting s&box with the -tools argument the car chassis model and the bouncy ball material will be missing.
The yellow material for construct will be missing aswell

**To Reproduce**
1. Unzip the facepunch/sandbox repository in addons
2. start s&box through steam with -tools argument
3. go to facepunch.construct map
4. The construct car park sign should have error textures, and the car should have an error on it

**Expected behavior**
Running s&box with -tools shouldn't result in missing files

**Screenshots**
![image](https://user-images.githubusercontent.com/28778347/129359175-88467f42-454b-4a79-b411-14b28c7eea26.png)
![image](https://user-images.githubusercontent.com/28778347/129359187-b5f91cc1-72de-4e0c-9cd9-ece40428e96e.png)

**Comment by aylaylay** [comment]
This is an issue with an uncompiled asset referencing another uncompiled asset that gets stripped out when pushed to steam.

We just have to make sure we don't do this internally. Users will never run into this issue unless they go out of their way to do it.
