### ISSUE TITLE
Add a way to import or copy paste objects from scene hierarchy to the new hammer system

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#6762]
### What can't you do?

With maploader no longer being the proper way to do maps I would like a way to convert my 'maps' that were done in the scene system. It does not seem like there is currently a way to do that. The amount of redoing that would have to be done is quite substantial. 

I have several projects that would benefit from this and I'm sure anyone else using anything with maploader would as well. Especially if anyone wants to take advantage of additive loading.

![Image](https://github.com/user-attachments/assets/a15c4cc3-ceb5-4287-967c-27bee116df89)

![Image](https://github.com/user-attachments/assets/cd84a60a-b1e1-4801-9713-53568aa82f16)

Things like this I don't want to have to manually redo.

### How would you like it to work?

It can be as simple as a copy paste, anything really just so we do not have to manually replace everything in hammer.

### What have you tried?

I understand the argument to just keep it in scene as maploader might not get 'deleted.' However, when hammer is eventually replaced in scene you won't be able to do anything in maploader anymore, so I'd rather just switch to the intended system.

**Comment by handsomematt** [comment]
Should be simple enough to let you clipboard serialized objects across

**Comment by KingOfTheFBI** [comment]
@handsomematt looks like this got broken somehow. Dragging in scene prefabs still works
https://github.com/user-attachments/assets/bfffcf9f-48e6-4a7a-b395-b089299f8c08
