### ISSUE TITLE
Allow setting F_ material properties with the Material.Set API

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6773]
### What can't you do?

Seems like you can do most stuff on runtime created materials but set the F_ things, like F_SELF_ILLUM, making it a bit limiting.

### How would you like it to work?

The same way it does with .Set?

### What have you tried?

Tried every single combination of F_SELF_ILLUM and anything one can think of to change it with no success

**Comment by handsomematt** [comment]
RenderAttributes.SetCombo( "S_SELF_ILLUM", true );

Although the shader isn't setup to have a dynamic self illumination mask so you won't get too far.

You should have a custom shader to do this.
