### ISSUE TITLE
System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.

### ISSUE THREAD

**Issue by johncessna** [Facepunch/sbox-issues#678]
**Describe the bug**
All gamemode icons are blank, unable to join or create servers.
When I attempt to create or join a server, the loading screen almost instantly closes and returns me to the main menu.
Console repeats the error "The requested name is valid, but no data of the required type was found. (files.facepunch.com:443)"

**To Reproduce**
1. Launch game.
2. Attempt to join gamemode server, or create server.

**Expected behavior**
Ability to create new games and see gamemode icons.

**Screenshots**
1. After launching the game
![sjjBGIv](https://user-images.githubusercontent.com/7742330/129392168-7ad7ba96-76ac-4b73-b5fc-2558d321126a.png)

2. Console log after attempting to create sandbox server, and being returned to main menu
![DCZUNhQ](https://user-images.githubusercontent.com/7742330/129392310-c60f3b71-87ee-49a7-b65b-956088da841c.png)

**Additional context**
Fresh install of s&box.
I have a VPN, but it was disabled when encountering the issue.

**Comment by Hazeofdream** [comment]
Have you checked to see if files.facepunch.com is within your C:\Windows\System32\drivers\etc\host?
