### ISSUE TITLE
Opening the game crashes my computer's wifi connection

### ISSUE THREAD

**Issue by ryantrawick** [Facepunch/sbox-issues#6780]
### Describe the bug

Just as the title says. I launch the game on Steam, select the main s&box, hit play, and then nothing can be loaded (sometimes it will load a few thumbnails before crapping out). It doesn't launch into or change to offline mode, it just spits out a bunch of connection errors. This has been lasting for over a month now, only with this particular game.

### To Reproduce

I can't really give any instructions to reproduce it, as it just happens every time I launch.

Things I've tried to fix it:

1. Verify the integrity of the game files on Steam.
2. Running the .exe as an administrator
3. Disabling Windows Defender Firewall
4. Checking that the Windows Defender Firewall rules are correct
5. Messing with the max allowed connections and retries and such to see if it was a network flooding issue

What kind of fixed it:

I did `ping cdn.sbox.game` and `ping services.facepunch.com`, and I added both the returned IPs to my Windows host file. The issue is it averages 0-20mbps (or so it says) and most every game take upwards of 5 minutes to download. I also can't join any servers as I get dropped, so I can only play by myself.

### Expected behavior

Everything loading normally at a regular speed like everything else has for the past 5 years of using this computer.

### Media/Files

[sbox.16.log](https://github.com/user-attachments/files/17609192/sbox.16.log)
![Image](https://github.com/user-attachments/assets/0e607dc6-1b80-4ac9-830c-2329b367f0be)
![Image](https://github.com/user-attachments/assets/97b225f6-6664-4a5f-8b29-49713607eb77)
![Image](https://github.com/user-attachments/assets/7d3e4203-5175-4581-9390-7c1735833131)

### Additional context

I am based in the South-East USA (in case s&box server might be far away).

My specs:

OS: Windows 10 64-bit Pro
Processor: AMD Ryzen 7 2700X Eight-Core Processor, 3700 Mhz, 8 Core(s), 16 Logical Processor(s)
Installed Physical Memory (RAM): 48.0 GB DDR5
GPU: NVIDIA GeForce GTX 1660 SUPER
Motherboard: ASRock B450M PRO4

speedtest.net results:

Download: 234.09 Mbps
Upload: 11.37 Mbps

**Comment by handsomematt** [comment]
Your PC is failing to verify the HTTPS certificate of cdn.sbox.game, there's nothing we can do about it on our end.

It could be a variety of reasons:
* Out of date Windows
* Anti virus interfering with HTTPS (MITM)
* ISP interfering with HTTPS (MITM)
* Bad WiFi device / drivers
