### ISSUE TITLE
[Hammer] Can't drag prefabs into hammer

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#6783]
### Describe the bug

Currently we are unable to just drag in a prefab from the asset browser into hammer.  This means each time I want to create something I have to do it from scratch.

### To Reproduce

It's in the title

### Expected behavior

We should be able to drag a prefab into hammer and have it exist in the scene.  This should just act as a reference so we don't have to recompile everytime we update the prefab.

**Comment by handsomematt** [comment]
done

**Comment by bakscratch** [comment]
This now works! Thank you Matt
