### ISSUE TITLE
Cloud assets slow down joining via new instance while developing

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6786]
### Describe the bug

When there are cloud assets to download, the amount of time it takes to join via a new instance is increased significantly. The seem to get downloaded from the host (I think?), and even after they are downloaded, they get processed very slowly 1 by 1 which affects the multiplayer dev experience significantly.

This happens in Micro Mayhem, not 100% sure if it's a consistent issue everywhere.

### To Reproduce

1. Clone https://github.com/apetavern/platform-dash (I invited Sol as a collaborator since cloud asset stuff seems to be his domain, let me know if someone else needs access instead)
2. Start up a game and join via a second instance
3. See the cloud assets taking a surprisingly long time to process

### Expected behavior

Quick and easy joining via 2nd instance

**Comment by solwllms** [comment]
Doing a bunch in parallel now which should make this faster, especially when the files have already been downloaded. (roughly ~20s down to ~2s)

FYI we're able to skip a lot of stuff when you dis/reconnect, should be almost instant as we don't have to reverify files etc.
