### ISSUE TITLE
[Hammer] Shift-drag to duplicate GameObjects doesn't work

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6788]
### Describe the bug

In the attached video, you can see a couple different things happen when I shift-drag a GameObject.

When duplicating a freshly created GameObject that has a component (in this case, ModelRenderer), the duplicate will have no components.

After saving and reopening the vmap, duplicating the cube GameObject creates a new object in the hierarchy that seems to refer to the same object in in the scene - changing the transform of one, changes that of the other.

https://github.com/user-attachments/assets/586b94dd-fd95-4344-9542-365945072008

### To Reproduce

1. Create a new vmap
2. Create a new cube GameObject
3. With the translation tool open (hotkey T), shift-click and drag on an axis to duplicate the GameObject along that axis
4. See how messed up the new GameObject is
5. Save, close Hammer, and reopen the vmap
6. Try shift-dragging the cube GameObject again
7. See that some slightly different messed up thing is happening

### Expected behavior

It should be possible to shift-drag GameObjects to duplicate them like you can with meshes and entities.

**Comment by handsomematt** [comment]
Should be wonderfully perfect now
