### ISSUE TITLE
Mesh editor cut tool

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#6792]
### What can't you do?

The cut tool from hammer is missing in scene, making it difficult to add edges to geometry

### How would you like it to work?

same as hammer

### What have you tried?

selecting 2 edges and connecting them is the only way I've found to add edges

**Comment by Nolankicks** [comment]
Dupe: https://github.com/Facepunch/sbox-issues/issues/5467

**Comment by DrakeFruit** [comment]
duplicate
