### ISSUE TITLE
Unnecessary console spam when using AE_CL_BODYGROUP_SET_VALUE

### ISSUE THREAD

**Issue by johncosfm** [Facepunch/sbox-issues#6793]
### Describe the bug

Not sure this really counts as a bug, more of an annoyance, but theres some presumably left over debug prints that print any time the AE_CL_BODYGROUP_SET_VALUE anim event is fired.
![Image](https://github.com/user-attachments/assets/248dbbb8-4807-49ab-8202-211d9ff14212)
The animevent works properly, but with the console spammed any time its activated its annoying to use.

### To Reproduce

1. Create model with bodygroups and animation sequence
2. Add AE_CL_BODYGROUP_SET_VALUE animevent to sequence
3. Observe that the console is filled with messages when the animation is played

### Expected behavior

AE_CL_BODYGROUP_SET_VALUE should be seen and not heard

**Comment by aylaylay** [comment]
Got rid
