### ISSUE TITLE
Simple shader has an option to render backfaces, but doesn't actually render backfaces when it's enabled

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#68]
**Describe the bug**
The Simple shader has an option to render backfaces, however, when this option is ticked, it doesn't render the backfaces. The Complex shader does render backfaces when this option is enabled.

**To Reproduce**

1. Go to the Material Editor
2. Create a new material (Save it as well, so that it previews in the editor)
3. Select a preview model that makes it easy to show backfaces (For example, orbiting the camera so that it's under a plane, or zooming in to the inside of a cube)
4. Enable "Render Backfaces" in the shader options, and observe the lack of change. Change to Complex, and see the rendered backfaces.

**Expected behavior**
Simple should be rendering backfaces, like Complex does.

**Screenshots**

https://user-images.githubusercontent.com/10066958/116640980-c77cb180-a939-11eb-8b03-d13e107f0d3e.mp4

**Additional context**

I noticed when changing the setting in the material editor while Hammer's open, with a prop that uses the material and has backfaces, the outline changes to go around the geometry that should be showing. I feel like this implies that rendering backfaces is something that's supposed to be working, as opposed to a checkbox that was mistakenly left in.

https://user-images.githubusercontent.com/10066958/116641303-6ef9e400-a93a-11eb-8476-703cb9f0adfa.mp4

**Comment by walllable** [comment]
I believe this is still an issue. I'll check in a bit.

**Comment by justynboi** [comment]
Still an issue

**Comment by timmybo5** [comment]
Still an issue.

![image](https://user-images.githubusercontent.com/4988198/152044496-d2da4ceb-5228-492a-aa87-6fdb5f30e59e.png)
