### ISSUE TITLE
Open All option in failed compilation window

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6803]
### What can't you do?

I can't open all the errors at once in this window
![Image](https://github.com/user-attachments/assets/0037a3d9-7dca-47eb-b455-621f9a7c8144)

### How would you like it to work?

Click open all which opens all the files that are affected

### What have you tried?

Clicking a single file, fixing, saving, and repeating over and over again.

**Comment by aylaylay** [comment]
Added shift+click to open all files
