### ISSUE TITLE
Hierarchy search should search component and property names as well

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6804]
### What can't you do?

![Image](https://github.com/user-attachments/assets/44d3ec21-e244-458d-9b72-faec93ddd0b7)

Search for a component within a scene in the hierarchy

### How would you like it to work?

Search for the component name and should game objects that have that a component with a name that matches the partial search

### What have you tried?

-

**Comment by solwllms** [comment]
You could implicly search by exact component name before, but now it's more explicit with `t:` and you can chain with others (eg `Main t:CameraComponent` to show all objects with a camera that contain 'Main' in the name)

I'm not sure I can see the usefulness of searching by property name? so closing this one.

**Comment by trundlr** [comment]
Thanks Sol! Really appreciate it :)
