### ISSUE TITLE
Unlock hammer compiler command line + set count threads vrad 3 

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#681]
Command line of hammer compiler is blocked, because of this, we can not configure compiler more precisely.
![image](https://user-images.githubusercontent.com/54669564/129413554-d11a7e3c-968f-458e-ae9c-14c0a5ff1fab.png)

Also, vrad 3 does not use all the processor threads , because of this, the compiler speed drops significantly.
![image](https://user-images.githubusercontent.com/54669564/129413394-91ad07cb-269f-4133-a509-089f3d0ad7c2.png)
(ryzen 2600 12 threads)

**Additional context**
Using all threads will speed up compilation. For example, in UE4, when compiling, all the processor threads are used, loading it by 100%, I would like this in s&box, and an open command line will give us more opportunities to configure the compiler

**Comment by MrBrax** [comment]
blocked how? i'm using powershell to compile my map every night

**Comment by aylaylay** [comment]
Blocked how, you can't edit it? Are you able to do that in Alyx? The command line is just showing you what is going run based on the settings you picked.

**Comment by gabengaGamer** [comment]
You can enter your own compile parameters in source 1 , why can't you implement the same thing in source 2 ?

**Comment by aylaylay** [comment]
Cos we don't want to do shit things that source 1 did. If you want to use the command line then use the command line to compile, not a GUI

**Comment by gabengaGamer** [comment]
Will there be more gui settings in the future ? as well as setting up the used threads ?

**Comment by aylaylay** [comment]
I just pushed a change that adds a checkbox to use all threads. More settings can be added if they're needed.

**Comment by gabengaGamer** [comment]
Wow thanks ! Hopefully there will be more customizations in the future.

**Comment by Sherlock2004** [comment]
@aylaylay   In Source 1 there were two windows, one was for "noobs" where you could choose just a quick compilation or a full one. But there was also a window for advanced users, where you could create your own presets, for example, quickly compile without light, or set a low priority for the compilation process.

**Comment by gabengaGamer** [comment]
![image](https://user-images.githubusercontent.com/54669564/129427479-a6b62f2d-7171-46bc-bb79-b60543a6dc34.png)
vrad 3 continues to use 6 threads, instead of 12, a bug?

**Comment by Sherlock2004** [comment]
> ![image](https://user-images.githubusercontent.com/54669564/129427479-a6b62f2d-7171-46bc-bb79-b60543a6dc34.png)
> vrad 3 continues to use 6 threads, instead of 12, a bug?

I think so, because when the checkbox of 12 threads was turned on, I did not see 100% of the processor load, it continued to load as usual at half the power.

**Comment by aylaylay** [comment]
Should be fixed

**Comment by gabengaGamer** [comment]
yeah , it works now, thank you
