### ISSUE TITLE
Hammer GameObjects don't load properly on map load

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6817]
### Describe the bug

Adding a gameobject or prefab to the map, saving it, and opening it again creates broken gameobjects

### To Reproduce

1. Create map, place dummy gameobjects, save, close, open again

### Expected behavior

Should load as normal

### Media/Files

[hammer_gameobject_select.zip](https://github.com/user-attachments/files/17638454/hammer_gameobject_select.zip)

https://github.com/user-attachments/assets/35c53265-ff39-4b5c-b70b-d3c1a929109f

**Comment by MrBrax** [comment]
[sbox-dev.log](https://github.com/user-attachments/files/17638497/sbox-dev.log)

**Comment by handsomematt** [comment]
Think I got it with next build.

**Comment by MrBrax** [comment]
still getting empty gameobjects, but now they don't show up as anything at all when loading
