### ISSUE TITLE
[Hammer] Scaling some GameObjects doesn't work

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6819]
### Describe the bug

Scaling some GameObjects doesn't work

### To Reproduce

1. Create a gameobject
2. Create a prop component
3. Try to scale it
4. See that it is very janky and broken

### Expected behavior

It should work like in scene

### Media/Files

https://github.com/user-attachments/assets/ba5b8bd1-27a6-443d-bd34-c9a6cf40f8ed

**Comment by handsomematt** [comment]
Should work now

**Comment by Nolankicks** [comment]
Still is broken @handsomematt 

https://github.com/user-attachments/assets/4347299f-bd2c-4b2b-8b96-c2820d8292b7
