### ISSUE TITLE
Problems with creating physical models.

### ISSUE THREAD

**Issue by Sherlock2004** [Facepunch/sbox-issues#682]
There is a problem in ModelDoc: for example, we create a model of a table. We indicate the model of the table itself, and then indicate the collision model (the tabletop and legs are all 1 smd file).
![Q1DaUWGiji](https://user-images.githubusercontent.com/88171363/129425649-011427c7-a5ef-4246-80e8-6852d43e8ab5.png)
We press compile and get a static model, regardless of whether "Mass Override" is specified for it or not. Whether this model is listed in hammer as prop_physics or not. The model is still static.

But if you create virtual blocks of collision, then the model works fine as a physical object.  This also works if, for example, importing mdl, you can see that ModelDoc breaks the collision model into "elements".
![FUQyISbG2p](https://user-images.githubusercontent.com/88171363/129425833-298168eb-9fe9-4c81-84e1-1a9a0bfab636.png)

Maybe I don't understand something about the new engine, or maybe it's just a bug. 🤨

**Comment by DoctorGurke** [comment]
Need a physics Hull for physics props, not a mesh. Use the physics Hull File node and set import mode to Hull per element

**Comment by Sherlock2004** [comment]
> Need a physics Hull for physics props, not a mesh. Use the physics Hull File node and set import mode to Hull per element

If I choose hull, then I get a noob collision, which many people do for models in garry's mod. I want to get a full detail collision.
![ocpQZiZyl6](https://user-images.githubusercontent.com/88171363/129445475-9c6d4ac9-7e9e-42b0-a131-131d8240cc3a.png)

**Comment by DoctorGurke** [comment]
did you do the second step as well? set the import mode to Hull per Element

**Comment by Sherlock2004** [comment]
> did you do the second step as well? set the import mode to Hull per Element

Okay, let's figure it out. What should I "add" to start with ???
![bdN068rSYc](https://user-images.githubusercontent.com/88171363/129447060-3fef58fe-7e10-4647-ae5a-e53717b15790.png)

**Comment by DoctorGurke** [comment]
> Use the physics Hull File node and set import mode to Hull per element

**Comment by Sherlock2004** [comment]
> > Use the physics Hull File node and set import mode to Hull per element

I cannot understand how to "change the mode". I just get a window to select a mesh. Sorry if I'm very dumb, I have been working with Source 1 for 12 years, everything is much easier there)))

**Comment by Sherlock2004** [comment]
Hang up. I found =) Thanks for the help.
![nRH2vtbCmH](https://user-images.githubusercontent.com/88171363/129447204-4ef58f26-3c47-4bf6-8b92-e69246790d19.png)

**Comment by Sherlock2004** [comment]
@DoctorGurke  Sorry for one more question. If I create a collision in this way, I can no longer specify different materials for the individual parts, for example, the table top is wood, and the legs are metal?

**Comment by DoctorGurke** [comment]
are they separate meshes on your main model file? Then you can just make multiple nodes and select the respective mesh pieces for each node at the top. If they aren't individual pieces, I'd honestly just make the shapes manually using `PhysicsShapeBox`

**Comment by Sherlock2004** [comment]
> are they separate meshes on your main model file? Then you can just make multiple nodes and select the respective mesh pieces for each node at the top. If they aren't individual pieces, I'd honestly just make the shapes manually using `PhysicsShapeBox`

I don't have a regular smd file yet from Source 1, I just wanted to port a few of my models for review. It looks like to make a full-fledged collision you will have to use the DMX format with separate parts.

**Comment by DoctorGurke** [comment]
yea idk how the source 1 import works, I've never bothered. Just get used to manually making hulls for situations like these then, it'll work out fine
