### ISSUE TITLE
[REGRESSION] Map Drop Object is broken

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6826]
### Describe the bug

Map drop object is broken

### To Reproduce

1. Drag a local map from the asset browser in the scene
2. See that is does not work

### Expected behavior

It should work

### Media/Files

https://github.com/user-attachments/assets/2dde30b5-0d5a-470b-ad74-450841fe5213

### Additional context

Attempting to click on Map Control Widget spits a `Cannot divide by zero` error after dragging in the map
This started happening after hammer game objects was merged. Maybe a bug from that?

**Comment by aylaylay** [comment]
Should be fixed now
