### ISSUE TITLE
All meshes in a model get deselected randomly (Didn't use nextObject!! WTF!!!)

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6827]
### Describe the bug

Everytime models are moved or recompiled, all meshes get deselected turning it into an invalid model.
When that happens, there are no changes to the file itself, but we have to go in and manually enable each mesh individually and restart S&box for it to register.
This started happening with #6493 

This is what the .vmdl looks like after reenabling the meshes:
![Image](https://github.com/user-attachments/assets/98fe45f2-223b-48ea-a578-b6542980ff9a)

The file itself hasn't been changed in the past month, and it broke yesterday after I recompiled everything and uploading to sbox.game
This happens to everyone else as well, almost as if uploading it to sbox.game was the trigger

### To Reproduce

Example model that gets the errors:
[business_armor.zip](https://github.com/user-attachments/files/17651703/business_armor.zip)

Logs (Inspecting the model and creating it in game):
[sbox-dev.log](https://github.com/user-attachments/files/17651689/sbox-dev.log)

### Expected behavior

Every mesh name should be valid

### Media/Files

![Image](https://github.com/user-attachments/assets/c220282f-1a02-4ee0-a5e0-7cce182de089)

### Additional context

These are the errors getting reported on sbox.game after the update:

https://sbox.game/fish/deathcard/errors/view/129cdd3fd2132990c2abd02cf7d5de9947cad3db32a0290a7f8fb343f7f7558f
https://sbox.game/fish/deathcard/errors/view/d6eb5f29ecd38d5a433ee66b81b4a49c78e6d32cec646b44c03e59a5f00d6ad1

**Comment by handsomematt** [comment]
Look what you've done @Gmod4phun

**Comment by Nolankicks** [comment]
Should at least have some backwards compatibility. I don't think a change is good if it breaks games.

**Comment by wheatleymf** [comment]
> Changing it back now makes no sense, it would just break the stuff again,

I assume rolling back this change would break less stuff than leaving it as is. Death Card for example has hundreds of assets that suffered from this change, leaving all of them broken. Unless FP makes some sort of upgrader, (or solves this conflict with old assets in any other way) fixing all these assets one by one would take ridiculously long time. I guess there are other games that may probably suffer from this as well. 

Not sure how this change is worth breaking so much stuff. It wasn't an issue before and wasn't messing with any workflows from what I am understanding.

**Comment by NotGaylien** [comment]
Personally i kind of like this change i have had issues with it in the past and just dealt with it and didnt think about it after,
and i have ended up giving up on naming shit entirely because it is so annoying and i feel like im wasting time copying my blender object name to the mesh name over and over and over.

if its possible to get an upgrader for old models, it would be great.

**Comment by Gmod4phun** [comment]
> > Changing it back now makes no sense, it would just break the stuff again,
> 
> I assume rolling back this change would break less stuff than leaving it as is. Death Card for example has hundreds of assets that suffered from this change, leaving all of them broken. Unless FP makes some sort of upgrader, (or solves this conflict with old assets in any other way) fixing all these assets one by one would take ridiculously long time. I guess there are other games that may probably suffer from this as well.
> 
> Not sure how this change is worth breaking so much stuff. It wasn't an issue before and wasn't messing with any workflows from what I am understanding.

The issue before was that if someone in your group was using something like Max/Maya and exported an FBX, set up the model in modeldoc, and someone else in your team would have imported that model into Blender, did some changes etc, then exported it again, the modeldoc mesh filter list would have changed. (Max/Maya doesn't export mesh names, but Blender does).

Indeed if there was a way of upgrading it without fucking people over, that would be nice.

**Comment by Retroeer** [comment]
I think the change was and still is ultimately better for the game, I think an upgrader is reasonable but I don't know how much time it would take to even make something like that just for a couple hundred models, I don't think reverting the change is the best way forward though

**Comment by aylaylay** [comment]
So we've already discussed out of date models using wrong mesh names for the filter but I've made it so you wont get that nextObject spam, models without valid render meshes will use the error model.

**Comment by yuberee** [comment]
https://github.com/user-attachments/assets/5d65f66e-7e99-4be6-ac4e-5b20a80dd9f4

Ok made use of some mouse macros and got it done.
If some regression happens I'll let you know but hopefully this fixes it.

**Comment by aylaylay** [comment]
Models without render meshes will just not render now instead of being errors. Part of the reason I made it show error was so you could easily find the models that needed fixing but if for whatever reason you want to set a blank model then it will just be invisible instead of error.

**Comment by yuberee** [comment]
Makes sense, modeldoc already complains if you don't have any mesh selected so that's enough.
