### ISSUE TITLE
[ActionGraph] Unable to open actiongraph from asset browser

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#6841]
### Describe the bug

Im unable to open a Newley created action from the asset browser as every time i try todo so the error : `Constructor on type 'Editor.ActionGraphs.MainWindow' not found.` shows up in the console.

### To Reproduce

1. open a fresh project.
2. create a actiongraph in the asset browser.
3. right click on it and choose `open in editor`
4. observe that the error `Constructor on type 'Editor.ActionGraphs.MainWindow' not found.`  is being printed to the console.

### Expected behavior

To open action  graph.

### Media/Files

https://github.com/user-attachments/assets/82f1d7a7-ce5c-4322-b67c-297dfd21ef70

### Additional context

Ran a verify files pass and I still get this issue.

**Comment by Metapyziks** [comment]
Thanks for reporting!
