### ISSUE TITLE
Editor hangs when selecting many GameObjects

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#6845]
### Describe the bug

When selecting a large amount of GameObjects, regardless of how many components they have, the editor tends to hang.
Ranges from a small hitch when selecting 10-20 GameObjects to freezing for a minute when selecting 400.
Makes it hard to work with large maps with many objects such as trees or rocks.

### To Reproduce

1. Duplicate a GameObject, 200 should be enough
2. Click the first GameObject
3. Shift click the last GameOject to select all the ones in between

### Expected behavior

.

### Media/Files

https://github.com/user-attachments/assets/056e4526-bec9-4369-8047-d328243d63ed

### Additional context

AMD Ryzen 7 3800X
GTX 1060 6GB
16GB 2144Mhz Memory
SSD

**Comment by xezno** [comment]
Happens because we're recursively calling SelectItem, which in turn creates an undo event for every single select event. Passing skipEvents should fix this but didn't when I tried, I'll have a deeper look into it

**Comment by xezno** [comment]
also why do you have a 3800X and 2144MHz memory
