### ISSUE TITLE
[Main Menu] Ability to favorite/star games and have them quickly accessible

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6848]
### What can't you do?

With the current main menu there's no way to "favourite" a game, favourite'ing would be useful in the case of a "oh this looks cool, I'll play it later" or "this was awesome I want to be able to quickly access it", currently the main menu lets you see up to 4 games you've played recently, but I imagine sbox will eventually have more than 4 games

### How would you like it to work?

Either they could be shown straight on the home page, or have their own "favourites" tab, either way would work

### What have you tried?

nothing

**Comment by MrBrax** [comment]
there are favourites already

**Comment by Retroeer** [comment]
just checked and yeah you're right but i don't think theres anyway to actually search for them and if you can i honestly cant find it

**Comment by MrBrax** [comment]
they show up on the home page and when you open a game info box you click the heart to favourite

**Comment by Retroeer** [comment]
seems like the favourite button doesnt actually register until you close sbox and relaunch it, which i guess would be an issue
