### ISSUE TITLE
Couldn't find vsopen.exe

### ISSUE THREAD

**Issue by realpack** [Facepunch/sbox-issues#685]
**To Reproduce**

1. Open `sbox/tools/Console.exe`
2. Click on any line where there is a stack trace.
```fix
Couldn't Open File: C:\Program Files (x86)\Steam\steamapps\common\sbox\Addons\base\code\Entity\Player.cs
Couldn't find vsopen.exe
```

**Expected behavior**
vsopen.exe should have run

**Screenshots**
![image](https://user-images.githubusercontent.com/19867624/129470081-fc034645-7884-4988-bd80-758f4206e36c.png)

**Additional context**
`sbox/bin/win64/vsopen.exe` is present in the folder.
I think the path to the application is wrong somewhere.

**Comment by garrynewman** [comment]
This console is going to go away, probably.
