### ISSUE TITLE
[AssetBrowser] Select Image cant find .psd's

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#6854]
### Describe the bug

when within the `select image dialog` you will be unable to select any .psd files. 

### To Reproduce

1. Open up a project with .psd  assets
2.  Right-click  on a psd within the asset browser and select `create texture`
3. open the generated .vtex in the texture editor and then click on the asset within the sequences property.
4. observe that the select image dialog will open at the .psd asset directory where you wont see the .psd asset.

### Expected behavior

to be able to select a .psd as an image.

### Media/Files

![Image](https://github.com/user-attachments/assets/6f6e1082-3d38-44c2-80ca-fab9581f1452)

**Comment by aylaylay** [comment]
Fixed
