### ISSUE TITLE
[Sbox.Game] Dates have the wrong year

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6859]
### Describe the bug

On Sbox.Game dates are displayed wrong.

### To Reproduce

1. Open sbox.game
2. Take a look at some dates in the api sections or blog comments.

### Expected behavior

The dates should be displayed correctly

### Media/Files

![Image](https://github.com/user-attachments/assets/5ac965a8-7be2-40f6-8ff9-2d2de17b2bda)
![Image](https://github.com/user-attachments/assets/f4229587-08b7-4d6b-ba0f-f05ce976c5f9)

**Comment by garrynewman** [comment]
These are join dates, not post dates
