### ISSUE TITLE
Console chart looks terrible

### ISSUE THREAD

**Issue by realpack** [Facepunch/sbox-issues#686]
**Describe the bug**
The chart in the console is displayed horribly.

**To Reproduce**

1. Open `sbox/tools/Console.exe`
2. Start the game
3. See the chart

**Expected behavior**
Display normally?

**Screenshots**
![8veSNUAI3d](https://user-images.githubusercontent.com/19867624/129471577-289a7e69-5402-4833-9122-2dbb56e4a956.gif)

**Additional context**
No matter what I run, no matter how I run this chart is displayed like this. This has been going on since the installation of the game.
[I know I'm not the only one with the problem.](https://discord.com/channels/833983068468936704/833983435092525147/876367085826093096)

**Comment by Rohansi** [comment]
This console might just be binned in favor of the console built into the game. Is there any good reason to keep the external one?

**Comment by realpack** [comment]
> This console might just be binned in favor of the console built into the game. Is there any good reason to keep the external one?

I hadn't thought about it, but I like to use the console in a external window.

Sometimes I have to look in a external window when I'm testing something and can't take my eyes off the controls.
Or when the console doesn't open.  ¯\\_(ツ)_/¯
