### ISSUE TITLE
Don't show engine errors in game

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6861]
### What can't you do?

I don't think engine errors should show for the player. If Facepunch pushed a bad update with an NRE, I don't think the game should be blamed for it.

### How would you like it to work?

Have errors not show up

### What have you tried?

N / A

### Additional context

![Image](https://github.com/user-attachments/assets/89d96e0c-5eaa-4fe7-b563-5f2c0cde5402)

**Comment by handsomematt** [comment]
You guys are obsessed with hiding errors
