### ISSUE TITLE
Physics Issues - "Server time diff is massive - snapping time" hitches.

### ISSUE THREAD

**Issue by agincel** [Facepunch/sbox-issues#6865]
### Describe the bug

I'm the creator of [Marble Racer](https://sbox.game/waveparadigm/marble_racer) - I hopped on sbox today to check on the game, and found it to be basically unplayable for me. I haven't touched it in a week or two, so I'm not exactly sure when this issue started.

I mainly game on my 165hz monitor, which may be related (though, my attempts to play on my 60hz monitor didn't fare any better, so it's inconclusive). What I'm observing in the live game is that it feels like the physics system is trying to operate at a much higher tick rate than it is set to when on higher refresh-rate displays. I had it set to 60 tick in the game settings, but have since changed it to 50 tick, but on either setting, I found myself accelerating much faster than normal, and experiencing repeated "hitching." Each hitch is accompanied by a warning in the F2 log: `[GameMenu] Server time diff is massive - snapping time`

This issue seems to happen inconsistently for different users, but it is making my own game unplayable for me. All of my physics calculations for the game happen inside FixedUpdate calls, and it worked great at the time of the Game Jam, and in a bunch of the months since, so I'm not really sure what could have happened here that broke this. Have I set something up incorrectly, or is there some issue with the game engine? Any help would be greatly appreciated.

Most frustratingly, the game has no issues on my setup when played in editor, or when hosting in-editor and joining that hosted instance from within the editor using "Join with New Instance." This issue only occurs when playing the Published game, in the Player instance of sbox.

### To Reproduce

1. Play https://sbox.game/waveparadigm/marble_racer on a display with a High Refresh Rate, or on a normal display with Vsync off.
2. If you're like me, you'll experience frequent Hitching, accompanied by the message `[GameMenu] Server time diff is massive - snapping time` in the log.

### Expected behavior

This hitching should not occur, and the game should be playing identically between Editor and Published.

### Media/Files

https://github.com/user-attachments/assets/b3bcf85e-a1e9-4cf8-af1d-d8a9c2a5b600

**Comment by agincel** [comment]
By going into Exclusive Fullscreen on my 60hz monitor, the problem completely goes away. Going into Exclusive Fullscreen on my HFR monitor, or windowed mode on any monitor, sees this issue return. It seems totally related to refresh-rate shenanigans, but I can't imagine why what with using FixedUpdate across all my physics operations...

**Comment by somewhere-in-the-universe** [comment]
I had the same isseue when I was playing jumper yesterday

**Comment by aylaylay** [comment]
I'm not able to repro

**Comment by aylaylay** [comment]
Just managed to get it to happen, only seems to happen when you're not the host and frame rate is uncapped.

**Comment by agincel** [comment]
What's so odd is that it happens to me even when I'm the host, as seen in the video above. But happy there's a repro at all 😅

**Comment by kurozael** [comment]
This needs to be re-tested - I notice that you have a dedicated server up for Marble Racer, that will need to be updated as well :)

**Comment by agincel** [comment]
Funny enough that Dedicated Server belongs to someone else 😅 - but I'll give it a shot!

**Comment by kurozael** [comment]
> That dedicated is ran by me as I'm running wide array of dedi tests on different games actively. I tend to update the server every 3-6 hours or sometimes earlier then that, I would update more frequently but you guys push too many updates too fast and dedicated server is only on staging so one has to suffer...
> 
> I will answer to your response tho and tell you that I have updated the dedi and the issue of the speed etc still persists on dedi and non dedi as I've been playing marble for the past 2-3 days for a few hours and had it happen to myself or random others that just joined the lobby and they weren't host but clearly had the issue.

To clarify, you're saying that right now the issue is present? It's weird because I was able to reproduce the issue with framerate uncapped on 144hz monitor, but after my changes I couldn't reproduce it again.

**Comment by kurozael** [comment]
@PhasedExistence thanks for the information that's super useful - but seems like a separate issue to this one. If you check the video in this issue, is it safe to say that is fixed? Where the ball is jumping/stuttering/rubber-banding a little when moving with high FPS?

I will investigate the ball speed being tied to framerate as well.
