### ISSUE TITLE
Viewmodel shows in modeldoc game simulation

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#687]
# Describe the bug

Viewmodel shows in modeldoc game simulation

# Steps To Reproduce

1. Open ModelDoc
2. Start game simulation (play button)
3. see viewmodel

# Expected behavior

no viewmodel

# Screenshots

![image](https://user-images.githubusercontent.com/36124472/129474469-44f927a7-2a74-4582-9280-2847b4f1af02.png)

# Additional context

I have entered a local fork of sandbox gamemode previously.
ran via `sbox-dev.exe`

**Comment by aylaylay** [comment]
Just pushed a fix for this, please close the issue if it works for you and you're happy with it
