### ISSUE TITLE
Elements are misplaced in storage setting tab

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6871]
### Describe the bug

Elements are misplaced in storage setting tab

### To Reproduce

1. Open the settings storage tab

### Expected behavior

Elements should not be misplaced

### Media/Files

https://github.com/user-attachments/assets/22eb0a3b-1b2b-4442-bf7d-cf76160d6f1f

**Comment by DevulTj** [comment]
this was fixed at some point, looks fine to me![Image](https://github.com/user-attachments/assets/5f6204f0-10ba-4a27-91fb-62193946ea48)
