### ISSUE TITLE
Artifacts in windowed mode

### ISSUE THREAD

**Issue by somewhere-in-the-universe** [Facepunch/sbox-issues#6874]
### Describe the bug

When you switch to the windowed mode in settings, some "glitch" artifacts start appearing in random places

### To Reproduce

1. Go to settings 
2. Change video mode to `windowed`
3. Try doing something (starting a "Half life 2 - Transition" map (https://sbox.game/firsttest/transitionblock) in sandbox classic worked with me for example)

### Expected behavior

there should be no artifacts

### Media/Files

![Image](https://github.com/user-attachments/assets/8968d525-5103-4a46-9bc6-9eb3ed14bae9)
![Image](https://github.com/user-attachments/assets/ffe16c90-138f-48b6-8085-61444381e41f)

### Additional context

I'm running on windows 10. On a 1920x1080 monitor.

**Comment by handsomematt** [comment]
is this just when the resolution changes

**Comment by somewhere-in-the-universe** [comment]
> is this just when the resolution changes

No, just when you have the windowed mode (in my case at least)

**Comment by Nolankicks** [comment]
Nope. I have these too

**Comment by somewhere-in-the-universe** [comment]
forgot to mention, I started the half lise 2 transition map in sandbox classic
