### ISSUE TITLE
`ReadOnly` attribute does not work on GameObject and Component properties

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6875]
### Describe the bug

`ReadOnly` attribute does not work on GameObject and Component properties

### To Reproduce

1. Put a `ReadOnly` attribute on a GameObject or Component property
2. See that you can still edit it

### Expected behavior

You should not be able to edit it

### Media/Files

```cs
[Property, ReadOnly] public string ReadonlyString { get; set; }
[Property, Sync, ReadOnly] public RoundComponent CurrentRound { get; set; }
```

https://github.com/user-attachments/assets/bbaed81b-5534-4f16-9ae4-6d09907f6afc

**Comment by aylaylay** [comment]
Fixed
