### ISSUE TITLE
dev tools Scene is just black on arch linux

### ISSUE THREAD

**Issue by CoolPuppyKid** [Facepunch/sbox-issues#6888]
### Describe the bug

when using dev tools the scene is just black

### To Reproduce

Press Play
Make A Project
Open The Project
And The Scene Is Blank

### Expected behavior

i would just like to see my scene pls btw camera preview works fine the little window that pops up when selecting a camera

### Media/Files

![Image](https://github.com/user-attachments/assets/139cea9f-0099-4103-9e9c-56c9e2526b88)

### Additional context

OS: Arch Linux
DE: Hyprland
I Have A Nvidia 3060 Mobile
I Am Using Nvidia Drivers (not open source ones)

**Comment by Nolankicks** [comment]
@Kaydax

**Comment by Kaydax** [comment]
Linux is considered an unsupported platform currently. If you need support you should join the [official s&box discord](https://discord.gg/sbox) or ask / report issues on this issue thread instead https://github.com/ValveSoftware/Proton/issues/4940
