### ISSUE TITLE
Allow for lobbies to be more than just public/private

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6898]
### What can't you do?

Right now if I open a networking game it appears to everyone in the main menu. What if my game is co-op and people want to play only with their friends?

### How would you like it to work?

Any lobby that is open is shown to all players in the main menu currently... either give us a way to hide the lobby from the main menu, or some finer grain control about setting the lobby privacy settings.

### What have you tried?

...

### Additional context

Kind of similar to https://github.com/Facepunch/sbox-issues/issues/6314 , since our main menu handles only joining off of friends

**Comment by Nolankicks** [comment]
Would probably be fixed with this issue since you could define some sort of bool. https://github.com/Facepunch/sbox-issues/issues/6610

**Comment by matekdev** [comment]
If you set the lobby config to `LobbyPrivacy.FriendsOnly`, and then attempt to `Networking.QueryLobbies();`, the lobby will not show up. Unless there is a different way we should be fetching for available lobbies. The person I was testing with for sure was a friend on steam.

**Comment by kurozael** [comment]
In Friends Only mode - friends can only join your game they won't show up when queried. I think this is just the behavior of querying servers via Steam Matchmaking.

**Comment by matekdev** [comment]
So in our games, there is no way we could grab the list of open lobbies from our friends?

I'm kind of surprised steamworks doesn't support that. I guess using the lobby codes are the next best bet. 

Anyways, thanks!

**Comment by kurozael** [comment]
Thanks for the separate issue, will investigate options.
