### ISSUE TITLE
Entity.Velocity and Entity.AngularVelocity not updated on client

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#69]
**Describe the bug**

Entity.Velocity and Entity.AngularVelocity are both never updated on the client, at least when accessing from OnFrame they are always [0, 0, 0].

The same for PhysicsBody.Velocity and PhysicsBody.AngularVelocity too.

**To Reproduce**

```csharp
public class TestEntity : ModelEntity, IFrameUpdate
{
    public void OnFrame()
    {
        DebugOverlay.Text(WorldPos, $"Velocity");
    }
}
```

**Comment by garrynewman** [comment]
I think the client may have an estimated velocity for stuff like this, it should probably be returning that under certain conditions

- being called clientside
- physics based movement
- not predicted
