### ISSUE TITLE
PreRender no longer working as intended after Net 9 update

### ISSUE THREAD

**Issue by Michael4Numbers** [Facepunch/sbox-issues#6906]
### Describe the bug

Before the Net 9 update, I had a camera with a Vector3 Lerp function on PreRender so that it could take the latest position. It worked great.
As of the Net 9 update, the camera is now jittering, seems like something is wrong with the order of operations as putting the camera code in PostPhysics works. Could also be something wrong with the delta time.

### To Reproduce

Make a rigidbody cube. Make a Camera with an offset and add a component with the following script:

> [Property] public GameObject Player { get; set; }
> 
> protected override void OnPreRender()
> {
> 	var target = Player.WorldPosition + (Player.WorldRotation.Up * 32);
> 	WorldPosition = Vector3.Lerp(WorldPosition, target, 25f * Time.Delta);
> }

### Expected behavior

Camera should not be jittering similar to doing the update on PostPhysics.

### Media/Files

https://github.com/user-attachments/assets/b6899c6a-f5c4-41fa-9d73-46673b674073

**Comment by handsomematt** [comment]
More likely related to FixedUpdate changes today? @kurozael

**Comment by Michael4Numbers** [comment]
The camera has no parent, player is just any game object you assign in the inspector. In the video, I set it to a cube with a rigidbody.

**Comment by kurozael** [comment]
Could you provide the project as a .zip?
