### ISSUE TITLE
Allow us to kick connections

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6908]
### What can't you do?

It would be nice if either the host or dedicated server could kick connections. 

### How would you like it to work?

...

### What have you tried?

You can technically send an RPC to the client telling them to disconnect and change scenes.

### Additional context

https://discord.com/channels/833983068468936704/895597253316714497/1306109231933685792

**Comment by bub-bl** [comment]
Using the Connection connection directly can be more easy/intuitive ?
Like: `Connection.Local.Kick();` or `Connection.Kick(steamid);`

**Comment by matekdev** [comment]
Done!
