### ISSUE TITLE
A resizable Box based-light_omni

### ISSUE THREAD

**Issue by IntellectualPotato** [Facepunch/sbox-issues#691]
a separate entity thats like the light_omni. but with a box select similar to the light_ortho but in every direction so we  could make LED strips look nicer would be great! rather than copy and pasting a ton of normal light_omni's 

No idea if there's a solution to this already but i am posting this here just incase

![e7bc1bd5289348fda3887a6bf7aa43ed](https://user-images.githubusercontent.com/84039323/129495222-bc8bfa75-11f4-45f7-837e-ba8d5513a258.png)

**Comment by gabengaGamer** [comment]
Light rect, like in unreal engine 4: https://docs.unrealengine.com/4.26/en-US/BuildingWorlds/LightingAndShadows/LightTypes/RectLights/ it would be cool to see it in s&box

**Comment by MrBrax** [comment]
light_area?

**Comment by samzanemesis** [comment]
I believe any self illuminating material should have the same effect on vrad3

**Comment by DoctorGurke** [comment]
selfillum just produces glow with post processing, it won't cast any actual light

**Comment by samzanemesis** [comment]
VRAD3 code mentions it will take influence from self illumination, I'll investigate

**Comment by DoctorGurke** [comment]
🙏

**Comment by samzanemesis** [comment]
@ogniK5377  killed it, it's now on live
![image](https://user-images.githubusercontent.com/6563447/145710697-e5cccf65-6f7a-449e-abe2-d92d152cb036.png)
