### ISSUE TITLE
Add a way to change skins and bodygroups with ParticleModelRenderer

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#6913]
### What can't you do?

I'm unable to change the body group that a model is drawn with by ParticleModelRenderer 

### How would you like it to work?

Similarly to how you set them with skinned model renderer

### What have you tried?

I don't have any work arounds for this.

**Comment by aylaylay** [comment]
Added

![Image](https://github.com/user-attachments/assets/08cfcad9-61df-4efd-980b-e0fd82bccb7b)
