### ISSUE TITLE
Give access to hitboxes via collision or triggers instead of traces.

### ISSUE THREAD

**Issue by agray26** [Facepunch/sbox-issues#6914]
### What can't you do?

I am unable to use the hitbox system with anything other than ray traces. This results in simulating projectiles in the real world require quite a few extra steps.  Currently I am trying to simulate bullets by spawning a game object with a rigid body and gravity enabled and launching it through the world via the rigid body's velocity component. This allows the bullet to exist in real time but because I am not using traces, hit detection on hitboxes is rather difficult. 

### How would you like it to work?

Either with a collider or a trigger, when my game object comes into contact with a hitbox. Give me a way to get that hitbox. 

### What have you tried?

As a work around to this I tried 2 different approaches that both seemed to work decently well. 

First I tried to run a trace off of the object every physics tick to the place that the object _will be_ by the next one. This seems to be really inefficient to do and is rather complicated. I was not able to get it to work perfectly but it was close enough. 
`		var physics = GameObject.Components.Get<Rigidbody>( FindMode.EnabledInSelfAndDescendants );
		var traceResults = Scene.Trace.Ray( GameObject.WorldPosition, GameObject.WorldPosition + ((physics.Velocity * Time.Delta) * 2) )
			.UseHitboxes()
			.RunAll();
`
Secondly I record the objects current place in the world when its created. And on every tick I run a trace from its current position to the recorded one to check to see if it hits any hitboxes. Then I update the position after it runs. 
`		var traceResults = Scene.Trace.Ray( GameObject.WorldPosition, LastPosition ) 
			//.IgnoreGameObject(GameObject)
			.UseHitboxes()
			.RunAll();
`

**Comment by garrynewman** [comment]
These aren't really want hitboxes are for. If you want your bullets to be "physical", create a gameobject and run a trace in Update when it moves.
