### ISSUE TITLE
Align Origin missing from PhysicsHullFile and PhysicsMeshFile nodes

### ISSUE THREAD

**Issue by krotter0** [Facepunch/sbox-issues#692]
Align Origin X/Y/Z options are missing from PhysicsHullFile and PhysicsMeshFile ModelDoc nodes, making them inconsistent with render nodes.
Maybe from SkeletonFile, ClothProxyMeshFile and VSNAPFile nodes too? Not sure if these actually need them, I've never used them before.

**Comment by aylaylay** [comment]
I've just added this. Try it out and see if you can break it. If it works and you're happy with it please close the issue.

**Comment by krotter0** [comment]
It seems to align the collision based on the optimized mesh, which may cause misalignment issues with the render mesh. Here's an extreme example with a huge model. I couldn't find any other issue.

https://user-images.githubusercontent.com/65136069/130325869-f5a90185-c7e0-4343-a274-118beee3e8e8.mp4

**Comment by aylaylay** [comment]
Just pushed a fix, give that a try

**Comment by krotter0** [comment]
Works, but import scale is ignored now.

**Comment by aylaylay** [comment]
Looks like this has always been an issue, scale is applied differently for physics, I'll work something out

**Comment by aylaylay** [comment]
Should be good now

**Comment by krotter0** [comment]
Seems to be working perfectly, thanks.
