### ISSUE TITLE
Particle Model Renderer - Models Reset to Cube

### ISSUE THREAD

**Issue by Jammie3d** [Facepunch/sbox-issues#6924]
### Describe the bug

Since #6913 was implemented all existing particle model renderers have been reverted back to being cubes instead of the models that were specified.

### To Reproduce

1. Open `prefabs/particles/landing_impact.prefab` in the Micro Mayhem/platform-dash repo (I believe Layla has access)
2. Select the Burst GameObject and see that the choices section is empty and the model being rendered is a cube instead of `models/vfx/explosionmodel.vmdl`

### Expected behavior

The previously set model should be choice 1.

**Comment by aylaylay** [comment]
Sorry - should be fixed now

**Comment by Jammie3d** [comment]
Thanks!
