### ISSUE TITLE
Bone merged bones do not animate or follow their bone transforms at all

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#6929]
### Describe the bug

Bone merged bones do not animate or follow their bone objects at all

### To Reproduce

- merge any model
- move one of its bone transforms after setting it to procedural
- it does nothing
- animate the merged model
- it does nothing

### Expected behavior

- merge any model
- move one of its bone transforms after setting it to procedural
- it moves
- animate the merged model
- it moves

**Comment by aylaylay** [comment]
do you have an example model for this? all of our citizen clothing can't really make use of this

**Comment by ShadowBrian** [comment]
Yeah we have a hat with a little spinny top, will set it up so it auto-animates and put it here in a bit!

**Comment by ShadowBrian** [comment]
[spinny_cap.zip](https://github.com/user-attachments/files/17948010/spinny_cap.zip)
Should be able to drop that in a project and get a spinny cap in models/cosmetics/spinny_cap

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/66e666d3-0601-4494-a413-6ef38dd34cac

**Comment by ShadowBrian** [comment]
I'll give it a test as soon as it's up!

**Comment by ShadowBrian** [comment]
Works! Thanks layla 🐐
