### ISSUE TITLE
Running SetupPhysicsFromModel on a ModelBuilder model without physics crashes the game

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#693]
**Describe the bug**

Game crashes if you try to run SetupPhysicsFromModel() on a ModelEntity using a model created by a ModelBuilder that happens to be lacking physics shapes.

**To Reproduce**

```cs
[ServerCmd( "crashtest")]
public static void CrashTest( )
{
	ModelEntity entity = new ModelEntity();
	entity.SetModel( new ModelBuilder().Create() );
	entity.SetupPhysicsFromModel(PhysicsMotionType.Static);
}
```

**Expected behavior**

Don't crash, either ignore the request like it does with normal models or make all models throw an exception when SetupPhysicsFromModel is ran and there is no physics on the model since you're clearly doing something wrong if that happens.

**Additional context**

Seems to happen no matter the PhysicsMotionType.

**Comment by aylaylay** [comment]
I have pushed a fix for this, please close the issue if it works for you

**Comment by Leafdroid** [comment]
Works!
