### ISSUE TITLE
Add `ISceneCollisionEvents`

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#6935]
### What can't you do?

I want to make a GameObjectSystem that damages props when they impact each other.

### How would you like it to work?

Run these events directly after Component.ICollisionListener.

```c#
namespace Sandbox;

public interface ISceneCollisionEvents : ISceneEvent<ISceneCollisionEvents >
{
	/// <summary>
	/// Called when a collider/rigidbody starts touching another collider.
	/// </summary>
	void OnCollisionStart( Collision collision ) { }

	/// <summary>
	/// Called once per physics step for every collider being touched.
	/// </summary>
	void OnCollisionUpdate( Collision collision ) { }

	/// <summary>
	/// Called when a collider/rigidbody stops touching another collider.
	/// </summary>
	void OnCollisionStop( CollisionStop collision ) { }
}
``` 

### What have you tried?

I have a component with Component.ICollisionListener that I've added to every prop, but I'd rather make it a single GameObjectSystem.

### Additional context

CollisionSoundSystem could use ISceneCollisionEvents.OnCollisionStart to register collisions instead of CollisionEventSystem.

![Image](https://github.com/user-attachments/assets/747b9479-40be-4d8f-88d1-3e1abc2733b1)

**Comment by aylaylay** [comment]
If we add this, it likely wont be on IScenePhysicsEvents but on seperate scene event - we don't want to loop through all of these on every collision

**Comment by aylaylay** [comment]
For what it's worth, the way you originally did prop impact damage seems better than doing it with a gameobjectsystem.

**Comment by aylaylay** [comment]
Added
