### ISSUE TITLE
Pasting text to <TextEnty/> taking O(n^1.7) time

### ISSUE THREAD

**Issue by DaiterGG** [Facepunch/sbox-issues#6938]
### Describe the bug

Pasting text to a simple razor input field can stall the game (tested in editor) for a long time

### To Reproduce

1. Create a simple TextEntry component
![Image](https://github.com/user-attachments/assets/82110e0d-f6b1-46c2-833e-eab7f3ad03aa)
2. Paste some big string
3. Game frozen for a long time

### Expected behavior

Game really doesn't struggle to deal with those kind of strings and it shouldn't do it here.

### Additional context

I pasted 90.000 character string and it stalled for 200 seconds
and 180.000 did for 650 seconds

**Comment by solwllms** [comment]
This should be much faster now, down from several sec to just a few ms. Note that for _crazy_ long text you'll likely still run into our rendering limit for labels. That's something we might look at in the future.

**Comment by DaiterGG** [comment]
All good and fast. I don't need to display it so it should be fine
