### ISSUE TITLE
SFM game lights are gone.

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#694]
**Describe the bug**
In HLA and older builds of s&box can let you create game lights in SFM, but recently it got removed for some reason. 

**To Reproduce**

Try to create a point, directional, spot, or orthographic light in the Animation Set Editor... You can't.

**Screenshots**

s&box right now.
![image](https://user-images.githubusercontent.com/17112771/129496393-a91551e3-e8e6-448f-9417-dac189f0fec1.png)

From HLA and older builds of s&box.
![image](https://user-images.githubusercontent.com/17112771/129496409-d2c2d49b-d3f4-4808-a842-6486c2ad81ec.png)

**Comment by aylaylay** [comment]
So were they for sure showing up in sbox at one point?

**Comment by justynboi** [comment]
Yes.

![image](https://user-images.githubusercontent.com/17112771/129497096-699058e9-ed5a-4b06-81f6-63509ef4276f.png)

**Comment by aylaylay** [comment]
Cheers, I'll have a fix shortly

**Comment by aylaylay** [comment]
Pushed a fix, please close the issue if it works for you and you're happy with it. Will take about 10 mins for it to be pushed to steam.

**Comment by justynboi** [comment]
It works! Thank you, Cheers!
