### ISSUE TITLE
NavMesh generation with certain terrain completely fills up RAM

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6941]
### Describe the bug

NavMesh generation with certain terrain will fill up RAM. I've had success generating other terrain of the same size, so I think the issue might have to do with how rough the terrain is.

### To Reproduce

1. Open the attached project
2. Open repro.scene
3. Open the Performance tab of Task Manager
4. Attempt to generate a navmesh in repro.scene
5. See that your memory is being filled up

### Expected behavior

It should be possible for me to generate a NavMesh on a computer with 32 gigabytes of RAM without running out of memory.

### Media/Files

[navmesh_hang.zip](https://github.com/user-attachments/files/17787830/navmesh_hang.zip)

**Comment by lolleko** [comment]
I tried your scene with the latest changes, it doesn't crash for me anymore. Could you also please verify this on your machine?
Drawing the navmesh on that scene is quite laggy though, tracking this in https://github.com/Facepunch/sbox-issues/issues/6963

**Comment by chrisspieler** [comment]
It works on my machine now. Thanks!
