### ISSUE TITLE
No scenes load in the s&box editor on startup

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6942]
### Describe the bug

Whenever I open a project, the scene that would normally load with the project (the startup scene, or minimal.scene in the case of a new project) does not load. Instead, a nearly scene in a tab named Untitled Scene appears, and it doesn't seem to be linked to any scene file, so if I try to save it, it asks where I want to save it.

### To Reproduce

1. Open any project or create a new project
2. See the Untitled Scene tab

### Expected behavior

Whatever previous mechanism existed for choosing which scene to load on startup - Startup Scene in project settings, last opened scene in cookies, whatever - that should be restored.

### Media/Files
Here are the logs from when I tried to open a project:
[sbox-dev.log](https://github.com/user-attachments/files/17787843/sbox-dev.log)

_No response_

**Comment by timmybo5** [comment]
This is pretty much happening to almost everyone.

https://github.com/user-attachments/assets/957235f1-11b9-47e1-818f-da76679889a0
