### ISSUE TITLE
SkinnedModelRenderer.CreateAttachments creates GameObjects in the wrong positions without bones

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6944]
### Describe the bug

In a SkinnedModelRenderer, GameObjects created via ModelRenderer.CreateAttachments may be in the wrong position unless bone GameObjects were created.

### To Reproduce

1. Open the attached project
2. Open repro.scene
3. Click on the Citizen GameObject in the Hierarchy
4. Click on the Create Attachments checkbox in the Inspector
5. Click on `eyes` attachment in the Hierarchy
6. See that the attachment is in the wrong position
7. Play the scene
8. Click on the `eyes` attachment in the Hierarchy again
9. See that the attachment doesn't move at all even though the model is animated

### Expected behavior

Attachment GameObjects should never be created in an incorrect position. Once created, the attachment should follow the animations of the model.

### Media/Files

[create_attachments.zip](https://github.com/user-attachments/files/17787877/create_attachments.zip)

**Comment by aylaylay** [comment]
Okay so now instead of creating them as children of bone objects, they're children of the renderer root and transformed in animation update
