### ISSUE TITLE
Hammer Gameobjects: Assets in gameobjects do not get uploaded

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#6945]
### Describe the bug

Anything in hammer that is using the new gameobject system does not upload assets connected to them when you publish to sbox.game. Nothing appears on the list of assets when publishing. Anything using entitles like prop_static will upload as expected, but not the new gameobjects.

![Image](https://github.com/user-attachments/assets/c24af6a7-d996-48d3-9f6d-69913dbf7da6)

Here is an example of an object I'm using that won't upload the model when publishing to sbox.game.

![Image](https://github.com/user-attachments/assets/e6c2ca2a-f76c-450d-80ca-56b1d16e285b)

This makes publishing hammer maps with the new system very limited.

### To Reproduce

1. Make a hammer map
2. Add a new gameobject that has a model renderer or something similar.
3. Include an asset like a model
4. Compile 
5. Upload

### Expected behavior

Asset should show up in the map.

**Comment by handsomematt** [comment]
#6839
