### ISSUE TITLE
New project from game template doesn't link scene editor window to scene asset

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#6952]
### Describe the bug

If you create a new project using the "Game - Minimal" template, when the editor starts up the open scene editor window will have no name and will not be linked to the minimal.scene asset despite displaying the contents of that scene. When you try to save with Ctrl+S, a "Save As" window pops up.

### To Reproduce

1. Open the s&box editor launcher
2. Click the New Project button
3. Create a new project using the "Game - Minimal" template
4. Wait for the editor to start up
5. See that a scene editor window has opened, and the tab has no name
6. See that the scene contains the three purple cubes that should exist in minimal.scene
7. Press Ctrl+S to save the scene
8. See that a "Save Scene As..." window pops up.

### Expected behavior

When first opening a project created using the "Game - Minimal" template, the scene editor window that opens should be linked to minimal.scene such that pressing Ctrl+S will save to minimal.scene without prompting where to save.

### Media/Files

[sbox-dev.log](https://github.com/user-attachments/files/17792258/sbox-dev.log)
https://github.com/user-attachments/assets/b660600e-e7b4-4dcb-ad69-e2e0912cdec2

**Comment by magnusm1908** [comment]
Having same issue

The only way to sort of fix it is by saving the blank name scene as an entirely new scene.
(Not overriding an existing .scene)

But it still seems to mess with .sound files and remove any sounds from the sound list when reopening the project.
