### ISSUE TITLE
Enable Input Node

### ISSUE THREAD

**Issue by Moth-Soup** [Facepunch/sbox-issues#6958]
### What can't you do?

I can't disable all or one inputs for keyboard and controllers using the Actiongraph.

### How would you like it to work?

I would like a node similar to that of the one found in Unreal Engine where you can call Player Input and then be able to enable or disable input, for example lets say I want to disable attack1, I should be able to get the node Enable Input, choose the input (the options should be none, all, or whatever individual ones you have) and then be able to set it to false or true.

### What have you tried?

I have tried disabling the player controller but I can still use inputs like attack1 or flashlight.

**Comment by Metapyziks** [comment]
You'll want a property like Can Attack on your component, then check it in your graph like this:

![Image](https://github.com/user-attachments/assets/3eb7414a-fb4d-4128-b8d7-1bf4ac45aff3)
![Image](https://github.com/user-attachments/assets/3ffb8ebf-b086-4de2-b541-8678cf2ff17c)
