### ISSUE TITLE
Enum flag properties broken

### ISSUE THREAD

**Issue by kEllieGit** [Facepunch/sbox-issues#6960]
### Describe the bug

Adding the [Flags] attribute to an enum and having an instance of that enum is broken.
Works as expected without the flags attribute.

> Example:
![Image](https://github.com/user-attachments/assets/beb26125-4e09-44d1-b71a-16699595b487)
![Image](https://github.com/user-attachments/assets/5955e645-2f78-41d3-8265-b9c0fec7f2a0)

### To Reproduce

1. Add the [Flags] attribute to an enum
2. Make a property with the type of the enum
3. Try to change it in the editor (no options show up!)

### Expected behavior

Being able to select multiple enum value flags.

**Comment by Metapyziks** [comment]
[Flags] enums should have values that are all powers of 2, does it work if you change it to:

```csharp
[Flags]
public enum LinkerType
{
    Hallway = 1,
}```
