### ISSUE TITLE
[REGRESSION] Opening some prefabs are broken

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6961]
### Describe the bug

Opening some prefabs are broken

### To Reproduce

1. Open a prefab

### Expected behavior

The prefab should open

### Media/Files

https://github.com/user-attachments/assets/003e0cc7-12dc-4cb3-970f-51eea62bde0f

**Comment by Nolankicks** [comment]
*Assigned @handsomematt*

**Comment by Nolankicks** [comment]
NOTE: It's only the first prefab or scene in each folder

**Comment by CarsonKompon** [comment]
I think what's happening here is the Scene you're trying to open IS open in a window that isn't visible (since it was open when you closed your last session and it wasn't restored properly)

If I'm correct, this could have been fixed with the commit I just pushed. Let me know

**Comment by Nolankicks** [comment]
Thanks! 😊
