### ISSUE TITLE
[Dedicated Server] Local libraries don't compile properly

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6964]
### Describe the bug

Local libraries don't compile properly 

### To Reproduce

1. Start a dedicated server for a local .sbproj with libraries 
2. See that it doesn't compile

### Expected behavior

They should compile

### Media/Files

![Image](https://github.com/user-attachments/assets/abccc2e2-3b1f-4e2d-aa93-68daa43b608a)
![Image](https://github.com/user-attachments/assets/c156b99e-c62d-44da-95f3-7808e503a5cf)
![Image](https://github.com/user-attachments/assets/faac0ca7-f045-4561-9e45-a3134c1e6a38)

**Comment by kira0x1** [comment]
ive been getting this aswell

**Comment by MrBrax** [comment]
this also seems to include the editor project

**Comment by kurozael** [comment]
Should be sorted in the next build 👍

**Comment by MrBrax** [comment]
still seems to error on editor project, is that a separate issue?

**Comment by kurozael** [comment]
@MrBrax Can you send me a project that I can run a dedicated server for so I can see the issue you're getting with editor project?
