### ISSUE TITLE
string properties marked with TextArea don't update correctly

### ISSUE THREAD

**Issue by johncosfm** [Facepunch/sbox-issues#6967]
### Describe the bug

When setting a value in code, a simple string property will update in the editor as expected, but if its marked with the TextArea attribute it wont update.

### To Reproduce

1. Create string marked with [Property, TextArea]
2. Set its value in code
3. Observe that it does not update in the inspector unless the whole area is redrawn

### Expected behavior

It should update itself in the same way that a string not marked with TextArea updates

**Comment by aylaylay** [comment]
Fixed
