### ISSUE TITLE
Classes with duplicate names but different namespaces cause hotreload errors

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#697]
**Describe the bug**

Make 2 classes in your project with the same name.

Namespace.Class1
Namespace.Example.Class1

Will cause warnings on hot reload and then NRE when trying to rejoin the server. Wont let you join the server after you leave it and you have to restart the client.

**Additional context**

NRE comes from `Sandbox.Entity.ToString()` (presumably because hot reload failed and leaves entities in a broken state)

Warning comes from `An item with the same key has already been added. Key: Namespace.Class1` and `EventSystem.SwapTypes`

**Comment by Jake-Rich** [comment]
Additional Info: May be caused / also triggered by singleton entities that create themselves in their static constructor.

```
public class Example : Entity
{
    public static Example Instance { get; } = new Example();
}
```

**Comment by Metapyziks** [comment]
Are you still having this issue? I've been unable to repro it so far, using this example:

```csharp
public class NameCollisionTest : Entity
{
	public static NameCollisionTest Instance { get; } = new NameCollisionTest();
}

namespace Example
{
	public class NameCollisionTest : Entity
	{
		public static NameCollisionTest Instance { get; } = new NameCollisionTest();
	}
}
```

This seems to hotload fine, with those static fields having the correct instances in them.

**Comment by Metapyziks** [comment]
Found the issue, the `EventSystem.SwapTypes` warning was a good clue. Thanks for reporting!
