### ISSUE TITLE
Give us more control over the Voice Transmitter component

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6973]
### What can't you do?

We can't set manually the distance attenuation, occlusion, occlusion radius, sound position, and more

### How would you like it to work?

Give more control on it

### What have you tried?

Above

**Comment by johncosfm** [comment]
Would also be nice to be able to directly access lip sync for games that dont use skinned model renderer or that have mouths that arent controlled by flexes. Perhaps it might make sense to just expose the sound handle?

**Comment by bub-bl** [comment]
> > [@johncosfm](https://github.com/johncosfm) Expose soundhandle can be good, but it is controlled in many ways in the voice transmitter component. A lot of values are overriden in OnUpdate
> 
> maybe just a readonly way to access the lipsync bit then

I will close this issue tomorrow if we don't have any response about lipsync, You can create an issue for that too

**Comment by aylaylay** [comment]
Lipsync is on there?

**Comment by bub-bl** [comment]
> > [@johncosfm](https://github.com/johncosfm) Expose soundhandle can be good, but it is controlled in many ways in the voice transmitter component. A lot of values are overriden in OnUpdate
> 
> maybe just a readonly way to access the lipsync bit then

If think the property is called `Visemes` in the voice component, so i can close this issue.
Thanks Laylad
