### ISSUE TITLE
Solo/Mute options in mixer do nothing

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6974]
### Describe the bug

When muting a mixer, the mixer continue to play the sound

### To Reproduce

- Create a mixer
- Mute them
- Add a sound point in the scene and apply the mixer on it

### Expected behavior

The mixer must be muted

**Comment by Gmod4phun** [comment]
duplicate of [#6476](https://github.com/Facepunch/sbox-issues/issues/6476)

**Comment by aylaylay** [comment]
Done
