### ISSUE TITLE
Remove input filter for the material editor

### ISSUE THREAD

**Issue by Andiq** [Facepunch/sbox-issues#6981]
### What can't you do?

So right now the material editor by default only wants materials named _color.png, _roughness.png and so on.

### How would you like it to work?

I think that can cause confusion and isnt really necessary. Why not make it so it shows you every .png in the folder.

### What have you tried?

Doing it trough file explorer and changing the filter to show all files.

**Comment by handsomematt** [comment]
![Image](https://github.com/user-attachments/assets/23c17e6e-db65-4fae-8d44-89c12aadad73)

?
