### ISSUE TITLE
Ability To Get All Entity Tags

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/sbox-issues#699]
### **What can't you do?**
Currently there is no way to obtain all the tags that an entity has, you can only check for a specific tag by using `Tags.Has()`

### **How would you like it to work?**
Basically a new method, could be called `Tags.GetAll()` or whatever people want it named. It could return a list that we can enumerate. 

_Thank you!_

**Comment by robotboy655** [comment]
`Tags.List` should do exactly what you want.

**Comment by DrVrej** [comment]
> `Tags.List` should do exactly what you want.

Yep that was exactly my request, happy to see it added, thank you. 👍
