### ISSUE TITLE
Right clicking a sound file and creating sound event is broken

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6991]
### Describe the bug

It either creates an completely empty json file or a sound event file without the selected sound file. This also happens occasionally for all resources when creating them, just making an empty json file `{}` that can't be edited until editor restart.

### To Reproduce

1. Right click a sound file
2. Create sound event

### Expected behavior

Resources should be created normally like before

### Media/Files

[sbox-dev.log](https://github.com/user-attachments/files/17871233/sbox-dev.log)

**Comment by Retroeer** [comment]
yeah i had this happen when trying to duplicate one of my game resources

**Comment by matekdev** [comment]
This is still occurring, very annoying!

**Comment by TiO2EvoLve** [comment]
I don't know why, but the background music of my previous games has become intermittent

**Comment by MrBrax** [comment]
seems like i'm getting this again
