### ISSUE TITLE
expose Pixmap, OpenFileDialog and SaveFileDialog to game context

### ISSUE THREAD

**Issue by stellawisps** [Facepunch/sbox-issues#6997]
### What can't you do?

I cannot open file dialogs outside of an editor project with EditorUtility, nor can I make or save Pixmaps.

### How would you like it to work?

when whitelist is disabled, you can call File.OpenFileDialog and File.OpenSaveDialog to access paths and save files.
Make it so that pixmaps can be created and saved as normal in a game project. 

### What have you tried?

DLLImporting user32.dll and calling the functions directly

### Additional context

I'm currently working on a piece of software to make textures and this is a big blocker, but I can understand why for platform games these would not want to be exposed. 

Maybe there needs to be a subset of functions that games can run if whitelist is disabled in general.

**Comment by MrBrax** [comment]
pixmap would be very useful to resize images

**Comment by handsomematt** [comment]
ask for a way to resize images or textures then, pixmap is qt
