### ISSUE TITLE
ConsoleSystem.Run doesn't convert objects to strings

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#7]
`public static ConsoleResult Run(string command, params object[] arguments)` takes objects as parameters but tries to cast them to a string meaning it will throw exceptions unless you pass in a string.

`ServerCmd` will automatically parse string -> type but `Angles.ToString()` is a different format than `Angles.Parse()` making you manually serialize angles if you want to pass them as a command. By that same token, passing rotation directly would be nice.

**Comment by garrynewman** [comment]
Thanks, should work now
