### ISSUE TITLE
Sound.SetPitch from PlaySound has no effect

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#70]
**Describe the bug**

Can't set the pitch dynamically on any sounds. I tested specifically on the returned Sound object from Entity.PlaySound.

https://user-images.githubusercontent.com/1388267/116650773-cd928280-a979-11eb-9602-4cdbdb14efe3.mp4

**To Reproduce**

```csharp
[Library( "ent_bouncyball", Title = "Bouncy Ball", Spawnable = true )]
public partial class BouncyBallEntity : Prop, IUse
{
	public override void Spawn()
	{
		base.Spawn();

		SetModel( "models/citizen_props/beachball.vmdl" );
		SetupPhysicsFromModel( PhysicsMotionType.Dynamic, false );
	}

	public bool IsUsable( Entity user )
	{
		return true;
	}

	static SoundEvent PopSound = new("sounds/balloon_pop_cute.vsnd");

	public bool OnUse( Entity user )
	{
		PlaySound( PopSound.Name ).SetPitch(Rand.Float(0, 1));
		return false;
	}
}
```

**Comment by aylaylay** [comment]
This should be fixed, you can also set the pitch range for a random pitch between min and max

**Comment by ogniK5377** [comment]
While this works, pitch can not be adjusted on the fly. I was wondering if there could be a follow up to this where pitch can be changed whilst the sound is playing

**Comment by aylaylay** [comment]
Sound.SetPitch now works at any point during playback. Sound.SetRandomPitch can set the initial random pitch

**Comment by handsomematt** [comment]
nice one mate dead lovely x

**Comment by o-brkyr** [comment]
Can't replicate this in the latest build - the following will replay a sound at a pitch, rather than play it once and change pitch during playback
```cs
private Sound localSound {get;set;}

[GameEvent.Tick]
public void onTick()
  if (variableInitiallyTrue) {
     localSound = PlaySound( "servo.move" );
     variableInitiallyTrue = false;
  }
  localSound.setPitch(someFloat);
}
```
