### ISSUE TITLE
[Hammer] Control is blocking with changing keyboard's language

### ISSUE THREAD

**Issue by 5FB5** [Facepunch/sbox-issues#700]
I have a problem that has been bugging me since the HLA days. As I found out, if you change the keyboard layout in Hammer, the control is blocked. You can't move the camera, apply hotkeys, etc. Since I'm Russian, if I change the keyboard language from English to Russian, I can't use Hammer normally

**Comment by robotboy655** [comment]
What key combo are you using to switch languages? When using WIndows Key + Space I have no problems.

**Comment by 5FB5** [comment]
Shift + Alt

**Comment by robotboy655** [comment]
Oh, you mean that you cannot move in the 3D view on the Russian keyboard layout, got it.

**Comment by robotboy655** [comment]
This should be fixed with the next game update. Please verify if it is fixed for you and close this issue if it is.

**Comment by 5FB5** [comment]
Yeah, it works. Thanks!
