### ISSUE TITLE
Let [EditorHandle] Accept Material Icons

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7004]
### What can't you do?

A component can accept Material Icons for their [Icon], but not for EditorHandle, I was trying to use the touch_app icon to convey a component the player could interact with, I could just download this and convert it, but it would be a great time save to be able to just path it directly

### How would you like it to work?

[EditorHandle] should accept either a path to the file or a Material Icon.

### What have you tried?

Nothing

**Comment by Retroeer** [comment]
https://github.com/user-attachments/assets/8880e96a-5afd-43fe-bd69-e8fcb728da6c
this is what it would look like, pretty nice honestly

**Comment by DevulTj** [comment]
![Image](https://github.com/user-attachments/assets/6293839d-a72f-4475-8526-25033314834b)

It's already a thing

`[EditorHandle( Icon = "touch_app" )]`

**Comment by Retroeer** [comment]
wtf

**Comment by Retroeer** [comment]
Seems like these icons are just oddly smaller than most of the gizmo icons? They are also at a weird grey instead of a white, which makes them look rather out of place with the rest of the editor stuff, it's not a huge issue but it'd be nice if they could fit better @DevulTj 
![Image](https://github.com/user-attachments/assets/e13db724-b71b-40d5-83b1-68a59dad52aa)
