### ISSUE TITLE
Something about Tag.Set (and Add/Remove) causes TriggerEnter and Exit to lose its mind

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7005]
### Describe the bug

If you have the following code
```
    public void OnTriggerEnter( GameObject other )
    {
        Log.Info($"GameObject: {other.Root.Name} has entered.");
        other.Root.Tags.Set("testtag", true);
    }

    public void OnTriggerExit( GameObject other )
    {
        Log.Info($"GameObject: {other.Root.Name} has left.");
        other.Root.Tags.Set("testtag", false);
    }
```
The trigger will lose the plot and start spouting the enter and exit log over and over

### To Reproduce

1. Download the [colliderrepro.zip](https://github.com/user-attachments/files/17879607/colliderrepro.zip)
2. Move the "MOVE ME INTO THE RED CUBE" GameObject into "The Red Cube"

### Expected behavior

The Tag should be getting added to the cube when entering, and removing upon exit

### Media/Files

https://github.com/user-attachments/assets/255dde65-5876-4545-a37c-3051beb4cabc

**Comment by aylaylay** [comment]
Sorry, only just seen this

**Comment by aylaylay** [comment]
Fixed
