### ISSUE TITLE
All converted prefab GameObjects get deleted after you undo after deleting a GameObject

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7009]
### Describe the bug

If you convert a bunch of shit to prefabs, and then delete a gameobject, it just deletes everything you converted

### To Reproduce

1. make a bunch of converted prefabs
2. delete a gameobject
3. undo

### Expected behavior

the converted prefabs should not be getting deleted

**Comment by lolleko** [comment]
I think this is fixed, i couldn't  really reproduce the "it just deletes everything you converted" part but I am hoping this means it is fixed.
Let me know if it isn't fully fixed and maybe provide some more detailed repro steps in that case.
