### ISSUE TITLE
Sandbox.NetworkObject.GetOrCreate NRE popping up recently

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#7014]
### Describe the bug

https://sbox.game/apetavern/micromayhem/errors/view/07bbe452e1a74684ce5c42e81f2515cffffa6e0289175ae20f064de4443f85d6

These issues started popping up on our game - we are not sure if we changed something that is causing it, or if it's a networking related bug.
These are quite rare to show up, and are unable to reproduce, so we are unsure how much they are affecting the game.

The code that produces this error is here:
```cs
var variantGameObject = variant.IsValid() ? variant.Clone( Vector3.Zero ) : Variants.FirstOrDefault();

if ( !variantGameObject.IsValid() )
	return null;

variantGameObject.NetworkSpawn();
```

This code is called in OnStart and is only run on the host.

Please let me know if you want access to the Micro Mayhem repository!

### To Reproduce

Unknown

### Expected behavior

No error

**Comment by trundlr** [comment]
@kurozael fyi

**Comment by kurozael** [comment]
Could it be that you're calling NetworkSpawn on a prefab? What does `Variants` contain?

**Comment by trundlr** [comment]
I do see an edge case where it could be a prefab, in the event the selected Variant is not Valid it tries to fallback to another, and we don't clone it. Bug on our side. Is there any way there could be a way to notify the developer when this happens through a specific error message? Thanks!!
