### ISSUE TITLE
SoundHandle needs `FollowParent` to be true in order for it to follow the sound.

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#7015]
### What it is?

If you want a sound handle to follow a parent you need to do the following...
```csharp
handle.FollowParent = true;
handle.SetParent( GameObject );
```

### What should it be?

Why do we need the extra bool that needs to be toggled on? If there is a parent, follow it, if not don't.

**Comment by garrynewman** [comment]
Because you might have parented it just because you want it to die when the parent does, and don't want to follow it.

**Comment by matekdev** [comment]
I feel like you should just force people to handle that case themselves. The reason this API feels so weird is that it behaves differently than what you'd expect compared to GameObject parenting.

Feel free to close this if you disagree, however, I still think that this is an odd API design.

**Comment by ceitine** [comment]
I agree with matek, I'd imagine it'd be shrimpler to be aboe to just `SetParent( null )` to stop following and `SetParent( obj )` to start following.

**Comment by garrynewman** [comment]
The sound having a parent is more than its position though. It controls its life. It means you can call stopsound on the gameobject to stop all its child sounds.

**Comment by garrynewman** [comment]
They're coded in a way that means that their parents don't have to be GameObjects. I believe they follow when you do go.PlaySound

**Comment by matekdev** [comment]
@garrynewman You can probably close this issue unless you change your mind. 

I have an unrelated follow-up for you, would it be unreasonable to have a property on `SoundHandle` so that it stops itself if the parent is destroyed? Unless my testing is wrong, I believe you need to call `GameObject.StopAllSounds()` to stop all children sounds.
