### ISSUE TITLE
Model.LoadAsync throws NRE when passed a null string

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#7019]
### Describe the bug

https://sbox.game/apetavern/micromayhem/errors/view/48892a02792160973bc07c0b9ef99d3b7a384310039e606aba131497b91ca8ef

NRE is thrown when Model.LoadAsync is called with a null string as the modelpath

### To Reproduce

Call Model.LoadAsync with a null string

### Expected behavior

Return a null model or provide a clearer error message

**Comment by aylaylay** [comment]
Model.LoadAsync fails but it doesn't NRE?

**Comment by trundlr** [comment]
> Model.LoadAsync fails but it doesn't NRE?

It does NRE, but I'd rather get a null model back or a more descriptive error message

**Comment by aylaylay** [comment]
> > Model.LoadAsync fails but it doesn't NRE?
> 
> It does NRE, but I'd rather get a null model back or a more descriptive error message

It doesn't, I tried it, I also have the source code
