### ISSUE TITLE
Confirmation dialog after pressing the "exit button"

### ISSUE THREAD

**Issue by PotatoTheTurtle** [Facepunch/sbox-issues#702]
**What can't you do?**
I was not able to cancel out of quitting the game.

**How would you like it to work?**
I would like to request or suggest a confirmation dialog after pressing the "exit game" button on the top right side of the main menu screen. The button also only indicates that it's an exit button via the "logo", ie. does not have any "context" text when hovering over it, but I suppose that isn't the main concern.

**What have you tried?**
Not pressing it, but I keep on doing it.

**Additional context**
It's frustrating when it's accidentally pressed and a possibility to cancel should be provided via some type of a confirmation dialog.

**Comment by NotGaylien** [comment]
what if the person is f...f...fre*ch or russian or even worse?
they wont understand either, i think we should have a long list of words and it should say exit in every language when you hover over. 
Otherwise they will also keep pressing the alluring button too!!!
