### ISSUE TITLE
Collider - Plane doesn't work with RigidBody

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7028]
### Describe the bug

If you try and use Collider - Plane with Rigidbody it'll just phase through the map
Apparently a Box Collider with a Z of 0 is (kind of) fine though

### To Reproduce

1. Make a GameObject
2. Give it a RigidBody
3. Give it a Plane Collider
4. hey wait its not supposed to phase through the map 

### Expected behavior

The Plane Collider should work for Rigidbody

### Media/Files

https://github.com/user-attachments/assets/52a0ec63-b935-4950-a426-8b598c80b8df

**Comment by aylaylay** [comment]
It's not meant to, plane is a mesh, meshes are static
