### ISSUE TITLE
Dragging a Rigidbody by the gizmo should temporarily disable motion

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7029]
### What can't you do?

If you try and move a Rigidbody while in scene view in-game, it's kind of weird, it'll snap to wherever the gizmo is but then immediately start falling even if you're still holding it. 

### How would you like it to work?

When you start to drag a gameobject with a rigidbody, it should tick Motion Enabled to false, and then back to true when you let go

### What have you tried?

Disabling motion and then dragging, but this is lame and wastes a nanosecond of my time :(

**Comment by aylaylay** [comment]
"it should tick Motion Enabled to false, and then back to true when you let go" this is an awful idea. I'll work on a way to transform them better but it wont be through modifying properties like that.

**Comment by Retroeer** [comment]
Was just a suggestion, I wasn't sure how you'd actually do it

**Comment by aylaylay** [comment]
https://github.com/user-attachments/assets/8dbe5b58-25f2-4ff4-aaa0-1524988535a8
