### ISSUE TITLE
[ActionGraph] Add OnTriggerEnter/Exit(GameObject) to Triggers ActionGraphs

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7036]
### What can't you do?

Right now you can only get the Collider, but we've since gotten the ability to just check for a GameObject, which I'm finding myself needing, since right now its checking for colliders, which my player has multiple, so it's playing ActionGraph events multiple times sometimes

### How would you like it to work?

Add a new GameObject variant of TriggerEnter/Exit

### What have you tried?

Nothing

**Comment by Metapyziks** [comment]
I feel like you'd get the same problem with GameObjects that have multiple child objects with colliders entering your trigger. Would you want it to trigger just for the root GameObject, or for each child?

Instead I think it should be up to your game to decide how to handle each event. Like in your example here, you should check if IsDestroyed is true before doing the other stuff.

![Image](https://github.com/user-attachments/assets/87b773e1-01cb-41eb-8e1d-de9c9bcfa9e0)

**Comment by Retroeer** [comment]
OnTriggerEnter/Exit(GameObject) only returns the root gameobject, regardless of how many children that have colliders are on it, it's very useful
If you wanted it to trigger for each child that's what the collider version is for

**Comment by Metapyziks** [comment]
Oh I didn't realize we already had those for C#

**Comment by Retroeer** [comment]
Haha all good, I should've made it clearer

**Comment by aylaylay** [comment]
I think he means expose the new event I added for gameobjects, I purposefully don't mark new functions as actiongraph until someone asks for them.

**Comment by aylaylay** [comment]
Added

**Comment by Retroeer** [comment]
thankies
