### ISSUE TITLE
ModelDoc: Add support for 'underlay' delta animations (aka Source 1 predelta)

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#704]
**What can't you do?**
I am trying to import models which use a different delta type animations (aka 'predelta').

In S&Box, there is currently no way to use the 'predelta' type animations that Source 1 could handle, only 'delta' animations. I am not sure what is the proper name for this type of animation, neither was Valve apparently. The 'predelta' animations are calculated with a slightly different code.

**How would you like it to work?**
It could be a separate option, like the Worldspace blend, mutually exclusive with it and the Delta option, or a separate parameter for the Delta option itself (internally, Source 1 used a STUDIO_DELTA flag for 'predelta' sequences, and also an extra STUDIO_POST flag for 'delta' sequences).

**What have you tried?**
Probably everything :/

**Additional context**
Source 1 showcase of a 'predelta' animation, and the lack of that option in Source 2
https://user-images.githubusercontent.com/5991682/129633758-66c2486f-9325-4e8c-b849-50815ab788d9.mp4

Two sample models for S&Box, with the default animation, and a 'baked' version of the animation (how it should look like).
https://user-images.githubusercontent.com/5991682/129634037-f1f57daf-d47a-4ec4-9e95-32bba209d0a7.mp4

The 'baked' animation was achieved by compiling the model for Source 1, importing the model into Source Film Maker, playing the correct animation, exporting from SFM into Blender, cleaning up the animation and exporting as 'baked' version. Having the ability to have 'predelta' support in S&Box would help me (and possibly others) save a lot of time when importing models that use this type of animations.

Here is an archive containing the models and their animations for testing: 
[sbox_predelta_test.zip](https://github.com/Facepunch/sbox-issues/files/6995650/sbox_predelta_test.zip)

I am unsure about the Source 2 implementation of delta animations, although I guess it is pretty similiar to Source 1. Here are some relevant code sources from the Source 1 implementation, which could hopefully be used to add this into Source 2 (if it isn't present already and is disabled for some reason):

Subtract base animations: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/utils/studiomdl/simplify.cpp#L1111

QuaternionSMAngles and QuaternionMAAngles: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/utils/studiomdl/simplify.cpp#L42

QuaternionSM: https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/bone_setup.cpp#L1170

QuaternionMA: https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/bone_setup.cpp#L1197

**Comment by garrynewman** [comment]
I don't know what any of this means @MaxLebled

**Comment by MaxLebled** [comment]
And quite frankly, neither do I. I never used this feature back in the Source 1 days. I contemplated closing the issue as "not planned", but figured that because it's well documented (example model and links to relevant S1 code), there might be a chance @aylaylay would be able to get to it.

That being said it seems extremely niche and only relevant to importing existing S1 assets, so... is it really worth the trouble?

**Comment by Gmod4phun** [comment]
I guess it is kinda niche, the models are originally from Unreal Engine 4, so I guess they probably have a name for that kind of animation but I havent been able to find any info regarding that. From my limited understanding of the delta/predelta, it has to do something with the order of the animation layering. I am not sure how troubling it would be to implement this, and it would be really nice to have, but if it proves too much trouble, no hard feelings.

**Comment by aylaylay** [comment]
We shouldn't be adding new animation nodes we don't understand just to be able to port animations.
