### ISSUE TITLE
Leaving every game gives a sequence error

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#7043]
### Describe the bug

Leaving every game gives a sequence error

### To Reproduce

Leave a game

### Expected behavior

N/A

### Media/Files

![Image](https://github.com/user-attachments/assets/6006bab8-ec13-4536-9a37-f364c8ff46b2)

**Comment by Metapyziks** [comment]
Haven't been able to repro this yet, could you record a short video of it?

**Comment by Nolankicks** [comment]
Seems like it was fixed overnight. Ubre and I both got it playing a few different games
