### ISSUE TITLE
IsProxy issues

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#7044]
### Describe the bug

As reported today, IsProxy behaves differently on live versions of a game, returning false on networked objects that have a different owner.

### To Reproduce

**In editor:**
1. Copy the code below into a component
2. Assign the component to a GameObject (I use one of the cubes in the default scene)
3. Connect through local instance
4. View console

```
public sealed class MyComponent : Component
{
	protected override void OnStart()
	{
		Log.Info( $"I am {Connection.Local.DisplayName} and I am proxy? {IsProxy}" );

		if ( !IsProxy )
		{
			GameObject.NetworkSpawn();
			GameObject.Network.AssignOwnership( Connection.Host );
		}

		Log.Info( $"This is OnStart running on {Connection.Local.DisplayName}, the owner of {GameObject} is {GameObject.Network.Owner.DisplayName} and is it proxy? {GameObject.IsProxy}" );
		Log.Info( $"This is OnStart running on {Connection.Local.DisplayName}, the owner of {GameObject.Parent} is {GameObject.Parent.Network.Owner?.DisplayName} and is it proxy? {GameObject.Parent.IsProxy}" );
	}


	TimeUntil _nextPrint;
	protected override void OnFixedUpdate()
	{
		if ( !_nextPrint ) return;

		Log.Info( $"This is OnFixedUpdate running on {Connection.Local.DisplayName}, the owner of {GameObject} is {GameObject.Network.Owner.DisplayName} and is it proxy? {GameObject.IsProxy}" );
		Log.Info( $"This is OnFixedUpdate running on {Connection.Local.DisplayName}, the owner of {GameObject.Parent} is {GameObject.Parent.Network.Owner?.DisplayName} and is it proxy? {GameObject.Parent.IsProxy}" );
		_nextPrint = 1f;
	}
}
```
The result will be that IsProxy on the connecting client returns True for the cube every time

**In live:**
1. Load the game fish.my_project_2 with `game fish.my_project_2`
2. Join through another client
3. View console
The result will be that IsProxy on the connecting client returns False for the cube every time

### Expected behavior

.

### Media/Files

Screenshot from second connection in tools:
![Image](https://github.com/user-attachments/assets/985cc1fa-cc50-43ba-aa81-65ae7d51f82d)

Screenshot from other client in live:
![Image](https://github.com/user-attachments/assets/e5e27a42-f066-47fc-8268-f101462651a9)

### Additional context

Suspected commit is
[sbox](https://commits.facepunch.com/r/sbox/master)
[/master](https://commits.facepunch.com/r/sbox/master)
[#daa652](https://commits.facepunch.com/507043)
earlier from garry.

I haven't tested on a S&box version from before the commit.

**Comment by matekdev** [comment]
Another issue that is semi-related to ownership
https://github.com/Facepunch/sbox-issues/issues/6987#issue-2681436238

**Comment by PolSpock** [comment]
Hi,

Today I encountered a related issue where the children `GameObject` of a parent `GameObject.NetworkSpawn()` no longer share the same `Network.Owner`
![Image](https://github.com/user-attachments/assets/f585381e-973c-41b9-b29d-5aed386c17c1)

**Comment by timmybo5** [comment]
Can confirm IsProxy is broken, it's like the new instance joining the game is considered the same client/owner.
