### ISSUE TITLE
Game crashes off my steam id

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#7046]
### Describe the bug

Was playing micro mayhem and got some crashes, no clue what triggered them. SteamID: 76561198045068860

### To Reproduce

-

### Expected behavior

-

**Comment by aylaylay** [comment]
Sentry says one vulkan crash 2 days ago and a mp3 crash 16 hours ago. I've added more checks around the mp3 crash

**Comment by trundlr** [comment]
Thanks, appreciate it!
