### ISSUE TITLE
Collider onTriggerEnter doesnt seem to work as before

### ISSUE THREAD

**Issue by DoctorWhoFR** [Facepunch/sbox-issues#7051]
### Describe the bug

I am trying to attach an collider to a bones, to make an "legs attack" but with proper detecting with something is really touching the foot not only a basic raycast.

Before, 
`
Collider.OnTriggerEnter += OnTriggerEnter;
`

was simply working, but known its seem that its not working anymore and no detecting is made.
Only the Collider.Touching parts seem to be updated.

### To Reproduce

```
using Sandbox;

public sealed class TestColliderAttack : Component
{

	[Property]
	public Collider Collider { get; set; }

	// dont work
	void OnTriggerEnter(Collider collide)
	{
		Log.Info( $"test {collide}" );
	}

	// dont work
	void OnGameObject( GameObject collide )
	{
		Log.Info( $"test {collide}" );
	}

	protected override void OnStart()
	{
		Log.Info( Collider );
		Collider.OnTriggerEnter += OnTriggerEnter;
		Collider.OnObjectTriggerEnter += OnGameObject;
	}

	protected override void OnUpdate()
	{
		// work
		foreach ( var touching in Collider.Touching )
		{
			Log.Info(touching);
		}
	}
}
```
https://github.com/user-attachments/assets/3cff57aa-79bb-493b-af2b-bb712ec2e403

### Expected behavior

I expect OnTriggerEnter to work whaterver he/or something enter the collider.
As Collider.Touching as an updated list of what is touching it and of course because it perfectly detect the plan and the testing cube, i dont think this is a "setup" part because if my box was the problem it will not be detected in Touching when touching it.

**Comment by aylaylay** [comment]
?

**Comment by DoctorWhoFR** [comment]
Sorry i was little bit sick ,

(the collider is on bones ValveBiped_Bip01_L_Foot)
![Image](https://github.com/user-attachments/assets/223b340e-d7df-4ca7-bba6-1c91571b67be)


Just to say, i have tested the same script directly with "simple box" and it's work, maybe its linked to bones 
https://github.com/DoctorWhoFR/s_murders001

**Comment by DoctorWhoFR** [comment]
does the repo project worked for you ?

**Comment by aylaylay** [comment]
You've made the l_foot bone procedural, if you disable it then the collider will follow. I will see if I can fix these not getting updated for procedural bones though.

**Comment by aylaylay** [comment]
And the second problem of OnTriggerEnter, OnObjectTriggerEnter actions not working is because you have a rigidbody on the playermodel, them collider actions don't invoke when there's a rigidbody - which I'll see about fixing also.

**Comment by aylaylay** [comment]
But basically, delete this rigidbody - it's a mesh so it can't be a rigidbody anyway.

![Image](https://github.com/user-attachments/assets/36185e5a-b5e2-4870-ad06-df6feee6f596)

**Comment by DoctorWhoFR** [comment]
So thx for your help, i am sorry for the rigidbody part, i was thinking it was needed for trigger to work properly ^^' my bad 

And thx for anything you will do for make it easier, s&box team is the best :)

**Comment by aylaylay** [comment]
Nope, no need for a rigidbody, just a collider as a trigger will work fine
