### ISSUE TITLE
[Authority] shouldn't be separate from [Broadcast]

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#7053]
`[Authority]` shouldn't be separate from `[Broadcast]`.
Instead Broadcast should have parameters for both Permissions AND the Desired Target

### Offered Solutions:

1. Add a "Target" variable to `[Broadcast]` similar to how we already have "Permission"
```cs
[Broadcast] // Anyone can call, can be sent to anyone
[Broadcast( Permission = NetPermission.Owner )] // Only the Owner can call, can be sent to anyone
[Broadcast( Permission = NetPermission.Anyone, Target = NetPermission.HostOnly )] // Anyone can call, is only sent to the Owner
```

2. An enum-less solution:
```cs
[Broadcast] // Anyone can call, can be sent to anyone
[Broadcast.ToEveryone.FromOwner] // Only the Owner can call, can be sent to anyone
[Broadcast.ToOwner.FromAnywhere] // Anyone can call, is only sent to the Owner
```

(`[Broadcast]` could also be renamed to `[Rpc]` for sake of consistency with `Rpc.Caller`, not sure if that should be a separate issue tho)

**Comment by garrynewman** [comment]
We should definitely be calling these [Rpc] instead of dancing around it.

**Comment by kurozael** [comment]
While we're at it we should be able to pass NetTransmission in as an option (which is currently internal) so we can send unreliable RPCs, this opens up pathways for people to later optimise their networking code. For example, sending an RPC to create a tracer effect doesn't need to be sent reliably - it doesn't really matter if the packet is dropped.

**Comment by garrynewman** [comment]
And are we okay with

```
[Rpc( Mode = RpcMode.,Broadcast, Permission = NetPermission.Anyone, Target = NetPermission.HostOnly,  Transmission = NetTransmission.Unreliable )] 
```

because this seems fucked to me

**Comment by MrBrax** [comment]
looks alright to me, could be done in shorthand too with overloads, right? i don't think you'd need to use all of those all the time, especially when you have Rpc.FilterInclude

**Comment by bub-bl** [comment]
Just set default values on properties and let us define what values we want to set

**Comment by kurozael** [comment]
It could probably be simplified by doing like:

[Rpc( NetPermission.HostOnly, NetTarget.Owner )] etc with overloads and although it seems long, I think it allows the best flexibility and just seems clearer IMO.

**Comment by Nolankicks** [comment]
With the new compiling stuff, will this all be changed for us?

**Comment by garrynewman** [comment]
Proceeding with this as `[Rpc( arg, arg, arg)]` for now. Going to try to rename the enums and try to build some sugar on top of it.

**Comment by Nolankicks** [comment]
Could you write up some docs for the default parameters?
