### ISSUE TITLE
Using polygon tool with multiple 2D views freezes and crashes hammer

### ISSUE THREAD

**Issue by randomperson189** [Facepunch/sbox-issues#706]
**Describe the bug**
When I use the the polygon tool with multiple 2D views, it freezes hammer, eats up all your RAM and eventually crashes it

**To Reproduce**

1. Change your hammer layout to Four-View Quad
2. Use the polygon tool and click on the grid
3. See that Hammer freezes

**Expected behaviour**
The tool should work like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/32617562/129728825-99c70bc2-cbd8-4019-b2f2-2d759d1beece.png)

**Comment by aylaylay** [comment]
I have pushed a fix for this, please close the issue if it works for you

**Comment by randomperson189** [comment]
Works now, thanks

**Comment by randomperson189** [comment]
Works now, thanks
