### ISSUE TITLE
.clothing resources thumbnail generation is broken

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#7072]
### Describe the bug

Creating a .clothing definition in a project will always generate a missing texture as the thumbnail.

### To Reproduce

1. Create a test.clothing resource in a project
2. regenerate thumbnail or open it in the inspector
3. Note missing texture regardless of Model inputs

### Expected behavior

They should get proper thumbnails generated, like the .clothing resources in the citizen addon.

### Media/Files

![Image](https://github.com/user-attachments/assets/9060c216-bd2e-4fef-ac74-34b16c6a1c22)
![Image](https://github.com/user-attachments/assets/574273dd-b442-4139-821b-fcb3d8c95253)

**Comment by aylaylay** [comment]
Saving the PNG wasn't creating the directory if it didn't exist, it should now
