### ISSUE TITLE
Add `CookieContainer.TryGet<T>(string key, out T value)`

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#7073]
### What it is?

the CookieContainer class contains a method called `TryGetString`, which returns the json string but not the deserialized value.

### What should it be?

It'd be convenient if there was an equivalent method that got the actual deserialized value.

Would save having to do this:
```CS
		if (ProjectCookie.TryGetString("leveldesigner.supercategories", out var superCategories))
		{
			superCategoriesTagsPicker.Deserialize(JsonSerializer.Deserialize<string>(superCategories));
		}
```

**Comment by aylaylay** [comment]
FYI there's already a Get<T>, are you still wanting a TryGet<T>?

**Comment by aylaylay** [comment]
Added `TryGet<T>` anyway

**Comment by Fortune117** [comment]
Thanks, it's a little pedantic but it saves me a line of code every time.
