### ISSUE TITLE
Trigger hitting things outside of its bounds

### ISSUE THREAD

**Issue by GreaterThen0** [Facepunch/sbox-issues#7096]
### Describe the bug

it seems like the trigger is offset from the parent.

all other collisions work fine.

### To Reproduce

the way my code works is simple:
I have a projectile game object with a child game object that has a sprite component.
the child sprite has a box collider and some code to call a function on the projectile parent if it gets triggered.
the projectile checks for tags and then draws a line between the collider and the target hit.

and this bug still happens when the projectile itself has the trigger and bypasses the child's trigger.

### Expected behavior

trigger goes off when a game object enters the bounds of the trigger.

### Media/Files

https://www.youtube.com/watch?v=-GNeC3m6na8

in the video:
the white line gets rendered when a trigger is called and will draw a line between the collider and the target hit.

### Additional context

the project I am working on is older so I might have to remake the project and port the code over but I would rather not.

**Comment by aylaylay** [comment]
Turn on physics debug, I can't see what's happening

**Comment by GreaterThen0** [comment]
https://www.youtube.com/watch?v=rOcvRum3gfg

Interestingly it seems the collider is moving from the 0,0,0 point to the spawn point

**Comment by GreaterThen0** [comment]
https://www.youtube.com/watch?v=rOcvRum3gfg

Interestingly it seems the collider is moving from the 0,0,0 point to the spawn point

**Comment by GreaterThen0** [comment]
> Turn on physics debug, I can't see what's happening

https://www.youtube.com/watch?v=rOcvRum3gfg

Interestingly it seems the collider is moving from the 0,0,0 point to the spawn point

(repost)

**Comment by aylaylay** [comment]
You likely have to spawn the projectile disabled, set the position and then enable. Or clear interpolation when moving it to the initial position.

**Comment by MrBrax** [comment]
isn't this an issue of cloning a prefab without any arguments then setting the position after, i got a similar issue of the object hitting triggers on its way to the new position substep

**Comment by GreaterThen0** [comment]
> isn't this an issue of cloning a prefab without any arguments then setting the position after, i got a similar issue of the object hitting triggers on its way to the new position substep

What do you mean with out any arguments?

Because I set the position a few lines after cloneing it which I assumed was the correct way.

**Comment by GreaterThen0** [comment]
> You likely have to spawn the projectile disabled, set the position and then enable. Or clear interpolation when moving it to the initial position.

Do you mean spawn with the entire projectile disabled or just the collider?

I'm also surprised the collider can move independently from its parent by default. I thought it would just be stuck to its parent unless told otherwise.

**Comment by MrBrax** [comment]
> > isn't this an issue of cloning a prefab without any arguments then setting the position after, i got a similar issue of the object hitting triggers on its way to the new position substep
> 
> What do you mean with out any arguments?
> 
> Because I set the position a few lines after cloneing it which I assumed was the correct way.

.Clone takes a position and a rotation argument for spawning

**Comment by GreaterThen0** [comment]
> > > isn't this an issue of cloning a prefab without any arguments then setting the position after, i got a similar issue of the object hitting triggers on its way to the new position substep
> > 
> > 
> > What do you mean with out any arguments?
> > Because I set the position a few lines after cloneing it which I assumed was the correct way.
> 
> .Clone takes a position and a rotation argument for spawning

I didn't know that, good to know!

**Comment by GreaterThen0** [comment]
> > > isn't this an issue of cloning a prefab without any arguments then setting the position after, i got a similar issue of the object hitting triggers on its way to the new position substep
> > 
> > 
> > What do you mean with out any arguments?
> > Because I set the position a few lines after cloneing it which I assumed was the correct way.
> 
> .Clone takes a position and a rotation argument for spawning

adding the position into the clone fixed it THANK YOU
