### ISSUE TITLE
C# layer not getting networked entities initially

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#71]
Been getting this bug since this commit specifically: https://commits.facepunch.com/382770
Seems unrelated but before that update I was receiving these networked entities without fail all the time.

Changing the networked type to [NetPredicted] has no real effect, except it will update when running `devcam`, presumably because that's changing another networked entity on the player.

![image](https://user-images.githubusercontent.com/1388267/116690475-52e55980-a9b1-11eb-8280-fc8b52e0a76f.png)

In the screenshot below you can see the ChildEnt is visible rendering meaning it definitely exists on the client. However the C# layer reports it as null / invalid.

Updating the entity itself seems to have no effect, nor does having everything set to `TransmitType.Always`.

![image](https://user-images.githubusercontent.com/1388267/116689939-9d1a0b00-a9b0-11eb-9196-31c14108e9af.png)

**Code To Reproduce**

```csharp
using Sandbox;

[Library("noplayer", Title = "debug test")]
partial class Game : Sandbox.Game
{
	public override Player CreatePlayer() => new Player();
}

partial class Player : BasePlayer
{
	[Net] public ModelEntity ChildEnt { get; set; }

	[Event("tick")]
	public void CheckHasEnt()
	{
		var state = Host.IsServer ? "[SERVER]" : "[CLIENT]";
		DebugOverlay.ScreenText(Host.IsServer ? 0 : 1,
			$"{state} Player.ChildEnt.IsValid() = {ChildEnt != null && ChildEnt.IsValid()}");
	}

	public override void Respawn()
	{
		Controller = new WalkController();
		Animator = new StandardPlayerAnimator();
		Camera = new FirstPersonCamera();

		EnableDrawing = true;
		Transmit = TransmitType.Always;

		SetModel("models/citizen/citizen.vmdl");
		base.Respawn();

		ChildEnt = new ModelEntity();
		ChildEnt.SetModel("models/citizen_props/beachball.vmdl");
		ChildEnt.Transmit = TransmitType.Always;
		ChildEnt.WorldPos = WorldPos;
	}

	[ServerCmd ("sboxdebug_forceupdate") ]
	public static void Dirty()
    {
		// doesn't seem to have any effect
		(ConsoleSystem.Caller as Player).NetworkDirty("ChildEnt", NetVarGroup.Net);
		
		// also has no effect...
		(ConsoleSystem.Caller as Player).ChildEnt.WorldPos += Vector3.Up * 32;
	}
}
```

**Comment by garrynewman** [comment]
Does it change if you change `ModelEntity`  to `EnityHandle`?

**Comment by garrynewman** [comment]
Alright, so here's why this is happening. The client code gets initialized sooner now thanks to the new tick hooks. So these entities are getting their network data before the other entities exist.

For now use EntityHandle - which is kind of a forward reference to the entity and will return non null when your client knows about the entity.

I will make it work automatically when entities are instantiated at some point over the next few weeks, which will make EntityHandle redundant.
