### ISSUE TITLE
Addon folders with any uppercase characters do not launch game

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#710]
**Describe the bug**

If you have any uppercase characters in your addon folder name the game will not launch and hang in the loading screen.

Seems to be caused from the MenuUI/Game/BaseGamePanel.cs:22 doing String.ToLower() on the game ident, removing this fixes it.

Maybe the better fix would be to force Addon.Ident to lowercase:

```diff
namespace Sandbox
{
  internal class Addon : IDisposable
  {
-    public string Ident => this.Config?.Ident ?? "local." + this.Name;
+    public string Ident => this.Config?.Ident ?? "local." + this.Name.ToLower();
  }
}
```

**To Reproduce**

Clone sbox-minimal and name it Minimal. Try to launch.

**Screenshots**

![image](https://user-images.githubusercontent.com/1388267/129802260-9a50fde9-95c0-4f2c-9fc6-41a6704f4135.png)

**Comment by StupidRepo** [comment]
bomp
