### ISSUE TITLE
Selecting model renderers in scene sometimes does not work

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#7100]
### Describe the bug

Selecting model renderers in scene sometimes does not work

### To Reproduce

Try to select a model renderer.

### Expected behavior

It should select

### Media/Files

https://github.com/user-attachments/assets/4af02b7b-823b-4471-abe7-f202539f8216

**Comment by aylaylay** [comment]
I was getting this too and now I'm not, if I run into it again I'll debug it

**Comment by Nolankicks** [comment]
I this intended @aylaylay? I would like to still be able to select objects?

**Comment by aylaylay** [comment]
I think @DevulTj is going to look into supporting selecting objects while gizmos are turned off

**Comment by DevulTj** [comment]
Should be good now
