### ISSUE TITLE
Triggers on rigidbodies are extremely unreliable

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#7102]
### Describe the bug

Enter listener usually works, but objects almost never leave, making them continue "touching" the trigger even when far away.

### To Reproduce

1. Add a trigger box collider to a rigidbody (with physics), either on the gameobject or a child
2. Trigger events will be extremely unreliable

### Expected behavior

Should work like a normal trigger

**Comment by aylaylay** [comment]
Make a repro

**Comment by MrBrax** [comment]
[rigidbody_trigger.zip](https://github.com/user-attachments/files/17993565/rigidbody_trigger.zip)

repro, walk into shower

**Comment by aylaylay** [comment]
thanks

**Comment by MrBrax** [comment]
fixed
