### ISSUE TITLE
Deleting Entities on Server from Clientside Requires NetworkIdent Hack

### ISSUE THREAD

**Issue by AMastryukov** [Facepunch/sbox-issues#711]
**Describe the bug**
When attempting to delete an entity on the server from the clientside, a hacky workaround is required. The workaround requires one to pass the `Entity.NetworkIdent` to a `[ServerCmd]` static method, then inside the method use `FindByIndex(networkIdent)` to delete it. While the above works, the solution feels very hacky.

**To Reproduce**
1. Create a clientside UI
2. Use the UI interactions to delete an entity
3. The solution above is required

**Expected behavior**
Users should be able to delete serverside entities using clientside UI without having to get the network identity of an entity and then look it up through the identity on the other end.

**Additional context**
I was trying to make a user interface for arming a C4 bomb. 
One of the options is to destroy it.

**Comment by Rohansi** [comment]
Garry's looking into server RPCs which would be similar to `[ServerCmd]` but should support passing entities directly when calling it (#191). It will basically do what you're doing here internally. Is this the solution you're looking for?

**Comment by AMastryukov** [comment]
> Garry's looking into server RPCs which would be similar to `[ServerCmd]` but should support passing entities directly when calling it (#191). It will basically do what you're doing here internally. Is this the solution you're looking for?

Yes, thank you.
