### ISSUE TITLE
FBX models with morph shapes on them seem to discard their normals

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#7111]
### Describe the bug

![Image](https://github.com/user-attachments/assets/6588af33-0927-4ed3-9b7e-4cd0c71f0696)

![Image](https://github.com/user-attachments/assets/46b14f62-5a34-4e3b-8f51-9eabab5b308d)

I've attached said files (there is a slight scale difference but you can ignore that)

[potato_canon_fbx+dmx.zip](https://github.com/user-attachments/files/18007261/potato_canon_fbx%2Bdmx.zip)

### To Reproduce

Open both files in modeldoc, observe clear differences in shading.

### Expected behavior

Open both files in modeldoc, observe no differences in shading.
The FBX should have hard edge normals.

**Comment by aylaylay** [comment]
Should be fixed now

![Image](https://github.com/user-attachments/assets/ea5a46eb-9cba-4663-bf1a-1abc7e56bed0)
