### ISSUE TITLE
ISceneCollisionEvents doesn't report the right surface when colliding with map geometry

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#7123]
### Describe the bug

ISceneCollisionEvents doesn't report the right surface when colliding with map geometry, It should report the surface of the material that it touched, but it seems to report the surface of some random material the map uses. In the image below everything is glass (map is thieves.terrortown, you can hear all props make glass noises when they collide with the map in this map)
https://cdn.discordapp.com/attachments/833983416390385685/1314548565367980053/image.png?ex=67542c41&is=6752dac1&hm=1ff3efb45fddb6f6489785dfffff20f25737d7b1c2b553a74b79669045e2ac25&

### To Reproduce

create something that implements ISceneCollisionEvents. print the surfaces it touches

### Expected behavior

It should grab the same surface that running a Trace.Ray against that material would grab.

**Comment by aylaylay** [comment]
Are impact sounds wrong then?

**Comment by Xenthio** [comment]
> Are impact sounds wrong then?

yes they are

**Comment by aylaylay** [comment]
Fixed

**Comment by Xenthio** [comment]
Hell yeah, thanks.
