### ISSUE TITLE
Trying to launch Faceposer gives an error

### ISSUE THREAD

**Issue by randomperson189** [Facepunch/sbox-issues#713]
**Describe the bug**
When I try and launch the Faceposer tool in sbox-dev, it shows these dialogs I linked below. I tried doing what it says and verified files but it still won't work.

**To Reproduce**

1. Open sbox-dev.exe
2. Click on Tools
3. Select Faceposer

**Expected behavior**
Faceposer tool should open and not show an error dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/32617562/129870588-cb07324b-b746-4152-ad66-651dc8969181.png)
![image](https://user-images.githubusercontent.com/32617562/129870597-43893138-2890-44b6-9bd7-9f8fb228e0c7.png)

**Comment by robotboy655** [comment]
I have pushed a potential fix for this, let me know if that fixes it/close the issue yourself if it is fixed.

**Comment by randomperson189** [comment]
> I have pushed a potential fix for this, let me know if that fixes it/close the issue yourself if it is fixed.

I tried now in the updated version but I'm still getting the error, I re-verified the files just in case. If anyone else is reading this, try and reproduce the issue yourself so I know if it's a me problem or not.

**Comment by conneath** [comment]
faceposer just freezes the game for me

**Comment by walllable** [comment]
Can confirm, my game also freezes when launching faceposer.

**Comment by aylaylay** [comment]
It's not compiling properly on the steam build, it works my end but the tool looks very broken anyway.

**Comment by garrynewman** [comment]
Is Faceposer useful? Is there good reason for us to get it working again and make it available?

**Comment by N-cognito** [comment]
Faceposer is useful not only for porting Source 1 assets to Source 2, but it also opens up opportunities for easy phoneme-based lipsyncing for voicelines using flexes built into a model, especially if voicelines aren't available at the time of model creation and need to be created by an audio designer in the future.

**Comment by robotboy655** [comment]
I think this was fixed a while back.
