### ISSUE TITLE
Cant rename non-compiling shader

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#7135]
### Describe the bug

Trying to rename a shader that doesn't compile will error

### To Reproduce

1. Create a new material shader asset
(2. Break it if #7131 is fixed)
3. Rename it

### Expected behavior

Rename should work or error should make more sense

### Media/Files

![Image](https://github.com/user-attachments/assets/8056ce57-1293-4464-aefc-da09e65dca27)

**Comment by Gmod4phun** [comment]
Probably because of #7130, and it happens to all asset types

**Comment by DoctorGurke** [comment]
likely, renaming a freshly created material (with the original create prompt) also seems to break and wont let me open it 😅
