### ISSUE TITLE
Code compilation in editor collapses all GameObjects in Hierarchy

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#7146]
### Describe the bug

Compiling your code currently collapses every single GameObject in the hierarchy. This is annoying because I may be modifying properties across components across nested GameObjects. 

### To Reproduce

1. Add some GameObjects as children of a GameObject
2. Expand the GameObject so you can see the children
3. Make a change and save to let your code compile
4. Observe the Hierarchy collapse all open GameObjects

### Expected behavior

The expanded GameObjects in the Hierarchy should not collapse.

**Comment by badandbest** [comment]
I've worked a lot with the hierarchy this past week so I know the cause of this.

[SceneTreeWidget.BuildUI](https://sbox.game/dev/api/Editor.SceneTreeWidget/BuildUI) has a HotloadAttribute and create a new hierarchy every time.

**Comment by Retroeer** [comment]
this is such a gripe for me I hope it's fixable

**Comment by badandbest** [comment]
That seems useful. Can you make it public please <3

![Image](https://github.com/user-attachments/assets/a6ca3651-ea6f-4cb9-871f-f4d2b49dd5b6)
