### ISSUE TITLE
Search bar in sbox.game docs has trouble registering inputs in quick succession

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7149]
### Describe the bug

Similar to how the API search bar was when it first came back, key strokes in quick succession cause the page to reload to how the search bar was previously rather than fully waiting for typing to be done.

### To Reproduce

1. Type a bunch of stuff into the bar

### Expected behavior

Search bar should behave identical to the API Page, or preferably how it does at the docs site, i loved having the quick drop down

### Media/Files

https://github.com/user-attachments/assets/d2a5addb-1635-4775-8f64-2d89654115e5

**Comment by garrynewman** [comment]
I knew this was coming 😢

**Comment by Retroeer** [comment]
once again foiled by having a high wpm 😔

**Comment by garrynewman** [comment]
How is it now?

**Comment by Gmod4phun** [comment]
Feels good

**Comment by Retroeer** [comment]
much better, it's not really in the scope of the issue but whats your thoughts on bringing this back?
 ![Image](https://github.com/user-attachments/assets/8f82a8bb-6f21-4ccf-9690-01733563b6a7)
Being able to quickly search through the pages like that is mostly why i still use the standalone docs site rather than the one on sbox.game
