### ISSUE TITLE
[Hammer] Block tool issues

### ISSUE THREAD

**Issue by FullStack0verfl0w** [Facepunch/sbox-issues#7152]
### Describe the bug

1. Geometry type list shuffles every engine session.
![Image](https://github.com/user-attachments/assets/3ca80006-7ad5-4d93-9f30-7829d25547b9)
![Image](https://github.com/user-attachments/assets/f0391323-593e-4817-bf73-57700d047963)
2. After creating/opening a map, geometry type resets to the first element in the list, but only in UI. The selected type doesn't match the geometry it creates.
![Image](https://github.com/user-attachments/assets/1d5f8cba-84a6-4884-be32-7611f3d39e93)
3. Sometimes (perhaps due to issues I described above) after changing geometry type or creating a shape it crashes the editor.
4. Material parameter does nothing.
5. Primitives, such as cylinder can have less than 2 two sides, and also unlimited amount of sides, which can cause the editor to freeze.

### To Reproduce

Reproducing bugs 1, 2, 4, and 5 isn't difficult, but bug 3 seems to occur randomly. I believe that fixing bugs 1 and 2 might fix 3 as well.

### Expected behavior

1. Geometry type list should be sorted somehow, moving the block shape to the top.
2. Reset geometry type to the first element (block) after creating/opening a map.
3. Block tool should not crash the editor.
4. Material parameter should be removed, since we already have Active Material in Hammer.
5. Limit the amount of sides for cylinders, spheres and spikes.

**Comment by aylaylay** [comment]
Fixed
