### ISSUE TITLE
S&box doesn't launch no logs are being created

### ISSUE THREAD

**Issue by GhilaneA** [Facepunch/sbox-issues#7158]
### Describe the bug

No screens appear or errors messages.
Tried to launch it on steam and also directly through the folder. I launched sbox.exe, sbox-dev.exe nothing happens. When I launch sbox-server.exe the cmd window appears for a few seconds before closing.
The only way I know it has been launch is because I have the button to stop the game on steam after clicking on play, but after waiting few seconds it goes back to play and I see steam synchronization icon.

### To Reproduce

1 go to s&box in the steam
2- click on Play
3- select "play s&box" and click on play

### Expected behavior

When clicking on play should display the S&box game or editor if the editor is selected

### Media/Files

here's my folder. 
![Image](https://github.com/user-attachments/assets/741e4cab-2697-4260-bca2-216adb92dbe4)

### Additional context

I also tried the solution here : https://github.com/Facepunch/sbox-issues/issues/5962. 
I don't have any steam_api.dll in system32 or system folders. only related to games or other softwares. 

here's s&box server cmd window before it crashes : 
![Image](https://github.com/user-attachments/assets/e7c10389-c439-428c-8358-1a98cf1d46e0)

hardware : laptop RTX 3060, R7 5800H, 32GB ram, windows 11 PRO

**Comment by handsomematt** [comment]
What specific Windows 11 version is it, can you run `winver`

**Comment by GhilaneA** [comment]
Hi, sure. 
V.21H2 build 22000.1098

**Comment by handsomematt** [comment]
That's 3 years old and out of service. Update please.
