### ISSUE TITLE
The SoundPointComponent's Component.ITemporaryEffect.IsActive implementation is not publicly accessible

### ISSUE THREAD

**Issue by thefuryofblood** [Facepunch/sbox-issues#7159]
### Describe the bug

The public access modifier is missing from the implemetnation of Component.ITemporaryEffect.IsActive, due to which it's not possible to actually get whether a sound is currently playing via the SoundPointComponent.

I'm assuming this is not the intended implementation of the interface's property as the read-only property is set to public in the interface.

### To Reproduce

1. Implement a SoundPointComponent in a Component and expose it as a property
2. Create and assign the SoundPointComponent property to your Component in the Editor
3. Call PlaySound on the SoundPointComponent 
4. Attempt to access the SoundHandle or SoundHandle.IsPlaying
5. Cry

### Expected behavior

It should be possible to play a sound from the SoundPointComponent and be able to tell whether the sound is playing from the IsActive functionality.

Better yet, it would be nice if PlaySound could also just return the SoundHandle.

**Comment by aylaylay** [comment]
Get it as a ITemporaryEffect and check if it's active

**Comment by thefuryofblood** [comment]
Oh woops, could've sworn I tried that before posting. Cheers that works!
`(soundPointComponent as ITemporaryEffect).IsActive;`

**Comment by aylaylay** [comment]
For what it's worth, I don't think there would be much harm making them public anyway
