### ISSUE TITLE
[Hammer] Quick Hide Unselected Objects with enabled Cordoning causes everything disappear

### ISSUE THREAD

**Issue by pBinarySoul** [Facepunch/sbox-issues#717]
**Describe the bug**
Quick Hide Unselected Objects with enabled Cordoning causes everything disappear, because cordons hide too.

**To Reproduce**
1. Add a cordon.
2. Toggle Cordoning (Ctrl+Shift+C)
3. Create some meshes inside the cordon.
4. Select a mesh and hide everything using Quick Hide Unselected Objects (Ctrl+H).

**Expected behavior**
A cordon, that contains selected object shouldn't be hidden.

**Screenshots**
[Video](https://youtu.be/NFDPbWXPtf0). + It doesn't hide anything outside the cordon if the cordon is active.

**Comment by robotboy655** [comment]
That's because hiding all unselected will also hide the cordon object which in turn will hide everything. 

I have made the QuickHide unselected not hide the cordons.
