### ISSUE TITLE
[HAMMER] Default env_cubemap_fog Cubemap Texture doesnt exist

### ISSUE THREAD

**Issue by TitusStudiosMediaGroup** [Facepunch/sbox-issues#718]
**Describe the bug**
`env_cubemap_fog`'s default "Cubemap Texture" property (`materials/skybox/tests/src/light_test_sky_sunset.vtex`) does not exist(?), and will spam your console if it doesnt. 

After map compile it will spam your console with: 
```
C:\buildbot\work\sbox\sbox\src\rendersystem\texturebase.cpp(2876):ResourceHandleToData( materials/skybox/tests/src/light_test_sky_sunny.vtex ) failed! Falling back to error texture!
```

**To Reproduce**
1. Make a map with a floor and a `info_player_start`
2. Place the `env_cubemap_fog` point entity anywhere on the map, leave its properties as default.
3. Compile the map.

**Ingame:**
Just before you connect in console:
```
Error loading resource file "materials/skybox/tests/src/light_test_sky_sunset.vtex_c" (Error: ERROR_FILEOPEN)
```
After loading in:
```
C:\buildbot\work\sbox\sbox\src\rendersystem\texturebase.cpp(2876):ResourceHandleToData( materials/skybox/tests/src/light_test_sky_sunny.vtex ) failed! Falling back to error texture!
C:\buildbot\work\sbox\sbox\src\rendersystem\texturebase.cpp(2876):ResourceHandleToData( materials/skybox/tests/src/light_test_sky_sunny.vtex ) failed! Falling back to error texture!
C:\buildbot\work\sbox\sbox\src\rendersystem\texturebase.cpp(2876):ResourceHandleToData( materials/skybox/tests/src/light_test_sky_sunny.vtex ) failed! Falling back to error texture!
.....continues infinitely
```

> NOTE: This issue can also be produced if you leave the Cubemap Texture property blank.

**Expected behavior**
That the default cubemap texture exist.

**Screenshots**
![https://i.imgur.com/Pi5mPup.png](https://i.imgur.com/Pi5mPup.png)
![https://i.imgur.com/kBq0ZEQ.png](https://i.imgur.com/kBq0ZEQ.png)

**Additional context**
There isnt a shader that I'm aware of to create one of these textures.
A fix is to use `materials/skybox/colorscript/skybox_sky_sunny.vtex` which exists but does not have any properties? It still works however.

**Comment by bakscratch** [comment]
Just pushed a fix to set the "materials/skybox/colorscript/skybox_sky_sunny.vtex" as the default as its the same thing as the one before. Let me know if that fixes it/close the issue yourself if it is fixed.

**Comment by TitusStudiosMediaGroup** [comment]
Works. Thank you.
