### ISSUE TITLE
Can't set new material override of terrain from code

### ISSUE THREAD

**Issue by GreaterThen0** [Facepunch/sbox-issues#7180]
### Describe the bug

When I attempt to set the material override of a terrain it gets set but doesn't apply

### To Reproduce

from a component set a terrain's material override.
	

		Material MatCopy = TerrainMat.CreateCopy();

		MatCopy.Set( "NoiseTexture", Final );

		Chunk.MaterialOverride = MatCopy;

		Chunk.ClipMapLodLevels = 3;
		Chunk.ClipMapLodExtentTexels = 256;

the material will appear to be set in the editor ( in the terrains material override ) but in-game doesn't change

### Expected behavior

to change the material override to the referenced material.

![Image](https://github.com/user-attachments/assets/36367982-161e-4c7c-8eaf-d3458545fa9d)

and adding UpdateMaterialsBuffer(); doesn't change results.

Is there a function I should be calling?

**Comment by GreaterThen0** [comment]
I have reopened this issue because the main problem didn't get solved

**Comment by GreaterThen0** [comment]
https://github.com/user-attachments/assets/c506d17d-79b2-4e6a-bfd0-41ba3d96abed

he is a clip of what is happening

**Comment by GreaterThen0** [comment]
![Image](https://github.com/user-attachments/assets/da9c56bb-af86-4dd0-a67e-d6d03b197ab2)


if I set the material in the prefab it looks like this

**Comment by solwllms** [comment]
This should work now

**Comment by GreaterThen0** [comment]
New build fixed it. Thank You!

> This should work now
