### ISSUE TITLE
Gameobject children collision matrix issue

### ISSUE THREAD

**Issue by BlakeWinser** [Facepunch/sbox-issues#7182]
### Describe the bug

If you apply a custom tag with specific collision matrix rules to a prefab GameObject, those rules will be ignored when cloning it if the colliders are on a child object.

### To Reproduce

1. Create a custom collision matrix tag, i.e. "item"
2. Set the item vs item to collide
3. Create a new GameObject that contains a Rigidbody on the parent.
4. Create a new child on this same GameObject, give it a model collider and a model renderer component.
5. Add the item tag to the parent GameObject, setting it to the child first also doesn't fix the issue.
6. Now clone the item during runtime and the 2 items will not collide with one another (if you place the items in the scene then run the game the collision works as expected).

Video provided which shows the exact steps and an example of the issue.

### Expected behavior

The 2 GameObjects should just collide as expected

### Media/Files

https://github.com/user-attachments/assets/d092318b-effc-46c6-91f1-3fd035679c78

### Additional context

For reference, the items I give myself via the console are simply cloned and parented to the player. When dropped, their model renderer and collider are enabled. To test, I created an item with everything on a single GameObject (no children), and the issue disappeared. This confirms the problem is related to the model collider being on a child object, which causes it to ignore the tag inherited from the parent.

**Comment by aylaylay** [comment]
Fixed
