### ISSUE TITLE
Console collapses component exceptions with different stack traces

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-issues#7186]
### Describe the bug

The console collapses messages with the same text. This is a nice way to stop spam but it causes unique exceptions in a single component method to collapse. Because of this, you will only get the stack trace of the most recent exception. The previous ones can only be found in the log file.

### To Reproduce

1. Create a method that produces multiple exceptions:

```
using Sandbox;
using System;

public static class ExceptionShowcase
{
	[SkipHotload]
	private static bool thrown = false;

	public static void Throw()
	{
		if ( thrown )
			throw new InvalidOperationException( "Second exception" );

		thrown = true;
		throw new ArgumentException( "First exception" );
	}
}
```

2. Call said method multiple times on a single GameObject/Component to induce collapsing behavior.
3. Observe only the stack trace of the "Second exception." The "First exception" stack trace is lost.

### Expected behavior

For exceptions with unique stack traces in the same component method to not collapse.

### Media/Files

Inserting spacer logs between exceptions preserves the stack traces:
![Image](https://github.com/user-attachments/assets/65ef82d5-e4db-4bc6-90c2-ea7c4dd79c7c)
![Image](https://github.com/user-attachments/assets/4d1e0a7c-0189-46cc-8519-430da4de5b97)

Without spacers only the newest stack trace is preserved:
![Image](https://github.com/user-attachments/assets/fd7a39d9-4f24-4f23-8a07-b5468adffb34)

**Comment by aylaylay** [comment]
Good point

**Comment by aylaylay** [comment]
Fixed
