### ISSUE TITLE
Generated file paths in solution and project files contain Windows-like remnants

### ISSUE THREAD

**Issue by adamnejm** [Facepunch/sbox-issues#719]
## Setup
- Arch Linux x64 *(5.13.10-arch1-1)*
- Proton 6.3-5
- Steam library on a separate drive *(ext4)*

## Details
1. Project paths in `s&box.sln` are wrong:
a) They use Windows file path separators (`\`);
b) Unnecessary Windows-style drive letter is prefixed in the filepath;
c) Addons directory is capitalized, but it should be all lowercase;

2. Paths in `Include` attribute of `ProjectReference` in generated project files (`.csproj`) have the same issue.
3. Paths in `Include` attribute of `Analyzer` and `Reference` face similar issue with the exception of **NOT** using Windows file path separators, correct UNIX separators (`/`) are used.

#### `s&box.sln`
Expected: `"/media/ssd/games/steam/steamapps/common/sbox/addons/base/code/base.csproj"`
Generated: `"Z:\media\ssd\games\steam\steamapps\common\sbox\Addons\base\code\base.csproj"`
#### `menu.csproj`
Expected:
```xml
<Reference Include="/media/ssd/games/steam/steamapps/common/sbox/bin/managed/Sandbox.Game.dll"/>
<ProjectReference Include="/media/ssd/games/steam/steamapps/common/sbox/addons/base/code/base.csproj" />
```
Generated:
```xml
<Reference Include="Z:/media/ssd/games/steam/steamapps/common/sbox/bin/managed/Sandbox.Game.dll"/>
<ProjectReference Include="Z:\media\ssd\games\steam\steamapps\common\sbox\Addons\base\code\base.csproj" />
```

## Manual fix
Correcting the file paths in the places mentioned works without any issues.
Unfortunately this has to be done every time after the game updates the affected files.

**Comment by Rohansi** [comment]
This is a side effect of running the game under Proton. Your manual fix is good and you should be able to save some time by saving your manually edited copy to a different file name so it doesn't get overwritten.

**Comment by adamnejm** [comment]
I already wrote a simple utility that scans through the files and fixes paths automatically, so personally I'm in the clear for the most part.
The blame is undeniably Proton, but do you think the issue should be investigated by them or fixed here by s&box?
Not sure how these files or file paths are generated, so can't really pinpoint the issue.

**Comment by Rohansi** [comment]
It's technically working as intended. The 'issue' is you're expecting the file created from Proton to be used outside of Proton. It'd be a special case on either side - how would Proton determine if a path should be created using Windows or Linux style? How can S&box detect that it's running under Proton and then map these paths to non-Proton paths? Solution is to probably not rely on these generated project files in this case

**Comment by deinferno** [comment]
I made a little script that make copies s&box.sln and csprojs with fixed pathes and stuff
[Gist link](https://gist.github.com/deinferno/d473b9e76ad24b1754e3443fe1d88f8f)
