### ISSUE TITLE
Forced to publish Base Library and Citizen files

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#7191]
### Describe the bug

When you publish a project the Base Library files are included

If you use the citizen in your project you are also forced to publish all the citizen files.

### To Reproduce

1. Place a citizen model in your scene.
2. Publish your project.

### Expected behavior

It shouldn't publish Base Library or Citizen files because they are already part of base.

### Media/Files

![Image](https://github.com/user-attachments/assets/81bce3f7-9028-42c2-9825-dc355149f17d)

![Image](https://github.com/user-attachments/assets/e81c1029-7361-4004-8840-74e5599fde7d)

**Comment by handsomematt** [comment]
it's deliberate
