### ISSUE TITLE
Updating Facepunch Weapons Crashes Game

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#7195]
### Describe the bug

Updating Facepunch Weapons Crashes Game

### To Reproduce

Update a facepunch asset

### Expected behavior

My game should not be crashing

### Media/Files

https://github.com/user-attachments/assets/e0525698-7c9a-49b3-90d7-b773f9b72756

**Comment by MaxLebled** [comment]
I've republished weapons without source files for the time being, while we sort out the bug that's causing this

**Comment by Nolankicks** [comment]
Doesn’t crash. Still have texturing issues.
