### ISSUE TITLE
Trail Renderers don't work anymore.

### ISSUE THREAD

**Issue by eEight-dev** [Facepunch/sbox-issues#7198]
### Describe the bug

Trail renderers don't render any trails now, I think this started happening before the 14th of December. They don't error out, they just simply don't work! But the Particle Trail Renderer component seems to work fine.

### To Reproduce

1. Open scenestaging repo
2. Select Trails scene
3. Move the balls around
4. They don't render any trails behind them

### Expected behavior

I expect them to render a trail like before.

### Additional context

This is also happening in all of my projects not only scenestaging.

**Comment by aylaylay** [comment]
Set `Emitting` to true on the component
