### ISSUE TITLE
SCSS Hot Reloading not always reloading

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#72]
**Describe the bug**
C# code reloading also has this issue, however, it seems to happen a lot more often with SCSS. The files need to be saved multiple times before the game ever catches a change.

**To Reproduce**
Attempt to save a file a few times

**Expected behavior**
File should hot reload each time

**Screenshots**

**Additional context**
It might also be worth adding a manual hot reload for situations like this when it comes up

**Comment by DevulTj** [comment]
I would like to add that it's happening quite frequently to me, on two machines.

**Comment by DevulTj** [comment]
Conna has fixed this issue, still happens with C# occasionally. Perhaps worth making a separate Issue for it?

**Comment by Trojaner** [comment]
Can confirm issue still happens, regardless of if C# or html

**Comment by DoctorGurke** [comment]
We got our scss to hotload properly again by literally just adding a "/" to the beginning of the stylesheet path lol, might wanna give that at try

**Comment by Trojaner** [comment]
That seems to work, thanks!
Also html seems to be working as well when using relative paths too

**Comment by TankNut** [comment]
> We got our scss to hotload properly again by literally just adding a "/" to the beginning of the stylesheet path

I can confirm this works as a fix for both SetTemplate and StyleSheet.Load
