### ISSUE TITLE
RigidBody MotionEnabled defaults to false if not serialized

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#7201]
### Describe the bug

Many of our prefabs don't have MotionEnabled serialized, which has always worked because it defaults to true, so I guess it never needed to in the first place.
But as of recently, if MotionEnabled isn't serialized it defaults to false.

### To Reproduce

Here's an example of a prefab missing the MotionEnabled property:
[split_wooden_log.json](https://github.com/user-attachments/files/18189386/split_wooden_log.json)
(Rename the type from .json to .prefab, it doesn't let me upload those)

When opening it in the editor, you'll see that MotionEnabled is false.

### Expected behavior

MotionEnabled is true by default, it should be true when missing while deserializing.

### Media/Files

Example of bug found recently because of the change.

https://github.com/user-attachments/assets/3cf2098f-5885-4738-819d-15f86ba93c83

### Additional context

The fix on our part is easy, just reenable and save. But who knows what else it broke.

**Comment by aylaylay** [comment]
This was an unfortunate oversight when changing json to serialize defaults. I can't think of a nice way to automatically right now.

**Comment by aylaylay** [comment]
Looks like this is fixed
