### ISSUE TITLE
[Mesh Component] Export Doesn't Work

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#7202]
### Describe the bug

When you try to export a `mesh `of a `Mesh Component`  the editor complains about the following : `Unable to cast object of type 'Sandbox.MeshComponent' to type 'Sandbox.PolygonMesh'.`

### To Reproduce

1. create a mesh with the block tool.
2. with the mesh component game object selected click on export .
3. select a name and path for your vmdl and click `save`
4. observe that the editor will bitch about being unable to cast object.

### Expected behavior

The editor to export the mesh without bitching

**Comment by aylaylay** [comment]
Fixed
