### ISSUE TITLE
Change materials of world meshes via code

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#721]
**What can't you do?**
Look up a mesh via code and set a material on it, possibly with custom scaling/coordinates

**How would you like it to work?**
Make a mesh in Hammer, put a name on it in object properties.

`WorldMesh.FindByName("test").SetMaterial("dev/measuregeneric")`

Something like that, not very used to the s&box api yet.

**What have you tried?**
Finding the meshes via entity lookups, can't find anything.
I don't even know if named world meshes exist in the compiled map, but it's worth a try.

**Comment by Ryhon0** [comment]
You can already change the materials of entities by calling this on client
```			Entity.SceneObject.SetMaterialOverride( Material.Load( "..." ) )
```
Not sure if there's a way to get meshes, maybe Entity.All

**Comment by MrBrax** [comment]
i checked entity.all, i don't get a list of meshes at least

**Comment by aylaylay** [comment]
This doesn't make sense. Anything static in the map is compiled into mesh chunks, changing the materials of these wouldn't make sense. If you want to change materials of something in the map, they need to be entities.

**Comment by MrBrax** [comment]
Fair, that's a shame. Guess my apartments will be fullbright :)

**Comment by aylaylay** [comment]
Why would they be fullbright :S

**Comment by MrBrax** [comment]
Because there's no baked lighting on mesh entities? Or is that new with S2?
