### ISSUE TITLE
Sphere OnCollisionStart Unreliable Against Map Instances

### ISSUE THREAD

**Issue by Chilevec** [Facepunch/sbox-issues#7213]
### Describe the bug

Sphere's unreliably collide with map geometry. Seemingly, when already colliding with part of the map, it will not detect collisions with other parts of the map (Ie when on the floor, does not detect collisions with walls).

### To Reproduce

1. Import a map, create a sphere (Add a collider)
2. Using ICollisionListener, log collisions in OnCollisionStart
3. Have sphere against the ground (colliding with map) and then gently move it into a wall (a different part of the map)
Media/Files will show what I did to recreate the issue I had in my initial project.

### Expected behavior

Successfully detecting collisions against map instances i.e. Should collide with walls whether or not in contact with floor.

### Media/Files

https://github.com/user-attachments/assets/28a14d2a-010e-4974-99a5-2295344854f6

### Additional context

May not be limited to spheres. Unsure.

**Comment by Chilevec** [comment]
Here is the code used in the video, however helpful it is.
```cs
using Sandbox;

public sealed class MoveAndDetectCollisions : Component, Component.ICollisionListener
{
	Rigidbody RB;
	List<Sphere> collisionSpheres = new List<Sphere>();
	public void OnCollisionStart(Collision collision)
	{
		collisionSpheres.Add(new Sphere(collision.Contact.Point, 10f));
	}
	protected override void OnStart()
	{
		RB = GetComponent<Rigidbody>();
	}
	protected override void OnUpdate()
	{
		foreach ( var sphere in collisionSpheres ) {
			Gizmo.Draw.LineSphere( sphere );
		}
		RB.ApplyImpulse( Input.AnalogMove * Time.Delta * 400f );
	}
}
```

**Comment by aylaylay** [comment]
Intended behaviour unfortunately, OnCollisionUpdate will report all hits
