### ISSUE TITLE
[REGRESSION] Baked lighting currently broken, causing lighting to show up purple

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#7214]
### Describe the bug

![Image](https://github.com/user-attachments/assets/6ff01275-00fe-4c37-abee-1bc756af5b3b)
![Image](https://github.com/user-attachments/assets/df9086f7-c536-4b57-9703-7538fc2a7703)

Lightmap compiles causing things to show up with their color being a purple color for some materials. Possibly due to recent commit from @samzanemesis ?
![Image](https://github.com/user-attachments/assets/0aa3266d-59df-4933-b47c-45800a2f6808)

### To Reproduce

Compile a map with baked lighting
Load up in game

### Expected behavior

Lighting looks proper

**Comment by samzanemesis** [comment]
Try when next build drops

**Comment by samzanemesis** [comment]
Had to revert it, still looking into a good solution for this

**Comment by KingOfTheFBI** [comment]
Looks to be fixed now, thanks!
