### ISSUE TITLE
[ShaderGraph] Compile can fail if its being generated/compiled for the first time.

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#7217]
### Describe the bug

Upon trying to compile a fresh graph or a preexisting graph the compile can fail. However if you restart the editor after compiling for the first time the files will compile fine now.

### To Reproduce

1. Make sure you don't have the s&box editor open.
2. Navigate to `sbox\.source2\temp\shadergraph`
3. Delete any shaders there.
4. Open the s&box editor. 
5. open Shadergraph.
6. trigger a compile by moving the `Result` node.
7. Observe the described issue.

### Expected behavior

To compile.

### Media/Files

https://github.com/user-attachments/assets/0ff28c5f-6b42-4382-8247-3efd2c23fa60

**Comment by aylaylay** [comment]
Fixed
