### ISSUE TITLE
Dedicated server startup error

### ISSUE THREAD

**Issue by SturnusA** [Facepunch/sbox-issues#7219]
### Describe the bug

CAppSystemDict:Unable to load module resourcecompiler (Dependency of application), error 126 when attempting to start a dedicated server
![Image](https://github.com/user-attachments/assets/95f5c540-2137-4161-8787-1b38d5d87da5)

### To Reproduce

1. Latest version installed through steamcmd
2. Launch through batch file
3. Get error

### Expected behavior

Expecting to launch the dedicated server

### Media/Files

![Image](https://github.com/user-attachments/assets/e4407b43-51eb-49eb-a02f-8de921cd461e)

### Additional context

Running windows 11, with all the pre-reqs installed. I've also test on a windows server (2019) with the same pre-reqs and get the same error.

**Comment by SturnusA** [comment]
Dug a bit into the process logs and found that the dedicated server staging branch is missing the below dll's. To temporarily fix this, you can copy the below dll's from your game install bin/win64 folder to the dedicated server bin/win64 folder and the server will launch without issue.

bin/win64/resourcecompiler.dll
bin/win64/modeldoc_utils.dll
bin/win64/dxcompiler.dll

Spoke with @aylaylay and they mentioned that the dedicated server shouldn't need these, but they're marked as dependencies in the staging branch of the dedicated server.

**Comment by aylaylay** [comment]
I've moved this so it's not added on dedicated server - when it's uploaded give it a try and let me know if it fixes the issue

**Comment by SturnusA** [comment]
Almost, getting the below error. Checking process logs and seeing that  it still can't find bin/win64/dxcompiler.dll

Copying the dxcompiler.dll from game install bin/win64 location to the dedicated server install bin/win64 location fixes the error.

![Image](https://github.com/user-attachments/assets/847a5ff6-c9df-4012-9904-b71b05c14f3f)

![Image](https://github.com/user-attachments/assets/2e0ca848-7acf-45bf-b6cb-4fb07d75b6b6)

![Image](https://github.com/user-attachments/assets/4b7db91b-30cc-4b91-9424-708a1ac73239)

**Comment by aylaylay** [comment]
Pushed a fix, hopefully

**Comment by SturnusA** [comment]
That fixed it, you're the best!

**Comment by aylaylay** [comment]
Fantastic
