### ISSUE TITLE
Make soundscapes in the Inspector

### ISSUE THREAD

**Issue by conneath** [Facepunch/sbox-issues#722]
Right now making soundscapes is pretty annoying since you have to mess with manifest files and whatnot
Maybe add a way to make soundscapes in the Inspector like how it's currently possible with soundscripts (.sound)

**Comment by MrBrax** [comment]
soundscapes in general needs an overhaul or at least more debug messages tbh

**Comment by gabengaGamer** [comment]
I agree, snd/env_soundscape needs to be reworked.

**Comment by KayaDLX** [comment]
Maps are dead silent right now in s&box, I really hope we could see a new improved soundscape entity soon.

Related issue: #1565

**Comment by handsomematt** [comment]
Soundscapes were re-implemented the other month
