### ISSUE TITLE
[Model Doc] Cloud browser is not apart of asset browser that is opened

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#7224]
### Describe the bug

Cloud browser is not apart of asset browser that is opened

### To Reproduce

Open a asset browser popup in model doc

### Expected behavior

Cloud should be right next to it

### Media/Files

https://github.com/user-attachments/assets/21670d8d-ae16-4803-8935-1b0e76211c06

**Comment by aylaylay** [comment]
Fixed
