### ISSUE TITLE
Ability to get `SoundHandle` for a `SoundStream`

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#7236]
### What can't you do?

Currently it seems like `SoundStream`'s act entirely different than any other sound's in S&Box.

I would like to create and play a `SoundStream` and be able to take advantage of the rest of the audio tooling that is already in S&Box. More specifically, I would like to be able to play the sound at a specific location in the world.

### How would you like it to work?

`.Handle` on an existing `SoundStream`

### What have you tried?

There is no way of doing this. Including for the specific example of trying to make the sound play at a location in the world.

**Comment by aylaylay** [comment]
SoundStream.Play returns SoundHandle?

**Comment by Remscar** [comment]
I'm baffled that I missed that, thank you.
