### ISSUE TITLE
Shader compile issue (recurring)

### ISSUE THREAD

**Issue by itsmeaddof123** [Facepunch/sbox-issues#7239]
### Describe the bug

I believe the same issue is occurring as seen here: https://github.com/Facepunch/sbox-issues/issues/2647

Assigning a shader to a material yields the following error:
![Image](https://github.com/user-attachments/assets/f697bbd6-5adf-4c7a-b820-ed934e141b11)
The issue persists even when restarting the editor, and I made sure to even test it on the default shader created by the editor itself and found the same issue.

### To Reproduce

Add a shader to a material in the material editor.

### Expected behavior

Shader properly compiles.

### Additional context

Windows 11, most recent update of s&box

**Comment by garrynewman** [comment]
Which shader is it? Can you send it to me?

**Comment by itsmeaddof123** [comment]
I was using the default shader template provided by the editor.

It appears this commit from matt fixed it:
![Image](https://github.com/user-attachments/assets/7005f4ca-4701-43b4-b2e3-04b62abbb3f2)
The template previously lacked modes which was causing this behavior.
