### ISSUE TITLE
Upload texture via Span

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#724]
**What can't you do?**
Upload texture using `ReadOnlySpan<byte>`

**How would you like it to work?**
Uploading using span

**What have you tried?**

**Additional context**
stackalloc my beloved

![IMG_20210819_220507_508.jpg](https://user-images.githubusercontent.com/36124472/130112608-de50a35c-ef35-415a-98a9-7726f4f70cd4.jpg)

Literally

```cs
public unsafe void Upload(ReadOnlySpan<byte> span, ....){
    Upload((byte*) span, span.Length, ...);
}
```
or
```cs
public unsafe void Upload(ReadOnlySpan<byte> span, ....){
    fixed(byte* ptr = span)
        Upload(ptr, span.Length, ...);
}
```

**Comment by goaaats** [comment]
This is likely impossible, since ``unsafe`` defeats the entire security model they are applying.

**Comment by Rohansi** [comment]
> This is likely impossible, since `unsafe` defeats the entire security model they are applying.

Spans do not require unsafe and `stackalloc` is allowed when used with spans.

**Comment by aylaylay** [comment]
I've made it use span, give it a try

**Comment by SupinePandora43** [comment]
> I've made it use span, give it a try

Thank you!
But I'm unable to test it, because i'm fa~~aaaaaaaaaaaaaaaaaa~~r away from pc.

**Comment by SupinePandora43** [comment]
> This is likely impossible, since ``unsafe`` defeats the entire security model they are applying.

@goaaats what security model?
