### ISSUE TITLE
Compile Notifications dropdown selection no longer works

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#7240]
### Describe the bug

![Image](https://github.com/user-attachments/assets/ac96278b-ceca-4f6b-b7d6-2cc23253507b)

Clicking on an option does not change the value

### To Reproduce

1. Open editor
2. Change value of Compile Notifications
3. It does not change

### Expected behavior

It changes

**Comment by aylaylay** [comment]
Fixed
