### ISSUE TITLE
"OnCollisionStart" doesn't detect objects without RigidBody [Tested in VR]

### ISSUE THREAD

**Issue by tinglykarma122** [Facepunch/sbox-issues#7242]
### Describe the bug

While testing ICollisionListener, I realized that it was not possible to detect collision with one of my objects. After sometime, figured out that if you add RigidBody to a object that only had Colliders, it will be detected.

### To Reproduce

1. Add the sample code from "ICollisionListener" (https://sbox.game/dev/doc/the-scene-system/components/component-interfaces/?q=colli) to an object in your project.
2. Add two cubes, with colliders and rigidbody in only one of them. 
3. Interact with these two cubes, and you'll notice that the "Log.Error" only detect collisions with the cube that have rigidbody.

* Tested in VR environment, so item 1 applies to player's hands.

### Expected behavior

I believe that it should detect based on colliders, without adding rigidbody + position/orientation constrain (more applicable to VR).

P.S.: I my project, I needed to detect the collision of one hand to another.

### Media/Files

![Image](https://github.com/user-attachments/assets/70e1dbee-ff19-4938-af4e-c428323b64fc)

### Additional context

O.S./PC Specs:
Windows 11
Ryzen 5600X
16GB DDR4 3200mhz
RTX 2060
HTC Vive

**Comment by aylaylay** [comment]
At least one body has to be dynamic or a trigger for it to generate collisions, this is by design otherwise we'd be generating pointless collisions.
