### ISSUE TITLE
[ModelBuilder] Creating procedural skinned meshes with bones

### ISSUE THREAD

**Issue by stellawisps** [Facepunch/sbox-issues#7243]
### What can't you do?

Currently if you try to add bones to a modelbuilder model you cannot specify weights and the model vanishes.

### How would you like it to work?

AddBone/AddBones which takes in all the current bone information as well as affected meshes, vertices, and weights

### What have you tried?

Tried to make separate meshes with object transforms instead of one model with a skeleton

**Comment by aylaylay** [comment]
You put blend indices and weights in the vertex data
