### ISSUE TITLE
All .NET 9 projects crash on older windows 10

### ISSUE THREAD

**Issue by PaperPrototype** [Facepunch/sbox-issues#7244]
### Describe the bug

Created a fresh install of windows 10, downloaded s&box and tried running it from steam, it immediately crashed. I was wondering why this kept happening, and then I tried running own of my own C# projects. Same thing happened. Created a blank Console app with .NET and it also threw the exact same error as all my other .NET projects
```
CLR: Assert failure(PID 5028 [0x000013a4], Thread: 13704 [0x3588]): !AreShadowStacksEnabled() || UseSpecialUserModeApc()
    File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp:7938 Image:
C:\Users\apape\Documents\GitHub\Prowl\Build\Editor\Debug\net9.0\Prowl.Editor.exe
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[5028] Prowl.Editor.exe' has exited with code -1073740286 (0xc0000602).
```

relevant .NET issue: https://github.com/dotnet/runtime/issues/108589

Solution was to add `<CETCompat>false</CETCompat>` to PropertyGroup for the project. Now everything works... except for s&box 😆

### To Reproduce

1. Create windows 10 bootable USB installer https://support.microsoft.com/en-us/windows/create-an-iso-file-for-windows-10-38547366-1dcb-7afd-1726-9eb222d72705 
2. Fresh install windows
3.  Install steam and s&box, try running s&box

### Expected behavior

s&box opens, and s&box open editor opens and runs (currently it just crashes as soon ass it launches, never even get to see a window open)

### Media/Files

If someone could point me in the direction of logs created by s&box I would love to include those here, as it would help confirm that my diagnosis is accurate.

**Comment by handsomematt** [comment]
Install windows updates

**Comment by PaperPrototype** [comment]
Realized i need to add ` aroundd the property for markdown to not try hiding the potential html tag, issue should have said "Solution was to add `<CETCompat>false</CETCompat>` to PropertyGroup for the project." But yeah I'll try updating windows next.

**Comment by PaperPrototype** [comment]
its fixed if you update your windows 10 to the latest patch fixes.
