### ISSUE TITLE
[Animgraph] 2D Blend "Auto-Calculate Blend Values" seems to do nothing

### ISSUE THREAD

**Issue by Grodbert** [Facepunch/sbox-issues#7245]
### Describe the bug

The Auto Calculate wizard inside a 2D blend doesn't seem to do anything.

### To Reproduce

1. Create a 2D blend node
2. Go inside by double clicking
3. Add a few animation clips through the little blue running man with a plus icon
4. Select them until they're blue
5. Press the little wand icon
6. nothing happens

### Expected behavior

Not sure what the expected behaviour would be, in the context of making movement blends (most common use of 2D blend), one would assume it could:

1. Recognise the names as directions _(N, NE, E, S, W etc)_
2. Give them values accordingly

What values it gives depend really, either it uses a reference _(for example, if walkN is x0, y100, then walkS would be x0, y-100, and WalkE would be x100, y0 etc.)_

Or, ever better, use the root motion to determine how many units it travels, either in that animation, or in a second _(taking into account the framerate set in modeldoc, ex. a run is about 400 units per second at 24fps, at 36fps it's 600)_, this approach makes it easier to set the model speed for programmers, as it normalises the values.

This way you can just dump your whole load of animations, press the wand, and it sets everything up perfectly.

Now that would be worth of a wand icon (wizard operations).

###### The wand in question
![Image](https://github.com/user-attachments/assets/e697e7a2-8e14-4fd7-9d1a-be6f2f2bfa45)

###### in HL:A, the 2D blend is different, so we have no way to see how Valve used this
![Image](https://github.com/user-attachments/assets/51e1a6e7-ca4d-41fc-82d9-110a57fa43ba)

### Additional context

I did try a few things,
using any naming scheme doesn't work, camel, serpent, no directions.
I was told just having "idle, walk, run" makes it work but I couldn't replicate it, although it was Braxen that said it so the source is dubious at best.

**Comment by aylaylay** [comment]
It's based on "Horizontal Axis" and "Vertical Axis"

**Comment by Grodbert** [comment]
I hope this doesn't reopen the issue, but Max and I figured out how to make it work.

It doesn't set up anything if you use parameters to control the Horizontal/Vertical axis, it does, however, if you use "Move speed", "Root Motion Speed", "Forward Speed", "Strafe Speed" and other such variations that were used in Half Life Alyx;

Everyone had assumed that, with the goal/path system being replaced with a parameter approach, all of those metrics had become obsolete.

So thanks for showing us that it wasn't broken or deprecated.
