### ISSUE TITLE
GetAttachment's returned Transform no longer accounts for values after animation

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#7251]
### Describe the bug

Sometime in the last 3 months (while Grubs was hidden), a change to the attachments API occurred so that attachment transforms retrieved from `GetAttachment` no longer account for the position and rotation of the attachment after animation.

The bones API does work for this: I have used TryGetBoneTransform to replicate the behaviour that GetAttachment used to have.

GetAttachment should return the value after animation like it used to, or a new function should be exposed to mimic the old behaviour.

https://cdn.discordapp.com/attachments/1264641510918455451/1321899012042784838/2024-12-26_13-54-32.mp4?ex=676ee9e4&is=676d9864&hm=d56bd0c16a5cf995dce1f035d16104e82c1516e06eeaffd130bba4972a504b9f&

### To Reproduce

1. Open [Grubs](https://github.com/apetavern/grubs)
2. in Weapon::GetMuzzleTransform(), log the value of the transform returned from GetAttachments.
3. Start a game, open the inventory (q), click the bazooka
4. Use W/S to update your aim position.
5. Notice the logged value's position and rotation do not change.

### Expected behavior

There should be a way to get an attachment's transform after animation.

**Comment by aylaylay** [comment]
Fixed
