### ISSUE TITLE
ModelPhysics doesn't take into account the SkinnedModelRenderer's WorldScale

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#7267]
### Describe the bug

When applying a ModelPhysics to ragdoll something, it doesn't take into account that SkinnedModelRenderer scale, and instead will build the collisions (and new model) based on the default scale.
We also encountered this in our other games, where we'd create new enemies by increasing their scale. When they got killed the ragdoll would shrink.

### To Reproduce

1. Create a gameobject with a citizen skinned modelrenderer
2. Scale it up/down
3. Apply a modelphysics component

It will shrink to its default size.

### Expected behavior

ModelPhysics should scale with the model.

### Media/Files

https://github.com/user-attachments/assets/004eb767-80f9-4050-b99a-be988b67d4bd

**Comment by aylaylay** [comment]
ModelPhysics will be obsolete at some point, but I've made it so physics will build with initial scale.
