### ISSUE TITLE
Unable to play certain sounds through code, able to with sound points

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#7268]
### Describe the bug

I have some sound files that seemingly are unable to be called through code, and only code.
They will play through a sound point (Which is what I've done as a workaround in the end), and they will play in the editor, but unlike other sounds I can't get them to play through code.

I've tried exporting them with the same settings as sounds that work, but that didn't change anything, even with 44.1khz and 120bit.
I've tried placing the sound files as options within another working sound, it would only play that original sound and never use any of the ones I place in, and if I removed the original sound S&box would crash.

### To Reproduce

Repro seen in the video:
[my_project_1.zip](https://github.com/user-attachments/files/18264045/my_project_1.zip)

There's a sound point playing the sound on the scene startup, and then there's a component attempting to play the sound via code every second.

### Expected behavior

.

### Media/Files

https://github.com/user-attachments/assets/e6a9c2e8-a4c5-4c5a-a21b-3a53094cd171

**Comment by aylaylay** [comment]
The constructor for soundevent is a name of a sound file, not the name of a sound event. It should be

```cs
Sound.Play( "gift", WorldPosition );
```

**Comment by yuberee** [comment]
Yes that seems to work correctly, weird that my previous method worked for every other sound though.

**Comment by aylaylay** [comment]
Example?

**Comment by yuberee** [comment]
https://github.com/search?q=repo%3ASmall-Fish-Dev%2FChristmassy-Game%20Sound.Play&type=code

Had no issue with
`Sound.Play( new SoundEvent( "sounds/impact.sound" ), WorldPosition )`
as that plays

**Comment by yuberee** [comment]
Ooooh, so that's why I had to manually set the volume. Makes sense now!

**Comment by aylaylay** [comment]
It warns you in the console when you do this.

`File sounds/impact.sound missing vsnd extension (sound). Fixing for now.`
