### ISSUE TITLE
Hidden Skybox with Indirect Lighting still affects scene

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#7288]
### Describe the bug

Pretty much the same as https://github.com/Facepunch/sbox-issues/issues/5910 , wich was fixed, but this time its for Skyboxes with IBL enabled.

Having a a skybox with Indirect Lighting will contribute to the scene's lighting even if that skybox is not supposed to be rendered by certain cameras (render tags stuff). The skybox itself is correctly hidden, but the indirect light is not.

### To Reproduce

1. Have a skybox with indirect lighting
2. Add a tag to it
3. Exclude that tag from rendering on your camera
4. Play scene, see that the indirect lighting still affects the scene

### Expected behavior

Should not affect the scene if its not supposed to be rendered.

### Media/Files

Repro scene:

[repro_light_bleed_skybox.zip](https://github.com/user-attachments/files/18280808/repro_light_bleed_skybox.zip)

Video:

https://github.com/user-attachments/assets/d5c249fb-7111-49cd-b489-564cff8c1c78

**Comment by aylaylay** [comment]
Fixed
