### ISSUE TITLE
[Lists] Any entry added to a list within a GameResource after the first save of the resource wont be saved

### ISSUE THREAD

**Issue by QuackCola** [Facepunch/sbox-issues#7289]
### Describe the bug

Any entries that are added to a list that is within a `GameResource` after the first save of said resource , wont be saved.

### To Reproduce

1. Open the provided project.
2. Within the `Asset Browser` click on the `bugtest.exmplres` resource within the `Assets` category.
3. Add 3 entries to the `List Of Strings` then save the resource. 
4. Add an additional entry and save again. 
5. Select the Model resource that's in the same directory then select the `bugtest.exmplres` resource again.
6. Notice how your last entry wasn't saved.

### Expected behavior

For a list entry to be saved  regardless if its the first save or not.

### Example where the entry `D` doesn't get saved even though I pressed save.

https://github.com/user-attachments/assets/2848464b-398e-49b0-889a-d48d11b2c192

### Example project

[bugreport.zip](https://github.com/user-attachments/files/18281160/bugreport.zip)

**Comment by aylaylay** [comment]
Fixed
