### ISSUE TITLE
Right trigger unbound on Valve Index controller

### ISSUE THREAD

**Issue by taek-dev** [Facepunch/sbox-issues#729]
**Describe the bug**
I'm trying to access the pressed value of the trigger on my right index controller using `Input.VR.RightHand.Trigger.Value`. However, this for some reason always shows as 0, even when the trigger is fully pressed. Getting the value of the trigger on the left controller using `Input.VR.LeftHand.Trigger.Value` returns the correct value, however. Additionally, `Input.VR.RightHand.Trigger.Delta` and `Input.VR.RightHand.Trigger.Active` appear to never change from their default state, making them useless.

**To Reproduce**

1. Write `Log.Info( Input.VR.RightHand.Trigger.Value );` in Simulate on your player class
2. Run the gamemode with VR enabled and your right controller on
3. Open the console
4. Press the trigger
5. The value displayed in the console should remain 0

Do the same with the left hand and the value should change correctly.

**Expected behavior**
The value should change between 0 and 1, exactly how it does with the left controller

**Additional context**
I am using the Valve Index controllers

**Comment by walllable** [comment]
Check your bindings, see if the right trigger is bound. I think the last time I checked, it wasn't. I think Garry mentioned wanting to fix that but I don't remember if he actually did, so it's worth checking I think.

**Comment by taek-dev** [comment]
> Check your bindings, see if the right trigger is bound. I think the last time I checked, it wasn't. I think Garry mentioned wanting to fix that but I don't remember if he actually did, so it's worth checking I think.

You're right, it was unbound. Judging by the scarcity of things *to* bind I'm guessing a lot of this will be obsolete as VR support improves. I'll rename this issue to be more accurate to the issue.

**Comment by garrynewman** [comment]
Are my binding json's wrong?
