### ISSUE TITLE
Assets dont load in project with code errors

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#7290]
### What can't you do?

I have a project, i open it, the code has errors, it doesnt load any of the assets now, everything is empty
now artists can access anything to fix models, change stuff and so on.

### How would you like it to work?

Just load the assets it can load, and components that dont exist from the errored code should just come up as missing component.

### What have you tried?

I have to delete all the code from the project in order to do what i need,
this is awful and makes artists workflow really shitty.

please dont say "just dont have errors" 
since this is specifically for artists working in projects.

**Comment by handsomematt** [comment]
Don't have code errors in your project
