### ISSUE TITLE
ModelDoc - Add support for concave physics meshes

### ISSUE THREAD

**Issue by TitusStudiosMediaGroup** [Facepunch/sbox-issues#730]
**What can't you do?**
Have complex/concave physics meshes (only hulls are supported?)

**How would you like it to work?**
Same as `PhysicsMeshFile` but have it support physics and not just collisions.

**What have you tried?**
Currently to use complex meshes without splitting them into many (which is very time consuming, and in some cases it wouldnt help), I've had a friend edit the physics mesh in Blender so it cant weld when used in `PhysicsHullFile` with the Import Mode set to "Hull Per Element". I've been told that the method my friend used to prevent the welding is complicated and would be hard to do on complex models (such as curved tracks).

**Images**
Currently what happens:
![https://i.imgur.com/qDNhDhr.png](https://i.imgur.com/qDNhDhr.png)
![https://i.imgur.com/HktTZ2J.png](https://i.imgur.com/HktTZ2J.png)

**Comment by aylaylay** [comment]
Why does a train track need physics?

**Comment by TitusStudiosMediaGroup** [comment]
Physics based trains

**Comment by aylaylay** [comment]
The track doesn't need to be physically simulated to do that. This will never be added by the way, you'll be lucky to find a physics engine that supports concave shapes for simulated bodies, it's technically possible but never worth doing. I'm just curious why you think you need this, a train track should be static.

**Comment by TitusStudiosMediaGroup** [comment]
Thanks for the info, you are correct it does not need to be simulated for the tracks, was bit of an oversight on my behalf, the bogies that run on the tracks attached to the train would have been a better example. Regardless if its not worth adding then this is pointless, closing.

**Comment by thegrb93** [comment]
@TitusStudiosMediaGroup the technique is to use many convex shapes to build up a concave shape. The algorithm isn't smart enough to do this automatically.
