### ISSUE TITLE
Hardcrash on Deleted Entity when Client changes GlowActive

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#732]
**Describe the bug**

When the Entity has been deleted on the Server but still exists on the client and the client tries to change the GlowActive.
It hardcrashes to Desktop.

**To Reproduce**

[glow-state-hardcrash.zip](https://github.com/Facepunch/sbox-issues/files/7023443/glow-state-hardcrash.zip)

1. Use the Addon provided
2. Go onto any map
3. ent_create sf_pistol
4. Pickup the Pistol.
5. Spawn a second Pistol.
6. Pickup the second Pistol while looking at it.
7. See hardcrash.

**Expected behavior**

it shouldn't hardcrash and rather throw an exception

**Screenshots**

Stacktrace from VSC C# Debugger attached to the Sbox-dev.exe

![unknown (2)](https://user-images.githubusercontent.com/37816311/130277102-ea5fb0b7-287b-4444-8935-13c36f54afb2.png)

**Additional context**

The workaround is to check if the entity IsValid() before changing it.
but it shouldn't hardcrash regardless.
like this:
![image](https://user-images.githubusercontent.com/37816311/130277601-32c38225-9428-4fce-b5e8-7045a3a485b3.png)

it should throw a NullRef exception rather than quit to desktop

**Comment by aylaylay** [comment]
I have pushed a fix for this, it will now assert as expected. Just a tip, you can just do lastEnt.IsValid because it itself does a null check too, you don't need to do both.

Please close the issue if it works for you when the build has been pushed to steam.

**Comment by Adesii** [comment]
yep, it now just throws an error instead of hardcrashing.

good to know that IsValid also does a null check. Makes sense.

Thanks!
