### ISSUE TITLE
Improper XML Documentation Comments breaks codegen.

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#736]
Description:
When writing a documentation comment, triple forward slash and an XML tag, codegen breaks if tags are improperly closed.

Reproduction:
1. Place ///<anything> anywhere in the code.
2. Start playing the game mode.

Expected Behaviour:
Improper comments are ignored and compilied code runs normally.

Screenshots:
Fine -
![devenv_YtUcC8tMBP](https://user-images.githubusercontent.com/36082767/130310260-0003931b-cc52-4021-8c02-7cede46d508d.png)

Not fine -
![devenv_mHZyGdWPr4](https://user-images.githubusercontent.com/36082767/130310263-1c11701f-19b9-43a2-879a-e2a91a06acf6.png)
![devenv_FUOoU26TuY](https://user-images.githubusercontent.com/36082767/130310265-b6263ba1-880f-4918-913f-113f0ad63607.png)
![devenv_a49HHvd5Kd](https://user-images.githubusercontent.com/36082767/130310316-aed80fa5-9352-4927-aa0f-f34ee30296fb.png)

Error -
![sbox-dev_pZZwZnjtZ7](https://user-images.githubusercontent.com/36082767/130310278-16ea16e4-9336-4f7e-a7e9-12a98d9929c0.png)
![sbox-dev_MDrvHTusI7](https://user-images.githubusercontent.com/36082767/130310279-a2bb0d02-b90b-48a3-9f78-15a3bfc8129d.png)

Additional Information:
This breaks code from files unrelated to the offending script also, for example for me this occurs when firing -
![sbox-dev_fR3ZpJFMpn](https://user-images.githubusercontent.com/36082767/130310454-e6728ac4-b8da-4ef3-af8c-fd92137963f8.png)

With the gun not actually firing. (No bullet holes, muzzle flash, or gun firing animation)
When the offending comment is in a script unused in the scene.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates. Please close the issue if you feel this is solved.
