### ISSUE TITLE
Re-add the .editorconfig

### ISSUE THREAD

**Issue by rtm516** [Facepunch/sbox-issues#74]
**What can't you do?**
N/A

**How would you like it to work?**
All addons have the same code style by default

**What have you tried?**
Copying the old .editorconfig into my addons works but ofc that will only be for me

**Additional context**
https://share.rtm516.co.uk/VunE4/xoFAceZE46.editorconfig is the original `.editorconfig`

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Tripperful** [comment]
Seems to be fixed now
