### ISSUE TITLE
Entity.EntityName should be Entity.Name

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#741]
**What it it**

Entity.EntityName

**What it should be**

Entity.Name

**Comment by robotboy655** [comment]
This conflicts with `ClientEntity.Name` which is the player's name, and I'd rather avoid having same confusion that we have in GMod, where you are unable to grab player entity's targetname.

Maybe `ClientEntity.Name` and `Client.Name` should be `ClientEntity.Nickname` or `ClientEntity.PlayerName`?

**Comment by garrynewman** [comment]
I don't see any real harm in keeping it as ClientEntity.Name
