### ISSUE TITLE
Network Mapped Hardlinks break loading of local Addons.

### ISSUE THREAD

**Issue by Moonded** [Facepunch/sbox-issues#749]
**Describe the bug**
Hardlink (inclusive junktions and symbolic links) break the loading process of addons in the local addons folder, after the sbox-dev.exe reaches said link.

**To Reproduce**
The Link in the Addon Folder needs to be named alphabetically before the menu folder for the menu to break!

1. Map a Network Drive to windows.
2. Create a symbolic link to that drive
3. Create a Directiory Junktion to that Smbolic link
4. Wait untill the games finnished loading. (Sometimes it wont end loading)

--

1. Map a Network Drive to windows.
2. Create Directory Junktion to the Networked Drive.
3. Wait untill the games finnished loading. (Sometimes it wont end loading)

**Expected behavior**
The excepcted behaviour would be a working hardlink, which would point to the assets/gamemode on the network drive and the game would be working fine/loading everything without a problem

OR 

The game would ignore hardlinks, etc and or skip those, without stop loading other assets.

**Screenshots**
https://i.imgur.com/XtHPTHZ.png
https://i.imgur.com/LKw1Ciw.png

**Additional context**
The reason I would like to use a network drive is to create more space on my drive and to ease the asset flow on out library for the team I am working with.

**Comment by garrynewman** [comment]
Are you getting any errors in our log files?

**Comment by Moonded** [comment]
I can"t see any errors regarding loading the asset folder (the hardlink folder), except not finding a .addon which is obvious as the folder is not a gamemode, but only for assets.

Anyway, here are the latest and only logs from yesterday. 

[Log.112.log](https://github.com/Facepunch/sbox-issues/files/7027167/Log.112.log)
[Log.log](https://github.com/Facepunch/sbox-issues/files/7027168/Log.log)
[Log.111.log](https://github.com/Facepunch/sbox-issues/files/7027169/Log.111.log)

**Comment by garrynewman** [comment]
I don't really understand what you're doing here, but to be honest I don't know whether it's up to us to support it. If you're creating symlinks in the OS then the running program should be unaware that they exist if it's doing it properly.

You know about `addon_add` right?

**Comment by Moonded** [comment]
I actually did not know about `addon_add` but that worked with network drives, thus im using that now.

Sbox could be breaking because normaly you cant have hardlinks with network drives.
