### ISSUE TITLE
Player ping, fakelag & fakeloss for network debugging

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#75]
**What can't you do?**

See player ping ~~or simulate poor network conditions~~

**How would you like it to work?**

BasePlayer could have a Ping property
~~net_fakelag / net_fakeloss convars for the client~~

~~net_fakelag exists already but doesn't seem to work.~~

**Comment by Lexa013** [comment]
What's the utility ?

**Comment by garrynewman** [comment]
Fakelag is possible.. 

It'll work as a regular client to a server but if you want to test it on a listen server you need to enable a different network mode for loopback connections.

So before you create your game set `net_usesocketsforloopback  1` and it net_fakelag should work.

**Comment by cr4yz** [comment]
> Fakelag is possible..
> 
> It'll work as a regular client to a server but if you want to test it on a listen server you need to enable a different network mode for loopback connections.
> 
> So before you create your game set `net_usesocketsforloopback 1` and it net_fakelag should work.

Ahh `net_usesocketsforloopback` before creating the game does it.

Come to think I'm not sure I really need fake loss, probably don't have to worry about it & it can be handled with an external program.
