### ISSUE TITLE
WalkController JumpFactor is hard coded

### ISSUE THREAD

**Issue by WhiskeeDev** [Facepunch/sbox-issues#751]
**What can't you do?**
Change the JumpFactor of the WalkController from a subclass without overriding and recreating the `CheckJumpButton` function.

**How would you like it to work?**
Define a `JumpFactor` Property in the WalkController Class, default to `1.2f`, and introduce this in line 483.

**What have you tried?**
Copying and overriding the `CheckJumpButton` function in my Controller subclass and changing the hardcoded jump factor in there.

**Additional context**
N/A

**Comment by bakscratch** [comment]
The WalkController is obsolete now.
