### ISSUE TITLE
Map Surface Properties Broken

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#754]
Static surface properties in maps don't work. This is because we add them at runtime, and while they exist in the game process, when compiling the map it starts a new process - which doesn't have them.

Easy solution is to have Hammer or something dump them to an easily loaded text file. AFAIK the compile process doesn't actually need to know the properties, just the names.

**Comment by aylaylay** [comment]
I can't see where this is broken, static surfaces seem to be working fine.

**Comment by robotboy655** [comment]
Meshes tied to entities also work fine in my tests, although I have not tested things like friction, only sounds and decals.

**Comment by aylaylay** [comment]
Done
