### ISSUE TITLE
Asset Brower should remember

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#755]
When selecting textures or materials, the search in asset browser should remember what you last searched for.

This would mean that when selecting multiple textures, for materials say, you wouldn't have to keep filling it out again. It'd open to the window where you selected the previous one. Speeding shit up.

**Comment by MrBrax** [comment]
would be nice if the system file browser remembered paths too for each module

**Comment by aylaylay** [comment]
Is there an example of this not working, I'm testing in modeldoc and every time I find a new material, it has my last search
