### ISSUE TITLE
Animgraph Editor: Grid/Snapping

### ISSUE THREAD

**Issue by N-cognito** [Facepunch/sbox-issues#759]
**What can't you do?**
Move/arrange nodes in neat and visually pleasing ways. Currently everything has to be placed manually and freehand, which leads to small but noticeable and unpleasant misalignments when trying to sort node groups, especially if you have a lot of nodes

**How would you like it to work?**
An option to enabled grid-snapping, which would only allow nodes to move in certain intervals, and an option to change said interval. Or, instead of an option for grid-snapping, a hotkey you can press when a node is selected to move it with grid-snapping instead of the usual drag-and-drop moving via left click.

**What have you tried?**
This can be done manually by editing m_vecPosition for each node in a text editor, but at a certain point there is just too many nodes to manage and keep track of

**Comment by aylaylay** [comment]
I've just added this, you can find the grid snap setting in the options window. Please close the issue if it works for you and you're happy with it. Note: the setting probably doesn't save, I wont be adding saving yet for a low priority feature.

**Comment by aylaylay** [comment]
I've defaulted the snap value to 16 anyway which is probably what everyone will be happy with using.

**Comment by N-cognito** [comment]
Would you be able to add the snapping into the State Machine nodes as well? Currently they don't inherit the snapping.

**Comment by aylaylay** [comment]
done
