### ISSUE TITLE
ModelDoc: Non-capsule collision for jigglebones

### ISSUE THREAD

**Issue by N-cognito** [Facepunch/sbox-issues#760]
**What can't you do?**
Change jigglebone collision to anything other than a capsule. Capsules simple do not work for a majority of jigglebones that need collision.

**How would you like it to work?**
Either an option to change the collision type from a capsule to a box, or an option to choose a custom physics mesh/shape to use for collision calculations

**What have you tried?**
Creating a cloth collision box on the same bone as the jigglebone, and setting it to a collision group that said jigglebone ignores. Unfortunately does not work for said jigglebone interacting with other collisions, but works for other jigglebones interacting with that box/bone.

**Comment by aylaylay** [comment]
From my initial look at it, this isn't so straight forward to do and not something I'll be trying any time soon.
