### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by serozr** [Facepunch/sbox-issues#762]
**How would you like it to work?**

a discord rich presence can be added. In this way, we can learn which game mode the people playing the game mode are playing, and on which server they are playing.

like this : https://imgur.com/a/653gsW3

**Comment by FlorianLeChat** [comment]
Besides, if this feature is added, it will be cool if it can be customized.

**Comment by Sardonyx78** [comment]
This can be implemented by the gamemodes,just modify the access config and connect through discord's rich presence gateway. Implementing a default rich presence is a bad idea imo, the developer might want to add their custom one's and it would be overridden by the game itself.

**Comment by FlorianLeChat** [comment]
> Just modify the access config and connect through discord's rich presence gateway.

This is exactly what I want to avoid doing. If this isn't possible with the current restrictions, that's why we're asking for a way to modify it through the tools implemented by the developers.

**Comment by DevulTj** [comment]
Not planned
