### ISSUE TITLE
Access (VR) controller haptics

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#763]
**What can't you do?**
There is no controller haptics access at all currently.

**How would you like it to work?**
Possibly just Input.VR.LeftHand.TriggerHaptics(Amplitude, Duration) but I'm not sure what all the available variables are in the SteamVR haptics API.

**Additional context**
Might also want to add a Todo for gamepad haptics later but clearly the API can't be the same given that VR has left/right hands.

**Comment by xezno** [comment]
This would be super useful! The [SteamVR unity library has a function](https://valvesoftware.github.io/steamvr_unity_plugin/api/Valve.VR.ISteamVR_Action_Vibration.html), `Execute(float secondsFromNow, float durationSeconds, float frequency, float amplitude, SteamVR_Input_Sources inputSource)` that does this - would be nice if we could get the same / similar in s&box i.e. `Input.VR.RightHand.Vibrate( 0f, 0.5f, 10f, 1.0f );`

**Comment by handsomematt** [comment]
Added VrHand.TriggerHapticVibration( float duration, float frequency, float amplitude )
Usage: Input.VR.LeftHand.TriggerHapticVibration( 0.25f, 100.0f, 1.0f )

Let me know if it doesn't work for your specific devices
