### ISSUE TITLE
Hammer no longer builds since the last update

### ISSUE THREAD

**Issue by Maxime66410** [Facepunch/sbox-issues#768]
When we want to build a map on hammer we can no longer build a map on any type of project.

1. Go to Hammer
2. Click on All Build
3. Scroll down to Console

`Start build: 2021-08-23T19:42:38
Hammer: Attempting incremental build.
Hammer: Copying previously compiled map to temp directory.
Unzip cinema.vpk (22 files):
Done (0.1 sec: 0.5ms read, 28.5ms write 0.6mb).
- addons\cinema\maps\cinema.vmap
Hammer FGD: d:\programmes\steam\steamapps\common\sbox\addons\base\config\base.fgd (config/base.fgd)
Hammer FGD: d:\programmes\steam\steamapps\common\sbox\addons\zombiepanic\config\zombiepanic.fgd (config/zombiepanic.fgd)
Settling physics objects...no objects to settle
Building map "maps\cinema"...

... Building 'world'
Loading Map...Done (0.34 seconds) 

Creating World
Fixing T-junction edge cracks...Done 0.1 seconds
Generate Overlay Meshes...[0....1....2....3....4....5....6....7....8....9....] Done (0.00 seconds)
Creating 1 world nodes Building render clusters... 1 meshes, 13579 triangles... 6 clusters (0.00 seconds)
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vmdl"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!
SaveGeometryToDMX: SaveToFile "c:\users\max66\appdata\local\temp\valve\rc_mapbld_7192\cinema\maps\cinema\worldnodes\node000_lr0_b0_s_cb_mesh_base.vmdl" failed!
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vmdl"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!
SaveGeometryToDMX: SaveToFile "c:\users\max66\appdata\local\temp\valve\rc_mapbld_7192\cinema\maps\cinema\worldnodes\node000_lr0_b1_s_cb_mesh_base.vmdl" failed!
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vmdl"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!
SaveGeometryToDMX: SaveToFile "c:\users\max66\appdata\local\temp\valve\rc_mapbld_7192\cinema\maps\cinema\worldnodes\node000_lr0_b2_s_cb_mesh_base.vmdl" failed!
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vmdl"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!
SaveGeometryToDMX: SaveToFile "c:\users\max66\appdata\local\temp\valve\rc_mapbld_7192\cinema\maps\cinema\worldnodes\node000_lr0_b3_s_cb_mesh_base.vmdl" failed!
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vmdl"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!
SaveGeometryToDMX: SaveToFile "c:\users\max66\appdata\local\temp\valve\rc_mapbld_7192\cinema\maps\cinema\worldnodes\node000_lr0_b4_s_cb_mesh_base.vmdl" failed!
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vmdl"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!
SaveGeometryToDMX: SaveToFile "c:\users\max66\appdata\local\temp\valve\rc_mapbld_7192\cinema\maps\cinema\worldnodes\node000_lr0_b5_s_cb_mesh_base.vmdl" failed!
Building bounds groups...[0....1....2....3....4....5....6....7....8....9....] Done (0.00 seconds)
+- addons\cinema\maps\cinema\worldnodes\node000.vwnod
+- addons\cinema\maps\cinema\entities\default_ents.vents
+- addons\cinema\maps\cinema\world.vwrld
Created 1 world nodes
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vrman"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!

... Building 'phys'
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vphys"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vrman"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
File "" doesn't exist!

... Building 'nav'
Nav settings not found, using default settings.
>>NAVGEN: pass 1/3: orig tris 11988
>>NAVGEN: -- Start --
>>NAVGEN: stage 01 / 26: WeldVertices took 0.004 sec, produced 11988 polys
>>NAVGEN: stage 02 / 26: RemoveDegens took 0.001 sec, produced 11988 polys
>>NAVGEN: stage 03 / 26: Recast took 1.499 sec, produced 5396 polys
>>NAVGEN: stage 04 / 26: WeldVertices took 0.008 sec, produced 5396 polys
>>NAVGEN: stage 05 / 26: RemoveDegens took 0.001 sec, produced 5396 polys
>>NAVGEN: stage 06 / 26: MatchPolysToGround, disabled
>>NAVGEN: stage 07 / 26: SplitPolysByMarkup took 0.000 sec, produced 5396 polys
>>NAVGEN: stage 08 / 26: RemovePolysMarkedNoNav took 0.000 sec, produced 5396 polys
>>NAVGEN: stage 09 / 26: RemoveStrayVerticalPolys took 0.000 sec, produced 5392 polys
>>NAVGEN: stage 10 / 26: WeldVertices took 0.002 sec, produced 5392 polys
>>NAVGEN: stage 11 / 26: RemoveDegens took 0.000 sec, produced 5392 polys
>>NAVGEN: stage 12 / 26: MergePolys took 0.164 sec, produced 2075 polys
>>NAVGEN: stage 13 / 26: LimitMaxPolyEdges took 0.000 sec, produced 2075 polys
>>NAVGEN: stage 14 / 26: LimitMaxPolyEdgeLen took 0.000 sec, produced 2077 polys
>>NAVGEN: stage 15 / 26: RemoveStrayVerticalPolys took 0.000 sec, produced 2077 polys
>>NAVGEN: stage 16 / 26: WeldVertices took 0.001 sec, produced 2077 polys
>>NAVGEN: stage 17 / 26: RemoveDegens took 0.000 sec, produced 2077 polys
>>NAVGEN: stage 18 / 26: SplitPolysByMarkup took 0.000 sec, produced 2077 polys
>>NAVGEN: stage 19 / 26: WeldVertices took 0.001 sec, produced 2077 polys
>>NAVGEN: stage 20 / 26: RemoveDegens took 0.000 sec, produced 2077 polys
>>NAVGEN: stage 21 / 26: ClipPolysToHullClearance took 0.062 sec, produced 2091 polys
>>NAVGEN: stage 22 / 26: GenerateConnections took 0.004 sec, produced 2091 polys
>>NAVGEN: stage 23 / 26: SplitBoundaryPolysWithConnections, disabled
>>NAVGEN: stage 24 / 26: AddJumps took 0.021 sec, produced 2091 polys
>>NAVGEN: stage 25 / 26: RemoveSmallAreasOnEdge took 0.000 sec, produced 2091 polys
>>NAVGEN: stage 26 / 26: IslandRemoval, disabled
>>NAVGEN: -- End --
>>NAVGEN: pass 2/3: orig tris 11988
>>NAVGEN: -- Start --
>>NAVGEN: stage 01 / 26: WeldVertices took 0.004 sec, produced 11988 polys
>>NAVGEN: stage 02 / 26: RemoveDegens took 0.001 sec, produced 11988 polys
>>NAVGEN: stage 03 / 26: Recast took 1.336 sec, produced 5981 polys
>>NAVGEN: stage 04 / 26: WeldVertices took 0.009 sec, produced 5980 polys
>>NAVGEN: stage 05 / 26: RemoveDegens took 0.001 sec, produced 5980 polys
>>NAVGEN: stage 06 / 26: MatchPolysToGround, disabled
>>NAVGEN: stage 07 / 26: SplitPolysByMarkup took 0.000 sec, produced 5980 polys
>>NAVGEN: stage 08 / 26: RemovePolysMarkedNoNav took 0.000 sec, produced 5980 polys
>>NAVGEN: stage 09 / 26: RemoveStrayVerticalPolys took 0.000 sec, produced 5975 polys
>>NAVGEN: stage 10 / 26: WeldVertices took 0.002 sec, produced 5975 polys
>>NAVGEN: stage 11 / 26: RemoveDegens took 0.001 sec, produced 5975 polys
>>NAVGEN: stage 12 / 26: MergePolys took 0.170 sec, produced 2247 polys
>>NAVGEN: stage 13 / 26: LimitMaxPolyEdges took 0.000 sec, produced 2247 polys
>>NAVGEN: stage 14 / 26: LimitMaxPolyEdgeLen took 0.000 sec, produced 2250 polys
>>NAVGEN: stage 15 / 26: RemoveStrayVerticalPolys took 0.000 sec, produced 2250 polys
>>NAVGEN: stage 16 / 26: WeldVertices took 0.001 sec, produced 2250 polys
>>NAVGEN: stage 17 / 26: RemoveDegens took 0.000 sec, produced 2249 polys
>>NAVGEN: stage 18 / 26: SplitPolysByMarkup took 0.000 sec, produced 2249 polys
>>NAVGEN: stage 19 / 26: WeldVertices took 0.001 sec, produced 2249 polys
>>NAVGEN: stage 20 / 26: RemoveDegens took 0.000 sec, produced 2249 polys
ClipPolysToHullClearanceInternal - too many non-reducing passes
>>NAVGEN: stage 21 / 26: ClipPolysToHullClearance took 0.069 sec, produced 2249 polys
>>NAVGEN: stage 22 / 26: GenerateConnections took 0.006 sec, produced 2249 polys
>>NAVGEN: stage 23 / 26: SplitBoundaryPolysWithConnections, disabled
>>NAVGEN: stage 24 / 26: AddJumps took 0.022 sec, produced 2249 polys
>>NAVGEN: stage 25 / 26: RemoveSmallAreasOnEdge took 0.000 sec, produced 2249 polys
>>NAVGEN: stage 26 / 26: IslandRemoval, disabled
>>NAVGEN: -- End --
>>NAVGEN: pass 3/3: orig tris 11988
>>NAVGEN: -- Start --
>>NAVGEN: stage 01 / 26: WeldVertices took 0.005 sec, produced 11988 polys
>>NAVGEN: stage 02 / 26: RemoveDegens took 0.001 sec, produced 11988 polys
>>NAVGEN: stage 03 / 26: Recast took 1.655 sec, produced 5315 polys
>>NAVGEN: stage 04 / 26: WeldVertices took 0.007 sec, produced 5315 polys
>>NAVGEN: stage 05 / 26: RemoveDegens took 0.001 sec, produced 5315 polys
>>NAVGEN: stage 06 / 26: MatchPolysToGround, disabled
>>NAVGEN: stage 07 / 26: SplitPolysByMarkup took 0.000 sec, produced 5315 polys
>>NAVGEN: stage 08 / 26: RemovePolysMarkedNoNav took 0.000 sec, produced 5315 polys
>>NAVGEN: stage 09 / 26: RemoveStrayVerticalPolys took 0.000 sec, produced 5305 polys
>>NAVGEN: stage 10 / 26: WeldVertices took 0.002 sec, produced 5305 polys
>>NAVGEN: stage 11 / 26: RemoveDegens took 0.000 sec, produced 5305 polys
>>NAVGEN: stage 12 / 26: MergePolys took 0.127 sec, produced 2220 polys
>>NAVGEN: stage 13 / 26: LimitMaxPolyEdges took 0.000 sec, produced 2220 polys
>>NAVGEN: stage 14 / 26: LimitMaxPolyEdgeLen took 0.000 sec, produced 2221 polys
>>NAVGEN: stage 15 / 26: RemoveStrayVerticalPolys took 0.000 sec, produced 2221 polys
>>NAVGEN: stage 16 / 26: WeldVertices took 0.001 sec, produced 2221 polys
>>NAVGEN: stage 17 / 26: RemoveDegens took 0.000 sec, produced 2221 polys
>>NAVGEN: stage 18 / 26: SplitPolysByMarkup took 0.000 sec, produced 2221 polys
>>NAVGEN: stage 19 / 26: WeldVertices took 0.001 sec, produced 2221 polys
>>NAVGEN: stage 20 / 26: RemoveDegens took 0.000 sec, produced 2221 polys
>>NAVGEN: stage 21 / 26: ClipPolysToHullClearance took 0.073 sec, produced 2228 polys
>>NAVGEN: stage 22 / 26: GenerateConnections took 0.006 sec, produced 2228 polys
>>NAVGEN: stage 23 / 26: SplitBoundaryPolysWithConnections, disabled
>>NAVGEN: stage 24 / 26: AddJumps took 0.025 sec, produced 2228 polys
>>NAVGEN: stage 25 / 26: RemoveSmallAreasOnEdge took 0.000 sec, produced 2228 polys
>>NAVGEN: stage 26 / 26: IslandRemoval, disabled
>>NAVGEN: -- End --
>>NAVGEN: -- Start --
>>NAVGEN: stage 01 / 01: IslandRemoval took 0.008 sec, produced 0 polys
>>NAVGEN: -- End --
GenerateResourceNameFromFileName: Invalid extension specified in file name "."!
ERROR: Could not construct resource handle for ".vrman"
CResourceCompilerPathScope - Failed to split search path C:\Users\max66\AppData\Local\Temp\valve\rc_vpk_7192\game\cinema\
Error! Unknown resource type for ""!
Failed to compile resource manifest world.vrman
--> Map build finished.
Pack cinema.vpk (C:\Users\max66\AppData\Local\Temp\valve\hammermapbuild\game\cinema\maps\cinema.vpk):
Writing... Done.
0/ 1 (elapsed 6.972): d:\programmes\steam\steamapps\common\sbox\addons\cinema\maps\cinema.vmap
Compile of 1 file(s) matching nonrecursive specification "d:/programmes/steam/steamapps/common/sbox/addons/cinema/maps/cinema.vmap" took 6.972 seconds
-----------------------------------------------------------------
ERROR: 4 compiled, 10 failed, 0 skipped, 0m:08s
-----------------------------------------------------------------
Leaking 2 elements Using breakpad crash handler Setting breakpad minidump AppID = 590830 Forcing breakpad minidump interfaces to load Looking up breakpad interfaces from steamclient Calling BreakpadMiniDumpSystemInit Looking up breakpad interfaces from steamclient Calling BreakpadMiniDumpSystemInit SteamInternal_SetMinidumpSteamID: Caching Steam ID: 76561198156802806 [API loaded yes] SteamInternal_SetMinidumpSteamID: Setting Steam ID: 76561198156802806 End build: 2021-08-23T19:42:47, elapsed time 0h:00m:09s.007ms
`

**Comment by Sherlock2004** [comment]
This problem is similar for everyone, even for me. Hopefully it will be corrected in the near future.

**Comment by pBinarySoul** [comment]
Fixed already.
