### ISSUE TITLE
[Event.Tick] is never called clientside

### ISSUE THREAD

**Issue by Mikusch** [Facepunch/sbox-issues#770]
**Describe the bug**
`[Event.Tick]` never runs clientside tick despite its documentation saying otherwise.

**To Reproduce**

```cs
namespace Example
{
	[Library( "entity_test" )]
	public class TestEntity : Entity
	{
		[Event.Tick]
		protected virtual void OnTick()
		{
			if ( IsServer )
				Log.Info( "Called serverside!" );	// Always printed
			else if ( IsClient )
				Log.Info( "Called clientside!" );	// Never printed
		}
	}
}

```

**Expected behavior**
`[Event.Tick]` should run clientside tick.

**Additional context**
`[Event.Tick.Client]` does not appear to be working either.

**Comment by kwerber** [comment]
Is the entity even networked to the client?

**Comment by handsomematt** [comment]
Your entity isn't networked to the client...

Look at Entity.Transmit
