### ISSUE TITLE
[ModelDoc] Focused Mesh doesn't parents on bone

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#771]
**Describe the bug**
Focused mesh ignores bone position

**To Reproduce**

1. Add RenderMeshFile
2. Create Bone
3. set bone of rendermeshfile
4. move bone
5. mesh file moves too
6. select rendermeshfile
7. see error - meshfile is now at 0,0,0
**Expected behavior**
meshfile is at bone position

**Screenshots**

![image](https://user-images.githubusercontent.com/36124472/130566201-07f84f53-4968-44a4-a40c-778634f815fc.png)
![image](https://user-images.githubusercontent.com/36124472/130566172-3648d020-5c02-4939-a31f-991d95704c68.png)

![image](https://user-images.githubusercontent.com/36124472/130566232-0c2c46bd-37f0-4e4c-b9f9-f0350974d52e.png)
![image](https://user-images.githubusercontent.com/36124472/130566275-13948a55-49d0-4060-a1b8-394aa5962f38.png)

**Comment by aylaylay** [comment]
Pushed a fix, please close the issue if it works for you and you're happy with it.
