### ISSUE TITLE
OnSequenceFinished and OnNewSequence shouldn't be on Entity

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#777]
I have moved both to `AnimEntity`. We should probably do the same with `OnSequenceFinished` and `OnNewSequence`, they will also only be called for AnimEntities.

_Originally posted by @robotboy655 in https://github.com/Facepunch/sbox-issues/issues/738#issuecomment-904803981_

**Comment by robotboy655** [comment]
Moved these 2 to AnimEntity too.
