### ISSUE TITLE
direct volumetric light does not work for light_environment

### ISSUE THREAD

**Issue by kote2345** [Facepunch/sbox-issues#778]
**Describe the bug**

Direct volumetric light does not work for light_environment, volumetric light working only for indirect lighting. As far as I remember, this worked in s&box around the end of May. In Half-Life Alyx, this also does not work

**To Reproduce**

1. put light_environment on map
2. turn on Volumetric Fogging for him
3. put env_volumetric_fog_controller on map
4. See that volumetric light does not work for light_environment for direct lighting

**Expected behavior**

It is expected that volumetric light will work as for other light sources

**Comment by VeeSaus** [comment]
Light_environment is intentionally set to not support volumetric fogging, as the fogging would cover the entire map. You can achieve environmental fog through the use of cubemap- and gradient fog. If it is godrays that you want, then you can use an orhto light, with diffuse and indirect lighting turned off, with the same angles as the sun.

**Comment by kote2345** [comment]
> If it is godrays that you want, then you can use an orhto light, with diffuse and indirect lighting turned off, with the same angles as the sun

I tried it, it is not suitable for open maps. I would like godrays for a large open map. The more volume light_ortho has, worse resolution of volumetric light, so you end up with just fog instead of godrays

**Comment by bakscratch** [comment]
The fog option on light_environment was removed a while back
