### ISSUE TITLE
Hold jump to rise in water

### ISSUE THREAD

**Issue by JamesC01** [Facepunch/sbox-issues#779]
**What can't you do?**
Right now, you have to tap space to rise in water, which causes problems, since double tapping space (at least in sandbox) causes you to noclip.

**How would you like it to work?**
Like half life 2, when you hold jump, you keep rising until you reach the surface.

I know this is probably easily fixed in code, but I think it would be nice to have the half life 2 style as default.

**Comment by DevulTj** [comment]
Not a s&box specific issue.
