### ISSUE TITLE
selection tool bug on mesh position that far from map grid

### ISSUE THREAD

**Issue by miw1234** [Facepunch/sbox-issues#780]
**Describe the bug**

selection tool does not work properly on object position that far from map grid

**To Reproduce**

1.creating some mesh and put it faraway from map grid
2.use selection tool or press q on that mesh

**Expected behavior**

selection tool should work properly on outside of mapgrid

**Screenshots**

![image](https://user-images.githubusercontent.com/49024001/130674665-24a9c628-3baf-4142-81c6-f7ca78ec250a.png)

**Additional context**
there is video this should be explanation as well
[Video](https://www.youtube.com/watch?v=Ft_P0yj7nd4)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates. There will still be a limit, but its now at 90+ times the distance which should be more than enough.

**Comment by miw1234** [comment]
yeah it's fixed thanks!
