### ISSUE TITLE
Get random point on Nav Mesh 

### ISSUE THREAD

**Issue by MackenzieShirk** [Facepunch/sbox-issues#785]
**What can't you do?**
I cant properly grab a random point on the nav mesh

**How would you like it to work?**
Should work like the other NavMesh functionality
`public static Vector3? GetRandomPoint(Vector3 point);`

**What have you tried?**
Very hacky work around is to use GetPointWithinRadius, set the point to 0,0,0, use a massive radius that covers the map.

**Comment by DrakeFruit** [comment]
Navmesh.GetRandomPoint();
