### ISSUE TITLE
Light Cookie is applied to all light_omni after applying Light Cookie to light_spot

### ISSUE THREAD

**Issue by kote2345** [Facepunch/sbox-issues#787]
**Describe the bug**

Light Cookie is applied to all light_omni after applying Light Cookie to light_spot

**To Reproduce**

1. Put light_spot on map
2. Select Light Cookie in light_spot
3. Put light_omni on map

Video: https://youtu.be/8Z0Opcc6zoA

**Comment by samzanemesis** [comment]
This should've been fixed a while ago in the build on steam, if it is fixed feel free to close the issue yourself
I am still working on getting proper support of lightcookies in omnilights

**Comment by kote2345** [comment]
Excellent, I checked, it's fixed
