### ISSUE TITLE
Character Animation Issue

### ISSUE THREAD

**Issue by ChristofferDL** [Facepunch/sbox-issues#788]
Describe the bug
Basically, when you look straight down. The player will just look left and right without any inputs being pressed.

To Reproduce
Look straight down.

Expected behaviour
Look where you are looking and not left and right.

Screenshots
https://user-images.githubusercontent.com/50109212/130757101-abe13883-cc35-45c1-ba08-82424cc7fd52.mp4

**Comment by MaxLebled** [comment]
This is a limitation of how the current look chains are implemented; I'm aware of the issue, it's something that's eventually going to get fixed
