### ISSUE TITLE
linear-gradient issues

### ISSUE THREAD

**Issue by rtm516** [Facepunch/sbox-issues#79]
**Describe the bug**
linear-gradient doesnt support `deg` or hard edges

**To Reproduce**

1. Create an element
2. Style with this
```css
background-image: linear-gradient(65deg, #d66f34 50%, #2d7233 50%);
```
3. Compare with a browser (https://jsfiddle.net/nu3Lfpar/4/)

**Expected behavior**
Browser
![image](https://user-images.githubusercontent.com/5401186/116797680-3e53af00-aae0-11eb-9670-ce8f6b082103.png)

Ingame:
![image](https://user-images.githubusercontent.com/5401186/116797685-50355200-aae0-11eb-8849-a728f387bc49.png)

**Comment by KingDavidW** [comment]
For anyone wanting to mess with degrees, they currently work with percentages ( 25% == 90deg )

Hard edges won't work though. In general linear-gradient does not follow stop positions

**Comment by R4K0** [comment]
degrees aren't supported, and while multiple steps are supported, you cannot specify the interval at which they appear, which would be a really useful feature.

Example: `linear-gradient(to left, #333, #333 50%, #eee 75%, #333 75%)`
