### ISSUE TITLE
Construct map errors

### ISSUE THREAD

**Issue by Alphaverse** [Facepunch/sbox-issues#790]
**Describe the bug**
When I start facepunch.construct I get a lot of errors in console. (The game was just installed and the map was loaded for the second time)

**To Reproduce**

1. Start "facepunch.construct"
2. Press F1 to open the console

**Expected behavior**

No error messages.

**Screenshots**

![Error1](https://user-images.githubusercontent.com/23063330/130781527-c99a77c7-1e5d-4f2d-b6bc-1acb8576306d.png)
![Error2](https://user-images.githubusercontent.com/23063330/130781536-952383ec-3cee-43e0-992f-497371f0250a.png)
![Error3](https://user-images.githubusercontent.com/23063330/130781543-7e2b4547-c676-4ce7-9b88-a6149e93ac31.png)

**Comment by miw1234** [comment]
did you try to reinstall your game?

**Comment by Alphaverse** [comment]
> did you try to reinstall your game?

The game was installed a few minutes before the errors were displayed and the map was just downloaded 2 minutes before. When I took the screenshot I loaded the map for the second time.
