### ISSUE TITLE
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event

### ISSUE THREAD

**Issue by Alphaverse** [Facepunch/sbox-issues#792]
**Describe the bug**
Whenever I start a game the error is displayed at least once anywhere in the console. Only the first occurrence has a stack trace though.

**To Reproduce**

1. Start a game
2. Press F1 to open the console

**Expected behavior**

No warning messages and not so many.

**Screenshots**

![QueueError1](https://user-images.githubusercontent.com/23063330/130810943-94980cff-7402-4df2-a60f-aea5bd064eda.png)
![QueueError2](https://user-images.githubusercontent.com/23063330/130810944-e68c763e-fca7-4c70-9f48-7b1dfd0c0c63.png)

**Comment by KayaDLX** [comment]
This is so specific and old, don't think I ever saw this happening in over a year, could be closed.
