### ISSUE TITLE
ClientData ConVars are not automatically cast

### ISSUE THREAD

**Issue by TheOpalium** [Facepunch/sbox-issues#795]
**Describe the bug**
ClientData ConVars are not automatically cast into their respective type, unlike other types of ConVars such as `ServerVar`. This throws error CS0029 (`Cannot implicitly convert type 'string' to '<wanted type>'`) when compiling the game mode.

**To Reproduce**
Here's a code sample:
```cs
[ConVar.ClientDataAttribute("spectator_only")]
public bool SpectatorOnly { get; set; } = false;
```

Results in:
```
<File>.cs(11,280): error CS0029: Cannot implicitly convert type 'string' to 'bool'
0009: 
0010: 		[ConVar.ClientData("spectator_only")]
0011: 		public bool SpectatorOnly { get; set; } = false;
0012: 

Build failed
```

**Expected behavior**
The ConVar should be automatically cast, like other ConVar types.

**Comment by garrynewman** [comment]
Oops - thanks - should be fixed now
