### ISSUE TITLE
Severe performance issues with transparency

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#797]
**Describe the bug**
Transparent textures have some severe problems, to the point that it's not even worth trying to make forests or anything with a lot of cards.

**To Reproduce**
1. Open construct, measure fps at spawn
2. Fly into the tree branches near the pond, measure fps
3. Notice that your fps is a fraction of what it should be (i go from ~130 to ~20)

**Expected behavior**
Decent FPS

**Screenshots**
![5kqknq](https://user-images.githubusercontent.com/1517911/130927271-b9c02b49-4932-417e-9864-13796f4e0f76.jpg)

**Additional context**
At least on NVIDIA GPUs

**Comment by PixelQubed** [comment]
Yeah, this needs to be sorted. It's a real big issue. It's not just trees, it's glass too. It's not as noticeable of a drop but it's about a drop of 35% performance with cascaded windows.

**Comment by rugg0064** [comment]
Also an issue on AMD GPU (RX 480 for me)

**Comment by PixelQubed** [comment]
> 
> 
> Also an issue on AMD GPU (RX 480 for me)

Well, I got a 1080Ti. I run the game in 4k. 250 fps average until I look at bushes and trees, or anything that uses transparency or alpha test. Then I get about 25 - 50 fps.

**Comment by DoctorGurke** [comment]
https://user-images.githubusercontent.com/12602100/131412464-a803c481-ef4c-4ed7-82ce-7438da391527.mp4

**Comment by DoctorGurke** [comment]
moral of the story: use alphatest

**Comment by DoctorGurke** [comment]
playing around with this I notice that transparency seems to be broken in general
the old collision issue still persists with transparency, not so with alpha test
depth seems to be busted as well, as seen on the video
they're the exact same mesh, copied, mirrored and turned into a model

**Comment by MrBrax** [comment]
> 
> 
> moral of the story: use alphatest

do all rust foliage use transparency instead of alphatest? looks like the latter, still tanks performance
