### ISSUE TITLE
Maxplayers isn't set/enforced

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#8]
Ran into this when I was testing to submit another issue. Don't know if this is intended or not. 
Last time this happened, the game crashed shortly after he spawned, although I don't have footage, and I don't know if the crash was related to him joining or not. 

Unsure if this also happens with people who aren't friends, although I'm inclined to assume not, since I haven't had any random people join in the past when running a listen server with a player limit of 1.

https://user-images.githubusercontent.com/10066958/115834625-6e65c880-a3e3-11eb-8383-66ad5215d74d.mp4

**Comment by Alphaverse** [comment]
In addition: 

First, it says unknown and then says it was set.
![2021-08-25 (8)](https://user-images.githubusercontent.com/23063330/130776091-c8e0fe6f-64fa-4e0f-93b9-ef22c0310be0.png)
