### ISSUE TITLE
A way to create physics from mesh

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/sbox-issues#80]
**What can't you do?**
Initialize complex physics shapes.

**How would you like it to work?**
```
PhysicsFromMesh(verts);
```
or
```
PhysicsInitConvex(points);
```

**What have you tried?**
Nothing there to try.

**Additional context**
It would be also nice if ```PhysicsFromModel``` would work with a generated model.

**Comment by Rohansi** [comment]
This has been possible for a while now:
```csharp
var mesh = new Mesh( ... );
mesh.CreateVertexBuffer<SimpleVertex>( VertexCount );
mesh.CreateIndexBuffer( IndexCount );

var model = new ModelBuilder()
	.AddMesh( mesh )
	.AddCollisionMesh( vertices, indices )
	.Create();

SetModel( model );
SetupPhysicsFromModel( PhysicsMotionType.Static );
```
