### ISSUE TITLE
Ability to change Host_Timescale Programatically

### ISSUE THREAD

**Issue by TehFlaminTaco** [Facepunch/sbox-issues#800]
**What can't you do?**
Slow-time programmatically

**How would you like it to work?**
The ability to change a value such as Time.Scale on the server; or the ability to run `host_timescale` changes.

**What have you tried?**
The Time Class, `ConsoleCommand.Run("host_timescale 0.1")`

**Additional context**
ConsoleCommand.Run used to work, but the blacklisting of things removed the ability, now there is no way to slow time.

**Comment by garrynewman** [comment]
Added Global.TimeScale
