### ISSUE TITLE
Color struct does not serialize correctly when using JsonSerializer

### ISSUE THREAD

**Issue by SleepyMode** [Facepunch/sbox-issues#809]
**Describe the bug**
The color struct does not serialize properly when using JsonSerializer. Any attempt to serialize a color will result in the following Json string: "{}".

**To Reproduce**
Use JsonSerializer.Serialize on any instance of the Color struct.

**Expected behavior**
The struct should be serialized correctly, probably similarly to Vector.
For example, for the colour with the values (1f, 1f, 1f, 1f), I expect it to Serialize similarly to Vector4 and result in "1, 1, 1, 1" or similar.

**Screenshots**
Serializing colours:
![](https://i.imgur.com/3w6xpS9.png)
![](https://i.imgur.com/XZJNtQP.png)

Serializing vectors:
![](https://i.imgur.com/kn1QP8n.png)
![](https://i.imgur.com/Q9fazhF.png)

**Additional context**
N/a.

**Comment by aylaylay** [comment]
I've added a json converter for color

**Comment by SleepyMode** [comment]
Correctly serializes following the update:
![](https://i.imgur.com/CRRJJZ4.png)
![](https://i.imgur.com/O9iv9sp.png)

**Comment by SleepyMode** [comment]
Re-tested with different values and now it actually fails to **deserialize** correctly:
![](https://i.imgur.com/J6Sccpp.png)
![](https://i.imgur.com/1E2nFuz.png)

**Comment by aylaylay** [comment]
Should be fixed now, it'll serialize and deserialize the same as Vector4

**Comment by SleepyMode** [comment]
There are some issues with the rounding that happens during serialization:
![](https://i.imgur.com/z269idl.png)

The serializer rounds the values up to 3 numbers after the decimal point however that seems to not be sufficient.
Not end-of-the-world, just inaccurate by up to 1/255 for each value.

**Comment by garrynewman** [comment]
Added some more places
