### ISSUE TITLE
Allow skipping the auto-respawn logic in Player.Simulate()

### ISSUE THREAD

**Issue by TheOpalium** [Facepunch/sbox-issues#810]
**What it is**
Currently, ``Sandbox.Player.Simulate()`` automatically respawns dead players after a few seconds. This means anything that inherits from Player (which I assume almost all custom player classes do) cannot have their own respawn logic, e.g. round-based games.
While it's possible to just avoid calling the base function, I feel like this is a bad practice since it does contain other important code (like active child simulation and probably more in the future). This would require developers to maintain the rest of the vital parts in their inheriting function and keep it up to date, which goes against the idea of inheritance and is kind of a pain.

**What it should be**
There should be some mechanism that skips the respawn code if the dev requires it. Perhaps an "AutoRespawn" flag that can be set to false.

**Comment by handsomematt** [comment]
Player is obsolete
