### ISSUE TITLE
Add Enable + Disable behavior to UI elements

### ISSUE THREAD

**Issue by AMastryukov** [Facepunch/sbox-issues#814]
**What can't you do?**
I can't easily enable/disable UI panels without setting the opacity and disabling interactions through css classes on UI elements. 

**How would you like it to work?**
I would like to be able to either:
- Call `UIElement.Enable()` and `UIElement.Disable()` to enable/disable visibility and interactions on those elements
- Set `UIElement.Enabled = true/false` to enable/disable visibility and interactions on those elements

Kind of like Canvases + Graphic Raycasters in Unity, except in one package.

**What have you tried?**
I've tried making custom classes inheriting from various UI Elements in Sandbox that set a class that contains the following:
```
.hidden
{
    display: none;
    pointer-events: none;
}
````
This is annoying because now every time I want to use `PanelCreator` I have to cast it to a special subclass like this: `(CustomUIElement) UIElement.Add.Label("Test")` to support this functionality.

**Comment by ogniK5377** [comment]
```cs
public static class MyPanelExtension
{
	public static void Hide(this Panel panel)
	{
		panel.Style.Display = DisplayMode.None;
		panel.Style.Dirty();
	}

	public static void Show( this Panel panel )
	{
		panel.Style.Display = DisplayMode.Flex;
		panel.Style.Dirty();
	}
}
```

Usage:
```cs
// Create our elements
Panel myPanelElement = Add.Panel();
Label myLabelElement = Add.Label();

// Hide them
myPanelElement.Hide();
myLabelElement.Hide();

// Show them
myPanelElement.Show();
myLabelElement.Show();
```

**Comment by Rohansi** [comment]
1. CSS classes can be shared between all elements so you do not need to define `.hidden` multiple times. Just have a common file loaded into your main panel.
2. Since the `.hidden` is now implicitly available for any panel, you can make some [extension methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) on `Panel` which add/remove/set the `.hidden` class.

**Comment by AMastryukov** [comment]
I wasn't aware of the existence of extension methods. It would be nice to have a built-in solution that could be done through a `Enabled` property without having to use extension methods to achieve this result.
