### ISSUE TITLE
[Material Editor] High memory usage on first image use

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#815]
**Describe the bug**

**To Reproduce**

1. Go to `Color`
2. Click on folder button
3. Pick a very high resolution texture
4. See high memory usage

**Expected behavior**

not that high usage

**Screenshots**

![image](https://user-images.githubusercontent.com/36124472/131221130-9d141879-fffb-47c1-8c6d-d875f028753d.png)

**Additional context**

i can't use 8192x8192 now, or it will crash.
i used jpg

**Comment by samzanemesis** [comment]
seems normal, texture goes to memory before being uploaded to GPU

**Comment by SupinePandora43** [comment]
> seems normal, texture goes to memory before being uploaded to GPU

Not that. I meant texture compilation. Asset browser shows 8K textures fine, but when i try to use them, i trigger compilation and OOM as result.

Is there a way to compile texture separately?
