### ISSUE TITLE
[Hammer] Dot grid resizes incorrectly when working on local plane

### ISSUE THREAD

**Issue by Jostiuk** [Facepunch/sbox-issues#817]
**Describe the bug**
When the dot grid is enabled in hammer, it will incorrectly resize if you zoom in on any 2d view while working on a local-based workplane. 
This issue is not persistent when the grid dots are disabled.

**To Reproduce**
1. Enable the grid dots in hammer's options.
2. Click the workplane eyedropper tool at the top of hammer.
2. Click on any face that is angled
3. Zoom in, in any 2d window.
4. The dots will scale weirdly and slide out of frame.

**Expected behavior**
The dots should follow what the vanilla grid does, and stay consistent and display the proper grid.

**Screenshots**
[https://i.imgur.com/H0Yguqt.gifv](url)

**Additional context**
The face I pick in the gif is angled 45 degrees from the global grid on the Z axis.

**Comment by aylaylay** [comment]
I've pushed a fix, it should be on steam in about 10 mins, see if it works in all the situations you try

**Comment by Jostiuk** [comment]
Whoops I was eating.

Everything seems to be working well now, thank you :)
