### ISSUE TITLE
Unable to upload .zip files to FP backend, causing 413 Request Entity Too Large

### ISSUE THREAD

**Issue by eagleonedevteam** [Facepunch/sbox-issues#818]
**Describe the bug**

Unable to upload any map in a .zip package to the FP backend that is above a certain size threshold

**To Reproduce**

1. Go to https://sbox.facepunch.com/*dev/*map_name
2. Click on 'Downloads'
3. Make sure download type is set to 'Zip'
4. Try to upload new file, or override previously existing one

**Expected behavior**

What should happen: Previously anything that was submitted would upload as long as it was under the 1gB threshold. Anything over this size limit would fail - but this was a known limit.

What now happens: Anything that is above 50mb will cause the browser to show a "413 Request Entity Too Large" with "cloudflare" showing. The file will not upload now.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/70182442/131234421-667751eb-8371-462a-aa36-11b65cda0609.png)

**Additional context**

This started occurring about 5 days ago.

This occurs both on existing maps in our development team, and anytime we tried making a new map to test this out

We have 14 maps uploaded and our Dev Team has quite a few game modes online, perhaps we as a dev group reached a limit?

Uploaded successfully a much smaller zip file of 50mb and the server accepted this. The next file size was 200mB and it gives the error.

**Comment by garrynewman** [comment]
I need to do a better uploading process, and also allow uploading from in game. 

I made a few tweaks - let me know if you can upload anything larger now.

**Comment by eagleonedevteam** [comment]
Just uploaded files up to 700mb no problem! I'll take a look to see how it handles the larger files when I get back home and see if I'm able to go past 1gb. Thank you!

**Comment by garrynewman** [comment]
Alright I'll close this for now, but I'm aware we need better upload methods.
