### ISSUE TITLE
StyleSheet.Load(...) Requires Stylesheet Name = Class Name

### ISSUE THREAD

**Issue by AMastryukov** [Facepunch/sbox-issues#819]
**Describe the bug**
`StyleSheet.Load("StylesheetName.scss")` requires that `"StylesheetName"` be the name of the class in which it is called.

**To Reproduce**
1. Open any class that uses `StyleSheet.Load(...)` method
2. Rename the stylesheet to something that isn't the class name
3. Replace the string in `StyleSheet.Load(...)` with the new stylesheet name
4. Stylesheet won't work

**Expected behavior**
`StyleSheet.Load(...)` should load whatever stylesheet you specify, not just the one named the same string as the class.

**Additional context**
Creating a robust stylesheet system that loads multiple stylesheets, or stylesheets that are named anything other than the class name doesn't work. In addition, this seems to also cause the problem with loading stylesheets in a child class that contain css classes. I don't want to shove everything in one stylesheet file.

**Comment by MrBrax** [comment]
`@import` in scss?

**Comment by AMastryukov** [comment]
> `@import` in scss?
Not sure how this solves the problem.

**Comment by MrBrax** [comment]
i kinda get what you mean, but why not use `@import` in the master stylesheet?

**Comment by AMastryukov** [comment]
> i kinda get what you mean, but why not use `@import` in the master stylesheet?

Because this is workaround, not a solution.

**Comment by garrynewman** [comment]
Is this definitely the case?

**Comment by AMastryukov** [comment]
> Is this definitely the case?

I just tried it, and it seems to happen. 

What I did was open a random UI file, changed the name of the `StyleSheet.Load(...)` string, and changed the name of the desired file to match the new string and it broke the UI.
