### ISSUE TITLE
Particles SetEntityBone, SetEntity, SetEntityAttachment attach incorrectly when the player is out of range

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#82]
**Describe the bug**
If you try to call `SetEntityBone`, `SetEntity`, `SetEntityAttachment` (with entity follow) the flame does not attach to the proper position if the player is not in range. WorldPos for the target seems to report correctly however everything else seems to only report its last known position.

Marking the player as `Transmit = TransmitType.Always;` doesn't seem to fix this issue, however the current work around to fix this is by adding all players to your current PVS.
```cs
foreach (Player player in All)
{
    Pvs.Add(player);
}
```

**To Reproduce**
1) Create a looping particle and attach it to an entity(a player) and use `SetEntityBone`, or `SetEntity` or `SetEntityAttachment`.
2) With another client, kill that player and wait for them to respawn out of your PVS
3) Attempt to recreate the particle with the same parameters, the particle should play at it's current location instead of where the entity is

**Expected behavior**
`SetEntityBone`, `SetEntity`, `SetEntityAttachment` should reflect their actual positions much like how `WorldPos` does when a client leaves your PVS.

**Comment by garrynewman** [comment]
Are you creating the entity clientside or serverside?

**Comment by ogniK5377** [comment]
On the server and client, however if I just isolate it to the server it still happens

**Comment by garrynewman** [comment]
So it sounds like if we're attaching to an entity we need the particle system to follow that entity's dormancy. If the entity isn't known just hide the particle system completely.. that sound right?

**Comment by ogniK5377** [comment]
That sounds correct yeah
