### ISSUE TITLE
Implement an equivalent to `game.CleanUpMap()` from Garry's Mod

### ISSUE THREAD

**Issue by Fires1** [Facepunch/sbox-issues#820]
**What can't you do?**
I can't easily reset the map and all current non-pawn entities to their initial state when PostLevelLoaded is called.

**How would you like it to work?**
Ideally an addition function on top of the `Game` that allows a single function call that would reset all existing entity data to it's initial saved value when the level was initially loaded. A linq predicate could also be included as a parameter to select what specific entities you want to clean up

**What have you tried?**
I've tried storing all entity data in a collection inside my `Game` copy and apply those saved properties onto my map-saved entities, then deleting all non-pawn non-map entities as well.

The difficulty comes in saving and holding onto each specific property of an entity, as many entities can have many different properties. It seems inefficient and slow to serialize them all to a format like json, then reload them off that.

Additionally tried to create addon "OnCleanup" methods, but involved too much overhead in the event of certain map elements that needed specific implementation.

**Comment by robotboy655** [comment]
This was done, currently exists as `EntityManager.CleanUpMap`. Example usage can be seen in the Sandbox gamemode.

The default filter looks like this:
```
static public bool DefaultCleanupFilter( string className, Entity ent )
{
	Log.Warning( className );

	// Basic Source engine stuff
	if ( className == "player" || className == "worldent" || className == "worldspawn" || className == "soundent" || className == "player_manager" )
	{
		return false;
	}

	// When creating entities we only have classNames to work with..
	if ( ent == null || !ent.IsValid ) return true;

	// Gamemode related stuff, game entity, HUD, etc
	if ( ent is GameBase || ent.Parent is GameBase )
	{
		return false;
	}

	// Player related stuff, clothing and weapons
	foreach ( var cl in Client.All )
	{
		if ( ent == cl.Pawn || cl.Pawn.Inventory.Contains( ent ) || ent.Parent == cl.Pawn ) return false;
	}

	return true;
}
```

This method also fires 2 events: `[Event.Entity.PreCleanup]` and `[Event.Entity.PostCleanup]`
