### ISSUE TITLE
Camera.LookAt, create a Rotation to face a given position

### ISSUE THREAD

**Issue by suiramdev** [Facepunch/sbox-issues#824]
### **What can't you do?**
By trying to reproduce a similar camera as nowadays MMORPGs, i struggled much for making my camera targeting my player.
I would like to make it face, look at my player but no actual functions let me do it easily without having to mess up with maths.

### **How would you like it to work?**
Like it exists in many game engines, such as Unity as you know a lot Facepunch :), we have an prebuilt function called "LookAt" on Transform objects. This make an object face an another one or a Vector3 position.
To give users more liberty, it can maybe also be a function inside Rotation that returns the Rotation needed to face a position from a given source position.

### **What have you tried?**
I messed with `Vector3.Dot()`, `Vector3.Cross()` following to a forum post but because i struggle in math, i couldn't find out how to make it. 
Forum post about it to help you out too :<https://gamedev.stackexchange.com/questions/15070/orienting-a-model-to-face-a-target>

**Comment by garrynewman** [comment]
`Rotation.LookAt`

**Comment by suiramdev** [comment]
I thought that this function was not used for that until I finally understood its use.
Sorry about the ticket, somehow useless.
