### ISSUE TITLE
Light cookies not baking to lightmap

### ISSUE THREAD

**Issue by Glitchvid** [Facepunch/sbox-issues#834]
**Describe the bug**
Light cookies are ignored when baking lightmaps, regression from HL:A branch.

**To Reproduce**

1. Make a spotlight
2. Set a cookie texture
3. Bake lighting
4. No light cookie on result!

**Screenshots**
*Half-Life Alyx:*
![Hol632](https://user-images.githubusercontent.com/241420/131583233-24684113-3148-4710-8e31-0088d3e990b0.png)
*s&box:*
![Jl5129](https://user-images.githubusercontent.com/241420/131583281-bddeff29-ab21-4798-90a0-b6e5f74d0434.png)
*in editor:*
![Occ489](https://user-images.githubusercontent.com/241420/131583378-942852f9-8493-4b56-ae50-8ee394a13680.png)

**Additional context**
Compile cmd:
```H:\Games\steam\steamapps\common\sbox\bin\win64\resourcecompiler.exe -fshallow -maxtextureres 256 -dxlevel 110 -quiet -html -unbufferedio -noassert -i "h:/games/steam/steamapps/common/sbox/addons/glitchvid/maps/zoo_cookies.vmap"  -world -bakelighting -lightmapMaxResolution 1024 -vrad3 -lightmapDoWeld -lightmapVRadQuality 1 -lightmapLocalCompile -lightmapCompressionDisabled 0 -phys -vis -nav -sareverb -sapaths -breakpad  -nompi  -nop4 -outroot "C:\Users\GLITCH~1\AppData\Local\Temp\valve\hammermapbuild\game"```

**Comment by samzanemesis** [comment]
Our lightcookie system is a bit different from Alyx's, I have implemented baking support to it and it should be on Steam in a few minutes, you can close the issue if it all works fine
![image](https://user-images.githubusercontent.com/6563447/131842524-887353b3-23a8-4ef4-a0b8-81b388684f0e.png)

**Comment by Glitchvid** [comment]
Thanks for looking at this!

Seems it uses the wrong cookie texture sometimes.
![9yq910](https://user-images.githubusercontent.com/241420/131953060-c94da6be-00b8-459f-ad6e-1995bd74fb52.png)
![gOV128](https://user-images.githubusercontent.com/241420/131953072-3bffa1e0-63ea-4c36-9c96-c6f536887e86.png)
It should be using a circular cookie, but is instead using the box one.  This sometimes happens inside the editor baked preview too.

Occasionally going to baked lighting preview crashes the editor, I can provide the mdmp if needed (though I assume FP slurps those up and you already have it).

Here's the testmap and my custom cookies.
[hgissue_834.zip](https://github.com/Facepunch/sbox-issues/files/7103489/hgissue_834.zip)
