### ISSUE TITLE
The Help string of PropertyAttribute should be 'set' and not 'protected set'

### ISSUE THREAD

**Issue by randomperson189** [Facepunch/sbox-issues#836]
**What it is**
Currently the the Help string of PropertyAttribute is `{get, protected set}` and that means I can't set it for an entity in hammer. e.g. `[Property( Title = "Test Property", Help = "Help text for property" )]`

**What it should be**
It should be  `{get, set}` just like all the other PropertyAttribute strings like `Title`, `Group`, `FGDType` and `Hammer`.

**Comment by garrynewman** [comment]
This is on purpose. You set the contents of the help by adding a comment to the property. This way you don't have to add a comment for intellisense/code and a comment for Hammer, it uses both. By setting it to protected set we're forcing people to document their code.

**Comment by randomperson189** [comment]
oh, in that case, https://wiki.facepunch.com/sbox/Linking_Entities_to_Hammer#hammerproperties has a typo. It should have </summary> in the example.
