### ISSUE TITLE
"Unity" style components

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#84]
**What can't you do?**

Add "components" to entities to avoid inheritance hell.

**How would you like it to work?**

I'm using unity components as a jumping off point that people are familiar with. 

As it is currently designed, we either have to inherit extra things we don't need or define a new class for each combination of features. People often bring up ECS but it is is often overkill + very complex when all you need is composition.

The benefits of integrating it into the base game / engine is hammer could become a pseudo unity editor. We already have support for `[HammerProp]` so with a little tweaking we could have our components show up in the editor and be able to be added and edited. This would streamline the process of editing props and prefabs as well as allowing more configuration (add a "Balloon" component to any prefab)

~~Components should probably each be their own entity.~~

Adding components myself. It works, but each person will end up rolling a slightly different and incompatible system & there isn't hammer support to configure your different "prefabs".

**Additional context**

Its not strictly about components but about standard tools for composition. I think inheritance hell is something that should be considered and avoided early on. Whether it ends up looking like unity components or not is inconsequential. It is also very likely this is planned or at least been considered but imo best to make an issue regardless.

**Task List**

- [x] Components.Add
- [x] Components.Remove
- [x] Enable/Disable component
- [x] Component networking
- [x] Components.Get<T>
- [x] Components.TryGet<T>
- [x] Components.GetOrCreate<T>
- [x] Components.GetAll<T>
- [x] Glow should be a component

**Comment by garrynewman** [comment]
I can see the benefits of components. I don't think having them as separate entities under the hood would be a good thing though.

I could imagine components replacing things like PlayerController, Camera etc. It needs more consideration on how people would actually use them in practice, but I do like the idea, even if only as a way to add extra custom metadata to an entity at runtime.

**Comment by mzegar** [comment]
Just wanted to chime in after working with s&box a decent amount, a component-based system would be preferable compared to the "forced" inheritance we currently have. I feel like it's extremely difficult to get people not to abuse inheritance and leads to inheritance hell once projects get pretty big.

**Comment by garrynewman** [comment]
I'm gonna have a play with this
