### ISSUE TITLE
Global.TickRate, when set, isn't applied until the gamemode is restarted but it is also remembered across different games

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-issues#840]
**To Reproduce**

1. Set Global.TickRate in a game constructor

**Expected behavior**

The tick rate should be what you set it to, but it isn't until you restart the gamemode or start another game

**Additional context**

The tick rate is also remembered so if one game sets Global.TickRate to something, and then you start another game, it'll be the tick rate the other game set

**Test code for checking the real tick rate**

```csharp
[Event.Tick.Server]
public static void MyTickTest()
{
    Log.Info( 1f / Time.Delta );
}
```

**Comment by garrynewman** [comment]
This should be fixed now 🙈
