### ISSUE TITLE
Better Generic_Path Tools

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#842]
**What can't you do?**

1. ~~Place a point between two points.~~ [Solved]
2. ~~Add Points to either end of a placed path.~~ [Solved]
3. [Piecewise Bezier Specific] Be able to rotate/scale Tangents around their origin.

**How would you like it to work?**

*[Solved]*
1. Either a right click menu, hotkey, or something along those lines that just places a new point in the middle of two selected PathNodes, ideally at the cental point.
![sbox-dev_mXdN3xbZJP](https://user-images.githubusercontent.com/36082767/131759948-b69eb5b9-9555-4df4-a42c-9eec5bdaf546.png)
![sbox-dev_8lBp0zyjHI](https://user-images.githubusercontent.com/36082767/131759954-d29bef7a-7a00-4b4d-a433-89f39f512884.png)

*[Solved]*
2. Right-Click/Hotkey/UI-Button to put you in point placing mode again at one of the ends, or a way to connect up two different beziers by their ends.
![sbox-dev_zci0gZJxBU](https://user-images.githubusercontent.com/36082767/131760113-89524c0e-e54b-40ad-9aea-82f61b2eb61d.png)
![sbox-dev_d4n7yc72as](https://user-images.githubusercontent.com/36082767/131760121-15373166-be3a-4ea4-a698-5b309df7e19c.png)

3. Selecting the tangent point and going into rotate mode causes it to rotate about the origin, similarly, scale the tangent vector using the scaling tool. Rotating/Scaling the PathNode should ideally effect both tangent points.
E.g. Turning this:
![sbox-dev_2882ScMd9u](https://user-images.githubusercontent.com/36082767/131763082-38474c32-1fca-4877-90b2-8d39c1b4fd2d.png)
![sbox-dev_8qkw8DeDUl](https://user-images.githubusercontent.com/36082767/131763114-e4c793c2-5c51-4e34-b9a7-47c5bc8748a7.png)
Would ideally have an effect, scaling:
![sbox-dev_Vu75G0q8In](https://user-images.githubusercontent.com/36082767/131763148-7ab9f742-5b69-4479-9495-113f54ebeb36.png)
Also tangent specific-rotation:
![sbox-dev_wB5GmofnPI](https://user-images.githubusercontent.com/36082767/131763183-4f24ee2d-877a-4d03-9efb-e75c1a46ce1c.png)
![sbox-dev_T01O9zcOVb](https://user-images.githubusercontent.com/36082767/131763186-1dc81dcc-5964-4c02-b4ef-e6bd01aedead.png)

**What have you tried?**
Right clicking/looking through menus/hotkeys/etc.

**Additional context**
I put this all in one ticket, but I will break it up if asked, they were just all Path related features so I didn't want to do them all individually, in case path improvements were not a priority.

**Comment by robotboy655** [comment]
1. Shift drag any node with the translation tool
2. Shift drag any node with the translation tool

**Comment by MD485** [comment]
Oh wow, sorry about that, slipped my mind entirely.
While I would be happy to close with just this, I still think the third point would be a neat feature if possible.

**Comment by robotboy655** [comment]
Ok the rotating/scaling should now work as expected, and the issue with loss of functionality should no longer happen.

If you cannot find any issues with the changes please close this issue.

**Comment by MD485** [comment]
Yep! It seems to work relatively like I'd expect, I did find some bugs though.

https://user-images.githubusercontent.com/36082767/132052496-41e57094-46a3-4f54-8a1e-3cb7a6d22873.mp4

By default you can't rotate the points, but then it seems they enter into a rotatable "state" after one is moved manually.
Which would be fine but it doesn't seem toggleable, so after rotating one point you can't rotate the other without rotating both.
Scaling seems off slightly too, when a point is selected you can scale uniformally but not in an axis locked way unless you select another point. (which also seems to only be possible after the points have been moved manually)

There was also a change in functionality:

https://user-images.githubusercontent.com/36082767/132052880-54a9d4ac-0493-42e1-9ce7-4ee64af56017.mp4

Previously with two points selected rotation would work like the two cubes, but now you individually rotate each point.
I didn't use this feature too much but I imagine it's more useful than the alternative.

Thanks for your work on this!

**Comment by robotboy655** [comment]
Most of these should be addressed with the next update, except for per axis scale. I don't see that something that is useful in context of path nodes.

**Comment by MD485** [comment]
Just gave it a test, works great, Thanks!
