### ISSUE TITLE
Elevate WorldPanel.SceneObject property access to protected

### ISSUE THREAD

**Issue by piqey** [Facepunch/sbox-issues#850]
**What can't you do?**
Access the PanelSceneObject instance from within WorldPanel subclasses.

**How would you like it to work?**
I think making WorldPanel.SceneObject protected instead of private would be sufficient.

**What have you tried?**
There is not much I can try aside from totally rewriting or copying all the WorldPanel which would be incredibly messy and in my opinion, not worth it.

**Additional context**
Was looking to disable the post processing on a specific WorldPanel as well as other possible changes I might make to the panel's rendering somewhere along the line.

**Comment by garrynewman** [comment]
Done
