### ISSUE TITLE
Sound.FromEntity and Entity.PlaySound crash in async methods with a deleted entity.

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#851]
**Describe the bug**
When using `Sound.FromEntity` or `Entity.PlaySound` to play a sound from a deleted entity after a delay in an async method, the game crashes instead of throwing a `NullReferenceException`.

**To Reproduce**
Make an entity with the following method, spawn the entity, call the method, remove the entity before the delay and watch the game crash.

```
public async void CrashTest()
{
	await Task.DelaySeconds( 0.5f );

	Sound.FromEntity( "anySound", this );
}
```

**Expected behavior**
Expected behaviour is a `NullReferenceException`, not a game crash.

**Comment by handsomematt** [comment]
You could probably do this for the time being:

```csharp
public async void CrashTest()
{
	await Task.DelaySeconds( 0.5f );

	if ( this.IsValid() )
		Sound.FromEntity( "anySound", this );
}
```

**Comment by Gmod4phun** [comment]
Yep that's what I'm currently using as a workaround.
