### ISSUE TITLE
VR Debug Tools

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#852]
There are some tools for debugging VR gamemodes that I think could be useful. Some things that come to mind are a toggle to show raw, clientside controller positions to compare to the controllers in-game? Something similar to what's shown 41 seconds into this, but without all the text and such. https://files.catbox.moe/leahh5.mp4
Another one that comes to mind is a way to see what the VR monitor/mirror looks like in-game by utilizing an overlay, potentially with a way to mount it to a controller or the HMD. This could be useful if you have a HUD on the mirror, and want to make sure it's working without messing with SteamVR's desktop viewer. In fact, this could be even more useful than SteamVR's desktop viewer if the overlay had the ability to only show the HUD that's being drawn on the game's mirror.

Maybe all of this could be integrated into a VR-specific console at some point?

**Comment by xezno** [comment]
So I've started some stuff on this - I've got it as an editor tool though:
![image](https://github.com/sboxgame/issues/assets/12881812/af696d7f-b128-4535-a876-3385e0d2c565)
For whatever reason the Oculus stuff doesn't report battery levels for controllers or HMD, at least on my end - but those work in fpsVR so maybe I'm handling that wrong.

Is this what you had in mind or were you thinking of something in the game itself?
What sort of statistics are most useful here?
