### ISSUE TITLE
Weird physgun bug

### ISSUE THREAD

**Issue by TNTudorE** [Facepunch/sbox-issues#856]
**Describe the bug**
The thruster will move without mouse input

**Video**
https://youtu.be/GA7HkJBEy28

**To Reproduce**

1 Spawn a soda can (the blue one)
2 Put a thruster on the can
3 Grab the back (where the flame is) of the thruster with the phys-gun
4 The thruster will start moving without moving your mouse

**Comment by walllable** [comment]
You should probably put this issue here instead.
https://github.com/Facepunch/sandbox/issues
sbox-issues are for bug reports/feature requests for the game itself. The one I linked above is for the sandbox gamemode specifically
