### ISSUE TITLE
Expose "size" as a get property for NetRead

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#86]
**What can't you do?**
Access the "size" property of NetRead

**How would you like it to work?**
`public int Size{ get; }`

**What have you tried?**
Nothing

**Additional context**
Currently, all we have is LengthAssert. However, this isn't particularly helpful in all circumstances. This is just verifying the size of something before copying. It would be nice to know the size of the entire message as we can network variable-length data types manually easier(eg an array without sending the array count)

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by ogniK5377** [comment]
Perfect, works great. Thanks!
