### ISSUE TITLE
[Hammer] Remove the scaling constraint for gizmo in 2D viewports. 

### ISSUE THREAD

**Issue by pBinarySoul** [Facepunch/sbox-issues#860]
**What can't you do?**
I can't see the gizmo at maximum zoom, because it is huge.

**How would you like it to work?**
The gizmo must scale down without a limit if I increase the zoom.

**Screenshots**
How it is now:
![How it is now](https://user-images.githubusercontent.com/36414434/132090467-ee4453c8-731d-47aa-8f26-36ad1b6928cb.png)

How it should be:
![How it should be](https://user-images.githubusercontent.com/36414434/132090473-342f3207-536a-4ef8-a971-eb9baab0f0ec.png)

**Comment by robotboy655** [comment]
This should be solved with the next game update. The lengths should now match the desired length value set by `hammer_gizmo_axis_length`.
