### ISSUE TITLE
Transition with style editing creates two part

### ISSUE THREAD

**Issue by DreamplaySE** [Facepunch/sbox-issues#861]
**Describe the bug**
When I set top/left to move a panel the transition seems to split up into two transitions making it seem laggy.

**To Reproduce**

1. Download [this gamemode repository](https://github.com/DreamplaySE/sbox-demo)
2. Run it
3. Click on the "Close" text once you get into the gamemode
4. See the laggy transition

**Expected behavior**
For the panel to move in 1 continuous transition/animation.

**Screenshots**
https://youtu.be/uV0AAHjdqPs

**Comment by cr4yz** [comment]
Looks to be the same as https://github.com/Facepunch/sbox-issues/issues/508

Closing for now, please reopen and let me know if you still have trouble
