### ISSUE TITLE
Text chat improperly parses input.

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#862]
**Describe the bug**

When a phrase is written into the player chat beginning with a double quote (") and ending with a semi-colon (;), input is improperly parsed.

**To Reproduce**

1. Write `"whatever whatever;` in the player chat.
This should print `""whatever`, truncating the second word and adding another double quote to the beginning of the input.
This also works with no words, but any words after the first space will be removed.

**Expected behavior**

Regardless of input the console should return what it was.

**Screenshots**

![sbox_tt48wAi3WC](https://user-images.githubusercontent.com/36082767/132093674-2a226b42-ea1b-4588-b264-ff7fd6306c51.png)
![sbox_nDN0JUmIpJ](https://user-images.githubusercontent.com/36082767/132093676-9d575e35-ec9d-4a91-99a0-02922290c555.png)

![sbox_E0MX1etFwR](https://user-images.githubusercontent.com/36082767/132093679-68f53c63-b637-44f1-8935-db1e785d6ab7.png)
![sbox_TMhcxJyFgR](https://user-images.githubusercontent.com/36082767/132093680-26fd6093-1c52-429f-830c-883b1d6003b8.png)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
