### ISSUE TITLE
Viewmodel PlaySounds in ModelDoc

### ISSUE THREAD

**Issue by OMGOMGplays** [Facepunch/sbox-issues#863]
it'd make it way easier to make sounds play if they were attached to the viewmodel of e.g. weapons instead of having to e.g. make one singular sound file with all the sounds needing to be placed at perfect timing using an external program for an e.g. reload animation.

**Comment by GamerXCZ** [comment]
Yes viewmodel sounds are played from world from static position (maybe 0,0,0)

I believe this is only a temporary bug when modeldoc supports adding animation sounds-

**Comment by realpack** [comment]
#650
