### ISSUE TITLE
The "max player" slider does not do anything, the game always defaults to 32 slots.

### ISSUE THREAD

**Issue by stopmotio** [Facepunch/sbox-issues#864]
**Describe the bug**
Due to a coding error, the maxplayer slider does not work

**To Reproduce**

1. Create a game with any gamemode(I did sandbox mode)
2. Set maxplayers to 1
3. Get someone else to join
4. They join regardless of player count

**Expected behavior**

In this event, the other player should not be able to join as the only player slot is being used by the host.

**Screenshots**

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

Slider changes `sv_maxplayers` when I checked a week or so ago. This no longer exists and throws an error in the console in yellow.

Thanks for allowing me to get access so soon! Never expected it and I really appreciate being able to watch this project grow and develop.

**Comment by DoctorGurke** [comment]
duplicate #8

**Comment by stopmotio** [comment]
Oh, I couldn't find that via search. My bad!
