### ISSUE TITLE
Cannot stop a sound if there are several sounds in the file

### ISSUE THREAD

**Issue by Maxime66410** [Facepunch/sbox-issues#865]
**Describe the bug**
When we want to stop a sound, which was started via a sound file that contains several sounds inside, the stop function does not work.

I noticed that when you ask to stop a sound via the Stop function, it stops the assigned sound, so if you have more than one sound in a file, it doesn't stop the sound that has been played.

**To Reproduce**

1. Go to 'Inspector'
2. Click on 'Type -> Sounds'
3. Add some sounds (2 or 3 for example)
4. In your code launch function PlaySound("YourNameFile").Stop(); or Sound.FromScreen("YourNameFile").Stop();

**Expected behavior**
When the Stop function is started it stops a predefined sound which is recorded in the sound file.
But if there are several then he stops the first in the array.
Whereas normally, following logic if there is only one sound, it must go through all the sounds and stop them one by one.

Example from my side I want to launch a file named "ambiantmusic.ambiant".

if launch the function for stop sound.

it tries to stop precisely "ambiantmusic.ambiant" , Except that currently the sounds that play these
 1: sound\music\km_chapelofunrest.vsnd (80001159 :: 0000045f)  [8.7s]
  0: sound\music\km_hell.vsnd (800010a1 :: 0000044f)  [56.4s]

**Screenshots**

![](https://media.discordapp.net/attachments/833983449857654795/884033864203374652/unknown.png)

![](https://media.discordapp.net/attachments/833983449857654795/884034423056654366/unknown.png)

**Additional context**

So if we use the Stop function in a sound file with several sounds, the stopped sound will be the first in the array.

**Comment by robotboy655** [comment]
I cannot reproduce the sounds not stopping. If anything I see a bug where doing this: `PlaySound("counting120").Stop()` stops sounds on other entities than the one I called PlaySound on. 

To be clear, `PlaySound("counting120").Stop()` is meant to stop the sound it creates, meaning nothing should happen when you use it.

**Comment by robotboy655** [comment]
The only way I can reproduce that if you do not stop the sound before starting to play a new one, is this what you mean?

So you are doing this:
```
Sound Sound1;
Sound Sound2;
Sound Sound3;
public override void TakeDamage( DamageInfo info )
{
	base.TakeDamage( info );

	Sound1 = PlaySound("multi_sound_test");
	Sound2 = PlaySound("multi_sound_test");
	Sound3 = PlaySound("multi_sound_test");
}
```

But you SHOULD be doing this:
```
Sound Sound1;
Sound Sound2;
Sound Sound3;
public override void TakeDamage( DamageInfo info )
{
	base.TakeDamage( info );

	Sound1.Stop();
	Sound2.Stop();
	Sound3.Stop();
	Sound1 = PlaySound("multi_sound_test");
	Sound2 = PlaySound("multi_sound_test");
	Sound3 = PlaySound("multi_sound_test");
}
```

**Comment by Maxime66410** [comment]
Hello again, sorry to answer so late.
We are actually launching a sound with a file to select several are recorded in this file.
You cannot stop the file from playing, since this file has random music which is written in this file.
So is a sound to start at random, to stop it I had to do a check of a list of music which is in this file.
