### ISSUE TITLE
Player limit doesn't work

### ISSUE THREAD

**Issue by flokiKun** [Facepunch/sbox-issues#867]
**Desc**
Player limit slider doesn't affect player limit var.

**Reproduce**

1. Go to Games.
2. Open Sandbox.
3. Set player limit to 1.
4. Start game.

**Expected behavior**
Expect 1 player limit, but really 32.

**Screenshots**
![image](https://user-images.githubusercontent.com/32014090/132138190-0c00bb2d-cf68-4a9e-92e1-4416cddf0392.png)
![image](https://user-images.githubusercontent.com/32014090/132138197-a6d3d786-32e2-4e68-a577-7bc45339916c.png)

**Comment by DoctorGurke** [comment]
duplicate #8
