### ISSUE TITLE
Add Particles.SetComponent to set an individual component on a control point

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#87]
**What can't you do?**
With particle system control points, they're typically set up as vectors. However certain properties let you access only a singular component(See SetFloat as an initializer).
![image](https://user-images.githubusercontent.com/25727384/116861458-77a62f00-ac46-11eb-846f-11e40e79a6d0.png)

It would be nice to set a single component instead of creating a vector3 just for that.

**How would you like it to work?**
```cs
Particles particle = Particles.Create("particles/foo.vpcf", WorldPos);
particle.SetComponent(0, 1, 100.0f); // Control point 0, Component Y, Value 100.0f 

// Would replace the need to do
particle.SetPos(0, new Vector3(0.0f, 100.0f, 0.0f));
```

**What have you tried?**
```cs
particle.SetPos(0, new Vector3(0.0f, 100.0f, 0.0f));
```

**Additional context**
Another great addition would be the ability to pass `Angles` as well instead of needing to convert the angle to a position as control points can have a rotation as well
![image](https://user-images.githubusercontent.com/25727384/116861337-49c0ea80-ac46-11eb-92ca-639817613478.png)

**Comment by robotboy655** [comment]
go away bot

**Comment by robotboy655** [comment]
Added `Particles.SetPositionComponent` and `Particles.SetOrientation`, the latter has overloads for both `Rotation` and `Angles`.
