### ISSUE TITLE
WorldPanel faces backwards

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#878]
**Describe the bug**

A WorldPanel will face backwards rather then forwards. When using a WorldPanel with an Entity I have to rotate it to the opposite direction.

**To Reproduce**

```csharp
class HoleWorldPanel : WorldPanel
{
	public HoleWorldPanel()
	{
		PanelBounds = new Rect( -360, -220, 720, 440 );

		StyleSheet.Load( "HoleWorldPanel.scss" );

		Add.Label( "Hole 1", "hole" );
		Add.Label( "Coooool", "name" );
		Add.Label( "Par 3", "par" );
	}

	public override void Tick()
	{
		DebugOverlay.Line( Transform.Position, Transform.Position + Transform.Rotation.Forward * 50.0f, 0, false );
	}
}
```

The line will face forward, but it will be the opposite of the panel.

**Screenshots**

![image](https://user-images.githubusercontent.com/1388267/132230721-782b3e42-cb08-4a83-bebf-356da2d66552.png)

Here my arrow is pointing behind the sign which is my Forward rotation that I have rotated.

**Comment by garrynewman** [comment]
Thanks - fixed
