### ISSUE TITLE
info_particle_system do not scale properly in the 3D Skybox

### ISSUE THREAD

**Issue by justynboi** [Facepunch/sbox-issues#880]
**Describe the bug**

Particles do scale properly in Hammer, but not in-game.

**Screenshots**
3D Skybox Scale set to 1

Hammer
![sbox-dev_6EbNC3TFHP](https://user-images.githubusercontent.com/17112771/132255384-779153a2-b4e2-4cba-bcfc-e1cc09723874.png)

In-Game
![sbox_0065](https://user-images.githubusercontent.com/17112771/132255464-7adeaac5-aa64-4c47-af8e-d30c541143bd.png)

3D Skybox Scale set to 16

Hammer
![sbox-dev_Gnks3GbvMk](https://user-images.githubusercontent.com/17112771/132255434-5472deee-0317-476d-92cf-6c4b16683df1.png)

In-Game
![sbox_0066](https://user-images.githubusercontent.com/17112771/132255469-d290107b-3d3d-41fb-908f-012e6b74b5b0.png)

**Additional context**

This was broken around when info_particle_system entity got rewrote

**Comment by justynboi** [comment]
Bumping this

**Comment by justynboi** [comment]
Bumping this again because it's still an issue.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by justynboi** [comment]
It's fixed! Thanks!
