### ISSUE TITLE
Weird graphical problem

### ISSUE THREAD

**Issue by mungasi2000** [Facepunch/sbox-issues#881]
The command console keeps spitting this error out:
CRenderContextDx11_SoftwareCommandLists:: Cannot resolve from a non-MSAA buffer to an MSAA buffer!
and I see an after image of myself whenever i set off an explosion

**To Reproduce**

1. Go into default Sandbox mode, Construct is the map i used
2. Literally just alt-tab, experiment with dedicated fullscreen alt tabbing and windowed alt tabbing
3. Your console should be flooding with errors
5. "CRenderContextDx11_SoftwareCommandLists:: Cannot resolve from a non-MSAA buffer to an MSAA buffer!"
6. also spawn an explosive barrel and shoot it till it explodes

*Expected Behaviour*

you will see the error in the console and the afterimage in the smoke, i think this also happened when i changed the antialiasing type

**Additional context**
I use Windows 10 Pro, my CPU is an AMD Ryzen 7 5800X, My GPU is an AMD Radeon RX 6800XT, I have the latest driver update for both.

https://user-images.githubusercontent.com/62508056/132265787-c919b662-74ca-48fb-91b4-bf6ad69c0e07.mp4

**Comment by KayaDLX** [comment]
Was fixed a long time ago, could be closed
