### ISSUE TITLE
sbox crashes when trying to import a map from source 1

### ISSUE THREAD

**Issue by FarikLoL** [Facepunch/sbox-issues#883]
when trying to import vmf map from source 1, sbox crashes

**To Reproduce**

1. need to open a hammer
2. click file>open
3. select map .vmf
4. when the conversion process comes to an end sbox is closed

the map should have been imported

[crash dump](https://github.com/Facepunch/sbox-issues/files/7121111/sbox-dev_2021_0907_142802_0_accessviolation.zip)
[the map I tried to import](https://github.com/Facepunch/sbox-issues/files/7121118/rp_bangclaw.zip)

**Comment by GamerXCZ** [comment]
Rather, there is a problem with your computer.
Here is your map.
[rp_bangclaw.vmap](https://github.com/Facepunch/sbox-issues/files/7127638/rp_bangclaw.zip)
