### ISSUE TITLE
[Feature] [Render] Set fps_max 120 or 240 by default (for a gamemode), add fps_max_menu command

### ISSUE THREAD

**Issue by GuardNexusGN** [Facepunch/sbox-issues#885]
When opened a gamemode - got 60 fps max. 
Used fps_max command to set a new limit. 

Will be great if sbox could render main menu with 60 fps and gamemode with 240 max (by default).
And nice to have fps_max_menu command, for main menu, esc overlay, etc.

**Comment by FlorianLeChat** [comment]
Totally agree, a bit like what CS:GO did.

**Comment by garrynewman** [comment]
I don't really understand why we have fps_max anyway - wouldn't you be better off limiting it with vsync?

**Comment by robotboy655** [comment]
fps_max is not tied to your display's refresh rate, you can limit your FPS to 120 or something on a 60hz screen, so the game feels responsive enough while not running it at unnecessary frame rates like 300, which in many cases is just a waste of energy.

As far as my understanding goes, VSync can introduce a not insignificant amount of input lag due to the way it works, as its designed to eliminate screen tearing effect, not to limit frame rate.

**Comment by garrynewman** [comment]
If you're at fps_max 120 on a 60hz screen, aren't you rendering frames that you never see 50% of the time? Wouldn't it be even more responsive to skip rendering that frame?

**Comment by ZenBre4ker** [comment]
You normally only take input every frame, therefor inbetween your monitor refresh cycles your game can do more stuff, meaning your intereaction feels more responsive.
Difficult to describe, but there are a lot of information only about this. Many pro Players play with framerates way above their refresh rate.
Also vsync is really a problem for input lag.

**Comment by robotboy655** [comment]
Rendering at 120fps on a 60hz monitor should still be more responsive due to 2 things:
* The display waits less time for the next frame (from 16ms to half that at most)
* Player input is processed more often

**Comment by GuardNexusGN** [comment]
FPS max needed for:
- 120, 144, 240 Hz monitors.
- FPS ralated gamemodes, when rendering and sending time to the output device can be decreased, 60 fps and 300 fps on 60 hz monitor make a lot of difference.

About output lag (best i can do in paint):
![image](https://user-images.githubusercontent.com/72446184/132511592-6fec4bd7-c28d-470e-ae96-0c7d96473ee8.png)

Why not Vsync:
- VSync has a good delay, adds a good lag, very noticeable in actions/fps games (can not play normally with 60 fps and vsync in cs:go).
- VSync adds jelly effect.
- Freesync/Adaptive sync.

**Comment by GamerXCZ** [comment]
> I don't really understand why we have fps_max anyway - wouldn't you be better off limiting it with vsync?

You never played movement games?

**Comment by MrBrax** [comment]
i must be the only one who always enables vsync, i feel no side effects of it other than no screen tearing

**Comment by Frozen-H2O** [comment]
> If you're at fps_max 120 on a 60hz screen, aren't you rendering frames that you never see 50% of the time? Wouldn't it be even more responsive to skip rendering that frame?

Here is a video that describes why higher fps feels smoother, despite not showing the frames on your monitor; however, the video is from 2015, so keep in mind certain technologies, like VSync, have improved a bit from when the video was made: https://www.youtube.com/watch?v=hjWSRTYV8e0&t=105s
