### ISSUE TITLE
Newly created gamemodes can't be loaded due to failure to create their fgd

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#887]
**Describe the bug**

A newly created game will be unable to create it's fgd if the file does not already exist, if an empty file exists the file is populated without error.

There's an incorrect check in `Sandbox.FgdWriter.WriteForAssembly` where it does the following:

```csharp
      bool flag = !EngineFileSystem.Root.FileExists(path1);
      if (flag)
        flag = contents1 != EngineFileSystem.Root.ReadAllText(path1);
      if (flag)
      {
        EngineFileSystem.Root.CreateDirectory("/addons/" + name + "/config");
        EngineFileSystem.Root.WriteAllText(path1, contents1);
      }
```

It is checking if the file does not exist and then trying to read from it, it should do the opposite.

**To Reproduce**

Clone sbox-minimal and run it.

**Screenshots**

![image](https://user-images.githubusercontent.com/1388267/132429192-65c25dfe-1da2-4437-bd47-5a60bb2467f6.png)

**Comment by garrynewman** [comment]
Thanks!
