### ISSUE TITLE
[ModelDoc] Allow modeldoc to use all processor threads.

### ISSUE THREAD

**Issue by realpack** [Facepunch/sbox-issues#888]
**What can't you do?**
I cannot specify a large fbx file in RenderMesh. ModelDoc freezes and does not work.
Only one processor thread is running at a time.

**How would you like it to work?**
Allow modeldoc to use more threads at this point.

**What have you tried?**
I have a large fbx file with a lot of animations.
It weighs 358 MB Animations make up most of its weight..

**Additional context**
Perhaps this can be solved somehow, but I have not found an answer.
I could not attach the file, because of a strange error.

**Comment by handsomematt** [comment]
fbx sdk is single threaded
