### ISSUE TITLE
Rotating PlatformEntity (ent_platform) crashes with 0 MoveDistance if LoopMovement is enabled

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#893]
**Describe the bug**
Creating a new PlatformEntity and setting its MoveDistance to 0, enabling LoopMovement and making it rotate (either with MoveType.Rotating or MoveType.RotatingContinuous) crashes the game. I would assume it's because of the division by zero in the DoMove() method of the PlatformEntity.

**To Reproduce**

```
RingEnt = new PlatformEntity(); // aka func_rotating
RingEnt.SetModel( "models/gmod4phun/stargate/gate_sg1/ring_sg1.vmdl" ); // or any other model of your choice
RingEnt.SetParent( this );
RingEnt.StopMoving();

RingEnt.MoveDirType = PlatformEntity.PlatformMoveType.RotatingContinious;
RingEnt.MoveDirIsLocal = true;
RingEnt.MoveDir = Rotation.Up.EulerAngles;

RingEnt.SpawnSettings = PlatformEntity.Flags.LoopMovement; // crashes if movedistance is 0 and loop is enabled

RingEnt.MoveDistance = 0;
RingEnt.StartMoving();
```

**Expected behavior**
Probably no movement at all, or just continuous rotation.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by Gmod4phun** [comment]
Thank you
