### ISSUE TITLE
No Particles.Create overload to attach to an entity without attachment

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#894]
There is no Particles.Create overload to attach a particle to an entity without an attachment.

You can do the following, but it will not tie the particle to the entity like it does when you call `Particles.Create( name, entity, attachment )` due to it not passing the entity pointer to `GameParticleManager.CreateParticleIndex`.

```csharp
var particle = Particles.Create( "particles/my_particle.vpcf" );
particle.SetEntity( 0, this );
```

To work around this you would need to keep a reference to each particle and destroy it OnDestroy.

```csharp
public partial class BouncyBallEntity : Prop, IUse
{
	Particles Particle;

	public override void Spawn()
	{
		Particle = Particles.Create( "particles/explosion_fireball.vpcf" );
		Particle.SetEntity( 0, this );
	}

	protected override void OnDestroy()
	{
		Particle.Destroy();
	}
}
```

It would be better if you only had to do:

```csharp
public partial class BouncyBallEntity : Prop, IUse
{
	public override void Spawn()
	{
		Particles.Create( "particles/explosion_fireball.vpcf", this );
	}
}
```

An overload matching that uses Particles.SetEntity would solve this.

```csharp
public static Particles Create(string name, Entity entity, bool follow = true )
```

**Comment by kurozael** [comment]
You should find this in the next Steam build. Please close the issue if it has been resolved 👍

**Comment by handsomematt** [comment]
Works well, cheers 🍾
