### ISSUE TITLE
Add get/set accessors for CurrentRotation in PlatformEntity (ent_platform)

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#895]
**What can't you do?**
I can't get the 'proper' current rotation of a PlatformEntity in degrees. Trying to get the angle from the entity's Rotation always  results in a value that's a modulo of 360, since they are quaternions. The internal `currentRotation`  float that keeps track of the total degrees is exactly what I need, but it's not accessible at the moment.

**How would you like it to work?**
Simple Get/Set accessors, like the other parameters have. (Main need is the Get accessor, but I could also benefit from a Set accessor so I can use modulo 360 to manually reset the rotation to the -360 to 360 degrees range when the rotation stops).

**Comment by robotboy655** [comment]
Made `get` public, I am a bit hesitant on making the `set` public, as it will cause weirdness if used while the platform is rotated.

if you think that `set` really really should be public, let it be known and I will look into it.

Also made some other useful properties public as well.

**Comment by Gmod4phun** [comment]
Thank you very much for this. Also, `set` being protected is good enough for my needs, since my entity is derived from PlatformEntity so I am able to set its value when needed.
