### ISSUE TITLE
Add UI element inspector.

### ISSUE THREAD

**Issue by sanny-io** [Facepunch/sbox-issues#897]
**What can't you do?**
Inspect UI elements for debugging purposes. It's quite useful seeing things like parents, children, dimensions, borders, margins, contents, and paddings.

**How would you like it to work?**
A button at the top of the console area where the other debug stuff is. Ideally, the system itself would just be a stripped down version of the elements tab in browser devtools.

**Comment by DevulTj** [comment]
Probably worth closing as this is in the game now
