### ISSUE TITLE
mat_fullbright and its variants show a black void with only viewmodel visible in regular executable, but not in sbox-dev

### ISSUE THREAD

**Issue by walllable** [Facepunch/sbox-issues#9]
Had this issue since I joined the dev preview on the 21st, only just now actually remembered to report it now that I have the issue tracker on my mind. Will try to be more vigilant.

When changing to mat_fullbright and its variants via the top bar in the console, only a black void shows, with the exception of the viewmodel, and a few others depending on the map. On testmap, the water shows, and on test/velocity, instead of some variants not showing the viewmodel, it shows a sort of ghosty version of it instead.

Just in case they're relevant, my specs are:
Ryzen 5 2600
GTX 1080ti
Windows 10 20H2

https://user-images.githubusercontent.com/10066958/115835721-97d32400-a3e4-11eb-983f-64d0221f64cc.mp4

https://user-images.githubusercontent.com/10066958/115835724-986bba80-a3e4-11eb-8a72-81fd6abae98b.mp4

https://user-images.githubusercontent.com/10066958/115835725-986bba80-a3e4-11eb-8234-e128a07c3ed7.mp4

EDIT: After a bit more investigation, I found that fullbright and its variants work when in sbox-dev, but not the regular executable.

**Comment by Plaonder** [comment]
Still broken, really annoying to have to launch the dev executable to see fullbright and its variants

**Comment by bakscratch** [comment]
Should of been closed ages ago.
