### ISSUE TITLE
Add TraceCircle

### ISSUE THREAD

**Issue by Matspyder51** [Facepunch/sbox-issues#900]
**What can't you do?**
With the current Traces setters, we can't trace in circle, we could set the radius to trace a sphere instead, but if we don't need the '3D' offset, it's adding some unnecessary calculations, we can't also trace around a position and ignoring what's inside, like an empty circle

**How would you like it to work?**
```cs
Trace.Ray(Position + Rotation.Up * 100, Position + Rotation.Down * 10)
			.Circle(10f)
			.Run();
```

Definition could be like
```cs
public Trace Circle( float radius, float offset = 0.0f );
```
With like a radius to `80f` and an offset to `60f`, the trace results will only contain data about what's inside the `20` remaining units of the exterior of the circle

**Additional context**

Because images are better than words, the trace will run only inside the red part, leaving the yellow part ignored
[
![image](https://user-images.githubusercontent.com/1222143/132936483-8c7ea92d-4b2c-4671-94ed-e3e02959f4b0.png)
](url)

**Comment by Rohansi** [comment]
Pretty sure it'd make more sense to trace a model/entity instead of having a builtin trace like this. A 2D circle outline isn't a cheap primitive to trace in 3D.

**Comment by aylaylay** [comment]
I have never in my life heard of a circle trace, this isn't a thing.

**Comment by ZenBre4ker** [comment]
Or you just run two cylinder traces and subtract everything you found in the smaller one from the larger one.

**Comment by Matspyder51** [comment]
Like ZenBre4ker said, since I need to get all entities who're inside the red part, ignoring what will be only inside the yellow part, and get back the entity who's the highest to have my end z position, so a sphere will not work for it, and the only other way I can find is running like a lot of line traces at specific circle positions, but even this, it will be inaccurate and probably heavy for performances
