### ISSUE TITLE
ent_path_platform horizontal player movement is broken.

### ISSUE THREAD

**Issue by Toasttf** [Facepunch/sbox-issues#904]
### **Describe the bug**

Player doesn't move with ent_path_platforms while they are moving in any horizontal direction. They just clip through it as it moves.

### **To Reproduce**
([Here is the map I used to test this issue](https://drive.google.com/file/d/1_RrjIf2x0QY26b7DaXhA-Dl4B1e74U1S/view?usp=sharing))

1. Create an ent_path_platform and set it to follow a path_generic that has horizontal movement.
2. Load the map in game and ride the platform around.
3. See error.

### **Expected behavior**

When the player is on an ent_path_platform, they should move with it.

### **Video of bug**

https://www.youtube.com/watch?v=HBxgnGlK7Ek

### **Additional context**

I've tried to bypass this issue using clips, parented models, and meshes. None have worked.

Problem exists on all types of path_generics (Linear, Spline, etc)

Vertical movement seems to work mostly without isssue.

Props and ragdolls don't have an issue with this.

This issue existed in HLA when in VR, but the workaround that fixed it (using SetAnchorParent) doesn't work here.

**Comment by robotboy655** [comment]
This is an issue with the current walk controller and applies to all moving platforms that use Keyframe physics.

**Comment by AfteraOfficiel** [comment]
Hi Matt, is not corrected, I still have the problem with the map given by the reporter and my personal map
