### ISSUE TITLE
Endless file-loop when opening multiple assets from Asset Browser to Notepad++

### ISSUE THREAD

**Issue by Mailer-Arch** [Facepunch/sbox-issues#907]
**Describe the bug**
Choosing the "Open X related files with Notepad++" context option after selecting multiple assets from the Asset Browser causes Notepad++ to attempt to open the same selected files on a loop over and over again. This seemingly never stops until the computer runs out of memory.

**To Reproduce**
1. Open s&box with the development tools and access the Asset browser.
2. Click on an asset to select it; then hold SHIFT and select another asset apart and therefore any assets listed in-between the two.
3. Right-click the multi-selection and choose "Open X related files with Notepad++" from the context menu.
4. Notepad++ should then attempt to open the selected files repeatedly and without any sign of stopping.

**/// To stop this unhinged process, use the Task Manager in conjunction to forcibly end the Notepad++ task before your computer runs out of memory! ///**

**Expected behavior**
The expected behavior would be for Notepad++ to open each of the asset files *once* and thereafter wait for user input. If you attempt to open the same file from explorer.exe twice, it would direct you to the file already open. Instead, there seems to be an exclusive behaviour between the Asset Browser and Notepad++ where the process of opening files does not stop as expected, and is instead capable of opening multiples of the same files in some way.

**Screenshots**
![EbWgfJJ8Gt](https://user-images.githubusercontent.com/31503866/132996660-3ab478e6-da0a-4848-8b88-e622ec86e2c7.png)

**Additional context**
This bug was observed using only a multi-selection of .vmdl files in the asset browser. It may be advised to try a multi-selection of the same asset type to replicate; otherwise .vmat should also be a compatible format to open in notepad++, among others. The relevant version of Notepad++ is v8.1.2 (64-bit).

**EDIT #1**
I was able to replicate the issue twice now. This time s&box also gave me an error message after I forcibly shut down the Notepad++ task. It is an issue that quickly spirals out of control so **please be careful when replicating**! s&box will try to re-open Notepad++ to continue the task, causing the same problem again after the following error window is closed. Closing s&box entirely seems to be mandatory to stop the same bug from happening again when Notepad++ is restarted.
![Jzq4e7s7UJ](https://user-images.githubusercontent.com/31503866/132996803-117dedd7-7327-4bdd-8445-f5b183f33627.png)

**Comment by robotboy655** [comment]
This should be fixed when the game next updates.
