### ISSUE TITLE
SCSS `:last-child` Pseudo-Class Only Works on Even-Numbered Children

### ISSUE THREAD

**Issue by AMastryukov** [Facepunch/sbox-issues#911]
**Describe the bug**
The `&:last-child` pseudo-class only works on even-numbered elements. That is, if I have 1, 3, 5, etc, element displayed, the `&:last-child` style is applied to it. If I have 2, 4, 6, etc, elements, then the style in `&:last-child` is not applied.

**To Reproduce**
Apply any noticeable style inside of `:last-child` pseudo-class and add new elements to see that the style is applied only when there is an odd number of elements.

**Expected behavior**
`:last-child` pseudo-class should always apply to the last child.

**Screenshots**
3 Elements:
![image](https://user-images.githubusercontent.com/12959805/133154366-5f12ba1c-a728-4f71-bae2-b392f4943983.png)
4 Elements:
![image](https://user-images.githubusercontent.com/12959805/133154413-0c1c8281-0e8d-4131-be91-191f14af9859.png)
5 Elements:
![image](https://user-images.githubusercontent.com/12959805/133154454-f3f328fb-27c9-426d-b1a0-31941e209e3d.png)
The style:
![image](https://user-images.githubusercontent.com/12959805/133154475-4076dbba-9b93-475c-a301-5a612c83cb2d.png)

**Comment by garrynewman** [comment]
Good catch - fixed
