### ISSUE TITLE
Does the RemoveClass method no longer work correctly ?

### ISSUE THREAD

**Issue by kevinhenschen** [Facepunch/sbox-issues#916]
**Describe the bug**
Before today, I had an action that remove a class from a button to make it visible, but recently (today) the class is no longer deleted and I can no longer have access to this button.

**To Reproduce**

_**SCSS PART (Simply Step / Code in screenshot) :**_ 
- Button = background-color: red;
- .BLUE = background-color: blue;

_**CS PART (Simply Step / Code in screenshot) :**_
- Create a Panel
- Add a Button with a class "BLUE" for example (var name : Button1)
- Add another button with event listener on click (var name : Button2)
- When you click button (Button2) start action : Button1.RemoveClass("BLUE")
- Button1 stay Blue Background

**Screenshots**
**_Screen 1 : Example Code_**
![image](https://user-images.githubusercontent.com/61383390/133326410-dc66ad66-9c80-49d3-a8a5-d2383a4293c8.png)

**_Screen 2 : A very simple diagram showing before the bug and after (+ Result of Code)_** 
![image](https://user-images.githubusercontent.com/61383390/133326997-a6de0cc3-fae3-4f17-b1d9-8aac58489e80.png)

**Additional context**
I have the impression that this bug appeared with the last version ... the reason? during the loading I could see "precache" which was not visible before, it may be the cause of the problem ... (to be confirmed)

**Comment by garrynewman** [comment]
The issue is caps sensitivity - I'll fix that
