### ISSUE TITLE
CustomSceneObjects are drawn after translucents

### ISSUE THREAD

**Issue by samzanemesis** [Facepunch/sbox-issues#920]
Right now CustomSceneObjects are drawn last in the rendering pipeline before postprocessing, causing solid geometry from it to be drawn over translucents

**To Reproduce**

Create a CustomSceneObject
Put something translucent over it

**Expected behavior**
CustomSceneObjects would not overdraw translucents

![image](https://user-images.githubusercontent.com/6563447/133383241-e494e553-3b64-4024-839a-b3b552b889bd.png)

**Comment by garrynewman** [comment]
Isn't this determined by the flags that are set?

**Comment by samzanemesis** [comment]
In case of this, CustomSceneObjects overrides any of these flags since it's drawn after most renderable on the scene system except view models
