### ISSUE TITLE
Support Generic NetworkComponents

### ISSUE THREAD

**Issue by tuvangezer** [Facepunch/sbox-issues#921]
**What can't you do?**
```C#
[Net] public Foo<Bar> fooInstance { get; set; }
// A class that my library/addon provides
public partial class Foo<T> : NetworkComponent where T: NetworkComponent
{
	public T a { get; set; }
}
// A class that contains information specific to the gamemode that use my library/addon
public partial class Bar : NetworkComponent  
{                                         

}
```

**How would you like it to work?**
I would like it to work with no problem as long as everything is a networkcomponent

**What have you tried?**
The code above

**Additional context**
I believe there will be many libraries/addons that will need to use generics. 
Examples:
- Database wrapper library that takes your gamemode specific data structure as a generic property.
- A weapon/vehicle etc library that gets your gamemode specific classes as a generic property.
- Gamemode frameworks

**Comment by handsomematt** [comment]
closing as #1448 is duplicate but more recent
