### ISSUE TITLE
Custom ent_door's and their triggers do not keep rotations on map compile

### ISSUE THREAD

**Issue by DeltaDesigns** [Facepunch/sbox-issues#923]
Door entities that use custom models (afaik only custom) don't keep their rotations in hammer when the map is compiled, reverting back to the models default rotation. For some reason though, any collision shape on the model that doesn't move does apply its the rotation.

To Reproduce:
1. Create a custom ent_door with model that uses animation only for its opening/closing
2. Place in hammer, rotate to something not its default.
3. Compile map, profit?

Expected behavior: Keep rotations

![Screenshot 2021-09-15 123740](https://user-images.githubusercontent.com/50308149/133474706-7bb15e7a-8bba-4840-8818-6a38d98b308b.png)
![Screenshot 2021-09-15 124049](https://user-images.githubusercontent.com/50308149/133474711-5b4a8bae-49fc-4c1b-842d-4dec5c0b823f.png)
![sbox_0033](https://user-images.githubusercontent.com/50308149/133474730-b27e4c0e-ddb8-483e-a96d-1a165a8bb11f.png)

Another bug is that these custom doors need a static frame collision or else the door will fly off the map on load

**Comment by PixelQubed** [comment]
This goes along with this issue I posted.

https://github.com/Facepunch/sbox-issues/issues/953

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
