### ISSUE TITLE
Search bar for local maps while creating a game no longer filters

### ISSUE THREAD

**Issue by KayaDLX** [Facepunch/sbox-issues#929]
**Describe the bug**

While looking for a specific local map and typing it into the search bar, I've noticed it no longer filters map based on what you write.

**To Reproduce**

1. Create a game
2. Look for local maps
3. Enter the name of the map in the search bar
4. Maps will not get filtered, UI will update but nothing will change

**Expected behavior**

Maps should get filtered based on what you wrote in the search bar.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by KayaDLX** [comment]
Can confirm working, thanks!
