### ISSUE TITLE
Typo in Wiki in Transform Tab 

### ISSUE THREAD

**Issue by Falkitop** [Facepunch/sbox-issues#939]
**Describe the bug**

**To Reproduce**
Go to the Wiki under the Transform Tab, under Methods
You see "Add a position this this transform and return the result. "

**Expected behavior**
Probably "Add a position to this transform and return the result. "

**Screenshots**
https://imgur.com/a/nDvldYV

**Comment by DoctorGurke** [comment]
it's a wiki. you can edit it.

**Comment by handsomematt** [comment]
> it's a wiki. you can edit it.

Its auto generated from code docs, so pointless to edit those pages if you even can.

**Comment by DoctorGurke** [comment]
oop-
