### ISSUE TITLE
Auto-generated assets emit wrong type for collections

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#941]
**Describe the bug**
When a collection property (such as `T[]`, `List<T>`, `IReadOnlyList<T>`, etc.) is added to an auto-generated asset class, the FGD generator emits `string` as its type instead of `array:T`.

**To Reproduce**

Add the following class to a project and build ingame:
```cs
[Library("string_list"), AutoGenerate]
public partial class StringList : Asset
{
    [Property]
    public string[] Items { get; set; }
}
```

The FGD generator produces the following (incorrect) output:
```fgd
@BaseClass = string_list : ""
[
    items(string) : "Items" :  : ""
]
```

**Expected behavior**
The expected output of the above example should be:
```fgd
@BaseClass = string_list : ""
[
    items(array:string) : "Items" :  : ""
]
```

**Comment by robotboy655** [comment]
I have made basic arrays work (`int[], string[]. float[]) with the next game update.

**Comment by robotboy655** [comment]
`List<T>`, `IList<T>` and `IReadOnlyList<T>` now work too.

**Comment by rndtrash** [comment]
> `List<T>`, `IList<T>` and `IReadOnlyList<T>` now work too.

Sadly, no, it still doesn't work :/
![image](https://user-images.githubusercontent.com/6745157/134567513-9ad4ac35-d82e-4a3d-a145-c720a43f898e.png)
![image](https://user-images.githubusercontent.com/6745157/134567550-7688c1d8-6687-47f6-8d4d-717a9f04343e.png)

**Comment by robotboy655** [comment]
It definitely works on my end:

![image](https://user-images.githubusercontent.com/3299036/134568156-087ff82a-0771-46b3-baae-6f618581d3d5.png)

Did you make sure you have ran the gamemode associated with the asset? Are you on the latest version of the game?

**Comment by rndtrash** [comment]
Huh, I've tried it again and now it works! It looks like .asset wasn't regenerated when I re-ran my gamemode. Excuse me for troubling you 😬

**Comment by TheBerkin** [comment]
Looks like it's working for primitive element types just fine now, but the issue still occurs when using a custom class / struct for the element type.

Example here: https://github.com/TheBerkin/sbox-c9t/blob/master/code/Assets/ScreenEffect.cs#L20

I hand-wrote an FGD to handle this:

```fgd
@struct = ScreenEffectModifier :
[
    Function(choices) : "Function" : 0 : "The type of curve function the modifier uses" =
    [
        0 : "Constant"
        1 : "Linear"
        2 : "Cosine"
        3 : "Wave"
        4 : "Triangle"
        5 : "Quadratic"
        6 : "Square"
        7 : "Random"
    ]
    Mix(choices) : "Mix" : 1 : "" =
    [
        0 : "Add"
        1 : "Multiply"
        2 : "Inverse Multiply"
        3 : "Subtract"
    ]
    Speed(float) : "Speed" : 1 : ""
    Offset(float) : "Offset" : 0 : ""
    Multiplier(float) : "Multiplier" : 1 : ""
]

@BaseClass = screenfx : ""
[
    Priority(integer) : "Priority" : 0 : ""
    Duration(float) : "Duration" : 1 : ""
    ColorStart(color255) : "Start Color" : "255 255 255" : ""
    ColorEnd(color255) : "End Color" : "255 255 255" : ""
    Brightness(float) : "Brightness" : 1 : ""
    Contrast(float) : "Contrast" : 1 : ""
    Saturation(float) : "Saturation" : 1 : ""
    Blend(choices) : "Color Blend" : 0 : "" =
    [
        0 : "Normal"
        1 : "Lighten"
        2 : "Multiply"
    ]
    Blur(float) : "Blur" : 0 : ""
    Modifiers(array:struct:ScreenEffectModifier) : "Modifiers"
]
```

The autogen falls back to `string` for the array type and doesn't seem to produce any `@struct` definition for `ScreenEffectModifier` either.

**Comment by robotboy655** [comment]
`struct:` syntax is not (yet?) supported, and I would consider this outside of the scope of this request.

**Comment by TheBerkin** [comment]
Fair enough - I can work around it for now. I'll submit a separate issue for it. Since everything else works I'll close this issue.
