### ISSUE TITLE
Input.VR.IsActive is set after the first simulate, should be set during initial spawn.

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#942]
**What it is**
Input.VR.IsActive is set after the first simulate from the client

**What it should be**
It should be set during the initial spawn

**Comment by garrynewman** [comment]
Where are you testing it?

**Comment by garrynewman** [comment]
Nevermind, should be fixed

![image](https://user-images.githubusercontent.com/928843/134148475-95304d18-3845-4586-b0be-932de9a96eda.png)
