### ISSUE TITLE
Git: Model hotloading

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/sbox-issues#945]
**What can't you do?**

Model loading only when needed.

**How would you like it to work?**

If addon's type is git, download only code.
Then, download models when it is being used.

**What have you tried?**

-

**Additional context**

Would be cool at least manually download vmdls and use them from `data/org/game`

**Comment by DevulTj** [comment]
What does this even mean? This would be super slow and freeze your game when loading expensive assets.

**Comment by SupinePandora43** [comment]
> What does this even mean? This would be super slow and freeze your game when loading expensive assets.

Yeah, but what if repo has a loo-o-o-o-ot models?

**Comment by Matspyder51** [comment]
You wait than everything is downloaded, Maybe you have a fast internet connection, but not every one can download few Mega in the middle of a game, downloading an asset of 50 mo can take le up until 30 seconds, so I don't want my game to freeze for 30 seconds every minute
