### ISSUE TITLE
Add .QC importing for ModelDoc

### ISSUE THREAD

**Issue by stepa2** [Facepunch/sbox-issues#946]
**What can't you do?**
Import Source 1 `.qc` file into ModelDoc automatically.

**How would you like it to work?**
Similar to _File/Import/Import Source MDL_

1. Add _Import Source QC_ button to _File/Import_ menu that opens `.qc` file selection menu
2. Parse .QC file contents and create model that (as much as possible) matches model defined by file

**What have you tried?**
It is possible to import `.smd` files and to reconstruct `.qc` in modeldoc manually.

**Additional context**

**Comment by aylaylay** [comment]
While this is technically possible, It's not something I want to add, we should be moving away from s1 formats. If this is something you really want, it's possible to make an external tool to convert it.
