### ISSUE TITLE
NetworkComponent incorrectly transmits null entities

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#947]
**Describe the bug**

When an Entity is networked to the client & is null it will send an ID of 0 which resolves to the world entity (id 0) on the client, mismatching prediction (null on server). Happened when the class dervived from NetworkComponent instead of Entity.

**To Reproduce**

1. Add an entity to your class that derives from NetworkComponent
2. Add [Net] attribute
3. Log in simulate to see mismatch between server (null) and client (WorldEntity)

**Screenshots**

`Log.Info( $"Hover: '{HoverEntity}' Selected: '{SelectedEntity}' Server: {Host.IsServer}" );`

```
Hover: '' Selected: '' Server: True
Hover: 'WorldEntity' Selected: 'WorldEntity' Server: False
```

**Comment by garrynewman** [comment]
This should be fixed now
