### ISSUE TITLE
Rider Support

### ISSUE THREAD

**Issue by Yomanz** [Facepunch/sbox-issues#949]
**What can't you do?**
Explore the stack trace from the console and breakpoints mainly.

**How would you like it to work?**
If there is an error in the console for s&box; you are given the option to click it and open up visual studio which I would assume brings you to the stack trace or places breakpoint at the very least but it would be nice to change this to use Rider in settings somewhere.

**What have you tried?**
Well, the only way to remedy this is to download Visual Studio and I would much rather use Rider.

**Additional context**
I'm sure it's being considered. The addition of this would make debugging so much easier.'

(This issue did already exist but it got closed for being stale: https://github.com/Facepunch/sbox-issues/issues/334)

**Comment by Rohansi** [comment]
Is there any documentation for how to achieve the same functionality with Rider? Right now it will open Visual Studio to the file and line number, using an existing instance if the s&box project is open, or open a new instance with the s&box project otherwise. It'd be pretty terrible if it behaved differently with Rider.

**Comment by Yomanz** [comment]
> Is there any documentation for how to achieve the same functionality with Rider? Right now it will open Visual Studio to the file and line number, using an existing instance if the s&box project is open, or open a new instance with the s&box project otherwise. It'd be pretty terrible if it behaved differently with Rider.

Found some docs on it: https://www.jetbrains.com/help/rider/Opening_Files_from_Command_Line.html

I just checked, if you try and open a file that exists within a solution, it will open the solution and the file to that specific line number.

**Comment by WilliamVenner** [comment]
It would be worth implementing support for specific IDEs (VS, VSCode, Rider etc) to jump to the line number based on the file association though.
