### ISSUE TITLE
[UseTemplate] adds '/code' to file paths, disallowing loading assets for locally hosted addons.

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#950]
**Describe the bug**
[UseTemplate] adds '/code' to directories which breaks when users download files from a hosted server

**To Reproduce**
1. Make a panel with a html file as a template.

code/MyPanel.cs
```cs
[UseTemplate]
public class MyPanel : Panel
{
    public MyPanel() {}
}
```
code/MyPanel.html
```html
<root></root>
```

2. Use [UseTemplate] and connect to a local server on a second client.
3. Observe failure to load said html file.
![sbox-dev_fEirqwYJ2b](https://user-images.githubusercontent.com/22372616/133926377-0f25cba0-897d-410e-aaa8-1447bd076546.png)

**Expected behavior**
It should load. It does not currently.

**Additional context**
This doesn't occur from addons when you're the host, or from GitHub/Facepunch's server as the FileSystem appears to mount this stuff at '/code' already. But this doesn't apply to joining someone's server and downloading files from their computer.

It also appears that SetTemplate also has the same behavior.

**Comment by handsomematt** [comment]
Some additional context from what we were talking about in Discord:

- SetTemplate("playerhud.html") works fine across all filesystems as it's not prepending /code

Testing the following across local / downloaded client:

```csharp
[ClientCmd("print_mounted_filesystem")]
public static void PrintFileSystem()
{
	var dirs = FileSystem.Mounted.FindFile( "/Code" );
	foreach( var dir in dirs )
	{
		Log.Info( dir );
	}
}
```

Local:
![image](https://user-images.githubusercontent.com/1388267/133926765-715d2087-551d-43c1-926e-d95604f1f366.png)

Downloaded:
![image](https://user-images.githubusercontent.com/1388267/133926797-c08e0332-b7a1-467f-b22c-c673ee6d2d62.png)

Downloaded again but printing root "/" files

![image](https://user-images.githubusercontent.com/1388267/133926817-cdb20934-563a-4b30-b468-b8c6942ee58e.png)

So html files and shite aren't landing in /code on downloaded filesystem, but will still download to the root directory.

**Comment by garrynewman** [comment]
Wow how has this every worked

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/136288564-88c10840-c8c6-44dd-9809-f11783c47be7.png)

Was testing a game earlier and it was still trying to load with `/code` prefix, UseTemplate generator is checking for paths starting with "code/" missing the / prefix.
