### ISSUE TITLE
Prop_Dynamic Animation Collision Bug

### ISSUE THREAD

**Issue by PixelQubed** [Facepunch/sbox-issues#953]
**Describe the bug**
So, when creating a prop_dynamic in model doc and assigning multiple physics hulls to separate animated bones, the model disappears in-game. It works with one Phys hull attached to a bone.

**To Reproduce**
You can make a prop in modeldoc with two or more bones and parent collision hulls to said bones and add an animation, and then it should just happen.

**Expected behaviour**
It shouldn't just float up into the sky. It should just play the animation and have the correct physics as set up in modeldoc.

**Screenshots**

https://cdn.discordapp.com/attachments/837029442001829958/889540268171337738/CtbY65YMo6.mp4

**Comment by DeltaDesigns** [comment]
Can confirm this as well

**Comment by PixelQubed** [comment]
> 
> 
> Can confirm this as well

Yeah well I think this is an important issue that needs fixing to enable the creation of more complex maps.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
