### ISSUE TITLE
Run Event on Panel elements

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#96]
**What can't you do?**

Attempting to use Event in UI panels.  In Player's OnChildAdded method I'm running an event if the child is an item entity, I'd like my inventory to hook into this event to force a re-render.

**How would you like it to work?**

[Event(name)] works on Panel

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by cr4yz** [comment]
Appears to be working, thanks!
