### ISSUE TITLE
Client.Name always empty string clientside

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#961]
Client.Name is always an empty string clientside but returns correct serverside - started today so probably the EntityName -> Name commit.

**Comment by handsomematt** [comment]
If the client's pawn goes out and back in of your PVS, Client.Name is then set correctly clientside.

**Comment by handsomematt** [comment]
Shit fix I'm doing for now:

```csharp
private async static void FixName( Client cl )
{
    var name = cl.Name;
    var ent = Entity.FindByIndex( cl.NetworkIdent );
    ent.Name = "twat";
    await GameTask.Delay(1);
    ent.Name = name;
}

public override void ClientJoined( Client cl )
{
    FixName( cl );
}
```

**Comment by garrynewman** [comment]
Should be fixed on next build
