### ISSUE TITLE
Weld Tool doesn't work properly

### ISSUE THREAD

**Issue by TopYozhik** [Facepunch/sbox-issues#964]
When a player tries to resize props, e.g. to make is 25% of it's size, and then tries to interact with it, he faces collision bugs.

**To Reproduce**
1. Go to Q menu
2. Click on Resizer
3. Spawn maya_testcube_100.vmdl (e.g.)
4. Resize it to minimal scale
5. Use Wheel Tool on it
6. Watch how Wheels are flying in the air
7. Face different strange collision bugs with this cube

**Expected behavior**
Resize tool scales the collision of an object properly ->
Wheel Tool gets the proper collision and doesn't cause bugs

**Screenshots**
![20210922175600_1](https://user-images.githubusercontent.com/44850575/134374646-9def0cac-f7e5-45b6-b9b1-7e8b31db2d12.jpg)

![20210922175640_1](https://user-images.githubusercontent.com/44850575/134374694-14368b2f-1964-4158-bb2b-828a735c7474.jpg)

**Comment by Gmod4phun** [comment]
Can't confirm. Works fine here.
![image](https://user-images.githubusercontent.com/5991682/134377606-64ebe0da-e55b-4ca1-8a25-71646cdb9b9f.png)

Probably needs more context, try a clean install.

**Comment by TopYozhik** [comment]
> Can't confirm. Works fine here.
> ![image](https://user-images.githubusercontent.com/5991682/134377606-64ebe0da-e55b-4ca1-8a25-71646cdb9b9f.png)
> 
> Probably needs more context, try a clean install.

maybe it's caused by Weld Tool. I welded both two resized blocks to third prop, and then tried to unfreeze it all. Try this method.
It's not a one-time bug, I can cause it every time

**Comment by Gmod4phun** [comment]
Yeah, it seems to be an issue with the Weld, not the Resizer. It is the resized props that seem to have their serverside physics glitched when used with weld.

https://user-images.githubusercontent.com/5991682/134383253-6ea83d5c-36ce-482d-a3a9-1977efe833a9.mp4

You should probably rename the issue.

**Comment by aylaylay** [comment]
I remember this working fine so I'm not sure what broke it, I'll look into it.
