### ISSUE TITLE
drone entity blades problem

### ISSUE THREAD

**Issue by degradka** [Facepunch/sbox-issues#968]
Whem you spawn the drone, blades are crazy

**To Reproduce**

1. Join SandBox gamemode
2. Open spawnmenu
3. Go to entities tab
4. Spawn drone

**Expected behavior**
I think blades should stay at drone

**Screenshots**
https://prnt.sc/1tagupv

**Comment by aylaylay** [comment]
Fixed, this was due to some import changes in modeldoc
