### ISSUE TITLE
FGD Parse error on gamemode without any entities for fgd generation to apply to

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#969]
**Describe the bug**

The auto generated FGD of a gamemode without any entities etc will cause an FGD Parse error.

**To Reproduce**

1. Make a basic test gamemode without any entities that would benefit from fgd generation
2. reload fgds via an editor tool or otherwise have the game load it
3. notice FGD Parse error in console

**Expected behavior**

Auto generated FGDs to always be valid

**Screenshots**

![sbox-dev_fRWuWL69lN](https://user-images.githubusercontent.com/12602100/134475738-df8719ca-cab3-479b-b75e-cfb8ed73e819.png)

Default generated fgd:
![Code_uezMmdVVRk](https://user-images.githubusercontent.com/12602100/134476128-11ee87a5-dcfd-4322-a575-310cf4d8fe62.png)

**Comment by Adesii** [comment]
the Error isn't from the Gamemode not including any entities. The issue is the - in the name it should fixup the name to be test_gamemode instead of test-gamemode.
seems like - aren't allowed in a name.

same thing happend to our sky-fortress gamemode.

**Comment by DoctorGurke** [comment]
Didn't even occur to me to test the name, cause dashes always worked in addon names haha

**Comment by robotboy655** [comment]
Should be solved, it will replace bad symbols with underscores now.
