### ISSUE TITLE
Folders which are in the addons folder are ignored and still downloaded

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#97]
**Describe the bug**
When creating a new server with content located in the addons folder, you'll be prompted to download those assets instead of just using what's already in the addons folder.

**To Reproduce**
Place a sound file or material in "sbox/addons/MyAddon/sound"

**Expected behavior**
The file shouldn't download, it should just use whatever is already in the addon folder

**Comment by garrynewman** [comment]
This is a temporary thing to be sure that everything is working, we'll shortcut it eventually

**Comment by ogniK5377** [comment]
:+1: I'll close the issue since it's intentional for the time being
