### ISSUE TITLE
Can't reliably set Entity Transform in Event.Frame

### ISSUE THREAD

**Issue by Geeknerd1337** [Facepunch/sbox-issues#970]
**Describe the bug**
Our gamemode  uses a modified version of Laylad's vehicle controller, which animates the transforms of its child wheels in an Event.Frame event. 

![image](https://user-images.githubusercontent.com/15205856/134519407-302b6bf0-1dea-4752-bb4b-c28dec6b17bf.png)

Seemingly as a result from this commit:
![image](https://user-images.githubusercontent.com/15205856/134519724-54b7d553-4941-4dd4-9f73-5406bb8847a6.png)

The transforms on the cars wheels on lights seem to update sporadically or not at all. I've confirmed the values driving these rotations are not choppy or at a stand still, this seems to be an issue with updating transforms in Event.Frame
https://user-images.githubusercontent.com/15205856/134519829-9fd4d631-6163-4ccc-8751-deb00ca5618a.mp4

I was able to confirm these suspicions with Laylad on discord.
![image](https://user-images.githubusercontent.com/15205856/134520189-e33ca6e4-dc55-41c6-90c7-85dd64579b05.png)

**To Reproduce**

1. Open S&Box
2. Load up the sandbox gamemode on any map
3. Spawn a car entity and enter it
4. Observe the transforms on the wheels not being updated if the car is moving.

**Expected behavior**
The wheels should move smoothly according to the values set in OnFrame.

**Screenshots**

**Comment by aylaylay** [comment]
Looks like the event was moved to after a bunch of transform work is done which was needed elsewhere but fucks up when you want to change child transforms etc.

I don't know the fix without undoing the reason why it was moved in the first place, maybe needs two events to make both situations work.

@garrynewman

**Comment by Geeknerd1337** [comment]
```csharp
public override CameraSetup BuildCamera(CameraSetup camSetup) {
			Event.Run("frame.old");
			return base.BuildCamera(camSetup);
			
		}
```
For now the above override in your game.cs gives you an event that you can reliably use to set child transforms.

**Comment by aylaylay** [comment]
Yeah that works for now, it's roughly where the event was called before, just watch out using anything in CurrentView, they're set after BuildCamera

**Comment by handsomematt** [comment]
@Geeknerd1337 this is probably fixed now as frame event got moved along with some additions preframe and prerender.

**Comment by aylaylay** [comment]
Fixed a while back
