### ISSUE TITLE
Make s&box macOS compatible!

### ISSUE THREAD

**Issue by StupidRepo** [Facepunch/sbox-issues#972]
Please! Garry's Mod is macOS compatible so why can s&box not?

**Comment by FlorianLeChat** [comment]
Garry's Mod works on MacOS mostly with black magic and the 64 bit branch, not to mention that this version has so many bugs (and so much time needed to get proper support) for such a small minority of players. It's almost the same debate as Linux support to make the 1% of Steam users happy.
