### ISSUE TITLE
Unrecognized Content Path after saving texture file

### ISSUE THREAD

**Issue by SherrifDoggo** [Facepunch/sbox-issues#974]
I'm porting a couple of my own textures from Source 1 to Source 2 right now but when i tried to save the file in the addons folder, it just yelled at me in yellow text and did some more strange things.

![image](https://user-images.githubusercontent.com/90926584/134601219-34fda83f-e426-48f5-8afb-a82004e35797.png)
Here's the error in all it's glory

![image](https://user-images.githubusercontent.com/90926584/134601273-e1616467-7919-4604-b983-dfe899a5f926.png)
Here's what it tells me if i try to save it again.

![image](https://user-images.githubusercontent.com/90926584/134601338-989ed45b-eb56-4bf0-9edd-5f8ea407c9d9.png)
And here's the path of the texture file, which i think is supposed to be valid, but something's fouled up.

I personally think that the issue might be that i have the game on my D: drive instead of my C: drive (C: drive is a 500gb ssd that's 50% Gmod addons and 50% Half Life: Alyx), But i don't want to unistall the whole game, allocate space for it on the SSD, wait a couple hours when that wasn't the issue

![image](https://user-images.githubusercontent.com/90926584/134601775-dce69351-afec-4314-9158-3c7251bec5aa.png)
(also this is my internet, so please dont make me reinstall the game on my SSD... please.)

**Comment by DoctorGurke** [comment]
Did you restart your game after you added the new addon folder

**Comment by SherrifDoggo** [comment]
Nope,
it worked.

Sorry for my lack of basic troubleshooting knowledge.
