### ISSUE TITLE
Hot reloading throws exception on first hotreload

### ISSUE THREAD

**Issue by deadmonstor** [Facepunch/sbox-issues#976]
**Describe the bug**
Hot loading throws this exception, seems to only happen on first hot reload from my experience 

**To Reproduce**

1. Load up sandbox
2. Hot reload Inventory.cs
3. See error

**Expected behavior**
No error

**Screenshots**
https://i.imgur.com/18QYHIU.png
https://i.imgur.com/fmGWQpA.png

**Additional context**
It seems I am also getting this when loading it, seems like it is to do with the error I am getting after. https://i.imgur.com/92NXEoq.png

**Comment by garrynewman** [comment]
This should also be fixed in the next build
