### ISSUE TITLE
WalkController parameters aren't networked

### ISSUE THREAD

**Issue by N-cognito** [Facepunch/sbox-issues#977]
**Describe the bug**
When using WalkController, player speeds equal to or above 345.0f cause visual stuttering of the player models. This seems to only appear if you are the one above said speed, the speed of other pawns is irrelevant.

**To Reproduce**
1. Set any mode speed to 344.99f or lower to view without stuttering
2. Set any mode speed to 345f or high to view WITH stuttering

**Expected behavior**
Playermodel should ideally move smoothly regardless of speed, unless at an extreme velocity where it wouldn't matter

**Screenshots**
https://streamable.com/0q7fpm

**Additional context**

On thing I've noted is that about 344.99f is the last value before the bug starts making an appearance, with 349.999 causing the bug on occasion, and 346.0f causing the bug to be persistent. It's not like I'm going too fast and the model is lagging behind, as extreme speeds don't seem to worsen the bug.

Another is that when the playermodel isn't stuttering, the player's hull is, and vice-versa

**Comment by handsomematt** [comment]
Can you show how you're setting the speed? It sounds like prediction problems from not setting it both serverside and clientside.

**Comment by N-cognito** [comment]
![Screenshot_186](https://user-images.githubusercontent.com/8404018/134754683-ed3bcef7-6ae2-4a3c-b61c-ee3c43416651.png)

This is a simple override version when using something like "partial class CustomPlayer : Player", but I was also running into this issue with changing the base values in base Player.cs

How would I go about making sure it's set both server and clientside if that is the issue?

**Comment by handsomematt** [comment]
Respawn is serverside only.

If you want to adjust the speed you can set it to match via rpc or some other method clientside or create your own inherited controller adjusting the values to what you want.

The stuttering is just a prediction error from WalkController.SprintSpeed being 350.0 on the server but remaining 320.0 on the client.
