### ISSUE TITLE
Net property does not import namespaces and codegen throws

### ISSUE THREAD

**Issue by deadmonstor** [Facepunch/sbox-issues#978]
**Describe the bug**
Net property does not import namespaces and codegen throws

**To Reproduce**

1. Create an entity in a namespace
2. Network that in another namespace
3. See codegen error

**Expected behavior**
Codegen doesn't fail and the entity should be networked/found

**Screenshots**
https://i.imgur.com/Bh3hSV9.png

**Additional context**

Made a test repo just in case https://github.com/deadmonstor/sbox-minimal / https://github.com/deadmonstor/sbox-minimal/commit/4de37494e26e122c100a3791df6c5bb3a2e83259

**Comment by garrynewman** [comment]
Thanks, should be fixed in next build

**Comment by deadmonstor** [comment]
Awesome, work perfectly
