### ISSUE TITLE
Clip-path for CSS

### ISSUE THREAD

**Issue by KingDavidW** [Facepunch/sbox-issues#98]
**What can't you do?**
Use clip-path properties in CSS

**How would you like it to work?**
Exactly as it would in CSS normally

**What have you tried?**
N/A

**Additional context**
You can look at this link for reference: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

This is pretty much a must have in UI, and if post processing effects / filters are going to also be done through CSS, it'll give us a lot of control.

Important to note that the capabilities could also cut HOLES into things, see this link for an example of that: https://css-tricks.com/cutting-inner-part-element-using-clip-path/

**Comment by Tripperful** [comment]
> **How would you like it to work?**
> Exactly as it would in CSS normally

Currently it's not even supported in web browsers so well, it's a rather complicated property which can be worked around so I'd say it's of low priority.

![image](https://user-images.githubusercontent.com/28317791/117153172-646c9e00-adc3-11eb-82a5-ffb61e6b6ca7.png)
