### ISSUE TITLE
Network Component [Net] properties are not being replicated to joining clients

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#983]
**Describe the bug**
When you change the value of a property that is networked on a network component, it wont be changed on clients that joined the server after the value had been changed

**To Reproduce**

1. Create a [Net] property
2. Change the value of the server
3. Second client will join
4. Second client wont have the same value as the server value

**Expected behavior**
Clients should get the values from the server when they join the server

**Additional Context**
When you change the inherited type to Entity, it'll work as expected

**Comment by garrynewman** [comment]
Is this still an issue?

**Comment by Jake-NSW** [comment]
Yes

**Comment by garrynewman** [comment]
What about now?

**Comment by Jake-NSW** [comment]
Nope still seems to be an issue, 
![image](https://user-images.githubusercontent.com/55055481/135747480-fcfb1bc1-409d-46b3-ba02-f732a6feb015.png)
![image](https://user-images.githubusercontent.com/55055481/135747458-82602c72-c128-4b4e-b20a-8693de557777.png)

Client joins after the value had been changed on the server and still doesn't seem to update

**Comment by garrynewman** [comment]
Fixed!
