### ISSUE TITLE
Can't Enter and Drive Vehicles

### ISSUE THREAD

**Issue by kevinhenschen** [Facepunch/sbox-issues#984]
**Describe the bug**

Before this bug it was possible to enter vehicles, now this is no longer possible

**To Reproduce**

1. Spawn Vehicle
2. Press "+iv_use" bind to enter
3. Nothing Append

**Expected behavior**

It seems to behave like this because the player has a rather strange value in Player.Vehicle which prevents the condition which checks before entering whether the player is in a vehicle or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/61383390/134774204-953461cf-16ea-4b6d-a50e-a3e112c465ae.png)

**Comment by aylaylay** [comment]
For clarity I fixed this in the sandbox repo by initializing vehicle to null, I assume this is a networking bug that will be fixed soon though.

**Comment by garrynewman** [comment]
It feel like with regressions like this we should keep stuff broken so that we have a decent repro

**Comment by aylaylay** [comment]
Yep thought that too after I fixed it.
