### ISSUE TITLE
[Net] properties aren't being set if assigned during object initialization

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#989]
**Describe the bug**
Looks like net stuff doesn't get set if you assign them with an Object initializer

```csharp
Controller = new SeatController()
{
    Seat = this
};
```
**Doesn't work**

```csharp
Controller = new SeatController();
Controller.Seat = this;
```
**Does work**

I take it it's something to do with the way entities are spawned, object initializer values get set before Spawn whereas assignment after the constructor is probably after Spawn.

**Comment by garrynewman** [comment]
This should be fixed now
