### ISSUE TITLE
Whitelist Attributes

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#99]
`System.Private.CoreLib/System.Attribute`
`System.Private.CoreLib/System.AttributeUsageAttribute`

Can't create custom attributes in addons without them being whitelisted.

Also there isn't a whitelist issue template so I'm marking this as feature for now.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Jake-Rich** [comment]
My bad, I think it needs to be `System.Private.CoreLib/System.Attribute*` since the constructor isn't covered without the wildcard at the end.

**Comment by garrynewman** [comment]
Done!

This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by Jake-Rich** [comment]
Fixed 👍
