### ISSUE TITLE
[VR] Option to use a separate non-vr camera for desktop display

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#990]
**What can't you do?**
In VR, the desktop display is forced to show one of the VR eyes. We need to be able to unlink this from the headset and use a regular non-vr camera, while still having the player in VR.

**How would you like it to work?**
Probably an enum for desktop render camera. Could have both VR eyes and the default non-vr system.

**What have you tried?**
Currently, we have to use a separate game instance to do this.

**Additional context**
A lot of VR games give you the option to change what's shown on your 2d desktop view. This is very useful for streamers & videos. It's common to show a third person perspective during VR livestreams.

**Comment by xezno** [comment]
This is possible now:
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/9db00d61-51f8-40bc-ae21-1450306e9e02)
