### ISSUE TITLE
[VR] Ability to detect headset/controller types

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#994]
**What can't you do?**
We can't detect what headset, controllers, & trackers the client is using.

**How would you like it to work?**
Something that returns the device name as a string in Input.VR
`if(Input.VR.LeftHand.DeviceName == "oculus_quest2")`
`if(Input.VR.TrackedObjects[1].DeviceName  == "tundra")`

**What have you tried?**
![image](https://user-images.githubusercontent.com/39461072/134831356-44668ab0-572e-420a-a492-c6c8ace4ed49.png)
We have this, but it's awful. There's only 3 options and I don't even know if it's checking the headset or a controller.
With SteamVR, you can combine whatever hardware you have. You can use a Quest 2 headset with one Index controller and one prototype Vive wand if you wanted.

**Additional context**
Use cases:
- Displaying ghost controllers when you try to push your hands through walls.
- Using floating headset as avatar in multiplayer
- Displaying tracker models during FBT calibration

**Comment by garrynewman** [comment]
I don't totally love the idea of getting this granular. If you're using an index you're probably using index controllers.. if not you're going to have a weird experience. If you're using an quest you're probably using quest controllers.

Particularly string names. We should be making things easier for people. Having them hardcore handle a list of controller types in their code isn't the way to do that, it's pain.

**Comment by gvarados1** [comment]
No, it's common to mix Vive & Index hardware. I just gave an extreme example.

- A lot of people with old Vives have upgrade only their controllers to knuckles
- Wireless Vive + knuckles
- Professional gamers use one Vive Wand and one Knuckle for increased gun stability

![image](https://user-images.githubusercontent.com/39461072/134916733-93288c95-26c1-4ed3-9cfd-ec96b383d20b.png)

If you can think of a better solution, add that in addition to string names.

**Comment by jeppevinkel** [comment]
I agree with gvarados here. You can not always assume a headset/controller type pair. Especially with the SteamVR ecosystem that's specifically designed to be modular and cross-compatible between all Lighthouse based devices.

**Comment by walllable** [comment]
I think there are some use cases for knowing what controllers/headset is being used. @ShadowBrian's game [Climbey](https://store.steampowered.com/app/520010/Climbey/) displays a pin on the user's backpack strap depending on which headset the player is using (Or headset and controllers, in the case of using a Vive with Index controllers.) The controls are also different on different controllers due to the different inputs available, for example, on Oculus controllers the Y and B buttons (or X and A, can't remember) handle the quick turning since the joysticks are used to change the pose the hands are in, while on Index controllers the right joystick is used t turn since it has finger tracking, and on Vive wands pressing the right touchpad to the right or left handles turning since moving your thumb on the trackpad handles the hand poses.

**Comment by gvarados1** [comment]
> Your use cases seem entirely solved by #1001 automatically?

#1001 is just for the models in-game (not a steamvr overlay)
This issue is for actually detecting which hardware the player is using

**Comment by handsomematt** [comment]
Right but your usecases are mainly to display these models - with #1001 the correct models for the users devices can be grabbed from OpenVR and you don't have to worry about picking them manually.

**Comment by DrakeFruit** [comment]
the use case isn't just displaying the controllers though, changing binding per controller is common.

**Comment by xezno** [comment]
Can you give me an example of where you'd need to do this in s&box? As far as I know our VR input stuff is set up to support the lowest common denominator and should be compatible with 99% of controllers

**Comment by gvarados1** [comment]
I included a couple examples in the original issue:

> - Displaying ghost controllers when you try to push your hands through walls.
> - Using floating headset as avatar in multiplayer
> - Displaying tracker models during FBT calibration

Most of these are just cosmetic though and would be solved with #1001 

The only case I can think of right now that wouldn't be solved with #1001 would be having custom cosmetics based on which hardware device you have.

**Comment by xezno** [comment]
What sort of custom cosmetics are you thinking of that need you to have granular access like this, surely you'd just want cosmetics for index users, vive users, oculus users? You shouldn't need super specific device types for that

**Comment by gvarados1** [comment]
As mentioned above, users can use any combination of steamvr devices with each other. There are a lot of vr headsets which are just the headset, without any controllers. For example, someone who is really into shooter games might use the Bigscreen Beyond headset with one Index controller and one Vive controller.

**Comment by xezno** [comment]
> As mentioned above, users can use any combination of steamvr devices with each other. There are a lot of vr headsets which are just the headset, without any controllers.

Right, but what we're saying is, there's not much of a use case for having this information, and there likely aren't many users mixing and matching hardware (though I do not have any concrete stats for this)

> Someone could use the Quest Pro headset with one Index controller and one Vive controller. Are they an Index user, vive user, or oculus user?

The way we have it hooked up right now is that the controller types are based on their primary controller, so based on what you've said before it's most likely that IsVive would be the case here.

If you can think of a solid, concrete use case for having granular headset/controller detection (and something that isn't already covered by a separate issue, e.g. #1001) then I'll think of a nice way to add it, but right now I don't see much of an advantage to having this info.

**Comment by gvarados1** [comment]
I think all the unique uses are cosmetic and wouldn't get much use (ex. having custom ghost controller tutorial animations)
IIRC my use case when I originally made this issue was for setting ghost models, which would be covered by the other issue.

I think the "IsKnuckles, IsRift, IsVive" is very confusing though and should probably get removed. It's missing a lot of headsets, Maybe all the Quest headsets are considered IsRift, but what about other headsets like pico?

**Comment by xezno** [comment]
So I did some thinking on this - would it be more helpful to have these on each controller, right now they only appear to whatever the primary controller is, which I think is what you're trying to say is useless.

Would moving these to VrHand & making them IsVive, IsTouch, IsKnuckles, IsWMR be more useful?

**Comment by gvarados1** [comment]
Having it on the actual device makes a lot more sense. Having a bunch of bools doesn't seem right to me though. It seems like spam and it would always be an incomplete list as more devices come out.

I want to be able to setup in-game models of vr trackers to make it easy to align them irl. There are multiple vr tracker devices (Vive2.0, Vive3.0, Tundra) and they all look different from each other. I want to be able to figure out which devices the users have and show them the actual model in-game. This is currently not possible, we have to use a generic model for all VR trackers in-game. This makes it hard to accurately align them with their real world physical trackers.

**Comment by xezno** [comment]
That's covered by #1001

**Comment by MuffinTastic** [comment]
Having a string or enum for the controller type on each VrHand instance makes more sense to me than having a bunch of bools. It's not like something can be a Touch controller and an Index controller/Knuckles at the same time.

**Comment by xezno** [comment]
So what I've done for this for now is moved all the IsVive/IsKnuckles/etc. stuff over to the controller class and added IsWMR too, because I think there are going to be a handful of setups that use mixed controllers.

We do also now detect the headset manufacturer internally - I can make this more nuanced and make it public if there's a use case, but I can't think of any good use for it right now. If anyone does have a use case then please let me know - but I think most are covered by #1001
