### ISSUE TITLE
Support for Viewmodel Camera Setup ZNear & ZFar

### ISSUE THREAD

**Issue by Jake-NSW** [Facepunch/sbox-issues#995]
**What can't you do?**
Viewmodel Camera have a different ZNear and ZFar

**How would you like it to work?**
Make it so you can change the viewmodel camera's ZNear and ZFar

**What have you tried?**
Changing the base cameras ZNear and ZFar changes the Viewmodel one to, but I dont want to be changing the ZNear on the camera itself since it causes vertex flickering weirdness

**Comment by kurozael** [comment]
Hi @Jake-NSW 

You should find this capability available in the next Steam build which usually takes 5-10 minutes.
