### ISSUE TITLE
Scissoring broken on various popups

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#996]
**Describe the bug**

Various popups - namely the invite friends & color editor - have the first half of their contents missing

**To Reproduce**

1. Go to the main menu
2. Click the invite button

Alternatively,

1. Go to the main menu
2. Click the tests button
3. Go into the text shadow tests tab
4. Click on the "backgroundcolor" color editor

**Expected behavior**

The popups should be fully visible

**Screenshots**

Invites:
![image](https://user-images.githubusercontent.com/12881812/134941696-dabaaec4-04bb-47e6-9b7e-225ecea94bd9.png)

Color editor:
![image](https://user-images.githubusercontent.com/12881812/134941722-e1b35526-9ff7-4cc2-907b-19426c6b8cfe.png)

**Additional context**

Someone else in the Discord was having the same problem, so I don't think this is a localized issue.

**Comment by garrynewman** [comment]
Should be fixed next build
