### ISSUE TITLE
Hammer; Path_particle_rope does not created the particle

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-issues#998]
path_particle_rope does not show when loaded in game, but show correctly inside hammer.

I have tried the other rope particles but they don't seem to work as well so It must be the entitiy side.

It should show what I see inside hammer ingame.

1.Click the path tool and select "path_particle_rope"
2.Draw 2 points
3.Build map.

![image](https://user-images.githubusercontent.com/8184184/134978026-ef0f2081-042a-4d32-b5a7-e2499d026ba7.png)

![image](https://user-images.githubusercontent.com/8184184/134978126-c429c849-3648-430f-8df5-f77cd4c955a1.png)

**Comment by robotboy655** [comment]
Sorry about this, should be fixed when the game next updates on Steam. Maps will need recompiling.
