### ISSUE TITLE
Allow changing level programmatically

### ISSUE THREAD

**Issue by SleepyMode** [Facepunch/sbox-issues#999]
**What can't you do?**
Change the current map through code.

**How would you like it to work?**
Preferably by assigning a value to the `Global.MapName` variable (which currently cannot be changed through code).
For example:
```cs
// This should set the level to facepunch.construct
Global.MapName = "facepunch.construct";
```

This should probably also still work if the map name being assigned is the current map, same way as changelevel does, which would allow for a sort of soft-restart which is sometimes needed (particularly for development).

**What have you tried?**
Using `changelevel` with ConsoleSystem but that was disabled a while ago and is honestly a pretty crappy way to do it.

**Additional context**
N/a

**Comment by NullEnt1ty** [comment]
Kinda related: I would like to have a way to change the gamemode too. You can do this with the `gamemode` console command, but yeah... it's blocked. I can see this being helpful for map/gamemode votes and minigame servers.

**Comment by garrynewman** [comment]
@kurozael I'm thinking `Global.ChangeLevel( "mapname" )`

**Comment by Jake-NSW** [comment]
I think it'd be pretty cool for game modes to have their own map change loading screen is well
